Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2018-08, with the labels that each got.

#27740 [@types/gl-matrix] add static method vec2#angle()
  types/gl-matrix/gl-matrix-tests.ts
  types/gl-matrix/index.d.ts
Labels: Merge:Express, Owner Approved

#27760 new version of Knuddels-App API
  types/knuddels-userapps-api/index.d.ts
  types/knuddels-userapps-api/knuddels-userapps-api-tests.ts
Labels: Author is Owner, Merge:Express

#27761 fix(yar): add missing session id property
  types/yar/index.d.ts
  types/yar/yar-tests.ts
Labels: Author is Owner, Merge:Express

#27756 ArangoDB: Add proper ArangoSearchView API
  types/arangodb/arangodb-tests.ts
  types/arangodb/index.d.ts
Labels: Author is Owner, Merge:Express

#27752 Update flatten method signature
  types/json2csv/JSON2CSVBase.d.ts
  types/json2csv/JSON2CSVTransform.d.ts
  types/json2csv/index.d.ts
  types/json2csv/json2csv-tests.ts
Labels: Author is Owner, Merge:Express

#27733 The function withInfo in @storybook/addon-info should accept 0 or 1 argument
  types/storybook__addon-info/index.d.ts
  types/storybook__addon-info/storybook__addon-info-tests.tsx
Labels: Merge:Express, Owner Approved

#27693 react-transition-group: Add typing for Transition children as function.
  types/react-transition-group/Transition.d.ts
  types/react-transition-group/react-transition-group-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#27718 [@types/playcanvas] Fix AnimationComponent.getAnimation return type
  types/playcanvas/engine/framework/components/animation/component.d.ts
Labels: Merge:Express, Owner Approved

#27754 Fixed domain tuples.
  types/recharts/index.d.ts
Labels: Merge:Express, Owner Approved

#27753 @types/mongodb fix keep alive for v 2.2/3.x (wrong documentation)
  types/mongodb/index.d.ts
  types/mongodb/v2/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27757 modify getPlayers in video.js
  types/video.js/index.d.ts
Labels: Merge:Express, Owner Approved

#27763 [mongodb] Remove Gady from contributors
  types/mongodb/v2/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27731 [@types/aws-lambda] Add Firehose lambda event and transformation helpers
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27751 [recharts] Allow DataKey function to return null, and add missing att…
  types/recharts/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27766 cqrs-domain: Fix lint
  types/cqrs-domain/index.d.ts
Labels: Awaiting reviewer feedback

#27765 clipboard-js: Fix test
  types/clipboard-js/clipboard-js-tests.ts
Labels: Awaiting reviewer feedback

#27764 bricks.js: Fix test
  types/bricks.js/bricks.js-tests.ts
Labels: Awaiting reviewer feedback

#27748 Add typings for gulp-template
  types/gulp-template/gulp-template-tests.ts
  types/gulp-template/index.d.ts
  types/gulp-template/tsconfig.json
  types/gulp-template/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27745 [hoist-non-react-statics] fix: support custom Props, exclude known react statics, improve test cases
  types/hoist-non-react-statics/hoist-non-react-statics-tests.ts
  types/hoist-non-react-statics/hoist-non-react-statics-tests.tsx
  types/hoist-non-react-statics/index.d.ts
  types/hoist-non-react-statics/tsconfig.json
Labels: Author is Owner, Unowned

#27736 Add gradient-string typings
  types/gradient-string/gradient-string-tests.ts
  types/gradient-string/index.d.ts
  types/gradient-string/tsconfig.json
  types/gradient-string/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27639 [couchbase]: Ensure OpCallback is composable with normal callbacks
  types/couchbase/couchbase-tests.ts
  types/couchbase/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27631 hapi - request's pre & preResponses type fix
  types/hapi/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27629 @types/react-select: Add missing property 'showNewOptionAtTop' to ReactCreatableSelectProps
  types/react-select/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27777 single-spa-react: typings
  types/single-spa-react/index.d.ts
  types/single-spa-react/single-spa-react-tests.ts
  types/single-spa-react/tsconfig.json
  types/single-spa-react/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27747 feat(webpack): add compilation dependency sets
  types/webpack/index.d.ts
  types/webpack/webpack-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#27786 Fix new --strictNullChecks errors from updated lib.dom
  types/d3-dispatch/d3-dispatch-tests.ts
  types/deku/deku-tests.ts
  types/downloadjs/downloadjs-tests.ts
  types/i18next-browser-languagedetector/i18next-browser-languagedetector-tests.ts
  types/jquery.notify/jquery.notify-tests.ts
  types/jsdom/jsdom-tests.ts
  types/mark.js/mark.js-tests.ts
  types/marko/marko-tests.ts
  types/mithril/test/test-api.ts
  types/mithril/test/test-class-component.ts
  types/mithril/test/test-factory-component.ts
  types/mithril/test/test-misc.ts
  types/mithril/test/test-route.ts
  types/redom/redom-tests.ts
  types/webtorrent/webtorrent-tests.ts
  types/yandex-maps/yandex-maps-tests.ts
Labels: Popular package, The Travis CI build failed

#27789 phonegap-nfc: Fix test
  types/phonegap-nfc/index.d.ts
  types/phonegap-nfc/phonegap-nfc-tests.ts
Labels: The Travis CI build failed

#27787 blazy: Support HTMLCollection in 'load'
  types/blazy/blazy-tests.ts
  types/blazy/index.d.ts
Labels: Merge:Express, Owner Approved

#27778 angular: Fix test
  types/angular/angular-tests.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#27798 angular-desktop-notification: Change USVString to string
  types/angular-desktop-notification/index.d.ts
Labels: Merge:Express, Owner Approved

#27793 snapsvg: Fix setTimeout call
  types/snapsvg/test/2.ts
Labels: Merge:Express, Owner Approved

#27370 Lodash: `fp.pickBy`: incorrect inference when predicate has type guard
  types/lodash/common/common.d.ts
  types/lodash/common/object.d.ts
  types/lodash/fp.d.ts
  types/lodash/lodash-tests.ts
  types/lowdb/_lodash.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27638 Adding definitions for fastGet, fastPut in ssh2-sftp-client
  types/ssh2-sftp-client/index.d.ts
  types/ssh2-sftp-client/ssh2-sftp-client-tests.ts
Labels: Merge:Express, Owner Approved

#27781 Fix InferableComponentEnhancerWithProps type inference for StatelessComponent
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27799 Remove webspeechapi
  types/webspeechapi/index.d.ts
  types/webspeechapi/tsconfig.json
  types/webspeechapi/tslint.json
  types/webspeechapi/webspeechapi-tests.ts
Labels: Merge:Express, Owner Approved

#27696 @types/vexflow: Add new definitions from Vexflow PR 634, NoteSubGroup class
  types/vexflow/index.d.ts
Labels: Merge:Express, Owner Approved

#27806 weixin-app: add Partial to trigger event
  types/weixin-app/index.d.ts
Labels: Merge:Express, Owner Approved

#27800 Add typings for cssnano
  types/cssnano/cssnano-tests.ts
  types/cssnano/index.d.ts
  types/cssnano/package.json
  types/cssnano/tsconfig.json
  types/cssnano/tslint.json
Labels: New Definition, Revision needed

#27801 Adds types for start method on generic-pool
  types/generic-pool/generic-pool-tests.ts
  types/generic-pool/index.d.ts
Labels: Awaiting reviewer feedback, Other Approved

#27802 Add new type definitions for memjs 1.2
  types/memjs/index.d.ts
  types/memjs/memjs-tests.ts
  types/memjs/tsconfig.json
  types/memjs/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27811 Add type definition for error-subclass
  types/error-subclass/error-subclass-tests.ts
  types/error-subclass/index.d.ts
  types/error-subclass/tsconfig.json
  types/error-subclass/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27651 [markdown-it] add 'silent' argument to rule
  types/markdown-it/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27723 react-flag-icon-css
  types/react-flag-icon-css/index.d.ts
  types/react-flag-icon-css/package.json
  types/react-flag-icon-css/react-flag-icon-css-tests.tsx
  types/react-flag-icon-css/tsconfig.json
  types/react-flag-icon-css/tslint.json
Labels: New Definition, Revision needed

#27796 webcomponents.js: Fix compatibility with lib.dom
  types/webcomponents.js/index.d.ts
  types/webcomponents.js/tsconfig.json
  types/webcomponents.js/webcomponents.js-tests.ts
Labels: Awaiting reviewer feedback

#27821 [Office-js] Adding support details to shared API enums
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27826 office-js: initial set of SharedAPI scrub
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27741 Add new (partial) typings for npm 'di' github 'node-di'
  types/di/di-tests.ts
  types/di/index.d.ts
  types/di/tsconfig.json
  types/di/tslint.json
Labels: New Definition, Revision needed

#27686 Adding types for crypto-random-string 1.0
  types/crypto-random-string/crypto-random-string-tests.ts
  types/crypto-random-string/index.d.ts
  types/crypto-random-string/tsconfig.json
  types/crypto-random-string/tslint.json
Labels: New Definition, Revision needed

#27850 office-js: Update links
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27812 Added additional ns prop for react-i18next
  types/react-i18next/src/trans.d.ts
Labels: Merge:Express, Owner Approved

#27828 [@types/dnssd] Fix return types
  types/dnssd/dnssd-tests.ts
  types/dnssd/index.d.ts
Labels: Merge:Express, Owner Approved

#27832 weixin-app - update setData to include callback
  types/weixin-app/index.d.ts
  types/weixin-app/weixin-app-tests.ts
Labels: Merge:Express, Owner Approved

#27834 Fix types from last big addition
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Merge:Express, Owner Approved

#27820 Stripe: added trial_from_plan to ISubscriptionCustCreationOptions interface
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved

#27809 @types/react-native - Add missing property textContentType for TextInputIOSProps.
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27827 [styled-system] Make GridAutoValue responsive
  types/styled-system/index.d.ts
Labels: Merge:Express, Owner Approved

#27839 Update redom-definitions on current state
  types/redom/index.d.ts
  types/redom/redom-tests.ts
Labels: Merge:Express, Owner Approved

#27785 @types/graphql: is*Type() predicates can take null and undefined
  types/graphql/graphql-tests.ts
  types/graphql/type/definition.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27849 Chrome-apps better coverage, cleanup and fixes
  types/chrome-apps/index.d.ts
  types/chrome-apps/test/index.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27838 videojs: update autoplay types to boolean or string
  types/video.js/index.d.ts
Labels: Awaiting reviewer feedback, Other Approved

#27837 Feature/react select v2 update
  types/react-select/lib/Creatable.d.ts
  types/react-select/lib/Select.d.ts
  types/react-select/lib/components/Control.d.ts
  types/react-select/lib/components/Group.d.ts
  types/react-select/lib/components/Input.d.ts
  types/react-select/lib/components/Menu.d.ts
  types/react-select/lib/components/MultiValue.d.ts
  types/react-select/lib/components/Option.d.ts
  types/react-select/lib/components/Placeholder.d.ts
  types/react-select/lib/components/SingleValue.d.ts
  types/react-select/lib/components/containers.d.ts
  types/react-select/lib/components/index.d.ts
  types/react-select/lib/components/indicators.d.ts
  types/react-select/lib/styles.d.ts
  types/react-select/test/examples/Experimental.tsx
  types/react-select/test/examples/MenuPortal.tsx
  types/react-select/test/examples/Popout.tsx
Labels: Awaiting reviewer feedback, Other Approved, Popular package, Revision needed

#27683 Update styled-system types to 3.0
  types/styled-system/dist/mixed.d.ts
  types/styled-system/dist/space.d.ts
  types/styled-system/dist/styles.d.ts
  types/styled-system/dist/util.d.ts
  types/styled-system/dist/variant.d.ts
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Owner Approved, The Travis CI build failed

#27788 [NodeJS] Fix 'this' type for stream options.
  types/node/index.d.ts
  types/node/node-tests.ts
  types/vinyl-fs/index.d.ts
Labels: Owner Approved, Popular package, Revision needed, The Travis CI build failed

#27852 Add typings for @storybook/addon-jest
  types/storybook__addon-jest/index.d.ts
  types/storybook__addon-jest/storybook__addon-jest-tests.tsx
  types/storybook__addon-jest/tsconfig.json
  types/storybook__addon-jest/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27846 @types/three: Update LoadingManager
  types/three/three-core.d.ts
Labels: Awaiting reviewer feedback, Popular package

#27824 passport-saml: Add 'name' property to SamlConfig
  types/passport-saml/index.d.ts
  types/passport-saml/passport-saml-tests.ts
Labels: Merge:Express, Owner Approved

#27857 Add explicit typing for $.fn.dataTable.ext property.
  types/datatables.net/datatables.net-tests.ts
  types/datatables.net/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#27858 Rename @types/storejs to @types/store (fixes #27825)
  types/store/index.d.ts
  types/store/store-tests.ts
  types/store/tsconfig.json
  types/store/tslint.json
  types/store/v1/index.d.ts
  types/store/v1/store-tests.ts
  types/store/v1/tsconfig.json
  types/store/v1/tslint.json
Labels: Unowned

#27862 office-js: clean up links and table formatting
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27847 New type definitions for rdflib 0.17
  types/rdflib/index.d.ts
  types/rdflib/rdflib-tests.ts
  types/rdflib/tsconfig.json
  types/rdflib/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27859 Add typings for is-callable
  types/is-callable/index.d.ts
  types/is-callable/is-callable-tests.ts
  types/is-callable/tsconfig.json
  types/is-callable/tslint.json
Labels: New Definition, Revision needed

#27863 fix(nanographql): support usage as normal fn
  types/nanographql/index.d.ts
  types/nanographql/nanographql-tests.ts
Labels: Author is Owner, Merge:Express

#27861 add @iarna/toml
  types/iarna__toml/iarna__toml-tests.ts
  types/iarna__toml/index.d.ts
  types/iarna__toml/parse-async.d.ts
  types/iarna__toml/parse-stream.d.ts
  types/iarna__toml/parse-string.d.ts
  types/iarna__toml/stringify.d.ts
  types/iarna__toml/tsconfig.json
  types/iarna__toml/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27867 [react-relay] Type-check fragment references.
  types/react-relay/index.d.ts
  types/react-relay/test/react-relay-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27896 Add jqueryui slider class type
  types/jqueryui/index.d.ts
  types/jqueryui/jqueryui-tests.ts
Labels: Awaiting reviewer feedback, Popular package

#27830 add convert function to quill's clipboard api
  types/quill/index.d.ts
  types/quill/quill-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27716 Add types for sdp-transform
  types/sdp-transform/index.d.ts
  types/sdp-transform/sdp-transform-tests.ts
  types/sdp-transform/tsconfig.json
  types/sdp-transform/tslint.json
Labels: New Definition, Revision needed

#27742 Add korean readme
  README.ko.md
  README.md
Labels: Unowned

#27622 [node]: Update assert.fail parameters
  types/node/index.d.ts
  types/node/v0/index.d.ts
  types/node/v0/node-tests.ts
  types/node/v4/index.d.ts
  types/node/v6/index.d.ts
  types/node/v6/node-tests.ts
  types/node/v7/index.d.ts
  types/node/v7/node-tests.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Owner Approved, Popular package, Revision needed, The Travis CI build failed

#27759 mongoose: add context to the ModelFindByIdAndUpdateOptions
  types/mongoose/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27774 mocha: Fix $ExpectType assertions
  types/mocha/mocha-tests.ts
Labels: Popular package, The Travis CI build failed

#27901 [react] add library managed attributes and upgrade TS requirement to 2.8
  types/create-react-class/index.d.ts
  types/gestalt/index.d.ts
  types/hoist-non-react-statics/hoist-non-react-statics-tests.tsx
  types/react-adal/index.d.ts
  types/react-addons-create-fragment/index.d.ts
  types/react-addons-css-transition-group/index.d.ts
  types/react-addons-linked-state-mixin/index.d.ts
  types/react-addons-pure-render-mixin/index.d.ts
  types/react-addons-shallow-compare/index.d.ts
  types/react-addons-test-utils/index.d.ts
  types/react-addons-transition-group/index.d.ts
  types/react-addons-update/index.d.ts
  types/react-aria-modal/index.d.ts
  types/react-dom-factories/index.d.ts
  types/react-dom/index.d.ts
  types/react-dom/v15/index.d.ts
  types/react-dragtastic/index.d.ts
  types/react-flag-icon-css/index.d.ts
  types/react-highlight/index.d.ts
  types/react-input-autosize/index.d.ts
  types/react-intl/react-intl-tests.tsx
  types/react-no-ssr/index.d.ts
  types/react-plotly.js/index.d.ts
  types/react-portal/v3/index.d.ts
  types/react-qr-reader/index.d.ts
  types/react-select/test/examples/Experimental.tsx
  types/react-select/v1/index.d.ts
  types/react-test-renderer/v15/tsconfig.json
  types/react/index.d.ts
  types/react/test/index.ts
  types/react/test/managedAttributes.tsx
  types/react/tsconfig.json
  types/react/v15/index.d.ts
  types/react/v15/test/index.ts
  types/react/v15/tsconfig.json
  types/recompose/index.d.ts
  types/recompose/recompose-tests.tsx
  types/single-spa-react/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#27829 [Office-js] Adding support tables to Shared API methods
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#27769 dom4: ElementTraversal is now part of ParentNode
  types/dom4/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27648 d3-quadtree: JsDoc, strictNullChecks and TS 2.3
  types/d3-quadtree/d3-quadtree-tests.ts
  types/d3-quadtree/index.d.ts
  types/d3-quadtree/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27670 [@types/aws-lambda]: Add extractedFields optional field
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27680 [react-twitter-auth] update types
  types/react-twitter-auth/index.d.ts
  types/react-twitter-auth/react-twitter-auth-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#27711 [@types/highcharts] Fix type definition for responsive rules chartOptions
  types/highcharts/index.d.ts
  types/highcharts/test/index.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27713 Bring connect-mongo types in line with express-session
  types/connect-mongo/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27721 [@types/pretty-ms] Update to 3.2. Add opiton `keepDecimalsOnWholeSeconds`
  types/pretty-ms/index.d.ts
  types/pretty-ms/pretty-ms-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27722 kendo-ui: add skip() function to DataSource
  types/kendo-ui/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27746 [@types/google.picker] Fix signature of Picker.setCallback()
  types/google.picker/index.d.ts
Labels: Merge:Express, Owner Approved

#27749 [@types/vimeo__player] Updating typings to match Vimeo's player.js v2.6.3
  types/vimeo__player/index.d.ts
  types/vimeo__player/vimeo__player-tests.ts
Labels: Merge:Express, Owner Approved

#27755 timezone-js: timezoneJS.Date.toString have a handy format parameter so we daclare it
  types/timezone-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27771 pouchdb-core: extend Database with EventEmitter
  types/pouchdb-core/index.d.ts
  types/pouchdb-core/pouchdb-core-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27783 owl.carousel : Add autoHeight option
  types/owl.carousel/index.d.ts
Labels: Merge:Express, Owner Approved

#27836 material__menu CornerBit interface is wrong
  types/material__menu/constants.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27848 Add selectV2 definition to @storybook/addon-knobs
  types/storybook__addon-knobs/index.d.ts
  types/storybook__addon-knobs/storybook__addon-knobs-tests.tsx
Labels: Merge:Express, Owner Approved

#27856 Update version of redom-types
  types/redom/index.d.ts
Labels: Merge:Express, Owner Approved

#27860 @types/react-resize-detector: Update to v3.1.0
  types/react-resize-detector/index.d.ts
  types/react-resize-detector/react-resize-detector-tests.tsx
Labels: Merge:Express, Owner Approved

#27866 [@types/node] add missing optional padding and saltLength
  types/node/index.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#27871 [react-select] switch DOM Node for ReactNode as per other files
  types/react-select/lib/Creatable.d.ts
  types/react-select/lib/Select.d.ts
  types/react-select/lib/builtins.d.ts
  types/react-select/lib/components/Control.d.ts
  types/react-select/lib/components/Group.d.ts
  types/react-select/lib/components/Menu.d.ts
  types/react-select/lib/components/MultiValue.d.ts
  types/react-select/lib/components/Option.d.ts
  types/react-select/lib/components/Placeholder.d.ts
  types/react-select/lib/components/containers.d.ts
Labels: Awaiting reviewer feedback, Other Approved, Popular package

#27875 Add types for extsprintf
  types/extsprintf/extsprintf-tests.ts
  types/extsprintf/index.d.ts
  types/extsprintf/tsconfig.json
  types/extsprintf/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27877 [@types/dnssd] More fixes according the original source
  types/dnssd/index.d.ts
Labels: Merge:Express, Owner Approved

#27880 [react-virtualized] Fix WindowScrollerChildProps
  types/react-virtualized/dist/es/WindowScroller.d.ts
  types/react-virtualized/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27884 feat(stripe): add failure_reason for refunds
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved

#27891 Add types for capture-console
  types/capture-console/capture-console-tests.ts
  types/capture-console/index.d.ts
  types/capture-console/tsconfig.json
  types/capture-console/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27894 [react-transition-group] Restrict Transition child function's argument type
  types/react-transition-group/Transition.d.ts
  types/react-transition-group/index.d.ts
  types/react-transition-group/react-transition-group-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#27895 [react-i18next]: use React.ReactNode instead of JSX.Element in `I18n`'s children and `I18nextProvider`
  types/react-i18next/index.d.ts
  types/react-i18next/src/I18n.d.ts
  types/react-i18next/src/I18nextProvider.d.ts
  types/react-i18next/test/react-i18next-tests.tsx
Labels: Merge:Express, Owner Approved

#27900 [google-cloud__datastore] Move from namespace to static attributes
  types/google-cloud__datastore/google-cloud__datastore-tests.ts
  types/google-cloud__datastore/index.d.ts
Labels: Merge:Express, Owner Approved

#27913 quill: fix signature for clipboard api
  types/quill/index.d.ts
  types/quill/quill-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#27794 velocity-animate: Support HTMLCollection in addition to NodeListOf<HTMLElement>
  types/velocity-animate/index.d.ts
Labels: The Travis CI build failed

#27797 webappsec-credential-management: Fix lib.dom error
  types/webappsec-credential-management/index.d.ts
  types/webappsec-credential-management/webappsec-credential-management-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27920 Change all `document.body!` to `document.body`
  types/bricks.js/bricks.js-tests.ts
  types/clipboard-js/clipboard-js-tests.ts
  types/d3-dispatch/d3-dispatch-tests.ts
  types/deku/deku-tests.ts
  types/jquery.notify/jquery.notify-tests.ts
  types/jsdom/jsdom-tests.ts
  types/mark.js/mark.js-tests.ts
  types/marko/marko-tests.ts
  types/mithril/test/test-api.ts
  types/mithril/test/test-class-component.ts
  types/mithril/test/test-factory-component.ts
  types/mithril/test/test-misc.ts
  types/mithril/test/test-route.ts
  types/webcomponents.js/webcomponents.js-tests.ts
  types/webtorrent/webtorrent-tests.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#27768 d3-selection: Fix tests
  types/d3-selection/d3-selection-tests.ts
  types/d3-selection/index.d.ts
Labels: Popular package, The Travis CI build failed

#27919 Jquery: change disables in tslint.json to disables in specific files
  types/jquery/test/example-tests.ts
  types/jquery/test/learn-tests.ts
  types/jquery/test/longdesc-tests.ts
  types/jquery/tslint.json
Labels: Popular package, The Travis CI build failed

#27818 [knex] Allow QueryBuilder in union parameters
  types/knex/index.d.ts
  types/knex/knex-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27911 fork-ts-checker-webpack-plugin: Don't limit Options.logger to the Console type
  types/fork-ts-checker-webpack-plugin/fork-ts-checker-webpack-plugin-tests.ts
  types/fork-ts-checker-webpack-plugin/index.d.ts
Labels: Merge:Express, Owner Approved

#27936 [auth0-js] Add prompt value in AuthorizeOptions
  types/auth0-js/auth0-js-tests.ts
  types/auth0-js/index.d.ts
Labels: Merge:Express, Owner Approved

#27822 Allow readonly parameters to @storybook/addon-knobs
  types/storybook__addon-knobs/index.d.ts
  types/storybook__addon-knobs/storybook__addon-knobs-tests.tsx
Labels: Merge:Express, Owner Approved

#27927 Fix typings for zipcodes
  types/zipcodes/index.d.ts
  types/zipcodes/zipcodes-tests.ts
Labels: Merge:Express, Owner Approved

#27945 BFS returns void if search not successful but should continue
  types/cytoscape/index.d.ts
Labels: Merge:Express, Owner Approved

#27939 Removes interactjs types
  notNeededPackages.json
  types/interact.js/index.d.ts
  types/interact.js/interact.js-tests.ts
  types/interact.js/tsconfig.json
  types/interact.js/tslint.json
Labels: Merge:Express, Owner Approved

#27886 [@types/parse-git-config] sync with latest api changes
  types/parse-git-config/index.d.ts
  types/parse-git-config/parse-git-config-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27892 Add lineDashOffset Definition to types/openlayers
  types/openlayers/index.d.ts
  types/openlayers/openlayers-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27917 fix(joi): add global exist function
  types/joi/index.d.ts
  types/joi/joi-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#27928 radium: Remove myself as author
  types/radium/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27930 Added few missing properties
  types/leaflet-routing-machine/index.d.ts
Labels: Author is Owner, Merge:Express

#27947 office-js: clean up formatting
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#27918 feat(catbox-redis): add typings
  types/catbox-redis/catbox-redis-tests.ts
  types/catbox-redis/index.d.ts
  types/catbox-redis/tsconfig.json
  types/catbox-redis/tslint.json
  types/catbox/index.d.ts
Labels: New Definition, Revision needed

#27864 three: WebGLRenderer: Rename animate() to setAnimationLoop()
  types/three/three-core.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27855 [redux-form] Add FieldsProps.move method
  types/redux-form/lib/FieldArray.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27996 [prop-types]: add PropTypes.exact()
  types/prop-types/index.d.ts
  types/react/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#27910 react-select: Remove "moment" dependency
  types/react-select/test/examples/Experimental.tsx
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#27907 moment-shortformat: Fix no-outside-dependencies lint failure
  types/moment-shortformat/package.json
Labels: Owner Approved, The Travis CI build failed

#27983 [material__menu] Corrected parameter type for MDCMenu.setAnchorCorner()
  types/material__menu/foundation.d.ts
  types/material__menu/index.d.ts
Labels: Merge:Express, Owner Approved

#27931 Update types for react-sidebar 3.0.0
  types/react-sidebar/index.d.ts
  types/react-sidebar/react-sidebar-tests.tsx
Labels: Merge:Express, Owner Approved

#27929 [react-navigation] add exportation StackViewTransitionConfigs
  types/react-navigation/index.d.ts
  types/react-navigation/react-navigation-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#27971 Change the type of URLFetchRequestOptions.payload from string to Object
  types/google-apps-script/google-apps-script-tests.ts
  types/google-apps-script/google-apps-script.url-fetch.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27951 Three js buffer geometry utils and drag controls
  types/three/index.d.ts
  types/three/three-core.d.ts
  types/three/three-dragcontrols.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27979 [office-js] Formatting support tables better
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#27981 fix issue DefinitelyTyped/DefinitelyTyped#27970
  types/qlik-engineapi/index.d.ts
Labels: Author is Owner, Merge:Express

#27994 Add changes for theme context
  types/react-native-material-ui/index.d.ts
  types/react-native-material-ui/react-native-material-ui-tests.tsx
Labels: Author is Owner, Merge:Express

#28013 [video.js] Adds missing 'ended' method to the player
  types/video.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27968 chore(fork-ts-checker-webpack-plugin): remove typings
  notNeededPackages.json
  types/fork-ts-checker-webpack-plugin/fork-ts-checker-webpack-plugin-tests.ts
  types/fork-ts-checker-webpack-plugin/index.d.ts
  types/fork-ts-checker-webpack-plugin/package.json
  types/fork-ts-checker-webpack-plugin/tsconfig.json
  types/fork-ts-checker-webpack-plugin/tslint.json
Labels: Awaiting reviewer feedback

#27950 [node] Update declarations for dns.resolveAny
  types/node/index.d.ts
  types/node/node-tests.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#28071 [react-relay] Add plural fragment refs and handle connection data well.
  types/react-relay/index.d.ts
  types/react-relay/test/react-relay-compat-tests.tsx
  types/react-relay/test/react-relay-tests.tsx
  types/relay-runtime/index.d.ts
Labels: Author is Owner, The Travis CI build failed

#28052 Fix return type React Native AsyncStorage.getItem
  types/react-native/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#28051 (react-native) Add keyboardType to AlertIOS prompt
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#27522 [React native] Add section in SectionListRenderItemInfo
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Popular package, Revision needed
