Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2018-07, with the labels that each got.

#26965 Jest: Docs improvements
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#26601 [graphql] Update to v14.0.0 (WIP)
  types/graphql/error/GraphQLError.d.ts
  types/graphql/error/formatError.d.ts
  types/graphql/error/locatedError.d.ts
  types/graphql/execution/execute.d.ts
  types/graphql/index.d.ts
  types/graphql/language/ast.d.ts
  types/graphql/language/index.d.ts
  types/graphql/language/kinds.d.ts
  types/graphql/language/parser.d.ts
  types/graphql/language/visitor.d.ts
  types/graphql/type/definition.d.ts
  types/graphql/type/schema.d.ts
  types/graphql/utilities/buildASTSchema.d.ts
  types/graphql/utilities/getOperationRootType.d.ts
  types/graphql/utilities/index.d.ts
  types/graphql/utilities/introspectionQuery.d.ts
  types/graphql/utilities/isValidJSValue.d.ts
  types/graphql/utilities/isValidLiteralValue.d.ts
  types/graphql/validation/index.d.ts
  types/graphql/validation/rules/FragmentsOnCompositeTypes.d.ts
  types/graphql/validation/rules/PossibleFragmentSpreads.d.ts
  types/graphql/validation/rules/ProvidedNonNullArguments.d.ts
  types/graphql/validation/rules/ProvidedRequiredArguments.d.ts
  types/graphql/validation/rules/ScalarLeafs.d.ts
  types/graphql/validation/rules/VariablesDefaultValueAllowed.d.ts
  types/graphql/validation/rules/VariablesInAllowedPosition.d.ts
  types/graphql/validation/specifiedRules.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#26966 remote-redux-devtools: bumped redux version to 4.x & correct (Generic)StoreEnhancer import & TypeScript 2.3
  types/remote-redux-devtools/index.d.ts
  types/remote-redux-devtools/package.json
Labels: Merge:Express, Owner Approved

#26857 [@types/minio] Add minio promisified removeObjects
  types/minio/index.d.ts
  types/minio/minio-tests.ts
Labels: Merge:Express, Owner Approved

#26971 [expect-puppeteer] toDisplayDialog() should return a Dialog
  types/expect-puppeteer/expect-puppeteer-tests.ts
  types/expect-puppeteer/index.d.ts
Labels: Merge:Express, Owner Approved

#26967 add missing `silent` value for webpack-serve logLevel
  types/webpack-serve/index.d.ts
  types/webpack-serve/webpack-serve-tests.ts
Labels: Unowned

#26811 [koa-websocket] Expose KoaWebsocket namespace
  types/koa-websocket/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26673 [@types/d3-transition] Add a new type to d3-transition that represents either a selection or transition
  types/d3-transition/index.d.ts
  types/d3-zoom/d3-zoom-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26829 react-select - adds classNamePrefix as property of ReactSelectProps
  types/react-select/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26854 [knockout] Reorder overrides of ko.observable to handle an edge-case better.
  types/knockout/index.d.ts
  types/knockout/test/index.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26853 combine possible error types in single type and use it for verification callback
  types/jsonwebtoken/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26864 codemirror-added type for countColumn function
  types/codemirror/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26972 New package: 'hard-source-webpack-plugin'
  types/hard-source-webpack-plugin/hard-source-webpack-plugin-tests.ts
  types/hard-source-webpack-plugin/index.d.ts
  types/hard-source-webpack-plugin/tsconfig.json
  types/hard-source-webpack-plugin/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26872 [react-big-calendar]: make event type generic
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#26876 react-router: add generatePath function export introduced in react-router 4.3.0
  types/react-router/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26940 @types/restify (7.2) : Add maxFileSize to MultipartBodyParser interface
  types/restify/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#26976 feat: add six-runtime
  types/six-runtime/index.d.ts
  types/six-runtime/six-runtime-tests.ts
  types/six-runtime/tsconfig.json
  types/six-runtime/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#26749 nano - added startkey & endkey to DocumentListParams interface
  types/nano/index.d.ts
Labels: Revision needed

#26645 [react-router] Change staticContext to optional prop
  types/react-router/index.d.ts
Labels: Popular package, Revision needed

#26874 Type Definitions for Summernote
  types/summernote/index.d.ts
  types/summernote/summernote-tests.ts
  types/summernote/tsconfig.json
  types/summernote/tslint.json
Labels: New Definition, Revision needed

#26806 Add Linear method definition
  types/sharp/index.d.ts
Labels: Revision needed

#26984 office-js - add omitted Project APIs
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26987 Add react-svg-inline types
  types/react-svg-inline/index.d.ts
  types/react-svg-inline/react-svg-inline-tests.tsx
  types/react-svg-inline/tsconfig.json
  types/react-svg-inline/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26827 (re-opened) Type definitions for slate-react
  types/slate-react/index.d.ts
  types/slate-react/package.json
  types/slate-react/slate-react-tests.tsx
  types/slate-react/tsconfig.json
  types/slate-react/tslint.json
Labels: New Definition, Revision needed

#26780 vuex-i18n - Nested Translations interface and support for translateIn with two parameters
  types/vuex-i18n/index.d.ts
  types/vuex-i18n/vuex-i18n-tests.ts
Labels: Revision needed

#26990 office-js: updated Project API based on comments
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#26992 Revert "[@types/hapi] Add null to Request.params and Request.payload"
  types/hapi/index.d.ts
  types/hapi/test/request/parameters.ts
Labels: Awaiting reviewer feedback

#26993 Add yesql definitions
  types/yesql/index.d.ts
  types/yesql/tsconfig.json
  types/yesql/tslint.json
  types/yesql/yesql-tests.ts
Labels: New Definition, Revision needed

#26968 new package: "match-sorter"
  types/match-sorter/index.d.ts
  types/match-sorter/match-sorter-tests.ts
  types/match-sorter/tsconfig.json
  types/match-sorter/tslint.json
Labels: New Definition, Revision needed

#26998 add nanographql typings
  types/nanographql/index.d.ts
  types/nanographql/nanographql-tests.ts
  types/nanographql/tsconfig.json
  types/nanographql/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27001 [streamtest]: initial typings for streamtest
  types/streamtest/index.d.ts
  types/streamtest/streamtest-tests.ts
  types/streamtest/tsconfig.json
  types/streamtest/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27002 Remove winston typings from DT, they are bundled with repo now
  notNeededPackages.json
  types/winston/index.d.ts
  types/winston/tsconfig.json
  types/winston/tslint.json
  types/winston/winston-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#27003 [office-js] Adding Manifest Editing Guidance Link
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26999 [ember]: fix composition of Mixins
  types/ember/index.d.ts
  types/ember/test/mixin.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved

#26980 Fix Issue #17865: ioredis sscan and sscanStream command types
  types/ioredis/index.d.ts
Labels: Merge:Express, Owner Approved

#26973 Add Types for react-primitives
  types/react-primitives/index.d.ts
  types/react-primitives/react-primitives-tests.tsx
  types/react-primitives/tsconfig.json
  types/react-primitives/tslint.json
Labels: New Definition, Revision needed

#27004 office-js: update Project typos
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#26994 Convert tabs to spaces in index.d.ts
  types/highcharts/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#26996 Fix issue where Stripe.plans.list would not support all options
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved

#26978 Update index.d.ts
  types/react-native/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#26882 karma: Add typings for 'middleware' in ConfigOptions
  types/karma/index.d.ts
  types/karma/karma-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#27008 [mongodb] Added countDocuments() and estimatedDocumentCount()
  types/mongodb/index.d.ts
  types/mongodb/mongodb-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27005 New typings for bpmn-moddle
  types/bpmn-moddle/bpmn-moddle-tests.ts
  types/bpmn-moddle/index.d.ts
  types/bpmn-moddle/tsconfig.json
  types/bpmn-moddle/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#27010 Add Types for react-coinhive
  types/react-coinhive/index.d.ts
  types/react-coinhive/react-coinhive-tests.tsx
  types/react-coinhive/tsconfig.json
  types/react-coinhive/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27015 [splunk-logging] New type definition for splunk-logging module
  types/splunk-logging/index.d.ts
  types/splunk-logging/splunk-logging-tests.ts
  types/splunk-logging/tsconfig.json
  types/splunk-logging/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26883 [js-yaml] Revert return type of loader functions to any
  types/js-yaml/index.d.ts
  types/js-yaml/js-yaml-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26907 [@types/minio] Add 2 missing constructor parameters
  types/minio/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27022 React js pagination
  types/react-js-pagination/index.d.ts
  types/react-js-pagination/react-js-pagination-tests.tsx
  types/react-js-pagination/tsconfig.json
  types/react-js-pagination/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26873 Add string to Tether.ITetherOptions.classes
  types/tether/index.d.ts
  types/tether/tether-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26895 [@types/webpack-dev-server] Module augmentation and descriptions for type defs
  types/webpack-dev-server/index.d.ts
  types/webpack-dev-server/webpack-dev-server-tests.ts
  types/webpack/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27020 Add 'package.json's for winston dependencies
  types/bunyan-winston-adapter/bunyan-winston-adapter-tests.ts
  types/bunyan-winston-adapter/index.d.ts
  types/bunyan-winston-adapter/package.json
  types/express-winston/express-winston-tests.ts
  types/express-winston/index.d.ts
  types/express-winston/package.json
  types/http-proxy-middleware/http-proxy-middleware-tests.ts
  types/http-proxy-middleware/package.json
  types/koa-logger-winston/index.d.ts
  types/koa-logger-winston/koa-logger-winston-tests.ts
  types/koa-logger-winston/package.json
  types/slack-winston/package.json
  types/svg-sprite/index.d.ts
  types/svg-sprite/package.json
  types/winston-dynamodb/package.json
  types/winston-syslog/package.json
Labels: Awaiting reviewer feedback, Popular package

#26942 Add typings for vexdb
  types/vexdb/index.d.ts
  types/vexdb/tsconfig.json
  types/vexdb/tslint.json
  types/vexdb/vexdb-tests.ts
Labels: New Definition, Revision needed

#26763 [@types/graphql] Add generic type on ExecutionResult
  types/graphql/execution/execute.d.ts
  types/graphql/graphql.d.ts
  types/graphql/index.d.ts
  types/graphql/subscription/subscribe.d.ts
Labels: Popular package, Revision needed

#26782 Add a definition of atlassian-crowd-client
  types/atlassian-crowd-client/api.d.ts
  types/atlassian-crowd-client/atlassian-crowd-client-tests.ts
  types/atlassian-crowd-client/index.d.ts
  types/atlassian-crowd-client/lib/models/attributes.d.ts
  types/atlassian-crowd-client/lib/models/group.d.ts
  types/atlassian-crowd-client/lib/models/session.d.ts
  types/atlassian-crowd-client/lib/models/user.d.ts
  types/atlassian-crowd-client/lib/models/validation-factors.d.ts
  types/atlassian-crowd-client/settings.d.ts
  types/atlassian-crowd-client/tsconfig.json
  types/atlassian-crowd-client/tslint.json
Labels: New Definition, Revision needed

#26989 Add .container to ChartSpecs for google.visualization
  types/google.visualization/index.d.ts
Labels: Merge:Express, Owner Approved, Where is Travis?

#26900 Define AggressiveSplitterPlugin in optimize namespace
  types/webpack/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#27024 @types/react-circular-progressbar: update component props according to project readme
  types/react-circular-progressbar/index.d.ts
  types/react-circular-progressbar/react-circular-progressbar-tests.tsx
Labels: Merge:Express, Owner Approved

#26887 [@types/tedious] Updating type definitions to match newer version of driver
  types/tedious/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26925 [ember-qunit] Add definition for `start()`
  types/ember-qunit/ember-qunit-tests.ts
  types/ember-qunit/index.d.ts
Labels: Merge:Express, Owner Approved

#27013 Add-Type: mongodb-uri 0.9, https://github.com/mongolab/mongodb-uri-node
  types/mongodb-uri/index.d.ts
  types/mongodb-uri/mongodb-uri-tests.ts
  types/mongodb-uri/tsconfig.json
  types/mongodb-uri/tslint.json
Labels: New Definition, Revision needed

#27029 Add types for react-gateway@2.8
  types/react-gateway/Gateway.d.ts
  types/react-gateway/GatewayDest.d.ts
  types/react-gateway/GatewayProvider.d.ts
  types/react-gateway/GatewayRegistry.d.ts
  types/react-gateway/index.d.ts
  types/react-gateway/react-gateway-tests.tsx
  types/react-gateway/tsconfig.json
  types/react-gateway/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27032 New typings for zip-webpack-plugin
  types/zip-webpack-plugin/index.d.ts
  types/zip-webpack-plugin/tsconfig.json
  types/zip-webpack-plugin/tslint.json
  types/zip-webpack-plugin/zip-webpack-plugin-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#27034 Add types for react-motion-ui-pack@0.10
  types/react-motion-ui-pack/index.d.ts
  types/react-motion-ui-pack/react-motion-ui-pack-tests.tsx
  types/react-motion-ui-pack/tsconfig.json
  types/react-motion-ui-pack/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26926 Added the IANAZone class for luxon
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26934 [Victory] DomainPaddingPropType accepts x and y arrays
  types/victory/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27028 improve http-graceful-shutdown - library should also support https servers
  types/http-graceful-shutdown/http-graceful-shutdown-tests.ts
  types/http-graceful-shutdown/index.d.ts
Labels: Unowned

#27062 Cytoscape: small fixes for tests; many fixes for return values
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27045 [Chart.js] Add static helpers
  types/chart.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#26793 expo: Add Expo.Linking API.
  types/expo/expo-tests.tsx
  types/expo/index.d.ts
Labels: Merge:Express, Owner Approved

#26787 [@types/chart.js] Add 'onResize' callback definition
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#26906 [@types/minio] Added metadata functionality
  types/minio/index.d.ts
  types/minio/minio-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27044 [hapi] Statehood format/parse should return a Promise.
  types/hapi/index.d.ts
Labels: Merge:Express, Owner Approved

#27050 [@types/mongoose] Added flag for useNewUrlParser in ConnectionOptions
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#27031 [ember] - Add missing Ember.Route#intermediateTransitionTo method
  types/ember/index.d.ts
  types/ember/test/route.ts
  types/ember/test/router.ts
Labels: Merge:Express, Owner Approved

#27051 Add Function forceReRender() to Definitions
  types/storybook__react/index.d.ts
  types/storybook__react/storybook__react-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#27054 Update syntax for `passport-strategy`
  types/passport-strategy/index.d.ts
Labels: Merge:Express, Owner Approved

#27030 Add missing stripe.iinvoice fields
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#27067 Add useNewUrlParser parameter to mongoose
  types/mongoose/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27075 columns argument in 'columnMetadata' event callback must be an array.
  types/tedious/index.d.ts
Labels: Merge:Express, Owner Approved

#27059 [react-native] - Wrap events to NativeSyntheticEvent
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Merge:Express, Owner Approved, Popular package

#27073 Add millisecond package types
  types/millisecond/index.d.ts
  types/millisecond/millisecond-tests.ts
  types/millisecond/tsconfig.json
  types/millisecond/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27056 Add type definitions for get-folder-size
  types/get-folder-size/get-folder-size-tests.ts
  types/get-folder-size/index.d.ts
  types/get-folder-size/tsconfig.json
  types/get-folder-size/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27057 fix mockjs.Random.string() signtuare
  types/mockjs/index.d.ts
Labels: Unowned

#27041 [splunk-bunyan-logger] Adding new type definition
  types/splunk-bunyan-logger/index.d.ts
  types/splunk-bunyan-logger/splunk-bunyan-logger-tests.ts
  types/splunk-bunyan-logger/tsconfig.json
  types/splunk-bunyan-logger/tslint.json
  types/splunk-logging/index.d.ts
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27049 [wepy] modifying wx.request params
  .github/CODEOWNERS
  types/wepy/wepy-tests.ts
  types/wepy/wx_enhanced.d.ts
Labels: Unowned

#27052 Add type definitions for react-notify-toast
  types/react-notify-toast/index.d.ts
  types/react-notify-toast/react-notify-toast-tests.tsx
  types/react-notify-toast/tsconfig.json
  types/react-notify-toast/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27058 [@types/three]: Fix Object3D#clone.
  types/three/three-core.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#26881 Fixed headerLeft and headerRight props
  types/react-navigation/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26936 Adding tags and events capabilities
  types/intercom-client/Company.d.ts
  types/intercom-client/Event.d.ts
  types/intercom-client/Tag.d.ts
  types/intercom-client/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26954 googlemaps: adapt to api changes
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26962 highcharts - Add interface for the wrapping and extension of tooltips.
  types/highcharts/index.d.ts
  types/highcharts/test/index.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27033 [chai] fix tests
  types/chai/tslint.json
Labels: Awaiting reviewer feedback, Popular package

#27035 Add types for react-slider@0.8
  types/react-slider/index.d.ts
  types/react-slider/react-slider-tests.tsx
  types/react-slider/tsconfig.json
  types/react-slider/tslint.json
Labels: New Definition, Revision needed

#27079 Add types for react-hammerjs@0.5
  types/react-hammerjs/index.d.ts
  types/react-hammerjs/react-hammerjs-tests.tsx
  types/react-hammerjs/tsconfig.json
  types/react-hammerjs/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27036 [node] Added missing COPYFILE_* constants
  types/node/index.d.ts
  types/node/node-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#27014 Add missing maxFreeSockets property of Agent class in node
  types/node/index.d.ts
  types/node/v0/index.d.ts
  types/node/v4/index.d.ts
  types/node/v6/index.d.ts
  types/node/v7/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#26678 Added 'strict' to the 'assert' module.
  types/node/index.d.ts
  types/node/node-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#27046 [Chart.js] Fix plugins global registration and order
  types/chart.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#27085 [arcgis-js-api] Update for version 3.25
  types/arcgis-js-api/v3/index.d.ts
Labels: Merge:Express, Owner Approved

#27078 [bootstrap] False is valid for interval option in carousel
  types/bootstrap/bootstrap-tests.ts
  types/bootstrap/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#26986 [stampit] moved Stamp type to reside in main namespace
  types/stampit/index.d.ts
  types/stampit/stampit-tests.ts
Labels: Merge:Express, Owner Approved

#27072 feat(fs-extra): replace fs.symlink.Type with local copy FsSymlinkType
  types/fs-extra/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27065 react-native-popup-dialog: PopupDialog show and dismiss methods typings
  types/react-native-popup-dialog/index.d.ts
  types/react-native-popup-dialog/react-native-popup-dialog-tests.tsx
Labels: Merge:Express, Owner Approved, Revision needed

#27091 [@types/hexo-util] Create @types/hexo-util
  types/hexo-util/hexo-util-tests.ts
  types/hexo-util/index.d.ts
  types/hexo-util/tsconfig.json
  types/hexo-util/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27087 New definitions for [slate-plain-serializer], [slate-html-serializer], [slate-base64-serializer]
  types/slate-base64-serializer/index.d.ts
  types/slate-base64-serializer/slate-base64-serializer-tests.ts
  types/slate-base64-serializer/tsconfig.json
  types/slate-base64-serializer/tslint.json
  types/slate-html-serializer/index.d.ts
  types/slate-html-serializer/slate-html-serializer-tests.ts
  types/slate-html-serializer/tsconfig.json
  types/slate-html-serializer/tslint.json
  types/slate-plain-serializer/index.d.ts
  types/slate-plain-serializer/slate-plain-serializer-tests.ts
  types/slate-plain-serializer/tsconfig.json
  types/slate-plain-serializer/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27088 Add types for socketio-jwt package. It may be unsupported, but it is still used.
  types/socketio-jwt/index.d.ts
  types/socketio-jwt/socketio-jwt-tests.ts
  types/socketio-jwt/tsconfig.json
  types/socketio-jwt/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#27099 Add typings for react-copy-write
  types/react-copy-write/index.d.ts
  types/react-copy-write/react-copy-write-tests.tsx
  types/react-copy-write/tsconfig.json
  types/react-copy-write/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27097 New definitions for [agora-rtc-sdk]
  types/agora-rtc-sdk/agora-rtc-sdk-tests.ts
  types/agora-rtc-sdk/index.d.ts
  types/agora-rtc-sdk/tsconfig.json
  types/agora-rtc-sdk/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27089 [arcgis-js-api] Update for version 4.8
  types/arcgis-js-api/index.d.ts
Labels: Merge:Express, Owner Approved

#27104 Add `cookiejar` types and improve `superagent`
  types/cookiejar/cookiejar-tests.ts
  types/cookiejar/index.d.ts
  types/cookiejar/tsconfig.json
  types/cookiejar/tslint.json
  types/superagent/index.d.ts
Labels: Awaiting reviewer feedback, New Definition, Popular package

#27107 [office-js] Adding links to conceptual Outlook topics in remarks
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27106 [generic-pool] Use void instead of undefined to represent lack of value.
  types/generic-pool/generic-pool-tests.ts
  types/generic-pool/index.d.ts
Labels: Merge:Express, Owner Approved

#27061 Fix @types/jest-each. It needs to export JestEach as default
  types/jest-each/index.d.ts
  types/jest-each/jest-each-tests.ts
Labels: Owner Approved, The Travis CI build failed

#27105 Fixed Bucket.combine method type in @types/google-cloud__storage
  types/google-cloud__storage/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#27098 Update [@types/bson] to match js-bson@1.0.6
  types/bson/bson-tests.ts
  types/bson/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27115 [office-js] Adding run<T> overload remarks
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27109 [got] Allow primitive types in JSON body for POST requests
  types/got/got-tests.ts
  types/got/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#27114 Lower atob required version to 2.1
  types/atob/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27134 Added a few missing tests for Jest
  types/jest/jest-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#27119 [materialize-css]Fix a typo in a monthsShort type
  types/materialize-css/common.d.ts
Labels: Merge:Express, Owner Approved

#27112 Update virtual-dom typings with constructors and type-guards
  types/virtual-dom/index.d.ts
  types/virtual-dom/virtual-dom-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved

#27124 fix(extend): improve signature of interface ExpectExtendMap
  types/jest/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27116 Modify three options missing from webpack-dev-middleware and webpack-hot-middleware
  types/webpack-dev-middleware/index.d.ts
  types/webpack-dev-middleware/webpack-dev-middleware-tests.ts
  types/webpack-hot-middleware/index.d.ts
  types/webpack-hot-middleware/webpack-hot-middleware-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#27131 lodash: fix pickBy for dictionary types
  types/lodash/common/object.d.ts
  types/lodash/fp.d.ts
  types/lodash/lodash-tests.ts
  types/lowdb/_lodash.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#27136 [react-native] - Update types based on new react-native 0.56 version
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Merge:Express, Owner Approved, Popular package

#27133 [highland] - 2.12.0 toNodeStream method
  types/highland/highland-tests.ts
  types/highland/index.d.ts
Labels: Merge:Express, Owner Approved

#27148 New package: react-native-toast-native
  types/react-native-toast-native/index.d.ts
  types/react-native-toast-native/react-native-toast-native-tests.tsx
  types/react-native-toast-native/tsconfig.json
  types/react-native-toast-native/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#27138 Add Types for swagger-ui-dist
  types/swagger-ui-dist/index.d.ts
  types/swagger-ui-dist/swagger-ui-dist-tests.ts
  types/swagger-ui-dist/tsconfig.json
  types/swagger-ui-dist/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26977 [redux-form] add typings for v7.4
  types/redux-form/immutable/index.d.ts
  types/redux-form/index.d.ts
  types/redux-form/lib/Field.d.ts
  types/redux-form/lib/Form.d.ts
  types/redux-form/lib/FormName.d.ts
  types/redux-form/lib/reducer.d.ts
  types/redux-form/lib/selectors.d.ts
  types/redux-form/package.json
  types/redux-form/redux-form-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26981 Update index.d.ts
  types/react-icon-base/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26991 @types/restify (7.2) : Add maxFileSize to BodyParserOptions interface
  types/restify/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27000 Added missing TextInput props on react-native-text-input-mask
  types/react-native-text-input-mask/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26995 Further restricted the generic type T
  types/throttle-debounce/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27011 Added alpha option to randomColor
  types/randomcolor/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27048 Add VictoryCursorContainer, VictoryBrushContainer, VictoryZoomContainer
  types/victory/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27017 [redux-form]: improve actions.initialize typing
  types/redux-form/lib/actions.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27121 Add definitions for promise-ftp, promise-ftp-common, and promise-sftp
  types/promise-ftp-common/index.d.ts
  types/promise-ftp-common/promise-ftp-common-tests.ts
  types/promise-ftp-common/tsconfig.json
  types/promise-ftp-common/tslint.json
  types/promise-ftp/index.d.ts
  types/promise-ftp/promise-ftp-tests.ts
  types/promise-ftp/tsconfig.json
  types/promise-ftp/tslint.json
  types/promise-sftp/index.d.ts
  types/promise-sftp/promise-sftp-tests.ts
  types/promise-sftp/tsconfig.json
  types/promise-sftp/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#27039 changes for v5 of react-tag-input
  types/react-tag-input/index.d.ts
  types/react-tag-input/react-tag-input-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#27126 Add definitions for node-dijkstra
  types/node-dijkstra/index.d.ts
  types/node-dijkstra/node-dijkstra-tests.ts
  types/node-dijkstra/tsconfig.json
  types/node-dijkstra/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#27047 [koa-bodyparser] export bodyParser.Options
  types/koa-bodyparser/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27149 Fix wrong return types in yesql pg and mysql functions
  types/yesql/index.d.ts
  types/yesql/yesql-tests.ts
Labels: Unowned

#27108 Added types for vue2-datepicker component
  types/vue2-datepicker/index.d.ts
  types/vue2-datepicker/package.json
  types/vue2-datepicker/tsconfig.json
  types/vue2-datepicker/tslint.json
  types/vue2-datepicker/vue2-datepicker-tests.ts
Labels: New Definition, Revision needed

#27153 chai-http: Add methods keepOpen() and close() to the agent
  types/chai-http/chai-http-tests.ts
  types/chai-http/index.d.ts
Labels: Merge:Express, Owner Approved

#27060 add missing searchTypeText property to react-select
  types/react-select/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#27069 [i18next] Fix dir() return type to be "ltr" | "rtl"
  types/i18next/index.d.ts
  types/i18next/v2/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27068 Mapbox popup className option
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#27171 [yargs] Add methods hide & showhidden
  types/yargs/index.d.ts
  types/yargs/yargs-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#27209 Cytoscape: animation fixes, layout interface usage
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#27196 office.js: add important note for auth.getaccesstokenasync
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#27157 [office-js] Adding conversationID descriptions to Message subclasses
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express
