Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2018-10, with the labels that each got.

#29213 Added 'gh-pages'.
  types/gh-pages/gh-pages-tests.ts
  types/gh-pages/index.d.ts
  types/gh-pages/tsconfig.json
  types/gh-pages/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#29264 fetch-mock: method option is never (but make it optional to keep compatibility)
  types/fetch-mock/fetch-mock-tests.ts
  types/fetch-mock/index.d.ts
Labels: Merge:Express, Owner Approved

#29250 Updates @types/rebass props, removes deprecated props
  types/rebass/index.d.ts
  types/rebass/rebass-tests.tsx
  types/rebass/tsconfig.json
Labels: Merge:LGTM, Other Approved, Unowned

#29036 [pigpio-dht] New types
  types/pigpio-dht/index.d.ts
  types/pigpio-dht/pigpio-dht-tests.ts
  types/pigpio-dht/tsconfig.json
  types/pigpio-dht/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#27878 Add type defintions for p5
  types/p5/constants.d.ts
  types/p5/global.d.ts
  types/p5/index.d.ts
  types/p5/lib/addons/p5.dom.d.ts
  types/p5/lib/addons/p5.sound.d.ts
  types/p5/literals.d.ts
  types/p5/src/color/creating_reading.d.ts
  types/p5/src/color/p5.Color.d.ts
  types/p5/src/color/setting.d.ts
  types/p5/src/core/constants.d.ts
  types/p5/src/core/environment.d.ts
  types/p5/src/core/p5.Element.d.ts
  types/p5/src/core/p5.Graphics.d.ts
  types/p5/src/core/p5.Renderer.d.ts
  types/p5/src/core/rendering.d.ts
  types/p5/src/core/shape/2d_primitives.d.ts
  types/p5/src/core/shape/attributes.d.ts
  types/p5/src/core/shape/curves.d.ts
  types/p5/src/core/shape/vertex.d.ts
  types/p5/src/core/structure.d.ts
  types/p5/src/core/transform.d.ts
  types/p5/src/data/p5.TypedDict.d.ts
  types/p5/src/events/acceleration.d.ts
  types/p5/src/events/keyboard.d.ts
  types/p5/src/events/mouse.d.ts
  types/p5/src/events/touch.d.ts
  types/p5/src/image/image.d.ts
  types/p5/src/image/loading_displaying.d.ts
  types/p5/src/image/p5.Image.d.ts
  types/p5/src/image/pixels.d.ts
  types/p5/src/io/files.d.ts
  types/p5/src/io/p5.Table.d.ts
  types/p5/src/io/p5.TableRow.d.ts
  types/p5/src/io/p5.XML.d.ts
  types/p5/src/math/calculation.d.ts
  types/p5/src/math/math.d.ts
  types/p5/src/math/noise.d.ts
  types/p5/src/math/p5.Vector.d.ts
  types/p5/src/math/random.d.ts
  types/p5/src/math/trigonometry.d.ts
  types/p5/src/typography/attributes.d.ts
  types/p5/src/typography/loading_displaying.d.ts
  types/p5/src/typography/p5.Font.d.ts
  types/p5/src/utilities/array_functions.d.ts
  types/p5/src/utilities/conversion.d.ts
  types/p5/src/utilities/string_functions.d.ts
  types/p5/src/utilities/time_date.d.ts
  types/p5/src/webgl/3d_primitives.d.ts
  types/p5/src/webgl/interaction.d.ts
  types/p5/src/webgl/light.d.ts
  types/p5/src/webgl/loading.d.ts
  types/p5/src/webgl/material.d.ts
  types/p5/src/webgl/p5.Camera.d.ts
  types/p5/src/webgl/p5.Geometry.d.ts
  types/p5/src/webgl/p5.RendererGL.d.ts
  types/p5/src/webgl/p5.Shader.d.ts
  types/p5/test/index.ts
  types/p5/tsconfig.json
  types/p5/tslint.json
Labels: New Definition, Revision needed

#29348 feat(bell): stricter types
  types/bell/bell-tests.ts
  types/bell/index.d.ts
Labels: Author is Owner, Merge:Express

#29341 [ember-data] Move registry mapping types into their own ghost modules
  types/ember-data/adapter.d.ts
  types/ember-data/index.d.ts
  types/ember-data/model.d.ts
  types/ember-data/serializer.d.ts
  types/ember-data/test/adapter.ts
  types/ember-data/test/belongs-to.ts
  types/ember-data/test/has-many.ts
  types/ember-data/test/injections.ts
  types/ember-data/test/record-reference.ts
  types/ember-data/test/relationships.ts
  types/ember-data/test/serializer.ts
  types/ember-data/test/store.ts
  types/ember-data/tsconfig.json
  types/ember-data/types/registries/adapter.d.ts
  types/ember-data/types/registries/model.d.ts
  types/ember-data/types/registries/serializer.d.ts
  types/ember-data/types/registries/transform.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29295 [jquery] Add examples documentation.
  types/jquery/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29293 react-big-calendar: Update declarations for 0.20.0
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29286 [jquery] `trigger`/`triggerHandler` accept boolean values for `extraParameters`.
  types/jquery/index.d.ts
  types/jquery/jquery-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29279 marked: Add `start` to `list` definition
  types/marked/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29331 react-native - Added allowFileAccess property for Android WebView
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Merge:Express, Owner Approved, Popular package

#29340 quill: use quill-delta shipped types
  types/quill/index.d.ts
  types/quill/package.json
  types/quill/quill-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29337 fix(ember__error): make EmberError extendable
  types/ember/index.d.ts
  types/ember__error/ember__error-tests.ts
  types/ember__error/index.d.ts
Labels: Merge:Express, Owner Approved

#29325 Jasmine Type safe method names list on a generic for CreateSpyObj
  types/frisby/v0/index.d.ts
  types/gulp-jasmine/index.d.ts
  types/jasmine-ajax/index.d.ts
  types/jasmine-data_driven_tests/index.d.ts
  types/jasmine-es6-promise-matchers/index.d.ts
  types/jasmine-matchers/index.d.ts
  types/jasmine-node/index.d.ts
  types/jasmine-promise-matchers/index.d.ts
  types/jasmine/index.d.ts
  types/jasminewd2/index.d.ts
  types/karma-jasmine/index.d.ts
  types/saywhen/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29336 Update bcrypt version
  types/bcrypt/index.d.ts
Labels: Merge:Express, Owner Approved

#29330 Update types for lingui__react
  types/lingui__react/I18n.d.ts
  types/lingui__react/index.d.ts
  types/lingui__react/lingui__react-tests.tsx
Labels: Merge:Express, Owner Approved

#29135 feat(puppeteer): update 1.8 and improve typings
  types/puppeteer/Errors.d.ts
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
  types/puppeteer/tsconfig.json
Labels: Merge:Express, Owner Approved

#29159 [cote] add error argument to responder on callback for cote package
  types/cote/cote-tests.ts
  types/cote/index.d.ts
Labels: Merge:Express, Owner Approved

#29305 `mjml` - incorrect type for `filePath` option
  types/mjml/index.d.ts
  types/mjml/mjml-tests.ts
Labels: Merge:Express, Owner Approved

#29306 Remove SpyInstance
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29294 chore(hapi): narrow types for credentials
  types/hapi/index.d.ts
  types/hapi/test/request/auth.ts
  types/hapi/test/server/server-auth-api.ts
  types/hapi/test/server/server-auth-default.ts
  types/hapi/test/server/server-auth-test.ts
  types/hapi/tsconfig.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29288 [react-spinkit] Allow passing inline styles
  types/react-spinkit/index.d.ts
  types/react-spinkit/react-spinkit-tests.tsx
Labels: Merge:Express, Owner Approved

#29292 Ramda: compose/pipe should accept last/first function that takes no params
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29251 Add attributes to response class (in selenium-webdriver)
  types/selenium-webdriver/http.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29166 Improve declaration file for "react-input-mask"
  types/react-input-mask/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29290 mithril: Fix doc comments
  types/mithril/index.d.ts
Labels: Merge:Express, Owner Approved

#29261 svg: Add missing SvgCommonProps "transform"
  types/expo/expo-tests.tsx
  types/expo/index.d.ts
Labels: Merge:Express, Owner Approved

#29245 [mongodb] Checked TSchema on insert and update documents
  types/mongodb/index.d.ts
  types/mongodb/mongodb-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29241 react-map-gl - Make mapboxApiAccessToken prop optional
  types/react-map-gl/index.d.ts
Labels: Merge:Express, Owner Approved

#29276 Fix react-map-gl props typo
  types/react-map-gl/index.d.ts
Labels: Merge:Express, Owner Approved

#29297 Added type definitions for aos
  types/aos/aos-tests.ts
  types/aos/global.d.ts
  types/aos/index.d.ts
  types/aos/tsconfig.json
  types/aos/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29277 Correct `onRuntimeError` to take error, not string
  types/office-runtime/index.d.ts
  types/office-runtime/office-runtime-tests.ts
Labels: Unowned

#29142 Update mapbox types to v0.49.0 and fix some types
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29150 [chroma-js] updates types to v1.4.0
  types/chroma-js/chroma-js-tests.ts
  types/chroma-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29291 Added type definitions for npm 'webprogbase-console-view' library.
  types/webprogbase-console-view/index.d.ts
  types/webprogbase-console-view/tsconfig.json
  types/webprogbase-console-view/tslint.json
  types/webprogbase-console-view/webprogbase-console-view-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#29289 Added type definition for react-lottie
  types/react-lottie/index.d.ts
  types/react-lottie/react-lottie-tests.tsx
  types/react-lottie/tsconfig.json
  types/react-lottie/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#29285 Added type definitions for ali-oss
  types/ali-oss/Cluster.d.ts
  types/ali-oss/ImageClient.d.ts
  types/ali-oss/ali-oss-tests.ts
  types/ali-oss/index.d.ts
  types/ali-oss/tsconfig.json
  types/ali-oss/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#29171 Adds alternative client side collection to meteor-publish-composite
  types/meteor-publish-composite/index.d.ts
  types/meteor-publish-composite/meteor-publish-composite-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29180 Add content property in AutocompleteUIParams in type jqueryui
  types/jqueryui/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29210 Fix bad return type in lazyJS ObjectLikeSequence.get()
  types/lazy.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29209 react-highlight-words - update props definition, specifically findChunks prop
  types/react-highlight-words/index.d.ts
  types/react-highlight-words/react-highlight-words-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#29368 [react-router-v3] Fix createHref & createPath argument
  types/react-router/v3/index.d.ts
  types/react-router/v3/lib/Router.d.ts
  types/react-router/v3/react-router-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#29173 node: Export Http2ServerRequest and Http2ServerResponse as class
  types/node/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Owner Approved, Popular package, Revision needed

#29365 [@types/react-onsenui] Add SearchInput component
  types/react-onsenui/index.d.ts
  types/react-onsenui/react-onsenui-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved

#29363 Adding missing width option to QRCodeRenderersOptions for qrcode
  types/qrcode/index.d.ts
Labels: Merge:Express, Owner Approved

#29351 Changing install signatures from yeoman-generator@3.0.0
  types/yeoman-generator/index.d.ts
  types/yeoman-generator/yeoman-generator-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#29329 Add resolvesArg to sinon typings
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#29303 ssh2-sftp-client: Edit definition. add for "on" function.
  types/ssh2-sftp-client/index.d.ts
  types/ssh2-sftp-client/ssh2-sftp-client-tests.ts
Labels: Merge:Express, Owner Approved

#29354 Allow false as cache group value
  types/webpack/index.d.ts
  types/webpack/webpack-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29372 Added type definitions for layzr.js
  types/layzr.js/index.d.ts
  types/layzr.js/layzr.js-tests.ts
  types/layzr.js/tsconfig.json
  types/layzr.js/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29373 Add type definitions for tiny-async-pool
  types/tiny-async-pool/index.d.ts
  types/tiny-async-pool/tiny-async-pool-tests.ts
  types/tiny-async-pool/tsconfig.json
  types/tiny-async-pool/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29366 Added type definitions for rellax.
  types/rellax/index.d.ts
  types/rellax/rellax-tests.ts
  types/rellax/tsconfig.json
  types/rellax/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29362 Added type definitions for moveto
  types/moveto/index.d.ts
  types/moveto/moveto-tests.ts
  types/moveto/tsconfig.json
  types/moveto/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29356 Add typings for `init-package-json`
  types/init-package-json/index.d.ts
  types/init-package-json/init-package-json-tests.ts
  types/init-package-json/tsconfig.json
  types/init-package-json/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29358 Add typings for react-timeago package
  types/react-timeago/index.d.ts
  types/react-timeago/react-timeago-tests.tsx
  types/react-timeago/tsconfig.json
  types/react-timeago/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29283 Added type definitions for passport-auth0
  types/passport-auth0/index.d.ts
  types/passport-auth0/passport-auth0-tests.ts
  types/passport-auth0/tsconfig.json
  types/passport-auth0/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#28592 ramda: Workaround for type inference problem in Filter
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Popular package, Revision needed

#29381 [jquery] Drop type guards from isNumeric()/isPlainObject() and improve declarations of jQuery.data()/.data()/jQuery.css()
  types/jquery/index.d.ts
  types/jquery/jquery-tests.ts
  types/jquery/test/longdesc-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29370 [react-daterange-picker] Fix onSelect prop type definitions
  types/react-daterange-picker/index.d.ts
  types/react-daterange-picker/react-daterange-picker-tests.tsx
Labels: Merge:Express, Owner Approved

#29188 Add types for browserify/commonjs-assert
  types/assert/assert-tests.ts
  types/assert/index.d.ts
  types/assert/tsconfig.json
  types/assert/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29235 Fix wrong optional `ChangeEvent` parameter for `InputProps.onChange`
  types/react-autosuggest/index.d.ts
  types/react-autosuggest/react-autosuggest-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#29382 fix engineVersion result type and closes #28133 and closes #27984
  types/qlik-engineapi/index.d.ts
Labels: Author is Owner, Merge:Express

#29379 Rename grid-styled to @rebass/grid, update to v6
  types/grid-styled/package.json
  types/rebass__grid/index.d.ts
  types/rebass__grid/rebass__grid-tests.tsx
  types/rebass__grid/tsconfig.json
  types/rebass__grid/tslint.json
Labels: Merge:Express, Owner Approved

#29237 Fix Annotations - should be array
  types/highcharts/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29271 Making some updates to comments in office-runtime and custom-functions-runtime
  types/custom-functions-runtime/custom-functions-runtime-tests.ts
  types/custom-functions-runtime/index.d.ts
  types/office-runtime/index.d.ts
Labels: Unowned

#29391 fix(node): revert remaining common var to const globals
  types/node/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29375 Add typings for node-crate
  types/node-crate/index.d.ts
  types/node-crate/node-crate-tests.ts
  types/node-crate/tsconfig.json
  types/node-crate/tslint.json
Labels: New Definition, Revision needed

#29401 Webpack: Adds maxSize as option to CacheGroupsOptions and SplitChunksOptions
  types/webpack/index.d.ts
  types/webpack/webpack-tests.ts
Labels: Awaiting reviewer feedback, Popular package

#29390 Enhance typings of easy-table
  types/easy-table/easy-table-tests.ts
  types/easy-table/index.d.ts
Labels: Author is Owner, Merge:Express

#29335 Fix @types/react-test-renderer typings on ReactTestIntance type typing
  types/react-test-renderer/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29387 fix(node): stdio streams can have more than three items
  types/node/v4/index.d.ts
  types/node/v6/index.d.ts
  types/node/v7/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29398 @types/mongoose add missing options to connect(), fixes #29136
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29152 Typings_Three_Core_LineDashedMaterial_Update
  types/three/three-core.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#29385 Added no-argument overload for Model.previous
  types/sequelize/index.d.ts
  types/sequelize/sequelize-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29257 @types/react-native-push-notification: Add missing permissions type on push notification options
  types/react-native-push-notification/index.d.ts
  types/react-native-push-notification/react-native-push-notification-tests.ts
Labels: Merge:Express, Owner Approved

#29282 [jquery] Change all `HTMLElement` to be `Element`
  types/jquery/v2/index.d.ts
  types/jquery/v2/jquery-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#29338 Update MeshBasicMaterial type definition in @types/three-core
  types/three/three-core.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29367 fix(ember-data): update value types for BelongsToReference, HasManyReference
  types/ember-data/index.d.ts
  types/ember-data/test/belongs-to.ts
  types/ember-data/test/has-many.ts
Labels: Merge:Express, Owner Approved, Revision needed

#29388 Add Google Advanced Service Types – Google Slides
  types/google-apps-script/apis/admin/directory_v1.d.ts
  types/google-apps-script/apis/admin/reports_v1.d.ts
  types/google-apps-script/apis/adsense/v1.4.d.ts
  types/google-apps-script/apis/analytics/v3.d.ts
  types/google-apps-script/apis/analyticsreporting/v4.d.ts
  types/google-apps-script/apis/appsactivity/v1.d.ts
  types/google-apps-script/apis/bigquery/v2.d.ts
  types/google-apps-script/apis/calendar/v3.d.ts
  types/google-apps-script/apis/classroom/v1.d.ts
  types/google-apps-script/apis/content/v2.d.ts
  types/google-apps-script/apis/dfareporting/v2.8.d.ts
  types/google-apps-script/apis/dfareporting/v3.0.d.ts
  types/google-apps-script/apis/dfareporting/v3.1.d.ts
  types/google-apps-script/apis/dfareporting/v3.2.d.ts
  types/google-apps-script/apis/drive/v2.d.ts
  types/google-apps-script/apis/fusiontables/v1.d.ts
  types/google-apps-script/apis/fusiontables/v2.d.ts
  types/google-apps-script/apis/gmail/v1.d.ts
  types/google-apps-script/apis/groupsmigration/v1.d.ts
  types/google-apps-script/apis/groupssettings/v1.d.ts
  types/google-apps-script/apis/licensing/v1.d.ts
  types/google-apps-script/apis/mirror/v1.d.ts
  types/google-apps-script/apis/plus/v1.d.ts
  types/google-apps-script/apis/plusDomains/v1.d.ts
  types/google-apps-script/apis/reseller/v1.d.ts
  types/google-apps-script/apis/sheets/v4.d.ts
  types/google-apps-script/apis/slides/v1.d.ts
  types/google-apps-script/apis/tagmanager/v1.d.ts
  types/google-apps-script/apis/tasks/v1.d.ts
  types/google-apps-script/apis/urlshortener/v1.d.ts
  types/google-apps-script/apis/youtube/v3.d.ts
  types/google-apps-script/apis/youtubeAnalytics/v1.d.ts
  types/google-apps-script/apis/youtubePartner/v1.d.ts
  types/google-apps-script/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29423 Describe methods for date-arithmetic package
  types/date-arithmetic/date-arithmetic-tests.ts
  types/date-arithmetic/index.d.ts
Labels: Author is Owner, Merge:Express

#29421 office-js: Update max for RoamingSettings
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#29404 Fixes #28026 by adding not found names to index.d.ts
  types/text-encoding/index.d.ts
Labels: Merge:Express, Owner Approved

#29376 Update Google Pay types (@types/googlepay)
  types/googlepay/googlepay-tests.ts
  types/googlepay/index.d.ts
Labels: Merge:Express, Owner Approved

#29114 [recompose] Improve type inference of static property helpers
  types/recompose/index.d.ts
  types/recompose/recompose-tests.tsx
Labels: Popular package, Revision needed

#29120 16.3.21 added
  types/ej.web.all/index.d.ts
Labels: Revision needed

#29269 [debug] Added 'extend' function definition to debug.IDebugger.
  types/debug/debug-tests.ts
  types/debug/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29424 [@types/proton-native] Fix Type RadioButtonProps and GridChildrenProps
  types/proton-native/index.d.ts
  types/proton-native/test/index.tsx
Labels: Merge:Express, Owner Approved

#29405 koa-joi-router: add prefix() to Router interface
  types/koa-joi-router/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#29431 [RFR] Fix Feathers Authentication Local (feathersjs__authentication-local) hook definition
  types/feathersjs__authentication-local/index.d.ts
Labels: Merge:Express, Owner Approved

#29284 fix(stripe): InvoiceItem.invoice can be null
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved

#29281 unzipper: autodrain promise
  types/unzipper/index.d.ts
  types/unzipper/unzipper-tests.ts
Labels: Merge:Express, Owner Approved

#29442 [ioredis] add types for exists
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
  types/ioredis/v3/index.d.ts
  types/ioredis/v3/ioredis-tests.ts
Labels: Merge:Express, Owner Approved

#29441 Add null in response if no results are found
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Merge:Express, Owner Approved

#29440 [ioredis] fix type of del result
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Merge:Express, Owner Approved

#29439 Add typings for the existing connect-datadog package
  types/connect-datadog/connect-datadog-tests.ts
  types/connect-datadog/index.d.ts
  types/connect-datadog/tsconfig.json
  types/connect-datadog/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29425 [@types/passport-auth0] : Updated StrategyOption to include "domain" variable
  types/passport-auth0/index.d.ts
  types/passport-auth0/passport-auth0-tests.ts
Labels: Unowned

#29418 Updates to field typing
  types/apostrophe/index.d.ts
Labels: Unowned

#29407 Changed type for border prop on button and Card. Bool => Number
  types/rebass/index.d.ts
Labels: Unowned

#29402 Add typings for react-facebook-login-component package
  types/react-facebook-login-component/index.d.ts
  types/react-facebook-login-component/react-facebook-login-component-tests.tsx
  types/react-facebook-login-component/tsconfig.json
  types/react-facebook-login-component/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#29252 @types/knex - Fix join callback argument for on, andOn, orOn
  types/knex/index.d.ts
  types/knex/knex-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29268 For chart.js, add stepSize to TickOptions
  types/chart.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29406 typedefinition for Caller
  types/caller/caller-tests.ts
  types/caller/index.d.ts
  types/caller/tsconfig.json
  types/caller/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#29287 Bootstrap v3: Update type definition
  types/bootstrap/v3/bootstrap-tests.ts
  types/bootstrap/v3/index.d.ts
  types/bootstrap/v3/tsconfig.json
  types/bootstrap/v3/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29446 Add definition for fabric Group.toActiveSelection
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29432 [screeps] Release 2.5.0
  types/screeps/index.d.ts
  types/screeps/screeps-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved

#29400 Changing arg from vec3 -> vec2 for mat3.translate in package gl-matrix.
  types/gl-matrix/gl-matrix-tests.ts
  types/gl-matrix/index.d.ts
Labels: Merge:Express, Owner Approved

#29132 [parse] Added fullText function to Parse.Query
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Owner Approved, Revision needed

#29448 [React] Add align attribute to Td and Th
  types/react/index.d.ts
Labels: Awaiting reviewer feedback, Other Approved, Popular package

#29454 office-js: Update project name
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#29453 custom-functions-runtime: Update project name
  types/custom-functions-runtime/index.d.ts
Labels: Unowned

#29455 office-runtime: Update project name
  types/office-runtime/index.d.ts
Labels: Unowned

#29205 Add new typings for keycloak-connect and express-ws-routes
  types/express-ws-routes/express-ws-routes-tests.ts
  types/express-ws-routes/index.d.ts
  types/express-ws-routes/tsconfig.json
  types/express-ws-routes/tslint.json
  types/keycloak-connect/index.d.ts
  types/keycloak-connect/keycloak-connect-tests.ts
  types/keycloak-connect/tsconfig.json
  types/keycloak-connect/tslint.json
Labels: New Definition, Revision needed

#29451 [ioredis] improve scan() function types
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29465 @types/next/document Add await to document.d.ts
  types/next/document.d.ts
Labels: Merge:Express, Owner Approved

#29456 feat(puppeteer): update to 1.9
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29469 sinon: Add spy.named() and stub.named()
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#29464 hls.js Fix typo for startFragPrefetch config
  types/hls.js/hls.js-tests.ts
  types/hls.js/index.d.ts
Labels: Merge:Express, Owner Approved

#29475 Add `in()`, `out()` & `command()` definitions for gm package
  types/gm/gm-tests.ts
  types/gm/index.d.ts
Labels: Merge:Express, Owner Approved

#29471 Add type definitions for airbnb/react-outside-click-handler
  types/react-outside-click-handler/index.d.ts
  types/react-outside-click-handler/test/react-outside-click-handler-tests.tsx
  types/react-outside-click-handler/tsconfig.json
  types/react-outside-click-handler/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29467 Add typings for react-google-login-component
  types/react-google-login-component/index.d.ts
  types/react-google-login-component/react-google-login-component-tests.tsx
  types/react-google-login-component/tsconfig.json
  types/react-google-login-component/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29458 Remove not-supported `OfficeRuntime.AsyncStorage.clear()` method
  types/office-runtime/index.d.ts
  types/office-runtime/office-runtime-tests.ts
Labels: Unowned

#29457 Create koa-ratelimit definition
  types/koa-ratelimit/index.d.ts
  types/koa-ratelimit/koa-ratelimit-tests.ts
  types/koa-ratelimit/tsconfig.json
  types/koa-ratelimit/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29479 [auth0-js] Add login_hint value in AuthorizeOptions
  types/auth0-js/auth0-js-tests.ts
  types/auth0-js/index.d.ts
Labels: Merge:Express, Owner Approved

#29484 Add styled-react-modal types
  types/styled-react-modal/index.d.ts
  types/styled-react-modal/styled-react-modal-tests.tsx
  types/styled-react-modal/tsconfig.json
  types/styled-react-modal/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29397 Add types for react-native-scaled-image
  types/react-native-scaled-image/index.d.ts
  types/react-native-scaled-image/react-native-scaled-image-tests.tsx
  types/react-native-scaled-image/tsconfig.json
  types/react-native-scaled-image/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29298 Updated react-onclickoutside typings (config object, better SFC support)
  types/react-onclickoutside/index.d.ts
  types/react-onclickoutside/react-onclickoutside-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#29299 grunt - fix grunt.file.expand errors
  types/grunt/grunt-tests.ts
  types/grunt/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29300 Add missing Luxon DateTime isInLeapYear getter
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29208 react-navigation: Updated withNavigation HOC for prop requirements
  types/react-navigation/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29503 [jquery][sizzle] Add detailed deprecation notices and `jQuery.nodeName()`, `jQuery.expr`, and `jQuery.easing`.
  types/jquery/index.d.ts
  types/jquery/jquery-tests.ts
  types/sizzle/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29302 Added type definitions for Parcel bundler
  types/parcel-bundler/index.d.ts
  types/parcel-bundler/parcel-bundler-tests.ts
  types/parcel-bundler/tsconfig.json
  types/parcel-bundler/tslint.json
Labels: New Definition, Revision needed, The Travis CI build failed

#29516 react: remove `string | number` in type ReactNode
  types/react/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#29537 React-native: SwitchProps updates to match source code
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Merge:Express, Owner Approved, Popular package

#29534 Add typings for react-sticky-box package
  types/react-sticky-box/index.d.ts
  types/react-sticky-box/react-sticky-box-tests.tsx
  types/react-sticky-box/tsconfig.json
  types/react-sticky-box/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29520 [jquery] Copied event properties are writable.
  types/jquery/index.d.ts
  types/jquery/jquery-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29514 i18next: Fix `FormatFunction`'s value type
  types/i18next/i18next-tests.ts
  types/i18next/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29507 Adding types for "react-window-size"
  types/react-window-size/index.d.ts
  types/react-window-size/react-window-size-tests.tsx
  types/react-window-size/tsconfig.json
  types/react-window-size/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#29508 [jest] Restore SpyInstance interface
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#29509 [a11y-dialog] Create new definitions
  types/a11y-dialog/a11y-dialog-tests.ts
  types/a11y-dialog/index.d.ts
  types/a11y-dialog/tsconfig.json
  types/a11y-dialog/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#29511 Fix wu.enumerate() definition error in 'wu' package
  types/wu/index.d.ts
Labels: Merge:Express, Owner Approved

#29505 Creating new definitions for "md5-file"
  types/md5-file/index.d.ts
  types/md5-file/md5-file-tests.ts
  types/md5-file/tsconfig.json
  types/md5-file/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Where is Travis?

#29499 [loopback] Declare that Role model extends PersistedModel
  types/loopback/index.d.ts
Labels: Merge:Express, Owner Approved

#29496 Adding types for passport-azure-ad strategy
  types/passport-azure-ad/bearer-strategy.d.ts
  types/passport-azure-ad/common.d.ts
  types/passport-azure-ad/index.d.ts
  types/passport-azure-ad/oidc-strategy.d.ts
  types/passport-azure-ad/passport-azure-ad-tests.ts
  types/passport-azure-ad/tsconfig.json
  types/passport-azure-ad/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#29495 web3: fixes for web3.eth.accounts types and methods, added missing methods
  types/web3/eth/accounts.d.ts
  types/web3/web3-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29492 allow GraphQLNonNull usage with and without new
  types/graphql/index.d.ts
  types/graphql/type/definition.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29490 office-js: Update project name
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29491 office-runtime: Update project name
  types/office-runtime/index.d.ts
Labels: Unowned

#29487 Add resolves this to sinon stub
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#29486 [auth0-lock] add Auth0LockConstructorOptions.allowAutocomplete
  types/auth0-lock/auth0-lock-tests.ts
  types/auth0-lock/index.d.ts
Labels: Merge:Express, Owner Approved
