Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2018-11, with the labels that each got.

#30103 add string-replace-webpack-plugin types
  types/string-replace-webpack-plugin/index.d.ts
  types/string-replace-webpack-plugin/string-replace-webpack-plugin-tests.ts
  types/string-replace-webpack-plugin/tsconfig.json
  types/string-replace-webpack-plugin/tslint.json
Labels: New Definition, Revision needed

#30124 Add makeup-floating-label definitions
  types/makeup-floating-label/index.d.ts
  types/makeup-floating-label/makeup-floating-label-tests.ts
  types/makeup-floating-label/tsconfig.json
  types/makeup-floating-label/tslint.json
Labels: New Definition, Revision needed

#30127 [detective] Add detective@5.1.0 definition
  types/detective/detective-tests.ts
  types/detective/index.d.ts
  types/detective/tsconfig.json
  types/detective/tslint.json
Labels: New Definition, Revision needed

#30112 Add Type Declarations for Tern
  types/tern/index.d.ts
  types/tern/lib/infer/index.d.ts
  types/tern/lib/tern/index.d.ts
  types/tern/test/tern.test.ts
  types/tern/tsconfig.json
  types/tern/tslint.json
Labels: New Definition, Revision needed

#30050 Fixed callback datatypes for Office.Body.getAsync() and Office.Appoint…
  types/office-js/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#30184 Update raygun4js typings
  types/raygun4js/index.d.ts
  types/raygun4js/raygun4js-tests.ts
  types/raygun4js/tslint.json
Labels: Merge:Express, Owner Approved

#30182 [@types/vimeo__player] Allow VimeoCuePointData to be any form of object
  types/vimeo__player/index.d.ts
Labels: Merge:Express, Owner Approved

#30174 Updating npm-package-arg to better reflect code
  types/npm-package-arg/index.d.ts
Labels: Merge:Express, Owner Approved

#30173 [autobahn] fix Connection
  types/autobahn/index.d.ts
Labels: Merge:Express, Owner Approved

#30167 react-stripe-elements - Allows for inaccessible types inside of index.d.ts to be accessed from other files.
  types/react-stripe-elements/index.d.ts
Labels: Merge:Express, Owner Approved

#30142 Yup compact rejector is optional
  types/yup/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#29842 mapbox-gl: Add missing member
  types/mapbox-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29838 Added detailed type definitions for bpampuch/pdfmake
  types/pdfmake/index.d.ts
  types/pdfmake/pdfmake-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29839 [@types/auth0] Add missing optional parameters for 'Get all clients'
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29884 Highcharts - Added definition for rangeSelector* properties
  types/highcharts/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29873 adds prop "state" to passport AuthenticateOptions
  types/passport-github2/index.d.ts
  types/passport/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30180 Add types for "raygun" package
  types/raygun/index.d.ts
  types/raygun/raygun-tests.ts
  types/raygun/tsconfig.json
  types/raygun/tslint.json
Labels: New Definition, Revision needed

#29921 Add static property 'accessile' to onoff.Gpio class in types/onoff
  types/onoff/index.d.ts
  types/onoff/onoff-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30028 add types for on-wake-up
  types/on-wake-up/index.d.ts
  types/on-wake-up/on-wake-up-tests.ts
  types/on-wake-up/tsconfig.json
  types/on-wake-up/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#30039 update codeTagProps and lineProps for react-syntax-highlighter
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#30045 consul: Add near parameter to ServiceOptions
  types/consul/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30081 [@types/ip] fixed definition for "toBuffer"
  types/ip/index.d.ts
  types/ip/ip-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30079 [@types/react-native-google-signin] Add iosClientId to ConfigureParams
  types/react-native-google-signin/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30094 Add open() method to $mdMenu service
  types/angular-material/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30075 src: update opossum to have volumeThreshold
  types/opossum/index.d.ts
  types/opossum/opossum-tests.ts
Labels: Merge:YSYL, Unowned

#30025 Created jsonquery typings
  types/jsonquery/index.d.ts
  types/jsonquery/jsonquery-tests.ts
  types/jsonquery/tsconfig.json
  types/jsonquery/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#30062 Changed executeSync `params` parameter to optional Closes: #29844
  types/ibm_db/ibm_db-tests.ts
  types/ibm_db/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30063 [@types/paypal-rest-sdk] fix related_resources type in transactions
  types/paypal-rest-sdk/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#29905 Update types for p-wait-for to v2.0
  types/p-wait-for/index.d.ts
  types/p-wait-for/p-wait-for-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30003 wavesurfer.js: Fix order of arguments
  types/wavesurfer.js/index.d.ts
  types/wavesurfer.js/wavesurfer.js-tests.ts
Labels: Merge:YSYL, Unowned

#30017 Add widgetType and titleField to Field
  types/apostrophe/index.d.ts
Labels: Merge:YSYL, Unowned

#29974 Update index.d.ts
  types/node-forge/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29948 Add typings for node-gamepad
  types/node-gamepad/index.d.ts
  types/node-gamepad/node-gamepad-tests.ts
  types/node-gamepad/tsconfig.json
  types/node-gamepad/tslint.json
Labels: New Definition, Revision needed

#30162 Add definitions for just-debounce-it
  types/just-debounce-it/index.d.ts
  types/just-debounce-it/just-debounce-it-tests.ts
  types/just-debounce-it/tsconfig.json
  types/just-debounce-it/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30183 Types for JQuery FormatDateTime
  types/jquery-formatdatetime/index.d.ts
  types/jquery-formatdatetime/jquery-formatdatetime-tests.ts
  types/jquery-formatdatetime/tsconfig.json
  types/jquery-formatdatetime/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30185 Adding hosted-git-info
  types/hosted-git-info/hosted-git-info-tests.ts
  types/hosted-git-info/index.d.ts
  types/hosted-git-info/tsconfig.json
  types/hosted-git-info/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#30171 [postcss-calc] Add Typescript definitions.
  types/postcss-calc/index.d.ts
  types/postcss-calc/package.json
  types/postcss-calc/postcss-calc-tests.ts
  types/postcss-calc/tsconfig.json
  types/postcss-calc/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30154 Add declarations for chordsheetjs
  types/chordsheetjs/chordsheetjs-tests.ts
  types/chordsheetjs/index.d.ts
  types/chordsheetjs/tsconfig.json
  types/chordsheetjs/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29959 add ascii-art definitions
  types/ascii-art/ascii-art-tests.ts
  types/ascii-art/index.d.ts
  types/ascii-art/tsconfig.json
  types/ascii-art/tslint.json
Labels: New Definition, Revision needed

#29704 Add types for the Serverless Framework
  types/serverless/classes/Plugin.d.ts
  types/serverless/classes/PluginManager.d.ts
  types/serverless/classes/Service.d.ts
  types/serverless/classes/Utils.d.ts
  types/serverless/classes/YamlParser.d.ts
  types/serverless/index.d.ts
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
  types/serverless/tsconfig.json
  types/serverless/tslint.json
Labels: New Definition, Revision needed

#29782 Adding types for graphlib-dot
  types/graphlib-dot/index.d.ts
  types/graphlib-dot/test/graphlib-dot-global-tests.ts
  types/graphlib-dot/test/graphlib-dot-tests.ts
  types/graphlib-dot/tsconfig.json
  types/graphlib-dot/tslint.json
Labels: New Definition, Revision needed

#29793 react-instantsearch
  types/react-instantsearch-core/index.d.ts
  types/react-instantsearch-core/react-instantsearch-core-tests.tsx
  types/react-instantsearch-core/tsconfig.json
  types/react-instantsearch-core/tslint.json
  types/react-instantsearch-dom/index.d.ts
  types/react-instantsearch-dom/react-instantsearch-dom-tests.tsx
  types/react-instantsearch-dom/tsconfig.json
  types/react-instantsearch-dom/tslint.json
  types/react-instantsearch-native/index.d.ts
  types/react-instantsearch-native/react-instantsearch-native-tests.tsx
  types/react-instantsearch-native/tsconfig.json
  types/react-instantsearch-native/tslint.json
  types/react-instantsearch/connectors.d.ts
  types/react-instantsearch/dom.d.ts
  types/react-instantsearch/index.d.ts
  types/react-instantsearch/native.d.ts
  types/react-instantsearch/react-instantsearch-tests.tsx
  types/react-instantsearch/tsconfig.json
  types/react-instantsearch/tslint.json
Labels: New Definition, Revision needed

#30175 [Leaflet] GeoJSON setStyle method accepts styler functions
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#30216 [office-js] Standardizing array notation
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#30034 [@types/aphrodite] Fixes undefined index type error
  types/aphrodite/index.d.ts
Labels: Awaiting reviewer feedback, Other Approved

#29908 [jsonwebtoken] Allow function as secretOrPublicKey argument for async verify
  types/jsonwebtoken/index.d.ts
  types/jsonwebtoken/jsonwebtoken-tests.ts
  types/jsonwebtoken/tslint.json
Labels: Owner Approved, Popular package, Revision needed

#30130 fix `TransactionReceipt.status`
  types/web3/index.d.ts
  types/web3/tslint.json
  types/web3/types.d.ts
  types/web3/web3-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#29941 Added definitions for crpc
  types/crpc/crpc-tests.ts
  types/crpc/index.d.ts
  types/crpc/tsconfig.json
  types/crpc/tslint.json
Labels: Abandoned, New Definition, The Travis CI build failed

#30156 [weixin-app] Fix wx.getStorageInfoSync return type
  types/weixin-app/index.d.ts
Labels: Merge:Express, Owner Approved

#30086 @types/cli-table2 fixed header parameter types
  types/cli-table2/cli-table2-tests.ts
  types/cli-table2/index.d.ts
Labels: Merge:Express, Owner Approved

#30018 [plotly.js] add box, heatmap, and histogram fields to PlotData
  types/plotly.js/index.d.ts
Labels: Merge:Express, Owner Approved

#29863 mongoose: change useCreateIndex position in connect option obj
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#30113 [seamless-immutable] Remove duplicate type from BaseImmutable
  types/seamless-immutable/index.d.ts
Labels: Merge:Express, Owner Approved

#30189 Add types for "styled-theming"
  types/styled-theming/index.d.ts
  types/styled-theming/styled-theming-tests.ts
  types/styled-theming/tsconfig.json
  types/styled-theming/tslint.json
Labels: New Definition, Revision needed

#30155 add type ali-app
  types/ali-app/ali-app-tests.ts
  types/ali-app/index.d.ts
  types/ali-app/tsconfig.json
  types/ali-app/tslint.json
  types/weixin-app/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, New Definition

#30204 [postcss-icss-values] Add Typescript definitions.
  types/postcss-icss-values/index.d.ts
  types/postcss-icss-values/package.json
  types/postcss-icss-values/postcss-icss-values-tests.ts
  types/postcss-icss-values/tsconfig.json
  types/postcss-icss-values/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#29976 Add typings for glue v4
  types/glue/v4/glue-tests.ts
  types/glue/v4/index.d.ts
  types/glue/v4/tsconfig.json
  types/glue/v4/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#30013 [markdown-it] Add submodules for all classes
  types/markdown-it-anchor/index.d.ts
  types/markdown-it-anchor/markdown-it-anchor-tests.ts
  types/markdown-it-container/index.d.ts
  types/markdown-it-container/markdown-it-container-tests.ts
  types/markdown-it-lazy-headers/index.d.ts
  types/markdown-it/index.d.ts
  types/markdown-it/lib/index.d.ts
  types/markdown-it/lib/parser_block.d.ts
  types/markdown-it/lib/parser_core.d.ts
  types/markdown-it/lib/parser_inline.d.ts
  types/markdown-it/lib/renderer.d.ts
  types/markdown-it/lib/ruler.d.ts
  types/markdown-it/lib/rules_block/state_block.d.ts
  types/markdown-it/lib/rules_core/state_core.d.ts
  types/markdown-it/lib/rules_inline/state_inline.d.ts
  types/markdown-it/lib/token.d.ts
  types/markdown-it/markdown-it-tests.ts
  types/prosemirror-markdown/index.d.ts
Labels: Revision needed

#30052 Add makeup-screenreader-trap definitions
  types/makeup-screenreader-trap/index.d.ts
  types/makeup-screenreader-trap/makeup-screenreader-trap-tests.ts
  types/makeup-screenreader-trap/tsconfig.json
  types/makeup-screenreader-trap/tslint.json
Labels: New Definition, Revision needed

#29994 Add terser types
  types/terser/index.d.ts
  types/terser/package.json
  types/terser/terser-tests.ts
  types/terser/tsconfig.json
  types/terser/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30187 Add types for rc-time-picker
  types/rc-time-picker/index.d.ts
  types/rc-time-picker/rc-time-picker-tests.tsx
  types/rc-time-picker/tsconfig.json
  types/rc-time-picker/tslint.json
Labels: New Definition, Revision needed

#30223 dd-trace: Fix incorrect typings for TracerOptions interface
  types/dd-trace/dd-trace-tests.ts
  types/dd-trace/index.d.ts
Labels: Revision needed

#30269 [weixin-app] Add get account info
  types/weixin-app/index.d.ts
  types/weixin-app/weixin-app-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#29946 [knex] Update enum arguments to reflect latest signature
  types/knex/index.d.ts
  types/knex/knex-tests.ts
  types/knex/tslint.json
Labels: Popular package, Revision needed

#30198 Added definition files for BluetoothClassicSerial Cordova plugin
  types/cordova-plugin-bluetoothclassic-serial/cordova-plugin-bluetoothclassic-serial-tests.ts
  types/cordova-plugin-bluetoothclassic-serial/index.d.ts
  types/cordova-plugin-bluetoothclassic-serial/tsconfig.json
  types/cordova-plugin-bluetoothclassic-serial/tslint.json
Labels: New Definition, Revision needed

#30222 Upgrade react-alert to 4.0
  types/react-alert/index.d.ts
  types/react-alert/react-alert-tests.tsx
  types/react-alert/v2/index.d.ts
  types/react-alert/v2/react-alert-tests.tsx
  types/react-alert/v2/tsconfig.json
  types/react-alert/v2/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30082 @types/json-rpc-random-id: Initial Typings
  types/json-rpc-random-id/index.d.ts
  types/json-rpc-random-id/json-rpc-random-id-tests.ts
  types/json-rpc-random-id/tsconfig.json
  types/json-rpc-random-id/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30226 [scheduler] Add types for scheduler package
  types/scheduler/index.d.ts
  types/scheduler/scheduler-tests.ts
  types/scheduler/tsconfig.json
  types/scheduler/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30235 [@commercetools/enzyme-extensions] Add types
  types/commercetools__enzyme-extensions/commercetools__enzyme-extensions-tests.tsx
  types/commercetools__enzyme-extensions/index.d.ts
  types/commercetools__enzyme-extensions/tsconfig.json
  types/commercetools__enzyme-extensions/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30253 [module-deps] Add module-deps@6.1.0 definition
  types/module-deps/index.d.ts
  types/module-deps/module-deps-tests.ts
  types/module-deps/tsconfig.json
  types/module-deps/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30267 New types for react-native-uuid-generator
  types/react-native-uuid-generator/index.d.ts
  types/react-native-uuid-generator/react-native-uuid-generator-tests.ts
  types/react-native-uuid-generator/tsconfig.json
  types/react-native-uuid-generator/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30259 Three change 2 place
  types/three/index.d.ts
  types/three/three-core.d.ts
  types/three/three-unrealbloompass.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#30240 [office-js] Add error code 12009 for Office.UI.dislayDialogAsync method
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#30258 Remove myself as a contributor
  types/auth0/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#30221 fix [diff] diffArrays option type
  types/diff/diff-tests.ts
  types/diff/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#30141 Added missing getAll() parser function
  types/mathjs/index.d.ts
  types/mathjs/mathjs-tests.ts
Labels: Merge:Express, Owner Approved

#30228 Pixi.js tiny fix
  types/pixi.js/index.d.ts
Labels: Author is Owner, Merge:Express

#30169 Add pino.final
  types/pino/index.d.ts
  types/pino/pino-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#30040 Change shown to visible
  types/react-native-popup-dialog/index.d.ts
  types/react-native-popup-dialog/react-native-popup-dialog-tests.tsx
Labels: Merge:Express, Owner Approved, Revision needed

#30230 [request] update agentOptions
  types/request/index.d.ts
  types/request/request-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#30134 fix: add grayscale theme to Victory
  types/victory/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30268 [bootstrap-toggle] Add Types
  types/bootstrap-toggle/bootstrap-toggle-tests.ts
  types/bootstrap-toggle/index.d.ts
  types/bootstrap-toggle/tsconfig.json
  types/bootstrap-toggle/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30140 [normalize-url] Updated definitions for version 3.3.0
  types/normalize-url/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30150 [duplexify] Add missing method types: obj(), cork() and uncork()
  types/duplexify/duplexify-tests.ts
  types/duplexify/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30284 d3-shape: Predeclare CanvasRenderingContext2D
  types/d3-shape/index.d.ts
Labels: Popular package, The Travis CI build failed

#29860 d3-selection: Use $ExpectError
  types/d3-selection/d3-selection-tests.ts
  types/d3-selection/index.d.ts
  types/react-native-svg-charts/tslint.json
Labels: Abandoned, Popular package, The Travis CI build failed

#30177 [Leaflet] Add type PathOptions to styles property in GeoJSONOptions
  types/leaflet/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#30161 D3 contour 1.3.0
  types/d3-contour/d3-contour-tests.ts
  types/d3-contour/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#29709 @types/mongoose Add missing typings for MongooseError constructors
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#30231 Reach router "router" component div props
  types/reach__router/index.d.ts
  types/reach__router/reach__router-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#30232 fix [three] add screenSpacePanning for examples/OrbitControls
  types/three/index.d.ts
  types/three/three-orbitcontrols.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#30035 [lodash] Support WeakMap's for memoize.Cache
  types/lodash/common/common.d.ts
  types/lodash/lodash-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#30266 @types/kdbush - support more array constructors
  types/kdbush/index.d.ts
  types/kdbush/kdbush-tests.ts
Labels: Merge:Express, Owner Approved

#30163 [Slate, Slate-React]: Update typings to reflect new Command structure
  types/slate-react/index.d.ts
  types/slate-react/slate-react-tests.tsx
  types/slate/index.d.ts
  types/slate/slate-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#30279 nodegit: make parameters optional
  types/nodegit/repository.d.ts
Labels: Merge:Express, Owner Approved

#30248 office-js: Add ICalendar to AttachmentContentFormat enum
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Revision needed

#29955 Add makeup-keyboard-trap definitions
  types/makeup-keyboard-trap/index.d.ts
  types/makeup-keyboard-trap/makeup-keyboard-trap-tests.ts
  types/makeup-keyboard-trap/tsconfig.json
  types/makeup-keyboard-trap/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#30069 d3-graphviz - Fixed typo in enum
  types/d3-graphviz/index.d.ts
Labels: Merge:YSYL, Unowned

#30060 [jspdf] Add get methods for pageSize
  types/jspdf/index.d.ts
  types/jspdf/tslint.json
Labels: Owner Approved, Revision needed

#30064 [jasmine] make SpyObjMethodNames more strongly-typed
  types/angular-wizard/index.d.ts
  types/frisby/index.d.ts
  types/frisby/v0/index.d.ts
  types/gulp-jasmine/index.d.ts
  types/jasmine-ajax/index.d.ts
  types/jasmine-data_driven_tests/index.d.ts
  types/jasmine-es6-promise-matchers/index.d.ts
  types/jasmine-fixture/index.d.ts
  types/jasmine-jquery/index.d.ts
  types/jasmine-matchers/index.d.ts
  types/jasmine-node/index.d.ts
  types/jasmine-promise-matchers/index.d.ts
  types/jasmine/index.d.ts
  types/jasmine_dom_matchers/index.d.ts
  types/jasminewd2/index.d.ts
  types/karma-jasmine/index.d.ts
  types/protractor-helpers/index.d.ts
  types/saywhen/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30109 [@types/babylon] typescript plugin name support
  types/babylon/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30059 Jasmine: Adds withContext method on Matcher<T>
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30111 Enzyme. Add argument to .exists method
  types/enzyme/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30074 [react-table] Add typings for selectTableHOC and treeTableHOC
  types/react-table/index.d.ts
  types/react-table/lib/hoc/selectTable.d.ts
  types/react-table/lib/hoc/treeTable.d.ts
  types/react-table/test/select-table-tests.tsx
  types/react-table/test/tree-table-tests.tsx
  types/react-table/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#30166 Added type definitions for 'react-native-flip-card'
  types/react-native-flip-card/index.d.ts
  types/react-native-flip-card/react-native-flip-card-tests.tsx
  types/react-native-flip-card/tsconfig.json
  types/react-native-flip-card/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#29964 Add makeup-prevent-scroll-keys definitions
  types/makeup-prevent-scroll-keys/index.d.ts
  types/makeup-prevent-scroll-keys/makeup-prevent-scroll-keys-tests.ts
  types/makeup-prevent-scroll-keys/tsconfig.json
  types/makeup-prevent-scroll-keys/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#29967 fix chai-jquery added enabled
  types/chai-jquery/chai-jquery-tests.ts
  types/chai-jquery/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#29992 koa-router: router.url with 3rd argument (query)
  types/koa-router/index.d.ts
  types/koa-router/koa-router-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30087 [Luxon] toSQL opts and fromFormatExplain result.
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
  types/luxon/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#30108 'file-saver' typedef: Added 'url' option to saveAs function.
  types/file-saver/file-saver-tests.ts
  types/file-saver/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30288 styled-system: Minor Fix, remove the true as an option to flexWrap
  types/styled-system/dist/styles.d.ts
Labels: Merge:Express, Owner Approved

#30280 Add server.d.ts to react-instantsearch
  types/react-instantsearch-dom/react-instantsearch-dom-tests.tsx
  types/react-instantsearch-dom/server.d.ts
  types/react-instantsearch-dom/tsconfig.json
  types/react-instantsearch/server.d.ts
  types/react-instantsearch/tsconfig.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#30224 [react-reconciler] Update types for react-reconciler v0.16
  types/react-reconciler/index.d.ts
Labels: Author is Owner, Merge:Express

#30219 remove [mobx-cookie] type definition
  notNeededPackages.json
  types/mobx-cookie/index.d.ts
  types/mobx-cookie/mobx-cookie-tests.ts
  types/mobx-cookie/tsconfig.json
  types/mobx-cookie/tslint.json
Labels: Author is Owner, Merge:Express

#30298 puppeteer/v0: Add no-unnecessary-type-assertion disables
  types/puppeteer/v0/puppeteer-tests.ts
Labels: Awaiting reviewer feedback, Popular package

#30202 Updating the ANSI typings.
  types/ansi/ansi-tests.ts
  types/ansi/index.d.ts
Labels: Author is Owner, Merge:Express

#30297 fast-diff: Provides its own types
  notNeededPackages.json
  types/fast-diff/fast-diff-tests.ts
  types/fast-diff/index.d.ts
  types/fast-diff/tsconfig.json
  types/fast-diff/tslint.json
Labels: Awaiting reviewer feedback, Has Merge Conflict

#30294 react-native-vector-iconts: Fix "lib"
  types/react-native-vector-icons/tsconfig.json
Labels: Awaiting reviewer feedback

#29898 paho-mqtt: Remove unnecessary module.d.ts
  types/paho-mqtt/index.d.ts
  types/paho-mqtt/module.d.ts
Labels: Abandoned, The Travis CI build failed

#30292 winston-syslog: Requires ts2.2
  types/winston-syslog/index.d.ts
Labels: Awaiting reviewer feedback

#30293 tiny-secp256k1: Depends on --lib es6
  types/tiny-secp256k1/tsconfig.json
Labels: Awaiting reviewer feedback

#30090 [Vuex i18n] Interface for plugin's module in store and signature for some methods
  types/vuex-i18n/index.d.ts
  types/vuex-i18n/vuex-i18n-tests.ts
Labels: Revision needed

#30277 [smooth-scroll] Add type definitions
  types/smooth-scroll/index.d.ts
  types/smooth-scroll/test/smooth-scroll-global.test.ts
  types/smooth-scroll/test/smooth-scroll.test.ts
  types/smooth-scroll/tsconfig.json
  types/smooth-scroll/tslint.json
Labels: New Definition, Revision needed

#30153 fix threejs `ShapeUtils`
  types/three/three-core.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#30316 Add 'error' event to minio-js types' BucketStream
  types/minio/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#30303 fix(react-native-modal-box): Fix tests
  types/react-native-modalbox/react-native-modalbox-tests.tsx
Labels: Author is Owner, Merge:Express

#30302 fix(hapi): server does not extend podium
  types/hapi/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#30274 angular-promise-tracker: Add tracker property to IRequestShortcutConfig
  types/angular-promise-tracker/angular-promise-tracker-tests.ts
  types/angular-promise-tracker/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#30196 Added Arangodb Foxx Queues typings
  types/arangodb/index.d.ts
Labels: Merge:Express, Owner Approved

#30186 [slate-react] - Fix RenderNodeProps node prop value to Block | Inline
  types/slate-react/index.d.ts
  types/slate-react/slate-react-tests.tsx
Labels: Merge:Express, Owner Approved

#30286 dockerode - misc fixes and additional typings
  types/dockerode/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#30322 koa-qs: Add types definitions
  types/koa-qs/index.d.ts
  types/koa-qs/koa-qs-tests.ts
  types/koa-qs/tsconfig.json
  types/koa-qs/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30314 Add types for mjml-react
  types/mjml-react/index.d.ts
  types/mjml-react/mjml-react-tests.tsx
  types/mjml-react/tsconfig.json
  types/mjml-react/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30194 [CKEditor] Add more skin settings
  types/ckeditor/ckeditor-tests.ts
  types/ckeditor/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#30164 rdf-js: Use single generic for I/O types of datafactory functions
  types/rdf-js/index.d.ts
  types/rdf-js/rdf-js-tests.ts
  types/rdf-js/tslint.json
Labels: Author is Owner, Merge:Express, Owner Approved

#30260 Adds type definitions for sql-template npm package
  types/sql-template/index.d.ts
  types/sql-template/sql-template-tests.ts
  types/sql-template/tsconfig.json
  types/sql-template/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30199 Add gl-react package type definitions
  types/gl-react-dom/index.d.ts
  types/gl-react-dom/tsconfig.json
  types/gl-react-dom/tslint.json
  types/gl-react-expo/index.d.ts
  types/gl-react-expo/tsconfig.json
  types/gl-react-expo/tslint.json
  types/gl-react-headless/index.d.ts
  types/gl-react-headless/tsconfig.json
  types/gl-react-headless/tslint.json
  types/gl-react-native/index.d.ts
  types/gl-react-native/tsconfig.json
  types/gl-react-native/tslint.json
  types/gl-react/index.d.ts
  types/gl-react/package.json
  types/gl-react/tsconfig.json
  types/gl-react/tslint.json
Labels: New Definition, Revision needed

#30176 [Leaflet] Make TileLayerOptions checkable
  types/leaflet-providers/index.d.ts
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30215 [@types/rebass] rearrange types to match rebass hierachy, remove unnecessary properties
  types/rebass/index.d.ts
  types/rebass/rebass-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#30214 Add changed method on TextMarker
  types/codemirror/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#30325 autoprefixer: Requires ts2.2
  types/autoprefixer/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#30308 Typings for expo-localization
  types/expo-localization/expo-localization-tests.ts
  types/expo-localization/index.d.ts
  types/expo-localization/tsconfig.json
  types/expo-localization/tslint.json
Labels: New Definition, Revision needed

#29634 [@types/recharts@1.1.0] add capHeight and lineHeight field type to TextProps interface
  types/recharts/index.d.ts
  types/recharts/recharts-tests.tsx
Labels: Revision needed

#30357 Update critters
  types/critters-webpack-plugin/critters-webpack-plugin-tests.ts
  types/critters-webpack-plugin/index.d.ts
Labels: Author is Owner, Merge:Express

#30327 feat(puppeteer): update for 1.10
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#30272 [CodeMirror] add type defs for comment addon
  types/codemirror/codemirror-comment.d.ts
  types/codemirror/test/comment.ts
  types/codemirror/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#30245 angular-toastr: Add extraData property
  types/angular-toastr/angular-toastr-tests.ts
  types/angular-toastr/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#30345 Add type definitions for setasap
  types/setasap/index.d.ts
  types/setasap/setasap-tests.ts
  types/setasap/tsconfig.json
  types/setasap/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30340 add typing for react-blessed
  types/react-blessed/index.d.ts
  types/react-blessed/react-blessed-tests.tsx
  types/react-blessed/react.d.ts
  types/react-blessed/tsconfig.json
  types/react-blessed/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#30328 add twilio-common
  types/twilio-common/index.d.ts
  types/twilio-common/tsconfig.json
  types/twilio-common/tslint.json
  types/twilio-common/twilio-common-tests.ts
Labels: Awaiting reviewer feedback, New Definition
