Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2018-06, with the labels that each got.

#26165 fix(argparse): addArgument accepts strings
  types/argparse/argparse-tests.ts
  types/argparse/index.d.ts
Labels: Merge:Express, Owner Approved

#25913 [core-js] Change lpad/rpad to padStart/padEnd
  types/core-js/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#26044 New typings for ServiceNow javascript api reference
  types/servicenow/index.d.ts
  types/servicenow/servicenow-tests.ts
  types/servicenow/tsconfig.json
  types/servicenow/tslint.json
Labels: New Definition, Revision needed

#26020 Add all parser options to express-xml-bodyparser
  types/express-xml-bodyparser/express-xml-bodyparser-tests.ts
  types/express-xml-bodyparser/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26017 Chroma-js: Added gamma method to Scale type
  types/chroma-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25838 mapbox-gl: Added StyleFunction to SymbolLayout - icon-allow-overlap
  types/mapbox-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26008 [Koa] Remove Context index signature
  types/koa/index.d.ts
  types/koa/koa-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26012 wu: lint, expose WuIterable interface
  types/wu/index.d.ts
  types/wu/tslint.json
  types/wu/wu-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26064 [PIXI.js] invalid powerPreference type
  types/pixi.js/index.d.ts
Labels: Popular package, Unowned

#25938 [@types/mem-fs-editor] Fixed JSON parsing and other fixes
  types/mem-fs-editor/index.d.ts
  types/mem-fs-editor/mem-fs-editor-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26006 react-router-redux: Relax redux version constraint
  types/react-router-redux/package.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25999 less: add definition for methods modifyVars, refreshStyles, watch
  types/less/index.d.ts
  types/less/less-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25927 @types/moment-timezone - added keepLocalTime converting option
  types/moment-timezone/index.d.ts
  types/moment-timezone/moment-timezone-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25973 d3-timer Activate strictNullChecks
  types/d3-hsv/d3-hsv-tests.ts
  types/d3-hsv/index.d.ts
  types/d3-timer/index.d.ts
  types/d3-timer/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#25971 is-svg: 3.0
  types/is-svg/index.d.ts
  types/is-svg/is-svg-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25963 [@types/grunt] fixing file.expand typing
  types/grunt/grunt-tests.ts
  types/grunt/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25966 Added .headless() to Firefox options
  types/selenium-webdriver/firefox.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25955 [@types/googlemaps] Fix #25954
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25951 [Dygraphs]: Allow Date type for input data array
  types/dygraphs/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25947 Update for react-bootstrap-typeahead 3.1
  types/react-bootstrap-typeahead/index.d.ts
  types/react-bootstrap-typeahead/react-bootstrap-typeahead-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#25920 d3-color : added piecewise method
  types/d3-interpolate/d3-interpolate-tests.ts
  types/d3-interpolate/index.d.ts
  types/d3-interpolate/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#25872 [react-redux] Fixed the typings for inferred types with functional components
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25853 react-transition-group: Allow component={null} on TransitionGroup
  types/react-transition-group/TransitionGroup.d.ts
  types/react-transition-group/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25852 added acoords to fabric base object definition
  types/fabric/fabric-impl.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25836 [IBM_DB] Database callback return type fixes
  types/ibm_db/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25806 Update mapbox-gl definitions (upgrade version + fix missing/removed defs)
  types/mapbox-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26179 [@storybook/addon-storyshots] Fill out missing initStoryshots options
  types/storybook__addon-storyshots/index.d.ts
  types/storybook__addon-storyshots/storybook__addon-storyshots-tests.ts
Labels: Merge:Express, Owner Approved

#26069 Fix PromiseConstructor issue in office-js typings.
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#25796 oauth2-server: Remove User "id" property from types.
  types/oauth2-server/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25777 http-proxy/Add missing property boolean `selfHandleResponse`
  types/http-proxy/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26040 S3rver: Add `declare namespace S3rver` to fix import
  types/s3rver/index.d.ts
Labels: Merge:YSYL, Unowned

#25755 classnames: let classNames() to accept boolean, as the original implementation does
  types/classnames/classnames-tests.ts
  types/classnames/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26205 react-navigation: Fix lint
  types/react-navigation/v2/index.d.ts
  types/react-navigation/v2/tslint.json
Labels: Awaiting reviewer feedback

#26025 React Dates DayPickerSingleDate Support
  types/react-dates/index.d.ts
  types/react-dates/react-dates-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#26155 Add definitions for `react-sticky-el`
  types/react-sticky-el/index.d.ts
  types/react-sticky-el/react-sticky-el-tests.tsx
  types/react-sticky-el/tsconfig.json
  types/react-sticky-el/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#26147 Add typings for tgfancy
  types/tgfancy/index.d.ts
  types/tgfancy/tgfancy-tests.ts
  types/tgfancy/tsconfig.json
  types/tgfancy/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#26129 Add types for newman
  types/newman/index.d.ts
  types/newman/newman-tests.ts
  types/newman/tsconfig.json
  types/newman/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#26042 [backo2] Add types for backo2 npm module
  types/backo2/backo2-tests.ts
  types/backo2/index.d.ts
  types/backo2/tsconfig.json
  types/backo2/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#26036 [redux-testkit] New typings for package
  types/redux-testkit/index.d.ts
  types/redux-testkit/package.json
  types/redux-testkit/redux-testkit-tests.ts
  types/redux-testkit/tsconfig.json
  types/redux-testkit/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#26010 [run-parallel-limit] New typings for package
  types/run-parallel-limit/index.d.ts
  types/run-parallel-limit/run-parallel-limit-tests.ts
  types/run-parallel-limit/tsconfig.json
  types/run-parallel-limit/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#26200 Update type definition to match urllib latest version (v2.28.0)
  types/urllib/index.d.ts
Labels: Author is Owner, Merge:Express

#26197 Fix for CollectionElements in Cytoscape
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26194 [node-telegram-bot-api] Added several methods introduced in node-telegram-bot-api v0.30.0
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved

#26201 Jest 23 requires test function to not be undefined
  types/jest/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#26204 [plotly.js] Add missing hoverlabel.
  types/plotly.js/index.d.ts
Labels: Merge:Express, Owner Approved

#26188 [video.js] Adds missing 'one' method to the player and fixes some indentation problems.
  types/video.js/index.d.ts
Labels: Merge:Express, Owner Approved

#26207 Add typings for generate-json-webpack-plugin
  types/generate-json-webpack-plugin/generate-json-webpack-plugin-tests.ts
  types/generate-json-webpack-plugin/index.d.ts
  types/generate-json-webpack-plugin/tsconfig.json
  types/generate-json-webpack-plugin/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26208 Add typings for webpackbar
  types/webpackbar/index.d.ts
  types/webpackbar/tsconfig.json
  types/webpackbar/tslint.json
  types/webpackbar/webpackbar-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#26206 Add typings for webpack-serve and webpack-hot-client
  types/webpack-hot-client/index.d.ts
  types/webpack-hot-client/tsconfig.json
  types/webpack-hot-client/tslint.json
  types/webpack-hot-client/webpack-hot-client-tests.ts
  types/webpack-serve/index.d.ts
  types/webpack-serve/tsconfig.json
  types/webpack-serve/tslint.json
  types/webpack-serve/webpack-serve-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#26141 use native DOM types for text-encoding module
  types/text-encoding/index.d.ts
  types/text-encoding/text-encoding-tests.ts
  types/text-encoding/tsconfig.json
Labels: Awaiting reviewer feedback

#26214 Office JS: Use AsyncContextOptions in more places
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26193 Revert "S3rver: Add `declare namespace S3rver` to fix import"
  types/s3rver/index.d.ts
Labels: Unowned

#26210 Add typings for svg-sprite-loader
  types/svg-sprite-loader/index.d.ts
  types/svg-sprite-loader/plugin.d.ts
  types/svg-sprite-loader/svg-sprite-loader-tests.ts
  types/svg-sprite-loader/tsconfig.json
  types/svg-sprite-loader/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25832 Add typings for uuid-parse
  types/uuid-parse/index.d.ts
  types/uuid-parse/tsconfig.json
  types/uuid-parse/tslint.json
  types/uuid-parse/uuid-parse-tests.ts
Labels: New Definition, Revision needed

#26062 Add ErrorList props support in react-jsonschema-form
  types/react-jsonschema-form/index.d.ts
  types/react-jsonschema-form/react-jsonschema-form-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#26217 Office JS: Combine and complete the Context interface declarations
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26056 ejs: Add support for the async option
  types/ejs/ejs-tests.ts
  types/ejs/index.d.ts
Labels: Owner Approved, Revision needed

#25880 [react-native-svg-charts] Typings for version 5.0.0
  types/react-native-svg-charts/index.d.ts
  types/react-native-svg-charts/package.json
  types/react-native-svg-charts/react-native-svg-charts-tests.tsx
  types/react-native-svg-charts/tsconfig.json
  types/react-native-svg-charts/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#26019 Add bin-pack typings
  types/bin-pack/bin-pack-tests.ts
  types/bin-pack/index.d.ts
  types/bin-pack/tsconfig.json
  types/bin-pack/tslint.json
Labels: New Definition, Revision needed

#26228 Fix v2 subfolder error (fix npm v2 of react-navigation)
  types/react-navigation/index.d.ts
  types/react-navigation/react-navigation-tests.tsx
  types/react-navigation/tsconfig.json
  types/react-navigation/tslint.json
  types/react-navigation/v1/index.d.ts
  types/react-navigation/v1/react-navigation-tests.tsx
  types/react-navigation/v1/tsconfig.json
  types/react-navigation/v1/tslint.json
  types/react-navigation/v2/tslint.json
  types/react-router-navigation-core/tsconfig.json
  types/react-router-navigation/tsconfig.json
Labels: Merge:Express, Owner Approved

#25849 Add definitions for axios-token-interceptor
  types/axios-token-interceptor/axios-token-interceptor-tests.ts
  types/axios-token-interceptor/index.d.ts
  types/axios-token-interceptor/package.json
  types/axios-token-interceptor/tsconfig.json
  types/axios-token-interceptor/tslint.json
Labels: New Definition, Revision needed

#25826 Add typings for cesium
  types/cesium/index.d.ts
  types/cesium/test/cesium-global.test.ts
  types/cesium/test/cesium-module.test.ts
  types/cesium/tsconfig.json
  types/cesium/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#26232 Add types to jquery.nicescroll
  types/jquery.nicescroll/index.d.ts
  types/jquery.nicescroll/jquery.nicescroll-tests.ts
  types/jquery.nicescroll/tsconfig.json
  types/jquery.nicescroll/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26227 smtp-server: New attributes for SMTPServerSession and SMTPServerOptions
  types/smtp-server/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#25997 kendo-ui: GridOptions.editable should allow string as well
  types/kendo-ui/index.d.ts
Labels: Revision needed

#25996 kendo-ui: CalendarOptions.footer should allow boolean as well
  types/kendo-ui/index.d.ts
Labels: Revision needed

#26083 Add imperium library typing
  types/imperium/imperium-tests.ts
  types/imperium/index.d.ts
  types/imperium/tsconfig.json
  types/imperium/tslint.json
Labels: New Definition, Revision needed

#26221 [react-stripe-elements] - Options should be spread into StripeProvider props
  types/react-stripe-elements/index.d.ts
  types/react-stripe-elements/react-stripe-elements-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26184 make RequestPromise generic
  types/request-promise-native/index.d.ts
Labels: Merge:Express, Owner Approved

#26191 Fix parameterized type inference for async-retry
  types/async-retry/async-retry-tests.ts
  types/async-retry/index.d.ts
Labels: Merge:Express, Owner Approved

#26203 Fix missing LabelList typing & update README
  types/recharts/README.MD
  types/recharts/index.d.ts
  types/recharts/recharts-tests.tsx
Labels: Merge:Express, Owner Approved

#26106 [swagger-schema-official] Make schema example property spec compliant
  types/swagger-schema-official/index.d.ts
Labels: Merge:Express, Owner Approved

#26246 [@types/koa-webpack] Upgrade to v5.x
  types/koa-webpack/index.d.ts
  types/koa-webpack/koa-webpack-tests.ts
Labels: Merge:Express, Owner Approved

#26245 nvd3 updated with 2 missing functions
  types/nvd3/index.d.ts
  types/nvd3/test/discreteBarChart.ts
  types/nvd3/test/multibarHorizontalChart.ts
Labels: Merge:Express, Owner Approved

#26242 [@types/express] Improve types for express 4.16 and Fix #18940 and #24495
  types/express-serve-static-core/index.d.ts
  types/express/express-tests.ts
  types/express/index.d.ts
  types/kraken-js/index.d.ts
  types/range-parser/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#26101 Add label render function
  types/recharts/index.d.ts
  types/recharts/recharts-tests.tsx
Labels: Merge:Express, Owner Approved

#26259 (react-native-tab-view) Update types for 1.0
  types/react-native-tab-view/index.d.ts
  types/react-native-tab-view/react-native-tab-view-tests.tsx
  types/react-router-navigation-core/react-router-navigation-core-tests.tsx
  types/react-router-navigation/index.d.ts
Labels: Merge:Express, Owner Approved

#26261 Improve typings for helmet
  types/helmet/index.d.ts
Labels: Merge:Express, Owner Approved

#26267 [yup] fix return types of validate and validateSync
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Express, Owner Approved

#26224 react-dom: optional `key` param for `createPortal`
  types/react-dom/index.d.ts
  types/react-dom/react-dom-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#26268 elasticsearch: Fix the _source parameter on mget
  types/elasticsearch/elasticsearch-tests.ts
  types/elasticsearch/index.d.ts
Labels: Merge:Express, Owner Approved

#26209 node: add `argv0` as one of options for `spawn` and `spawnSync`
  types/node/index.d.ts
  types/node/node-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#26234 Office js many fixes: See commit descriptions
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26269 Create typings for react-native-custom-tabs
  types/react-native-custom-tabs/index.d.ts
  types/react-native-custom-tabs/react-native-custom-tabs-tests.ts
  types/react-native-custom-tabs/tsconfig.json
  types/react-native-custom-tabs/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26243 Types for JQuery Mouse Exit
  types/jquery-mouse-exit/index.d.ts
  types/jquery-mouse-exit/jquery-mouse-exit-tests.ts
  types/jquery-mouse-exit/tsconfig.json
  types/jquery-mouse-exit/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#26231 [openpgp] Update openpgp type definitions to match module
  types/openpgp/index.d.ts
  types/openpgp/openpgp-tests.ts
Labels: Unowned

#26220 [webpack-hot-client] Allow either HTTP or HTTPS server
  types/webpack-hot-client/index.d.ts
Labels: Unowned

#26212 Add typings for yauzl-promise
  types/yauzl-promise/index.d.ts
  types/yauzl-promise/tsconfig.json
  types/yauzl-promise/tslint.json
  types/yauzl-promise/yauzl-promise-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#26157 Fix for issue #25343 @types/react-redux
  types/react-redux/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#26153 JSforce: Add proper types for describe calls
  types/jsforce/cache.d.ts
  types/jsforce/connection.d.ts
  types/jsforce/describe-result.d.ts
  types/jsforce/index.d.ts
  types/jsforce/jsforce-tests.ts
  types/jsforce/salesforce-object.d.ts
  types/jsforce/tsconfig.json
Labels: Owner Approved, Revision needed

#26287 [node-telegram-bot-api] Make some types more specific
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26275 (react-navigation) Add StackActions
  types/react-navigation/index.d.ts
Labels: Merge:Express, Owner Approved

#26170 Update index.d.ts
  types/esri-leaflet/index.d.ts
Labels: Merge:Express, Owner Approved

#26281 Make stream a function. Add password to buffer
  types/unzipper/index.d.ts
Labels: Merge:Express, Owner Approved

#26274 Office.js - Outlook Recurrence Documention
  types/office-js/index.d.ts
Labels: Merge:Express, Owner Approved

#26273 fix(prettier): add missing getFileInfo APIs
  types/prettier/index.d.ts
  types/prettier/prettier-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#26280 ThreeJS : Add null types to scene #fog and #overrideMaterial.
  types/three/three-core.d.ts
Labels: Merge:Express, Owner Approved

#26241 feat: add declaration file for koa-static-cache
  types/koa-static-cache/index.d.ts
  types/koa-static-cache/koa-static-cache-tests.ts
  types/koa-static-cache/tsconfig.json
  types/koa-static-cache/tslint.json
Labels: New Definition, Revision needed

#26300 Add types for react-infinite-scroll-component
  types/react-infinite-scroll-component/index.d.ts
  types/react-infinite-scroll-component/react-infinite-scroll-component-tests.tsx
  types/react-infinite-scroll-component/tsconfig.json
  types/react-infinite-scroll-component/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26295 Fix version conflict with axios-token-interceptor definition
  types/axios-token-interceptor/package.json
Labels: Unowned

#26294 More type-safe typings for bleno module.
  types/bleno/bleno-tests.ts
  types/bleno/index.d.ts
  types/bleno/tslint.json
Labels: Unowned

#26286 Add typings for git-branch
  types/git-branch/git-branch-tests.ts
  types/git-branch/index.d.ts
  types/git-branch/tsconfig.json
  types/git-branch/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26285 Add basic types for vue-color
  types/vue-color/index.d.ts
  types/vue-color/package.json
  types/vue-color/tsconfig.json
  types/vue-color/tslint.json
  types/vue-color/vue-color-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#26219 [webpack-serve] optional serve property and correct node api types
  types/webpack-serve/index.d.ts
  types/webpack-serve/webpack-serve-tests.ts
Labels: Unowned

#26276 Add types for @reach/router
  types/reach__router/index.d.ts
  types/reach__router/reach__router-tests.tsx
  types/reach__router/tsconfig.json
  types/reach__router/tslint.json
  types/react/tsconfig.json
Labels: Awaiting reviewer feedback, New Definition, Popular package

#26279 Type definitions for motor-hat module
  types/motor-hat/index.d.ts
  types/motor-hat/motor-hat-tests.ts
  types/motor-hat/tsconfig.json
  types/motor-hat/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#26007 Introduce declarations for `ember-resolver`
  types/ember-resolver/ember-resolver-tests.ts
  types/ember-resolver/index.d.ts
  types/ember-resolver/tsconfig.json
  types/ember-resolver/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#25943 Add type definition for parse5
  notNeededPackages.json
  types/jsdom/index.d.ts
  types/parse5-htmlparser2-tree-adapter/index.d.ts
  types/parse5-htmlparser2-tree-adapter/parse5-htmlparser2-tree-adapter-tests.ts
  types/parse5-htmlparser2-tree-adapter/tsconfig.json
  types/parse5-htmlparser2-tree-adapter/tslint.json
  types/parse5-parser-stream/index.d.ts
  types/parse5-parser-stream/parse5-parser-stream-tests.ts
  types/parse5-parser-stream/tsconfig.json
  types/parse5-parser-stream/tslint.json
  types/parse5-plain-text-conversion-stream/index.d.ts
  types/parse5-plain-text-conversion-stream/parse5-plain-text-conversion-stream-tests.ts
  types/parse5-plain-text-conversion-stream/tsconfig.json
  types/parse5-plain-text-conversion-stream/tslint.json
  types/parse5-sax-parser/index.d.ts
  types/parse5-sax-parser/parse5-sax-parser-tests.ts
  types/parse5-sax-parser/tsconfig.json
  types/parse5-sax-parser/tslint.json
  types/parse5-serializer-stream/index.d.ts
  types/parse5-serializer-stream/parse5-serializer-stream-tests.ts
  types/parse5-serializer-stream/tsconfig.json
  types/parse5-serializer-stream/tslint.json
  types/parse5/index.d.ts
  types/parse5/parse5-tests.ts
  types/parse5/tsconfig.json
  types/parse5/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#26100 [backbone.marionette] adds View.getUI() and Behavior.getUI()
  types/backbone.marionette/backbone.marionette-tests.ts
  types/backbone.marionette/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26135 add the missing `key` arg for `length()`
  types/lru-cache/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26110 [express-session] Add sameSite property to SessionOptions
  types/express-session/express-session-tests.ts
  types/express-session/index.d.ts
Labels: Awaiting reviewer feedback

#26142 add missing advanced customization props for react-native-htmlview
  types/react-native-htmlview/index.d.ts
  types/react-native-htmlview/react-native-htmlview-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#26150 Update kendo-ui/index.d.ts (GridOptions toolbar)
  types/kendo-ui/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26240 Add scoped-http-client typings
  types/scoped-http-client/index.d.ts
  types/scoped-http-client/scoped-http-client-tests.ts
  types/scoped-http-client/tsconfig.json
  types/scoped-http-client/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#26313 add cancel prop on IchooseImage for 'jweixin'
  types/jweixin/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26306 [puppeteer] remove myself as reviewer
  types/puppeteer/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#26307 [react-navigation] Add index to NavigationLeafRoute
  types/react-navigation/index.d.ts
  types/react-navigation/react-navigation-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved

#26301 Fixed query and set's param types
  types/snekfetch/index.d.ts
Labels: Author is Owner, Merge:Express, Other Approved, Owner Approved

#26296 Add typing for method in libphonenumber
  types/google-libphonenumber/index.d.ts
Labels: Merge:Express, Owner Approved

#26298 [koa-webpack] add close method
  types/koa-webpack/index.d.ts
  types/koa-webpack/koa-webpack-tests.ts
Labels: Merge:Express, Owner Approved

#26216 In react/index.d.ts, add default type annotation <T = Element> to SyntheticEvent and EventHandler types
  types/react/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#26303 Add generic types to Queue and Job
  types/bull/bull-tests.tsx
  types/bull/index.d.ts
Labels: Merge:Express, Owner Approved

#26297 nodegit: Fix return type of Commit#amend
  types/nodegit/commit.d.ts
  types/nodegit/index.d.ts
  types/nodegit/nodegit-tests.ts
Labels: Merge:Express, Owner Approved

#25975 Set type of symlink parameter `type` to a union of `"file" | "dir" | "junction" | undefined | null`
  types/fs-extra-promise-es6/fs-extra-promise-es6-tests.ts
  types/fs-extra-promise-es6/index.d.ts
  types/fs-extra-promise/fs-extra-promise-tests.ts
  types/fs-extra-promise/index.d.ts
  types/fs-extra/index.d.ts
  types/node/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package, Revision needed

#26316 [@types/react-select] Fix OnInputChangeHandler type.
  types/react-select/index.d.ts
Labels: Merge:Express, Owner Approved

#26177 Make formParameters optional for Xrm.Navigation.openForm in xrm
  types/xrm/index.d.ts
Labels: Merge:Express, Owner Approved

#26308 bleno: Characteristic and friends cannot be simply imported from the module
  types/bleno/bleno-tests.ts
Labels: Unowned

#26192 Add shrinkwrap.yaml to .gitignore
  .gitignore
Labels: Infrastructure, Merge:YSYL, Unowned

#26074 dropzone: add dictUploadCanceled to DropzoneOptions & make JQuery interface global & add access to Dropzone via HTMLElement
  types/dropzone/dropzone-tests.ts
  types/dropzone/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26166 [@storybook/addon-links] Remove unnecessary MouseEvent argument
  types/storybook__addon-links/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26168 fixing handlebars runtime module declaration
  types/handlebars/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#26173 Updated index.d.ts for 'connect-mongo'
  types/connect-mongo/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26292 Add type definition for serialize-error
  types/serialize-error/index.d.ts
  types/serialize-error/serialize-error-tests.ts
  types/serialize-error/tsconfig.json
  types/serialize-error/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#26315 Added definitions for 'glob-to-regexp'
  types/glob-to-regexp/glob-to-regexp-tests.ts
  types/glob-to-regexp/index.d.ts
  types/glob-to-regexp/tsconfig.json
  types/glob-to-regexp/tslint.json
Labels: New Definition, Revision needed

#26333 Office.js: Changing hyperlinks to use AEDoc syntax
  types/office-js/index.d.ts
Labels: Merge:Express, Owner Approved

#26305 Put openURL under CustomTabs namespace
  types/react-native-custom-tabs/index.d.ts
  types/react-native-custom-tabs/react-native-custom-tabs-tests.ts
Labels: Unowned

#26202 SharedWorker: Add SharedWorkerGlobalScope to allow types within the worker.
  types/sharedworker/index.d.ts
  types/sharedworker/sharedworker-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26215 [google-cloud__pubsub]Added new apiEndpoint options key for Google PubSub definition type
  types/google-cloud__pubsub/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26031 Add support for web3
  types/web3/eth/abi.d.ts
  types/web3/eth/accounts.d.ts
  types/web3/eth/contract.d.ts
  types/web3/eth/index.d.ts
  types/web3/eth/types.d.ts
  types/web3/index.d.ts
  types/web3/promiEvent.d.ts
  types/web3/providers.d.ts
  types/web3/tsconfig.json
  types/web3/tslint.json
  types/web3/types.d.ts
  types/web3/utils.d.ts
  types/web3/web3-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#26187 leaflet-locatecontrol: change markerStyle to any
  types/leaflet.locatecontrol/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#26160 Chromecast CAF Receiver Framework
  types/chromecast-caf-receiver/cast.framework.breaks.d.ts
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/cast.framework.events.d.ts
  types/chromecast-caf-receiver/cast.framework.messages.d.ts
  types/chromecast-caf-receiver/cast.framework.system.d.ts
  types/chromecast-caf-receiver/cast.framework.ui.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
  types/chromecast-caf-receiver/index.d.ts
  types/chromecast-caf-receiver/tsconfig.json
  types/chromecast-caf-receiver/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#25859 Add re-base@3.x type definitions
  types/re-base/index.d.ts
  types/re-base/re-base-tests.ts
  types/re-base/tsconfig.json
  types/re-base/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#26226 libxmljs: major overhaul of types to latest version
  types/libxmljs/index.d.ts
  types/libxmljs/libxmljs-tests.ts
  types/libxmljs/tsconfig.json
  types/libxmljs/tslint.json
  types/libxslt/index.d.ts
  types/libxslt/internal-types.d.ts
  types/libxslt/libxslt-tests.ts
  types/libxslt/tsconfig.json
  types/libxslt/tslint.json
Labels: New Definition

#26293 react-native: Add event for TextInput onFocus and onBlur
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Popular package, Revision needed

#26258 (react-native-material-textfield) Add style prop
  types/react-native-material-textfield/index.d.ts
  types/react-native-material-textfield/react-native-material-textfield-tests.tsx
Labels: Merge:Express, Owner Approved

#26404 [chen] make webAuth support social login
  types/react-native-auth0/index.d.ts
Labels: Merge:Express, Owner Approved

#26399 [jest] add toHaveBeenNthCalledWith matcher
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#26362 react-native-snap-carousel: add inverted (optional boolean) support
  types/react-native-snap-carousel/index.d.ts
Labels: Merge:Express, Owner Approved

#26354 [nodegit] Fix bugs with Object types.
  types/nodegit/diff-binary-file.d.ts
  types/nodegit/object.d.ts
  types/nodegit/odb-expand-id.d.ts
  types/nodegit/odb.d.ts
  types/nodegit/reference.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Revision needed

#26237 [react-native-datepicker]: Added missing getDateStr method for DatePicker
  types/react-native-datepicker/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved
