Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2018-05, with the labels that each got.

#25433 Add types for react-autocomplete
  types/react-autocomplete/index.d.ts
  types/react-autocomplete/react-autocomplete-tests.tsx
  types/react-autocomplete/tsconfig.json
  types/react-autocomplete/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25432 Add types for @atlaskit/single-select
  types/atlaskit__single-select/atlaskit__single-select-tests.tsx
  types/atlaskit__single-select/index.d.ts
  types/atlaskit__single-select/tsconfig.json
  types/atlaskit__single-select/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25431 Create definitions for react-image-crop
  types/react-image-crop/index.d.ts
  types/react-image-crop/test/react-image-crop-global-tests.ts
  types/react-image-crop/test/react-image-crop-module-tests.tsx
  types/react-image-crop/tsconfig.json
  types/react-image-crop/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25446 Add react-share
  types/react-share/index.d.ts
  types/react-share/react-share-tests.ts
  types/react-share/tsconfig.json
  types/react-share/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25445 Add express-routemap
  types/express-routemap/express-routemap-tests.ts
  types/express-routemap/index.d.ts
  types/express-routemap/tsconfig.json
  types/express-routemap/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25444 Add rword
  types/rword/index.d.ts
  types/rword/rword-tests.ts
  types/rword/tsconfig.json
  types/rword/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25447 Papaparse: added Parser.pause() & Parser.resume()
  types/papaparse/index.d.ts
Labels: Awaiting reviewer feedback

#25441 update index.d.ts
  types/mongodb/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25436 Add types for react-circular-progressbar
  types/react-circular-progressbar/index.d.ts
  types/react-circular-progressbar/react-circular-progressbar-tests.tsx
  types/react-circular-progressbar/tsconfig.json
  types/react-circular-progressbar/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25428 @types/puppeteer updated types for puppeteer realease 1.3
  types/puppeteer/index.d.ts
Labels: Merge:Express, Owner Approved

#25427 Add @atlaskit/layer types
  types/atlaskit__layer/atlaskit__layer-tests.tsx
  types/atlaskit__layer/index.d.ts
  types/atlaskit__layer/tsconfig.json
  types/atlaskit__layer/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25426 [awesomplete] Add destroy function
  types/awesomplete/awesomplete-tests.ts
  types/awesomplete/index.d.ts
Labels: Merge:Express, Owner Approved

#25418 Add url-safe-base64 npm module declarations
  types/url-safe-base64/index.d.ts
  types/url-safe-base64/tsconfig.json
  types/url-safe-base64/tslint.json
  types/url-safe-base64/url-safe-base64-tests.ts
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25417 Definitions for react-native-material-textfield
  types/react-native-material-textfield/index.d.ts
  types/react-native-material-textfield/react-native-material-textfield-tests.tsx
  types/react-native-material-textfield/tsconfig.json
  types/react-native-material-textfield/tslint.json
  types/react-native-material-ui/index.d.ts
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25413 Adding type definition for murmurhash library
  types/murmurhash/index.d.ts
  types/murmurhash/murmurhash-tests.ts
  types/murmurhash/tsconfig.json
  types/murmurhash/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25410 [esprima] Add tolerant TokenizeOption property
  types/esprima/esprima-tests.ts
  types/esprima/index.d.ts
Labels: Merge:Express, Owner Approved

#25409 Types for JQuery Focus Exit
  types/jquery-focus-exit/index.d.ts
  types/jquery-focus-exit/jquery-focus-exit-tests.ts
  types/jquery-focus-exit/tsconfig.json
  types/jquery-focus-exit/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25391 `node-telegram-bot-api` package: WebHookOptions interace `port` property name typo
  types/node-telegram-bot-api/index.d.ts
Labels: Merge:Express, Owner Approved

#25390 Change table package name
  types/table/index.d.ts
Labels: Merge:Express, Owner Approved

#25389 [auth0-lock] Add missing props in AuthResult
  types/auth0-lock/auth0-lock-tests.ts
  types/auth0-lock/index.d.ts
Labels: Awaiting reviewer feedback

#25387 d3-dispatch: Update type definition
  types/d3-dispatch/d3-dispatch-tests.ts
  types/d3-dispatch/index.d.ts
  types/d3-dispatch/tsconfig.json
Labels: Merge:Express, Owner Approved

#25386 react-native-navigation - Add NavigatorEvent interface
  types/react-native-navigation/index.d.ts
  types/react-native-navigation/react-native-navigation-tests.tsx
Labels: Merge:Express, Owner Approved

#25384 pify: Tests fail for exclude option
  types/pify/index.d.ts
  types/pify/pify-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#25443 Add @zeit/next-typescript
  types/zeit__next-typescript/index.d.ts
  types/zeit__next-typescript/tsconfig.json
  types/zeit__next-typescript/tslint.json
  types/zeit__next-typescript/zeit__next-typescript-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#25474 chart.js -- ChartPoint.y is allowed to be string and Date
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved

#25473 node: Fix parameter type of TransformOptions transform callback
  types/node/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25471 Add type definitions for express-jsonschema
  types/express-jsonschema/express-jsonschema-tests.ts
  types/express-jsonschema/index.d.ts
  types/express-jsonschema/tsconfig.json
  types/express-jsonschema/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25470 recharts: Add tickMargin to XAxisProps and YAxisProps
  types/recharts/index.d.ts
Labels: Merge:Express, Owner Approved

#25456 Updated cleave.js - Added missing getISOFormatDate function and fixed contructor parameters
  types/cleave.js/cleave.js-tests.tsx
  types/cleave.js/index.d.ts
Labels: Merge:Express, Owner Approved

#25472 Add type definition for "request-as-curl"
  types/request-as-curl/index.d.ts
  types/request-as-curl/request-as-curl-tests.ts
  types/request-as-curl/tsconfig.json
  types/request-as-curl/tslint.json
Labels: New Definition, Revision needed

#25469 Added type definitions for behavior3
  types/behavior3/behavior3-tests.ts
  types/behavior3/index.d.ts
  types/behavior3/tsconfig.json
  types/behavior3/tslint.json
Labels: New Definition, Revision needed

#25510 Added intercom-client
  types/intercom-client/index.d.ts
  types/intercom-client/intercom-client-tests.ts
  types/intercom-client/tsconfig.json
  types/intercom-client/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25503 ws: add address method to Server
  types/ws/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25505 [react-native] ScrollView - make scrollToLocation method
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#25495 [angular-translate] Remove angular reference
  types/angular-translate/index.d.ts
Labels: Awaiting reviewer feedback

#25497 react-native-navigation: Add all Drawer properties
  types/react-native-navigation/index.d.ts
  types/react-native-navigation/react-native-navigation-tests.tsx
Labels: Merge:Express, Owner Approved

#25494 feat: add declarations for fork-ts-checker-webpack-plugin
  types/fork-ts-checker-webpack-plugin/fork-ts-checker-webpack-plugin-tests.ts
  types/fork-ts-checker-webpack-plugin/index.d.ts
  types/fork-ts-checker-webpack-plugin/tsconfig.json
  types/fork-ts-checker-webpack-plugin/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25493 ReactSVG - Update to 3.0
  types/react-svg/index.d.ts
  types/react-svg/react-svg-tests.tsx
Labels: Merge:Express, Owner Approved

#25487 node: Type spawn's args as a ReadonlyArray of string
  types/node/index.d.ts
  types/node/v0/index.d.ts
  types/node/v4/index.d.ts
  types/node/v6/index.d.ts
  types/node/v7/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25485 Add react-resize-detector definitions for refreshMode & refreshRate
  types/react-resize-detector/index.d.ts
  types/react-resize-detector/react-resize-detector-tests.tsx
Labels: Merge:Express, Owner Approved

#25466 Jasmine - Make createSpyObj definitions consistent - same strict type for all methodNames arguments.
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#25464 Fixed Expo PermissionType
  types/expo/expo-tests.tsx
  types/expo/index.d.ts
Labels: Merge:Express, Owner Approved

#25463 jwplayer: add missing event handlers (once, off, trigger)
  types/jwplayer/index.d.ts
Labels: Merge:Express, Owner Approved

#25461 [adone] refactoring
  types/adone/glosses/app.d.ts
  types/adone/glosses/is.d.ts
  types/adone/index.d.ts
  types/adone/test/glosses/app.ts
  types/adone/tsconfig.json
Labels: Author is Owner, Merge:Express, Owner Approved

#25459 Type definitions for bidirectional-map
  types/bidirectional-map/bidirectional-map-tests.ts
  types/bidirectional-map/index.d.ts
  types/bidirectional-map/tsconfig.json
  types/bidirectional-map/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25457 Hapi: Fix issue with invalid export linting
  types/hapi/index.d.ts
Labels: Merge:Express, Owner Approved

#25453 [idyll-ast] add type declarations for idyll-ast
  types/idyll-ast/idyll-ast-tests.ts
  types/idyll-ast/index.d.ts
  types/idyll-ast/tsconfig.json
  types/idyll-ast/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25455 [idyll-document] add type definition for idyll-document
  types/idyll-document/idyll-document-tests.ts
  types/idyll-document/index.d.ts
  types/idyll-document/tsconfig.json
  types/idyll-document/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25451 Chrome: Add node to BookmarkRemoveInfo type
  types/chrome/index.d.ts
Labels: Merge:Express, Owner Approved

#25336 [reactstrap] <Col> component types: Added missing "order" attribute to ColumnProps
  types/reactstrap/lib/Col.d.ts
Labels: Merge:Express, Owner Approved

#25301 [browser-sync] Appended/updated definitions and tests.
  types/browser-sync/browser-sync-tests.ts
  types/browser-sync/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25309 [redux-form] add missing updateUnregisteredFields prop
  types/redux-form/lib/reduxForm.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25327 @types/node: Add missing methods to Console, plus docs
  types/node/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25507 Add typing for object syntax on component register method
  types/angular/angular-tests.ts
  types/angular/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25350 AngularJS: improve types for `IQService.all` (support for arrays of non-promises).
  types/angular/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25339 bluebird-retry: add StopError
  types/bluebird-retry/bluebird-retry-tests.ts
  types/bluebird-retry/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25337 [@types/ace] Autocompletion Hook Interfaces
  types/ace/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25452 [EvaporateJS] Add evaporate 2.1 typing
  types/evaporate/evaporate-tests.ts
  types/evaporate/index.d.ts
  types/evaporate/tsconfig.json
  types/evaporate/tslint.json
Labels: Revision needed

#25502 google-apps-script: Add BooleanCriteria, InterpolationType, ConditionalFormatRuleBuilder, ConditionalFormatRule
  types/google-apps-script/google-apps-script.calendar.d.ts
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
Labels: Merge:Express, Owner Approved

#25311 [sequelize] Added exact key matching and partial update.
  types/sequelize/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25517 Remove extraneous character in react-native documentation
  types/react-native/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25454 [idyll] add type declaration for idyll
  types/idyll/idyll-tests.ts
  types/idyll/index.d.ts
  types/idyll/tsconfig.json
  types/idyll/tslint.json
Labels: New Definition, Revision needed

#25488 [shallowequal] Update shallowequal exports to allow '* as' imports.
  types/shallowequal/index.d.ts
  types/shallowequal/shallowequal-tests.ts
Labels: Author is Owner, Revision needed

#25532 fix(prettier): add missing props and fix wrong types
  types/prettier/index.d.ts
Labels: Author is Owner, Merge:Express

#25531 knockout: Add type params to the KnockoutBindingHandler type
  types/knockout/index.d.ts
  types/knockout/test/index.ts
Labels: Merge:Express, Owner Approved

#25530 Mongoose model init
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#25537 Add mobx-devtools-mst
  types/mobx-devtools-mst/index.d.ts
  types/mobx-devtools-mst/mobx-devtools-mst-tests.ts
  types/mobx-devtools-mst/tsconfig.json
  types/mobx-devtools-mst/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25519 react-sidebar updates
  types/react-sidebar/index.d.ts
  types/react-sidebar/react-sidebar-tests.tsx
Labels: Merge:Express, Owner Approved

#25518 Adding Office.onReady()
  types/office-js/index.d.ts
Labels: Merge:Express, Owner Approved

#25515 d3-hsv: update to 0.1.0
  types/d3-hsv/d3-hsv-tests.ts
  types/d3-hsv/index.d.ts
  types/d3-hsv/tsconfig.json
Labels: Merge:Express, Owner Approved

#25514 [@types/three] Fix Three.ParametricGeometry arguments
  types/three/test/webgl/webgl_geometries.ts
  types/three/three-core.d.ts
Labels: Merge:Express, Owner Approved

#25500 node: API docs never mention NodeBuffer, remove the definition
  types/fs-extra-promise-es6/fs-extra-promise-es6-tests.ts
  types/fs-extra-promise-es6/index.d.ts
  types/fs-extra-promise/fs-extra-promise-tests.ts
  types/fs-extra-promise/index.d.ts
  types/ip/index.d.ts
  types/noble/noble-tests.ts
  types/node/index.d.ts
  types/node/v9/index.d.ts
  types/request/request-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#25499 [urijs] Bugfix: segment(number) can also return undefined.
  types/urijs/index.d.ts
  types/urijs/urijs-tests.ts
Labels: Merge:Express, Owner Approved

#25483 [react-fontawesome] Changing props from a type union to an interface
  types/react-fontawesome/index.d.ts
Labels: Merge:Express, Owner Approved

#25486 feat(algoliasearch): rewrite almost completely
  types/algoliasearch/algoliasearch-tests.ts
  types/algoliasearch/index.d.ts
  types/algoliasearch/lite/index.d.ts
  types/algoliasearch/tsconfig.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#25355 [websocket] Add type definitions for w3cwebsocket
  types/websocket/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25164 http-proxy: Provide argument option as already parsed url
  types/http-proxy/http-proxy-tests.ts
  types/http-proxy/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25379 [draft-js] add missing entity methods to ContentState
  types/draft-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25376 Adding types for the new fields of react-sticky.
  types/react-sticky/index.d.ts
  types/react-sticky/react-sticky-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#25533 [react-navigation] SwitchNavigatorConfig backBehavior initialRoute (Intial) definition typo fixed
  types/react-navigation/index.d.ts
  types/react-navigation/react-navigation-tests.tsx
Labels: Merge:Express, Owner Approved

#25523 feat: add declarations for sw-precache
  types/sw-precache/index.d.ts
  types/sw-precache/package.json
  types/sw-precache/sw-precache-tests.ts
  types/sw-precache/tsconfig.json
  types/sw-precache/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25521 [mongodb] Fix profiling levels
  types/mongodb/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#25520 fix(prosemirror-*): replace void with undefined in return union types
  types/prosemirror-collab/index.d.ts
  types/prosemirror-collab/prosemirror-collab-tests.ts
  types/prosemirror-inputrules/index.d.ts
  types/prosemirror-inputrules/prosemirror-inputrules-tests.ts
  types/prosemirror-model/index.d.ts
  types/prosemirror-model/prosemirror-model-tests.ts
  types/prosemirror-state/index.d.ts
  types/prosemirror-state/prosemirror-state-tests.ts
  types/prosemirror-transform/index.d.ts
  types/prosemirror-transform/prosemirror-transform-tests.ts
  types/prosemirror-view/index.d.ts
  types/prosemirror-view/prosemirror-view-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#25508 [@types/puppeteer] Add evaluateHandle, focus, hover, tap, type to Frame definition
  types/puppeteer/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#25419 Creating type definitions for "react-native-keychain"
  types/react-native-keychain/index.d.ts
  types/react-native-keychain/react-native-keychain-tests.ts
  types/react-native-keychain/tsconfig.json
  types/react-native-keychain/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25333 [notifyjs] Fix `notifyjs is not a module`
  types/notifyjs/index.d.ts
  types/notifyjs/notifyjs-tests.ts
  types/notifyjs/tsconfig.json
Labels: Awaiting reviewer feedback

#25571 feat(types/proper-lockfile): add new types
  types/proper-lockfile/index.d.ts
  types/proper-lockfile/proper-lockfile-tests.ts
  types/proper-lockfile/tsconfig.json
  types/proper-lockfile/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25570 feat(types/cloneable-readable): add new types for cloneable-readable pkg
  types/cloneable-readable/cloneable-readable-tests.ts
  types/cloneable-readable/index.d.ts
  types/cloneable-readable/tsconfig.json
  types/cloneable-readable/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25569 [three.js] class CatmullRomCurve3
  types/three/three-core.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#25565 New types for yahoo/react-stickynode 1.4
  types/react-stickynode/index.d.ts
  types/react-stickynode/react-stickynode-tests.tsx
  types/react-stickynode/tsconfig.json
  types/react-stickynode/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25557 [react-google-places-suggest] Add type definitions
  types/react-google-places-suggest/index.d.ts
  types/react-google-places-suggest/react-google-places-suggest-tests.tsx
  types/react-google-places-suggest/tsconfig.json
  types/react-google-places-suggest/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25556 [babel-types] Allow sparse ArrayExpression nodes
  types/babel-types/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25555 feat(types/shelljs-exec-proxy): types for new module
  types/shelljs-exec-proxy/index.d.ts
  types/shelljs-exec-proxy/shelljs-exec-proxy-tests.ts
  types/shelljs-exec-proxy/tsconfig.json
  types/shelljs-exec-proxy/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25554 feat(types/freshy): types for new module freshy
  types/freshy/freshy-tests.ts
  types/freshy/index.d.ts
  types/freshy/tsconfig.json
  types/freshy/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25567 Add missing parameter to gm's `define` method
  types/gm/gm-tests.ts
  types/gm/index.d.ts
Labels: Merge:Express, Owner Approved

#25544 resolve: use ReadonlyArray for options
  types/resolve/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#25549 Add missing Expo Updates module
  types/expo/expo-tests.tsx
  types/expo/index.d.ts
Labels: Merge:Express, Owner Approved

#25541 feat: add declarations for sw-precache-webpack-plugin
  types/sw-precache-webpack-plugin/index.d.ts
  types/sw-precache-webpack-plugin/sw-precache-webpack-plugin-tests.ts
  types/sw-precache-webpack-plugin/tsconfig.json
  types/sw-precache-webpack-plugin/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#25538 d3-polygon strict null check
  types/d3-polygon/d3-polygon-tests.ts
  types/d3-polygon/index.d.ts
  types/d3-polygon/tsconfig.json
  types/d3-polygon/tslint.json
Labels: Merge:Express, Owner Approved, Revision needed

#25021 Add type definitions for Power BI Custom Visuals API (powerbi-visuals-tools)
  types/powerbi-visuals-tools/index.d.ts
  types/powerbi-visuals-tools/powerbi-visuals-tools-tests.ts
  types/powerbi-visuals-tools/tsconfig.json
  types/powerbi-visuals-tools/tslint.json
Labels: New Definition, Revision needed

#25542 feat: Add declarations for andyhu/transliteration
  types/transliteration/index.d.ts
  types/transliteration/transliteration-tests.ts
  types/transliteration/tsconfig.json
  types/transliteration/tslint.json
Labels: New Definition, Other Approved

#25467 fix: add `defined` method on `is` npm module
  types/is/index.d.ts
  types/is/is-tests.ts
Labels: Merge:Express, Owner Approved

#25371 [react-faux-dom] Omit ReactFauxDomProps
  types/react-faux-dom/index.d.ts
  types/react-faux-dom/tslint.json
Labels: Merge:Express, Owner Approved, Revision needed

#25282 [ember-data] - improve relationship options
  types/ember-data/index.d.ts
  types/ember-data/test/model.ts
Labels: Merge:Express, Owner Approved, Revision needed

#25252 [Leaflet Draw] Add missing events, functions & namespaces
  types/leaflet-draw/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#25462 chart.js: Add options for time cartesian axis.
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#25480 Add support of subgroupStack on DataGroup
  types/vis/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#25405 [auth0] Add additional Authenticator class definitions and Managers.
  types/auth0/index.d.ts
Labels: Merge:Express, Owner Approved

#25550 Add type definitions for promise-map-limit package
  .github/CODEOWNERS
  types/promise-map-limit/index.d.ts
  types/promise-map-limit/promise-map-limit-tests.ts
  types/promise-map-limit/tsconfig.json
  types/promise-map-limit/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#25458 [mongoose] Fix: The `mongoose.pluralize(..)` function now gets/sets the function to pluralize collection names
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#25492 materialize-css: Add missing declarations and tests
  types/materialize-css/autocomplete.d.ts
  types/materialize-css/carousel.d.ts
  types/materialize-css/character-counter.d.ts
  types/materialize-css/chips.d.ts
  types/materialize-css/collapsible.d.ts
  types/materialize-css/common.d.ts
  types/materialize-css/datepicker.d.ts
  types/materialize-css/dropdown.d.ts
  types/materialize-css/fab.d.ts
  types/materialize-css/formselect.d.ts
  types/materialize-css/index.d.ts
  types/materialize-css/inputfields.d.ts
  types/materialize-css/materialbox.d.ts
  types/materialize-css/modal.d.ts
  types/materialize-css/parallax.d.ts
  types/materialize-css/pushpin.d.ts
  types/materialize-css/range.d.ts
  types/materialize-css/scrollspy.d.ts
  types/materialize-css/sidenav.d.ts
  types/materialize-css/slider.d.ts
  types/materialize-css/tabs.d.ts
  types/materialize-css/taptarget.d.ts
  types/materialize-css/test/autocomplete.test.ts
  types/materialize-css/test/carousel.test.ts
  types/materialize-css/test/character-counter.test.ts
  types/materialize-css/test/chips.test.ts
  types/materialize-css/test/collapsible.test.ts
  types/materialize-css/test/common.test.ts
  types/materialize-css/test/datepicker.test.ts
  types/materialize-css/test/dropdown.test.ts
  types/materialize-css/test/fab.test.ts
  types/materialize-css/test/formselect.test.ts
  types/materialize-css/test/inputfields.test.ts
  types/materialize-css/test/materialbox.test.ts
  types/materialize-css/test/materialize-css-global.test.ts
  types/materialize-css/test/materialize-css-jquery.test.ts
  types/materialize-css/test/materialize-css-module.test.ts
  types/materialize-css/test/modal.test.ts
  types/materialize-css/test/parallax.test.ts
  types/materialize-css/test/pushpin.test.ts
  types/materialize-css/test/range.test.ts
  types/materialize-css/test/scrollspy.test.ts
  types/materialize-css/test/sidenav.test.ts
  types/materialize-css/test/slider.test.ts
  types/materialize-css/test/tabs.test.ts
  types/materialize-css/test/taptarget.test.ts
  types/materialize-css/test/timepicker.test.ts
  types/materialize-css/test/toast.test.ts
  types/materialize-css/test/tooltip.test.ts
  types/materialize-css/test/waves.test.ts
  types/materialize-css/timepicker.d.ts
  types/materialize-css/toast.d.ts
  types/materialize-css/tooltip.d.ts
  types/materialize-css/tsconfig.json
  types/materialize-css/waves.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#25399 [eslint] create NodeListener and extend RuleListener
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#25484 types/he: version 1.1.1 updates, include `decimal` in EncodeOptions interface
  types/he/he-tests.ts
  types/he/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25481 Fix react-autocomplete renderItem prop type
  types/react-autocomplete/index.d.ts
Labels: Merge:LGTM, Other Approved, Unowned

#25437 Removing type definitions that do not exist
  types/mapbox-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25424 ramda: Use typescript@2.8
  types/ramda/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25423 Set redux-batched-subscribe semver limit to <4.0.0
  types/redux-batched-subscribe/package.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#25421 es6-shim: Avoid conflict with global PropertyKey type
  types/es6-shim/es6-shim-tests.ts
  types/es6-shim/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25044 firefox-webext-browser: remove bookmark.import/export
  types/firefox-webext-browser/firefox-webext-browser-tests.ts
  types/firefox-webext-browser/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Revision needed

#25295 mapbox-gl: Added missing property to the 'CirclePaint' interface.
  types/mapbox-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25323 [react-bootstrap-daterangepicker] containerClass, containerStyles
  types/react-bootstrap-daterangepicker/index.d.ts
  types/react-bootstrap-daterangepicker/react-bootstrap-daterangepicker-tests.tsx
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#25324 Update react-redux-i18n for react-redux 5.0.18 types
  types/react-redux-i18n/index.d.ts
  types/react-redux-i18n/package.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#25347 [react-table] Add support for Functional Rendering
  types/react-table/index.d.ts
  types/react-table/react-table-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#25383 [ArangoDB] Fix collection properties argument & index fields type
  types/arangodb/arangodb-tests.ts
  types/arangodb/index.d.ts
Labels: Author is Owner, Unowned

#25388 [react] Remove as attribute from AnchorHTMLAttributes
  types/react/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#25398 update ansi-styles to 3.2.1
  types/ansi-styles/ansi-styles-tests.ts
  types/ansi-styles/escape-code.d.ts
  types/ansi-styles/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25407 node: Add WHATWG URL API types for v6
  types/node/v6/index.d.ts
  types/node/v6/node-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25415 Meteor universe i18n
  types/meteor-univserse-i18n/index.d.ts
  types/meteor-univserse-i18n/meteor-univserse-i18n-tests.ts
  types/meteor-univserse-i18n/tsconfig.json
  types/meteor-univserse-i18n/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#25416 Add the atob & btoa npm module definitions
  types/atob/atob-tests.ts
  types/atob/index.d.ts
  types/atob/tsconfig.json
  types/atob/tslint.json
  types/btoa/btoa-tests.ts
  types/btoa/index.d.ts
  types/btoa/tsconfig.json
  types/btoa/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved, Revision needed

#25420 core-js: Comment out dict[sym] test
  types/core-js/core-js-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25228 [react-redux]: decoration target props should not extend injected props, contravariance issue
  types/mirrorx/index.d.ts
  types/next-redux-wrapper/index.d.ts
  types/react-intl-redux/index.d.ts
  types/react-redux-toastr/index.d.ts
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
  types/react-redux/tsconfig.json
  types/react-router-redux/index.d.ts
  types/redux-auth-wrapper/index.d.ts
  types/redux-devtools/index.d.ts
  types/redux-form/v6/index.d.ts
  types/redux-form/v6/redux-form-tests.tsx
  types/redux-little-router/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#25572 New types for redux-shortcuts 0.0.3
  types/redux-shortcuts/index.d.ts
  types/redux-shortcuts/package.json
  types/redux-shortcuts/redux-shortcuts-tests.ts
  types/redux-shortcuts/tsconfig.json
  types/redux-shortcuts/tslint.json
Labels: New Definition, Revision needed

#25580 Add 'external' to node v6, v7, and v8 MemoryUsage interface
  types/node/index.d.ts
  types/node/v6/index.d.ts
  types/node/v7/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Popular package, Revision needed

#25344 Fix version comment in material-ui, should be 0.20
  types/material-ui/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25524 pumpify: add ctor args, duplexify members, tests
  types/pumpify/index.d.ts
  types/pumpify/pumpify-tests.ts
  types/pumpify/tsconfig.json
Labels: Needs more info, Unowned

#25587 [svgo] Export Options type
  types/svgo/index.d.ts
  types/svgo/svgo-tests.ts
Labels: Awaiting reviewer feedback

#25504 fix(storybook__addon-storyshots): improve imageSnapshot options
  types/storybook__addon-storyshots/index.d.ts
  types/storybook__addon-storyshots/storybook__addon-storyshots-tests.ts
Labels: Needs more info, Revision needed, Unowned

#25568 Add types for graphql-depth-limit
  types/graphql-depth-limit/graphql-depth-limit-tests.ts
  types/graphql-depth-limit/index.d.ts
  types/graphql-depth-limit/tsconfig.json
  types/graphql-depth-limit/tslint.json
Labels: New Definition, Revision needed

#25286 [redux-actions@2.3.0] More specific definitions
  types/redux-actions/index.d.ts
  types/redux-actions/redux-actions-tests.ts
Labels: Awaiting reviewer feedback

#25476 daterangepicker: typings for v3.0.1
  types/daterangepicker/daterangepicker-tests.ts
  types/daterangepicker/index.d.ts
  types/daterangepicker/tslint.json
  types/react-bootstrap-daterangepicker/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25482 [react-router] Add generic param for staticContext
  types/react-router/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#25511 hexo-log: Remove dependencies on test frameworks
  types/hexo-log/hexo-log-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#25006 A-Frame additions
  types/aframe/aframe-tests.ts
  types/aframe/index.d.ts
  types/aframe/tslint.json
Labels: Merge:Express, Owner Approved, Revision needed

#25588 tough-cookie: add store parameter to deserializeSync interface
  types/tough-cookie/index.d.ts
  types/tough-cookie/tough-cookie-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#25590 [react-navigation] Add missing initialRouteKey property on NavigationStackRouterConfig
  types/react-navigation/index.d.ts
  types/react-navigation/react-navigation-tests.tsx
Labels: Merge:Express, Owner Approved

#25599 Add gulp-svgmin types
  types/gulp-svgmin/gulp-svgmin-tests.ts
  types/gulp-svgmin/index.d.ts
  types/gulp-svgmin/tsconfig.json
  types/gulp-svgmin/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#25606 [chai-spies] Added missing iteration assertions
  types/chai-spies/chai-spies-tests.ts
  types/chai-spies/index.d.ts
Labels: Merge:Express, Owner Approved

#25607 [ArangoDB] Update geo index type
  types/arangodb/arangodb-tests.ts
  types/arangodb/index.d.ts
Labels: Author is Owner, Unowned

#25610 Node: remove myself as author
  types/node/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#25611 Remove typings of ids package
  notNeededPackages.json
  types/ids/ids-tests.ts
  types/ids/index.d.ts
  types/ids/tsconfig.json
  types/ids/tslint.json
Labels: Merge:Express, Owner Approved
