Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2019-07, with the labels that each got.

#36563 [@types/relay-runtime] Add some missing properties
  types/relay-runtime/index.d.ts
Labels: Awaiting reviewer feedback

#36554 @types/react-native: fix StyleSheet.create() styles parameter
  types/react-native/index.d.ts
  types/react-native/test/stylesheet-create.tsx
  types/react-native/tsconfig.json
Labels: Awaiting reviewer feedback, Popular package

#36395 Type for Cordova SQLite pouchdb adapter
  types/pouchdb-adapter-cordova-sqlite/index.d.ts
  types/pouchdb-adapter-cordova-sqlite/pouchdb-adapter-cordova-sqlite-tests.ts
  types/pouchdb-adapter-cordova-sqlite/tsconfig.json
  types/pouchdb-adapter-cordova-sqlite/tslint.json
  types/pouchdb/index.d.ts
Labels: New Definition, Revision needed

#36259 [eventsource] compatibility with non-DOM consumers
  types/eventsource/dom-monkeypatch.d.ts
  types/eventsource/index.d.ts
  types/eventsource/lib/eventsource-polyfill/index.d.ts
  types/eventsource/test/eventsource-dom.test.ts
  types/eventsource/test/eventsource-nodejs.test.ts
  types/eventsource/tsconfig.json
Labels: Owner Approved, Revision needed

#36099 Export SOCKET_KEY from feathersjs/socket.io
  types/feathersjs__socketio/feathersjs__socketio-tests.ts
  types/feathersjs__socketio/index.d.ts
Labels: Revision needed

#36157 [@types/enzyme] adding `invoke` definition to support enzyme@3.10
  types/enzyme/enzyme-tests.tsx
  types/enzyme/index.d.ts
Labels: Owner Approved, Popular package, Revision needed

#36211 Add typings for connect-trim-body npm module
  types/connect-trim-body/connect-trim-body-tests.ts
  types/connect-trim-body/index.d.ts
  types/connect-trim-body/tsconfig.json
  types/connect-trim-body/tslint.json
Labels: New Definition, Revision needed

#36533 Add new type definitions for parquetjs
  types/parquetjs/index.d.ts
  types/parquetjs/lib/field.interface.d.ts
  types/parquetjs/lib/metadata.interface.d.ts
  types/parquetjs/lib/reader.d.ts
  types/parquetjs/lib/row.interface.d.ts
  types/parquetjs/lib/rowBuffer.interface.d.ts
  types/parquetjs/lib/schema.d.ts
  types/parquetjs/lib/schema.interface.d.ts
  types/parquetjs/lib/shred.d.ts
  types/parquetjs/lib/writer.d.ts
  types/parquetjs/parquet.d.ts
  types/parquetjs/parquetjs-tests.ts
  types/parquetjs/tsconfig.json
  types/parquetjs/tslint.json
Labels: New Definition, Revision needed

#36576 [@types/load-google-maps-api] Update for 2.0
  types/load-google-maps-api/index.d.ts
  types/load-google-maps-api/load-google-maps-api-tests.ts
Labels: Author is Owner, Merge:Express

#36573 Add pino-std-serializers
  types/oracledb/index.d.ts
  types/pino-std-serializers/index.d.ts
  types/pino-std-serializers/pino-std-serializers-tests.ts
  types/pino-std-serializers/tsconfig.json
  types/pino-std-serializers/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, New Definition

#36559 googlemaps - google.maps.Map.getProjection() can return null
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#36556 Inboxsdk update
  types/inboxsdk/inboxsdk-tests.ts
  types/inboxsdk/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36544 Yup: Allow specific type with oneOf and mixed schema
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#36568 [Dockerode] Add Mounts field to ContainerInfo
  types/dockerode/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36548 feat(chance): add missing string/character options
  types/chance/chance-tests.ts
  types/chance/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36529 [office-js-preview] (Outlook) Update InternetHeaders
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#36540 [Luxon] fix ToRelativeUnit type
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#36425 [hapi-pino] Support scoped Hapi package, update for 6.x
  types/hapi-pino/hapi-pino-tests.ts
  types/hapi-pino/index.d.ts
  types/hapi-pino/tsconfig.json
Labels: Merge:Express, Owner Approved

#36522 [webappsec-credential-management] Align AuthenticatorSelectionCriteria with spec
  types/webappsec-credential-management/index.d.ts
  types/webappsec-credential-management/webappsec-credential-management-tests.ts
Labels: Merge:Express, Owner Approved

#36543 [mousetrap] Fix different from the actual return types
  types/mousetrap/index.d.ts
  types/mousetrap/test/index.ts
Labels: Merge:Express, Owner Approved

#36550 [is-number] Added `num is number` user defined type guard as return type
  types/is-number/index.d.ts
  types/is-number/is-number-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#36485 [@types/express-http-proxy] Add proxyReqBodyDecorator property to ProxyOptions
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#36164 yet other fixes for swagger types
  types/swagger-schema-official/index.d.ts
  types/swagger-schema-official/swagger-schema-official-tests.ts
  types/swagger-schema-official/tslint.json
Labels: Author is Owner, Merge:Express, Other Approved, Owner Approved

#36510 [@types/underscore] Fix #36308 - underscore has bad chain typings fix only for function 'map' (#36319)
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#36504 [@types-baseui] fix button size interface
  types/baseui/baseui-tests.tsx
  types/baseui/button/index.d.ts
Labels: Merge:Express, Owner Approved

#36399 ramda: improve applySpec typing
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
  types/ramda/tools.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#36574 [@types/pixelmatch] Add missing types added in v5.0
  types/pixelmatch/index.d.ts
Labels: Merge:Express, Owner Approved

#36267 Improve cast.framework.ContentProtection from
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36572 Add @types/feather-route-matcher
  types/feather-route-matcher/feather-route-matcher-tests.ts
  types/feather-route-matcher/index.d.ts
  types/feather-route-matcher/tsconfig.json
  types/feather-route-matcher/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36560 add typings for node-gzip
  types/node-gzip/index.d.ts
  types/node-gzip/node-gzip-tests.ts
  types/node-gzip/tsconfig.json
  types/node-gzip/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36557 Add types/tests for grid-template-parser
  types/grid-template-parser/grid-template-parser-tests.ts
  types/grid-template-parser/index.d.ts
  types/grid-template-parser/tsconfig.json
  types/grid-template-parser/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36553 [audiobuffer-to-wav] Add definition for audiobuffer-to-wav
  types/audiobuffer-to-wav/audiobuffer-to-wav-tests.ts
  types/audiobuffer-to-wav/index.d.ts
  types/audiobuffer-to-wav/tsconfig.json
  types/audiobuffer-to-wav/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36549 Add types/tests for deindent
  types/deindent/deindent-tests.ts
  types/deindent/index.d.ts
  types/deindent/tsconfig.json
  types/deindent/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36547 [@wordpress/block-serialization-default-parser] add new definitions
  types/wordpress__block-serialization-default-parser/index.d.ts
  types/wordpress__block-serialization-default-parser/tsconfig.json
  types/wordpress__block-serialization-default-parser/tslint.json
  types/wordpress__block-serialization-default-parser/wordpress__block-serialization-default-parser-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#36538 [@wordpress/shortcode] add new definitions
  types/wordpress__shortcode/index.d.ts
  types/wordpress__shortcode/tsconfig.json
  types/wordpress__shortcode/tslint.json
  types/wordpress__shortcode/wordpress__shortcode-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#36535 [@wordpress/is-shallow-equal] add new definitions
  types/wordpress__is-shallow-equal/index.d.ts
  types/wordpress__is-shallow-equal/tsconfig.json
  types/wordpress__is-shallow-equal/tslint.json
  types/wordpress__is-shallow-equal/wordpress__is-shallow-equal-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#35892 [ramda] Update `pathOr` return typings to match `path`
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36580 Yup: Allow for Ref in oneOf()
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#36552 Add declarations and documentation for missing methods in "double-ended-queue"
  types/double-ended-queue/double-ended-queue-tests.ts
  types/double-ended-queue/index.d.ts
Labels: Merge:Express, Owner Approved

#36542 [mailgun-js] add testMode and testModeLogger to Mailgun constructor for version 0.…
  types/mailgun-js/index.d.ts
  types/mailgun-js/mailgun-js-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#35895 UUID: reverse overloaded intersection so that ReturnType<T> will come up with string
  types/uuid/interfaces.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36016 FEAT(koa): add ExtendableContext interface to extends context
  types/koa/index.d.ts
  types/koa/koa-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35905 [Ramda] fix construct, juxt, head, tail and last type definitions
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36328 [storybook__addon-knobs] Add missing type overload for optionsKnob
  types/storybook__addon-knobs/index.d.ts
  types/storybook__addon-knobs/storybook__addon-knobs-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36462 [@types/vis] add getBaseEdges definition
  types/vis/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36460 [@types/invariant] Make invariant(false) return `never`
  types/invariant/index.d.ts
  types/invariant/invariant-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36442 fix enzyme's ShallowRendererProps interface
  types/enzyme/enzyme-tests.tsx
  types/enzyme/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36261 feat(urijs): compat with non-dom consumers
  types/urijs/dom-monkeypatch.d.ts
  types/urijs/index.d.ts
  types/urijs/test/urijs-dom.test.ts
  types/urijs/test/urijs-nodejs.test.ts
  types/urijs/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#36386 [factory-girl] fixed seq method and adapted definitions to fix correction
  types/factory-girl/factory-girl-tests.ts
  types/factory-girl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36391 modify & fix some definition for package 'markdown-it'. and update version to '0.0.8'
  types/markdown-it/lib/parser_core.d.ts
  types/markdown-it/lib/rules_core/state_core.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36401 [auth0] Add missing fields for the Client interface
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36410 [@types/gapi] Update Docs with updated Google API Client webpage/owner
  types/gapi/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36423 [@types/mongoose] Property 'disconnected' does not exist on type 'ConnectionStates'.
  types/mongoose/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36445 Fix linting types which should be optional
  types/codemirror/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36430 Update acquire() and lock() to support multi locks
  types/redlock/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36586 [k6] Expose to autoimport
  types/k6/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36584 [office-js] [office-js-preview] Update platforms
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36583 [office-js] [office-js-preview] (Access) Deprecate or remove references
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#36499 [mailgun-js] Add types for generic requests
  types/mailgun-js/index.d.ts
  types/mailgun-js/mailgun-js-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#36527 Fix Stripe payment intent status
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36595 Update README to require spaces
  README.es.md
  README.md
Labels: Unowned

#36581 R.zip compatible with a tuple array
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#36571 Add missing typings
  types/react-bootstrap/lib/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36511 [@types/http-assert] Fix types for methods ok, strictEqual, notStrictEqual, deepEqual, notDeepEqual
  types/http-assert/http-assert-tests.ts
  types/http-assert/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36599 new version update
  types/flexmonster/index.d.ts
Labels: Author is Owner, Merge:Express

#36596 Add lossless-json types
  types/lossless-json/index.d.ts
  types/lossless-json/lossless-json-tests.ts
  types/lossless-json/tsconfig.json
  types/lossless-json/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36534 [@wordpress/hooks] add new definitions
  types/wordpress__hooks/index.d.ts
  types/wordpress__hooks/tsconfig.json
  types/wordpress__hooks/tslint.json
  types/wordpress__hooks/wordpress__hooks-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#36594 Add Type Definitions for imsi-grok
  types/imsi-grok/imsi-grok-tests.ts
  types/imsi-grok/index.d.ts
  types/imsi-grok/tsconfig.json
  types/imsi-grok/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36458 [classnames] improve types for `classnames/bind` and add types for `classnames/dedupe`
  types/classnames/bind.d.ts
  types/classnames/classnames-tests.ts
  types/classnames/dedupe.d.ts
  types/classnames/index.d.ts
  types/classnames/tsconfig.json
  types/classnames/types.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36415 papaparse: add transformHeader option
  types/papaparse/index.d.ts
  types/papaparse/papaparse-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36474 Add wrappedComponentRef prop to react-router withRouter()
  types/react-router/index.d.ts
  types/react-router/test/WithRouter.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36477 ICanvasDimensions add string type
  types/fabric/fabric-impl.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35890 [dompurify] Add typing for factory function
  types/dompurify/index.d.ts
  types/dompurify/test/dompurify-namespace-tests.ts
  types/dompurify/test/dompurify-tests.ts
  types/dompurify/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#36409 Added type definition for `codegen.macro`
  types/codegen.macro/codegen.macro-tests.ts
  types/codegen.macro/index.d.ts
  types/codegen.macro/tsconfig.json
  types/codegen.macro/tslint.json
Labels: New Definition, Revision needed

#36608 [@types/ts-nameof] Update to 3.2
  types/ts-nameof/index.d.ts
  types/ts-nameof/ts-nameof-tests.ts
Labels: Author is Owner, Merge:Express

#36605 Fabricjs - new/updated definitions. Updated to latest 3.x
  types/fabric/fabric-impl.d.ts
  types/fabric/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36600 Updated type definitions for react-image-crop
  types/react-image-crop/index.d.ts
  types/react-image-crop/test/react-image-crop-module-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36578 [office-js-preview] Updating office-js-preview with beta CDN content
  types/office-js-preview/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#36603 [office-js and office-js-preview] add missing property to AsyncResult
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Revision needed

#36598 [@types/tar] Add extract options gid, noMtime, transform and onentry
  types/tar/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36611 fix(chart.js): add missing ChartTooltipItem fields
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36545 export SupportedSocialApps type
  types/react-native-share/index.d.ts
Labels: Merge:Express, Owner Approved

#36601 [@types/country-data] Add missing keys to countries export
  types/country-data/country-data-tests.ts
  types/country-data/index.d.ts
Labels: Merge:Express, Owner Approved

#36614 [eventsource] compatibility with non-DOM consumers cont.
  types/eventsource/dom-monkeypatch.d.ts
  types/eventsource/test/eventsource-dom.test.ts
  types/eventsource/test/eventsource-nodejs.test.ts
Labels: Merge:Express, Owner Approved

#36507 Add withTheme definition for react-jsonschema-form
  types/react-jsonschema-form/index.d.ts
  types/react-jsonschema-form/react-jsonschema-form-tests.tsx
  types/react-jsonschema-form/tsconfig.json
Labels: Merge:Express, Owner Approved

#36490 @Types/FeedParser Fix typing for Enclosures
  types/feedparser/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#36617 stubby: new definitions
  types/stubby/index.d.ts
  types/stubby/stubby-tests.ts
  types/stubby/tsconfig.json
  types/stubby/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36615 Add @postlight/mercury-parser type definitions
  types/postlight__mercury-parser/index.d.ts
  types/postlight__mercury-parser/postlight__mercury-parser-tests.ts
  types/postlight__mercury-parser/tsconfig.json
  types/postlight__mercury-parser/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36602 new package: resolve-protobuf-schema
  types/resolve-protobuf-schema/index.d.ts
  types/resolve-protobuf-schema/resolve-protobuf-schema-tests.ts
  types/resolve-protobuf-schema/tsconfig.json
  types/resolve-protobuf-schema/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36495 Add support for auto pagination in Stripe
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
  types/stripe/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36506 [node] Add shell as option for execFile
  types/node/child_process.d.ts
  types/node/test/child_process.ts
  types/node/v10/child_process.d.ts
  types/node/v11/child_process.d.ts
  types/node/v8/base.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36491 Improve cast.framework.messages.PlayerState in chromecast-caf-receiver
  types/chromecast-caf-receiver/cast.framework.messages.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Where is Travis?

#36282 Include "dom" via triple-slash reference in @types/superagent: Fixes #12044
  types/promisify-supertest/index.d.ts
  types/simple-cw-node/index.d.ts
  types/superagent-bunyan/index.d.ts
  types/superagent-no-cache/index.d.ts
  types/superagent-prefix/index.d.ts
  types/superagent/index.d.ts
  types/supertest/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#36416 Adds type definitions for 'node-zendesk'
  types/node-zendesk/index.d.ts
  types/node-zendesk/node-zendesk-tests.ts
  types/node-zendesk/tsconfig.json
  types/node-zendesk/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#36619 add koa-graphql types
  types/koa-graphql/index.d.ts
  types/koa-graphql/koa-graphql-tests.ts
  types/koa-graphql/tsconfig.json
  types/koa-graphql/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36525 [react] Support <a ping> attribute
  types/react/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36520 [node] add dns promise API types
  types/node/dns.d.ts
  types/node/v10/dns.d.ts
  types/node/v11/dns.d.ts
  types/node/v11/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36516 fix uni.upx2px missing parameter
  types/uni-app/lib/uni.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36513 Add invoices.finalizeInvoice to Stripe
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36364 Add new definitions for [@types/splitpanes]
  types/splitpanes/index.d.ts
  types/splitpanes/package.json
  types/splitpanes/splitpanes-tests.ts
  types/splitpanes/tsconfig.json
  types/splitpanes/tslint.json
  types/vue-splitpane/index.d.ts
  types/vue-splitpane/package.json
  types/vue-splitpane/tsconfig.json
  types/vue-splitpane/tslint.json
  types/vue-splitpane/vue-splitpane-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#36528 Cheerio - Added startIndex property
  types/cheerio/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#36636 [react-native] update/add new accessibility properties
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Popular package, Revision needed

#36536 [urijs] Ensure compatibility with node.js environment
  types/urijs/index.d.ts
Labels: Merge:Express, Owner Approved

#36562 feat: node v12.5
  types/marko/src/runtime/html/Template.d.ts
  types/node/child_process.d.ts
  types/node/constants.d.ts
  types/node/globals.d.ts
  types/node/index.d.ts
  types/node/node-tests.ts
  types/node/stream.d.ts
  types/node/test/child_process.ts
  types/node/test/global.ts
  types/node/test/process.ts
  types/node/test/tls.ts
  types/node/test/v8.ts
  types/node/test/worker_threads.ts
  types/node/tls.d.ts
  types/node/v8.d.ts
  types/node/worker_threads.d.ts
  types/readable-stream/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36607 Added typing defs for mathjs-6.0
  types/mathjs/index.d.ts
  types/mathjs/mathjs-tests.ts
Labels: Merge:Express, Owner Approved

#36681 [table] adds missing wrapWord property
  types/table/index.d.ts
Labels: Merge:Express, Owner Approved

#36680 [mui-datatables] add missing customRowRender option
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
Labels: Merge:Express, Owner Approved

#36662 [stripe-v3] Support for handleCardSetup and SetupIntent
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#36610 lodash: Consider rest operator for intersectionBy
  types/lodash/common/array.d.ts
  types/lodash/lodash-tests.ts
  types/lodash/ts3.1/common/array.d.ts
  types/lodash/ts3.1/lodash-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#36716 [styled-system] Update typings to v5 (continued)
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Awaiting reviewer feedback

#36639 Add typings for cometd's BinaryExtension
  types/cometd/BinaryExtension/index.d.ts
  types/cometd/cometd-tests.ts
  types/cometd/tsconfig.json
Labels: Merge:Express, Owner Approved

#36637 [ioredis] Added typings for pttl
  types/ioredis/index.d.ts
  types/ioredis/v3/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36623 [arcgis-js-api] Update for version 3.29
  types/arcgis-js-api/v3/index.d.ts
Labels: Merge:Express, Owner Approved

#36629 Update diff2html configuration options typings
  types/diff2html/diff2html-tests.ts
  types/diff2html/index.d.ts
Labels: Author is Owner, Merge:Express

#36649 Allow interpolation in fontWeight + fix selector usage
  types/styled-system__css/index.d.ts
  types/styled-system__css/styled-system__css-tests.ts
Labels: Author is Owner, Merge:Express

#36659 Add optional params to Parse PushData object
  types/parse/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36657 fix(node): add missing vm and import.meta typings
  types/node/globals.d.ts
  types/node/node-tests.ts
  types/node/test/vm.ts
  types/node/tsconfig.json
  types/node/vm.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#36668 [aws-lambda] Add missing fields on CognitoUserPoolTriggerEvent
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#36675 (office.js and office.preview.js) reverse mistaken change
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#36683 [@wordpress/components] fix incorrectly typed "icon" prop in <IconButton />
  types/wordpress__components/icon-button/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Author is Owner, Merge:Express

#36701 Yup: Add Id<T> type to make inferred types more readable
  types/yup/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#36638 [@wordpress/blocks] misc scattered fixes found in the wild
  types/wordpress__blocks/api/children.d.ts
  types/wordpress__blocks/api/factory.d.ts
  types/wordpress__blocks/api/registration.d.ts
  types/wordpress__blocks/index.d.ts
  types/wordpress__blocks/store/actions.d.ts
  types/wordpress__blocks/store/selectors.d.ts
  types/wordpress__blocks/wordpress__blocks-tests.tsx
Labels: Author is Owner, Merge:Express

#36634 Add support for pay_immediately=false when updating Stripe subscriptions
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#36707 [Crossfilter] Change return type of group.all() to a readonly array
  types/crossfilter/crossfilter-tests.ts
  types/crossfilter/index.d.ts
Labels: Merge:Express, Owner Approved

#36711 Added initialNumToRender prop
  types/react-native-snap-carousel/index.d.ts
Labels: Merge:Express, Owner Approved

#36714 @types/bootstrap dropdown added missing parameter options
  types/bootstrap/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#36723 RSocket - Fix incorrect return types
  types/rsocket-core/RSocketClient.d.ts
  types/rsocket-flowable/Single.d.ts
  types/rsocket-tcp-server/RSocketTCPServer.d.ts
Labels: Author is Owner, Merge:Express

#36721 react-tagsinput: allow `addKeys` to be `string[]`
  types/react-tagsinput/index.d.ts
Labels: Merge:Express, Owner Approved

#36719 @types/http-assert version up
  types/http-assert/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#36243 [ldapjs-client] Basic Typings
  types/ldapjs-client/index.d.ts
  types/ldapjs-client/ldapjs-client-tests.ts
  types/ldapjs-client/tsconfig.json
  types/ldapjs-client/tslint.json
Labels: New Definition, Revision needed

#36609 Adding type assertions for collections as a whole
  types/nedb/index.d.ts
Labels: Merge:Express, Owner Approved

#36686 Added payment_method to Stripe's IPaymentIntentConfirmOptions
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36679 [@types/stripe] Correct types for invoice.charge and invoiceItem.invoice
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#36627 Update HTTPS config options for superagent
  types/superagent/index.d.ts
  types/superagent/superagent-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#36582 [@types/stripe] Add external_accounts to IAccount
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#36590 [@types/webappsec-credential-management] Change RP ID to optional.
  types/webappsec-credential-management/index.d.ts
Labels: Merge:Express, Owner Approved

#36632 [@types/stripe] Add support for Credit Notes
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#36606 [@types/stripe] Add missing "card" field to ISource
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#36733 rsocket - allow partial in clientconfig and add tests
  types/rsocket-core/RSocketClient.d.ts
  types/rsocket-core/index.d.ts
  types/rsocket-flowable/index.d.ts
  types/rsocket-tcp-client/index.d.ts
  types/rsocket-tcp-client/rsocket-tcp-client-tests.ts
  types/rsocket-tcp-client/tsconfig.json
  types/rsocket-tcp-server/index.d.ts
  types/rsocket-tcp-server/rsocket-tcp-server-tests.ts
  types/rsocket-tcp-server/tsconfig.json
  types/rsocket-types/index.d.ts
  types/rsocket-websocket-client/index.d.ts
  types/rsocket-websocket-server/index.d.ts
Labels: Author is Owner, Merge:Express

#36664 Update type definitions for react-jsonschema-form
  types/react-jsonschema-form/index.d.ts
  types/react-jsonschema-form/react-jsonschema-form-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#36622 [@types/consolidate] union engines + requires mapping
  types/consolidate/consolidate-tests.ts
  types/consolidate/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36613 Mark chart data prop as ReadonlyArray
  types/recharts/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36589 [@types/mapbox-gl] Add ImageSource.updateImage
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#36565 [@types/stream-mock] remove stream-mock definitions
  notNeededPackages.json
  types/stream-mock/index.d.ts
  types/stream-mock/stream-mock-tests.ts
  types/stream-mock/tsconfig.json
  types/stream-mock/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#36558 Update sinon-test definitions
  types/sinon-test/index.d.ts
  types/sinon-test/sinon-test-tests.ts
  types/sinon-test/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#36648 [just-safe-get] New package definition
  types/just-safe-get/index.d.ts
  types/just-safe-get/just-safe-get-tests.ts
  types/just-safe-get/tsconfig.json
  types/just-safe-get/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#36715 [phoenix] Fix SocketConnectOptions for phoenix >= 1.4.3
  types/phoenix/index.d.ts
  types/phoenix/phoenix-tests.ts
Labels: Merge:Express, Owner Approved

#36652 [bulll] add missing variable, function definitions
  types/bull/bull-tests.tsx
  types/bull/index.d.ts
Labels: Merge:Express, Owner Approved

#36728 Update tests in preparation for TS #32260
  types/storage-helper/storage-helper-tests.ts
  types/wordpress__hooks/wordpress__hooks-tests.ts
Labels: Merge:Express, Owner Approved

#36626 [recharts] Added missing baseValue prop
  types/recharts/index.d.ts
Labels: Revision needed
