Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2019-05, with the labels that each got.

#35047 Added convert-string
  types/convert-string/convert-string-tests.ts
  types/convert-string/index.d.ts
  types/convert-string/tsconfig.json
  types/convert-string/tslint.json
Labels: New Definition, Revision needed

#35085 [@types/victory] Add categories props variations and horizontal props for VictoryChart
  types/victory/index.d.ts
  types/victory/victory-tests.tsx
Labels: Merge:Express, Owner Approved

#35120 Mongodb: Fix typos: Cursor#max and Cursor#min
  types/mongodb/index.d.ts
  types/mongodb/mongodb-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#35123 [mui-datatables]
  types/mui-datatables/index.d.ts
Labels: Merge:Express, Owner Approved

#35115 [yeoman-generator] add async and env.adapter
  types/yeoman-generator/index.d.ts
  types/yeoman-generator/yeoman-generator-tests.ts
Labels: Merge:Express, Owner Approved

#35078 [@types/styled-system] Improve styled-system
  types/styled-system/index.d.ts
  types/styled-system/package.json
  types/styled-system/styled-system-tests.tsx
Labels: Merge:Express, Owner Approved

#34919 [office-js, office-js-preview] Updating with 1.9 Requirement Set Preview to GA transition
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35118 Updated react-mentions to support v3.0
  types/react-mentions/index.d.ts
  types/react-mentions/react-mentions-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35132 [@types/next-server] add `next/amp` support
  types/next-server/amp.d.ts
  types/next-server/test/next-server-amp-tests.tsx
  types/next-server/tsconfig.json
  types/next/amp.d.ts
  types/next/tsconfig.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#34996 [mapbox-gl] Define explicit EaseToOptions
  types/mapbox-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35008 [Gokul] adds getters and setter for MaxNetworkRetries for Stripe
  types/stripe/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35100 jira-client -add getIssueWatchers method
  types/jira-client/index.d.ts
Labels: Merge:Express, Owner Approved

#35126 http-link-header: get, rel, and set return an array
  types/http-link-header/http-link-header-tests.ts
  types/http-link-header/index.d.ts
Labels: Merge:Express, Owner Approved

#35007 fix: getStoragetSync return value is incorrect.
  types/uni-app/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35142 [office-js, office-js-preview] Excel chart description changes
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35096 dropzone: add transformFile to DropzoneOptions
  types/dropzone/dropzone-tests.ts
  types/dropzone/index.d.ts
Labels: Merge:Express, Owner Approved

#35138 Add types for squirrelly
  types/squirrelly/index.d.ts
  types/squirrelly/squirrelly-tests.ts
  types/squirrelly/tsconfig.json
  types/squirrelly/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35136 Add types for djv
  types/djv/djv-tests.ts
  types/djv/index.d.ts
  types/djv/tsconfig.json
  types/djv/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34755 Update definitions for jest-when to match version @2.4.0
  types/jest-when/index.d.ts
  types/jest-when/jest-when-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#34768 Update index.d.ts
  types/react-native-video/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#34799 [ignite-ui] Update Ignite UI typing to 19.1 release version
  types/ignite-ui/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#34879 🐣🐇🐣 new package: kind-of 🎅
  types/kind-of/index.d.ts
  types/kind-of/kind-of-tests.ts
  types/kind-of/tsconfig.json
  types/kind-of/tslint.json
Labels: New Definition, Revision needed

#35026 [vue-tel-input] Add definitions for vue-tel-input
  types/vue-tel-input/index.d.ts
  types/vue-tel-input/package.json
  types/vue-tel-input/tsconfig.json
  types/vue-tel-input/tslint.json
  types/vue-tel-input/vue-tel-input-tests.ts
Labels: New Definition, Revision needed

#35016 [secure-random-password]: add types
  types/secure-random-password/index.d.ts
  types/secure-random-password/secure-random-password-tests.ts
  types/secure-random-password/tsconfig.json
  types/secure-random-password/tslint.json
Labels: New Definition, Revision needed

#34796 updated @types/react-image-crop to match the newest version of react-image-crop
  types/react-image-crop/index.d.ts
  types/react-image-crop/test/react-image-crop-global-tests.ts
  types/react-image-crop/test/react-image-crop-module-tests.tsx
Labels: Popular package, Revision needed

#34890 Introduce type definitions for jest-expect-message
  types/jest-expect-message/index.d.ts
  types/jest-expect-message/jest-expect-message-tests.ts
  types/jest-expect-message/tsconfig.json
  types/jest-expect-message/tslint.json
Labels: New Definition, Revision needed

#35030 Add express-async-wrap
  types/express-async-wrap/express-async-wrap-tests.ts
  types/express-async-wrap/index.d.ts
  types/express-async-wrap/tsconfig.json
  types/express-async-wrap/tslint.json
Labels: New Definition, Revision needed

#34997 Types definitions to simplecrawler module
  types/simplecrawler/cache-backend-fs.d.ts
  types/simplecrawler/cache.d.ts
  types/simplecrawler/cookies.d.ts
  types/simplecrawler/crawler.d.ts
  types/simplecrawler/index.d.ts
  types/simplecrawler/queue.d.ts
  types/simplecrawler/simplecrawler-tests.ts
  types/simplecrawler/tsconfig.json
  types/simplecrawler/tslint.json
Labels: New Definition, Revision needed

#35150 [@types/dialogflow] Changed invalid date time type to string
  types/dialogflow/index.d.ts
Labels: Merge:Express, Owner Approved

#35140 [@types/pusher-js] 4.3.0 - introduce new forceTLS & deprecate encrypted
  types/pusher-js/index.d.ts
  types/pusher-js/pusher-js-tests.ts
Labels: Merge:Express, Owner Approved

#35122 [duplexer2] Support regular stream.Duplex options
  types/duplexer2/duplexer2-tests.ts
  types/duplexer2/index.d.ts
Labels: Merge:Express, Owner Approved

#35121 [aws-lambda] Keys should be optional inside CloudFrontHeaders
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#35113 [@types/expo] Fix Segment analytics type definitions
  types/expo/index.d.ts
Labels: Merge:Express, Owner Approved

#35147 Added date prompts type
  types/prompts/index.d.ts
Labels: Merge:Express, Owner Approved

#35004 Types for the 'mixed.notType' property from the Yup library.
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#35130 fix(node): events.once resolves to type any[] instead of just any
  types/node/events.d.ts
  types/node/test/events.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#35029 [stripe] Add API version 2019-02-19 account props
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35032 Update dropzone "init" option "this" type
  types/dropzone/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35128 Updates to office-runtime package
  types/office-runtime/index.d.ts
  types/office-runtime/office-runtime-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#35168 [puppeteer] Fix misspelled paper format "Tabloid"
  types/puppeteer/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#35158 [@styled-system] Add missing props to Margin and Padding
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Merge:Express, Owner Approved

#35141 Adds namespace to options in loadable__component and loadable__server
  types/loadable__component/index.d.ts
  types/loadable__component/loadable__component-tests.tsx
  types/loadable__server/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#35139 fix(bull): add options to job
  types/bull/bull-tests.tsx
  types/bull/index.d.ts
Labels: Merge:Express, Owner Approved

#35149 mariasql: Fix export and namespace
  types/mariasql/index.d.ts
Labels: Merge:Express, Owner Approved

#35173 Add note regarding status of the DT-provided Sequelize types
  types/sequelize/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#35048 Updated @feathersjs/socket-commons
  types/feathersjs__socket-commons/feathersjs__socket-commons-tests.ts
  types/feathersjs__socket-commons/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35167 Add types for simmerjs
  types/simmerjs/index.d.ts
  types/simmerjs/simmerjs-tests.ts
  types/simmerjs/tsconfig.json
  types/simmerjs/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35164 Add types for chunk
  types/chunk/chunk-tests.ts
  types/chunk/index.d.ts
  types/chunk/tsconfig.json
  types/chunk/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35174 add yeoman-environment
  types/yeoman-environment/index.d.ts
  types/yeoman-environment/package.json
  types/yeoman-environment/tsconfig.json
  types/yeoman-environment/tslint.json
  types/yeoman-environment/yeoman-environment-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#35175 [sarif] update to Sarif Version 2.1.0-rtm.0
  types/sarif/index.d.ts
Labels: Author is Owner, Merge:Express

#35172 React-Slick: Added missing value to types that are supported in the documentation
  types/react-slick/index.d.ts
  types/react-slick/react-slick-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#35177 [meteor-astronomy] typing improved.
  types/meteor-astronomy/index.d.ts
Labels: Author is Owner, Merge:Express

#34289 [slate] support marks in schema
  types/slate/index.d.ts
  types/slate/slate-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#35114 [ember] all computed property descriptors are also PropertyDecorators
  types/ember__controller/index.d.ts
  types/ember__object/-private/types.d.ts
  types/ember__object/computed.d.ts
  types/ember__object/index.d.ts
  types/ember__object/test/octane.ts
  types/ember__service/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved

#35185 Included definition for proxyErrorHandler in express-http-proxy
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Merge:Express, Owner Approved

#35186 Remove spicy language from fb-emitter 🔥
  types/fbemitter/fbemitter-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#35192 Express http proxy refactorings
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35064 [react] Remove pshrmn from author list
  types/react/index.d.ts
Labels: Author is Owner, Popular package, The Travis CI build failed

#35187 [x-ray] add instance.abort parameter
  types/x-ray/index.d.ts
  types/x-ray/x-ray-tests.ts
Labels: Owner Approved, Revision needed

#35197 [IMP] redux-storage: support v4.1.2
  types/redux-storage-engine-jsurl/index.d.ts
  types/redux-storage-engine-localstorage/index.d.ts
  types/redux-storage/index.d.ts
  types/redux-storage/package.json
  types/redux-storage/redux-storage-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35067 StripeJS: Add elementType to StripeJS change event handler
  types/stripejs/element.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35133 Add logical negation
  types/mapbox-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#35188 [@types/victory] Add y0 data accessor to datable components
  types/victory/index.d.ts
  types/victory/victory-tests.tsx
Labels: Merge:Express, Owner Approved

#35072 [autoprefixer] Specify Stats object and stricter types
  types/autoprefixer/autoprefixer-tests.ts
  types/autoprefixer/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35199 Add types for inflation
  types/inflation/index.d.ts
  types/inflation/inflation-tests.ts
  types/inflation/tsconfig.json
  types/inflation/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35207 [react-dev-utils] Update for 9.0.0
  types/react-dev-utils/WebpackDevServerUtils.d.ts
  types/react-dev-utils/errorOverlayMiddleware.d.ts
  types/react-dev-utils/formatWebpackMessages.d.ts
  types/react-dev-utils/ignoredFiles.d.ts
  types/react-dev-utils/index.d.ts
  types/react-dev-utils/test/webpack-utils.ts
  types/react-dev-utils/tsconfig.json
  types/webpack/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#35219 [webpack] fix ToJsonOutput.chunks (should be an array)
  types/webpack/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#35217 Remove rollup-plugin-delete types
  notNeededPackages.json
  types/rollup-plugin-delete/index.d.ts
  types/rollup-plugin-delete/package.json
  types/rollup-plugin-delete/rollup-plugin-delete-tests.ts
  types/rollup-plugin-delete/tsconfig.json
  types/rollup-plugin-delete/tslint.json
Labels: Author is Owner, Merge:Express

#35218 [node-telegram-bot-api] Mark several properties on the WebHookOptions interface as optional
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35202 [yandex-maps] Fix module format, fix each()
  types/yandex-maps/index.d.ts
  types/yandex-maps/tslint.json
  types/yandex-maps/yandex-maps-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#35215 [react-dev-utils] Add new arguments to createCompiler arguments
  types/react-dev-utils/WebpackDevServerUtils.d.ts
  types/react-dev-utils/formatWebpackMessages.d.ts
  types/react-dev-utils/tsconfig.json
  types/react-dev-utils/webpackHotDevClient.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#35220 [@types/react-beautiful-dnd]: add resetServerContext
  types/react-beautiful-dnd/index.d.ts
  types/react-beautiful-dnd/react-beautiful-dnd-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#35131 fix incorrect return values for aws-serverless-express proxy
  types/aws-serverless-express/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35117 Add options for ensureDir and ensureDirSync
  types/fs-extra/fs-extra-tests.ts
  types/fs-extra/index.d.ts
  types/fs-extra/v4/fs-extra-tests.ts
  types/fs-extra/v4/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35125 [ldapjs] created initial stubs for Server, createServer, and related objects/functions
  types/ldapjs/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35119 [plotly.js] Add width to PlotData interface
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35116 Auth0: Add roles permissions management for Auth0
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35099 [@types/restify] add missing param `requestBodyOnGet` for `BodyParserOptions`
  types/restify/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35092 Update requestPermissions typing
  types/react-native-push-notification/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35093 strip-bom: Delete obsolete type definitions
  notNeededPackages.json
  types/strip-bom/index.d.ts
  types/strip-bom/strip-bom-tests.ts
  types/strip-bom/tsconfig.json
  types/strip-bom/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35090 [styled-react-modal] update and export ModalProps interface
  types/styled-react-modal/index.d.ts
  types/styled-react-modal/styled-react-modal-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#35225 added missing export in react-router-dom
  types/react-router-dom/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#35083 @types/passport-http: fix unused template param #1
  types/passport-http/index.d.ts
  types/passport-http/passport-http-tests.ts
Labels: Merge:Express, Owner Approved

#35243 Update project url for one-time
  types/one-time/index.d.ts
Labels: Awaiting reviewer feedback

#35214 [@types/pino] add ignore to PrettyOptions
  types/pino/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#35221 [WPS] Add changes made to static object.
  types/webpack-plugin-serve/index.d.ts
  types/webpack-plugin-serve/package.json
  types/webpack-plugin-serve/webpack-plugin-serve-tests.ts
Labels: Author is Owner, Merge:Express

#35224 feat: update emoji-regex types
  types/emoji-regex/emoji-regex-tests.ts
  types/emoji-regex/es2015/index.d.ts
  types/emoji-regex/es2015/text.d.ts
  types/emoji-regex/index.d.ts
  types/emoji-regex/text.d.ts
  types/emoji-regex/tsconfig.json
Labels: Merge:Express, Owner Approved

#35226 [express-fileupload] missing types
  types/express-fileupload/index.d.ts
Labels: Merge:Express, Owner Approved

#35232 [@sap/xsenv] Upgrade types to version 2.0
  types/sap__xsenv/index.d.ts
  types/sap__xsenv/sap__xsenv-tests.ts
Labels: Author is Owner, Merge:Express

#35257 [react-native] Add subject as Share option
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Awaiting reviewer feedback, Popular package

#35229 Added callback to fluxible rehydrate function definition
  types/fluxible/index.d.ts
Labels: Merge:Express, Owner Approved

#34832 Remove `open` and `openSet` from `Connection` as they don’t exist any…
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#34884 [@types/seamless-immutable] Overrides<T> doesn't change some parameters to Immutable<T> or Immutable<T[]>
  types/seamless-immutable/index.d.ts
  types/seamless-immutable/seamless-immutable-tests.ts
Labels: Merge:Express, Owner Approved

#34444 fix(node-pushnotifications): add web support
  types/node-pushnotifications/index.d.ts
  types/node-pushnotifications/node-pushnotifications-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#35163 Add missing type to BottomTabNavigatorConfig
  types/react-navigation/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#35109 [google.visualization] Added type support for Controls and Dashboards
  types/google.visualization/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#35262 [react-native] Correct types for NetInfo event listeners
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Awaiting reviewer feedback, Popular package

#35252 [google-cloud__pubsub] Deprecated as of 0.26.0
  notNeededPackages.json
  types/google-cloud__pubsub/google-cloud__pubsub-tests.ts
  types/google-cloud__pubsub/index.d.ts
  types/google-cloud__pubsub/tsconfig.json
  types/google-cloud__pubsub/tslint.json
Labels: Author is Owner, Merge:Express, Owner Approved

#35248 [office-js-preview] Grammar and typo fixesfor Excel Preview
  types/office-js-preview/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#35144 Fixes #31316: Add RouterContext type, update react-router to 5.0
  types/react-router/index.d.ts
  types/react-router/test/RouterContext.tsx
  types/react-router/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#35203 [lodash] `partition` allow setting tuple type
  types/lodash/common/collection.d.ts
  types/lodash/fp.d.ts
  types/lodash/lodash-tests.ts
  types/lodash/readme.md
  types/lowdb/_lodash.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#35230 [osenv] Add typing for osenv
  types/osenv/index.d.ts
  types/osenv/osenv-tests.ts
  types/osenv/tsconfig.json
  types/osenv/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35244 google-apps-script - `May 3, 2019` update
  types/google-apps-script/google-apps-script.document.d.ts
Labels: Merge:Express, Owner Approved

#35095 Added partial definition for React-Big-Scheduler
  types/react-big-scheduler/index.d.ts
  types/react-big-scheduler/package.json
  types/react-big-scheduler/react-big-scheduler-tests.ts
  types/react-big-scheduler/tsconfig.json
  types/react-big-scheduler/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#35148 Update types/jsrender definitions
  types/jsrender/index.d.ts
  types/jsrender/jsrender-tests.ts
  types/jsrender/tsconfig.json
  types/jsrender/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#35272 Avoid extends check for Memo/LazyExoticComponent
  types/react/index.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#35153 fix path.divideAt return definition as @types/paper
  types/paper/index.d.ts
Labels: Merge:Express, Owner Approved

#35145 [@types/gulp-sass] fix Options to support 'importer'
  types/gulp-sass-variables/index.d.ts
  types/gulp-sass/index.d.ts
Labels: Merge:Express, Owner Approved

#35137 Make ReducerMapMeta type work on nested reducerMap
  types/redux-actions/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#35166 Add a missing call and missing options to nock index.d.ts
  types/nock/index.d.ts
  types/nock/nock-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#35231 Async: update async.retry to have errorFilter
  types/async/index.d.ts
  types/async/test/index.ts
Labels: Merge:Express, Owner Approved, Popular package

#35240 Fabric - misc private methods/props
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35157 TinyMCE - Spell Checker Pro plugin settings, adding missing functions
  types/tinymce/index.d.ts
  types/tinymce/tinymce-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35259 [react-cropper] Made ref property optional
  types/react-cropper/index.d.ts
  types/react-cropper/react-cropper-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35066 [stripe] Added name and address to Stripe Customer objects
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35134 [@types/hard-source-webpack-plugin] Add definition of plugins
  types/hard-source-webpack-plugin/hard-source-webpack-plugin-tests.ts
  types/hard-source-webpack-plugin/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35268 [office-js, office-js-preview] Excel for iOS doesn't supported CompressedFile
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35263 [office-js, office-js-preview] Removing unnecessary links
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#35266 rebind-host definition
  types/rebind-host/index.d.ts
  types/rebind-host/rebind-host-tests.ts
  types/rebind-host/tsconfig.json
  types/rebind-host/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35107 [react-motion] Fix missing generic-param error on children
  types/react-motion/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35182 fix(hapi__nes): add callback parameters to onDisconnect
  types/hapi__nes/client.d.ts
  types/hapi__nes/test/client-require.ts
Labels: Merge:Express, Owner Approved

#35198 [draft-js] Add role prop on draft editor interface
  types/draft-js/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#35261 feat(types): add sylvester-es6
  types/sylvester-es6/index.d.ts
  types/sylvester-es6/sylvester-es6-tests.ts
  types/sylvester-es6/tsconfig.json
  types/sylvester-es6/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35277 Add fs-capacitor types
  types/fs-capacitor/fs-capacitor-tests.ts
  types/fs-capacitor/index.d.ts
  types/fs-capacitor/tsconfig.json
  types/fs-capacitor/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35296 remove reference to styled components' css prop
  types/rebass__grid/index.d.ts
  types/rebass__grid/rebass__grid-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved

#35286 [react-native] Improve PermissionsAndroid types
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Popular package, Revision needed

#35347 fix lodash's Collection.groupBy return type
  types/lodash/ts3.1/common/collection.d.ts
  types/lodash/ts3.1/lodash-tests.ts
Labels: Popular package, The Travis CI build failed

#35091 [@types/node] Fix generateKeyPair optional cipher and passphrase (fixes #33788)
  types/node/crypto.d.ts
  types/node/test/crypto.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35146 [@types/stripe] add optional name and phone to customer related interfaces
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#35191 [pdfmake] content can be an array
  types/pdfmake/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#35195 @types/isotope-layout: Multiple sortBy - string | string[]
  types/isotope-layout/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#35179 [@types/enzyme] add generic types support to getDOMNode
  types/enzyme/enzyme-tests.tsx
  types/enzyme/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#35104 [showdown] fix and reorder definitions, add and fix docs
  types/showdown/index.d.ts
  types/showdown/showdown-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35190 Add GraphQLJSONObject type to graphql-type-json definition
  types/graphql-type-json/graphql-type-json-tests.ts
  types/graphql-type-json/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35181 Underscore: fix _.map IterateePropertyShorthand overload
  types/underscore/index.d.ts
  types/underscore/tslint.json
  types/underscore/underscore-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35152 [@types/line-by-line] Fixed stream use case
  types/line-by-line/index.d.ts
  types/line-by-line/line-by-line-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35171 [scrypt-js] change types of password and salt to accept array and Uint8Array
  types/scrypt-js/index.d.ts
  types/scrypt-js/scrypt-js-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35180 [react-native-text-input-mask] made `extracted` and `mask` optional
  types/react-native-text-input-mask/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35135 [react-autosuggest] Make suggestions readonly
  types/react-autosuggest/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35112 [googlemaps] Add `LatLngLiteral` support in `LatLng`
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#35165 Updated "delaunator" typings to version 3.0
  types/delaunator/delaunator-tests.ts
  types/delaunator/index.d.ts
  types/delaunator/tsconfig.json
Labels: Merge:Express, Owner Approved, Revision needed

#35127 Upgrade type definition for Oracledb to version 3.1.2
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
Labels: Merge:Express, Owner Approved

#35293 [hast-format] Add types for HAST format 2.3
  types/hast-format/hast-format-tests.ts
  types/hast-format/index.d.ts
  types/hast-format/tsconfig.json
  types/hast-format/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#35290 Add type definition of non npm package amap-js-api-arrival-range
  types/amap-js-api-arrival-range/amap-js-api-arrival-range-tests.ts
  types/amap-js-api-arrival-range/index.d.ts
  types/amap-js-api-arrival-range/tsconfig.json
  types/amap-js-api-arrival-range/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#35287 Added type definitions for apple-mapkit-js v5.4.0
  types/apple-mapkit-js/apple-mapkit-js-tests.ts
  types/apple-mapkit-js/index.d.ts
  types/apple-mapkit-js/tsconfig.json
  types/apple-mapkit-js/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#35276 Add graphql-upload
  types/graphql-upload/graphql-upload-tests.ts
  types/graphql-upload/index.d.ts
  types/graphql-upload/tsconfig.json
  types/graphql-upload/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#34994 [underscore] Add generic type for memoize
  types/underscore.string/index.d.ts
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Awaiting reviewer feedback, Has Merge Conflict, Popular package

#35208 Allow typing of RawDraftEntity's data
  types/draft-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35212 [mssql] Add Request.query tagged template overloads
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#35223 chrome: make tabs.discard arguments optional
  types/chrome/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL
