Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2019-03, with the labels that each got.

#33349 [turndown] Add definitions for turndown
  types/turndown/index.d.ts
  types/turndown/tsconfig.json
  types/turndown/tslint.json
  types/turndown/turndown-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33348 Add cavy types
  types/cavy/cavy-tests.tsx
  types/cavy/index.d.ts
  types/cavy/tsconfig.json
  types/cavy/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33362 [kafkajs] new type definitions
  types/kafkajs/index.d.ts
  types/kafkajs/kafkajs-tests.ts
  types/kafkajs/tsconfig.json
  types/kafkajs/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33342 Add types for date-and-time
  types/date-and-time/date-and-time-tests.ts
  types/date-and-time/index.d.ts
  types/date-and-time/tsconfig.json
  types/date-and-time/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33337 Add types for npm-list-author-packages
  types/npm-list-author-packages/index.d.ts
  types/npm-list-author-packages/npm-list-author-packages-tests.ts
  types/npm-list-author-packages/tsconfig.json
  types/npm-list-author-packages/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33371 Add slonik (v15.4) typings
  types/slonik/index.d.ts
  types/slonik/slonik-tests.ts
  types/slonik/symbols.d.ts
  types/slonik/tsconfig.json
  types/slonik/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33336 Added type definitions for driftless
  types/driftless/driftless-tests.ts
  types/driftless/index.d.ts
  types/driftless/tsconfig.json
  types/driftless/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33158 [ink-table] Add definitions for ink-table
  types/ink-table/index.d.ts
  types/ink-table/ink-table-tests.tsx
  types/ink-table/tsconfig.json
  types/ink-table/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33138 Add declaration of isEqual() method to pkijs 's RelativeDistinguishedNames class
  types/pkijs/index.d.ts
  types/pkijs/pkijs-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33151 [gl-vec4] Add gl-vec4 typing
  types/gl-vec4/add.d.ts
  types/gl-vec4/clone.d.ts
  types/gl-vec4/copy.d.ts
  types/gl-vec4/create.d.ts
  types/gl-vec4/distance.d.ts
  types/gl-vec4/divide.d.ts
  types/gl-vec4/dot.d.ts
  types/gl-vec4/fromValues.d.ts
  types/gl-vec4/gl-vec4-tests.ts
  types/gl-vec4/index.d.ts
  types/gl-vec4/inverse.d.ts
  types/gl-vec4/length.d.ts
  types/gl-vec4/lerp.d.ts
  types/gl-vec4/max.d.ts
  types/gl-vec4/min.d.ts
  types/gl-vec4/multiply.d.ts
  types/gl-vec4/negate.d.ts
  types/gl-vec4/normalize.d.ts
  types/gl-vec4/random.d.ts
  types/gl-vec4/scale.d.ts
  types/gl-vec4/scaleAndAdd.d.ts
  types/gl-vec4/set.d.ts
  types/gl-vec4/squaredDistance.d.ts
  types/gl-vec4/squaredLength.d.ts
  types/gl-vec4/subtract.d.ts
  types/gl-vec4/transformMat4.d.ts
  types/gl-vec4/transformQuat.d.ts
  types/gl-vec4/tsconfig.json
  types/gl-vec4/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33122 webpack-env: add remaining AcceptOptions
  types/webpack-env/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33134 feat(coinbase): Add fees, timestamps and IDs
  types/coinbase/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33127 feat(node): v11.10
  types/adone/test/glosses/system/process.ts
  types/consul/consul-tests.ts
  types/execa/execa-tests.ts
  types/node/child_process.d.ts
  types/node/crypto.d.ts
  types/node/globals.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/index.d.ts
  types/node/node-tests.ts
  types/node/perf_hooks.d.ts
  types/node/repl.d.ts
  types/node/stream.d.ts
  types/node/test/child_process.ts
  types/node/test/crypto.ts
  types/node/test/http.ts
  types/node/test/http2.ts
  types/node/test/perf_hooks.ts
  types/node/test/repl.ts
  types/node/test/stream.ts
  types/node/test/tls.ts
  types/node/test/zlib.ts
  types/node/tls.d.ts
  types/node/tsconfig.json
  types/node/zlib.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33106 [giphy-api] Fix response
  types/giphy-api/giphy-api-tests.ts
  types/giphy-api/index.d.ts
Labels: Merge:YSYL, Unowned

#33286 Added react-native-snackbar-component
  types/react-native-snackbar-component/index.d.ts
  types/react-native-snackbar-component/react-native-snackbar-component-tests.tsx
  types/react-native-snackbar-component/tsconfig.json
  types/react-native-snackbar-component/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33283 Added react-native-percentage-circle
  types/react-native-percentage-circle/index.d.ts
  types/react-native-percentage-circle/react-native-percentage-circle-tests.tsx
  types/react-native-percentage-circle/tsconfig.json
  types/react-native-percentage-circle/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33426 [gl-vec3] Add typing for gl-vec3
  types/gl-vec3/add.d.ts
  types/gl-vec3/angle.d.ts
  types/gl-vec3/clone.d.ts
  types/gl-vec3/copy.d.ts
  types/gl-vec3/create.d.ts
  types/gl-vec3/dist.d.ts
  types/gl-vec3/div.d.ts
  types/gl-vec3/dot.d.ts
  types/gl-vec3/equals.d.ts
  types/gl-vec3/exactEquals.d.ts
  types/gl-vec3/forEach.d.ts
  types/gl-vec3/fromValues.d.ts
  types/gl-vec3/gl-vec3-tests.ts
  types/gl-vec3/index.d.ts
  types/gl-vec3/inverse.d.ts
  types/gl-vec3/len.d.ts
  types/gl-vec3/lerp.d.ts
  types/gl-vec3/max.d.ts
  types/gl-vec3/min.d.ts
  types/gl-vec3/mul.d.ts
  types/gl-vec3/negate.d.ts
  types/gl-vec3/normalize.d.ts
  types/gl-vec3/random.d.ts
  types/gl-vec3/scale.d.ts
  types/gl-vec3/scaleAndAdd.d.ts
  types/gl-vec3/set.d.ts
  types/gl-vec3/sqrDist.d.ts
  types/gl-vec3/sqrLen.d.ts
  types/gl-vec3/sub.d.ts
  types/gl-vec3/transformMat3.d.ts
  types/gl-vec3/transformMat4.d.ts
  types/gl-vec3/transformQuat.d.ts
  types/gl-vec3/tsconfig.json
  types/gl-vec3/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33274 [react-swipeable-views] add disableLazyLoading prop
  types/react-swipeable-views/index.d.ts
  types/react-swipeable-views/react-swipeable-views-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33487 Add comma option to arrayFormat to match qs update
  types/qs/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33472 pino-http: add `customLogLevel` option
  types/pino-http/index.d.ts
  types/pino-http/pino-http-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#33454 [react-tooltip] add props.children
  types/react-tooltip/index.d.ts
Labels: Merge:Express, Owner Approved

#33488 [underscore] Deduce return type from key in _.pluck (round 2)
  types/icepick/icepick-tests.ts
  types/underscore.string/index.d.ts
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33081 [node] Add ClientRequest.prototype.path
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/v0/index.d.ts
  types/node/v10/http.d.ts
  types/node/v4/index.d.ts
  types/node/v6/index.d.ts
  types/node/v7/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33137 node crypto - generateKeyPair(Sync) types for returning KeyObjects
  types/node/crypto.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33176 add process.hrtime.bigint() to node v10
  types/node/globals.d.ts
  types/node/index.d.ts
  types/node/package.json
  types/node/ts3.1/node-tests.ts
  types/node/ts3.2/globals.d.ts
  types/node/ts3.2/index.d.ts
  types/node/ts3.2/node-tests.ts
  types/node/ts3.2/tsconfig.json
  types/node/ts3.2/tslint.json
  types/node/ts3.2/util.d.ts
  types/node/v10/globals.d.ts
  types/node/v10/node-tests.ts
  types/node/v10/package.json
  types/node/v10/ts3.1/node-tests.ts
  types/node/v10/ts3.2/globals.d.ts
  types/node/v10/ts3.2/index.d.ts
  types/node/v10/ts3.2/node-tests.ts
  types/node/v10/ts3.2/tsconfig.json
  types/node/v10/ts3.2/tslint.json
  types/node/v10/ts3.2/util.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33195 Node: specify `UnhandledRejectionListener` `reason` param type
  types/node/globals.d.ts
  types/node/node-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33325 [@types/node]: buffer module, add transcode function
  types/node/buffer.d.ts
  types/node/index.d.ts
  types/node/test/buffer.ts
  types/node/v10/buffer.d.ts
  types/node/v10/index.d.ts
  types/node/v10/node-tests.ts
  types/node/v7/index.d.ts
  types/node/v7/node-tests.ts
  types/node/v8/index.d.ts
  types/node/v8/node-tests.ts
  types/node/v9/index.d.ts
  types/node/v9/node-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33476 [jsdom] `runVMScript` should return `any`
  types/jsdom/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33045 [node] Make SpawnSyncReturns.error optional
  types/cross-spawn/cross-spawn-tests.ts
  types/node/child_process.d.ts
  types/node/v10/child_process.d.ts
  types/node/v8/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33177 [node] fix forward declaration of SharedArrayBuffer
  types/node/index.d.ts
  types/node/test/buffer.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#33435 Adding properties related with custom styles
  types/react-native-dialog/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Revision needed

#33444 [autoprefixer] update grid options type
  types/autoprefixer/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#33448 [slate-react]: [removed] renderPlaceholder from Editor
  types/slate-react/index.d.ts
Labels: Merge:Express, Owner Approved

#33453 [yup] Add missing 'string.length' method.
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33455 [wu.js] Add toArray
  types/wu/index.d.ts
  types/wu/wu-tests.ts
Labels: Merge:Express, Owner Approved

#33433 google-apps-script: Type definitions for Google Apps Script 2019-02-27
  types/google-apps-script/google-apps-script.base.d.ts
  types/google-apps-script/google-apps-script.data-studio.d.ts
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
Labels: Merge:Express, Owner Approved

#33276 [MongoDB] Several fixes and start getting rid of TSLint rule exceptions
  types/mongodb/index.d.ts
  types/mongodb/mongodb-tests.ts
  types/mongodb/tslint.json
Labels: Merge:Express, Owner Approved, Popular package

#33480 [office-js, office-js-preview] Use AsyncContextOptions in Outlook options parameters instead of any
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#33485 Update fabric Text.measureLine to correct return object
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#33355 mailparser: Add options object to simpleParser
  types/mailparser/index.d.ts
  types/mailparser/mailparser-tests.ts
  types/mailparser/tslint.json
Labels: Awaiting reviewer feedback

#33563 Sinon: replace Bluebird with PromiseLike object
  types/sinon/ts3.1/sinon-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33231 tinymce: Fix a few incorrect types
  types/tinymce/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33560 [is-online] Remove types
  notNeededPackages.json
  types/is-online/index.d.ts
  types/is-online/is-online-tests.ts
  types/is-online/tsconfig.json
  types/is-online/tslint.json
Labels: Author is Owner, Merge:Express, Other Approved

#33551 [cypress-axe] update types for v0.4.0
  types/cypress-axe/index.d.ts
  types/cypress-axe/package.json
  types/cypress-axe/tslint.json
Labels: Author is Owner, Merge:Express

#33549 [google.script.client-side] Improve type of google.script.run object
  types/google.script.client-side/google.script.client-side-tests.ts
  types/google.script.client-side/index.d.ts
  types/google.script.client-side/tsconfig.json
Labels: Author is Owner, Merge:Express

#33542 [p-queue] Remove types
  notNeededPackages.json
  types/p-queue/index.d.ts
  types/p-queue/p-queue-tests.ts
  types/p-queue/tsconfig.json
  types/p-queue/tslint.json
  types/p-queue/v2/index.d.ts
  types/p-queue/v2/p-queue-tests.ts
  types/p-queue/v2/tsconfig.json
  types/p-queue/v2/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Popular package

#33537 flexmonster's d.ts update
  types/flexmonster/index.d.ts
Labels: Author is Owner, Merge:Express

#33526 [office-js] [office-js-preview] (Outlook) Event.completed preview
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#33511 [Tern] added and improved declarations that were missing/incomplete/incorrect
  types/tern/index.d.ts
  types/tern/lib/infer/index.d.ts
  types/tern/lib/tern/index.d.ts
Labels: Author is Owner, Merge:Express, Popular package

#33544 [p-limit] Remove types
  notNeededPackages.json
  types/p-limit/index.d.ts
  types/p-limit/p-limit-tests.ts
  types/p-limit/tsconfig.json
  types/p-limit/tslint.json
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#33547 [p-event] Remove types
  notNeededPackages.json
  types/p-event/index.d.ts
  types/p-event/p-event-tests.ts
  types/p-event/tsconfig.json
  types/p-event/tslint.json
  types/p-event/v1/index.d.ts
  types/p-event/v1/p-event-tests.ts
  types/p-event/v1/tsconfig.json
  types/p-event/v1/tslint.json
Labels: Author is Owner, Merge:Express, Other Approved

#33590 [expo] Add Accuracy enum
  types/expo/expo-tests.tsx
  types/expo/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#33591 [expo] Add Localization
  types/expo/expo-tests.tsx
  types/expo/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#33534 Update to bootstrap 4.3
  types/bootstrap/bootstrap-tests.ts
  types/bootstrap/index.d.ts
Labels: Author is Owner, Merge:Express, Other Approved, Popular package

#33554 Add types for webpack-watched-glob-entries-plugin
  types/webpack-watched-glob-entries-plugin/index.d.ts
  types/webpack-watched-glob-entries-plugin/tsconfig.json
  types/webpack-watched-glob-entries-plugin/tslint.json
  types/webpack-watched-glob-entries-plugin/webpack-watched-glob-entries-plugin-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#33486 [office-js] [office-js-preview] AttachmentDetails-Add url prop
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved

#33543 Add types for wordwrap
  types/wordwrap/index.d.ts
  types/wordwrap/tsconfig.json
  types/wordwrap/tslint.json
  types/wordwrap/wordwrap-tests.ts
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#33317 types/hubot: added catchAll
  types/hubot/index.d.ts
Labels: Merge:Express, Owner Approved

#33595 Add type definitions for ResizeObserver API
  types/resize-observer-browser/index.d.ts
  types/resize-observer-browser/resize-observer-browser-tests.ts
  types/resize-observer-browser/tsconfig.json
  types/resize-observer-browser/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33277 [@types/algoliasearch] add IndexSettings.queryLanguages
  types/algoliasearch/algoliasearch-tests.ts
  types/algoliasearch/index.d.ts
  types/algoliasearch/lite/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#33594 [office-js, office-js-preview] Fixing typo in OfficeTheme.controlForegroundColor
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#33539 Add typings for tarantool-driver
  types/tarantool-driver/index.d.ts
  types/tarantool-driver/tarantool-driver-tests.ts
  types/tarantool-driver/tsconfig.json
  types/tarantool-driver/tslint.json
Labels: New Definition, Revision needed

#33531 [humanize-ms] Add typing for humanize-ms
  types/humanize-ms/humanize-ms-tests.ts
  types/humanize-ms/index.d.ts
  types/humanize-ms/tsconfig.json
  types/humanize-ms/tslint.json
Labels: New Definition, Revision needed

#33552 [pretty-time] Add typing for pretty-time
  types/pretty-time/index.d.ts
  types/pretty-time/pretty-time-tests.ts
  types/pretty-time/tsconfig.json
  types/pretty-time/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#33613 [facebook-js-sdk] Fixed type of LoginOptions.auth_type
  types/facebook-js-sdk/facebook-js-sdk-tests.ts
  types/facebook-js-sdk/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#33445 [hoist-non-react-statics] Expose NonReactStatics type alias
  types/hoist-non-react-statics/hoist-non-react-statics-tests.tsx
  types/hoist-non-react-statics/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33167 @types/ssh2-streams: utils.parseKey now conforms to current API
  types/ssh2-streams/index.d.ts
  types/ssh2-streams/ssh2-streams-tests.ts
  types/ssh2/ssh2-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33132 Made changes to gsap types.Updated definition for Tween callback property.
  types/gsap/Animation.d.ts
  types/gsap/Ease.d.ts
  types/gsap/Timeline.d.ts
  types/gsap/Tween.d.ts
  types/gsap/TweenConfig.d.ts
  types/gsap/gsap-tests.ts
  types/gsap/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33100 Add package: gun
  types/gun/gun-tests.ts
  types/gun/gun.d.ts
  types/gun/index.d.ts
  types/gun/tsconfig.json
  types/gun/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33471 Add types for open-graph
  types/open-graph/index.d.ts
  types/open-graph/open-graph-tests.ts
  types/open-graph/tsconfig.json
  types/open-graph/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33181 react-lazyload: Improve typing of children
  types/react-lazyload/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33194 Update to Calender.selectDates()
  types/kendo-ui/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33196 Add new property 'controlSize' for googlemaps
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33205 Make connect-mongo compatible with newer mongodb and mongoose
  types/connect-mongo/connect-mongo-tests.ts
  types/connect-mongo/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#33208 @three package, in the optional MTLLoader code: fixed one error and specified several "any" types.
  types/three/three-mtlloader.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#32943 [animejs] use default export
  types/animejs/animejs-tests.ts
  types/animejs/index.d.ts
  types/animejs/tsconfig.json
Labels: Merge:Express, Other Approved, Owner Approved, Revision needed

#32927 [detox] Remove named export, define default export
  types/detox/index.d.ts
  types/detox/runners/jest/adapter/index.d.ts
  types/detox/runners/mocha/adapter/index.d.ts
  types/detox/test/detox-jest-setup-tests.ts
  types/detox/test/detox-mocha-setup-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33093 [underscore] Fix wrongly-defined return type for _.matches, _.matcher
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33031 redux-form - Removed wrong type reference to FormData
  types/redux-form/index.d.ts
  types/redux-form/lib/actions.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#33110 fixed linewidth attribute in three.js
  types/three/index.d.ts
  types/three/three-core.d.ts
Labels: Awaiting reviewer feedback, Popular package

#33622 [three.js] Remove unresolvable authors
  types/three/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#33143 [react-scroll-into-view-if-needed] add type defs
  types/react-scroll-into-view-if-needed/index.d.ts
  types/react-scroll-into-view-if-needed/package.json
  types/react-scroll-into-view-if-needed/react-scroll-into-view-if-needed-tests.tsx
  types/react-scroll-into-view-if-needed/tsconfig.json
  types/react-scroll-into-view-if-needed/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33359 Remove @types/chokidar declerations
  notNeededPackages.json
  types/browser-sync/index.d.ts
  types/browser-sync/package.json
  types/chokidar/chokidar-tests.ts
  types/chokidar/index.d.ts
  types/chokidar/tsconfig.json
  types/chokidar/tslint.json
  types/gulp/package.json
  types/hexo-fs/package.json
  types/sc-hot-reboot/package.json
  types/watchpack/package.json
Labels: Abandoned, Owner Approved, Popular package, The Travis CI build failed

#33162 Update to new ParameterizedContext
  types/koa-send/index.d.ts
Labels: Merge:Express, Owner Approved

#33149 [rc-slider] Add tabIndex to Handle props
  types/rc-slider/index.d.ts
  types/rc-slider/rc-slider-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#33599 add types for `d3-cloud`
  types/d3-cloud/d3-cloud-tests.ts
  types/d3-cloud/index.d.ts
Labels: Merge:Express, Owner Approved

#33240 throttle-debounce 2.1.0 - Add cancel method
  types/throttle-debounce/index.d.ts
  types/throttle-debounce/throttle-debounce-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33618 [marked] Add TextRenderer types
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#33569 serialport - Add includeDelimiter option to readline parser
  types/serialport/index.d.ts
  types/serialport/serialport-tests.ts
  types/serialport/v6/index.d.ts
Labels: Merge:Express, Owner Approved

#33256 Add missing $parent to the based class
  types/bpmn-moddle/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33265 [@types/bootstrap-notify] Add parameters to callbacks for bootstrap-notify
  types/bootstrap-notify/bootstrap-notify-tests.ts
  types/bootstrap-notify/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33270 [tabris-plugin-firebase] Remove not needed package
  notNeededPackages.json
  types/tabris-plugin-firebase/index.d.ts
  types/tabris-plugin-firebase/tabris-plugin-firebase-tests.ts
  types/tabris-plugin-firebase/tsconfig.json
  types/tabris-plugin-firebase/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#33272 Superagent 4.x Request.end() doesn't return anything
  types/superagent/index.d.ts
  types/supertest-as-promised/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#33314 Update Jasmine-data_driven_tests/index.d.ts to add TS declarations for 'using' and 'xusing'
  types/jasmine-data_driven_tests/index.d.ts
  types/jasmine-data_driven_tests/jasmine-data_driven_tests-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#33201 Infer parameter and return types for sinon.spy()
  types/sinon/ts3.1/index.d.ts
  types/sinon/ts3.1/sinon-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33351 Update source-map-support to include definition for resetRetrieveHandlers
  types/source-map-support/index.d.ts
  types/source-map-support/source-map-support-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33353 Added data parameter in filter Callback (Chart.js)
  types/chart.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33179 googlemaps - all fields except "name" optional in PlaceResult
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Popular package, Revision needed

#33623 [three.js] Remove @dhritzkiv (myself) from definition authors
  types/three/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#33518 [@types/handlebars]: Remove package, types are now integrated in handlebars
  notNeededPackages.json
  types/ember-data/tsconfig.json
  types/ember-feature-flags/tsconfig.json
  types/ember-mocha/tsconfig.json
  types/ember-modal-dialog/tsconfig.json
  types/ember-qunit/tsconfig.json
  types/ember-resolver/tsconfig.json
  types/ember-test-helpers/tsconfig.json
  types/ember/index.d.ts
  types/ember/test/ember-tests.ts
  types/ember/test/string.ts
  types/ember/tsconfig.json
  types/ember__string/-private/handlebars.d.ts
  types/ember__string/ember__string-tests.ts
  types/ember__string/index.d.ts
  types/ember__string/tsconfig.json
  types/ember__test-helpers/tsconfig.json
  types/ember__test/tsconfig.json
  types/handlebars/handlebars-tests.ts
  types/handlebars/index.d.ts
  types/handlebars/tsconfig.json
  types/handlebars/tslint.json
  types/handlebars/v1/index.d.ts
  types/handlebars/v1/tsconfig.json
  types/handlebars/v1/tslint.json
  types/vision/package.json
Labels: Merge:Express, Owner Approved, Popular package

#33341 Added interface to re-export module with theme interface
  types/styled-components/index.d.ts
  types/styled-components/native.d.ts
  types/styled-components/test/native.tsx
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package, Revision needed

#33365 [cipher-base] Add typing for cipher-base
  types/cipher-base/cipher-base-tests.ts
  types/cipher-base/index.d.ts
  types/cipher-base/tsconfig.json
  types/cipher-base/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33360 [victory] Add (data, active) alternative to VictoryScatter
  types/victory/index.d.ts
  types/victory/victory-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#33368 Add missing doFetch type to react-request RenderProps
  types/react-request/index.d.ts
  types/react-request/react-request-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#33392 DocumentArray disciminator() should be able to receive both document and model interface
  types/mongoose/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33401 sqlite3: Add constants for file open
  types/sqlite3/index.d.ts
  types/sqlite3/sqlite3-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33407 [draft-js] Fix v.0.10.5 types declaration
  types/draft-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33402 Update recharts/index.d.ts
  types/recharts/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33405 jsonwebtoken: Allow audience to be verified with regular expressions
  types/jsonwebtoken/index.d.ts
  types/jsonwebtoken/jsonwebtoken-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#33654 Add codeowners update
  package.json
  scripts/tsconfig.json
  scripts/update-codeowners.js
Labels: Unowned

#33577 [stripe] Added Stripe PaymentIntents
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33581 [react-native-tab-view] Add activeColor and inactiveColor
  types/react-native-tab-view/index.d.ts
Labels: Merge:Express, Owner Approved

#33503 [repeat-element] Add typing for repeat-element
  types/repeat-element/index.d.ts
  types/repeat-element/repeat-element-tests.ts
  types/repeat-element/tsconfig.json
  types/repeat-element/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33564 [cheerio] Allow user to use Buffer in load()
  types/cheerio/cheerio-tests.ts
  types/cheerio/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#33579 chore(png-async): remove typings
  notNeededPackages.json
  types/png-async/index.d.ts
  types/png-async/png-async-tests.ts
  types/png-async/tsconfig.json
  types/png-async/tslint.json
Labels: Merge:Express, Owner Approved

#33247 [phoenix] Improve type definitions
  types/phoenix/index.d.ts
  types/phoenix/phoenix-tests.ts
  types/phoenix/tslint.json
Labels: Revision needed

#33504 Twitch-ext configuration definition
  types/twitch-ext/index.d.ts
  types/twitch-ext/twitch-ext-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#33572 Added new types for html5plus
  types/html5plus/html5plus-tests.ts
  types/html5plus/index.d.ts
  types/html5plus/tsconfig.json
  types/html5plus/tslint.json
Labels: New Definition, Revision needed

#33611 Add type definition for datadog-statsd-metrics-collector
  types/connect-datadog/index.d.ts
  types/datadog-statsd-metrics-collector/datadog-statsd-metrics-collector-tests.ts
  types/datadog-statsd-metrics-collector/index.d.ts
  types/datadog-statsd-metrics-collector/tsconfig.json
  types/datadog-statsd-metrics-collector/tslint.json
  types/node-dogstatsd/index.d.ts
Labels: New Definition, Revision needed

#33629 Remove 'del' package
  notNeededPackages.json
  types/del/del-tests.ts
  types/del/index.d.ts
  types/del/tsconfig.json
  types/del/tslint.json
  types/del/v2/del-tests.ts
  types/del/v2/index.d.ts
  types/del/v2/tsconfig.json
  types/del/v2/tslint.json
  types/gulp/test/index.ts
  types/rollup-plugin-delete/package.json
  types/vinyl-paths/vinyl-paths-tests.ts
Labels: Awaiting reviewer feedback, Popular package

#33625 added referrerpolicy to anchor tag in react types
  types/react/index.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#33356 [@types/node]: Add argument types for `net.Server.close` callback
  types/node/index.d.ts
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v10/index.d.ts
  types/node/v10/net.d.ts
  types/node/v10/node-tests.ts
  types/node/v8/index.d.ts
  types/node/v8/node-tests.ts
  types/node/v9/index.d.ts
  types/node/v9/node-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#33418 Allow `FederatedCredential` to be passed to `fetch()`
  types/webappsec-credential-management/index.d.ts
  types/webappsec-credential-management/webappsec-credential-management-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33410 openpgp.js: Add HKP types
  types/openpgp/common/index.d.ts
  types/openpgp/index.d.ts
  types/openpgp/openpgp-tests.ts
  types/openpgp/ts3.2/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Revision needed

#33415 amqplib: Add serverProperties to Connection object
  types/amqplib/amqplib-tests.ts
  types/amqplib/callback_api.d.ts
  types/amqplib/index.d.ts
  types/amqplib/properties.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33462 [types/react] Fix regression with PropsWithChildren [The Travis build is lying]
  types/react/index.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#33603 [sntp] Add typing for sntp
  types/sntp/index.d.ts
  types/sntp/sntp-tests.ts
  types/sntp/tsconfig.json
  types/sntp/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33423 [ansi-escapes] make arguments to functions optional
  types/ansi-escapes/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33437 aws-lambda Authorizer response context only allows booleans, numbers and strings
  types/aws-lambda/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#33438 Add Howler 2.1.1 definitions
  types/howler/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Revision needed

#33446 [react-redux] Expose static members for connected components
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#33443 [gestalt] Fix SegmentedControlProps
  types/gestalt/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33459 [sharp] Add "mitchell" kernel option
  types/sharp/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved

#33456 Add definition for tmi.js
  types/tmi.js/index.d.ts
  types/tmi.js/strict-event-emitter-types/index.d.ts
  types/tmi.js/tmi.js-tests.ts
  types/tmi.js/tsconfig.json
  types/tmi.js/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33457 @storybook/addon-knobs: remove SelectValue type
  types/storybook__addon-knobs/index.d.ts
  types/storybook__addon-knobs/storybook__addon-knobs-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33660 Nightly cleanup 06-03-2019
  types/ember/v1/package.json
  types/ember/v2/package.json
  types/hbs/package.json
  types/kafkajs/index.d.ts
  types/koa-hbs/package.json
  types/snazzy-info-window/package.json
  types/swag/package.json
Labels: Awaiting reviewer feedback

#33674 Try to add conditional update-codeowners to travis
  .travis.yml
Labels: The Travis CI build failed, Unowned

#33432 electron-store - Fix `onDidChange` return value defition
  types/electron-store/electron-store-tests.ts
  types/electron-store/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33307 fix(mongodb): add collation option to findOneAndReplace and FindOneAn…
  types/mongodb/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#33497 Add types for unsplash-js
  types/unsplash-js/index.d.ts
  types/unsplash-js/tsconfig.json
  types/unsplash-js/tslint.json
  types/unsplash-js/unsplash-js-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33496 [mumath] Update typing for mumath
  types/mumath/clamp.d.ts
  types/mumath/closest.d.ts
  types/mumath/index.d.ts
  types/mumath/isMultiple.d.ts
  types/mumath/len.d.ts
  types/mumath/lerp.d.ts
  types/mumath/mod.d.ts
  types/mumath/mumath-tests.ts
  types/mumath/order.d.ts
  types/mumath/precision.d.ts
  types/mumath/round.d.ts
  types/mumath/scale.d.ts
  types/mumath/tsconfig.json
  types/mumath/within.d.ts
Labels: Other Approved, Unowned

#33494 [html-truncate] Add typing for html-truncate
  types/html-truncate/html-truncate-tests.ts
  types/html-truncate/index.d.ts
  types/html-truncate/tsconfig.json
  types/html-truncate/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#33465 Adding html5-History definition
  types/html5-history/html5-history-tests.ts
  types/html5-history/index.d.ts
  types/html5-history/tsconfig.json
  types/html5-history/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved, Revision needed

#33499 [@types/puppeteer] Add definitions for create browser fetcher and browser fetcher
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#33490 Add key to react-router-config RouteConfig
  types/react-router-config/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33498 Upgrade to Viewer v6.4
  types/forge-viewer/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#33466 [nodegit] Fix some union and nullable types in nodegit
  types/nodegit/commit.d.ts
  types/nodegit/diff.d.ts
  types/nodegit/index.d.ts
  types/nodegit/reset.d.ts
  types/nodegit/revert.d.ts
  types/nodegit/time.d.ts
Labels: Merge:Express, Owner Approved

#33482 [@types/cometd] Add useWorkerScheduler into config
  types/cometd/index.d.ts
Labels: Merge:Express, Owner Approved

#33463 [react-router] Fix withRouter loosing union type
  types/react-router/index.d.ts
  types/react-router/test/WithRouter.tsx
Labels: Merge:Express, Owner Approved, Popular package

#33464 [moment-timezone] Add support for "moment-timezone/moment-timezone" import
  types/moment-timezone/index.d.ts
  types/moment-timezone/moment-timezone.d.ts
  types/moment-timezone/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package
