Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2019-08, with the labels that each got.

#37278 added types for which-pm-runs
  types/which-pm-runs/index.d.ts
  types/which-pm-runs/tsconfig.json
  types/which-pm-runs/tslint.json
  types/which-pm-runs/which-pm-runs-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#37276 added types for preferred-pm
  types/preferred-pm/index.d.ts
  types/preferred-pm/preferred-pm-tests.ts
  types/preferred-pm/tsconfig.json
  types/preferred-pm/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37238 Add types for node-abi
  types/node-abi/index.d.ts
  types/node-abi/node-abi-tests.ts
  types/node-abi/tsconfig.json
  types/node-abi/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37271 [amplitude-js] Allow setUserId to accept null
  types/amplitude-js/amplitude-js-tests.ts
  types/amplitude-js/index.d.ts
Labels: Merge:Express, Owner Approved

#37240 [@types/react-native-actionsheet] Add missing ActionSheetCustom
  types/react-native-actionsheet/index.d.ts
  types/react-native-actionsheet/react-native-actionsheet-tests.tsx
Labels: Merge:Express, Owner Approved

#37292 Simplify PromisedThrow types in chai-as-promised
  types/chai-as-promised/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37182 [@types/node] Allow to extends Http2ServerResponse and MyHttp2ServerRequest
  types/node/http2.d.ts
  types/node/index.d.ts
  types/node/test/http2.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#37202 [ReactStripeElements] update method types
  types/react-stripe-elements/index.d.ts
  types/react-stripe-elements/react-stripe-elements-tests.tsx
Labels: Merge:Express, Owner Approved

#37283 [prettier]: make some SupportLanguage configs optional
  types/prettier/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#37243 [mapbox-gl] Added setZoomRate and setWheelZoomRate
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Merge:Express, Owner Approved

#37198 Package: react-window-infinite-loader 1.0.3 updated types
  types/react-window-infinite-loader/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#37227 [@types/graphql-resolvers] Allow passing arbitrary TArgs to all utilities
  types/graphql-resolvers/index.d.ts
  types/graphql-resolvers/package.json
Labels: Merge:Express, Owner Approved, Revision needed

#37245 react-autosuggest: include state types
  types/react-autosuggest/index.d.ts
Labels: Merge:Express, Owner Approved

#37150 Add (missing) inputContainerStyle props
  types/react-native-material-dropdown/index.d.ts
Labels: Merge:Express, Owner Approved

#37193 [echarts] fix series-bar.itemStyle.color for linear gradient & radial gradient
  types/echarts/options/series/bar.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#37235 google-apps-script July 26, 2019
  types/google-apps-script/google-apps-script.data-studio.d.ts
  types/google-apps-script/google-apps-script.groups.d.ts
  types/google-apps-script/google-apps-script.maps.d.ts
  types/google-apps-script/google-apps-script.slides.d.ts
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
  types/google-apps-script/google-apps-script.url-fetch.d.ts
Labels: Merge:Express, Owner Approved

#37251 [auth0-js] Add options for IdP initiated flows
  types/auth0-js/auth0-js-tests.ts
  types/auth0-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#37274 [dat.gui] Add GUI class static members
  types/dat.gui/index.d.ts
  types/dat.gui/tslint.json
Labels: Owner Approved, Revision needed

#37273 [k6] Update for v0.25
  types/k6/http.d.ts
  types/k6/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37294 Typings for cucumber-html-reporter library.
  types/cucumber-html-reporter/cucumber-html-reporter-tests.ts
  types/cucumber-html-reporter/index.d.ts
  types/cucumber-html-reporter/tsconfig.json
  types/cucumber-html-reporter/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#37285 Detect emoji support
  types/detect-emoji-support/detect-emoji-support-tests.ts
  types/detect-emoji-support/index.d.ts
  types/detect-emoji-support/tsconfig.json
  types/detect-emoji-support/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37281 [blueimp-load-image] New type definitions
  types/blueimp-load-image/blueimp-load-image-tests.ts
  types/blueimp-load-image/index.d.ts
  types/blueimp-load-image/tsconfig.json
  types/blueimp-load-image/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37262 Add types for langmap
  types/langmap/index.d.ts
  types/langmap/langmap-tests.ts
  types/langmap/tsconfig.json
  types/langmap/tslint.json
  types/langmap/types.d.ts
Labels: Awaiting reviewer feedback, New Definition

#37269 add @types/react-devtools
  types/react-devtools/index.d.ts
  types/react-devtools/react-devtools-tests.ts
  types/react-devtools/tsconfig.json
  types/react-devtools/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37047 [@types/paypal-rest-sdk] Fix type of transactions field in Payment typing
  types/paypal-rest-sdk/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37207 [storybook__addon-storyshots-puppeteer] new types definition
  types/storybook__addon-storyshots-puppeteer/index.d.ts
  types/storybook__addon-storyshots-puppeteer/storybook__addon-storyshots-puppeteer-tests.ts
  types/storybook__addon-storyshots-puppeteer/tsconfig.json
  types/storybook__addon-storyshots-puppeteer/tslint.json
  types/storybook__addon-storyshots/index.d.ts
  types/storybook__addon-storyshots/storybook__addon-storyshots-tests.ts
Labels: New Definition, Revision needed

#37181 [yargs-interactive] Update type definition to v2.1
  types/yargs-interactive/index.d.ts
  types/yargs-interactive/yargs-interactive-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37303 react-native - Ensures the default launch screen compiles
  types/react-native/LaunchScreen.d.ts
  types/react-native/index.d.ts
  types/react-native/test/init-example.tsx
  types/react-native/tslint.json
Labels: Merge:Express, Owner Approved, Popular package

#37308 styled-system: ColorProps now extends OpacityProps
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Awaiting reviewer feedback

#37286 add types for wx-server-sdk（微信小程序服务端api）
  types/wx-server-sdk/index.d.ts
  types/wx-server-sdk/tsconfig.json
  types/wx-server-sdk/tslint.json
  types/wx-server-sdk/wx-server-sdk-tests.ts
Labels: New Definition, Revision needed

#37179 New type definition for jsspec
  types/jsspec__jsspec/index.d.ts
  types/jsspec__jsspec/jsspec__jsspec-tests.ts
  types/jsspec__jsspec/tsconfig.json
  types/jsspec__jsspec/tslint.json
Labels: New Definition, Revision needed

#37263 add @types/express-form-data
  types/express-form-data/express-form-data-tests.ts
  types/express-form-data/index.d.ts
  types/express-form-data/tsconfig.json
  types/express-form-data/tslint.json
Labels: New Definition, Revision needed

#37076 [@types/slate] Update for version 0.47
  types/slate-react/index.d.ts
  types/slate-react/slate-react-tests.tsx
  types/slate/index.d.ts
  types/slate/slate-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#37266 nodegit: fix Treebuilder.create signature
  types/nodegit/tree-builder.d.ts
Labels: Merge:Express, Owner Approved

#37260 [nightwatch] add chrome options and make test_settings options optional
  types/nightwatch/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#37291 [segment-analytics] support analytics.js-core library
  types/segment-analytics/index.d.ts
  types/segment-analytics/segment-analytics-tests.ts
Labels: Merge:Express, Owner Approved

#37298 [powerapps-component-framework] Fix EntityReference type
  types/powerapps-component-framework/componentframework.d.ts
  types/powerapps-component-framework/powerapps-component-framework-tests.ts
Labels: Merge:Express, Owner Approved

#37319 [openid-client] Add more detailed types to introspection response as per RFC7662
  types/openid-client/index.d.ts
  types/openid-client/openid-client-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#37320 [@types/react-sortable-tree] Add types for TreeRendererProps and NodeRendererProps interfaces
  types/react-sortable-tree/index.d.ts
Labels: Merge:Express, Owner Approved

#37315 [Bull] Added number to removeOnFail on Bull JobOpts
  types/bull/index.d.ts
Labels: Merge:Express, Owner Approved

#37272 added typings for vmap-js
  types/vmap/index.d.ts
  types/vmap/tsconfig.json
  types/vmap/tslint.json
  types/vmap/vmap-tests.ts
Labels: New Definition, Revision needed

#37317 Add two additional types for React Image Crop
  types/react-image-crop/index.d.ts
  types/react-image-crop/test/react-image-crop-global-tests.ts
  types/react-image-crop/test/react-image-crop-module-tests.tsx
Labels: Merge:Express, Owner Approved

#37316 Upgrade to Forge Viewer v7
  types/forge-viewer/README.md
  types/forge-viewer/index.d.ts
Labels: Merge:Express, Owner Approved

#37302 [express-mung] Add exports to types
  types/express-mung/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#37326 [@types/redux-orm] correct throughFields property on many() object param
  types/redux-orm/fields.d.ts
  types/redux-orm/redux-orm-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37328 [office-js] [office-js-preview] (Outlook) Update hostName values
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37332 Fix/update session send message
  types/chrome/chrome-cast/index.d.ts
Labels: Merge:Express, Owner Approved

#37314 Added types for react-native-pdf-lib
  types/react-native-pdf-lib/index.d.ts
  types/react-native-pdf-lib/react-native-pdf-lib-tests.ts
  types/react-native-pdf-lib/tsconfig.json
  types/react-native-pdf-lib/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37160 Add types for dexie-batch
  types/dexie-batch/dexie-batch-tests.ts
  types/dexie-batch/index.d.ts
  types/dexie-batch/package.json
  types/dexie-batch/tsconfig.json
  types/dexie-batch/tslint.json
Labels: New Definition, The Travis CI build failed

#36669 rdflib - Added class Query and improved signatures for methods in Formula and IndexedFormula
  types/rdflib/index.d.ts
  types/rdflib/rdflib-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37066 feat(prometheus-gc-stats): Add `config` argument types
  types/prometheus-gc-stats/index.d.ts
  types/prometheus-gc-stats/prometheus-gc-stats-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37081 node-forge: Fix type of `pki.rsa.setPublicKey()`
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37043 [@types/boom] Add typeof to Boom
  types/boom/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37096 [@types/deep-freeze] - allow functions to be called with out error
  types/deep-freeze/deep-freeze-tests.ts
  types/deep-freeze/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37125 Improve typing of makeAsyncSelect.
  types/react-select/src/Async.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#37131 [numeral] Add type to locales property
  types/numeral/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#37104 feat(toposort): second element of array can be undefined
  types/toposort/index.d.ts
  types/toposort/toposort-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37117 [compression] include actual documentation in jsdoc comments
  types/compression/compression-tests.ts
  types/compression/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37161 Modify the ali-oss PutObjectOptions interface
  types/ali-oss/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37152 [ws] Define interfaces for parameters to onopen, onclose, onerror and onmessage
  types/ws/index.d.ts
  types/ws/ws-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37296 Updated to newest vue js and vue2-datepicker version
  types/vue2-datepicker/index.d.ts
  types/vue2-datepicker/package.json
  types/vue2-datepicker/tsconfig.json
  types/vue2-datepicker/vue2-datepicker-tests.ts
Labels: Author is Owner, Merge:Express

#37203 Add types for highlightjs
  types/highlightjs/highlightjs-tests.ts
  types/highlightjs/index.d.ts
  types/highlightjs/tsconfig.json
  types/highlightjs/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37267 add @types/integreate-adaptive-simpson
  types/integrate-adaptive-simpson/index.d.ts
  types/integrate-adaptive-simpson/integrate-adaptive-simpson-tests.ts
  types/integrate-adaptive-simpson/tsconfig.json
  types/integrate-adaptive-simpson/tslint.json
  types/integrate-adaptive-simpson/vector.d.ts
Labels: Awaiting reviewer feedback, New Definition

#37216 Update chrome.webRequest events for blocking
  types/chrome/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37222 [@types/gremlin] Moved authentication classes to right namespace
  types/gremlin/gremlin-tests.ts
  types/gremlin/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37225 [react-select] Change type definition for mergeStyles
  types/react-select/src/styles.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37230 pdfjs-dist getViewport signature change in 2.1.266
  types/pdfjs-dist/index.d.ts
  types/pdfjs-dist/pdfjs-dist-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37228 [cookie-signature] Fix return type of unsign function
  types/cookie-signature/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37242 [react-helmet] Added TagUpdates type for onChangeClientState
  types/react-helmet/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37358 [@storybook/addon-a11y] remove typings provided by package directly
  notNeededPackages.json
  types/storybook__addon-a11y/index.d.ts
  types/storybook__addon-a11y/storybook__addon-a11y-tests.tsx
  types/storybook__addon-a11y/tsconfig.json
  types/storybook__addon-a11y/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#37374 [googlemaps] Cleanup and update google.maps.MapPanes
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#37361 Added gematriya types
  types/gematriya/index.d.ts
  types/gematriya/test/gematriya-global-tests.ts
  types/gematriya/test/gematriya-module-tests.ts
  types/gematriya/tsconfig.json
  types/gematriya/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37345 Add type definitions for `tdweb` (web telegram client)
  types/tdweb/index.d.ts
  types/tdweb/tdweb-tests.ts
  types/tdweb/tsconfig.json
  types/tdweb/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37338 [@types/staticmaps] Add types for staticmaps
  types/staticmaps/index.d.ts
  types/staticmaps/staticmaps-tests.ts
  types/staticmaps/tsconfig.json
  types/staticmaps/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37349 [jquery] Add support for drag events.
  types/jquery/jquery-tests.ts
  types/jquery/misc.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#37365 types/jest: add missing function getTimerCount
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#37356 Add missing keyboardHidesTabBar declaration
  types/react-navigation/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37195 knockout.validation: Support of format function for validationmessages
  types/knockout.validation/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37363 [auth0-js] add documentation for `username` signup option
  types/auth0-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#37353 Update Metadata interfaces
  types/jsforce/api/metadata.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37318 [gapi-people] Add definitions for Birthday object
  types/gapi.people/index.d.ts
Labels: Merge:Express, Owner Approved

#37346 [react-native-push-notification] Add visibility and importance to notification options
  types/react-native-push-notification/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved

#37364 airtable: update SelectOptions to match airtable docs
  types/airtable/airtable-tests.ts
  types/airtable/index.d.ts
Labels: Merge:Express, Owner Approved

#37362 airtable: add boolean, number, and collaborator field types
  types/airtable/airtable-tests.ts
  types/airtable/index.d.ts
Labels: Merge:Express, Owner Approved

#37313 [proper-lockfile] Patches options.retries with the correct type
  types/proper-lockfile/index.d.ts
  types/proper-lockfile/proper-lockfile-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#37357 [Workbox] Update 'installed' event type
  types/workbox-window/Workbox.d.ts
Labels: Merge:Express, Owner Approved

#37371 expandableRowsOnClick on MUIDataTableOptions of mui-datatables
  types/mui-datatables/index.d.ts
Labels: Merge:Express, Owner Approved

#37327 [@types/fnando__sparkline] Amended svg parameter type.
  types/fnando__sparkline/fnando__sparkline-tests.ts
  types/fnando__sparkline/index.d.ts
Labels: Author is Owner, Merge:Express

#37376 types/mongoose: add Document.overwrite function
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#37280 Fix @types/frisby expectNot type
  types/frisby/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37380 [storybook__preact] Specify preact JSX element for the Renderable type
  types/storybook__preact/index.d.ts
  types/storybook__preact/storybook__preact-tests.tsx
Labels: Merge:Express, Owner Approved

#37379 [googlemaps] Remove all unnecessary tslint disables
  types/googlemaps/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#37284 [algoliasearch] change module format
  types/algoliasearch/algoliasearch-tests.ts
  types/algoliasearch/index.d.ts
  types/algoliasearch/lite/index.d.ts
Labels: Author is Owner, Owner Approved, Revision needed

#37386 [@mapbox/tile-cover]Add types for tile-cover
  types/mapbox__tile-cover/index.d.ts
  types/mapbox__tile-cover/mapbox__tile-cover-tests.ts
  types/mapbox__tile-cover/tsconfig.json
  types/mapbox__tile-cover/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37395 react-transition-group: fix import SwitchTransition
  types/react-transition-group/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37385 [googlemaps] Enable and fix simple rules
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
  types/googlemaps/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#37290 fix(pdfMake): upgrade pageSize type
  types/pdfmake/index.d.ts
Labels: Merge:Express, Owner Approved

#37391 react-pdf: Add children to Document component Props
  types/react-pdf/dist/Document.d.ts
  types/react-pdf/index.d.ts
Labels: Merge:Express, Owner Approved

#37387 [blueimp-load-image] Making optional fields optional
  types/blueimp-load-image/index.d.ts
Labels: Author is Owner, Merge:Express

#37403 [@types/randomColor] Make return type smarter
  types/randomcolor/index.d.ts
  types/randomcolor/randomcolor-tests.ts
Labels: Merge:Express, Owner Approved

#37197 Fix react-beautiful-dnd DropAnimation types for v11
  types/react-beautiful-dnd/index.d.ts
Labels: Revision needed

#37217 feat(node): v12.7
  types/node/dns.d.ts
  types/node/http.d.ts
  types/node/index.d.ts
  types/node/inspector.d.ts
  types/node/node-tests.ts
  types/node/readline.d.ts
  types/node/scripts/generate-inspector/index.ts
  types/node/scripts/generate-inspector/inspector.d.ts.template
  types/node/test/readline.ts
  types/node/tty.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package, Revision needed

#37400 Simplify .editorconfig & .prettierrc.json
  .editorconfig
  .prettierrc.json
Labels: Other Approved, Unowned

#37409 [ramda] Removed utility types in `tools.d.ts` to integrate with "ts-toolbelt" instead
  types/ramda/index.d.ts
  types/ramda/package.json
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#37297 [google__maps] Fixes GeocodingComponents
  types/google__maps/google__maps-tests.ts
  types/google__maps/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37304 Update/Add braintree-web types for threeDSecure create/prepareLookup
  types/braintree-web/index.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37277 Update p5 to 0.9
  types/p5/constants.d.ts
  types/p5/global.d.ts
  types/p5/index.d.ts
  types/p5/lib/addons/p5.dom.d.ts
  types/p5/lib/addons/p5.sound.d.ts
  types/p5/literals.d.ts
  types/p5/src/color/creating_reading.d.ts
  types/p5/src/color/p5.Color.d.ts
  types/p5/src/color/setting.d.ts
  types/p5/src/core/constants.d.ts
  types/p5/src/core/environment.d.ts
  types/p5/src/core/p5.Element.d.ts
  types/p5/src/core/p5.Graphics.d.ts
  types/p5/src/core/p5.Renderer.d.ts
  types/p5/src/core/rendering.d.ts
  types/p5/src/core/shape/2d_primitives.d.ts
  types/p5/src/core/shape/attributes.d.ts
  types/p5/src/core/shape/curves.d.ts
  types/p5/src/core/shape/vertex.d.ts
  types/p5/src/core/structure.d.ts
  types/p5/src/core/transform.d.ts
  types/p5/src/data/local_storage.d.ts
  types/p5/src/data/p5.TypedDict.d.ts
  types/p5/src/events/acceleration.d.ts
  types/p5/src/events/keyboard.d.ts
  types/p5/src/events/mouse.d.ts
  types/p5/src/events/touch.d.ts
  types/p5/src/image/image.d.ts
  types/p5/src/image/loading_displaying.d.ts
  types/p5/src/image/p5.Image.d.ts
  types/p5/src/image/pixels.d.ts
  types/p5/src/io/files.d.ts
  types/p5/src/io/p5.Table.d.ts
  types/p5/src/io/p5.TableRow.d.ts
  types/p5/src/io/p5.XML.d.ts
  types/p5/src/math/calculation.d.ts
  types/p5/src/math/math.d.ts
  types/p5/src/math/noise.d.ts
  types/p5/src/math/p5.Vector.d.ts
  types/p5/src/math/random.d.ts
  types/p5/src/math/trigonometry.d.ts
  types/p5/src/typography/attributes.d.ts
  types/p5/src/typography/loading_displaying.d.ts
  types/p5/src/typography/p5.Font.d.ts
  types/p5/src/utilities/array_functions.d.ts
  types/p5/src/utilities/conversion.d.ts
  types/p5/src/utilities/string_functions.d.ts
  types/p5/src/utilities/time_date.d.ts
  types/p5/src/webgl/3d_primitives.d.ts
  types/p5/src/webgl/interaction.d.ts
  types/p5/src/webgl/light.d.ts
  types/p5/src/webgl/loading.d.ts
  types/p5/src/webgl/material.d.ts
  types/p5/src/webgl/p5.Camera.d.ts
  types/p5/src/webgl/p5.Geometry.d.ts
  types/p5/src/webgl/p5.RendererGL.d.ts
  types/p5/src/webgl/p5.Shader.d.ts
  types/p5/test/index.ts
  types/p5/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#37301 Export interfaces in react-native-share
  types/react-native-share/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37307 [pbf] Added class constants
  types/pbf/index.d.ts
  types/pbf/pbf-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37388 deprecate react-intl types
  notNeededPackages.json
  types/react-intl-redux/index.d.ts
  types/react-intl-redux/package.json
  types/react-intl-redux/tsconfig.json
  types/react-intl/index.d.ts
  types/react-intl/react-intl-tests.tsx
  types/react-intl/tsconfig.json
  types/react-intl/tslint.json
  types/react-intl/v1/index.d.ts
  types/react-intl/v1/react-intl-tests.tsx
  types/react-intl/v1/tsconfig.json
  types/react-intl/v1/tslint.json
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#35871 mailgun-js: Allow sending templates
  types/mailgun-js/index.d.ts
  types/mailgun-js/mailgun-js-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#37410 [office-js, office-js-preview] Clarifying `numberFormatLocal` description
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37427 [googlemaps] Just reformat with prettier
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#36672 [react-native-sortable-list] added generic support and bump version
  types/react-native-sortable-list/index.d.ts
  types/react-native-sortable-list/react-native-sortable-list-tests.tsx
  types/react-native-sortable-list/tslint.json
Labels: Other Approved, Revision needed

#37436 [@types/react] Add Valign attributes
  types/react/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37324 Adding the location property in the Multer File interface
  types/multer/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37329 + [mapnik] additional method definitions on the class VectorTile
  types/mapnik/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37174 [node] Bugfix tty read write stream constructor
  types/node/test/tty.ts
  types/node/tty.d.ts
  types/node/v10/node-tests.ts
  types/node/v10/tty.d.ts
  types/node/v11/test/tty.ts
  types/node/v11/tty.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37428 jasmine: Add definitionAdded static falsy, truthy, empty, notEmpty
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/jasmine/ts3.1/index.d.ts
  types/jasmine/ts3.1/jasmine-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#37402 [@types/mongodb] make _id optional for collection.insertX functions
  types/agenda/index.d.ts
  types/connect-mongodb-session/index.d.ts
  types/gridfs-stream/index.d.ts
  types/mongodb/index.d.ts
  types/mongoose/v4/index.d.ts
  types/mongorito/index.d.ts
  types/mongration/index.d.ts
  types/multer-gridfs-storage/v1/index.d.ts
  types/multer-gridfs-storage/v2/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37441 [office-js] [office-js-preview] (Outlook) Add note about Outlook value
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37420 [office-js] (Outlook) Remove preview API
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#37407 [office-js] [office-js-preview] (Outlook) Link to error object
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37419 Added verify & sign options valid for 8.5.1
  types/jsonwebtoken/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37405 [react-transition-group] Unify to standard module syntax
  types/react-transition-group/CSSTransition.d.ts
  types/react-transition-group/SwitchTransition.d.ts
  types/react-transition-group/Transition.d.ts
  types/react-transition-group/TransitionGroup.d.ts
  types/react-transition-group/index.d.ts
  types/react-transition-group/react-transition-group-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#37417 [newrelic] Allow promise transaction handlers.
  types/newrelic/index.d.ts
  types/newrelic/newrelic-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#37394 [snoowrap] not needed as of 1.19.0
  notNeededPackages.json
  types/snoowrap/dist/objects/Comment.d.ts
  types/snoowrap/dist/objects/Listing.d.ts
  types/snoowrap/dist/objects/LiveThread.d.ts
  types/snoowrap/dist/objects/MultiReddit.d.ts
  types/snoowrap/dist/objects/PrivateMessage.d.ts
  types/snoowrap/dist/objects/RedditContent.d.ts
  types/snoowrap/dist/objects/RedditUser.d.ts
  types/snoowrap/dist/objects/ReplyableContent.d.ts
  types/snoowrap/dist/objects/Submission.d.ts
  types/snoowrap/dist/objects/Subreddit.d.ts
  types/snoowrap/dist/objects/VoteableContent.d.ts
  types/snoowrap/dist/objects/WikiPage.d.ts
  types/snoowrap/dist/objects/index.d.ts
  types/snoowrap/index.d.ts
  types/snoowrap/snoowrap-tests.ts
  types/snoowrap/tsconfig.json
  types/snoowrap/tslint.json
Labels: Merge:Express, Owner Approved

#37424 react-pdf: Update some types to use pdfjs-dist for better type safety
  types/react-pdf/dist/Document.d.ts
  types/react-pdf/dist/Outline.d.ts
  types/react-pdf/dist/Page.d.ts
  types/react-pdf/index.d.ts
  types/react-pdf/react-pdf-tests.tsx
Labels: Merge:Express, Owner Approved

#37416 Fixed intro.js module export
  types/intro.js/index.d.ts
Labels: Merge:Express, Owner Approved

#37445 react-gateway: Allow functional components in GatewayDest 'component' prop.
  types/react-gateway/GatewayDest.d.ts
Labels: Merge:Express, Owner Approved

#37421 Add type definitions for `react-inspector`
  types/react-inspector/index.d.ts
  types/react-inspector/package.json
  types/react-inspector/react-inspector-tests.tsx
  types/react-inspector/tsconfig.json
  types/react-inspector/tslint.json
Labels: New Definition, Revision needed

#37337 Add types for bayes-classifier
  types/bayes-classifier/bayes-classifier-tests.ts
  types/bayes-classifier/index.d.ts
  types/bayes-classifier/tsconfig.json
  types/bayes-classifier/tslint.json
Labels: New Definition, Revision needed

#37255 [lscache] Update version to v.1.3.0
  types/lscache/index.d.ts
  types/lscache/lscache-tests.ts
  types/lscache/tslint.json
Labels: Revision needed

#37431 [conductor-animate] Create Types
  types/conductor-animate/conductor-animate-tests.tsx
  types/conductor-animate/index.d.ts
  types/conductor-animate/tsconfig.json
  types/conductor-animate/tslint.json
Labels: New Definition, Revision needed

#37336 Fix typo in mongoose-deep-populate
  types/mongoose-deep-populate/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37139 [c3] Update all c3 types to meet latest documentation and source code
  types/c3/c3-tests.ts
  types/c3/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#37334 Added color property to @types/debug Debugger interface
  types/debug/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#37469 [openid-client] Add revoke method to client
  types/openid-client/index.d.ts
  types/openid-client/openid-client-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#37450 [@mapbox/mapbox-sdk] Use correct type for overlay
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#37465 Fix stripe cancellation_reason mispelling
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37451 [chai] Provide type definitions for chai.use
  types/bardjs/index.d.ts
  types/chai-almost/index.d.ts
  types/chai-arrays/index.d.ts
  types/chai-as-promised/index.d.ts
  types/chai-datetime/index.d.ts
  types/chai-dom/index.d.ts
  types/chai-enzyme/index.d.ts
  types/chai-fs/index.d.ts
  types/chai-fuzzy/index.d.ts
  types/chai-jest-snapshot/index.d.ts
  types/chai-jquery/index.d.ts
  types/chai-json-schema/index.d.ts
  types/chai-moment/chai-moment-tests.ts
  types/chai-moment/index.d.ts
  types/chai-oequal/index.d.ts
  types/chai-roughly/index.d.ts
  types/chai-spies/index.d.ts
  types/chai-string/index.d.ts
  types/chai-subset/index.d.ts
  types/chai-things/index.d.ts
  types/chai-uuid/index.d.ts
  types/chai-webdriverio/index.d.ts
  types/chai-xml/index.d.ts
  types/chai/chai-tests.ts
  types/chai/index.d.ts
  types/d3kit/v1/index.d.ts
  types/deep-equal-in-any-order/index.d.ts
  types/dirty-chai/index.d.ts
  types/ember-mocha/index.d.ts
  types/hexo-log/index.d.ts
  types/hexo-util/index.d.ts
  types/hexo/index.d.ts
  types/jsx-chai/index.d.ts
  types/karma-chai-sinon/index.d.ts
  types/karma-chai/index.d.ts
  types/redux-test-utils/index.d.ts
  types/sinon-chai/index.d.ts
  types/sinon-chai/v2/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#37423 Removed jpeg-js in favor of upstream typings
  notNeededPackages.json
  types/jpeg-js/index.d.ts
  types/jpeg-js/jpeg-js-tests.ts
  types/jpeg-js/tsconfig.json
  types/jpeg-js/tslint.json
Labels: Merge:Express, Owner Approved

#37432 [raygun] Add GroupingKey type and user function
  types/raygun/index.d.ts
  types/raygun/raygun-tests.ts
Labels: Merge:Express, Owner Approved

#37458 Added missing baseline property to TextOptions
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Merge:Express, Owner Approved

#37408 subtitle: added function stringifyVtt
  types/subtitle/index.d.ts
  types/subtitle/subtitle-tests.ts
Labels: Merge:Express, Owner Approved

#37440 mocha-steps: update to 1.3 with mocha 6.0
  types/mocha-steps/index.d.ts
  types/mocha-steps/mocha-steps-tests.ts
Labels: Merge:Express, Owner Approved

#37453 [pathval] Add types for pathval
  types/pathval/index.d.ts
  types/pathval/pathval-tests.ts
  types/pathval/tsconfig.json
  types/pathval/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37456 Created type definitions for 'leaflet.featuregroup.subgroup'
  types/leaflet.featuregroup.subgroup/index.d.ts
  types/leaflet.featuregroup.subgroup/leaflet.featuregroup.subgroup-tests.ts
  types/leaflet.featuregroup.subgroup/tsconfig.json
  types/leaflet.featuregroup.subgroup/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37464 Add type definitions for rollup-plugin-postcss
  types/rollup-plugin-postcss/index.d.ts
  types/rollup-plugin-postcss/package.json
  types/rollup-plugin-postcss/rollup-plugin-postcss-tests.ts
  types/rollup-plugin-postcss/tsconfig.json
  types/rollup-plugin-postcss/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#37462 Add type definitions for rollup-plugin-url
  types/rollup-plugin-url/index.d.ts
  types/rollup-plugin-url/package.json
  types/rollup-plugin-url/rollup-plugin-url-tests.ts
  types/rollup-plugin-url/tsconfig.json
  types/rollup-plugin-url/tslint.json
Labels: Awaiting reviewer feedback, New Definition
