Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2019-02, with the labels that each got.

#32571 Fix jsforce definitions
  types/jsforce/api/chatter.d.ts
  types/jsforce/api/metadata.d.ts
  types/jsforce/jsforce-tests.ts
  types/jsforce/tslint.json
Labels: Merge:Express, Other Approved, Owner Approved

#32567 Split node into one file per module
  types/node/assert.d.ts
  types/node/async_hooks.d.ts
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/cluster.d.ts
  types/node/console.d.ts
  types/node/constants.d.ts
  types/node/crypto.d.ts
  types/node/dgram.d.ts
  types/node/dns.d.ts
  types/node/domain.d.ts
  types/node/events.d.ts
  types/node/fs.d.ts
  types/node/globals.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/https.d.ts
  types/node/index.d.ts
  types/node/inspector.d.ts
  types/node/module.d.ts
  types/node/net.d.ts
  types/node/os.d.ts
  types/node/path.d.ts
  types/node/perf_hooks.d.ts
  types/node/process.d.ts
  types/node/punycode.d.ts
  types/node/querystring.d.ts
  types/node/readline.d.ts
  types/node/repl.d.ts
  types/node/scripts/generate-inspector/inspector.d.ts.template
  types/node/stream.d.ts
  types/node/string_decoder.d.ts
  types/node/timers.d.ts
  types/node/tls.d.ts
  types/node/trace_events.d.ts
  types/node/tsconfig.json
  types/node/tslint.json
  types/node/tty.d.ts
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/v8.d.ts
  types/node/vm.d.ts
  types/node/worker_threads.d.ts
  types/node/zlib.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#32685 [@pollyjs monorepo] bump version, correct header typing
  types/pollyjs__adapter-fetch/index.d.ts
  types/pollyjs__adapter-node-http/index.d.ts
  types/pollyjs__adapter/index.d.ts
  types/pollyjs__core/index.d.ts
  types/pollyjs__persister-fs/index.d.ts
  types/pollyjs__persister/index.d.ts
  types/pollyjs__utils/index.d.ts
Labels: Merge:Express, Owner Approved

#32633 auth0-js - Added back needed fields for Auth0Error
  types/auth0-js/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32707 [sqlanywhere] added void return type to functions which return void to prevent implicit any.
  types/sqlanywhere/index.d.ts
Labels: Merge:Express, Owner Approved

#32703 [iobroker] Don't strip null | undefined from async `getState/getObject`
  types/iobroker/index.d.ts
  types/iobroker/iobroker-tests.ts
Labels: Author is Owner, Merge:Express

#32701 @types/nouislider : Make create function return a NoUiSlider instance
  types/nouislider/index.d.ts
Labels: Merge:Express, Owner Approved

#32711 [@types/theo] Theo 8.1 updates support
  types/theo/index.d.ts
  types/theo/package.json
Labels: Merge:Express, Owner Approved

#32668 d3-shape: Update to 1.3.3
  types/d3-shape/d3-shape-tests.ts
  types/d3-shape/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Popular package, Revision needed

#32248 detox: Prevent exporting global "expect" from other modules.
  types/detox/index.d.ts
Labels: Owner Approved, Revision needed

#32541 Bootstrap v3: Fix jQuery compatibility
  types/bootstrap/v3/bootstrap-tests.ts
  types/bootstrap/v3/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#32724 [create-xpub] Add types
  types/create-xpub/create-xpub-tests.ts
  types/create-xpub/index.d.ts
  types/create-xpub/tsconfig.json
  types/create-xpub/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32721 [byte-range] Add types
  types/byte-range/byte-range-tests.ts
  types/byte-range/index.d.ts
  types/byte-range/tsconfig.json
  types/byte-range/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32725 [build-output-script] Add types
  types/build-output-script/build-output-script-tests.ts
  types/build-output-script/index.d.ts
  types/build-output-script/tsconfig.json
  types/build-output-script/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32717 [json-schema] allow `$schema` property to be string
  types/json-schema/index.d.ts
Labels: Owner Approved, Popular package, Revision needed

#32687 [expired] Add types
  types/expired/expired-tests.ts
  types/expired/index.d.ts
  types/expired/tsconfig.json
  types/expired/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32713 [onionoo] Add types
  types/onionoo/index.d.ts
  types/onionoo/onionoo-tests.ts
  types/onionoo/tsconfig.json
  types/onionoo/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32693 [micromodal] New definition
  types/micromodal/index.d.ts
  types/micromodal/micromodal-tests.ts
  types/micromodal/tsconfig.json
  types/micromodal/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#32530 [@types/mapbox-gl] Improve Expression, Source types
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
  types/react-map-gl/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32698 Add definition for list.js 1.5.0
  types/list.js/index.d.ts
  types/list.js/list.js-tests.ts
  types/list.js/tsconfig.json
  types/list.js/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32646 [office-js, office-js-preview] Adding descriptions to async overloads
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#32714 Fabricjs - added IObjectOptions.clipPath & IObjectOptions.dirty
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Revision needed

#32659 [react] Breaking! Update hooks API to (what's expected to be) the final 16.8.0 API
  types/react/index.d.ts
  types/react/test/hooks.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#32546 Add types for react-dev-utils
  types/react-dev-utils/FileSizeReporter.d.ts
  types/react-dev-utils/InlineChunkHtmlPlugin.d.ts
  types/react-dev-utils/InterpolateHtmlPlugin.d.ts
  types/react-dev-utils/ModuleScopePlugin.d.ts
  types/react-dev-utils/WatchMissingNodeModulesPlugin.d.ts
  types/react-dev-utils/WebpackDevServerUtils.d.ts
  types/react-dev-utils/checkRequiredFiles.d.ts
  types/react-dev-utils/clearConsole.d.ts
  types/react-dev-utils/eslintFormatter.d.ts
  types/react-dev-utils/formatWebpackMessages.d.ts
  types/react-dev-utils/getCSSModuleLocalIdent.d.ts
  types/react-dev-utils/getCacheIdentifier.d.ts
  types/react-dev-utils/getProcessForPort.d.ts
  types/react-dev-utils/index.d.ts
  types/react-dev-utils/launchEditor.d.ts
  types/react-dev-utils/noopServiceWorkerMiddleware.d.ts
  types/react-dev-utils/openBrowser.d.ts
  types/react-dev-utils/printBuildError.d.ts
  types/react-dev-utils/printHostingInstructions.d.ts
  types/react-dev-utils/test/eslintFormatter.ts
  types/react-dev-utils/test/noopServiceWorkerMiddleware.ts
  types/react-dev-utils/test/utils.ts
  types/react-dev-utils/test/webpack-plugins.ts
  types/react-dev-utils/test/webpack-utils.ts
  types/react-dev-utils/tsconfig.json
  types/react-dev-utils/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32442 [diff] update missing option fields
  types/diff/diff-tests.ts
  types/diff/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#32723 feat(puppeteer): v1.12
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#32673 [styled-components] Add ServerStyleSheet.seal()
  types/styled-components/index.d.ts
  types/styled-components/test/index.tsx
Labels: Awaiting reviewer feedback, Popular package

#32738 [ssri] Add Typescript definitions.
  types/ssri/index.d.ts
  types/ssri/ssri-tests.ts
  types/ssri/tsconfig.json
  types/ssri/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#32737 Add typings for react-motion-loop.
  types/react-motion-loop/index.d.ts
  types/react-motion-loop/react-motion-loop-tests.tsx
  types/react-motion-loop/tsconfig.json
  types/react-motion-loop/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32504 Mithril - Additional signature for m.route.link
  types/mithril/index.d.ts
  types/mithril/test/test-route.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Revision needed

#32631 Fix Definitions for @loadable/server ChunkExtractor
  types/loadable__server/index.d.ts
  types/loadable__server/loadable__server-tests.tsx
Labels: Merge:Express, Owner Approved, Revision needed

#32629 [@types/shallowequal] separate shallowequal.comparer
  types/shallowequal/index.d.ts
  types/shallowequal/shallowequal-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#32688 [cassandra-driver] Updated definitions for version 4.0.0
  types/cassandra-driver/cassandra-driver-tests.ts
  types/cassandra-driver/index.d.ts
Labels: Merge:Express, Owner Approved, Revision needed

#32578 [@types/stripe] Fix balance_transaction type in IRefund
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32699 [@types/react-flatpickr] Add className to DateTimePickerProps
  types/react-flatpickr/index.d.ts
  types/react-flatpickr/react-flatpickr-tests.tsx
Labels: Merge:Express, Owner Approved, Revision needed

#32742 [@types/hls.js] Add bandwidth estimate type
  types/hls.js/index.d.ts
Labels: Merge:Express, Owner Approved

#30309 Updated types for Lolex to the current version (3)
  types/lolex/index.d.ts
  types/lolex/lolex-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#32741 Rename `eye` to `identity` in mathjs from v5
  types/mathjs/index.d.ts
  types/mathjs/mathjs-tests.ts
Labels: Merge:Express, Owner Approved

#32745 koa-bunyan-logger: Add missing helper middleware types
  types/koa-bunyan-logger/index.d.ts
  types/koa-bunyan-logger/koa-bunyan-logger-tests.ts
Labels: Merge:Express, Owner Approved

#32748 Elliptic.js: Key creation also accepts String
  types/elliptic/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32749 Add documentation from the project pages of node-usb and libusb when available
  types/usb/index.d.ts
Labels: Merge:Express, Owner Approved

#32593 Reactable - Added missing props to type definition
  types/reactable/index.d.ts
Labels: Merge:Express, Owner Approved

#32622 [rc-slider] Adds tabIndex prop types
  types/rc-slider/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32599 gapi.auth2: Add ux_mode and redirect_uri to SigninOptions
  types/gapi.auth2/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32630 [@types/chrome] Fix parameter type in chrome.tabs.onHighlighted.addListener callback
  types/chrome/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32579 [jest] add type inference
  types/expect-puppeteer/index.d.ts
  types/frisby/index.d.ts
  types/jest-axe/index.d.ts
  types/jest-image-snapshot/index.d.ts
  types/jest-in-case/index.d.ts
  types/jest-in-case/jest-in-case-tests.ts
  types/jest-json-schema/index.d.ts
  types/jest-matchers/index.d.ts
  types/jest-plugin-context/index.d.ts
  types/jest-specific-snapshot/index.d.ts
  types/jest-when/index.d.ts
  types/jest-when/jest-when-tests.ts
  types/jest/index.d.ts
  types/jest/jest-tests.ts
  types/jest/tsconfig.json
  types/storybook__addon-storyshots/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32766 [jest-image-snapshot]: Update to fix #32760 & for library updates
  types/jest-image-snapshot/index.d.ts
  types/jest-image-snapshot/jest-image-snapshot-tests.ts
Labels: Author is Owner, Merge:Express

#32569 [Jest] add test.todo
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package

#32734 [memjs] Add promise return values when no callback is provided
  types/memjs/index.d.ts
  types/memjs/memjs-tests.ts
Labels: Merge:Express, Owner Approved

#32756 Type the onRangeChange prop in react-big-calendar
  types/react-big-calendar/index.d.ts
Labels: Merge:Express, Owner Approved

#32755 [isotope-layout] filtering function passes an argument of an item being filtered
  types/isotope-layout/index.d.ts
  types/isotope-layout/isotope-layout-tests.ts
Labels: Merge:Express, Owner Approved

#32706 [Sequelize] Buffer/Buffer[]/boolean[] in where clause
  types/sequelize/index.d.ts
  types/sequelize/sequelize-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved, Popular package, Revision needed

#32759 puppeteer: preserve type information in Page.evaluate and friends
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#32754 Add force-graph typings
  types/force-graph/force-graph-tests.ts
  types/force-graph/index.d.ts
  types/force-graph/tsconfig.json
  types/force-graph/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32663 [@types/google-apps-script] Remove the unnecessary console declaration
  types/google-apps-script/google-apps-script.base.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32639 TinyMCE: allow to omit menu items
  types/tinymce/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32708 [@types/iopipe__iopipe]Fix iopipe function wrapper definition
  types/iopipe__iopipe/index.d.ts
  types/iopipe__iopipe/iopipe__iopipe-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#32603 Create Type Declarations for connect-history-api-fallback-exclusions
  types/connect-history-api-fallback-exclusions/connect-history-api-fallback-exclusions-tests.ts
  types/connect-history-api-fallback-exclusions/index.d.ts
  types/connect-history-api-fallback-exclusions/tsconfig.json
  types/connect-history-api-fallback-exclusions/tslint.json
Labels: New Definition, Revision needed

#32799 [victory] Add missing prop types for VictoryBar
  types/victory/index.d.ts
  types/victory/tslint.json
  types/victory/victory-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#32792 [Slate]: Correct `getMarksAtIndex` return type
  types/slate/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#32788 [reactstrap] Update type of CustomInput label prop
  types/reactstrap/lib/CustomInput.d.ts
  types/reactstrap/reactstrap-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#32784 [js-stellar-base] fix(keypair): Keypair.type and sign/verify
  types/stellar-base/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#32512 @types/leaflet: Add VideoOverlay
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#32763 [react-intl] Fix: defineMessage autocomplete
  types/react-intl/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32779 [stellar-base]: add TransactionBuilder.setTimeout and TimeoutInfinite
  types/stellar-base/index.d.ts
  types/stellar-base/stellar-base-tests.ts
Labels: Merge:Express, Owner Approved

#32790 mime: default_type went away in mime v2
  types/mime/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32764 Fabricjs missing pattern transform definitions
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#32796 [react-tabs] Props for components now extend HtmlElements
  types/react-tabs/index.d.ts
  types/react-tabs/react-tabs-tests.ts
  types/react-tabs/tslint.json
Labels: Merge:Express, Owner Approved

#32677 add useNativeValidation to material__textfield
  types/material__textfield/foundation.d.ts
  types/material__textfield/index.d.ts
Labels: Merge:Express, Owner Approved

#32782 [pubnub] Add grant method
  types/pubnub/index.d.ts
  types/pubnub/pubnub-tests.ts
Labels: Merge:Express, Owner Approved

#32791 pathjs: various small fixes
  types/pathjs/index.d.ts
  types/pathjs/pathjs-tests.ts
Labels: Merge:Express, Owner Approved

#32803 Support koa-joi-router 5.2
  types/koa-joi-router/index.d.ts
  types/koa-joi-router/koa-joi-router-tests.ts
Labels: Merge:Express, Owner Approved

#32794 Fixed wrong typing for onLayoutChange
  types/react-grid-layout/index.d.ts
Labels: Merge:Express, Owner Approved

#32804 feat: add type for "rollup-plugin-buble"
  types/rollup-plugin-buble/index.d.ts
  types/rollup-plugin-buble/package.json
  types/rollup-plugin-buble/rollup-plugin-buble-tests.ts
  types/rollup-plugin-buble/tsconfig.json
  types/rollup-plugin-buble/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32776 [NEW] wait-on types
  types/wait-on/index.d.ts
  types/wait-on/tsconfig.json
  types/wait-on/tslint.json
  types/wait-on/wait-on-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#32675 [next] Add `enhanceApp` / `enhanceComponent`
  types/next/document.d.ts
  types/next/test/next-document-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#32739 add type definition for prosemirror-test-builder
  types/prosemirror-test-builder/index.d.ts
  types/prosemirror-test-builder/prosemirror-test-builder-tests.ts
  types/prosemirror-test-builder/tsconfig.json
  types/prosemirror-test-builder/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#32548 [supercluster] Upgrade to 5.0; stricter types
  types/supercluster/index.d.ts
  types/supercluster/supercluster-tests.ts
  types/supercluster/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#32549 [express-unless] Overload unless function.
  types/express-unless/express-unless-tests.ts
  types/express-unless/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#32809 [React bootstrap typeahead] added customOption
  types/react-bootstrap-typeahead/index.d.ts
  types/react-bootstrap-typeahead/react-bootstrap-typeahead-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#32768 [react-native] Enhance Keyboard API Event typings
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Awaiting reviewer feedback, Popular package

#32823 Update react-dom, react-test-renderer to 16.8.0; stricter useEffect types
  types/react-dom/index.d.ts
  types/react-dom/react-dom-tests.tsx
  types/react-dom/test-utils/index.d.ts
  types/react-dom/tsconfig.json
  types/react-test-renderer/index.d.ts
  types/react-test-renderer/react-test-renderer-tests.ts
  types/react/index.d.ts
  types/react/test/hooks.tsx
Labels: Merge:Express, Owner Approved, Popular package

#32833 Update react-native-popup-dialog
  types/react-native-popup-dialog/index.d.ts
  types/react-native-popup-dialog/react-native-popup-dialog-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#32818 [victory] Allow for functional styles in victory
  types/victory/index.d.ts
  types/victory/tslint.json
  types/victory/victory-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#32815 [office-js] Fixing Application.load description
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#32814 [Meteor] fix Mongo $addToSet and add Meteor.absoluteUrl.defaultOptions
  types/meteor/meteor.d.ts
  types/meteor/mongo.d.ts
  types/meteor/test/meteor-tests.ts
Labels: Merge:Express, Owner Approved

#32801 fix(url-parse): Add optional stringify fn to `toString`
  types/url-parse/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32695 [Ramda] - Added type definition for R.move
  types/ramda/es/move.d.ts
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#32813 [video.js]: add player inactivityTimeout option
  types/video.js/index.d.ts
Labels: Merge:Express, Owner Approved

#32812 [video.js]: add player readyState()
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Merge:Express, Owner Approved

#32789 loglevel: Move noConflict and getLogger to a DefaultLogger interface
  types/loglevel/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32831 Angular IPromise interop with platform Promise.
  types/angular/angular-tests.ts
  types/angular/index.d.ts
  types/angular/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#32834 [yup] Add definition for `isSchema()` method signature
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#32841 [kissfft-js]: Add type declarations for kissfft-js
  types/kissfft-js/index.d.ts
  types/kissfft-js/kissfft-js-tests.ts
  types/kissfft-js/tsconfig.json
  types/kissfft-js/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32839 Add types for @carbon/themes
  types/carbon__themes/carbon__themes-tests.ts
  types/carbon__themes/index.d.ts
  types/carbon__themes/tsconfig.json
  types/carbon__themes/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32837 Add types for @carbon/colors and update paths
  types/carbon__colors/carbon__colors-tests.ts
  types/carbon__colors/index.d.ts
  types/carbon__colors/tsconfig.json
  types/carbon__colors/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32810 Update README with links to gitter and infrastructure
  README.md
Labels: Other Approved, Unowned

#32728 Update list.js definitions to use typescript exports and also export interfaces
  types/list.js/index.d.ts
Labels: Merge:LGTM, Other Approved, Revision needed, Unowned

#32595 [webpack-dev-server] Add writeToDisk configuration
  types/webpack-dev-server/index.d.ts
  types/webpack-dev-server/webpack-dev-server-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#32643 [@types/react-native-modal-dropdown]: added scrollEnabled property
  types/react-native-modal-dropdown/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32666 d3-force: Update to 1.2
  types/d3-force/d3-force-tests.ts
  types/d3-force/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#32712 add types for spellchecker
  types/spellchecker/index.d.ts
  types/spellchecker/spellchecker-tests.ts
  types/spellchecker/tsconfig.json
  types/spellchecker/tslint.json
Labels: New Definition, Revision needed

#32527 updating debug to be compilable in TS > 3.1
  types/debug/debug-tests.ts
  types/debug/index.d.ts
  types/debug/tslint.json
Labels: Owner Approved, Popular package, Revision needed

#32510 Added type definition for hexo
  types/hexo/hexo-tests.ts
  types/hexo/index.d.ts
  types/hexo/tsconfig.json
  types/hexo/tslint.json
Labels: New Definition, Revision needed

#32716 add types for aws-param-store
  types/aws-param-store/aws-param-store-tests.ts
  types/aws-param-store/index.d.ts
  types/aws-param-store/package.json
  types/aws-param-store/tsconfig.json
  types/aws-param-store/tslint.json
Labels: New Definition, Revision needed

#32354 [@types/feathersjs__errors] Added typings for the missing "code", "className" and "data" property members of the FeathersError object.
  types/feathersjs__errors/index.d.ts
Labels: Revision needed

#32709 Added types for cordova-plugin-background-download
  types/cordova-plugin-background-download/cordova-plugin-background-download-tests.ts
  types/cordova-plugin-background-download/index.d.ts
  types/cordova-plugin-background-download/tsconfig.json
  types/cordova-plugin-background-download/tslint.json
Labels: New Definition, Revision needed

#32020 [jscodeshift] Add types for jscodeshift 0.6
  types/jscodeshift/index.d.ts
  types/jscodeshift/package.json
  types/jscodeshift/src/Collection.d.ts
  types/jscodeshift/src/collections/JSXElement.d.ts
  types/jscodeshift/src/collections/Node.d.ts
  types/jscodeshift/src/collections/VariableDeclarator.d.ts
  types/jscodeshift/src/core.d.ts
  types/jscodeshift/src/template.d.ts
  types/jscodeshift/test/js-transforms/README.md
  types/jscodeshift/test/js-transforms/bind-this-to-bind-expression.ts
  types/jscodeshift/test/js-transforms/call-expression-bind-this-to-arrow-function-expression.ts
  types/jscodeshift/test/js-transforms/function-expression-to-arrow-function-expression.ts
  types/jscodeshift/test/js-transforms/props-to-destructuring.ts
  types/jscodeshift/test/js-transforms/pure-to-composite-component.ts
  types/jscodeshift/test/jscodeshift-tests.ts
  types/jscodeshift/tsconfig.json
  types/jscodeshift/tslint.json
Labels: New Definition, Revision needed

#32523 [webappsec-credential-management] Make userHandle optional
  types/webappsec-credential-management/index.d.ts
  types/webappsec-credential-management/webappsec-credential-management-tests.ts
Labels: Revision needed

#32870 [office-js] [office-js-preview] (Outlook) Remove inapplicable props
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#32859 Fabricjs - missing color matrix definition
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#32857 [ioBroker] Add `custom` property to ObjectCommon
  types/iobroker/index.d.ts
  types/iobroker/iobroker-tests.ts
Labels: Author is Owner, Merge:Express

#32850 algoliasearch: add missing type for removeStopWords
  types/algoliasearch/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#32767 Elliptic: importFromPublic accepts an object containing X and Y as Strings
  types/elliptic/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#32691 Adds 'typesVersions' support to NodeJS definitions
  types/node/base.d.ts
  types/node/globals.d.ts
  types/node/index.d.ts
  types/node/node-tests.ts
  types/node/package.json
  types/node/ts3.1/index.d.ts
  types/node/ts3.1/node-tests.ts
  types/node/ts3.1/tsconfig.json
  types/node/ts3.1/tslint.json
  types/node/ts3.1/util.d.ts
  types/node/tsconfig.json
  types/node/util.d.ts
Labels: Merge:Express, New Definition, Owner Approved, Popular package

#32827 platform: The parse and toString methods are not maybe undef
  types/platform/index.d.ts
  types/platform/platform-tests.ts
Labels: Merge:Express, Owner Approved

#32811 [video.js]: add player networkState
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Merge:Express, Owner Approved

#32838 [meteor] More detailed typing for Meteor.methods(), fixed User model.
  types/meteor/globals/meteor.d.ts
  types/meteor/meteor.d.ts
Labels: Merge:Express, Owner Approved

#32775 libxmljs: Allow booleans in parser options
  types/libxmljs/index.d.ts
Labels: Merge:Express, Owner Approved

#32855 [@types/aws-lambda] Add WebSocket integration props to APIGatewayEventRequestContext
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32846 Fixed typo in enzyme configure description
  types/enzyme/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32860 [fastify-static] remove as package bundles typings
  notNeededPackages.json
  types/fastify-static/fastify-static-tests.ts
  types/fastify-static/index.d.ts
  types/fastify-static/package.json
  types/fastify-static/tsconfig.json
  types/fastify-static/tslint.json
Labels: Merge:Express, Owner Approved

#32844 @types/Yup createError path and message optional
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#32861 Add @carbon/layout
  types/carbon__layout/carbon__layout-tests.ts
  types/carbon__layout/index.d.ts
  types/carbon__layout/tsconfig.json
  types/carbon__layout/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32862 Add @carbon/motion
  types/carbon__motion/carbon__motion-tests.ts
  types/carbon__motion/index.d.ts
  types/carbon__motion/tsconfig.json
  types/carbon__motion/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32856 [utif] Add types
  types/utif/index.d.ts
  types/utif/tsconfig.json
  types/utif/tslint.json
  types/utif/utif-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#32849 Add bunyan-seq typings
  types/bunyan-seq/bunyan-seq-tests.ts
  types/bunyan-seq/index.d.ts
  types/bunyan-seq/tsconfig.json
  types/bunyan-seq/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32848 Add moment-precise-range-plugin
  types/moment-precise-range-plugin/index.d.ts
  types/moment-precise-range-plugin/moment-precise-range-plugin-tests.ts
  types/moment-precise-range-plugin/package.json
  types/moment-precise-range-plugin/tsconfig.json
  types/moment-precise-range-plugin/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#32671 [@types/koa-compose]: Provide way for typesafe compose
  types/koa-compose/index.d.ts
  types/koa-compose/koa-compose-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#32722 [rebass] fix `as` prop to accept custom components, strings, etc.
  types/rebass/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32392 react-paginate: export ReactPaginateProps interface in v5 and v6
  types/react-paginate/index.d.ts
  types/react-paginate/v5/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#32733 [acl] Export all module interfaces, fix lint exceptions
  types/acl/index.d.ts
  types/acl/test/index.ts
  types/acl/test/mongodbBackend.ts
  types/acl/test/redisBackend.ts
  types/acl/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#32580 [@types/react-highlight-words] Upgrading typings to version 0.16.0
  types/react-highlight-words/index.d.ts
  types/react-highlight-words/react-highlight-words-tests.tsx
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Revision needed

#32661 [node] correct SlowBuffer
  types/node/buffer.d.ts
  types/node/globals.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#32689 stripe: Update cancel subscription options as of 2018-11-08
  types/stripe/index.d.ts
Labels: Popular package, Revision needed

#32907 [sarif] Update to latest sarif version 2.0.0-csd.2.beta-2019-01-09
  types/sarif/index.d.ts
Labels: Author is Owner, Merge:Express

#32887 fix: set fastify-cors typings not needed
  notNeededPackages.json
  types/fastify-cors/fastify-cors-tests.ts
  types/fastify-cors/index.d.ts
  types/fastify-cors/tsconfig.json
  types/fastify-cors/tslint.json
Labels: Author is Owner, Merge:Express

#32883 Update backbone-relational to version 0.10.0
  types/backbone-relational/backbone-relational-tests.ts
  types/backbone-relational/index.d.ts
Labels: Merge:Express, Owner Approved

#32730 [node] Sort fields in IncomingHttpHeaders
  types/node/http.d.ts
  types/node/v4/index.d.ts
  types/node/v6/index.d.ts
  types/node/v7/index.d.ts
  types/node/v8/index.d.ts
  types/node/v9/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32806 [cassandra-driver] Added missing and fixed existing declarations
  types/cassandra-driver/cassandra-driver-tests.ts
  types/cassandra-driver/index.d.ts
Labels: Merge:Express, Owner Approved

#32889 Prettier: Add parser babel
  types/prettier/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32893 generic-pool: Add missing flag 'testOnReturn'
  types/generic-pool/generic-pool-tests.ts
  types/generic-pool/index.d.ts
Labels: Merge:Express, Owner Approved

#32805 [@types/node-fetch]: Added missing properties for FetchError
  types/node-fetch/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#32896 feat(react-native-document-picker): add more utils types
  types/react-native-document-picker/index.d.ts
Labels: Merge:Express, Owner Approved

#32892 [react-native-tab-view] Added useNativeDriver prop
  types/react-native-tab-view/index.d.ts
Labels: Merge:Express, Owner Approved

#32888 [@types/luxon] Fix args type for Interval#toDuration
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#32872 [@types/redux-form] Add startSubmit and stopSubmit immutable actions
  types/redux-form/immutable/index.d.ts
  types/redux-form/index.d.ts
  types/redux-form/redux-form-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#32880 Make Xrm.Device.captureImage imageOptions optional
  types/xrm/index.d.ts
Labels: Merge:Express, Owner Approved

#32912 Add typings for color-support
  types/color-support/color-support-tests.ts
  types/color-support/index.d.ts
  types/color-support/tsconfig.json
  types/color-support/tslint.json
Labels: New Definition, Revision needed

#32886 [styled-system]: Add missing justifyItems definition.
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Merge:Express, Owner Approved
