Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2019-12, with the labels that each got.

#39048 types/soundmanager2 - added audioFormats SoundManager Top-Level property
  types/soundmanager2/index.d.ts
  types/soundmanager2/soundmanager2-tests.ts
Labels: Perf: Same, Revision needed

#40712 feat: Add `@ungap/global‑this`
  types/ungap__global-this/index.d.ts
  types/ungap__global-this/tsconfig.json
  types/ungap__global-this/tslint.json
  types/ungap__global-this/ungap__global-this-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#40658 @types/react: Mark booleanish HTML/SVG JSX attributes as such
  types/react/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same, Popular package, Revision needed

#40624 Titanium updates
  types/titanium/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Revision needed

#40692 [password] Add types for password pkg
  types/password/index.d.ts
  types/password/password-tests.ts
  types/password/tsconfig.json
  types/password/tslint.json
Labels: New Definition, Revision needed

#40537 [chart.js] Add DoughnutModel interface
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Perf: Same, Popular package, Revision needed

#40744 [trashable] Add types for trashable
  types/trashable/index.d.ts
  types/trashable/trashable-tests.ts
  types/trashable/tsconfig.json
  types/trashable/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#40762 add types: rn-app-upgrade
  types/rn-app-upgrade/index.d.ts
  types/rn-app-upgrade/rn-app-upgrade-tests.ts
  types/rn-app-upgrade/tsconfig.json
  types/rn-app-upgrade/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#40724 Add Types for react-countdown-circle-timer 1.0.3
  types/react-countdown-circle-timer/index.d.ts
  types/react-countdown-circle-timer/react-countdown-circle-timer-tests.tsx
  types/react-countdown-circle-timer/tsconfig.json
  types/react-countdown-circle-timer/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#40725 add @types/react-stars
  types/react-stars/index.d.ts
  types/react-stars/react-stars-tests.tsx
  types/react-stars/tsconfig.json
  types/react-stars/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#40637 [office-js] [office-js-preview] (Outlook) Update MasterCategories per…
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#40643 Added responseInterceptor swagger-ui-dist
  types/swagger-ui-dist/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#40648 Add roxy option to the rox-* packages
  types/rox-browser/index.d.ts
  types/rox-node/index.d.ts
  types/rox-react-native/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#40653 Upgrading @types/oracledb to 4.1
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
  types/oracledb/tsconfig.json
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#40713 [chai] Adjust comment of isNaN / isNotNaN
  types/chai/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40609 [ssh2-sftp-client] add the second param for list method
  types/ssh2-sftp-client/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40719 [leaflet.js] fix typings for Polyline.addLatLng()
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40741 [@keystonejs/adapter-mongoose] fix typo in adapter name
  types/keystonejs__adapter-mongoose/index.d.ts
  types/keystonejs__adapter-mongoose/keystonejs__adapter-mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40726 Update ioredis sentinel retry strategy
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40752 Add error and fallback to rules interface for no-context/moo
  types/moo/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40755 [merge2] Use PassThrough stream instead of common ReadWriteStream
  types/merge2/index.d.ts
  types/merge2/merge2-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40666 [list.js] Make filterFunction optional
  types/list.js/index.d.ts
  types/list.js/list.js-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40634 Cheerio / adding undefined to return type of attr method of Cheerio interface
  types/cheerio/cheerio-tests.ts
  types/cheerio/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#39337 feat: Add `function‑bind`
  types/function-bind/function-bind-tests.ts
  types/function-bind/implementation.d.ts
  types/function-bind/index.d.ts
  types/function-bind/package.json
  types/function-bind/ts3.3/function-bind-tests.ts
  types/function-bind/ts3.3/implementation.d.ts
  types/function-bind/ts3.3/index.d.ts
  types/function-bind/ts3.3/tsconfig.json
  types/function-bind/ts3.3/tslint.json
  types/function-bind/tsconfig.json
  types/function-bind/tslint.json
Labels: New Definition, Revision needed

#40656 Adding types for existing node module "express-list-endpoints"
  types/express-list-endpoints/express-list-endpoints-tests.ts
  types/express-list-endpoints/index.d.ts
  types/express-list-endpoints/tsconfig.json
  types/express-list-endpoints/tslint.json
Labels: New Definition, Revision needed

#40708 feat: Add `@ungap/create‑content`
  types/ungap__create-content/index.d.ts
  types/ungap__create-content/test/create-content.cjs.test.ts
  types/ungap__create-content/test/create-content.umd.test.ts
  types/ungap__create-content/tsconfig.json
  types/ungap__create-content/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#40771 [sharp] update typings to 0.23.3 and fix #40640
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#40583 [@types/fabric] Fix gradients, version 3.5
  types/fabric/fabric-impl.d.ts
  types/fabric/index.d.ts
  types/fabric/test/index.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40778 [nuxtjs__auth] added missing declarations
  types/nuxtjs__auth/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40788 add rpxtransformers to xstyled__system
  types/xstyled__system/index.d.ts
  types/xstyled__system/xstyled__system-tests.tsx
Labels: Author is Owner, Merge:Express, Perf: Same

#40756 fix(airtable): return types for Table.create
  types/airtable/airtable-tests.ts
  types/airtable/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40782 Added wrap prop for the TabsProps interface (gestalt)
  types/gestalt/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40767 hapi__joi: AnySchema extends SchemaInternals and isJoi is dropped
  types/hapi__joi/hapi__joi-tests.ts
  types/hapi__joi/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Worse, Popular package

#40749 [materialize-css] Updated materialize-css autocomplete typing
  types/materialize-css/autocomplete.d.ts
  types/materialize-css/index.d.ts
  types/materialize-css/test/autocomplete.test.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40793 fix: add missing typing for auth0-js lib
  types/auth0-js/auth0-js-tests.ts
  types/auth0-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#40779 [react-virtualized] Correcting Table.noRowsRenderer property function return type
  types/react-virtualized/dist/es/Table.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40789 Adding new WebGL2RenderingContext
  types/react/global.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40770 Update css-tree types: `some` returns boolean, add find, findLast, findAll
  types/css-tree/css-tree-tests.ts
  types/css-tree/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40777 Make 'slate' and 'slate-react' Plugin types generic
  types/slate-react/index.d.ts
  types/slate-react/slate-react-tests.tsx
  types/slate/index.d.ts
  types/slate/slate-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40807 [icepick] Updates to input arrays to use ReadonlyArray, general cleanup, major version bump
  types/icepick/icepick-tests.ts
  types/icepick/index.d.ts
  types/icepick/tsconfig.json
  types/icepick/tslint.json
Labels: Author is Owner, Merge:Express, Owner Approved

#40720 fix(ioredis): make types more accurate
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
  types/redlock/index.d.ts
  types/redlock/v3/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40811 feat(ejs): Update to v3.0
  types/ejs/index.d.ts
  types/ejs/test/ejs.umd.test.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#40806 fix: add setValue for react-native-material-textfield
  types/react-native-material-textfield/index.d.ts
  types/react-native-material-textfield/react-native-material-textfield-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same

#40812 [@types/stripe] Add client_secret property to ISetupIntentConfirmOptions
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40792 Adds clear to levelup + updates tests
  types/levelup/index.d.ts
  types/levelup/levelup-tests.ts
Labels: Merge:Express, Owner Approved

#40794 [rdf-js] Add Dataset interface
  types/rdf-js/index.d.ts
  types/rdf-js/rdf-js-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40815 [@types/stripe]: Adding cancel_at to subscription
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40808 [algoliasearch] Add QueryParameters.userToken
  types/algoliasearch/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40824 [@types/mongodb] Adding missing options parameters in functions of Admin interface
  types/mongodb/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40827 email-templates: Updated View root to be optional (default is even specified in comments)
  types/email-templates/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40739 [parquetjs] optional/repeated are always usable
  types/parquetjs/lib/schema.interface.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40826 (pino) Add definition for logger bindings
  types/pino/index.d.ts
  types/pino/pino-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40839 @types/mui-datatables - Change BlobPart back to string type
  types/mui-datatables/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40823 [atmosphere-javascript] Add new property for type Request
  types/atmosphere.js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40848 Dockerode: Add RootFS to image inspect typing
  types/dockerode/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#40831 Updated and fixed types for blocked package
  types/blocked/blocked-tests.ts
  types/blocked/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40851 [mapbox-gl] Update mapbox-gl to v1.6.0
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#40847 fix(ioredis): add length property to pipeline
  types/ioredis/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40855 [geolite2] Update to 2.0
  types/geolite2/geolite2-tests.ts
  types/geolite2/index.d.ts
Labels: Author is Owner, Merge:Express

#40825 [tough-cookie] Fix members of GetCookiesOption
  types/tough-cookie/index.d.ts
  types/tough-cookie/tough-cookie-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40865 [reactstrap] Update typings to 8.2
  types/reactstrap/index.d.ts
  types/reactstrap/lib/Button.d.ts
  types/reactstrap/lib/ButtonToggle.d.ts
  types/reactstrap/lib/Container.d.ts
  types/reactstrap/lib/Dropdown.d.ts
  types/reactstrap/lib/ListGroup.d.ts
  types/reactstrap/lib/NavbarText.d.ts
  types/reactstrap/lib/Popover.d.ts
  types/reactstrap/lib/Row.d.ts
  types/reactstrap/lib/Tooltip.d.ts
  types/reactstrap/reactstrap-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#40738 [ramda] cleanup
  types/ramda/OTHER_FILES.txt
  types/ramda/README.md
  types/ramda/index.d.ts
  types/ramda/package.json
  types/ramda/ramda-tests.ts
  types/ramda/test/filter-tests.ts
  types/ramda/test/maxBy-tests.ts
  types/ramda/test/minBy-tests.ts
  types/ramda/tools.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same, Popular package

#40830 [office-js, office-js-preview] Excel updates from CDN (ExcelApiOnline 1.1)
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#40840 Fix missing argument defintion in nuxtjs__auth
  types/nuxtjs__auth/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40867 [office-js, office-js-preview] Specifying table name restrictions
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#40748 Added missing VictoryPortal type definitions with tests
  types/victory/index.d.ts
  types/victory/victory-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same

#40868 Sync frida-gum typings with Frida 12.7.25
  types/frida-gum/index.d.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#38878 Feature/parse/various
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#40829 Add missing typings for react-mentions v3.3.0
  types/react-mentions/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40872 [chart.js] Added missing property `z` to GridLineOptions.
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40835 [react-native] Fix SectionList component type and add missing methods
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40881 Remove instances of hard-coded strings in css-tree
  types/css-tree/index.d.ts
Labels: Author is Owner, Merge:Express, Perf: Same, Popular package

#40501 [@types/react-highlight] add innerHTML prop and make all props optional
  types/react-highlight/index.d.ts
  types/react-highlight/react-highlight-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40631 [@types/google.visualization] adding missing tooltip action methods
  types/google.visualization/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40642 [Enzyme] Allow .find() with class component type parameter
  types/enzyme/enzyme-tests.tsx
  types/enzyme/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#40862 Add "compact" option to Globalize's CommonNumberFormatterOptions.
  types/globalize/dist/globalize.d.ts
  types/globalize/globalize-tests.ts
Labels: Owner Approved, Perf: Same, Revision needed

#40647 Update KaTeX to v0.11.1
  types/katex/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40753 [react-syntax-highlighter] Fix lineProps and codeTagProps
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#40889 plotly.js: Move direction from Layout to PlotData
  types/plotly.js/index.d.ts
  types/plotly.js/test/core-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40876 aws-lambda - removes the wrong assumption that headers are always set
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40863 - Added missing property
  types/react-native-sqlite-storage/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40673 Update types for amphtml-validator
  types/amphtml-validator/amphtml-validator-tests.ts
  types/amphtml-validator/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#40903 power-assert: follow-up to microsoft/TypeScript#35566
  types/power-assert/index.d.ts
  types/power-assert/ts3.7/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#40906 ramda: Remove myself from maintainers
  types/ramda/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#40880 [react] Add crossOrigin to SVGAttributes
  types/react/index.d.ts
  types/react/test/elementAttributes.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40896 [@types/node] Use ExecException for child_process.execFile()
  types/node/child_process.d.ts
  types/node/v10/child_process.d.ts
Labels: Merge:Express, Owner Approved, Perf: Worse, Popular package

#40652 @types/stripe-v3: Element addEventListener and on is alias of eachother
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#40732 [@types/react-loadable] Remove `() => null` type definition for `loading` prop option
  types/react-loadable/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40809 docs: add usage example & fix: correct fn name for express-list-endpoints
  types/express-list-endpoints/express-list-endpoints-tests.ts
  types/express-list-endpoints/index.d.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#40803 [PapaParse] Add delimitersToGuess to ParseConfig definition
  types/papaparse/index.d.ts
  types/papaparse/papaparse-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#40810 [styled-components] Allow static properties to be passed through
  types/styled-components/index.d.ts
  types/styled-components/test/index.tsx
  types/styled-components/ts3.7/index.d.ts
  types/styled-components/ts3.7/test/index.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40914 Bookshelf: prettier, methods removed and update options
  types/bookshelf/index.d.ts
Labels: Merge:Express, Owner Approved

#40588 feat(react-swipeable-views-utils): Add types
  types/react-swipeable-views-utils/index.d.ts
  types/react-swipeable-views-utils/package.json
  types/react-swipeable-views-utils/react-swipeable-views-utils-tests.tsx
  types/react-swipeable-views-utils/tsconfig.json
  types/react-swipeable-views-utils/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#40878 [@types/parse] 2.10: Stricter Parse.Object attributes type, improve linting, and add tests
  types/parse/index.d.ts
  types/parse/parse-tests.ts
  types/parse/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Perf: Same

#40842 Adds interface-datastore types with tests
  types/interface-datastore/index.d.ts
  types/interface-datastore/interface-datastore-tests.ts
  types/interface-datastore/tsconfig.json
  types/interface-datastore/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#40800 Adjust polymer attributeChangedCallback to spec.
  types/polymer/index.d.ts
  types/webcomponents.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#40760 Make map type optional [ffmpeg-fluent]
  types/fluent-ffmpeg/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#40703 Fix a couple option types on Cesium classes ImageMaterialProperty and LabelGraphics
  types/cesium/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#40817 [react-naitve] fix YellowBox type
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#40704 Add sticky-session to types
  types/sticky-session/index.d.ts
  types/sticky-session/sticky-session-tests.ts
  types/sticky-session/tsconfig.json
  types/sticky-session/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#40852 Add "File" type to both add functions as input
  types/webtorrent/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40854 fix: mask must accept Regex[] type - react-input-mask
  types/react-input-mask/index.d.ts
  types/react-input-mask/react-input-mask-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40933 Sync frida-gum typings with Frida 12.7.26
  types/frida-gum/index.d.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#40649 [@types/dc] updated dc type definitions to latest version
  types/dc/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#40687 [office-js, office-js-preview] Adding PDF support note for Excel on the web
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same, Revision needed

#40718 [dropzone] Update types for success callback
  types/dropzone/dropzone-tests.ts
  types/dropzone/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#40937 Mongoose: add session? to QueryFindOneAndUpdateOptions interface
  types/mongoose/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40936 chart.js - stop(), resize(), clear() return 'this', not empty object
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40921 matter-js: Adds missing background property types
  types/matter-js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40942 [@types/stripe] Update IEvent previous_attributes type
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40837 Add DamerauLevenshteinDistance to natural
  types/natural/index.d.ts
  types/natural/natural-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40890 [parquetjs] Add useDataPageV2 option, deduplicate opts to interface
  types/parquetjs/lib/writer.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40902 ISubscriptionUpdateOptions within stripe looks for a default_source and not source parameter
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40893 fix(stripe): add off_session and default_payment_method to subscripti…
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40769 [@types/stripe] Update payment intent payment methods
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40904 chai.d.ts add .include aliases to Deep, Nested, and Own interfaces
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40912 [@types/node] Add close event to FSWatcher
  types/node/fs.d.ts
  types/node/v10/fs.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40672 [@types/gremlin] Update translator type to be able to translate scripts to submit to Azure's Cosmos DB
  types/gremlin/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40696 update: update the jsescOption options for babel_generator
  types/babel__generator/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#40702 Plotly.js tweaks
  types/plotly.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40706 analytics-node: Add types for timeout option in Analytics constructor
  types/analytics-node/analytics-node-tests.ts
  types/analytics-node/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40790 add types jsreport-chrome-pdf
  types/jsreport-chrome-pdf/index.d.ts
  types/jsreport-chrome-pdf/jsreport-chrome-pdf-tests.ts
  types/jsreport-chrome-pdf/tsconfig.json
  types/jsreport-chrome-pdf/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#40798 Added 'node-loggly-bulk' package support
  types/node-loggly-bulk/index.d.ts
  types/node-loggly-bulk/node-loggly-bulk-tests.ts
  types/node-loggly-bulk/tsconfig.json
  types/node-loggly-bulk/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#40802 Add definitions for `react-cookies`
  types/react-cookies/index.d.ts
  types/react-cookies/react-cookies-tests.ts
  types/react-cookies/tsconfig.json
  types/react-cookies/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#40721 plotly.js: Icon's ascent/descent are optional (and deprecated)
  types/plotly.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40757 Added negotiateLocale(key) to angular-translate
  types/angular-translate/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same, Revision needed

#40763 mongoose-paginate-v2: support read opts, mongoose: tiny typo fix
  types/mongoose-paginate-v2/index.d.ts
  types/mongoose/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#40714 `react-modal`: add `portal` instance property
  types/react-modal/index.d.ts
  types/react-modal/react-modal-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#37803 [diva.js] Add types for diva.js
  types/diva.js/diva.js-tests.ts
  types/diva.js/document-layout.d.ts
  types/diva.js/handlers.d.ts
  types/diva.js/image-manifest.d.ts
  types/diva.js/index.d.ts
  types/diva.js/interfaces.d.ts
  types/diva.js/renderer.d.ts
  types/diva.js/tsconfig.json
  types/diva.js/tslint.json
  types/diva.js/viewer-core.d.ts
  types/diva.js/viewport.d.ts
Labels: New Definition, Revision needed

#37711 Update option to current version
  types/webpack-hot-middleware/index.d.ts
Labels: Popular package, Revision needed

#40978 Update status badges
  README.cn.md
  README.md
  README.ru.md
Labels: Unowned

#40998 VS Code 1.41.0 Extension API
  types/vscode/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#40976 types/react-grid-layout: update types for version 0.17.1
  types/react-grid-layout/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41001 [fancytree] Add ext-persist's getPersistData() return type
  types/jquery.fancytree/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41005 swagger-ui-dist: Change `layout` field to accept any string
  types/swagger-ui-dist/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40997 Add typings to GeometryFactory in jsts.
  types/jsts/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40991 [@types/carbon-components-react] add missing ReactAnchorAttr types to SwitcherItem
  types/carbon-components-react/lib/components/UIShell/SwitcherItem.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40984 [echarts] update links in doc
  types/echarts/index.d.ts
  types/echarts/options/axis-pointer.d.ts
  types/echarts/options/data-zoom.d.ts
  types/echarts/options/series/bar.d.ts
  types/echarts/options/series/boxplot.d.ts
  types/echarts/options/series/candlestick.d.ts
  types/echarts/options/series/custom.d.ts
  types/echarts/options/series/effect-scatter.d.ts
  types/echarts/options/series/funnel.d.ts
  types/echarts/options/series/gauge.d.ts
  types/echarts/options/series/graph.d.ts
  types/echarts/options/series/heatmap.d.ts
  types/echarts/options/series/line.d.ts
  types/echarts/options/series/lines.d.ts
  types/echarts/options/series/map.d.ts
  types/echarts/options/series/parallel.d.ts
  types/echarts/options/series/pictorial-bar.d.ts
  types/echarts/options/series/pie.d.ts
  types/echarts/options/series/radar.d.ts
  types/echarts/options/series/sankey.d.ts
  types/echarts/options/series/scatter.d.ts
  types/echarts/options/series/sunburst.d.ts
  types/echarts/options/series/theme-river.d.ts
  types/echarts/options/series/tree.d.ts
  types/echarts/options/series/treemap.d.ts
  types/echarts/options/single-axis.d.ts
  types/echarts/options/tooltip.d.ts
  types/echarts/options/x-axis.d.ts
  types/echarts/options/y-axis.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#40966 [@types/ioredis] hgetall returns object
  types/ioredis/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40971 types/react-stripe-elements: add InjectedStripeProps.elements
  types/react-stripe-elements/index.d.ts
  types/react-stripe-elements/react-stripe-elements-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#41012 fix(rdf-js): match should allow null on optional parameters
  types/rdf-js/index.d.ts
  types/rdf-js/rdf-js-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40883 react-widgets: fix busySpinner missing from DropdownList typing
  types/react-widgets/index.d.ts
  types/react-widgets/lib/DropdownList.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40970 types/stripe-v3: add elements.Elements.getElement
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40972 Add missing types and fix existing types for cbor 5.0
  types/cbor/cbor-tests.ts
  types/cbor/index.d.ts
  types/cbor/tslint.json
Labels: Merge:Express, Owner Approved

#40801 add support for trackSingle and trackSingleCustom types in facebook pixel
  types/facebook-pixel/facebook-pixel-tests.ts
  types/facebook-pixel/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40960 keystonejs__keystone - Added build function to base app type.
  types/keystonejs__keystone/index.d.ts
  types/keystonejs__keystone/keystonejs__keystone-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#40895 [@types/aws-lambda] Fix Context.memoryLimitInMB type
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/index.d.ts
  types/aws-serverless-express/aws-serverless-express-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40958 @types/braintree webhooks
  types/braintree/braintree-tests.ts
  types/braintree/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#40946 fix(mapbox-gl): add missing accessToken prop on MapboxOptions
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#40948 fix(theme-ui): simplify SxStyleProp type
  types/theme-ui/index.d.ts
  types/theme-ui/theme-ui-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same
