Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2019-04, with the labels that each got.

#34230 [meteor] Fixing generate-globals script - file EOLs may not be the same as sys. EOLs
  types/meteor/scripts/generate-globals
Labels: Awaiting reviewer feedback, Merge:YSYL

#34338 [luxon] Refine types further
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#34373 -added more properties on attachment object
  types/sendmail/index.d.ts
Labels: Author is Owner, Merge:Express

#34361 [jexl] Upgrade types for jexl@2.1 by TomFrost
  types/jexl/index.d.ts
  types/jexl/jexl-tests.ts
Labels: Author is Owner, Merge:Express

#34356 [storybook-readme] Migrate to v5
  types/storybook-readme/index.d.ts
  types/storybook-readme/storybook-readme-tests.tsx
Labels: Author is Owner, Merge:Express

#34353 Update force-graph to support version 1.14.4
  types/force-graph/index.d.ts
Labels: Author is Owner, Merge:Express

#34348 firefox-webext-browser - Fix a lot of event types
  types/firefox-webext-browser/firefox-webext-browser-tests.ts
  types/firefox-webext-browser/index.d.ts
Labels: Author is Owner, Merge:Express

#34303 [arcgis-js-api] Update for version 4.11
  types/arcgis-js-api/index.d.ts
Labels: Merge:Express, Owner Approved

#34285 Add overloads to child_process.spawn for better type inference
  types/node/child_process.d.ts
  types/node/test/child_process.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package, Revision needed

#34318 Fixed property type in @types/jsoneditor
  types/jsoneditor/index.d.ts
Labels: Merge:Express, Owner Approved

#34314 [marked] Add InlineLexer Type
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package, Revision needed

#34306 react-tag-autocomplete - Add type for handleValidate prop function
  types/react-tag-autocomplete/index.d.ts
  types/react-tag-autocomplete/react-tag-autocomplete-tests.tsx
Labels: Merge:Express, Owner Approved

#34327 @types/node Improve https and tls types
  types/node/https.d.ts
  types/node/node-tests.ts
  types/node/test/tls.ts
  types/node/tls.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#34345 align-text: optional callback
  types/align-text/index.d.ts
  types/align-text/test/array.ts
  types/align-text/test/simple.ts
  types/align-text/tsconfig.json
Labels: Author is Owner, Merge:Express

#34221 bn.js: Adds Uint8Array as a valid constructor argument.
  types/bn.js/bn.js-tests.ts
  types/bn.js/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#34324 express-http-proxy: Improve Proxy Command Typings
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Merge:Express, Owner Approved

#34358 koa-log4: Add support for 'auto' log level.
  types/koa-log4/index.d.ts
Labels: Merge:Express, Owner Approved

#34260 [@storybook/vue] add missing optional option (useful for notes)
  types/storybook__vue/index.d.ts
  types/storybook__vue/storybook__vue-tests.ts
Labels: Merge:Express, Owner Approved

#34364 refactor(shelljs): Refactor ShellJS types to be more correct
  types/shelljs/.editorconfig
  types/shelljs/index.d.ts
  types/shelljs/make.d.ts
  types/shelljs/shelljs-tests.ts
  types/shelljs/tsconfig.json
  types/shelljs/tslint.json
Labels: Owner Approved, Popular package, Revision needed, Where is Travis?

#34270 [Pusher-JS] update static type def to include static properties
  types/pusher-js/index.d.ts
  types/pusher-js/pusher-js-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#34189 Attempts are passed to onRetry function
  types/async-retry/index.d.ts
Labels: Merge:Express, Owner Approved

#34308 Add definition for the handleKey function within the mousetrap module
  types/mousetrap/index.d.ts
  types/mousetrap/test/index.ts
Labels: Merge:Express, Owner Approved

#34343 Add non-singleton version of yargs, and other things used by lerna
  types/yargs/index.d.ts
  types/yargs/tsconfig.json
  types/yargs/yargs-tests.ts
  types/yargs/yargs.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#34196 [stripe] Updated create and update invoice
  types/stripe/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#34296 semver: add missing properties and functions, correct some parameter types
  types/semver/index.d.ts
  types/semver/semver-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#34241 Update tmp to 0.1
  types/tmp/index.d.ts
  types/tmp/tmp-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#34295 watch: Incorrect type for Options.ignoreDirectoryPattern
  types/watch/index.d.ts
Labels: Merge:Express, Owner Approved

#34301 React-Tagcloud - types fix
  types/react-tagcloud/index.d.ts
Labels: Merge:Express, Owner Approved

#34249 [facepaint] Add type definitions
  types/facepaint/facepaint-tests.ts
  types/facepaint/index.d.ts
  types/facepaint/tsconfig.json
  types/facepaint/tslint.json
Labels: New Definition, Revision needed, The Travis CI build failed

#34236 Added type definitions for `burns`
  types/burns/burns-tests.ts
  types/burns/index.d.ts
  types/burns/tsconfig.json
  types/burns/tslint.json
Labels: New Definition, Revision needed

#34378 Lodash: `flow`: add missing test for 0-argument first function
  types/lodash/lodash-tests.ts
Labels: Popular package, The Travis CI build failed

#34342 Export interface HitsProvided
  types/react-instantsearch-core/index.d.ts
Labels: Merge:Express, Owner Approved

#34412 [office-js-preview] Updating Excel Preview APIs
  types/office-js-preview/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#34394 @types/xml2js change the type of the Error object
  types/xml2js/index.d.ts
  types/xml2js/xml2js-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#34399 [Lozad] Expose IntersectionObserver object, and fix version to 1.9
  types/lozad/index.d.ts
  types/lozad/lozad-tests.ts
Labels: Merge:Express, Owner Approved

#34384 Added `Client.atomicUpdate` to solr-client Types
  types/solr-client/index.d.ts
Labels: Merge:Express, Owner Approved

#34395 fix(js-yaml): predicate is a function and not a string
  types/js-yaml/index.d.ts
  types/js-yaml/js-yaml-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#34352 Update react-resize-detector types to version 4
  types/react-resize-detector/index.d.ts
  types/react-resize-detector/react-resize-detector-tests.tsx
Labels: Merge:Express, Owner Approved

#34390 Fix return type of @storybook/addon-knobs/radios
  types/storybook__addon-knobs/index.d.ts
  types/storybook__addon-knobs/storybook__addon-knobs-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#34388 [redux-sentry-middleware]: Updated dependency, fixed transformer return types
  types/redux-sentry-middleware/index.d.ts
  types/redux-sentry-middleware/package.json
Labels: Author is Owner, Merge:Express

#34411 Add types for follow-redirects
  types/follow-redirects/follow-redirects-tests.ts
  types/follow-redirects/http.d.ts
  types/follow-redirects/https.d.ts
  types/follow-redirects/index.d.ts
  types/follow-redirects/tsconfig.json
  types/follow-redirects/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34401 react-window: Add direction & layout props
  types/react-window/index.d.ts
  types/react-window/react-window-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved

#34409 add parse-human-date-range
  types/parse-human-date-range/index.d.ts
  types/parse-human-date-range/parse-human-date-range-tests.ts
  types/parse-human-date-range/tsconfig.json
  types/parse-human-date-range/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34410 Add types for tough-cookie-file-store
  types/tough-cookie-file-store/index.d.ts
  types/tough-cookie-file-store/tough-cookie-file-store-tests.ts
  types/tough-cookie-file-store/tsconfig.json
  types/tough-cookie-file-store/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34407 [math-trunc] Add type definitions
  types/math-trunc/index.d.ts
  types/math-trunc/math-trunc-tests.ts
  types/math-trunc/tsconfig.json
  types/math-trunc/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34398 Add types for stream-mock
  types/stream-mock/index.d.ts
  types/stream-mock/stream-mock-tests.ts
  types/stream-mock/tsconfig.json
  types/stream-mock/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34417 [storybook-readme] Make arguments of config to optional
  types/storybook-readme/index.d.ts
Labels: Author is Owner, Merge:Express

#34377 Add types for rtl-detect
  types/rtl-detect/index.d.ts
  types/rtl-detect/rtl-detect-tests.ts
  types/rtl-detect/tsconfig.json
  types/rtl-detect/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34376 Add types for find-down
  types/find-down/find-down-tests.ts
  types/find-down/index.d.ts
  types/find-down/tsconfig.json
  types/find-down/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34362 [is-image] Add type of is-image
  types/is-image/index.d.ts
  types/is-image/is-image-tests.ts
  types/is-image/tsconfig.json
  types/is-image/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34360 [imul] Add type definitions
  types/imul/imul-tests.ts
  types/imul/index.d.ts
  types/imul/tsconfig.json
  types/imul/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34355 new package: reapeating
  types/repeating/index.d.ts
  types/repeating/repeating-tests.ts
  types/repeating/tsconfig.json
  types/repeating/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#34354 New type definition of non-npm package amap-js-api-geocoder
  types/amap-js-api-geocoder/amap-js-api-geocoder-tests.ts
  types/amap-js-api-geocoder/index.d.ts
  types/amap-js-api-geocoder/tsconfig.json
  types/amap-js-api-geocoder/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34277 [graphql-api-koa] Add initial type definitions
  types/graphql-api-koa/graphql-api-koa-tests.ts
  types/graphql-api-koa/index.d.ts
  types/graphql-api-koa/tsconfig.json
  types/graphql-api-koa/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#33933 ramda: support R.__ in R.propOr
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#33567 [react-request] add more types
  types/react-request/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#34177 [ckeditor] Set parameters to optional for filter.applyTo()
  types/ckeditor/ckeditor-tests.ts
  types/ckeditor/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#34227 Add react-image-crop `renderSelectionAddon(state)`
  types/react-image-crop/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#34035 Adds support for @rebass/grid/emotion
  types/rebass__grid/emotion.d.ts
  types/rebass__grid/index.d.ts
  types/rebass__grid/rebass__grid-tests.tsx
  types/rebass__grid/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#34248 Type definition for sbd library
  types/sbd/index.d.ts
  types/sbd/sbd-tests.ts
  types/sbd/tsconfig.json
  types/sbd/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#34132 [sharedb] Update type signatures for Backend #use and #addProjection
  types/sharedb/index.d.ts
  types/sharedb/lib/sharedb.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#34304 Update type definitions for react-helmet-async v1.0
  types/react-helmet-async/index.d.ts
  types/react-helmet-async/react-helmet-async-tests.tsx
  types/react-helmet-async/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#34418 [google-apps-script] Add Apps Script Event Types
  types/google-apps-script/google-apps-script-events.d.ts
  types/google-apps-script/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#34259 [@types/google__maps] fix: PlaceSearchResult vicinity is a string
  types/google__maps/index.d.ts
Labels: Merge:Express, Owner Approved, Where is Travis?

#33703 [axe-webdriverjs] Update analyze function definition
  types/axe-webdriverjs/axe-webdriverjs-tests.ts
  types/axe-webdriverjs/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Revision needed

#34243 Remove elastic-apm-node
  notNeededPackages.json
  types/elastic-apm-node/elastic-apm-node-tests.ts
  types/elastic-apm-node/index.d.ts
  types/elastic-apm-node/start.d.ts
  types/elastic-apm-node/tsconfig.json
  types/elastic-apm-node/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#34222 underscore: Allow to pass _.List<T> to OOP wrapper
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#34276 [graphql-react] Add initial type definitions
  types/graphql-react/graphql-react-tests.tsx
  types/graphql-react/index.d.ts
  types/graphql-react/tsconfig.json
  types/graphql-react/tslint.json
Labels: New Definition, Revision needed

#34366 [react-alice-carousel] Update to v1.13
  types/react-alice-carousel/index.d.ts
Labels: Owner Approved, Revision needed

#34448 @types/react-resize-detector: Fix the type of onResize and update to v4.0.5
  types/react-resize-detector/index.d.ts
  types/react-resize-detector/react-resize-detector-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#34200 [toastr] support strictNullChecks and optional parameters as undefined.
  types/toastr/index.d.ts
  types/toastr/toastr-tests.ts
  types/toastr/tsconfig.json
Labels: Popular package, Revision needed

#34267 feat(react): support onAuxClick & onAuxClickCapture events
  types/react/index.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#34436 [react-virtualized]fix incompatible onScroll type for ListProps by using OnScrollParams
  types/react-virtualized/dist/es/List.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#34428 [marked] Fix property
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#34441 Typings for 'hummus-recipe'
  types/hummus-recipe/hummus-recipe-tests.ts
  types/hummus-recipe/index.d.ts
  types/hummus-recipe/tsconfig.json
  types/hummus-recipe/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34442 [math-sign] Add type definitions
  types/math-sign/index.d.ts
  types/math-sign/math-sign-tests.ts
  types/math-sign/tsconfig.json
  types/math-sign/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34427 Use esModuleInterop mode, and improve tests
  types/graphql-api-koa/graphql-api-koa-tests.ts
  types/graphql-api-koa/tsconfig.json
Labels: Unowned

#34188 Add a description about asOfVersion in "Removing a package"
  README.md
Labels: Merge:YSYL, Unowned, Where is Travis?

#34440 [@types/webpack] Adding missing webpack property "version"
  types/webpack/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#34403 flexmonster.d.ts update
  types/flexmonster/index.d.ts
Labels: Author is Owner, Revision needed

#34253 [react] RE: Add unstable_Profiler
  types/react/index.d.ts
  types/react/test/tsx.tsx
Labels: Owner Approved, Popular package, The Travis CI build failed

#34435 Updating firefox-webext-browser to v67.0b7
  types/firefox-webext-browser/index.d.ts
Labels: Author is Owner, Merge:Express

#34375 Improve @rebase/grid
  types/rebass__grid/index.d.ts
  types/rebass__grid/rebass__grid-tests.tsx
Labels: Merge:Express, Owner Approved

#34408 Add markdown-to-jsx typings
  types/markdown-to-jsx/index.d.ts
  types/markdown-to-jsx/markdown-to-jsx-tests.tsx
  types/markdown-to-jsx/tsconfig.json
  types/markdown-to-jsx/tslint.json
Labels: New Definition, Revision needed

#34454 Move global declarations into a namespace for 'amap-js-api'.
  types/amap-js-api/type-util.d.ts
Labels: Merge:Express, Owner Approved

#34471 attachment filename optional based on package requirement
  types/sendmail/index.d.ts
Labels: Author is Owner, Merge:Express

#34468 WebAssembly JS API Definition Update
  types/webassembly-js-api/index.d.ts
  types/webassembly-js-api/tsconfig.json
  types/webassembly-js-api/webassembly-js-api-tests.ts
Labels: Merge:Express, Owner Approved

#34469 [@types/hogan.js] Add type definitions for hogan.js
  types/hogan.js/hogan.js-tests.ts
  types/hogan.js/index.d.ts
  types/hogan.js/tsconfig.json
  types/hogan.js/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34334 fix(auth0-js): extend cross origin login options with missing authorize options
  types/auth0-js/auth0-js-tests.ts
  types/auth0-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#34465 [async-retry] Change options type to extend retry library types
  types/async-retry/async-retry-tests.ts
  types/async-retry/index.d.ts
Labels: Merge:Express, Owner Approved

#34450 Add react-linkify module to DefinitelyTyped
  types/react-linkify/index.d.ts
  types/react-linkify/react-linkify-tests.tsx
  types/react-linkify/tsconfig.json
  types/react-linkify/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34429 [react-burger-menu] Add missing types to match v2.6.8
  types/react-burger-menu/index.d.ts
Labels: Merge:Express, Owner Approved

#34406 [hoist-non-react-statics] Fix #33690 once and for all
  types/hoist-non-react-statics/package.json
Labels: Merge:Express, Owner Approved, Popular package

#34382 fix(node-fetch): HeadersInit type
  types/node-fetch/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#34430 [@types/google-apps-script] Simplify Apps Script Advanced Types. Remove versions.
  types/google-apps-script/apis/adsense_v1_4.d.ts
  types/google-apps-script/apis/analytics_v3.d.ts
  types/google-apps-script/apis/analyticsreporting_v4.d.ts
  types/google-apps-script/apis/appsactivity_v1.d.ts
  types/google-apps-script/apis/bigquery_v2.d.ts
  types/google-apps-script/apis/calendar_v3.d.ts
  types/google-apps-script/apis/classroom_v1.d.ts
  types/google-apps-script/apis/content_v2.d.ts
  types/google-apps-script/apis/dfareporting_v3_3.d.ts
  types/google-apps-script/apis/directory_v1.d.ts
  types/google-apps-script/apis/docs_v1.d.ts
  types/google-apps-script/apis/drive_v2.d.ts
  types/google-apps-script/apis/driveactivity_v2.d.ts
  types/google-apps-script/apis/fusiontables_v2.d.ts
  types/google-apps-script/apis/gmail_v1.d.ts
  types/google-apps-script/apis/groupsmigration_v1.d.ts
  types/google-apps-script/apis/groupssettings_v1.d.ts
  types/google-apps-script/apis/licensing_v1.d.ts
  types/google-apps-script/apis/mirror_v1.d.ts
  types/google-apps-script/apis/peopleapi_v1.d.ts
  types/google-apps-script/apis/reports_v1.d.ts
  types/google-apps-script/apis/reseller_v1.d.ts
  types/google-apps-script/apis/sheets_v4.d.ts
  types/google-apps-script/apis/slides_v1.d.ts
  types/google-apps-script/apis/tagmanager_v2.d.ts
  types/google-apps-script/apis/tasks_v1.d.ts
  types/google-apps-script/apis/urlshortener_v1.d.ts
  types/google-apps-script/apis/youtube_v3.d.ts
  types/google-apps-script/apis/youtubeanalytics_v2.d.ts
  types/google-apps-script/apis/youtubepartner_v1.d.ts
  types/google-apps-script/google-apps-script-tests.ts
  types/google-apps-script/google-apps-script.calendar.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#34420 [sarif] Update to latest sarif version 2.0.0-csd.2.beta-2019-04-03
  types/sarif/index.d.ts
Labels: Author is Owner, Merge:Express

#34422 [react-native-tab-view] change labelStyle to TextStyle
  types/react-native-tab-view/index.d.ts
Labels: Merge:Express, Owner Approved

#34421 [stripe] Add missing invoice.auto_advance
  types/stripe/index.d.ts
  types/stripe/stripe-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#34470 Add definition of non-npm package amap-js-api-autocomplete
  types/amap-js-api-autocomplete/amap-js-api-autocomplete-tests.ts
  types/amap-js-api-autocomplete/index.d.ts
  types/amap-js-api-autocomplete/tsconfig.json
  types/amap-js-api-autocomplete/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34462 [react-transition-group] Support optional `classNames` prop on `<CSSTransition/>`
  types/react-transition-group/CSSTransition.d.ts
  types/react-transition-group/index.d.ts
  types/react-transition-group/react-transition-group-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#34425 [qrcode-svg] Add type definitions for qrcode-svg module
  types/qrcode-svg/index.d.ts
  types/qrcode-svg/qrcode-svg-tests.ts
  types/qrcode-svg/tsconfig.json
  types/qrcode-svg/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#34458 Add types for @ungap/url-search-params
  types/ungap__url-search-params/index.d.ts
  types/ungap__url-search-params/tsconfig.json
  types/ungap__url-search-params/tslint.json
  types/ungap__url-search-params/ungap__url-search-params-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#34331 Fix Slick.EventHandler
  types/slickgrid/index.d.ts
  types/slickgrid/test/index.ts
  types/slickgrid/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#34350 Update rotation prop to Plotdata at index.d.ts
  types/plotly.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#34238 new package: word-wrap
  types/word-wrap/index.d.ts
  types/word-wrap/tsconfig.json
  types/word-wrap/tslint.json
  types/word-wrap/word-wrap-tests.ts
Labels: New Definition, Revision needed

#34140 Add react-tabs-redux types
  types/react-tabs-redux/TabContent.d.ts
  types/react-tabs-redux/TabLink.d.ts
  types/react-tabs-redux/Tabs.d.ts
  types/react-tabs-redux/index.d.ts
  types/react-tabs-redux/react-tabs-redux-tests.tsx
  types/react-tabs-redux/tsconfig.json
  types/react-tabs-redux/tslint.json
Labels: New Definition, Revision needed

#34148 [lyricist] added definitions and tests
  types/lyricist/index.d.ts
  types/lyricist/lyricist-tests.ts
  types/lyricist/tsconfig.json
  types/lyricist/tslint.json
Labels: New Definition, Revision needed

#34481 [fast-ratelimit] Add type definitions for fast-ratelimit
  types/fast-ratelimit/fast-ratelimit-tests.ts
  types/fast-ratelimit/index.d.ts
  types/fast-ratelimit/tsconfig.json
  types/fast-ratelimit/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34499 [styled-components] Revert union distribution
  types/styled-components/index.d.ts
  types/styled-components/test/index.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#34508 [styled-system] updated BordersProps in v4.1
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Merge:Express, Owner Approved

#34246 [CodeMirror] Add commands actions
  types/codemirror/codemirror-showhint.d.ts
  types/codemirror/index.d.ts
  types/codemirror/test/index.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#34400 Ember: fix type for `Route#controllerFor`.
  types/ember/test/inject.ts
  types/ember__routing/route.d.ts
  types/ember__routing/test/route.ts
Labels: Merge:Express, Owner Approved, Revision needed

#34495 [hls.js] Restore Hls.media property and fix annotation.
  types/hls.js/hls.js-tests.ts
  types/hls.js/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved

#34446 Dockerode: Correctly type Entrypoint fields for creation and inspection
  types/dockerode/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#34482 Add type for new "ref" proptype in airbnb-prop-type
  types/airbnb-prop-types/airbnb-prop-types-tests.ts
  types/airbnb-prop-types/index.d.ts
Labels: Merge:Express, Owner Approved

#34476 Added the optional parameter to the save function.
  types/jspdf/index.d.ts
Labels: Merge:Express, Owner Approved

#34487 [amap-js-api] fix typo
  types/amap-js-api/amap-js-api-tests.ts
  types/amap-js-api/overlay/circle.d.ts
Labels: Author is Owner, Merge:Express

#34506 [Tern] fix event handler signature
  types/tern/lib/tern/index.d.ts
Labels: Author is Owner, Merge:Express, Popular package

#34516 Add playThroughEarpieceAndroid option to AudioMode.
  types/expo/expo-tests.tsx
  types/expo/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#34519 [undertaker] Update metadata & fix .task return
  types/gulp/test/index.ts
  types/undertaker/index.d.ts
  types/undertaker/undertaker-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#34439 Add type definitions for square-connect npm library
  types/square-connect/index.d.ts
  types/square-connect/square-connect-tests.ts
  types/square-connect/tsconfig.json
  types/square-connect/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34518 Add types for use-dark-mode
  types/use-dark-mode/index.d.ts
  types/use-dark-mode/tsconfig.json
  types/use-dark-mode/tslint.json
  types/use-dark-mode/use-dark-mode-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#34537 new package: isarray
  types/isarray/index.d.ts
  types/isarray/isarray-tests.ts
  types/isarray/tsconfig.json
  types/isarray/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#34536 addWithUpdate parameter is optional and fill property should accept pattern type
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#34505 React-datepicker: add missing strictParsing property
  types/react-datepicker/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#34485 [algoliasearch] Added forwardToReplicas to setSettings
  types/algoliasearch/algoliasearch-tests.ts
  types/algoliasearch/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#34147 [musicmatch] added basic definitions and tests
  types/musicmatch/index.d.ts
  types/musicmatch/musicmatch-tests.ts
  types/musicmatch/tsconfig.json
  types/musicmatch/tslint.json
Labels: New Definition, Revision needed

#34162 Add new ServiceNow London API type definitions
  types/servicenow-london/Class.d.ts
  types/servicenow-london/GlideDBFunctionBuilder.d.ts
  types/servicenow-london/GlideDate.d.ts
  types/servicenow-london/GlideDateTime.d.ts
  types/servicenow-london/GlideDuration.d.ts
  types/servicenow-london/GlideEmailOutbound.d.ts
  types/servicenow-london/GlideFilter.d.ts
  types/servicenow-london/GlideLocale.d.ts
  types/servicenow-london/GlidePluginManager.d.ts
  types/servicenow-london/GlideRecordOperation.d.ts
  types/servicenow-london/GlideSchedule.d.ts
  types/servicenow-london/GlideScopedEvaluator.d.ts
  types/servicenow-london/GlideScriptedProcessor.d.ts
  types/servicenow-london/GlideSecureRandomUtil.d.ts
  types/servicenow-london/GlideServletRequest.d.ts
  types/servicenow-london/GlideServletResponse.d.ts
  types/servicenow-london/GlideSession.d.ts
  types/servicenow-london/GlideStringUtil.d.ts
  types/servicenow-london/GlideSysAttachment.d.ts
  types/servicenow-london/GlideSystem.d.ts
  types/servicenow-london/GlideTime.d.ts
  types/servicenow-london/GlideUser.d.ts
  types/servicenow-london/QueryOperator.d.ts
  types/servicenow-london/RESTAPIRequest.d.ts
  types/servicenow-london/RESTAPIRequestBody.d.ts
  types/servicenow-london/RESTAPIResponse.d.ts
  types/servicenow-london/RESTAPIResponseStream.d.ts
  types/servicenow-london/RESTMessageV2.d.ts
  types/servicenow-london/RESTResponseV2.d.ts
  types/servicenow-london/RenderProperties.d.ts
  types/servicenow-london/SOAPMessageV2.d.ts
  types/servicenow-london/SOAPResponseV2.d.ts
  types/servicenow-london/ScopedElementDescriptor.d.ts
  types/servicenow-london/ScopedGlideElement.d.ts
  types/servicenow-london/ScopedGlideRecord.d.ts
  types/servicenow-london/ScopedQueryCondition.d.ts
  types/servicenow-london/Workflow.d.ts
  types/servicenow-london/XMLDocument2.d.ts
  types/servicenow-london/XMLNode.d.ts
  types/servicenow-london/XMLNodeIterator.d.ts
  types/servicenow-london/index.d.ts
  types/servicenow-london/servicenow-london-tests.ts
  types/servicenow-london/tsconfig.json
  types/servicenow-london/tslint.json
Labels: New Definition, Revision needed

#34265 Add typings for cuint
  types/cuint/cuint-tests.ts
  types/cuint/index.d.ts
  types/cuint/tsconfig.json
  types/cuint/tslint.json
Labels: New Definition, Revision needed

#34386 [React] Fix optionality of inferred props
  types/react/index.d.ts
  types/react/test/managedAttributes.tsx
Labels: Owner Approved, Popular package, The Travis CI build failed

#34344 Mongoose: fix wrong type of shardKey in schema option
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Owner Approved, Popular package, Revision needed

#34554 [node] Add typed encoding argument to Buffer methods
  types/node/globals.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#34402 xrm: Set removePreSearch handler to match addPreSearch
  types/xrm/index.d.ts
Labels: Merge:Express, Owner Approved

#34557 Additional Fabric definitions
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#34298 Added typedefinitions for the npm package jsonld (jsonld.js)
  types/jsonld/index.d.ts
  types/jsonld/jsonld-spec.d.ts
  types/jsonld/jsonld-tests.ts
  types/jsonld/tsconfig.json
  types/jsonld/tslint.json
Labels: New Definition, Revision needed

#33997 Node: tighten URL query type
  types/node/querystring.d.ts
  types/node/test/querystring.ts
  types/node/url.d.ts
Labels: Popular package, Revision needed

#34564 Add overload to styled-components to improve perf
  types/styled-components/index.d.ts
Labels: Awaiting reviewer feedback, Popular package

#34569 Add type parameter for airbnb-prop-types ref objects
  types/airbnb-prop-types/index.d.ts
Labels: Merge:Express, Owner Approved

#34568 Correct documentation link in types/youtube
  types/youtube/index.d.ts
Labels: Merge:Express, Owner Approved

#34538 Add `background` option for macOS
  types/open/index.d.ts
  types/open/open-tests.ts
Labels: Merge:Express, Owner Approved

#34570 webpack-chain: remove, because the official package has newer types
  notNeededPackages.json
  types/webpack-chain/index.d.ts
  types/webpack-chain/tsconfig.json
  types/webpack-chain/tslint.json
  types/webpack-chain/webpack-chain-tests.ts
Labels: Awaiting reviewer feedback

#34273 [qs] Add 'comma' to parse options
  types/qs/index.d.ts
  types/qs/qs-tests.ts
  types/qs/tslint.json
Labels: Owner Approved, Popular package, Revision needed

#34520 [scheduler] Add tracing module
  types/scheduler/index.d.ts
  types/scheduler/test/scheduler.ts
  types/scheduler/test/tracing.ts
  types/scheduler/tracing.d.ts
  types/scheduler/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#34383 Improve types for flowjs
  types/flowjs/index.d.ts
  types/flowjs/package.json
  types/flowjs/ts3.1/flowjs-tests.ts
  types/flowjs/ts3.1/index.d.ts
  types/flowjs/ts3.1/tsconfig.json
  types/flowjs/ts3.1/tslint.json
  types/ng-flow/index.d.ts
  types/ng-flow/package.json
  types/ng-flow/ts3.1/index.d.ts
  types/ng-flow/ts3.1/ng-flow-tests.ts
  types/ng-flow/ts3.1/tsconfig.json
  types/ng-flow/ts3.1/tslint.json
Labels: New Definition, Revision needed

#34549 [multy]: TS definitions for multy
  types/multy/index.d.ts
  types/multy/multy-tests.ts
  types/multy/tsconfig.json
  types/multy/tslint.json
Labels: New Definition, Revision needed

#34459 Type Definitions for package project-name
  types/project-name/index.d.ts
  types/project-name/project-name-tests.ts
  types/project-name/tsconfig.json
  types/project-name/tslint.json
Labels: New Definition, Revision needed

#34534 Correct callback signature for express-handlebars renderView
  types/express-handlebars/express-handlebars-tests.ts
  types/express-handlebars/index.d.ts
Labels: Merge:Express, Owner Approved

#34483 Update pixi.js for v4.8.7
  types/pixi.js/index.d.ts
Labels: Author is Owner, Merge:Express

#34627 [ADD] fontVariant was missing from TextStyleIOS
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Awaiting reviewer feedback, Popular package

#34624 [stripe-v3] extract owner's adress to an interface
  types/stripe-v3/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package
