Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-05, with the labels that each got.

#43695 Added typings for @accedo/accedo-one package
  types/accedo__accedo-one/accedo__accedo-one-tests.ts
  types/accedo__accedo-one/index.d.ts
  types/accedo__accedo-one/tsconfig.json
  types/accedo__accedo-one/tslint.json
Labels: New Definition

#44359 Update types for tmp to the latest version of the API
  types/tmp/index.d.ts
  types/tmp/tmp-tests.ts
Labels: Other Approved, Owner Approved, Perf: Same, Popular package

#43922 [pubsub-js] Add some more public function to export and reformat code
  types/pubsub-js/index.d.ts
  types/pubsub-js/pubsub-js-tests.ts
Labels: Awaiting reviewer feedback, Maintainer Approved, Perf: Same

#44379 [tabulator-tables] Add sortValuesList on SharedSelectAutoCompleteEditorParams and update label on LinkParams
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Owner Approved, Perf: Same

#44402 Update support schedule in READMEs
  README.cn.md
  README.es.md
  README.ko.md
  README.md
  README.ru.md
Labels: Maintainer Approved, Other Approved

#44409 [tabulator-tables]Calculation function should be able to return anything
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Owner Approved, Perf: Same

#44415 add optional scale argument to ToImgopts interface
  types/plotly.js/index.d.ts
  types/plotly.js/test/core-tests.ts
Labels: Owner Approved, Perf: Same

#42743 Added type definitions for react-text-marquee
  types/react-text-marquee/index.d.ts
  types/react-text-marquee/react-text-marquee-tests.tsx
  types/react-text-marquee/tsconfig.json
  types/react-text-marquee/tslint.json
Labels: Maintainer Approved, New Definition

#42950 [slick-carousel] Enable noImplicitThis
  types/slick-carousel/tsconfig.json
Labels: Other Approved, Owner Approved

#44420 supertest: supertest.agent() supports request methods like superagent.agent
  types/supertest/index.d.ts
  types/supertest/supertest-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package

#44437 fix: prompts Choice types aren't correct
  types/prompts/index.d.ts
  types/prompts/prompts-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44439 [detect-port]: add PortConfig type for first argument from default function
  types/detect-port/detect-port-tests.ts
  types/detect-port/index.d.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#44323 [@types/jquery] Change return type for find function to HTMLElement
  types/jquery-ajax-chain/jquery-ajax-chain-tests.ts
  types/jquery/JQuery.d.ts
  types/jquery/jquery-tests.ts
  types/jqueryui/jqueryui-tests.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Merge:Auto, Perf: Worse

#44434 keccak: fix type definition
  types/keccak/index.d.ts
  types/keccak/keccak-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44426 [react-relay] useRefetchableFragment refetch function should accept partial vars
  types/react-relay/lib/relay-experimental/useRefetchableFragmentNode.d.ts
  types/react-relay/test/relay-experimental-tests.tsx
Labels: Perf: Same

#44427 [react-relay] Fix data nullability for `useRefetchableFragment`
  types/react-relay/index.d.ts
  types/react-relay/lib/relay-experimental/useRefetchableFragment.d.ts
  types/react-relay/test/relay-experimental-tests.tsx
Labels: Perf: Same

#44461 [react-relay] Fix `UNSTABLE_renderPolicy`
  types/react-relay/lib/relay-experimental/useLazyLoadQuery.d.ts
Labels: Perf: Same

#44375 Add breakpoints definition to Rellax
  types/rellax/index.d.ts
  types/rellax/rellax-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44462 [react-native] Add support for VirtualizedList
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44287 react-bootstrap-table2-toolkit: Fix type for ClearSearchButton props.
  types/react-bootstrap-table2-toolkit/index.d.ts
  types/react-bootstrap-table2-toolkit/react-bootstrap-table2-toolkit-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#44467 react-native-sortable-list: added keyboardShouldPersistTaps property 0.0.24
  types/react-native-sortable-list/index.d.ts
  types/react-native-sortable-list/react-native-sortable-list-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#44229 [@types/puppeteer] add product to FetcherOptions
  types/puppeteer/v1/index.d.ts
Labels: Awaiting reviewer feedback, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#42751 Add new types for mitranim/posterus
  types/posterus/fiber.d.ts
  types/posterus/index.d.ts
  types/posterus/posterus-tests.ts
  types/posterus/tsconfig.json
  types/posterus/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#43908 [emoji-mart] Missing theme prop
  types/emoji-mart/dist-es/utils/shared-props.d.ts
  types/emoji-mart/index.d.ts
Labels: Awaiting reviewer feedback, Maintainer Approved, Merge:Auto, Other Approved, Perf: Same

#43858 google-apps-script CardService update
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/google-apps-script.conference-data.d.ts
  types/google-apps-script/index.d.ts
  types/google-apps-script/tslint.json
Labels: Owner Approved, Perf: Same

#43783 Create new type definitions for rr-notifications
  types/rr-notifications/index.d.ts
  types/rr-notifications/rr-notifications-tests.ts
  types/rr-notifications/tsconfig.json
  types/rr-notifications/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#43628 add pdf-parse
  types/pdf-parse/index.d.ts
  types/pdf-parse/pdf-parse-tests.ts
  types/pdf-parse/tsconfig.json
  types/pdf-parse/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#44021 [react-native] Remove Deprecated & Add Deprecation Notices
  types/react-native/index.d.ts
Labels: Awaiting reviewer feedback, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#44042 Allow nullable defaults
  types/convict/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#44044 bytebuffer - Add proper overloads for functions to reflect returned types
  types/bytebuffer/bytebuffer-tests.ts
  types/bytebuffer/index.d.ts
Labels: Awaiting reviewer feedback, Maintainer Approved, Merge:Auto, Other Approved, Perf: Same, Popular package

#43222 [react-redux] Add ref and children props to Connected Components
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#44189 [jsforce] Add missing /// <reference types="node" />
  types/jsforce/index.d.ts
Labels: Awaiting reviewer feedback, Owner Approved, Perf: Same, Popular package

#43370 Add type definitions for searchjs
  types/searchjs/index.d.ts
  types/searchjs/searchjs-tests.ts
  types/searchjs/tsconfig.json
  types/searchjs/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#44237 fix(update-dom-mediacapture-record): more specific addEventListener typing
  types/dom-mediacapture-record/dom-mediacapture-record-tests.ts
  types/dom-mediacapture-record/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#43082 Add types for filter-css
  types/filter-css/filter-css-tests.ts
  types/filter-css/index.d.ts
  types/filter-css/tsconfig.json
  types/filter-css/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#44231 added 'seekto' to MediaSessionAction in wicg-mediasession
  types/wicg-mediasession/index.d.ts
Labels: Awaiting reviewer feedback, Owner Approved, Perf: Same

#44226 [prompts] Add stdout and stdin to the PromptObject definition
  types/prompts/index.d.ts
  types/prompts/tsconfig.json
Labels: Awaiting reviewer feedback, Owner Approved, Perf: Worse, Popular package

#38189 [redux-form]: fix type discrepancies
  types/redux-form/lib/actions.d.ts
  types/redux-form/lib/reducer.d.ts
  types/redux-form/lib/reduxForm.d.ts
  types/redux-form/redux-form-tests.tsx
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#44316 Make Vimeo request() generic to optionally type results
  types/vimeo/index.d.ts
  types/vimeo/tsconfig.json
  types/vimeo/vimeo-tests.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto

#43153 added typings for cytoscape-edgehandles
  types/cytoscape-edgehandles/cytoscape-edgehandles-tests.ts
  types/cytoscape-edgehandles/index.d.ts
  types/cytoscape-edgehandles/tsconfig.json
  types/cytoscape-edgehandles/tslint.json
Labels: New Definition

#44387 Add missing non-gold props
  types/react-mic/index.d.ts
  types/react-mic/react-mic-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#44397 fix(ibm.db): fix type in property name
  types/ibm_db/ibm_db-tests.ts
  types/ibm_db/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44399 fix(mongoose): `autoCreate` property of schema options
  types/mongoose/index.d.ts
  types/mongoose/test/mongoose.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44392 update(html-minifier-terser): 5.1 version
  types/html-minifier-terser/html-minifier-terser-tests.ts
  types/html-minifier-terser/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#44391 fix(mongodb): missing 'abort' method on GridFSBucketWriteStream
  types/mongodb/index.d.ts
  types/mongodb/test/index.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#44313 update(underscore): expose `VERSION` - minor version bump
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44333 Add JSDoc from jest to jest-expect-message
  types/jest-expect-message/index.d.ts
Labels: Owner Approved, Perf: Same

#44206 [undertaker] Add missing /// <reference types="node" />
  types/undertaker/index.d.ts
  types/undertaker/undertaker-tests.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#44176 [@types/amplitude-js] - Config - sameSiteCookie is not defined
  types/amplitude-js/index.d.ts
Labels: Awaiting reviewer feedback, Owner Approved, Perf: Same

#44164 google-apps-script-oauth2 - Add Storage interface & updates for current version
  .github/CODEOWNERS
  types/google-apps-script-oauth2/google-apps-script-oauth2-tests.ts
  types/google-apps-script-oauth2/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#44143 fix: types across cesium
  types/cesium/index.d.ts
Labels: Perf: Same

#44141 [redis] Add error type to retry_delay
  types/redis-mock/redis-mock-tests.ts
  types/redis/index.d.ts
  types/redis/redis-tests.ts
  types/redis/ts3.1/index.d.ts
  types/redis/ts3.1/redis-tests.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#44137 [resolve]: update to v1.17
  types/resolve/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#44132 jaeger-client: add the close method to the JaegerTracer
  types/jaeger-client/index.d.ts
  types/jaeger-client/jaeger-client-tests.ts
Labels: Awaiting reviewer feedback, Perf: Same

#44166 chrome: Add new altgr attribute to chrome.input.ime.
  types/chrome/index.d.ts
Labels: Awaiting reviewer feedback, Owner Approved, Perf: Same, Popular package

#44129 [mongoose-paginate-v2] Add custom PaginateOptions for all queries
  types/mongoose-paginate-v2/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#44069 update types for cli-progress
  types/cli-progress/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#43388 jquery PromiseBase/Deferred should not be assignable to Promise
  types/jquery/jquery-tests.ts
  types/jquery/misc.d.ts
Labels: Awaiting reviewer feedback, Critical package, Other Approved

#41105 Adding support for viz.js
  types/viz.js/common.d.ts
  types/viz.js/full.render.js.d.ts
  types/viz.js/index.d.ts
  types/viz.js/tsconfig.json
  types/viz.js/tslint.json
  types/viz.js/viz.js-tests.ts
Labels: New Definition

#43970 [@types/hapi__joi] Update Joi to v17.1
  types/hapi__joi/hapi__joi-tests.ts
  types/hapi__joi/index.d.ts
Labels: Perf: Same, Popular package

#44395 [Bootstrap-3-Typeahead] Add missing detail to definitions
  types/bootstrap-3-typeahead/index.d.ts
Labels: Owner Approved, Perf: Same

#43275 types for Yandex.Metrika Tag API
  types/yandex-metrika-tag/index.d.ts
  types/yandex-metrika-tag/tsconfig.json
  types/yandex-metrika-tag/tslint.json
  types/yandex-metrika-tag/yandex-metrika-tag-tests.ts
Labels: Maintainer Approved, Merge:Auto, New Definition

#44412 Update RetryStrategy types to match docs
  types/redis/index.d.ts
  types/redis/redis-tests.ts
  types/redis/ts3.1/index.d.ts
  types/redis/ts3.1/redis-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44478 update(copyfiles): update to v2.2
  types/copyfiles/copyfiles-tests.ts
  types/copyfiles/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44476 [mongodb] fix return array type for distinct
  types/mongodb/index.d.ts
  types/mongodb/test/collection/distinct.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44489 Fix bad merge in redux-form
  types/redux-form/lib/reduxForm.d.ts
Labels: Popular package

#43440 qs: improve `parse` return type
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express/express-tests.ts
  types/ghost-storage-base/ghost-storage-base-tests.ts
  types/i18n-abide/i18n-abide-tests.ts
  types/lasso/lasso-tests.ts
  types/qs/index.d.ts
  types/qs/qs-tests.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#44335 Remove parse-duration
  notNeededPackages.json
  types/parse-duration/index.d.ts
  types/parse-duration/parse-duration-tests.ts
  types/parse-duration/tsconfig.json
  types/parse-duration/tslint.json
Labels: Author is Owner

#43801 Added pdf-thumbnail typings
  types/pdf-thumbnail/index.d.ts
  types/pdf-thumbnail/pdf-thumbnail-tests.ts
  types/pdf-thumbnail/tsconfig.json
  types/pdf-thumbnail/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#44034 fix(node): move worker_threads module functions to correct scope
  types/node/test/worker_threads.ts
  types/node/v12/test/worker_threads.ts
  types/node/v12/worker_threads.d.ts
  types/node/worker_threads.d.ts
Labels: Critical package, Owner Approved, Perf: Same

#44503 [slate]: Ensure setNodeByKey arguments are Partial
  types/slate/index.d.ts
  types/slate/slate-tests.ts
Labels: Merge:Auto, Owner Approved

#44506 FixedOffsetZone.utcInstance returns FixedOffsetZone, not string
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44328 Update reactour definition for v1.17
  types/reactour/index.d.ts
  types/reactour/reactour-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#44094 [office-js, office-js-preview] Updating with ExcelApi 1.11 information
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#44525 Add customProperties.getAll to Office-js-preview
  types/office-js-preview/index.d.ts
Labels: Owner Approved

#44384 [@types/tryghost__content-api] Fix tag visibilities values
  types/tryghost__content-api/index.d.ts
Labels: Owner Approved, Perf: Same

#44303 [@types/react-table] Update groupByID property
  types/react-table/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package

#44528 update(luxon): v1.24
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#44524 [Update] browser-image-compression
  types/browser-image-compression/browser-image-compression-tests.ts
  types/browser-image-compression/index.d.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44517 Update/opentok - Add Broadcast and Signal api calls.
  types/opentok/index.d.ts
  types/opentok/opentok-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44522 [carbon-components-react] 7.10.x - Fix tabs interfaces and update tests.
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/Tab/Tab.d.ts
  types/carbon-components-react/lib/components/Tabs/Tabs.d.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44438 Modified type of i18n-js I18n.fallbacks
  types/i18n-js/i18n-js-tests.ts
  types/i18n-js/index.d.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#44507 [serverless] Add variableResolvers to plugin definition
  types/serverless/classes/Plugin.d.ts
  types/serverless/serverless-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44327 Fix and improve dagre types and tests
  types/dagre/dagre-tests.ts
  types/dagre/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44535 fix(aria-query): correct DT header author handle
  types/aria-query/index.d.ts
Labels: Other Approved, Perf: Same

#44520 add definitions for once() to noble
  types/noble/index.d.ts
  types/noble/noble-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44541 @testing-library/jest dom - toHaveValue should allow null as a parameter
  types/testing-library__jest-dom/index.d.ts
  types/testing-library__jest-dom/test/testing-library__jest-dom-global-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44139 Expose ExpressJS functionality of `next('router')`
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
Labels: Awaiting reviewer feedback, Critical package, Maintainer Approved, Merge:Auto, Other Approved, Perf: Same

#44262 [ioredis] Add *bylex commands to @types/ioredis
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Awaiting reviewer feedback, Merge:Auto, Owner Approved, Perf: Same, Popular package

#44559 (slate) fix insertText
  types/slate/index.d.ts
  types/slate/slate-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44565 openpgp: Fix openpgp.wkd.WKD.lookup method parameter
  types/openpgp/index.d.ts
  types/openpgp/openpgp-tests.ts
  types/openpgp/ts3.2/index.d.ts
  types/openpgp/ts3.2/openpgp-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44555 semantic-release: update type definitions for 17.0
  types/semantic-release/index.d.ts
  types/semantic-release/semantic-release-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#44406 add object.fromentries
  types/object.fromentries/index.d.ts
  types/object.fromentries/object.fromentries-tests.ts
  types/object.fromentries/tsconfig.json
  types/object.fromentries/tslint.json
Labels: New Definition

#44288 react-bootstrap-table2-paginator: Fix type for PaginationProvider pagination prop, and add test.
  types/react-bootstrap-table2-paginator/index.d.ts
  types/react-bootstrap-table2-paginator/react-bootstrap-table2-paginator-tests.tsx
Labels: Perf: Same

#44381 [knex-db-manager] Fix populatePathPattern config parameter and populateDb method
  types/knex-db-manager/index.d.ts
Labels: Owner Approved, Perf: Same

#44574 [yup] Add missing aliases, defined(), and fix array innerType
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44584 VS Code 1.45.0 Extension API
  types/vscode/index.d.ts
Labels: Perf: Same

#44579 fix(mongoose): orFail has wrong typings
  types/mongoose/index.d.ts
  types/mongoose/test/query.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44526 Fixed missing file in package of [types/hyphen]
  types/hyphen/common.d.ts
  types/hyphen/common.ts
  types/hyphen/index.d.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44599 [brainhubeu__react-carousel] Add arrowLeftDisabled and arrowRightDisabled props
  types/brainhubeu__react-carousel/brainhubeu__react-carousel-tests.tsx
  types/brainhubeu__react-carousel/index.d.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#44602 [react-lottie] Add the style prop to the Lottie component
  types/react-lottie/index.d.ts
  types/react-lottie/react-lottie-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#44607 fix(mssql): correct return types for Transaction.begin
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Merge:Auto, Owner Approved

#44608 fix(express-http-proxy): correct `filter` method definition
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44449 [ioBroker] add encrypt/decrypt methods to adapter
  types/iobroker/index.d.ts
  types/iobroker/iobroker-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44548 [ioBroker] add error handler to adapter constructor options
  types/iobroker/index.d.ts
  types/iobroker/iobroker-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44457 [prosemirror-state] update plugin key interface
  types/prosemirror-state/index.d.ts
  types/prosemirror-state/prosemirror-state-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44615 fix(gm): add `selectFrame` method
  types/gm/gm-tests.ts
  types/gm/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#44542 XUMM-API: Add new TX type & API payload meta options
  types/xumm-api/index.d.ts
  types/xumm-api/xumm-api-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44564 [react] [react-dom] Add unstable prefix to experimental APIs
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
Labels: Critical package, Maintainer Approved, Other Approved, Owner Approved, Perf: Same, The Travis CI build failed

#44616 [@types/bull] add addBulk function to Queue
  types/bull/bull-tests.tsx
  types/bull/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44582 [yup] Add support for custom type-assertion tests that narrow the schema type
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Worse, Popular package

#44573 [yup] Make typing for oneOf work to refine the schema type
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44400 Fix typings for async.retryable
  types/async/index.d.ts
  types/async/test/index.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#44534 added definitions for redux-subscriber
  types/redux-subscriber/index.d.ts
  types/redux-subscriber/redux-subscriber-tests.ts
  types/redux-subscriber/tsconfig.json
  types/redux-subscriber/tslint.json
Labels: New Definition, Other Approved

#44430 Add danger for showing dts-critic suggestions
  .travis.yml
  azure-pipelines.yml
  dangerfile.ts
  package.json
Labels: Perf: Same, Popular package, The Travis CI build failed

#44648 [cesium] Fix member variables on graphics types
  types/cesium/index.d.ts
  types/cesium/test/cesium-global.test.ts
  types/cesium/test/cesium-module.test.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#44642 fix(pino): remedy destination static method and add missing option prettifier
  types/pino/index.d.ts
  types/pino/pino-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#43716 update(puppeteer): `product` option support
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#44236 feat(helmet): make `directives` of CSP config required
  types/helmet/helmet-tests.ts
  types/helmet/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Auto, Owner Approved, Perf: Same, Popular package

#44632 Add toHaveDescription() to @testing-library/jest-dom
  types/testing-library__jest-dom/index.d.ts
  types/testing-library__jest-dom/test/testing-library__jest-dom-global-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44302 Additions to CodeMirror definitions
  types/codemirror/addon/comment/comment.d.ts
  types/codemirror/addon/display/autorefresh.d.ts
  types/codemirror/addon/display/panel.d.ts
  types/codemirror/addon/display/placeholder.d.ts
  types/codemirror/addon/edit/closebrackets.d.ts
  types/codemirror/addon/edit/closetag.d.ts
  types/codemirror/addon/edit/matchbrackets.d.ts
  types/codemirror/addon/edit/matchtags.d.ts
  types/codemirror/addon/hint/show-hint.d.ts
  types/codemirror/addon/merge/merge.d.ts
  types/codemirror/addon/runmode/runmode.d.ts
  types/codemirror/addon/scroll/scrollpastend.d.ts
  types/codemirror/addon/search/match-highlighter.d.ts
  types/codemirror/addon/search/searchcursor.d.ts
  types/codemirror/addon/selection/active-line.d.ts
  types/codemirror/addon/tern/tern.d.ts
  types/codemirror/codemirror-tests.ts
  types/codemirror/index.d.ts
  types/codemirror/mode/meta.d.ts
  types/codemirror/test/addon/comment/comment.ts
  types/codemirror/test/addon/display/autorefresh.ts
  types/codemirror/test/addon/display/panel.ts
  types/codemirror/test/addon/display/placeholder.ts
  types/codemirror/test/addon/edit/closebrackets.ts
  types/codemirror/test/addon/edit/closetag.ts
  types/codemirror/test/addon/edit/matchbrackets.ts
  types/codemirror/test/addon/edit/matchtags.ts
  types/codemirror/test/addon/hint/show-hint.ts
  types/codemirror/test/addon/runmode/runmode.ts
  types/codemirror/test/addon/scroll/scrollpastend.ts
  types/codemirror/test/addon/search/match-highlighter.ts
  types/codemirror/test/addon/search/searchcursor.ts
  types/codemirror/test/addon/selection/active-line.ts
  types/codemirror/test/addon/tern/tern.ts
  types/codemirror/test/index.ts
  types/codemirror/tsconfig.json
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#44372 Add circle-to-polygon typings
  types/circle-to-polygon/circle-to-polygon-tests.ts
  types/circle-to-polygon/index.d.ts
  types/circle-to-polygon/tsconfig.json
  types/circle-to-polygon/tslint.json
Labels: New Definition

#44357 [yargs] Add missing "yargs/*" path mapping
  types/yargs/v12/tsconfig.json
  types/yargs/v13/tsconfig.json
Labels: Critical package, Perf: Same

#44386 Add types for mute-stream
  types/mute-stream/index.d.ts
  types/mute-stream/mute-stream-tests.ts
  types/mute-stream/tsconfig.json
  types/mute-stream/tslint.json
Labels: New Definition

#44350 [ember-test-helpers] Add missing "ember-test-helpers/*" path mapping
  types/ember-test-helpers/v0/tsconfig.json
Labels: Owner Approved, Perf: Same

#44348 [ember-feature-flags] Add missing "ember-feature-flags/*" path mapping
  types/ember-feature-flags/v3/tsconfig.json
Labels: Owner Approved, Perf: Same

#44349 [ember-modal-dialog] Add missing "ember-modal-dialog/*" path mapping
  types/ember-modal-dialog/v2/tsconfig.json
Labels: Owner Approved, Perf: Same

#44308 [cypress-axe] update types for v0.8.1
  types/cypress-axe/index.d.ts
  types/cypress-axe/package.json
Labels: Owner Approved

#44331 [keyboardjs] Add aliases for bind and unbind and add tests
  types/keyboardjs/index.d.ts
  types/keyboardjs/keyboardjs-tests.ts
  types/keyboardjs/tsconfig.json
  types/keyboardjs/tslint.json
Labels: Owner Approved

#44127 feat: add types for parsePhoneNumber and PhoneNumber
  types/react-phone-number-input/index.d.ts
  types/react-phone-number-input/react-phone-number-input-tests.tsx
Labels: Awaiting reviewer feedback, Merge:Auto, Other Approved, Perf: Same

#44593 add definitions for new props of v6.1.0 and 6.1.1 release of react-native-calendar-picker
  types/react-native-calendar-picker/index.d.ts
  types/react-native-calendar-picker/react-native-calendar-picker-tests.tsx
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44635 [react-lottie] Mark array props as readonly
  types/react-lottie/index.d.ts
  types/react-lottie/react-lottie-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#44455 [mongoose]: fix model properties not directly available on document
  types/mongoose/index.d.ts
  types/mongoose/test/model.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44521 CodeMirror: removed method, options on marks
  types/codemirror/index.d.ts
  types/codemirror/test/index.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Owner Approved, Perf: Same, Popular package

#44253 Hexo: add RendererData to exported module.
  types/hexo/hexo-tests.ts
  types/hexo/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#44254 [@types/auth0] added scope type string to ClientCredentialsGrantOptions
  types/auth0/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#44255 Smaller changes for tooltip widget options in jQuery UI 1.12
  types/jqueryui/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#44261 [@types/ssh2-streams] Fix parseKey return type
  types/ssh2-streams/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#44352 [hapi] Add missing "hapi/*" path mapping
  types/hapi/v17/tsconfig.json
Labels: Perf: Same

#44354 [puppeteer] Add missing "puppeteer/*" path mapping
  types/puppeteer/v1/tsconfig.json
Labels: Perf: Same, Popular package

#44346 @types/chromecast-cast Changed chrome.cast.media.MediaInfo#metadata type
  types/chrome/chrome-cast/index.d.ts
Labels: Perf: Same, Popular package

#44665 [@types/mongoose]: Adds strictQuery to SchemaOptions
  types/mongoose/index.d.ts
  types/mongoose/test/mongoose.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44650 [screeps] Various fixes
  types/screeps/index.d.ts
  types/screeps/screeps-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44670 [office-js] [office-js-preview] (Outlook) saveAsync production build …
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Owner Approved, Where is Travis?

#44358 [cache-manager] Add missing cache reset functions to Cache type definitions
  types/cache-manager/cache-manager-tests.ts
  types/cache-manager/index.d.ts
Labels: Perf: Same

#44356 [react-test-renderer] Add missing "react-test-renderer/*" path mapping
  types/react-test-renderer/v15/tsconfig.json
Labels: Perf: Same, Popular package

#44299 Add types for hcaptcha__vue-hcaptcha
  types/hcaptcha__vue-hcaptcha/hcaptcha__vue-hcaptcha-tests.ts
  types/hcaptcha__vue-hcaptcha/index.d.ts
  types/hcaptcha__vue-hcaptcha/package.json
  types/hcaptcha__vue-hcaptcha/tsconfig.json
  types/hcaptcha__vue-hcaptcha/tslint.json
Labels: New Definition

#44326 add pinyin-engine
  types/pinyin-engine/index.d.ts
  types/pinyin-engine/pinyin-engine-tests.ts
  types/pinyin-engine/tsconfig.json
  types/pinyin-engine/tslint.json
Labels: New Definition

#44332 Add types for hafas-client package
  types/hafas-client/hafas-client-tests.ts
  types/hafas-client/index.d.ts
  types/hafas-client/p/bvg/index.d.ts
  types/hafas-client/p/cfl/index.d.ts
  types/hafas-client/p/cmta/index.d.ts
  types/hafas-client/p/db-busradar-nrw/index.d.ts
  types/hafas-client/p/db/index.d.ts
  types/hafas-client/p/hvv/index.d.ts
  types/hafas-client/p/insa/index.d.ts
  types/hafas-client/p/invg/index.d.ts
  types/hafas-client/p/nahsh/index.d.ts
  types/hafas-client/p/nvv/index.d.ts
  types/hafas-client/p/oebb/index.d.ts
  types/hafas-client/p/pkp/index.d.ts
  types/hafas-client/p/rmv/index.d.ts
  types/hafas-client/p/rsag/index.d.ts
  types/hafas-client/p/saarfahrplan/index.d.ts
  types/hafas-client/p/sbahn-muenchen/index.d.ts
  types/hafas-client/p/sncb/index.d.ts
  types/hafas-client/p/svv/index.d.ts
  types/hafas-client/p/vbb/index.d.ts
  types/hafas-client/p/vbn/index.d.ts
  types/hafas-client/p/vmt/index.d.ts
  types/hafas-client/p/vsn/index.d.ts
  types/hafas-client/tsconfig.json
  types/hafas-client/tslint.json
Labels: New Definition

#44324 fix(micro-cors): add missing option and change existing type to more appropriate type
  types/micro-cors/index.d.ts
  types/micro-cors/micro-cors-tests.ts
Labels: Perf: Same
