Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-07, with the labels that each got.

#45791 [react-dates]: change reopenPickerOnClearDates to reopenPickerOnClearDate for SingleDatePickerShape
  types/react-dates/index.d.ts
  types/react-dates/react-dates-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45754 [node-telegram-bot-api] Updated new methods to release v0.50.0
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45750 Add types for k-bucket
  types/k-bucket/index.d.ts
  types/k-bucket/k-bucket-tests.ts
  types/k-bucket/tsconfig.json
  types/k-bucket/tslint.json
Labels: New Definition

#45810 feat(url-params-parser): new definition file
  types/url-params-parser/index.d.ts
  types/url-params-parser/tsconfig.json
  types/url-params-parser/tslint.json
  types/url-params-parser/url-params-parser-tests.ts
  types/url-params-parser/url_parser.d.ts
Labels: New Definition

#45808 feat(fitvids): new module definition
  types/fitvids/fitvids-tests.ts
  types/fitvids/index.d.ts
  types/fitvids/tsconfig.json
  types/fitvids/tslint.json
Labels: New Definition

#45803 [react-native] Add declaration for URL global type
  types/react-native/globals.d.ts
  types/react-native/test/globals.tsx
Labels: Perf: Same, Popular package

#45700 fix(nodegit): fix Tree.diff return type
  types/nodegit/nodegit-tests.ts
  types/nodegit/tree.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Worse

#45727 [@types/react-native] touchSoundDisabled TouchableWithoutFeedback prop
  types/react-native/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#45806 fix openseadragon types to represent addSimpleImage correctly
  types/openseadragon/index.d.ts
  types/openseadragon/openseadragon-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45156 [react-select] Remove cssKey param from CommonProps.cx
  types/react-select/src/types.d.ts
Labels: Abandoned, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, Untested Change

#45833 Update microsoft-graph typings to 1.13
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#44989 Feature/43320 take two
  types/ramda/index.d.ts
  types/ramda/test/paths-tests.ts
Labels: Abandoned, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45838 Note that [ember-data] Store extends Service
  types/ember-data/index.d.ts
  types/ember-data/test/store.ts
Labels: Merge:Auto, Owner Approved

#45687 Update HMSET for Redis 4
  types/redis/index.d.ts
  types/redis/redis-tests.ts
  types/redis/ts3.1/index.d.ts
  types/redis/ts3.1/redis-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45698 Sanctuary - Adds Pair declarations
  types/sanctuary/index.d.ts
  types/sanctuary/tslint.json
Labels: Author is Owner, Config Edit, Owner Approved, Perf: Same

#45842 [underscore] Fix findIndex and findLastIndex signatures
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45272 [@types/email-templates] Export all interfaces and types and remove duplicated code
  types/email-templates/email-templates-tests.ts
  types/email-templates/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45855 Type updates for frappe-gantt library
  types/frappe-gantt/frappe-gantt-tests.ts
  types/frappe-gantt/index.d.ts
  types/frappe-gantt/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Worse

#45560 Fix serverless typing for httpApi logs and Environement
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#45719 [react-bytesize-icons] Update to version 0.12.2
  types/react-bytesize-icons/index.d.ts
  types/react-bytesize-icons/react-bytesize-icons-tests.tsx
Labels: Merge:Auto, No Other Owners, Other Approved, Perf: Same

#45883 [gm] Added type definition for 'composite' method
  types/gm/gm-tests.ts
  types/gm/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45886 [@types/redis] Update ts3.1/index.d.ts GET command should return string or null
  types/redis/ts3.1/index.d.ts
  types/redis/ts3.1/redis-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45763 [@types/underscore] Collection and Array Tests - Map, Pluck, Filter, GroupBy, and Flatten
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45892 feat(ffmpeg): async version of `save`
  types/ffmpeg/ffmpeg-tests.ts
  types/ffmpeg/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45904 Add 'inline' to the type definition of SourceMapOptions.content
  types/uglify-js/index.d.ts
  types/uglify-js/uglify-js-tests.ts
Labels: Critical package, Perf: Same

#45232 [muibox] "placeholder" property
  types/muibox/index.d.ts
  types/muibox/muibox-tests.ts
Labels: Abandoned, Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#45884 @types/cytoscape fix spelling issue to match docs
  types/cytoscape/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Untested Change

#45900 Updating index.d.ts of merge-images to correct it
  types/merge-images/index.d.ts
Labels: Perf: Same, Untested Change

#45627 [webpack] fix for MultiCompiler doesn't define Multistats for callback/handler of run method
  types/webpack/index.d.ts
Labels: Critical package, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#45891 Add types for react-blockies
  types/react-blockies/index.d.ts
  types/react-blockies/react-blockies-tests.tsx
  types/react-blockies/tsconfig.json
  types/react-blockies/tslint.json
Labels: New Definition

#45862 [react-native] Add onTextInput prop to TextInput
  types/react-native/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45811 [vexflow] feat: add optional Formatter constructor options
  types/vexflow/index.d.ts
  types/vexflow/vexflow-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#45914 [@types/daterangepicker] property 'drops' could accept 'auto' value (update to 3.1)
  types/daterangepicker/daterangepicker-tests.ts
  types/daterangepicker/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45896 Add types for react-file-icon
  types/react-file-icon/index.d.ts
  types/react-file-icon/react-file-icon-tests.tsx
  types/react-file-icon/tsconfig.json
  types/react-file-icon/tslint.json
Labels: New Definition

#45890 Add types for greek-utils npm library
  types/greek-utils/greek-utils-tests.ts
  types/greek-utils/index.d.ts
  types/greek-utils/tsconfig.json
  types/greek-utils/tslint.json
Labels: New Definition, Other Approved

#45887 ssh2 sftp add exists
  types/ssh2/index.d.ts
Labels: Perf: Same, Untested Change

#45881 ssh2-sftp-client add method
  types/ssh2-sftp-client/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#45865 yt-search: update for 2.0.1
  types/yt-search/index.d.ts
  types/yt-search/tslint.json
  types/yt-search/yt-search-tests.ts
Labels: Author is Owner, Config Edit, No Other Owners, Perf: Same

#45878 feat(nanoscheduler): new type definition
  types/nanoscheduler/index.d.ts
  types/nanoscheduler/nanoscheduler-tests.ts
  types/nanoscheduler/tsconfig.json
  types/nanoscheduler/tslint.json
Labels: New Definition

#45857 feat(bounds.js): new type definition
  types/bounds.js/bounds.js-tests.ts
  types/bounds.js/index.d.ts
  types/bounds.js/tsconfig.json
  types/bounds.js/tslint.json
Labels: New Definition

#45875 Add type definitions for cxs-css/cxs
  types/cxs/component/index.d.ts
  types/cxs/cxs-tests.ts
  types/cxs/index.d.ts
  types/cxs/package.json
  types/cxs/tsconfig.json
  types/cxs/tslint.json
Labels: New Definition

#45876 [webpack] Argument "env" passed to configuration factories can be undefined
  types/webpack/index.d.ts
  types/webpack/test/index.ts
Labels: Critical package, Perf: Same

#45870 Add missing methods to type declaration
  types/intro.js/index.d.ts
Labels: Owner Approved, Perf: Worse, Untested Change

#45858 fix(node): add `module.path`
  types/node/globals.d.ts
  types/node/test/global.ts
  types/node/v11/globals.d.ts
  types/node/v11/test/global.ts
  types/node/v12/globals.d.ts
  types/node/v12/test/global.ts
  types/node/v13/globals.d.ts
  types/node/v13/test/global.ts
Labels: Author is Owner, Critical package, Owner Approved, Perf: Same

#45859 @types/rethinkdb - Add optional options parameter for Sequence.distinct()
  types/rethinkdb/index.d.ts
Labels: Perf: Same, Untested Change

#45852 `@babel/traverse`: add `visitors.merge`
  types/babel__traverse/babel__traverse-tests.ts
  types/babel__traverse/index.d.ts
Labels: Critical package, Perf: Same

#45846 refactor(node): Move `Console` definition to `console.d.ts`
  types/node/console.d.ts
  types/node/globals.d.ts
Labels: Author is Owner, Critical package, Perf: Same, Untested Change

#45845 refactor(node): Move `Buffer` definition to `buffer.d.ts`
  types/node/buffer.d.ts
  types/node/globals.d.ts
  types/node/ts3.2/base.d.ts
  types/node/ts3.2/buffer.d.ts
  types/node/ts3.2/globals.d.ts
Labels: Author is Owner, Critical package, Perf: Same, Untested Change

#45847 refactor(node): Move `Domain` definition to `domain.d.ts`
  types/node/domain.d.ts
  types/node/globals.d.ts
Labels: Author is Owner, Critical package, Perf: Same, Untested Change

#45848 refactor(node): Move `EventEmitter` definition to `events.d.ts`
  types/node/events.d.ts
  types/node/globals.d.ts
  types/node/http.d.ts
Labels: Author is Owner, Critical package, Perf: Same, Untested Change

#45850 Add typings for the WICG Native File System API
  types/wicg-native-file-system/index.d.ts
  types/wicg-native-file-system/tsconfig.json
  types/wicg-native-file-system/tslint.json
  types/wicg-native-file-system/wicg-native-file-system-tests.ts
Labels: New Definition

#45841 [leaflet] Fix type of LatLngBounds.overlap
  types/leaflet/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#45903 [@types/raygun4js] [version 2.20.0] Custom timings - Track Event typings
  types/raygun4js/index.d.ts
  types/raygun4js/raygun4js-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45840 fix(jest): Fix usage example of `jest.MockedClass`
  types/jest/index.d.ts
Labels: Critical package, Owner Approved, Perf: Worse, Untested Change

#45839 Add extra parameter for chrome.input.ime.AssistiveWindowProperties in chrome
  types/chrome/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45835 Add types for the `stringify-author` package
  types/stringify-author/index.d.ts
  types/stringify-author/stringify-author-tests.ts
  types/stringify-author/tsconfig.json
  types/stringify-author/tslint.json
Labels: New Definition

#45828 @types/plotly.js Added histfunc and added y and z to hoverinfo
  types/plotly.js/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#45826 chromecast-caf-receiver - add Event type to BitrateChangedEvent
  types/chromecast-caf-receiver/cast.framework.events.d.ts
Labels: Perf: Same, Untested Change

#45822 Add types to randomatic
  types/randomatic/index.d.ts
  types/randomatic/randomatic-tests.ts
  types/randomatic/tsconfig.json
  types/randomatic/tslint.json
Labels: New Definition

#45820 feat(aws-lambda): add the amazon connect contact flow trigger
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/connect-contact-flow-tests.ts
  types/aws-lambda/trigger/connect-contact-flow.d.ts
  types/aws-lambda/tsconfig.json
Labels: Config Edit, Owner Approved, Perf: Same, Popular package

#45817 [@types/passport] Passport's authorize function accepts Strategy
  types/passport/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45815 markdown-to-jsx: children prop is required and must be a string
  types/markdown-to-jsx/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45814 update(simperium): add missing optional parameters to event listener
  types/simperium/index.d.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Untested Change

#45809 [recharts] fix CartesianGridProps' CoordinatesGenerator(s)
  types/recharts/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#44899 [Cesium] - fix wrong parameters on EllipsoidTangentPlane.fromPoints
  types/cesium/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#45804 [leaflet] Change TileEvent coords to Coords interface
  types/leaflet/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#45800 [Cheerio] Do not expose `cheerio` object globally
  types/cheerio/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45799 [mongoose] add missing 'useFindAndModify' option
  types/mongoose/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#44740 fix: USAGE of Express for types express
  types/express/index.d.ts
Labels: Critical package, Other Approved, Perf: Same, Untested Change

#45794 Add types for linkify-markdown
  types/linkify-markdown/index.d.ts
  types/linkify-markdown/linkify-markdown-tests.ts
  types/linkify-markdown/tsconfig.json
  types/linkify-markdown/tslint.json
Labels: New Definition

#45788 xml-formatter: Delete not-needed types
  notNeededPackages.json
  types/xml-formatter/index.d.ts
  types/xml-formatter/tsconfig.json
  types/xml-formatter/tslint.json
  types/xml-formatter/xml-formatter-tests.ts
Labels: Edits Infrastructure

#45738 pubnub: Update for Objects v2
  types/pubnub/index.d.ts
  types/pubnub/pubnub-tests.ts
  types/pubnub/tslint.json
Labels: Config Edit, Owner Approved, Perf: Worse

#45784 Add missing chai-as-promised assert functions
  types/chai-as-promised/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#45483 [uikit] UIkit.modal.prompt returns `string` or `null` (when cancelled)
  types/uikit/index.d.ts
Labels: Perf: Worse, Untested Change

#45777 [string-natural-compare] Add type definition
  types/string-natural-compare/index.d.ts
  types/string-natural-compare/string-natural-compare-tests.ts
  types/string-natural-compare/tsconfig.json
  types/string-natural-compare/tslint.json
Labels: New Definition

#45771 [raygun] Remove typings
  notNeededPackages.json
  types/raygun/index.d.ts
  types/raygun/raygun-tests.ts
  types/raygun/tsconfig.json
  types/raygun/tslint.json
Labels: Edits Infrastructure, Owner Approved

#45770 Add types for changelog-filename-regex
  types/changelog-filename-regex/changelog-filename-regex-tests.ts
  types/changelog-filename-regex/index.d.ts
  types/changelog-filename-regex/tsconfig.json
  types/changelog-filename-regex/tslint.json
Labels: New Definition

#45764 [styled-components]: fix the type for StylisPlugin
  types/styled-components/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45759 [prettier] Add type definitions for trim and cursor
  types/prettier/index.d.ts
  types/prettier/prettier-tests.ts
Labels: Author is Owner, Critical package, Owner Approved, Perf: Better

#45758 [@types/passport-twitter] Fix typo `reguestTokenURL` to `requestTokenURL`
  types/passport-twitter/index.d.ts
Labels: Other Approved, Perf: Same, Untested Change

#45752 fix(@types/xmldom): Move `dom` from tsconfig to `index.d.ts`
  types/xmldom/index.d.ts
  types/xmldom/tsconfig.json
Labels: Config Edit, Perf: Worse, Popular package

#45736 [ramda] split tests to separate modules: 'remove' - 'take'
  types/ramda/ramda-tests.ts
  types/ramda/test/remove-tests.ts
  types/ramda/test/repeat-tests.ts
  types/ramda/test/replace-tests.ts
  types/ramda/test/reverse-tests.ts
  types/ramda/test/scan-tests.ts
  types/ramda/test/set-tests.ts
  types/ramda/test/slice-tests.ts
  types/ramda/test/sort-tests.ts
  types/ramda/test/sortBy-tests.ts
  types/ramda/test/sortWith-tests.ts
  types/ramda/test/splitAt-tests.ts
  types/ramda/test/splitEvery-tests.ts
  types/ramda/test/splitWhen-tests.ts
  types/ramda/test/startsWith-tests.ts
  types/ramda/test/subtract-tests.ts
  types/ramda/test/sum-tests.ts
  types/ramda/test/symmetricDifference-tests.ts
  types/ramda/test/symmetricDifferenceWith-tests.ts
  types/ramda/test/tail-tests.ts
  types/ramda/test/take-tests.ts
  types/ramda/tsconfig.json
Labels: Config Edit, Perf: Same, Popular package

#45729 Add definitions for time format
  types/cleave.js/options/index.d.ts
Labels: Perf: Same, Untested Change

#45716 Patch nulogy__components
  types/nulogy__components/index.d.ts
  types/nulogy__components/src/Link.d.ts
  types/nulogy__components/src/NDSProvider.d.ts
Labels: Author is Owner, Perf: Same, Untested Change

#45666 mssql - Changed the parameter of the tvp factory to be omitted
  types/mssql/index.d.ts
Labels: Perf: Same, Untested Change

#45548 redux-form: add splice method to FieldArrayFieldsProps
  types/redux-form/lib/FieldArray.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#45195 feat(glob): export glob api alias
  types/glob/glob-tests.ts
  types/glob/index.d.ts
Labels: Author is Owner, Critical package, Perf: Same

#45591 DraftJS: Key for RawDraftEntityRange should be a string
  types/draft-js/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45919 Removing myself from the Cheerio types project
  types/cheerio/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Untested Change

#45917 Add types for mudder
  types/mudder/index.d.ts
  types/mudder/mudder-tests.ts
  types/mudder/tsconfig.json
  types/mudder/tslint.json
Labels: New Definition, Other Approved

#45915 Add type definitions for the `readme-filename` package
  types/readme-filename/index.d.ts
  types/readme-filename/readme-filename-tests.ts
  types/readme-filename/tsconfig.json
  types/readme-filename/tslint.json
Labels: New Definition, Other Approved

#45913 [open-graph-scraper] Add open-graph-scraper
  types/open-graph-scraper/index.d.ts
  types/open-graph-scraper/open-graph-scraper-tests.ts
  types/open-graph-scraper/tsconfig.json
  types/open-graph-scraper/tslint.json
Labels: New Definition

#45795 Add types for get-installed-path
  types/get-installed-path/get-installed-path-tests.ts
  types/get-installed-path/index.d.ts
  types/get-installed-path/tsconfig.json
  types/get-installed-path/tslint.json
Labels: New Definition, Other Approved

#45911 Fixes stream-json types with esModuleInterop: true
  types/stream-json/filters/Filter.d.ts
  types/stream-json/filters/Ignore.d.ts
  types/stream-json/filters/Pick.d.ts
  types/stream-json/filters/Replace.d.ts
  types/stream-json/index.d.ts
  types/stream-json/streamers/StreamArray.d.ts
  types/stream-json/streamers/StreamBase.d.ts
  types/stream-json/streamers/StreamObject.d.ts
  types/stream-json/streamers/StreamValues.d.ts
  types/stream-json/utils/Batch.d.ts
  types/stream-json/utils/withParser.d.ts
Labels: Perf: Same, Untested Change

#45908 google-libphonenumer - Update PhoneNumberUtil with getLengthOfGeographicalAreaCode()
  types/google-libphonenumber/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#45749 [roslib] Add URDF classes
  types/roslib/index.d.ts
  types/roslib/roslib-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45869 d3-dispatch - parameter `that` need not be an `EventTarget`
  types/d3-dispatch/d3-dispatch-tests.ts
  types/d3-dispatch/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45849 refactor(node): Move `Process` definition to `process.d.ts`
  types/node/globals.d.ts
  types/node/process.d.ts
  types/node/ts3.2/base.d.ts
  types/node/ts3.2/globals.d.ts
  types/node/ts3.2/process.d.ts
Labels: Author is Owner, Critical package, Perf: Same, Untested Change

#45932 [sort-json] Add sort-json
  types/sort-json/index.d.ts
  types/sort-json/sort-json-tests.ts
  types/sort-json/tsconfig.json
  types/sort-json/tslint.json
Labels: New Definition

#45929 webpack: add missing MultiStats methods
  types/webpack/index.d.ts
  types/webpack/test/index.ts
Labels: Critical package, Perf: Same

#45928 add types for @ledgerhq/hw-app-btc
  types/ledgerhq__hw-app-btc/index.d.ts
  types/ledgerhq__hw-app-btc/ledgerhq__hw-app-btc-tests.ts
  types/ledgerhq__hw-app-btc/tsconfig.json
  types/ledgerhq__hw-app-btc/tslint.json
Labels: New Definition

#45925 [ramda] Update contributors in index.d.ts
  types/ramda/index.d.ts
Labels: Author is Owner, Perf: Same, Popular package, Untested Change

#45683 [chrome] Add chrome.enterprise.networkingAttributes and update chrome.platformKeys
  types/chrome/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#45275 [oracledb] Optional user in GetPooledConnectionOptions
  types/oracledb/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Merge:YSYL, Owner Approved, Perf: Same, Untested Change

#45888 [@types/mailgun-js] Fix mailgun-js type to add multiple data to mailing list
  types/mailgun-js/index.d.ts
Labels: Other Approved, Perf: Same, Untested Change

#45546 Update types/react-native-auth0 to reflect new API
  types/react-native-auth0/index.d.ts
  types/react-native-auth0/react-native-auth0-tests.ts
Labels: Merge:YSYL, Perf: Same

#45522 [draft-js] Allow a merged SelectionState to be passed to forceSelection
  types/draft-js/draft-js-tests.tsx
  types/draft-js/index.d.ts
Labels: Merge:YSYL, Perf: Same, Popular package

#45633 @types/weighted: exported default and corrected definitions
  types/weighted/index.d.ts
  types/weighted/weighted-tests.ts
Labels: Merge:YSYL, Perf: Worse

#45299 [@types/sdp-transform] Add a missing field from 'origin'
  types/sdp-transform/index.d.ts
  types/sdp-transform/sdp-transform-tests.ts
Labels: Merge:YSYL, Perf: Same

#45303 added sendAnimation type and added sendContact options
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Merge:Auto, Merge:YSYL, Owner Approved, Perf: Same

#45674 update(worker-plugin): v4 update
  types/worker-plugin/index.d.ts
  types/worker-plugin/worker-plugin-tests.ts
Labels: Merge:YSYL, Perf: Same

#45703 [glider-js] Update static types
  types/glider-js/glider-js-tests.ts
  types/glider-js/index.d.ts
Labels: Author is Owner, Merge:YSYL, No Other Owners, Perf: Same

#45251 [lgtv2] Make payload optional for SpecializedSocket.send
  types/lgtv2/index.d.ts
  types/lgtv2/lgtv2-tests.ts
Labels: Author is Owner, Merge:Auto, Merge:YSYL, No Other Owners, Other Approved, Perf: Same

#45691 [reactstrap]: Update types to 8.5
  types/reactstrap/index.d.ts
  types/reactstrap/lib/Modal.d.ts
  types/reactstrap/lib/Popover.d.ts
  types/reactstrap/lib/Progress.d.ts
  types/reactstrap/lib/Tooltip.d.ts
  types/reactstrap/reactstrap-tests.tsx
Labels: Author is Owner, Merge:YSYL, Perf: Same, Popular package

#45477 [Ramda] Add an overload function declaration for R.pair
  types/ramda/index.d.ts
  types/ramda/test/pair-tests.ts
Labels: Merge:YSYL, Perf: Same, Popular package

#45885 d3-selection - key function in `.data` may return `number` as well
  types/d3-selection/d3-selection-tests.ts
  types/d3-selection/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45705 Added doc strings and removed internal/duplicated entries
  types/websocket/index.d.ts
  types/websocket/websocket-tests.ts
Labels: Merge:YSYL, Perf: Same, Popular package

#45708 Correct type of SymbolLayout 'text-max-width' property in 'mapbox-gl'
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Merge:YSYL, Perf: Same, Popular package

#45747 [geodesy] Fix decimal point type
  types/geodesy/geodesy-tests.ts
  types/geodesy/index.d.ts
Labels: Merge:YSYL, Perf: Same

#45306 refactor(mui-datatables): updated for v3.1.x
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
  types/mui-datatables/tsconfig.json
Labels: Author is Owner, Config Edit, Other Approved, Perf: Same

#45918 Add type definitions for nanoid-dictionary
  types/nanoid-dictionary/index.d.ts
  types/nanoid-dictionary/lowercase.d.ts
  types/nanoid-dictionary/nanoid-dictionary-tests.ts
  types/nanoid-dictionary/nolookalikes.d.ts
  types/nanoid-dictionary/numbers.d.ts
  types/nanoid-dictionary/tsconfig.json
  types/nanoid-dictionary/tslint.json
  types/nanoid-dictionary/uppercase.d.ts
Labels: New Definition, Other Approved

#45916 [react-bootstrap-table-next] Allow to pass JSX.Element as *PageText option
  types/react-bootstrap-table-next/index.d.ts
Labels: Perf: Same, Untested Change

#45456 source-map-support: Fix return value types for `retrieveSourceMap`
  types/source-map-support/index.d.ts
  types/source-map-support/package.json
  types/source-map-support/source-map-support-tests.ts
Labels: Config Edit, Merge:YSYL, Perf: Worse, Popular package

#45427 Update react-grid-layout onDrop arguments
  types/react-grid-layout/index.d.ts
Labels: Merge:YSYL, Perf: Same, Untested Change

#45370 Add placeholder typings for includes function
  types/ramda/index.d.ts
Labels: Merge:YSYL, Perf: Worse, Popular package, Untested Change

#45349 [ramda] Removed intersectionWith
  types/ramda/OTHER_FILES.txt
  types/ramda/es/intersectionWith.d.ts
  types/ramda/index.d.ts
  types/ramda/src/intersectionWith.d.ts
Labels: Config Edit, Perf: Same, Popular package

#45508 [mem-fs-editor] Improved definition
  types/mem-fs-editor/index.d.ts
  types/mem-fs-editor/mem-fs-editor-tests.ts
Labels: Merge:YSYL, Perf: Same

#45326 fix(es‑abstract/helpers): Fix ES namespace argument type
  types/es-abstract/helpers/getIteratorMethod.d.ts
  types/es-abstract/helpers/isPropertyDescriptor.d.ts
  types/es-abstract/helpers/isSamePropertyDescriptor.d.ts
  types/es-abstract/test/helpers/assertRecord.test.ts
  types/es-abstract/test/helpers/getIteratorMethod.test.ts
Labels: Author is Owner, Popular package

#45540 Superfine amendments
  types/superfine/index.d.ts
  types/superfine/superfine-tests.ts
  types/superfine/superfine-tests.tsx
Labels: Author is Owner, No Other Owners, Perf: Worse

#45893 [@types/underscore] Collection and Array Tests - Reduce and ReduceRight
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45905 fix(cheerio): xml() to accept dom parameter
  types/cheerio/cheerio-tests.ts
  types/cheerio/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45930 [koa-cash] add typings for koa-cash v4.0
  types/koa-cash/index.d.ts
  types/koa-cash/koa-cash-tests.ts
  types/koa-cash/tsconfig.json
  types/koa-cash/tslint.json
Labels: New Definition

#45746 feat(glider-js): friction-free selector type
  types/glider-js/glider-js-tests.ts
  types/glider-js/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Worse

#45953 Update fastify code in tests
  types/swagger-stats/swagger-stats-tests.ts
Labels: Merge:Auto, Owner Approved

#45951 [recharts] Use lowercase `.md` suffix
  types/recharts/README.md
Labels: Config Edit, Owner Approved, Perf: Same, Popular package

#45956 Revert "refactor(node): Move `Buffer` definition to `buffer.d.ts` (#4…
  types/node/buffer.d.ts
  types/node/globals.d.ts
  types/node/ts3.2/base.d.ts
  types/node/ts3.2/buffer.d.ts
  types/node/ts3.2/globals.d.ts
Labels: Critical package, Perf: Same, Untested Change

#45836 prosemirror-commands: Add types Command and Keymap
  types/prosemirror-commands/index.d.ts
  types/prosemirror-commands/prosemirror-commands-tests.ts
  types/prosemirror-keymap/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved, Perf: Worse, Revision needed

#45907 [dwt] A major upgrade from version 15 to version 16
  types/dwt/Addon.BarcodeReader.d.ts
  types/dwt/Addon.OCR.d.ts
  types/dwt/Addon.OCRPro.d.ts
  types/dwt/Addon.PDF.d.ts
  types/dwt/Addon.Webcam.d.ts
  types/dwt/Dynamsoft.Enum.d.ts
  types/dwt/Dynamsoft.FileUploader.d.ts
  types/dwt/Dynamsoft.d.ts
  types/dwt/README.md
  types/dwt/WebTwain.Acquire.d.ts
  types/dwt/WebTwain.Buffer.d.ts
  types/dwt/WebTwain.Edit.d.ts
  types/dwt/WebTwain.IO.d.ts
  types/dwt/WebTwain.Util.d.ts
  types/dwt/WebTwain.Viewer.d.ts
  types/dwt/WebTwain.d.ts
  types/dwt/addon.ocr.d.ts
  types/dwt/addon.ocrp.d.ts
  types/dwt/addon.pdf.d.ts
  types/dwt/addon.webcam.d.ts
  types/dwt/dbr.d.ts
  types/dwt/dwt-tests.ts
  types/dwt/index.d.ts
  types/dwt/mbc.d.ts
Labels: Author is Owner, Config Edit, Owner Approved, Perf: Same

#45742 fix(glider-js): add `eventPropagate` option
  types/glider-js/glider-js-tests.ts
  types/glider-js/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45960 Sharedb: getSnapshotBulk second param should be a string array
  types/sharedb/index.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45787 Fix field defs for Document of forge-viewer
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
  types/forge-viewer/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto

#45920 [@types/raygun4js] Export internal interfaces
  types/raygun4js/index.d.ts
  types/raygun4js/raygun4js-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#45967 (@types/theme-ui): add highlight color
  types/theme-ui/index.d.ts
  types/theme-ui/theme-ui-tests.tsx
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45966 [pg] Move application_name field from PoolConfig to ClientConfig
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45978 [ember] @ember/object Correct arguments for Evented
  types/ember__object/evented.d.ts
  types/ember__object/test/event.ts
Labels: Merge:Auto, Owner Approved, Popular package

#45971 Update country-data typings
  types/country-data/country-data-tests.ts
  types/country-data/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45894 [@types/undercore] Object Tests - Type Checks
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45856 fix(node-persist): corrected logging option definition
  types/node-persist/index.d.ts
  types/node-persist/node-persist-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Worse

#45989 VS Code 1.47.0 extension API (vscode.d.ts)
  types/vscode/index.d.ts
Labels: Perf: Same, Untested Change

#45981 mui-datatables added missing types to MUIDataTableState
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same
