Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-03, with the labels that each got.

#42654 [Simplebar] Add typing for v5
  types/simplebar/index.d.ts
  types/simplebar/simplebar-tests.ts
  types/simplebar/v2/index.d.ts
  types/simplebar/v2/simplebar-tests.ts
  types/simplebar/v2/test/module-tests.ts
  types/simplebar/v2/tsconfig.json
  types/simplebar/v2/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#42702 Create a new package: Matrix AppService Bridge (matrix-appservice-bridge)
  types/matrix-appservice-bridge/index.d.ts
  types/matrix-appservice-bridge/matrix-appservice-bridge-tests.ts
  types/matrix-appservice-bridge/tsconfig.json
  types/matrix-appservice-bridge/tslint.json
Labels: New Definition, Revision needed

#42724 [teslajs] fix wrong Vehicle interface
  types/teslajs/index.d.ts
  types/teslajs/teslajs-tests.ts
Labels: Unowned

#42726 Fix MemoryCache `get` function type to correctly reflect nullability
  types/memory-cache/index.d.ts
Labels: Merge:Express, Owner Approved

#42719 chai: Tighten argument types of assert.throw methods.
  types/chai/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42723 feat(mongodb): add connection TLS options
  types/mongodb/index.d.ts
  types/mongodb/test/index.ts
Labels: Merge:Express, Owner Approved, Popular package

#42731 weixin-app: add missing members
  types/weixin-app/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42632 [Slonik] Added UUID type to TypeNameIdentifierType
  types/slonik/index.d.ts
Labels: Merge:Express, Owner Approved

#42740 Add types for @types/chart.js (tooltip model)
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42747 Remove thislooksfun from list of selenium-webdriver maintainers
  types/selenium-webdriver/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#42746 Remove thislooksfun from list of Bluebird maintainers
  types/bluebird/bluebird-tests.ts
  types/bluebird/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#42600 feat(watchify): update to version 3.11
  types/watchify/index.d.ts
  types/watchify/tsconfig.json
  types/watchify/tslint.json
  types/watchify/watchify-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#42613 add missing option `transformKey` in `flat`
  types/flat/flat-tests.ts
  types/flat/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#42729 Fix libxmljs Document.find overloads
  types/libxmljs/index.d.ts
  types/libxmljs/libxmljs-tests.ts
Labels: Merge:Express, Owner Approved

#42754 matter-js: add render.options.wireframeBackground
  types/matter-js/index.d.ts
Labels: Merge:Express, Owner Approved

#42762 Enrich sqs event with x ray trace header
  types/aws-lambda/test/sqs-tests.ts
  types/aws-lambda/trigger/sqs.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42420 [aws-lambda] New API Gateway Authorizer types, deprecating old ones.
  types/apex.js/index.d.ts
  types/aws-lambda/common/api-gateway.d.ts
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/trigger/api-gateway-authorizer.d.ts
  types/aws-lambda/trigger/api-gateway-proxy.d.ts
  types/cfn-response/index.d.ts
Labels: Awaiting reviewer feedback, Other Approved, Popular package

#42763 feat: @rdfjs/fetch
  types/rdfjs__fetch-lite/index.d.ts
  types/rdfjs__fetch/index.d.ts
  types/rdfjs__fetch/rdfjs__fetch-tests.ts
  types/rdfjs__fetch/tsconfig.json
  types/rdfjs__fetch/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, New Definition

#42646 add options.externalKey in koa-session
  types/koa-session/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#42649 [d3-brush] Added keymodifiers definition
  types/d3-brush/d3-brush-tests.ts
  types/d3-brush/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#42728 add types for @hapi/catbox-memcached
  types/hapi__catbox-memcached/hapi__catbox-memcached-tests.ts
  types/hapi__catbox-memcached/index.d.ts
  types/hapi__catbox-memcached/tsconfig.json
  types/hapi__catbox-memcached/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#42543 urijs: Correct UMD typings, remove implicit global declaration
  types/urijs/index.d.ts
  types/urijs/src/URITemplate.d.ts
  types/urijs/test/urijs-dom.test.ts
  types/urijs/test/urijs-global-module.test.ts
  types/urijs/test/urijs-global-script.test.ts
  types/urijs/test/urijs-nodejs.test.ts
  types/urijs/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#42738 feat(karma-json-preprocessor): new type definition
  types/karma-json-preprocessor/index.d.ts
  types/karma-json-preprocessor/karma-json-preprocessor-tests.ts
  types/karma-json-preprocessor/tsconfig.json
  types/karma-json-preprocessor/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42735 feat(karma-json-to-file-reporter): add type definition
  types/karma-json-to-file-reporter/index.d.ts
  types/karma-json-to-file-reporter/karma-json-to-file-reporter-tests.ts
  types/karma-json-to-file-reporter/tsconfig.json
  types/karma-json-to-file-reporter/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42721 feat(parameterize): add parameterize typings
  types/parameterize/index.d.ts
  types/parameterize/parameterize-tests.ts
  types/parameterize/tsconfig.json
  types/parameterize/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#42745 Added type definitions for scrollbooster
  types/scrollbooster/index.d.ts
  types/scrollbooster/scrollbooster-tests.ts
  types/scrollbooster/tsconfig.json
  types/scrollbooster/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42744 Add declarations for 'cron-converter'.
  types/cron-converter/cron-converter-tests.ts
  types/cron-converter/index.d.ts
  types/cron-converter/package.json
  types/cron-converter/tsconfig.json
  types/cron-converter/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42770 fix return type
  types/matrix-js-sdk/index.d.ts
Labels: Author is Owner, Merge:Express

#42736 Add @types/human-date
  types/human-date/human-date-tests.ts
  types/human-date/index.d.ts
  types/human-date/tsconfig.json
  types/human-date/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#42753 feat(filing-cabinet): type definitions for v2.5
  types/filing-cabinet/filing-cabinet-tests.ts
  types/filing-cabinet/index.d.ts
  types/filing-cabinet/tsconfig.json
  types/filing-cabinet/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42758 feat(style-search): new type definition v0.1
  types/style-search/index.d.ts
  types/style-search/style-search-tests.ts
  types/style-search/tsconfig.json
  types/style-search/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42760 feat(file-entry-cache): type definition v5.0
  types/file-entry-cache/file-entry-cache-tests.ts
  types/file-entry-cache/index.d.ts
  types/file-entry-cache/tsconfig.json
  types/file-entry-cache/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42769 fix public property opts
  types/matrix-appservice-bridge/index.d.ts
Labels: Unowned

#42773 fix(lodash): No `strict` override
  types/lodash/scripts/tsconfig.json
  types/lodash/ts3.1/scripts/tsconfig.json
Labels: Awaiting reviewer feedback, Other Approved, Popular package

#42776 Add type definitions for "scrambo"
  types/scrambo/index.d.ts
  types/scrambo/scrambo-tests.ts
  types/scrambo/tsconfig.json
  types/scrambo/tslint.json
Labels: New Definition, Revision needed

#42775 newrelic adds distributed tracing Transaction handle method insertDistributedTraceHeaders
  types/newrelic/index.d.ts
  types/newrelic/newrelic-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42772 [office-js, office-js-preview, office-runtime] Changing codeowners
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
  types/office-runtime/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#42774 react-table: add maintainer
  types/react-table/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#42766 [styled-system] Add missing margin and padding properties
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#42779 feat(decomment): type definition for v0.9
  types/decomment/decomment-tests.ts
  types/decomment/index.d.ts
  types/decomment/tsconfig.json
  types/decomment/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42780 feat(is-relative-path): type definition for v2
  types/is-relative-path/index.d.ts
  types/is-relative-path/is-relative-path-tests.ts
  types/is-relative-path/tsconfig.json
  types/is-relative-path/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42657 @mdx-js/react exports mdx (alias for React.createElement)
  types/mdx-js__react/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#42782 [@types/cesium] Add PropertyBag
  types/cesium/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42651 [@types/parse] Added AuthProvider and user function definitions
  types/parse/index.d.ts
  types/parse/parse-tests.ts
  types/parse/ts3.7/index.d.ts
  types/parse/ts3.7/parse-tests.ts
Labels: Merge:Express, Owner Approved

#42796 Fix typo
  types/react-swipeable-views-utils/index.d.ts
Labels: Merge:Express, Owner Approved

#42789 [stripe-v3] fix: add missing subtype 'validation_error' to ErrorType
  types/stripe-v3/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42794 matter-js: add mouse events
  types/matter-js/index.d.ts
  types/matter-js/matter-js-tests.ts
Labels: Merge:Express, Owner Approved

#42800 react-leaflet: fix GeoJSON data property's type
  types/react-leaflet/index.d.ts
  types/react-leaflet/react-leaflet-tests.tsx
Labels: Merge:Express, Owner Approved

#42662 [Express] [Type Update] Use generics for Response
  types/express/express-tests.ts
  types/express/index.d.ts
  types/ghost-storage-base/ghost-storage-base-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#42685 Mocha: add color as mocha option
  types/mocha/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#42684 add @mocha package declaration for mocha.loadFilesAsync()
  types/mocha/index.d.ts
  types/mocha/mocha-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#42784 [@types/rtp-parser] New Definition
  types/rtp-parser/index.d.ts
  types/rtp-parser/rtp-parser-tests.ts
  types/rtp-parser/tsconfig.json
  types/rtp-parser/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42752 feat(standard-engine): new type definition v12
  types/standard-engine/index.d.ts
  types/standard-engine/standard-engine-tests.ts
  types/standard-engine/tsconfig.json
  types/standard-engine/tslint.json
Labels: New Definition, Revision needed

#42805 Update default export of Diva.js
  types/diva.js/index.d.ts
Labels: Author is Owner, Merge:Express

#42765 feat(gestalt): updated gestalt to newest types v1.10.0
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Merge:Express, Owner Approved

#42692 [serverless] Add getAccountId method on AwsProvider
  types/serverless/plugins/aws/provider/awsProvider.d.ts
Labels: Merge:Express, Owner Approved

#42693 Enable noImplicitAny
  types/akamai-edgeworkers/tsconfig.json
  types/amplify-deferred/tsconfig.json
  types/backbone-fetch-cache/tsconfig.json
  types/backlog-js/tsconfig.json
  types/bootstrap-fileinput/tsconfig.json
  types/cldrjs/tsconfig.json
  types/cordova-plugin-keyboard/tsconfig.json
  types/cordova-plugin-websql/tsconfig.json
  types/cordova/tsconfig.json
  types/df-visible/tsconfig.json
  types/dhtmlxgantt/tsconfig.json
  types/egg-mock/tsconfig.json
  types/fancybox/tsconfig.json
  types/jquery.cycle/tsconfig.json
  types/jquery.timepicker/tsconfig.json
  types/jquery.validation/tsconfig.json
  types/jquery.watermark/tsconfig.json
  types/mailparser/tsconfig.json
  types/pouchdb/tsconfig.json
  types/restler/tsconfig.json
  types/samlp/tsconfig.json
  types/sqlanywhere/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#42790 Update flatten typing under StyleSheet namespace. React-Native
  types/react-native/index.d.ts
  types/react-native/test/stylesheet-flatten.tsx
  types/react-native/tsconfig.json
Labels: Popular package, Revision needed

#42668 Fix typings of express-mysql-session
  types/express-mysql-session/express-mysql-session-tests.ts
  types/express-mysql-session/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#42811 feat(git-branch-is): new type definition for v3.1
  types/git-branch-is/git-branch-is-tests.ts
  types/git-branch-is/index.d.ts
  types/git-branch-is/tsconfig.json
  types/git-branch-is/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42411 [react-table]: V7 upgrade to support rc-16
  types/react-table/index.d.ts
  types/react-table/react-table-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Popular package

#42828 [react-native] Specify more detailed type of `hardwareBackPress` handler
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#42819 Added types for jest-sinon package
  types/jest-sinon/index.d.ts
  types/jest-sinon/jest-sinon-tests.ts
  types/jest-sinon/tsconfig.json
  types/jest-sinon/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42824 Add types for markdown-table
  types/markdown-table/index.d.ts
  types/markdown-table/markdown-table-tests.ts
  types/markdown-table/tsconfig.json
  types/markdown-table/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42822 update to 15.3
  types/dwt/Dynamsoft.d.ts
  types/dwt/README.md
  types/dwt/addon.ocr.d.ts
  types/dwt/addon.ocrp.d.ts
  types/dwt/addon.pdf.d.ts
  types/dwt/addon.webcam.d.ts
  types/dwt/dbr.d.ts
  types/dwt/index.d.ts
  types/dwt/mbc.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42821 [mongodb] Allow optional fields in $inc and $mul
  types/mongodb/index.d.ts
  types/mongodb/test/collection/updateX.ts
Labels: Merge:Express, Owner Approved, Popular package

#42834 Add deprecation schedule
  README.md
Labels: Other Approved, Unowned

#42803 [cesium] add constructor and removeProperty to PropertyBag
  types/cesium/index.d.ts
Labels: Owner Approved, Revision needed

#42739 Add just-map-values and just-safe-set types
  types/just-map-values/index.d.ts
  types/just-map-values/just-map-values-tests.ts
  types/just-map-values/tsconfig.json
  types/just-map-values/tslint.json
  types/just-safe-set/index.d.ts
  types/just-safe-set/just-safe-set-tests.ts
  types/just-safe-set/tsconfig.json
  types/just-safe-set/tslint.json
Labels: New Definition, Revision needed

#42579 [@types/marked] fixed type of `marked.MarkedOptions.highlight` in case of async highlighting
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Popular package, Revision needed

#42847 [react-native] update NativeEventEmitter constructor and removeAllListeners method
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Popular package, Revision needed

#42832 [plotly.js] - polar layout
  types/plotly.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42816 [@types/recharts]: LabelListProps: dataKey should be optional if valueAccessor is defined
  types/recharts/index.d.ts
  types/recharts/recharts-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#42809 @types/prompts: Add description field for choices
  types/prompts/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42837 @testing-library__react: add debug options
  types/testing-library__react/index.d.ts
  types/testing-library__react/package.json
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#42792 iab-vpaid: Correct AdVideoMidPoint to AdVideoMidpoint (lowercase 'p').
  types/iab-vpaid/iab-vpaid-tests.ts
  types/iab-vpaid/index.d.ts
Labels: Merge:Express, Owner Approved

#42835 [chance] add option definition for chance.cpf()
  types/chance/chance-tests.ts
  types/chance/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#42826 [@types/frida-gum]: update: make `Java.Wrapper` more generic
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
Labels: Merge:Express, Owner Approved

#42852 Add type IdleState to chrome.idle
  types/chrome/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42814 pdfmake - update v0.1.65
  types/pdfmake/index.d.ts
  types/pdfmake/pdfmake-tests.ts
  types/pdfmake/tslint.json
Labels: Merge:Express, Owner Approved

#42725 plaid-link: Add linkCustomizationName to CreateConfig
  types/plaid-link/index.d.ts
Labels: Merge:Express, Owner Approved

#42844 update(mongodb): MongoError `hasErrorLabel` missing from 3.5
  types/mongodb/index.d.ts
  types/mongodb/test/index.ts
Labels: Merge:Express, Owner Approved, Popular package

#42850 [jasmine] Support custom async matchers
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/jasmine/ts3.1/index.d.ts
  types/jasmine/ts3.1/jasmine-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#42843 feat(gravatar): missing 1.8 version features
  types/gravatar/gravatar-tests.ts
  types/gravatar/index.d.ts
  types/gravatar/tslint.json
Labels: Merge:Express, Owner Approved

#42842 chromecast-caf-sender: add null as a valid return type of interceptors
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Merge:Express, Owner Approved

#42866 [plotly.js] opacity to PlotData
  types/plotly.js/index.d.ts
Labels: Merge:Express, Owner Approved

#42881 Update Readme for Russian language
  README.md
  README.ru.md
Labels: Unowned

#42857 Added 'pi-camera' type definition
  types/pi-camera/index.d.ts
  types/pi-camera/pi-camera-tests.ts
  types/pi-camera/tsconfig.json
  types/pi-camera/tslint.json
Labels: New Definition, Revision needed

#42873 office-js-preview Page-to-Dialog messaging APIs
  types/office-js-preview/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42825 feat(bearcat-es6) add type definition for bearcat-es6 0.6.1
  types/bearcat-es6/bearcat-es6-tests.ts
  types/bearcat-es6/index.d.ts
  types/bearcat-es6/tsconfig.json
  types/bearcat-es6/tslint.json
Labels: New Definition, Revision needed

#42764 Type definitions for FullCalendar-Vue
  types/fullcalendar__vue/fullcalendar__vue-tests.ts
  types/fullcalendar__vue/index.d.ts
  types/fullcalendar__vue/options.d.ts
  types/fullcalendar__vue/package.json
  types/fullcalendar__vue/tsconfig.json
  types/fullcalendar__vue/tslint.json
Labels: New Definition, Revision needed

#42827 Using generic types in List Component
  types/react-onsenui/index.d.ts
  types/react-onsenui/react-onsenui-tests.tsx
Labels: Owner Approved, Revision needed

#42778 [node] move to 13.9
  types/node/async_hooks.d.ts
  types/node/globals.d.ts
  types/node/http.d.ts
  types/node/index.d.ts
  types/node/perf_hooks.d.ts
  types/node/readline.d.ts
  types/node/test/async_hooks.ts
  types/node/test/http.ts
  types/node/test/perf_hooks.ts
  types/node/test/process.ts
  types/node/test/readline.ts
  types/node/test/worker_threads.ts
  types/node/worker_threads.d.ts
Labels: Author is Owner, Popular package, Revision needed

#42900 [clockpicker] Enable noImplicitThis
  types/clockpicker/tsconfig.json
Labels: Merge:Express, Owner Approved

#42885 matter-js: add Grid.bucketWidth, Grid.bucketHeight and update constraint render options
  types/matter-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#42861 Extend matrix-js-sdk types
  types/matrix-appservice-bridge/index.d.ts
  types/matrix-js-sdk/index.d.ts
Labels: Merge:Express, Owner Approved

#42856 [titanium] update types for Titanium 9.0.0
  types/titanium/index.d.ts
  types/titanium/titanium-tests.ts
  types/titanium/tsconfig.json
Labels: Author is Owner, Merge:Express, Other Approved, Owner Approved, Revision needed

#42749 feat(figma): Type definitions for update 14
  types/figma/index.d.ts
Labels: Merge:Express, Owner Approved

#42859 Add getTileUrl() method to TileLayer
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#42919 [leaflet] Enable noImplicitThis
  types/leaflet/v0/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#42913 [jquery-knob] Enable noImplicitThis
  types/jquery-knob/tsconfig.json
Labels: Merge:Express, Owner Approved

#42921 [mailcheck] Enable noImplicitThis
  types/mailcheck/tsconfig.json
Labels: Merge:Express, Owner Approved

#42928 [nestdb] Enable noImplicitThis
  types/nestdb/tsconfig.json
Labels: Merge:Express, Owner Approved

#42897 [classnames] Remove myself as maintainer.
  types/classnames/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#42938 [react-mdl] Enable noImplicitThis
  types/react-mdl/tsconfig.json
Labels: Merge:Express, Owner Approved

#42958 Update README.ko.md
  README.ko.md
  README.md
Labels: Unowned

#42963 Added deprecation schedule to readme.es.md
  README.es.md
Labels: Unowned

#42908 [flatbuffers] Enable noImplicitThis
  types/flatbuffers/tsconfig.json
Labels: Unowned

#42629 fix(bazinga-translator): correct definition to support UMD
  types/bazinga-translator/index.d.ts
  types/bazinga-translator/test/bazinga-translator-tests.commonjs.ts
  types/bazinga-translator/test/bazinga-translator-tests.umd.ts
  types/bazinga-translator/tsconfig.json
  types/bazinga-translator/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#42748 React countup upgrade definitions up to version 4.3.3
  types/react-countup/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#42964 node-ssh: initial definition
  types/node-ssh/index.d.ts
  types/node-ssh/node-ssh-tests.ts
  types/node-ssh/tsconfig.json
  types/node-ssh/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42959 Add wordpress-hash-node
  types/wordpress-hash-node/index.d.ts
  types/wordpress-hash-node/tsconfig.json
  types/wordpress-hash-node/tslint.json
  types/wordpress-hash-node/wordpress-hash-node-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#42894 Add node-phpass
  types/node-phpass/index.d.ts
  types/node-phpass/node-phpass-tests.ts
  types/node-phpass/tsconfig.json
  types/node-phpass/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42756 Hubot: Adds some missing, new, types to bring up to date for v3
  types/hubot/hubot-tests.ts
  types/hubot/index.d.ts
Labels: Revision needed

#42890 Fix(sdp-transform) bandwidth should be array
  types/sdp-transform/index.d.ts
Labels: Merge:Express, Owner Approved

#42936 [react-infinite-scroller] Enable noImplicitThis
  types/react-infinite-scroller/tsconfig.json
Labels: Merge:Express, Owner Approved

#42939 [react-select] Enable noImplicitThis
  types/react-select/v1/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#42864 [office-js] (Outlook) Removed restUrl link to SharedProperties
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved

#42965 [jest] Improve toContain matcher description.
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#42906 [ember-testing-helpers] Enable noImplicitThis
  types/ember-testing-helpers/tsconfig.json
Labels: Merge:Express, Owner Approved

#42945 [redux-promise] Enable noImplicitThis
  types/redux-promise/tsconfig.json
Labels: Merge:Express, Owner Approved

#42953 [through2] Enable noImplicitThis
  types/through2/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#42961 [styled-system] Allow null ResponsiveValue
  types/styled-system/index.d.ts
  types/styled-system/styled-system-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#42886 new types for package "overload-protection"
  types/overload-protection/index.d.ts
  types/overload-protection/overload-protection-tests.ts
  types/overload-protection/tsconfig.json
  types/overload-protection/tslint.json
Labels: New Definition, Revision needed

#42652 [mongoose] Define lean() result type
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Popular package, Revision needed

#42887 [pino] add `levelKey` option, deprecate `changeLevelName` option
  types/pino/index.d.ts
  types/pino/pino-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#42838 [lingui__react]: Add i18nHash to withI18n
  types/lingui__react/withI18n.d.ts
Labels: Owner Approved, Revision needed

#42968 Add locale types
  types/locale/index.d.ts
  types/locale/locale-tests.ts
  types/locale/tsconfig.json
  types/locale/tslint.json
Labels: New Definition, Revision needed

#42940 [react] Enable noImplicitThis
  types/react/tsconfig.json
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#38067 add cloudevents-sdk/v03 types
  types/cloudevents-sdk/cloudevents-sdk-tests.ts
  types/cloudevents-sdk/index.d.ts
  types/cloudevents-sdk/tsconfig.json
  types/cloudevents-sdk/tslint.json
Labels: New Definition, Revision needed

#42848 [office-js, office-js-preview] Update with latest from CDN
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42892 feat(testing-library/dom): Add name option to byRole
  types/testing-library__dom/index.d.ts
  types/testing-library__dom/queries.d.ts
  types/testing-library__dom/testing-library__dom-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#42967 [jasmine] Allow resolveTo/rejectWith with empty parameters
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/jasmine/ts3.1/index.d.ts
  types/jasmine/ts3.1/jasmine-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#43025 [@types/urijs] Added properties and methods: duplicateQueryParameters, escapeQuerySpace, preventInvalidHostname
  types/urijs/index.d.ts
Labels: Owner Approved, Popular package, The Travis CI build failed

#42926 [naver-whale] Enable noImplicitThis
  types/naver-whale/tsconfig.json
Labels: Merge:Express, Owner Approved

#42932 [react-data-grid] Enable noImplicitThis
  types/react-data-grid/tsconfig.json
  types/react-data-grid/v1/tsconfig.json
  types/react-data-grid/v2/tsconfig.json
Labels: Merge:Express, Other Approved, Owner Approved

#43039 [mongoose] Fix _id type of lean() result
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Awaiting reviewer feedback, Popular package

#42974 [emscripten] Fix addFunction arg type
  types/emscripten/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42955 [wu] Enable noImplicitThis
  types/wu/tsconfig.json
Labels: Merge:Express, Other Approved, Owner Approved

#42979 Update types for Redux-state-sync
  types/redux-state-sync/index.d.ts
  types/redux-state-sync/redux-state-sync-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42960 fix(cesium): missing objects added
  types/cesium/index.d.ts
  types/cesium/test/cesium-global.test.ts
  types/cesium/test/cesium-module.test.ts
Labels: Merge:Express, Owner Approved

#43033 Remove ambient module declaration in 'randomColor'.
  types/randomcolor/index.d.ts
Labels: Merge:Express, Owner Approved

#42891 @types/react-native-video: Add type for onBuffer argument
  types/react-native-video/index.d.ts
Labels: Merge:Express, Owner Approved

#42981 fix(autoprefixer): correct deprecated properties
  types/autoprefixer/autoprefixer-tests.ts
  types/autoprefixer/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#42849 Pg: Adds a boolean value for the parseInputDatesAsUTC ClientConfig option
  types/pg/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42929 [ngreact] Enable noImplicitThis
  types/ngreact/tsconfig.json
Labels: Merge:Express, Other Approved, Owner Approved

#42972 passport prompts - Fix username of contributor
  types/passport/index.d.ts
  types/prompts/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42617 [mongoose] Use mongodb.FilterQuery type
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Awaiting reviewer feedback, Other Approved, Popular package, Revision needed

#43068 react-native: fix broken link for AppRegistry.
  types/react-native/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#42846 [office-js-preview] (Outlook) Body.appendOnSendAsync
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Revision needed
