Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-06, with the labels that each got.

#45144 react-native-calendars: Add missing props
  types/react-native-calendars/index.d.ts
  types/react-native-calendars/react-native-calendars-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#45115 ember__test-helpers - update click signature
  types/ember__test-helpers/ember__test-helpers-tests.ts
  types/ember__test-helpers/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, The Travis CI build failed

#45209 Add NetworkCreateOptions and type createNetwork
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#45052 * Update typing for js-captcha 1.3
  types/js-captcha/dist/js/jCaptcha.d.ts
  types/js-captcha/index.d.ts
  types/js-captcha/js-captcha-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Perf: Same

#45067 fix: definition of CanvasGradient and CanvasPattern
  types/uni-app/lib/uni.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Revision needed

#45218 [dockerode] Use NetworkCreateOptions in createNetwork()
  types/dockerode/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same

#45215 [echarts] Tooltip interface standardization
  types/echarts/index.d.ts
  types/echarts/options/series/bar.d.ts
  types/echarts/options/series/boxplot.d.ts
  types/echarts/options/series/candlestick.d.ts
  types/echarts/options/series/custom.d.ts
  types/echarts/options/series/effect-scatter.d.ts
  types/echarts/options/series/funnel.d.ts
  types/echarts/options/series/gauge.d.ts
  types/echarts/options/series/graph.d.ts
  types/echarts/options/series/heatmap.d.ts
  types/echarts/options/series/line.d.ts
  types/echarts/options/series/map.d.ts
  types/echarts/options/series/parallel.d.ts
  types/echarts/options/series/pictorial-bar.d.ts
  types/echarts/options/series/pie.d.ts
  types/echarts/options/series/radar.d.ts
  types/echarts/options/series/sankey.d.ts
  types/echarts/options/series/scatter.d.ts
  types/echarts/options/series/theme-river.d.ts
  types/echarts/options/series/tree.d.ts
  types/echarts/options/series/treemap.d.ts
  types/echarts/options/tooltip.d.ts
Labels: Maintainer Approved, Merge:Auto, Popular package

#45168 add types for ink-box
  types/ink-box/index.d.ts
  types/ink-box/ink-box-tests.tsx
  types/ink-box/tsconfig.json
  types/ink-box/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition, Other Approved

#45211 fix(node): add missing Http2 types
  types/node/http2.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#44972 @types/node - Fix return type of process.kill
  types/node/globals.d.ts
  types/node/v12/globals.d.ts
Labels: Critical package, Owner Approved, Perf: Same

#45002 Add export for power-assert-formatter
  types/power-assert-formatter/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#44952 [node] Mirror child_process encoding between execSync and spawnSync
  types/node/child_process.d.ts
  types/node/test/child_process.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#44515 Update `@babel/core`, `@babel/traverse` and `babel-plugin-macros`.
  types/babel-plugin-macros/index.d.ts
  types/babel__core/babel__core-tests.ts
  types/babel__core/index.d.ts
  types/babel__traverse/babel__traverse-tests.ts
  types/babel__traverse/index.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#45019 Add superfine types.
  types/superfine/index.d.ts
  types/superfine/superfine-tests.ts
  types/superfine/superfine-tests.tsx
  types/superfine/tsconfig.json
  types/superfine/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#44982 webpack: Add mainTemplate.hooks.require and hooks.hash typings
  types/webpack/index.d.ts
  types/webpack/test/index.ts
Labels: Critical package, Owner Approved, Perf: Same

#45205 [aws-lambda] Add support for payload format v2 of API Gateway proxy
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/trigger/api-gateway-proxy.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44842 sharedb – Fix missing & incorrect types
  types/sharedb/index.d.ts
  types/sharedb/lib/client.d.ts
  types/sharedb/lib/sharedb.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#44882 [secure-random-password] Update definition
  types/secure-random-password/index.d.ts
  types/secure-random-password/secure-random-password-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45226 Add typescript dependency
  package.json
Labels: Perf: Same

#45238 Revert "feat(hapi__joi): add regex method to ObjectSchema (#44252)"
  types/hapi__joi/index.d.ts
Labels: Popular package

#45242 fix/add some AWS serverless types
  types/serverless/index.d.ts
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved

#45076 Revert delete of CSS typed OM
  types/w3c-css-typed-object-model-level-1/index.d.ts
  types/w3c-css-typed-object-model-level-1/tsconfig.json
  types/w3c-css-typed-object-model-level-1/tslint.json
  types/w3c-css-typed-object-model-level-1/w3c-css-typed-object-model-level-1-tests.ts
Labels: New Definition, Other Approved

#45066 Add new typeing for System Logger
  types/system-logger/index.d.ts
  types/system-logger/system-logger-tests.ts
  types/system-logger/tsconfig.json
  types/system-logger/tslint.json
Labels: New Definition

#45118 chore(es‑abstract): Simplify `tsconfig.json`
  types/es-abstract/es-abstract-tests.ts
  types/es-abstract/tsconfig.json
Labels: Author is Owner, Popular package

#45121 Fix isMatchCustomizer return type fix
  types/lodash/common/lang.d.ts
  types/lodash/lodash-tests.ts
  types/lodash/ts3.1/common/lang.d.ts
  types/lodash/ts3.1/lodash-tests.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, The Travis CI build failed

#45135 New type definition created for passport-instagram-token package.
  types/passport-instagram-token/index.d.ts
  types/passport-instagram-token/passport-instagram-token-tests.ts
  types/passport-instagram-token/tsconfig.json
  types/passport-instagram-token/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition, The Travis CI build failed

#45136 New type definition created for passport-instagram-graph package
  types/passport-instagram-graph/index.d.ts
  types/passport-instagram-graph/passport-instagram-graph-tests.ts
  types/passport-instagram-graph/tsconfig.json
  types/passport-instagram-graph/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition, The Travis CI build failed

#45163 [workerpool] Fix the return type of workerpool.Promise.catch.
  types/workerpool/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45208 react-datepicker: add customTimeInput prop
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45236 [@types/relay-runtime]: Support object & list value arguments
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/store/ClientID.d.ts
  types/relay-runtime/lib/store/RelayModernStore.d.ts
  types/relay-runtime/lib/subscription/requestSubscription.d.ts
  types/relay-runtime/lib/util/ReaderNode.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
  types/relay-runtime/tslint.json
Labels: Perf: Same

#45072 [node-jose]: Add additional createEncrypt options
  types/node-jose/index.d.ts
  types/node-jose/node-jose-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45263 Tweaks to API Gateway proxy v2 definitions
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/trigger/api-gateway-proxy.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45125 fix(amazon-connect-streams) Sync types with official repo
  types/amazon-connect-streams/amazon-connect-streams-tests.ts
  types/amazon-connect-streams/index.d.ts
  types/amazon-connect-streams/tslint.json
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45160 update(stylelint-webpack-plugin): v2 update
  types/stylelint-webpack-plugin/index.d.ts
  types/stylelint-webpack-plugin/stylelint-webpack-plugin-tests.ts
  types/stylelint-webpack-plugin/v0/index.d.ts
  types/stylelint-webpack-plugin/v0/stylelint-webpack-plugin-tests.ts
  types/stylelint-webpack-plugin/v0/tsconfig.json
  types/stylelint-webpack-plugin/v0/tslint.json
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45159 feat(npm-install-webpack-plugin): v4 module definition
  types/npm-install-webpack-plugin/index.d.ts
  types/npm-install-webpack-plugin/npm-install-webpack-plugin-tests.ts
  types/npm-install-webpack-plugin/tsconfig.json
  types/npm-install-webpack-plugin/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45153 Add definitions for syllable
  types/syllable/index.d.ts
  types/syllable/syllable-tests.ts
  types/syllable/tsconfig.json
  types/syllable/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition, The Travis CI build failed

#45038 [react-stickynode] Update types to match version 3.0.2
  types/react-stickynode/index.d.ts
  types/react-stickynode/react-stickynode-tests.tsx
Labels: Perf: Same

#45025 [Rascal] Add missing export for SubscriptionSession
  types/rascal/index.d.ts
  types/rascal/rascal-tests.ts
Labels: Author is Owner, Perf: Same

#45112 [node]: Add missing "freeSockets" property to HTTP Agent
  types/node/http.d.ts
  types/node/node-tests.ts
  types/node/test/http.ts
Labels: Critical package, Perf: Same, The Travis CI build failed

#45131 Updated ws types to be compatible with updates types in node
  types/ws/index.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same, The Travis CI build failed

#45127 feat(svg-spritemap-webpack-plugin): new type definition
  types/svg-spritemap-webpack-plugin/index.d.ts
  types/svg-spritemap-webpack-plugin/svg-spritemap-webpack-plugin-tests.ts
  types/svg-spritemap-webpack-plugin/tsconfig.json
  types/svg-spritemap-webpack-plugin/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition, The Travis CI build failed

#45093 Add type definitions for svg2ttf
  types/svg2ttf/index.d.ts
  types/svg2ttf/svg2ttf-tests.ts
  types/svg2ttf/tsconfig.json
  types/svg2ttf/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition, Other Approved, The Travis CI build failed

#45175 [node] Add missing properties to ReadableStream on Node >= v12
  types/node/stream.d.ts
  types/node/v12/stream.d.ts
  types/node/v13/stream.d.ts
  types/readable-stream/index.d.ts
Labels: Critical package, Perf: Same

#45181 Add `id` prop type for @hcaptcha/react-hcaptcha
  types/hcaptcha__react-hcaptcha/index.d.ts
Labels: Owner Approved, Perf: Same

#45183 Remove myself from contributors of react-bootstrap types
  types/react-bootstrap/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package

#45182 Add types for react-relative-portal
  types/react-relative-portal/index.d.ts
  types/react-relative-portal/react-relative-portal-tests.tsx
  types/react-relative-portal/tsconfig.json
  types/react-relative-portal/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45180 type definitions for node-microphone
  types/node-microphone/index.d.ts
  types/node-microphone/node-microphone-tests.ts
  types/node-microphone/tsconfig.json
  types/node-microphone/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45176 feat(gtmetrix): new type definition
  types/gtmetrix/gtmetrix-tests.ts
  types/gtmetrix/index.d.ts
  types/gtmetrix/tsconfig.json
  types/gtmetrix/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45167 [gapi.client.sheets] automatic update
  types/gapi.client.sheets/index.d.ts
  types/gapi.client.sheets/readme.md
Labels: Author is Owner, Perf: Same

#45170 add types for ink-divider
  types/ink-divider/index.d.ts
  types/ink-divider/ink-divider-tests.tsx
  types/ink-divider/tsconfig.json
  types/ink-divider/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45166 [gapi.client.drive] automatic update
  types/gapi.client.drive/index.d.ts
  types/gapi.client.drive/readme.md
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same

#45169 [gapi.client.discovery] automatic update
  types/gapi.client.discovery/index.d.ts
  types/gapi.client.discovery/readme.md
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same

#45157 [gapi.client.calendar] automatic update
  types/gapi.client.calendar/index.d.ts
  types/gapi.client.calendar/readme.md
Labels: Author is Owner, Other Approved, Perf: Same

#45046 fix(lusca): missing CSRF 'header' base property
  types/lusca/index.d.ts
  types/lusca/lusca-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45231 feat(es‑abstract): Make `ESAbstract.PropertyDescriptor` generic
  types/es-abstract/es2015.d.ts
  types/es-abstract/es2016.d.ts
  types/es-abstract/es2017.d.ts
  types/es-abstract/es2018.d.ts
  types/es-abstract/es2019.d.ts
  types/es-abstract/es5.d.ts
  types/es-abstract/index.d.ts
  types/es-abstract/test/es2015.test.ts
  types/es-abstract/test/es5.test.ts
  types/es-abstract/test/helpers/isPropertyDescriptor.test.ts
  types/es-abstract/test/index.test.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45269 [react-native] Add Focusable View Prop
  types/react-native/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package

#45203 stripe-v3: add type for method stripe.retrieveSetupIntent
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45280 [types/react-tracking] Fix TrackingInfo async repsonse
  types/react-tracking/index.d.ts
  types/react-tracking/test/react-tracking-with-types-tests.tsx
  types/react-tracking/test/react-tracking-without-types-tests.tsx
Labels: Perf: Same

#45291 [office-js] [office-js-preview] (saveAsync) Remove OWA note
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner

#44619 [@types/mongoose]: strong typed model.create()/new ()
  types/mongoose/index.d.ts
  types/mongoose/test/model.ts
Labels: Maintainer Approved, New Definition, Perf: Same, Popular package, Where is GH Actions?

#45288 Update @typeform/embed to v0.20
  types/typeform__embed/index.d.ts
  types/typeform__embed/typeform__embed-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45064 libxslt: fix callback type signatures, errors can be null
  types/libxslt/index.d.ts
  types/libxslt/internal-types.d.ts
  types/libxslt/libxslt-tests.ts
Labels: Perf: Same

#45079 [ioredis] Add map types back to hmset and mset
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#45164 add type definitions for @giusto/ink-router
  types/giusto__ink-router/giusto__ink-router-tests.tsx
  types/giusto__ink-router/index.d.ts
  types/giusto__ink-router/tsconfig.json
  types/giusto__ink-router/tslint.json
Labels: New Definition, Other Approved

#45117 feat(es‑abstract): Use script to generate `GetIntrinsics`
  types/es-abstract/GetIntrinsic.d.ts
  types/es-abstract/scripts/collect-intrinsics.ts
  types/es-abstract/scripts/tsconfig.json
  types/es-abstract/test/GetIntrinsic.test.ts
  types/es-abstract/test/helpers/callBound.test.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, The Travis CI build failed

#45193 fix(glob): correct return type to match Glob interface
  types/glob/glob-tests.ts
  types/glob/index.d.ts
Labels: Critical package, Other Approved, Perf: Same

#45194 update(jsdoc-to-markdown): version 6 bump
  types/jsdoc-to-markdown/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same

#45189 Created types for json-schema-faker npm library
  types/json-schema-faker/index.d.ts
  types/json-schema-faker/json-schema-faker-tests.ts
  types/json-schema-faker/tsconfig.json
  types/json-schema-faker/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition, Other Approved

#45202 Add types for react-vis
  types/react-vis/index.d.ts
  types/react-vis/react-vis-tests.tsx
  types/react-vis/tsconfig.json
  types/react-vis/tslint.json
Labels: New Definition

#45199 react-table: fix type of nested headers
  types/react-table/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Worse, Popular package

#45200 Added types for StreamSaver.js
  types/streamsaver/index.d.ts
  types/streamsaver/streamsaver-tests.ts
  types/streamsaver/tsconfig.json
  types/streamsaver/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45307 fix: hls.js media type should be HTMLMediaElement
  types/hls.js/hls.js-tests.ts
  types/hls.js/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45292 [@types/node-forge] - change return type of publicKeyFromPem() and privateKeyFromPem()
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45296 [@types/braintree] Correct PlanGateway#all return type and Subscripti…
  types/braintree/braintree-tests.ts
  types/braintree/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45311 Update lightship types to 6.1
  types/lightship/index.d.ts
  types/lightship/lightship-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45314 [office-js-preview] (Outlook) Fix links with broken anchors
  types/office-js-preview/index.d.ts
Labels: Author is Owner

#45198 feat(node-sass-tilde-importer): custom node-sass plugin
  types/node-sass-tilde-importer/index.d.ts
  types/node-sass-tilde-importer/node-sass-tilde-importer-tests.ts
  types/node-sass-tilde-importer/tsconfig.json
  types/node-sass-tilde-importer/tslint.json
Labels: New Definition

#45197 [@types/mkdirp] Fixed type of `opts` argument to sync methods.
  types/mkdirp/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#45089 Fix returned promise generic types
  types/rpi-gpio/index.d.ts
  types/rpi-gpio/rpi-gpio-tests.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same

#45092 [d3-brush] Added possibility of event.selection to be null
  types/d3-brush/d3-brush-tests.ts
  types/d3-brush/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#45074 [mixpanel-browser] Add missing init options and callback response
  types/mixpanel-browser/index.d.ts
  types/mixpanel-browser/mixpanel-browser-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45322 fix(sade): option & parse-lazy types
  types/sade/index.d.ts
  types/sade/sade-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45313 [@xstyled/system] Add alias "bg" and correct "StyleFunc" interface.
  types/xstyled__system/index.d.ts
  types/xstyled__system/xstyled__system-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#45266 types/stylus: Fix the Stylus.UrlOptions interface
  types/stylus/index.d.ts
  types/stylus/stylus-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45316 update(dotenv-webpack): minor version updates
  types/dotenv-webpack/dotenv-webpack-tests.ts
  types/dotenv-webpack/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45337 fix(es‑abstract): Make `Call` type parameters match `Reflect.apply`
  types/es-abstract/es2015.d.ts
  types/es-abstract/test/es2015.test.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Popular package

#45184 [mongoose] Solve TypeError when setting different currentTime
  types/mongoose/index.d.ts
  types/mongoose/test/mongoose.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45262 [chai-dom] Add tagName to Assertion interface.
  types/chai-dom/chai-dom-tests.ts
  types/chai-dom/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45271 update AWS Serverless type
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#45358 Fix React-Big-Calendar onRangeChange types
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#45362 [node] Added missing CORS headers to IncomingHttpHeaders
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/v10/http.d.ts
  types/node/v11/http.d.ts
  types/node/v11/test/http.ts
  types/node/v12/http.d.ts
  types/node/v12/test/http.ts
  types/node/v13/http.d.ts
  types/node/v13/test/http.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved

#45124 [@types/cytoscape] Added type definitions for Edge Endpoints
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
  types/cytoscape/tslint.json
Labels: Owner Approved, Perf: Same, The Travis CI build failed

#45224 [cache-manager-ioredis] Fixed type resolution for default export
  types/cache-manager-ioredis/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same

#45225 feat(psi): new type definition
  types/psi/index.d.ts
  types/psi/psi-tests.ts
  types/psi/tsconfig.json
  types/psi/tslint.json
Labels: New Definition

#45060 Fix polka-express compatibility types
  types/polka/index.d.ts
  types/polka/polka-tests.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Worse

#45223 Add Types for quicksettings
  types/quicksettings/index.d.ts
  types/quicksettings/quicksettings-tests.ts
  types/quicksettings/tsconfig.json
  types/quicksettings/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45221 created typings for react-portal-tooltip
  types/react-portal-tooltip/index.d.ts
  types/react-portal-tooltip/lib/Card.d.ts
  types/react-portal-tooltip/lib/StatefulToolTip.d.ts
  types/react-portal-tooltip/lib/ToolTip.d.ts
  types/react-portal-tooltip/react-portal-tooltip-tests.tsx
  types/react-portal-tooltip/tsconfig.json
  types/react-portal-tooltip/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#45109 ffi-napi: First argument to 'Library' can be null
  types/ffi-napi/ffi-napi-tests.ts
  types/ffi-napi/index.d.ts
Labels: Perf: Same, The Travis CI build failed

#45259 [k6] Update documentation. Add namepaces
  types/k6/crypto.d.ts
  types/k6/encoding.d.ts
  types/k6/global.d.ts
  types/k6/html.d.ts
  types/k6/http.d.ts
  types/k6/index.d.ts
  types/k6/k6-tests.ts
  types/k6/metrics.d.ts
  types/k6/options.d.ts
  types/k6/ws.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45369 [@types/recharts] Add `label` to `ReferenceAreaProps`
  types/recharts/index.d.ts
  types/recharts/recharts-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45363 Add types for ltijs
  types/ltijs/index.d.ts
  types/ltijs/lib/IdToken.d.ts
  types/ltijs/lib/Provider/Provider.d.ts
  types/ltijs/lib/Provider/Services/DeepLinking.d.ts
  types/ltijs/lib/Provider/Services/GradeService.d.ts
  types/ltijs/lib/Provider/Services/NamesAndRoles.d.ts
  types/ltijs/lib/Utils/Database.d.ts
  types/ltijs/lib/Utils/Platform.d.ts
  types/ltijs/ltijs-tests.ts
  types/ltijs/tsconfig.json
  types/ltijs/tslint.json
Labels: New Definition

#45081 Remove react-bootstrap@1
  types/react-bootstrap/v1/index.d.ts
  types/react-bootstrap/v1/tsconfig.json
  types/react-bootstrap/v1/tslint.json
Labels: Popular package, The CI failed, The Travis CI build failed

#45106 update(node): AsyncLocalStorage in v12.17
  types/node/v12/async_hooks.d.ts
  types/node/v12/node-tests.ts
  types/node/v12/test/async_hooks.ts
  types/node/v12/tsconfig.json
Labels: Author is Owner, Critical package, Owner Approved, Perf: Same, The Travis CI build failed

#45234 [jest] Add useFakeTimers implementation argument
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Critical package, Owner Approved, Perf: Same

#45240 allow FileCoverageData in CoverageMapData
  types/istanbul-lib-coverage/index.d.ts
  types/istanbul-lib-coverage/istanbul-lib-coverage-tests.ts
Labels: Critical package, Perf: Same

#45247 "mosca" Added 'ready' possibility to Server.on events
  types/mosca/index.d.ts
Labels: Owner Approved, Perf: Same

#45246 [howler] Significant type definition improvements
  types/howler/howler-tests.ts
  types/howler/index.d.ts
  types/howler/tslint.json
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#45190 react-boostrap-table-next: 2 additions, some corrections
  types/react-bootstrap-table-next/index.d.ts
Labels: Perf: Same

#45237 create new definitions for ajv-bsontype
  types/ajv-bsontype/ajv-bsontype-tests.ts
  types/ajv-bsontype/index.d.ts
  types/ajv-bsontype/package.json
  types/ajv-bsontype/tsconfig.json
  types/ajv-bsontype/tslint.json
Labels: New Definition

#44955 [json-schema] Added type definition for JSON object
  types/json-schema/index.d.ts
  types/json-schema/tslint.json
Labels: Critical package, Perf: Same

#44970 [ot] Update ot types
  types/ot/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto

#45368 Ember: add @ember/object/compat
  types/ember__object/OTHER_FILES.txt
  types/ember__object/compat.d.ts
  types/ember__object/test/compat.ts
  types/ember__object/tsconfig.json
Labels: Author is Owner, Other Approved, Owner Approved, Perf: Same, Popular package

#45265 Update IOptions interface to include enableArithAbort
  types/mssql/index.d.ts
Labels: Owner Approved, Perf: Same

#45107 [iost-contract] [node] Fixed typo: definnitions => definitions
  types/iost-contract/base.d.ts
  types/node/base.d.ts
  types/node/v10/base.d.ts
  types/node/v11/base.d.ts
  types/node/v12/base.d.ts
  types/node/v13/base.d.ts
Labels: Critical package, Owner Approved, Perf: Same, The Travis CI build failed

#44914 Add missing definitions
  types/forge-viewer/index.d.ts
Labels: Owner Approved, The Travis CI build failed

#45375 html-to-text: Add format: blockquote support
  types/html-to-text/html-to-text-tests.ts
  types/html-to-text/index.d.ts
  types/html-to-text/lib/formatter.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45241 [socketio-jwt] Make decodedPropertyName not required in socketio-jwt
  types/socketio-jwt/index.d.ts
  types/socketio-jwt/socketio-jwt-tests.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#45333 refactor(es‑abstract/scripts): Extract and simplify intrinsics data
  types/es-abstract/scripts/collect-intrinsics.ts
  types/es-abstract/scripts/intrinsics-data.ts
  types/es-abstract/test/GetIntrinsic.test.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Popular package

#44969 Remove cash, attempt 2
  notNeededPackages.json
  types/cash/index.d.ts
  types/cash/tsconfig.json
  types/cash/tslint.json
  types/materialize-css/common.d.ts
  types/materialize-css/index.d.ts
  types/materialize-css/package.json
  types/materialize-css/test/common.test.ts
  types/materialize-css/test/inputfields.test.ts
Labels: Other Approved, Perf: Better

#45393 bull: Add pause doNotWaitActive option, removeJobs, preventParsingData
  types/bull/bull-tests.tsx
  types/bull/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45345 [matrix-appservice-bridge] Add string type to BridgeOptions.registration
  types/matrix-appservice-bridge/index.d.ts
  types/matrix-appservice-bridge/matrix-appservice-bridge-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45379 fix(aws-lambda): approximateArrivalTimestamp should be number
  types/aws-lambda/test/kinesis-tests.ts
  types/aws-lambda/trigger/kinesis-firehose-transformation.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#44898 fix(react): Infer correct type in ElementRef
  types/react/index.d.ts
  types/react/test/index.ts
Labels: Author is Owner, Critical package, Perf: Same

#45348 Calidation generic type support
  types/calidation/calidation-tests.tsx
  types/calidation/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#45336 feat(aws-lambda): add generic type to cloud watch scheduled event
  types/aws-lambda/test/cloudwatch-tests.ts
  types/aws-lambda/trigger/cloudwatch-events.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45404 sanitize-html: textFilter signature missing tagName parameter
  types/sanitize-html/index.d.ts
  types/sanitize-html/sanitize-html-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45356 [@types/mongoose]: add Connection.useDb options
  types/mongoose/index.d.ts
  types/mongoose/test/mongoose.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#45424 VS Code 1.46.0 extension API (vscode.d.ts)
  types/vscode/index.d.ts
Labels: Perf: Same

#45415 Update relay network types
  types/relay-runtime/lib/network/RelayNetworkTypes.d.ts
Labels: Owner Approved, Perf: Same

#45430 update(sanitize-html): update defaults and options
  types/sanitize-html/index.d.ts
  types/sanitize-html/sanitize-html-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45432 Export Graphql Response types in relay-runtime
  types/relay-runtime/index.d.ts
Labels: Perf: Same

#45286 Update serverless index.d.ts with tags property
  types/serverless/index.d.ts
Labels: Owner Approved, Perf: Same

#45287 Add new types for ethjs-util
  types/ethjs-util/ethjs-util-tests.ts
  types/ethjs-util/index.d.ts
  types/ethjs-util/tsconfig.json
  types/ethjs-util/tslint.json
Labels: New Definition

#45290 updated knuddels-userapps-api
  types/knuddels-userapps-api/index.d.ts
Labels: Other Approved, Perf: Same

#45293 Fix the bargap and bargroupgap to match the spec
  types/plotly.js/index.d.ts
Labels: Owner Approved, Perf: Same

#45295 feat(webpack-shell-plugin): definition types
  types/webpack-shell-plugin/index.d.ts
  types/webpack-shell-plugin/tsconfig.json
  types/webpack-shell-plugin/tslint.json
  types/webpack-shell-plugin/webpack-shell-plugin-tests.ts
Labels: Maintainer Approved, Merge:Auto, New Definition

#45298 Update controller type for multiple swiper sync
  types/swiper/js/swiper.esm.d.ts
Labels: Owner Approved, Perf: Same, Popular package

#45212 WordPress Element: Remove types package
  notNeededPackages.json
  types/wordpress__block-editor/package.json
  types/wordpress__block-editor/tsconfig.json
  types/wordpress__blocks/package.json
  types/wordpress__blocks/tsconfig.json
  types/wordpress__components/package.json
  types/wordpress__components/tsconfig.json
  types/wordpress__compose/package.json
  types/wordpress__compose/tsconfig.json
  types/wordpress__edit-post/package.json
  types/wordpress__edit-post/tsconfig.json
  types/wordpress__editor/package.json
  types/wordpress__editor/tsconfig.json
  types/wordpress__element/create-interpolate-element.d.ts
  types/wordpress__element/index.d.ts
  types/wordpress__element/platform.d.ts
  types/wordpress__element/raw-html.d.ts
  types/wordpress__element/react-platform.d.ts
  types/wordpress__element/react.d.ts
  types/wordpress__element/serialize.d.ts
  types/wordpress__element/tsconfig.json
  types/wordpress__element/tslint.json
  types/wordpress__element/utils.d.ts
  types/wordpress__element/wordpress__element-tests.ts
  types/wordpress__media-utils/package.json
  types/wordpress__media-utils/tsconfig.json
  types/wordpress__plugins/package.json
  types/wordpress__plugins/tsconfig.json
Labels: Author is Owner, Owner Approved

#45309 [ioredis] Permit null for err in DNSLookupFunction callback signature
  types/ioredis/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package

#45308 [recharts] adjusted 'utcTime' to 'utc' according to rechats.js
  types/recharts/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#45417 Update ESLint types for version 7
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
  types/eslint/ts3.1/eslint-tests.ts
  types/eslint/ts3.1/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45446 Mapbox GL - Add rotation/pitch alignment methods to Marker
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Merge:Auto, Owner Approved, Popular package

#45428 [yup] Export Locale interfaces for augmentation
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45434 fix: `morgan` is not tightly coupled to `express`
  types/morgan/index.d.ts
  types/morgan/morgan-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#45451 Stripe-v3 StyleOptions update
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Merge:Auto, Owner Approved, Popular package

#45453 @sap/xsenv is on npm now
  types/sap__xsenv/index.d.ts
Labels: Perf: Same

#45233 [mapbox-gl] fix dtslint warnings
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Author is Owner, Other Approved, Perf: Same, Popular package

#45273 Update pubnub index.d.ts - HistoryMessage.meta entries should be any type
  types/pubnub/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#45130 [mapbox-gl] Add getters and setters for pitch min and max
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package, The Travis CI build failed

#44298 [@types/relay-runtime]: OperationAvailability v9.x.x
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
Labels: Perf: Same
