Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-02, with the labels that each got.

#42018 cookie-session: Add sameSite: "none" support
  types/cookie-session/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same

#41996 Adds DragSelect types
  types/dragselect/dragselect-tests.ts
  types/dragselect/index.d.ts
  types/dragselect/tsconfig.json
  types/dragselect/tslint.json
Labels: New Definition, Revision needed

#42024 [react-native] Fix Picker component definitions + test
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#42036 [webpack] Add RuntimeValue for DefinePlugin
  types/webpack/index.d.ts
  types/webpack/test/index.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#41561 feat: Add types for frappe-gantt
  types/frappe-gantt/frappe-gantt-tests.ts
  types/frappe-gantt/index.d.ts
  types/frappe-gantt/tsconfig.json
  types/frappe-gantt/tslint.json
Labels: New Definition, Revision needed

#42064 [ldapjs] Correct version for ldapjs type definitions
  types/ldapjs/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#41806 Relay runtime: add missing ClientID
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/store/ClientID.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42022 [@testing-library/jest-dom] Add new type for toHaveStyle matcher
  types/testing-library__jest-dom/index.d.ts
  types/testing-library__jest-dom/test/testing-library__jest-dom-global-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#42023 chart.js: Update ChartData to accept both Arrays and ReadonlyArrays
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41987 Add path for @testing-library/cypress/add-commands
  types/testing-library__cypress/OTHER_FILES.txt
  types/testing-library__cypress/add-commands.d.ts
  types/testing-library__cypress/testing-library__cypress-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same

#42037 [basic-auth] Add http2.Http2ServerRequest type to the auth() parameter
  types/basic-auth/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42020 [newrelic] Add missing methods for tracing & instrumenting loaded modules
  types/newrelic/index.d.ts
  types/newrelic/newrelic-tests.ts
Labels: Merge:Express, Owner Approved

#42035 [fluent-ffmpeg] Update Autopad parameters
  types/fluent-ffmpeg/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41973 signalr: make the second parameter of the Hub.Proxy.off method optional
  types/signalr/index.d.ts
  types/signalr/signalr-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42056 SuperAgent: Add missing disableTLSCerts method
  types/superagent/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42059 SuperAgent: Fix ResponseError
  types/superagent/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41940 [pngjs]: fix type for sync.read at pngjs
  types/pngjs/index.d.ts
  types/pngjs/pngjs-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42066 Add object type to the MJML package
  types/mjml/index.d.ts
  types/mjml/mjml-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42030 [braintree] Use discriminated union for WebhookNotifications
  types/braintree/braintree-tests.ts
  types/braintree/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41946 [@types/react-stripe-elements] Update createToken to accept BankAccountOptions as well
  types/react-stripe-elements/index.d.ts
  types/react-stripe-elements/react-stripe-elements-tests.tsx
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41878 [umzug] fix: support array of migrations as input
  types/umzug/index.d.ts
Labels: Perf: Same, Revision needed

#41830 [@types/plupload] Enable import
  types/plupload/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same, Revision needed

#41902 The getClientIp can return null
  types/request-ip/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#41913 @types/mailgen updated for mailgen v2.0.9 => ContentBody.table can now take type Array<Table>
  types/mailgen/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41889 feat(eslint): add errorOnUnmatchedPattern to CLIEngine Options
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
  types/eslint/ts3.1/eslint-tests.ts
  types/eslint/ts3.1/index.d.ts
Labels: Awaiting reviewer feedback, Other Approved, Perf: Same, Popular package

#41972 17.4.46 added
  types/ej.web.all/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41979 [jquery] Context can be a selector
  types/jquery/JQueryStatic.d.ts
  types/jquery/jquery-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#42091 [cesium] Add types for ground polyline primitive/geometry and label/billboard opts
  types/cesium/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#42058 Remove duplicate Facebook @types/fb package
  notNeededPackages.json
  types/fb/fb-tests.ts
  types/fb/index.d.ts
  types/fb/tsconfig.json
  types/fb/tslint.json
  types/ng-facebook/index.d.ts
  types/ng-facebook/ng-facebook-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42047 feat(connect-mongo): mark as not needed as of 3.1
  notNeededPackages.json
  types/connect-mongo/connect-mongo-tests.ts
  types/connect-mongo/index.d.ts
  types/connect-mongo/tsconfig.json
  types/connect-mongo/tslint.json
  types/passport.socketio/package.json
Labels: Merge:Express, Owner Approved, Perf: Same

#42065 [webpack] DefinePlugin recursive CodeValuePrimitive
  types/webpack/index.d.ts
  types/webpack/test/index.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42079 [@types/sodium-native] Add crypto_box_* constants
  types/sodium-native/index.d.ts
  types/sodium-native/sodium-native-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42060 Add forge.pki.publicKeyToRSAPublicKeyPem to node-forge
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42073 Allow other expected values to be nested in jasmine.objectContaining
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41926 fix(tabtab): Enable Prettier, TSLint and `strictNullChecks`
  types/tabtab/index.d.ts
  types/tabtab/tabtab-tests.ts
  types/tabtab/tsconfig.json
  types/tabtab/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40407 Update gapi.client.classroom types using new type generator
  types/gapi.client.classroom/gapi.client.classroom-tests.ts
  types/gapi.client.classroom/index.d.ts
  types/gapi.client.classroom/readme.md
  types/gapi.client.classroom/tsconfig.json
Labels: Perf: Worse, Revision needed

#41735 [heremaps] update to v 3.1 API
  types/heremaps/heremaps-tests.ts
  types/heremaps/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#40822 [yup] Added better definition for yup's SchemaDescription.fields
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Perf: Same, Popular package, Revision needed

#41909 [@types/wnumb] Update types to wNumb version 1.2.0
  types/nouislider/nouislider-tests.ts
  types/nouislider/v7/nouislider-tests.ts
  types/nouislider/v8/nouislider-tests.ts
  types/wnumb/index.d.ts
  types/wnumb/wnumb-tests.ts
Labels: Perf: Same, Revision needed

#42107 [plotly.js] add domain to layout.
  types/plotly.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#42113 [@Cesium] 1.66
  types/cesium/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#42102 [office-js, office-js-preview] PivotTableCollection description typo fixes
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#42017 Ember Data: add re-exports for new packages
  types/ember-data/test/store.ts
  types/ember-data/tsconfig.json
  types/ember-data__adapter/OTHER_FILES.txt
  types/ember-data__adapter/error.d.ts
  types/ember-data__adapter/index.d.ts
  types/ember-data__adapter/json-api.d.ts
  types/ember-data__adapter/rest.d.ts
  types/ember-data__adapter/test/error.ts
  types/ember-data__adapter/test/index.ts
  types/ember-data__adapter/test/json-api.ts
  types/ember-data__adapter/test/lib/assert.ts
  types/ember-data__adapter/test/rest.ts
  types/ember-data__adapter/tsconfig.json
  types/ember-data__adapter/tslint.json
  types/ember-data__model/index.d.ts
  types/ember-data__model/test/lib/assert.ts
  types/ember-data__model/test/model.ts
  types/ember-data__model/tsconfig.json
  types/ember-data__model/tslint.json
  types/ember-data__serializer/OTHER_FILES.txt
  types/ember-data__serializer/index.d.ts
  types/ember-data__serializer/json-api.d.ts
  types/ember-data__serializer/json.d.ts
  types/ember-data__serializer/rest.d.ts
  types/ember-data__serializer/test/index.ts
  types/ember-data__serializer/test/json-api.ts
  types/ember-data__serializer/test/json.ts
  types/ember-data__serializer/test/rest.ts
  types/ember-data__serializer/test/transform.ts
  types/ember-data__serializer/transform.d.ts
  types/ember-data__serializer/tsconfig.json
  types/ember-data__serializer/tslint.json
  types/ember-data__store/ember-data__store-tests.ts
  types/ember-data__store/index.d.ts
  types/ember-data__store/tsconfig.json
  types/ember-data__store/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, New Definition, Perf: Same

#42098 node-mailjet attachments array
  types/node-mailjet/index.d.ts
  types/node-mailjet/node-mailjet-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42096 binary-parser: update to 1.5.0
  types/binary-parser/binary-parser-tests.ts
  types/binary-parser/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42095 angular-material: Missing IPanelAnimation.duration
  types/angular-material/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same, Revision needed

#42110 Add definitions for migrate-mongo
  types/migrate-mongo/index.d.ts
  types/migrate-mongo/migrate-mongo-tests.ts
  types/migrate-mongo/tsconfig.json
  types/migrate-mongo/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42100 fix(carbon-components-react) Slider misses onChange override prop
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/Slider/Slider.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42082 feat: Add typings for math-random
  types/math-random/index.d.ts
  types/math-random/math-random-tests.ts
  types/math-random/tsconfig.json
  types/math-random/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42101 Added type definitions for cnpj
  types/cnpj/cnpj-tests.ts
  types/cnpj/index.d.ts
  types/cnpj/tsconfig.json
  types/cnpj/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42076 @chromecast-caf-receiver - Update LoggerLevel to ENUM
  types/chromecast-caf-receiver/cast.framework.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42099 fix(carbon-components-react) Tab missed disabled prop
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/Tab/Tab.d.ts
Labels: Owner Approved, Perf: Same, Revision needed

#42019 [chroma-js] Add `mode` param to `valid()`
  types/chroma-js/chroma-js-tests.ts
  types/chroma-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#42016 Fix focused typing to match onFocusChange
  types/react-dates/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#42007 Change SDP onClose type to expect date
  types/react-dates/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#41988 `json-file-plus`: fix types
  package.json
  types/json-file-plus/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Worse

#42061 Add definitions for smshelper
  types/smshelper/index.d.ts
  types/smshelper/smshelper-tests.ts
  types/smshelper/tsconfig.json
  types/smshelper/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#42052 added @types/react-native-background-downloader
  types/react-native-background-downloader/index.d.ts
  types/react-native-background-downloader/react-native-background-downloader-tests.tsx
  types/react-native-background-downloader/tsconfig.json
  types/react-native-background-downloader/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41807 Relay runtime: add a new 'log' interface
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/network/RelayNetworkLoggerTransaction.d.ts
  types/relay-runtime/lib/network/createRelayNetworkLogger.d.ts
  types/relay-runtime/lib/store/RelayModernEnvironment.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Perf: Same, Revision needed

#42147 chore(package): Remove unnecessary dependencies
  package.json
Labels: Other Approved, Unowned

#42160 Add period to LibratoConfig for librato-node
  types/librato-node/index.d.ts
  types/librato-node/librato-node-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42161 [pouchdb-find] Add missing field to PouchDB.Find.FindResponse
  types/pouchdb-find/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42146 [SuperAgent] Fix Response.error type
  types/superagent/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42029 feat(multer): refine filter function callback
  types/multer/index.d.ts
  types/multer/multer-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42117 Bump ts-toolbelt to ^6.1.11
  types/ramda/package.json
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42123 fix(pino): Add missing params in PrettyOptions
  types/pino/index.d.ts
  types/pino/pino-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42097 fix(carbon-components-react) TooltipDefinition missed some props
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/TooltipDefinition/TooltipDefinition.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#42135 ssh2-sftp-client: fix get method dest parameter
  types/ssh2-sftp-client/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42083 @types/vast-client: add missing track() method to VASTTracker
  types/vast-client/index.d.ts
  types/vast-client/vast-client-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#42128 fix(carbon-components-react) Updated DataTableCustomSelectionProps accordingly to the Element's props
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/DataTable/DataTable.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42127 later - next() can return single date
  types/later/index.d.ts
  types/later/later-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42103 fix(jest): issue #42067
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#42075 [redux-form] Add additional params to ValidateCallback type
  types/redux-form/lib/reduxForm.d.ts
  types/redux-form/redux-form-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42104 [react-datepicker] Add new props
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same, Popular package

#42139 deleting gridstack since lib has Typescript definition
  notNeededPackages.json
  types/gridstack/gridstack-tests.ts
  types/gridstack/index.d.ts
  types/gridstack/tsconfig.json
  types/gridstack/tslint.json
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#42162 [contentstack] Update contentstack to include Assets and missing definitions
  types/contentstack/contentstack-tests.ts
  types/contentstack/index.d.ts
Labels: Author is Owner, Merge:Express, Other Approved, Perf: Same

#42166 [@types/hapi-pino] Update hapi-pino to 6.4
  types/hapi-pino/hapi-pino-tests.ts
  types/hapi-pino/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#42132 [ioredis] add missing `unlink` to Pipeline
  types/ioredis/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41989 feat(karma-jasmine): update to version 3.1
  types/karma-jasmine/index.d.ts
  types/karma-jasmine/karma-jasmine-tests.ts
  types/karma-jasmine/tsconfig.json
  types/karma-jasmine/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#42025 feat(multer): pre-v1 dead code removal
  types/multer/index.d.ts
  types/multer/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#42169 VS Code 1.42.0 Extension API
  types/vscode/index.d.ts
Labels: Perf: Same

#42124 [plotly.js] - add title to trace.
  types/plotly.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#42109 Add graphite module declarations
  types/graphite/graphite-tests.ts
  types/graphite/index.d.ts
  types/graphite/tsconfig.json
  types/graphite/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42041 fix(bcrypt-nodejs): allow null as hash progress callback
  types/bcrypt-nodejs/bcrypt-nodejs-tests.ts
  types/bcrypt-nodejs/index.d.ts
  types/bcrypt-nodejs/tsconfig.json
  types/bcrypt-nodejs/tslint.json
Labels: Perf: Same, Unowned

#42050 Added type definitions for shevyjs
  types/shevyjs/constants/index.d.ts
  types/shevyjs/index.d.ts
  types/shevyjs/shevyjs-tests.ts
  types/shevyjs/tsconfig.json
  types/shevyjs/tslint.json
  types/shevyjs/types.d.ts
  types/shevyjs/utils/index.d.ts
Labels: Awaiting reviewer feedback, New Definition

#42057 added @types/react-native-video-player
  types/react-native-video-player/index.d.ts
  types/react-native-video-player/react-native-video-player-tests.tsx
  types/react-native-video-player/tsconfig.json
  types/react-native-video-player/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42153 feat(nanotimer): complete definition
  types/nanotimer/index.d.ts
  types/nanotimer/nanotimer-tests.ts
  types/nanotimer/tsconfig.json
  types/nanotimer/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42174 react-native: add sendIntent to LinkingStatic
  types/react-native/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#42189 Fix a type in mongoose tests
  types/mongoose/mongoose-tests.ts
Labels: Awaiting reviewer feedback, Popular package

#42121 Change folder name to google__markerclustererplus to match scoped package
  types/google__markerclustererplus/google__markerclustererplus-tests.ts
  types/google__markerclustererplus/index.d.ts
  types/google__markerclustererplus/tsconfig.json
  types/google__markerclustererplus/tslint.json
Labels: Other Approved, Unowned

#42140 [emscripten] Delete Math interface and fix locateFile()
  types/emscripten/emscripten-tests.ts
  types/emscripten/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#42039 Added @types/vndb
  types/vndb/index.d.ts
  types/vndb/tsconfig.json
  types/vndb/tslint.json
  types/vndb/vndb-tests.ts
Labels: New Definition, Revision needed

#42138 Add LJHarb to LJHarb's packages
  types/array.prototype.flat/index.d.ts
  types/array.prototype.flatmap/index.d.ts
  types/define-properties/index.d.ts
  types/enzyme-adapter-react-15.4/index.d.ts
  types/enzyme-adapter-react-15/index.d.ts
  types/enzyme-adapter-react-16/index.d.ts
  types/enzyme/index.d.ts
  types/function-bind/index.d.ts
  types/internal-slot/index.d.ts
  types/is-date-object/index.d.ts
  types/is-generator-function/index.d.ts
  types/is-object/index.d.ts
  types/json-file-plus/index.d.ts
  types/object-inspect/index.d.ts
  types/object-keys/index.d.ts
  types/object.getownpropertydescriptors/index.d.ts
  types/promise.allsettled/index.d.ts
  types/promise.prototype.finally/index.d.ts
  types/qs/index.d.ts
  types/tape/index.d.ts
  types/util.promisify/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42044 Re-introduce prematurely deprecated rdflib typings
  notNeededPackages.json
  types/rdflib/index.d.ts
  types/rdflib/rdflib-tests.ts
  types/rdflib/tsconfig.json
  types/rdflib/tslint.json
Labels: New Definition, Revision needed

#42078 added 'Clarinet'
  types/clarinet/clarinet-tests.ts
  types/clarinet/index.d.ts
  types/clarinet/tsconfig.json
  types/clarinet/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42171 [@catho/quantum] Fix componets event handlers types
  types/catho__quantum/components/Alert/index.d.ts
  types/catho__quantum/components/Button/index.d.ts
  types/catho__quantum/components/Checkbox/index.d.ts
  types/catho__quantum/components/Dropdown/index.d.ts
  types/catho__quantum/components/Form/index.d.ts
  types/catho__quantum/components/Input/index.d.ts
  types/catho__quantum/components/Modal/index.d.ts
  types/catho__quantum/components/Pagination/index.d.ts
  types/catho__quantum/components/RadioGroup/index.d.ts
  types/catho__quantum/components/RangeSlider/index.d.ts
  types/catho__quantum/components/SnackBar/index.d.ts
  types/catho__quantum/components/Tag/index.d.ts
  types/catho__quantum/components/TextArea/index.d.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#42187 fix(carbon-components-react) Added ref for inputs and textareas
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/NumberInput/NumberInput.d.ts
  types/carbon-components-react/lib/components/TextArea/TextArea.d.ts
  types/carbon-components-react/lib/components/TextInput/ControlledPasswordInput.d.ts
  types/carbon-components-react/lib/components/TextInput/PasswordInput.d.ts
  types/carbon-components-react/lib/components/TextInput/props.d.ts
  types/carbon-components-react/typings/shared.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42152 Relay runtime: fix Store constructor parameters
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/store/RelayModernStore.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#42179 [jwplayer] Add missing method signatures for JWPlayer.off()
  types/jwplayer/index.d.ts
Labels: Merge:Express, Owner Approved

#42183 Added 'console group' methods to type Console in react-native
  types/react-native/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42155 [rsocket-core] Add rsocket error types
  types/rsocket-core/RSocketFrame.d.ts
Labels: Merge:Express, Owner Approved

#42178 Update tooltip.d.ts
  types/echarts/options/tooltip.d.ts
Labels: Merge:Express, Owner Approved

#42125 fix(carbon-components-react) TileGroup's onChange signature: all arguments are mandatory
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/TileGroup/TileGroup.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42165 fix(google__maps): sessiontoken in PlaceAutocomplete is optional
  types/google__maps/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42177 Updated tests and Options interface to match js code.
  types/ffmpeg.js/ffmpeg-mp4/index.d.ts
  types/ffmpeg.js/ffmpeg-webm/index.d.ts
  types/ffmpeg.js/test/ffmpeg.js-direct-tests.ts
  types/ffmpeg.js/test/ffmpeg.js-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#42184 [plotly.js] - add pad to plotmarker.
  types/plotly.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#42195 [office-js] [office-js-preview] (Outlook) Link to OM in Item description
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#42167 Update react-beautiful-dnd DragDropContextProps to include sensors
  types/react-beautiful-dnd/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42188 feat(object.getownpropertydescriptors): Add missing files
  types/object.getownpropertydescriptors/implementation.d.ts
  types/object.getownpropertydescriptors/index.d.ts
  types/object.getownpropertydescriptors/object.getownpropertydescriptors-tests.ts
  types/object.getownpropertydescriptors/polyfill.d.ts
  types/object.getownpropertydescriptors/shim.d.ts
  types/object.getownpropertydescriptors/tsconfig.json
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same, Popular package

#42048 feat(errorhandler): update to 1.5 version
  types/errorhandler/errorhandler-tests.ts
  types/errorhandler/index.d.ts
  types/errorhandler/tsconfig.json
  types/errorhandler/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#42045 feat(compression): amend module definition and bump to 1.7
  types/compression/compression-tests.ts
  types/compression/index.d.ts
  types/compression/tsconfig.json
  types/compression/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#42040 feat(express-fileupload): update definition details
  types/express-fileupload/express-fileupload-tests.ts
  types/express-fileupload/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Better

#42186 [redis-info] Add base types
  types/redis-info/index.d.ts
  types/redis-info/redis-info-tests.ts
  types/redis-info/tsconfig.json
  types/redis-info/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42191 Revert "chart.js: Update ChartData to accept both Arrays and ReadonlyArrays"
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#42198 atom: Add nightly release channel
  types/atom/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42089 fix(carbon-components-react) Dropdown itemToElement prop should be ReactNode
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/lib/components/Dropdown/Dropdown.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#42219 [webpack] Fix type for Stats.ToJsonOutput['assetsByChunkName']
  types/webpack/index.d.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#42230 fix(intercom-client): fix find methods
  types/intercom-client/index.d.ts
Labels: Perf: Same

#42218 [electron-load-devtool] Update to v1.2
  types/electron-load-devtool/electron-load-devtool-tests.ts
  types/electron-load-devtool/index.d.ts
Labels: Awaiting reviewer feedback, Other Approved, Perf: Same

#42225 [arangodb] Add ttl index type
  types/arangodb/index.d.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#42211 update @types/sketchapp: add optional types
  types/sketchapp/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#42203 Export types and interfaces
  types/react-native-background-downloader/index.d.ts
  types/react-native-background-downloader/react-native-background-downloader-tests.tsx
Labels: Author is Owner, Merge:Express, Perf: Same

#42173 [parse/node] Add missing types for encrypting users
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42180 Fixing react-mic onStop event type
  types/react-mic/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42168 Updated types for ReCaptcha and added loadReCaptcha function
  types/react-recaptcha-v3/index.d.ts
  types/react-recaptcha-v3/react-recaptcha-v3-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same

#42207 fix(theme-ui): add missing FlexProps type
  types/theme-ui__components/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42208 feat(browserslist): update to version 4.8
  types/browserslist/browserslist-tests.ts
  types/browserslist/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42216 mongodb: fix typo in the comment for auth option
  types/mongodb/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42215 Add ChildNode to union in fireEvent `element` arg
  types/testing-library__dom/events.d.ts
  types/testing-library__dom/testing-library__dom-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42090 [react-table] remove UseFiltersOptions
  types/react-table/Readme.md
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42227 fix(chrome): add `pendingUrl` Tab property. Fixes #42224
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42108 feat(mkdirp): upgrade mkdirp types to 1.0
  types/mkdirp-promise/index.d.ts
  types/mkdirp-promise/mkdirp-promise-tests.ts
  types/mkdirp-promise/tsconfig.json
  types/mkdirp-promise/tslint.json
  types/mkdirp/index.d.ts
  types/mkdirp/mkdirp-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#42209 [redis] Fix return type of get() to return string | null
  types/redis/index.d.ts
  types/redis/redis-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42232 Add support for silent flag in notifyjs
  types/notifyjs/index.d.ts
  types/notifyjs/notifyjs-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42197 New property "registerChild" for the react-virtualized package was added about a week ago
  types/react-virtualized/dist/es/CellMeasurer.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42236 @pusher/chatkit-client: Fix sending files/attachments and multipart messages
  types/pusher__chatkit-client/currentuser.d.ts
  types/pusher__chatkit-client/message.d.ts
  types/pusher__chatkit-client/pusher__chatkit-client-tests.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#42156 fix(mongoose): add arrayFilters in update operations
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
  types/mongoose/v4/index.d.ts
  types/mongoose/v4/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42245 [braintree] Adds typing for PaymentMethod webhook
  types/braintree/braintree-tests.ts
  types/braintree/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#42116 fix(react-table): [v6] remove `hideFilter` prop
  types/react-table/v6/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#42248 Definitions to "pdf-image" package
  types/pdf-image/index.d.ts
  types/pdf-image/pdf-image-tests.ts
  types/pdf-image/tsconfig.json
  types/pdf-image/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42242 feat(markdown-magic): type definitions for version 1.0
  types/markdown-magic/index.d.ts
  types/markdown-magic/markdown-magic-tests.ts
  types/markdown-magic/tsconfig.json
  types/markdown-magic/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42237 feat: Add types for array-initial
  types/array-initial/array-initial-tests.ts
  types/array-initial/index.d.ts
  types/array-initial/tsconfig.json
  types/array-initial/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42234 Add type definitions for buffer-split
  types/buffer-split/buffer-split-tests.ts
  types/buffer-split/index.d.ts
  types/buffer-split/tsconfig.json
  types/buffer-split/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42222 Added react-typing-animation
  types/react-typing-animation/index.d.ts
  types/react-typing-animation/react-typing-animation-tests.tsx
  types/react-typing-animation/tsconfig.json
  types/react-typing-animation/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42217 Add type definitions for docker-events
  types/docker-events/docker-events-tests.ts
  types/docker-events/index.d.ts
  types/docker-events/tsconfig.json
  types/docker-events/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42214 feat(karma-browserstack-launcher): version 1.5
  types/karma-browserstack-launcher/index.d.ts
  types/karma-browserstack-launcher/karma-browserstack-launcher-tests.ts
  types/karma-browserstack-launcher/tsconfig.json
  types/karma-browserstack-launcher/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42158 feat(react-native-appsflyer): complete definition
  types/react-native-appsflyer/index.d.ts
  types/react-native-appsflyer/react-native-appsflyer-tests.ts
  types/react-native-appsflyer/tsconfig.json
  types/react-native-appsflyer/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#42142 [angular-aria] Add types for AngularJS $aria service
  types/angular-aria/angular-aria-tests.ts
  types/angular-aria/index.d.ts
  types/angular-aria/tsconfig.json
  types/angular-aria/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41751 Update RTCPeerConnection.d.ts
  types/webrtc/RTCPeerConnection.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41978 [jsonld] Fix some types
  types/jsonld/index.d.ts
  types/jsonld/jsonld-spec.d.ts
  types/jsonld/jsonld-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same
