Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-12, with the labels that each got.

#49343 fix(youtube): export enum instead of export const enum
  types/youtube/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49102 Improve types of json-server router
  types/json-server/index.d.ts
  types/json-server/json-server-tests.ts
Labels: Maintainer Approved, Perf: Worse, Self Merge

#49823 [codecs] initial type definitions
  types/codecs/codecs-tests.ts
  types/codecs/index.d.ts
  types/codecs/tsconfig.json
  types/codecs/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#49831 Revert "🤖 Merge PR #49581 [tweenjs] - Add inference of Tween target t…
  types/tweenjs/index.d.ts
  types/tweenjs/tweenjs-tests.ts
Labels: Author is Owner, Edits Owners, Owner Approved, Perf: Same, Self Merge

#49662 Add types for basic use case of H.map.provider.LocalObjectProvider in heremaps package
  types/heremaps/heremaps-tests.ts
  types/heremaps/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49759 create @types/customize-cra
  types/customize-cra/customize-cra-tests.ts
  types/customize-cra/index.d.ts
  types/customize-cra/src/babel.d.ts
  types/customize-cra/src/core.d.ts
  types/customize-cra/src/webpack.d.ts
  types/customize-cra/tsconfig.json
  types/customize-cra/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#49771 [office-js] [office-js-preview] (Outlook) Note RoamingSettings intera…
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved, Perf: Same, Self Merge, Untested Change

#49818 Update equalTo: Definitions for Parse Platform to support Array Types
  types/parse/index.d.ts
  types/parse/parse-tests.ts
  types/parse/ts3.6/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#47020 [@types/jest] Infer matcher types based on expect
  types/jest-in-case/jest-in-case-tests.ts
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Critical package, Edits multiple packages, Perf: Same, Revision needed

#49826 [match-sorter] Remove match-sorter types
  notNeededPackages.json
  types/match-sorter/index.d.ts
  types/match-sorter/match-sorter-tests.ts
  types/match-sorter/tsconfig.json
  types/match-sorter/tslint.json
Labels: Config Edit, Edits Infrastructure, Maintainer Approved, Owner Approved, Self Merge

#49125 update(webpack-sources): v2.1 updates
  types/webpack-sources/index.d.ts
  types/webpack-sources/lib/index.d.ts
  types/webpack-sources/webpack-sources-tests.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Perf: Same, Self Merge

#49850 feat(is-core-module): new definition
  types/is-core-module/index.d.ts
  types/is-core-module/is-core-module-tests.ts
  types/is-core-module/tsconfig.json
  types/is-core-module/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#49877 fix(validate-npm-package-name): backward compatibility
  types/validate-npm-package-name/index.d.ts
  types/validate-npm-package-name/validate-npm-package-name-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#49854 update(registry-auth-token): v4.2 update
  types/registry-auth-token/index.d.ts
  types/registry-auth-token/registry-auth-token-tests.ts
  types/registry-auth-token/registry-url.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#49862 [bootstrap] fix options for bootstrap's tooltip/popover
  types/bootstrap/bootstrap-tests.ts
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#49548 feat(@types/gulp-sourcemaps): updated modules typings
  types/gulp-sourcemaps/gulp-sourcemaps-tests.ts
  types/gulp-sourcemaps/index.d.ts
Labels: Edits Owners, No Other Owners, Perf: Same, Unreviewed

#48155 update(favicons): version 6.*
  types/favicons/favicons-tests.ts
  types/favicons/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge, Unreviewed

#49673 react-select - Added isMulti generic to react-select for conditional types
  types/react-select/src/Async.d.ts
  types/react-select/src/AsyncCreatable.d.ts
  types/react-select/src/Creatable.d.ts
  types/react-select/src/Select.d.ts
  types/react-select/src/animated/Placeholder.d.ts
  types/react-select/src/animated/ValueContainer.d.ts
  types/react-select/src/animated/index.d.ts
  types/react-select/src/components/Control.d.ts
  types/react-select/src/components/Group.d.ts
  types/react-select/src/components/Menu.d.ts
  types/react-select/src/components/MultiValue.d.ts
  types/react-select/src/components/Option.d.ts
  types/react-select/src/components/Placeholder.d.ts
  types/react-select/src/components/SingleValue.d.ts
  types/react-select/src/components/containers.d.ts
  types/react-select/src/components/index.d.ts
  types/react-select/src/components/indicators.d.ts
  types/react-select/src/stateManager.d.ts
  types/react-select/src/styles.d.ts
  types/react-select/src/types.d.ts
  types/react-select/src/utils.d.ts
  types/react-select/test/Header.tsx
  types/react-select/test/Placeholder.tsx
  types/react-select/test/examples/AnimatedMulti.tsx
  types/react-select/test/examples/CustomIndicatorsContainer.tsx
Labels: Owner Approved, Perf: Worse, Popular package, Self Merge

#49840 Add type definitions for videojs-hotkeys
  types/videojs-hotkeys/index.d.ts
  types/videojs-hotkeys/tsconfig.json
  types/videojs-hotkeys/tslint.json
  types/videojs-hotkeys/videojs-hotkeys-tests.ts
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#49858 [mercadopago] fix: add missing properties to interfaces
  types/mercadopago/models/customers/create-payload.model.d.ts
  types/mercadopago/models/preferences/create-payload.model.d.ts
  types/mercadopago/shared/address.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Other Approved, Perf: Same, Self Merge, Untested Change

#47221 Allow extra properties in when calling `createTag`.
  types/select2/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49874 Orbit ui react components
  types/orbit-ui__react-components/index.d.ts
  types/orbit-ui__react-components/orbit-ui__react-components-tests.tsx
  types/orbit-ui__react-components/package.json
  types/orbit-ui__react-components/tsconfig.json
  types/orbit-ui__react-components/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#49708 [@testing-library/jasmine-dom] Allow all elements
  types/testing-library__jasmine-dom/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#49811 Update index.d.ts
  types/react-native-audio/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#49865 Create a new package '@adeira/murmur-hash'
  types/adeira__murmur-hash/adeira__murmur-hash-tests.ts
  types/adeira__murmur-hash/index.d.ts
  types/adeira__murmur-hash/tsconfig.json
  types/adeira__murmur-hash/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#49321 fix(serve-favicon): compatibility for old import syntax
  types/serve-favicon/index.d.ts
  types/serve-favicon/serve-favicon-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#48783 [twitter-text] Update type definitions for v3.1.0
  types/twitter-text/index.d.ts
  types/twitter-text/tslint.json
  types/twitter-text/twitter-text-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#49885 Use ReadonlyArray for InitOptions["providers"] in `next-auth`
  types/next-auth/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49895 Add missing props on MultiPeriodMarking
  types/react-native-calendars/index.d.ts
  types/react-native-calendars/react-native-calendars-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge

#49866 feat: Add `is‑arguments`
  types/is-arguments/index.d.ts
  types/is-arguments/is-arguments-tests.ts
  types/is-arguments/tsconfig.json
  types/is-arguments/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#49247 [imap] improve typing for config.tlsOptions
  types/imap/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49624 browser-or-node: Adds type for isJsDom
  types/browser-or-node/browser-or-node-tests.ts
  types/browser-or-node/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49832 More specific FHIR codes (types/fhir)
  types/fhir/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49884 added LocalStorage class to Autodesk.Viewing.Private
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49289 [mathjs] Fix concat interface argument types
  types/mathjs/index.d.ts
  types/mathjs/mathjs-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#49886 @hapi__yar allow CookieOptions.isSameSite to be 'None'
  types/hapi__yar/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#49228 Update index.d.ts
  types/qiniu-js/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#48873 [extensible-duck] Export Duck class as default to match library
  types/extensible-duck/extensible-duck-tests.ts
  types/extensible-duck/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#49604 [eslint] accept string not string[] for ignorePattern option of capitalized-comments rule
  types/eslint/OTHER_FILES.txt
  types/eslint/eslint-tests.ts
  types/eslint/rules/stylistic-issues.d.ts
Labels: Config Edit, Owner Approved, Perf: Same, Popular package, Self Merge

#49853 Add paramater to field() and siblingField()
  types/simpl-schema/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49789 Updated typings for react-bootstrap-typeahead
  types/react-bootstrap-typeahead/index.d.ts
  types/react-bootstrap-typeahead/react-bootstrap-typeahead-tests.tsx
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#49337 fix(svg-path-parser): use discriminated union for Command
  types/svg-path-parser/index.d.ts
  types/svg-path-parser/svg-path-parser-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#48902 Added type declaration for isDate function for Validator package
  types/validator/es/lib/isDate.d.ts
  types/validator/index.d.ts
  types/validator/lib/isDate.d.ts
  types/validator/validator-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#48677 cookie-session: Make session property optional again
  types/cookie-session/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49797 [google.visualization] Add typing for load options
  types/google.visualization/google.visualization-tests.ts
  types/google.visualization/index.d.ts
Labels: Author is Owner, Other Approved, Perf: Same, Self Merge

#49086 [amplitude-js] Update comment to latest SDK version
  types/amplitude-js/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49848 Fix bounding box type definition
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Author is Owner, Edits Owners, Other Approved, Perf: Same, Self Merge

#49890 create typings for tiny-json-http module
  types/tiny-json-http/index.d.ts
  types/tiny-json-http/tiny-json-http-tests.ts
  types/tiny-json-http/tsconfig.json
  types/tiny-json-http/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#49839 Add types for mongoose-aggregate-paginate-v2 (modified from mongoose-paginate-v2)
  types/mongoose-aggregate-paginate-v2/index.d.ts
  types/mongoose-aggregate-paginate-v2/mongoose-aggregate-paginate-v2-tests.ts
  types/mongoose-aggregate-paginate-v2/tsconfig.json
  types/mongoose-aggregate-paginate-v2/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#49851 Fix the type of `_`
  types/yargs/index.d.ts
  types/yargs/yargs-tests.ts
Labels: Critical package, Owner Approved, Perf: Same

#49904 [office-js, office-js-preview] Update ContentControl.placeholderText to note Word for the web support
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved, Untested Change

#48724 feat(mongodb): deprecate createCollection options
  types/mongodb/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49357 Update Cytoscape typings
  types/cytoscape/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#47583 update(compression-webpack-plugin): v6 updates
  types/compression-webpack-plugin/compression-webpack-plugin-tests.ts
  types/compression-webpack-plugin/index.d.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Self Merge

#49806 update(page): version 1.11
  types/page/index.d.ts
  types/page/page-tests.ts
  types/page/tsconfig.json
  types/page/tslint.json
Labels: Config Edit, Edits Owners, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#49327 update(svg-spritemap-webpack-plugin): v3.7 updates
  types/svg-spritemap-webpack-plugin/index.d.ts
  types/svg-spritemap-webpack-plugin/svg-spritemap-webpack-plugin-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#49361 update(event-hooks-webpack-plugin): v2.2 update
  types/event-hooks-webpack-plugin/event-hooks-webpack-plugin-tests.ts
  types/event-hooks-webpack-plugin/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#49298 update(svg-spritemap-webpack-plugin): v3.6 updates
  types/svg-spritemap-webpack-plugin/index.d.ts
  types/svg-spritemap-webpack-plugin/svg-spritemap-webpack-plugin-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#49342 update(karma-firefox-luancher): v2.1 updates
  types/karma-firefox-launcher/index.d.ts
  types/karma-firefox-launcher/karma-firefox-launcher-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#48941 fix: typo in navermaps typings
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#49907 [braintree] Make TransactionRequestSource a type
  types/braintree/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#49115 [twilio-video] Adds priority setting for Local Track Publications
  types/twilio-video/index.d.ts
  types/twilio-video/twilio-video-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#49339 [honeybadger] add context property
  types/honeybadger/honeybadger-tests.ts
  types/honeybadger/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#49274 Added declaration for the writeFile function
  types/ssh2-streams/index.d.ts
  types/ssh2-streams/ssh2-streams-tests.ts
  types/ssh2/index.d.ts
Labels: Edits Owners, Edits multiple packages, Other Approved, Perf: Same, Popular package

#49377 Update agenda type with agenda 3.0.1
  types/agenda/agenda-tests.ts
  types/agenda/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#49898 Remove releaseConnection from Pool interface
  types/mysql/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#47603 plotly.js - Add cliponaxis to PlotData, allow multiple button types for modeBarButtons
  types/plotly.js/index.d.ts
  types/plotly.js/lib/traces/box.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Popular package, Self Merge

#49320 chore(pvutils): remove references to dom lib
  types/pvutils/index.d.ts
  types/pvutils/pvutils-tests.ts
  types/pvutils/tsconfig.json
Labels: Maintainer Approved, Perf: Better, Popular package, Self Merge

#49910 [react-datepicker] Change previous/nextMonthButtonLabel to include Re…
  types/react-datepicker/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49520 vhost: fix return type
  types/vhost/index.d.ts
  types/vhost/vhost-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#49014 feat(blueimp-load-image): Add promise style usage
  types/blueimp-load-image/blueimp-load-image-tests.ts
  types/blueimp-load-image/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#49911 @types/qunit: add strict boolean true/false assertion types
  types/qunit/index.d.ts
  types/qunit/test/global-test.ts
Labels: Other Approved, Owner Approved, Perf: Same, Self Merge

#48204 [@types/serverless] MSK support for lambda events for package serverless v2.3.0, update types to v1.79.0
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#49149 elasticsearch: add more 'includeTypeName' parameters
  types/elasticsearch/elasticsearch-tests.ts
  types/elasticsearch/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge

#48295 [@types/multimap] Add optional generics and fix some types
  types/multimap/index.d.ts
  types/multimap/multimap-tests.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#49921 [mobile-messaging-cordova] Lists and date time for customAttributes, in-app chat, notification primary button actions
  types/mobile-messaging-cordova/index.d.ts
  types/mobile-messaging-cordova/mobile-messaging-cordova-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49412 update(yup): Add missing locale types
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge

#49678 [@types/chai-spies] Fix signature on spy.on and sandbox.on to allow for any number of arguments
  types/chai-spies/chai-spies-tests.ts
  types/chai-spies/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49828 [use-deep-compare-effect] Remove use-deep-compare-effect types
  notNeededPackages.json
  types/use-deep-compare-effect/index.d.ts
  types/use-deep-compare-effect/tsconfig.json
  types/use-deep-compare-effect/tslint.json
  types/use-deep-compare-effect/use-deep-compare-effect-tests.ts
Labels: Config Edit, Edits Infrastructure, Maintainer Approved, Other Approved, Owner Approved, Popular package, Self Merge

#49297 react-bootstrap: Add bsClass prop definition to Panel
  types/react-bootstrap/lib/Panel.d.ts
  types/react-bootstrap/test/react-bootstrap-tests.tsx
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#49925 Changed faker.address.nearByGPSCoordinate() coordinate parameter type from string to ReadOnlyArray<string>
  types/faker/faker-tests.ts
  types/faker/index.d.ts
Labels: Owner Approved, Popular package, Self Merge

#49427 Update typings for console-stamp to v0.2.9
  types/console-stamp/console-stamp-tests.ts
  types/console-stamp/index.d.ts
  types/console-stamp/tsconfig.json
Labels: Maintainer Approved, Perf: Same, Self Merge

#49923 [undertaker] first param of task function callback is Error | null, not any
  types/undertaker/index.d.ts
  types/undertaker/undertaker-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#49686 [README] Create a package.json section
  README.cn.md
  README.es.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
Labels: Edits Infrastructure, Multiple Languages

#49922 Mongoose: Added flag for Optimistic Concurrency option in SchemaType
  types/mongoose/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49905 Create typings for @dsinjs/binary-tree
  types/dsinjs__binary-tree/btree.d.ts
  types/dsinjs__binary-tree/btreenode.d.ts
  types/dsinjs__binary-tree/index.d.ts
  types/dsinjs__binary-tree/tsconfig.json
  types/dsinjs__binary-tree/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge, Untested Change

#49145 [yandex-maps]: improve panorama namespace
  types/yandex-maps/index.d.ts
  types/yandex-maps/yandex-maps-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#49929 [office-js] [office-js-preview] (Outlook) Note Context host and platf…
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved, Untested Change

#49531 html-to-text: upgrade to v6.0
  types/html-to-text/html-to-text-tests.ts
  types/html-to-text/index.d.ts
  types/html-to-text/lib/block-text-builder.d.ts
  types/html-to-text/lib/formatter.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#49889 [google.analytics] Added two missing cookie fields
  types/google.analytics/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49250 Update `marked` type definition to remove first parameter of `walkTokens` field from `MarkOptions`
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#49252 [marked] add `dryrun` options to `Slugger.slug`
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#49931 [gestalt] Updated with new componet flex props. DatePicker is still not added.
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Author is Owner, Owner Approved, Self Merge

#49735 update(clear): options fix
  types/clear/clear-tests.ts
  types/clear/index.d.ts
  types/clear/tsconfig.json
Labels: Owner Approved, Perf: Same, Self Merge, Unmerged

#49163 update(serialize-javascript): update to v5 and minor fixes
  types/serialize-javascript/index.d.ts
  types/serialize-javascript/serialize-javascript-tests.ts
Labels: Edits Owners, Maintainer Approved, Other Approved, Perf: Same, Popular package, Self Merge

#49926 Fix conflicting PaginateOptions in mongoose-paginate-v2 and mongoos…
  types/mongoose-aggregate-paginate-v2/index.d.ts
  types/mongoose-paginate-v2/index.d.ts
Labels: Edits multiple packages, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#47811 [i18n] Add class for I18n (support i18n version 0.12.0)
  types/i18n/i18n-tests.ts
  types/i18n/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#49410 [@types/puppeteer] Fix types for errors namespace
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Popular package, Self Merge

#49916 add(ooura): add new definition for npm package ooura (fft-library)
  types/ooura/index.d.ts
  types/ooura/ooura-tests.ts
  types/ooura/tsconfig.json
  types/ooura/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#49810 [streamx] initial type definitions
  types/streamx/index.d.ts
  types/streamx/test/failing-tests.ts
  types/streamx/test/passing-tests.ts
  types/streamx/tsconfig.json
  types/streamx/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#49420 [less] Add types for FileManager
  types/less/index.d.ts
  types/less/less-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#49312 [select2] Added missing parameter for templateSelection
  types/select2/index.d.ts
  types/select2/select2-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#49932 [uikit] Delete README.md
  types/uikit/README.md
  types/uikit/v2/README.md
Labels: Owner Approved, Perf: Same, Untested Change

#49538 nova-editor: New features from Nova 3
  types/nova-editor-node/index.d.ts
  types/nova-editor-node/nova-editor-node-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#48890 codemirror: Fixed hint incorrectly being required for the showHint function
  types/codemirror/addon/hint/show-hint.d.ts
  types/codemirror/test/addon/hint/show-hint.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#49944 Update lifecycle image, using svg
  README.md
Labels: Edits Infrastructure

#49182 @types/beanstalkd : Updating index.d.ts due to wrongly typed methods parameters
  types/beanstalkd/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49031 mssql: Add MSSQLError class + update subclasses
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49525 [list.js] cover all valueNames definitions
  types/list.js/index.d.ts
  types/list.js/list.js-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49783 Change the definition of Omit<T, K> so that it preserves discriminated unions
  types/mongodb/index.d.ts
  types/mongodb/test/collection/findX.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge

#49833 plotly.js: add layout type for boxmode
  types/plotly.js/index.d.ts
  types/plotly.js/lib/traces/box.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#48278 Add some missing options in TextMarkerOptions
  types/codemirror/index.d.ts
  types/codemirror/test/index.ts
Labels: Edits Owners, Maintainer Approved, Other Approved, Perf: Same, Popular package, Self Merge

#48764 update(ua-parser-js): correct UMD definition
  types/ua-parser-js/index.d.ts
  types/ua-parser-js/tslint.json
  types/ua-parser-js/ua-parser-js-tests.ts
Labels: Edits Owners, Maintainer Approved, Perf: Better, Popular package, Self Merge

#49906 parsimmon: sepBy1 should return a non-empty array
  types/parsimmon/index.d.ts
  types/parsimmon/parsimmon-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49933 [pino-http] fix: Declare support for the optional `next` parameter
  types/pino-http/index.d.ts
  types/pino-http/pino-http-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#49770 Fix createFromEntity type on navigateTo
  types/xrm/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#49974 [mustache] Add `.render()` options parameter introduced in v4.1.0
  types/mustache/index.d.ts
  types/mustache/mustache-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#49986 [mapbox-gl] fix Layer type definition
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Author is Owner, Other Approved, Owner Approved, Popular package, Self Merge

#49901 feat(salesman.js): new definition
  types/salesman.js/index.d.ts
  types/salesman.js/salesman.js-tests.ts
  types/salesman.js/tsconfig.json
  types/salesman.js/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#49987 Use correct type for header and footer spacing
  types/wkhtmltopdf/index.d.ts
  types/wkhtmltopdf/wkhtmltopdf-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#49971 [socket.io] add parser option to server constructor
  types/socket.io/index.d.ts
  types/socket.io/socket.io-tests.ts
Labels: Owner Approved, Perf: Worse, Popular package, Self Merge

#49873 chore: init google-maps-web @ 3.42
  types/google-maps-web/google-maps-web-tests.ts
  types/google-maps-web/index.d.ts
  types/google-maps-web/tsconfig.json
  types/google-maps-web/tslint.json
Labels: New Definition

#49998 [office-js, office-js-preview] Correcting Word.ContentControl.placeholderText behavior for Word on the web
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved, Untested Change

#48888 Update react-copy-to-clipboard
  types/react-copy-to-clipboard/index.d.ts
  types/react-copy-to-clipboard/react-copy-to-clipboard-tests.tsx
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#48737 [jquery] Refinement for `parents()` types
  types/jquery/JQuery.d.ts
  types/jquery/jquery-tests.ts
Labels: Critical package, Maintainer Approved, Perf: Same, Self Merge

#49790 [babel-webpack-plugin] Remove types
  types/babel-webpack-plugin/babel-webpack-plugin-tests.ts
  types/babel-webpack-plugin/index.d.ts
  types/babel-webpack-plugin/tsconfig.json
  types/babel-webpack-plugin/tslint.json
Labels: Config Edit, Maintainer Approved, Owner Approved, Self Merge

#49589 Added PDFPageProxy#getPermissions
  types/pdfjs-dist/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49903 [@types/carbon-components-react] Fix ContentSwitcher & Switcher types.
  types/carbon-components-react/lib/components/ContentSwitcher/ContentSwitcher.d.ts
  types/carbon-components-react/lib/components/Switch/Switch.d.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49947 multer: fix type of callback for custom storage
  types/multer/index.d.ts
  types/multer/multer-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#49965 Fix jest-environment-puppeteer dependencies
  types/jest-environment-puppeteer/package.json
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49979 [mongodb] Rename typo $diacraticSensitive -> $diacriticSensitive.
  types/mongodb/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49928 Update of internal dependency in 'adeira__graphql-global-id'
  types/adeira__graphql-global-id/index.d.ts
  types/adeira__graphql-global-id/package.json
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#48980 [react-cytoscapejs] update types for v1.2.1
  types/react-cytoscapejs/index.d.ts
  types/react-cytoscapejs/react-cytoscapejs-tests.tsx
Labels: Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#49969 chore(jest): remove unneeded `Omit` definition
  types/jest/index.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#49295 fix(cheerio): mark properties on `Element` as `null` or optional
  types/cheerio/cheerio-tests.ts
  types/cheerio/index.d.ts
  types/cheerio/tsconfig.json
Labels: Config Edit, Critical package, Maintainer Approved, Perf: Same, Self Merge

#49935 prosemirror-markdown - 1.5.0 - noCloseToken
  types/prosemirror-markdown/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#49918 [forge-viewer] updated Autodesk.Viewing.Model
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#49976 [forge-viewer] added DataVisualization extension
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#49968 update(mousetrap): parameterless ctor support and other changes
  types/mousetrap/index.d.ts
  types/mousetrap/test/global-bind.ts
  types/mousetrap/test/index-module.ts
  types/mousetrap/test/index.ts
  types/mousetrap/tsconfig.json
  types/mousetrap/tslint.json
Labels: Config Edit, Edits Owners, Maintainer Approved, Owner Approved, Perf: Better, Popular package, Self Merge

#49940 [matter-js] Add Render.lookAt method and Render.showSleeping option
  types/matter-js/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49843 [preact-i18n] updated types to match v2.3.0-preactx
  types/preact-i18n/index.d.ts
  types/preact-i18n/package.json
  types/preact-i18n/preact-i18n-tests.tsx
  types/preact-i18n/tsconfig.json
Labels: Config Edit, Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#49943 [headroom.js] support for new v0.12.0 feature to define separate up/down values for offset option
  types/headroom/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49229 fix(@babel/traverse): add missing denylist option
  types/babel__traverse/babel__traverse-tests.ts
  types/babel__traverse/index.d.ts
Labels: Critical package, Maintainer Approved, Perf: Same, Self Merge

#49647 [@types/single-spa-react] Added typings for errorBoundary and renderType in SingleSpaReact Options
  types/single-spa-react/index.d.ts
  types/single-spa-react/single-spa-react-tests.tsx
Labels: Owner Approved, Perf: Worse, Self Merge

#49919 [@types/tuya-panel-kit]update and fix typing for tuya-panel-kit
  types/tuya-panel-kit/index.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Self Merge, Untested Change

#49938 [@types/mz] Fixing bad return type definition in async read()
  types/mz/fs.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#49954 Add skip and todo to module type definition to package qunit
  types/qunit/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#49860 Mocha: Add global setup/teardown methods for mocha 8.2
  types/mocha/index.d.ts
  types/mocha/mocha-tests.ts
Labels: Critical package, Maintainer Approved, Perf: Same, Self Merge

#49682 Update knuddels-userapps-api
  types/knuddels-userapps-api/index.d.ts
  types/knuddels-userapps-api/knuddels-userapps-api-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#49008 Fix typo in @types/node for tls.connect options when using PSK
  types/node/test/tls.ts
  types/node/tls.d.ts
  types/node/v13/test/tls.ts
  types/node/v13/tls.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge
