Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-10, with the labels that each got.

#46804 react-d3-graph - updated Node's size property to reflect latest version @2.5.0
  types/react-d3-graph/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48373 [d3-random] Update types to v2.1
  types/d3-random/d3-random-tests.ts
  types/d3-random/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Popular package

#48370 [d3] Update types to v5.16
  types/d3/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Popular package, Untested Change

#48242 Bull arena 3.0 support
  types/bull-arena/index.d.ts
  types/bull-arena/package.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48259 [ember-feature-flag] export enableFeature
  types/ember-feature-flags/ember-feature-flags-tests.ts
  types/ember-feature-flags/index.d.ts
  types/ember-feature-flags/test-support/index.d.ts
  types/ember-feature-flags/tests/helpers/with-feature.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48294 Update Quill types
  types/quill/index.d.ts
  types/quill/quill-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#46973 [react-lazyload] add prop 'classNamePrefix'
  types/react-lazyload/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48315 [k6] Update for v0.28
  types/k6/index.d.ts
  types/k6/options.d.ts
  types/k6/test/options.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#46867 Add missing columnToggle in TableToolkitProps
  types/react-bootstrap-table2-toolkit/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Other Approved, Perf: Same, Untested Change

#48405 Update koa-compress types to include defaultEncoding
  types/koa-compress/index.d.ts
  types/koa-compress/koa-compress-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48404 Fix typo in definition of papaparse
  types/papaparse/index.d.ts
  types/papaparse/papaparse-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48290 [react-burger-menu] Add missing onClose and onOpen props (2.7.0)
  types/react-burger-menu/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48387 [d3-random] Update types to v2.2
  types/d3-random/d3-random-tests.ts
  types/d3-random/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#48384 [d3-force] Update types to v2.1
  types/d3-force/d3-force-tests.ts
  types/d3-force/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#47784 [@types/react] Resolve https://github.com/microsoft/TypeScript/issues/40511
  types/react/index.d.ts
Labels: Critical package, Other Approved, Perf: Same, Untested Change

#48374 [extenso] Create types
  types/extenso/extenso-tests.ts
  types/extenso/index.d.ts
  types/extenso/tsconfig.json
  types/extenso/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48412 [react] Mark deprecated iframe attributes
  types/react/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Untested Change

#47152 update(imagemin-gifsicle): docs and version bump
  types/imagemin-gifsicle/imagemin-gifsicle-tests.ts
  types/imagemin-gifsicle/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#48372 feat(autokanji): new definition
  types/autokanji/autokanji-tests.ts
  types/autokanji/index.d.ts
  types/autokanji/tsconfig.json
  types/autokanji/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48369 add typings for nodemailer-html-to-text:3.1
  types/nodemailer-html-to-text/index.d.ts
  types/nodemailer-html-to-text/nodemailer-html-to-text-tests.ts
  types/nodemailer-html-to-text/tsconfig.json
  types/nodemailer-html-to-text/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48174 [flexslider] Update type definitions to version 2.7
  types/flexslider/flexslider-tests.ts
  types/flexslider/index.d.ts
  types/flexslider/tslint.json
Labels: Merge:Auto, Other Approved, Perf: Same

#48378 deflate-js type bindings for v0.2.3
  types/deflate-js/index.d.ts
  types/deflate-js/test/deflate-js-tests.cjs.ts
  types/deflate-js/tsconfig.json
  types/deflate-js/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48400 add typings for react-native-aws3
  types/react-native-aws3/index.d.ts
  types/react-native-aws3/react-native-aws3-tests.ts
  types/react-native-aws3/tsconfig.json
  types/react-native-aws3/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48403 add typings for react-native-onboarding-swiper
  types/react-native-onboarding-swiper/index.d.ts
  types/react-native-onboarding-swiper/react-native-onboarding-swiper-tests.tsx
  types/react-native-onboarding-swiper/tsconfig.json
  types/react-native-onboarding-swiper/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48394 jsdom-screenshot types for version 3.2
  types/jsdom-screenshot/index.d.ts
  types/jsdom-screenshot/jsdom-screenshot-tests.ts
  types/jsdom-screenshot/tsconfig.json
  types/jsdom-screenshot/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48406 add typings for react-native-image-gallery
  types/react-native-image-gallery/index.d.ts
  types/react-native-image-gallery/react-native-image-gallery-tests.tsx
  types/react-native-image-gallery/tsconfig.json
  types/react-native-image-gallery/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48413 Adds type definitions for to-px
  types/to-px/index.d.ts
  types/to-px/to-px-tests.ts
  types/to-px/tsconfig.json
  types/to-px/tslint.json
Labels: New Definition

#48342 smtp-server: change SMTPServerAuthenticationResponse.user type to be nullable
  types/smtp-server/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#47650 [@types/ssh2-sftp-client] Replaced outdated ssh2Stream.TransferOptions interface references
  types/ssh2-sftp-client/index.d.ts
  types/ssh2-sftp-client/ssh2-sftp-client-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48392 add google-one-tap types
  types/google-one-tap/index.d.ts
  types/google-one-tap/test/google-one-tap-global.test.ts
  types/google-one-tap/tsconfig.json
  types/google-one-tap/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48371 feat(furigana-markdown-it): new definition
  types/furigana-markdown-it/furigana-markdown-it-tests.ts
  types/furigana-markdown-it/index.d.ts
  types/furigana-markdown-it/tsconfig.json
  types/furigana-markdown-it/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48421 ffluent-ffmpeg: Added cwd to FfmpegCommandOptions
  types/fluent-ffmpeg/fluent-ffmpeg-tests.ts
  types/fluent-ffmpeg/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48269 react-native-push-notification: Added `allowWhileIdle` to push notifications
  types/react-native-push-notification/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48417 [@types/ramda] optionally stricter types for tryCatch, + currying
  types/ramda/index.d.ts
  types/ramda/test/tryCatch-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48308 Add Title and BusyIndicator to Fundamental-React
  types/fundamental-react/fundamental-react-tests.tsx
  types/fundamental-react/index.d.ts
  types/fundamental-react/lib/BusyIndicator/BusyIndicator.d.ts
  types/fundamental-react/lib/Title/Title.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48418 `unsplash-js`: improve types with stricter types
  types/unsplash-js/index.d.ts
  types/unsplash-js/unsplash-js-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#46770 [system-service] Remove superfluous /// <reference types="node" />
  types/system-service/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Better, Untested Change

#48227 [ottomated__passport-streamlabs] Unmangle scoped package names
  types/ottomated__passport-streamlabs/ottomated__passport-streamlabs-tests.ts
  types/ottomated__passport-streamlabs/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Perf: Same

#48233 [ungap__create-content] Unmangle scoped package names
  types/ungap__create-content/test/create-content.cjs.test.ts
  types/ungap__create-content/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48416 fix(copyfiles): correct `exclude` option and version bump
  types/copyfiles/copyfiles-tests.ts
  types/copyfiles/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#48448 office-js, office-preview-js add description of types defined with ty…
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved

#48442 Update @mapbox/mapbox-sdk StaticImage request configuration to reflect current package
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48447 [matrix-appservice-bridge] Remove types as project converted to TS
  notNeededPackages.json
  types/matrix-appservice-bridge/index.d.ts
  types/matrix-appservice-bridge/matrix-appservice-bridge-tests.ts
  types/matrix-appservice-bridge/tsconfig.json
  types/matrix-appservice-bridge/tslint.json
Labels: Author is Owner, Edits Infrastructure, Maintainer Approved, Merge:Auto, Other Approved

#48119 [ember__routing] update Transition API
  types/ember__routing/-private/transition.d.ts
  types/ember__routing/test/route.ts
  types/ember__routing/test/router-service.ts
  types/ember__routing/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48454 Add types for @paypal/paypal-js
  types/paypal__paypal-js/index.d.ts
  types/paypal__paypal-js/paypal__paypal-js-tests.ts
  types/paypal__paypal-js/tsconfig.json
  types/paypal__paypal-js/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48430 Added soundex-code Typescript declaration
  types/soundex-code/index.d.ts
  types/soundex-code/soundex-code-tests.ts
  types/soundex-code/tsconfig.json
  types/soundex-code/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48235 [ungap__weakmap] Unmangle scoped package names
  types/ungap__weakmap/test/weakmap.cjs.test.ts
  types/ungap__weakmap/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Other Approved, Owner Approved, Perf: Same

#48234 [ungap__global-this] Unmangle scoped package names
  types/ungap__global-this/tsconfig.json
  types/ungap__global-this/ungap__global-this-tests.ts
Labels: Config Edit, Maintainer Approved, Merge:Auto, Other Approved, Owner Approved, Perf: Same

#48232 [react-native-community__cli] Unmangle scoped package names
  types/react-native-community__cli/index.d.ts
  types/react-native-community__cli/react-native-community__cli-tests.ts
  types/react-native-community__cli/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Perf: Same

#48231 [reach__alert-dialog] Unmangle scoped package names
  types/reach__alert-dialog/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48230 [postlight__mercury-parser] Unmangle scoped package names
  types/postlight__mercury-parser/postlight__mercury-parser-tests.ts
  types/postlight__mercury-parser/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48228 [ottomated__passport-twitch] Unmangle scoped package names
  types/ottomated__passport-twitch/ottomated__passport-twitch-tests.ts
  types/ottomated__passport-twitch/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Perf: Same

#48226 [okta__okta-vue] Unmangle scoped package names
  types/okta__okta-vue/okta__okta-vue-tests.ts
  types/okta__okta-vue/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Perf: Same

#48225 [material__ripple] Unmangle scoped package names
  types/material__ripple/constants.d.ts
  types/material__ripple/foundation.d.ts
  types/material__ripple/index.d.ts
  types/material__ripple/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto

#48223 [iopipe__iopipe] Unmangle scoped package names
  types/iopipe__iopipe/index.d.ts
  types/iopipe__iopipe/iopipe__iopipe-tests.ts
  types/iopipe__iopipe/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Perf: Same

#48222 [guardian__prosemirror-invisibles] Unmangle scoped package names
  types/guardian__prosemirror-invisibles/guardian__prosemirror-invisibles-tests.ts
  types/guardian__prosemirror-invisibles/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Perf: Same

#48221 [fullcalendar__vue] Unmangle scoped package names
  types/fullcalendar__vue/fullcalendar__vue-tests.ts
  types/fullcalendar__vue/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48220 [ckeditor__ckeditor5-utils] Unmangle scoped package names
  types/ckeditor__ckeditor5-utils/ckeditor__ckeditor5-utils-tests.ts
  types/ckeditor__ckeditor5-utils/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48218 [ckeditor__ckeditor5-core] Unmangle scoped package names
  types/ckeditor__ckeditor5-core/ckeditor__ckeditor5-core-tests.ts
  types/ckeditor__ckeditor5-core/index.d.ts
  types/ckeditor__ckeditor5-core/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48217 [bandagedbd__bdapi] Unmangle scoped package names
  types/bandagedbd__bdapi/bandagedbd__bdapi-tests.ts
  types/bandagedbd__bdapi/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48216 [apptimize__apptimize-web-sdk] Unmangle scoped package names
  types/apptimize__apptimize-web-sdk/apptimize__apptimize-web-sdk-tests.ts
  types/apptimize__apptimize-web-sdk/tsconfig.json
Labels: Config Edit, Maintainer Approved, Merge:Auto, Perf: Same

#48432 Add typings for gif-encoder
  types/gif-encoder/gif-encoder-tests.ts
  types/gif-encoder/index.d.ts
  types/gif-encoder/tsconfig.json
  types/gif-encoder/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48428 [ip-address] remove deprecated functions
  types/ip-address/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48457 [gapi.client.storage] automatic update
  types/gapi.client.storage/gapi.client.storage-tests.ts
  types/gapi.client.storage/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved

#48449 Argparse constants moved according to v1 to v2 specification
  types/argparse/argparse-tests.ts
  types/argparse/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#48357 [react-native-version-check] Replaces erroneous property appName with packageName
  types/react-native-version-check/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#46812 mailparser: Mark email address as possibly being undefined
  types/mailparser/index.d.ts
Labels: Perf: Same, Untested Change

#48435 [koa-session] Replace koa.Context with koa.BaseContext
  types/koa-session/index.d.ts
  types/koa-session/koa-session-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48305 Add types for outliers
  types/outliers/index.d.ts
  types/outliers/outliers-tests.ts
  types/outliers/tsconfig.json
  types/outliers/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48463 sinon: add calledOnceWithMatch assertion
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#47165 fix(echarts): correct `title` padding property types
  types/echarts/echarts-tests.ts
  types/echarts/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#48441 nova-editor: Fix commitChars on completion item
  types/nova-editor-node/index.d.ts
  types/nova-editor-node/nova-editor-node-tests.ts
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved, Perf: Same

#48429 [properties-reader] Add missing optinal parameters types
  types/properties-reader/index.d.ts
  types/properties-reader/properties-reader-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48480 Update react-native-zeroconf types to v0.12
  types/react-native-zeroconf/index.d.ts
  types/react-native-zeroconf/react-native-zeroconf-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#47210 update(jest-image-snapshot): missing export
  types/jest-image-snapshot/index.d.ts
  types/jest-image-snapshot/jest-image-snapshot-tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Owner Approved, Perf: Same, Popular package

#48483 [mailgun-js] Adds method to delete a member of a list
  types/mailgun-js/index.d.ts
  types/mailgun-js/mailgun-js-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48379 Change configValidationMode as optional for serverless aws provider
  types/serverless/plugins/aws/provider/awsProvider.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48254 [vue-nice-dates] Update types to v2.0
  types/vue-nice-dates/Calendar.d.ts
  types/vue-nice-dates/CalendarDay.d.ts
  types/vue-nice-dates/CalendarGrid.d.ts
  types/vue-nice-dates/CalendarNavigation.d.ts
  types/vue-nice-dates/CalendarWeekHeader.d.ts
  types/vue-nice-dates/DatePicker.d.ts
  types/vue-nice-dates/DatePickerCalendar.d.ts
  types/vue-nice-dates/DateRangePicker.d.ts
  types/vue-nice-dates/DateRangePickerCalendar.d.ts
  types/vue-nice-dates/index.d.ts
  types/vue-nice-dates/shared.d.ts
  types/vue-nice-dates/vue-nice-dates-tests.ts
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved, Perf: Same

#48344 fix(echarts): type declaration for overloading of echartsInstance.on
  types/echarts/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package, Untested Change

#48427 Chart.js - missing tooltip axis option
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48445 feat: [request] new RequestOptions
  types/needle/index.d.ts
  types/needle/needle-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48356 [@types/react-grid-layout]: Pass handle option to react-resizable
  types/react-grid-layout/index.d.ts
  types/react-grid-layout/react-grid-layout-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48486 Update apple-mapkit-js to Version 5.50
  types/apple-mapkit-js/apple-mapkit-js-tests.ts
  types/apple-mapkit-js/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48444 [echarts] Update supported options for `echartsInstance.showLoading` method
  types/echarts/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package, Untested Change

#48097 [forest-express-sequelize] separate smart field|action|segment option from collection option
  types/forest-express-mongoose/forest-express-mongoose-tests.ts
  types/forest-express-mongoose/index.d.ts
  types/forest-express-sequelize/forest-express-sequelize-tests.ts
  types/forest-express-sequelize/index.d.ts
Labels: Edits multiple packages, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48499 [react-native] Fix typos in type definition file
  types/react-native/index.d.ts
Labels: Critical package, Untested Change

#48462 [ReactNative] Add dataDetectorType to android text props component
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Critical package, Perf: Same

#48494 Feature/fundamental react
  types/fundamental-react/fundamental-react-tests.tsx
  types/fundamental-react/index.d.ts
  types/fundamental-react/lib/Avatar/Avatar.d.ts
  types/fundamental-react/lib/Identifier/Identifier.d.ts
  types/fundamental-react/lib/LayoutPanel/LayoutPanel.d.ts
  types/fundamental-react/lib/ObjectStatus/ObjectStatus.d.ts
  types/fundamental-react/lib/Panel/Panel.d.ts
  types/fundamental-react/lib/Title/Title.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#47268 [chai] feat(./): add missing types for `finite` and `isFinite`
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Critical package, Merge:Auto, Owner Approved, Perf: Same

#48498 [react] Fix typos in type definitions
  types/react/index.d.ts
  types/react/v15/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Untested Change

#48468 [electron-prompt] Update to 1.6.0
  types/electron-prompt/electron-prompt-tests.ts
  types/electron-prompt/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, No Other Owners, Perf: Same

#48439 [ip-address] remove ip-address; types were inlined
  README.md
  notNeededPackages.json
  types/ip-address/index.d.ts
  types/ip-address/ip-address-tests.ts
  types/ip-address/tsconfig.json
  types/ip-address/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Merge:Auto, Other Approved, Owner Approved

#48479 Change type from interface to class for FetchOptions in NodeGit
  types/nodegit/fetch-options.d.ts
  types/nodegit/nodegit-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48103 feat: add fingerprintjs__fingerprintjs types
  types/fingerprintjs/fingerprintjs-tests.ts
  types/fingerprintjs/index.d.ts
  types/fingerprintjs/tslint.json
  types/fingerprintjs2/tsconfig.json
  types/fingerprintjs2/v1/fingerprintjs2-tests.ts
  types/fingerprintjs2/v1/index.d.ts
  types/fingerprintjs2/v1/tsconfig.json
  types/fingerprintjs2/v1/tslint.json
  types/fingerprintjs__fingerprintjs/fingerprintjs__fingerprintjs-tests.ts
  types/fingerprintjs__fingerprintjs/index.d.ts
  types/fingerprintjs__fingerprintjs/tsconfig.json
  types/fingerprintjs__fingerprintjs/tslint.json
Labels: Edits multiple packages, Maintainer Approved, Merge:Auto, New Definition

#48513 Improve @paypal/paypal-js typings
  types/paypal__paypal-js/index.d.ts
  types/paypal__paypal-js/paypal__paypal-js-tests.ts
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved, Perf: Same

#47163 bonjour: Fix remote service definition
  types/bonjour/bonjour-tests.ts
  types/bonjour/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#48471 [d3-scale] Update types to v3.1
  types/d3-scale/d3-scale-tests.ts
  types/d3-scale/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#48201 [jquery] Adding 'code' prop to keydown events.
  types/jquery/misc.d.ts
  types/jquery/v2/index.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48425 [googlemaps] Simplify handlers in addListener
  types/googlemaps/index.d.ts
  types/googlemaps/reference/event.d.ts
  types/googlemaps/reference/info-window.d.ts
  types/googlemaps/reference/map.d.ts
  types/googlemaps/test/reference/map-tests.ts
  types/googlemaps/tsconfig.json
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#48274 node: socket is optional on http.OutgoingMessage
  types/node/http.d.ts
  types/node/test/http.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48453 chore(node): apply `prettier` to `assert` types
  types/node/assert.d.ts
  types/node/ts3.4/assert.d.ts
  types/node/v10/assert.d.ts
  types/node/v10/ts3.6/assert.d.ts
  types/node/v11/assert.d.ts
  types/node/v11/test/assert.ts
  types/node/v11/ts3.6/assert.d.ts
  types/node/v12/assert.d.ts
  types/node/v12/test/assert.ts
  types/node/v12/ts3.3/assert.d.ts
  types/node/v13/assert.d.ts
  types/node/v13/test/assert.ts
  types/node/v13/ts3.4/assert.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#48352 [node] Update `zlib` module
  types/node/v10/zlib.d.ts
  types/node/v11/zlib.d.ts
  types/node/v12/zlib.d.ts
  types/node/v13/zlib.d.ts
  types/node/zlib.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48335 [gapi.client.analytics] automatic update
  types/gapi.client.analytics/gapi.client.analytics-tests.ts
  types/gapi.client.analytics/index.d.ts
  types/gapi.client.analytics/readme.md
  types/gapi.client.analytics/tsconfig.json
  types/gapi.client.analytics/tslint.json
Labels: Merge:Auto, Other Approved, Perf: Same

#48397 Fixed meteor:universe-i18n runWithLocale.
  types/meteor-universe-i18n/index.d.ts
  types/meteor-universe-i18n/meteor-universe-i18n-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#47532 [react-router-dom] Add tests and update lowest supported TypeScript version
  types/react-router-dom/index.d.ts
  types/react-router-dom/react-router-dom-tests.tsx
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#48533 [crypto-js] Correct CipherHelper decrypt method
  types/crypto-js/index.d.ts
  types/crypto-js/test/crypto-js-module.tests.ts
Labels: Author is Owner, Merge:Auto, Other Approved, Owner Approved, Perf: Same, Popular package

#47270 [react-table] Removed groupByBoundary & added leafRows
  types/react-table/index.d.ts
  types/react-table/react-table-tests.tsx
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#48552 [@types/tinymce] TinyMCE 4.x extend options for table plugin
  types/tinymce/index.d.ts
  types/tinymce/tinymce-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48516 dogapi: fix response type of send_all
  types/dogapi/dogapi-tests.ts
  types/dogapi/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48539 [mock-fs] Update type definitions to v4.13.
  types/mock-fs/index.d.ts
  types/mock-fs/lib/filesystem.d.ts
  types/mock-fs/mock-fs-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#47739 [scriptable-ios]: Update for Scriptable app v1.5.0
  types/scriptable-ios/index.d.ts
  types/scriptable-ios/scriptable-ios-tests.ts
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved, Perf: Same

#48563 Add Scenario to export in k6
  types/k6/options.d.ts
  types/k6/test/options.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48550 Add require function to nw.js type definition
  types/nw.js/index.d.ts
  types/nw.js/nw.js-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48502 [prosemirror-view] Optional `side` param for `coordsAtPos`
  types/prosemirror-view/index.d.ts
  types/prosemirror-view/prosemirror-view-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48599 hls.js: fix incorrect type for programDateTime
  types/hls.js/hls.js-tests.ts
  types/hls.js/index.d.ts
Labels: Merge:Auto, Owner Approved, Popular package

#48587 Use prettier to autoformat dogapi files based on the existing prettier config
  types/dogapi/dogapi-tests.ts
  types/dogapi/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48383 [yup] allow date validator to be used with string properties
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48590 [needle] Add uri_modifier and follow_if_same_location to needle options
  types/needle/index.d.ts
  types/needle/needle-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#48608 [ramda] infer return type of nAry
  types/ramda/index.d.ts
  types/ramda/test/nAry-tests.ts
Labels: Merge:Auto, Owner Approved, Popular package

#48292 feat(react-relay): Added loadQuery function
  types/react-relay/lib/hooks.d.ts
  types/react-relay/lib/relay-experimental/EntryPointTypes.d.ts
  types/react-relay/lib/relay-experimental/loadQuery.d.ts
  types/react-relay/test/relay-experimental-tests.tsx
Labels: Author is Owner, Perf: Same

#48576 Update typings for `UserInfo` in `react-native-auth0`
  types/react-native-auth0/index.d.ts
  types/react-native-auth0/react-native-auth0-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48529 [googlemaps] distance-matrix
  types/googlemaps/index.d.ts
  types/googlemaps/reference/distance-matrix.d.ts
  types/googlemaps/test/reference/distance-matrix-tests.ts
  types/googlemaps/tsconfig.json
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#48615 `eslint`: add `parent` property to node
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Merge:Auto, Owner Approved, Popular package

#48612 [ramda] infer types of bind
  types/ramda/index.d.ts
  types/ramda/test/bind-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48613 [ramda] infer types of binary
  types/ramda/index.d.ts
  types/ramda/test/binary-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48614 [ramda] infer types of curryN
  types/ramda/index.d.ts
  types/ramda/test/curryN-tests.ts
  types/ramda/tsconfig.json
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#47867 [yargs] Add types for deprecate, deprecated, and deprecatedOptions
  types/yargs/index.d.ts
  types/yargs/yargs-tests.ts
Labels: Critical package, Merge:Auto, Owner Approved, Perf: Same

#48452 fix(node): improve typing of `assert.strict`
  types/node/assert.d.ts
  types/node/test/assert.ts
  types/node/v10/assert.d.ts
  types/node/v11/assert.d.ts
  types/node/v11/test/assert.ts
  types/node/v12/assert.d.ts
  types/node/v12/test/assert.ts
  types/node/v13/assert.d.ts
  types/node/v13/test/assert.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#48625 Recurly.js updates
  types/recurly__recurly-js/lib/configure.d.ts
  types/recurly__recurly-js/lib/elements.d.ts
  types/recurly__recurly-js/lib/paypal.d.ts
  types/recurly__recurly-js/test/configure.ts
  types/recurly__recurly-js/test/paypal.ts
Labels: Author is Owner, Merge:Auto, Owner Approved

#48490 cytoscape: Corrects Visibility property value from 'none' to 'hidden'
  types/cytoscape/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48482 Fix typo -- "credentails" to "credentials" in node-auth Providers type
  types/next-auth/providers.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48505 [webpackbar] Fix typo in comment
  types/webpackbar/v2/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48507 Wrong JobId definition in function requirements
  types/bull/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, Untested Change

#48509 Update pathoverlay to reflect jsdocs
  types/mapbox-gl/index.d.ts
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Edits multiple packages, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package

#48553 [amqplib] Change consume callback return type to void
  types/amqplib/callback_api.d.ts
  types/amqplib/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package, Untested Change

#48492 Add all documented properties to ErrorParam, fixes #48491
  types/jwplayer/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Untested Change

#48548 [node/zlib] add promisified APIs
  types/node/test/zlib.ts
  types/node/v12/test/zlib.ts
  types/node/v12/zlib.d.ts
  types/node/zlib.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#48549 [node/crypto] add missing keytypes and their generation
  types/node/crypto.d.ts
  types/node/test/crypto.ts
  types/node/v12/crypto.d.ts
  types/node/v12/test/crypto.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#48611 ramda: infer zipObj keys
  types/ramda/index.d.ts
  types/ramda/test/zipObj-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#48558 Add missing `activeStartDate` property to `CalendarTileProperties` for react-calendar
  types/react-calendar/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#48607 [big.js] Add `toNumber` method
  types/big.js/index.d.ts
  types/big.js/test/big.js-global-tests.ts
  types/big.js/test/big.js-module-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#48573 [react-select] Export type definition for Select
  types/react-select/index.d.ts
  types/react-select/src/Select.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package, Untested Change

#48560 [Braintree] Update statusHistory definition to array
  types/braintree/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48517 [jsrsasign] Amend `getPEM` return type to `string`
  types/jsrsasign/modules/KEYUTIL.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48633 fix: typos for URL in workbox-webpack-plugin
  types/workbox-webpack-plugin/index.d.ts
  types/workbox-webpack-plugin/workbox-webpack-plugin-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48546 [node] Add deprecation messages for `punycode` module
  types/node/punycode.d.ts
  types/node/v10/punycode.d.ts
  types/node/v11/punycode.d.ts
  types/node/v12/punycode.d.ts
  types/node/v13/punycode.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48424 [node] Update `worker_threads` module
  types/node/test/worker_threads.ts
  types/node/v12/worker_threads.d.ts
  types/node/v13/worker_threads.d.ts
  types/node/worker_threads.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48504 PACKAGE object-hash | Added BufferEncoding type for Browser
  types/object-hash/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package, Untested Change

#48640 [react-loader-spinner] Add missing props definitions
  types/react-loader-spinner/index.d.ts
  types/react-loader-spinner/test/react-loader-spinner-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#48260 fix(react-native-text-input-mask): refInput typo
  types/react-native-text-input-mask/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Untested Change
