Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-11, with the labels that each got.

#49076 fix(benchmark): update benchmark types to match release 2.1.4
  types/benchmark/benchmark-tests.ts
  types/benchmark/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49120 Repair links
  notNeededPackages.json
Labels: Edits Infrastructure

#49301 Fixed Types for setRowProps on Mui datatables
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#49300 [react-native] fixed broken links to react-native docs (http error 404)
  types/react-native/index.d.ts
Labels: Critical package, Perf: Same, Untested Change

#49306 chore: Adds in fetchKey for stale query refs
  types/react-relay/lib/relay-experimental/EntryPointTypes.d.ts
Labels: Author is Owner, Perf: Same, Untested Change

#49285 Removing myself as a contributor to @types/Parse - too many notifications/mentions
  types/parse/index.d.ts
Labels: Author is Owner, Perf: Same, Untested Change

#49168 chore(node): remove old versions
  types/node/v0/index.d.ts
  types/node/v0/node-tests.ts
  types/node/v0/tsconfig.json
  types/node/v0/tslint.json
  types/node/v4/index.d.ts
  types/node/v4/node-tests.ts
  types/node/v4/tsconfig.json
  types/node/v4/tslint.json
  types/node/v6/base.d.ts
  types/node/v6/index.d.ts
  types/node/v6/node-tests.ts
  types/node/v6/tsconfig.json
  types/node/v6/tslint.json
  types/node/v7/base.d.ts
  types/node/v7/index.d.ts
  types/node/v7/node-tests.ts
  types/node/v7/tsconfig.json
  types/node/v7/tslint.json
  types/node/v8/base.d.ts
  types/node/v8/index.d.ts
  types/node/v8/inspector.d.ts
  types/node/v8/node-tests.ts
  types/node/v8/tsconfig.json
  types/node/v8/tslint.json
  types/node/v9/base.d.ts
  types/node/v9/index.d.ts
  types/node/v9/inspector.d.ts
  types/node/v9/node-tests.ts
  types/node/v9/tsconfig.json
  types/node/v9/tslint.json
Labels: Author is Owner, Config Edit, Critical package, Owner Approved

#48863 [react-stickynode] Update types to match version 3.0.4
  types/react-stickynode/index.d.ts
  types/react-stickynode/react-stickynode-tests.tsx
Labels: Merge:Auto, Merge:YSYL, Owner Approved, Perf: Same

#48393 fix(express-brute-redis): Add missing options and fix outdated types
  types/express-brute-redis/express-brute-redis-tests.ts
  types/express-brute-redis/index.d.ts
Labels: Abandoned, Perf: Better

#48313 [Serverless] add optional Description field in awsProvider.resources
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Abandoned, Perf: Same

#49299 remove(gapi.client.sheets): passthrough for #49235
  notNeededPackages.json
  types/gapi.client.sheets/gapi.client.sheets-tests.ts
  types/gapi.client.sheets/index.d.ts
  types/gapi.client.sheets/readme.md
  types/gapi.client.sheets/tsconfig.json
  types/gapi.client.sheets/tslint.json
Labels: Author is Owner, Edits Infrastructure

#49269 Create new definition @types/golang-wasm
  types/golang-wasm/index.d.ts
  types/golang-wasm/test/index.ts
  types/golang-wasm/tsconfig.json
  types/golang-wasm/tslint.json
Labels: New Definition

#49267 fix(@babel/core): add more `TransformCaller` types
  types/babel__core/babel__core-tests.ts
  types/babel__core/index.d.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#46778 [react-redux] Add default state type to Connect
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
Labels: Critical package, Owner Approved, Perf: Same

#49292 [igdb-api-node]: Update types for igdb-api-node v5.0
  types/igdb-api-node/igdb-api-node-tests.ts
  types/igdb-api-node/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49280 [@ember/component] add @ember/component/template-only
  types/ember__component/template-only.d.ts
  types/ember__component/test/template-only.ts
  types/ember__component/tsconfig.json
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#49279 [d3-array] Update types to v2.6
  types/d3-array/d3-array-tests.ts
  types/d3-array/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same, Popular package

#48777 chore: improve snowpack-env
  types/snowpack-env/index.d.ts
  types/snowpack-env/snowpack-env-tests.ts
Labels: Merge:Auto, Owner Approved

#49291 feat(cfn-response-promise): new definition
  types/cfn-response-promise/cfn-response-promise-tests.ts
  types/cfn-response-promise/index.d.ts
  types/cfn-response-promise/tsconfig.json
  types/cfn-response-promise/tslint.json
Labels: Merge:Auto, New Definition, Other Approved

#49313 fundamental-react: add properties to SideNav and MenuItem
  types/fundamental-react/fundamental-react-tests.tsx
  types/fundamental-react/lib/Menu/Menu.d.ts
  types/fundamental-react/lib/SideNavigation/SideNav.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49284 [radium] fix for stylerules in radium
  types/radium/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48848 Add missing index argument to SeamlessImmutable array filter
  types/seamless-immutable/index.d.ts
  types/seamless-immutable/seamless-immutable-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#47781 update(fs-extra): missing aliases
  types/fs-extra/fs-extra-tests.ts
  types/fs-extra/index.d.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#49268 Types for is-valid-zipcode
  types/is-valid-zipcode/index.d.ts
  types/is-valid-zipcode/is-valid-zipcode-tests.ts
  types/is-valid-zipcode/tsconfig.json
  types/is-valid-zipcode/tslint.json
Labels: Merge:Auto, New Definition, Other Approved

#48757 akamai-edgeworkers October 2020 changes
  types/akamai-edgeworkers/README.md
  types/akamai-edgeworkers/index.d.ts
  types/akamai-edgeworkers/test/create-response-tests.ts
  types/akamai-edgeworkers/test/http-request-tests.ts
  types/akamai-edgeworkers/test/log-tests.ts
  types/akamai-edgeworkers/test/scenario-stream.ts
  types/akamai-edgeworkers/test/stream.ts
  types/akamai-edgeworkers/tsconfig.json
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved, Perf: Same

#49318 Fix mini-css-extract-plugin types to work with Webpack 5
  types/mini-css-extract-plugin/index.d.ts
  types/mini-css-extract-plugin/mini-css-extract-plugin-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#49265 [@types/jsrsasign] JWS.sign password can be an object
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/KJUR/crypto/Mac.d.ts
  types/jsrsasign/modules/KJUR/jws/JWS.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49105 feat: Add Gantt chart to @types/google.visualization. Closes #43921
  types/google.visualization/google.visualization-tests.ts
  types/google.visualization/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#49341 upgrade carbon-components to v10.23
  types/carbon-components/carbon-components-tests.ts
  types/carbon-components/components/content-switcher/content-switcher.d.ts
  types/carbon-components/components/data-table/data-table.d.ts
  types/carbon-components/components/date-picker/date-picker.d.ts
  types/carbon-components/components/floating-menu/floating-menu.d.ts
  types/carbon-components/components/text-input/text-input.d.ts
  types/carbon-components/components/tooltip/tooltip--simple.d.ts
  types/carbon-components/components/tooltip/tooltip.d.ts
  types/carbon-components/components/ui-shell/header-submenu.d.ts
  types/carbon-components/components/ui-shell/navigation-menu.d.ts
  types/carbon-components/globals/js/settings.d.ts
  types/carbon-components/index.d.ts
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved

#49340 [@ember/routing] Add rootURL type to RouterService
  types/ember__routing/router-service.d.ts
  types/ember__routing/test/router.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#47305 Update/axe-webdriverjs
  types/axe-webdriverjs/axe-webdriverjs-tests.ts
  types/axe-webdriverjs/index.d.ts
Labels: Perf: Worse

#49309 Provide better types for connect-flash
  types/connect-flash/connect-flash-tests.ts
  types/connect-flash/index.d.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#49307 feat(brotli): new definition
  types/brotli/brotli-tests.ts
  types/brotli/compress.d.ts
  types/brotli/decompress.d.ts
  types/brotli/index.d.ts
  types/brotli/tsconfig.json
  types/brotli/tslint.json
Labels: Merge:Auto, New Definition, Other Approved

#49154 [3box] Add initial types
  types/3box/3box-tests.ts
  types/3box/index.d.ts
  types/3box/tsconfig.json
  types/3box/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49296 [@ember/routing] add RouteInfoWithAttributes, etc,
  types/ember__routing/-private/route-info-with-attributes.d.ts
  types/ember__routing/-private/transition.d.ts
  types/ember__routing/route.d.ts
  types/ember__routing/router-service.d.ts
  types/ember__routing/test/route.ts
  types/ember__routing/test/router-service.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#46446 [react-redux] Improved factory function types and deprecated `TypedUseSelectorHook`.
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
Labels: Critical package, Maintainer Approved, Merge:Auto, Perf: Same

#48652 Update typings for AngularJS 1.8.1 (packages: `angular`, `angular-sanitize`)
  types/angular-sanitize/index.d.ts
  types/angular/angular-tests.ts
  types/angular/index.d.ts
Labels: Edits multiple packages, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package

#49196 [d3-scale] Default scales to not returning unknown values
  types/d3-axis/v1/d3-axis-tests.ts
  types/d3-scale/d3-scale-tests.ts
  types/d3-scale/index.d.ts
  types/d3-zoom/v1/d3-zoom-tests.ts
  types/react-native-svg-charts/tsconfig.json
Labels: Author is Owner, Edits multiple packages, Maintainer Approved, Merge:Auto, Other Approved, Perf: Same, Popular package

#49322 chore(asn1js): remove unused pvutils import and dom lib
  types/asn1js/index.d.ts
  types/asn1js/tsconfig.json
Labels: Maintainer Approved, Merge:Auto, Perf: Better, Popular package, Untested Change

#49314 fix(terser-webpack-plugin): target `webpack@5`
  types/terser-webpack-plugin/index.d.ts
  types/terser-webpack-plugin/package.json
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, Untested Change

#49336 [jasmine] Add back jasmine.DiffBuilder.
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#49261 [jest-image-snapshot] Fix customDiffConfig type
  types/jest-image-snapshot/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, Untested Change

#49290 update(cfn-response): v1.0 update and fix
  types/cfn-response/cfn-response-tests.ts
  types/cfn-response/index.d.ts
  types/cfn-response/tsconfig.json
Labels: Merge:Auto, Owner Approved, Perf: Same

#49345 [@ember/routing] Resolve duplicate identifier 'rootURL' error
  types/ember__routing/router-service.d.ts
Labels: Merge:Auto, Other Approved, Owner Approved, Perf: Same, Untested Change

#48434 [detox] Add typing for `.not` expectation
  types/detox/index.d.ts
  types/detox/test/detox-module-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49315 Upgrade react-pdf to 5.0.0
  types/react-pdf/OTHER_FILES.txt
  types/react-pdf/dist/entry.parcel.d.ts
  types/react-pdf/dist/entry.webpack.d.ts
  types/react-pdf/dist/esm/entry.parcel.d.ts
  types/react-pdf/dist/esm/entry.webpack.d.ts
  types/react-pdf/dist/umd/entry.parcel.d.ts
  types/react-pdf/dist/umd/entry.webpack.d.ts
  types/react-pdf/index.d.ts
  types/react-pdf/react-pdf-tests.tsx
Labels: Config Edit, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Worse

#49195 [pdfjs-dist] add some missing viewport parameters
  types/pdfjs-dist/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package, Untested Change

#49173 Fix missing offsetCenter in PointerEvent
  types/react-map-gl/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48440 [@wordpress/components] Update ColorPalette and ColorPicker props
  types/wordpress__components/color-palette/index.d.ts
  types/wordpress__components/color-picker/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same

#49317 Update Mui Datatable to v3.7
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
Labels: Merge:Auto, Owner Approved, Perf: Same

#49194 [terraformer__arcgis] accept all GeoJSON types for geojsonToArcGIS
  types/terraformer__arcgis/index.d.ts
  types/terraformer__arcgis/terraformer__arcgis-tests.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#49332 Fix type of err in xml2js
  types/xml2js/xml2js-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#47184 feat(copy-webpack-plugin): assets filtering and v6.2
  types/copy-webpack-plugin/copy-webpack-plugin-tests.ts
  types/copy-webpack-plugin/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#49366 [@types/assets-webpack-plugin]: Fix types to work with webpack 5
  types/assets-webpack-plugin/assets-webpack-plugin-tests.ts
  types/assets-webpack-plugin/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49360 [bookshelf] Add autoRefresh and update knex
  types/bookshelf/bookshelf-tests.ts
  types/bookshelf/index.d.ts
  types/bookshelf/package.json
Labels: Merge:Auto, Owner Approved, Perf: Same

#49257 fix: Add pg dynamic password support to ClientOptions
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#49348 [jasmine-ajax] Add missing response properties: statusText, responseURL, responseJSON
  types/jasmine-ajax/index.d.ts
  types/jasmine-ajax/jasmine-ajax-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49374 `react-aria-menubutton`: allow ref forwarding
  types/react-aria-menubutton/index.d.ts
  types/react-aria-menubutton/react-aria-menubutton-tests.tsx
Labels: Merge:Auto, Owner Approved

#49359 [datatables.net-fixedcolumns] Fix some definitions and compliance with v3.3.1
  types/datatables.net-fixedcolumns/datatables.net-fixedcolumns-tests.ts
  types/datatables.net-fixedcolumns/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49103 Add type definition for missing property source-distance-from-node
  types/cytoscape/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Merge:YSYL, Owner Approved, Perf: Same, Untested Change

#48287 update(vivus): minor updates (0.4.5)
  types/vivus/index.d.ts
  types/vivus/tslint.json
  types/vivus/vivus-tests.ts
Labels: Abandoned, Perf: Same

#49379 Add joi-phone-number typings
  types/joi-phone-number/index.d.ts
  types/joi-phone-number/joi-phone-number-tests.ts
  types/joi-phone-number/tsconfig.json
  types/joi-phone-number/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49176 amqplib exchange types should include all strings
  types/amqplib/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Other Approved, Perf: Same, Popular package, Untested Change

#49350 [forge-viewer] updated type definitions
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#49370 Remove types for jwt-decode
  notNeededPackages.json
  types/jwt-decode/index.d.ts
  types/jwt-decode/jwt-decode-tests.ts
  types/jwt-decode/tsconfig.json
  types/jwt-decode/tslint.json
  types/jwt-decode/v1/index.d.ts
  types/jwt-decode/v1/jwt-decode-tests.ts
  types/jwt-decode/v1/tsconfig.json
  types/jwt-decode/v1/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Merge:Auto, Popular package

#49365 Update bottomBarHighlight type
  types/react-native-onboarding-swiper/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#49368 [lodash] Fix transform to accept readonly array
  types/lodash/common/object.d.ts
  types/lodash/lodash-tests.ts
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#49352 [spotify-wep-api-node] add `addToQueue` definition
  types/spotify-api/index.d.ts
  types/spotify-web-api-node/index.d.ts
  types/spotify-web-api-node/spotify-web-api-node-tests.ts
Labels: Edits multiple packages, Maintainer Approved, Merge:Auto, Perf: Same

#49355 Fix css-minimizer-webpack-plugin types to work with Webpack 5
  types/css-minimizer-webpack-plugin/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#48485 update(string-similarity): v4 and umd support
  types/string-similarity/index.d.ts
  types/string-similarity/test/string-similarity.global.ts
  types/string-similarity/test/string-similarity.module.ts
  types/string-similarity/tsconfig.json
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#48171 [hummus-recipe] Add missing RecipeOptions
  types/hummus-recipe/hummus-recipe-tests.ts
  types/hummus-recipe/index.d.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#49349 chore(asn1js): set package version number
  types/asn1js/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package, Untested Change

#49383 [@ember/routing] add metadata to RouteInfo
  types/ember__routing/-private/route-info-with-attributes.d.ts
  types/ember__routing/-private/route-info.d.ts
  types/ember__routing/test/router-service.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#48481 [serverless] add an ARN to function definition for launching SNS events
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#49386 [scriptable-ios]: Update for Scriptable v1.6.0
  types/scriptable-ios/index.d.ts
  types/scriptable-ios/scriptable-ios-tests.ts
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved, Perf: Same

#49351 mongodb/MongoError.code can be a string
  types/mongodb/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, Untested Change

#48889 react: Export type representing second argument of ForwardRefRenderFunction
  types/react/index.d.ts
  types/react/test/index.ts
Labels: Critical package, Merge:Auto, Owner Approved, Perf: Same

#49393 VS Code 1.51.0 Extension API
  types/vscode/index.d.ts
Labels: Perf: Same, Untested Change

#49394 [react-native] Add support for ref on Pressable
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Critical package, Owner Approved, Perf: Same

#49396 [applepayjs] Make detail and identifier required in shipping method
  types/applepayjs/applepayjs-tests.ts
  types/applepayjs/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49385 remove(incremental-dom): remove type
  notNeededPackages.json
  types/incremental-dom/incremental-dom-tests.ts
  types/incremental-dom/index.d.ts
  types/incremental-dom/tsconfig.json
  types/incremental-dom/tslint.json
Labels: Config Edit, Edits Infrastructure, Maintainer Approved, Merge:Auto

#49408 [yt-player] Update v3.5
  types/yt-player/index.d.ts
  types/yt-player/yt-player-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49384 update(minimist): simplify package
  types/minimist/index.d.ts
  types/minimist/minimist-tests.ts
  types/minimist/tsconfig.json
  types/minimist/tslint.json
Labels: Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same

#48495 [array-binarysearch.closest] Fix typo in closest tests
  types/array-binarysearch.closest/array-binarysearch.closest-tests.ts
Labels: Abandoned, Perf: Same

#49347 Bring gapi.client.sheets back
  notNeededPackages.json
  types/gapi.client.sheets/index.d.ts
  types/gapi.client.sheets/package.json
  types/gapi.client.sheets/tsconfig.json
  types/gapi.client.sheets/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Merge:Auto, New Definition, Untested Change

#49380 Update react-bootstrap-typeahead typings to include new Hint componen…
  types/react-bootstrap-typeahead/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Perf: Same, Untested Change

#49305 feat(js-gravatar): new definition
  types/js-gravatar/index.d.ts
  types/js-gravatar/js-gravatar-tests.ts
  types/js-gravatar/tsconfig.json
  types/js-gravatar/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48145 [segment-analytics]: update user().id() method to reflect undocumented functionality
  types/segment-analytics/index.d.ts
  types/segment-analytics/segment-analytics-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same, Popular package

#49273 [gulp-codecov] add definition
  types/gulp-codecov/gulp-codecov-tests.ts
  types/gulp-codecov/index.d.ts
  types/gulp-codecov/tsconfig.json
  types/gulp-codecov/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49330 [d3-array] Bump version number to v2.6
  types/d3-array/index.d.ts
Labels: Author is Owner, Maintainer Approved, Merge:Auto, Other Approved, Perf: Same, Popular package, Untested Change

#49406 [handbrake-js]: Add type definitions for handbrake-js module
  types/handbrake-js/handbrake-js-tests.ts
  types/handbrake-js/index.d.ts
  types/handbrake-js/tsconfig.json
  types/handbrake-js/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49405 [paypal-js] Document 'data-client-token' attribute
  types/paypal__paypal-js/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#49304 feat(words-to-time-converter): new definition
  types/words-to-time-converter/index.d.ts
  types/words-to-time-converter/tsconfig.json
  types/words-to-time-converter/tslint.json
  types/words-to-time-converter/words-to-time-converter-tests.ts
Labels: Maintainer Approved, Merge:Auto, New Definition

#49401 added promise-the-world
  types/promise-the-world/defer.d.ts
  types/promise-the-world/delay.d.ts
  types/promise-the-world/index.d.ts
  types/promise-the-world/mutex.d.ts
  types/promise-the-world/promise-the-world-tests.ts
  types/promise-the-world/queue.d.ts
  types/promise-the-world/tsconfig.json
  types/promise-the-world/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48871 feat: types for chai-quantifiers
  types/chai-quantifiers/chai-quantifiers-tests.ts
  types/chai-quantifiers/index.d.ts
  types/chai-quantifiers/tsconfig.json
  types/chai-quantifiers/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49277 Add types for elementary-circuits-directed-graph
  types/elementary-circuits-directed-graph/elementary-circuits-directed-graph-tests.ts
  types/elementary-circuits-directed-graph/index.d.ts
  types/elementary-circuits-directed-graph/tsconfig.json
  types/elementary-circuits-directed-graph/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49398 Add ContainerProps to react-select exports
  types/react-select/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, Untested Change

#48831 feat(express-requests-logger): new definition
  types/express-requests-logger/express-requests-logger-tests.ts
  types/express-requests-logger/index.d.ts
  types/express-requests-logger/tsconfig.json
  types/express-requests-logger/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48760 feat(express-delay-header): new definition
  types/express-delay-header/express-delay-header-tests.ts
  types/express-delay-header/index.d.ts
  types/express-delay-header/tsconfig.json
  types/express-delay-header/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48525 update(csurf): v1.11
  types/csurf/csurf-tests.ts
  types/csurf/index.d.ts
  types/csurf/tsconfig.json
  types/csurf/tslint.json
Labels: Maintainer Approved, Merge:Auto

#49378 [d3-array] Update types to v2.7
  types/d3-array/d3-array-tests.ts
  types/d3-array/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#49397 Fix broken RenewAuthOptions.responseType link
  types/auth0-js/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package, Untested Change

#48709 [license-checker] Update typings
  types/license-checker/index.d.ts
  types/license-checker/license-checker-tests.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#47190 Upgrade types for express-actuator@1.6.1
  types/express-actuator/express-actuator-tests.ts
  types/express-actuator/index.d.ts
Labels: Merge:Auto, Other Approved, Perf: Same

#49421 Update twine-sugarcube definitions to 2.33.3
  types/twine-sugarcube/test/ui.ts
  types/twine-sugarcube/ui.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved

#49387 [gestalt]: Update gestalt definition to be in sync with 14.26
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#49389 [text-to-svg] Add definitions
  types/text-to-svg/index.d.ts
  types/text-to-svg/text-to-svg-tests.ts
  types/text-to-svg/tsconfig.json
  types/text-to-svg/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49334 [bull-arena] Remove bull-arena heavy dependencies
  types/bull-arena/bull-arena-tests.ts
  types/bull-arena/index.d.ts
  types/bull-arena/package.json
Labels: Merge:Auto, Owner Approved, Perf: Same

#49434 update firefox-webext-browser to v82 and fix a bunch of stuff
  types/firefox-webext-browser/firefox-webext-browser-tests.ts
  types/firefox-webext-browser/index.d.ts
  types/firefox-webext-browser/tsconfig.json
Labels: Author is Owner, Merge:Auto, No Other Owners, Other Approved, Perf: Same

#49402 Add types for the eev package
  types/eev/eev-tests.ts
  types/eev/index.d.ts
  types/eev/tsconfig.json
  types/eev/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#48870 Add types for Skilja package (array chunker)
  types/skilja/index.d.ts
  types/skilja/skilja-tests.ts
  types/skilja/tsconfig.json
  types/skilja/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49363 [node] Catch up assert typesVersions <= 3.6
  types/node/assert.d.ts
  types/node/ts3.4/assert.d.ts
  types/node/tslint.json
  types/node/v12/ts3.3/assert.d.ts
  types/node/v12/tslint.json
Labels: Config Edit, Critical package, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Untested Change

#49126 Add types for branca
  types/branca/branca-tests.ts
  types/branca/index.d.ts
  types/branca/tsconfig.json
  types/branca/tslint.json
Labels: Maintainer Approved, Merge:Auto, New Definition

#49426 Create definition for use-synced-local-storage@1.0
  types/use-synced-local-storage/index.d.ts
  types/use-synced-local-storage/tsconfig.json
  types/use-synced-local-storage/tslint.json
  types/use-synced-local-storage/use-synced-local-storage-tests.ts
Labels: New Definition

#49424 remove(diff2html): remove package
  notNeededPackages.json
  types/diff2html/diff2html-tests.ts
  types/diff2html/index.d.ts
  types/diff2html/tsconfig.json
  types/diff2html/tslint.json
Labels: Config Edit, Edits Infrastructure, Owner Approved

#49381 Updated prosemirror-model to include `hasRequiredAttrs` to `NodeType`
  types/prosemirror-model/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Untested Change

#49423 IITC (Ingress Intel Total Conversation) types
  types/iitc/core/android.d.ts
  types/iitc/core/artifact.d.ts
  types/iitc/core/boot.d.ts
  types/iitc/core/chat.d.ts
  types/iitc/core/constants.d.ts
  types/iitc/core/data_cache.d.ts
  types/iitc/core/dialog.d.ts
  types/iitc/core/entity_decode.d.ts
  types/iitc/core/entity_info.d.ts
  types/iitc/core/extract_niantic_parameters.d.ts
  types/iitc/core/game_status.d.ts
  types/iitc/core/hooks.d.ts
  types/iitc/core/idle.d.ts
  types/iitc/core/iitctypes.d.ts
  types/iitc/core/inteltypes.d.ts
  types/iitc/core/location.d.ts
  types/iitc/core/main.d.ts
  types/iitc/core/map_data_calc_tools.d.ts
  types/iitc/core/map_data_debug.d.ts
  types/iitc/core/map_data_render.d.ts
  types/iitc/core/map_data_request.d.ts
  types/iitc/core/ornaments.d.ts
  types/iitc/core/panes.d.ts
  types/iitc/core/player_names.d.ts
  types/iitc/core/portal_data.d.ts
  types/iitc/core/portal_detail.d.ts
  types/iitc/core/portal_detail_display.d.ts
  types/iitc/core/portal_detail_display_tools.d.ts
  types/iitc/core/portal_highlighter.d.ts
  types/iitc/core/portal_info.d.ts
  types/iitc/core/portal_marker.d.ts
  types/iitc/core/redeeming.d.ts
  types/iitc/core/region_scoreboard.d.ts
  types/iitc/core/request_handling.d.ts
  types/iitc/core/search.d.ts
  types/iitc/core/send_request.d.ts
  types/iitc/core/smartphone.d.ts
  types/iitc/core/utils_file.d.ts
  types/iitc/core/utils_misc.d.ts
  types/iitc/iitc-tests.ts
  types/iitc/index.d.ts
  types/iitc/leafletExtentions/index.d.ts
  types/iitc/package.json
  types/iitc/tsconfig.json
  types/iitc/tslint.json
Labels: New Definition

#49293 Remove highlight.js typings
  notNeededPackages.json
  types/highlight.js/highlight.js-tests.ts
  types/highlight.js/index.d.ts
  types/highlight.js/tsconfig.json
  types/highlight.js/tslint.json
  types/highlight.js/v7/index.d.ts
  types/highlight.js/v7/tsconfig.json
  types/highlight.js/v7/tslint.json
  types/highlightjs/index.d.ts
  types/highlightjs/package.json
  types/highlightjs/tslint.json
  types/markdown-it/package.json
  types/remarkable/package.json
Labels: Config Edit, Edits Infrastructure, Edits multiple packages, Other Approved, Owner Approved, Perf: Worse, Popular package

#49230 Update index.d.ts in react-cytoscape
  types/react-cytoscapejs/index.d.ts
Labels: Maintainer Approved, Merge:Auto, Merge:YSYL, No Other Owners, Perf: Same, Untested Change

#49418 Add new types: Cookie clicker
  types/cookieclicker/cookieclicker-tests.ts
  types/cookieclicker/index.d.ts
  types/cookieclicker/tsconfig.json
  types/cookieclicker/tslint.json
Labels: New Definition, Other Approved

#49414 remove(comment-json): remove definition
  notNeededPackages.json
  types/comment-json/comment-json-tests.ts
  types/comment-json/index.d.ts
  types/comment-json/tsconfig.json
  types/comment-json/tslint.json
Labels: Config Edit, Edits Infrastructure

#49411 toastify-js types definition
  types/toastify-js/index.d.ts
  types/toastify-js/toastify-js-tests.ts
  types/toastify-js/tsconfig.json
  types/toastify-js/tslint.json
Labels: New Definition

#49395 Add types for @rails/ujs
  types/rails__ujs/features/confirm.d.ts
  types/rails__ujs/features/disable.d.ts
  types/rails__ujs/features/method.d.ts
  types/rails__ujs/features/remote.d.ts
  types/rails__ujs/index.d.ts
  types/rails__ujs/rails__ujs-tests.ts
  types/rails__ujs/start.d.ts
  types/rails__ujs/tsconfig.json
  types/rails__ujs/tslint.json
  types/rails__ujs/utils/ajax.d.ts
  types/rails__ujs/utils/csp.d.ts
  types/rails__ujs/utils/csrf.d.ts
  types/rails__ujs/utils/dom.d.ts
  types/rails__ujs/utils/event.d.ts
  types/rails__ujs/utils/form.d.ts
Labels: New Definition, Other Approved

#48561 [koa-generic-session] Add the missing `cookie.overwite` field.
  types/koa-generic-session/index.d.ts
  types/koa-generic-session/koa-generic-session-tests.ts
Labels: Abandoned, Perf: Same

#47743 update(mailparser): version bump and minor changes
  types/mailparser/index.d.ts
  types/mailparser/mailparser-tests.ts
  types/mailparser/tslint.json
Labels: Abandoned, Perf: Same

#48286 update(useragent): v2.3
  types/useragent/index.d.ts
  types/useragent/tslint.json
  types/useragent/useragent-tests.ts
Labels: Abandoned, Perf: Same

#47955 update(ratelimiter): version 3.4 update and other changes
  types/ratelimiter/index.d.ts
  types/ratelimiter/ratelimiter-tests.ts
  types/ratelimiter/tslint.json
Labels: Abandoned, Perf: Same

#46933 update(js-beautify): re-export types for CJS and minor version bump
  types/js-beautify/index.d.ts
  types/js-beautify/js-beautify-tests.ts
  types/js-beautify/tslint.json
Labels: Abandoned, Perf: Same

#48535 [@types/wait-on] add options for 5.2
  types/wait-on/index.d.ts
  types/wait-on/wait-on-tests.ts
Labels: Abandoned, Perf: Same

#49003 types for simpleddp
  types/simpleddp/classes/ddpCollection.d.ts
  types/simpleddp/classes/ddpEventListener.d.ts
  types/simpleddp/classes/ddpOnChange.d.ts
  types/simpleddp/classes/ddpReactiveCollection.d.ts
  types/simpleddp/classes/ddpReactiveDocument.d.ts
  types/simpleddp/classes/ddpReducer.d.ts
  types/simpleddp/classes/ddpSubscription.d.ts
  types/simpleddp/ddpEvent.d.ts
  types/simpleddp/index.d.ts
  types/simpleddp/options.d.ts
  types/simpleddp/simpleddp-tests.ts
  types/simpleddp/tsconfig.json
  types/simpleddp/tslint.json
Labels: New Definition

#48905 [@types/chroma-js] Add missing color.mix method
  types/chroma-js/chroma-js-tests.ts
  types/chroma-js/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#49415 [d3] Bump types to v6.1
  types/d3/index.d.ts
Labels: Author is Owner, Perf: Same, Popular package, Untested Change

#49416 Added definitions for Common class
  types/matter-js/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#49422 [ws] Add request argument in handleUpgrade
  types/ws/index.d.ts
Labels: Critical package, Perf: Same, Untested Change

#49428 Add isDisabled to IndicatorProps
  types/react-select/src/components/indicators.d.ts
Labels: Perf: Same, Popular package, Untested Change

#49430 add options for Container.wait
  types/dockerode/index.d.ts
Labels: Other Approved, Owner Approved, Perf: Same, Untested Change

#46576 Rewrite (thereby fix) types for express-session (second attempt)
  types/cassandra-store/index.d.ts
  types/connect-azuretables/index.d.ts
  types/connect-pg-simple/connect-pg-simple-tests.ts
  types/connect-pg-simple/index.d.ts
  types/connect-redis/index.d.ts
  types/easy-session/easy-session-tests.ts
  types/easy-session/index.d.ts
  types/express-session/express-session-tests.ts
  types/express-session/index.d.ts
  types/express-socket.io-session/express-socket.io-session-tests.ts
  types/express-socket.io-session/index.d.ts
  types/passport.socketio/package.json
  types/passport.socketio/passport.socketio-tests.ts
  types/passport/passport-tests.ts
Labels: Config Edit, Edits multiple packages, Maintainer Approved, Merge:Auto, Owner Approved, Perf: Same, Popular package

#49439 update(toastify-js): UMD support, missing options
  types/toastify-js/index.d.ts
  types/toastify-js/toastify-js-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49435 Correct the type of dat.gui __folders
  types/dat.gui/dat.gui-tests.ts
  types/dat.gui/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#48493 [nodemailer-mailgun-transport]: add alias apiKey
  types/nodemailer-mailgun-transport/index.d.ts
  types/nodemailer-mailgun-transport/nodemailer-mailgun-transport-tests.ts
Labels: Maintainer Approved, Merge:Auto, Perf: Same

#48961 [alexa-sdk] Remove types
  types/alexa-sdk/alexa-sdk-tests.ts
  types/alexa-sdk/index.d.ts
  types/alexa-sdk/tsconfig.json
  types/alexa-sdk/tslint.json
Labels: Config Edit, Maintainer Approved, Merge:Auto

#49165 Updates type definitions from sharp 0.26.0 to support animated GIF and WEBP formats.
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#49437 [scriptable-ios]: change addSpacer to accept no parameters
  types/scriptable-ios/index.d.ts
  types/scriptable-ios/scriptable-ios-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#49445 [@brainhubeu/react-carousel] fix: DotsProps missing className
  types/brainhubeu__react-carousel/brainhubeu__react-carousel-tests.tsx
  types/brainhubeu__react-carousel/index.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49449 [mapbox-gl] map.addImage() supports ImageBitmap as image
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Merge:Auto, Owner Approved, Popular package

#49452 [mapbox-gl] Add Expression type to *-sort-key properties
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Merge:Auto, Owner Approved, Perf: Same, Popular package

#49392 fundamental-react: update new Tile type and tests
  types/fundamental-react/fundamental-react-tests.tsx
  types/fundamental-react/lib/Tile/Tile.d.ts
Labels: Merge:Auto, Owner Approved, Perf: Same

#49432 Update snowpack-env to fix bug introduced in last change
  types/snowpack-env/index.d.ts
  types/snowpack-env/snowpack-env-tests.ts
Labels: Author is Owner, Merge:Auto, Owner Approved

#49451 cookieclicker: Fix minor mistakes
  types/cookieclicker/cookieclicker-tests.ts
  types/cookieclicker/index.d.ts
Labels: Author is Owner, Merge:Auto, Owner Approved, Perf: Same

#49457 fix(js-beautify): correct exported lib types
  types/gulp-json-editor/index.d.ts
  types/js-beautify/index.d.ts
  types/js-beautify/js-beautify-tests.ts
Labels: Edits multiple packages, Other Approved, Owner Approved, Perf: Same, Popular package
