Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-04, with the labels that each got.

#43333 chore(deps): Update dependency prettier to v2
  .prettierrc.json
  package.json
Labels: Other Approved, Unowned

#43539 [aws-lambda]: Fix definition of APIGatewayRequestAuthorizerEvent
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/trigger/api-gateway-authorizer.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43205 [ramda] Update equals to allow __ (placeholder) signature
  types/ramda/index.d.ts
  types/ramda/test/equals-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#43359 Ramda: R.into add case of converting types: R.into<From, To>([], transducer, sourceList);
  types/ramda/index.d.ts
  types/ramda/ramda-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#43528 express-http-proxy: proxyReqPathResolver can also return Promise<string>
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Merge:Express, Owner Approved

#43534 Allow RefObject<T> in reach__router's innerRef.
  types/reach__router/index.d.ts
  types/reach__router/reach__router-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#43525 update urijs types
  types/urijs/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43535 [sortablejs] adds missing static properties to Sortable
  types/sortablejs/index.d.ts
  types/sortablejs/sortablejs-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43538 clownface: subject traversal only find blank and named nodes
  types/clownface/clownface-tests.ts
  types/clownface/index.d.ts
  types/clownface/lib/Clownface.d.ts
Labels: Author is Owner, Merge:Express

#43548 added interfaces to exported clients
  types/sparql-http-client/ParsingClient.d.ts
  types/sparql-http-client/StreamClient.d.ts
Labels: Author is Owner, Merge:Express

#43152 QUnit: Added missing Promise returns
  types/qunit/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43398 Adds types for recurly.js
  types/recurly__recurly-js/index.d.ts
  types/recurly__recurly-js/test/3d-secure.ts
  types/recurly__recurly-js/test/adyen.ts
  types/recurly__recurly-js/test/apple-pay.ts
  types/recurly__recurly-js/test/bank-account.ts
  types/recurly__recurly-js/test/configure.ts
  types/recurly__recurly-js/test/elements.ts
  types/recurly__recurly-js/test/gift-card.ts
  types/recurly__recurly-js/test/paypal.ts
  types/recurly__recurly-js/test/pricing/checkout.ts
  types/recurly__recurly-js/test/pricing/subscription.ts
  types/recurly__recurly-js/test/token/elements.ts
  types/recurly__recurly-js/test/token/hosted-field.ts
  types/recurly__recurly-js/test/validate.ts
  types/recurly__recurly-js/tsconfig.json
  types/recurly__recurly-js/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43554 Remove mrdziuban from ramda contributors.
  types/ramda/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#43540 [react-calendar] Init typings
  types/react-calendar/index.d.ts
  types/react-calendar/react-calendar-tests.tsx
  types/react-calendar/tsconfig.json
  types/react-calendar/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43542 Add is-base64
  types/is-base64/index.d.ts
  types/is-base64/is-base64-tests.ts
  types/is-base64/tsconfig.json
  types/is-base64/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43541 New package for Web Locks API definitions
  types/web-locks-api/index.d.ts
  types/web-locks-api/tsconfig.json
  types/web-locks-api/tslint.json
  types/web-locks-api/web-locks-api-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#43551 feat: add definition for looper
  types/looper/index.d.ts
  types/looper/looper-tests.ts
  types/looper/tsconfig.json
  types/looper/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43550 Add location type arg for query params to route definition v3
  types/react-router/v3/lib/Router.d.ts
  types/react-router/v3/react-router-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#43549 feat: Add `cssom`
  types/cssom/index.d.ts
  types/cssom/test/cssom.cjs.test.ts
  types/cssom/test/cssom.umd.test.ts
  types/cssom/tsconfig.json
  types/cssom/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Where is Travis?

#43487 Add jest-cucumber-fusion
  types/jest-cucumber-fusion/index.d.ts
  types/jest-cucumber-fusion/jest-cucumber-fusion-tests.ts
  types/jest-cucumber-fusion/package.json
  types/jest-cucumber-fusion/tsconfig.json
  types/jest-cucumber-fusion/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Where is Travis?

#43558 video.js: ensure example class-based plugin works
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43557 clownface: fix addIn/addOut & in/out signatures
  types/clownface/clownface-tests.ts
  types/clownface/index.d.ts
  types/clownface/lib/Clownface.d.ts
Labels: Author is Owner, Merge:Express

#43452 Add types for react-audio-player
  types/react-audio-player/index.d.ts
  types/react-audio-player/react-audio-player-tests.tsx
  types/react-audio-player/tsconfig.json
  types/react-audio-player/tslint.json
Labels: New Definition, Revision needed, Where is Travis?

#43460 [webtorrent] add missing property "progress" on TorrentFile
  types/webtorrent/index.d.ts
Labels: Revision needed

#43516 Added react-native-datawedge-intents
  types/react-native-datawedge-intents/index.d.ts
  types/react-native-datawedge-intents/react-native-datawedge-intents-tests.ts
  types/react-native-datawedge-intents/tsconfig.json
  types/react-native-datawedge-intents/tslint.json
Labels: New Definition, Revision needed

#43502 Added types for parse-full-name
  types/parse-full-name/index.d.ts
  types/parse-full-name/parse-full-name-tests.ts
  types/parse-full-name/tsconfig.json
  types/parse-full-name/tslint.json
Labels: New Definition, Revision needed

#43560 [screeps] Updated types for 2020-03-24 game update
  types/screeps/index.d.ts
  types/screeps/screeps-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43555 Add @sinonjs/fake-timers redirect to @testing-library/cypress
  types/testing-library__cypress/index.d.ts
  types/testing-library__cypress/tsconfig.json
  types/testing-library__dom/index.d.ts
  types/testing-library__react/index.d.ts
  types/testing-library__vue/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43425 feat(table): update type definitions for v5.0
  types/table/index.d.ts
  types/table/table-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#43561 Update index.d.ts
  types/vhost/index.d.ts
Labels: Unowned

#43579 feat(node): Update to v13.11
  types/node/async_hooks.d.ts
  types/node/fs.d.ts
  types/node/index.d.ts
  types/node/os.d.ts
  types/node/test/async_hooks.ts
  types/node/test/fs.ts
  types/node/test/os.ts
  types/node/test/tls.ts
  types/node/test/vm.ts
  types/node/tls.d.ts
  types/node/ts3.5/node-tests.ts
  types/node/ts3.5/wasi.d.ts
  types/node/vm.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#43576 [prettier] Update to v2
  types/prettier/index.d.ts
  types/prettier/parser-babel.d.ts
  types/prettier/prettier-tests.ts
  types/prettier/standalone.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package

#43564 Remove types for react-native-responsive-dimensions
  notNeededPackages.json
  types/react-native-responsive-dimensions/index.d.ts
  types/react-native-responsive-dimensions/react-native-responsive-dimensions-tests.ts
  types/react-native-responsive-dimensions/tsconfig.json
  types/react-native-responsive-dimensions/tslint.json
Labels: Author is Owner, Merge:Express

#43531 [jest] add mock.getMockImplementation type
  types/jest/index.d.ts
  types/jest/jest-tests.ts
  types/jest/package.json
Labels: Merge:Express, Owner Approved, Popular package

#43566 Add params and location query type args to withRouter
  types/react-router/v3/index.d.ts
  types/react-router/v3/lib/withRouter.d.ts
  types/react-router/v3/react-router-tests.tsx
Labels: Merge:Express, Owner Approved, Popular package

#43469 update(ejs): `beautify` option from 3.0.2
  types/ejs/index.d.ts
  types/ejs/test/ejs.cjs.test.ts
  types/ejs/test/ejs.umd.test.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Popular package, Revision needed

#43547 [signale] Add missing properties
  types/signale/index.d.ts
Labels: Merge:Express, Owner Approved

#43572 feat(webidl2): Update to v23.11
  types/webidl2/index.d.ts
  types/webidl2/tsconfig.json
  types/webidl2/webidl2-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#43571 Add node-apple-receipt-verify
  types/node-apple-receipt-verify/index.d.ts
  types/node-apple-receipt-verify/node-apple-receipt-verify-tests.ts
  types/node-apple-receipt-verify/tsconfig.json
  types/node-apple-receipt-verify/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43562 feat(@markedjs/html-differ): new type definition v3.0
  types/markedjs__html-differ/OTHER_FILES.txt
  types/markedjs__html-differ/index.d.ts
  types/markedjs__html-differ/lib/logger.d.ts
  types/markedjs__html-differ/markedjs__html-differ-tests.ts
  types/markedjs__html-differ/tsconfig.json
  types/markedjs__html-differ/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43305 [raphael] Fix typings and update for 2.3
  types/raphael/index.d.ts
  types/raphael/raphael-tests.ts
  types/raphael/test/raphael-tests-api.ts
  types/raphael/test/raphael-tests-font.ts
  types/raphael/test/raphael-tests-global.ts
  types/raphael/test/raphael-tests-module.ts
  types/raphael/test/raphael-tests-official.ts
  types/raphael/test/raphael-tests-old.ts
  types/raphael/test/raphael-tests-plugin.ts
  types/raphael/tsconfig.json
  types/raphael/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#43435 Add MathNode.content optional property
  types/mathjs/index.d.ts
  types/mathjs/mathjs-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#43585 LZString.decompress* returns null for invalid inputs
  types/lz-string/index.d.ts
  types/lz-string/lz-string-tests.ts
Labels: Merge:Express, Owner Approved

#43439 [styled-system__should-forward-prop] Add missing props type
  types/styled-system__should-forward-prop/index.d.ts
  types/styled-system__should-forward-prop/styled-system__should-forward-prop-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43575 [geoip-lite] more accurate Lookup type
  types/geoip-lite/index.d.ts
Labels: Unowned

#43473 [CodeMirror] add normalizeKeyMap function
  types/codemirror/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Popular package

#43580 [react] Fix capitalization of playsInline video prop
  types/react/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43417 Ghost content api ghostdata fix
  types/tryghost__content-api/index.d.ts
Labels: Revision needed

#43510 feat: added passport-instagram type definitions
  types/passport-instagram/index.d.ts
  types/passport-instagram/passport-instagram-tests.ts
  types/passport-instagram/tsconfig.json
  types/passport-instagram/tslint.json
Labels: New Definition, Revision needed

#43570 [video.js] Add Player.MediaObject, loadMedia, getMedia
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Merge:Express, Owner Approved

#43586 Update react-tagsinput Type Mappings to use Generics instead of <any>…
  types/react-tagsinput/index.d.ts
Labels: Merge:Express, Owner Approved

#43563 Ember Data Adapter: export default AdapterError
  types/ember-data__adapter/error.d.ts
  types/ember-data__adapter/test/error.ts
Labels: Merge:Express, Owner Approved

#43595 feat: updated passport-instagram type definitions after reading it's source documentation more carefully
  types/passport-instagram/index.d.ts
  types/passport-instagram/passport-instagram-tests.ts
Labels: Author is Owner, Merge:Express

#43584 fix(chai-dom): add missing visible assertion
  types/chai-dom/chai-dom-tests.ts
  types/chai-dom/index.d.ts
Labels: Merge:Express, Owner Approved

#43433 fix(braintree-web): add missing propertes to factory methods
  types/braintree-web/index.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
  types/braintree-web/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#43613 Updated jest pinned dependencies
  types/expect-puppeteer/index.d.ts
  types/frisby/index.d.ts
  types/jest-axe/index.d.ts
  types/jest-image-snapshot/index.d.ts
  types/jest-in-case/index.d.ts
  types/jest-json-schema/index.d.ts
  types/jest-matcher-one-of/index.d.ts
  types/jest-plugin-context/index.d.ts
  types/jest-when/index.d.ts
  types/jest/index.d.ts
  types/jest/package.json
  types/testing-library__jest-dom/index.d.ts
  types/wordpress__jest-console/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#43615 [jest] Return this from mockClear and mockReset
  types/jest/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43617 [@babel/plugin-transform-runtime] Add types
  types/babel__plugin-transform-runtime/babel__plugin-transform-runtime-tests.ts
  types/babel__plugin-transform-runtime/index.d.ts
  types/babel__plugin-transform-runtime/tsconfig.json
  types/babel__plugin-transform-runtime/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43620 feat(express-fileupload): `uploadTimeout` added
  types/express-fileupload/express-fileupload-tests.ts
  types/express-fileupload/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43614 [mrz] Add types
  types/mrz/index.d.ts
  types/mrz/mrz-tests.ts
  types/mrz/tsconfig.json
  types/mrz/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43612 [@babel/preset-env] Add types
  types/babel__preset-env/babel__preset-env-tests.ts
  types/babel__preset-env/index.d.ts
  types/babel__preset-env/tsconfig.json
  types/babel__preset-env/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43608 Adds pdf-fill-form's module and types
  types/pdf-fill-form/index.d.ts
  types/pdf-fill-form/pdf-fill-form-tests.ts
  types/pdf-fill-form/tsconfig.json
  types/pdf-fill-form/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43602 feat: added node-pdftk definitions
  types/node-pdftk/index.d.ts
  types/node-pdftk/node-pdftk-tests.ts
  types/node-pdftk/tsconfig.json
  types/node-pdftk/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43606 feat: Add `webidl2js`
  types/webidl2js/index.d.ts
  types/webidl2js/test/convert-idl.ts
  types/webidl2js/tsconfig.json
  types/webidl2js/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43611 feat: Add `html‑encoding‑sniffer`
  types/html-encoding-sniffer/html-encoding-sniffer-tests.ts
  types/html-encoding-sniffer/index.d.ts
  types/html-encoding-sniffer/tsconfig.json
  types/html-encoding-sniffer/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43532 passport-http-bearer: Make message field optional
  types/passport-http-bearer/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#43603 rsocket-flowable - adds Single.never()
  types/rsocket-flowable/Single.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#43607 feat: Add `cssstyle`
  types/cssstyle/cssstyle-tests.ts
  types/cssstyle/index.d.ts
  types/cssstyle/tsconfig.json
  types/cssstyle/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Where is Travis?

#43556 reach__router: Correct type for `ref` in `Link<TState>`.
  types/reach__router/index.d.ts
  types/reach__router/reach__router-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#43568 [react-query] Few improvements
  types/react-query/index.d.ts
  types/react-query/react-query-tests.ts
Labels: Author is Owner, Revision needed

#43565 Feature/add typings for feflow cli
  types/feflow__cli/feflow__cli-tests.ts
  types/feflow__cli/index.d.ts
  types/feflow__cli/tsconfig.json
  types/feflow__cli/tslint.json
Labels: New Definition, Revision needed

#43155 [react-bootstrap-table-next] Add typing for react-bootstrap-table-next
  types/react-bootstrap-table-next/index.d.ts
  types/react-bootstrap-table-next/react-bootstrap-table-next-tests.tsx
  types/react-bootstrap-table-next/tsconfig.json
  types/react-bootstrap-table-next/tslint.json
  types/react-bootstrap-table2-filter/index.d.ts
  types/react-bootstrap-table2-filter/react-bootstrap-table2-filter-tests.tsx
  types/react-bootstrap-table2-filter/tsconfig.json
  types/react-bootstrap-table2-filter/tslint.json
  types/react-bootstrap-table2-paginator/index.d.ts
  types/react-bootstrap-table2-paginator/react-bootstrap-table2-paginator-tests.tsx
  types/react-bootstrap-table2-paginator/tsconfig.json
  types/react-bootstrap-table2-paginator/tslint.json
  types/react-bootstrap-table2-toolkit/index.d.ts
  types/react-bootstrap-table2-toolkit/react-bootstrap-table2-toolkit-tests.tsx
  types/react-bootstrap-table2-toolkit/tsconfig.json
  types/react-bootstrap-table2-toolkit/tslint.json
Labels: New Definition, Revision needed

#43622 Add can-autoplay types
  types/can-autoplay/can-autoplay-tests.ts
  types/can-autoplay/index.d.ts
  types/can-autoplay/tsconfig.json
  types/can-autoplay/tslint.json
Labels: New Definition, Revision needed

#43592 feat(tsc-watch): new type definition v4.2
  types/tsc-watch/client.d.ts
  types/tsc-watch/index.d.ts
  types/tsc-watch/lib/client.d.ts
  types/tsc-watch/tsc-watch-tests.ts
  types/tsc-watch/tsconfig.json
  types/tsc-watch/tslint.json
Labels: New Definition, Revision needed

#43599 Add type definitions for git-diff-parser module
  types/git-diff-parser/git-diff-parser-tests.ts
  types/git-diff-parser/index.d.ts
  types/git-diff-parser/tsconfig.json
  types/git-diff-parser/tslint.json
Labels: New Definition, Revision needed

#43675 fix(sparql-http-client): the endpointUrl is optional
  types/sparql-http-client/Endpoint.d.ts
  types/sparql-http-client/sparql-http-client-tests.ts
Labels: Author is Owner, Merge:Express

#43677 [twilio-video] fix support for VP8 simulcast
  types/twilio-video/index.d.ts
  types/twilio-video/twilio-video-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43662 [scriptable-ios] Updated typings to 1.4
  types/scriptable-ios/index.d.ts
Labels: Author is Owner, Merge:Express

#43638 [ot] Update ot types
  types/ot/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43524 [@types/rebass]: Add font style props to Text and Heading components
  types/rebass/index.d.ts
  types/rebass/rebass-tests.tsx
Labels: Merge:Express, Owner Approved

#43635 Update index.d.ts to add rawErrors to the widget props
  types/react-jsonschema-form/index.d.ts
Labels: Merge:Express, Owner Approved

#43663 Add definitions for json2csv v5.0
  types/json2csv/JSON2CSVAsyncParser.d.ts
  types/json2csv/JSON2CSVBase.d.ts
  types/json2csv/JSON2CSVTransform.d.ts
  types/json2csv/index.d.ts
  types/json2csv/json2csv-tests.ts
  types/json2csv/transforms/base.d.ts
  types/json2csv/transforms/flatten.d.ts
  types/json2csv/transforms/index.d.ts
  types/json2csv/transforms/unwind.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43604 refactor: use interface merging to simplify class declarations
  types/clownface/clownface-tests.ts
  types/clownface/lib/Clownface.d.ts
  types/clownface/lib/Context.d.ts
  types/rdf-ext/lib/DataFactory.d.ts
  types/rdf-js/index.d.ts
  types/rdfjs__dataset/DatasetCore.d.ts
  types/sparql-http-client/BaseClient.d.ts
  types/sparql-http-client/Endpoint.d.ts
  types/sparql-http-client/ParsingQuery.d.ts
  types/sparql-http-client/RawQuery.d.ts
  types/sparql-http-client/ResultParser.d.ts
  types/sparql-http-client/StreamQuery.d.ts
  types/sparql-http-client/StreamStore.d.ts
Labels: Merge:Express, Owner Approved

#43671 Fix the type of lines of lyric-parser
  types/lyric-parser/index.d.ts
Labels: Merge:Express, Owner Approved

#43660 dependency-tree: add tsConfig to options
  types/dependency-tree/dependency-tree-tests.ts
  types/dependency-tree/index.d.ts
Labels: Merge:Express, Owner Approved

#43642 [node-notifier] Enable strictNullChecks
  types/node-notifier/v5/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#43653 fix(tcp-ping): Fix incorrect typings for probe method
  types/tcp-ping/index.d.ts
  types/tcp-ping/tcp-ping-tests.ts
Labels: Merge:Express, Owner Approved

#43624 feat(eslint): update types to 6.8
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
  types/eslint/ts3.1/eslint-tests.ts
  types/eslint/ts3.1/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43627 @babel/traverse: Refine types for unshift/pushcontainer and insertAfter/Before
  types/babel__traverse/babel__traverse-tests.ts
  types/babel__traverse/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43639 [xregexp] Enable strictNullChecks
  types/xregexp/tsconfig.json
Labels: Merge:Express, Owner Approved, Popular package

#43530 [@types/ldapjs] Callback error arguments can be null
  types/ldapjs/index.d.ts
Labels: Merge:Express, Owner Approved

#43521 correct parameter name for secp256k1 API v4.0
  types/secp256k1/index.d.ts
Labels: Merge:Express, Owner Approved

#43578 secure-json-parse: add missing option
  types/secure-json-parse/index.d.ts
Labels: Merge:Express, Owner Approved

#43674 Add missing strategy options to StrategyOptionsBase typing
  types/passport-oauth2/index.d.ts
  types/passport-oauth2/passport-oauth2-tests.ts
Labels: Merge:Express, Owner Approved

#43263 Adding types for js-worker-search
  types/js-worker-search/index.d.ts
  types/js-worker-search/js-worker-search-tests.ts
  types/js-worker-search/tsconfig.json
  types/js-worker-search/tslint.json
Labels: New Definition, Revision needed

#43386 [stream-to-promise]: add Duplex stream overload
  types/stream-to-promise/index.d.ts
Labels: Revision needed

#42949 [sharedb] Enable noImplicitThis
  types/sharedb/tsconfig.json
Labels: Owner Approved, Revision needed

#43655 fix(plotly.js): missing Icon optional fields
  types/plotly.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43636 fix(plotly.js): fix minor errors
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#43633 [analytics-node] Enforce either userId or anonymousId as identifiers
  package.json
  types/analytics-node/analytics-node-tests.ts
  types/analytics-node/index.d.ts
Labels: Merge:Express, Owner Approved

#43681 Adjusted types for mergeTags property of react-email-editor
  types/react-email-editor/index.d.ts
  types/react-email-editor/react-email-editor-tests.tsx
Labels: Merge:Express, Owner Approved

#43686 [jsonwebtoken make callbacks nullable
  types/jsonwebtoken/index.d.ts
  types/jsonwebtoken/jsonwebtoken-tests.ts
  types/sc-auth/sc-auth-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#43682 [swiper] Update swiper typings to v5.3
  .github/CODEOWNERS
  types/swiper/index.d.ts
  types/swiper/swiper-tests.ts
Labels: Merge:Express, Owner Approved

#43664 mongodb: Refactor the types for ChangeStreams
  types/mongodb/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#43661 OverlayScrollbars version 1.12.0
  types/overlayscrollbars/index.d.ts
Labels: Author is Owner, Merge:Express

#43673 Series Gauge missing field data
  types/echarts/options/series/gauge.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43545 @types/intercom-client messages definitions
  types/intercom-client/Message.d.ts
  types/intercom-client/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43687 [@types/relay-runtime]: Fix a couple optional fields
  types/relay-runtime/lib/util/NormalizationNode.d.ts
Labels: Awaiting reviewer feedback

#43679 [react-native] Add module DevSettings
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Awaiting reviewer feedback, Popular package

#43667 Add buffer-json
  types/buffer-json/buffer-json-tests.ts
  types/buffer-json/index.d.ts
  types/buffer-json/tsconfig.json
  types/buffer-json/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43659 feat(fast-isnumeric): new type definition v1.1
  types/fast-isnumeric/fast-isnumeric-tests.ts
  types/fast-isnumeric/index.d.ts
  types/fast-isnumeric/tsconfig.json
  types/fast-isnumeric/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43651 [@hapi/call] ] new definition
  types/hapi__call/hapi__call-tests.ts
  types/hapi__call/index.d.ts
  types/hapi__call/tsconfig.json
  types/hapi__call/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43544 [gapi.client] replace PromiseLike with Promise
  types/gapi.client/index.d.ts
  types/gapi.client/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL

#43672 fix: nullable value for node-pdftk output method
  types/node-pdftk/index.d.ts
  types/node-pdftk/node-pdftk-tests.ts
Labels: Unowned

#43522 Update node-gettext typings to v3.0.0
  types/node-gettext/index.d.ts
  types/node-gettext/node-gettext-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43293 [gapi.client.people] Update Google People API
  types/gapi.client.people/gapi.client.people-tests.ts
  types/gapi.client.people/index.d.ts
  types/gapi.client.people/readme.md
  types/gapi.client.people/tsconfig.json
  types/gapi.client.people/tslint.json
Labels: Revision needed

#43432 Adding type definitions for aws-kcl library
  types/aws-kcl/aws-kcl-tests.ts
  types/aws-kcl/index.d.ts
  types/aws-kcl/tsconfig.json
  types/aws-kcl/tslint.json
Labels: New Definition, Revision needed

#43503 [brainhubeu__react-carousel] update API to 1.13.20
  types/brainhubeu__react-carousel/brainhubeu__react-carousel-tests.tsx
  types/brainhubeu__react-carousel/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43448 [jsforce] Add missing jsforce connection types
  types/jsforce/connection.d.ts
  types/jsforce/index.d.ts
  types/jsforce/jsforce-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#43515 datatables.net : The API constructor now accepts a parameter of type SettingsLegacy (https://datatables.net/reference/type/DataTables.Settings)
  types/datatables.net/datatables.net-tests.ts
  types/datatables.net/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43504 mixpanel-browser: Add default export
  types/mixpanel-browser/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43506 mixpanel-browser: update type for 2.35.0
  types/mixpanel-browser/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43499 [validator] export validator function argument types from lib/* files
  types/validator/index.d.ts
  types/validator/lib/isAlpha.d.ts
  types/validator/lib/isAlphanumeric.d.ts
  types/validator/lib/isByteLength.d.ts
  types/validator/lib/isCurrency.d.ts
  types/validator/lib/isDecimal.d.ts
  types/validator/lib/isEmail.d.ts
  types/validator/lib/isEmpty.d.ts
  types/validator/lib/isFQDN.d.ts
  types/validator/lib/isFloat.d.ts
  types/validator/lib/isHash.d.ts
  types/validator/lib/isIP.d.ts
  types/validator/lib/isISBN.d.ts
  types/validator/lib/isISO8601.d.ts
  types/validator/lib/isISSN.d.ts
  types/validator/lib/isIdentityCard.d.ts
  types/validator/lib/isInt.d.ts
  types/validator/lib/isLength.d.ts
  types/validator/lib/isMACAddress.d.ts
  types/validator/lib/isMobilePhone.d.ts
  types/validator/lib/isNumeric.d.ts
  types/validator/lib/isPostalCode.d.ts
  types/validator/lib/isURL.d.ts
  types/validator/lib/isUUID.d.ts
  types/validator/lib/normalizeEmail.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#43501 [i18n-js] Add types for getFullScope
  types/i18n-js/i18n-js-tests.ts
  types/i18n-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43497 [validator]: update for validator@13.0.0
  types/validator/index.d.ts
  types/validator/lib/isBtcAddress.d.ts
  types/validator/lib/isEAN.d.ts
  types/validator/lib/isEthereumAddress.d.ts
  types/validator/lib/isHSL.d.ts
  types/validator/lib/isIBAN.d.ts
  types/validator/lib/isLocale.d.ts
  types/validator/lib/isPassportNumber.d.ts
  types/validator/lib/isRgbColor.d.ts
  types/validator/lib/isSemVer.d.ts
  types/validator/validator-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#43700 [gunzip-maybe] Creation of Types
  types/gunzip-maybe/gunzip-maybe-tests.ts
  types/gunzip-maybe/index.d.ts
  types/gunzip-maybe/tsconfig.json
  types/gunzip-maybe/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43715 Add types for text-mask-core and text-mask-addons
  types/text-mask-addons/index.d.ts
  types/text-mask-addons/text-mask-addons-tests.ts
  types/text-mask-addons/tsconfig.json
  types/text-mask-addons/tslint.json
  types/text-mask-core/index.d.ts
  types/text-mask-core/text-mask-core-tests.ts
  types/text-mask-core/tsconfig.json
  types/text-mask-core/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43702 created types for @rdfjs/express-handler
  types/rdfjs__express-handler/index.d.ts
  types/rdfjs__express-handler/rdfjs__express-handler-tests.ts
  types/rdfjs__express-handler/tsconfig.json
  types/rdfjs__express-handler/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43434 [express]: adding generics for query type
  types/easy-session/easy-session-tests.ts
  types/express-paginate/express-paginate-tests.ts
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express/express-tests.ts
  types/express/index.d.ts
  types/ghost-storage-base/ghost-storage-base-tests.ts
  types/passport-jwt/passport-jwt-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Popular package

#43600 [@types/intercom-client] Update response definitions for User API's find method
  types/intercom-client/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#43689 Add types for start-server-webpack-plugin
  types/start-server-webpack-plugin/index.d.ts
  types/start-server-webpack-plugin/start-server-webpack-plugin-tests.ts
  types/start-server-webpack-plugin/tsconfig.json
  types/start-server-webpack-plugin/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved, Revision needed

#43722 Fix datadog-statsd-metrics-collector constructor definition
  types/datadog-statsd-metrics-collector/datadog-statsd-metrics-collector-tests.ts
  types/datadog-statsd-metrics-collector/index.d.ts
Labels: Author is Owner, Merge:Express

#43697 [@types/chart.js] Add missing getElementsAtXAxis method. Closes #23159
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Popular package

#43710 Add a fix for custom footer typing
  types/mui-datatables/index.d.ts
Labels: Merge:Express, Owner Approved

#43696 Added requestId member on all CloudFrontEvent types
  types/aws-lambda/common/cloudfront.d.ts
  types/aws-lambda/test/cloudfront-tests.ts
Labels: Merge:Express, Owner Approved, Popular package

#43668 terminal-kit expose Terminal.asyncCleanup();
  types/terminal-kit/Terminal.d.ts
Labels: Merge:Express, Owner Approved

#43717 Add missing property 'fingerprint256' to PeerCertificate
  types/node/tls.d.ts
  types/node/v10/tls.d.ts
  types/node/v11/tls.d.ts
  types/node/v12/tls.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43707 Partialize all the table copy.
  types/mui-datatables/index.d.ts
Labels: Merge:Express, Owner Approved

#43729 Add undefined as valid senderId in sendCustomMessage method
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Merge:Express, Owner Approved, Revision needed

#43725 Change FancytreeOptions.rtl type to boolean instead of false
  types/jquery.fancytree/index.d.ts
  types/jquery.fancytree/jquery.fancytree-tests.ts
Labels: Merge:Express, Owner Approved

#43721 Add missing types for react-calendar 3.0
  types/react-calendar/index.d.ts
Labels: Merge:Express, Owner Approved

#43730 [@types/react] Add missing charSet attr to the link tag type
  types/react/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#43723 [mongoose] Added connection options related to auto encryption using CSFLE
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Revision needed

#43719 [aes-js] Counter allows for either a number or a ByteSource
  types/aes-js/aes-js-tests.ts
  types/aes-js/index.d.ts
Labels: Merge:Express, Owner Approved

#43720 Fix client.sessions() parameters in @types/orientjs
  types/orientjs/index.d.ts
Labels: Merge:Express, Owner Approved

#43728 [iv-viewer] Add iv viewer
  types/iv-viewer/index.d.ts
  types/iv-viewer/iv-viewer-tests.ts
  types/iv-viewer/tsconfig.json
  types/iv-viewer/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#43745 VS Code 1.44.0 Extension API
  types/vscode/index.d.ts
  types/vscode/tslint.json
Labels: Awaiting reviewer feedback

#43708 yup: add snake case to ObjectSchema
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Merge:Express, Owner Approved, Popular package, Where is Travis?

#43703 Fix return of messages callbacks on class Socket
  types/phoenix/index.d.ts
Labels: Merge:Express, Owner Approved, Where is Travis?

#43691 react-bootstrap: add umd global export
  types/react-bootstrap/index.d.ts
Labels: Awaiting reviewer feedback, Maintainer Approved, Popular package, Revision needed
