Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2020-01, with the labels that each got.

#41285 feat(react-stripe-elements): expose `handleCardAction`
  types/react-stripe-elements/index.d.ts
  types/react-stripe-elements/react-stripe-elements-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41237 [testing-library__dom] Fix async bound queries
  types/testing-library__dom/get-queries-for-element.d.ts
  types/testing-library__dom/index.d.ts
  types/testing-library__dom/testing-library__dom-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#41341 Updated to match for newest vue2-datepicker version
  types/vue2-datepicker/index.d.ts
  types/vue2-datepicker/package.json
Labels: Author is Owner, Merge:Express

#41323 [cassandra-store] Create declaration file
  types/cassandra-store/index.d.ts
  types/cassandra-store/package.json
  types/cassandra-store/tsconfig.json
  types/cassandra-store/tslint.json
Labels: Awaiting reviewer feedback, Maintainer Approved, New Definition

#41333 React router guard
  types/react-router-guard/index.d.ts
  types/react-router-guard/test/History.tsx
  types/react-router-guard/test/Layout.tsx
  types/react-router-guard/test/Page.tsx
  types/react-router-guard/test/RouterGuard.tsx
  types/react-router-guard/test/checkAuth.ts
  types/react-router-guard/tsconfig.json
  types/react-router-guard/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41295 [react-places-autocomplete] add session token to searchOptions
  types/react-places-autocomplete/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#41280 [braintree] verificationAmount written like verificationAcmount
  types/braintree/index.d.ts
Labels: Maintainer Approved, Merge:Express, Other Approved, Owner Approved, Perf: Same

#41294 HoverRadius support
  types/chart.js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41350 [blip-sdk] Added analysis call parameters
  types/blip-sdk/index.d.ts
Labels: Author is Owner, Merge:Express

#41307 value validators accept number or date
  types/vuelidate/lib/validators.d.ts
  types/vuelidate/package.json
Labels: Merge:Express, Owner Approved, Perf: Same

#41296 adjust return types from safe clownface
  types/clownface/clownface-tests.ts
  types/clownface/index.d.ts
Labels: Author is Owner, Merge:Express, Other Approved, Perf: Same

#41263 feat(cli-progress): update creation options
  types/cli-progress/cli-progress-tests.ts
  types/cli-progress/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41312 [swagger-ui-express] Add explorer to opts
  types/swagger-ui-express/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same

#41051 feat(parse/Query): add generic type check for modifiers functions
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Other Approved, Perf: Same

#41257 Add 'additionalMetaSchemas' prop to react-jsonschema-form
  types/react-jsonschema-form/index.d.ts
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same

#41345 react-syntax-highlighter: add cjs format support
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#41314 Fixed incorrect types in nodegit class DiffDelta and Blob
  types/nodegit/blob.d.ts
  types/nodegit/diff-delta.d.ts
  types/nodegit/index.d.ts
  types/nodegit/wrapper.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41319 [react-native-material-textfield] Add formatText to TextFieldProps
  types/react-native-material-textfield/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41329 [mongoose] Add useUnifiedTopology to ConnectionOptions
  types/mongoose/index.d.ts
  types/mongoose/mongoose-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41328 react-widgets: Fixed allowed values for onToggle and defaultOpen props
  types/react-widgets/lib/DateTimePicker.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41331 [protocol-buffers-schema] Fixed error in the name of the service collection
  types/protocol-buffers-schema/types.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41340 Add missing types for getPerformance() in `apicache`
  types/apicache/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41207 [react-map-gl]Add type definitions of source and layer components
  types/react-map-gl/index.d.ts
  types/react-map-gl/react-map-gl-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#40861 Add types for react-mathquill
  types/edtr-io__mathquill/edtr-io__mathquill-tests.ts
  types/edtr-io__mathquill/index.d.ts
  types/edtr-io__mathquill/tsconfig.json
  types/edtr-io__mathquill/tslint.json
  types/react-mathquill/index.d.ts
  types/react-mathquill/react-mathquill-tests.tsx
  types/react-mathquill/tsconfig.json
  types/react-mathquill/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved, Revision needed

#41261 plot.ly add showlegend to PlotData
  types/plotly.js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41264 [passport-facebook-token]: add fbGraphVersion for StrategyOptions
  types/passport-facebook-token/index.d.ts
  types/passport-facebook-token/passport-facebook-token-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41265 [color]: Show colors in types for developer QOL
  types/color/color-tests.ts
  types/color/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#41249 feat(react-toast-notification): align with version 2.4.0
  types/react-toast-notifications/index.d.ts
  types/react-toast-notifications/react-toast-notifications-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41288 koa__cors: Allow `origin` to be a function returning a promise.
  types/koa__cors/index.d.ts
  types/koa__cors/koa__cors-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL

#41276 @types/draft-js fix customStyleFn return type
  types/draft-js/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#41244 feat(angular-wizard): `setEditMode` method definition
  types/angular-wizard/angular-wizard-tests.ts
  types/angular-wizard/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41306 Added react-native-share-extension
  types/react-native-share-extension/index.d.ts
  types/react-native-share-extension/react-native-share-extension-tests.tsx
  types/react-native-share-extension/tsconfig.json
  types/react-native-share-extension/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved, Revision needed

#41173 feat(@hapi/joi): prevent incorrectly infering Joi.object type from user provided parameters
  types/hapi__joi/hapi__joi-tests.ts
  types/hapi__joi/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#41040 Pg: Adds a boolean value for PoolClient.release's support for truthy and error values
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#41259 Add types for knuth-shuffle
  types/knuth-shuffle/index.d.ts
  types/knuth-shuffle/knuth-shuffle-tests.ts
  types/knuth-shuffle/tsconfig.json
  types/knuth-shuffle/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#41200 [react-with-styles] Add basic context type and useStyles hook
  types/react-with-styles/OTHER_FILES.txt
  types/react-with-styles/lib/WithStylesContext.d.ts
  types/react-with-styles/lib/hooks/useStyles.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41217 [amqp-connection-manager] Loosen publish and sendToQueue signatures.
  types/amqp-connection-manager/amqp-connection-manager-tests.ts
  types/amqp-connection-manager/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41289 Add kompression types
  types/kompression/index.d.ts
  types/kompression/kompression-tests.ts
  types/kompression/tsconfig.json
  types/kompression/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#41303 Fix typings for Flatbuffers v1.10+ release
  types/flatbuffers/flatbuffers-tests.ts
  types/flatbuffers/index.d.ts
Labels: Merge:LGTM, Other Approved, Perf: Same, Unowned

#41366 Node: `querystring`: allow nullish values in input type
  types/node/v12/querystring.d.ts
  types/node/v12/test/querystring.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41365 feat: add types for @mdx-js/react
  types/mdx-js__react/index.d.ts
  types/mdx-js__react/mdx-js__react-tests.tsx
  types/mdx-js__react/tsconfig.json
  types/mdx-js__react/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41360 @atlaskit/feedback collector
  types/atlaskit__feedback-collector/index.d.ts
  types/atlaskit__feedback-collector/test/atlaskit__feedback-collector-tests.tsx
  types/atlaskit__feedback-collector/test/atlaskit__feedback-flag-tests.tsx
  types/atlaskit__feedback-collector/test/atlaskit__feedback-form-tests.tsx
  types/atlaskit__feedback-collector/tsconfig.json
  types/atlaskit__feedback-collector/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41367 parse: Improve typing of GeoPoint constructor
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#41371 [N3] Use correct typings for prefix utility function
  types/n3/index.d.ts
  types/n3/n3-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#41372 [N3] Type constructors properly as they require the new keyword
  types/n3/index.d.ts
  types/n3/n3-tests.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same

#41373 Sync frida-gum typings with Frida 12.8.3
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
Labels: Author is Owner, Merge:Express

#41370 [@types/react-simple-maps] Update to 1.0
  types/react-simple-maps/index.d.ts
  types/react-simple-maps/react-simple-maps-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express

#41277 fix(truncate-middle): null union type for `str`
  types/truncate-middle/index.d.ts
  types/truncate-middle/truncate-middle-tests.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41297 [web-bluetooth] Added missing BluetoothDevice event
  types/web-bluetooth/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same

#41376 d3-graphviz: fix graphviz() and selectWithoutDataPropagation()
  types/d3-graphviz/d3-graphviz-tests.ts
  types/d3-graphviz/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41362 Updated tabulator-tables/index.d.ts: RowLookup type and selectRow
  types/tabulator-tables/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41298 fix: rdf-js parsers actually return a quad stream
  types/rdfjs__parser-jsonld/index.d.ts
  types/rdfjs__parser-jsonld/rdfjs__parser-jsonld-tests.ts
  types/rdfjs__parser-n3/index.d.ts
  types/rdfjs__parser-n3/rdfjs__parser-n3-tests.ts
  types/rdfjs__serializer-jsonld-ext/index.d.ts
  types/rdfjs__serializer-jsonld/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41377 [blip-sdk] Fixed wrong types in method call
  types/blip-sdk/index.d.ts
Labels: Author is Owner, Merge:Express

#41315 Adding missing types for lightship package (from upstream)
  types/lightship/index.d.ts
  types/lightship/lightship-tests.ts
Labels: Merge:Express, Owner Approved

#41305 Updated react-stripe-elements and react-v3 to add missing types
  types/react-stripe-elements/index.d.ts
  types/react-stripe-elements/react-stripe-elements-tests.tsx
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41255 [bn.js] Fix module import without 'allowSyntheticDefaultImports'
  types/bn.js/bn.js-tests.ts
  types/bn.js/index.d.ts
  types/bn.js/tslint.json
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41352 [react-helmet]: fix types of htmlAttributes and bodyAttributes values
  types/react-helmet/index.d.ts
  types/react-helmet/react-helmet-tests.tsx
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same, Popular package

#41349 node: Fix typo
  types/node/index.d.ts
  types/node/v11/index.d.ts
  types/node/v12/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#41369 react-table: Fix type of useGetLatest
  types/react-table/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41299 [react-stickynode] Adjust 2.1 definitions
  types/react-stickynode/index.d.ts
  types/react-stickynode/react-stickynode-tests.tsx
Labels: Awaiting reviewer feedback, Merge:YSYL

#41313 Fix node and webpack-env compatibility
  types/node/globals.d.ts
  types/webpack-env/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#41311 [gapi.client.photoslibrary] Add Google Photos Library API
  types/gapi.client.photoslibrary/gapi.client.photoslibrary-tests.ts
  types/gapi.client.photoslibrary/index.d.ts
  types/gapi.client.photoslibrary/readme.md
  types/gapi.client.photoslibrary/tsconfig.json
  types/gapi.client.photoslibrary/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41385 Add types for react-native-responsive-dimensions
  types/react-native-responsive-dimensions/index.d.ts
  types/react-native-responsive-dimensions/react-native-responsive-dimensions-tests.ts
  types/react-native-responsive-dimensions/tsconfig.json
  types/react-native-responsive-dimensions/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41408 [react-native] fixes StyleSheet.flatten use caused by StyleSheet.comp…
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#41423 chore: Remove self from mongoose definition authors
  types/mongoose/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same, Popular package

#41403 fix: jsqubits type bug
  types/jsqubits/index.d.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#41391 fix(parse/query): missing base attributes in doesNotMatchKeyInQuery()
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#41378 [victory] flush out D3 scale a bit and add to callback
  types/victory/index.d.ts
  types/victory/victory-tests.tsx
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#41346 20191218 google-apps-script
  types/google-apps-script/google-apps-script-events.d.ts
  types/google-apps-script/google-apps-script-tests.ts
  types/google-apps-script/google-apps-script.base.d.ts
  types/google-apps-script/google-apps-script.cache.d.ts
  types/google-apps-script/google-apps-script.calendar.d.ts
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/google-apps-script.charts.d.ts
  types/google-apps-script/google-apps-script.contacts.d.ts
  types/google-apps-script/google-apps-script.content.d.ts
  types/google-apps-script/google-apps-script.data-studio.d.ts
  types/google-apps-script/google-apps-script.document.d.ts
  types/google-apps-script/google-apps-script.drive.d.ts
  types/google-apps-script/google-apps-script.forms.d.ts
  types/google-apps-script/google-apps-script.gmail.d.ts
  types/google-apps-script/google-apps-script.groups.d.ts
  types/google-apps-script/google-apps-script.html.d.ts
  types/google-apps-script/google-apps-script.jdbc.d.ts
  types/google-apps-script/google-apps-script.language.d.ts
  types/google-apps-script/google-apps-script.lock.d.ts
  types/google-apps-script/google-apps-script.mail.d.ts
  types/google-apps-script/google-apps-script.maps.d.ts
  types/google-apps-script/google-apps-script.optimization.d.ts
  types/google-apps-script/google-apps-script.properties.d.ts
  types/google-apps-script/google-apps-script.script.d.ts
  types/google-apps-script/google-apps-script.sites.d.ts
  types/google-apps-script/google-apps-script.slides.d.ts
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
  types/google-apps-script/google-apps-script.types.d.ts
  types/google-apps-script/google-apps-script.url-fetch.d.ts
  types/google-apps-script/google-apps-script.utilities.d.ts
  types/google-apps-script/google-apps-script.xml-service.d.ts
  types/google-apps-script/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Maintainer Approved, Merge:Express, Other Approved, Perf: Same

#41381 Add pagination option. Rework of #41228
  types/mongoose-paginate-v2/index.d.ts
  types/mongoose-paginate-v2/mongoose-paginate-v2-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41401 [ui-select] angular-ui/ui-select v0.19.8
  types/ui-select/index.d.ts
  types/ui-select/ui-select-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41397 Fix wrong type in blessed (screen.ignoreLocked)
  types/blessed/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41395 react-native-share: add types for components
  types/react-native-share/Button.d.ts
  types/react-native-share/Overlay.d.ts
  types/react-native-share/Sheet.d.ts
  types/react-native-share/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Worse

#41393 qrcode-svg 1.1.0. Completed input options. Organized and documented from package readme.
  types/qrcode-svg/index.d.ts
  types/qrcode-svg/qrcode-svg-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#41406 [micromatch] v4.0
  types/micromatch/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#41347 Add support for forwardedAs to styled-components
  types/styled-components/index.d.ts
  types/styled-components/test/index.tsx
  types/styled-components/ts3.7/index.d.ts
  types/styled-components/ts3.7/test/index.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41309 [@types/spotify-api] Update AlbumObjectSimplified and AlbumObjectFull
  types/spotify-api/index.d.ts
  types/spotify-api/spotify-api-tests.ts
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same

#41433 types for Apptimize web sdk
  types/apptimize__apptimize-web-sdk/apptimize__apptimize-web-sdk-tests.ts
  types/apptimize__apptimize-web-sdk/index.d.ts
  types/apptimize__apptimize-web-sdk/package.json
  types/apptimize__apptimize-web-sdk/tsconfig.json
  types/apptimize__apptimize-web-sdk/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#41416 Types + tests for existing npm module multibase
  types/multibase/index.d.ts
  types/multibase/multibase-tests.ts
  types/multibase/tsconfig.json
  types/multibase/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41413 Types + tests for existing npm module multiaddr
  types/multiaddr/index.d.ts
  types/multiaddr/multiaddr-tests.ts
  types/multiaddr/tsconfig.json
  types/multiaddr/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41450 `react-router`: pass state generic to history
  types/react-router/index.d.ts
  types/react-router/test/WithRouter.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41457 [parse] Make Parse.Cloud.run and Parse.Cloud.define generic
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Worse

#41444 [@types/cesium] Fix incorrect PolygonGraphics option being required
  types/cesium/index.d.ts
Labels: Author is Owner, Awaiting reviewer feedback, Merge:Express, Perf: Same

#41428 [mui-datatables] add property fixedHeaderOptions
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
Labels: Merge:Express, Other Approved, Owner Approved, Perf: Same

#41368 webpack: Add few missing type definitions on compilation.MainTemplate
  types/webpack/index.d.ts
  types/webpack/webpack-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed

#41334 [react-calendar-timeline] Overly restrictive types or not matching library
  types/react-calendar-timeline/index.d.ts
  types/react-calendar-timeline/react-calendar-timeline-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same

#41443 countries-and-timezones: add null return values
  types/countries-and-timezones/countries-and-timezones-tests.ts
  types/countries-and-timezones/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41454 [safe-timers] Add definitions
  types/safe-timers/index.d.ts
  types/safe-timers/safe-timers-tests.ts
  types/safe-timers/tsconfig.json
  types/safe-timers/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41451 Add types for `hh-mm-ss` module
  types/hh-mm-ss/hh-mm-ss-tests.ts
  types/hh-mm-ss/index.d.ts
  types/hh-mm-ss/tsconfig.json
  types/hh-mm-ss/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41449 Add types for json8-patch
  types/json8-patch/index.d.ts
  types/json8-patch/json8-patch-tests.ts
  types/json8-patch/tsconfig.json
  types/json8-patch/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41440 [git-semver-tags] Added type definitions for git-semver-tags
  types/git-semver-tags/git-semver-tags-tests.ts
  types/git-semver-tags/index.d.ts
  types/git-semver-tags/tsconfig.json
  types/git-semver-tags/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41399 dom-matches: add types/tests
  types/dom-matches/dom-matches-tests.ts
  types/dom-matches/index.d.ts
  types/dom-matches/tsconfig.json
  types/dom-matches/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41390 feat: Add `domexception`
  types/domexception/index.d.ts
  types/domexception/lib/DOMException-impl.d.ts
  types/domexception/test/domexception.index.test.ts
  types/domexception/test/domexception.webidl2js.test.ts
  types/domexception/tsconfig.json
  types/domexception/tslint.json
  types/domexception/webidl2js-wrapper.d.ts
Labels: Awaiting reviewer feedback, New Definition

#41389 feat: Add `w3c‑xmlserializer`
  types/w3c-xmlserializer/index.d.ts
  types/w3c-xmlserializer/tsconfig.json
  types/w3c-xmlserializer/tslint.json
  types/w3c-xmlserializer/w3c-xmlserializer-tests.ts
Labels: Awaiting reviewer feedback, New Definition

#41293 feat: Add typings for esm
  types/esm/esm-tests.ts
  types/esm/index.d.ts
  types/esm/tsconfig.json
  types/esm/tslint.json
Labels: Awaiting reviewer feedback, Merge:YSYL, New Definition

#41291 Add types for dom-parser
  types/dom-parser/dom-parser-tests.ts
  types/dom-parser/index.d.ts
  types/dom-parser/tsconfig.json
  types/dom-parser/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, New Definition, Other Approved

#41455 [react-native] Improve undefined type checking of Platform.select
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
  types/react-native/tsconfig.json
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#41465 Update index.d.ts
  types/react-native/index.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#41183 [jszip] add string output type
  types/jszip/index.d.ts
  types/jszip/jszip-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same, Popular package, Revision needed

#41469 Fix $ExpectType in new esm package
  types/esm/esm-tests.ts
Labels: Perf: Same

#41441 Add types for tz-lookup
  types/tz-lookup/index.d.ts
  types/tz-lookup/tsconfig.json
  types/tz-lookup/tslint.json
  types/tz-lookup/tz-lookup-tests.ts
Labels: New Definition, Revision needed

#41335 dygraphs: add missing getRowForX() definition
  types/dygraphs/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41398 chai-style: add types/tests
  types/chai-style/chai-style-tests.ts
  types/chai-style/index.d.ts
  types/chai-style/tsconfig.json
  types/chai-style/tslint.json
Labels: New Definition, Revision needed

#41411 Add types for meyda
  types/meyda/index.d.ts
  types/meyda/meyda-tests.ts
  types/meyda/tsconfig.json
  types/meyda/tslint.json
Labels: New Definition, Revision needed

#40977 Add styled component declarations to rebass
  types/rebass/index.d.ts
  types/rebass/rebass-tests.tsx
  types/rebass/styled-components.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41467 [blip-sdk] Added new content assistant method definitions
  types/blip-sdk/index.d.ts
Labels: Author is Owner, Merge:Express

#41414 [meteor] Make check an assertion function
  types/angular-meteor/index.d.ts
  types/meteor-astronomy/index.d.ts
  types/meteor-jboulhous-dev/index.d.ts
  types/meteor-persistent-session/index.d.ts
  types/meteor-prime8consulting-oauth2/index.d.ts
  types/meteor-publish-composite/index.d.ts
  types/meteor-roles/index.d.ts
  types/meteor-universe-i18n/index.d.ts
  types/meteor/check.d.ts
  types/meteor/globals/check.d.ts
  types/meteor/index.d.ts
  types/meteor/test/globals/meteor-tests.ts
  types/meteor/test/meteor-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#41445 crypto: Fix chacha20-poly1305 cipher.
  types/node/crypto.d.ts
Labels: Merge:Express, Owner Approved, Popular package

#41460 [UPDATE] Missing From Current Schema | Google-Apps-Script/api/directory_v1.d.ts | Version 1
  types/google-apps-script/apis/directory_v1.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41437 Added Plotly.js LayoutAxis property
  types/plotly.js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Revision needed

#41471 Fix an optional field in ExchangeRatesApiOptions
  types/dinero.js/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41470 Add forge.pki.getPublicKeyFingerprint to node-forge
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41468 added secondary_text_matched_substrings?:
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41448 @wordpress/components: Add type defs for Card
  types/wordpress__components/card/body/index.d.ts
  types/wordpress__components/card/divider/index.d.ts
  types/wordpress__components/card/footer/index.d.ts
  types/wordpress__components/card/header/index.d.ts
  types/wordpress__components/card/index.d.ts
  types/wordpress__components/card/media/index.d.ts
  types/wordpress__components/index.d.ts
  types/wordpress__components/package.json
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same

#41282 Use types from tar-stream as return types of tar-fs
  types/tar-fs/index.d.ts
  types/tar-fs/tar-fs-tests.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41438 [@types/cesium] Add some missing class and update to Cesium 1.65
  types/cesium/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41462 Swap Element with HTMLElement for TS type validation with Mapbox types.
  types/mapbox-gl/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41382 Mathjs: add overloaded `round`
  types/mathjs/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#41383 Changed `estree` CatchClause types to add support for optional params
  types/estree/estree-tests.ts
  types/estree/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#41364 [mongoose] Add options to deleteOne
  types/mongoose/index.d.ts
Labels: Awaiting reviewer feedback, Merge:YSYL, Perf: Same, Popular package

#41426 [jquery-slimscroll] Renamed directory to match package name
  types/jquery-slimscroll/index.d.ts
  types/jquery-slimscroll/jquery-slimscroll-tests.ts
  types/jquery-slimscroll/tsconfig.json
  types/jquery-slimscroll/tslint.json
Labels: Unowned

#41472 Add types for sizeof
  types/sizeof/index.d.ts
  types/sizeof/sizeof-tests.ts
  types/sizeof/tsconfig.json
  types/sizeof/tslint.json
Labels: Awaiting reviewer feedback, New Definition, Other Approved

#41463 LokiJS DynamicView.branchResultset: parameter transform is optional
  types/lokijs/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41379 `react-modal`: correct `portal.overlay`
  types/react-modal/index.d.ts
  types/react-modal/react-modal-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41434 Fix node compatibility (just repeat ec74215)
  types/node/module.d.ts
  types/node/test/global.ts
  types/node/test/process.ts
Labels: Awaiting reviewer feedback, Perf: Same, Popular package

#41120 [koa-router] Update version to match package
  types/koa-router/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Revision needed

#41342 line-by-line: enable all encodings supported by Node
  types/line-by-line/index.d.ts
Labels: Perf: Same, Revision needed

#41321 [http-proxy] update TargetUrl
  types/http-proxy/http-proxy-tests.ts
  types/http-proxy/index.d.ts
Labels: Perf: Same, Popular package, Revision needed

#41478 [react-aria-menubutton] Remove the nonexistent `isOpen` prop
  types/react-aria-menubutton/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41479 recharts: added className to TextProps, added onMouseEnter and onMouseLeave to CellProps
  types/recharts/index.d.ts
  types/recharts/recharts-tests.tsx
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41481 [react-select] Add NonceProvider component
  types/react-select/index.d.ts
  types/react-select/src/NonceProvider.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41486 [mongoose] adds optional generic type argument to aggregations
  types/mongoose/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package

#41422 babel-plugin-macros: Export all types and fix References type
  types/babel-plugin-macros/babel-plugin-macros-tests.ts
  types/babel-plugin-macros/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same

#41482 Add rdf-dataset-indexed
  types/rdf-dataset-indexed/index.d.ts
  types/rdf-dataset-indexed/rdf-dataset-indexed-tests.ts
  types/rdf-dataset-indexed/tsconfig.json
  types/rdf-dataset-indexed/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41490 feat: Add `symbol‑tree`
  types/symbol-tree/index.d.ts
  types/symbol-tree/lib/SymbolTree.d.ts
  types/symbol-tree/lib/TreeIterator.d.ts
  types/symbol-tree/lib/TreePosition.d.ts
  types/symbol-tree/test/symbol-tree.test.ts
  types/symbol-tree/tsconfig.json
  types/symbol-tree/tslint.json
Labels: Awaiting reviewer feedback, New Definition

#41405 [emoji-mart] Update getEmojiDataFromNative util type
  types/emoji-mart/dist-es/index.d.ts
  types/emoji-mart/dist-es/utils/index.d.ts
  types/emoji-mart/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#41394 react-query: Update refetch return type to promise
  types/react-query/index.d.ts
  types/react-query/react-query-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Worse

#41213 Add 'name' prop to gapi.client.drive.update
  types/gapi.client.drive/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#41304 feat(intro.js): rework UMD module definition. Closes #41108
  types/intro.js/index.d.ts
  types/intro.js/intro.js-tests.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#41140 power-assert: Revert updates
  types/power-assert/index.d.ts
  types/power-assert/package.json
  types/power-assert/power-assert-tests.ts
  types/power-assert/ts3.7/index.d.ts
  types/power-assert/ts3.7/tsconfig.json
  types/power-assert/ts3.7/tslint.json
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same, Revision needed

#41251 [elliptic] Add types to incomplete 'derive'
  types/elliptic/elliptic-tests.ts
  types/elliptic/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same, Popular package

#41165 [react-native-video] Add missing props
  types/react-native-video/index.d.ts
  types/react-native-video/react-native-video-tests.tsx
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved

#41114 chore(bootstrap-datepicker): add missing types
  types/bootstrap-datepicker/bootstrap-datepicker-tests.ts
  types/bootstrap-datepicker/index.d.ts
Labels: Awaiting reviewer feedback, Merge:LGTM, Other Approved, Perf: Same

#41400 add: type definition for react-native-check-box
  types/react-native-check-box/index.d.ts
  types/react-native-check-box/react-native-check-box-tests.tsx
  types/react-native-check-box/tsconfig.json
  types/react-native-check-box/tslint.json
Labels: New Definition, Revision needed

#41493 types for downscale - uses esmoduleinterop for export default
  types/downscale/downscale-tests.ts
  types/downscale/index.d.ts
  types/downscale/tsconfig.json
  types/downscale/tslint.json
Labels: New Definition, Revision needed

#41417 types/react-stripe-elements: simplify StripeProps
  types/react-stripe-elements/index.d.ts
Labels: Author is Owner, Perf: Same, Popular package, Revision needed

#41518 [react-table]: restrict Header/Cell render types
  types/react-table/index.d.ts
Labels: Author is Owner, Merge:Express, Owner Approved, Perf: Same, Popular package

#41517 Improve type definitions for sizeof
  types/sizeof/index.d.ts
  types/sizeof/sizeof-tests.ts
Labels: Author is Owner, Merge:Express, Perf: Same

#41358 [cli-color@2.0] Add types for cli-color
  types/cli-color/art.d.ts
  types/cli-color/bare.d.ts
  types/cli-color/beep.d.ts
  types/cli-color/cli-color-tests.ts
  types/cli-color/columns.d.ts
  types/cli-color/erase.d.ts
  types/cli-color/get-stripped-length.d.ts
  types/cli-color/index.d.ts
  types/cli-color/move.d.ts
  types/cli-color/reset.d.ts
  types/cli-color/slice.d.ts
  types/cli-color/strip.d.ts
  types/cli-color/throbber.d.ts
  types/cli-color/trim.d.ts
  types/cli-color/window-size.d.ts
Labels: Merge:Express, Owner Approved

#41453 fix: update faker ContextualCard interface
  types/faker/faker-tests.ts
  types/faker/index.d.ts
Labels: Merge:Express, Owner Approved, Perf: Same, Popular package, Revision needed
