Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-08, with the labels that each got.

#54873 [Node] Add the `ready` event
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v12/net.d.ts
  types/node/v12/test/net.ts
  types/node/v14/net.d.ts
  types/node/v14/test/net.ts
  types/node/v15/net.d.ts
  types/node/v15/test/net.ts
Labels: Critical package, Maintainer Approved, Self Merge

#54878 update(@yaireo/tagify): v4.6
  types/yaireo__tagify/index.d.ts
  types/yaireo__tagify/test/yaireo__tagify-react-tests.tsx
  types/yaireo__tagify/tsconfig.json
  types/yaireo__tagify/yaireo__tagify-tests.ts
Labels: Owner Approved, Self Merge

#54823 allow injected functions in @types/chrome to have params
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Edits Owners, Other Approved, Owner Approved, Popular package, Self Merge

#54890 Stricter types for `chrome.{runtime,tabs}.sendMessage`
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Owner Approved, Popular package, Self Merge

#54900 [microsoft-ajax] Added support for native Date interface implementations
  types/microsoft-ajax/index.d.ts
  types/microsoft-ajax/microsoft-ajax-tests.ts
Labels: Owner Approved, Self Merge

#54867 [pretty-time] Bugfix: Allow package to take single numbers and lists of strings
  types/pretty-time/index.d.ts
  types/pretty-time/pretty-time-tests.ts
Labels: Owner Approved, Self Merge

#54862 Add @types/libnpmpublish
  types/libnpmpublish/index.d.ts
  types/libnpmpublish/libnpmpublish-tests.ts
  types/libnpmpublish/tsconfig.json
  types/libnpmpublish/tslint.json
Labels: New Definition, Other Approved

#54747 Updating Incomes API returns and Typescript mapping
  types/belvo/belvo-tests.ts
  types/belvo/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Self Merge

#54901 [flickity] Allow string type for initialIndex
  types/flickity/flickity-tests.ts
  types/flickity/index.d.ts
Labels: Owner Approved, Self Merge

#54884 google-one-tap - appended renderButton declaration
  types/google-one-tap/index.d.ts
  types/google-one-tap/test/google-one-tap-global.test.ts
  types/google-one-tap/tsconfig.json
Labels: Owner Approved, Self Merge

#54904 Strict types for `chrome.{tabs,extension}.sendRequest`
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Owner Approved, Popular package, Self Merge

#54910 add types for egm96-universal
  types/egm96-universal/egm96-universal-tests.ts
  types/egm96-universal/index.d.ts
  types/egm96-universal/tsconfig.json
  types/egm96-universal/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54909 Add types for colormap
  types/colormap/colormap-tests.ts
  types/colormap/index.d.ts
  types/colormap/tsconfig.json
  types/colormap/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54891 [discord-rpc] Add `prompt` to RPCLoginOptions, rename `tokenEndpoint` to `redirectUri`
  types/discord-rpc/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#54905 fix: Add FocusEvent to @types/react-widgets DateTimePicker onBlur/onFocus event handlers
  types/react-widgets/lib/DateTimePicker.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#54859 Added Types for Package esutils
  types/esutils/esutils-tests.ts
  types/esutils/index.d.ts
  types/esutils/tsconfig.json
  types/esutils/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54883 Updates for Cannonjs types. Added Trimesh, added HingeConstraint properties, added Shape properties, fixed ConvexPolyhedron constructor
  types/cannon/index.d.ts
Labels: Edits Owners, Maintainer Approved, Self Merge, Untested Change

#53931 react-native-calendars expanded and week calendars, customHeader types
  types/react-native-calendars/index.d.ts
  types/react-native-calendars/react-native-calendars-tests.tsx
Labels: Maintainer Approved, Self Merge

#54888 [engine.io] Update `handleUpgrade` signature
  types/engine.io/index.d.ts
Labels: Other Approved, Owner Approved, Popular package, Self Merge, Untested Change

#54882 fixed typo (#54843) Lodash
  types/lodash/common/lang.d.ts
Labels: Critical package, Maintainer Approved, Self Merge, Untested Change

#54594 Add IE11 types
  types/web-ie11/index.d.ts
  types/web-ie11/tsconfig.json
  types/web-ie11/tslint.json
  types/web-ie11/web-ie11-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#54912 [oidc-provider] 7.6.x update
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Self Merge

#54908 Update @types/chrome with new Manifest V3 manifest type
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Owner Approved, Popular package, Self Merge

#54455 fix(json-schema): schema.required should accept boolean
  types/json-schema/index.d.ts
  types/json-schema/json-schema-tests.ts
Labels: Critical package, Maintainer Approved, Self Merge

#54805 [checksum] Bugfix: Add encoding support to object key
  types/checksum/checksum-tests.ts
  types/checksum/index.d.ts
Labels: Maintainer Approved, Self Merge

#54553 Fix @ckeditor/ckeditor5-engine detect downcasthelper
  types/ckeditor__ckeditor5-engine/ckeditor__ckeditor5-engine-tests.ts
  types/ckeditor__ckeditor5-engine/src/conversion/conversion.d.ts
  types/ckeditor__ckeditor5-engine/src/conversion/conversionhelpers.d.ts
  types/ckeditor__ckeditor5-engine/src/conversion/downcasthelpers.d.ts
  types/ckeditor__ckeditor5-engine/src/conversion/upcasthelpers.d.ts
  types/ckeditor__ckeditor5-engine/v27/ckeditor__ckeditor5-engine-tests.ts
  types/ckeditor__ckeditor5-engine/v27/src/conversion/conversion.d.ts
  types/ckeditor__ckeditor5-engine/v27/src/conversion/conversionhelpers.d.ts
  types/ckeditor__ckeditor5-engine/v27/src/conversion/downcasthelpers.d.ts
  types/ckeditor__ckeditor5-engine/v27/src/conversion/upcasthelpers.d.ts
Labels: Author is Owner, Maintainer Approved, Self Merge

#54877 add(videojs-mobile-ui): new definition
  types/videojs-mobile-ui/index.d.ts
  types/videojs-mobile-ui/tsconfig.json
  types/videojs-mobile-ui/tslint.json
  types/videojs-mobile-ui/videojs-mobile-ui-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#54907 Added types for steamapi
  types/steamapi/index.d.ts
  types/steamapi/steamapi-tests.ts
  types/steamapi/tsconfig.json
  types/steamapi/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54923 Strict types for chrome.contextMenus.*
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Owner Approved, Popular package, Self Merge

#54925 Add jwa package definitions
  types/jwa/index.d.ts
  types/jwa/jwa-tests.ts
  types/jwa/tsconfig.json
  types/jwa/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54921 Add CoffeeScript type definitionsRefs: jashkenas/coffeescript#5358
  types/coffeescript/coffeescript-tests.ts
  types/coffeescript/index.d.ts
  types/coffeescript/tsconfig.json
  types/coffeescript/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54875 Meteor Blaze: Add helper type to make the access to data and template instance member type safe.
  types/meteor/blaze.d.ts
  types/meteor/globals/blaze.d.ts
  types/meteor/globals/templating.d.ts
  types/meteor/templating.d.ts
  types/meteor/test/globals/meteor-tests.ts
  types/meteor/test/meteor-tests.ts
Labels: Author is Owner, Owner Approved, Self Merge

#53803 Added @types/eslint-utils
  types/eslint-utils/index.d.ts
  types/eslint-utils/patternMatcher.d.ts
  types/eslint-utils/referenceTracker.d.ts
  types/eslint-utils/test/index.ts
  types/eslint-utils/test/pattern-matcher.ts
  types/eslint-utils/test/reference-tracker.ts
  types/eslint-utils/tsconfig.json
  types/eslint-utils/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54913 Add types for redis-parser
  types/redis-parser/index.d.ts
  types/redis-parser/redis-parser-tests.ts
  types/redis-parser/tsconfig.json
  types/redis-parser/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54897 [gestalt] updates reflecting 29.6. Added missing button fullWidht
  types/gestalt/index.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Self Merge, Untested Change

#54711 [node] Fix encoding shorthand options type
  types/denodeify/denodeify-tests.ts
  types/node/fs.d.ts
  types/node/index.d.ts
  types/node/test/fs.ts
  types/node/v14/fs.d.ts
  types/node/v14/test/fs.ts
  types/node/v15/fs.d.ts
  types/node/v15/test/fs.ts
Labels: Critical package, Edits Owners, Edits multiple packages, Maintainer Approved, Owner Approved, Self Merge

#53730 Fix index.d.ts in @types/react-text-mask
  types/react-text-mask/index.d.ts
  types/react-text-mask/react-text-mask-tests.ts
  types/react-text-mask/react-text-mask-tests.tsx
  types/react-text-mask/tsconfig.json
Labels: Owner Approved, Popular package, Self Merge

#54933 Fix chrome.runtime.sendMessage() and add tests
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Owner Approved, Popular package, Self Merge

#54727 Add render overloads to progress types.
  types/progress/index.d.ts
  types/progress/progress-tests.ts
Labels: Maintainer Approved, Popular package, Self Merge, Unmerged

#54938 Add webpack-dev-middleware context.outputFileSystem
  types/webpack-dev-middleware/index.d.ts
  types/webpack-dev-middleware/webpack-dev-middleware-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#54813 Update @mparticle/web-sdk to allow alias scope
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-instance-tests.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Owner Approved, Self Merge

#54940 Add getScrollbarWidth type for react-virtualized/Table
  types/react-virtualized/dist/es/Table.d.ts
Labels: Maintainer Approved, Popular package, Self Merge, Untested Change

#54886 [node] Add missing http/https events
  types/node/http.d.ts
  types/node/https.d.ts
  types/node/test/http.ts
  types/node/test/https.ts
  types/node/ts3.6/node-tests.ts
  types/node/v12/http.d.ts
  types/node/v12/https.d.ts
  types/node/v12/test/http.ts
  types/node/v12/test/https.ts
  types/node/v12/ts3.6/node-tests.ts
  types/node/v14/http.d.ts
  types/node/v14/https.d.ts
  types/node/v14/test/http.ts
  types/node/v14/test/https.ts
  types/node/v14/ts3.6/node-tests.ts
  types/node/v15/http.d.ts
  types/node/v15/https.d.ts
  types/node/v15/test/http.ts
  types/node/v15/test/https.ts
  types/node/v15/ts3.6/node-tests.ts
  types/stoppable/stoppable-tests.ts
Labels: Critical package, Edits multiple packages, Maintainer Approved, Self Merge

#53860 [@types/styled-components] Fix type linting for `as` property
  types/styled-components/index.d.ts
  types/styled-components/test/index.tsx
  types/styled-components/ts3.6/index.d.ts
  types/styled-components/ts3.6/test/index.tsx
Labels: Critical package, Maintainer Approved, Self Merge

#53595 [react-native] Add react native v0.63
  react-native/v0.63/package.json
  types/react-native/v0.63/BatchedBridge.d.ts
  types/react-native/v0.63/Devtools.d.ts
  types/react-native/v0.63/LaunchScreen.d.ts
  types/react-native/v0.63/globals.d.ts
  types/react-native/v0.63/index.d.ts
  types/react-native/v0.63/legacy-properties.d.ts
  types/react-native/v0.63/test/ART.tsx
  types/react-native/v0.63/test/animated.tsx
  types/react-native/v0.63/test/globals.tsx
  types/react-native/v0.63/test/index.tsx
  types/react-native/v0.63/test/init-example.tsx
  types/react-native/v0.63/test/legacy-properties.tsx
  types/react-native/v0.63/test/stylesheet-create.tsx
  types/react-native/v0.63/test/stylesheet-flatten.tsx
  types/react-native/v0.63/tsconfig.json
  types/react-native/v0.63/tslint.json
Labels: Check Config, Edits Infrastructure, Maintainer Approved, Popular package, Self Merge

#54117 [d3-selection] Enable default linting rules
  types/d3-selection/d3-selection-tests.ts
  types/d3-selection/index.d.ts
  types/d3-selection/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge

#54722 Bugfix: Allow filesize-parser to accept numbers as per the tests
  types/filesize-parser/filesize-parser-tests.ts
  types/filesize-parser/index.d.ts
Labels: Owner Approved, Self Merge

#54372 update layui-src verson to v2.6.8
  types/layui-src/Layui.d.ts
  types/layui-src/README.md
  types/layui-src/index.d.ts
  types/layui-src/layui-src-tests.ts
  types/layui-src/misc.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Self Merge

#54571 [minipass] Update to 3.1
  types/minipass/index.d.ts
  types/minipass/minipass-tests.ts
Labels: Maintainer Approved, Popular package, Self Merge

#54874 Add types for zengin-code
  types/zengin-code/index.d.ts
  types/zengin-code/tsconfig.json
  types/zengin-code/tslint.json
  types/zengin-code/zengin-code-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#54713 [N3] fix: Resolve backwards compatibility for format option
  types/n3/index.d.ts
  types/n3/n3-tests.ts
Labels: Author is Owner, Owner Approved, Self Merge

#54581 Fix @ckeditor/ckeditor5-utils Options target
  types/ckeditor__ckeditor5-utils/ckeditor__ckeditor5-utils-tests.ts
  types/ckeditor__ckeditor5-utils/src/dom/position.d.ts
  types/ckeditor__ckeditor5-utils/src/dom/rect.d.ts
  types/ckeditor__ckeditor5-utils/v25/src/dom/position.d.ts
  types/ckeditor__ckeditor5-utils/v25/src/dom/rect.d.ts
  types/ckeditor__ckeditor5-utils/v27/src/dom/position.d.ts
  types/ckeditor__ckeditor5-utils/v27/src/dom/rect.d.ts
Labels: Author is Owner, Maintainer Approved, Self Merge

#54969 update(imagemin-upng): v3 - ESM migration
  types/imagemin-upng/imagemin-upng-tests.ts
  types/imagemin-upng/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#53715 Revert "🤖 Merge PR #53483 [koa-bodyparser] add ability to strictly type request body by @pkuczynski"
  types/koa-bodyparser/index.d.ts
  types/koa-bodyparser/koa-bodyparser-tests.ts
  types/koa-bodyparser/test/body-typed-on-use-tests.ts
  types/koa-bodyparser/test/body-typed-with-koa-tests.ts
  types/koa-bodyparser/test/body-untyped-tests.ts
  types/koa-bodyparser/test/raw-body-tests.ts
  types/koa-bodyparser/tsconfig.json
Labels: Popular package, Author is Owner, The CI failed, Edits Owners

#54963 Add types for @hmscore/react-native-hms-push
  types/hmscore__react-native-hms-push/index.d.ts
  types/hmscore__react-native-hms-push/src/HmsPushEvent.d.ts
  types/hmscore__react-native-hms-push/src/HmsPushProfileTypes.d.ts
  types/hmscore__react-native-hms-push/src/HmsPushResultCode.d.ts
  types/hmscore__react-native-hms-push/src/LocalNotification/Importance.d.ts
  types/hmscore__react-native-hms-push/src/LocalNotification/LocalNotificationAttributes.d.ts
  types/hmscore__react-native-hms-push/src/LocalNotification/Priority.d.ts
  types/hmscore__react-native-hms-push/src/LocalNotification/RepeatType.d.ts
  types/hmscore__react-native-hms-push/src/LocalNotification/Visibility.d.ts
  types/hmscore__react-native-hms-push/src/LocalNotification/index.d.ts
  types/hmscore__react-native-hms-push/src/RNRemoteMessage.d.ts
  types/hmscore__react-native-hms-push/src/RemoteDataMessage.d.ts
  types/hmscore__react-native-hms-push/src/RemoteMessageBuilder.d.ts
  types/hmscore__react-native-hms-push/src/ResultResponse.d.ts
  types/hmscore__react-native-hms-push/test/backgroundHandler-test.tsx
  types/hmscore__react-native-hms-push/test/localnotification-test.tsx
  types/hmscore__react-native-hms-push/test/main-test.tsx
  types/hmscore__react-native-hms-push/tsconfig.json
  types/hmscore__react-native-hms-push/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#54967 Add types for react-embed-gist
  types/react-embed-gist/index.d.ts
  types/react-embed-gist/react-embed-gist-tests.tsx
  types/react-embed-gist/tsconfig.json
  types/react-embed-gist/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#54970 VS Code 1.59.0 Extension API
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#54951 Fix running tests using npm 7
  .npmrc
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#54953 Add type definitions for eins-modal
  types/eins-modal/eins-modal-tests.ts
  types/eins-modal/index.d.ts
  types/eins-modal/tsconfig.json
  types/eins-modal/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#54924 @ckeditor/ckeditor5-core improve PluginCollection.get() typing
  types/ckeditor__ckeditor5-core/ckeditor__ckeditor5-core-tests.ts
  types/ckeditor__ckeditor5-core/src/plugin.d.ts
  types/ckeditor__ckeditor5-core/src/plugincollection.d.ts
  types/ckeditor__ckeditor5-editor-inline/ckeditor__ckeditor5-editor-inline-tests.ts
Labels: Self Merge, Owner Approved, Edits multiple packages

#54903 Update @ckeditor/ckeditor5-watchdog to v29
  types/ckeditor__ckeditor5-watchdog/ckeditor__ckeditor5-watchdog-tests.ts
  types/ckeditor__ckeditor5-watchdog/index.d.ts
  types/ckeditor__ckeditor5-watchdog/v27/ckeditor__ckeditor5-watchdog-tests.ts
  types/ckeditor__ckeditor5-watchdog/v27/index.d.ts
  types/ckeditor__ckeditor5-watchdog/v27/src/contextwatchdog.d.ts
  types/ckeditor__ckeditor5-watchdog/v27/src/editorwatchdog.d.ts
  types/ckeditor__ckeditor5-watchdog/v27/src/utils/areconnectedthroughproperties.d.ts
  types/ckeditor__ckeditor5-watchdog/v27/src/watchdog.d.ts
  types/ckeditor__ckeditor5-watchdog/v27/tsconfig.json
  types/ckeditor__ckeditor5-watchdog/v27/tslint.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#54501 Fix @ckeditor/ckeditor5-engine DowncastWriter
  types/ckeditor__ckeditor5-engine/ckeditor__ckeditor5-engine-tests.ts
  types/ckeditor__ckeditor5-engine/src/view/downcastwriter.d.ts
  types/ckeditor__ckeditor5-engine/v27/ckeditor__ckeditor5-engine-tests.ts
  types/ckeditor__ckeditor5-engine/v27/src/view/downcastwriter.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#54931 Update w3c-web-hid definitions
  types/w3c-web-hid/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change, Edits Owners

#54956 [node] Fix deprecated message of Cluster.isMaster of Node.js
  types/node/cluster.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#54911 feat: add @hippy/react
  types/hippy__react/hippy__react-tests.tsx
  types/hippy__react/index.d.ts
  types/hippy__react/tsconfig.json
  types/hippy__react/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#54936 [react] Add `media` attribute support for `meta`
  types/react/index.d.ts
  types/react/v15/index.d.ts
  types/react/v16/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#54964 mapbox-gl: Update type defs for v2.4
  types/mapbox-gl/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#54600 statsd-client: add histogram & wrapCallback types
  types/statsd-client/index.d.ts
  types/statsd-client/statsd-client-tests.ts
Labels: Self Merge, Maintainer Approved

#54976 feat: adding hmgetBuffer to ioredis.Redis contract
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#54943 Add types for 'scan.js'
  types/onscan.js/index.d.ts
  types/onscan.js/onscan.js-tests.ts
  types/onscan.js/tsconfig.json
  types/onscan.js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#54983 [apple-mapkit-js] add `rotation-start` & `rotation-end` Map events
  types/apple-mapkit-js-browser/apple-mapkit-js-browser-tests.ts
  types/apple-mapkit-js-browser/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#54975 Add case insensitivity types to command-line-args
  types/command-line-args/command-line-args-tests.ts
  types/command-line-args/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#54989 Shim OffscreenCanvas in dom-webcodecs
  types/dom-webcodecs/index.d.ts
Labels: Untested Change

#54952 update(bootstrap): v5.1 updates
  types/bootstrap/bootstrap-tests.ts
  types/bootstrap/index.d.ts
  types/bootstrap/js/dist/alert.d.ts
  types/bootstrap/js/dist/base-component.d.ts
  types/bootstrap/js/dist/button.d.ts
  types/bootstrap/js/dist/carousel.d.ts
  types/bootstrap/js/dist/collapse.d.ts
  types/bootstrap/js/dist/dropdown.d.ts
  types/bootstrap/js/dist/modal.d.ts
  types/bootstrap/js/dist/offcanvas.d.ts
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/scrollspy.d.ts
  types/bootstrap/js/dist/tab.d.ts
  types/bootstrap/js/dist/toast.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#54714 update(body-scroll-lock): correct return type
  types/body-scroll-lock/body-scroll-lock-tests.ts
  types/body-scroll-lock/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#54902 [core-js] Added support for native Date interface implementations
  types/core-js/core-js-tests.ts
  types/core-js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#54810 [file-exists] Bugfix: Add TypeScript support for Promises
  types/file-exists/file-exists-tests.ts
  types/file-exists/index.d.ts
  types/file-exists/tsconfig.json
Labels: Self Merge, Maintainer Approved

#54716 Fix the goToIndex parameter type in react-gallery-carousel
  types/react-gallery-carousel/index.d.ts
  types/react-gallery-carousel/react-gallery-carousel-tests.tsx
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#54949 update(mini-css-extract-plugin): v2.2 updates
  types/mini-css-extract-plugin/index.d.ts
  types/mini-css-extract-plugin/mini-css-extract-plugin-tests.ts
  types/webpack-sources/index.d.ts
  types/webpack-sources/lib/SourceMapSource.d.ts
  types/webpack-sources/webpack-sources-tests.ts
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, Critical package

#54634 Handles optional opts argument in Vorpal.parse
  types/vorpal/index.d.ts
  types/vorpal/vorpal-tests.ts
Labels: Self Merge, Owner Approved

#54985 Remark prism
  types/remark-prism/index.d.ts
  types/remark-prism/package.json
  types/remark-prism/remark-prism-tests.ts
  types/remark-prism/tsconfig.json
  types/remark-prism/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#54928 Tweak types for colormap
  types/colormap/colormap-tests.ts
  types/colormap/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#54988 [threejs] Adds Offscreencanvas stub to threejs because it does not exist in the DOM anymore
  types/three/src/renderers/WebGLRenderer.d.ts
Labels: Popular package, Owner Approved, Untested Change

#54982 Add missing plotly.js tickangle type
  types/plotly.js/index.d.ts
  types/plotly.js/test/core-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#54961 [p2] Added event types, stricter static constants, fixed getBodyByID, added missing constructor options, prettier formatted.
  types/p2/index.d.ts
  types/p2/p2-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Edits Owners

#54646 [chromecast-caf-receiver] Align to SDK and docs (only breaking changes)
  types/chromecast-caf-receiver/cast.framework.breaks.d.ts
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/cast.framework.events.category.d.ts
  types/chromecast-caf-receiver/cast.framework.events.d.ts
  types/chromecast-caf-receiver/cast.framework.messages.d.ts
  types/chromecast-caf-receiver/cast.framework.system.d.ts
  types/chromecast-caf-receiver/cast.framework.ui.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
  types/chromecast-caf-receiver/index.d.ts
  types/chromecast-caf-receiver/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Owners

#54939 [leaflet-gpx] Add missing properties for marker_options
  types/leaflet-gpx/index.d.ts
  types/leaflet-gpx/leaflet-gpx-tests.ts
Labels: Self Merge, Owner Approved

#54991 Update webrtc for TS4.4 RC
  types/w3c-image-capture/index.d.ts
  types/webrtc/RTCPeerConnection.d.ts
  types/webrtc/index.d.ts
  types/webrtc/test/RTCPeerConnection.ts
Labels: Edits multiple packages

#54992 Update w3c-css-typed-object-model-level-1 for TS4.4 RC
  types/w3c-css-typed-object-model-level-1/index.d.ts
  types/w3c-css-typed-object-model-level-1/w3c-css-typed-object-model-level-1-tests.ts
Labels: Author is Owner, No Other Owners

#55017 [express-busboy] Version bump; add strip function
  types/express-busboy/express-busboy-tests.ts
  types/express-busboy/index.d.ts
Labels: Self Merge, Owner Approved

#54998 added types for steam-user
  types/steam-user/components/chatroom.d.ts
  types/steam-user/index.d.ts
  types/steam-user/steam-user-tests.ts
  types/steam-user/tsconfig.json
  types/steam-user/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55036 [opentype.js] Extending RenderOptions to include letterSpacing and tracking
  types/opentype.js/index.d.ts
  types/opentype.js/opentype.js-tests.ts
Labels: Self Merge, Owner Approved

#55040 Add Event Options to mParticle event logging methods v2.13.0 (#1)
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-instance-tests.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Self Merge, Owner Approved

#55024 [koa-cache-control] Bugfix: Add proxyRevalidate to object
  types/koa-cache-control/index.d.ts
  types/koa-cache-control/koa-cache-control-tests.ts
Labels: Self Merge, Owner Approved

#54699 Add definitions for AWS CloudFront Functions
  types/aws-cloudfront-function/aws-cloudfront-function-tests.ts
  types/aws-cloudfront-function/index.d.ts
  types/aws-cloudfront-function/tsconfig.json
  types/aws-cloudfront-function/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55016 Add type definitions to @marvelapp/react-ab-test
  types/marvelapp__react-ab-test/index.d.ts
  types/marvelapp__react-ab-test/marvelapp__react-ab-test-tests.ts
  types/marvelapp__react-ab-test/marvelapp__react-ab-test-tests.tsx
  types/marvelapp__react-ab-test/tsconfig.json
  types/marvelapp__react-ab-test/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#54791 Update luxon to 2.0
  types/luxon/index.d.ts
  types/luxon/src/datetime.d.ts
  types/luxon/src/duration.d.ts
  types/luxon/src/info.d.ts
  types/luxon/src/settings.d.ts
  types/luxon/src/zone.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Popular package, Self Merge, Maintainer Approved

#54579 Correctly Type inputRef of react-calendar
  types/react-calendar/index.d.ts
  types/react-calendar/react-calendar-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#54980 [payu-emea-sdk] SecureFormErrorMessage type: validate -> validation
  types/payu-emea-sdk/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#54960 Add type definitions for itty-router-extras
  types/itty-router-extras/index.d.ts
  types/itty-router-extras/itty-router-extras-tests.ts
  types/itty-router-extras/package.json
  types/itty-router-extras/tsconfig.json
  types/itty-router-extras/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#55001 add(js-image-zoom): new definition
  types/js-image-zoom/index.d.ts
  types/js-image-zoom/js-image-zoom-tests.ts
  types/js-image-zoom/tsconfig.json
  types/js-image-zoom/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55029 Adds definitions for is-html
  types/is-html/index.d.ts
  types/is-html/is-html-tests.ts
  types/is-html/tsconfig.json
  types/is-html/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#54987 Add typings for proposal-relative-indexing-method
  types/proposal-relative-indexing-method/index.d.ts
  types/proposal-relative-indexing-method/proposal-relative-indexing-method-tests.ts
  types/proposal-relative-indexing-method/tsconfig.json
  types/proposal-relative-indexing-method/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#54818 fix smart-truncate
  types/smart-truncate/index.d.ts
  types/smart-truncate/smart-truncate-tests.ts
Labels: Self Merge, Maintainer Approved

#55041 [yandex-maps] add presets and fix some types regards to docs
  types/yandex-maps/index.d.ts
  types/yandex-maps/yandex-maps-tests.ts
Labels: Self Merge, Owner Approved

#55045 [aws-lambda] - Add firehose event property sourceKinesisStreamArn
  types/aws-lambda/test/kinesis-tests.ts
  types/aws-lambda/trigger/kinesis-firehose-transformation.d.ts
Labels: Popular package, Self Merge, Owner Approved

#55053 changed factory_girl typing to provide attributes instead of array
  types/factory-girl/factory-girl-tests.ts
  types/factory-girl/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#54984 feat: add node-ssha256
  types/node-ssha256/index.d.ts
  types/node-ssha256/node-ssha256-tests.ts
  types/node-ssha256/tsconfig.json
  types/node-ssha256/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55013 jest: Update for v27
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package, Edits Owners

#54997 [react-date-range] Extend key type of DateRange.onChangeProps to string
  types/react-date-range/index.d.ts
  types/react-date-range/react-date-range-tests.tsx
Labels: Self Merge, Owner Approved

#55008 updated steamid typings to v2.0
  types/steamid/index.d.ts
  types/steamid/steamid-tests.ts
  types/steamid/tsconfig.json
Labels: Self Merge, Maintainer Approved, Check Config, Edits Owners

#54801 [googlepay] add allowedPaymentMethods to ButtonOptions
  types/googlepay/googlepay-tests.ts
  types/googlepay/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Owner Approved

#54846 @types/google-protobuf: Add missing (static and instance) methods to class Map
  types/google-protobuf/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#54993 update(p2): remove contributor handle
  types/p2/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change, Edits Owners

#54837 Add width and height attributes to source elements @types/react @types/babel-plugin-react-html-attrs
  types/babel-plugin-react-html-attrs/babel-plugin-react-html-attrs-tests.tsx
  types/babel-plugin-react-html-attrs/index.d.ts
  types/react/index.d.ts
  types/react/test/elementAttributes.tsx
  types/react/v16/index.d.ts
  types/react/v16/test/elementAttributes.tsx
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Critical package

#54563 19.2.0.44 added
  types/ej.web.all/ej.web.all-tests.ts
  types/ej.web.all/index.d.ts
Labels: Self Merge, Maintainer Approved

#55055 [openui5] Update definition files for OpenUI5 1.93
  types/openui5/index.d.ts
  types/openui5/openui5-tests.ts
  types/openui5/sap.f.d.ts
  types/openui5/sap.m.d.ts
  types/openui5/sap.tnt.d.ts
  types/openui5/sap.ui.codeeditor.d.ts
  types/openui5/sap.ui.commons.d.ts
  types/openui5/sap.ui.core.d.ts
  types/openui5/sap.ui.dt.d.ts
  types/openui5/sap.ui.fl.d.ts
  types/openui5/sap.ui.integration.d.ts
  types/openui5/sap.ui.layout.d.ts
  types/openui5/sap.ui.mdc.d.ts
  types/openui5/sap.ui.suite.d.ts
  types/openui5/sap.ui.support.d.ts
  types/openui5/sap.ui.table.d.ts
  types/openui5/sap.ui.testrecorder.d.ts
  types/openui5/sap.ui.unified.d.ts
  types/openui5/sap.ui.ux3.d.ts
  types/openui5/sap.ui.webc.fiori.d.ts
  types/openui5/sap.ui.webc.main.d.ts
  types/openui5/sap.uxap.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#55077 Holderjs.run options can be optional
  types/holderjs/holderjs-tests.ts
  types/holderjs/index.d.ts
Labels: Self Merge, Owner Approved

#55025 Add definitions for jconv
  types/jconv/index.d.ts
  types/jconv/jconv-tests.ts
  types/jconv/tsconfig.json
  types/jconv/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#54667 [contentful-resolve-response] update resolveResponse params
  types/contentful-resolve-response/contentful-resolve-response-tests.ts
  types/contentful-resolve-response/index.d.ts
Labels: Self Merge, Maintainer Approved

#55033 fix(node): the return value type of the fsPromises.watch method is incorrect
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/test/fs.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#54695 [react-native]: Add Websocket addEventListener and removeEventListener
  types/react-native/globals.d.ts
  types/react-native/test/globals.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#55076 [serverless] adds HttpApiCors interface which can be used to fine tune the httpApi CORS settings
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Self Merge, Owner Approved

#55092 New @ckeditor/ckeditor5-build-decoupled-document v29
  types/ckeditor__ckeditor5-build-decoupled-document/ckeditor__ckeditor5-build-decoupled-document-tests.ts
  types/ckeditor__ckeditor5-build-decoupled-document/index.d.ts
  types/ckeditor__ckeditor5-build-decoupled-document/tsconfig.json
  types/ckeditor__ckeditor5-build-decoupled-document/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55085 Remove deta types
  notNeededPackages.json
  types/deta/deta-tests.ts
  types/deta/index.d.ts
  types/deta/tsconfig.json
  types/deta/tslint.json
Labels: Other Approved, Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#55057 feat(node): v16.6
  types/node/assert.d.ts
  types/node/async_hooks.d.ts
  types/node/base.d.ts
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/cluster.d.ts
  types/node/console.d.ts
  types/node/crypto.d.ts
  types/node/dgram.d.ts
  types/node/diagnostics_channel.d.ts
  types/node/dns.d.ts
  types/node/domain.d.ts
  types/node/events.d.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/globals.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/https.d.ts
  types/node/index.d.ts
  types/node/inspector.d.ts
  types/node/net.d.ts
  types/node/os.d.ts
  types/node/path.d.ts
  types/node/perf_hooks.d.ts
  types/node/process.d.ts
  types/node/punycode.d.ts
  types/node/querystring.d.ts
  types/node/readline.d.ts
  types/node/repl.d.ts
  types/node/scripts/generate-docs/html-doc-processing.ts
  types/node/scripts/generate-docs/node-doc-processing.ts
  types/node/scripts/generate-docs/tsconfig.json
  types/node/stream.d.ts
  types/node/stream/web.d.ts
  types/node/string_decoder.d.ts
  types/node/test/diagnostics_channel.ts
  types/node/test/inspector.ts
  types/node/test/stream.ts
  types/node/test/trace_events.ts
  types/node/timers.d.ts
  types/node/timers/promises.d.ts
  types/node/tls.d.ts
  types/node/trace_events.d.ts
  types/node/ts3.6/base.d.ts
  types/node/ts3.6/node-tests.ts
  types/node/ts3.6/tsconfig.json
  types/node/tsconfig.json
  types/node/tty.d.ts
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/v8.d.ts
  types/node/vm.d.ts
  types/node/wasi.d.ts
  types/node/worker_threads.d.ts
  types/node/zlib.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Check Config

#55094 [create-torrent] fixed a missing type (https://github.com/webtorrent/create-torrent#api)
  types/create-torrent/create-torrent-tests.ts
  types/create-torrent/index.d.ts
Labels: Other Approved, Self Merge

#55086 Add misc to JobPayload definitions in forge-apis
  types/forge-apis/forge-apis-tests.ts
  types/forge-apis/index.d.ts
Labels: Other Approved, Self Merge

#54299 [npm] Add all commands and update to npm 7.19.0
  types/global-npm/global-npm-tests.ts
  types/global-npm/index.d.ts
  types/npm/index.d.ts
  types/npm/npm-tests.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#54996 Add Query context and validator 'required' field
  types/parse/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#55015 [concat-map] Bugfix: Function takes two arguments
  types/concat-map/concat-map-tests.ts
  types/concat-map/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#55044 [googletag] Update definition of googletag.Service.addEventListener
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#55075 [bootstrap-select] Add BootstrapVersion property
  types/bootstrap-select/bootstrap-select-tests.ts
  types/bootstrap-select/index.d.ts
Labels: Self Merge, Owner Approved

#54869 [throng] Bugfix: Note that function returns Promise
  types/throng/index.d.ts
  types/throng/throng-tests.ts
Labels: Self Merge, Owner Approved

#54868 [ffbinaries] Bugfix: Handle null return and optional configuration object of detectPlatform
  types/ffbinaries/ffbinaries-tests.ts
  types/ffbinaries/index.d.ts
Labels: Self Merge, Maintainer Approved

#55115 [url-parse] Fix `URLParse.set` type
  types/url-parse/index.d.ts
  types/url-parse/url-parse-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55117 [types/bootstrap] Carousel option `interval` allows false
  types/bootstrap/js/dist/carousel.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#55051 [node] Allow omitting ctx in SNICallback
  types/node/test/tls.ts
  types/node/tls.d.ts
Labels: Owner Approved, Maintainer Approved, Critical package, The CI failed

#55093 Bump jest 27 deps
  types/jest/package.json
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#54732 [suncalc] Bugfix: Mark alwaysUp and alwaysDown as optional and true
  types/suncalc/index.d.ts
  types/suncalc/suncalc-tests.ts
Labels: Self Merge, Maintainer Approved

#54731 [parse-color] Bugfix: Make keyword potentially undefined
  types/parse-color/index.d.ts
  types/parse-color/parse-color-tests.ts
Labels: Self Merge, Maintainer Approved

#54834 Update type definition of koa-ejs
  types/koa-ejs/index.d.ts
  types/koa-ejs/koa-ejs-tests.ts
Labels: Other Approved, Self Merge

#55066 [roslib] add type-generic support
  types/roslib/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#54726 [d3-cloud] Prefer union instead of overloads
  types/d3-cloud/d3-cloud-tests.ts
  types/d3-cloud/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved

#55047 [echarts | zrender] textStyle.rich & label.color can be a function ...
  types/echarts/echarts-tests.ts
  types/echarts/index.d.ts
  types/echarts/options/line-style.d.ts
  types/echarts/options/series/candlestick.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#55011 Added types for rollup-plugin-svelte-svg
  types/rollup-plugin-svelte-svg/OTHER_FILES.txt
  types/rollup-plugin-svelte-svg/index.d.ts
  types/rollup-plugin-svelte-svg/package.json
  types/rollup-plugin-svelte-svg/rollup-plugin-svelte-svg-tests.ts
  types/rollup-plugin-svelte-svg/svg.d.ts
  types/rollup-plugin-svelte-svg/tsconfig.json
  types/rollup-plugin-svelte-svg/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#55130 [faker] updated finance.iban signature
  types/faker/faker-tests.ts
  types/faker/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#55032 [chromecast-caf-receiver] Update declarations according to SDK docs (1)
  types/chromecast-caf-receiver/cast.framework.breaks.d.ts
  types/chromecast-caf-receiver/cast.framework.events.category.d.ts
  types/chromecast-caf-receiver/cast.framework.ui.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#55084 [@types/google-protobuf] Add missing Symbol.iterator function to interface of Map.Iterator<T>
  types/google-protobuf/google-protobuf-tests.ts
  types/google-protobuf/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#55099 Add types for `skeleton-rendezvous`
  types/skeleton-rendezvous/index.d.ts
  types/skeleton-rendezvous/skeleton-rendezvous-tests.ts
  types/skeleton-rendezvous/tsconfig.json
  types/skeleton-rendezvous/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved
