Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-09, with the labels that each got.

#55143 Add .modal() function to eins-modal
  types/eins-modal/eins-modal-tests.ts
  types/eins-modal/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#55069 Add missing 'fbAsyncInit' to facebook-js-sdk types
  types/facebook-js-sdk/facebook-js-sdk-tests.ts
  types/facebook-js-sdk/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#55276 Updates @types/sharp@0.28 to account for all input types
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55493 Codeowners update script: Pull before push
  .github/workflows/UpdateCodeowners.yml
  scripts/update-codeowners.js
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#55147 [express-actuator] update to version 1.8
  types/express-actuator/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change, Edits Owners

#55141 Fabric: Add mouse events to handlers
  types/fabric/fabric-impl.d.ts
  types/fabric/test/index.ts
Labels: Self Merge, Maintainer Approved

#55528 [svgo]: improve typings for `optimize` function and `removeAttrs` plugin
  types/svgo/index.d.ts
  types/svgo/svgo-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55518 remove(terser-webpack-plugin): DT no longer neeeded
  notNeededPackages.json
  types/terser-webpack-plugin/index.d.ts
  types/terser-webpack-plugin/package.json
  types/terser-webpack-plugin/terser-webpack-plugin-tests.ts
  types/terser-webpack-plugin/tsconfig.json
  types/terser-webpack-plugin/tslint.json
  types/terser-webpack-plugin/v2/index.d.ts
  types/terser-webpack-plugin/v2/package.json
  types/terser-webpack-plugin/v2/terser-webpack-plugin-tests.ts
  types/terser-webpack-plugin/v2/tsconfig.json
  types/terser-webpack-plugin/v2/tslint.json
  types/terser-webpack-plugin/v4/index.d.ts
  types/terser-webpack-plugin/v4/package.json
  types/terser-webpack-plugin/v4/terser-webpack-plugin-tests.ts
  types/terser-webpack-plugin/v4/tsconfig.json
  types/terser-webpack-plugin/v4/tslint.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#55438 [googletag] Add definitions not declared by GPT Reference
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#55529 mapbox-gl: Fix image-related return types and add updateImage
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55554 [twitch-ext] Added missing Authorized.helixToken property
  types/twitch-ext/index.d.ts
  types/twitch-ext/twitch-ext-tests.ts
Labels: Self Merge, Owner Approved

#55506 Deprecate transitionToRoute of Controller in Ember
  types/ember/v2/index.d.ts
  types/ember__controller/index.d.ts
Labels: Popular package, Owner Approved, Edits multiple packages, Untested Change

#55317 [xrm] Add setPrecision method to number attribute & add organizationG…
  types/xrm/index.d.ts
Labels: Owner Approved, Untested Change

#55107 [Draft-js] Add properties "onCopy" and "onCut" of the DraftEditorProps
  types/draft-js/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#55353 Adding owner to definitions
  types/akamai-edgeworkers/index.d.ts
Labels: Author is Owner, Owner Approved, Untested Change, Edits Owners

#55563 VS Code 1.60.0 Extension API
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#55566 [office-runtime] [custom-functions-runtime] Remove owner no longer on…
  types/custom-functions-runtime/index.d.ts
  types/office-runtime/index.d.ts
Labels: Owner Approved, Edits multiple packages, Untested Change, Edits Owners

#55021 [express-less] Version bump: Add object key
  types/express-less/express-less-tests.ts
  types/express-less/index.d.ts
Labels: Self Merge, Maintainer Approved

#55305 [hull.js] Bugfix: Return number[][]
  types/hull.js/hull.js-tests.ts
  types/hull.js/index.d.ts
Labels: Other Approved, Self Merge

#55537 update(bootstrap): redo #54842
  types/bootstrap/js/dist/alert.d.ts
  types/bootstrap/js/dist/base-component.d.ts
  types/bootstrap/js/dist/carousel.d.ts
  types/bootstrap/js/dist/collapse.d.ts
  types/bootstrap/js/dist/dropdown.d.ts
  types/bootstrap/js/dist/modal.d.ts
  types/bootstrap/js/dist/offcanvas.d.ts
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/scrollspy.d.ts
  types/bootstrap/js/dist/tab.d.ts
  types/bootstrap/js/dist/toast.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
  types/bootstrap/test/alert-tests.ts
  types/bootstrap/test/button-tests.ts
  types/bootstrap/test/carousel-tests.ts
  types/bootstrap/test/collapse-tests.ts
  types/bootstrap/test/dropdown-tests.ts
  types/bootstrap/test/global-script.ts
  types/bootstrap/test/modal-tests.ts
  types/bootstrap/test/offcanvas-tests.ts
  types/bootstrap/test/popover-tests.ts
  types/bootstrap/test/scrollspy-tests.ts
  types/bootstrap/test/tab-tests.ts
  types/bootstrap/test/toast-tests.ts
  types/bootstrap/test/tooltip-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#55521 Add types for node-wav.
  types/node-wav/index.d.ts
  types/node-wav/node-wav-tests.ts
  types/node-wav/tsconfig.json
  types/node-wav/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55064 fix big.js - add missing `prec`
  types/big.js/index.d.ts
  types/big.js/test/big.js-import-default-tests.ts
  types/big.js/test/big.js-module-tests.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#55544 remove bson
  notNeededPackages.json
  types/bson/bson-tests.ts
  types/bson/index.d.ts
  types/bson/tsconfig.json
  types/bson/tslint.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved, Critical package

#55522 Update wrong type definition
  types/voice-activity-detection/index.d.ts
  types/voice-activity-detection/voice-activity-detection-tests.ts
Labels: Self Merge, Owner Approved

#55002 [yeoman-generator] Add the missing `resolved`-option to the generator-options
  types/yeoman-generator/index.d.ts
  types/yeoman-generator/lib/util/storage.d.ts
  types/yeoman-generator/yeoman-generator-tests.ts
Labels: Unmerged, Self Merge, Author is Owner, Maintainer Approved

#55558 [jsforce]: Add Constructor to SfDate Class
  types/jsforce/date.d.ts
  types/jsforce/jsforce-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55575 fix: RenderOptions type
  types/rax/index.d.ts
  types/rax/test/hooks.tsx
  types/rax/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved

#55533 Remove node-fetch - not needed as of 3.0.0
  notNeededPackages.json
  types/adobe__node-fetch-retry/package.json
  types/file-fetch/package.json
  types/frisby/package.json
  types/libnpmpublish/package.json
  types/make-fetch-happen/package.json
  types/node-fetch/externals.d.ts
  types/node-fetch/index.d.ts
  types/node-fetch/node-fetch-tests.ts
  types/node-fetch/tsconfig.json
  types/node-fetch/tslint.json
  types/npm-registry-fetch/package.json
  types/proto-fetch/package.json
  types/react-native-version-check/package.json
  types/zipkin-instrumentation-fetch/package.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package

#55586 yeoman-generator: Make the config argument of the Generator.option method optional
  types/yeoman-generator/index.d.ts
  types/yeoman-generator/yeoman-generator-tests.ts
Labels: Self Merge, Owner Approved

#55577 [@types/bootstrap] always return instance from GetOrCreateInstanceFactory
  types/bootstrap/js/dist/base-component.d.ts
  types/bootstrap/test/alert-tests.ts
  types/bootstrap/test/button-tests.ts
  types/bootstrap/test/carousel-tests.ts
  types/bootstrap/test/collapse-tests.ts
  types/bootstrap/test/dropdown-tests.ts
  types/bootstrap/test/modal-tests.ts
  types/bootstrap/test/offcanvas-tests.ts
  types/bootstrap/test/popover-tests.ts
  types/bootstrap/test/scrollspy-tests.ts
  types/bootstrap/test/tab-tests.ts
  types/bootstrap/test/toast-tests.ts
  types/bootstrap/test/tooltip-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#55543 @types/chrome: Improve ScriptInjection type
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#55486 [socketcluster-server][ag-auth] Fix dependency & add its type definition
  types/ag-auth/ag-auth-tests.ts
  types/ag-auth/index.d.ts
  types/ag-auth/tsconfig.json
  types/ag-auth/tslint.json
  types/socketcluster-server/server.d.ts
  types/socketcluster-server/serversocket.d.ts
  types/socketcluster-server/socketcluster-server-tests.ts
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved, No Other Owners

#54698 [styled-components]: Added `displayName` and `componentId`
  types/styled-components/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package, Untested Change

#55538 Add types for postcss-inline-svg
  types/postcss-inline-svg/index.d.ts
  types/postcss-inline-svg/package.json
  types/postcss-inline-svg/postcss-inline-svg-tests.ts
  types/postcss-inline-svg/tsconfig.json
  types/postcss-inline-svg/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#55316 [react] Added type definitions for input type attribute
  types/react/index.d.ts
  types/react/test/elementAttributes.tsx
  types/react/v16/index.d.ts
  types/react/v16/test/elementAttributes.tsx
Labels: Author is Owner, Owner Approved, Critical package, Unreviewed

#55598 [Luxon] Fix is* input to be unknown
  types/luxon/src/datetime.d.ts
  types/luxon/src/duration.d.ts
  types/luxon/src/interval.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#55361 Change aws-cloudfront-function to ambient declarations
  types/aws-cloudfront-function/aws-cloudfront-function-tests.ts
  types/aws-cloudfront-function/index.d.ts
  types/aws-cloudfront-function/tslint.json
Labels: Unmerged, Self Merge, Maintainer Approved, Check Config

#55545 auth0: Add options to PasswordlessAuthenticator
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#55564 [react-datepicker] make Modifiers type parameter optional
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#55596 pdf-fill-form: Add writeSync, allow other types
  types/pdf-fill-form/index.d.ts
  types/pdf-fill-form/pdf-fill-form-tests.ts
Labels: Self Merge, Owner Approved

#55606 [ioredis] add missing definition of bitfield command
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55615 Add types and actions to wicg-mediasession from the w3c spec and TS 4.4
  types/wicg-mediasession/index.d.ts
  types/wicg-mediasession/wicg-mediasession-tests.ts
Labels: Self Merge, Owner Approved

#55608 [@types/meteor] Add isAppTest property to Meteor
  types/meteor/globals/meteor.d.ts
  types/meteor/meteor.d.ts
  types/meteor/test/globals/meteor-tests.ts
  types/meteor/test/meteor-tests.ts
Labels: Self Merge, Owner Approved

#55605 [README] Restore markdown link checks
  .github/workflows/lint-md.yml
Labels: Edits Infrastructure

#55619 fixed chrome.action.enable/disable: tabId is optional
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#55622 [README] Translate heading references
  README.cn.md
  README.es.md
  README.it.md
  README.ja.md
  types/node/scripts/generate-docs/README.md
Labels: Edits Infrastructure, Critical package

#55594 Fix type definition for onPassword prop in react-pdf lib
  types/react-pdf/dist/Document.d.ts
Labels: Popular package, Owner Approved, Untested Change

#55370 [jaeger-client] Supported the ability to set context key
  types/jaeger-client/index.d.ts
Labels: Owner Approved, Untested Change, Unreviewed

#54885 Update rxjs dependency in @types/inquirer
  types/console-ui/index.d.ts
  types/inquirer-autocomplete-prompt/index.d.ts
  types/inquirer-fuzzy-path/index.d.ts
  types/inquirer-npm-name/index.d.ts
  types/inquirer/index.d.ts
  types/inquirer/package.json
  types/yeoman-environment/index.d.ts
  types/yeoman-generator/index.d.ts
  types/yeoman-test/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Untested Change

#55405 types/xrm - Added Entity and EntityReference interfaces to WebApiOffline
  types/xrm/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#55412 Fix @ckeditor/core Plugin destroy method
  types/ckeditor__ckeditor5-autosave/ckeditor__ckeditor5-autosave-tests.ts
  types/ckeditor__ckeditor5-autosave/v27/ckeditor__ckeditor5-autosave-tests.ts
  types/ckeditor__ckeditor5-core/ckeditor__ckeditor5-core-tests.ts
  types/ckeditor__ckeditor5-core/src/plugin.d.ts
  types/ckeditor__ckeditor5-core/v27/ckeditor__ckeditor5-core-tests.ts
  types/ckeditor__ckeditor5-core/v27/src/plugin.d.ts
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved

#55494 Remove from definition owners
  types/node-forge/index.d.ts
Labels: Popular package, Author is Owner, Untested Change, Edits Owners

#55481 feat(apple-mapkit-js): lint fixes & migrate Map Events to individual map type event
  types/apple-mapkit-js-browser/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#55497 smartystreets-javascript-sdk: fix typo Componenet to Component
  types/smartystreets-javascript-sdk/index.d.ts
Labels: Other Approved, Owner Approved, Untested Change

#55480 fix(jira-client): `listProjects` should return an array
  types/jira-client/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#55435 prosemirror-view@1.19.3: Fix `update` function in `NodeView`
  types/prosemirror-view/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#55469 Fix @types/babel__core PluginPass['filename'] may equal undefined
  types/babel__core/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#55597 sql.js: Support import sql.js/dist/sql*
  types/sql.js/OTHER_FILES.txt
  types/sql.js/dist/sql-asm-debug.d.ts
  types/sql.js/dist/sql-asm-memory-growth.d.ts
  types/sql.js/dist/sql-asm.d.ts
  types/sql.js/dist/sql-wasm-debug.d.ts
  types/sql.js/dist/sql-wasm.d.ts
  types/sql.js/sql.js-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Check Config

#55472 [is-function] Allow `is-function` to be passed no arguments
  types/is-function/index.d.ts
  types/is-function/is-function-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#55431 Fix @types/chai Allow chaining with a/an
  types/chai/v2/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#55425 fix(node): error when exactOptionalPropertyTypes is enabled
  types/node/globals.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#55623 Add scorm-browser package definition
  types/scorm-browser/1.2/CMIDataTypes.d.ts
  types/scorm-browser/1.2/CMIElement.d.ts
  types/scorm-browser/1.2/CMIErrorCode.d.ts
  types/scorm-browser/1.2/CMIVocabulary.d.ts
  types/scorm-browser/1.2/index.d.ts
  types/scorm-browser/index.d.ts
  types/scorm-browser/scorm-browser-tests.ts
  types/scorm-browser/tsconfig.json
  types/scorm-browser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55237 [react-native] adds missing background location permission type for PermissionAndroid.
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Other Approved, Popular package, Unreviewed

#55014 [bitauth] Bugfix: bitauth middleware is already a function
  types/bitauth/bitauth-tests.ts
  types/bitauth/index.d.ts
Labels: Self Merge, Maintainer Approved

#55508 Updated "chrome.downloads"
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#55387 [window-size]: Update to version 1.1.1
  types/window-size/index.d.ts
  types/window-size/tsconfig.json
  types/window-size/window-size-tests.ts
Labels: Self Merge, Maintainer Approved, Check Config, Edits Owners

#55514 [p5] fix type of `p5.Vector.lerp`
  types/p5/src/math/p5.Vector.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#55604 docopt: Make options parameter optional
  types/docopt/docopt-tests.ts
  types/docopt/index.d.ts
Labels: Self Merge, Owner Approved

#55552 tuya-panel-kit: add some comment and types
  types/tuya-panel-kit/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#55418 [node] Update vm
  types/node/index.d.ts
  types/node/test/vm.ts
  types/node/vm.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Edits Owners

#55504 [passport-discord] Typing fixes
  types/passport-discord/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change, Edits Owners

#55618 Adding types for set-tz library
  types/set-tz/index.d.ts
  types/set-tz/set-tz-tests.ts
  types/set-tz/tsconfig.json
  types/set-tz/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#55339 Update localize types to current version
  types/localizejs-library/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#55398 add(fontagon): new definition
  types/fontagon/fontagon-tests.ts
  types/fontagon/index.d.ts
  types/fontagon/tsconfig.json
  types/fontagon/tslint.json
  types/ttf2woff/index.d.ts
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved

#55012 update(romans): CommonJS migration and v1.1
  types/romans/index.d.ts
  types/romans/romans-tests.ts
  types/romans/test/romans-tests.global.ts
  types/romans/tsconfig.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#55607 Links: use https for some urls
  README.cn.md
  README.es.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  types/angular-fullscreen/index.d.ts
  types/angular-ui-router/angular-ui-router-tests.ts
  types/charset/charset-tests.ts
  types/compression/index.d.ts
  types/espruino/index.d.ts
  types/fbjs/lib/TouchEventUtils.d.ts
  types/glob-watcher/index.d.ts
  types/google-drive-realtime-api/index.d.ts
  types/gulp-ruby-sass/index.d.ts
  types/hapi/v16/index.d.ts
  types/highland/index.d.ts
  types/iitc/core/utils_misc.d.ts
  types/jquery/v1/jquery-tests.ts
  types/jquery/v2/jquery-tests.ts
  types/jsdom/v2/jsdom-tests.ts
  types/materialize-css/v0/index.d.ts
  types/ng-showdown/index.d.ts
  types/node/index.d.ts
  types/node/node-tests.ts
  types/node/test/stream.ts
  types/node/v12/index.d.ts
  types/node/v12/node-tests.ts
  types/node/v12/test/stream.ts
  types/node/v14/index.d.ts
  types/node/v14/node-tests.ts
  types/node/v14/test/stream.ts
  types/qunit/v1/qunit-tests.ts
  types/ramda/test/where-tests.ts
  types/react-native-bcrypt/index.d.ts
  types/react-tagcloud/react-tagcloud-tests.tsx
  types/redis/index.d.ts
  types/simple-peer/index.d.ts
  types/vinyl/index.d.ts
  types/website-scraper/website-scraper-tests.ts
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package, Too Many Owners, Edits Owners

#55240 Added type definitions for `markdown-navbar`
  types/markdown-navbar/index.d.ts
  types/markdown-navbar/markdown-navbar-tests.ts
  types/markdown-navbar/tsconfig.json
  types/markdown-navbar/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55523 Fix a typo in `inquirer` type-declarations
  types/inquirer/inquirer-tests.ts
  types/inquirer/lib/utils/utils.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#55371 [keyv] correct types for `serialize` & `deserialize` options keys
  types/keyv/index.d.ts
  types/keyv/keyv-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#53947 [s3rver] Update the types to v3.7
  types/s3rver/index.d.ts
  types/s3rver/s3rver-tests.ts
  types/s3rver/tslint.json
Labels: Self Merge, Maintainer Approved, Edits Owners

#55624 Add d3-org-chart types
  types/d3-org-chart/d3-org-chart-tests.ts
  types/d3-org-chart/index.d.ts
  types/d3-org-chart/tsconfig.json
  types/d3-org-chart/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55629 CI: add workflow_dispatch
  .github/workflows/CI.yml
Labels: Edits Infrastructure

#55334 @types/akamai-edgeworkers - Added TransformStream and related interfaces of WHATWG Streams API in the Types definitions
  types/akamai-edgeworkers/index.d.ts
  types/akamai-edgeworkers/test/transformstream.ts
  types/akamai-edgeworkers/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Owners

#55614 [express-http-proxy]: fix typings for proxyRes, proxyReq
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Self Merge, Owner Approved

#55419 Add missing 'zmin' and 'zmax' in PlotData definition
  types/plotly.js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#55433 Fix messageMove response type in imapflow module
  types/imapflow/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#54650 [@types/urijs] Fix unnecessarily strict query params
  types/urijs/index.d.ts
  types/urijs/test/urijs-dom.test.ts
  types/urijs/test/urijs-nodejs.test.ts
Labels: Popular package, Self Merge, Owner Approved

#55613 [sharp] Add types for 0.29 additions
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#55625 [README] Retire manual table of contents
  README.cn.md
  README.es.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
Labels: Edits Infrastructure

#55212 unit tests and declaration file are refactored.
  types/nut-pipe/index.d.ts
  types/nut-pipe/nut-pipe-tests.ts
Labels: Self Merge, Author is Owner, No Other Owners

#55499 update(html-minifier-terser): v6 updates
  types/html-minifier-terser/html-minifier-terser-tests.ts
  types/html-minifier-terser/index.d.ts
Labels: Self Merge, Author is Owner, Critical package, No Other Owners

#55234 [google-map-react] Add id as an option that is passed to script loader
  types/google-map-react/google-map-react-tests.tsx
  types/google-map-react/index.d.ts
Labels: Popular package, Self Merge

#55636 add: type definition for apimatic__json-bigint
  types/apimatic__json-bigint/apimatic__json-bigint-tests.ts
  types/apimatic__json-bigint/index.d.ts
  types/apimatic__json-bigint/tsconfig.json
  types/apimatic__json-bigint/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55595 feat: minimal types for barnard59
  types/barnard59-core/barnard59-core-tests.ts
  types/barnard59-core/index.d.ts
  types/barnard59-core/lib/Pipeline.d.ts
  types/barnard59-core/lib/factory/pipeline.d.ts
  types/barnard59-core/lib/run.d.ts
  types/barnard59-core/package.json
  types/barnard59-core/tsconfig.json
  types/barnard59-core/tslint.json
  types/barnard59/barnard59-tests.ts
  types/barnard59/findPipeline.d.ts
  types/barnard59/index.d.ts
  types/barnard59/package.json
  types/barnard59/runner.d.ts
  types/barnard59/tsconfig.json
  types/barnard59/tslint.json
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved

#55250 [koa__router] use consistent default types and rename CustomT to ContextT
  types/koa__router/index.d.ts
  types/koa__router/koa__router-tests.ts
Labels: Popular package, Self Merge

#55638 progressbar.js: change container from SVGPathElement to HTMLElement
  types/progressbar.js/shape.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#55652 Revert "CI: add workflow_dispatch (#55629)"
  .github/workflows/CI.yml
Labels: Edits Infrastructure

#55059 [powerapps-component-framework] Update paging API: firstPageNumber, lastPageNumber, pageSize, loadOnlyNewPage
  types/powerapps-component-framework/componentframework.d.ts
  types/powerapps-component-framework/powerapps-component-framework-tests.ts
Labels: Self Merge, Owner Approved

#55635 feat(node): v16.9
  types/node/crypto.d.ts
  types/node/index.d.ts
  types/node/stream.d.ts
  types/node/test/crypto.ts
  types/node/test/stream.ts
  types/node/test/util.ts
  types/node/util.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#55570 add types for service-worker-updater
  types/service-worker-updater/index.d.ts
  types/service-worker-updater/service-worker-updater-tests.tsx
  types/service-worker-updater/tsconfig.json
  types/service-worker-updater/tslint.json
Labels: Other Approved, New Definition, Self Merge

#55555 Add @trimblemaps/trimblemaps-js Types
  types/trimblemaps__trimblemaps-js/index.d.ts
  types/trimblemaps__trimblemaps-js/trimblemaps__trimblemaps-js-tests.ts
  types/trimblemaps__trimblemaps-js/tsconfig.json
  types/trimblemaps__trimblemaps-js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55456 superagent is now actually typeof SuperAgentStatic
  types/superagent-proxy/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#55666 improvements to RecordRTC types
  types/recordrtc/index.d.ts
  types/recordrtc/recordrtc-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#55648 barnard59-core: complete Pipeline class hierarchy
  types/barnard59-core/barnard59-core-tests.ts
  types/barnard59-core/index.d.ts
  types/barnard59-core/lib/Pipeline.d.ts
  types/barnard59-core/lib/Step.d.ts
  types/barnard59-core/lib/StreamObject.d.ts
  types/barnard59-core/lib/factory/pipeline.d.ts
  types/barnard59/runner.d.ts
Labels: Self Merge, Author is Owner, Edits multiple packages, No Other Owners

#55656 Add types for cytoscape-cxtmenu
  types/cytoscape-cxtmenu/cytoscape-cxtmenu-tests.ts
  types/cytoscape-cxtmenu/index.d.ts
  types/cytoscape-cxtmenu/tsconfig.json
  types/cytoscape-cxtmenu/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55643 [sharp] Add types for 0.29.1 additions
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#55536 chore: add types for netlify-auth-providers
  types/netlify-auth-providers/index.d.ts
  types/netlify-auth-providers/netlify-auth-providers-tests.ts
  types/netlify-auth-providers/tsconfig.json
  types/netlify-auth-providers/tslint.json
Labels: New Definition, Self Merge

#55650 Adding barnard59-base and barnard59-graph-store
  types/barnard59-base/barnard59-base-tests.ts
  types/barnard59-base/combine.d.ts
  types/barnard59-base/concat.d.ts
  types/barnard59-base/filter.d.ts
  types/barnard59-base/flatten.d.ts
  types/barnard59-base/forEach.d.ts
  types/barnard59-base/glob.d.ts
  types/barnard59-base/index.d.ts
  types/barnard59-base/json.d.ts
  types/barnard59-base/limit.d.ts
  types/barnard59-base/map.d.ts
  types/barnard59-base/nul.d.ts
  types/barnard59-base/offset.d.ts
  types/barnard59-base/stdout.d.ts
  types/barnard59-base/toReadable.d.ts
  types/barnard59-base/toString.d.ts
  types/barnard59-base/tsconfig.json
  types/barnard59-base/tslint.json
  types/barnard59-core/index.d.ts
  types/barnard59-graph-store/barnard59-graph-store-tests.ts
  types/barnard59-graph-store/get.d.ts
  types/barnard59-graph-store/index.d.ts
  types/barnard59-graph-store/package.json
  types/barnard59-graph-store/post.d.ts
  types/barnard59-graph-store/put.d.ts
  types/barnard59-graph-store/tsconfig.json
  types/barnard59-graph-store/tslint.json
Labels: New Definition, Self Merge, Edits multiple packages, No Other Owners

#55306 [justified-layout] Add `forcedAspectRatio` key to object
  types/justified-layout/index.d.ts
  types/justified-layout/justified-layout-tests.ts
Labels: Self Merge, Owner Approved

#55457 feat: add suggestedName to wicg-file-system-access
  types/wicg-file-system-access/index.d.ts
  types/wicg-file-system-access/wicg-file-system-access-tests.ts
Labels: Self Merge, Owner Approved

#55209 update analytics-node Identity type
  types/analytics-node/analytics-node-tests.ts
  types/analytics-node/index.d.ts
Labels: Popular package, Self Merge

#55674 Fix type of Domain in plotly.js PlotData
  types/plotly.js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#55668 feat(node): add missing KeyObject.from
  types/node/crypto.d.ts
  types/node/test/crypto.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#55275 [jest-dev-server] add path option
  types/jest-dev-server/index.d.ts
  types/jest-dev-server/jest-dev-server-tests.ts
Labels: Self Merge, Edits Owners

#55583 Added types for magicmirror-module
  types/magicmirror-module/index.d.ts
  types/magicmirror-module/magicmirror-module-tests.ts
  types/magicmirror-module/tsconfig.json
  types/magicmirror-module/tslint.json
Labels: New Definition, Self Merge

#55649 add: type definition for pino-datadog
  types/pino-datadog/index.d.ts
  types/pino-datadog/pino-datadog-tests.ts
  types/pino-datadog/tsconfig.json
  types/pino-datadog/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#54861 Fixed formidable definitions for breaking changes in EventEmitter in Node >= 13
  types/formidable/PersistentFile.d.ts
Labels: Unmerged, Popular package, Self Merge, Untested Change

#55579 @types/mui-datatables - Added missing row attribute to logic
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
Labels: Self Merge, Owner Approved

#55492 [simple-peer] Add missing trickle options to typedefs
  types/simple-peer/index.d.ts
  types/simple-peer/simple-peer-tests.ts
Labels: Self Merge, Owner Approved

#55315 add those missing parameters
  types/wegame-api/index.d.ts
  types/wegame-api/wegame-api-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#55697 webpack v4: Add infrastructureLogging option
  types/webpack/v4/index.d.ts
  types/webpack/v4/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#55203 [koa-proxy] Bugfix: Add encoding key
  types/koa-proxy/index.d.ts
  types/koa-proxy/koa-proxy-tests.ts
Labels: Self Merge

#55301 [delete-empty] Bugfix: Promise can take opts
  types/delete-empty/delete-empty-tests.ts
  types/delete-empty/index.d.ts
Labels: Self Merge

#55304 [graphql-depth-limit] Make ignore optional
  types/graphql-depth-limit/graphql-depth-limit-tests.ts
  types/graphql-depth-limit/index.d.ts
Labels: Self Merge, Owner Approved

#55308 [provinces] Add English key
  types/provinces/index.d.ts
  types/provinces/provinces-tests.ts
Labels: Self Merge, Maintainer Approved

#55475 [gulp-help] Adds gulp help options
  types/gulp-help/gulp-help-tests.ts
  types/gulp-help/index.d.ts
Labels: Other Approved, Self Merge

#55477 [gulp-protractor] Add missing keys to object
  types/gulp-protractor/gulp-protractor-tests.ts
  types/gulp-protractor/index.d.ts
Labels: Self Merge, Owner Approved

#55664 feat(relay-runtime): updates log function types
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#55706 [fix] remove nul.d.ts file
  types/barnard59-base/barnard59-base-tests.ts
  types/barnard59-base/combine.d.ts
  types/barnard59-base/index.d.ts
  types/barnard59-base/map.d.ts
  types/barnard59-base/nul.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved

#55368 Add lodash-es/tap
  types/lodash-es/index.d.ts
  types/lodash-es/lodash-es-tests.ts
  types/lodash-es/tap.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#55709 update(mini-css-extract-plugin): v2.3
  types/mini-css-extract-plugin/index.d.ts
  types/mini-css-extract-plugin/mini-css-extract-plugin-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#55723 [sax-stream] Adds noscript key
  types/sax-stream/index.d.ts
  types/sax-stream/sax-stream-tests.ts
Labels: Self Merge, Owner Approved

#55512 fix(react-datepicker): fix registerLocale localData type
  types/react-datepicker/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#55671 feat: export rdf-ext term as classes they are
  types/rdf-ext/lib/BlankNode.d.ts
  types/rdf-ext/lib/Dataset.d.ts
  types/rdf-ext/lib/DefaultGraph.d.ts
  types/rdf-ext/lib/Literal.d.ts
  types/rdf-ext/lib/NamedNode.d.ts
  types/rdf-ext/lib/Quad.d.ts
  types/rdf-ext/lib/Variable.d.ts
  types/rdf-ext/package.json
  types/rdf-ext/rdf-ext-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#55716 [apicache] Makes input argument of options optional
  types/apicache/apicache-tests.ts
  types/apicache/index.d.ts
Labels: Self Merge, Owner Approved

#55735 [object-hash] Function can return Buffer
  types/object-hash/index.d.ts
  types/object-hash/object-hash-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55733 [node-abi] Allow function to be given null
  types/node-abi/index.d.ts
  types/node-abi/node-abi-tests.ts
Labels: Self Merge, Owner Approved

#55730 [pascalcase] Widen input type
  types/pascalcase/index.d.ts
  types/pascalcase/pascalcase-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#55720 [inflection] Adds support for version key
  types/inflection/index.d.ts
  types/inflection/inflection-tests.ts
Labels: Self Merge, Owner Approved

#55202 [koa-ejs] Version bump: Add writeResp key
  types/koa-ejs/index.d.ts
  types/koa-ejs/koa-ejs-tests.ts
Labels: Self Merge

#55750 fix(luxon): rewrite and add `src/impl/formats` support
  types/luxon/src/datetime.d.ts
  types/luxon/src/impl/formats.d.ts
  types/luxon/test/luxon-tests.global.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#55483 [prosemirror-view] Re-add `| undefined` for TypeScript 4.4
  types/prosemirror-view/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#55744 [README] Replace invalid example links after removing ts3.6 support
  README.cn.md
  README.it.md
  README.ja.md
  README.md
  README.pt.md
Labels: Edits Infrastructure

#55694 [README] Rename README.cn.md to README.zh.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.ru.md
  README.zh.md
Labels: Edits Infrastructure

#55392 Fix koi-joi-router multipartOptions type
  types/koa-joi-router/index.d.ts
  types/koa-joi-router/koa-joi-router-tests.ts
Labels: Self Merge, Owner Approved

#55742 [prosemirror-menu] Make non-nullable renderGrouped's returned dom
  types/prosemirror-menu/index.d.ts
  types/prosemirror-menu/prosemirror-menu-tests.ts
Labels: Self Merge, Owner Approved

#55676 feat: added express-conditional-middleware
  types/express-conditional-middleware/express-conditional-middleware-tests.ts
  types/express-conditional-middleware/index.d.ts
  types/express-conditional-middleware/tsconfig.json
  types/express-conditional-middleware/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55582 Add types for node-hrx
  types/node-hrx/index.d.ts
  types/node-hrx/node-hrx-tests.ts
  types/node-hrx/tsconfig.json
  types/node-hrx/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#55547 [recharts] revert v1, fix ts4.4 error
  types/recharts/README.md
  types/recharts/index.d.ts
  types/recharts/recharts-tests.tsx
  types/recharts/tsconfig.json
  types/recharts/tslint.json
Labels: New Definition, Popular package

#55356 [node-red__registry] Fix send
  types/node-red__registry/index.d.ts
  types/node-red__registry/node-red__registry-tests.ts
Labels: Self Merge, Author is Owner, No Other Owners
