Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-07, with the labels that each got.

#54023 [react] Added types for anchor 'target' attribute
  types/react/index.d.ts
  types/react/test/elementAttributes.tsx
  types/react/v16/index.d.ts
  types/react/v16/test/elementAttributes.tsx
Labels: Author is Owner, Critical package, Owner Approved

#53937 Handle optional properties case for `mongodb` 's `distinct`
  types/mongodb/index.d.ts
  types/mongodb/test/collection/distinct.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Self Merge

#54196 `debug`: adds "selectColor" method to debug.Debug (default) interface
  types/debug/debug-tests.ts
  types/debug/index.d.ts
Labels: Critical package, Edits Owners, Owner Approved

#54176 [mapbox-gl] Remove duplicate types
  types/mapbox-gl/index.d.ts
Labels: Owner Approved, Popular package, Untested Change

#54120 [ramda] Fix docstring for tap()
  types/ramda/index.d.ts
Labels: Owner Approved, Popular package, Untested Change

#54115 [d3-random] Enable default linting rules
  types/d3-random/index.d.ts
  types/d3-random/tslint.json
Labels: Author is Owner, Popular package, Untested Change

#54200 Add type definitions to async-exit-hook
  types/async-exit-hook/async-exit-hook-tests.ts
  types/async-exit-hook/index.d.ts
  types/async-exit-hook/tsconfig.json
  types/async-exit-hook/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53953 [react-big-calendar] add dayColumnWrapper components property
  types/react-big-calendar/index.d.ts
Labels: Owner Approved, Untested Change

#53948 Please remove me (Digiguru) as author
  types/react/index.d.ts
  types/react/v15/index.d.ts
  types/react/v16/index.d.ts
  types/vhtml/index.d.ts
Labels: Critical package, Edits Owners, Edits multiple packages, Maintainer Approved, Owner Approved, Self Merge, Unmerged, Untested Change

#54199 Fix dom-mediacapture-record tests for TS 4.4
  types/dom-mediacapture-transform/dom-mediacapture-transform-tests.ts
Labels: Owner Approved, Self Merge

#54047 Type declarations for cookieconsent
  types/cookieconsent/cookieconsent-tests.ts
  types/cookieconsent/index.d.ts
  types/cookieconsent/package.json
  types/cookieconsent/tsconfig.json
  types/cookieconsent/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54149 [PDFKit] Add list options to 'TextOptions' interface
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#54116 [d3-scale] Enable default linting rules
  types/d3-scale/index.d.ts
  types/d3-scale/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54109 [d3-hierarchy] Enable default linting rules
  types/d3-hierarchy/index.d.ts
  types/d3-hierarchy/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54106 [d3-fetch] Enable default linting rules
  types/d3-fetch/index.d.ts
  types/d3-fetch/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54105 [d3-drag] Enable default linting rules
  types/d3-drag/index.d.ts
  types/d3-drag/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54066 [d3-contour] Enable default linting rules
  types/d3-contour/index.d.ts
  types/d3-contour/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54185 Bugfix: allow natural-compare to support numbers
  types/natural-compare/index.d.ts
  types/natural-compare/natural-compare-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#54189 [chrome-remote-interface] Add event callbacks
  types/chrome-remote-interface/chrome-remote-interface-tests.ts
  types/chrome-remote-interface/index.d.ts
Labels: Author is Owner, Owner Approved, Self Merge

#54128 [d3-shape] Fix build
  types/d3-shape/d3-shape-tests.ts
  types/d3-shape/v1/d3-shape-tests.ts
  types/d3-shape/v2/d3-shape-tests.ts
Labels: Author is Owner, Popular package

#53994 Ensure Ember types are compatible with `strictFunctionTypes`
  types/ember/test/create.ts
  types/ember/test/helper.ts
  types/ember/test/observable.ts
  types/ember/test/private/observable-tests.ts
  types/ember/tsconfig.json
  types/ember__component/helper.d.ts
Labels: Author is Owner, Check Config, Edits multiple packages, Maintainer Approved, Owner Approved, Popular package, Self Merge

#54104 [d3-dispatch] Enable default linting rules
  types/d3-dispatch/index.d.ts
  types/d3-dispatch/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#53978 [jsonwebtoken] Fix decode types and tests
  types/jsonwebtoken/index.d.ts
  types/jsonwebtoken/jsonwebtoken-tests.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Self Merge

#54114 fix(prettier): all `default` value should be optional
  types/prettier/index.d.ts
  types/prettier/prettier-tests.ts
Labels: Critical package, Edits Owners, Maintainer Approved, Owner Approved, Self Merge

#54173 Removed unnecessary children prop in react-scroll-sync props interfaces
  types/react-scroll-sync/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#54107 [d3-force] Enable default linting rules
  types/d3-force/index.d.ts
  types/d3-force/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54108 [d3-geo] Enable default linting rules
  types/d3-geo/index.d.ts
  types/d3-geo/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54111 [d3-quadtree] Enable default linting rules
  types/d3-quadtree/index.d.ts
  types/d3-quadtree/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54127 [d3-zoom] Enable default linting rules
  types/d3-zoom/index.d.ts
  types/d3-zoom/tslint.json
Labels: Author is Owner, Maintainer Approved, Popular package, Self Merge, Untested Change

#54126 [d3-transition] Enable default linting rules
  types/d3-transition/index.d.ts
  types/d3-transition/tslint.json
Labels: Author is Owner, Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#54210 [react-datepicker] remove Rogach from notifications
  types/react-datepicker/index.d.ts
Labels: Author is Owner, Edits Owners, Popular package, Untested Change

#53935 Added Types for Package: poisson-disk-sampling
  types/poisson-disk-sampling/OTHER_FILES.txt
  types/poisson-disk-sampling/index.d.ts
  types/poisson-disk-sampling/poisson-disk-sampling-tests.ts
  types/poisson-disk-sampling/src/implementations/fixed-density.d.ts
  types/poisson-disk-sampling/src/implementations/variable-density.d.ts
  types/poisson-disk-sampling/src/neighbourhood.d.ts
  types/poisson-disk-sampling/src/sphere-random.d.ts
  types/poisson-disk-sampling/src/tiny-ndarray.d.ts
  types/poisson-disk-sampling/tsconfig.json
  types/poisson-disk-sampling/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#54058 react-gravatar: added default 'mp' to match docs
  types/react-gravatar/index.d.ts
Labels: Maintainer Approved, Self Merge, Untested Change

#53943 Add errorHandler argument to `*hot.accept` in webpack-env
  types/webpack-env/index.d.ts
  types/webpack-env/webpack-env-tests.ts
Labels: Critical package, Maintainer Approved, Other Approved, Self Merge

#54205 [forge-viewer] update for version 7.46
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Maintainer Approved, Self Merge, Untested Change

#54045 More accurate model relationship type for eachRelationship in ember-data
  types/ember-data/index.d.ts
  types/ember-data/test/relationships.ts
Labels: Owner Approved, Self Merge

#54214 Update phonegap for TS 4.4's DOM
  types/phonegap/index.d.ts
Labels: Untested Change

#54215 Make wicg-entries-api match TS 4.4's DOM types
  types/wicg-entries-api/index.d.ts
Labels: Untested Change

#53566 feat(node): v15.14
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/crypto.d.ts
  types/node/fs/promises.d.ts
  types/node/http.d.ts
  types/node/index.d.ts
  types/node/net.d.ts
  types/node/test/buffer.ts
  types/node/test/child_process.ts
  types/node/test/crypto.ts
  types/node/test/fs.ts
  types/node/test/http.ts
  types/node/test/net.ts
  types/node/test/stream.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Other Approved, Self Merge

#54203 Upgrade wordpress/* type dependencies
  types/wordpress__block-editor/index.d.ts
  types/wordpress__block-editor/package.json
  types/wordpress__blocks/index.d.ts
  types/wordpress__blocks/package.json
  types/wordpress__components/index.d.ts
  types/wordpress__components/package.json
  types/wordpress__compose/index.d.ts
  types/wordpress__compose/package.json
  types/wordpress__edit-post/index.d.ts
  types/wordpress__edit-post/package.json
  types/wordpress__editor/index.d.ts
  types/wordpress__editor/package.json
  types/wordpress__media-utils/index.d.ts
  types/wordpress__media-utils/package.json
  types/wordpress__plugins/index.d.ts
  types/wordpress__plugins/package.json
Labels: Edits multiple packages, Maintainer Approved, Other Approved, Owner Approved, Self Merge, Untested Change

#54034 [chec/commerce.js] Checkout Token "gateways" now returns an array of Gateway types
  types/chec__commerce.js/types/checkout-token.d.ts
  types/chec__commerce.js/types/gateway.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Self Merge, Untested Change

#54129 update(postcss-modules-extract-imports): v3.0 update
  types/postcss-modules-extract-imports/index.d.ts
  types/postcss-modules-extract-imports/package.json
  types/postcss-modules-extract-imports/postcss-modules-extract-imports-tests.ts
  types/postcss-modules-extract-imports/tsconfig.json
Labels: Check Config, Maintainer Approved, Owner Approved, Popular package, Self Merge

#54048 update(validator): minor updates to v13.6
  types/validator/es/lib/isBase58.d.ts
  types/validator/es/lib/isVAT.d.ts
  types/validator/index.d.ts
  types/validator/lib/isBase58.d.ts
  types/validator/lib/isVAT.d.ts
  types/validator/validator-tests.ts
Labels: Critical package, Edits Owners, Maintainer Approved, Self Merge

#54143 Add voilab-pdf-table
  types/voilab-pdf-table/index.d.ts
  types/voilab-pdf-table/plugins/fitcolumn.d.ts
  types/voilab-pdf-table/plugins/rowshader.d.ts
  types/voilab-pdf-table/tsconfig.json
  types/voilab-pdf-table/tslint.json
  types/voilab-pdf-table/voilab-pdf-table-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#53627 fix(canvas-fit): property fix
  types/canvas-fit/canvas-fit-tests.ts
  types/canvas-fit/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Self Merge

#53970 Tedious - Adding setTimeout method to Request - v11.0.9
  types/tedious/index.d.ts
Labels: Maintainer Approved, Self Merge, Untested Change

#54130 add(postcss-plugins): new definition
  types/postcss-plugins/index.d.ts
  types/postcss-plugins/postcss-plugins-tests.ts
  types/postcss-plugins/tsconfig.json
  types/postcss-plugins/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53707 update(typopo): v2.5
  types/typopo/index.d.ts
  types/typopo/typopo-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Self Merge

#54060 [estree] add exported for ExportAllDeclaration
  types/estree/index.d.ts
Labels: Critical package, Maintainer Approved, Self Merge, Untested Change

#54218 [@types/node-telegram-bot-api] Added types for editMessageMedia function
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Edits Owners, Owner Approved, Popular package, Self Merge

#54235 [react-instantsearch] correctly type the "this" type of connectors
  types/react-instantsearch-core/index.d.ts
  types/react-instantsearch-core/react-instantsearch-core-tests.tsx
Labels: Author is Owner, Owner Approved, Self Merge

#54213 @types/chart.js labelColor is now an array of ChartTooltipLabelColors, closes #53517
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
Labels: Edits Owners, Owner Approved, Popular package, Self Merge

#54236 [react-beautiful-dnd] Update types to 13.1. Adds default sensor exports.
  types/react-beautiful-dnd/index.d.ts
  types/react-beautiful-dnd/react-beautiful-dnd-tests.tsx
Labels: Edits Owners, Owner Approved, Popular package, Self Merge

#54241 Add undefined to optional properties
  types/zarinpal-checkout/index.d.ts
  types/zchat-browser/index.d.ts
  types/zdog/index.d.ts
  types/zedit__upf/index.d.ts
  types/zen-observable/index.d.ts
  types/zepto/index.d.ts
  types/zeroclipboard/index.d.ts
  types/zeroclipboard/v1/index.d.ts
  types/zfont/index.d.ts
  types/ziggy-js/index.d.ts
  types/zingchart/es6/index.d.ts
  types/zip-webpack-plugin/index.d.ts
  types/zip.js/index.d.ts
  types/zui/index.d.ts
  types/zumly/index.d.ts
  types/zurb-twentytwenty/index.d.ts
Labels: Critical package, Edits multiple packages, Untested Change

#54242 Add undefined to optional properties, part Y
  types/ya-disk/index.d.ts
  types/yadda/lib/Macro.d.ts
  types/yadda/lib/parsers/FeatureParser.d.ts
  types/yaireo__tagify/dist/react.tagify.d.ts
  types/yaireo__tagify/index.d.ts
  types/yallist/index.d.ts
  types/yallist/yallist-tests.ts
  types/yandex-maps/index.d.ts
  types/yandex-metrika-tag/index.d.ts
  types/yandex-money-sdk/index.d.ts
  types/yar/index.d.ts
  types/yargs-interactive/index.d.ts
  types/yargs-parser/index.d.ts
  types/yargs-parser/v11/index.d.ts
  types/yargs-unparser/index.d.ts
  types/yargs/index.d.ts
  types/yargs/v10/index.d.ts
  types/yargs/v11/index.d.ts
  types/yargs/v12/index.d.ts
  types/yargs/v13/index.d.ts
  types/yargs/v15/index.d.ts
  types/yargs/v16/index.d.ts
  types/yargs/v8/index.d.ts
  types/yarnpkg__lockfile/index.d.ts
  types/yauzl/index.d.ts
  types/yayson/index.d.ts
  types/ydn-db/index.d.ts
  types/yeoman-environment/index.d.ts
  types/yeoman-environment/lib/adapter.d.ts
  types/yeoman-environment/lib/util/log.d.ts
  types/yeoman-generator/index.d.ts
  types/yeoman-test/index.d.ts
  types/yesql/index.d.ts
  types/yog-bigpipe/index.d.ts
  types/yog-log/index.d.ts
  types/yog2-kernel/index.d.ts
  types/yoga-layout/index.d.ts
  types/youtube-dl/index.d.ts
  types/youtube-player/dist/types.d.ts
  types/youtube/index.d.ts
  types/yt-player/index.d.ts
  types/yt-search/index.d.ts
  types/yuka/src/navigation/navmesh/NavMeshLoader.d.ts
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Critical package, Edits multiple packages, Too Many Owners

#54244 Add undefined to optional properties, part X
  types/x-axios-progress-bar/index.d.ts
  types/x-editable/index.d.ts
  types/xar/index.d.ts
  types/xast/index.d.ts
  types/xdate/index.d.ts
  types/xelib/index.d.ts
  types/xml-c14n/index.d.ts
  types/xml-crypto/index.d.ts
  types/xml-encryption/index.d.ts
  types/xml-flow/index.d.ts
  types/xml-parser/index.d.ts
  types/xml-zero-lexer/index.d.ts
  types/xml/index.d.ts
  types/xml2js/index.d.ts
  types/xml2json/index.d.ts
  types/xmldoc/index.d.ts
  types/xmldom/index.d.ts
  types/xmljs/index.d.ts
  types/xmlrpc/index.d.ts
  types/xmltojson/index.d.ts
  types/xo/index.d.ts
  types/xrm/index.d.ts
  types/xrm/v6/index.d.ts
  types/xrm/v7/index.d.ts
  types/xrm/v8/index.d.ts
  types/xstyled__styled-components/index.d.ts
  types/xstyled__system/index.d.ts
Labels: Edits multiple packages, Owner Approved, Popular package, Untested Change

#54249 Add undefined to optional properties, part U
  types/udp-discovery/index.d.ts
  types/uglify-js/index.d.ts
  types/uglify-js/v2/index.d.ts
  types/uglifycss/index.d.ts
  types/uglifyjs-webpack-plugin/index.d.ts
  types/ui-grid/index.d.ts
  types/ui-router-extras/index.d.ts
  types/ui-select/index.d.ts
  types/uikit/index.d.ts
  types/uikit/v2/index.d.ts
  types/uinput/index.d.ts
  types/ultra-strftime/index.d.ts
  types/umbraco/umbraco-services.d.ts
  types/umd/index.d.ts
  types/umtrack-wx/index.d.ts
  types/umzug/index.d.ts
  types/underscore/index.d.ts
  types/undertaker/index.d.ts
  types/uni-app/lib/app.d.ts
  types/uni-app/lib/page.d.ts
  types/uni-app/lib/uni.d.ts
  types/uni-app/lib/vue.d.ts
  types/unist/index.d.ts
  types/universal-analytics/index.d.ts
  types/unix-permissions/index.d.ts
  types/until-promise/index.d.ts
  types/unused-files-webpack-plugin/index.d.ts
  types/unused-webpack-plugin/index.d.ts
  types/unzip-stream/index.d.ts
  types/unzipper/index.d.ts
  types/unzipper/unzipper-tests.ts
  types/update-notifier/index.d.ts
  types/update-notifier/v1/index.d.ts
  types/update-notifier/v2/index.d.ts
  types/uploadcare/index.d.ts
  types/upng-js/index.d.ts
  types/urijs/index.d.ts
  types/urijs/src/URITemplate.d.ts
  types/urlrouter/index.d.ts
  types/use-double-click/index.d.ts
  types/use-global-hook/index.d.ts
  types/user-agents/index.d.ts
  types/user-event/index.d.ts
  types/user-idle-observer/index.d.ts
  types/useragent/index.d.ts
  types/uslug/index.d.ts
  types/uuid-1345/index.d.ts
  types/uuid-1345/uuid-1345-tests.ts
  types/uuid/index.d.ts
  types/uuid/v2/index.d.ts
  types/uuid/v3/interfaces.d.ts
  types/uuid/v7/interfaces.d.ts
  types/uws/index.d.ts
Labels: Critical package, Edits multiple packages, The CI failed, Too Many Owners

#54247 Add team drives apis to google.picker types
  types/google.picker/google.picker-tests.ts
  types/google.picker/index.d.ts
Labels: Owner Approved, Self Merge

#53788 node-jose: added iv option to JWE.createEncrypt
  types/node-jose/index.d.ts
  types/node-jose/node-jose-tests.ts
Labels: Maintainer Approved, Self Merge

#54243 Add react-loading-overlay 1.0
  types/react-loading-overlay/index.d.ts
  types/react-loading-overlay/react-loading-overlay-tests.tsx
  types/react-loading-overlay/tsconfig.json
  types/react-loading-overlay/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54190 Make aframe work with TS 4.4 DOM
  types/aframe/index.d.ts
Labels: Untested Change

#54261 Update types for adeira__js
  types/adeira__js/adeira__js-tests.ts
  types/adeira__js/index.d.ts
Labels: Owner Approved, Self Merge

#54246 Add options param to isAlphaNumeric
  types/validator/index.d.ts
  types/validator/validator-tests.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Self Merge

#54230 Add types for extract-colors
  types/extract-colors/extract-colors-tests.ts
  types/extract-colors/index.d.ts
  types/extract-colors/tsconfig.json
  types/extract-colors/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54263 [json-string-splitter] Add type definitions for json-string-splitter
  types/json-string-splitter/index.d.ts
  types/json-string-splitter/json-string-splitter-tests.ts
  types/json-string-splitter/tsconfig.json
  types/json-string-splitter/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53540 Update SensorOptions in w3c-generic-sensor
  types/w3c-generic-sensor/index.d.ts
  types/w3c-generic-sensor/w3c-generic-sensor-tests.ts
Labels: Maintainer Approved, Self Merge

#54268 [react-phone-number-input] remove obsolete properties, rename flagsPath to flagUrl
  types/react-phone-number-input/index.d.ts
  types/react-phone-number-input/react-phone-number-input-tests.tsx
Labels: Owner Approved, Self Merge

#53984 wavesurfer.js: update to 5.1
  types/wavesurfer.js/index.d.ts
  types/wavesurfer.js/src/plugin/markers.d.ts
  types/wavesurfer.js/wavesurfer.js-tests.ts
Labels: Author is Owner, Edits Owners, Other Approved, Self Merge

#54219 [@types/quick-picker] Added type definitions.
  types/quick-picker/index.d.ts
  types/quick-picker/quick-picker-tests.tsx
  types/quick-picker/tsconfig.json
  types/quick-picker/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54264 [serverless] Correct cli.log signature
  types/serverless/index.d.ts
  types/serverless/serverless-tests.ts
Labels: Edits Owners, Owner Approved, Self Merge

#54279 [convict] Add ValidateOptions.output
  types/convict/convict-tests.ts
  types/convict/index.d.ts
Labels: Owner Approved, Popular package, Self Merge

#54274 react-big-calendar: export Views as const
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Owner Approved, Self Merge

#54290 slick-carousel: Rename argument of slickGoTo according to the documentation
  types/slick-carousel/index.d.ts
  types/slick-carousel/slick-carousel-tests.ts
Labels: Owner Approved, Self Merge

#54280 [google-apps-script] add url methods to SpreadsheetApp.RichTextValue and SpreadsheetApp.RichTextValueBuilder
  types/google-apps-script/google-apps-script-tests.ts
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
Labels: Owner Approved, Self Merge

#54292 psi // FIX: fix typo // rename treshold to threshold
  types/psi/index.d.ts
Labels: Maintainer Approved, Self Merge, Untested Change

#54181 Remove index signature from unist.Node
  types/hast/hast-tests.ts
  types/unist/index.d.ts
  types/unist/unist-tests.ts
  types/xast/xast-tests.ts
Labels: Critical package, Edits Owners, Edits multiple packages, Maintainer Approved, Owner Approved, Self Merge

#54291 [three] r130
  types/three/examples/jsm/loaders/GLTFLoader.d.ts
  types/three/examples/jsm/loaders/IFCLoader.d.ts
  types/three/examples/jsm/loaders/SVGLoader.d.ts
  types/three/examples/jsm/misc/Volume.d.ts
  types/three/examples/jsm/objects/Water2.d.ts
  types/three/index.d.ts
  types/three/src/core/InterleavedBuffer.d.ts
  types/three/src/core/InterleavedBufferAttribute.d.ts
  types/three/src/extras/core/Shape.d.ts
  types/three/src/geometries/BoxGeometry.d.ts
  types/three/src/geometries/CircleGeometry.d.ts
  types/three/src/geometries/ConeGeometry.d.ts
  types/three/src/geometries/CylinderGeometry.d.ts
  types/three/src/geometries/DodecahedronGeometry.d.ts
  types/three/src/geometries/ExtrudeGeometry.d.ts
  types/three/src/geometries/IcosahedronGeometry.d.ts
  types/three/src/geometries/LatheGeometry.d.ts
  types/three/src/geometries/OctahedronGeometry.d.ts
  types/three/src/geometries/PlaneGeometry.d.ts
  types/three/src/geometries/PolyhedronGeometry.d.ts
  types/three/src/geometries/RingGeometry.d.ts
  types/three/src/geometries/ShapeGeometry.d.ts
  types/three/src/geometries/SphereGeometry.d.ts
  types/three/src/geometries/TetrahedronGeometry.d.ts
  types/three/src/geometries/TorusGeometry.d.ts
  types/three/src/geometries/TorusKnotGeometry.d.ts
  types/three/src/geometries/TubeGeometry.d.ts
  types/three/src/helpers/AxesHelper.d.ts
  types/three/src/loaders/ObjectLoader.d.ts
  types/three/src/materials/ShaderMaterial.d.ts
  types/three/src/objects/InstancedMesh.d.ts
  types/three/src/objects/Line.d.ts
  types/three/src/objects/LineLoop.d.ts
  types/three/src/objects/LineSegments.d.ts
  types/three/src/objects/Mesh.d.ts
  types/three/src/objects/Points.d.ts
  types/three/src/objects/SkinnedMesh.d.ts
  types/three/src/renderers/webgl/WebGLAttributes.d.ts
  types/three/test/buffergeometry/buffergeometry-instancing-interleaved.ts
  types/three/test/objects/instanced-mesh.ts
  types/three/tsconfig.json
Labels: Author is Owner, Owner Approved, Popular package, Self Merge

#54297 Add namePrependSlash property to ZipOptions interface in archiver
  types/archiver/archiver-tests.ts
  types/archiver/index.d.ts
Labels: Maintainer Approved, Owner Approved, Popular package, Self Merge

#54281 Fix export to reflect updates to node HTTP package
  types/http-codes/http-codes-tests.ts
  types/http-codes/index.d.ts
  types/http-codes/tsconfig.json
Labels: Other Approved, Self Merge

#54282 [types/yargs] add getHelp function
  types/yargs/index.d.ts
  types/yargs/yargs-tests.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Self Merge

#54216 New @ckeditor/ckeditor5-build-inline v28
  types/ckeditor__ckeditor5-build-inline/ckeditor__ckeditor5-build-inline-tests.ts
  types/ckeditor__ckeditor5-build-inline/index.d.ts
  types/ckeditor__ckeditor5-build-inline/tsconfig.json
  types/ckeditor__ckeditor5-build-inline/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54227 Add types for chrome-location
  types/chrome-location/chrome-location-tests.ts
  types/chrome-location/index.d.ts
  types/chrome-location/tsconfig.json
  types/chrome-location/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54306 argparse: Add required: boolean to SubparserOptions
  types/argparse/argparse-tests.ts
  types/argparse/index.d.ts
Labels: Owner Approved, Popular package, Self Merge

#54221 Add declarations for the 'pgn-parser' npm package
  types/pgn-parser/index.d.ts
  types/pgn-parser/pgn-parser-tests.ts
  types/pgn-parser/tsconfig.json
  types/pgn-parser/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#54238 react-google-recaptcha: add missing asyncScriptOnLoad function, closes #53388
  types/react-google-recaptcha/index.d.ts
  types/react-google-recaptcha/react-google-recaptcha-tests.tsx
  types/react-google-recaptcha/tsconfig.json
Labels: Maintainer Approved, Popular package, Self Merge

#54273 remove(html2canvas): remove types
  notNeededPackages.json
  types/html2canvas/html2canvas-tests.ts
  types/html2canvas/index.d.ts
  types/html2canvas/tsconfig.json
  types/html2canvas/tslint.json
Labels: Edits Infrastructure

#54275 [@types/dns-packet] Support for more answer types
  types/dns-packet/dns-packet-tests.ts
  types/dns-packet/index.d.ts
Labels: Owner Approved, Popular package, Self Merge

#54325 Add undefined to optional properties, Mini to Node
  types/mini-css-extract-plugin/index.d.ts
  types/minimatch/index.d.ts
  types/minimist/index.d.ts
  types/minio/index.d.ts
  types/minipass/index.d.ts
  types/minizlib/index.d.ts
  types/mixpanel-browser/index.d.ts
  types/mkdirp/index.d.ts
  types/mocha/index.d.ts
  types/mock-fs/lib/filesystem.d.ts
  types/mockery/index.d.ts
  types/moment-duration-format/index.d.ts
  types/mongodb/index.d.ts
  types/mongodb/test/collection/bulkWrite.ts
  types/mongodb/test/collection/filterQuery.ts
  types/mongodb/test/collection/findX.ts
  types/mongodb/test/collection/insertX.ts
  types/mongodb/test/collection/updateX.ts
  types/mongodb/v1/index.d.ts
  types/mongodb/v2/index.d.ts
  types/morgan/index.d.ts
  types/move-concurrently/index.d.ts
  types/moxios/index.d.ts
  types/mssql/index.d.ts
  types/multer/index.d.ts
  types/multicast-dns/index.d.ts
  types/mustache/index.d.ts
  types/mute-stream/index.d.ts
  types/mysql/index.d.ts
  types/mz/child_process.d.ts
  types/mz/fs.d.ts
  types/mz/readline.d.ts
  types/nconf/index.d.ts
  types/ncp/index.d.ts
  types/needle/index.d.ts
  types/needle/v0/index.d.ts
  types/needle/v1/index.d.ts
  types/new-relic-browser/index.d.ts
  types/newrelic/index.d.ts
  types/node-cron/index.d.ts
  types/node-dir/index.d.ts
  types/node-fetch/externals.d.ts
  types/node-fetch/index.d.ts
  types/node-fetch/node-fetch-tests.ts
  types/node-forge/index.d.ts
  types/node-ipc/index.d.ts
  types/node-jose/index.d.ts
  types/node-notifier/index.d.ts
  types/node-notifier/notifiers/balloon.d.ts
  types/node-notifier/notifiers/growl.d.ts
  types/node-notifier/notifiers/notificationcenter.d.ts
  types/node-notifier/notifiers/notifysend.d.ts
  types/node-notifier/notifiers/toaster.d.ts
  types/node-notifier/v5/index.d.ts
  types/node-sass/index.d.ts
  types/node-schedule/index.d.ts
  types/node-telegram-bot-api/index.d.ts
  types/node-uuid/index.d.ts
Labels: Critical package, Edits multiple packages, The CI failed, Too Many Owners

#54262 [moddle] Add type definitions for moddle
  types/moddle/index.d.ts
  types/moddle/test/describers/extension/base.ts
  types/moddle/test/describers/extension/custom.ts
  types/moddle/test/describers/extension/index.ts
  types/moddle/test/describers/index.ts
  types/moddle/test/describers/meta.ts
  types/moddle/test/describers/properties.ts
  types/moddle/test/describers/propertiesExtended.ts
  types/moddle/test/describers/redefine.ts
  types/moddle/test/describers/replace.ts
  types/moddle/test/examples.ts
  types/moddle/test/lib-test.ts
  types/moddle/tsconfig.json
  types/moddle/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53912 upgrade knuddels-userapp-backend-api to version 1.20210618111624
  types/knuddels-userapp-backend-api/index.d.ts
Labels: Maintainer Approved, Self Merge, Unmerged, Untested Change

#54265 Fix improper InvalidTagEventData.message type on yaireo__tagify
  types/yaireo__tagify/index.d.ts
  types/yaireo__tagify/yaireo__tagify-tests.ts
Labels: Owner Approved, Self Merge

#54339 Forbid symlinks
  .github/workflows/CI.yml
Labels: Edits Infrastructure

#54301 [N3] Make format types stricter using tempate literals
  types/n3/index.d.ts
  types/n3/n3-tests.ts
Labels: Edits Owners, Owner Approved, Self Merge

#54341 [@types/wechat-miniprogram] update to 3.4
  types/wechat-miniprogram/index.d.ts
  types/wechat-miniprogram/lib.wx.api.d.ts
  types/wechat-miniprogram/lib.wx.page.d.ts
  types/wechat-miniprogram/test/issue.test.ts
Labels: Author is Owner, Other Approved, Self Merge

#54353 Add undefined to optional properties, Regenerator to Rimraf
  types/regenerator-runtime/index.d.ts
  types/registry-auth-token/index.d.ts
  types/regression/index.d.ts
  types/relateurl/index.d.ts
  types/relaxed-json/index.d.ts
  types/relay-runtime/lib/handlers/connection/ConnectionHandler.d.ts
  types/relay-runtime/lib/mutations/RelayDeclarativeMutationConfig.d.ts
  types/relay-runtime/lib/mutations/applyOptimisticMutation.d.ts
  types/relay-runtime/lib/mutations/commitMutation.d.ts
  types/relay-runtime/lib/network/RelayNetworkTypes.d.ts
  types/relay-runtime/lib/network/RelayObservable.d.ts
  types/relay-runtime/lib/query/fetchQuery.d.ts
  types/relay-runtime/lib/store/RelayModernEnvironment.d.ts
  types/relay-runtime/lib/store/RelayModernQueryExecutor.d.ts
  types/relay-runtime/lib/store/RelayModernStore.d.ts
  types/relay-runtime/lib/store/RelayResponseNormalizer.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
  types/relay-runtime/lib/subscription/requestSubscription.d.ts
  types/relay-runtime/lib/util/NormalizationNode.d.ts
  types/relay-runtime/lib/util/ReaderNode.d.ts
  types/relay-runtime/lib/util/RelayConcreteNode.d.ts
  types/relay-runtime/lib/util/RelayRuntimeTypes.d.ts
  types/request-ip/index.d.ts
  types/request-promise-native/index.d.ts
  types/request-promise/index.d.ts
  types/request/index.d.ts
  types/requestidlecallback/index.d.ts
  types/require-directory/index.d.ts
  types/require-from-string/index.d.ts
  types/requirejs/index.d.ts
  types/resize-observer-browser/index.d.ts
  types/resolve/index.d.ts
  types/response-time/index.d.ts
  types/restify/index.d.ts
  types/restify/v4/index.d.ts
  types/restify/v5/index.d.ts
  types/retry/index.d.ts
  types/rimraf/index.d.ts
  types/rimraf/v2/index.d.ts
Labels: Critical package, Edits multiple packages, Too Many Owners, Untested Change

#54348 feat: add revocation methods
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Author is Owner, Owner Approved, Self Merge

#53974 update(zenscroll): support for `noZensmooth` property
  types/zenscroll/index.d.ts
  types/zenscroll/zenscroll-tests.ts
Labels: Owner Approved, Self Merge

#54332 [@types/ramda] Fix fromPairs returning numeric keys
  types/ramda/index.d.ts
  types/ramda/test/fromPairs-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#53694 adds Resource as valid type for url option Resource.Model.fromGltf
  types/cesium/index.d.ts
  types/cesium/test/cesium-module.test.ts
Labels: Maintainer Approved, Self Merge

#54331 add notIncludeMembers for chai assert
  types/chai/chai-tests.ts
  types/chai/index.d.ts
  types/chai/v2/index.d.ts
Labels: Critical package, Owner Approved, Self Merge

#54303 google.picker - mark setEnableTeamDrives and SUPPORT_TEAM_DRIVES as deprecated
  types/google.picker/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#54259 [@types/babel__traverse] Add missing methods to NodePath: getPrevSibling(), getNextSibling()
  types/babel__traverse/index.d.ts
  types/babel__traverse/ts4.1/index.d.ts
Labels: Critical package, Owner Approved, Self Merge, Untested Change

#54209 [@types/koa__router] add optional generic types to method function definitions
  types/koa__router/index.d.ts
  types/koa__router/koa__router-tests.ts
  types/koa__router/tslint.json
Labels: Check Config, Owner Approved, Self Merge

#54154 react-simple-maps: update types for `onMove*` events of `ZoomableGroup`
  types/react-simple-maps/index.d.ts
Labels: Self Merge, Untested Change

#54367 [fontfaceobserver] Add version of package
  types/fontfaceobserver/index.d.ts
Labels: Popular package, Self Merge, Untested Change

#54307 Missing Type definition "retainEndDateOnFirstSelection" from version-1.3.0
  types/react-date-range/v0/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#54013 Couchbase type: Fixed Consistency enum 'NOT_BOUND' value, which was different than th…
  types/couchbase/index.d.ts
Labels: Self Merge, Untested Change

#54374 mapbox-gl: fix async signature for once method
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#54151 [express-serve-static-core] fix stack depth error on long path parameters
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
Labels: Critical package, Other Approved, Self Merge

#54343 fix ConcentricLayoutOptions for cytoscape
  types/cytoscape/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#53634 update(country-list-js): drop TS4.1 requirement
  types/country-list-js/country-list-js-tests.ts
  types/country-list-js/index.d.ts
Labels: Unreviewed

#53797 update(slug): global script usage
  types/slug/index.d.ts
  types/slug/slug-tests.ts
Labels: Unreviewed

#54364 [cross-zip] Add cross-zip
  types/cross-zip/cross-zip-tests.ts
  types/cross-zip/index.d.ts
  types/cross-zip/tsconfig.json
  types/cross-zip/tslint.json
Labels: New Definition

#54293 feat: add @adobe/aio-lib-analytics
  types/adobe__aio-lib-analytics/adobe__aio-lib-analytics-tests.ts
  types/adobe__aio-lib-analytics/index.d.ts
  types/adobe__aio-lib-analytics/tsconfig.json
  types/adobe__aio-lib-analytics/tslint.json
Labels: New Definition

#53933 Fixes resolve type for blueimp-load-image
  types/blueimp-load-image/index.d.ts
Labels: Owner Approved, Unreviewed, Untested Change

#54206 [@wordpress/components] Fix saramarcondes to sarayourfriend
  .github/CODEOWNERS
  types/wordpress__components/index.d.ts
Labels: Edits Infrastructure, Edits Owners, Owner Approved, Untested Change

#54039 aws-synthetics-puppeteer
  types/aws-synthetics-puppeteer/README.md
  types/aws-synthetics-puppeteer/aws-synthetics-puppeteer-tests.ts
  types/aws-synthetics-puppeteer/index.d.ts
  types/aws-synthetics-puppeteer/package.json
  types/aws-synthetics-puppeteer/src/BrokenLinkCheckerReport.d.ts
  types/aws-synthetics-puppeteer/src/Constants.d.ts
  types/aws-synthetics-puppeteer/src/HttpRequestCapturer.d.ts
  types/aws-synthetics-puppeteer/src/HttpRequestsReport.d.ts
  types/aws-synthetics-puppeteer/src/RequestResponseLogHelper.d.ts
  types/aws-synthetics-puppeteer/src/Synthetics.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsConfiguration.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsHarFileHelper.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsLink.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsLogger.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsMetricEmitter.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsReport.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsScreenshot.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsTracing.d.ts
  types/aws-synthetics-puppeteer/src/SyntheticsUploader.d.ts
  types/aws-synthetics-puppeteer/tsconfig.json
  types/aws-synthetics-puppeteer/tslint.json
Labels: New Definition

#54296 nodemailer: add missing properties to SentMessageInfo interface, closes #54161
  types/nodemailer/lib/json-transport.d.ts
  types/nodemailer/lib/sendmail-transport/index.d.ts
  types/nodemailer/lib/ses-transport.d.ts
  types/nodemailer/lib/smtp-transport.d.ts
  types/nodemailer/lib/stream-transport.d.ts
  types/nodemailer/nodemailer-tests.ts
Labels: Maintainer Approved, Other Approved, Popular package, Self Merge

#54384 fix build errors
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#54361 [yup] Add types for default on non array types.
  types/yup/index.d.ts
  types/yup/yup-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#54389 Fix a bunch of broken `https://github.com/DefinitelyTyped` owners
  types/absinthe__socket/index.d.ts
  types/amazon-dax-client/index.d.ts
  types/angular-notifications/index.d.ts
  types/angular-notify/index.d.ts
  types/angular-ui-notification/index.d.ts
  types/chai-like/index.d.ts
  types/conductor-animate/index.d.ts
  types/field/index.d.ts
  types/figlet/index.d.ts
  types/ft-poller/index.d.ts
  types/geobuf/index.d.ts
  types/ibm-openapi-validator/index.d.ts
  types/jquery.mmenu/index.d.ts
  types/node-ip2region/index.d.ts
  types/node-phpass/index.d.ts
  types/object.fromentries/index.d.ts
  types/posterus/index.d.ts
  types/procurios.resizesensor/index.d.ts
  types/relay-config/index.d.ts
  types/slick-carousel/index.d.ts
  types/static-eval/index.d.ts
  types/string-natural-compare/index.d.ts
  types/uri-template-lite/index.d.ts
  types/vhost/index.d.ts
  types/webmidi/index.d.ts
Labels: Edits Owners, Edits multiple packages, Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#54383 VS Code 1.58.0 Extension API
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#54255 update(jasmine): v3.8
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Critical package, Owner Approved, Self Merge

#54394 chore(node): correct misc issues
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/http.d.ts
  types/node/test/crypto.ts
  types/node/test/fs.ts
  types/node/test/http.ts
  types/node/test/url.ts
  types/node/url.d.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Self Merge

#54286 [node]: Allow timer functions to work with callbacks with a single unknown argument
  types/node/test/timers.ts
  types/node/timers.d.ts
Labels: Critical package, Maintainer Approved, Self Merge

#54363 react-redux: fix wrapping components with propTypes
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
  types/react-redux/v6/index.d.ts
  types/react-redux/v6/react-redux-tests.tsx
Labels: Critical package, Owner Approved, Self Merge

#53861 vhost - Add vhost payload to request handler
  types/vhost/index.d.ts
  types/vhost/vhost-tests.ts
Labels: Edits Owners, Self Merge

#54393 Re-remove Ailrun from figlet
  types/figlet/index.d.ts
Labels: Edits Owners, Owner Approved, Untested Change

#54330 @SimonSchick feat(node): v16.3
  types/graceful-fs/graceful-fs-tests.ts
  types/node/async_hooks.d.ts
  types/node/child_process.d.ts
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/index.d.ts
  types/node/os.d.ts
  types/node/process.d.ts
  types/node/test/fs.ts
  types/node/test/os.ts
  types/node/test/process.ts
  types/node/test/readline.ts
  types/node/test/timers_promises.ts
  types/node/test/util_types.ts
  types/node/ts3.6/base.d.ts
  types/node/util.d.ts
  types/node/util/types.d.ts
Labels: Critical package, Edits multiple packages, Self Merge

#54284 jasmine: add config interfaces
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Critical package, Self Merge

#53652 [bitcore-lib-cash] add sighash and BN types
  types/bitcore-lib-cash/bitcore-lib-cash-tests.ts
  types/bitcore-lib-cash/index.d.ts
Labels: Self Merge

#54304 [react-plotly.js] added missing onBeforeHover event to interface
  types/react-plotly.js/index.d.ts
  types/react-plotly.js/react-plotly.js-tests.tsx
Labels: Edits Owners, Owner Approved, Self Merge

#54276 Added type definitions for vite-plugin-react-svg
  types/vite-plugin-react-svg/index.d.ts
  types/vite-plugin-react-svg/package.json
  types/vite-plugin-react-svg/tsconfig.json
  types/vite-plugin-react-svg/tslint.json
  types/vite-plugin-react-svg/vite-plugin-react-svg-tests.ts
Labels: New Definition, Self Merge

#54368 @types/cors: Allow booleans in static origin array
  types/cors/cors-tests.ts
  types/cors/index.d.ts
Labels: Critical package, Owner Approved, Self Merge

#54072 [socketcluster-server] Add AGAction
  types/ag-channel/index.d.ts
  types/ag-simple-broker/index.d.ts
  types/async-stream-emitter/index.d.ts
  types/consumable-stream/index.d.ts
  types/eetase/index.d.ts
  types/sc-broker-cluster/index.d.ts
  types/sc-channel/index.d.ts
  types/scc-broker-client/index.d.ts
  types/socketcluster-client/index.d.ts
  types/socketcluster-server/action.d.ts
  types/socketcluster-server/index.d.ts
  types/socketcluster-server/server.d.ts
  types/socketcluster-server/serversocket.d.ts
  types/socketcluster-server/socketcluster-server-tests.ts
  types/stream-demux/index.d.ts
  types/writable-consumable-stream/index.d.ts
Labels: Author is Owner, Edits multiple packages, No Other Owners, Self Merge

#54377 @types/tizen-tv-webapis: fix typings getCurrentStreamInfo and getTotalTrackInfo
  types/tizen-tv-webapis/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#53939 [detox] update type for negating not call
  types/detox/index.d.ts
  types/detox/test/detox-global-tests.ts
  types/detox/test/detox-module-tests.ts
Labels: Self Merge

#54396 Sync frida-gum typings with Frida 15.0.0
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
Labels: Author is Owner, Owner Approved, Self Merge

#53753 Add gettext.js exported utility functions
  types/gettext.js/gettext.js-tests.ts
  types/gettext.js/index.d.ts
Labels: Self Merge

#54399 snowflake-sdk optional authentication types
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#54406 remove myself from maintainers
  types/react-datepicker/index.d.ts
Labels: Author is Owner, Edits Owners, Popular package, Untested Change

#54408 [lowercase-object-keys] Added definitions
  types/lowercase-object-keys/index.d.ts
  types/lowercase-object-keys/lowercase-object-keys-tests.ts
  types/lowercase-object-keys/tsconfig.json
  types/lowercase-object-keys/tslint.json
Labels: New Definition

#54204 fix(maplibre-gl): typings are now included in maplibre-gl
  notNeededPackages.json
  types/maplibre-gl/index.d.ts
  types/maplibre-gl/maplibre-gl-tests.ts
  types/maplibre-gl/tsconfig.json
  types/maplibre-gl/tslint.json
Labels: Edits Infrastructure, Self Merge

#54318 [react-big-calendar] Add new Calendar prop, doShowMoreDrillDown
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Owner Approved, Popular package, Self Merge

#54400 fix(node): fix execSync issues
  types/node/child_process.d.ts
  types/node/test/child_process.ts
  types/node/v15/child_process.d.ts
  types/node/v15/test/child_process.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Self Merge

#54411 [react-geosuggest]: Add missing placeDetailFields property
  types/react-geosuggest/index.d.ts
  types/react-geosuggest/react-geosuggest-tests.tsx
Labels: Owner Approved, Self Merge

#54398 Improve is-object types
  types/is-object/index.d.ts
  types/is-object/is-object-tests.ts
Labels: Edits Owners, Owner Approved, Self Merge

#54424 Add connect-memcached
  types/connect-memcached/connect-memcached-tests.ts
  types/connect-memcached/index.d.ts
  types/connect-memcached/tsconfig.json
  types/connect-memcached/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53602 [react-native]: Update AbortSignal
  types/react-native/globals.d.ts
  types/react-native/test/globals.tsx
Labels: Owner Approved, Popular package, Self Merge

#54430 twemoji: update to return string or HTMLElement dependent on `parse()` param type
  types/twemoji/index.d.ts
  types/twemoji/test/twemoji-tests.common-js.ts
  types/twemoji/test/twemoji-tests.global.ts
Labels: Edits Owners, Maintainer Approved, Self Merge
