Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-02, with the labels that each got.

#50678 [@types/tpdirect] Fix wrong typing in get prime result when using token pay
  types/tpdirect/google-pay.d.ts
  types/tpdirect/payment-request-api.d.ts
  types/tpdirect/samsung-pay.d.ts
  types/tpdirect/tpdirect-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50942 Updated typings for npm package 'pdf-viewer-reactjs' version 2.2.2
  types/pdf-viewer-reactjs/index.d.ts
  types/pdf-viewer-reactjs/pdf-viewer-reactjs-tests.tsx
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50400 Backbone fixes
  types/backbone-relational/index.d.ts
  types/backbone/backbone-tests.ts
  types/backbone/index.d.ts
  types/backbone/tsconfig.json
Labels: Check Config, Edits multiple packages, Owner Approved, Perf: Same, Popular package, Self Merge

#50562 React-Calendar: Add missing value property to ViewCallbackProperties interface
  types/react-calendar/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#50952 [pino-http] Add new res parameter to reqCustomProps
  types/pino-http/index.d.ts
  types/pino-http/pino-http-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50914 @mapbox/mapbox-sdk: matrix api annotations should be an array and source destinations can be "all"
  types/mapbox__mapbox-sdk/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#50962 Backbone: apply prettier
  types/backbone/backbone-tests.ts
  types/backbone/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#50954 fix(next-auth): jwt.decode option should return object
  types/next-auth/index.d.ts
  types/next-auth/next-auth-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#49841 Add react-native-sha1 typescript type
  types/react-native-sha1/index.d.ts
  types/react-native-sha1/react-native-sha1-tests.ts
  types/react-native-sha1/tsconfig.json
  types/react-native-sha1/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50933 [express-prometheus-middleware] Add types
  types/express-prometheus-middleware/express-prometheus-middleware-tests.ts
  types/express-prometheus-middleware/index.d.ts
  types/express-prometheus-middleware/tsconfig.json
  types/express-prometheus-middleware/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50943 added new devexpress-web major version 202.5
  types/devexpress-web/index.d.ts
  types/devexpress-web/v201/devexpress-web-tests.ts
  types/devexpress-web/v201/index.d.ts
  types/devexpress-web/v201/tsconfig.json
  types/devexpress-web/v201/tslint.json
Labels: Check Config, Edits Owners, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#50965 Backbone: enable some linters
  types/backbone/backbone-tests.ts
  types/backbone/index.d.ts
  types/backbone/tslint.json
Labels: Author is Owner, Owner Approved, Popular package, Self Merge

#50958 [json5] Remove typings
  notNeededPackages.json
  types/json5/index.d.ts
  types/json5/json5-tests.ts
  types/json5/tsconfig.json
  types/json5/tslint.json
Labels: Critical package, Edits Infrastructure, Maintainer Approved, Owner Approved, Self Merge

#50926 [hellosign-sdk] type definitions
  types/hellosign-sdk/hellosign-sdk-tests.ts
  types/hellosign-sdk/index.d.ts
  types/hellosign-sdk/tsconfig.json
  types/hellosign-sdk/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50776 update graphql version to ^15.4.0
  types/keystonejs__keystone/package.json
Labels: Owner Approved, Perf: Same, Self Merge

#49830 upgrade reactour type from v1.17 to v1.18
  types/reactour/index.d.ts
  types/reactour/reactour-tests.tsx
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge, Unmerged

#50902 auth0: add _id for signup result
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#50963 [forge-viewer] update for version 7.35
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#50419 [smtp-server] Added optional property user to SMTPServerSession type
  types/smtp-server/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#50534 Update Connection to Datastore and provide addition context
  types/waterline/index.d.ts
  types/waterline/waterline-tests.ts
Labels: Author is Owner, Other Approved, Perf: Same, Self Merge

#50974 smartystreets-javascript-sdk - bugfix components is an object of but only one exists per candidate and fix return type for US Street/Zip
  types/smartystreets-javascript-sdk/index.d.ts
  types/smartystreets-javascript-sdk/smartystreets-javascript-sdk-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50981 [pulsar-client] Added missing log function to ClientOpts
  types/pulsar-client/index.d.ts
  types/pulsar-client/pulsar-client-tests.ts
Labels: Owner Approved, Self Merge

#50800 chore: add stopPropagation to @pollyjs/core interceptor interface
  types/pollyjs__core/index.d.ts
  types/pollyjs__core/pollyjs__core-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50946 Add upnp-mediarenderer-client definition
  types/upnp-mediarenderer-client/index.d.ts
  types/upnp-mediarenderer-client/tsconfig.json
  types/upnp-mediarenderer-client/tslint.json
  types/upnp-mediarenderer-client/upnp-mediarenderer-client-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#50864 [@types/react-form] Update types for 4.0 version
  types/react-form/index.d.ts
  types/react-form/react-form-tests.tsx
  types/react-form/v2/index.d.ts
  types/react-form/v2/react-form-tests.tsx
  types/react-form/v2/tsconfig.json
  types/react-form/v2/tslint.json
Labels: Check Config, Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#50941 [react-select] removing myself as owner
  types/react-select/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50605 feat(passport-jwt): Type `secretOrKeyProvider` property of `StrategyOptions`
  types/passport-jwt/index.d.ts
  types/passport-jwt/passport-jwt-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#50735 Fix server-side request forgery vulnerability (NPM advisory 1594)
  types/moxios/package.json
Labels: Other Approved, Perf: Same, Self Merge

#50405 feat(react): Remove type safety from returned ReactElement of JSXElementConstructor
  types/react/index.d.ts
  types/react/v16/index.d.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#50969 Microsoft Graph- version 1.29
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#50964 [@mapbox/mapbox-gl-geocoder] Add types
  types/mapbox__mapbox-gl-geocoder/index.d.ts
  types/mapbox__mapbox-gl-geocoder/mapbox__mapbox-gl-geocoder-tests.ts
  types/mapbox__mapbox-gl-geocoder/tsconfig.json
  types/mapbox__mapbox-gl-geocoder/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Other Approved, Self Merge

#50984 [react-native] Specify valid keys in Animated.ValueXY#getTranslateTransform signature
  types/react-native/index.d.ts
  types/react-native/test/animated.tsx
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51008 smartystreets-javascript-sdk - allow for batch execution of US street and zipcode lookups
  types/smartystreets-javascript-sdk/index.d.ts
  types/smartystreets-javascript-sdk/smartystreets-javascript-sdk-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50976 [matrix-js-sdk] add various types & clarify some old ones
  types/matrix-js-sdk/index.d.ts
  types/matrix-js-sdk/matrix-js-sdk-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50990 (fix)[w3c-web-serial] Add missing getInfo and SerialPortInfo
  types/w3c-web-serial/index.d.ts
  types/w3c-web-serial/w3c-web-serial-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50968 Backbone fixes
  types/backbone.layoutmanager/index.d.ts
  types/backbone.marionette/index.d.ts
  types/backbone/backbone-tests.ts
  types/backbone/index.d.ts
  types/backgrid/index.d.ts
  types/giraffe/index.d.ts
Labels: Edits multiple packages, Maintainer Approved, Owner Approved, Perf: Worse, Popular package, Self Merge

#50793 updated to accept options object and not only a boolean
  types/gulp-csso/gulp-csso-tests.ts
  types/gulp-csso/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51012 [express-sitemap-xml] Update to 3.0
  types/express-sitemap-xml/express-sitemap-xml-tests.ts
  types/express-sitemap-xml/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51019 [hellosign-sdk]: Fix up times and add missing methods
  types/hellosign-sdk/hellosign-sdk-tests.ts
  types/hellosign-sdk/index.d.ts
Labels: Owner Approved, Self Merge

#50552 codemirror: setBookmark().find() returns a Pos, not a range
  types/codemirror/index.d.ts
  types/codemirror/test/index.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#50721 [node] mkdir with recursive: true can have undefined result
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/test/fs.ts
  types/node/v13/fs.d.ts
  types/node/v13/test/fs.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#50852 tls: Fix tls.Server constructor and TlsOptions
  types/node/net.d.ts
  types/node/test/tls.ts
  types/node/tls.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#50669 [react-autosuggest] add containerProps property introduced in version 10.1.0
  types/react-autosuggest/index.d.ts
  types/react-autosuggest/react-autosuggest-tests.tsx
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge

#50353 [@types/puppeteer] add return type 'ElementHandle' to page.evaluateHandle
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#50993 [avocat] add initial types
  types/avocat/avocat-tests.ts
  types/avocat/index.d.ts
  types/avocat/package.json
  types/avocat/tsconfig.json
  types/avocat/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51000 [@hapipal/avocat] add initial types
  types/hapipal__avocat/hapipal__avocat-tests.ts
  types/hapipal__avocat/index.d.ts
  types/hapipal__avocat/package.json
  types/hapipal__avocat/tsconfig.json
  types/hapipal__avocat/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#51007 [@hapipal/toys] add initial types
  types/hapipal__toys/hapipal__toys-tests.ts
  types/hapipal__toys/index.d.ts
  types/hapipal__toys/package.json
  types/hapipal__toys/tsconfig.json
  types/hapipal__toys/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50997 [@hapipal/schmervice] add initial types
  types/hapipal__schmervice/hapipal__schmervice-tests.ts
  types/hapipal__schmervice/index.d.ts
  types/hapipal__schmervice/test/organization_service.ts
  types/hapipal__schmervice/test/user_service.ts
  types/hapipal__schmervice/tsconfig.json
  types/hapipal__schmervice/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#51004 Remove myself as an owner from @types/newman
  types/newman/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Other Approved, Perf: Same, Self Merge, Untested Change

#50988 [nunjucks] Fix incorrect loader extend type in type definition
  types/nunjucks/index.d.ts
  types/nunjucks/nunjucks-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51006 [@types/react-native] remove franzmoro from contributors list
  types/react-native/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51015 [libsodium-wrappers-sumo]: Update to 0.7.9
  types/libsodium-wrappers-sumo/index.d.ts
  types/libsodium-wrappers-sumo/libsodium-wrappers-sumo-tests.ts
  types/libsodium-wrappers/index.d.ts
Labels: Author is Owner, Edits multiple packages, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#51011 [cacache] Update to 15.0
  types/cacache/cacache-tests.ts
  types/cacache/en.d.ts
  types/cacache/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Popular package, Self Merge

#50953 chore: rax sync react types
  types/rax/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, No Other Owners, Other Approved, Self Merge, Untested Change

#51016 [morgan-json] add new definition
  types/morgan-json/index.d.ts
  types/morgan-json/morgan-json-tests.ts
  types/morgan-json/tsconfig.json
  types/morgan-json/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#51021 @types/vue-select: Update vue-select to v3.11
  types/vue-select/index.d.ts
  types/vue-select/vue-select-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#51028 Added nanoid-dictionary/alphanumeric
  types/nanoid-dictionary/alphanumeric.d.ts
  types/nanoid-dictionary/index.d.ts
  types/nanoid-dictionary/nanoid-dictionary-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51029 feat(react-modal): Add overlayElement, contentElement, and preventScroll
  types/react-modal/index.d.ts
  types/react-modal/react-modal-tests.tsx
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50825 [mongodb] Add missing directConnection to MongoClientOptions interface
  types/mongodb/index.d.ts
  types/mongodb/test/index.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51003 mongodb: fix typings related to projection
  types/mongodb/index.d.ts
  types/mongodb/test/collection/findX.ts
  types/mongodb/test/cursor.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#50334 [line-reader] Fix typings
  types/line-reader/index.d.ts
  types/line-reader/line-reader-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50944 [cls-hooked]: more specific types
  types/cls-hooked/cls-hooked-tests.ts
  types/cls-hooked/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51031 [sharedb] Support backend.on('submitRequestEnd')
  types/sharedb/index.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51045 VS Code 1.53.0 Extension API
  types/vscode/index.d.ts
Labels: Perf: Same, Untested Change

#50945 [@hapi/jwt] type definitions
  types/hapi__jwt/hapi__jwt-tests.ts
  types/hapi__jwt/index.d.ts
  types/hapi__jwt/package.json
  types/hapi__jwt/tsconfig.json
  types/hapi__jwt/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51022 update(karma): v6 updates
  types/karma/index.d.ts
  types/karma/karma-tests.ts
  types/karma/package.json
  types/karma/v1/index.d.ts
  types/karma/v1/karma-tests.ts
  types/karma/v1/tsconfig.json
  types/karma/v1/tslint.json
  types/karma/v3/index.d.ts
  types/karma/v3/karma-tests.ts
  types/karma/v3/package.json
  types/karma/v3/tsconfig.json
  types/karma/v3/tslint.json
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#50935 [@types/jwplayer]: Add warning event
  types/jwplayer/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#50936 @types/newman : added envVar
  types/newman/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge, Untested Change

#51054 [pngjs] Update to 6.0
  types/pngjs/index.d.ts
  types/pngjs/pngjs-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#51048 [react-autosuggest]Remove (my) contributor line
  types/react-autosuggest/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50940 [react-reconciler] Update to v0.26
  types/react-reconciler/index.d.ts
  types/react-reconciler/test/ReactFiberHostConfigWithNoHydration.ts
  types/react-reconciler/test/ReactFiberHostConfigWithNoPersistence.ts
  types/react-reconciler/test/ReactFiberHostConfigWithNoTestSelectors.ts
  types/react-reconciler/test/ReactTestHostConfig.ts
  types/react-reconciler/test/ReactTestRendererScheduling.ts
  types/react-reconciler/test/ReactTypes.ts
  types/react-reconciler/test/react-reconciler-tests.ts
  types/react-reconciler/tsconfig.json
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#50991 Allowed class refs in @loadable/component
  types/loadable__component/index.d.ts
  types/loadable__component/loadable__component-tests.tsx
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50992 Created types for Openpay SDK functions
  types/openpay/index.d.ts
  types/openpay/openpay-tests.ts
  types/openpay/tsconfig.json
  types/openpay/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#51044 Revert "🤖 Merge PR #50944 [cls-hooked]: more specific types by @axiac"
  types/cls-hooked/cls-hooked-tests.ts
  types/cls-hooked/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51013 [hawk] Add types for hawk
  types/hawk/OTHER_FILES.txt
  types/hawk/hawk-tests.ts
  types/hawk/index.d.ts
  types/hawk/lib/browser.d.ts
  types/hawk/lib/client.d.ts
  types/hawk/lib/crypto.d.ts
  types/hawk/lib/server.d.ts
  types/hawk/lib/utils.d.ts
  types/hawk/package.json
  types/hawk/tsconfig.json
  types/hawk/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#51041 [qrcode] Add Buffer and Uint8ClampedArray support to QRCodeSegment
  types/qrcode/index.d.ts
  types/qrcode/qrcode-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51059 mongodb: fix overloading with generic find options
  types/mongodb/index.d.ts
  types/mongodb/test/collection/findX.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#51051 [google.script.client-size] Made public endpoints more easily customizable
  types/google.script.client-side/README.md
  types/google.script.client-side/google.script.client-side-tests.ts
  types/google.script.client-side/index.d.ts
Labels: Perf: Same, The CI failed

#51039 Type declarations for use-prefers-color-scheme
  types/use-prefers-color-scheme/index.d.ts
  types/use-prefers-color-scheme/tsconfig.json
  types/use-prefers-color-scheme/tslint.json
  types/use-prefers-color-scheme/use-prefers-color-scheme-tests.ts
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#51072 update(sire-parser): version 8.4
  types/siren-parser/Field.d.ts
  types/siren-parser/index.d.ts
  types/siren-parser/siren-parser-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51055 [prettier] Update to 2.2
  types/prettier/index.d.ts
  types/prettier/parser-espree.d.ts
  types/prettier/parser-meriyah.d.ts
  types/prettier/prettier-tests.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#51057 feat: add types for redux-logic-test
  types/redux-logic-test/index.d.ts
  types/redux-logic-test/package.json
  types/redux-logic-test/redux-logic-test-tests.ts
  types/redux-logic-test/tsconfig.json
  types/redux-logic-test/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51076 Added Types for node-livereload (livereload server implementation)
  types/livereload/index.d.ts
  types/livereload/livereload-tests.ts
  types/livereload/tsconfig.json
  types/livereload/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#51079 enzyme: update tests for TS 4.3
  types/enzyme/enzyme-tests.tsx
Labels: Popular package

#51068 Backbone: replace all Function types
  types/backbone/backbone-tests.ts
  types/backbone/index.d.ts
  types/backbone/tslint.json
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#51049 add types for search-index by @TravisYeah
  types/search-index/index.d.ts
  types/search-index/search-index-tests.ts
  types/search-index/tsconfig.json
  types/search-index/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51052 upgrade carbon__pictograms-react to version 11.3.0
  types/carbon__pictograms-react/OTHER_FILES.txt
  types/carbon__pictograms-react/carbon__pictograms-react-tests.tsx
  types/carbon__pictograms-react/es/art--tools--01/index.d.ts
  types/carbon__pictograms-react/es/bluepages/index.d.ts
  types/carbon__pictograms-react/es/content--design/index.d.ts
  types/carbon__pictograms-react/es/design--leadership/index.d.ts
  types/carbon__pictograms-react/es/design--research/index.d.ts
  types/carbon__pictograms-react/es/do-not--02/index.d.ts
  types/carbon__pictograms-react/es/emergency--exit/index.d.ts
  types/carbon__pictograms-react/es/eyewash--station/index.d.ts
  types/carbon__pictograms-react/es/index.d.ts
  types/carbon__pictograms-react/es/mail--verse/index.d.ts
  types/carbon__pictograms-react/es/microphone/index.d.ts
  types/carbon__pictograms-react/es/no--smoking/index.d.ts
  types/carbon__pictograms-react/es/organization/index.d.ts
  types/carbon__pictograms-react/es/overview/index.d.ts
  types/carbon__pictograms-react/es/professional--marketplace/index.d.ts
  types/carbon__pictograms-react/es/rotate--device/index.d.ts
  types/carbon__pictograms-react/es/sales--connect/index.d.ts
  types/carbon__pictograms-react/es/sprout/index.d.ts
  types/carbon__pictograms-react/es/stairs--down/index.d.ts
  types/carbon__pictograms-react/es/stairs--up/index.d.ts
  types/carbon__pictograms-react/es/stairs/index.d.ts
  types/carbon__pictograms-react/es/tablet--device--check/index.d.ts
  types/carbon__pictograms-react/es/tablet--device/index.d.ts
  types/carbon__pictograms-react/es/user--experience-design/index.d.ts
  types/carbon__pictograms-react/es/visual--design/index.d.ts
  types/carbon__pictograms-react/es/workday/index.d.ts
  types/carbon__pictograms-react/index.d.ts
  types/carbon__pictograms-react/lib/art--tools--01/index.d.ts
  types/carbon__pictograms-react/lib/bluepages/index.d.ts
  types/carbon__pictograms-react/lib/content--design/index.d.ts
  types/carbon__pictograms-react/lib/design--leadership/index.d.ts
  types/carbon__pictograms-react/lib/design--research/index.d.ts
  types/carbon__pictograms-react/lib/do-not--02/index.d.ts
  types/carbon__pictograms-react/lib/emergency--exit/index.d.ts
  types/carbon__pictograms-react/lib/eyewash--station/index.d.ts
  types/carbon__pictograms-react/lib/index.d.ts
  types/carbon__pictograms-react/lib/mail--verse/index.d.ts
  types/carbon__pictograms-react/lib/microphone/index.d.ts
  types/carbon__pictograms-react/lib/no--smoking/index.d.ts
  types/carbon__pictograms-react/lib/organization/index.d.ts
  types/carbon__pictograms-react/lib/overview/index.d.ts
  types/carbon__pictograms-react/lib/professional--marketplace/index.d.ts
  types/carbon__pictograms-react/lib/rotate--device/index.d.ts
  types/carbon__pictograms-react/lib/sales--connect/index.d.ts
  types/carbon__pictograms-react/lib/sprout/index.d.ts
  types/carbon__pictograms-react/lib/stairs--down/index.d.ts
  types/carbon__pictograms-react/lib/stairs--up/index.d.ts
  types/carbon__pictograms-react/lib/stairs/index.d.ts
  types/carbon__pictograms-react/lib/tablet--device--check/index.d.ts
  types/carbon__pictograms-react/lib/tablet--device/index.d.ts
  types/carbon__pictograms-react/lib/user--experience-design/index.d.ts
  types/carbon__pictograms-react/lib/visual--design/index.d.ts
  types/carbon__pictograms-react/lib/workday/index.d.ts
Labels: Author is Owner, Check Config, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#51074 Type declarations for use-color-scheme
  types/use-color-scheme/index.d.ts
  types/use-color-scheme/tsconfig.json
  types/use-color-scheme/tslint.json
  types/use-color-scheme/use-color-scheme-tests.ts
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#51065 [react-select] Add missing autoComplete prop for Input component
  types/react-select/src/components/Input.d.ts
  types/react-select/test/examples/CustomInput.tsx
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51036 Update addMatchImageSnapshotCommand() options
  types/cypress-image-snapshot/cypress-image-snapshot-tests.ts
  types/cypress-image-snapshot/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51066 Add type definitions to @rebass/layout
  types/rebass__layout/index.d.ts
  types/rebass__layout/rebass__layout-tests.tsx
  types/rebass__layout/tsconfig.json
  types/rebass__layout/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#51086 add types for generated json report
  types/webpack-bundle-analyzer/index.d.ts
  types/webpack-bundle-analyzer/webpack-bundle-analyzer-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge

#51095 update(uglify-js): v3.12 bump
  types/uglify-js/index.d.ts
  types/uglify-js/uglify-js-tests.ts
Labels: Author is Owner, Critical package, Perf: Same

#50934 [url-match-patterns] Add types for url-match-patterns
  types/url-match-patterns/index.d.ts
  types/url-match-patterns/tsconfig.json
  types/url-match-patterns/tslint.json
  types/url-match-patterns/url-match-patterns-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#50702 Update simpl-schema SimpleSchema objectKeys definition to specify parameter `keyPrefix` as optional
  types/simpl-schema/index.d.ts
  types/simpl-schema/simpl-schema-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50680 fix(passport): done callback arguments
  types/passport/index.d.ts
  types/passport/passport-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#51098 Quill - added isEnabled type method
  types/quill/index.d.ts
  types/quill/quill-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge

#51092 [ramda] adds more control to lensIndex
  types/ramda/index.d.ts
  types/ramda/test/lensIndex-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50819 [react-slider] Changed `export =` to `export default`
  types/react-slider/index.d.ts
  types/react-slider/react-slider-tests.tsx
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51110 md5: add Uint8Array to possible md5() argument types
  types/md5/index.d.ts
  types/md5/md5-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50843 [@types/unl-core]: Update bounds type for unl-core 3.x.x
  types/unl-core/index.d.ts
  types/unl-core/unl-core-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#51090 [google.visualization] Update TimelineOptions
  types/google.visualization/google.visualization-tests.ts
  types/google.visualization/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51122 [three] – update WebXR definitions
  types/three/src/renderers/webxr/WebXR.d.ts
  types/three/src/renderers/webxr/WebXRManager.d.ts
  types/three/test/renderers/webxr/webxr-vr-cube.ts
  types/three/tsconfig.json
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51035 Type definitions for weaveid
  types/weaveid/index.d.ts
  types/weaveid/package.json
  types/weaveid/tsconfig.json
  types/weaveid/tslint.json
  types/weaveid/weaveid-tests.ts
Labels: Check Config, Maintainer Approved, New Definition, Other Approved, Self Merge

#51050 Changes to workgrid-toolbar types
  types/workgrid-toolbar/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge, Untested Change

#51087 update(koa-helmet): missing owner handle
  types/koa-helmet/index.d.ts
Labels: Edits Owners, Maintainer Approved, Other Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50581 [Remarkable] Add linkify plugin and update dependency
  types/remarkable/lib/linkify.d.ts
  types/remarkable/linkify/index.d.ts
  types/remarkable/remarkable-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#51082 add types for wordfilter
  types/wordfilter/index.d.ts
  types/wordfilter/tsconfig.json
  types/wordfilter/tslint.json
  types/wordfilter/wordfilter-tests.ts
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51127 [recordrtc] Update return type for getState function
  types/recordrtc/index.d.ts
  types/recordrtc/recordrtc-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51123 Update and fix vue-select types
  types/vue-select/index.d.ts
  types/vue-select/vue-select-tests.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Self Merge

#51117 Smartystreets javascript sdk - add support for "us reverse geo" and documentation
  types/smartystreets-javascript-sdk/index.d.ts
  types/smartystreets-javascript-sdk/smartystreets-javascript-sdk-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50629 add express-oauth-server specific options
  types/express-oauth-server/express-oauth-server-tests.ts
  types/express-oauth-server/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51118 [w3c-web-hid] Add w3c webhid type definitions
  types/w3c-web-hid/index.d.ts
  types/w3c-web-hid/tsconfig.json
  types/w3c-web-hid/tslint.json
  types/w3c-web-hid/w3c-web-hid-tests.ts
Labels: Maintainer Approved, New Definition, Perf: Same, Self Merge

#51093 [gapi.auth2] fixing result types for GoogleUser methods
  types/gapi.auth2/gapi.auth2-tests.ts
  types/gapi.auth2/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51125 [auth0] Add revokeRefreshToken method
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50845 [video.js] Add userActions to ComponentOptions
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51069 [ramda] improve concat | dissoc | groupBy | toLower | toUpper | toPairs | toPairsIn
  types/ramda/index.d.ts
  types/ramda/test/concat-tests.ts
  types/ramda/test/dissoc-tests.ts
  types/ramda/test/toLower-tests.ts
  types/ramda/test/toPairs-tests.ts
  types/ramda/test/toPairsIn-tests.ts
  types/ramda/test/toUpper-tests.ts
  types/ramda/tsconfig.json
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge

#50516 [bell] Remove types
  types/bell/bell-tests.ts
  types/bell/index.d.ts
  types/bell/tsconfig.json
  types/bell/tslint.json
Labels: Owner Approved, Self Merge, Unmerged

#50711 [circular-json] Remove types
  types/circular-json/circular-json-tests.ts
  types/circular-json/index.d.ts
  types/circular-json/tsconfig.json
  types/circular-json/tslint.json
Labels: Owner Approved, Popular package, Self Merge, Unmerged

#50910 @types/cytoscape: Fix the type of roots in the BreadthFirstLayoutOptions
  types/cytoscape/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#51097 c-struct typings
  types/c-struct/c-struct-tests.ts
  types/c-struct/index.d.ts
  types/c-struct/tsconfig.json
  types/c-struct/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50650 [catbox-memory] Remove types
  types/catbox-memory/catbox-memory-tests.ts
  types/catbox-memory/index.d.ts
  types/catbox-memory/tsconfig.json
  types/catbox-memory/tslint.json
Labels: Owner Approved, Self Merge, Unmerged

#51152 Remove missed package.json from bell
  types/bell/package.json
Labels: New Definition

#50771 Add/Upgrade task container types on node onfleet types
  types/onfleet__node-onfleet/Resources/Tasks.d.ts
  types/onfleet__node-onfleet/onfleet__node-onfleet-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51113 [sorted-array-functions] Add types
  types/sorted-array-functions/index.d.ts
  types/sorted-array-functions/sorted-array-functions-tests.ts
  types/sorted-array-functions/tsconfig.json
  types/sorted-array-functions/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50975 fix: add current property to semaphore.Sempahore
  types/semaphore/index.d.ts
  types/semaphore/semaphore-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#50728 feat (data-api-client) add transactionId for the query() function
  types/data-api-client/data-api-client-tests.ts
  types/data-api-client/index.d.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#51138 @types/googlemaps: Add 'className' to MarkerLabel interface
  types/googlemaps/reference/marker.d.ts
  types/googlemaps/test/reference/marker-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50781 chai: notEqual and notStrictEqual docstrings
  types/chai/index.d.ts
Labels: Critical package, Owner Approved, Perf: Worse, Self Merge, Untested Change

#51161 [calendar] Fix @types/calendar typings
  types/calendar/calendar-tests.ts
  types/calendar/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51136 [video.js] Add types which allow for items to be turned off in the controlBar
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51154 chore: rename google-maps-web to google.maps
  types/google.maps/google.maps-tests.ts
  types/google.maps/index.d.ts
  types/google.maps/tsconfig.json
  types/google.maps/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Other Approved, Self Merge

#50918 Add types for reactjs-localstorage
  types/reactjs-localstorage/index.d.ts
  types/reactjs-localstorage/reactjs-localstorage-tests.ts
  types/reactjs-localstorage/tsconfig.json
  types/reactjs-localstorage/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51162 [Swiper] More accurate event callbacks
  types/swiper/index.d.ts
  types/swiper/swiper-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50741 [react-native-calendar-picker] Add missing types in declaration (up to date with 7.0.8 and docs)
  types/react-native-calendar-picker/index.d.ts
  types/react-native-calendar-picker/react-native-calendar-picker-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge, Unmerged

#51180 fix(aws-lambda): connect contact flow queue type
  types/aws-lambda/test/connect-contact-flow-tests.ts
  types/aws-lambda/trigger/connect-contact-flow.d.ts
Labels: Owner Approved, Popular package, Self Merge

#51176 Add public methods to react-bootstrap-typeahead.
  types/react-bootstrap-typeahead/index.d.ts
  types/react-bootstrap-typeahead/react-bootstrap-typeahead-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge

#51073 mongodb: fix findOne<T> options to be optional again
  types/mongodb/index.d.ts
  types/mongodb/test/collection/findX.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51020 google-apps-script: Added moveTo function to Folder interface
  types/google-apps-script/google-apps-script.drive.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#51109 [node] Make `eventType` more strict in `fs.watch` listener
  types/node/fs.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#51126 [react-native-svg-charts] update ProgressCircleProps
  types/react-native-svg-charts/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#51129 [cheerio] Add comment element type
  types/cheerio/cheerio-tests.ts
  types/cheerio/index.d.ts
Labels: Critical package, Maintainer Approved, Other Approved, Owner Approved, Perf: Same, Self Merge

#51131 fs-extra catch map error in TS
  types/fs-extra/fs-extra-tests.ts
  types/fs-extra/index.d.ts
  types/graceful-fs/index.d.ts
  types/hexo-fs/index.d.ts
  types/watchpack/index.d.ts
Labels: Critical package, Edits multiple packages, Maintainer Approved, Perf: Same, Self Merge

#51137 [@types/chrome] Add Action API from Chrome 88 / Manifest v3
  types/chrome/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51142 [mapbox-gl] fix Layer type definition
  types/mapbox-gl/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51158 [ioredis] fix xread command typing
  types/ioredis/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50549 meteor: add accounts-server token method typings
  types/meteor/accounts-base.d.ts
  types/meteor/globals/accounts-base.d.ts
  types/meteor/test/globals/meteor-tests.ts
  types/meteor/test/meteor-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51151 koa: add types for parsed query and headers
  types/koa/index.d.ts
Labels: Critical package, Edits Owners, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#51145 chore: expose private attr of player
  types/spotify-web-playback-sdk/index.d.ts
  types/spotify-web-playback-sdk/spotify-web-playback-sdk-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51194 ♻️(video.js) fix Middleware.setSource signature
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge
