Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-11, with the labels that each got.

#56899 [nodegit] add the missing getRemoteNames decleration
  types/nodegit/nodegit-tests.ts
  types/nodegit/repository.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#56861 fix: replaced setRedirectTo with setReturnTo in connect-ensure-login package
  types/connect-ensure-login/connect-ensure-login-tests.ts
  types/connect-ensure-login/index.d.ts
Labels: Self Merge, Maintainer Approved

#56666 [react-aria-modal] Improved onEnter and onExit types
  types/react-aria-modal/index.d.ts
  types/react-aria-modal/react-aria-modal-tests.tsx
Labels: Self Merge, Author is Owner, Owner Approved

#56391 `circular-dependency-plugin`: upgrade webpack types to v5
  types/circular-dependency-plugin/circular-dependency-plugin-tests.ts
  types/circular-dependency-plugin/index.d.ts
  types/circular-dependency-plugin/package.json
  types/circular-dependency-plugin/tsconfig.json
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#56884 aws-lambda: Add AWS CDK custom resource Provider Framework typings
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/cdk-custom-resource-tests.ts
  types/aws-lambda/trigger/cdk-custom-resource.d.ts
  types/aws-lambda/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#56799 @types/qlik-visualizationextensions: add listbox to VisualizationType
  types/qlik-visualizationextensions/index.d.ts
  types/qlik-visualizationextensions/qlik-visualizationextensions-tests.ts
Labels: Self Merge, Owner Approved

#56709 Add types for appium-adb
  types/appium-adb/appium-adb-tests.ts
  types/appium-adb/index.d.ts
  types/appium-adb/lib/adb.d.ts
  types/appium-adb/lib/helpers.d.ts
  types/appium-adb/lib/logcat.d.ts
  types/appium-adb/lib/tools/adb-commands.d.ts
  types/appium-adb/lib/tools/adb-emu-commands.d.ts
  types/appium-adb/lib/tools/android-manifest.d.ts
  types/appium-adb/lib/tools/apk-signing.d.ts
  types/appium-adb/lib/tools/apk-utils.d.ts
  types/appium-adb/lib/tools/apks-utils.d.ts
  types/appium-adb/lib/tools/index.d.ts
  types/appium-adb/lib/tools/keyboard-commands.d.ts
  types/appium-adb/lib/tools/lockmgmt.d.ts
  types/appium-adb/lib/tools/settings-client-commands.d.ts
  types/appium-adb/lib/tools/system-calls.d.ts
  types/appium-adb/tsconfig.json
  types/appium-adb/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56888 [Bookshelf] load method relations param type
  types/bookshelf/bookshelf-tests.ts
  types/bookshelf/index.d.ts
Labels: Self Merge, Owner Approved

#56889 [Bookshelf] add fetchPage method
  types/bookshelf/bookshelf-tests.ts
  types/bookshelf/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#56907 update @rdfjs/fetch(-lite) to 3.0 (ESM-only)
  types/rdfjs__fetch-lite/index.d.ts
  types/rdfjs__fetch-lite/package.json
  types/rdfjs__fetch-lite/rdfjs__fetch-lite-tests.ts
  types/rdfjs__fetch/index.d.ts
  types/rdfjs__fetch/package.json
  types/rdfjs__fetch/rdfjs__fetch-tests.ts
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, No Other Owners

#56855 [prosemirror-state] Mark undocumented Transaction constructor as private
  types/prosemirror-state/index.d.ts
  types/prosemirror-state/prosemirror-state-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#56892 feat: Add types for fill-range
  types/fill-range/fill-range-tests.ts
  types/fill-range/index.d.ts
  types/fill-range/tsconfig.json
  types/fill-range/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56893 feat: Add types for to-regex-range
  types/to-regex-range/index.d.ts
  types/to-regex-range/to-regex-range-tests.ts
  types/to-regex-range/tsconfig.json
  types/to-regex-range/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56533 [@types/carbon-components-react] Update types to match 7.46.0
  types/carbon-components-react/index.d.ts
  types/carbon-components-react/lib/components/Checkbox/Checkbox.d.ts
  types/carbon-components-react/lib/components/DataTable/TableExpandHeader.d.ts
  types/carbon-components-react/lib/components/Modal/Modal.d.ts
  types/carbon-components-react/lib/components/MultiSelect/MultiSelect.d.ts
  types/carbon-components-react/lib/components/Search/Search.d.ts
  types/carbon-components-react/lib/components/Tag/Tag.d.ts
  types/carbon-components-react/lib/components/Tooltip/Tooltip.d.ts
Labels: Unmerged, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#56911 [use-sync-external-store] Update for alpha
  types/use-sync-external-store/shim/index.d.ts
  types/use-sync-external-store/shim/withSelector.d.ts
  types/use-sync-external-store/use-sync-external-store-tests.ts
  types/use-sync-external-store/withSelector.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#56906 [forge-viewer] update for version 7.55
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
  types/forge-viewer/three/three.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#56922 [use-sync-external-store] entrypoint withSelector -> with-selector
  types/use-sync-external-store/shim/with-selector.d.ts
  types/use-sync-external-store/shim/withSelector.d.ts
  types/use-sync-external-store/use-sync-external-store-tests.ts
  types/use-sync-external-store/with-selector.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#56173 [redux-first-router] precise `RouteThunk`, `Bag`, `kind`, `notFoundPath` & `Query`
  types/redux-first-router/index.d.ts
  types/redux-first-router/redux-first-router-tests.ts
Labels: Self Merge, Maintainer Approved

#56806 feat: add type definitions for canvas-size
  types/canvas-size/canvas-size-tests.ts
  types/canvas-size/index.d.ts
  types/canvas-size/tsconfig.json
  types/canvas-size/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56865 [sharp] Add support for sharp 0.29.2
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#56866 Update onfleet.d.ts, add missing optional arguments
  types/onfleet__node-onfleet/onfleet.d.ts
  types/onfleet__node-onfleet/onfleet__node-onfleet-tests.ts
Labels: Self Merge, Owner Approved

#56208 CSON only exports a Singleton instance
  types/cson/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#56913 react-imgix: modify definition owners by adding an imgix sdk team member
  types/react-imgix/index.d.ts
Labels: Author is Owner, Owner Approved, Untested Change, Edits Owners

#56819 [react-native]: Fix typo (`canimprove` -> `can improve`)
  types/react-native/index.d.ts
Labels: Owner Approved, Critical package, Untested Change

#56938 @types/elasticsearch: fix share -> shard typo
  types/elasticsearch/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#56783 Added 'search' input reference to vue-select
  types/vue-select/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#56853 Added `workflow` to docusign-esign types
  types/docusign-esign/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#56792 Add non-private "connecting" property to ldapjs Client class
  types/ldapjs/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#56846 [pkijs] Make recipientCertificate optional in EnvelopedData.decrypt()
  types/pkijs/index.d.ts
Labels: Self Merge, Untested Change

#56945 [ioredis] Add SMISMEMBER command type
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#56923 Googletag: accept more arguments to cmd.push
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
  types/googletag/ts3.9/googletag-tests.ts
  types/googletag/ts3.9/index.d.ts
Labels: Self Merge, Owner Approved

#56898 [jasmine] Make Jasmine constructor arguments optional
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Other Approved, Self Merge, Owner Approved, Critical package

#56836 [echarts] Add types to data-zoom.d.ts
  types/echarts/options/data-zoom.d.ts
Labels: Popular package, Self Merge, Untested Change

#56818 Correct the error type definition of koa-json-error
  types/koa-json-error/index.d.ts
Labels: Self Merge, Untested Change

#56845 [pkijs] Add addRecipientByCertificate() to EnvelopedData
  types/pkijs/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#56822 [ElasticLunr] Add bool property to SearchConfig<T>
  types/elasticlunr/index.d.ts
Labels: Self Merge, Untested Change

#56949 [ref-struct-di] fixed array syntax typings
  types/ref-struct-di/index.d.ts
  types/ref-struct-di/ref-struct-di-tests.ts
  types/ref-struct-di/ts4.1/index.d.ts
  types/ref-struct-di/ts4.1/ref-struct-di-tests.ts
Labels: Self Merge, Owner Approved

#56852 [react-dom] `hydrateRoot` accepts initial children
  types/react-dom/next.d.ts
  types/react-dom/test/next-tests.tsx
Labels: Self Merge, Author is Owner, Critical package

#56844 [react] Document type limitations of Suspense#fallback in React 18
  types/react/index.d.ts
  types/react/test/next.tsx
Labels: Self Merge, Author is Owner, Owner Approved, Critical package

#56939 [forge-viewer] updated StreamLine
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#56927 Serverless: add stackTags type to Service
  types/serverless/classes/Service.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#56519 [braintree-web]: Add PayPalCheckout to the loadPayPalSDK Promise return type
  types/braintree-web/modules/paypal-checkout.d.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Self Merge, Owner Approved

#56654 [tailwindcss] make TailwindConfig type usable in tailwind.config.js
  types/tailwindcss/tailwind-config-default.d.ts
  types/tailwindcss/tailwind-config.d.ts
  types/tailwindcss/test/tailwindcss-default-config-code-tests.ts
  types/tailwindcss/test/tailwindcss-default-config-value-tests.ts
  types/tailwindcss/test/tailwindcss-tests.ts
  types/tailwindcss/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Huge Change

#56798 [@types/ioredis] - wrong signature for xautoclaim
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#56812 braintree-web: Add missing property in PayPalCheckoutCreatePaymentOpt…
  types/braintree-web/modules/paypal-checkout.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#56920 [use-sync-external-store] Add Mark Erikson to owners
  types/use-sync-external-store/index.d.ts
Labels: Other Approved, Author is Owner, Untested Change, No Other Owners, Edits Owners

#56733 fix(passport-google-oauth20): Profile._json definition
  types/passport-google-oauth20/index.d.ts
  types/passport-google-oauth20/passport-google-oauth20-tests.ts
  types/passport-google-oauth20/tsconfig.json
Labels: Other Approved, Self Merge, Check Config

#56505 [react-addons-transition-group] Use React v15 typings following peerDependencies
  types/react-addons-transition-group/react-addons-transition-group-tests.ts
  types/react-addons-transition-group/tsconfig.json
  types/react/test/index.ts
  types/react/v15/test/index.ts
  types/react/v16/test/index.ts
Labels: Self Merge, Edits multiple packages, Critical package

#56914 [chillout] Add types
  types/chillout/chillout-tests.ts
  types/chillout/index.d.ts
  types/chillout/tsconfig.json
  types/chillout/tslint.json
Labels: New Definition, Self Merge

#56502 elliptic: Improve typings for ec.Signature
  types/elliptic/elliptic-tests.ts
  types/elliptic/index.d.ts
Labels: Popular package, Self Merge

#56492 [power-assert] update asserts based on feedback from @twada
  types/power-assert/index.d.ts
  types/power-assert/power-assert-tests.ts
Labels: Self Merge, Edits Owners

#56886 feat: implement type definitions for lzbase62 package
  types/lzbase62/index.d.ts
  types/lzbase62/lzbase62-tests.ts
  types/lzbase62/tsconfig.json
  types/lzbase62/tslint.json
Labels: New Definition, Self Merge

#56867 Add types for `sales-tax` package
  types/sales-tax/index.d.ts
  types/sales-tax/sales-tax-tests.ts
  types/sales-tax/tsconfig.json
  types/sales-tax/tslint.json
Labels: New Definition, Self Merge

#56879 Add ntqdm
  types/ntqdm/index.d.ts
  types/ntqdm/ntqdm-tests.ts
  types/ntqdm/tsconfig.json
  types/ntqdm/tslint.json
Labels: New Definition, Self Merge

#56489 [dateformat] Update to v5
  types/dateformat/dateformat-tests.ts
  types/dateformat/index.d.ts
Labels: Popular package, Self Merge, Author is Owner

#56885 [lambda-rate-limiter] Add types
  types/lambda-rate-limiter/index.d.ts
  types/lambda-rate-limiter/lambda-rate-limiter-tests.ts
  types/lambda-rate-limiter/tsconfig.json
  types/lambda-rate-limiter/tslint.json
Labels: New Definition, Self Merge

#56509 Gtag: Allow string as third parameter in 'set' command
  types/gtag.js/gtag.js-tests.ts
  types/gtag.js/index.d.ts
Labels: Popular package, Self Merge

#56948 chore(googletag): update the code comment
  types/googletag/index.d.ts
  types/googletag/ts3.9/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Untested Change, No Other Owners

#56891 feat: Add types for esm-utils
  types/esm-utils/esm-utils-tests.ts
  types/esm-utils/index.d.ts
  types/esm-utils/package.json
  types/esm-utils/tsconfig.json
  types/esm-utils/tslint.json
Labels: New Definition, Self Merge

#56882 [@types/apidoc] Add `dryRun` option and fix output type
  types/apidoc/apidoc-tests.ts
  types/apidoc/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#56931 In trtc-js-sdk, removed Client.setDefaultMuteRemoteStreams(), added ClientConfig.autoSubscribe flag
  types/trtc-js-sdk/index.d.ts
  types/trtc-js-sdk/trtc-js-sdk-tests.ts
Labels: Self Merge, Owner Approved

#56493 [@types/google-libphonenumber] add getNationalSignificantNumber to PhoneNumberUtil
  types/google-libphonenumber/google-libphonenumber-tests.ts
  types/google-libphonenumber/index.d.ts
Labels: Popular package, Self Merge

#56457 [@types/fluent-ffmpeg] Fix return for PresetFunction. Fix typos. Closes #52550
  types/fluent-ffmpeg/fluent-ffmpeg-tests.ts
  types/fluent-ffmpeg/index.d.ts
Labels: Self Merge

#56966 [openui5] Update the definition files for OpenUI5 1.96
  types/openui5/index.d.ts
  types/openui5/openui5-tests.ts
  types/openui5/sap.f.d.ts
  types/openui5/sap.m.d.ts
  types/openui5/sap.ui.core.d.ts
  types/openui5/sap.ui.fl.d.ts
  types/openui5/sap.ui.integration.d.ts
  types/openui5/sap.ui.layout.d.ts
  types/openui5/sap.ui.mdc.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#56971 fix(koa__router): mark `name` property in layers as nullable
  types/koa__router/index.d.ts
  types/koa__router/koa__router-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#56973 [chec__commerce.js] Add attributes types to product
  types/chec__commerce.js/index.d.ts
  types/chec__commerce.js/test/products.ts
  types/chec__commerce.js/types/product-attribute-option.ts
  types/chec__commerce.js/types/product-attribute.d.ts
  types/chec__commerce.js/types/product.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#56878 Add markdown-escape
  types/markdown-escape/index.d.ts
  types/markdown-escape/markdown-escape-tests.ts
  types/markdown-escape/tsconfig.json
  types/markdown-escape/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56975 VS Code 1.62.0 Extension API
  types/vscode/index.d.ts
Labels: Other Approved, Popular package, Untested Change

#56956 Add typescript definitions for ceddl-polyfill
  types/ceddl__ceddl-polyfill/ceddl__ceddl-polyfill-tests.ts
  types/ceddl__ceddl-polyfill/index.d.ts
  types/ceddl__ceddl-polyfill/tsconfig.json
  types/ceddl__ceddl-polyfill/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56985 React-vis: Add all properties to DiscreteColorLegendProps
  types/react-vis/index.d.ts
  types/react-vis/react-vis-tests.tsx
Labels: Self Merge, Owner Approved

#56982 react-router-hash-link: Fix `ref` type
  types/react-router-hash-link/index.d.ts
  types/react-router-hash-link/react-router-hash-link-tests.tsx
Labels: Self Merge, Owner Approved

#56960 [tailwindcss] add function color type, and plugin type
  types/tailwindcss/index.d.ts
  types/tailwindcss/plugin.d.ts
  types/tailwindcss/tailwind-config.d.ts
  types/tailwindcss/test/tailwindcss-plugin-tests.ts
  types/tailwindcss/test/tailwindcss-tests.ts
  types/tailwindcss/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#56987 package(coingecko-api) fetch history support
  types/coingecko-api/coingecko-api-tests.ts
  types/coingecko-api/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#56644 node-telegram-bot-api: Added missing MessageEntityTypes for Telegram API
  types/node-telegram-bot-api/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#56988 [Bootbox] Added missing default properties
  types/bootbox/bootbox-tests.ts
  types/bootbox/index.d.ts
Labels: Self Merge, Owner Approved

#56766 Update Request to include rawBody property
  types/restify/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#56904 feat: add types for event-source-polyfill
  types/event-source-polyfill/event-source-polyfill-tests.ts
  types/event-source-polyfill/index.d.ts
  types/event-source-polyfill/tsconfig.json
  types/event-source-polyfill/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56575 [koa-generic-session] Update definitions for version 2
  types/koa-generic-session/index.d.ts
  types/koa-generic-session/koa-generic-session-tests.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#56976 react-router-hash-link: Support active nav styling
  types/react-router-hash-link/index.d.ts
  types/react-router-hash-link/react-router-hash-link-tests.tsx
Labels: Self Merge, Owner Approved

#56978 [office-runtime] (Outlook) Mailbox 1.10 supports Storage
  types/office-runtime/index.d.ts
Labels: Other Approved, Untested Change

#56730 fix(echarts): Legend width and height support string type
  types/echarts/options/legend.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#56817 [@types/google-apps-scrcipt] add types for IconImage
  types/google-apps-script/google-apps-script.card-service.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#57014 remove simple-icons
  notNeededPackages.json
  types/simple-icons/index.d.ts
  types/simple-icons/simple-icons-tests.ts
  types/simple-icons/tsconfig.json
  types/simple-icons/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#56979 Remove @trimblemaps/trimblemaps-js
  notNeededPackages.json
  types/trimblemaps__trimblemaps-js/index.d.ts
  types/trimblemaps__trimblemaps-js/trimblemaps__trimblemaps-js-tests.ts
  types/trimblemaps__trimblemaps-js/tsconfig.json
  types/trimblemaps__trimblemaps-js/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#57000 feat: implement types for `system-sleep` package
  types/system-sleep/index.d.ts
  types/system-sleep/system-sleep-tests.ts
  types/system-sleep/tsconfig.json
  types/system-sleep/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#57010 feat(unzalgo): add support for v3.0
  types/unzalgo/index.d.ts
  types/unzalgo/unzalgo-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#56808 [ola] adding new definition
  types/ola/index.d.ts
  types/ola/ola-tests.ts
  types/ola/tsconfig.json
  types/ola/tslint.json
Labels: Unmerged, New Definition, Self Merge, Maintainer Approved

#57011 Add Typings for `getSprint` and `genericAgileGet` to jira-client
  types/jira-client/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#57024 New reset method added of Jmxuer
  types/jmuxer/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#56983 [mailparser] Add support for MailParser options
  types/mailparser/index.d.ts
  types/mailparser/mailparser-tests.ts
  types/mailparser/package.json
Labels: Self Merge, Maintainer Approved

#57006 Add types for packages in Metro 0.66
  types/metro-babel-transformer/index.d.ts
  types/metro-babel-transformer/metro-babel-transformer-tests.ts
  types/metro-babel-transformer/tsconfig.json
  types/metro-babel-transformer/tslint.json
  types/metro-cache/index.d.ts
  types/metro-cache/metro-cache-tests.ts
  types/metro-cache/test/types-tests.ts
  types/metro-cache/tsconfig.json
  types/metro-cache/tslint.json
  types/metro-cache/types.d.ts
  types/metro-config/configTypes.d.ts
  types/metro-config/index.d.ts
  types/metro-config/loadConfig.d.ts
  types/metro-config/metro-config-tests.ts
  types/metro-config/test/configTypes-tests.ts
  types/metro-config/test/loadConfig-tests.ts
  types/metro-config/tsconfig.json
  types/metro-config/tslint.json
  types/metro-core/Terminal.d.ts
  types/metro-core/index.d.ts
  types/metro-core/metro-core-tests.ts
  types/metro-core/test/Terminal-tests.ts
  types/metro-core/tsconfig.json
  types/metro-core/tslint.json
  types/metro-resolver/index.d.ts
  types/metro-resolver/metro-resolver-tests.ts
  types/metro-resolver/test/types-tests.ts
  types/metro-resolver/tsconfig.json
  types/metro-resolver/tslint.json
  types/metro-resolver/types.d.ts
  types/metro-source-map/index.d.ts
  types/metro-source-map/metro-source-map-tests.ts
  types/metro-source-map/tsconfig.json
  types/metro-source-map/tslint.json
  types/metro-transform-worker/index.d.ts
  types/metro-transform-worker/metro-transform-worker-tests.ts
  types/metro-transform-worker/tsconfig.json
  types/metro-transform-worker/tslint.json
  types/metro/Asset.d.ts
  types/metro/DeltaBundler/types.d.ts
  types/metro/ModuleGraph/types.d.ts
  types/metro/ModuleGraph/worker/collectDependencies.d.ts
  types/metro/Server.d.ts
  types/metro/index.d.ts
  types/metro/lib/reporting.d.ts
  types/metro/metro-tests.ts
  types/metro/shared/types.d.ts
  types/metro/src/Server.d.ts
  types/metro/src/lib/TerminalReporter.d.ts
  types/metro/src/shared/output/bundle.d.ts
  types/metro/test/Asset-tests.ts
  types/metro/test/DeltaBundler/types-tests.ts
  types/metro/test/ModuleGraph/types-tests.ts
  types/metro/test/lib/reporting-tests.ts
  types/metro/test/shared/types-tests.ts
  types/metro/test/src/Server-tests.ts
  types/metro/test/src/lib/TerminalReporter-tests.ts
  types/metro/test/src/shared/output/bundle-tests.ts
  types/metro/tsconfig.json
  types/metro/tslint.json
Labels: Other Approved, New Definition, Self Merge, Edits multiple packages, Maintainer Approved

#56903 feat(babel-plugin-react-docgen): add types
  types/babel-plugin-react-docgen/babel-plugin-react-docgen-tests.ts
  types/babel-plugin-react-docgen/index.d.ts
  types/babel-plugin-react-docgen/tsconfig.json
  types/babel-plugin-react-docgen/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#56762 [cadesplugin] Added new types
  types/cadesplugin/cadescom.d.ts
  types/cadesplugin/cadescom_async.d.ts
  types/cadesplugin/cadesplugin-tests.ts
  types/cadesplugin/cadesplugin.d.ts
  types/cadesplugin/capicom.d.ts
  types/cadesplugin/capicom_async.d.ts
  types/cadesplugin/capicom_enums.d.ts
  types/cadesplugin/common.d.ts
  types/cadesplugin/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57020 create @types/which-polygon
  types/which-polygon/index.d.ts
  types/which-polygon/tsconfig.json
  types/which-polygon/tslint.json
  types/which-polygon/which-polygon-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#56254 [mjml-react] Add Explicit types for children
  types/mjml-react/index.d.ts
  types/mjml-react/mjml-react-tests.tsx
Labels: Self Merge, Owner Approved

#57001 [luxon] add singular units for duration object
  types/luxon/src/duration.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Popular package, Self Merge, Maintainer Approved

#56815 Add onComment method to ParseOptions in css-tree
  types/css-tree/css-tree-tests.ts
  types/css-tree/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#56513 [accept-language-parser] allow undefined to be passed on parse
  types/accept-language-parser/accept-language-parser-tests.ts
  types/accept-language-parser/index.d.ts
Labels: Popular package, Self Merge

#56676 Update dom-webcodecs to latest spec
  types/dom-mediacapture-transform/dom-mediacapture-transform-tests.ts
  types/dom-mediacapture-transform/index.d.ts
  types/dom-webcodecs/index.d.ts
  types/dom-webcodecs/test/animated-gif-renderer.ts
  types/dom-webcodecs/test/dom-webcodecs-tests.ts
  types/dom-webcodecs/tsconfig.json
  types/dom-webcodecs/webcodecs.generated.d.ts
Labels: Self Merge, Owner Approved, Edits multiple packages

#57019 [steamapi] Export all types, add overloads and more
  types/steamapi/index.d.ts
  types/steamapi/steamapi-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57029 [coingecko-api] Add Coins Fetch funcion types
  types/coingecko-api/coingecko-api-tests.ts
  types/coingecko-api/index.d.ts
Labels: Self Merge, Owner Approved

#57048 [@types/react-native]: Added missing values for TextInputAndroid.autoComplete
  types/react-native/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Untested Change

#56964 Update maintainer
  types/power-assert/index.d.ts
Labels: Untested Change, Edits Owners

#56664 Update @ckeditor/ckeditor5-engine to v31
  types/ckeditor__ckeditor5-engine/OTHER_FILES.txt
  types/ckeditor__ckeditor5-engine/ckeditor__ckeditor5-engine-tests.ts
  types/ckeditor__ckeditor5-engine/index.d.ts
  types/ckeditor__ckeditor5-engine/src/controller/datacontroller.d.ts
  types/ckeditor__ckeditor5-engine/src/conversion/upcasthelpers.d.ts
  types/ckeditor__ckeditor5-engine/src/dataprocessor/htmldataprocessor.d.ts
  types/ckeditor__ckeditor5-engine/src/dataprocessor/xmldataprocessor.d.ts
  types/ckeditor__ckeditor5-engine/src/model/element.d.ts
  types/ckeditor__ckeditor5-engine/src/model/markercollection.d.ts
  types/ckeditor__ckeditor5-engine/src/model/nodelist.d.ts
  types/ckeditor__ckeditor5-engine/src/model/text.d.ts
  types/ckeditor__ckeditor5-engine/src/model/textproxy.d.ts
  types/ckeditor__ckeditor5-engine/src/model/writer.d.ts
  types/ckeditor__ckeditor5-engine/src/view/document.d.ts
  types/ckeditor__ckeditor5-engine/src/view/domconverter.d.ts
  types/ckeditor__ckeditor5-engine/src/view/element.d.ts
  types/ckeditor__ckeditor5-engine/src/view/filler.d.ts
  types/ckeditor__ckeditor5-engine/src/view/matcher.d.ts
  types/ckeditor__ckeditor5-engine/src/view/observer/domeventobserver.d.ts
  types/ckeditor__ckeditor5-engine/src/view/observer/keyobserver.d.ts
  types/ckeditor__ckeditor5-engine/src/view/rawelement.d.ts
  types/ckeditor__ckeditor5-engine/src/view/renderer.d.ts
  types/ckeditor__ckeditor5-engine/src/view/stylesmap.d.ts
  types/ckeditor__ckeditor5-engine/src/view/text.d.ts
  types/ckeditor__ckeditor5-engine/src/view/textproxy.d.ts
  types/ckeditor__ckeditor5-engine/src/view/uielement.d.ts
Labels: Self Merge, Author is Owner, Check Config

#57022 [three] r134
  types/three/OTHER_FILES.txt
  types/three/examples/jsm/controls/ArcballControls.d.ts
  types/three/examples/jsm/controls/DeviceOrientationControls.d.ts
  types/three/examples/jsm/loaders/GLTFLoader.d.ts
  types/three/examples/jsm/misc/GPUComputationRenderer.d.ts
  types/three/examples/jsm/nodes/inputs/ColorNode.d.ts
  types/three/examples/jsm/nodes/materials/StandardNodeMaterial.d.ts
  types/three/examples/jsm/nodes/materials/nodes/StandardNode.d.ts
  types/three/examples/jsm/objects/MarchingCubes.d.ts
  types/three/examples/jsm/renderers/CSS2DRenderer.d.ts
  types/three/examples/jsm/renderers/CSS3DRenderer.d.ts
  types/three/index.d.ts
  types/three/src/Three.d.ts
  types/three/src/extras/objects/ImmediateRenderObject.d.ts
  types/three/src/lights/LightShadow.d.ts
  types/three/src/loaders/LoaderUtils.d.ts
  types/three/src/materials/MeshPhysicalMaterial.d.ts
  types/three/src/renderers/WebGLRenderer.d.ts
  types/three/src/renderers/webgl/WebGLRenderLists.d.ts
  types/three/src/textures/Texture.d.ts
  types/three/test/misc/misc-gpucomputationrender.ts
  types/three/test/utils/utils-webgl-marchingcubes.ts
  types/three/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Check Config

#56992 Type is optional in SearchShardsParams in elasticsearch package.
  types/elasticsearch/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#57003 add types for remote-git-tags
  types/remote-git-tags/index.d.ts
  types/remote-git-tags/remote-git-tags-tests.ts
  types/remote-git-tags/tsconfig.json
  types/remote-git-tags/tslint.json
Labels: New Definition, Self Merge

#57057 [chec/commerce.js] Fix bug where assets was incorrectly defined as an Asset, should be string[]
  types/chec__commerce.js/test/products.ts
  types/chec__commerce.js/types/product-variant-group.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#56998 feat: implement types for `deasync-promise` package
  types/deasync-promise/deasync-promise-tests.ts
  types/deasync-promise/index.d.ts
  types/deasync-promise/tsconfig.json
  types/deasync-promise/tslint.json
Labels: New Definition, Self Merge

#57058 Revert "Update maintainer"
  types/power-assert/index.d.ts
Labels: Untested Change, Edits Owners

#57053 feat(random-useragent): Add function overloads
  types/random-useragent/index.d.ts
  types/random-useragent/random-useragent-tests.ts
Labels: Self Merge, Owner Approved

#56379 Add types for `cldr`
  types/cldr/cldr-tests.ts
  types/cldr/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#56567 [node-ipc] Adding support for readableAll and writableAll config options
  types/node-ipc/index.d.ts
  types/node-ipc/node-ipc-tests.ts
Labels: Popular package, Self Merge

#57059 semantic-release: Add missing fields in NextRelease
  types/semantic-release/index.d.ts
  types/semantic-release/semantic-release-tests.ts
Labels: Self Merge, Owner Approved

#56595 @ckeditor/ckeditor5-alignment fixes
  types/ckeditor__ckeditor5-alignment/ckeditor__ckeditor5-alignment-tests.ts
  types/ckeditor__ckeditor5-alignment/src/alignment.d.ts
  types/ckeditor__ckeditor5-alignment/src/alignmentcommand.d.ts
  types/ckeditor__ckeditor5-alignment/src/alignmentediting.d.ts
  types/ckeditor__ckeditor5-alignment/src/alignmentui.d.ts
  types/ckeditor__ckeditor5-alignment/src/utils.d.ts
  types/ckeditor__ckeditor5-alignment/v27/ckeditor__ckeditor5-alignment-tests.ts
  types/ckeditor__ckeditor5-alignment/v27/index.d.ts
  types/ckeditor__ckeditor5-alignment/v27/src/alignment.d.ts
  types/ckeditor__ckeditor5-alignment/v27/src/alignmentcommand.d.ts
  types/ckeditor__ckeditor5-alignment/v27/src/alignmentediting.d.ts
  types/ckeditor__ckeditor5-alignment/v27/src/alignmentui.d.ts
  types/ckeditor__ckeditor5-alignment/v27/src/utils.d.ts
  types/ckeditor__ckeditor5-alignment/v27/tsconfig.json
  types/ckeditor__ckeditor5-alignment/v27/tslint.json
Labels: Self Merge, Author is Owner, No Other Owners

#56612 [css-font-loading-module] augment global FontFaceSet type rather than exporting
  types/css-font-loading-module/css-font-loading-module-tests.ts
  types/css-font-loading-module/index.d.ts
Labels: Popular package, Self Merge

#56807 [ramda] type guards implemented
  types/ramda/index.d.ts
  types/ramda/test/is-tests.ts
  types/ramda/test/propIs-tests.ts
  types/ramda/test/propSatisfies-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#56901 feat(uuid-browser): add types
  types/uuid-browser/index.d.ts
  types/uuid-browser/interfaces.d.ts
  types/uuid-browser/tsconfig.json
  types/uuid-browser/tslint.json
  types/uuid-browser/uuid-browser-tests.ts
  types/uuid-browser/v1.d.ts
  types/uuid-browser/v4.d.ts
  types/uuid-browser/v5.d.ts
Labels: New Definition, Self Merge

#56838 fix(node): fs.{Read,Write}Stream::close with callback
  types/node/fs.d.ts
  types/node/test/fs.ts
  types/node/v12/fs.d.ts
  types/node/v12/test/fs.ts
  types/node/v14/fs.d.ts
  types/node/v14/test/fs.ts
Labels: Self Merge, Owner Approved, Critical package

#56784 [multer-s3] import S3 client only
  types/multer-s3/index.d.ts
  types/multer-s3/multer-s3-tests.ts
Labels: Self Merge, Owner Approved

#56989 [jwplayer]: update addButton signature
  types/jwplayer/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#56674 Update package json for vulnerability in Axios
  types/moxios/package.json
Labels: Self Merge

#56703 [@types/express-serve-static-core] Fix express-serve-static-core locals type so it can be overwritten
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express-serve-static-core/ts4.0/express-serve-static-core-tests.ts
  types/express-serve-static-core/ts4.0/index.d.ts
Labels: Self Merge, Critical package

#57021 feat(leaflet.markercluster): add types for spiderfy and unspiderfy methods
  types/leaflet.markercluster/index.d.ts
  types/leaflet.markercluster/leaflet.markercluster-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57051 ceddl-polyfill adding missing root definition
  types/ceddl__ceddl-polyfill/ceddl__ceddl-polyfill-tests.ts
  types/ceddl__ceddl-polyfill/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#56986 update ui-grid index.d.ts, add missing property and function
  types/ui-grid/index.d.ts
  types/ui-grid/ui-grid-tests.ts
Labels: Self Merge, Owner Approved

#56629 [node-turn] Update options and fields
  types/node-turn/index.d.ts
  types/node-turn/node-turn-tests.ts
Labels: Self Merge, Author is Owner, No Other Owners

#57083 [ahoy.js] Update track methods to the latest version
  types/ahoy.js/index.d.ts
  types/ahoy.js/test/ahoy.js-tests.cjs.ts
  types/ahoy.js/test/ahoy.js-tests.esm.ts
Labels: Self Merge, Owner Approved

#57064 [@types/react-table] Add autoResetResize type
  types/react-table/index.d.ts
  types/react-table/react-table-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#56902 [module-deps] Allow persistentCache fallback to take null file data
  types/module-deps/index.d.ts
  types/module-deps/module-deps-tests.ts
Labels: Self Merge, Owner Approved

#57028 prune(yargs): remove sources for old versions
  types/yargs/v10/index.d.ts
  types/yargs/v10/tsconfig.json
  types/yargs/v10/tslint.json
  types/yargs/v10/yargs-tests.ts
  types/yargs/v11/index.d.ts
  types/yargs/v11/tsconfig.json
  types/yargs/v11/tslint.json
  types/yargs/v11/yargs-tests.ts
  types/yargs/v12/index.d.ts
  types/yargs/v12/tsconfig.json
  types/yargs/v12/tslint.json
  types/yargs/v12/yargs-tests.ts
  types/yargs/v12/yargs.d.ts
  types/yargs/v13/index.d.ts
  types/yargs/v13/tsconfig.json
  types/yargs/v13/tslint.json
  types/yargs/v13/yargs-tests.ts
  types/yargs/v13/yargs.d.ts
  types/yargs/v8/index.d.ts
  types/yargs/v8/tsconfig.json
  types/yargs/v8/tslint.json
  types/yargs/v8/yargs-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Huge Change

#57002 fix: remove ToolbarAndroid from react-native
  types/react-native-vector-icons/FontAwesome5.d.ts
  types/react-native-vector-icons/Icon.d.ts
  types/react-native-vector-icons/react-native-vector-icons-tests.tsx
  types/react-native/index.d.ts
  types/react-native/legacy-properties.d.ts
  types/react-native/v0.63/index.d.ts
  types/react-native/v0.63/legacy-properties.d.ts
  types/react-native/v0.64/index.d.ts
  types/react-native/v0.64/legacy-properties.d.ts
  types/react-native/v0.65/index.d.ts
  types/react-native/v0.65/legacy-properties.d.ts
  types/styled-components-react-native/index.d.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Critical package

#56961 Update sinonjs/fake-timers types to 8.1.0
  types/sinonjs__fake-timers/index.d.ts
  types/sinonjs__fake-timers/sinonjs__fake-timers-tests.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package, Edits Owners

#57099 autosuggest-highlight update to the 3.2.0 version (add the 'options' parameter for match function)
  types/autosuggest-highlight/autosuggest-highlight-tests.ts
  types/autosuggest-highlight/index.d.ts
  types/autosuggest-highlight/match/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#56569 [react-simple-maps] update `ZoomableGroupProps` interface
  types/react-simple-maps/index.d.ts
  types/react-simple-maps/react-simple-maps-tests.tsx
  types/react-simple-maps/tsconfig.json
Labels: Self Merge, Maintainer Approved

#57098 [ramda] Fix regression in #56807 with constructors with arguments
  types/ramda/index.d.ts
  types/ramda/test/is-tests.ts
  types/ramda/test/propIs-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#56449 [@types/fluent-ffmpeg] Update tags field to better reflect the format used by fluent-ffmpeg
  types/fluent-ffmpeg/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#56936 Microsoft Graph - Upgrade to 2.9
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#56924 [dynmap] Fix configuration types
  types/dynmap/dynmap-tests.ts
  types/dynmap/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#57040 add markdown-it-external-links typings
  types/markdown-it-external-links/index.d.ts
  types/markdown-it-external-links/markdown-it-external-links-tests.ts
  types/markdown-it-external-links/tsconfig.json
  types/markdown-it-external-links/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#57115 [gestalt] Update definitions to 40.0
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Self Merge, Owner Approved

#57085 [@wordpress/data-controls]: Update to version 2.2.6
  types/wordpress__data-controls/index.d.ts
  types/wordpress__data-controls/package.json
  types/wordpress__data-controls/wordpress__data-controls-tests.ts
Labels: Other Approved, Self Merge

#57108 Update Zendesk Chat Web SDK types
  types/zchat-browser/index.d.ts
  types/zchat-browser/zchat-browser-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57116 [README][types/fbt] Add documentation
  types/fbt/README.md
Labels: Self Merge, Author is Owner, Owner Approved

#57121 [react-native-onboarding-swiper] Add missing FlatList ref to class
  types/react-native-onboarding-swiper/index.d.ts
  types/react-native-onboarding-swiper/react-native-onboarding-swiper-tests.tsx
Labels: Self Merge, Owner Approved, Edits Owners

#56955 added horizontal props to react native svg charts - barchart
  types/react-native-svg-charts/index.d.ts
  types/react-native-svg-charts/react-native-svg-charts-tests.tsx
Labels: Self Merge, Owner Approved

#56912 [sharedb] Add types for Backend#projections and some Connection methods
  types/sharedb/index.d.ts
  types/sharedb/lib/client.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#53705 Update index.ts googlelibphonenumber (missing numbers)
  types/google-libphonenumber/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved, Untested Change

#57063 [ramda] filter and find typeguards implemented
  types/ramda/index.d.ts
  types/ramda/test/filter-tests.ts
  types/ramda/test/find-tests.ts
  types/ramda/test/findLast-tests.ts
  types/ramda/test/pipe-tests.ts
  types/ramda/test/reject-tests.ts
  types/ramda/tools.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Edits Owners

#57043 Add passport-orcid types
  types/passport-orcid/index.d.ts
  types/passport-orcid/passport-orcid-tests.ts
  types/passport-orcid/tsconfig.json
  types/passport-orcid/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved
