Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-05, with the labels that each got.

#52592 [parse] - Project cleanup and fix for Object.set/save
  types/parse/index.d.ts
  types/parse/node.d.ts
  types/parse/package.json
  types/parse/parse-tests.ts
  types/parse/react-native.d.ts
  types/parse/ts3.6/index.d.ts
  types/parse/ts3.6/node.d.ts
  types/parse/ts3.6/parse-tests.ts
  types/parse/ts3.6/react-native.d.ts
  types/parse/ts4.0/index.d.ts
  types/parse/ts4.0/node.d.ts
  types/parse/ts4.0/parse-tests.ts
  types/parse/ts4.0/react-native.d.ts
  types/parse/ts4.0/tsconfig.json
  types/parse/ts4.0/tslint.json
  types/parse/tslint.json
  types/parse/v1/index.d.ts
  types/parse/v1/parse-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52488 update(xo): v0.39 updates
  types/xo/index.d.ts
  types/xo/xo-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Better, Self Merge

#52606 update(markdown-it-emoji): improve shortcut list usage
  types/markdown-it-emoji/bare.d.ts
  types/markdown-it-emoji/index.d.ts
  types/markdown-it-emoji/light.d.ts
  types/markdown-it-emoji/test/markdown-it-emoji-cjs.ts
  types/markdown-it-emoji/test/markdown-it-emoji-global.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52703 [oidc-provider] 7.x adds missing property
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Owner Approved, Self Merge

#52512 update(asciichart): minor changes
  types/asciichart/asciichart-tests.ts
  types/asciichart/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52426 feat: definition for cypress-dotenv
  types/cypress-dotenv/cypress-dotenv-tests.ts
  types/cypress-dotenv/index.d.ts
  types/cypress-dotenv/package.json
  types/cypress-dotenv/tsconfig.json
  types/cypress-dotenv/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge, Unmerged

#52587 [prompts] Fix PromptObject.choices type
  types/prompts/index.d.ts
  types/prompts/prompts-tests.ts
Labels: Owner Approved, Perf: Worse, Popular package, Self Merge

#52491 [postcss-reporter] Update to postcss-reporter v7
  types/postcss-reporter/index.d.ts
  types/postcss-reporter/lib/formatter.d.ts
  types/postcss-reporter/package.json
  types/postcss-reporter/postcss-reporter-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52721 wavesurfer.js: update to 5.0
  types/wavesurfer.js/index.d.ts
  types/wavesurfer.js/src/plugin/playhead.d.ts
  types/wavesurfer.js/src/plugin/regions.d.ts
  types/wavesurfer.js/wavesurfer.js-tests.ts
Labels: Author is Owner, Other Approved, Perf: Same, Self Merge

#52683 Fix Typing For Vertices.mean - Returns single vector, instead of array<vector>
  types/matter-js/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#52693 [superagent] add new type definition & formatting
  types/superagent/index.d.ts
  types/superagent/superagent-tests.ts
  types/superagent/v2/index.d.ts
  types/superagent/v2/superagent-tests.ts
Labels: Critical package, Edits Owners, Owner Approved, Perf: Same

#52609 [@types/braintree] fixed type for subscription billingPeriod dates
  types/braintree/index.d.ts
Labels: Owner Approved, Perf: Worse, Untested Change

#52645 chore: update the onSnapToItem type
  types/react-native-snap-carousel/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#52729 Remove typings for just-clone, just-debounce-it, just-extend, just-map-values, just-merge, just-pick, just-safe-get, just-safe-set, just-snake-case, and just-throttle
  notNeededPackages.json
  types/just-clone/index.d.ts
  types/just-clone/just-clone-tests.ts
  types/just-clone/tsconfig.json
  types/just-clone/tslint.json
  types/just-debounce-it/index.d.ts
  types/just-debounce-it/just-debounce-it-tests.ts
  types/just-debounce-it/tsconfig.json
  types/just-debounce-it/tslint.json
  types/just-extend/index.d.ts
  types/just-extend/just-extend-tests.ts
  types/just-extend/tsconfig.json
  types/just-extend/tslint.json
  types/just-map-values/index.d.ts
  types/just-map-values/just-map-values-tests.ts
  types/just-map-values/tsconfig.json
  types/just-map-values/tslint.json
  types/just-merge/index.d.ts
  types/just-merge/just-merge-tests.ts
  types/just-merge/tsconfig.json
  types/just-merge/tslint.json
  types/just-pick/index.d.ts
  types/just-pick/just-pick-tests.ts
  types/just-pick/tsconfig.json
  types/just-pick/tslint.json
  types/just-safe-get/index.d.ts
  types/just-safe-get/just-safe-get-tests.ts
  types/just-safe-get/tsconfig.json
  types/just-safe-get/tslint.json
  types/just-safe-set/index.d.ts
  types/just-safe-set/just-safe-set-tests.ts
  types/just-safe-set/tsconfig.json
  types/just-safe-set/tslint.json
  types/just-snake-case/index.d.ts
  types/just-snake-case/just-snake-case-tests.ts
  types/just-snake-case/tsconfig.json
  types/just-snake-case/tslint.json
  types/just-throttle/index.d.ts
  types/just-throttle/just-throttle-tests.ts
  types/just-throttle/tsconfig.json
  types/just-throttle/tslint.json
Labels: Edits Infrastructure, Edits multiple packages, Owner Approved

#52538 [@types/chrome] Refactor chrome.window interface. Add onBoundsChanged event
  types/chrome/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Unreviewed, Untested Change

#52723 fix(css-mediaquery): missing prefers-color-scheme
  types/css-mediaquery/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#52522 [draft-js] add "move-block" to EditorChangeType.
  types/draft-js/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Unreviewed, Untested Change

#52520 [spotify-web-playback-sdk] rename Player class.
  types/spotify-web-playback-sdk/index.d.ts
Labels: Owner Approved, Perf: Same, Unreviewed, Untested Change

#52513 [dhtmlxgantt] Updated types for v7
  types/dhtmlxgantt/index.d.ts
Labels: Owner Approved, Perf: Same, Unreviewed, Untested Change

#52497 [@types/react-json-editor-ajrm] add Missing optional theme prop in JSONInputProperties
  types/react-json-editor-ajrm/index.d.ts
Labels: Owner Approved, Perf: Same, Unreviewed, Untested Change

#52707 update(base-64): version 1 update
  types/base-64/base-64-tests.ts
  types/base-64/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52665 [mathjs] remove null from exports
  types/mathjs/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Untested Change

#52623 [@types/gradient-parser] Add optional `length` type
  types/gradient-parser/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#52742 k6 - Updated docs links
  types/k6/crypto.d.ts
  types/k6/data.d.ts
  types/k6/encoding.d.ts
  types/k6/global.d.ts
  types/k6/html.d.ts
  types/k6/http.d.ts
  types/k6/index.d.ts
  types/k6/metrics.d.ts
  types/k6/net/grpc.d.ts
  types/k6/options.d.ts
  types/k6/ws.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#52507 fix: fix the serialize function definition and add types definition for init function, and ensureAuthenticated middleware
  types/forest-express-mongoose/forest-express-mongoose-tests.ts
  types/forest-express-mongoose/index.d.ts
  types/forest-express-sequelize/forest-express-sequelize-tests.ts
  types/forest-express-sequelize/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved, Perf: Worse, Unreviewed

#52356 update(split2): version bump to 3.2
  types/split2/index.d.ts
  types/split2/split2-tests.ts
  types/split2/tslint.json
Labels: Perf: Same, Unreviewed

#52744 vscode-notebook-renderer: update to separate preload type
  types/vscode-notebook-renderer/events.d.ts
  types/vscode-notebook-renderer/index.d.ts
  types/vscode-notebook-renderer/preload.d.ts
  types/vscode-notebook-renderer/vscode-notebook-renderer-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#52496 Add types for chai-datetime
  types/chai-datetime/chai-datetime-tests.ts
  types/chai-datetime/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52739 Add `cert`, `key`, and `pfx` options to webpack-livereload-plugin types
  types/webpack-livereload-plugin/index.d.ts
  types/webpack-livereload-plugin/webpack-livereload-plugin-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52691 add(winbox): new definition
  types/winbox/index.d.ts
  types/winbox/test/winbox-tests.global.ts
  types/winbox/test/winbox-tests.module.ts
  types/winbox/tsconfig.json
  types/winbox/tslint.json
Labels: New Definition

#52727 update(strip-final-newline): v3 update
  types/strip-final-newline/index.d.ts
  types/strip-final-newline/strip-final-newline-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Popular package

#52337 update(svg-parser): missing UMD support
  types/svg-parser/index.d.ts
  types/svg-parser/svg-parser-tests.ts
Labels: Edits Owners, Perf: Same, Popular package, Unreviewed

#52682 delete(rc-slider): remove definition
  notNeededPackages.json
  types/rc-slider/README.md
  types/rc-slider/index.d.ts
  types/rc-slider/rc-slider-tests.tsx
  types/rc-slider/tsconfig.json
  types/rc-slider/tslint.json
Labels: Edits Infrastructure, Owner Approved, Popular package

#52663 delete(mockdate): remove package
  notNeededPackages.json
  types/mockdate/index.d.ts
  types/mockdate/mockdate-tests.ts
  types/mockdate/tsconfig.json
  types/mockdate/tslint.json
Labels: Edits Infrastructure, Owner Approved, Popular package

#52735 [react] Fix link to React profiler API documentation
  types/react/index.d.ts
  types/react/v16/index.d.ts
Labels: Critical package, Owner Approved, Perf: Worse, Self Merge, Untested Change

#52692 add(svg-outline-stroke): new definition
  types/svg-outline-stroke/index.d.ts
  types/svg-outline-stroke/svg-outline-stroke-tests.ts
  types/svg-outline-stroke/tsconfig.json
  types/svg-outline-stroke/tslint.json
Labels: New Definition

#52196 update(json2csv): module changes
  types/json2csv/JSON2CSVAsyncParser.d.ts
  types/json2csv/JSON2CSVBase.d.ts
  types/json2csv/JSON2CSVParser.d.ts
  types/json2csv/JSON2CSVTransform.d.ts
  types/json2csv/index.d.ts
  types/json2csv/json2csv-tests.ts
  types/json2csv/transforms/base.d.ts
  types/json2csv/transforms/flatten.d.ts
  types/json2csv/transforms/index.d.ts
  types/json2csv/transforms/unwind.d.ts
  types/json2csv/tslint.json
Labels: Edits Owners, Perf: Same, Popular package, Unreviewed

#52158 update(metrostations): v5
  types/metrostations/index.d.ts
  types/metrostations/metrostations-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#52217 update(pdfobject): v2.2
  types/pdfobject/index.d.ts
  types/pdfobject/pdfobject-tests.ts
  types/pdfobject/tslint.json
Labels: Edits Owners, Perf: Same, Unreviewed

#52298 update(urban-dictionary): v3 updates
  types/urban-dictionary/index.d.ts
  types/urban-dictionary/urban-dictionary-tests.ts
Labels: Edits Owners, Perf: Same, Unreviewed

#52728 [unordered-array-remove] Add types
  types/unordered-array-remove/index.d.ts
  types/unordered-array-remove/test/unordered-array-remove-tests.ts
  types/unordered-array-remove/tsconfig.json
  types/unordered-array-remove/tslint.json
Labels: New Definition, Other Approved

#52747 [json-stringify-nice] Add types
  types/json-stringify-nice/index.d.ts
  types/json-stringify-nice/test/json-stringify-nice-tests.ts
  types/json-stringify-nice/tsconfig.json
  types/json-stringify-nice/tslint.json
Labels: New Definition, Other Approved

#52748 [common-ancestor-path] Add types
  types/common-ancestor-path/index.d.ts
  types/common-ancestor-path/test/common-ancestor-path-tests.ts
  types/common-ancestor-path/tsconfig.json
  types/common-ancestor-path/tslint.json
Labels: New Definition, Other Approved

#52551 Feature: remove theme-ui and theme-ui__components typings (no longer needed)
  notNeededPackages.json
  types/theme-ui/index.d.ts
  types/theme-ui/package.json
  types/theme-ui/theme-ui-tests.tsx
  types/theme-ui/tsconfig.json
  types/theme-ui/tslint.json
  types/theme-ui__components/index.d.ts
  types/theme-ui__components/package.json
  types/theme-ui__components/theme-ui__components-tests.tsx
  types/theme-ui__components/tsconfig.json
  types/theme-ui__components/tslint.json
Labels: Edits Infrastructure, Edits multiple packages, Owner Approved, Unreviewed

#52565 Bluebird: add asyncHooks parameter to Bluebird.config method
  types/bluebird/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge, Untested Change

#52237 [google-libphonenumber] fixed return type in PhoneNumberUtil
  types/google-libphonenumber/google-libphonenumber-tests.ts
  types/google-libphonenumber/index.d.ts
Labels: Other Approved, Perf: Same, Popular package, Unreviewed

#52001 jasmine: add a few new types
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Critical package, Owner Approved, Perf: Better, Self Merge

#52005 jasmine: update class
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/jasmine/tsconfig.json
Labels: Check Config, Critical package, Owner Approved, Perf: Better, Self Merge

#52558 feat: add envinfo type definitely
  types/envinfo/envinfo-tests.ts
  types/envinfo/index.d.ts
  types/envinfo/tsconfig.json
  types/envinfo/tslint.json
Labels: New Definition, Other Approved

#52660 buble: Fix transform options list, bump version
  types/buble/buble-tests.ts
  types/buble/index.d.ts
  types/rollup-plugin-buble/rollup-plugin-buble-tests.ts
Labels: Edits Owners, Edits multiple packages, Owner Approved, Perf: Same, Self Merge

#52472 add maptalks typings
  types/maptalks/index.d.ts
  types/maptalks/maptalks-tests.ts
  types/maptalks/tsconfig.json
  types/maptalks/tslint.json
Labels: New Definition, Other Approved

#52420 add scale_factor to osrm TableOptions
  types/osrm/index.d.ts
  types/osrm/osrm-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#52753 [powerapps-component-framework] Added LookupProperty and LookupValue interfaces
  types/powerapps-component-framework/componentframework.d.ts
  types/powerapps-component-framework/index.d.ts
  types/powerapps-component-framework/powerapps-component-framework-tests.ts
Labels: Owner Approved, Self Merge

#52255 restore options devtool
  types/webpack/v4/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge, Untested Change

#52737 wavesurfer.js: Add backend setPeaks definition
  types/wavesurfer.js/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#52712 fix(react-router): Fix bad path parameters type when params have constraints
  types/react-router/index.d.ts
  types/react-router/test/generatePath.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge

#52625 Added options to Accounts.user() and Meteor.user() (closes #52142).
  types/meteor/accounts-base.d.ts
  types/meteor/globals/accounts-base.d.ts
  types/meteor/globals/meteor.d.ts
  types/meteor/meteor.d.ts
  types/meteor/test/globals/meteor-tests.ts
  types/meteor/test/meteor-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52616 Fix mapbog-gl SymbolLayer style definition
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52553 allow boolean true to keep controlbar buttons
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Popular package, Self Merge

#52511 Cytoscape Stylesheet - text-rotation 'autorotate'
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52591 [ckeditor4] Re-add Ckeditor4 types
  notNeededPackages.json
  types/ckeditor4/ckeditor4-tests.ts
  types/ckeditor4/index.d.ts
  types/ckeditor4/tsconfig.json
  types/ckeditor4/tslint.json
Labels: Edits Infrastructure, New Definition, Other Approved

#52700 [thunky] Add types
  types/thunky/index.d.ts
  types/thunky/promise.d.ts
  types/thunky/test/thunky-tests.ts
  types/thunky/tsconfig.json
  types/thunky/tslint.json
Labels: New Definition, Other Approved

#52696 [xsalsa20] Add types
  types/xsalsa20/index.d.ts
  types/xsalsa20/test/xsalsa20-tests.ts
  types/xsalsa20/tsconfig.json
  types/xsalsa20/tslint.json
Labels: New Definition, Other Approved

#52694 [bogon] Add types
  types/bogon/index.d.ts
  types/bogon/test/bogon-tests.ts
  types/bogon/tsconfig.json
  types/bogon/tslint.json
Labels: New Definition, Other Approved

#52688 Create basic type definitions for swagger-ui
  types/swagger-ui/index.d.ts
  types/swagger-ui/swagger-ui-tests.ts
  types/swagger-ui/tsconfig.json
  types/swagger-ui/tslint.json
Labels: New Definition, Other Approved

#52771 VS Code 1.56.0 Extension API
  types/vscode/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#52583 feat: add node-zendesk attachment response types
  types/node-zendesk/index.d.ts
  types/node-zendesk/node-zendesk-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#52751 Added rn-material-ui-textfield package
  types/rn-material-ui-textfield/index.d.ts
  types/rn-material-ui-textfield/rn-material-ui-textfield-tests.tsx
  types/rn-material-ui-textfield/tsconfig.json
  types/rn-material-ui-textfield/tslint.json
Labels: Check Config, New Definition, Other Approved

#52431 update(integer): bump to 4.0 and minor fixes
  types/integer/index.d.ts
  types/integer/integer-tests.ts
Labels: Edits Owners, Perf: Better, Unreviewed

#52415 update(slice-ansi): v6 update
  types/slice-ansi/index.d.ts
  types/slice-ansi/slice-ansi-tests.ts
Labels: Author is Owner, Perf: Same, Popular package, Unreviewed

#52711 [multicast-dns] Add types
  types/multicast-dns/index.d.ts
  types/multicast-dns/test/multicast-dns-tests.ts
  types/multicast-dns/tsconfig.json
  types/multicast-dns/tslint.json
Labels: New Definition

#52634 Declaration files for JMuxer
  types/jmuxer/index.d.ts
  types/jmuxer/jmuxer-tests.ts
  types/jmuxer/tsconfig.json
  types/jmuxer/tslint.json
Labels: New Definition, Other Approved

#52657 New declaration for google-polyline
  types/google-polyline/google-polyline-tests.ts
  types/google-polyline/index.d.ts
  types/google-polyline/tsconfig.json
  types/google-polyline/tslint.json
Labels: New Definition

#52674 dom-webcodecs: Add types for the draft WebCodecs W3C spec
  types/dom-webcodecs/dom-webcodecs-tests.ts
  types/dom-webcodecs/index.d.ts
  types/dom-webcodecs/tsconfig.json
  types/dom-webcodecs/tslint.json
  types/dom-webcodecs/webcodecs.generated.d.ts
Labels: New Definition

#52743 Add Definitions for node-canvas-text
  types/node-canvas-text/index.d.ts
  types/node-canvas-text/node-canvas-text-tests.ts
  types/node-canvas-text/tsconfig.json
  types/node-canvas-text/tslint.json
Labels: New Definition

#52734 add(npm-dependants): new definition
  types/npm-dependants/index.d.ts
  types/npm-dependants/npm-dependants-tests.ts
  types/npm-dependants/tsconfig.json
  types/npm-dependants/tslint.json
Labels: New Definition

#51999 jasmine: update Env
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/jasminewd2/index.d.ts
  types/jasminewd2/jasminewd2-tests.ts
Labels: Critical package, Edits multiple packages, Owner Approved, Perf: Worse, Self Merge

#52561 Create type definitions for webos-service
  types/webos-service/activity-manager.d.ts
  types/webos-service/index.d.ts
  types/webos-service/message.d.ts
  types/webos-service/method.d.ts
  types/webos-service/service.d.ts
  types/webos-service/subscription.d.ts
  types/webos-service/tsconfig.json
  types/webos-service/tslint.json
  types/webos-service/webos-service-tests.ts
Labels: New Definition

#52628 new definition for @vertx/eventbus-bridge-client.js
  types/vertx__eventbus-bridge-client.js/index.d.ts
  types/vertx__eventbus-bridge-client.js/tsconfig.json
  types/vertx__eventbus-bridge-client.js/tslint.json
  types/vertx__eventbus-bridge-client.js/vertx__eventbus-bridge-client.js-tests.ts
Labels: New Definition

#52627 Add 1line-aa package definition
  types/1line-aa/1line-aa-tests.ts
  types/1line-aa/index.d.ts
  types/1line-aa/tsconfig.json
  types/1line-aa/tslint.json
Labels: New Definition

#52668 Add types for Typed.js
  types/typed.js/config.d.ts
  types/typed.js/htmlparser.d.ts
  types/typed.js/index.d.ts
  types/typed.js/initializer.d.ts
  types/typed.js/tsconfig.json
  types/typed.js/tslint.json
  types/typed.js/typed.js-tests.ts
Labels: New Definition

#52725 [forge-viewer] added missing types for Dasher
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
  types/forge-viewer/three/three.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52476 node-jose: extracted options interfaces
  types/node-jose/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Unmerged, Untested Change

#52785 [mini-css-extract-plugin] fix chunkFilename type to match output.chunkFilename
  types/mini-css-extract-plugin/index.d.ts
  types/mini-css-extract-plugin/mini-css-extract-plugin-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52791 Undeprecate @types/ckeditor
  notNeededPackages.json
Labels: Edits Infrastructure

#52715 Add types for broken-link-checker
  types/broken-link-checker/broken-link-checker-tests.ts
  types/broken-link-checker/index.d.ts
  types/broken-link-checker/tsconfig.json
  types/broken-link-checker/tslint.json
Labels: Check Config, New Definition

#52330 Sync with the latest version of react-router-hash-link
  types/react-router-hash-link/index.d.ts
  types/react-router-hash-link/react-router-hash-link-tests.tsx
Labels: Edits Owners, Perf: Worse, Unreviewed

#52422 Export Test and Tap classes in node-tap
  types/tap/index.d.ts
  types/tap/tap-tests.ts
Labels: Author is Owner, Perf: Same, Unreviewed

#52764 update tap definition owners
  types/tap/index.d.ts
Labels: Author is Owner, Edits Owners, Perf: Worse, Untested Change

#52384 [ibm_db] Add ODBCResult methods to enable access to column metadata
  types/ibm_db/ibm_db-tests.ts
  types/ibm_db/index.d.ts
Labels: Perf: Same, Unreviewed

#52787 [faker] Add missing `cityName` and fix `city` argument type in faker.address
  types/faker/faker-tests.ts
  types/faker/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge

#51523 Fix rrdir AsyncIterable + clean up picomatch
  types/picomatch/index.d.ts
  types/picomatch/lib/constants.d.ts
  types/picomatch/lib/parse.d.ts
  types/picomatch/lib/picomatch.d.ts
  types/picomatch/lib/scan.d.ts
  types/picomatch/parse.d.ts
  types/picomatch/picomatch-tests.ts
  types/rrdir/index.d.ts
  types/rrdir/rrdir-tests.ts
  types/rrdir/test/rrdir-tests.cjs.ts
  types/rrdir/tsconfig.json
Labels: Check Config, Edits multiple packages, Perf: Worse, Popular package, Unreviewed

#52717 update(get-folder-size): v3 update
  types/get-folder-size/get-folder-size-tests.ts
  types/get-folder-size/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Worse, Self Merge

#52763 [Tailwindcss] Add extend property
  types/tailwindcss/tailwind-config.d.ts
  types/tailwindcss/tailwindcss-tests.ts
Labels: Owner Approved, Perf: Worse, Self Merge

#52524 @types/react-css-modules: allow using prop `styleName` in React Components
  types/react-css-modules/index.d.ts
  types/react-css-modules/react-css-modules-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge

#52351 picomatch - accept string arrays for `ignore`
  types/picomatch/lib/picomatch.d.ts
  types/picomatch/picomatch-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52809 relay-test-utils: add type signature of MockFunctions.queuePendingOperation
  types/relay-test-utils/lib/RelayModernMockEnvironment.d.ts
  types/relay-test-utils/relay-test-utils-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge

#52796 Add type definitions for package ya-disk
  types/ya-disk/index.d.ts
  types/ya-disk/package.json
  types/ya-disk/ts4.0/index.d.ts
  types/ya-disk/ts4.0/tsconfig.json
  types/ya-disk/ts4.0/tslint.json
  types/ya-disk/ts4.0/ya-disk-tests.ts
  types/ya-disk/tsconfig.json
  types/ya-disk/tslint.json
  types/ya-disk/ya-disk-tests.ts
Labels: New Definition, Other Approved

#52699 fix(webpack-dev-server): add missing `listeningApp` property to `WebpackDevServer`
  types/poi/index.d.ts
  types/react-dev-utils/index.d.ts
  types/webpack-dev-server/index.d.ts
  types/webpack-dev-server/webpack-dev-server-tests.ts
  types/webpack-shell-plugin/index.d.ts
Labels: Edits multiple packages, Owner Approved, Perf: Same, Popular package

#52003 jasmine: update reporters
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Critical package, Owner Approved, Perf: Worse, Self Merge

#52781 Update dotenv-webpack to webpack 5
  types/dotenv-webpack/index.d.ts
  types/dotenv-webpack/package.json
  types/dotenv-webpack/tsconfig.json
Labels: Owner Approved, Perf: Better, Self Merge, Untested Change

#52768 [nodegit] Add types for Repository#createCommitWithSignature and friends
  types/nodegit/commit.d.ts
  types/nodegit/repository.d.ts
  types/nodegit/tag.d.ts
Labels: Owner Approved, Perf: Worse, Self Merge, Untested Change

#52685 [google-apps-script] Added Addon event objects declarations
  types/google-apps-script/addons/google-apps-script.addon-event-objects.d.ts
  types/google-apps-script/google-apps-script-tests.ts
  types/google-apps-script/index.d.ts
Labels: Owner Approved, Perf: Worse, Self Merge

#52810 Add ApplePayPayload interface
  types/braintree-web/modules/apple-pay.d.ts
  types/braintree-web/test/web.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52794 [react-native] fix type comment on Image.onLoad
  types/react-native/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52505 [ndarray] Prevent return type from shadowing function type
  types/cwise-compiler/index.d.ts
  types/cwise/cwise-tests.ts
  types/cwise/index.d.ts
  types/gl-texture2d/index.d.ts
  types/ndarray-ops/index.d.ts
  types/ndarray-scratch/index.d.ts
  types/ndarray/index.d.ts
  types/ndarray/ndarray-tests.ts
  types/numjs/index.d.ts
Labels: Edits Owners, Edits multiple packages, Owner Approved, Perf: Same, Self Merge

#52795 Yallist splice
  types/yallist/index.d.ts
  types/yallist/yallist-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52826 fix(number-to-words): UMD support and input type fix
  types/number-to-words/index.d.ts
  types/number-to-words/number-to-words-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52599 Remove Simplebar types
  notNeededPackages.json
  types/simplebar/index.d.ts
  types/simplebar/simplebar-tests.ts
  types/simplebar/test/module-tests.ts
  types/simplebar/tsconfig.json
  types/simplebar/tslint.json
  types/simplebar/v1/index.d.ts
  types/simplebar/v1/simplebar-tests.ts
  types/simplebar/v1/tsconfig.json
  types/simplebar/v1/tslint.json
  types/simplebar/v2/index.d.ts
  types/simplebar/v2/simplebar-tests.ts
  types/simplebar/v2/test/module-tests.ts
  types/simplebar/v2/tsconfig.json
  types/simplebar/v2/tslint.json
Labels: Edits Infrastructure

#52731 Delete react-editext as-of v4.0
  notNeededPackages.json
  types/react-editext/index.d.ts
  types/react-editext/react-editext-tests.tsx
  types/react-editext/tsconfig.json
  types/react-editext/tslint.json
Labels: Edits Infrastructure, No Other Owners, Perf: Same

#52815 [default-user-agent] Add types
  types/default-user-agent/index.d.ts
  types/default-user-agent/test/default-user-agent-tests.ts
  types/default-user-agent/tsconfig.json
  types/default-user-agent/tslint.json
Labels: New Definition, Other Approved

#52824 [astring] Remove types
  notNeededPackages.json
  types/astring/index.d.ts
  types/astring/test/astring-global.test.ts
  types/astring/test/astring.test.ts
  types/astring/tsconfig.json
  types/astring/tslint.json
Labels: Edits Infrastructure, Other Approved

#52185 [bcrypt] Update types to 5.0
  types/bcrypt/bcrypt-tests.ts
  types/bcrypt/index.d.ts
  types/bcrypt/tsconfig.json
Labels: Edits Owners, Perf: Worse, Popular package, Unreviewed

#52033 fix(webpack-dev-middleware): support webpack5
  types/webpack-dev-middleware/index.d.ts
  types/webpack-dev-middleware/package.json
  types/webpack-dev-middleware/tsconfig.json
  types/webpack-dev-middleware/webpack-dev-middleware-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Better, Popular package, Self Merge

#52769 types/chrome: Add getProfileUserInfo overload with ProfileDetails/AccountStatus
  types/chrome/index.d.ts
Labels: Owner Approved, Perf: Worse, Popular package, Self Merge, Untested Change

#52480 [jsrsasign] `verifySignature()` accepts strings, too
  types/jsrsasign/index.d.ts
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/X509.d.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#52842 Add ffbinaries
  types/ffbinaries/ffbinaries-tests.ts
  types/ffbinaries/index.d.ts
  types/ffbinaries/tsconfig.json
  types/ffbinaries/tslint.json
Labels: New Definition

#52838 [inline-css] Update to 3.0
  types/inline-css/index.d.ts
  types/inline-css/inline-css-tests.ts
  types/inline-css/tsconfig.json
  types/inline-css/tslint.json
Labels: Edits Owners, Owner Approved, Perf: Worse, Self Merge

#52839 [is-url] Add docs, improve tests, enable strictNull
  types/is-url/index.d.ts
  types/is-url/is-url-tests.ts
  types/is-url/tsconfig.json
  types/is-url/tslint.json
Labels: Edits Owners, Other Approved, Perf: Same, Self Merge

#52845 [ioredis] Add RPOP with COUNT parameter
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Owner Approved, Perf: Worse, Popular package, Self Merge

#52835 [exorcist] Update to 2.0
  types/exorcist/exorcist-tests.ts
  types/exorcist/index.d.ts
  types/exorcist/tsconfig.json
  types/exorcist/tslint.json
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#52808 sharp@0.28.1: Add support for limitInputPixels in OverlayOptions interface
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52483 openpgp: Fix some `packet.List` function definitions
  types/openpgp/index.d.ts
  types/openpgp/openpgp-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52850 [Faker] faker.address.nearbyGPSCoordinate accepts `number[]` as coordinates
  types/faker/faker-tests.ts
  types/faker/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#52445 [fabric] Add typings for controls
  types/fabric/fabric-impl.d.ts
  types/fabric/index.d.ts
  types/fabric/test/index.ts
Labels: Edits Owners, Perf: Same, Popular package, Unreviewed

#52667 Create declaration for murmurhash3js-revisited
  types/murmurhash3js-revisited/index.d.ts
  types/murmurhash3js-revisited/murmurhash3js-revisited-tests.ts
  types/murmurhash3js-revisited/tsconfig.json
  types/murmurhash3js-revisited/tslint.json
Labels: New Definition, Other Approved

#52855 Update get-pixels/save-pixels
  types/get-pixels/get-pixels-tests.ts
  types/get-pixels/index.d.ts
  types/save-pixels/index.d.ts
Labels: Edits multiple packages

#52642 New Types Package - preact-virtual-list
  types/preact-virtual-list/index.d.ts
  types/preact-virtual-list/package.json
  types/preact-virtual-list/preact-virtual-list-tests.tsx
  types/preact-virtual-list/tsconfig.json
  types/preact-virtual-list/tslint.json
Labels: Check Config, New Definition, Self Merge

#52544 update(emoji-flags): v1.3 and types changes
  types/emoji-flags/emoji-flags-tests.ts
  types/emoji-flags/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#52754 [video.js] Add responsive to VideoJsPlayerOptions & VideoJsPlayer
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Owner Approved, Perf: Worse, Popular package, Self Merge

#52716 Add types for es-aggregate-error
  types/es-aggregate-error/es-aggregate-error-tests.ts
  types/es-aggregate-error/index.d.ts
  types/es-aggregate-error/tsconfig.json
  types/es-aggregate-error/tslint.json
Labels: Check Config, New Definition, Self Merge

#52451 update(localized-countries): v2 update
  types/localized-countries/index.d.ts
  types/localized-countries/localized-countries-tests.ts
Labels: Edits Owners, Perf: Same, Unreviewed

#52463 fix(react-dom): Remove Blocking Mode
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
Labels: Critical package, Perf: Worse, Unreviewed

#52160 buildPipeline is converted to dynamic parameter numbers
  types/nut-pipe/index.d.ts
  types/nut-pipe/nut-pipe-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#52295 update [react-native-webrtc]: Edit properties types of RTCPeerConnectionConfiguration interface
  types/react-native-webrtc/index.d.ts
  types/react-native-webrtc/react-native-webrtc-tests.tsx
Labels: Perf: Same, Self Merge

#52596 [koa-joi-router] Update to version 8.0.0
  types/koa-joi-router/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#52622 [React-JSONSchema-Form] Added some JSDOC
  types/react-jsonschema-form/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge, Untested Change

#52311 i18n-js: add missing function I18n.locales.get()
  types/i18n-js/i18n-js-tests.ts
  types/i18n-js/index.d.ts
Labels: Perf: Same, Popular package, Self Merge

#52246 [lowlight] add listLanguages
  types/lowlight/index.d.ts
Labels: Perf: Same, Self Merge, Untested Change

#52656 feat: add fbt types
  types/fbt/fbt-tests.tsx
  types/fbt/index.d.ts
  types/fbt/tsconfig.json
  types/fbt/tslint.json
Labels: New Definition, Self Merge

#52830 [three] r128
  types/three/OTHER_FILES.txt
  types/three/examples/jsm/interactive/HTMLMesh.d.ts
  types/three/examples/jsm/interactive/InteractiveGroup.d.ts
  types/three/examples/jsm/loaders/GLTFLoader.d.ts
  types/three/examples/jsm/loaders/XLoader.d.ts
  types/three/examples/jsm/postprocessing/SSRPass.d.ts
  types/three/examples/jsm/shaders/SSRShader.d.ts
  types/three/index.d.ts
  types/three/src/renderers/webxr/WebXR.d.ts
  types/three/test/postprocessing/postprocessing-ssr.ts
Labels: Author is Owner, Check Config, Owner Approved, Perf: Same, Popular package, Self Merge

#52779 amplitude-js: Add includeFbclid property to Config
  types/amplitude-js/amplitude-js-tests.ts
  types/amplitude-js/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52813 update(money-math): missing methods
  types/money-math/index.d.ts
  types/money-math/money-math-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52786 Add type definitions for streamifier
  types/streamifier/index.d.ts
  types/streamifier/streamifier-tests.ts
  types/streamifier/tsconfig.json
  types/streamifier/tslint.json
Labels: New Definition, Self Merge

#51296 phoenix_live_view 0.15.4: support for uploaders
  types/phoenix_live_view/index.d.ts
  types/phoenix_live_view/phoenix_live_view-tests.ts
  types/phoenix_live_view/tsconfig.json
Labels: Author is Owner, No Other Owners, Self Merge

#52168 [@types/passport-spotify] fix verifyFunction arguments order, expires_in is not optional
  types/passport-spotify/index.d.ts
  types/passport-spotify/passport-spotify-tests.ts
Labels: Perf: Same, Self Merge

#52891 feat(compute-gcd): new definition
  types/compute-gcd/compute-gcd-tests.ts
  types/compute-gcd/index.d.ts
  types/compute-gcd/tsconfig.json
  types/compute-gcd/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52670 Introduce types for jest-preset-stylelint
  types/jest-preset-stylelint/index.d.ts
  types/jest-preset-stylelint/jest-preset-stylelint-tests.ts
  types/jest-preset-stylelint/tsconfig.json
  types/jest-preset-stylelint/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52636 New @ckeditor/ckeditor5-essentials v27
  types/ckeditor__ckeditor5-essentials/ckeditor__ckeditor5-essentials-tests.ts
  types/ckeditor__ckeditor5-essentials/index.d.ts
  types/ckeditor__ckeditor5-essentials/src/essentials.d.ts
  types/ckeditor__ckeditor5-essentials/tsconfig.json
  types/ckeditor__ckeditor5-essentials/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#52631 New @ckeditor/ckeditor5-export-pdf v27
  types/ckeditor__ckeditor5-core/src/editor/editorconfig.d.ts
  types/ckeditor__ckeditor5-export-pdf/OTHER_FILES.txt
  types/ckeditor__ckeditor5-export-pdf/ckeditor__ckeditor5-export-pdf-tests.ts
  types/ckeditor__ckeditor5-export-pdf/index.d.ts
  types/ckeditor__ckeditor5-export-pdf/src/exportpdf.d.ts
  types/ckeditor__ckeditor5-export-pdf/src/exportpdfcommand.d.ts
  types/ckeditor__ckeditor5-export-pdf/tsconfig.json
  types/ckeditor__ckeditor5-export-pdf/tslint.json
Labels: Check Config, Edits multiple packages, Maintainer Approved, New Definition, Perf: Same, Self Merge
