Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-03, with the labels that each got.

#51329 [mapbox-gl-draw] improve type export
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#51264 type definitions for 'double-metaphone'
  types/double-metaphone/double-metaphone-tests.ts
  types/double-metaphone/index.d.ts
  types/double-metaphone/tsconfig.json
  types/double-metaphone/tslint.json
Labels: New Definition, Other Approved

#51397 Add types for react-anchor-link-smooth-scroll
  types/react-anchor-link-smooth-scroll/index.d.ts
  types/react-anchor-link-smooth-scroll/react-anchor-link-smooth-scroll-tests.tsx
  types/react-anchor-link-smooth-scroll/tsconfig.json
  types/react-anchor-link-smooth-scroll/tslint.json
Labels: Check Config, New Definition, Other Approved

#51403 Adding types for are.na / arena-js
  types/are.na/are.na-tests.ts
  types/are.na/index.d.ts
  types/are.na/tsconfig.json
  types/are.na/tslint.json
Labels: Check Config, New Definition, Other Approved

#51410 Add types for mersennetwister
  types/mersennetwister/index.d.ts
  types/mersennetwister/mersennetwister-tests.ts
  types/mersennetwister/tsconfig.json
  types/mersennetwister/tslint.json
Labels: New Definition, Other Approved

#51417 Add type definitions for unused-webpack-plugin
  types/unused-webpack-plugin/index.d.ts
  types/unused-webpack-plugin/tsconfig.json
  types/unused-webpack-plugin/tslint.json
  types/unused-webpack-plugin/unused-webpack-plugin-tests.ts
Labels: New Definition, Other Approved

#51418 Add type definitions for @okta/jwt-verifier
  types/okta__jwt-verifier/index.d.ts
  types/okta__jwt-verifier/okta__jwt-verifier-tests.ts
  types/okta__jwt-verifier/tsconfig.json
  types/okta__jwt-verifier/tslint.json
Labels: New Definition, Other Approved

#51425 Added types declarations to handlebars-webpack-plugin
  types/handlebars-webpack-plugin/handlebars-webpack-plugin-tests.ts
  types/handlebars-webpack-plugin/index.d.ts
  types/handlebars-webpack-plugin/package.json
  types/handlebars-webpack-plugin/tsconfig.json
  types/handlebars-webpack-plugin/tslint.json
Labels: New Definition, Other Approved

#51435 [segment-api] Added segment-api typings
  types/segment-api/index.d.ts
  types/segment-api/segment-api-tests.ts
  types/segment-api/tsconfig.json
  types/segment-api/tslint.json
Labels: Check Config, New Definition, Other Approved

#51444 add css generator
  types/css-generator/css-generator-tests.ts
  types/css-generator/index.d.ts
  types/css-generator/tsconfig.json
  types/css-generator/tslint.json
Labels: New Definition, Other Approved

#51457 add types for delta-e
  types/delta-e/delta-e-tests.ts
  types/delta-e/index.d.ts
  types/delta-e/tsconfig.json
  types/delta-e/tslint.json
Labels: New Definition, Other Approved

#51462 Add types for react-native-global-props
  types/react-native-global-props/index.d.ts
  types/react-native-global-props/react-native-global-props-tests.tsx
  types/react-native-global-props/tsconfig.json
  types/react-native-global-props/tslint.json
Labels: Check Config, New Definition, Other Approved

#51483 create @ffmpeg-installer/ffmpeg
  types/ffmpeg-installer__ffmpeg/ffmpeg-installer__ffmpeg-tests.ts
  types/ffmpeg-installer__ffmpeg/index.d.ts
  types/ffmpeg-installer__ffmpeg/tsconfig.json
  types/ffmpeg-installer__ffmpeg/tslint.json
Labels: New Definition

#51480 fix: relay-network types for path is Array<string | number>
  types/relay-runtime/lib/network/RelayNetworkTypes.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Untested Change

#51428 bump uniqid version to 5.3
  types/uniqid/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#51155 fs-extra: Define missing fs.realpath.native
  types/fs-extra/fs-extra-tests.ts
  types/fs-extra/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same

#51474 [types/spotify-api] Update CurrentlyPlayingObject to support episodes + actions
  types/spotify-api/index.d.ts
  types/spotify-api/spotify-api-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51322 Fix: rax shared define
  types/rax/global.d.ts
  types/rax/index.d.ts
Labels: Author is Owner, Owner Approved, Untested Change

#51355 feat(react-router): add params inference to Route
  types/react-router/index.d.ts
  types/react-router/test/InheritingRoute.tsx
  types/react-router/test/Route.tsx
  types/react-router/test/generatePath.ts
  types/react-router/tsconfig.json
Labels: Critical package, Maintainer Approved, Other Approved, Owner Approved, Perf: Same, Self Merge

#51433 gamedig: Added requestRules to QueryOptions
  types/gamedig/gamedig-tests.ts
  types/gamedig/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51487 [@types/react-leaflet] Update types for v2.8.0.
  types/react-leaflet/index.d.ts
  types/react-leaflet/react-leaflet-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge

#51501 Update azdata to 1.26.0
  types/azdata/azdata-tests.ts
  types/azdata/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51077 [underscore] Update to 11.0
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#51294 [mysql]: Added missing types to declaration of TypeCast type
  types/mysql/index.d.ts
  types/mysql/mysql-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51495 [forge-viewer] added missing methods
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51477 [types@next-auth] - Update client.d.ts
  types/next-auth/client.d.ts
  types/next-auth/next-auth-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51316 [prettier] Add tests for plugin options, convert oppositeDescription to string
  types/prettier/index.d.ts
  types/prettier/prettier-tests.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#50999 Allow using Uint8Arrays with varint
  types/varint/index.d.ts
  types/varint/varint-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#51517 redux-sentry-middleware: Support @sentry/browser 6.x in typings
  types/redux-sentry-middleware/index.d.ts
  types/redux-sentry-middleware/package.json
Labels: Owner Approved, Perf: Same, Untested Change

#51181 Added comments and a missing public emit() method that
  types/oboe/index.d.ts
  types/oboe/oboe-tests.ts
Labels: Other Approved, Perf: Worse, Self Merge

#51492 [cli-progress] Fix `startTime` type
  types/cli-progress/cli-progress-tests.ts
  types/cli-progress/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51525 [spectrum] Add missing i18n settings, use readonly array for parameters
  types/spectrum/index.d.ts
  types/spectrum/spectrum-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51530 [@types/wechat-miniprogram] update to 3.3
  types/wechat-miniprogram/index.d.ts
  types/wechat-miniprogram/lib.wx.api.d.ts
  types/wechat-miniprogram/lib.wx.cloud.d.ts
  types/wechat-miniprogram/lib.wx.component.d.ts
  types/wechat-miniprogram/test/api-promisify.test.ts
  types/wechat-miniprogram/test/api.test.ts
  types/wechat-miniprogram/test/app.test.ts
  types/wechat-miniprogram/test/behavior.test.ts
  types/wechat-miniprogram/test/component.test.ts
  types/wechat-miniprogram/test/issue.test.ts
  types/wechat-miniprogram/test/page.test.ts
  types/wechat-miniprogram/tsconfig.json
  types/wechat-miniprogram/tslint.json
Labels: Author is Owner, Other Approved, Self Merge

#51056 [standard-http-error]: Static Status Message Constants
  types/standard-http-error/index.d.ts
  types/standard-http-error/standard-http-error-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#51438 [three] release 126
  types/three/OTHER_FILES.txt
  types/three/examples/jsm/libs/fflate.module.min.d.ts
  types/three/examples/jsm/loaders/GLTFLoader.d.ts
  types/three/examples/jsm/loaders/VOXLoader.d.ts
  types/three/examples/jsm/misc/Ocean.d.ts
  types/three/examples/jsm/objects/ReflectorForSSRPass.d.ts
  types/three/examples/jsm/postprocessing/SSRPass.d.ts
  types/three/examples/jsm/shaders/OceanShaders.d.ts
  types/three/examples/jsm/shaders/SSRShader.d.ts
  types/three/examples/jsm/webxr/XREstimatedLight.d.ts
  types/three/examples/jsm/webxr/XRHandModelFactory.d.ts
  types/three/examples/jsm/webxr/XRHandOculusMeshModel.d.ts
  types/three/examples/jsm/webxr/XRHandPrimitiveModel.d.ts
  types/three/index.d.ts
  types/three/src/Three.d.ts
  types/three/src/core/Object3D.d.ts
  types/three/src/helpers/ArrowHelper.d.ts
  types/three/src/loaders/DataTextureLoader.d.ts
  types/three/src/loaders/LoaderUtils.d.ts
  types/three/src/materials/Material.d.ts
  types/three/src/materials/MeshMatcapMaterial.d.ts
  types/three/src/materials/MeshNormalMaterial.d.ts
  types/three/src/materials/MeshPhongMaterial.d.ts
  types/three/src/materials/MeshStandardMaterial.d.ts
  types/three/src/materials/ShaderMaterial.d.ts
  types/three/src/polyfills.d.ts
  types/three/src/renderers/WebGLRenderTarget.d.ts
  types/three/src/renderers/WebGLRenderer.d.ts
  types/three/src/renderers/shaders/UniformsLib.d.ts
  types/three/src/textures/DataTexture.d.ts
  types/three/src/textures/DataTexture2DArray.d.ts
  types/three/src/textures/DataTexture3D.d.ts
  types/three/test/examples/loaders/gltfloader-plugin.ts
  types/three/test/loaders/loaders-gltfloader-extensions.ts
  types/three/test/loaders/loaders-gltfloader-plugin.ts
  types/three/test/loaders/loaders-voxloader.ts
  types/three/test/materials/materials-texture3d-partialupdate.ts
  types/three/test/postprocessing/postprocessing-ssr.ts
  types/three/test/renderers/renderers-renderTarget-texture2DArray.ts
  types/three/test/webxr/webxr-ar-lighting.ts
  types/three/test/webxr/webxr-vr-handinput-cubes.ts
  types/three/tsconfig.json
Labels: Author is Owner, Check Config, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#51532 Remove owner from jsonld
  types/jsonld/index.d.ts
Labels: Edits Owners, Perf: Same, Untested Change

#51338 [koa] Fix http-assert import issue
  types/koa/index.d.ts
  types/koa/tsconfig.json
Labels: Author is Owner, Check Config, Critical package, Owner Approved, Perf: Same, Unreviewed, Untested Change

#51497 add types for time-constants
  types/time-constants/index.d.ts
  types/time-constants/time-constants-tests.ts
  types/time-constants/tsconfig.json
  types/time-constants/tslint.json
Labels: New Definition

#51017 update(numeral): `value()` method returns union type
  types/numeral/index.d.ts
  types/numeral/test/numeral-tests-cjs.ts
  types/numeral/test/numeral-tests-global.ts
Labels: Author is Owner, Perf: Same, Popular package, Unreviewed

#51389 feat: added definitions for es-get-iterator, iterate-iterator, and iterate-value
  types/es-get-iterator/es-get-iterator-tests.ts
  types/es-get-iterator/index.d.ts
  types/es-get-iterator/tsconfig.json
  types/es-get-iterator/tslint.json
  types/iterate-iterator/index.d.ts
  types/iterate-iterator/iterate-iterator-tests.ts
  types/iterate-iterator/tsconfig.json
  types/iterate-iterator/tslint.json
  types/iterate-value/index.d.ts
  types/iterate-value/iterate-value-tests.ts
  types/iterate-value/tsconfig.json
  types/iterate-value/tslint.json
Labels: Edits multiple packages, Maintainer Approved, New Definition, Other Approved, Self Merge

#51215 [spotify-web-api-node] Wrong return type in getShowEpisodes method
  types/spotify-web-api-node/index.d.ts
  types/spotify-web-api-node/spotify-web-api-node-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51555 VS Code 1.54.0 Extension API
  types/vscode/index.d.ts
Labels: Perf: Same, Popular package, Untested Change

#51175 Add pg/lib/type-overrides types.
  types/pg/lib/type-overrides.d.ts
  types/pg/pg-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51537 [braintree] Add disbursement webhook notification kind and body
  types/braintree/braintree-tests.ts
  types/braintree/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51088 add types for fast-fifo
  types/fast-fifo/fast-fifo-tests.ts
  types/fast-fifo/fixed-size.d.ts
  types/fast-fifo/index.d.ts
  types/fast-fifo/tsconfig.json
  types/fast-fifo/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51567 wavesurfer.js: fix incorrect type for a property
  types/wavesurfer.js/index.d.ts
  types/wavesurfer.js/wavesurfer.js-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51573 [@types/indy-sdk] update schema and ledger response type
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51300 [react-native-maps]: Remove myself from the definition owners
  types/react-native-maps/index.d.ts
Labels: Author is Owner, Edits Owners, Owner Approved, Unreviewed, Untested Change

#51348 [react-native]: Remove myself from the definition owners
  types/react-native/index.d.ts
Labels: Author is Owner, Critical package, Edits Owners, Owner Approved, Perf: Same, Unreviewed, Untested Change

#51557 update(dotenv-webpack): v6 update
  types/dotenv-webpack/dotenv-webpack-tests.ts
  types/dotenv-webpack/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51578 update(dotenv-webpack): v7
  types/dotenv-webpack/dotenv-webpack-tests.ts
  types/dotenv-webpack/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#51216 @types/google-apps-script - Added missing "Time-driven events" interface
  types/google-apps-script/google-apps-script-events.d.ts
  types/google-apps-script/google-apps-script-tests.ts
Labels: Other Approved, Owner Approved, Perf: Same, Self Merge

#51409 Updating whois-json return type
  types/whois-json/index.d.ts
  types/whois-json/whois-json-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#51583 chore(concurrently): update promise callback types
  types/concurrently/concurrently-tests.ts
  types/concurrently/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51560 [yaireo__tagify] Fix types, add missing types, add missing docs, cleanup
  types/yaireo__tagify/index.d.ts
  types/yaireo__tagify/yaireo__tagify-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#51390 [react-datepicker]: Add customHeaderCount prop to typings (react-datepicker 3.5.0)
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51419 add mongodb.Timestamp as a valid $currentDate target in mongodb type defs
  types/mongodb/index.d.ts
  types/mongodb/test/collection/updateX.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51568 [bull-arena] Allow passing Redis instance directly
  types/bull-arena/bull-arena-tests.ts
  types/bull-arena/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51440 [luxon] Add DATETIME_MED_WITH_WEEKDAY preset
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51601 [auth0] Fix auth0 TokensManager class name
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Owner Approved, Popular package, Self Merge

#51592 [chosen-js] adjust SelectedData, replace deprecated JQueryEventObject
  types/chosen-js/chosen-js-tests.ts
  types/chosen-js/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51398 [redux-injectable-store] Update types for 1.1
  types/redux-injectable-store/index.d.ts
  types/redux-injectable-store/redux-injectable-store-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#51591 [pdfmake] Add image cover, superscript and subscript
  types/pdfmake/interfaces.d.ts
  types/pdfmake/test/pdfmake-examples-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51405 Added the missing filterTime interface property
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51585 nodegit: Repository.discover returns Promise<string>, not Promise<buf>
  types/nodegit/repository.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#51402 [atom] add tests for autocomplete-plus
  types/atom/OTHER_FILES.txt
  types/atom/autocomplete-plus/autocomplete-plus-tests.ts
  types/atom/autocomplete-plus/index.d.ts
  types/atom/tslint.json
Labels: Author is Owner, Check Config, Owner Approved, Perf: Same, Unreviewed

#51399 [@types/carbon-components-react] Update to match 7.29.0
  types/carbon-components-react/index.d.ts
  types/carbon-components-react/lib/components/ComboBox/ComboBox.d.ts
  types/carbon-components-react/lib/components/ComposedModal/ComposedModal.d.ts
  types/carbon-components-react/lib/components/DatePicker/DatePicker.d.ts
  types/carbon-components-react/lib/components/Modal/Modal.d.ts
  types/carbon-components-react/lib/components/MultiSelect/MultiSelect.d.ts
  types/carbon-components-react/lib/components/Search/Search.d.ts
  types/carbon-components-react/lib/components/Tile/Tile.d.ts
  types/carbon-components-react/lib/components/UIShell/SideNavDivider.d.ts
  types/carbon-components-react/lib/components/UIShell/index.d.ts
Labels: Author is Owner, Perf: Same, Unreviewed, Untested Change

#51602 qs: Add object type as a possible argument to qs.parse
  types/qs/index.d.ts
  types/qs/qs-tests.ts
Labels: Critical package, Owner Approved, Perf: Same

#51584 discord-rpc: Add partyId to client.setActivity
  types/discord-rpc/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#51566 Add button type for discord-rpc
  types/discord-rpc/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge, Untested Change

#51545 [react-flatpickr] Drop "begincalendar"'s ownership of the package
  types/react-flatpickr/index.d.ts
Labels: Author is Owner, Edits Owners, Owner Approved, Perf: Same, Untested Change

#51427 [node] Update broken link to V8 stack trace docs
  types/node/globals.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Untested Change

#51443 chore(exif): added the missing interface properties
  types/exif/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#51450 [cometd] Fix: Adds missing shorthand property for websocket transport
  types/cometd/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#51475 [sql.js] Remove hozuki's definition owner status
  types/sql.js/index.d.ts
Labels: Author is Owner, Edits Owners, Owner Approved, Perf: Same, Untested Change

#51490 fix: rax render method type
  types/rax/index.d.ts
Labels: Author is Owner, Owner Approved, Self Merge, Untested Change

#51386 Updated Agent for https type
  types/tunnel/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Unreviewed, Untested Change

#51334 [react-instantsearch] reflect `smartSort` widget/connector implementation and new parameters `stats` widget/connector
  types/react-instantsearch-core/index.d.ts
  types/react-instantsearch-dom/index.d.ts
  types/react-instantsearch-native/index.d.ts
  types/react-instantsearch/connectors.d.ts
  types/react-instantsearch/dom.d.ts
  types/react-instantsearch/index.d.ts
  types/react-instantsearch/react-instantsearch-tests.tsx
Labels: Edits multiple packages, Owner Approved, Perf: Same, Popular package, Self Merge

#51563 fix(eslint): change the argument type of constructor of ESLint class …
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge

#51499 update(uglify-js): v3.13
  types/uglify-js/index.d.ts
  types/uglify-js/uglify-js-tests.ts
Labels: Author is Owner, Critical package, Owner Approved, Perf: Same

#50820 Update Mac.d.ts for doFinal, doFinalHex and doFinalString right return type and examples
  types/jsrsasign/modules/KJUR/crypto/Mac.d.ts
Labels: Owner Approved, Perf: Same, Unreviewed, Untested Change

#51464 [vuelidate] Added missing separator parameter
  types/vuelidate/lib/validators.d.ts
Labels: Perf: Same, Untested Change

#51274 update(svg-spritemap-webpack-plugin): v3.9 (webpack 5)
  types/svg-spritemap-webpack-plugin/index.d.ts
  types/svg-spritemap-webpack-plugin/package.json
  types/svg-spritemap-webpack-plugin/svg-spritemap-webpack-plugin-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#51382 Add Cloudflare type definitions
  types/cloudflare/cloudflare-tests.ts
  types/cloudflare/index.d.ts
  types/cloudflare/tsconfig.json
  types/cloudflare/tslint.json
Labels: New Definition

#51529 Definitions for cabarc
  types/cabarc/cabarc-tests.ts
  types/cabarc/index.d.ts
  types/cabarc/tsconfig.json
  types/cabarc/tslint.json
Labels: New Definition, Other Approved

#51488 fix(react): Use SchedulerInteraction type from scheduler/tracing
  types/react/index.d.ts
  types/react/v16/index.d.ts
Labels: Author is Owner, Critical package, Owner Approved, Perf: Same, Self Merge, Untested Change

#51582 [rails__actioncable] Create types
  types/rails__actioncable/index.d.ts
  types/rails__actioncable/rails__actioncable-tests.ts
  types/rails__actioncable/tsconfig.json
  types/rails__actioncable/tslint.json
Labels: New Definition, Other Approved

#51576 fix(next-auth): allow string `signIn` callbacks
  types/next-auth/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#51363 Added type definitions for noloopfor
  types/noloopfor/index.d.ts
  types/noloopfor/noloopfor-tests.ts
  types/noloopfor/tsconfig.json
  types/noloopfor/tslint.json
Labels: New Definition, Other Approved

#51432 use-double-click: add types
  types/use-double-click/index.d.ts
  types/use-double-click/tsconfig.json
  types/use-double-click/tslint.json
  types/use-double-click/use-double-click-tests.tsx
Labels: Check Config, New Definition, Other Approved

#51577 feat: add carbon__feature-flags
  types/carbon__feature-flags/OTHER_FILES.txt
  types/carbon__feature-flags/carbon__feature-flags-tests.ts
  types/carbon__feature-flags/es/index.d.ts
  types/carbon__feature-flags/generated/feature-flags.d.ts
  types/carbon__feature-flags/index.d.ts
  types/carbon__feature-flags/tsconfig.json
  types/carbon__feature-flags/tslint.json
Labels: Check Config, New Definition, Other Approved

#51544 Added types for mcping-js
  types/mcping-js/index.d.ts
  types/mcping-js/mcping-js-tests.ts
  types/mcping-js/tsconfig.json
  types/mcping-js/tslint.json
Labels: New Definition, Other Approved

#51552 [leaflet-textpath] Add new package.
  types/leaflet-textpath/index.d.ts
  types/leaflet-textpath/leaflet-textpath-tests.ts
  types/leaflet-textpath/tsconfig.json
  types/leaflet-textpath/tslint.json
Labels: New Definition, Other Approved

#51504 [videojs-contrib-quality-levels]: Add types
  types/videojs-contrib-quality-levels/index.d.ts
  types/videojs-contrib-quality-levels/src/quality-level-list.d.ts
  types/videojs-contrib-quality-levels/src/quality-level.d.ts
  types/videojs-contrib-quality-levels/tsconfig.json
  types/videojs-contrib-quality-levels/tslint.json
  types/videojs-contrib-quality-levels/videojs-contrib-quality-levels-tests.ts
Labels: Check Config, New Definition

#51515 Definitions for tsv
  types/tsv/index.d.ts
  types/tsv/tsconfig.json
  types/tsv/tslint.json
  types/tsv/tsv-tests.ts
Labels: New Definition, Other Approved

#51507 Add type definitions for react-twitter-conversion-tracker-plus
  types/react-twitter-conversion-tracker-plus/index.d.ts
  types/react-twitter-conversion-tracker-plus/react-twitter-conversion-tracker-plus-tests.ts
  types/react-twitter-conversion-tracker-plus/tsconfig.json
  types/react-twitter-conversion-tracker-plus/tslint.json
Labels: New Definition, Other Approved

#51508 Add type definitions for react-twitter-conversion-tracker
  types/react-twitter-conversion-tracker/index.d.ts
  types/react-twitter-conversion-tracker/react-twitter-conversion-tracker-tests.ts
  types/react-twitter-conversion-tracker/tsconfig.json
  types/react-twitter-conversion-tracker/tslint.json
Labels: New Definition, Other Approved

#51491 [html-replace-webpack-plugin] Adding initial types for `html-replace-webpack-plugin`
  types/html-replace-webpack-plugin/html-replace-webpack-plugin-tests.ts
  types/html-replace-webpack-plugin/index.d.ts
  types/html-replace-webpack-plugin/tsconfig.json
  types/html-replace-webpack-plugin/tslint.json
Labels: New Definition, Other Approved

#51505 Add types for detect-libc
  types/detect-libc/detect-libc-tests.ts
  types/detect-libc/index.d.ts
  types/detect-libc/tsconfig.json
  types/detect-libc/tslint.json
Labels: New Definition

#51579 [restify] Update type of options for mount method
  types/restify/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51308 create @types/react-native-ad-manager
  types/react-native-ad-manager/helper-types.d.ts
  types/react-native-ad-manager/index.d.ts
  types/react-native-ad-manager/src/CTKAdManagerBanner.d.ts
  types/react-native-ad-manager/src/CTKAdManagerInterstitial.d.ts
  types/react-native-ad-manager/src/native-ads/NativeAdsManager.d.ts
  types/react-native-ad-manager/src/native-ads/TriggerableViewManager.d.ts
  types/react-native-ad-manager/src/native-ads/withNativeAd.d.ts
  types/react-native-ad-manager/test/NativeAdView.tsx
  types/react-native-ad-manager/test/react-native-ad-manager-tests.tsx
  types/react-native-ad-manager/tsconfig.json
  types/react-native-ad-manager/tslint.json
Labels: Check Config, New Definition, Unreviewed

#51150 chore: deprecate @types/agenda
  notNeededPackages.json
  types/agenda/agenda-tests.ts
  types/agenda/index.d.ts
  types/agenda/tsconfig.json
  types/agenda/tslint.json
Labels: Edits Infrastructure

#51392 [ci-info] Remove types and update [is-ci] to 3.0
  notNeededPackages.json
  types/ci-info/ci-info-tests.ts
  types/ci-info/index.d.ts
  types/ci-info/tsconfig.json
  types/ci-info/tslint.json
  types/is-ci/index.d.ts
  types/is-ci/package.json
Labels: Edits Infrastructure, Edits multiple packages, Perf: Same, Popular package, Unreviewed

#51393 [find-package-json] Update to 1.2
  types/find-package-json/find-package-json-tests.ts
  types/find-package-json/index.d.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Popular package, Unreviewed

#51163 [websequencediagrams] Update to 1.0
  types/websequencediagrams/index.d.ts
  types/websequencediagrams/websequencediagrams-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#51121 [uuid-readable] Update to 0.0.2
  types/uuid-readable/index.d.ts
  types/uuid-readable/uuid-readable-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Better, Unreviewed

#51551 [leaflet-geosearch] Remove package and add to notNeededPackages.json
  notNeededPackages.json
  types/leaflet-geosearch/index.d.ts
  types/leaflet-geosearch/leaflet-geosearch-tests.ts
  types/leaflet-geosearch/tsconfig.json
  types/leaflet-geosearch/tslint.json
Labels: Edits Infrastructure, Other Approved, Owner Approved

#51258 [osrs-json-api] Add TrendChangeObject interface, and allow string type for TrendPriceObject
  types/osrs-json-api/index.d.ts
  types/osrs-json-api/osrs-json-api-tests.ts
Labels: Perf: Same, Unreviewed

#51356 InitOptions miss field `theme`
  types/next-auth/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#51164 [xar] Add missing options
  types/xar/index.d.ts
  types/xar/xar-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Worse, Self Merge

#51166 [calendar] Map exact return types with generics
  types/calendar/calendar-tests.ts
  types/calendar/index.d.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#51459 [openrct2] Add types for OpenRCT2 plugin framework
  types/openrct2/index.d.ts
  types/openrct2/test/openrct2-tests.example.ts
  types/openrct2/test/openrct2-tests.ts
  types/openrct2/tsconfig.json
  types/openrct2/tslint.json
Labels: Check Config, New Definition, Other Approved

#51130 fix(serverless): update config properties
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Perf: Same, Unreviewed

#51429 fix(sinon): spying on instance should be possible
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge

#51210 react-calendar: Add missing closeCalendar prop
  types/react-calendar/index.d.ts
  types/react-calendar/react-calendar-tests.tsx
Labels: Other Approved, Perf: Same, Popular package, Unreviewed

#51256 [jasmine] Clock method 'install' returns Clock.
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Critical package, Owner Approved, Perf: Same, Unreviewed

#51408 Update convict methods to use templete literal types
  types/convict-format-with-validator/index.d.ts
  types/convict/convict-tests.ts
  types/convict/index.d.ts
Labels: Edits Owners, Edits multiple packages, Owner Approved, Perf: Same, Popular package, Self Merge

#51135 Youtube: Add Spherical (360 degree) video config get/set
  types/youtube/index.d.ts
  types/youtube/youtube-tests.ts
Labels: Perf: Same, Popular package, Unreviewed

#51112 [babel-plugin-tester] Fix wrong types
  types/babel-plugin-tester/babel-plugin-tester-tests.ts
  types/babel-plugin-tester/index.d.ts
Labels: Edits Owners, Perf: Same, Unreviewed

#51096 bl typings update
  types/bl/bl-tests.ts
  types/bl/index.d.ts
Labels: Edits Owners, Perf: Same, Popular package, Unreviewed

#51061 [continuation-local-storage] cleanup and type corrections
  types/continuation-local-storage/continuation-local-storage-tests.ts
  types/continuation-local-storage/index.d.ts
Labels: Edits Owners, Perf: Same, Popular package, Unreviewed

#51482 [websocket] move disableNagleAlgorithm to IConfig
  types/websocket/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge, Untested Change

#51394 [rox-browser] add default export
  types/rox-browser/index.d.ts
  types/rox-browser/tslint.json
Labels: Check Config, Edits Owners, Owner Approved, Perf: Same, Self Merge, Untested Change

#51594 [inboxsdk] Corrected addComposeNotice return type
  types/inboxsdk/inboxsdk-tests.ts
  types/inboxsdk/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#51539 fix(node): Backport #38480 to node 10 and node 11 declarations: replace reserved identifier in a function parameter
  types/node/v10/readline.d.ts
  types/node/v11/readline.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge, Untested Change

#51597 [jqueryui]: Fix return type of addClass (and similar methods) to match those of jquery.
  types/jqueryui/index.d.ts
  types/jqueryui/jqueryui-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51607 feat(marked): update tokenizer api to 2.x
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51571 Croppie. Update CroppieOptions according to documentation
  types/croppie/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#51613 [sql.js] Export as default
  types/sql.js/index.d.ts
  types/sql.js/sql.js-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#51605 [next-auth] Update signin with third parameter
  types/next-auth/client.d.ts
  types/next-auth/next-auth-tests.ts
  types/next-auth/package.json
Labels: Owner Approved, Perf: Same, Self Merge

#51099 [react-table]: mark column parent optional
  types/react-table/index.d.ts
  types/react-table/react-table-tests.tsx
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge, Unmerged

#51520 Improve Jasmine CustomReporterResult type
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge

#51411 [tuya-panel-kit] add some miss props and comment
  types/tuya-panel-kit/index.d.ts
  types/tuya-panel-kit/package.json
Labels: Author is Owner, Owner Approved, Self Merge, Untested Change

#51496 [prosemirror-gapcursor] Add NodeSpec.allowGapCursor
  types/prosemirror-gapcursor/index.d.ts
  types/prosemirror-gapcursor/prosemirror-gapcursor-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#51617 [rails__actioncable] Add readonly props, update types
  types/rails__actioncable/index.d.ts
  types/rails__actioncable/rails__actioncable-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#51543 Improve Omit override
  types/react-flatpickr/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge, Untested Change

#51575 [next-auth] Add main server export overload
  types/next-auth/index.d.ts
  types/next-auth/next-auth-tests.ts
Labels: Author is Owner, Edits Owners, Owner Approved, Perf: Same, Self Merge

#51616 [proper-url-join] Add types for new leading & trailing slash option
  types/proper-url-join/index.d.ts
  types/proper-url-join/proper-url-join-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51265 Allow passing a multicompiler to koa-webpack
  types/koa-webpack/index.d.ts
  types/koa-webpack/koa-webpack-tests.ts
Labels: Unreviewed

#51547 Added damerau-levenshtein types
  types/damerau-levenshtein/damerau-levenshtein-tests.ts
  types/damerau-levenshtein/index.d.ts
  types/damerau-levenshtein/tsconfig.json
  types/damerau-levenshtein/tslint.json
Labels: New Definition, Other Approved

#51288 [clipboard-js] Remove types
  types/clipboard-js/clipboard-js-tests.ts
  types/clipboard-js/index.d.ts
  types/clipboard-js/tsconfig.json
  types/clipboard-js/tslint.json
Labels: Unreviewed

#51620 remove(webpack-merge): remove package
  notNeededPackages.json
  types/webpack-merge/index.d.ts
  types/webpack-merge/tsconfig.json
  types/webpack-merge/tslint.json
  types/webpack-merge/v0/index.d.ts
  types/webpack-merge/v0/tsconfig.json
  types/webpack-merge/v0/tslint.json
  types/webpack-merge/v0/webpack-merge-tests.ts
  types/webpack-merge/webpack-merge-tests.ts
Labels: Edits Infrastructure, Owner Approved, Popular package

#51436 build: Force double quotes through prettier
  .prettierrc.json
Labels: Edits Infrastructure

#51618 feat(three-dat.gui): Add declarations and tests
  types/three-dat.gui/index.d.ts
  types/three-dat.gui/package.json
  types/three-dat.gui/three-dat.gui-tests.ts
  types/three-dat.gui/tsconfig.json
  types/three-dat.gui/tslint.json
Labels: Check Config, New Definition

#51291 [nodemailer-ses-transport] Fix version to 1.5
  types/nodemailer-ses-transport/index.d.ts
Labels: Perf: Same, Unreviewed, Untested Change

#51611 Updated GitHub profile link for Nicholas Newman in react-anchor-link-smooth-scroll
  types/react-anchor-link-smooth-scroll/index.d.ts
Labels: Edits Owners, Perf: Same, Untested Change

#51299 fix(cheerio): support passing an array of elements to `load`
  types/cheerio/cheerio-tests.ts
  types/cheerio/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge

#51588 @ember/routing Add fullRouteName to Route
  types/ember__routing/route.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51420 feat(http-proxy-middleware): remove types
  notNeededPackages.json
  types/http-proxy-middleware/http-proxy-middleware-tests.ts
  types/http-proxy-middleware/index.d.ts
  types/http-proxy-middleware/tsconfig.json
  types/http-proxy-middleware/tslint.json
  types/webpack-dev-server/index.d.ts
  types/webpack-dev-server/package.json
  types/webpack-dev-server/webpack-dev-server-tests.ts
  types/webpack-plugin-serve/index.d.ts
  types/webpack-plugin-serve/package.json
  types/webpack-plugin-serve/webpack-plugin-serve-tests.ts
Labels: Edits Infrastructure, Edits multiple packages, Owner Approved, Perf: Same, Popular package, Unreviewed

#50921 Add TailwindCSS type definitions
  types/tailwindcss/colors.d.ts
  types/tailwindcss/defaultTheme.d.ts
  types/tailwindcss/index.d.ts
  types/tailwindcss/resolveConfig.d.ts
  types/tailwindcss/tailwind-config.d.ts
  types/tailwindcss/tailwindcss-tests.ts
  types/tailwindcss/tsconfig.json
  types/tailwindcss/tslint.json
Labels: New Definition
