Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-01, with the labels that each got.

#50272 [node-telegram-bot-api] Update typings for version 0.51.0
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50263 @types/lodash fix typo
  types/lodash/common/array.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Untested Change

#50282 [git-diff] fix boolean type and few description changes
  types/git-diff/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#50341 Fix Dir.readSync to declare a null return value
  types/node/fs.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Untested Change

#50311 [@types/node] Make AssertionError extend Error, not just implement its interface
  types/node/assert.d.ts
  types/node/test/assert.ts
Labels: Critical package, Owner Approved, Perf: Same

#50319 [tar-stream] Extract options
  types/tar-stream/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50161 [selenium-webdriver] Fix typo in IPerfLoggingPrefs
  types/selenium-webdriver/chrome.d.ts
  types/selenium-webdriver/test/chrome.ts
Labels: Critical package, Owner Approved, Perf: Same, Unreviewed

#50060 Adding AnonymousUtils definition for parse
  types/parse/index.d.ts
  types/parse/parse-tests.ts
  types/parse/ts3.6/index.d.ts
  types/parse/ts3.6/parse-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50267 react-redux: add Mark Erikson as owner
  types/react-redux/index.d.ts
Labels: Author is Owner, Critical package, Edits Owners, Perf: Same, Untested Change

#50352 [sql-query-identifier] remove typings
  notNeededPackages.json
  types/sql-query-identifier/index.d.ts
  types/sql-query-identifier/sql-query-identifier-tests.ts
  types/sql-query-identifier/tsconfig.json
  types/sql-query-identifier/tslint.json
Labels: Edits Infrastructure, No Other Owners

#50307 feat(classify-poetry): new definition
  types/classify-poetry/classifiers/abc.d.ts
  types/classify-poetry/classifiers/couplet.d.ts
  types/classify-poetry/classifiers/haiku.d.ts
  types/classify-poetry/classifiers/limerick.d.ts
  types/classify-poetry/classifiers/quatrain.d.ts
  types/classify-poetry/classifiers/sonnet.d.ts
  types/classify-poetry/classifiers/tanka.d.ts
  types/classify-poetry/classifiers/terzaRima.d.ts
  types/classify-poetry/classify-poetry-tests.ts
  types/classify-poetry/index.d.ts
  types/classify-poetry/tsconfig.json
  types/classify-poetry/tslint.json
Labels: New Definition

#50001 update(copy-webpack-plugin): `info`, `to` options
  types/copy-webpack-plugin/copy-webpack-plugin-tests.ts
  types/copy-webpack-plugin/index.d.ts
Labels: Author is Owner, Perf: Same, Popular package, Unreviewed

#50004 update react-hyperscript
  types/react-hyperscript/index.d.ts
  types/react-hyperscript/react-hyperscript-tests.ts
Labels: Perf: Same, Unreviewed

#50009 ali-oss: [feat] add STS class type
  types/ali-oss/ali-oss-tests.ts
  types/ali-oss/index.d.ts
Labels: Perf: Same, Unreviewed

#50038 [mercadopago] export MercadoPago interface
  types/mercadopago/index.d.ts
  types/mercadopago/interface.d.ts
  types/mercadopago/mercadopago-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#50350 Add type definition for wuzzy package
  types/wuzzy/index.d.ts
  types/wuzzy/tsconfig.json
  types/wuzzy/tslint.json
  types/wuzzy/wuzzy-tests.ts
Labels: New Definition

#50270 flashpoint-launcher: 9.1 typings
  types/flashpoint-launcher/flashpoint-launcher-tests.ts
  types/flashpoint-launcher/index.d.ts
  types/flashpoint-launcher/tsconfig.json
  types/flashpoint-launcher/tslint.json
Labels: New Definition, Other Approved

#50085 [twilio-video] Fix publishTrack options
  types/twilio-video/index.d.ts
  types/twilio-video/twilio-video-tests.ts
Labels: Perf: Same, Unreviewed

#50247 [README] Add Naming section
  README.cn.md
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
Labels: Edits Infrastructure, Maintainer Approved

#50242 [README] Use consistent heading case
  README.cn.md
  README.es.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
Labels: Edits Infrastructure, Maintainer Approved

#50095 Update elm type definitions to work with 0.19
  types/elm/elm-tests.ts
  types/elm/index.d.ts
Labels: Edits Owners, Perf: Same, Unreviewed

#50086 [forge-viewer] updated Autodesk.Viewing.Navigation
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Other Approved, Perf: Same, Unreviewed, Untested Change

#50244 [README] Use same/distinct placeholders to hint at relationship
  README.cn.md
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
Labels: Edits Infrastructure

#50325 Adding types for TaskerJsRunner (https://github.com/amoshydra/tasker-js-runner/)
  types/tasker-js-runner/index.d.ts
  types/tasker-js-runner/package.json
  types/tasker-js-runner/tasker-js-runner-tests.ts
  types/tasker-js-runner/tsconfig.json
  types/tasker-js-runner/tslint.json
Labels: New Definition

#50283 types: add carbon__elements
  types/carbon__elements/carbon__elements-tests.ts
  types/carbon__elements/index.d.ts
  types/carbon__elements/tsconfig.json
  types/carbon__elements/tslint.json
Labels: New Definition, Other Approved

#50277 Add typings for ahoy.js
  types/ahoy.js/index.d.ts
  types/ahoy.js/test/ahoy.js-tests.cjs.ts
  types/ahoy.js/test/ahoy.js-tests.esm.ts
  types/ahoy.js/tsconfig.json
  types/ahoy.js/tslint.json
Labels: New Definition

#50037 [agenda] fixing types for agenda.mongo() method to allow passing a db object directly
  types/agenda/agenda-tests.ts
  types/agenda/index.d.ts
Labels: Perf: Same, Unreviewed

#50010 serverless: extended Service class attributes
  types/serverless/classes/Service.d.ts
  types/serverless/index.d.ts
  types/serverless/serverless-tests.ts
Labels: Perf: Same, Unreviewed

#50059 [@types/tpdirect] Add more typing and more test cases
  types/tpdirect/direct-pay.d.ts
  types/tpdirect/google-pay.d.ts
  types/tpdirect/payment-request-api.d.ts
  types/tpdirect/tpdirect-tests.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#50058 hafas-client update to version 5.12
  types/hafas-client/hafas-client-tests.ts
  types/hafas-client/index.d.ts
  types/hafas-client/p/mobiliteit-lu/index.d.ts
  types/hafas-client/p/vrn/index.d.ts
Labels: Author is Owner, No Other Owners, Perf: Same, Unreviewed

#50356 remove(emoji-regex): as of 9.2.0
  notNeededPackages.json
  types/emoji-regex/emoji-regex-tests.ts
  types/emoji-regex/es2015/index.d.ts
  types/emoji-regex/es2015/text.d.ts
  types/emoji-regex/index.d.ts
  types/emoji-regex/text.d.ts
  types/emoji-regex/tsconfig.json
  types/emoji-regex/tslint.json
Labels: Edits Infrastructure

#50096 [undertaker] refactor out task callback definition
  types/undertaker/index.d.ts
  types/undertaker/undertaker-tests.ts
Labels: Perf: Same, Popular package, Unreviewed

#50225 feat(aws-lambda): use tuple for property type in `LexSlotDetail` interface
  types/aws-lambda/test/lex-tests.ts
  types/aws-lambda/trigger/lex.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50335 New type definition for @ronomon/hash-table
  types/ronomon__hash-table/index.d.ts
  types/ronomon__hash-table/ronomon__hash-table-tests.ts
  types/ronomon__hash-table/tsconfig.json
  types/ronomon__hash-table/tslint.json
Labels: New Definition

#50262 node: ChildProcess "close" event can have null code/signal
  types/node/child_process.d.ts
  types/node/test/child_process.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge

#50351 Updated type definitions for git-config-path
  types/git-config-path/git-config-path-tests.ts
  types/git-config-path/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#50243 add definitions for AVIF and HEIF in sharp
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Edits Owners, Other Approved, Owner Approved, Perf: Same, Popular package, Self Merge

#50136 nuxtjs__auth: Added missing Storage functions
  types/nuxtjs__auth/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#50097 node/dns: add setLocalAddress and cancel to dns promises resolver
  types/node/dns.d.ts
  types/node/index.d.ts
  types/node/test/dns.ts
Labels: Critical package, Edits Owners, Owner Approved, Perf: Same, Self Merge, Unmerged

#50139 [sharedb] Update types for Backend and Connection
  types/sharedb/index.d.ts
  types/sharedb/lib/client.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Author is Owner, Perf: Same, Unreviewed

#50365 Add types for drag-controls
  types/drag-controls/drag-controls-tests.ts
  types/drag-controls/index.d.ts
  types/drag-controls/package.json
  types/drag-controls/tsconfig.json
  types/drag-controls/tslint.json
Labels: Check Config, New Definition

#50367 [@types/struct] Added typing that allows infinite arguments in array
  types/struct/index.d.ts
  types/struct/struct-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50359 [node] Add more "@deprecated" comments
  types/node/crypto.d.ts
  types/node/http.d.ts
  types/node/net.d.ts
  types/node/url.d.ts
  types/node/v11/url.d.ts
  types/node/v12/url.d.ts
  types/node/v13/url.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Untested Change

#50355 update(markdown-it-emoji): v2 changes
  types/markdown-it-emoji/bare.d.ts
  types/markdown-it-emoji/index.d.ts
  types/markdown-it-emoji/light.d.ts
  types/markdown-it-emoji/test/markdown-it-emoji-cjs.ts
  types/markdown-it-emoji/test/markdown-it-emoji-global.ts
  types/markdown-it-emoji/tsconfig.json
  types/markdown-it/index.d.ts
Labels: Edits Owners, Edits multiple packages, Owner Approved, Perf: Worse, Popular package, Self Merge

#50018 [lqip-modern] it should not error when passing only part of `LqipOptions`
  types/lqip-modern/index.d.ts
  types/lqip-modern/lqip-modern-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50166 node-imap: ConnectionOptions instead of TlsOptions for tls.connect(...)
  types/imap/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Unmerged, Untested Change

#50362 Update types for swagger-jsdoc 6.0
  types/swagger-jsdoc/index.d.ts
  types/swagger-jsdoc/swagger-jsdoc-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#49000 update(dom-purify): v2.2
  types/dompurify/index.d.ts
  types/dompurify/test/dompurify-namespace-tests.ts
  types/dompurify/test/dompurify-tests.ts
Labels: Author is Owner, Other Approved, Owner Approved, Perf: Same, Popular package, Self Merge

#50261 update(iban): expose countries dictionary
  types/iban/iban-tests.ts
  types/iban/index.d.ts
Labels: Other Approved, Perf: Same, Self Merge

#50250 [@types/react-draft-wysiwyg]: add missing webDriverTestId prop type
  types/react-draft-wysiwyg/index.d.ts
  types/react-draft-wysiwyg/test/render-with-test-id.tsx
  types/react-draft-wysiwyg/tsconfig.json
Labels: Owner Approved, Perf: Same, Self Merge

#50240 Allow the translations to be self-maintained by language owners
  .github/workflows/CodeOwnersSelfMerge.yml
  docs/CODEOWNERS
Labels: Edits Infrastructure, Unreviewed

#50332 [office-js] [office-js-preview] Update useStandardHeight and useStandardWidth definitions
  types/office-js-preview/index.d.ts
  types/office-js/index.d.ts
Labels: Author is Owner, Edits multiple packages, Owner Approved, Perf: Same, Untested Change, Where is GH Actions?

#49999 [babyparse] Remove types
  types/babyparse/babyparse-tests.ts
  types/babyparse/index.d.ts
  types/babyparse/tsconfig.json
  types/babyparse/tslint.json
Labels: Unreviewed

#50383 fix(mapbox-gl): add missing marker's rotation methods
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#49593 @types/breeze - Added missing breeze typings based on the breeze typings file from breeze-odata4
  types/breeze/breeze-tests.ts
  types/breeze/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#50381 Fix user define promisify definition for line-reader package
  types/line-reader/index.d.ts
  types/line-reader/line-reader-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50378 [argparse]: Expose ArgumentTypeError exception
  types/argparse/argparse-tests.ts
  types/argparse/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#49852 types/big.js: Don't export global 'Big' identifier
  types/big.js/index.d.ts
  types/big.js/test/big.js-global-module-tests.ts
  types/big.js/test/big.js-global-tests.ts
  types/big.js/test/big.js-import-compatibility-tests.ts
  types/big.js/test/big.js-import-default-tests.ts
  types/big.js/test/big.js-module-tests.ts
  types/big.js/tsconfig.json
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50398 K6 0.29
  types/k6/http.d.ts
  types/k6/index.d.ts
  types/k6/net/grpc.d.ts
  types/k6/options.d.ts
  types/k6/test/grpc.ts
  types/k6/test/http.ts
  types/k6/test/options.ts
  types/k6/tsconfig.json
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#50112 fix method name updateLineItems() for shopify-buy >= v1
  types/shopify-buy/index.d.ts
  types/shopify-buy/shopify-buy-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50215 [codemirror] add `configureMouse` to EditorConfiguration
  types/codemirror/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50401 [@types/node-forge] add isIssuer() and issued()
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge

#50363 [@types/plotly.js]: Add missing automargin prop to data
  types/plotly.js/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge, Untested Change

#50397 Remove types for markdown-it-anchor
  notNeededPackages.json
  types/markdown-it-anchor/index.d.ts
  types/markdown-it-anchor/markdown-it-anchor-tests.ts
  types/markdown-it-anchor/tsconfig.json
  types/markdown-it-anchor/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Self Merge

#50415 react-html-email type definitions
  types/react-html-email/index.d.ts
  types/react-html-email/react-html-email-tests.ts
  types/react-html-email/tsconfig.json
  types/react-html-email/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50393 Shippo type definitions
  types/shippo/index.d.ts
  types/shippo/shippo-tests.ts
  types/shippo/tsconfig.json
  types/shippo/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50413 mouse-event-offset type definition
  types/mouse-event-offset/index.d.ts
  types/mouse-event-offset/mouse-event-offset-tests.ts
  types/mouse-event-offset/tsconfig.json
  types/mouse-event-offset/tslint.json
Labels: Check Config, New Definition

#50399 Engine.io handlePreFlightRequest arguments don't match function.
  types/engine.io/engine.io-tests.ts
  types/engine.io/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50395 Add type definition for HasBin
  types/hasbin/hasbin-tests.ts
  types/hasbin/index.d.ts
  types/hasbin/tsconfig.json
  types/hasbin/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50204 [inputmask] Updated typings and JSDoc to match Inputmask v5.0.4
  types/inputmask/index.d.ts
  types/inputmask/test/inputmask-global-tests.ts
  types/inputmask/test/inputmask-jquery-tests.ts
  types/inputmask/test/inputmask-module-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50417 [react-native] Export Touchable as a value
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Critical package, Owner Approved, Perf: Same

#50423 fix(googlemaps): accept mixed LatLng | WeightedLocation array in HeatmapLayer.setData
  types/googlemaps/googlemaps-tests.ts
  types/googlemaps/reference/visualization.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50427 [react-router] Allow numeric and optional router params for generatePath
  types/react-router/index.d.ts
  types/react-router/test/generatePath.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#50165 fixed-data-table-2-fix-column-types: fix Column and ColumnGroup props
  types/fixed-data-table-2/fixed-data-table-2-tests.tsx
  types/fixed-data-table-2/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50035 [oracledb] Upgrade types to 5.1
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
  types/oracledb/v3/index.d.ts
  types/oracledb/v3/oracledb-tests.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#50308 update(page.js): missing `strict` method
  types/page/index.d.ts
  types/page/page-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#50422 add react-snapshot
  types/react-snapshot/index.d.ts
  types/react-snapshot/react-snapshot-tests.tsx
  types/react-snapshot/tsconfig.json
  types/react-snapshot/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#50441 @types/polka - Support instantiated server that exists on Polka API
  types/polka/index.d.ts
  types/polka/polka-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50391 add tmi.js 1.7 features, fix constructor
  types/tmi.js/index.d.ts
Labels: Edits Owners, Maintainer Approved, Other Approved, Perf: Same, Self Merge, Untested Change

#50168 [newrelic] Remove dropped functions from 7.0 release.
  types/newrelic/index.d.ts
  types/newrelic/newrelic-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#50388 [@types/carbon-components-react] Add missing danger button kinds.
  types/carbon-components-react/lib/components/Button/Button.d.ts
Labels: Author is Owner, Maintainer Approved, Other Approved, Perf: Same, Self Merge, Untested Change

#50434 Add types for `unixify`
  types/unixify/index.d.ts
  types/unixify/tsconfig.json
  types/unixify/tslint.json
  types/unixify/unixify-tests.ts
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#50372 [compression-webpack-plugin]: unsub rhys-vdw
  types/compression-webpack-plugin/index.d.ts
  types/compression-webpack-plugin/v2/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Untested Change

#50239 [sharp] specifies format type
  types/sharp/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50287 webpack-manifest-plugin: Fix Options.generate entryPoints
  types/webpack-manifest-plugin/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50371 urijs: Add missing optional arguments to withinString() callback function
  types/urijs/index.d.ts
  types/urijs/test/urijs-nodejs.test.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50377 [@types/jest]: Fix getMockImplementation definition
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Critical package, Edits Owners, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#49863 [@types/numeral] fix numeral.isNumeral() type
  types/numeral/index.d.ts
  types/numeral/numeral-tests.ts
Labels: Maintainer Approved, Other Approved, Perf: Same, Popular package, Self Merge

#50421 [@types/mapbox-gl] Add missing Sky layer
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#49651 [mdarea] Add mdarea package
  types/mdarea/index.d.ts
  types/mdarea/mdarea-tests.ts
  types/mdarea/tsconfig.json
  types/mdarea/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Other Approved, Self Merge

#50163 intercom-web: use generics for better type checking for Intercom
  types/intercom-web/index.d.ts
  types/intercom-web/intercom-web-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50444 [relay-runtime] Add types for RelayModernEnvironment
  types/relay-runtime/lib/store/RelayModernEnvironment.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#49689 add `config/async` types
  types/config/async.d.ts
  types/config/config-tests.ts
  types/config/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge

#50140 [tuya-panel-kit] add docs comment and add TransitionPresets、useTheme
  types/tuya-panel-kit/index.d.ts
  types/tuya-panel-kit/theme.d.ts
  types/tuya-panel-kit/tslint.json
Labels: Author is Owner, Maintainer Approved, Self Merge, Untested Change

#50407 [@types/atom] Add a missing field to the options
  types/atom/autocomplete-plus/index.d.ts
Labels: Owner Approved, Perf: Same, The CI failed, Untested Change

#50451 `unsplash-js`: remove
  notNeededPackages.json
  types/unsplash-js/index.d.ts
  types/unsplash-js/tsconfig.json
  types/unsplash-js/tslint.json
  types/unsplash-js/unsplash-js-tests.ts
Labels: Edits Infrastructure, Owner Approved

#50402 [@types/express-rate-limit] Added signature for request and response to options.max
  types/express-rate-limit/express-rate-limit-tests.ts
  types/express-rate-limit/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50414 UpdateInterface.d.ts
  types/react-world-flags/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#50443 Types for reefjs
  types/reefjs/index.d.ts
  types/reefjs/reefjs-tests.ts
  types/reefjs/tsconfig.json
  types/reefjs/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#50406 Added missing Tab capture API
  types/chrome/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#50191 updates rsocket-core types to the latest 0.0.22 version
  types/rsocket-core/AuthMetadata.d.ts
  types/rsocket-core/CompositeMetadata.d.ts
  types/rsocket-core/RoutingMetadata.d.ts
  types/rsocket-core/WellKnownAuthType.d.ts
  types/rsocket-core/WellKnownMimeType.d.ts
  types/rsocket-core/index.d.ts
  types/rsocket-core/rsocket-core-tests.ts
  types/rsocket-core/tsconfig.json
Labels: Author is Owner, Other Approved, Self Merge

#50466 karma-coverage: Fix tests for TS 4.2 template literals
  types/karma-coverage/karma-coverage-tests.ts
Labels: Owner Approved, Self Merge

#50465 Fix k6 lint error
  types/k6/net/grpc.d.ts
Labels: Untested Change

#50448 CSS to React Native types
  types/css-to-react-native/css-to-react-native-tests.ts
  types/css-to-react-native/index.d.ts
  types/css-to-react-native/tsconfig.json
  types/css-to-react-native/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#50464 jasmine: Fix tests for TS 4.2 template literals
  types/jasmine/jasmine-tests.ts
Labels: Critical package

#50467 linkifyjs: Fix tests for TS 4.2 template literals
  types/linkifyjs/linkifyjs-tests.ts
Labels: Perf: Same

#50430 Add types for 'uzip' package
  types/uzip/index.d.ts
  types/uzip/tsconfig.json
  types/uzip/tslint.json
  types/uzip/uzip-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#50411 codemirror: Added missing options of setBookmark.
  types/codemirror/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#48402 parse5: rework to be strongly typed
  types/parse5-htmlparser2-tree-adapter/index.d.ts
  types/parse5-htmlparser2-tree-adapter/parse5-htmlparser2-tree-adapter-tests.ts
  types/parse5-parser-stream/parse5-parser-stream-tests.ts
  types/parse5-plain-text-conversion-stream/parse5-plain-text-conversion-stream-tests.ts
  types/parse5-serializer-stream/parse5-serializer-stream-tests.ts
  types/parse5/index.d.ts
  types/parse5/lib/tree-adapters/default.d.ts
  types/parse5/parse5-tests.ts
  types/xmlserializer/index.d.ts
Labels: Edits Owners, Edits multiple packages, Maintainer Approved, Perf: Same, Popular package, Self Merge

#50462 ember: Fix tests for TS 4.2 template literals
  types/ember/test/private/computed-tests.ts
  types/ember/test/utils.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50460 Add prosemirror-changeset type definitions
  types/prosemirror-changeset/index.d.ts
  types/prosemirror-changeset/prosemirror-changeset-tests.ts
  types/prosemirror-changeset/tsconfig.json
  types/prosemirror-changeset/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#50473 [skmeans] Update signature of Data.centroids
  types/skmeans/index.d.ts
  types/skmeans/skmeans-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50478 Add level to the hooks logMethod signature in pino options
  types/pino/index.d.ts
  types/pino/pino-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50379 jws support isValid
  types/jws/index.d.ts
  types/jws/jws-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50437 Bootstrap 5 + Popperjs 2
  types/bootstrap/bootstrap-tests.ts
  types/bootstrap/js/dist/dropdown.d.ts
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
  types/bootstrap/package.json
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50461 [forms] Fix incorrect types + have form definition be reflected in what bound data is available
  types/forms/forms-tests.ts
  types/forms/index.d.ts
Labels: Edits Owners, Other Approved, Perf: Worse, Self Merge

#50435 add makeText function and dashes property to two.js
  types/two.js/index.d.ts
Labels: Edits Owners, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#50456 Add types for is-valid-domain package
  types/is-valid-domain/index.d.ts
  types/is-valid-domain/is-valid-domain-tests.ts
  types/is-valid-domain/tsconfig.json
  types/is-valid-domain/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50452 [react-native] Fix Declaration for BodyInit_ to allow Local File Upload
  types/react-native/globals.d.ts
  types/react-native/test/globals.tsx
Labels: Author is Owner, Critical package, Perf: Same

#50469 meteor: Fix tests for TS 4.2 template literals
  types/meteor/test/meteor-tests-module-only.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50479 [prosemirror-view] Optional `side` param for `domAtPos`
  types/prosemirror-view/index.d.ts
  types/prosemirror-view/prosemirror-view-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50470 luxon: Fix tests for stricter DOM types in TS 4.2
  types/luxon/luxon-tests.ts
Labels: Perf: Same, Popular package

#50458 [next-auth] Adds optional `domain` to `CookieOptions`.
  types/next-auth/index.d.ts
  types/next-auth/next-auth-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50476 Update slice-source's use of ReadableStreamReader
  types/slice-source/index.d.ts
Labels: Owner Approved, Perf: Same, Untested Change

#50428 [gulp] add TaskFunctionCallback as an alias to Undertaker.TaskCallback
  types/gulp/index.d.ts
  types/gulp/test/index.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50447 [react-router] Fix regression in generatePath with non-literal strings
  types/react-router/index.d.ts
  types/react-router/test/generatePath.ts
Labels: Critical package, Owner Approved, Perf: Same

#48799 CodeMirror: Make argument to showHint optional
  types/codemirror/addon/hint/show-hint.d.ts
  types/codemirror/test/addon/hint/show-hint.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50471 feat: upgrade carbon__pictograms-react to v11.1
  types/carbon__pictograms-react/OTHER_FILES.txt
  types/carbon__pictograms-react/carbon__pictograms-react-tests.tsx
  types/carbon__pictograms-react/es/baby--bottle/index.d.ts
  types/carbon__pictograms-react/es/cloud-pak--family/index.d.ts
  types/carbon__pictograms-react/es/cloud-pak--for-applications/index.d.ts
  types/carbon__pictograms-react/es/cloud-pak--for-data/index.d.ts
  types/carbon__pictograms-react/es/cloud-pak--for-integration/index.d.ts
  types/carbon__pictograms-react/es/cloud-pak--for-multicloud-management/index.d.ts
  types/carbon__pictograms-react/es/cloud-pak--for-security/index.d.ts
  types/carbon__pictograms-react/es/cloud-pak--system/index.d.ts
  types/carbon__pictograms-react/es/condition--builder/index.d.ts
  types/carbon__pictograms-react/es/doctor-patient/index.d.ts
  types/carbon__pictograms-react/es/dropper/index.d.ts
  types/carbon__pictograms-react/es/filter--variable/index.d.ts
  types/carbon__pictograms-react/es/hpi/index.d.ts
  types/carbon__pictograms-react/es/index.d.ts
  types/carbon__pictograms-react/es/nyc--chrysler-building/index.d.ts
  types/carbon__pictograms-react/es/nyc--world-trade-center/index.d.ts
  types/carbon__pictograms-react/es/prague--dancing-house--01/index.d.ts
  types/carbon__pictograms-react/es/prague--dancing-house--02/index.d.ts
  types/carbon__pictograms-react/es/prescription/index.d.ts
  types/carbon__pictograms-react/es/random--samples/index.d.ts
  types/carbon__pictograms-react/es/rock-on/index.d.ts
  types/carbon__pictograms-react/es/select--range/index.d.ts
  types/carbon__pictograms-react/es/social--work--01/index.d.ts
  types/carbon__pictograms-react/es/social--work--02/index.d.ts
  types/carbon__pictograms-react/es/telemedicine--mobile/index.d.ts
  types/carbon__pictograms-react/es/telemedicine/index.d.ts
  types/carbon__pictograms-react/index.d.ts
  types/carbon__pictograms-react/lib/baby--bottle/index.d.ts
  types/carbon__pictograms-react/lib/cloud-pak--family/index.d.ts
  types/carbon__pictograms-react/lib/cloud-pak--for-applications/index.d.ts
  types/carbon__pictograms-react/lib/cloud-pak--for-data/index.d.ts
  types/carbon__pictograms-react/lib/cloud-pak--for-integration/index.d.ts
  types/carbon__pictograms-react/lib/cloud-pak--for-multicloud-management/index.d.ts
  types/carbon__pictograms-react/lib/cloud-pak--for-security/index.d.ts
  types/carbon__pictograms-react/lib/cloud-pak--system/index.d.ts
  types/carbon__pictograms-react/lib/condition--builder/index.d.ts
  types/carbon__pictograms-react/lib/doctor-patient/index.d.ts
  types/carbon__pictograms-react/lib/dropper/index.d.ts
  types/carbon__pictograms-react/lib/filter--variable/index.d.ts
  types/carbon__pictograms-react/lib/hpi/index.d.ts
  types/carbon__pictograms-react/lib/index.d.ts
  types/carbon__pictograms-react/lib/nyc--chrysler-building/index.d.ts
  types/carbon__pictograms-react/lib/nyc--world-trade-center/index.d.ts
  types/carbon__pictograms-react/lib/prague--dancing-house--01/index.d.ts
  types/carbon__pictograms-react/lib/prague--dancing-house--02/index.d.ts
  types/carbon__pictograms-react/lib/prescription/index.d.ts
  types/carbon__pictograms-react/lib/random--samples/index.d.ts
  types/carbon__pictograms-react/lib/rock-on/index.d.ts
  types/carbon__pictograms-react/lib/select--range/index.d.ts
  types/carbon__pictograms-react/lib/social--work--01/index.d.ts
  types/carbon__pictograms-react/lib/social--work--02/index.d.ts
  types/carbon__pictograms-react/lib/telemedicine--mobile/index.d.ts
  types/carbon__pictograms-react/lib/telemedicine/index.d.ts
Labels: Author is Owner, Check Config, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#50475 Fix serverless Service.functions
  types/serverless/classes/Service.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#50484 Update lifeomic/axios-fetch for 1.5
  types/lifeomic__axios-fetch/index.d.ts
  types/lifeomic__axios-fetch/package.json
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#50491 [cached@5.0.2] first definition types
  types/cached/cached-tests.ts
  types/cached/index.d.ts
  types/cached/tsconfig.json
  types/cached/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#50490 [parcel-bundler]: update to new name / username
  types/parcel-bundler/index.d.ts
Labels: Edits Owners, Perf: Same, Untested Change

#50486 Adjust types for service creation
  types/dockerode/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Untested Change

#50489 Make all props in popperConfig optional
  types/bootstrap/bootstrap-tests.ts
  types/bootstrap/js/dist/dropdown.d.ts
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50420 [types/factory_girl] Make `factory` can be used named import / Add override definitions for `seq` and `sequence`
  types/factory-girl/factory-girl-tests.ts
  types/factory-girl/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#50498 Change type for callback inside dnsLookup [@types/ioredis]
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#50254 Parcel-Bundler: Add missing `autoInstall` property to ParcelOptions
  types/parcel-bundler/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge, Untested Change

#50492 Make resize-observer types mergeable
  types/resize-observer-browser/index.d.ts
  types/resize-observer-browser/resize-observer-browser-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50344 [minio] Add missing property pathStyle
  types/minio/index.d.ts
  types/minio/minio-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#50300 fix(promise-the-world): resolve should accept no parameters
  types/promise-the-world/defer.d.ts
  types/promise-the-world/promise-the-world-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50336 [i18n-js] Add `scope` option to `toHumanSize`. Improve `defaultValue` type.
  types/i18n-js/i18n-js-tests.ts
  types/i18n-js/index.d.ts
Labels: Other Approved, Perf: Same, Self Merge

#50324 [forge-viewer] added Edit2D extension
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Other Approved, Perf: Same, Self Merge

#50384 [forge-viewer] - update for version 7.34
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Author is Owner, Other Approved, Perf: Same, Self Merge

#50510 Use camelCase for inflight method
  types/mongodb-queue/index.d.ts
  types/mongodb-queue/mongodb-queue-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#50503 MJML-React loosen children type
  types/mjml-react/index.d.ts
  types/mjml-react/mjml-react-tests.tsx
Labels: Edits Owners, Owner Approved, Perf: Worse, Self Merge

#50504 update(japan-postal-code): minor corrections
  types/japan-postal-code/index.d.ts
  types/japan-postal-code/japan-postal-code-tests.ts
  types/japan-postal-code/tsconfig.json
Labels: Owner Approved, Perf: Better, Self Merge

#50507 Add optional options param to isBase64
  types/validator/index.d.ts
  types/validator/validator-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#50501 [cached] fixed bad "any" type and fixed missing optional param
  types/cached/cached-tests.ts
  types/cached/index.d.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#50309 update(omelette): Added on('completion') types
  types/omelette/index.d.ts
  types/omelette/omelette-tests.ts
Labels: Other Approved, Perf: Same, Self Merge

#50497 vhtml: Enable strict type checks for JSX children
  types/vhtml/index.d.ts
  types/vhtml/test/jsx-tests.tsx
  types/vhtml/test/vhtml-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge
