Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-04, with the labels that each got.

#52122 [mousetrap] add pause and unpause methods definitions
  types/mousetrap/index.d.ts
  types/mousetrap/test/index.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52066 Add react-big-calendar backgroundEvents
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge

#51994 Update of the OutputInfo interface for the sharp module
  types/sharp/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52128 Update to Forge API library version 0.8 (0.8.5)
  types/forge-apis/forge-apis-tests.ts
  types/forge-apis/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#52106 Defs for arconnect
  types/arconnect/arconnect-tests.ts
  types/arconnect/index.d.ts
  types/arconnect/package.json
  types/arconnect/tsconfig.json
  types/arconnect/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#51716 fix(git-branch-is): correct definition
  types/git-branch-is/git-branch-is-tests.ts
  types/git-branch-is/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Better, Self Merge

#52120 Correct library misnaming: highlight.js
  notNeededPackages.json
  types/highlight.js/highlight.js-tests.ts
  types/highlight.js/index.d.ts
  types/highlight.js/package.json
  types/highlight.js/tsconfig.json
  types/highlight.js/tslint.json
Labels: Check Config, Edits Infrastructure, New Definition, Popular package

#51603 [object-hash] refactor, update version, remove all rules from tslint
  types/object-hash/index.d.ts
  types/object-hash/object-hash-tests.ts
  types/object-hash/tslint.json
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge

#52089 [fnando__sparkline] Add support to datapoint type
  types/fnando__sparkline/fnando__sparkline-tests.ts
  types/fnando__sparkline/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52129 Update gestalt for 20.3
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52123 [rails__actioncable] Support for enabled property of logger
  types/rails__actioncable/index.d.ts
  types/rails__actioncable/rails__actioncable-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52133 chore(serverless): add myself as owner
  types/serverless/index.d.ts
Labels: Edits Owners, Other Approved, Perf: Same, Untested Change

#52144 [react-relay] Export QueryRendererProps interface
  types/react-relay/legacy.d.ts
  types/react-relay/test/react-relay-tests.tsx
Labels: Owner Approved, Popular package, Self Merge

#51484 ws: use numeric literals for readyState types
  types/ws/index.d.ts
  types/ws/tsconfig.json
  types/ws/ws-tests.ts
Labels: Critical package, Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#52147 [rails__actioncable] Fix subscriptions.create params
  types/rails__actioncable/index.d.ts
  types/rails__actioncable/rails__actioncable-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52027 Update react-notifications-component with latest type changes up to v3.1
  types/react-notifications-component/index.d.ts
  types/react-notifications-component/react-notifications-component-tests.tsx
Labels: Edits Owners, Other Approved, Perf: Same, Self Merge

#52140 Restore highlightjs v9 types
  types/highlightjs/index.d.ts
  types/highlightjs/package.json
  types/highlightjs/tslint.json
Labels: Check Config, Edits Owners, Perf: Same, Untested Change

#52153 fix degit exports
  types/degit/degit-tests.ts
  types/degit/index.d.ts
Labels: Perf: Same

#52110 Add json-api-serializer types
  types/json-api-serializer/index.d.ts
  types/json-api-serializer/json-api-serializer-tests.ts
  types/json-api-serializer/tsconfig.json
  types/json-api-serializer/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52039 Add text method to Blob in node-fetch
  types/node-fetch/index.d.ts
  types/node-fetch/node-fetch-tests.ts
Labels: Critical package, Owner Approved, Perf: Same

#52072 [JSForce] findOne can return null, closes #49881
  types/jsforce/salesforce-object.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52088 Fix name typo
  types/react-cytoscapejs/index.d.ts
Labels: Author is Owner, Perf: Same, Untested Change

#52073 [4.0.0] React-Select: update NonceProvider's Props types
  types/react-select/src/NonceProvider.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52070 [chai] add missing aliases for least/most, and test aliases for above/below
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#52024 Add type definitions for ember__destroyable
  types/ember/index.d.ts
  types/ember__destroyable/index.d.ts
  types/ember__destroyable/test/lib/assert.ts
  types/ember__destroyable/test/main.ts
  types/ember__destroyable/tsconfig.json
  types/ember__destroyable/tslint.json
Labels: Check Config, Edits multiple packages, Maintainer Approved, New Definition, Owner Approved, Perf: Same, Popular package, Self Merge

#52097 Add missing declarations for {rm, rmdir} in fs-extra
  types/fs-extra/fs-extra-tests.ts
  types/fs-extra/index.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#52151 Adding types for wawoff2
  types/wawoff2/index.d.ts
  types/wawoff2/tsconfig.json
  types/wawoff2/tslint.json
  types/wawoff2/wawoff2-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#52026 [koa] add expectations in tests for typed response body
  types/koa/test/typed-response-body-tests.ts
  types/koa/tsconfig.json
Labels: Author is Owner, Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#52059 [fabric] add charWidthsCache
  types/fabric/fabric-impl.d.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51746 update(rollup-plugin-url): v3 and minor fix
  types/rollup-plugin-url/index.d.ts
  types/rollup-plugin-url/rollup-plugin-url-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#51745 update(mv): minor corrections
  types/mv/index.d.ts
  types/mv/mv-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#52115 Add overflowX and overflowY to styled-system
  types/styled-system/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51731 [@types/chrome] Define chrome.tabGroups API available in Chrome 89
  types/chrome/index.d.ts
  types/chrome/test/index.ts
  types/chrome/tslint.json
Labels: Check Config, Edits Owners, Maintainer Approved, Other Approved, Perf: Same, Popular package, Self Merge

#52126 Add types for dynamodb-lock-client
  types/dynamodb-lock-client/dynamodb-lock-client-tests.ts
  types/dynamodb-lock-client/index.d.ts
  types/dynamodb-lock-client/package.json
  types/dynamodb-lock-client/tsconfig.json
  types/dynamodb-lock-client/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#51441 relay-runtime: Types for ConnectionHandler.getConnectionID
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/handlers/connection/ConnectionHandler.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52138 [xrm] Add new addOnPostSave method
  types/xrm/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#51651 [echarts] Add appendToBody, className and order property to tooltip
  types/echarts/options/tooltip.d.ts
Labels: Maintainer Approved, Other Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51307 Definitions for node-siege
  types/node-siege/index.d.ts
  types/node-siege/node-siege-tests.ts
  types/node-siege/tsconfig.json
  types/node-siege/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge, Unmerged

#51540 async: fix types for async.retry
  types/async/index.d.ts
  types/async/test/index.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52146 [luxon] add LocalZone.instance
  types/luxon/index.d.ts
  types/luxon/luxon-tests.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge

#51834 vhtml: Move JSX from global namespace to vhtml.JSX
  types/vhtml/index.d.ts
  types/vhtml/test/jsx-tests.tsx
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#52035 [adm-zip] fixes for error cases, add EntryHeader interface
  types/adm-zip/adm-zip-tests.ts
  types/adm-zip/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#51948 [temp] temp's async functions return a Promise
  types/temp/index.d.ts
  types/temp/temp-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#52164 fix(floreal): correct definition
  types/floreal/date.d.ts
  types/floreal/floreal-tests.ts
  types/floreal/index.d.ts
  types/floreal/tsconfig.json
Labels: Owner Approved, Perf: Same, Self Merge

#52180 fix(email-templates): remove direct 'dom' dependency
  types/email-templates/email-templates-tests.ts
  types/email-templates/index.d.ts
  types/email-templates/tsconfig.json
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52087 [mongodb] fix typing of _id fields in arrays
  types/mongodb/index.d.ts
  types/mongodb/test/collection/updateX.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Perf: Same, Self Merge

#52176 [merge-images] Update types to 1.2
  types/merge-images/index.d.ts
  types/merge-images/merge-images-tests.ts
Labels: Author is Owner, Other Approved, Owner Approved, Perf: Same, Self Merge

#51673 `react-autosuggest`: `InputProps`: strict function types
  types/react-autosuggest/index.d.ts
  types/react-autosuggest/react-autosuggest-tests.tsx
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#52149 [generate-ctrl-c-event] add definitions
  types/generate-ctrl-c-event/generate-ctrl-c-event-tests.ts
  types/generate-ctrl-c-event/index.d.ts
  types/generate-ctrl-c-event/tsconfig.json
  types/generate-ctrl-c-event/tslint.json
Labels: New Definition, Other Approved

#52184 Add `architect/functions`.http.helpers object which was missing
  types/architect__functions/http.d.ts
  types/architect__functions/test/http-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52074 [fluent-ffmpeg] add rotation property to streams
  types/fluent-ffmpeg/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#52191 Microsoft Graph - Upgrade to 1.35
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52192 update-fetchMessages
  types/pubnub/index.d.ts
  types/pubnub/pubnub-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52197 update(minizlib): minor changes
  types/minizlib/index.d.ts
  types/minizlib/minizlib-tests.ts
  types/minizlib/tsconfig.json
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52131 update type definitions for sharp 0.28.1
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#52189 remove hls.js
  notNeededPackages.json
  types/hls.js/OTHER_FILES.txt
  types/hls.js/dist/hls.light.d.ts
  types/hls.js/hls.js-tests.ts
  types/hls.js/index.d.ts
  types/hls.js/tsconfig.json
  types/hls.js/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Owner Approved, Popular package, Self Merge

#52172 nodegit: Tag.listMatch() should receive 2 arguments
  types/nodegit/index.d.ts
  types/nodegit/tag.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#52213 [regenerate] Add type definitions
  types/regenerate/index.d.ts
  types/regenerate/test/regenerate.cjs.test.ts
  types/regenerate/test/regenerate.umd.test.ts
  types/regenerate/tsconfig.json
  types/regenerate/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#51864 Update rpio declarations to 2.4
  types/rpio/index.d.ts
  types/rpio/rpio-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#52210 [yeoman-test] update to 5.0
  types/yeoman-test/index.d.ts
  types/yeoman-test/yeoman-test-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52143 Add types for react-keyboard-event-handler
  types/react-keyboard-event-handler/index.d.ts
  types/react-keyboard-event-handler/react-keyboard-event-handler-tests.tsx
  types/react-keyboard-event-handler/tsconfig.json
  types/react-keyboard-event-handler/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#52181 delete(hash-it): remove package
  notNeededPackages.json
  types/hash-it/hash-it-tests.ts
  types/hash-it/index.d.ts
  types/hash-it/tsconfig.json
  types/hash-it/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Owner Approved, Self Merge

#51988 update(probe-image-size): v7 updates
  types/probe-image-size/index.d.ts
  types/probe-image-size/probe-image-size-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52171 Adds types for selectn.js by Wil Moore III
  types/selectn/index.d.ts
  types/selectn/selectn-tests.ts
  types/selectn/tsconfig.json
  types/selectn/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#51768 Adding missing property definition (formatInOriginalFormat in google-libphonenumber)
  types/google-libphonenumber/google-libphonenumber-tests.ts
  types/google-libphonenumber/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#52119 [underscore] added 'get' to the definition.
  types/underscore/index.d.ts
  types/underscore/underscore-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52182 feat(eslint-plugin-markdown): Add types
  types/eslint-plugin-markdown/eslint-plugin-markdown-tests.ts
  types/eslint-plugin-markdown/index.d.ts
  types/eslint-plugin-markdown/tsconfig.json
  types/eslint-plugin-markdown/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52219 Remove as author from aws-lambda type definitions
  types/aws-lambda/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52208 [ioredis] Added noDelay, stringNumbers, maxScriptsCachingTime to RedisOptions per ioredis documentation.
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52177 [just-merge] Add new types for just-merge
  types/just-merge/index.d.ts
  types/just-merge/just-merge-tests.ts
  types/just-merge/tsconfig.json
  types/just-merge/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#52188 [hyphen]: Remove outdated information from comment
  types/hyphen/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge, Untested Change

#52166 [google-apps-script] Update CardService class according API Reference
  types/google-apps-script/google-apps-script.card-service.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#51896 delete(algoliasearch): remove types
  notNeededPackages.json
  types/algoliasearch-helper/algoliasearch-helper-tests.ts
  types/algoliasearch-helper/index.d.ts
  types/algoliasearch-helper/tsconfig.json
  types/algoliasearch-helper/tslint.json
  types/algoliasearch/algoliasearch-tests.ts
  types/algoliasearch/index.d.ts
  types/algoliasearch/lite/index.d.ts
  types/algoliasearch/tsconfig.json
  types/algoliasearch/tslint.json
  types/react-instantsearch-core/index.d.ts
  types/react-instantsearch-core/package.json
Labels: Edits Infrastructure, Edits multiple packages, Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge

#52178 opein-provider: Fix typo in InteractiveResult
  types/oidc-provider/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Better, Self Merge, Untested Change

#52111 [aws-lambda] Add Amazaon Cognito Custom Email Sender Trigger
  types/aws-lambda/test/cognito-tests.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/custom-email-sender.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52233 change my github name in definitions
  types/chart.js/index.d.ts
  types/js-roman-numerals/index.d.ts
  types/topojson-client/index.d.ts
  types/topojson-server/index.d.ts
  types/topojson-simplify/index.d.ts
  types/topojson/index.d.ts
Labels: Edits Owners, Edits multiple packages, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#51824 [pdfjs-dist] Add `workerPort` global option
  types/pdfjs-dist/index.d.ts
  types/pdfjs-dist/pdfjs-dist-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#52156 Update supported arguments for feature method in topojson-client
  types/topojson-client/index.d.ts
  types/topojson-client/topojson-client-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#51832 clean-css: Accept RawSourceMap as an input source map
  types/clean-css/clean-css-tests.ts
  types/clean-css/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#52209 [@wordpress/core-data] Move Schema from api-fetch
  types/wordpress__api-fetch/index.d.ts
  types/wordpress__api-fetch/wordpress__api-fetch-tests.ts
  types/wordpress__core-data/actions.d.ts
  types/wordpress__core-data/index.d.ts
  types/wordpress__core-data/schema.d.ts
  types/wordpress__core-data/selectors.d.ts
  types/wordpress__core-data/wordpress__core-data-tests.ts
  types/wordpress__editor/components/autocompleters.d.ts
  types/wordpress__editor/components/post-taxonomies/index.d.ts
  types/wordpress__editor/store/selectors.d.ts
  types/wordpress__media-utils/utils/upload-media.d.ts
Labels: Edits multiple packages, Owner Approved, Perf: Worse, Self Merge

#51879 update(csurf): fix minor problems
  types/csurf/csurf-tests.ts
  types/csurf/index.d.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Self Merge

#51882 update(7zip-min): version 1.3 changes
  types/7zip-min/7zip-min-tests.ts
  types/7zip-min/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#52227 Add type declarations for `ultron`
  types/ultron/index.d.ts
  types/ultron/tsconfig.json
  types/ultron/tslint.json
  types/ultron/ultron-tests.ts
Labels: Maintainer Approved, New Definition, Self Merge

#52247 Add types for the steelseries package
  types/steelseries/index.d.ts
  types/steelseries/steelseries-tests.ts
  types/steelseries/tsconfig.json
  types/steelseries/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52207 director: Create type definitions
  types/director/director-tests.ts
  types/director/index.d.ts
  types/director/tsconfig.json
  types/director/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52226 Match onabort in AbortSignal with DOM definition
  types/node-fetch/externals.d.ts
  types/node-fetch/node-fetch-tests.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#52222 [gapi.people] Fix: `SearchContactsResult` should be optional
  types/gapi.people/gapi.people-tests.ts
  types/gapi.people/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51786 [@types/carbon-components-react] Update types to match 7.31.x
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/index.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenu.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenuDivider.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenuGroup.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenuItem.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenuOption.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenuRadioGroup.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenuRadioGroupOptions.d.ts
  types/carbon-components-react/lib/components/ContextMenu/ContextMenuSelectableItem.d.ts
  types/carbon-components-react/lib/components/ContextMenu/index.d.ts
  types/carbon-components-react/lib/components/ContextMenu/useContextMenu.d.ts
  types/carbon-components-react/lib/components/DataTableSkeleton/DataTableSkeleton.d.ts
  types/carbon-components-react/lib/components/Heading/index.d.ts
  types/carbon-components-react/lib/components/MultiSelect/MultiSelect.d.ts
  types/carbon-components-react/lib/components/Popover/index.d.ts
  types/carbon-components-react/lib/components/Select/Select.d.ts
  types/carbon-components-react/lib/components/StructuredList/StructuredList.d.ts
  types/carbon-components-react/lib/components/UIShell/SideNav.d.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Self Merge

#52174 [fbdl-core]: Add types
  types/fbdl-core/fbdl-core-tests.ts
  types/fbdl-core/index.d.ts
  types/fbdl-core/tsconfig.json
  types/fbdl-core/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52017 Declare possible null attribute values to support strict null checking
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51885 update(alex): version bump and minor changes
  types/alex/alex-tests.ts
  types/alex/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#52243 update(zipcodes): missing exports added
  types/zipcodes/index.d.ts
  types/zipcodes/zipcodes-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#51853 update(supports-color): version 8
  types/supports-color/index.d.ts
  types/supports-color/supports-color-tests.ts
  types/supports-color/v3/index.d.ts
  types/supports-color/v3/supports-color-tests.ts
  types/supports-color/v3/tsconfig.json
  types/supports-color/v3/tslint.json
Labels: Author is Owner, Maintainer Approved, Perf: Worse, Popular package, Self Merge

#52229 [faker]: Sync up arg types for system subobject
  types/faker/faker-tests.ts
  types/faker/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52240 Nullable belongs to
  types/ember-data/index.d.ts
  types/ember-data/test/belongs-to.ts
  types/ember-data/test/promises.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52241 Nullable belongs to tests
  types/ember-data__model/test/model.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52198 Added types definition for "level" npm package
  types/level/index.d.ts
  types/level/level-tests.ts
  types/level/tsconfig.json
  types/level/tslint.json
  types/levelup/index.d.ts
Labels: Edits multiple packages, Maintainer Approved, New Definition, Other Approved, Perf: Better, Self Merge

#52244 [ramda] add missing overload for sortBy
  types/ramda/index.d.ts
  types/ramda/test/sortBy-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52223 [react-text-mask] Change param config in conformToMask to optional
  types/react-text-mask/index.d.ts
  types/react-text-mask/react-text-mask-tests.ts
  types/react-text-mask/tsconfig.json
Labels: Owner Approved, Popular package, Self Merge

#51897 update(system-task): correct constructor and other changes
  types/system-task/index.d.ts
  types/system-task/system-task-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#52186 defs: post-message-stream
  types/post-message-stream/index.d.ts
  types/post-message-stream/post-message-stream-tests.ts
  types/post-message-stream/tsconfig.json
  types/post-message-stream/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52259 [@types/loadable__server] code style fix
  types/loadable__server/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52249 Add pino-pretty
  types/pino-pretty/index.d.ts
  types/pino-pretty/pino-pretty-tests.ts
  types/pino-pretty/tsconfig.json
  types/pino-pretty/tslint.json
  types/pino/index.d.ts
  types/pino/pino-tests.ts
  types/pino/v3/index.d.ts
  types/pino/v3/pino-tests.ts
Labels: Edits multiple packages, Maintainer Approved, New Definition, Perf: Same, Popular package, Self Merge

#52251 fix(file-saver): disableAutoBOM is true by default
  types/file-saver/index.d.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52235 Updates types for Recurly.js v4.16.1
  types/recurly__recurly-js/index.d.ts
  types/recurly__recurly-js/lib/apple-pay.d.ts
  types/recurly__recurly-js/lib/configure.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#52276 Add new exemptions to npm-naming lint rule
  types/babel__standalone/tslint.json
  types/contentstack/tslint.json
  types/holderjs/tslint.json
  types/pollyjs__adapter-xhr/tslint.json
  types/react-responsive/tslint.json
  types/react-sparklines/tslint.json
  types/sql.js/tslint.json
Labels: Check Config, Edits multiple packages, Owner Approved, Popular package

#52260 [node-temperature-converter] Add types
  types/node-temperature-converter/index.d.ts
  types/node-temperature-converter/node-temperature-converter-tests.ts
  types/node-temperature-converter/tsconfig.json
  types/node-temperature-converter/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#52183 [paradisebotsapi.js] Add types
  types/paradisebotsapi.js/index.d.ts
  types/paradisebotsapi.js/paradisebotsapi.js-tests.ts
  types/paradisebotsapi.js/tsconfig.json
  types/paradisebotsapi.js/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#52232 Added encodingMode in the Luaparser options interface
  types/luaparse/index.d.ts
  types/luaparse/luaparse-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52257 [@types/intro.js] Add missing fields to intro.js type
  types/intro.js/index.d.ts
Labels: Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#52261 [@types/parse] Add Parse Cloud Validators
  types/parse/index.d.ts
  types/parse/parse-tests.ts
  types/parse/ts3.6/index.d.ts
  types/parse/ts4.0/index.d.ts
Labels: Other Approved, Owner Approved, Perf: Same, Self Merge

#52236 [@types/bl] update bl types to v5
  types/bl/BufferList.d.ts
  types/bl/bl-tests.ts
  types/bl/index.d.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Popular package, Self Merge

#52137 [google.visualization] Update chart selection typings
  types/google.visualization/google.visualization-tests.ts
  types/google.visualization/index.d.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52292 [d3-chord] Add ribbonArrow()
  types/d3-chord/d3-chord-tests.ts
  types/d3-chord/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52256 scrivito: Update to Scrivito 1.21
  types/scrivito/index.d.ts
Labels: Edits Owners, Maintainer Approved, Owner Approved, Perf: Same, Self Merge, Untested Change

#52285 [hapi__hapi] Describe response.charset() overload
  types/hapi__hapi/index.d.ts
  types/hapi__hapi/test/response/response.ts
Labels: Other Approved, Owner Approved, Perf: Worse, Popular package, Self Merge

#52218 update(resize-img): v2.0
  types/resize-img/index.d.ts
  types/resize-img/resize-img-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#52288 Fix typo in bcrypt genSalt documentation
  types/bcrypt/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52275 [@types/eslint] Add 12 and 2021 to ParserOptions's ecmaVersion
  types/eslint/eslint-tests.ts
  types/eslint/helpers.d.ts
  types/eslint/index.d.ts
  types/eslint/rules/best-practices.d.ts
  types/eslint/rules/deprecated.d.ts
  types/eslint/rules/ecmascript-6.d.ts
  types/eslint/rules/index.d.ts
  types/eslint/rules/node-commonjs.d.ts
  types/eslint/rules/possible-errors.d.ts
  types/eslint/rules/strict-mode.d.ts
  types/eslint/rules/stylistic-issues.d.ts
  types/eslint/rules/variables.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Better, Self Merge

#52301 [serverless] support package.patterns
  types/serverless/index.d.ts
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Owner Approved, Self Merge

#51904 [coinbase] Adding pagination and timestamp params
  types/coinbase/coinbase-tests.ts
  types/coinbase/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#52272 add(android-versions): new definition
  types/android-versions/android-versions-tests.ts
  types/android-versions/index.d.ts
  types/android-versions/tsconfig.json
  types/android-versions/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52271 Add types for prismjs/components/
  types/prismjs/OTHER_FILES.txt
  types/prismjs/components.d.ts
  types/prismjs/components/index.d.ts
  types/prismjs/prismjs-tests.ts
Labels: Check Config, Maintainer Approved, Owner Approved, Perf: Same, Popular package, Self Merge

#52296 add(android-device-list): new definition
  types/android-device-list/android-device-list-tests.ts
  types/android-device-list/index.d.ts
  types/android-device-list/tsconfig.json
  types/android-device-list/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52286 [karma] Add/update multiple types
  types/karma/index.d.ts
  types/karma/karma-tests.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#52291 [@wordpress/hooks] Remove package
  notNeededPackages.json
  types/wordpress__hooks/index.d.ts
  types/wordpress__hooks/tsconfig.json
  types/wordpress__hooks/tslint.json
  types/wordpress__hooks/wordpress__hooks-tests.ts
Labels: Edits Infrastructure, Maintainer Approved, Owner Approved, Self Merge

#52306 fix(react-helmet): introduce state export for `peek`
  types/react-helmet/index.d.ts
  types/react-helmet/react-helmet-tests.tsx
  types/react-helmet/tslint.json
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#52103 update(japanese-holidays): add methods
  types/japanese-holidays/index.d.ts
  types/japanese-holidays/japanese-holidays-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#52107 Upgrade @carbon/elements to version 10.31
  types/carbon__elements/carbon__elements-tests.ts
  types/carbon__elements/index.d.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#52054 Fix secp256k1 to follow the state-of-the-art declarations.
  types/secp256k1/index.d.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52269 [fs-extra] Make rm types compatible with @types/node@12.x
  types/fs-extra/fs-extra-tests.ts
  types/fs-extra/index.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Perf: Same, Self Merge

#52302 [invity_api] Update to version 1.0.3
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#52308 Update gestalt to 21.0
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52326 [three] minor updates - Matrix4 / OrbitControls / TrackballControls
  types/three/examples/jsm/controls/OrbitControls.d.ts
  types/three/examples/jsm/controls/TrackballControls.d.ts
  types/three/src/math/Matrix4.d.ts
  types/three/test/lights/lights-pointlights2.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Popular package, Self Merge

#52325 sendmail: Add 3 options into MailInput
  types/sendmail/index.d.ts
  types/sendmail/sendmail-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52279 [forge-viewer] update for version 7.40
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
  types/forge-viewer/three/three.d.ts
Labels: Author is Owner, Owner Approved, Perf: Same, Self Merge

#52258 [@types/meteor] Add modern-browsers package
  types/meteor/index.d.ts
  types/meteor/modern-browsers.d.ts
  types/meteor/test/meteor-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#52239 @type for leaflet-offline
  types/leaflet-offline/index.d.ts
  types/leaflet-offline/leaflet-offline-tests.ts
  types/leaflet-offline/tsconfig.json
  types/leaflet-offline/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52215 Add a `type` member to the `Def` type
  types/marked/index.d.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge, Untested Change

#52329 fix(picomatch): Better types when returnState equals true
  types/picomatch/index.d.ts
  types/picomatch/picomatch-tests.ts
Labels: Edits Owners, Maintainer Approved, Other Approved, Perf: Same, Popular package, Self Merge

#52284 [nodemailer-express-handlebars] add definitions
  types/nodemailer-express-handlebars/index.d.ts
  types/nodemailer-express-handlebars/nodemailer-express-handlebars-tests.ts
  types/nodemailer-express-handlebars/tsconfig.json
  types/nodemailer-express-handlebars/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#51972 fix(rdf-loaders-registry): wrong return type
  types/rdf-loaders-registry/index.d.ts
  types/rdf-loaders-registry/rdf-loaders-registry-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#52145 [oidc-provider] 7.2 update
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Author is Owner, No Other Owners, Other Approved, Perf: Same, Self Merge

#52319 Update tap definitions from v14.10 to v15.0
  types/tap/index.d.ts
  types/tap/tap-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#52339 [jsforce]: add tests and support for soap api
  types/jsforce/api/soap.d.ts
  types/jsforce/connection.d.ts
  types/jsforce/index.d.ts
  types/jsforce/jsforce-tests.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52352 Update mui-datatables customHeadLabelRender def
  types/mui-datatables/index.d.ts
  types/mui-datatables/mui-datatables-tests.tsx
Labels: Owner Approved, Perf: Same, Self Merge

#52071 @ember routing Specify that the returned Transition resolves to a Route
  types/ember__routing/-private/transition.d.ts
  types/ember__routing/test/route.ts
  types/ember__routing/test/router-service.ts
Labels: Owner Approved, Perf: Same, Popular package, Self Merge

#52297 Update sinon to use shipped fake-timers types
  types/sinon/index.d.ts
  types/sinon/package.json
  types/sinon/sinon-tests.ts
  types/sinon/tsconfig.json
Labels: Author is Owner, Critical package, Maintainer Approved, Perf: Same, Self Merge

#52327 [raf-schd] Support overloaded functions
  types/raf-schd/index.d.ts
  types/raf-schd/raf-schd-tests.ts
Labels: Owner Approved, Perf: Same, Self Merge

#51665 [@types/rosie]: Allow `option`s of type `any` for dynamic attribute definitions in rosie factories
  types/rosie/index.d.ts
  types/rosie/rosie-tests.ts
Labels: Maintainer Approved, Perf: Same, Self Merge, Unmerged
