Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2021-06, with the labels that each got.

#53476 [gestalt] Fix FlexProps and ModuleProps, add Flex.Item, and export Fieldset
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Owner Approved, Self Merge

#52859 [@types/carbon-components-react] Update types to match 7.34.x
  types/carbon-components-react/OTHER_FILES.txt
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/index.d.ts
  types/carbon-components-react/lib/components/Button/Button.d.ts
  types/carbon-components-react/lib/components/Checkbox/Checkbox.d.ts
  types/carbon-components-react/lib/components/DataTable/Table.d.ts
  types/carbon-components-react/lib/components/FeatureFlags/index.d.ts
  types/carbon-components-react/lib/components/Grid/Grid.d.ts
  types/carbon-components-react/lib/components/Link/Link.d.ts
  types/carbon-components-react/lib/components/NumberInput/NumberInput.d.ts
  types/carbon-components-react/lib/components/Pagination/Pagination.d.ts
  types/carbon-components-react/lib/components/Search/Search.d.ts
  types/carbon-components-react/lib/components/StructuredList/StructuredList.d.ts
  types/carbon-components-react/lib/components/StructuredList/index.d.ts
  types/carbon-components-react/lib/components/TextInput/ControlledPasswordInput.d.ts
  types/carbon-components-react/lib/components/TextInput/PasswordInput.d.ts
  types/carbon-components-react/lib/components/UIShell/HeaderMenuButton.d.ts
  types/carbon-components-react/lib/components/UIShell/SideNav.d.ts
Labels: Author is Owner, Check Config, Maintainer Approved, Perf: Worse, Self Merge

#53536 dynamodb 1.3: Add Generics to Query/Scanning Promises and Callback results
  types/dynamodb/Callback.d.ts
  types/dynamodb/ExecuteFilter.d.ts
  types/dynamodb/Model.d.ts
  types/dynamodb/Query.d.ts
  types/dynamodb/Scan.d.ts
  types/dynamodb/dynamodb-tests.ts
  types/dynamodb/index.d.ts
Labels: Owner Approved, Self Merge

#53537 koa-helmet missing type
  types/koa-helmet/index.d.ts
  types/koa-helmet/koa-helmet-tests.ts
Labels: Edits Owners, Owner Approved, Popular package, Self Merge

#53417 fix(mongoose): remove DT
  notNeededPackages.json
  types/forest-express-mongoose/package.json
  types/joigoose/package.json
  types/koa2-ratelimit/package.json
  types/mongoose-auto-increment/package.json
  types/mongoose-autopopulate/package.json
  types/mongoose-deep-populate/package.json
  types/mongoose-deep-populate/tsconfig.json
  types/mongoose-delete/package.json
  types/mongoose-geojson-schema/package.json
  types/mongoose-id-validator/package.json
  types/mongoose-lean-virtuals/package.json
  types/mongoose-mock/package.json
  types/mongoose-paginate-v2/package.json
  types/mongoose-promise/package.json
  types/mongoose-simple-random/package.json
  types/mongoose-unique-validator/package.json
  types/mongoose/README.md
  types/mongoose/index.d.ts
  types/mongoose/test/definitions.ts
  types/mongoose/test/document.ts
  types/mongoose/test/model.ts
  types/mongoose/test/mongoose.ts
  types/mongoose/test/query.ts
  types/mongoose/tsconfig.json
  types/mongoose/tslint.json
  types/mongoose/v3/index.d.ts
  types/mongoose/v3/mongoose-tests.ts
  types/mongoose/v3/tsconfig.json
  types/mongoose/v3/tslint.json
  types/mongoose/v4/README.md
  types/mongoose/v4/index.d.ts
  types/mongoose/v4/mongoose-tests.ts
  types/mongoose/v4/tsconfig.json
  types/mongoose/v4/tslint.json
  types/multer-gridfs-storage/package.json
  types/multer-gridfs-storage/v3/package.json
  types/resourcejs/package.json
Labels: Edits Infrastructure, Edits multiple packages, Maintainer Approved, Other Approved, Popular package, Self Merge, Too Many Owners

#53509 Initial commit - Types for package clusterize.js-paging
  types/clusterize.js-paging/clusterize.js-paging-tests.ts
  types/clusterize.js-paging/index.d.ts
  types/clusterize.js-paging/tsconfig.json
  types/clusterize.js-paging/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52906 update(css-minimmizer-webpack-plugin): v3 updates
  types/css-minimizer-webpack-plugin/css-minimizer-webpack-plugin-tests.ts
  types/css-minimizer-webpack-plugin/index.d.ts
  types/css-minimizer-webpack-plugin/package.json
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#53529 Add type definitions for lcm
  types/lcm/index.d.ts
  types/lcm/lcm-tests.ts
  types/lcm/tsconfig.json
  types/lcm/tslint.json
Labels: Maintainer Approved, New Definition, Other Approved, Self Merge

#53524 New @ckeditor/ckeditor5-image v27.1
  types/ckeditor__ckeditor5-core/src/editor/editorconfig.d.ts
  types/ckeditor__ckeditor5-image/ckeditor__ckeditor5-image-tests.ts
  types/ckeditor__ckeditor5-image/index.d.ts
  types/ckeditor__ckeditor5-image/src/autoimage.d.ts
  types/ckeditor__ckeditor5-image/src/image.d.ts
  types/ckeditor__ckeditor5-image/src/image/converters.d.ts
  types/ckeditor__ckeditor5-image/src/image/imageediting.d.ts
  types/ckeditor__ckeditor5-image/src/image/imageloadobserver.d.ts
  types/ckeditor__ckeditor5-image/src/image/insertimagecommand.d.ts
  types/ckeditor__ckeditor5-image/src/image/ui/utils.d.ts
  types/ckeditor__ckeditor5-image/src/image/utils.d.ts
  types/ckeditor__ckeditor5-image/src/imagecaption.d.ts
  types/ckeditor__ckeditor5-image/src/imagecaption/imagecaptionediting.d.ts
  types/ckeditor__ckeditor5-image/src/imagecaption/utils.d.ts
  types/ckeditor__ckeditor5-image/src/imageinsert.d.ts
  types/ckeditor__ckeditor5-image/src/imageinsert/imageinsertui.d.ts
  types/ckeditor__ckeditor5-image/src/imageinsert/ui/imageinsertformrowview.d.ts
  types/ckeditor__ckeditor5-image/src/imageinsert/ui/imageinsertpanelview.d.ts
  types/ckeditor__ckeditor5-image/src/imageinsert/utils.d.ts
  types/ckeditor__ckeditor5-image/src/imageresize.d.ts
  types/ckeditor__ckeditor5-image/src/imageresize/imageresizebuttons.d.ts
  types/ckeditor__ckeditor5-image/src/imageresize/imageresizeediting.d.ts
  types/ckeditor__ckeditor5-image/src/imageresize/imageresizehandles.d.ts
  types/ckeditor__ckeditor5-image/src/imageresize/resizeimagecommand.d.ts
  types/ckeditor__ckeditor5-image/src/imagestyle.d.ts
  types/ckeditor__ckeditor5-image/src/imagestyle/converters.d.ts
  types/ckeditor__ckeditor5-image/src/imagestyle/imagestylecommand.d.ts
  types/ckeditor__ckeditor5-image/src/imagestyle/imagestyleediting.d.ts
  types/ckeditor__ckeditor5-image/src/imagestyle/imagestyleui.d.ts
  types/ckeditor__ckeditor5-image/src/imagestyle/utils.d.ts
  types/ckeditor__ckeditor5-image/src/imagetextalternative.d.ts
  types/ckeditor__ckeditor5-image/src/imagetextalternative/imagetextalternativecommand.d.ts
  types/ckeditor__ckeditor5-image/src/imagetextalternative/imagetextalternativeediting.d.ts
  types/ckeditor__ckeditor5-image/src/imagetextalternative/imagetextalternativeui.d.ts
  types/ckeditor__ckeditor5-image/src/imagetextalternative/ui/textalternativeformview.d.ts
  types/ckeditor__ckeditor5-image/src/imagetoolbar.d.ts
  types/ckeditor__ckeditor5-image/src/imageupload.d.ts
  types/ckeditor__ckeditor5-image/src/imageupload/imageuploadediting.d.ts
  types/ckeditor__ckeditor5-image/src/imageupload/imageuploadprogress.d.ts
  types/ckeditor__ckeditor5-image/src/imageupload/imageuploadui.d.ts
  types/ckeditor__ckeditor5-image/src/imageupload/uploadimagecommand.d.ts
  types/ckeditor__ckeditor5-image/src/imageupload/utils.d.ts
  types/ckeditor__ckeditor5-image/tsconfig.json
  types/ckeditor__ckeditor5-image/tslint.json
  types/ckeditor__ckeditor5-link/src/linkimageediting.d.ts
  types/ckeditor__ckeditor5-link/src/linkimageui.d.ts
  types/ckeditor__ckeditor5-utils/src/dom/position.d.ts
Labels: Check Config, Edits multiple packages, Maintainer Approved, New Definition, Self Merge

#52853 Fix return type of istanbul-reports create
  types/istanbul-reports/index.d.ts
  types/istanbul-reports/istanbul-reports-tests.ts
Labels: Critical package, Maintainer Approved, Perf: Same, Self Merge

#53520 [react-image-gallery] Updated types
  types/react-image-gallery/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#53532 [get-sass-vars] Add type-declaration for `get-sass-vars`
  types/get-sass-vars/get-sass-vars-tests.ts
  types/get-sass-vars/index.d.ts
  types/get-sass-vars/tsconfig.json
  types/get-sass-vars/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53521 [three] – r129
  types/three/OTHER_FILES.txt
  types/three/examples/jsm/utils/CameraUtils.d.ts
  types/three/examples/jsm/webxr/OculusHandModel.d.ts
  types/three/examples/jsm/webxr/OculusHandPointerModel.d.ts
  types/three/examples/jsm/webxr/Text2D.d.ts
  types/three/examples/jsm/webxr/XRHandMeshModel.d.ts
  types/three/examples/jsm/webxr/XRHandModelFactory.d.ts
  types/three/examples/jsm/webxr/XRHandOculusMeshModel.d.ts
  types/three/index.d.ts
  types/three/src/Three.d.ts
  types/three/src/constants.d.ts
  types/three/src/core/BufferGeometry.d.ts
  types/three/src/core/Object3D.d.ts
  types/three/src/materials/MeshBasicMaterial.d.ts
  types/three/src/materials/MeshDistanceMaterial.d.ts
  types/three/src/materials/MeshLambertMaterial.d.ts
  types/three/src/materials/MeshMatcapMaterial.d.ts
  types/three/src/materials/MeshNormalMaterial.d.ts
  types/three/src/materials/MeshPhongMaterial.d.ts
  types/three/src/materials/MeshPhysicalMaterial.d.ts
  types/three/src/materials/MeshStandardMaterial.d.ts
  types/three/src/materials/MeshToonMaterial.d.ts
  types/three/src/materials/ShaderMaterial.d.ts
  types/three/src/math/MathUtils.d.ts
  types/three/src/math/Matrix4.d.ts
  types/three/src/objects/Skeleton.d.ts
  types/three/src/renderers/WebGLMultipleRenderTargets.d.ts
  types/three/src/renderers/WebGLRenderTarget.d.ts
  types/three/src/renderers/WebGLRenderer.d.ts
  types/three/src/renderers/webgl/WebGLRenderLists.d.ts
  types/three/test/cameras/camera-cinematic.ts
  types/three/test/cameras/camera.ts
  types/three/test/renderers/renderers-renderTarget-multiple.ts
  types/three/test/utils/utils-webgl-portal.ts
  types/three/tsconfig.json
Labels: Author is Owner, Check Config, Owner Approved, Popular package, Self Merge

#53533 [musickit-js]: add dt package
  types/musickit-js/MusicKit.API.d.ts
  types/musickit-js/MusicKit.Events.d.ts
  types/musickit-js/MusicKit.Library.d.ts
  types/musickit-js/MusicKit.MKError.d.ts
  types/musickit-js/MusicKit.MediaItem.d.ts
  types/musickit-js/MusicKit.MusicKitInstance.d.ts
  types/musickit-js/MusicKit.Player.d.ts
  types/musickit-js/MusicKit.Queue.d.ts
  types/musickit-js/MusicKit.SetQueueOptions.d.ts
  types/musickit-js/MusicKit.d.ts
  types/musickit-js/index.d.ts
  types/musickit-js/test/musickit-js-tests.ts
  types/musickit-js/tsconfig.json
  types/musickit-js/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#53499 [types/reach__router] Update the types of useParams
  types/reach__router/index.d.ts
  types/reach__router/reach__router-tests.tsx
Labels: Critical package, Owner Approved, Self Merge

#52887 [tap@15] Fix invalid type for pattern in Assertions.Match
  types/tap/index.d.ts
  types/tap/tap-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#53482 Fix faker.datatype.float param name
  types/faker/index.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#53485 [eslint] add `cacheStategy` option
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Critical package, Owner Approved, Self Merge

#53481 Add missing fields to AsyncTypeahead
  types/react-bootstrap-typeahead/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#53462 Added definition for redact-axios-error
  types/redact-axios-error/axios-error-groomer.d.ts
  types/redact-axios-error/axios-error-interceptor.d.ts
  types/redact-axios-error/index.d.ts
  types/redact-axios-error/redact-axios-error-tests.ts
  types/redact-axios-error/tsconfig.json
  types/redact-axios-error/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53450 [@chec/commerce.js] Add missing commerce.request() method
  types/chec__commerce.js/features/cart.d.ts
  types/chec__commerce.js/features/products.d.ts
  types/chec__commerce.js/index.d.ts
  types/chec__commerce.js/test/index.ts
  types/chec__commerce.js/test/products.ts
  types/chec__commerce.js/tsconfig.json
  types/chec__commerce.js/types/cart.d.ts
  types/chec__commerce.js/types/product-variant-group.d.ts
  types/chec__commerce.js/types/product.d.ts
  types/chec__commerce.js/types/variant-option.d.ts
  types/chec__commerce.js/types/variant.d.ts
Labels: Author is Owner, Owner Approved, Self Merge

#53487 [react][react-dom] experimental updates
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
Labels: Critical package, Edits multiple packages, Owner Approved, Self Merge

#53371 [mathjs] remove types package
  notNeededPackages.json
  types/mathjs/index.d.ts
  types/mathjs/mathjs-tests.ts
  types/mathjs/package.json
  types/mathjs/tsconfig.json
  types/mathjs/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Other Approved, Popular package, Self Merge

#52832 [@types/estree]: Add support for es2022 PropertyDefinition and PrivateIdentifier nodes
  types/estree/estree-tests.ts
  types/estree/index.d.ts
Labels: Critical package, Owner Approved, Perf: Same, Self Merge

#53467 [sinon] allow partial arguments for calledWith
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Critical package, Owner Approved, Self Merge

#53531 [chrome] Add tabId param for FetchProperties.
  types/chrome/index.d.ts
Labels: Maintainer Approved, Other Approved, Owner Approved, Popular package, Self Merge, Untested Change

#53336 update(perf_hooks): Improve types for the measure method
  types/node/perf_hooks.d.ts
  types/node/test/perf_hooks.ts
  types/node/v12/perf_hooks.d.ts
  types/node/v12/test/perf_hooks.ts
  types/node/v14/perf_hooks.d.ts
Labels: Critical package, Owner Approved, Self Merge

#53543 [video.js] Added fill as VideoPlayer option
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#53115 Add documented but not typed functions and options for Leaflet, v1.7.1
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#52965 fix(remarkable): invalid preset value
  types/remarkable/index.d.ts
  types/remarkable/lib/index.d.ts
  types/remarkable/remarkable-tests.ts
Labels: Maintainer Approved, Self Merge

#53184 update(firstline): typed input encoding options
  types/firstline/firstline-tests.ts
  types/firstline/index.d.ts
Labels: Owner Approved, Self Merge

#53368 [react-native] Change ColorValue type so that it can be assignable from objects
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Owner Approved, Popular package, Self Merge

#53538 Add documentation of template vars and small cleanup to vscode-notebook-renderers
  types/vscode-notebook-renderer/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53428 [react-big-calendar] fix header component definition and extract SlotInfo
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Owner Approved, Self Merge

#52904 [json-pointer] Improve types
  types/json-pointer/index.d.ts
  types/json-pointer/json-pointer-tests.ts
  types/json-pointer/tsconfig.json
  types/json-pointer/tslint.json
Labels: Edits Owners, Maintainer Approved, Perf: Same, Self Merge

#53544 New @ckeditor/ckeditor5-markdown-gfm v27.1
  types/ckeditor__ckeditor5-markdown-gfm/ckeditor__ckeditor5-markdown-gfm-tests.ts
  types/ckeditor__ckeditor5-markdown-gfm/index.d.ts
  types/ckeditor__ckeditor5-markdown-gfm/src/gfmdataprocessor.d.ts
  types/ckeditor__ckeditor5-markdown-gfm/src/html2markdown/html2markdown.d.ts
  types/ckeditor__ckeditor5-markdown-gfm/src/markdown.d.ts
  types/ckeditor__ckeditor5-markdown-gfm/src/markdown2html/markdown2html.d.ts
  types/ckeditor__ckeditor5-markdown-gfm/tsconfig.json
  types/ckeditor__ckeditor5-markdown-gfm/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#52775 feat(node): v15.9
  types/express-serve-static-core/index.d.ts
  types/express-serve-static-core/ts4.0/index.d.ts
  types/node/buffer.d.ts
  types/node/crypto.d.ts
  types/node/dgram.d.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/http.d.ts
  types/node/index.d.ts
  types/node/os.d.ts
  types/node/perf_hooks.d.ts
  types/node/process.d.ts
  types/node/readline.d.ts
  types/node/test/buffer.ts
  types/node/test/crypto.ts
  types/node/test/dgram.ts
  types/node/test/fs.ts
  types/node/test/http.ts
  types/node/test/perf_hooks.ts
  types/node/test/readline.ts
  types/node/test/timers_promises.ts
  types/node/test/tls.ts
  types/node/timers.d.ts
  types/node/timers/promises.d.ts
  types/node/tls.d.ts
  types/node/wasi.d.ts
  types/node/worker_threads.d.ts
Labels: Critical package, Edits multiple packages, Maintainer Approved, Self Merge

#53561 vscode-notebook-renderer: Improve documentation for getRenderer
  types/vscode-notebook-renderer/index.d.ts
Labels: Owner Approved, Untested Change

#53545 gatsby-plugin-breakpoints: Update BreakpointProvider type
  types/gatsby-plugin-breakpoints/gatsby-plugin-breakpoints-tests.tsx
  types/gatsby-plugin-breakpoints/index.d.ts
Labels: Owner Approved, Self Merge

#53564 Fix Type sshKeyPath
  types/ftps/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53550 [@types/wechat-miniprogram-xmly-plugin]fix PLAY_STATE lost two types
  types/wechat-miniprogram-xmly/player.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Other Approved, Self Merge, Untested Change

#53556 [react-native] Fix FlatList header and footer styles
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Owner Approved, Popular package, Self Merge

#53560 [react-native]: fix: don’t make callback arguments optional
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Author is Owner, Owner Approved, Popular package, Self Merge

#53553 update webpack-merge-and-include-globally to 2.3.4
  types/webpack-merge-and-include-globally/index.d.ts
Labels: Maintainer Approved, Self Merge, Untested Change

#53562 update(webpack-dev-middleware): v5 update
  types/webpack-dev-middleware/index.d.ts
  types/webpack-dev-middleware/package.json
  types/webpack-dev-middleware/webpack-dev-middleware-tests.ts
Labels: Author is Owner, Owner Approved, Popular package, Self Merge

#53314 update(worker-plugin): v5
  types/worker-plugin/index.d.ts
  types/worker-plugin/worker-plugin-tests.ts
Labels: Author is Owner, Owner Approved, Self Merge

#52776 feat(node): v15.12
  types/node/child_process.d.ts
  types/node/crypto.d.ts
  types/node/globals.d.ts
  types/node/http2.d.ts
  types/node/index.d.ts
  types/node/stream.d.ts
  types/node/test/child_process.ts
  types/node/test/crypto.ts
  types/node/test/http2.ts
  types/node/test/stream.ts
  types/node/test/worker_threads.ts
  types/node/ts3.6/base.d.ts
  types/node/ts3.6/index.d.ts
  types/node/worker_threads.d.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Self Merge

#53557 Type definitions added for promise-state-machine-es6
  types/promise-state-machine-es6/index.d.ts
  types/promise-state-machine-es6/promise-state-machine-es6-tests.ts
  types/promise-state-machine-es6/tsconfig.json
  types/promise-state-machine-es6/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53479 Add definitions for mParticle SDK
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-instance-tests.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
  types/mparticle__web-sdk/tsconfig.json
  types/mparticle__web-sdk/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#51756 remove rdf-js
  notNeededPackages.json
  types/clownface/package.json
  types/hydra-box/package.json
  types/n3/index.d.ts
  types/n3/package.json
  types/rdf-data-model/package.json
  types/rdf-dataset-ext/package.json
  types/rdf-dataset-indexed/package.json
  types/rdf-ext/package.json
  types/rdf-js/index.d.ts
  types/rdf-js/rdf-js-tests.ts
  types/rdf-js/tsconfig.json
  types/rdf-js/tslint.json
  types/rdf-loader-code/package.json
  types/rdf-loaders-registry/package.json
  types/rdf-transform-triple-to-quad/package.json
  types/rdf-validate-datatype/package.json
  types/rdf-validate-shacl/package.json
  types/rdfjs__dataset/package.json
  types/rdfjs__express-handler/package.json
  types/rdfjs__fetch-lite/package.json
  types/rdfjs__fetch/package.json
  types/rdfjs__formats-common/package.json
  types/rdfjs__namespace/package.json
  types/rdfjs__parser-jsonld/package.json
  types/rdfjs__parser-n3/package.json
  types/rdfjs__serializer-jsonld-ext/package.json
  types/rdfjs__serializer-jsonld/package.json
  types/rdfjs__serializer-ntriples/package.json
  types/rdfjs__serializer-rdfjs/package.json
  types/rdfjs__sink-map/package.json
  types/rdfjs__term-map/package.json
  types/rdfjs__term-set/package.json
  types/rdfjs__to-ntriples/package.json
  types/sparql-http-client/package.json
  types/sparqljs/package.json
Labels: Edits Infrastructure, Edits multiple packages, Maintainer Approved, Self Merge

#53580 Fix missed mongoose dependents
  types/mongoose-paginate/package.json
  types/mongoose-sequence/package.json
  types/passport-local-mongoose/package.json
Labels: Edits multiple packages, Maintainer Approved, Self Merge

#53572 [stremio-addon-sdk] Export stremio's interfaces and types
  types/stremio-addon-sdk/index.d.ts
  types/stremio-addon-sdk/stremio-addon-sdk-tests.ts
Labels: Edits Owners, Other Approved, Owner Approved, Self Merge

#53589 Update vscode-notebook-render for newest API
  types/vscode-notebook-renderer/index.d.ts
  types/vscode-notebook-renderer/vscode-notebook-renderer-tests.ts
Labels: Owner Approved, Self Merge

#53542 node-ssdp: Bump version to 4.0.
  types/node-ssdp/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53592 destroy -> dispose in vscode-notebook-renderer
  types/vscode-notebook-renderer/index.d.ts
  types/vscode-notebook-renderer/vscode-notebook-renderer-tests.ts
Labels: Owner Approved, Self Merge

#53573 [har-format] Adding render blocking and LCP info
  types/har-format/index.d.ts
Labels: Owner Approved, Popular package, Self Merge, Untested Change

#53600 Add mjClass prop to ClassNameProps in mjml-react package
  types/mjml-react/index.d.ts
  types/mjml-react/mjml-react-tests.tsx
Labels: Owner Approved, Self Merge

#53567 Define types of `profile._json`
  types/passport-google-oauth20/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#53534 [gestalt] updated Header/Text, Video element, Removed FlexProp overflow and minor changes
  types/gestalt/index.d.ts
Labels: Author is Owner, Owner Approved, Self Merge, Untested Change

#53601 add cssClass prop to MjmlSocial component in mjml-react
  types/mjml-react/index.d.ts
  types/mjml-react/mjml-react-tests.tsx
Labels: Owner Approved, Self Merge

#53581 aws-lambda | add types for client certificate information in APIGatewayEventIdentity
  types/aws-lambda/common/api-gateway.d.ts
  types/aws-lambda/test/api-gateway-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#53599 feat(tailwindcss): New config types for purge property
  types/tailwindcss/tailwind-config.d.ts
  types/tailwindcss/tailwindcss-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#52941 [angular-es] Fix property type `template` for iComponent, Change `template` not required
  types/angular-es/angular-es-tests.ts
  types/angular-es/index.d.ts
Labels: Owner Approved, Self Merge

#53568 [three] r129 minor fixes
  types/three/examples/jsm/postprocessing/EffectComposer.d.ts
  types/three/examples/jsm/postprocessing/Pass.d.ts
  types/three/examples/jsm/postprocessing/SSRPass.d.ts
  types/three/examples/jsm/postprocessing/SSRrPass.d.ts
  types/three/src/Three.d.ts
  types/three/test/cameras/camera-cinematic.ts
  types/three/test/cameras/camera.ts
  types/three/test/postprocessing/postprocessing-effectcomposer-pass.ts
  types/three/tsconfig.json
Labels: Author is Owner, Owner Approved, Popular package, Self Merge

#53546 add @type/svg-maps__brazil
  types/svg-maps__brazil/index.d.ts
  types/svg-maps__brazil/svg-maps__brazil-tests.ts
  types/svg-maps__brazil/tsconfig.json
  types/svg-maps__brazil/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53608 Type definitions improved for promise-state-machine-es6
  types/promise-state-machine-es6/index.d.ts
  types/promise-state-machine-es6/promise-state-machine-es6-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Self Merge

#53591 fix(node): remove abort method on AbortSignal
  types/node/globals.d.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Other Approved, Owner Approved, Self Merge, Untested Change

#53597 [chec/commerce.js] Better Response Testing + Fixed a few Types
  types/chec__commerce.js/test/categories.ts
  types/chec__commerce.js/test/merchants.ts
  types/chec__commerce.js/test/products.ts
  types/chec__commerce.js/types/asset.d.ts
  types/chec__commerce.js/types/merchant.d.ts
  types/chec__commerce.js/types/product-variant-group.d.ts
  types/chec__commerce.js/types/product.d.ts
Labels: Author is Owner, Owner Approved, Self Merge

#53585 Update version reference of @riderize/passport-strava-oauth2 types
  types/riderize__passport-strava-oauth2/index.d.ts
  types/riderize__passport-strava-oauth2/riderize__passport-strava-oauth2-tests.ts
  types/riderize__passport-strava-oauth2/tsconfig.json
  types/riderize__passport-strava-oauth2/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#52987 [download] Update to 8.0
  types/download/download-tests.ts
  types/download/index.d.ts
Labels: Edits Owners, Maintainer Approved, Popular package, Self Merge

#53620 Remove self from jasmine contributors
  types/jasmine/index.d.ts
Labels: Author is Owner, Critical package, Edits Owners, Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53617 [jasmine] Add aliases for renamed interfaces
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Author is Owner, Critical package, Maintainer Approved, Owner Approved, Self Merge

#53598 [cloudinary-uploadwidget] Add typings for cloudinary-uploadwidget non-module script (v2)
  types/cloudinary-uploadwidget-browser/cloudinary-uploadwidget-browser-tests.ts
  types/cloudinary-uploadwidget-browser/index.d.ts
  types/cloudinary-uploadwidget-browser/tsconfig.json
  types/cloudinary-uploadwidget-browser/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53483 [koa-bodyparser] add ability to strictly type request body
  types/koa-bodyparser/index.d.ts
  types/koa-bodyparser/koa-bodyparser-tests.ts
  types/koa-bodyparser/test/body-typed-on-use-tests.ts
  types/koa-bodyparser/test/body-typed-with-koa-tests.ts
  types/koa-bodyparser/test/body-untyped-tests.ts
  types/koa-bodyparser/test/raw-body-tests.ts
  types/koa-bodyparser/tsconfig.json
Labels: Edits Owners, Maintainer Approved, Popular package, Self Merge

#53625 vscode-notebook-renderer: Add owner and small cleanup
  types/vscode-notebook-renderer/index.d.ts
Labels: Edits Owners, Untested Change

#53626 [powerapps-component-framework] Lookup return discrepancy fixes
  types/powerapps-component-framework/componentframework.d.ts
  types/powerapps-component-framework/index.d.ts
  types/powerapps-component-framework/powerapps-component-framework-tests.ts
Labels: Author is Owner, Edits Owners, Owner Approved, Self Merge

#53352 draft-convert: Add type definitions for basic conversion functions
  types/draft-convert/draft-convert-tests.tsx
  types/draft-convert/index.d.ts
Labels: Owner Approved, Self Merge

#53631 Finish putting riderize__passport-strava-oauth2 back
  notNeededPackages.json
  types/riderize__passport-strava-oauth2/index.d.ts
Labels: Edits Infrastructure, Untested Change

#53632 Artificially increase riderize__passport-strava-oauth2 version
  types/riderize__passport-strava-oauth2/index.d.ts
  types/riderize__passport-strava-oauth2/tslint.json
Labels: Check Config, Untested Change

#53613 Add credentials amqplain type
  types/amqplib/callback_api.d.ts
  types/amqplib/index.d.ts
Labels: Edits Owners, Owner Approved, Popular package, Self Merge, Untested Change

#52999 add a className prop to react-custom-scroll types
  types/react-custom-scroll/index.d.ts
  types/react-custom-scroll/react-custom-scroll-tests.tsx
Labels: Author is Owner, Maintainer Approved, Self Merge

#53378 [ol] Update WFS.d.ts
  types/ol/format/WFS.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#53565 feat: add yargs-unparser libdefs
  types/yargs-unparser/index.d.ts
  types/yargs-unparser/tsconfig.json
  types/yargs-unparser/tslint.json
  types/yargs-unparser/yargs-unparser-tests.ts
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#53383 esri-leaflet: Adding type definition for ServiceOptions.withCredentials
  types/esri-leaflet/esri-leaflet-tests.ts
  types/esri-leaflet/index.d.ts
Labels: Owner Approved, Self Merge

#53638 [materialize-css] Added missing exposed instance properties on the Timepicker
  types/materialize-css/test/timepicker.test.ts
  types/materialize-css/timepicker.d.ts
Labels: Owner Approved, Self Merge

#53623 Add types for docker-modem
  types/docker-modem/docker-modem-tests.ts
  types/docker-modem/index.d.ts
  types/docker-modem/tsconfig.json
  types/docker-modem/tslint.json
Labels: Check Config, Maintainer Approved, New Definition, Self Merge

#53612 [react-router]: Fix param types of generatePath for zero or more and …
  types/react-router/index.d.ts
  types/react-router/test/generatePath.ts
Labels: Critical package, Owner Approved, Self Merge

#53604 [react-slider] Update types to support thumb index (v1.30)
  types/react-slider/index.d.ts
  types/react-slider/react-slider-tests.tsx
Labels: Owner Approved, Self Merge

#53384 Update types/drawflow/index.d.ts
  types/drawflow/index.d.ts
Labels: Owner Approved, Self Merge, Untested Change

#53420 Add definitions for jsbn.BigInteger from @types/node-forge
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#52924 fix(jest-when): update When to accept generic function argument
  types/jest-when/example-module.ts
  types/jest-when/index.d.ts
  types/jest-when/jest-when-tests.ts
Labels: Edits Owners, Maintainer Approved, Perf: Same, Popular package, Self Merge

#53453 Upgrade @types/carbon__elements to v10.35
  types/carbon__elements/carbon__elements-tests.ts
  types/carbon__elements/index.d.ts
Labels: Author is Owner, No Other Owners, Other Approved, Self Merge

#52875 @types/heremaps include H.data.geojson.Reader
  types/heremaps/heremaps-tests.ts
  types/heremaps/index.d.ts
Labels: Maintainer Approved, Perf: Same, Self Merge

#53654 Remove self from mapbox-gl maintainers list
  types/mapbox-gl/index.d.ts
Labels: Author is Owner, Edits Owners, Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#53660 Fixing typos in express-rate-limit
  types/express-rate-limit/index.d.ts
Labels: Maintainer Approved, Popular package, Self Merge, Untested Change

#53661 Fixed typo on TapAreaProp (Gestalt)
  types/gestalt/index.d.ts
Labels: Author is Owner, Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53641 [@chec/commerce.js] Add Phone to Customer Type + Order Type
  types/chec__commerce.js/features/customer.d.ts
  types/chec__commerce.js/test/customer.ts
  types/chec__commerce.js/test/order.ts
  types/chec__commerce.js/tsconfig.json
  types/chec__commerce.js/types/address.d.ts
  types/chec__commerce.js/types/checkout-capture-response.d.ts
  types/chec__commerce.js/types/checkout-capture.d.ts
  types/chec__commerce.js/types/customer.d.ts
  types/chec__commerce.js/types/order-collected.d.ts
  types/chec__commerce.js/types/order-conditionals.d.ts
  types/chec__commerce.js/types/order-line-item.d.ts
  types/chec__commerce.js/types/order-tax-line.d.ts
  types/chec__commerce.js/types/order-tax.d.ts
  types/chec__commerce.js/types/order.d.ts
Labels: Author is Owner, Owner Approved, Self Merge

#52726 wavesurfer.js: add docs + missing elements, split index, use ESM modules
  types/wavesurfer.js/index.d.ts
  types/wavesurfer.js/src/drawer.canvasentry.d.ts
  types/wavesurfer.js/src/drawer.d.ts
  types/wavesurfer.js/src/drawer.multicanvas.d.ts
  types/wavesurfer.js/src/html-init.d.ts
  types/wavesurfer.js/src/mediaelement-webaudio.d.ts
  types/wavesurfer.js/src/mediaelement.d.ts
  types/wavesurfer.js/src/peakcache.d.ts
  types/wavesurfer.js/src/plugin/cursor.d.ts
  types/wavesurfer.js/src/plugin/elan.d.ts
  types/wavesurfer.js/src/plugin/markers.d.ts
  types/wavesurfer.js/src/plugin/mediasession.d.ts
  types/wavesurfer.js/src/plugin/microphone.d.ts
  types/wavesurfer.js/src/plugin/minimap.d.ts
  types/wavesurfer.js/src/plugin/playhead.d.ts
  types/wavesurfer.js/src/plugin/regions.d.ts
  types/wavesurfer.js/src/plugin/spectogram.d.ts
  types/wavesurfer.js/src/plugin/timeline.d.ts
  types/wavesurfer.js/src/util/absMax.d.ts
  types/wavesurfer.js/src/util/clamp.d.ts
  types/wavesurfer.js/src/util/fetch.d.ts
  types/wavesurfer.js/src/util/frame.d.ts
  types/wavesurfer.js/src/util/get-id.d.ts
  types/wavesurfer.js/src/util/index.d.ts
  types/wavesurfer.js/src/util/max.d.ts
  types/wavesurfer.js/src/util/min.d.ts
  types/wavesurfer.js/src/util/observer.d.ts
  types/wavesurfer.js/src/util/orientation.d.ts
  types/wavesurfer.js/src/util/prevent-click.d.ts
  types/wavesurfer.js/src/util/request-animation-frame.d.ts
  types/wavesurfer.js/src/util/style.d.ts
  types/wavesurfer.js/src/wavesurfer.d.ts
  types/wavesurfer.js/src/webaudio.d.ts
  types/wavesurfer.js/types/backend.d.ts
  types/wavesurfer.js/types/params.d.ts
  types/wavesurfer.js/types/plugin.d.ts
  types/wavesurfer.js/types/util.d.ts
  types/wavesurfer.js/types/xhr.d.ts
  types/wavesurfer.js/wavesurfer.js-tests.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Self Merge

#53640 gdal: Added Geometry.fromGeoJson function and fixed the argument type of SpatialReference.fromEPSG
  types/gdal/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53664 update(zingchart): add typings for 'legend' and 'plot' attribute
  types/zingchart/es6/index.d.ts
  types/zingchart/zingchart-tests.ts
Labels: Other Approved, Self Merge

#53650 fix(console-log-level): make `options` optional
  types/console-log-level/console-log-level-tests.ts
  types/console-log-level/index.d.ts
Labels: Owner Approved, Popular package, Self Merge

#53649 Add type definition for sound-play
  types/sound-play/index.d.ts
  types/sound-play/sound-play-tests.ts
  types/sound-play/tsconfig.json
  types/sound-play/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53590 Added forge.pkcs7.messageToPem and forge.pkcs7.messageFro…
  types/node-forge/README.md
  types/node-forge/index.d.ts
Labels: Edits Owners, Maintainer Approved, Popular package, Self Merge, Untested Change

#53658 Update index.d.ts
  types/tinymce/index.d.ts
Labels: Edits Owners, Maintainer Approved, Owner Approved, Self Merge, Untested Change

#52170 Update react-native-share-menu for 5.0 by @PhilBeaudoin
  types/react-native-share-menu/index.d.ts
  types/react-native-share-menu/react-native-share-menu-tests.ts
Labels: Edits Owners, Owner Approved, Perf: Same, Self Merge

#53629 node: Fix link tags using parens
  types/node/console.d.ts
  types/node/v12/globals.d.ts
  types/node/v14/console.d.ts
Labels: Critical package, Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53637 chore(markdown-it): remove unused imports
  types/markdown-it/lib/index.d.ts
Labels: Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#53647 create @types/rollup-plugin-auto-external
  types/rollup-plugin-auto-external/index.d.ts
  types/rollup-plugin-auto-external/package.json
  types/rollup-plugin-auto-external/rollup-plugin-auto-external-tests.ts
  types/rollup-plugin-auto-external/tsconfig.json
  types/rollup-plugin-auto-external/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53447 Add support for type-level augmentation of types in `ref-napi`
  types/ref-napi/index.d.ts
  types/ref-napi/ref-napi-tests.ts
Labels: Owner Approved, Self Merge

#53452 ffi-napi: Fix library function inference for JavaScript
  types/ffi-napi/ffi-napi-tests.ts
  types/ffi-napi/index.d.ts
Labels: Owner Approved, Self Merge

#53609 Adds a script for closing old issues on the repo
  .gitignore
  package.json
  scripts/close-old-issues.js
Labels: Edits Infrastructure

#53007 fix(stylus): expose Renderer for client and types consumption
  types/stylus/index.d.ts
  types/stylus/lib/renderer.d.ts
  types/stylus/stylus-tests.ts
Labels: Maintainer Approved, Popular package, Self Merge

#52585 update(big.js): Missing optional rounding mode parameter in `toExponential`, `toFixed` and `toPrecision`
  types/big.js/index.d.ts
  types/big.js/test/big.js-import-default-tests.ts
  types/big.js/test/big.js-module-tests.ts
Labels: Maintainer Approved, Perf: Same, Popular package, Self Merge

#53679 json-form-data ValidJSON can contain an array of ValidJSONs
  types/json-form-data/index.d.ts
  types/json-form-data/json-form-data-tests.ts
Labels: Edits Owners, Owner Approved, Self Merge

#52242 styled-components: Enable 'as' and 'forwardedAs' props to be linted
  types/styled-components/index.d.ts
  types/styled-components/test/index.tsx
Labels: Critical package, Perf: Same, Self Merge, Unmerged

#52836 [findup-sync] Add docs, remove superfluous interface, update code style
  types/findup-sync/findup-sync-tests.ts
  types/findup-sync/index.d.ts
Labels: Author is Owner, Maintainer Approved, Perf: Same, Popular package, Self Merge

#53622 add types for react-page-visibility
  types/react-page-visibility/index.d.ts
  types/react-page-visibility/react-page-visibility-tests.tsx
  types/react-page-visibility/tsconfig.json
  types/react-page-visibility/tslint.json
Labels: Maintainer Approved, New Definition, Self Merge

#53646 add proto-fetch and file-fetch
  types/file-fetch/file-fetch-tests.ts
  types/file-fetch/index.d.ts
  types/file-fetch/tsconfig.json
  types/file-fetch/tslint.json
  types/proto-fetch/index.d.ts
  types/proto-fetch/proto-fetch-tests.ts
  types/proto-fetch/tsconfig.json
  types/proto-fetch/tslint.json
Labels: Edits multiple packages, Maintainer Approved, New Definition, Self Merge

#53686 update(cson): fix at 7.20 version
  types/cson/cson-tests.ts
  types/cson/index.d.ts
  types/cson/tsconfig.json
  types/cson/tslint.json
Labels: Owner Approved, Self Merge

#53666 fix(validator) - added version argument to isIPRange
  types/validator/OTHER_FILES.txt
  types/validator/es/lib/isIPRange.d.ts
  types/validator/index.d.ts
  types/validator/lib/isIPRange.d.ts
  types/validator/validator-tests.ts
Labels: Check Config, Critical package, Maintainer Approved, Self Merge

#53680 [openui5] Update definition files for OpenUI5 1.90
  types/openui5/README.md
  types/openui5/index.d.ts
  types/openui5/jquery.sap.d.ts
  types/openui5/openui5-tests.ts
  types/openui5/sap.f.d.ts
  types/openui5/sap.m.d.ts
  types/openui5/sap.tnt.d.ts
  types/openui5/sap.ui.codeeditor.d.ts
  types/openui5/sap.ui.commons.d.ts
  types/openui5/sap.ui.core.d.ts
  types/openui5/sap.ui.d.ts
  types/openui5/sap.ui.dt.d.ts
  types/openui5/sap.ui.fl.d.ts
  types/openui5/sap.ui.integration.d.ts
  types/openui5/sap.ui.layout.d.ts
  types/openui5/sap.ui.mdc.d.ts
  types/openui5/sap.ui.rta.d.ts
  types/openui5/sap.ui.suite.d.ts
  types/openui5/sap.ui.support.d.ts
  types/openui5/sap.ui.table.d.ts
  types/openui5/sap.ui.testrecorder.d.ts
  types/openui5/sap.ui.unified.d.ts
  types/openui5/sap.ui.ux3.d.ts
  types/openui5/sap.uxap.d.ts
  types/openui5/tsconfig.json
  types/openui5/tslint.json
Labels: Check Config, Edits Owners, Maintainer Approved, No Other Owners, Self Merge

#53460 Remove ts3.5 support from jsdom
  types/jsdom/package.json
  types/jsdom/ts3.5/index.d.ts
  types/jsdom/ts3.5/jsdom-tests.ts
  types/jsdom/ts3.5/tsconfig.json
  types/jsdom/ts3.5/tslint.json
  types/jsdom/ts4.0/index.d.ts
Labels: Popular package, Unreviewed

#53672 Export Upload class in graphql-upload
  types/graphql-upload/index.d.ts
Labels: Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#53676 [echarts] add clip type of SeriesBar
  types/echarts/options/series/bar.d.ts
Labels: Maintainer Approved, Popular package, Self Merge, Untested Change

#53692 [ffi-napi] Augments 'ref.Type' with 'ffi_type' when 'ffi-napi' is loaded
  types/ffi-napi/ffi-napi-tests.ts
  types/ffi-napi/index.d.ts
Labels: Owner Approved, Self Merge

#53685 feat(react): Add types for `next` release channel
  types/react-dom/experimental.d.ts
  types/react-dom/index.d.ts
  types/react-dom/next.d.ts
  types/react-dom/test/experimental-tests.tsx
  types/react-dom/test/next-tests.tsx
  types/react-dom/tsconfig.json
  types/react-is/index.d.ts
  types/react-is/next.d.ts
  types/react-is/test/next-tests.tsx
  types/react-is/test/react-is-tests.tsx
  types/react-is/tsconfig.json
  types/react/OTHER_FILES.txt
  types/react/experimental.d.ts
  types/react/index.d.ts
  types/react/next.d.ts
  types/react/test/experimental.tsx
  types/react/test/next.tsx
  types/react/tsconfig.json
Labels: Author is Owner, Check Config, Critical package, Edits multiple packages, Maintainer Approved, Self Merge

#53677 [prompts] Correct PromptObject.initial's type
  types/prompts/index.d.ts
  types/prompts/prompts-tests.ts
Labels: Owner Approved, Popular package, Self Merge

#53674 requestBody in chrome can be null
  types/chrome/index.d.ts
Labels: Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#53614 update(oracledb): Add QueryStream interface
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
Labels: Owner Approved, Self Merge

#53491 Add initialValueFormat to props
  types/react-phone-number-input/index.d.ts
  types/react-phone-number-input/react-phone-number-input-tests.tsx
Labels: Owner Approved, Self Merge

#53696 Add types for `unstable_createMutableSource` and `unstable_useMutableSource`
  types/react/next.d.ts
  types/react/test/next.tsx
Labels: Author is Owner, Critical package, Maintainer Approved, Owner Approved, Self Merge

#53668 fix: adds missing params object for getTextContent type for pdfjs-dist
  types/pdfjs-dist/index.d.ts
Labels: Maintainer Approved, Popular package, Self Merge, Untested Change

#53530 react-native-video: Added types for `mixWithOthers`
  types/react-native-video/index.d.ts
Labels: Maintainer Approved, Owner Approved, Popular package, Self Merge, Untested Change

#53698 Remove `@types/graphql-relay`
  notNeededPackages.json
  types/graphql-relay/graphql-relay-tests.ts
  types/graphql-relay/index.d.ts
  types/graphql-relay/package.json
  types/graphql-relay/tsconfig.json
  types/graphql-relay/tslint.json
Labels: Edits Infrastructure, Maintainer Approved, Self Merge

#53682 Added return of Array on RowGroupSettings
  types/datatables.net-rowgroup/index.d.ts
Labels: Maintainer Approved, Self Merge, Untested Change

#53678 Update index.d.ts
  types/datatables.net-rowgroup/index.d.ts
Labels: Maintainer Approved, Self Merge, Untested Change

#52862 update(svg-spritemap-webpack-plugin): v4 updates
  types/svg-spritemap-webpack-plugin/index.d.ts
  types/svg-spritemap-webpack-plugin/package.json
  types/svg-spritemap-webpack-plugin/svg-spritemap-webpack-plugin-tests.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Perf: Same, Self Merge

#53220 update(get-image-colors): v4 updates
  types/get-image-colors/get-image-colors-tests.ts
  types/get-image-colors/index.d.ts
Labels: Author is Owner, Maintainer Approved, No Other Owners, Self Merge

#53315 update(send): v0.17
  types/send/index.d.ts
  types/send/send-tests.ts
  types/send/tslint.json
Labels: Edits Owners, Maintainer Approved, Popular package, Self Merge

#53690 [@types/bootstrap] v5 components getInstance() can return null
  types/bootstrap/js/dist/carousel.d.ts
  types/bootstrap/js/dist/collapse.d.ts
  types/bootstrap/js/dist/dropdown.d.ts
  types/bootstrap/js/dist/modal.d.ts
  types/bootstrap/js/dist/offcanvas.d.ts
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/scrollspy.d.ts
  types/bootstrap/js/dist/tab.d.ts
  types/bootstrap/js/dist/toast.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
  types/bootstrap/test/carousel-tests.ts
  types/bootstrap/test/collapse-tests.ts
  types/bootstrap/test/dropdown-tests.ts
  types/bootstrap/test/modal-tests.ts
  types/bootstrap/test/offcanvas-tests.ts
  types/bootstrap/test/popover-tests.ts
  types/bootstrap/test/scrollspy-tests.ts
  types/bootstrap/test/tab-tests.ts
  types/bootstrap/test/toast-tests.ts
  types/bootstrap/test/tooltip-tests.ts
Labels: Maintainer Approved, Owner Approved, Popular package, Self Merge

#53192 [aws4] Fix incorrect type and add type expectations to test
  types/aws4/aws4-tests.ts
  types/aws4/index.d.ts
Labels: Maintainer Approved, Popular package, Self Merge

#52388 [@wordpress/api-fetch] Remove DT definitions
  notNeededPackages.json
  types/wordpress__api-fetch/index.d.ts
  types/wordpress__api-fetch/tsconfig.json
  types/wordpress__api-fetch/tslint.json
  types/wordpress__api-fetch/wordpress__api-fetch-tests.ts
  types/wordpress__data-controls/index.d.ts
  types/wordpress__data-controls/package.json
Labels: Edits Infrastructure, Edits multiple packages, Perf: Same, The CI failed

#53606 Move templates which should redirect folks to discussions
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/infrastructure_issue.md
Labels: Edits Infrastructure, Revision needed

#53699 New question type
  types/google-apps-script/google-apps-script.forms.d.ts
Labels: Maintainer Approved, Self Merge, Untested Change

#53480 Fix types for node-mailjet request IDs
  types/node-mailjet/index.d.ts
  types/node-mailjet/node-mailjet-tests.ts
Labels: Edits Owners, Owner Approved, Self Merge

#53488 [react-pdf] updating props for the Page and Document components based on readme correction from original repository
  types/react-pdf/dist/Document.d.ts
  types/react-pdf/dist/Page.d.ts
  types/react-pdf/index.d.ts
Labels: Owner Approved, Popular package, Self Merge, Untested Change

#53709 matter-js update type definitions from version 0.14.2 to 0.17.1
  types/matter-js/index.d.ts
Labels: Maintainer Approved, Owner Approved, Self Merge, Untested Change

#53706 luxon 1.27.0
  types/luxon/index.d.ts
  types/luxon/src/datetime.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Maintainer Approved, Owner Approved, Popular package, Self Merge

#53742 VS Code 1.57.0 Extension API
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#53710 css-minimizer-webpack-plugin: Add {cssnano,csso,cleanCss}Minify
  types/css-minimizer-webpack-plugin/css-minimizer-webpack-plugin-tests.ts
  types/css-minimizer-webpack-plugin/index.d.ts
Labels: Maintainer Approved, Self Merge
