Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2022-01, with the labels that each got.

#57790 fix formidable types
  types/formidable/formidable-tests.ts
  types/formidable/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#57852 [amplitude-js] remove myself as author
  types/amplitude-js/index.d.ts
  types/amplitude-js/v4/index.d.ts
  types/amplitude-js/v5/index.d.ts
Labels: Other Approved, Popular package, Author is Owner, Untested Change, Edits Owners

#57862 jest: Add tests for optional arg to promise mocking funcs
  types/jest/jest-tests.ts
Labels: Author is Owner, Critical package

#57740 [react-native] Fix getNativeScrollRef return type
  types/react-native/index.d.ts
Labels: Self Merge, Owner Approved, Critical package, Untested Change, Edits Owners

#57889 [graphql-upload] Fix Upload type definition
  types/graphql-upload/index.d.ts
Labels: Popular package, Self Merge, Untested Change

#57473 [node]: correct the return type for `destroy` and `end`
  types/bittorrent-protocol/index.d.ts
  types/charm/index.d.ts
  types/ebml/index.d.ts
  types/firebird/index.d.ts
  types/hexo-util/index.d.ts
  types/jsforce/query.d.ts
  types/list-stream/index.d.ts
  types/minipass/index.d.ts
  types/minizlib/index.d.ts
  types/node-expat/index.d.ts
  types/node/globals.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/net.d.ts
  types/node/stream.d.ts
  types/node/test/crypto.ts
  types/node/test/http.ts
  types/node/test/http2.ts
  types/node/test/net.ts
  types/node/v12/globals.d.ts
  types/node/v12/http.d.ts
  types/node/v12/http2.d.ts
  types/node/v12/net.d.ts
  types/node/v12/stream.d.ts
  types/node/v14/globals.d.ts
  types/node/v14/http.d.ts
  types/node/v14/http2.d.ts
  types/node/v14/net.d.ts
  types/node/v14/stream.d.ts
  types/readable-stream/index.d.ts
  types/request/index.d.ts
  types/simple-peer/index.d.ts
  types/simple-websocket/index.d.ts
  types/ssh2/index.d.ts
  types/tar-stream/v1/index.d.ts
Labels: Self Merge, Edits multiple packages, Critical package, Too Many Owners

#57807 update(cssnano): v5 bump
  types/cssnano/cssnano-tests.ts
  types/cssnano/index.d.ts
  types/cssnano/package.json
  types/cssnano/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Check Config

#57916 [charcodes] Added new definitions
  types/charcodes/charcodes-tests.ts
  types/charcodes/index.d.ts
  types/charcodes/tsconfig.json
  types/charcodes/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#57747 Updated ComboBox Errors
  types/gestalt/index.d.ts
Labels: Self Merge, Author is Owner, Untested Change

#57900 [react-native] Add missing props to TextInputKeyPressEventData
  types/react-native/v0.63/index.d.ts
  types/react-native/v0.64/index.d.ts
  types/react-native/v0.65/index.d.ts
Labels: Popular package, Self Merge, Untested Change

#57737 [jasmine] Use ThisType<> to make spy this type-safe
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#57709 [version change required: from 8.0.2 -> 12.4.0] update @types/sass-loader types with latest version of sass-loader
  types/sass-loader/interfaces.d.ts
  types/sass-loader/sass-loader-tests.ts
Labels: Popular package, Self Merge

#57905 [@types/bootstrap] carousel option is called ride
  types/bootstrap/js/dist/carousel.d.ts
  types/bootstrap/test/carousel-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#57757 HereOptions interface updated to conditional appCode
  types/node-geocoder/index.d.ts
Labels: Self Merge, Untested Change

#57935 [express-fileupload]: removed vosatom from definition owners
  types/express-fileupload/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#57915 twine-sugarcube: Add missing definitions and apply small fixes
  types/twine-sugarcube/macro.d.ts
  types/twine-sugarcube/test/macro.ts
Labels: Self Merge, Owner Approved

#57909 add defaultTool to [react-svg-pan-zoom]
  types/react-svg-pan-zoom/index.d.ts
  types/react-svg-pan-zoom/react-svg-pan-zoom-tests.tsx
Labels: Other Approved, Self Merge, Edits Owners

#57936 fix(node-cron): add missing parameter
  types/node-cron/index.d.ts
  types/node-cron/node-cron-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#57932 Add typings for @lerna/package & @lerna/project
  types/lerna__package/index.d.ts
  types/lerna__package/lerna__package-tests.ts
  types/lerna__package/tsconfig.json
  types/lerna__package/tslint.json
  types/lerna__project/index.d.ts
  types/lerna__project/lerna__project-tests.ts
  types/lerna__project/tsconfig.json
  types/lerna__project/tslint.json
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved

#57914 [ioredis] add zmscore
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#57701 [amplitude-js] Add resetSessionId method to AmplitudeClient
  types/amplitude-js/amplitude-js-tests.ts
  types/amplitude-js/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Edits Owners

#57902 @types/node-telegram-bot-api: New type definition
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#57919 Node.js TCP Socket - remove obsolete timeout option and add abortController
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v16/net.d.ts
  types/node/v16/test/net.ts
Labels: Self Merge, Owner Approved, Critical package

#57942 [jsrsasign] - fixes for version 9
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/KEYUTIL.d.ts
  types/jsrsasign/modules/KJUR/asn1/csr/CSRUtil.d.ts
  types/jsrsasign/modules/KJUR/asn1/csr/CertificationRequest.d.ts
  types/jsrsasign/modules/KJUR/asn1/csr/CertificationRequestInfo.d.ts
Labels: Self Merge, Owner Approved

#57939 [nat-upnp] Fixed spelling mistake and an incorrect type
  types/nat-upnp/index.d.ts
  types/nat-upnp/nat-upnp-tests.ts
Labels: Other Approved, Self Merge, Owner Approved

#57787 [jsts] Fix GeoJSONReader constructor
  types/jsts/index.d.ts
  types/jsts/jsts-tests.ts
Labels: Other Approved, Self Merge

#57712 [jsts] Add algorithm.(Robust)LineIntersector to typings
  types/jsts/index.d.ts
  types/jsts/jsts-tests.ts
Labels: Other Approved, Self Merge

#57928 [firefox-webext-browser] Add missing methods for bookmarks
  types/firefox-webext-browser/firefox-webext-browser-tests.ts
  types/firefox-webext-browser/index.d.ts
Labels: Self Merge, Owner Approved

#57690 Jenkins. Added optional folder parameter for listing jobs
  types/jenkins/index.d.ts
  types/jenkins/jenkins-tests.ts
Labels: Other Approved, Self Merge, No Other Owners

#57748 Move `loadTransaction` from `ServerOptions` to `DecisionOptions`
  types/oauth2orize/index.d.ts
Labels: Self Merge, Untested Change

#57947 [three] r136
  types/three/examples/jsm/controls/ArcballControls.d.ts
  types/three/examples/jsm/controls/TransformControls.d.ts
  types/three/examples/jsm/loaders/RGBMLoader.d.ts
  types/three/examples/jsm/objects/Reflector.d.ts
  types/three/examples/jsm/objects/Refractor.d.ts
  types/three/index.d.ts
  types/three/src/Three.d.ts
  types/three/src/constants.d.ts
  types/three/src/math/Color.d.ts
  types/three/src/renderers/WebGLRenderer.d.ts
  types/three/src/textures/FramebufferTexture.d.ts
  types/three/test/controls/controls-arcballcontrols.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#57949 [navermaps] update GeocodeResponse v2
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57925 [ref-struct-di] improved typing for constructor args
  types/ref-struct-di/index.d.ts
  types/ref-struct-di/ts4.1/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#57933 TailwindCSS: Allow for string selector in TailwindConfig's important property
  types/tailwindcss/tailwind-config.d.ts
  types/tailwindcss/test/tailwindcss-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#57749 [musickit-js]: add authorized auth status
  types/musickit-js/MusicKit.Events.d.ts
  types/musickit-js/MusicKit.d.ts
  types/musickit-js/test/musickit-js-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#57636 fixing config js extendDeep signature
  types/config/config-tests.ts
  types/config/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#57893 [fparser] New type definition
  types/fparser/index.d.ts
  types/fparser/src/fparser.d.ts
  types/fparser/test/fparser-tests.cjs.ts
  types/fparser/test/fparser-tests.global.ts
  types/fparser/tsconfig.json
  types/fparser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#53719 [openseadragon] update types for v.3.0
  types/openseadragon/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change

#57948 [jsrsasign] - fixes for version 9, Certificate and TBSCertificate
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/KJUR/asn1/x509/Certificate.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/TBSCertificate.d.ts
  types/jsrsasign/modules/X509.d.ts
Labels: Self Merge, Owner Approved

#57940 leaflet: typo `pointsToPath` parameter name, `close` -> `closed`
  types/leaflet/index.d.ts
Labels: Other Approved, Popular package, Untested Change

#57941 [webtorrent] add missing announceList property
  types/webtorrent/index.d.ts
  types/webtorrent/webtorrent-tests.ts
Labels: Other Approved, Self Merge

#57963 [@types/ioredis] Update ioredis flushdb option to include 'sync' and 'async'
  types/ioredis/index.d.ts
  types/ioredis/ioredis-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#57912 Fix [node-telegram-bot-api]: pinChatMessage - changed type for messageId to number, Added: messageId field in unpinChatMessage.
  package.json
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Popular package, Self Merge, Edits Infrastructure

#57726 add some new definitions and fix some issues
  types/hummer-env/components/BaseComponent.d.ts
  types/hummer-env/components/Button.d.ts
  types/hummer-env/components/CanvasView.d.ts
  types/hummer-env/components/HorizontalScroller.d.ts
  types/hummer-env/components/Image.d.ts
  types/hummer-env/components/Index.d.ts
  types/hummer-env/components/Input.d.ts
  types/hummer-env/components/List.d.ts
  types/hummer-env/components/Scroller.d.ts
  types/hummer-env/components/Switch.d.ts
  types/hummer-env/components/Text.d.ts
  types/hummer-env/components/TextArea.d.ts
  types/hummer-env/components/View.d.ts
  types/hummer-env/components/ViewPager.d.ts
  types/hummer-env/hummer-env-tests.ts
  types/hummer-env/index.d.ts
  types/hummer-env/interface/event.ts
  types/hummer-env/interface/info.ts
  types/hummer-env/interface/style.d.ts
  types/hummer-env/interface/style.ts
Labels: Self Merge, Author is Owner, No Other Owners

#57967 [navermaps] update ReverseGeocodeResponse v2
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#57968 [@types/qlik-engineapi] Correct return type of getDocList in qlik-engineapi
  types/qlik-engineapi/index.d.ts
  types/qlik-engineapi/qlik-engineapi-tests.ts
Labels: Self Merge, Owner Approved

#57578 feat(amplitude-js): Add cookieStorage. Closes #57387
  types/amplitude-js/amplitude-js-tests.ts
  types/amplitude-js/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#57894 Add status codes for ApplePaySession interface according to documentation
  types/braintree-web/modules/apple-pay.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Self Merge, Owner Approved

#57973 cfenv types updated
  types/cfenv/cfenv-tests.ts
  types/cfenv/index.d.ts
Labels: Self Merge, Owner Approved

#57974 [Memoizee] Added string as a possible type to options/promise
  types/memoizee/index.d.ts
  types/memoizee/memoizee-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#57592 @types/Coingecko-api Add property include_24hr_change to SimplePriceParams
  types/coingecko-api/coingecko-api-tests.ts
  types/coingecko-api/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved

#57975 Fix typo "defaul"
  types/node/process.d.ts
  types/node/v12/globals.d.ts
  types/node/v14/process.d.ts
  types/node/v16/process.d.ts
  types/p5/lib/addons/p5.sound.d.ts
  types/parse/parse-tests.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Critical package, Too Many Owners

#57961 update(postcss-calc): v8.1 bump
  types/postcss-calc/index.d.ts
  types/postcss-calc/package.json
  types/postcss-calc/postcss-calc-tests.ts
  types/postcss-calc/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Check Config

#57959 [@types/three] Fix OBB.intersectsOBB argument not being optional
  types/three/examples/jsm/math/OBB.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#57943 [react-instantsearch] Add DynamicWidgets
  types/react-instantsearch-core/index.d.ts
  types/react-instantsearch-core/react-instantsearch-core-tests.tsx
  types/react-instantsearch-dom/index.d.ts
  types/react-instantsearch-dom/react-instantsearch-dom-tests.tsx
  types/react-instantsearch/dom.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved

#57983 [googletag] add PrivacySettingsConfig.nonPersonalizedAds and improve code comments
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
  types/googletag/ts3.9/googletag-tests.ts
  types/googletag/ts3.9/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#57743 [mongoose-paginate-v2] fix(custom-labels): can be false to be excluded from response
  types/mongoose-paginate-v2/index.d.ts
  types/mongoose-paginate-v2/mongoose-paginate-v2-tests.ts
Labels: Self Merge, Edits Owners

#57957 [spotify-api] fix typos in type names
  types/spotify-api/index.d.ts
  types/spotify-api/spotify-api-tests.ts
Labels: Self Merge, Owner Approved

#57663 Feature/57662 LevelUp interface is missing properties `status` & `isOperational()` #57662
  types/abstract-leveldown/abstract-leveldown-tests.ts
  types/abstract-leveldown/index.d.ts
  types/level-ttl/level-ttl-tests.ts
  types/levelup/index.d.ts
  types/levelup/levelup-tests.ts
  types/subleveldown/subleveldown-tests.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Edits Owners

#57965 Improve @wordpress/components types for Animate, DropdownMenu, ResizableBox, and ToolbarButton
  types/wordpress__components/animate/index.d.ts
  types/wordpress__components/dropdown-menu/index.d.ts
  types/wordpress__components/resizable-box/index.d.ts
  types/wordpress__components/toolbar-button/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Other Approved, Self Merge

#57904 [google-apps-script] Add CardService Divider and TimePicker cards
  types/google-apps-script/google-apps-script-tests.ts
  types/google-apps-script/google-apps-script.card-service.d.ts
Labels: Self Merge, Owner Approved

#57971 Add new @lerna/package-graph definitions
  types/lerna__package-graph/index.d.ts
  types/lerna__package-graph/lerna__package-graph-tests.ts
  types/lerna__package-graph/lib/cyclic-package-graph-node.d.ts
  types/lerna__package-graph/lib/package-graph-node.d.ts
  types/lerna__package-graph/tsconfig.json
  types/lerna__package-graph/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#57988 node-forge Update version to v1.0.0
  types/node-forge/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#57972 prosemirror-model@1.16.0: add whitespace option to NodeSpec
  types/prosemirror-model/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#57997 [watch] Use correct types for 1.x
  types/watch/index.d.ts
  types/watch/watch-tests.ts
Labels: Other Approved, Self Merge

#57808 :tada: remove `webpack-dev-server`
  notNeededPackages.json
  types/poi/package.json
  types/poi/tsconfig.json
  types/react-dev-utils/package.json
  types/react-dev-utils/tsconfig.json
  types/webpack-dev-server/index.d.ts
  types/webpack-dev-server/package.json
  types/webpack-dev-server/tsconfig.json
  types/webpack-dev-server/tslint.json
  types/webpack-dev-server/v3/index.d.ts
  types/webpack-dev-server/v3/package.json
  types/webpack-dev-server/v3/tsconfig.json
  types/webpack-dev-server/v3/tslint.json
  types/webpack-dev-server/v3/webpack-dev-server-tests.ts
  types/webpack-dev-server/webpack-dev-server-tests.ts
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package

#57897 feat(abstract-things): new type definition
  types/abstract-things/abstract-things-tests.ts
  types/abstract-things/events/index.d.ts
  types/abstract-things/index.d.ts
  types/abstract-things/thing.d.ts
  types/abstract-things/tsconfig.json
  types/abstract-things/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#58004 [miniprogram]add some api types
  types/miniprogram/index.d.ts
  types/miniprogram/miniprogram-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57640 update(onfleet__node-onfleet): add GetTaskResult in Task Type
  types/onfleet__node-onfleet/Resources/Tasks.d.ts
  types/onfleet__node-onfleet/onfleet__node-onfleet-tests.ts
Labels: Self Merge

#57837 [apollo-upload-client] Update dependencies
  types/apollo-upload-client/apollo-upload-client-tests.ts
  types/apollo-upload-client/index.d.ts
  types/apollo-upload-client/package.json
  types/apollo-upload-client/public/ReactNativeFile.d.ts
  types/apollo-upload-client/public/createUploadLink.d.ts
  types/apollo-upload-client/public/formDataAppendFile.d.ts
  types/apollo-upload-client/public/isExtractableFile.d.ts
  types/apollo-upload-client/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved, Check Config

#57960 clownface: isList added in v1.4
  types/clownface/clownface-tests.ts
  types/clownface/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#57996 [uuid] fix: Add package.json to package's exports
  types/uuid/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Check Config

#57951 Fix typings for @lerna/package
  types/lerna__package/index.d.ts
  types/lerna__package/lerna__package-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#57987 Updated type definitions for clamscan
  types/clamscan/clamscan-tests.ts
  types/clamscan/index.d.ts
  types/clamscan/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#57989 [Serverless] Add types for CloudFormation EventBridge rules
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Self Merge, Owner Approved

#57998 [sweet-pubsub] Added Typings for sweet-pubsub
  types/sweet-pubsub/index.d.ts
  types/sweet-pubsub/sweet-pubsub-tests.ts
  types/sweet-pubsub/tsconfig.json
  types/sweet-pubsub/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#57954 [nodepub] Added new definition
  types/nodepub/index.d.ts
  types/nodepub/nodepub-tests.ts
  types/nodepub/tsconfig.json
  types/nodepub/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#57413 [@types/plotly.js] Update Plotly toImage and downloadImage API
  types/plotly.js/index.d.ts
  types/plotly.js/test/core-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#57809 Add additional methods to the function, and expand convert type
  types/koa-convert/index.d.ts
  types/koa-convert/koa-convert-tests.ts
Labels: Other Approved, Unmerged, Self Merge

#58016 update(zingchart): Update typings for offsetEnd/Start
  types/zingchart/es6/index.d.ts
  types/zingchart/zingchart-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#57858 Add types for fake-diff
  types/fake-diff/fake-diff-tests.ts
  types/fake-diff/index.d.ts
  types/fake-diff/tsconfig.json
  types/fake-diff/tslint.json
Labels: Other Approved, Unmerged, New Definition, Self Merge, Maintainer Approved

#58008 fix(metro): annotate deprecated options
  types/metro/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#57847 :tada: remove 'express-rate-limit' as of v6.0.0
  notNeededPackages.json
  types/express-rate-limit/express-rate-limit-tests.ts
  types/express-rate-limit/index.d.ts
  types/express-rate-limit/tsconfig.json
  types/express-rate-limit/tslint.json
  types/express-rate-limit/v2/express-rate-limit-tests.ts
  types/express-rate-limit/v2/index.d.ts
  types/express-rate-limit/v2/tsconfig.json
  types/express-rate-limit/v2/tslint.json
  types/express-rate-limit/v3/express-rate-limit-tests.ts
  types/express-rate-limit/v3/index.d.ts
  types/express-rate-limit/v3/tsconfig.json
  types/express-rate-limit/v3/tslint.json
  types/rate-limit-redis/package.json
Labels: Popular package, Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#58009 [ESLint] fix ValidTestCase
  types/eslint/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#58011 Update json-diff to 0.7.1
  types/json-diff/index.d.ts
  types/json-diff/json-diff-tests.ts
Labels: Other Approved, Self Merge, Edits Owners

#57692 auth0 Option dictionary for verifyEmailCode
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#58026 Indy-sdk fix: createRevocationState parameter type issue
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Self Merge, Owner Approved

#58024 update(archiver): version bump
  types/archiver/archiver-tests.ts
  types/archiver/index.d.ts
  types/archiver/tslint.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#58032 [forge-viewer] update for version 7.59
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#57999 [bwip-js] Fix alttext type - should be string
  types/bwip-js/bwip-js-tests.ts
  types/bwip-js/index.d.ts
Labels: Self Merge, Owner Approved

#58014 Meteor hot-module-replacement types
  types/meteor/README.md
  types/meteor/globals/reactive-dict.d.ts
  types/meteor/hot-module-replacement.d.ts
  types/meteor/index.d.ts
  types/meteor/test/globals/meteor-tests.ts
  types/meteor/test/meteor-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57470 [cavy] Infer props from native components
  types/cavy/cavy-tests.tsx
  types/cavy/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved

#57469 [cavy] Tester requires a single child
  types/cavy/cavy-tests.tsx
  types/cavy/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved

#58027 fix: add safelist property to TailwindConfig interface
  types/tailwindcss/tailwind-config.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#57966 fix: add support for ts3.9
  types/aws4/aws4-tests.ts
  types/aws4/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#58048 :tada: remove `postcss-calc` as of 8.2.0
  notNeededPackages.json
  types/postcss-calc/index.d.ts
  types/postcss-calc/package.json
  types/postcss-calc/postcss-calc-tests.ts
  types/postcss-calc/tsconfig.json
  types/postcss-calc/tslint.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#58022 Meteor: scripts/generate-globals updates
  types/meteor/globals/accounts-base.d.ts
  types/meteor/globals/meteor.d.ts
  types/meteor/globals/mongo.d.ts
  types/meteor/globals/templating.d.ts
  types/meteor/scripts/generate-globals
  types/meteor/test/globals/meteor-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Check Config

#58020 Meteor: use modern namespace for local modules
  types/meteor/accounts-base.d.ts
  types/meteor/blaze.d.ts
  types/meteor/browser-policy-common.d.ts
  types/meteor/check.d.ts
  types/meteor/ddp-rate-limiter.d.ts
  types/meteor/ddp.d.ts
  types/meteor/ejson.d.ts
  types/meteor/email.d.ts
  types/meteor/globals/accounts-base.d.ts
  types/meteor/globals/blaze.d.ts
  types/meteor/globals/browser-policy-common.d.ts
  types/meteor/globals/check.d.ts
  types/meteor/globals/ddp-rate-limiter.d.ts
  types/meteor/globals/ddp.d.ts
  types/meteor/globals/ejson.d.ts
  types/meteor/globals/email.d.ts
  types/meteor/globals/http.d.ts
  types/meteor/globals/meteor.d.ts
  types/meteor/globals/mongo.d.ts
  types/meteor/globals/random.d.ts
  types/meteor/globals/session.d.ts
  types/meteor/globals/tiny-test.d.ts
  types/meteor/globals/tools.d.ts
  types/meteor/globals/tracker.d.ts
  types/meteor/http.d.ts
  types/meteor/meteor.d.ts
  types/meteor/mongo.d.ts
  types/meteor/random.d.ts
  types/meteor/session.d.ts
  types/meteor/tiny-test.d.ts
  types/meteor/tools.d.ts
  types/meteor/tracker.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#58055 b2a: added base64url encode/decode function types (v1.1.0)
  types/b2a/b2a-tests.ts
  types/b2a/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#57788 fix(json-merge-patch): apply generics and remove custom json types
  types/json-merge-patch/index.d.ts
  types/json-merge-patch/json-merge-patch-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#58053 [mockjs] Fix typo
  types/mockjs/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#58010 fix(chrome): fix tabIds to a number array
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Owner Approved

#58031 Adds missing error for optimized function in svgo
  types/svgo/index.d.ts
  types/svgo/svgo-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved

#58056 Added async function signatures for test-console package
  types/test-console/index.d.ts
  types/test-console/test-console-tests.ts
Labels: Self Merge, Owner Approved

#58054 update(karma): `refreshFile` added and some minor changes
  types/karma/index.d.ts
  types/karma/karma-tests.ts
  types/karma/lib/constants.d.ts
  types/karma/package.json
  types/karma/tslint.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#58057 Google apps script
  types/google-apps-script/google-apps-script-tests.ts
  types/google-apps-script/google-apps-script.card-service.d.ts
Labels: Self Merge, Owner Approved

#58064 update(karma): remove v4 sources
  types/karma/v4/index.d.ts
  types/karma/v4/karma-tests.ts
  types/karma/v4/lib/constants.d.ts
  types/karma/v4/package.json
  types/karma/v4/tsconfig.json
  types/karma/v4/tslint.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#57741 @types/express-useragent add isMobileNative
  types/express-useragent/express-useragent-tests.ts
  types/express-useragent/index.d.ts
Labels: Other Approved, Unmerged, Self Merge

#58069 [luxon] Add new Duration#toHuman() method
  types/luxon/src/duration.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#58063 lockfile-info: create types
  types/lockfile-info/index.d.ts
  types/lockfile-info/lockfile-info-tests.ts
  types/lockfile-info/tsconfig.json
  types/lockfile-info/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#57538 [@types/carbon-components-react] Update types to match 7.49.0
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/index.d.ts
  types/carbon-components-react/lib/components/ComposedModal/ComposedModal.d.ts
  types/carbon-components-react/lib/components/DataTable/TableToolbarSearch.d.ts
  types/carbon-components-react/lib/components/FileUploader/FileUploaderButton.d.ts
  types/carbon-components-react/lib/components/FileUploader/FileUploaderDropContainer.d.ts
  types/carbon-components-react/lib/components/Menu/Menu.d.ts
  types/carbon-components-react/lib/components/Modal/Modal.d.ts
  types/carbon-components-react/lib/components/Popover/index.d.ts
  types/carbon-components-react/lib/components/Search/Search.d.ts
  types/carbon-components-react/lib/components/Switch/Switch.d.ts
  types/carbon-components-react/lib/components/Tab/Tab.d.ts
  types/carbon-components-react/lib/components/TimePickerSelect/TimePickerSelect.d.ts
  types/carbon-components-react/lib/components/Toggle/Toggle.Skeleton.d.ts
  types/carbon-components-react/lib/components/UIShell/HeaderMenu.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#58073 Remove self as maintainer on relay-runtime
  types/relay-runtime/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#58041 [gulp-changed]: Replace deprecated `compareSha1Digest` with `compareContents`
  types/gulp-changed/gulp-changed-tests.ts
  types/gulp-changed/index.d.ts
Labels: Self Merge, Owner Approved

#58062 sinon-sandbox: add type defs
  types/sinon-sandbox/index.d.ts
  types/sinon-sandbox/sinon-sandbox-tests.ts
  types/sinon-sandbox/tsconfig.json
  types/sinon-sandbox/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#58038 Lesgo: fix lesgo types definition bugs for 0.6.0
  types/lesgo/index.d.ts
  types/lesgo/lesgo-tests.ts
  types/lesgo/middlewares/errorHttpResponseMiddleware.d.ts
  types/lesgo/middlewares/httpMiddleware.d.ts
  types/lesgo/middlewares/index.d.ts
  types/lesgo/middlewares/normalizeHttpRequestMiddleware.d.ts
  types/lesgo/middlewares/normalizeSQSMessageMiddleware.d.ts
  types/lesgo/middlewares/successHttpResponseMiddleware.d.ts
  types/lesgo/middlewares/verifyJwtMiddleware.d.ts
  types/lesgo/package.json
  types/lesgo/services/AuroraDbService.d.ts
  types/lesgo/services/DynamoDbService.d.ts
  types/lesgo/services/ElasticCacheService.d.ts
  types/lesgo/services/ElasticsearchService.d.ts
  types/lesgo/services/FirebaseAdminService.d.ts
  types/lesgo/services/JWTService.d.ts
  types/lesgo/services/S3Service.d.ts
  types/lesgo/services/SQSService.d.ts
  types/lesgo/services/index.d.ts
  types/lesgo/services/pagination/LengthAwarePaginator.d.ts
  types/lesgo/services/pagination/Paginator.d.ts
  types/lesgo/tests/services/AuroraDbService.ts
  types/lesgo/tests/services/DynamoDbService.ts
  types/lesgo/tests/services/ElasticsearchService.ts
  types/lesgo/tests/services/FirebaseAdminService.ts
  types/lesgo/tests/services/JWTService.ts
  types/lesgo/tests/services/LoggerService.ts
  types/lesgo/tests/services/S3Service.ts
  types/lesgo/tests/services/SQSService.ts
  types/lesgo/tests/services/pagination/index.ts
  types/lesgo/utils/cache.d.ts
  types/lesgo/utils/crypto.d.ts
  types/lesgo/utils/db.d.ts
  types/lesgo/utils/dynamodb.d.ts
  types/lesgo/utils/elasticsearch.d.ts
  types/lesgo/utils/isEmpty.d.ts
  types/lesgo/utils/logger.d.ts
  types/lesgo/utils/objectStore.d.ts
  types/lesgo/utils/prepSQLInsertParams.d.ts
  types/lesgo/utils/prepSQLUpdateParams.d.ts
  types/lesgo/utils/queue.d.ts
  types/lesgo/utils/validateFields.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#58042 vexflow: add parameters to openGroup() in contexts
  types/vexflow/index.d.ts
  types/vexflow/vexflow-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#58080 Add ToolbarGroup to @wordpress/components
  types/wordpress__components/dropdown-menu/index.d.ts
  types/wordpress__components/index.d.ts
  types/wordpress__components/toolbar-group/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Other Approved, Self Merge

#57876 [braintree-web] Add localPayment types
  types/braintree-web/index.d.ts
  types/braintree-web/modules/local-payment.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Self Merge, Owner Approved

#58087 [pdfmake] added min module types
  types/pdfmake/build/pdfmake.min.d.ts
  types/pdfmake/test/pdfmake-module-browser-min-tests.ts
  types/pdfmake/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved

#58077 Add Guide to @wordpress/components
  types/wordpress__components/guide/index.d.ts
  types/wordpress__components/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Other Approved, Self Merge

#58098 added node-summary type declarations
  types/node-summary/index.d.ts
  types/node-summary/node-summary-tests.ts
  types/node-summary/tsconfig.json
  types/node-summary/tslint.json
Labels: New Definition

#58065 add(webp-in-css): new definition
  types/webp-in-css/index.d.ts
  types/webp-in-css/package.json
  types/webp-in-css/tsconfig.json
  types/webp-in-css/tslint.json
  types/webp-in-css/webp-in-css-tests.ts
Labels: New Definition

#57795 [hl7] Added definitions
  types/hl7/events/adt.event.d.ts
  types/hl7/events/base.event.d.ts
  types/hl7/events/index.d.ts
  types/hl7/events/omg.event.d.ts
  types/hl7/events/orm.event.d.ts
  types/hl7/events/oru.event.d.ts
  types/hl7/events/siu.event.d.ts
  types/hl7/hl7-tests.ts
  types/hl7/index.d.ts
  types/hl7/segments/ail.segment.d.ts
  types/hl7/segments/ais.segment.d.ts
  types/hl7/segments/index.d.ts
  types/hl7/segments/msh.segment.d.ts
  types/hl7/segments/obr.segment.d.ts
  types/hl7/segments/obx.segment.d.ts
  types/hl7/segments/orc.segment.d.ts
  types/hl7/segments/pid.segment.d.ts
  types/hl7/segments/pv1.segment.d.ts
  types/hl7/tsconfig.json
  types/hl7/tslint.json
Labels: New Definition, Check Config

#57694 history package. push and restore functions are able to take 2 objects as 2 arguments
  types/history/index.d.ts
Labels: Critical package, Untested Change, Unreviewed

#58101 react-pdf needs to target es2015
  types/react-pdf/tsconfig.json
Labels: Popular package, Check Config

#58100 Update @types/eslint-scope to solve issue with matching version 3.7.2
  types/eslint-scope/eslint-scope-tests.ts
  types/eslint-scope/index.d.ts
Labels: Critical package

#58084 fix: add type `isDestroyed` for `prosemirror-view`
  types/prosemirror-view/index.d.ts
Labels: Other Approved, Popular package, Untested Change, Edits Owners

#58082 postcss-less > Fix incorrect generic type parameter
  types/postcss-less/index.d.ts
Labels: Other Approved, Owner Approved, Untested Change

#58067 [ink-text-animation] Add implicit types for children
  types/ink-text-animation/index.d.ts
Labels: Owner Approved, Untested Change

#57867 Stricter types for Chrome APIs
  types/chrome/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#58103 Fix return type of yog's BigPipe.destroy
  types/yog-bigpipe/index.d.ts
Labels: Untested Change

#58039 Update graphql dependency version to 16.2.0
  types/graphql-upload/index.d.ts
  types/graphql-upload/package.json
Labels: Popular package, Untested Change

#58045 Updates for Relay 13
  types/react-relay/index.d.ts
  types/react-relay/relay-hooks/MatchContainer.d.ts
  types/react-relay/relay-hooks/helpers.d.ts
  types/react-relay/test/react-relay-tests.tsx
  types/react-relay/test/relay-hooks-tests.tsx
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
  types/relay-runtime/lib/store/readInlineData.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Other Approved, Popular package, Owner Approved, Edits multiple packages

#58033 [final-form-focus] Add generic for InitialFormValues
  types/final-form-focus/index.d.ts
Labels: Owner Approved, Untested Change

#57879 [jquery/v2] .not(array)
  types/jquery/v2/index.d.ts
  types/jquery/v2/jquery-tests.ts
Labels: Critical package

#58025 Add type defs for ThreeDSecure.on(...) method for braintree-web package
  types/braintree-web/modules/three-d-secure.d.ts
Labels: Popular package, Untested Change

#58013 metadataCueParsed event - Update index.d.ts
  types/jwplayer/index.d.ts
Labels: Untested Change

#58001 [@types/pg] Add missing options config
  types/pg/index.d.ts
Labels: Popular package, Untested Change

#57991 [spotify-web-api-node] Improve `after` property type
  types/spotify-web-api-node/index.d.ts
Labels: Untested Change

#57982 [@tryghost/content-api] update `index.d.ts` to reflect the changes in the **Ghost API Versioning**
  types/tryghost__content-api/index.d.ts
Labels: Untested Change

#57980 add: add property displayTextRenderer in interface of types/react-typing-effect
  types/react-typing-effect/index.d.ts
Labels: Untested Change

#57937 Add another possible combination of arguments for jQuery's .get() and…
  types/jquery/JQueryStatic.d.ts
  types/jquery/test/example-tests.ts
Labels: Critical package

#58083 node-mailjet: Add delete method
  types/node-mailjet/index.d.ts
  types/node-mailjet/node-mailjet-tests.ts
Labels: Other Approved, Self Merge

#58059 pacote: add missing `packumentCache` option
  types/pacote/index.d.ts
  types/pacote/pacote-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#58106 Add types for ComboboxControl to @wordpress/components
  types/wordpress__components/combobox-control/index.d.ts
  types/wordpress__components/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Self Merge, Owner Approved

#58107 Update ineum module 216
  types/ineum/index.d.ts
  types/ineum/ineum-tests.ts
Labels: Self Merge, Owner Approved

#58086 [spotify-web-api-node] fix wrong return type in getMySavedShows method
  types/spotify-web-api-node/index.d.ts
  types/spotify-web-api-node/spotify-web-api-node-tests.ts
Labels: Other Approved, Self Merge

#57711 Fixed capabilities and mailbox types
  types/imapflow/index.d.ts
Labels: Unmerged, Self Merge, Untested Change

#58058 Add Tip and VisuallyHidden to @wordpress/components
  types/wordpress__components/index.d.ts
  types/wordpress__components/tip/index.d.ts
  types/wordpress__components/ui/context/wordpress-component.d.ts
  types/wordpress__components/visually-hidden/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Self Merge, Owner Approved

#58123 [@types/hdkey] Add missing param definition for fromMasterSeed function (ver. 2.0.1)
  types/hdkey/hdkey-tests.ts
  types/hdkey/index.d.ts
Labels: Self Merge, Owner Approved
