Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2022-04, with the labels that each got.

#59070 Update adm-zip types to v0.5.9
  types/adm-zip/adm-zip-tests.ts
  types/adm-zip/index.d.ts
  types/adm-zip/util.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#59638 Bug-fix and more specfiic types for node-dijkstra
  types/node-dijkstra/index.d.ts
  types/node-dijkstra/node-dijkstra-tests.ts
Labels: Self Merge, Owner Approved

#59263 [Nightwatch] Add: types for BDD testing
  types/nightwatch/index.d.ts
  types/nightwatch/test/nightwatch-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59646 [@mapbox/maki] Fix typings for Maki v7
  types/mapbox__maki/index.d.ts
  types/mapbox__maki/mapbox__maki-tests.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#59656 Update encoding-japanese for v2
  types/encoding-japanese/index.d.ts
  types/encoding-japanese/test/encoding-japanese-tests.cjs.ts
Labels: Self Merge, Owner Approved

#59643 Add comments to @ckeditor/ckeditor5-ui binding methods
  types/ckeditor__ckeditor5-ui/ckeditor__ckeditor5-ui-tests.ts
  types/ckeditor__ckeditor5-ui/src/bindings/clickoutsidehandler.d.ts
  types/ckeditor__ckeditor5-ui/src/bindings/injectcsstransitiondisabler.d.ts
  types/ckeditor__ckeditor5-ui/src/bindings/preventdefault.d.ts
  types/ckeditor__ckeditor5-ui/src/bindings/submithandler.d.ts
  types/ckeditor__ckeditor5-ui/src/view.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#59416 @types/dockerode - Improve typings for createVolume
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#59672 [node-telegram-bot-api] Add `approveChatJoinRequest` and `declineChatJoinRequest` functions
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59199 [object-fit-images] Fix name: objectFillImages -> objectFitImages
  types/object-fit-images/index.d.ts
  types/object-fit-images/object-fit-images-tests.ts
Labels: Self Merge, Maintainer Approved

#59678 sharp: add types for jp2() that is used for jpeg 2000 output
  types/sharp/index.d.ts
  types/sharp/sharp-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59340 Add Typings for Auth0 getLog[s] methods
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#59424 Opentok v2.13.0 - Broadcast, SIP, Stream API updates
  types/opentok/index.d.ts
  types/opentok/opentok-tests.ts
Labels: Self Merge, Owner Approved

#59675 [@types/pdfkit] Add font to PDFDocumentOptions
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#59687 [video.js] Add `click` property to UserActions
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#59693 [node-telegram-bot-api] Fix typo in `approveChatJoinRequest`
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Owner Approved

#59694 fix(atlassian-connect-js): improve listener signature of onAny event methods
  types/atlassian-connect-js/atlassian-connect-js-tests.ts
  types/atlassian-connect-js/index.d.ts
Labels: Self Merge, Owner Approved

#59507 feat: add types for svg-baker-runtime
  types/svg-baker-runtime/index.d.ts
  types/svg-baker-runtime/src/browser-sprite.config.d.ts
  types/svg-baker-runtime/src/browser-sprite.d.ts
  types/svg-baker-runtime/src/browser-symbol.d.ts
  types/svg-baker-runtime/src/sprite.config.d.ts
  types/svg-baker-runtime/src/sprite.d.ts
  types/svg-baker-runtime/src/symbol.d.ts
  types/svg-baker-runtime/svg-baker-runtime-tests.ts
  types/svg-baker-runtime/tsconfig.json
  types/svg-baker-runtime/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59671 [react-infinite-scroller] Fix tests when `ReactFragment` does not include `{}`
  types/react-infinite-scroller/react-infinite-scroller-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#59477 @types/dockerode Add missing elements to ContainerCreateOptions
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#58725 [consumer-data-standards] Deconstify enums
  types/consumer-data-standards/tslint.json
Labels: Self Merge, Maintainer Approved

#59667 Add @gatsbyjs/reach-router types
  types/gatsbyjs__reach-router/gatsbyjs__reach-router-tests.tsx
  types/gatsbyjs__reach-router/index.d.ts
  types/gatsbyjs__reach-router/tsconfig.json
  types/gatsbyjs__reach-router/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59714 [@ember/component/helper] Make `FunctionBasedHelper` an (abstract) constructor type
  types/ember__component/helper.d.ts
  types/ember__component/test/helper.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#59715 [@ember/component/helper] Handle missing helper signatures more gracefully
  types/ember__component/helper.d.ts
  types/ember__component/test/helper.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#59696 add fake-lodash-pure-js types
  types/fake-lodash-pure-js/fake-lodash-pure-js-tests.ts
  types/fake-lodash-pure-js/index.d.ts
  types/fake-lodash-pure-js/tsconfig.json
  types/fake-lodash-pure-js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59711 [atlassian-connect-js] Updates from Atlassian, other improvements
  types/atlassian-connect-js/atlassian-connect-js-tests.ts
  types/atlassian-connect-js/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59662 Adds types for the 'node-postal' package
  types/node-postal/index.d.ts
  types/node-postal/node-postal-tests.ts
  types/node-postal/tsconfig.json
  types/node-postal/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59516 Add 'ignorerounding' flag to Option object in `audiosprite`
  types/audiosprite/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#59623 [serverless] add filterPatterns attribute in event/stream
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Other Approved, Self Merge

#59736 [googletag] increase major version to 2.0
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
  types/googletag/ts4.2/googletag-tests.ts
  types/googletag/ts4.2/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#59652 [mapbox__mapbox-sdk] Add types for static style parameters
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Other Approved, Self Merge

#59605 [wordpress__components] Updated typings for v11
  types/wordpress__editor/index.d.ts
  types/wordpress__editor/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#59511 [wordpress__data] Updated typings for version 6.0.0
  types/wordpress__data/index.d.ts
  types/wordpress__data/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#59499 Add messageId to track()
  types/analytics-node/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#59461 fix: aws4 request body type can be a Buffer
  types/aws4/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#59744 [iobroker] fix definition of SettableState type
  types/iobroker/index.d.ts
  types/iobroker/iobroker-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#59695 Opentok v2.13.0 support for patching archives & broadcasts
  types/opentok/index.d.ts
  types/opentok/opentok-tests.ts
Labels: Other Approved, Self Merge

#59491 espruino: add types for BLE interface
  types/espruino/espruino-tests.ts
  types/espruino/index.d.ts
Labels: Self Merge, Owner Approved

#59184 [heap] Add undefined to method return types
  types/heap/heap-tests.ts
  types/heap/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved

#59762 [ethereum-block-by-date] update types for version 1.4.3
  types/ethereum-block-by-date/ethereum-block-by-date-tests.ts
  types/ethereum-block-by-date/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners, Edits Owners

#59664 [musickit-js] add resource types
  types/musickit-js/MusicKit.API.d.ts
  types/musickit-js/MusicKit.Library.d.ts
  types/musickit-js/test/musickit-js-tests.ts
Labels: Other Approved, Self Merge

#59770 update(zingchart): add typings for tooltip.htmlMode and valueBox.rules
  types/zingchart/es6/index.d.ts
  types/zingchart/zingchart-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#59482 fix(uglify-js): add 'webkit' compression option
  types/uglify-js/index.d.ts
  types/uglify-js/uglify-js-tests.ts
Labels: Unmerged, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#59717 [itemsjs] Add types for itemsjs
  types/itemsjs/index.d.ts
  types/itemsjs/itemsjs-tests.ts
  types/itemsjs/tsconfig.json
  types/itemsjs/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59731 Remove @orbit-ui/react-components
  notNeededPackages.json
  types/orbit-ui__react-components/index.d.ts
  types/orbit-ui__react-components/orbit-ui__react-components-tests.tsx
  types/orbit-ui__react-components/package.json
  types/orbit-ui__react-components/tsconfig.json
  types/orbit-ui__react-components/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#59730 fix(monday-sdk-js): update GetResponse to reflect the nested data structure
  types/monday-sdk-js/index.d.ts
  types/monday-sdk-js/test/monday-sdk-js-global.test.ts
  types/monday-sdk-js/test/monday-sdk-js-module.test.ts
Labels: Self Merge, Owner Approved

#59374 feat: generic mapbox response types
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Self Merge, Owner Approved

#59776 Update webrtc for TS 4.7
  types/w3c-image-capture/index.d.ts
  types/webrtc/RTCPeerConnection.d.ts
  types/webrtc/index.d.ts
  types/webrtc/test/RTCPeerConnection.ts
Labels: Edits multiple packages

#59517 fix(remark-prism): Increase option flexibility
  types/remark-prism/index.d.ts
  types/remark-prism/remark-prism-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#59739 [omggif] Remove Node dependency
  types/omggif/index.d.ts
  types/omggif/omggif-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#59642 typings for yup-locale-pl
  types/yup-locale-pl/index.d.ts
  types/yup-locale-pl/tsconfig.json
  types/yup-locale-pl/tslint.json
  types/yup-locale-pl/yup-locale-pl-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#59767 [react-datepicker] Add changes from v4.3.0 -> v4.4.0
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#59648 [@types/enzyme] Add the `renderProp` definition to ReactWrapper.
  types/enzyme/enzyme-tests.tsx
  types/enzyme/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#59345 Refactor @ckeditor/ckeditor5-engine operations
  types/ckeditor__ckeditor5-engine/OTHER_FILES.txt
  types/ckeditor__ckeditor5-engine/ckeditor__ckeditor5-engine-tests.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/attributeoperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/detachoperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/insertoperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/markeroperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/mergeoperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/moveoperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/nooperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/operation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/operationfactory.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/renameoperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/rootattributeoperation.d.ts
  types/ckeditor__ckeditor5-engine/src/model/operation/splitoperation.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Check Config

#59746 [react] Remove unstable_createMutableSource
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/vite-plugin-react-svg/index.d.ts
  types/vite-plugin-react-svg/tsconfig.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#59740 added types for styletron-engine-monolithic
  types/styletron-engine-monolithic/index.d.ts
  types/styletron-engine-monolithic/styletron-engine-monolithic-tests.ts
  types/styletron-engine-monolithic/tsconfig.json
  types/styletron-engine-monolithic/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#57886 feat(@rifat/miio): new type definition
  types/rifat__miio/index.d.ts
  types/rifat__miio/rifat__miio-tests.ts
  types/rifat__miio/tsconfig.json
  types/rifat__miio/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59631 [jscodeshift] fileInfo.path is relative, not absolute
  types/jscodeshift/src/core.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#59641 [react-native] 0.68.0 add type definition for ScrollView automaticallyAdjustKeyboardInsets
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#59785 [ramda] fix: append
  types/ramda/index.d.ts
  types/ramda/test/append-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59683 feat(prettier): add singleAttributePerLine, update pluginSearchDirs
  types/prettier/index.d.ts
  types/prettier/prettier-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#59728 [@types/discord-rpc] Fixes #59650
  types/discord-rpc/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change

#59707 update yauzl types for better representation of core logic
  types/yauzl/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#59726 [imapflow] feat: add accessToken for xoauth support
  types/imapflow/imapflow-tests.ts
  types/imapflow/index.d.ts
Labels: Self Merge, Maintainer Approved

#59722 Fix spelling typo in chrome
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#59201 wavesurfer.js: Regions plugin improvements
  types/wavesurfer.js/src/plugin/regions.d.ts
  types/wavesurfer.js/wavesurfer.js-tests.ts
Labels: Self Merge, Owner Approved

#59829 [intercom-web] add showArticle method
  types/intercom-web/index.d.ts
  types/intercom-web/intercom-web-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59795 feat(globaloffensive): add types for globaloffensive
  types/globaloffensive/enums.d.ts
  types/globaloffensive/globaloffensive-tests.ts
  types/globaloffensive/index.d.ts
  types/globaloffensive/tsconfig.json
  types/globaloffensive/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59718 Add Typings for concatjson
  types/concatjson/concatjson-tests.ts
  types/concatjson/index.d.ts
  types/concatjson/tsconfig.json
  types/concatjson/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#59245 mapbox-gl: add "number-format" to expressions
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#59819 write types for throttle-debounce v4.0
  types/throttle-debounce/index.d.ts
  types/throttle-debounce/throttle-debounce-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#59825 Added types for @americanexpress/react-seo
  types/americanexpress__react-seo/americanexpress__react-seo-tests.tsx
  types/americanexpress__react-seo/index.d.ts
  types/americanexpress__react-seo/tsconfig.json
  types/americanexpress__react-seo/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59531 Fixed paypal__checkout-server-sdk OrdersPatch.RequestData type
  types/paypal__checkout-server-sdk/lib/orders/lib.d.ts
  types/paypal__checkout-server-sdk/paypal__checkout-server-sdk-tests.ts
Labels: Self Merge, Owner Approved

#59630 add types for google.accounts (Google Identity Services js SDK)
  types/google.accounts/google.accounts-tests.ts
  types/google.accounts/index.d.ts
  types/google.accounts/tsconfig.json
  types/google.accounts/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59838 Add export map for react
  types/react/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Check Config

#59635 Add types for the 'fnv-plus' package
  types/fnv-plus/fnv-plus-tests.ts
  types/fnv-plus/index.d.ts
  types/fnv-plus/tsconfig.json
  types/fnv-plus/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#59844 [jsreport-core] Fix blobStorage option type
  types/jsreport-core/index.d.ts
  types/jsreport-core/jsreport-core-tests.ts
Labels: Self Merge, Owner Approved

#59640 mailchimp__mailchimp_transactional: Add message.sendTemplate
  types/mailchimp__mailchimp_transactional/index.d.ts
  types/mailchimp__mailchimp_transactional/mailchimp__mailchimp_transactional-tests.ts
Labels: Self Merge, Owner Approved

#59832 Update mParticle WEB SDK return types and parameters
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-instance-tests.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Self Merge, Owner Approved

#59850 [react] Deprecate ReactChildren
  types/moxy__next-router-scroll/RouterScrollProvider.d.ts
  types/react-mentions/lib/utils/readConfigFromChildren.d.ts
  types/react-native-table-component/index.d.ts
  types/react-router-transition/index.d.ts
  types/react/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package, Untested Change

#59686 Update doc comments on Sharp toBuffer so that they match package documentation
  types/sharp/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#59697 Microsoft Graph - upgrade to version 2.18
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59798 [ramda] feat: omit falsy values from first argument in `or`
  types/ramda/index.d.ts
  types/ramda/test/or-tests.ts
  types/ramda/tools.d.ts
Labels: Popular package, Self Merge, Owner Approved

#59639 [pi-pir-sensor] Added types for pir-pir-sensor package
  types/pi-pir-sensor/index.d.ts
  types/pi-pir-sensor/pi-pir-sensor-tests.ts
  types/pi-pir-sensor/tsconfig.json
  types/pi-pir-sensor/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59856 Microsoft Graph - upgrade to 2.19
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#58893 ember__runloop: timer is optional for cancel
  types/ember__runloop/ember__runloop-tests.ts
  types/ember__runloop/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#59647 [mapbox-gl] Fix some types for style spec, TileJSON, things we've found internally
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#59883 add missing size prop to LineMarkSeriesProps in react-vis
  types/react-vis/index.d.ts
  types/react-vis/react-vis-tests.tsx
Labels: Self Merge, Owner Approved

#59875 [globrex] Add `flags` option
  types/globrex/globrex-tests.ts
  types/globrex/index.d.ts
Labels: Self Merge, Maintainer Approved

#59855 update(cookie): v0.5 updates
  types/cookie/cookie-tests.ts
  types/cookie/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#59629 [jasmine] Use type-safe spies for spyOnProperty
  types/jasmine/v3/index.d.ts
  types/jasmine/v3/jasmine-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#59884 Add types for bcswipe
  types/bcswipe/bcswipe-tests.ts
  types/bcswipe/index.d.ts
  types/bcswipe/tsconfig.json
  types/bcswipe/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59833 [react] Add tests for current behavior with missing or empty return statements and assignability to `ReactNode`
  types/react/test/index.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#59741 [wordpress__block-editor] Updated typings for v7
  types/wordpress__block-editor/index.d.ts
  types/wordpress__block-editor/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#59836 [@coinify/currency] New package definition for v1.3
  types/coinify__currency/coinify__currency-tests.ts
  types/coinify__currency/index.d.ts
  types/coinify__currency/tsconfig.json
  types/coinify__currency/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59859 Chai assert typing
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#59660 Add application to snowflake-sdk ConnectionOptions
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59845 [mongoose-paginate-v2] Remove types
  notNeededPackages.json
  types/mongoose-paginate-v2/index.d.ts
  types/mongoose-paginate-v2/mongoose-paginate-v2-tests.ts
  types/mongoose-paginate-v2/package.json
  types/mongoose-paginate-v2/tsconfig.json
  types/mongoose-paginate-v2/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#59756 Updated APIs for 1.19 beta release of GameTest Framework APIs
  types/mojang-minecraft/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#59873 Minor black-engine typing improvement
  types/black-engine/Engine.d.ts
  types/black-engine/messages/MessageBinding.d.ts
  types/black-engine/messages/MessageDispatcher.d.ts
  types/black-engine/physics/arcade/Arcade.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#59310 [@types/react-redux] mergeProps takes DispatchProp when mapDispatchToProps is undefined or null
  types/react-redux/index.d.ts
  types/react-redux/react-redux-tests.tsx
Labels: Owner Approved, Maintainer Approved, Critical package, Where is GH Actions?

#59831 @ember/object: add get fallbacks for unknown objects
  types/ember/test/ember-module-tests.ts
  types/ember/v3/test/ember-module-tests.ts
  types/ember__object/index.d.ts
  types/ember__object/test/get-set.ts
  types/ember__object/tsconfig.json
  types/ember__object/v3/index.d.ts
  types/ember__object/v3/test/get-set.ts
  types/ember__object/v3/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits multiple packages, Maintainer Approved

#59486 [@primer/octicons]: Update to 17.0.0
  types/primer__octicons/index.d.ts
  types/primer__octicons/primer__octicons-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#59830 [mapbox__mapbox-gl-traffic] New package definition for v1.0
  types/mapbox__mapbox-gl-traffic/index.d.ts
  types/mapbox__mapbox-gl-traffic/test/mapbox__mapbox-gl-traffic-tests.ts
  types/mapbox__mapbox-gl-traffic/tsconfig.json
  types/mapbox__mapbox-gl-traffic/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#58826 upate(showdown): v2 update
  types/showdown/index.d.ts
  types/showdown/showdown-tests.ts
  types/showdown/tslint.json
Labels: Popular package, Self Merge, Maintainer Approved

#59397 fix(node): missing property `readyState` on net.Socket
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v12/net.d.ts
  types/node/v12/test/net.ts
  types/node/v14/net.d.ts
  types/node/v14/test/net.ts
  types/node/v16/net.d.ts
  types/node/v16/test/net.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#59439 fix(rtlcss): amend configuration and creation options
  types/rtlcss/index.d.ts
  types/rtlcss/rtlcss-tests.ts
Labels: Author is Owner, No Other Owners

#59406 Add missing promises version for MemoryCookieStore to tough-cookie
  types/tough-cookie/index.d.ts
  types/tough-cookie/tough-cookie-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#59564 [react] Re-enable managedAttributes tests and support exactOptionalPropertyTypes flag
  types/react/index.d.ts
  types/react/test/managedAttributes.tsx
  types/react/tsconfig.json
  types/react/v16/index.d.ts
  types/react/v16/test/managedAttributes.tsx
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Check Config

#59619 [jsts] added MultiPolygon + related fixes
  types/jsts/index.d.ts
  types/jsts/jsts-tests.ts
Labels: Self Merge, Owner Approved

#59216 [@types/parse] Add additional supported aggregation options
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Self Merge, Maintainer Approved

#59781 [ramda] chore: update jsdoc
  types/ramda/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#59355 [babel__traverse] Add new method `hasNode()` to `NodePath`
  types/babel__traverse/babel__traverse-tests.ts
  types/babel__traverse/index.d.ts
  types/babel__traverse/ts4.1/babel__traverse-tests.ts
  types/babel__traverse/ts4.1/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#59894 [google-spreadsheet] add missing headerRowIndex options
  types/google-spreadsheet/google-spreadsheet-tests.ts
  types/google-spreadsheet/index.d.ts
Labels: Self Merge, Owner Approved

#59782 [ramda] feat: add 6 of the 10 missing functions
  types/ramda/OTHER_FILES.txt
  types/ramda/es/collectBy.d.ts
  types/ramda/es/on.d.ts
  types/ramda/es/partialObject.d.ts
  types/ramda/es/promap.d.ts
  types/ramda/es/splitWhenever.d.ts
  types/ramda/index.d.ts
  types/ramda/src/collectBy.d.ts
  types/ramda/src/on.d.ts
  types/ramda/src/partialObject.d.ts
  types/ramda/src/promap.d.ts
  types/ramda/src/splitWhenever.d.ts
  types/ramda/test/collectBy-tests.ts
  types/ramda/test/on-tests.ts
  types/ramda/test/partialObject-tests.ts
  types/ramda/test/promap-tests.ts
  types/ramda/test/splitWhen-tests.ts
  types/ramda/test/splitWhenever-tests.ts
  types/ramda/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Check Config

#59906 Remove ownership for elisee, by request
  types/async-lock/index.d.ts
  types/escape-html/index.d.ts
  types/recursive-readdir/index.d.ts
  types/recursive-readdir/v1/index.d.ts
  types/slate-irc/index.d.ts
Labels: Popular package, Edits multiple packages, Untested Change, Edits Owners

#59897 feat: update @nginstack/engine definitions
  types/nginstack__engine/index.d.ts
  types/nginstack__engine/nginstack__engine-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59898 feat: update @nginstack/iquery definitions
  types/nginstack__iquery/index.d.ts
  types/nginstack__iquery/nginstack__iquery-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59899 feat: update @nginstack/orm definitions
  types/nginstack__orm/index.d.ts
  types/nginstack__orm/nginstack__orm-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59902 feat: update @nginstack/web-framework definitions
  types/nginstack__web-framework/index.d.ts
  types/nginstack__web-framework/nginstack__web-framework-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59903 feat: update @nginstack/dev-tools definitions
  types/nginstack__dev-tools/index.d.ts
  types/nginstack__dev-tools/nginstack__dev-tools-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59904 feat: update @nginstack/devops definitions
  types/nginstack__devops/index.d.ts
  types/nginstack__devops/nginstack__devops-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59901 feat: update @nginstack/datasource definitions
  types/nginstack__datasource/index.d.ts
  types/nginstack__datasource/nginstack__datasource-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59900 feat: update @nginstack/jsunit definitions
  types/nginstack__jsunit/index.d.ts
  types/nginstack__jsunit/nginstack__jsunit-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59907 [auth0] Fix typo with type for DatabaseAuthenticator#signUp
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#59853 update(jasmine): v4.1 updates
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#58814 Update type defintions for echarts@4
  types/echarts/index.d.ts
  types/echarts/options/series/funnel.d.ts
Labels: Popular package, Maintainer Approved, Where is GH Actions?, Untested Change, Edits Owners

#59748 [react-dom] Add `renderToPipeableStream` and `renderToReadableStream`
  types/react-dom/server.d.ts
  types/react-dom/test/react-dom-tests.tsx
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#59749 [react-dom] Update unstable entrypoints
  types/react-dom/experimental.d.ts
  types/react-dom/next.d.ts
  types/react-dom/test/experimental-tests.tsx
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#59887 [postcss-js] Add types for postcss-js
  types/postcss-js/index.d.ts
  types/postcss-js/package.json
  types/postcss-js/postcss-js-tests.ts
  types/postcss-js/tsconfig.json
  types/postcss-js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#59880 [async-lock] Add maxOccupationTime to AsyncLockOptions
  types/async-lock/async-lock-tests.ts
  types/async-lock/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#59414 [webpack-env] add `import.meta.webpackContext` for webpack 5.70.0+
  types/webpack-env/index.d.ts
  types/webpack-env/webpack-env-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#59708 xml2js: Add ValidationError type definition
  types/xml2js/index.d.ts
  types/xml2js/xml2js-tests.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#59911 feat(@types/react-reconciler): add priority constant for `react-reconciler`
  types/react-reconciler/constant.d.ts
  types/react-reconciler/test/ReactReconcilerPriorityConstant.ts
  types/react-reconciler/test/react-reconciler-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59916 fix(@types/react-reconciler): wrong path
  types/react-reconciler/constants.d.ts
  types/react-reconciler/test/react-reconciler-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59453 Add addType to ejson
  types/ejson/ejson-tests.ts
  types/ejson/index.d.ts
Labels: Self Merge, Maintainer Approved

#59259 @types/xml2js: Replace "Function" with proper callback definition
  types/xml2js/index.d.ts
  types/xml2js/xml2js-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59908 update(find-test-names): v1.16/v1.17 updates
  types/find-test-names/find-test-names-tests.ts
  types/find-test-names/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#57599 feat(postcss-prefix-selector): add types for v1.14
  types/postcss-prefix-selector/index.d.ts
  types/postcss-prefix-selector/postcss-prefix-selector-tests.ts
  types/postcss-prefix-selector/tsconfig.json
  types/postcss-prefix-selector/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59754 [monday-sdk-js] Add missing execute function definitions
  types/monday-sdk-js/index.d.ts
  types/monday-sdk-js/test/monday-sdk-js-global.test.ts
  types/monday-sdk-js/test/monday-sdk-js-module.test.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#59925 feat(react-pdf): add support for parcel 2 and webpack 5 base on react-pdf 5.7.0
  types/react-pdf/dist/esm/entry.parcel2.d.ts
  types/react-pdf/dist/esm/entry.webpack5.d.ts
  types/react-pdf/dist/umd/entry.parcel2.d.ts
  types/react-pdf/dist/umd/entry.webpack5.d.ts
  types/react-pdf/index.d.ts
  types/react-pdf/react-pdf-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#59530 [less-middleware] Allow boolean for compress render option
  types/less-middleware/index.d.ts
  types/less-middleware/less-middleware-tests.ts
  types/less-middleware/tsconfig.json
Labels: Self Merge, Maintainer Approved

#59580 Add 8-arg version of cipher to ronomon__crypto-async
  types/ronomon__crypto-async/index.d.ts
  types/ronomon__crypto-async/ronomon__crypto-async-tests.ts
Labels: Self Merge, Owner Approved

#59578 [numjs] Make `slice` accept null
  types/numjs/index.d.ts
  types/numjs/numjs-tests.ts
Labels: Self Merge, Maintainer Approved

#59488 Better handling of event definitions in @ckeditor/ckeditor5-utils Emitter
  types/ckeditor__ckeditor5-utils/ckeditor__ckeditor5-utils-tests.ts
  types/ckeditor__ckeditor5-utils/src/emittermixin.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#59735 [node-zendesk] Fix `next_page` and `previous_page` types
  types/node-zendesk/index.d.ts
  types/node-zendesk/node-zendesk-tests.ts
Labels: Other Approved, Self Merge

#59941 [bootstrap] Allow title/content to be Element or JQuery
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
  types/bootstrap/v4/bootstrap-tests.ts
  types/bootstrap/v4/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#59930 @types/node: fix markdown format mistake
  types/node/buffer.d.ts
Labels: Maintainer Approved, Critical package, The CI failed, Untested Change

#59896 [@types/aws-api-gateway-client] Add type definition (initial commit)
  types/aws-api-gateway-client/aws-api-gateway-client-tests.ts
  types/aws-api-gateway-client/index.d.ts
  types/aws-api-gateway-client/tsconfig.json
  types/aws-api-gateway-client/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59518 [@types/carbon-components-react] Update types to match 7.55.0
  types/carbon-components-react/carbon-components-react-tests.tsx
  types/carbon-components-react/index.d.ts
  types/carbon-components-react/lib/components/Accordion/AccordionItem.d.ts
  types/carbon-components-react/lib/components/Checkbox/Checkbox.d.ts
  types/carbon-components-react/lib/components/CodeSnippet/CodeSnippet.d.ts
  types/carbon-components-react/lib/components/ComboBox/ComboBox.d.ts
  types/carbon-components-react/lib/components/ComposedModal/ComposedModal.d.ts
  types/carbon-components-react/lib/components/DatePickerInput/DatePickerInput.d.ts
  types/carbon-components-react/lib/components/Dropdown/Dropdown.d.ts
  types/carbon-components-react/lib/components/FileUploader/FileUploader.d.ts
  types/carbon-components-react/lib/components/Link/Link.d.ts
  types/carbon-components-react/lib/components/MultiSelect/MultiSelect.d.ts
  types/carbon-components-react/lib/components/OverflowMenu/OverflowMenu.d.ts
  types/carbon-components-react/lib/components/Pagination/Pagination.d.ts
  types/carbon-components-react/lib/components/ProgressBar/ProgressBar.d.ts
  types/carbon-components-react/lib/components/RadioButtonGroup/RadioButtonGroup.d.ts
  types/carbon-components-react/lib/components/SkeletonIcon/SkeletonIcon.d.ts
  types/carbon-components-react/lib/components/SkeletonIcon/index.d.ts
  types/carbon-components-react/lib/components/Tabs/Tabs.d.ts
  types/carbon-components-react/lib/components/TextArea/TextArea.d.ts
Labels: Self Merge, Maintainer Approved

#59910 feat(tx2): Add Typings
  types/tx2/index.d.ts
  types/tx2/tsconfig.json
  types/tx2/tslint.json
  types/tx2/tx2-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved
