Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2022-10, with the labels that each got.

#62494 [prompt] Add missed `hidden` attribute
  types/prompt/index.d.ts
  types/prompt/prompt-tests.ts
Labels: Self Merge, Owner Approved

#62422 Add types for locomotive-scroll
  types/locomotive-scroll/index.d.ts
  types/locomotive-scroll/locomotive-scroll-tests.ts
  types/locomotive-scroll/tsconfig.json
  types/locomotive-scroll/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62505 murmurhash3js-revisited: add seed parameter
  types/murmurhash3js-revisited/index.d.ts
  types/murmurhash3js-revisited/murmurhash3js-revisited-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#62244 [dcp-client] update
  types/dcp-client/dcp-client-tests.ts
  types/dcp-client/index.d.ts
  types/dcp-client/src/compute.d.ts
  types/dcp-client/src/wallet.d.ts
  types/dcp-client/src/worker.d.ts
  types/dcp-client/tslint.json
Labels: Self Merge, Author is Owner, Owner Approved

#62016 [newman] Improve types
  types/newman/index.d.ts
  types/newman/newman-tests.ts
Labels: Self Merge, Maintainer Approved

#62515 [twitter-text] Fix typing for `modifyIndicesFrom...`
  types/twitter-text/index.d.ts
  types/twitter-text/twitter-text-tests.ts
Labels: Self Merge, Owner Approved

#62517 Removed myself from Definitions by list
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#62504 Add types for random-web-token
  types/random-web-token/index.d.ts
  types/random-web-token/random-web-token-tests.ts
  types/random-web-token/tsconfig.json
  types/random-web-token/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62497 [node:net] Update types
  types/node/index.d.ts
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/ts4.8/net.d.ts
  types/node/ts4.8/test/net.ts
  types/node/v16/net.d.ts
  types/node/v16/ts4.8/net.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#62273 plotly.js Allow grouping of default and custom modebar buttons
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#62503 Fix for #62338: add missing UsersLogsQuery and getUserLogs typings to auth0
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#62524 Add optional message field in bootbox prompt
  types/bootbox/bootbox-tests.ts
  types/bootbox/index.d.ts
Labels: Other Approved, Self Merge

#62509 Add new types for Meteor Atmosphere package littledata:synced-cron
  types/meteor-synced-cron/README.md
  types/meteor-synced-cron/index.d.ts
  types/meteor-synced-cron/meteor-synced-cron-tests.ts
  types/meteor-synced-cron/tsconfig.json
  types/meteor-synced-cron/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62435 [telegram-web-app] popupClosed event button_id parameter
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Owner Approved

#62519 [react-big-calendar] Add `enableAutoScroll`
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#62530 [bootstrap]: Update various types
  types/bootstrap/index.d.ts
  types/bootstrap/js/dist/offcanvas.d.ts
  types/bootstrap/js/dist/scrollspy.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
  types/bootstrap/test/offcanvas-tests.ts
  types/bootstrap/test/popover-tests.ts
  types/bootstrap/test/scrollspy-tests.ts
  types/bootstrap/test/tooltip-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#62464 Add type definitions to natural-drag-animation-rbdnd npm package
  types/natural-drag-animation-rbdnd/index.d.ts
  types/natural-drag-animation-rbdnd/natural-drag-animation-rbdnd-tests.tsx
  types/natural-drag-animation-rbdnd/tsconfig.json
  types/natural-drag-animation-rbdnd/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59905 [node] remove lib: "dom"; add global Event and EventTarget, fix other global types
  types/node/buffer.d.ts
  types/node/dom-events.d.ts
  types/node/events.d.ts
  types/node/globals.d.ts
  types/node/index.d.ts
  types/node/perf_hooks.d.ts
  types/node/stream.d.ts
  types/node/stream/consumers.d.ts
  types/node/test/buffer.ts
  types/node/test/crypto.ts
  types/node/test/events.ts
  types/node/test/perf_hooks.ts
  types/node/test/stream.ts
  types/node/test/url.ts
  types/node/test/util.ts
  types/node/test/wasi.ts
  types/node/test/worker_threads.ts
  types/node/tsconfig.json
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/v16/buffer.d.ts
  types/node/v16/stream/consumers.d.ts
  types/node/worker_threads.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Check Config

#62183 spotify-api edit RecommendationsFromSeedsResponse and AlbumObjectSimplified
  types/spotify-api/index.d.ts
  types/spotify-api/spotify-api-tests.ts
Labels: Self Merge, Owner Approved

#62544 [invity_api] Update to version 1.0.9
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#62543 Fix the extraTunnelHeaders type in guacamole-common-js
  types/guacamole-common-js/index.d.ts
  types/guacamole-common-js/lib/HTTPTunnel.d.ts
  types/guacamole-common-js/test/guacamole-common-js-test.ts
Labels: Self Merge, Owner Approved, Edits Owners

#62545 [iobroker] Add ukrainian language to types
  types/iobroker/iobroker-tests.ts
  types/iobroker/objects.d.ts
Labels: Self Merge, Owner Approved

#62542 [tabulator-tables] Updates from 5.4
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#62553 Add typings for newrelic.getBrowserTimingHeader options
  types/newrelic/index.d.ts
  types/newrelic/newrelic-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#62416 node: Synchronize ts4.8 with current
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#62552 react-tag-autocomplete updates for version v6.3.0 (newTagPrefix updated to newTagText) fixes #62548
  types/react-tag-autocomplete/index.d.ts
  types/react-tag-autocomplete/react-tag-autocomplete-tests.tsx
Labels: Self Merge, Owner Approved

#62455 [sharedb] add `Connection.canSend`
  types/sharedb/lib/client.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#62540 fix for issue #59335 - dragoffset is an object with x y properties
  types/scrollbooster/index.d.ts
  types/scrollbooster/scrollbooster-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#62561 update(zingchart): fix typings for FONTSIZE and FONTFAMILY, typo for scrollXScrollY, and reorder interfaces
  types/zingchart/es6/index.d.ts
  types/zingchart/index.d.ts
  types/zingchart/zingchart-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners, Huge Change

#62331 feat(gtag.js): update item interface
  types/gtag.js/gtag.js-tests.ts
  types/gtag.js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#62496 [prompts] Update to 2.4
  types/prompts/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#62467 [@types/facebook-js-sdk] add data_access_expiration_time property to AuthResponse
  types/facebook-js-sdk/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#62458 Updating PouchDB-Find Types
  types/pouchdb-find/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change, Edits Owners

#62518 feat: create type definitions for `find-node-modules` package
  types/find-node-modules/find-node-modules-tests.ts
  types/find-node-modules/index.d.ts
  types/find-node-modules/tsconfig.json
  types/find-node-modules/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#62499 feat(ali-oss): perfact SignatureUrlOptions
  types/ali-oss/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62498 [nw.js] Fix typo
  types/nw.js/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62500 [wojtekmaj__react-daterange-picker] Fix props
  types/wojtekmaj__react-daterange-picker/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62374 feat: add missing function declaration for libsodium-wrappers
  types/libsodium-wrappers/index.d.ts
  types/libsodium-wrappers/libsodium-wrappers-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#62488 [minio] Add support for minio new way of marshaling Metadata in listObjectsV2WithMetadata
  types/minio/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#62489 Add placement types to Overlay
  types/react-bootstrap/lib/Overlay.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#62516 feat: :sparkles: add types for set-blocking
  types/set-blocking/index.d.ts
  types/set-blocking/set-blocking-tests.ts
  types/set-blocking/tsconfig.json
  types/set-blocking/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62563 Move mozilla-readability to npm package name
  types/mozilla__readability/index.d.ts
  types/mozilla__readability/mozilla__readability-tests.ts
  types/mozilla__readability/tsconfig.json
  types/mozilla__readability/tslint.json
Labels: New Definition

#62512 Add types for Cloudflare Turnstile
  types/cloudflare-turnstile/cloudflare-turnstile-tests.ts
  types/cloudflare-turnstile/index.d.ts
  types/cloudflare-turnstile/tsconfig.json
  types/cloudflare-turnstile/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62575 [auth0] add missing connection strategy oidc
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#62535 refactor(laravel-vapor): add data, cancelToken and progress properties
  types/laravel-vapor/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#62514 add @cypress/code-coverage
  types/cypress__code-coverage/cypress__code-coverage-tests.ts
  types/cypress__code-coverage/index.d.ts
  types/cypress__code-coverage/package.json
  types/cypress__code-coverage/support.d.ts
  types/cypress__code-coverage/task.d.ts
  types/cypress__code-coverage/tsconfig.json
  types/cypress__code-coverage/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62531 Create @types/node-barco-eventmaster
  types/barco-eventmaster/barco-eventmaster-tests.ts
  types/barco-eventmaster/index.d.ts
  types/barco-eventmaster/tsconfig.json
  types/barco-eventmaster/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62532 Add types for ml-classify-text
  types/ml-classify-text/index.d.ts
  types/ml-classify-text/ml-classify-text-tests.ts
  types/ml-classify-text/tsconfig.json
  types/ml-classify-text/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62570 [webpack-bundle-analyzer] Update to 4.6
  types/webpack-bundle-analyzer/index.d.ts
  types/webpack-bundle-analyzer/webpack-bundle-analyzer-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#62534 add types for hsl-to-rgb-for-reals
  types/hsl-to-rgb-for-reals/hsl-to-rgb-for-reals-tests.ts
  types/hsl-to-rgb-for-reals/index.d.ts
  types/hsl-to-rgb-for-reals/tsconfig.json
  types/hsl-to-rgb-for-reals/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#62565 added SerialPort.forget() method to w3c-web-serial
  types/w3c-web-serial/index.d.ts
  types/w3c-web-serial/w3c-web-serial-tests.ts
Labels: Self Merge, Owner Approved

#62506 @reach/router: align NavigateFn variants
  types/reach__router/index.d.ts
  types/reach__router/reach__router-tests.tsx
Labels: Self Merge, Maintainer Approved, Critical package

#62572 [jest] mark the `expected` argument of `*CalledWith*` matchers as optional
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#62587 Add "destroy" to FlickityEvents type
  types/flickity/flickity-tests.ts
  types/flickity/index.d.ts
Labels: Self Merge, Owner Approved

#62490 feat: added emmetio implicit-tag definition
  types/emmetio__implicit-tag/emmetio__implicit-tag-tests.ts
  types/emmetio__implicit-tag/index.d.ts
  types/emmetio__implicit-tag/tsconfig.json
  types/emmetio__implicit-tag/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#62579 add `omit-deep` types
  types/omit-deep/index.d.ts
  types/omit-deep/omit-deep-tests.ts
  types/omit-deep/tsconfig.json
  types/omit-deep/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62110 [@types/reveal] update type definitions for version 4.3.1
  types/reveal.js/.eslintrc.json
  types/reveal.js/index.d.ts
  types/reveal.js/plugin/highlight/highlight/index.d.ts
  types/reveal.js/plugin/markdown/markdown/index.d.ts
  types/reveal.js/plugin/math/math/index.d.ts
  types/reveal.js/plugin/notes/notes/index.d.ts
  types/reveal.js/plugin/search/search/index.d.ts
  types/reveal.js/plugin/zoom/zoom/index.d.ts
  types/reveal.js/reveal.js-tests.ts
  types/reveal.js/tsconfig.json
  types/reveal.js/tslint.json
  types/reveal/index.d.ts
  types/reveal/reveal-tests.ts
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved, Check Config

#62456 node: Add validateHeaderName and validateHeaderValue to http
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/ts4.8/http.d.ts
  types/node/ts4.8/test/http.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#62594 Update types for VS Code 1.72
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#62585 feat(react-native): ✨ add types for react-native-typing-animation
  types/react-native-typing-animation/index.d.ts
  types/react-native-typing-animation/react-native-typing-animation-tests.tsx
  types/react-native-typing-animation/tsconfig.json
  types/react-native-typing-animation/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62591 better-sqlite3: SQLiteError actually extends Error
  types/better-sqlite3/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#62598 xrm: event handler improvements
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Owner Approved

#62597 chore: sync updates to google.maps
  types/google.maps/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#62533 [openseadragon] add missing type hints
  types/openseadragon/index.d.ts
  types/openseadragon/openseadragon-tests.ts
Labels: Self Merge, Maintainer Approved

#62620 Add new SendBasicOption
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#62619 Add emoji type and emoji field to MessageEntity
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#62600 feat: ✨ add types for rndm
  types/rndm/index.d.ts
  types/rndm/rndm-tests.ts
  types/rndm/tsconfig.json
  types/rndm/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#62624 encoding-japanese: Remove the redundant type and add more tests
  types/encoding-japanese/index.d.ts
  types/encoding-japanese/test/encoding-japanese-tests.cjs.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#62610 [jsts] buffer overloads + hashCode on jsts.geom.Geometry
  types/jsts/index.d.ts
  types/jsts/jsts-tests.ts
Labels: Self Merge, Owner Approved

#62210 [gamedig] Add GameResolver Types
  types/gamedig/gamedig-tests.ts
  types/gamedig/index.d.ts
  types/gamedig/lib/GameResolver.d.ts
  types/gamedig/tslint.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Edits Owners

#62632 node: Add validateHeaderName/validateHeaderValue to v14 and v16
  types/node/http.d.ts
  types/node/ts4.8/http.d.ts
  types/node/v14/http.d.ts
  types/node/v14/test/http.ts
  types/node/v14/ts4.8/http.d.ts
  types/node/v14/ts4.8/test/http.ts
  types/node/v16/http.d.ts
  types/node/v16/test/http.ts
  types/node/v16/ts4.8/http.d.ts
  types/node/v16/ts4.8/test/http.ts
Labels: Self Merge, Maintainer Approved, Critical package

#62639 feat: ✨ add types for is-map
  types/is-map/index.d.ts
  types/is-map/is-map-tests.ts
  types/is-map/tsconfig.json
  types/is-map/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62599 1.19.0 changes, inheritance of interfaces
  types/consumer-data-standards/banking/index.d.ts
  types/consumer-data-standards/common/index.d.ts
  types/consumer-data-standards/energy/index.d.ts
  types/consumer-data-standards/energy_sdh/index.d.ts
  types/consumer-data-standards/index.d.ts
  types/consumer-data-standards/register/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners, Huge Change

#62603 Add type definition of package html-pdf-node on npm
  types/html-pdf-node/html-pdf-node-tests.ts
  types/html-pdf-node/index.d.ts
  types/html-pdf-node/tsconfig.json
  types/html-pdf-node/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#62609 add plv8 internal types (inside the sandbox)
  types/plv8-internal/index.d.ts
  types/plv8-internal/plv8-internal-tests.ts
  types/plv8-internal/tsconfig.json
  types/plv8-internal/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62617 [sx127x-driver] added types for SX127x
  types/sx127x-driver/index.d.ts
  types/sx127x-driver/sx127x-driver-tests.ts
  types/sx127x-driver/tsconfig.json
  types/sx127x-driver/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62628 add new field to FileBase
  types/node-telegram-bot-api/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change

#62538 fix for issue #60426 in video.js
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#58200 :tada: remove 'express-request-id' as of 3.0.0
  notNeededPackages.json
  types/express-request-id/express-request-id-tests.ts
  types/express-request-id/index.d.ts
  types/express-request-id/tsconfig.json
  types/express-request-id/tslint.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#62660 fix(plotly.js): add texttemplate to plotly. Closes #62558
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#62664 Add node dependency to joi-phone-number
  types/joi-phone-number/index.d.ts
Labels: Untested Change

#62623 feat: Add the missing generic for Database.Transaction
  types/better-sqlite3/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#62643 [aws-lambda]: Add AWS Amplify GraphQL resolver
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/amplify-resolver-tests.ts
  types/aws-lambda/trigger/amplify-resolver.d.ts
  types/aws-lambda/trigger/appsync-resolver.d.ts
  types/aws-lambda/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#62607 [gapi] Add plugin_name to gapi.client init options
  types/gapi/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#62662 [mercadopago] Fix types for `SimpleAddress` interface
  types/mercadopago/mercadopago-tests.ts
  types/mercadopago/shared/address.d.ts
Labels: Self Merge, Owner Approved

#62677 webostvjs: add minimum and maximum properties for MediaOptionsAdaptiveStreaming
  types/webostvjs/index.d.ts
  types/webostvjs/test/mediaOptions.ts
Labels: Self Merge, Author is Owner, Owner Approved

#62611 Add crypto built-in to Akamai-EdgeWorkers
  types/akamai-edgeworkers/index.d.ts
  types/akamai-edgeworkers/test/crypto.ts
  types/akamai-edgeworkers/test/scenario-crypto.ts
  types/akamai-edgeworkers/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved

#62560 Include 'chrome' to puppeteer headless modes types
  types/puppeteer/index.d.ts
  types/puppeteer/puppeteer-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#62654 [node] Add type side of global Blob, along with tests
  types/node/buffer.d.ts
  types/node/stream.d.ts
  types/node/test/buffer.ts
  types/node/ts4.8/buffer.d.ts
  types/node/ts4.8/stream.d.ts
  types/node/ts4.8/test/buffer.ts
Labels: Self Merge, Maintainer Approved, Critical package

#62671 js-nacl update type on instantiate
  types/js-nacl/index.d.ts
  types/js-nacl/js-nacl-tests.ts
Labels: Other Approved, Self Merge

#62633 Sticker changes and new functionality
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#62665 Johnny-Five: Led: Fix `stop` arguments
  types/johnny-five/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62644 extend matomo-tracker-react-native Event type
  types/matomo-tracker-react-native/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62634 [branchy] Add types
  types/branchy/branchy-tests.ts
  types/branchy/index.d.ts
  types/branchy/tsconfig.json
  types/branchy/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62696 Update dynamodb-localhost start options with docker arg
  types/dynamodb-localhost/dynamodb-localhost-tests.ts
  types/dynamodb-localhost/index.d.ts
Labels: Self Merge, Owner Approved

#62486 [@types/node-media-server] Change type "true" to "boolean" and fix mistaken use of array types
  types/node-media-server/index.d.ts
  types/node-media-server/node-media-server-tests.ts
Labels: Self Merge, Owner Approved

#62581 add `@beyonk/gdpr-cookie-consent-banner` types
  types/beyonk__gdpr-cookie-consent-banner/index.d.ts
  types/beyonk__gdpr-cookie-consent-banner/package.json
  types/beyonk__gdpr-cookie-consent-banner/test/beyonk__gdpr-cookie-consent-banner-tests.esm.ts
  types/beyonk__gdpr-cookie-consent-banner/test/beyonk__gdpr-cookie-consent-banner-tests.umd.ts
  types/beyonk__gdpr-cookie-consent-banner/tsconfig.json
  types/beyonk__gdpr-cookie-consent-banner/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#62491 Fix types for dash for node-media-server
  types/node-media-server/index.d.ts
  types/node-media-server/node-media-server-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#62673 types definitions @bitcoin-computer project
  types/bitcoin-computer__lib/bitcoin-computer__lib-tests.ts
  types/bitcoin-computer__lib/index.d.ts
  types/bitcoin-computer__lib/tsconfig.json
  types/bitcoin-computer__lib/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#62708 [tmi.js] Fix typo (`maxReconnectInverval` -> `maxReconnectInterval`)
  types/tmi.js/index.d.ts
  types/tmi.js/tmi.js-tests.ts
Labels: Self Merge, Owner Approved

#62720 feat: update @nginstack/iquery definitions
  types/nginstack__iquery/index.d.ts
  types/nginstack__iquery/lib/IClauseJoin.d.ts
  types/nginstack__iquery/lib/IClauseWhereManager.d.ts
  types/nginstack__iquery/nginstack__iquery-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#62725 feat: update @nginstack/dev-tools definitions
  types/nginstack__dev-tools/index.d.ts
  types/nginstack__dev-tools/nginstack__dev-tools-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#62722 feat: update @nginstack/jsunit definitions
  types/nginstack__jsunit/index.d.ts
  types/nginstack__jsunit/lib/TestCase.d.ts
  types/nginstack__jsunit/lib/TestRunner.d.ts
  types/nginstack__jsunit/nginstack__jsunit-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#62724 feat: update @nginstack/web-framework definitions
  types/nginstack__web-framework/index.d.ts
  types/nginstack__web-framework/lib/anchor/Anchor.d.ts
  types/nginstack__web-framework/lib/audio/Audio.d.ts
  types/nginstack__web-framework/lib/button/ButtonTimer.d.ts
  types/nginstack__web-framework/lib/classdef/GlobalActionSet.d.ts
  types/nginstack__web-framework/lib/classdef/GridEvent.d.ts
  types/nginstack__web-framework/lib/classdef/GridFieldEvent.d.ts
  types/nginstack__web-framework/lib/classdef/GridLocateEvent.d.ts
  types/nginstack__web-framework/lib/classdef/LookupMultipleInsertEvent.d.ts
  types/nginstack__web-framework/lib/classdef/OpenKeyEvent.d.ts
  types/nginstack__web-framework/lib/classdef/TreeNodeEvent.d.ts
  types/nginstack__web-framework/lib/classdef/ViewDef.d.ts
  types/nginstack__web-framework/lib/classdef/ViewDefField.d.ts
  types/nginstack__web-framework/lib/classdef/getGlobalActions.d.ts
  types/nginstack__web-framework/lib/component/ComponentFactoryResolver.d.ts
  types/nginstack__web-framework/lib/dialogs/FormDialog.d.ts
  types/nginstack__web-framework/lib/dialogs/UploadDialog.d.ts
  types/nginstack__web-framework/lib/dsv/CompositeVisualization.d.ts
  types/nginstack__web-framework/lib/dsv/CompositeVisualizationSlot.d.ts
  types/nginstack__web-framework/lib/dsv/EChartsVisualizationDef.d.ts
  types/nginstack__web-framework/lib/dsv/ReportVisualization.d.ts
  types/nginstack__web-framework/lib/dsv/Visualization.d.ts
  types/nginstack__web-framework/lib/dsv/VisualizationDef.d.ts
  types/nginstack__web-framework/lib/dsv/VisualizationFilterDef.d.ts
  types/nginstack__web-framework/lib/dsv/VisualizationFilters.d.ts
  types/nginstack__web-framework/lib/export/DataExporter.d.ts
  types/nginstack__web-framework/lib/export/DataExporterFieldDef.d.ts
  types/nginstack__web-framework/lib/export/DataSetExporter.d.ts
  types/nginstack__web-framework/lib/grid/DetailGrid.d.ts
  types/nginstack__web-framework/lib/grid/FieldPermissionValidator.d.ts
  types/nginstack__web-framework/lib/grid/Grid.d.ts
  types/nginstack__web-framework/lib/grid/GridExportEvent.d.ts
  types/nginstack__web-framework/lib/grid/GridExporter.d.ts
  types/nginstack__web-framework/lib/grid/GridField.d.ts
  types/nginstack__web-framework/lib/label/Label.d.ts
  types/nginstack__web-framework/lib/process/Interaction.d.ts
  types/nginstack__web-framework/lib/process/ProcessCreateEvent.d.ts
  types/nginstack__web-framework/lib/process/ProcessEvent.d.ts
  types/nginstack__web-framework/lib/process/ProcessManager.d.ts
  types/nginstack__web-framework/lib/process/getCurrentProcess.d.ts
  types/nginstack__web-framework/lib/simple-layout/Accumulator.d.ts
  types/nginstack__web-framework/lib/simple-layout/SimpleLayout.d.ts
  types/nginstack__web-framework/lib/simple-layout/SimpleLayoutBuffer.d.ts
  types/nginstack__web-framework/lib/simple-layout/SimpleLayoutExporter.d.ts
  types/nginstack__web-framework/nginstack__web-framework-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#62492 [ramda] Improved typings for assoc, chain, path, and pickAll
  types/ramda/index.d.ts
  types/ramda/test/assoc-tests.ts
  types/ramda/test/chain-tests.ts
  types/ramda/test/path-tests.ts
  types/ramda/test/pickAll-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#62666 feat(carbon__icons-react): upgrade to 11.10
  types/carbon__icons-react/OTHER_FILES.txt
  types/carbon__icons-react/carbon__icons-react-tests.tsx
  types/carbon__icons-react/es/Plan.d.ts
  types/carbon__icons-react/es/index.d.ts
  types/carbon__icons-react/es/watson-health/WatsonHealthImageAvailabilityLocal.d.ts
  types/carbon__icons-react/es/watson-health/WatsonHealthImageAvailabilityRetrieving.d.ts
  types/carbon__icons-react/es/watson-health/WatsonHealthImageAvailabilityUnavailable.d.ts
  types/carbon__icons-react/index.d.ts
  types/carbon__icons-react/lib/Plan.d.ts
  types/carbon__icons-react/lib/index.d.ts
  types/carbon__icons-react/lib/watson-health/WatsonHealthImageAvailabilityLocal.d.ts
  types/carbon__icons-react/lib/watson-health/WatsonHealthImageAvailabilityRetrieving.d.ts
  types/carbon__icons-react/lib/watson-health/WatsonHealthImageAvailabilityUnavailable.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Check Config, No Other Owners

#62717 [node] Bring in changes from v18.11.0
  types/node/crypto.d.ts
  types/node/fs/promises.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/index.d.ts
  types/node/path.d.ts
  types/node/test/crypto.ts
  types/node/test/fs.ts
  types/node/test/http.ts
  types/node/test/http2.ts
  types/node/test/util.ts
  types/node/ts4.8/crypto.d.ts
  types/node/ts4.8/fs/promises.d.ts
  types/node/ts4.8/http.d.ts
  types/node/ts4.8/http2.d.ts
  types/node/ts4.8/path.d.ts
  types/node/ts4.8/test/crypto.ts
  types/node/ts4.8/test/fs.ts
  types/node/ts4.8/test/http.ts
  types/node/ts4.8/test/http2.ts
  types/node/ts4.8/test/util.ts
  types/node/ts4.8/util.d.ts
  types/node/util.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#62731 feat: add StereoAudioRecorder type in RecordRTC
  types/recordrtc/index.d.ts
  types/recordrtc/recordrtc-tests.ts
Labels: Self Merge, Owner Approved

#62695 [webpack]: add getDependencies to LoaderContext interface
  types/webpack/v4/index.d.ts
  types/webpack/v4/test/index.ts
Labels: Self Merge, Maintainer Approved, Critical package

#62686 [react-mentions]: support customSuggestionsContainer
  types/react-mentions/index.d.ts
  types/react-mentions/react-mentions-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#62704 web-bluetooth: remove non-existant method unwatchAdvertisements
  types/web-bluetooth/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#62487 [leaflet] Update to leaflet 1.9.1
  types/leaflet/index.d.ts
Labels: Other Approved, Unmerged, Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#62613 search-index - fixed NOT QueryVerb and added tokenSplitRegex
  types/search-index/index.d.ts
  types/search-index/search-index-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#62622 [@types/chrome] Add types for chrome.scripting.removeCSS()
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#62737 [@types/twit] Added missing parameter 'event'
  types/twit/index.d.ts
  types/twit/twit-tests.ts
Labels: Self Merge, Owner Approved

#62743 feat(@types/validator): include isISO31661Alpha2 CountryCodes declaration
  types/validator/es/lib/isISO31661Alpha2.d.ts
  types/validator/index.d.ts
  types/validator/lib/isISO31661Alpha2.d.ts
  types/validator/validator-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#62740 fix (css-tree): add missing methods
  types/css-tree/css-tree-tests.ts
  types/css-tree/index.d.ts
Labels: Self Merge, Owner Approved

#62672 [node] fix: stream depends on global Blob not available in v16
  types/node/v16/stream.d.ts
  types/node/v16/ts4.8/stream.d.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#62710 Include xhoverformat, yhoverformat in PlotData type
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#62642 [react-native] Update incorrect `SwitchChangeEvent` type
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
  types/react-native/v0.63/index.d.ts
  types/react-native/v0.63/test/index.tsx
  types/react-native/v0.64/index.d.ts
  types/react-native/v0.64/test/index.tsx
  types/react-native/v0.65/index.d.ts
  types/react-native/v0.65/test/index.tsx
  types/react-native/v0.66/index.d.ts
  types/react-native/v0.66/test/index.tsx
  types/react-native/v0.67/index.d.ts
  types/react-native/v0.67/test/index.tsx
  types/react-native/v0.68/index.d.ts
  types/react-native/v0.68/test/index.tsx
  types/react-native/v0.69/index.d.ts
  types/react-native/v0.69/test/index.tsx
Labels: Owner Approved, Critical package

#62653 Update pdfkit
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#62367 Upgrade types for @sap/xsenv to version 3.3
  types/sap__xsenv/index.d.ts
  types/sap__xsenv/sap__xsenv-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#62728 fix: add customer id to card.delete. Closes #62718
  types/mercadopago/mercadopago-tests.ts
  types/mercadopago/resources/cards.d.ts
Labels: Self Merge, Owner Approved

#62747 Add comment to explain why exposing access token in CI is OK
  .github/workflows/CI.yml
Labels: Edits Infrastructure

#62742 [appium-adb] Fix parameter type in waitForEmulatorReady method.
  types/appium-adb/appium-adb-tests.ts
  types/appium-adb/lib/tools/system-calls.d.ts
Labels: Self Merge, Owner Approved

#62526 Fix problems with support window workflow & script
  .github/workflows/support-window.yml
  scripts/support-window.js
Labels: Edits Infrastructure, Unreviewed

#62763 Add back JSON assertion to support-window script
  .github/workflows/support-window.yml
  scripts/support-window.js
Labels: Edits Infrastructure

#62688 Add types for `@alpinejs/focus`
  types/alpinejs__focus/alpinejs__focus-tests.ts
  types/alpinejs__focus/index.d.ts
  types/alpinejs__focus/tsconfig.json
  types/alpinejs__focus/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62749 [xrm] Add onOutputChange support
  types/xrm/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#62714 [jest] add types for `jest.getSeed()` method
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#62604 [react-native] Fixed types for event.target and event.nativeEvent.target
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
  types/react-native/v0.68/index.d.ts
  types/react-native/v0.69/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#62645 [aws-lambda]: Add domainName property to AppSync resolver request object
  types/aws-lambda/test/appsync-resolver-tests.ts
  types/aws-lambda/trigger/appsync-resolver.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#62782 Node global interfaces redux
  types/node/dom-events.d.ts
  types/node/globals.d.ts
  types/node/node-tests.ts
  types/node/test/buffer.ts
  types/node/test/dom-events.ts
  types/node/test/events.ts
  types/node/test/perf_hooks.ts
  types/node/ts4.8/buffer.d.ts
  types/node/ts4.8/dom-events.d.ts
  types/node/ts4.8/node-tests.ts
  types/node/ts4.8/test/dom-events.ts
  types/node/ts4.8/test/events.ts
  types/node/tsconfig.json
  types/node/v16/stream.d.ts
  types/node/v16/test/events.ts
  types/node/v16/ts4.8/test/events.ts
Labels: Self Merge, Maintainer Approved, Critical package

#62741 chore (keyv): remove as types now shipped
  notNeededPackages.json
  types/got/got-tests.ts
  types/got/v8/got-tests.ts
  types/keyv/index.d.ts
  types/keyv/keyv-tests.ts
  types/keyv/tsconfig.json
  types/keyv/tslint.json
  types/keyv__mongo/index.d.ts
  types/keyv__mongo/keyv__mongo-tests.ts
  types/keyv__mongo/tsconfig.json
  types/keyv__mongo/tslint.json
  types/keyv__mysql/index.d.ts
  types/keyv__mysql/keyv__mysql-tests.ts
  types/keyv__mysql/tsconfig.json
  types/keyv__mysql/tslint.json
  types/keyv__postgres/index.d.ts
  types/keyv__postgres/keyv__postgres-tests.ts
  types/keyv__postgres/tsconfig.json
  types/keyv__postgres/tslint.json
  types/keyv__redis/index.d.ts
  types/keyv__redis/keyv__redis-tests.ts
  types/keyv__redis/package.json
  types/keyv__redis/tsconfig.json
  types/keyv__redis/tslint.json
  types/keyv__sqlite/index.d.ts
  types/keyv__sqlite/keyv__sqlite-tests.ts
  types/keyv__sqlite/tsconfig.json
  types/keyv__sqlite/tslint.json
  types/onionoo/onionoo-tests.ts
  types/onionoo/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package

#62702 [node] Remove legacy status from querystring
  types/node/querystring.d.ts
  types/node/ts4.8/querystring.d.ts
  types/node/v16/querystring.d.ts
  types/node/v16/ts4.8/querystring.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#62784 @ember/controller: remove non-public-API exports
  types/ember__controller/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#62727 Johnny-Five: Update `Led` to support analog pins
  types/johnny-five/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62707 Johnny-Five: Define all `Board` events
  types/johnny-five/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62694 feat(ali-oss): add `asyncSignatureUrl()` function
  types/ali-oss/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62700 add types for `await-promises`
  types/await-promises/await-promises-tests.ts
  types/await-promises/index.d.ts
  types/await-promises/tsconfig.json
  types/await-promises/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62691 fix: react-email-editor types for ToolsConfig
  types/react-email-editor/index.d.ts
  types/react-email-editor/react-email-editor-tests.tsx
Labels: Self Merge, Owner Approved

#62615 ramda: Support assertion function in tap function
  types/ramda/index.d.ts
  types/ramda/test/tap-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#62739 Making OpenGraphImage height and width optional
  types/open-graph-scraper/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#62780 Added types for react-video-recorder
  types/react-video-recorder/index.d.ts
  types/react-video-recorder/react-video-recorder-tests.tsx
  types/react-video-recorder/tsconfig.json
  types/react-video-recorder/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62745 feat: add types for `json-stable-stringify-without-jsonify`
  types/json-stable-stringify-without-jsonify/index.d.ts
  types/json-stable-stringify-without-jsonify/json-stable-stringify-without-jsonify-tests.ts
  types/json-stable-stringify-without-jsonify/tsconfig.json
  types/json-stable-stringify-without-jsonify/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62744 Hapi ref types
  types/hapi__hapi/index.d.ts
  types/hapi__hapi/test/route/route-options-types.ts
  types/hapi__hapi/test/route/route-options.ts
  types/hapi__hapi/test/server/server-auth-api-types.ts
  types/hapi__hapi/test/server/server-auth-api.ts
  types/hapi__hapi/test/server/server-rules.ts
  types/hapi__hapi/tsconfig.json
  types/hapipal__schmervice/hapipal__schmervice-tests.ts
  types/hapipal__schmervice/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Edits Owners

#62715 Add types for tiny-human-time.
  types/tiny-human-time/index.d.ts
  types/tiny-human-time/tiny-human-time-tests.ts
  types/tiny-human-time/tsconfig.json
  types/tiny-human-time/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#62748 Add types for iterate-object.
  types/iterate-object/index.d.ts
  types/iterate-object/iterate-object-tests.ts
  types/iterate-object/tsconfig.json
  types/iterate-object/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#62758 Add types for friendly-words
  types/friendly-words/friendly-words-tests.ts
  types/friendly-words/index.d.ts
  types/friendly-words/tsconfig.json
  types/friendly-words/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#62462 [@types/nova-editor-node] workspace.activeTextEditor can be null
  types/nova-editor-node/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change
