Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2022-07, with the labels that each got.

#61025 [ssh2] Thorough update of ssh2 typings
  types/ssh2/index.d.ts
  types/ssh2/ssh2-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#61027 Replace remaining $ExpectErrors with @ts-expect-error
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/test/cdk-custom-resource-tests.ts
  types/aws-lambda/test/cloudfront-tests.ts
  types/aws-lambda/test/cognito-tests.ts
  types/aws-lambda/test/lex-tests.ts
  types/backbone/backbone-tests.ts
  types/bluebird/bluebird-tests.ts
  types/bookshelf/bookshelf-tests.ts
  types/deep-eql/deep-eql-tests.ts
  types/express/express-tests.ts
  types/express/ts4.0/express-tests.ts
  types/knex-cleaner/knex-cleaner-tests.ts
  types/koa/test/typed-response-body.ts
  types/lodash/lodash-tests.ts
  types/node-red-node-test-helper/node-red-node-test-helper-tests.ts
  types/node/test/buffer.ts
  types/node/test/dns.ts
  types/node/test/fs.ts
  types/node/test/process.ts
  types/node/test/querystring.ts
  types/node/test/stream.ts
  types/node/test/test.ts
  types/node/test/url.ts
  types/node/v14/test/buffer.ts
  types/node/v14/test/dns.ts
  types/node/v14/test/fs.ts
  types/node/v14/test/querystring.ts
  types/node/v14/test/url.ts
  types/node/v16/test/buffer.ts
  types/node/v16/test/dns.ts
  types/node/v16/test/fs.ts
  types/node/v16/test/querystring.ts
  types/node/v16/test/url.ts
  types/react-native/v0.68/test/globals.tsx
  types/react-native/v0.68/test/index.tsx
  types/react/test/elementAttributes.tsx
  types/react/test/experimental.tsx
  types/react/test/hooks.tsx
  types/react/test/index.ts
  types/react/test/managedAttributes.tsx
  types/react/test/tsx.tsx
  types/react/v15/test/tsx.tsx
  types/react/v16/test/hooks.tsx
  types/react/v16/test/index.ts
  types/react/v16/test/managedAttributes.tsx
  types/react/v16/test/tsx.tsx
  types/react/v17/test/elementAttributes.tsx
  types/react/v17/test/hooks.tsx
  types/react/v17/test/index.ts
  types/react/v17/test/managedAttributes.tsx
  types/react/v17/test/tsx.tsx
  types/redux-orm/redux-orm-tests.ts
  types/superagent-retry-delay/superagent-retry-delay-tests.ts
  types/webpack/v4/test/index.ts
Labels: Edits multiple packages, Maintainer Approved, Critical package, The CI failed, Too Many Owners

#60851 [react-big-calendar] Pass through TResource to ResourceHeaderProps
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#61069 [indy-sdk] feat(indy-sdk): add generateWalletKey
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60970 fix(node): `fs.cp` accepts URL for src and dest
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/test/fs.ts
  types/node/v16/fs.d.ts
  types/node/v16/fs/promises.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#61066 feat(@types/validator): include missing definition for blacklisted characters option in email validation
  types/validator/lib/isEmail.d.ts
  types/validator/validator-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60812 Bump mudder to version 2.1
  types/mudder/index.d.ts
  types/mudder/mudder-tests.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#61062 Add chartjs-plugin-doughnutlabel-rebourne types
  types/chartjs-plugin-doughnutlabel-rebourne/chartjs-plugin-doughnutlabel-rebourne-tests.ts
  types/chartjs-plugin-doughnutlabel-rebourne/index.d.ts
  types/chartjs-plugin-doughnutlabel-rebourne/package.json
  types/chartjs-plugin-doughnutlabel-rebourne/tsconfig.json
  types/chartjs-plugin-doughnutlabel-rebourne/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61056 [googletag] update based on GPT reference 2022-06-30 UTC.
  types/googletag/index.d.ts
  types/googletag/ts4.2/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#61058 [passport-naver]Fix: passReqToCallback must be true
  types/passport-naver/index.d.ts
  types/passport-naver/passport-naver-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61047 Remove tailwindcss types
  notNeededPackages.json
  types/tailwindcss/colors.d.ts
  types/tailwindcss/defaultTheme.d.ts
  types/tailwindcss/index.d.ts
  types/tailwindcss/nesting.d.ts
  types/tailwindcss/plugin.d.ts
  types/tailwindcss/resolveConfig.d.ts
  types/tailwindcss/tailwind-config-default.d.ts
  types/tailwindcss/tailwind-config.d.ts
  types/tailwindcss/test/tailwindcss-corePlugins-tests.ts
  types/tailwindcss/test/tailwindcss-default-config-code-tests.ts
  types/tailwindcss/test/tailwindcss-default-config-value-tests.ts
  types/tailwindcss/test/tailwindcss-font-size-tests.ts
  types/tailwindcss/test/tailwindcss-nesting-tests.ts
  types/tailwindcss/test/tailwindcss-optional-config-tests.ts
  types/tailwindcss/test/tailwindcss-plugin-tests.ts
  types/tailwindcss/test/tailwindcss-tests.ts
  types/tailwindcss/tsconfig.json
  types/tailwindcss/tslint.json
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved, Huge Change

#60914 [auth0] Add getGuardianEnrollment type
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#61071 intro.js - Add `onbeforeexit` definition and tests
  types/intro.js/index.d.ts
  types/intro.js/intro.js-tests.ts
Labels: Self Merge, Owner Approved

#61078 Update package.json
  types/pikaday/package.json
Labels: Popular package, Self Merge, Owner Approved

#61080 chrome.tabs.getCurrent Promise resolve Type
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#61070 feat: react native fabric component types
  types/react-native/Codegen.d.ts
  types/react-native/index.d.ts
  types/react-native/test/fabric-component-sample.ts
  types/react-native/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved

#60939 update(configstore): ESM updates
  types/configstore/configstore-tests.ts
  types/configstore/index.d.ts
  types/configstore/package.json
  types/update-notifier/update-notifier.d.ts
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved, Check Config

#61079 Add type for convert-array-to-csv
  types/convert-array-to-csv/convert-array-to-csv-tests.ts
  types/convert-array-to-csv/index.d.ts
  types/convert-array-to-csv/tsconfig.json
  types/convert-array-to-csv/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61068 [chrome] executeScript should return a typed value
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#60817 feat(@types/connect-mongodb-session): Add missing options
  types/connect-mongodb-session/connect-mongodb-session-tests.ts
  types/connect-mongodb-session/index.d.ts
Labels: Self Merge, Owner Approved

#60840 [subscribe-ui-event] Allow target in SubscribeOption
  types/subscribe-ui-event/index.d.ts
  types/subscribe-ui-event/subscribe-ui-event-tests.ts
Labels: Unreviewed

#60806 [signalfx] Added sendEvent to the interfaces, and fixed the return type of send to be Promise<void>.
  types/signalfx/index.d.ts
  types/signalfx/signalfx-tests.ts
Labels: Unreviewed

#60794 [@types/braintree-web] Add DataCollector missing types
  types/braintree-web/modules/data-collector.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Unreviewed

#60787 [mssql] recordsets can be arrays of various types
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Popular package, Author is Owner, Unreviewed

#61090 Fix react-dom/test-utils types entry point
  types/react-dom/package.json
Labels: Owner Approved, Critical package, Check Config

#60876 getLicense takes a string as argument
  types/react-native-video/index.d.ts
Labels: Popular package, Owner Approved, Untested Change, Unreviewed

#61053 [jest-when] Replace $ExpectError with @ts-expect-error
  types/jest-when/jest-when-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#61097 [spdx-expression-parse] Fix typo `s/Conjuction/Conjunction/`
  types/spdx-expression-parse/index.d.ts
  types/spdx-expression-parse/spdx-expression-parse-tests.ts
Labels: Other Approved, Self Merge, Maintainer Approved

#61077 Add tag field
  types/hyper-function-component/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#61051 Fill out root eslintrc and update README
  .eslintrc.json
  README.md
Labels: Edits Infrastructure

#61048 [node-barion] Add type definitions for node-barion
  types/node-barion/index.d.ts
  types/node-barion/node-barion-tests.ts
  types/node-barion/tsconfig.json
  types/node-barion/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61096 Updating types for ember-modal-service and ember-task-scheduler
  types/ember-modal-service/components/modal.d.ts
  types/ember-modal-service/ember-modal-service-tests.ts
  types/ember-modal-service/models/modal.ts
  types/ember-modal-service/services/modal.d.ts
  types/ember-task-scheduler/ember-task-scheduler-tests.ts
  types/ember-task-scheduler/index.d.ts
Labels: Author is Owner, Edits multiple packages, No Other Owners

#60696 [react] fix: missing target types at KeyboardEvent
  types/react/index.d.ts
Labels: Self Merge, Critical package, Untested Change

#60844 [chroma.js]Add missing method and property.
  types/chroma-js/chroma-js-tests.ts
  types/chroma-js/index.d.ts
Labels: Popular package, Unreviewed, Edits Owners

#60859 [infra] Show original context in CI stack traces
  package.json
Labels: Edits Infrastructure

#61095 [sequelize] Fix typo: optionz -> options
  types/sequelize/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#61098 node: Add Server.closeIdleConnections and Server.closeAllConnections
  types/node/http.d.ts
  types/node/https.d.ts
  types/node/test/http.ts
  types/node/test/https.ts
Labels: Self Merge, Owner Approved, Critical package

#61104 Turn on first two eslint rules
  .eslintrc.json
  types/activex-access/.eslintrc.json
  types/activex-adodb/.eslintrc.json
  types/activex-adox/.eslintrc.json
  types/activex-dao/.eslintrc.json
  types/activex-diskquota/index.d.ts
  types/activex-excel/.eslintrc.json
  types/activex-faxcomexlib/.eslintrc.json
  types/activex-faxcomexlib/index.d.ts
  types/activex-infopath/.eslintrc.json
  types/activex-iwshruntimelibrary/.eslintrc.json
  types/activex-libreoffice/.eslintrc.json
  types/activex-msforms/.eslintrc.json
  types/activex-mshtml/.eslintrc.json
  types/activex-msxml2/.eslintrc.json
  types/activex-office/.eslintrc.json
  types/activex-outlook/.eslintrc.json
  types/activex-powerpoint/.eslintrc.json
  types/activex-scripting/index.d.ts
  types/activex-shdocvw/index.d.ts
  types/activex-shell/index.d.ts
  types/activex-stdole/.eslintrc.json
  types/activex-vbide/.eslintrc.json
  types/activex-wia/.eslintrc.json
  types/activex-word/.eslintrc.json
  types/big.js/index.d.ts
  types/consumer-data-standards/.eslintrc.json
  types/eonasdan-bootstrap-datetimepicker/.eslintrc.json
  types/firmata/.eslintrc.json
  types/frida-gum/index.d.ts
  types/ftpd/.eslintrc.json
  types/jquery.qrcode/.eslintrc.json
  types/mfiles/.eslintrc.json
  types/microsoftteams/.eslintrc.json
  types/mysql/.eslintrc.json
  types/nodegit/.eslintrc.json
  types/novnc-core/.eslintrc.json
  types/onesignal-cordova-plugin/.eslintrc.json
  types/openfin/.eslintrc.json
  types/photoshop/.eslintrc.json
  types/powerbi-visuals-tools/.eslintrc.json
  types/sharepoint/.eslintrc.json
  types/signalr/.eslintrc.json
  types/webcl/.eslintrc.json
  types/wiiu/.eslintrc.json
  types/xrm/.eslintrc.json
  types/youtube/.eslintrc.json
Labels: Popular package, Edits Infrastructure, Edits multiple packages, Untested Change, Check Config, Too Many Owners

#60776 asana: Define opt_fields as string, not string[]
  types/asana/asana-tests.ts
  types/asana/index.d.ts
Labels: Self Merge

#60991 node missing type def under perf_hooks.d.ts for the RH interface.
  types/node/perf_hooks.d.ts
  types/node/test/perf_hooks.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60634 [@types/async]: Fix type declarations for every,sortBy,everyLimit,detectLimit,groupBy,flatMap,tryEach functions
  types/async/index.d.ts
  types/async/test/index.ts
Labels: Popular package, Self Merge

#61111 [node-forge] pbkdf2 allows message digest to be string
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#61113 Use cross-env to set NODE_OPTIONS in scripts
  package.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#61114 Sync frida-gum typings with Frida 15.1.28
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61093 add type definitions for heic-convert
  types/heic-convert/heic-convert-tests.ts
  types/heic-convert/index.d.ts
  types/heic-convert/tsconfig.json
  types/heic-convert/tslint.json
Labels: Revision needed, New Definition

#60990 [@wordpress/blocks] Fix `BlockDeprecation` type.
  types/wordpress__blocks/index.d.ts
  types/wordpress__blocks/wordpress__blocks-tests.tsx
Labels: Self Merge, Owner Approved

#60956 [@types/plotly.js] Add pattern, griddash, and register
  types/plotly.js/index.d.ts
  types/plotly.js/lib/traces/candlestick.d.ts
  types/plotly.js/lib/traces/ohcl.d.ts
  types/plotly.js/lib/traces/pie.d.ts
  types/plotly.js/test/core-tests.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#61116 google-spreadsheet v3.3: sheet.clear(range) and sheet.clearRows()
  types/google-spreadsheet/google-spreadsheet-tests.ts
  types/google-spreadsheet/index.d.ts
Labels: Self Merge, Owner Approved

#61067 update exaroton package to 1.8 ♻️
  types/exaroton/exaroton-tests.ts
  types/exaroton/index.d.ts
  types/exaroton/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60577 add exposed sessionStore in express.Request
  types/express-session/express-session-tests.ts
  types/express-session/index.d.ts
Labels: Popular package, Self Merge

#61122 [ssh2-sftp-client] Add missing methods declarations
  types/ssh2-sftp-client/index.d.ts
  types/ssh2-sftp-client/ssh2-sftp-client-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#61092 [pdfmake] Updates, fixes, documentation
  types/pdfmake/index.d.ts
  types/pdfmake/interfaces.d.ts
  types/pdfmake/test/pdfmake-interfaces-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#61085 Improve chartjs-plugin-doughnutlabel-rebourne
  types/chartjs-plugin-doughnutlabel-rebourne/chartjs-plugin-doughnutlabel-rebourne-tests.ts
  types/chartjs-plugin-doughnutlabel-rebourne/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#61120 fix(google-apps-script): `getCursor` also returns null
  types/google-apps-script/google-apps-script.document.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#61138 add ExecError type to teen_process
  types/teen_process/index.d.ts
  types/teen_process/teen_process-tests.ts
Labels: Self Merge, Owner Approved

#60987 `jexl` AST and grammar types
  types/jexl/Ast.d.ts
  types/jexl/Expression.d.ts
  types/jexl/Grammar.d.ts
  types/jexl/index.d.ts
  types/jexl/jexl-tests.ts
Labels: Self Merge, Owner Approved

#61132 [@types/plotly.js] Update Config and PlotData definitions
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#61123 Add redis-server
  types/redis-server/index.d.ts
  types/redis-server/redis-server-tests.ts
  types/redis-server/tsconfig.json
  types/redis-server/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61045 Extended mapnik type 'Map' and added new types 'Layer' and 'Projection'
  types/mapnik/index.d.ts
  types/mapnik/mapnik-tests.ts
Labels: Self Merge, Owner Approved

#61127 Minor fix for ember-modal-service types
  types/ember-modal-service/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#60873 asana: Task/Section/User Task List/Typeahead bug fixes to current types
  types/asana/asana-tests.ts
  types/asana/index.d.ts
Labels: Self Merge, Owner Approved

#61150 Update constructor types for i18n for issue #60984
  types/i18n/i18n-tests.ts
  types/i18n/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#60125 Add types for gensync
  types/gensync/gensync-tests.ts
  types/gensync/index.d.ts
  types/gensync/tsconfig.json
  types/gensync/tslint.json
Labels: New Definition, Check Config

#61130 fix(ldapjs): Add missing Attribute constructor
  types/ldapjs/index.d.ts
  types/ldapjs/ldapjs-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#61134 VS Code 1.69.0 Extension API
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#61055 [ssh2] Tweaks to SSH2 typings
  types/ssh2/index.d.ts
  types/ssh2/ssh2-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#61155 Add type for srtparsejs
  types/srtparsejs/index.d.ts
  types/srtparsejs/srtparsejs-tests.ts
  types/srtparsejs/tsconfig.json
  types/srtparsejs/tslint.json
Labels: New Definition

#61158 feat(sync-fetch): add sync-fetch types
  types/sync-fetch/index.d.ts
  types/sync-fetch/sync-fetch-tests.ts
  types/sync-fetch/tsconfig.json
  types/sync-fetch/tslint.json
Labels: New Definition

#60815 fix(@types/folder-hash): Add missing encoding `base64url`
  types/folder-hash/index.d.ts
Labels: Owner Approved, Untested Change, Unreviewed, Edits Owners

#60843 feat: add R.modify type definition for @types/ramda
  types/ramda/OTHER_FILES.txt
  types/ramda/es/modify.d.ts
  types/ramda/index.d.ts
  types/ramda/src/modify.d.ts
  types/ramda/test/modify-tests.ts
  types/ramda/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved, Check Config

#61162 [sync-fetch] Replace $ExpectError with @ts-expect-error
  types/sync-fetch/sync-fetch-tests.ts
Labels: Self Merge, Owner Approved

#60893 Add more precise types to humps
  types/humps/index.d.ts
  types/humps/test/humps-tests.cjs.ts
  types/humps/test/humps-tests.global.ts
Labels: Popular package, Self Merge, Maintainer Approved

#61139 [asana] Replace $ExpectError with @ts-expect-error
  types/asana/asana-tests.ts
Labels: Other Approved, Self Merge

#61081 [react-native] realign the RN types dependency to the right React version counterpart
  types/react-native/index.d.ts
  types/react-native/v0.63/tsconfig.json
  types/react-native/v0.64/tsconfig.json
  types/react-native/v0.65/tsconfig.json
  types/react-native/v0.66/tsconfig.json
  types/react-native/v0.67/tsconfig.json
  types/react-native/v0.68/tsconfig.json
Labels: Other Approved, Popular package, Maintainer Approved, The CI failed, Untested Change, Edits Owners

#61129 New Interface
  types/hyper-function-component/hyper-function-component-tests.ts
  types/hyper-function-component/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#61151 [google-apps-script] fix(slides): add setSkipped function signature
  types/google-apps-script/google-apps-script.slides.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#60902 Add Au Becs Payment Option
  types/stripe-v3/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#61165 Adding missing styles for prism (oneDark, oneLight)
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#61178 feat(node-json-transform): Implemented types for node-json-transform
  types/node-json-transform/index.d.ts
  types/node-json-transform/node-json-transform-tests.ts
  types/node-json-transform/tsconfig.json
  types/node-json-transform/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61174 Add missing event arg to callback signature
  types/wordpress__components/keyboard-shortcuts/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Self Merge, Owner Approved

#61091 Type definitions for cadviewer
  types/cadviewer/cadviewer-tests.ts
  types/cadviewer/index.d.ts
  types/cadviewer/tsconfig.json
  types/cadviewer/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61180 Renaming model file, so it shows when updating the package
  types/ember-modal-service/models/modal.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#60995 Mark estree and estree-jsx as 1.0
  types/estree-jsx/estree-jsx-tests.ts
  types/estree-jsx/index.d.ts
  types/estree-jsx/tslint.json
  types/estree/estree-tests.ts
  types/estree/flow.d.ts
  types/estree/index.d.ts
  types/estree/tslint.json
Labels: Other Approved, Self Merge, Edits multiple packages, Maintainer Approved, Critical package, Check Config

#61190 Add material-colors types
  types/material-colors/index.d.ts
  types/material-colors/material-colors-tests.ts
  types/material-colors/tsconfig.json
  types/material-colors/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#61215 [@ember/test-helpers] Add rerender
  types/ember__test-helpers/ember__test-helpers-tests.ts
  types/ember__test-helpers/index.d.ts
  types/ember__test-helpers/setup-rendering-context.d.ts
Labels: Popular package, Self Merge, Owner Approved

#61105 feat(geojson): GeometryCollection with Generics
  types/geojson/geojson-tests.ts
  types/geojson/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#61196 feat: add animated_gif types
  types/animated_gif/animated_gif-tests.ts
  types/animated_gif/index.d.ts
  types/animated_gif/tsconfig.json
  types/animated_gif/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61210 Jest - Update Args for retryTimes
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#61052 Make 'canvas' param optional for canvas-confetti create
  types/canvas-confetti/canvas-confetti-tests.ts
  types/canvas-confetti/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#61206 clone of react-simple-map
  types/nowigence-react-simple-maps/index.d.ts
  types/nowigence-react-simple-maps/nowigence-react-simple-maps-tests.tsx
  types/nowigence-react-simple-maps/tsconfig.json
  types/nowigence-react-simple-maps/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61202 [sharedb] bump major version
  types/sharedb/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#61193 feat: adds ldap-authentication
  types/ldap-authentication/index.d.ts
  types/ldap-authentication/ldap-authentication-tests.ts
  types/ldap-authentication/tsconfig.json
  types/ldap-authentication/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61175 asana: updated DispatcherOptions to include defaultHeaders
  types/asana/asana-tests.ts
  types/asana/index.d.ts
Labels: Other Approved, Self Merge

#61026 [happo-cypress] Make types compatible with Cypress v10
  types/happo-cypress/happo-cypress-tests.ts
  types/happo-cypress/index.d.ts
  types/happo-cypress/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved

#61101 Smooch - Add missing message types & improve metadata type
  types/smooch/global.d.ts
  types/smooch/smooch-tests.ts
Labels: Self Merge, Owner Approved

#60778 [@types/node] Add several missing members from `crypto` and `crypto.webcrypto`
  types/diffie-hellman/diffie-hellman-tests.ts
  types/node/crypto.d.ts
  types/node/test/crypto.ts
  types/node/test/util_types.ts
  types/node/v14/crypto.d.ts
  types/node/v14/test/crypto.ts
  types/node/v16/crypto.d.ts
  types/node/v16/test/crypto.ts
  types/node/v16/test/util_types.ts
Labels: Other Approved, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Critical package

#61216 added definitions for react-bootstrap-confirmation
  types/react-bootstrap-confirmation/index.d.ts
  types/react-bootstrap-confirmation/react-bootstrap-confirmation-tests.tsx
  types/react-bootstrap-confirmation/tsconfig.json
  types/react-bootstrap-confirmation/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61220 style(geojson): prettier ts files
  types/geojson/geojson-tests.ts
  types/geojson/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60814 Add type definitions for vinyl-named
  types/vinyl-named/index.d.ts
  types/vinyl-named/tsconfig.json
  types/vinyl-named/tslint.json
  types/vinyl-named/vinyl-named-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#61218 create @types/hunspell-spellchecker
  types/hunspell-spellchecker/hunspell-spellchecker-tests.ts
  types/hunspell-spellchecker/index.d.ts
  types/hunspell-spellchecker/tsconfig.json
  types/hunspell-spellchecker/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61227 feat: tradePay resultCode callback
  types/miniprogram/index.d.ts
  types/miniprogram/miniprogram-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61221 Add types for semver-compare-multi
  types/semver-compare-multi/index.d.ts
  types/semver-compare-multi/semver-compare-multi-tests.ts
  types/semver-compare-multi/tsconfig.json
  types/semver-compare-multi/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61201 Add typings for create-keyframe-animation
  types/create-keyframe-animation/create-keyframe-animation-tests.ts
  types/create-keyframe-animation/index.d.ts
  types/create-keyframe-animation/tsconfig.json
  types/create-keyframe-animation/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61228 feat: create types for `react-refresh`
  types/react-refresh/babel.d.ts
  types/react-refresh/index.d.ts
  types/react-refresh/package.json
  types/react-refresh/react-refresh-tests.ts
  types/react-refresh/runtime.d.ts
  types/react-refresh/tsconfig.json
  types/react-refresh/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#61241 [googletag] remove deprecated functions and update code comments
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
  types/googletag/ts4.2/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#61244 [@types/amplitude-js] Change type of `sessionId` field in `interface Config`
  types/amplitude-js/amplitude-js-tests.ts
  types/amplitude-js/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#61035 [mapbox__mapbox-gl-draw] Fixed custom mode
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
Labels: Self Merge, Owner Approved

#61260 feat: update @nginstack/web-framework definitions
  types/nginstack__web-framework/index.d.ts
  types/nginstack__web-framework/nginstack__web-framework-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61261 feat: update @nginstack/dev-tools definitions
  types/nginstack__dev-tools/index.d.ts
  types/nginstack__dev-tools/nginstack__dev-tools-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61258 feat: update @nginstack/jsunit definitions
  types/nginstack__jsunit/index.d.ts
  types/nginstack__jsunit/nginstack__jsunit-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61256 feat: update @nginstack/iquery definitions
  types/nginstack__iquery/index.d.ts
  types/nginstack__iquery/nginstack__iquery-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61257 feat: update @nginstack/orm definitions
  types/nginstack__orm/index.d.ts
  types/nginstack__orm/nginstack__orm-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#61083 asana: Propose self as a Definition Owner
  types/asana/index.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Untested Change, Edits Owners

#61084 asana: Improve task, story, and custom field API type definitions based on new tests
  types/asana/asana-tests.ts
  types/asana/index.d.ts
  types/asana/tsconfig.json
Labels: Self Merge, Maintainer Approved

#61245 fix: missing children in ImageBackgroundProps for react-native@0.66.x
  types/react-native/v0.66/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#61249 [react-refresh] Replace $ExpectError with @ts-expect-error
  types/react-refresh/react-refresh-tests.ts
Labels: Self Merge, Owner Approved

#61250 [amplitude-js] Replace $ExpectError with @ts-expect-error
  types/amplitude-js/amplitude-js-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#61272 react-onsensu: Added some missing props to SearchInput
  types/react-onsenui/index.d.ts
  types/react-onsenui/react-onsenui-tests.tsx
Labels: Self Merge, Owner Approved

#61283 node-imap types
  types/node-imap/index.d.ts
  types/node-imap/node-imap-tests.ts
  types/node-imap/tsconfig.json
  types/node-imap/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61278 [@types/jest] Add `test.failing` method
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#61240 [@types/node] fix CryptoKey.usages
  types/node/crypto.d.ts
  types/node/test/crypto.ts
  types/node/v16/crypto.d.ts
  types/node/v16/test/crypto.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#61222 [google-apps-script] Add missing Drive Service APIs
  types/google-apps-script/google-apps-script.drive.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#61263 fix(react-date-range): invalid value undefined
  types/react-date-range/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#61276 Add type definition for @styled-system/props
  types/styled-system__props/index.d.ts
  types/styled-system__props/styled-system__props-tests.ts
  types/styled-system__props/tsconfig.json
  types/styled-system__props/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61197 [react-resizable] make width and height prop conditionally required
  types/react-resizable/index.d.ts
  types/react-resizable/react-resizable-tests.tsx
  types/react-resizable/tslint.json
Labels: Popular package, Self Merge, Maintainer Approved, Check Config

#61295 fix(@styled-system/props): changed prop value to `any` instead of `unknown`
  types/styled-system__props/index.d.ts
  types/styled-system__props/styled-system__props-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#61167 [react] Add test suite for what can be returned from render
  types/react/test/tsx.tsx
  types/react/v16/test/tsx.tsx
  types/react/v17/test/tsx.tsx
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#61297 Update react-edit-text: add missing props
  types/react-edit-text/index.d.ts
  types/react-edit-text/react-edit-text-tests.tsx
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#61173 Added declarations file addressing issue#12 for package rclone.js
  types/rclone.js/index.d.ts
  types/rclone.js/rclone.js-tests.ts
  types/rclone.js/tsconfig.json
  types/rclone.js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61273 @types/node: add missing v18 stable properties for streams
  types/levelup/index.d.ts
  types/levelup/levelup-tests.ts
  types/node/stream.d.ts
  types/readable-stream/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#61301 [fabric] Add selected types to IEvent for 'selection:<modifier>' support
  types/fabric/fabric-impl.d.ts
  types/fabric/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#60885 Added types for rrdtool
  types/rrdtool/index.d.ts
  types/rrdtool/rrdtool-tests.ts
  types/rrdtool/tsconfig.json
  types/rrdtool/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#61289 Update `mustache` for the use in ES modules
  types/mustache/OTHER_FILES.txt
  types/mustache/index.d.mts
  types/mustache/index.d.ts
  types/mustache/mustache-tests.ts
  types/mustache/package.json
  types/mustache/test/commonjs.ts
  types/mustache/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Check Config

#61315 feat(react-instantsearch-core): adding facetOrdering to RefinementListExposed interface
  types/react-instantsearch-core/index.d.ts
  types/react-instantsearch-core/react-instantsearch-core-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#61252 Update vue 2 dependents
  types/vue-feather-icons/index.d.ts
  types/vue-select/index.d.ts
Labels: Edits multiple packages, Untested Change

#61314 [@types/mocha] Fix `import` statements for the Use in ES Modules
  types/mustache/index.d.mts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Check Config

#61317 Updating createdRowFunc signature
  types/datatables.net/datatables.net-tests.ts
  types/datatables.net/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#61268 [bootstrap] Add types for Modal events
  types/bootstrap/index.d.ts
  types/bootstrap/js/dist/modal.d.ts
  types/bootstrap/test/modal-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#61285 [indy-sdk] fix(indy-sdk): build attrib request
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60581 fix: add missing parameters on Link props
  types/react-scroll/modules/components/Link.d.ts
  types/react-scroll/test/react-scroll-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#61332 [three] r142
  types/three/OTHER_FILES.txt
  types/three/examples/jsm/controls/FirstPersonControls.d.ts
  types/three/examples/jsm/controls/FlyControls.d.ts
  types/three/examples/jsm/controls/OrbitControls.d.ts
  types/three/examples/jsm/curves/NURBSUtils.d.ts
  types/three/examples/jsm/loaders/GLTFLoader.d.ts
  types/three/examples/jsm/postprocessing/SAOPass.d.ts
  types/three/examples/jsm/shaders/ACESFilmicToneMappingShader.d.ts
  types/three/examples/jsm/shaders/SSRrShader.d.ts
  types/three/examples/jsm/utils/CameraUtils.d.ts
  types/three/examples/jsm/utils/GeometryCompressionUtils.d.ts
  types/three/examples/jsm/utils/GeometryUtils.d.ts
  types/three/examples/jsm/utils/SkeletonUtils.d.ts
  types/three/index.d.ts
  types/three/src/audio/AudioContext.d.ts
  types/three/src/extras/DataUtils.d.ts
  types/three/src/renderers/WebGLRenderer.d.ts
  types/three/test/audio/audio-context.ts
  types/three/test/lines/lines-line2.ts
  types/three/test/postprocessing/postprocessing-acesfilmictonemapping.ts
  types/three/test/utils/utils-webgl-portal.ts
  types/three/tsconfig.json
Labels: Popular package, Author is Owner, Owner Approved, Check Config

#61336 [luxon] adds parseFormatForOpts to support 3.0
  types/luxon/index.d.ts
  types/luxon/src/datetime.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Popular package, Self Merge, Owner Approved

#61156 [semantic-release] add Branch and improve Logger typings
  types/semantic-release/index.d.ts
  types/semantic-release/semantic-release-tests.ts
Labels: Self Merge, Maintainer Approved

#61324 Add @types/cytoscape-context-menus
  types/cytoscape-context-menus/cytoscape-context-menus-tests.ts
  types/cytoscape-context-menus/index.d.ts
  types/cytoscape-context-menus/tsconfig.json
  types/cytoscape-context-menus/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61330 Adds @types/geojson-vt
  types/geojson-vt/geojson-vt-tests.ts
  types/geojson-vt/index.d.ts
  types/geojson-vt/tsconfig.json
  types/geojson-vt/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#61300 Update ErrorResult interface for jsforce
  types/jsforce/record-result.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#61145 [plaid-link] add optional institution_id arg to LinkHandler 'open'
  types/plaid-link/index.d.ts
  types/plaid-link/plaid-link-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#61282 web-bluetooth: remove non-existant property
  types/web-bluetooth/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#61326 [roslib] Add dispose method to ActionClient
  types/roslib/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#61335 [jsrsasign] Fix return of X509#getExtInfo
  types/jsrsasign/modules/X509.d.ts
Labels: Self Merge, Owner Approved, Untested Change
