Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2022-06, with the labels that each got.

#60590 Updated for DSB 1.17.0 release
  types/consumer-data-standards/admin/index.d.ts
  types/consumer-data-standards/banking/index.d.ts
  types/consumer-data-standards/common/index.d.ts
  types/consumer-data-standards/dcr/index.d.ts
  types/consumer-data-standards/energy/index.d.ts
  types/consumer-data-standards/energy_sdh/index.d.ts
  types/consumer-data-standards/index.d.ts
  types/consumer-data-standards/register/index.d.ts
  types/consumer-data-standards/tslint.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, Check Config, No Other Owners, Huge Change

#60425 [UIkit] Include 'add' functionality to Icons
  types/uikit/dist/js/uikit.d.ts
  types/uikit/uikit-tests.ts
Labels: Self Merge, Owner Approved

#60603 Add focusInputOnCountrySelection type to react-phone-number-input
  types/react-phone-number-input/index.d.ts
  types/react-phone-number-input/test/react-phone-number-input.tsx
Labels: Popular package, Self Merge, Owner Approved

#60619 fix(uglify-js): add `webkit` in minify options
  types/uglify-js/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#60569 feat: create mimetext types
  types/mimetext/index.d.ts
  types/mimetext/mimetext-tests.ts
  types/mimetext/tsconfig.json
  types/mimetext/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60584 Jest 28.x Update some Types definitions
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60561 @ckeditor/ckeditor5-link Better definition for LinkConfig interface and decorators property
  types/ckeditor__ckeditor5-link/ckeditor__ckeditor5-link-tests.ts
  types/ckeditor__ckeditor5-link/src/link.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60621 fix(awsome-notifications): typo for `confirmOk`
  types/awesome-notifications/awesome-notifications-tests.ts
  types/awesome-notifications/index.d.ts
Labels: Other Approved, Self Merge

#60632 [sharedb] Add custom event support for Backend#on
  types/sharedb/index.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#60527 d3-org-chart: update `expandAll` & `collapseAll` return types
  types/d3-org-chart/d3-org-chart-tests.ts
  types/d3-org-chart/index.d.ts
Labels: Self Merge, Owner Approved

#60633 [json-logic-js] update to v2
  types/json-logic-js/index.d.ts
  types/json-logic-js/json-logic-js-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#60573 Add node-midi (just 'midi' on npm) type declarations
  types/midi/index.d.ts
  types/midi/midi-tests.ts
  types/midi/tsconfig.json
  types/midi/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60285 [@types/uikit] Update to uikit 3.14.1
  types/uikit/dist/js/uikit.d.ts
  types/uikit/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#60608 `@types/greasemonkey`: add `responseType` property to `GM.Request`
  types/greasemonkey/greasemonkey-tests.ts
  types/greasemonkey/index.d.ts
Labels: Other Approved, Self Merge, Owner Approved

#60643 Update @types/fhir
  types/fhir/index.d.ts
  types/fhir/r2.d.ts
  types/fhir/r3.d.ts
  types/fhir/r4.d.ts
  types/fhir/r5.d.ts
  types/fhir/test/r2-tests.ts
  types/fhir/test/r3-tests.ts
  types/fhir/test/r4-tests.ts
  types/fhir/test/r5-tests.ts
  types/fhir/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved, Huge Change

#60640 Create a type for plotly.js hover event
  types/plotly.js/index.d.ts
  types/react-plotly.js/index.d.ts
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved, Untested Change

#60644 [qunit] add prop-contains and not-prop-contains
  types/qunit/index.d.ts
  types/qunit/test/global-test.ts
Labels: Popular package, Self Merge, Owner Approved

#60652 [office-js] Update documentation of tests file
  types/office-js/office-js-tests.ts
Labels: Author is Owner

#60627 feat: Ssdeep types (Ssdeep.js)
  types/ssdeep.js/index.d.ts
  types/ssdeep.js/ssdeep.js-tests.ts
  types/ssdeep.js/tsconfig.json
  types/ssdeep.js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60455 Updates types for Recurly.js v4.21.0
  types/recurly__recurly-js/index.d.ts
  types/recurly__recurly-js/lib/configure.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Untested Change

#60597 [aws-lambda] Add AutoScalingScaleInHandler
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/autoscaling-tests.ts
  types/aws-lambda/test/cognito-tests.ts
  types/aws-lambda/trigger/autoscaling.d.ts
  types/aws-lambda/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60651 [react] add missing html table attributes
  types/react/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#60636 [SnapSVG] fix MouseEvent by TouchEvent on Touch handlers
  types/snapsvg/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#60618 fix: typo for the automaticallyAdjustKeyboardInsets description
  types/react-native/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package, Untested Change

#60635 [react-datepicker] add type CalendarContainerProps
  types/react-datepicker/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change, Edits Owners

#60606 Add new package: marv
  types/marv/api/callback.d.ts
  types/marv/api/promise.d.ts
  types/marv/index.d.ts
  types/marv/marv-tests.ts
  types/marv/tsconfig.json
  types/marv/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60657 [svelte-leafletjs] support events props to LeafletMap
  types/svelte-leafletjs/index.d.ts
  types/svelte-leafletjs/package.json
  types/svelte-leafletjs/svelte-leafletjs-tests.ts
Labels: Self Merge, Owner Approved

#60667 feat: update clientjs import
  types/clientjs/clientjs-tests.ts
  types/clientjs/index.d.ts
Labels: Self Merge, Owner Approved

#60631 jest: Add closeTo function
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#60495 [node] mark POSIX-only functions as optional
  types/node/process.d.ts
  types/node/test/process.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60572 [react-map-gl] Add explicit types for children for Popup and Marker
  types/react-map-gl/index.d.ts
  types/react-map-gl/react-map-gl-tests.tsx
Labels: Self Merge, Owner Approved

#60671 [ramda] Add curried definition for uncurryN
  types/ramda/index.d.ts
  types/ramda/test/uncurryN-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60666 chore: add the type 'zh-CN' to IdentityCardLocale and the type 'CN' to PostalCodeLocale
  types/validator/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#60641 [react] Add default value for `PropsWithChildren` type parameter
  types/react/index.d.ts
  types/react/test/tsx.tsx
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#60669 Add new package: marv-pg-driver
  types/marv-pg-driver/index.d.ts
  types/marv-pg-driver/marv-pg-driver-tests.ts
  types/marv-pg-driver/tsconfig.json
  types/marv-pg-driver/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#60649 Bigi - Change type of modInverse from "number" to "bigi"
  types/bigi/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#60659 [mssql] Add authentication to connection config
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60574 [react-flatpickr] Add explicit children prop
  types/react-flatpickr/index.d.ts
  types/react-flatpickr/react-flatpickr-tests.tsx
Labels: Self Merge, Owner Approved

#60664 [DT Infrastructure] Fix failing jobs since change from CJS to ESM
  scripts/ghostbuster.js
  scripts/update-codeowners.js
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#60490 Add NumeralOption `tailPrefix` in Cleave.js
  types/cleave.js/options/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#60660 [transit-js] add types for transit-js
  types/transit-js/index.d.ts
  types/transit-js/transit-js-tests.ts
  types/transit-js/tsconfig.json
  types/transit-js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60668 [Sharp] Fix blend mode
  types/sharp/index.d.ts
Labels: Other Approved, Popular package, Owner Approved, Untested Change

#60672 [json-logic-js] export type aliases for each logic operation
  types/json-logic-js/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#60646 Update definitions for react-resizable v3.0.4
  types/react-resizable/index.d.ts
  types/react-resizable/react-resizable-tests.tsx
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#60702 [cache-manager] Update to v4.0.1
  types/cache-manager/cache-manager-tests.ts
  types/cache-manager/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#60701 [@types/fabric] tune Object#scaleToHeight & Object#scaleToWidth return types
  types/fabric/fabric-impl.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60706 [node] Change TLSSocket `encrypted` type to `true`
  types/node/test/tls.ts
  types/node/tls.d.ts
  types/node/v12/tls.d.ts
  types/node/v14/tls.d.ts
  types/node/v16/tls.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60388 [@types/parse] adds subscribe()'s sessionToken parameter
  types/parse/index.d.ts
  types/parse/parse-tests.ts
Labels: Self Merge, Maintainer Approved

#60308 mapbox-gl: Add CustomSource type definitions
  types/mapbox-gl/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#60663 [chrome] Add new chrome.storage.session StorageArea - Chrome 102+
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60588 Add types for `@hapi/content`, `@hapi/subtext` and update types for `@hapi/call`
  types/hapi__call/hapi__call-tests.ts
  types/hapi__call/index.d.ts
  types/hapi__content/hapi__content-tests.ts
  types/hapi__content/index.d.ts
  types/hapi__content/tsconfig.json
  types/hapi__content/tslint.json
  types/hapi__subtext/hapi__subtext-tests.ts
  types/hapi__subtext/index.d.ts
  types/hapi__subtext/tsconfig.json
  types/hapi__subtext/tslint.json
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved, Check Config, Edits Owners

#60683 Correct typing for input_components in manifest
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#60682 [aws-lambda] add custom sms sender cognito trigger
  types/aws-lambda/test/cognito-tests.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/custom-sms-sender.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60409 [gapi.drive] add supportsAllDrives and fields to GetParameters interface
  types/gapi.drive/gapi.drive-tests.ts
  types/gapi.drive/index.d.ts
Labels: Self Merge, Maintainer Approved

#60432 fix AttributeType constant for MultiOptionSet in xrm package
  types/xrm/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#60656 [yandex-maps] add suggest method for search suggestions
  types/yandex-maps/index.d.ts
  types/yandex-maps/yandex-maps-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#60522 [heap] Add definitions for missing methods `contains` / `has` and `clear`
  types/heap/heap-tests.ts
  types/heap/index.d.ts
Labels: Other Approved, Self Merge

#60163 feat: Add type definitions for Sign In With Google JavaScript API
  types/gsi/gsi-tests.ts
  types/gsi/index.d.ts
  types/gsi/tsconfig.json
  types/gsi/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60717 chore: bump lerna type versions to 5.1
  types/lerna__child-process/index.d.ts
  types/lerna__collect-updates/index.d.ts
  types/lerna__package-graph/index.d.ts
  types/lerna__package/index.d.ts
  types/lerna__project/index.d.ts
  types/lerna__query-graph/index.d.ts
  types/lerna__run-topologically/index.d.ts
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, Untested Change, No Other Owners

#60653 Created types for react-pivottable
  types/react-pivottable/PivotTable.d.ts
  types/react-pivottable/PivotTableUI.d.ts
  types/react-pivottable/PlotlyRenderers.d.ts
  types/react-pivottable/TableRenderers.d.ts
  types/react-pivottable/Utilities.d.ts
  types/react-pivottable/index.d.ts
  types/react-pivottable/input.d.ts
  types/react-pivottable/react-pivottable-tests.tsx
  types/react-pivottable/tsconfig.json
  types/react-pivottable/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60710 update(puppeteer-core): remove v1 sources
  types/puppeteer-core/v1/index.d.ts
  types/puppeteer-core/v1/puppeteer-core-tests.ts
  types/puppeteer-core/v1/tsconfig.json
  types/puppeteer-core/v1/tslint.json
Labels: Popular package, Self Merge, Owner Approved

#60595 [eslint] Strongly-type the 'plugins' field on the ESLint.Options interface
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
  types/xo/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#60679 :trash: remove Puppeteer v0 sources
  types/puppeteer/v0/index.d.ts
  types/puppeteer/v0/puppeteer-tests.ts
  types/puppeteer/v0/tsconfig.json
  types/puppeteer/v0/tslint.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#60714 Mark `@wordpress/jest-console` as not needed
  notNeededPackages.json
  types/wordpress__jest-console/index.d.ts
  types/wordpress__jest-console/tsconfig.json
  types/wordpress__jest-console/tslint.json
  types/wordpress__jest-console/wordpress__jest-console-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#60665 Add types for tablestore
  types/tablestore/index.d.ts
  types/tablestore/tablestore-tests.ts
  types/tablestore/tsconfig.json
  types/tablestore/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60716 [hafas-client] version 5.24
  types/hafas-client/hafas-client-tests.ts
  types/hafas-client/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60725 update(puppeteer): remove sources for v1
  types/puppeteer/v1/DeviceDescriptors.d.ts
  types/puppeteer/v1/Errors.d.ts
  types/puppeteer/v1/index.d.ts
  types/puppeteer/v1/puppeteer-tests.ts
  types/puppeteer/v1/tsconfig.json
  types/puppeteer/v1/tslint.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#60712 Add typings for link2aws
  types/link2aws/index.d.ts
  types/link2aws/link2aws-tests.ts
  types/link2aws/tsconfig.json
  types/link2aws/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#60724 [leaflet] Fix overload order for events
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60737 [react-native-auth0] - Correcting the federated parameter in WabAuth.clearSession to be optional according to the documenation.
  types/react-native-auth0/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60741 VS Code 1.68.0 Extension API
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#60729 Pacify tests
  types/ckeditor__ckeditor5-utils/ckeditor__ckeditor5-utils-tests.ts
  types/map-to-obj/map-to-obj-tests.ts
  types/swagger-stats/package.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#60596 Add missing styles
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Self Merge, Maintainer Approved, Critical package, Edits Owners

#60720 [aws-lambda]: Add DynamoDBStreamHandler response object with `batchItemFailures` support
  types/aws-lambda/test/dynamodb-tests.ts
  types/aws-lambda/trigger/dynamodb-stream.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60689 [@types/tryghost__content-api] fix version number 5.0
  types/tryghost__content-api/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#60684 multer-s3 3.0.x definitions
  types/multer-s3/index.d.ts
  types/multer-s3/multer-s3-tests.ts
  types/multer-s3/package.json
Labels: Other Approved, Self Merge, Owner Approved

#60362 feat: add onCreateBatch to MPConfiguration
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/package.json
  types/mparticle__web-sdk/test/mparticle__web-sdk-instance-tests.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#60743 Add types for three-gif-loader
  types/three-gif-loader/index.d.ts
  types/three-gif-loader/lib/gif-texture.d.ts
  types/three-gif-loader/three-gif-loader-tests.ts
  types/three-gif-loader/tsconfig.json
  types/three-gif-loader/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60762 fix(@types/ember-cli-fastboot): fix isFastBoot property
  types/ember-cli-fastboot/services/fastboot.d.ts
  types/ember-cli-fastboot/test/ember-cli-fastboot-tests.ts
Labels: Self Merge, Owner Approved

#60694 update(uglify-js): v3.16 updates
  types/uglify-js/index.d.ts
  types/uglify-js/uglify-js-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#60722 feat(node): add Readable.toWeb and Readable.fromWeb
  types/node/stream.d.ts
  types/node/test/stream.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60757 add ali-oss type override
  types/ali-oss/ali-oss-tests.ts
  types/ali-oss/index.d.ts
Labels: Other Approved, Self Merge

#60439 feat(dialogify-browser): v1.0 type definition
  types/dialogify-browser/dialogify-browser-tests.ts
  types/dialogify-browser/dialogify.d.ts
  types/dialogify-browser/index.d.ts
  types/dialogify-browser/tsconfig.json
  types/dialogify-browser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60565 update(minify): v9 update and missing exports added
  types/minify/index.d.ts
  types/minify/lib/css.d.ts
  types/minify/lib/html.d.ts
  types/minify/lib/img.d.ts
  types/minify/lib/js.d.ts
  types/minify/lib/minify.d.ts
  types/minify/minify-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#60765 Add new package "react-type-animation"
  types/react-type-animation/index.d.ts
  types/react-type-animation/react-type-animation-tests.tsx
  types/react-type-animation/tsconfig.json
  types/react-type-animation/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60751 Add types for contrast-color
  types/contrast-color/contrast-color-tests.ts
  types/contrast-color/index.d.ts
  types/contrast-color/tsconfig.json
  types/contrast-color/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60579 MatchSelector (xpath) object support for expect-puppeteer
  types/expect-puppeteer/expect-puppeteer-tests.ts
  types/expect-puppeteer/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#60758 fix(@types/braintree): fix update request type
  types/braintree/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60563 add onStart and onBack to Gamepad component props in react-gamepad
  types/react-gamepad/index.d.ts
  types/react-gamepad/test/readme-tests.tsx
Labels: Self Merge, Owner Approved

#60739 [Vanilla Datepicker js] fixed DatepickerOptions prev arrow missing
  types/vanillajs-datepicker/Datepicker.d.ts
  types/vanillajs-datepicker/vanillajs-datepicker-tests.ts
Labels: Other Approved, Self Merge

#60791 [remark-hint] Requires TS >=4.5
  types/remark-hint/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60562 Update req.logout for passport 0.6.0
  types/passport/index.d.ts
  types/passport/passport-tests.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#60676 [google-apps-script] avoid duplicated declaration for `console` object with @types/node
  types/google-apps-script/google-apps-script.base.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
  types/google-apps-script/test/google-apps-script-tests.with-node.ts
  types/google-apps-script/tsconfig.json
Labels: Self Merge, Owner Approved

#60774 Update evaluatex to include ast
  types/evaluatex/evaluatex-tests.ts
  types/evaluatex/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60790 fix(pica): correct `resizeBuffer` types
  types/pica/index.d.ts
  types/pica/test/pica-tests.cjs.ts
  types/pica/test/pica-tests.global.ts
Labels: Self Merge, Owner Approved

#60585 express-serve-static-core: make Express.Response.get return string|undefined
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express-serve-static-core/ts4.0/express-serve-static-core-tests.ts
  types/express-serve-static-core/ts4.0/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package

#60571 [Rascal] Mixed Shorthand Configurations
  types/rascal/index.d.ts
  types/rascal/rascal-tests.ts
Labels: Self Merge, Owner Approved

#60796 fix(@types/waterline): remove bad attributes
  types/waterline/waterline-tests.ts
Labels: Self Merge, Maintainer Approved

#60795 fix(@types/node): url.parse API has been un-deprecated
  types/node/url.d.ts
  types/node/v16/url.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#60777 Fix type "react-type-animation"
  types/react-type-animation/index.d.ts
  types/react-type-animation/react-type-animation-tests.tsx
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#60797 twitter-text: add type definition of regexen
  types/twitter-text/index.d.ts
  types/twitter-text/twitter-text-tests.ts
Labels: Self Merge, Owner Approved

#60813 update tabulator-tables added missing debug options and rowMoving event
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#60784 @types/django-bananas
  types/django-bananas/auth/PermissionRequired.d.ts
  types/django-bananas/auth/UserPassesTest.d.ts
  types/django-bananas/colors.d.ts
  types/django-bananas/django-bananas-tests.tsx
  types/django-bananas/index.d.ts
  types/django-bananas/themes.d.ts
  types/django-bananas/tsconfig.json
  types/django-bananas/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60810 node: Fix doc spacing for domain module
  types/node/domain.d.ts
  types/node/v16/domain.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#60826 types/nightwatch - Fix acceptable input types for frame command (allow CSS string)
  types/nightwatch/index.d.ts
  types/nightwatch/test/nightwatch-tests.ts
Labels: Self Merge, Owner Approved

#60808 node-fetch: make implementeation compatible with lib.dom.d.ts
  types/node-fetch/externals.d.ts
  types/node-fetch/node-fetch-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60827 Azure Data Studio 1.37.0 Extension API
  types/azdata/azdata-tests.ts
  types/azdata/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60816 Remove `git log --follow` from FAQ
  README.es.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#60793 Update evaluatex to support custom functions
  types/evaluatex/dist/evaluatex.d.ts
  types/evaluatex/evaluatex-tests.ts
  types/evaluatex/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60831 [@types/indy-sdk] add types for logging functions
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Self Merge, Owner Approved

#60691 [react] Allow `TrustedHTML` in `dangerouslySetInnerHTML`
  types/react/global.d.ts
  types/react/index.d.ts
  types/react/test/index.ts
  types/react/v16/global.d.ts
  types/react/v16/index.d.ts
  types/react/v16/test/index.ts
  types/react/v17/global.d.ts
  types/react/v17/index.d.ts
  types/react/v17/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#60533 [pacote] Add some result fields
  types/pacote/index.d.ts
  types/pacote/pacote-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60835 [react-scroll-sync] ScrollSyncPaneProps.group also accepts string[]
  types/react-scroll-sync/index.d.ts
  types/react-scroll-sync/react-scroll-sync-tests.tsx
Labels: Self Merge, Owner Approved

#60837 Revert "🤖 Merge PR #60691 [react] Allow `TrustedHTML` in `dangerously…
  types/react/global.d.ts
  types/react/index.d.ts
  types/react/test/index.ts
  types/react/v16/global.d.ts
  types/react/v16/index.d.ts
  types/react/v16/test/index.ts
  types/react/v17/global.d.ts
  types/react/v17/index.d.ts
  types/react/v17/test/index.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60833 Add types for @novnc/novnc
  types/novnc__novnc/index.d.ts
  types/novnc__novnc/novnc__novnc-tests.ts
  types/novnc__novnc/tsconfig.json
  types/novnc__novnc/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60832 fix(@jest/types): align jest v28 dependencies (requires typescript bump to v4.5)
  types/expect-puppeteer/index.d.ts
  types/heft-jest/index.d.ts
  types/jest-axe/index.d.ts
  types/jest-expect-message/index.d.ts
  types/jest-image-snapshot/index.d.ts
  types/jest-in-case/index.d.ts
  types/jest-json-schema/index.d.ts
  types/jest-matcher-one-of/index.d.ts
  types/jest-plugin-context/index.d.ts
  types/jest-sinon/index.d.ts
  types/jest-specific-snapshot/index.d.ts
  types/jest-when/index.d.ts
  types/jest/index.d.ts
  types/jest/package.json
  types/mapbox__aws-sdk-jest/index.d.ts
  types/testing-library__jest-dom/index.d.ts
Labels: Other Approved, Self Merge, Edits multiple packages, Maintainer Approved, Critical package, Untested Change

#60856 Add assert.timeout to @types/qunit
  types/qunit/index.d.ts
  types/qunit/test/global-test.ts
Labels: Popular package, Self Merge, Owner Approved

#60861 [smartystreets-javascript-sdk] Fix typo in Lookup class
  types/smartystreets-javascript-sdk/index.d.ts
  types/smartystreets-javascript-sdk/smartystreets-javascript-sdk-tests.ts
Labels: Self Merge, Owner Approved

#60867 Update type definitions for `spdx-correct`, bringing it up to date with versions 3.1.0 and 3.1.1
  types/spdx-correct/index.d.ts
  types/spdx-correct/spdx-correct-tests.ts
Labels: Self Merge, Owner Approved

#60855 [selfsigned] support usage without arguments
  types/selfsigned/index.d.ts
  types/selfsigned/selfsigned-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60869 cookieclicker: Update types to 2.048
  types/cookieclicker/cookieclicker-tests.ts
  types/cookieclicker/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60821 [react-native]: fix missing callback typing for Modal props `onRequestClose`
  types/react-native/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#60858 Update hyper-function-component
  types/hyper-function-component/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#60782 [meteor] Implemented async MongoDB API and hint.
  types/meteor/globals/mongo.d.ts
  types/meteor/globals/server-render.d.ts
  types/meteor/index.d.ts
  types/meteor/mongo.d.ts
  types/meteor/test/globals/meteor-tests.ts
  types/meteor/test/meteor-mongo-tests.ts
  types/meteor/test/meteor-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60693 [@wordpress/data] Fix return value of dispatched actions to be a Promise
  types/wordpress__data/index.d.ts
  types/wordpress__data/wordpress__data-tests.tsx
Labels: Other Approved, Self Merge

#60887 Microsoft Graph - Upgrade to 2.22
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60864 added definitions for react-modal-video
  types/react-modal-video/index.d.ts
  types/react-modal-video/react-modal-video-tests.tsx
  types/react-modal-video/tsconfig.json
  types/react-modal-video/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60838 Type definitions for meteor/react-meteor-data v1.0.0
  types/meteor/index.d.ts
  types/meteor/react-meteor-accounts.d.ts
  types/meteor/test/react-meteor-accounts-tests.tsx
  types/meteor/tsconfig.json
Labels: Self Merge, Owner Approved

#60892 @types/django-bananas fixes
  types/django-bananas/django-bananas-tests.tsx
  types/django-bananas/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#60798 [use-position] update type definitions
  types/use-position/index.d.ts
Labels: Untested Change, Edits Owners

#60718 update typing for react-geocode
  types/react-geocode/index.d.ts
Labels: Untested Change

#60890 doc(react-native): Remove myself from authors
  types/react-native/index.d.ts
  types/react-native/v0.63/index.d.ts
  types/react-native/v0.64/index.d.ts
  types/react-native/v0.65/index.d.ts
  types/react-native/v0.66/index.d.ts
Labels: Author is Owner, Owner Approved, Critical package, Untested Change, Edits Owners

#60850 Google App Scripts: add attachments
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#60871 fix(jest): improving spyOn for better auto complete suggestions
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Owner Approved, Critical package

#60886 feat(video.js): return type for the VideoJSPlayer#played() method
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#60845 [redux-define] make it easier for consumers to use Action type
  types/redux-define/index.d.ts
  types/redux-define/redux-define-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60896 [DT Infra] Update supported versions mentioned in README
  README.es.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh.md
Labels: Edits Infrastructure

#60910 Remove myself from authors
  types/react-transition-group/index.d.ts
Labels: Author is Owner, Owner Approved, Critical package, Untested Change, Edits Owners

#60899 throng: remove self from Definition Owner
  types/throng/index.d.ts
Labels: Author is Owner, Untested Change, Edits Owners

#60912 fix(video.js): preload options isn't any old string
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#60884 Feature/adobe pdf service
  types/adobe__pdfservices-node-sdk/adobe__pdfservices-node-sdk-tests.ts
  types/adobe__pdfservices-node-sdk/auth/credentials.d.ts
  types/adobe__pdfservices-node-sdk/auth/service-account-credentials-builder.d.ts
  types/adobe__pdfservices-node-sdk/auth/service-account-credentials.d.ts
  types/adobe__pdfservices-node-sdk/client-config.d.ts
  types/adobe__pdfservices-node-sdk/error/service-api-error.d.ts
  types/adobe__pdfservices-node-sdk/error/service-usage-error.d.ts
  types/adobe__pdfservices-node-sdk/execution-context.d.ts
  types/adobe__pdfservices-node-sdk/index.d.ts
  types/adobe__pdfservices-node-sdk/io/file-ref.d.ts
  types/adobe__pdfservices-node-sdk/operation/combine-file-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/compress-pdf-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/create-pdf-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/delete-pages-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/document-merge-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/export-pdf-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/export-pdf-to-images-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/extract-pdf-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/insert-pages-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/linearize-pdf-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/ocr-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/compresspdf/compress-pdf-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/createpdf/create-pdf-from-excel-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/createpdf/create-pdf-from-html-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/createpdf/create-pdf-from-ppt-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/createpdf/create-pdf-from-word-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/createpdf/page-layout.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/documentmerge/document-merge-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/documentmerge/fragments.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/extractpdf/extract-pdf-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/ocr/ocr-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/page-ranges.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/pdfproperties/pdf-properties-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/protectpdf/password-protect-options.d.ts
  types/adobe__pdfservices-node-sdk/operation/option/protectpdf/permissions.d.ts
  types/adobe__pdfservices-node-sdk/operation/pdf-properties-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/protect-pdf-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/remove-protection-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/reorder-pages-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/replace-pages-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/rotate-pages-operation.d.ts
  types/adobe__pdfservices-node-sdk/operation/split-pdf-operation.d.ts
  types/adobe__pdfservices-node-sdk/pdfservices-sdk.d.ts
  types/adobe__pdfservices-node-sdk/tsconfig.json
  types/adobe__pdfservices-node-sdk/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60916 [snap-shot-core] Add package
  types/snap-shot-core/index.d.ts
  types/snap-shot-core/snap-shot-core-tests.ts
  types/snap-shot-core/tsconfig.json
  types/snap-shot-core/tslint.json
Labels: New Definition

#60920 fix(auth0): add scope to auth0.SignInOptions
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#60908 [tabulator-tables] fix GlobalTooltipOption
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#60735 [react-native-autocomplete-input] Add renderResultList prop and fix types
  types/react-native-autocomplete-input/index.d.ts
  types/react-native-autocomplete-input/react-native-autocomplete-input-tests.tsx
Labels: Self Merge, Owner Approved, Edits Owners

#60932 Update kap-plugin dependencies
  types/kap-plugin/index.d.ts
  types/kap-plugin/package.json
Labels: Owner Approved, Untested Change

#60933 Update luxon tests for TS 4.8
  types/luxon/test/luxon-tests.module.ts
Labels: Popular package, Self Merge, Owner Approved

#60934 Disable npm-naming in maptalks/react-router-guard
  types/maptalks/tslint.json
  types/react-router-guard/tslint.json
Labels: Edits multiple packages, Check Config

#60904 [@types/rpi-ws281x-native] Add types for "rpi-ws281x-native" package
  types/rpi-ws281x-native/index.d.ts
  types/rpi-ws281x-native/lib/constants.d.ts
  types/rpi-ws281x-native/rpi-ws281x-native-tests.ts
  types/rpi-ws281x-native/tsconfig.json
  types/rpi-ws281x-native/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60846 [ember-data] Add buildQuery method type for Ember RESTAdapter
  types/ember-data/index.d.ts
  types/ember-data/v2/index.d.ts
  types/ember-data/v3/index.d.ts
Labels: Untested Change
