Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2022-05, with the labels that each got.

#60135 Update definitions for JavaScript Color Gradient
  types/javascript-color-gradient/index.d.ts
  types/javascript-color-gradient/javascript-color-gradient-tests.ts
Labels: Other Approved, Self Merge

#59791 feat: diagnostics_channel channel.publish()
  types/node/diagnostics_channel.d.ts
  types/node/test/diagnostics_channel.ts
  types/node/v16/diagnostics_channel.d.ts
  types/node/v16/test/diagnostics_channel.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60124 [jsrsasign]Update jsrsasign types for v10.5
  types/jsrsasign/index.d.ts
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/ASN1HEX.d.ts
  types/jsrsasign/modules/KEYUTIL.d.ts
  types/jsrsasign/modules/KJUR/asn1/ASN1Object.d.ts
  types/jsrsasign/modules/KJUR/asn1/ASNObjects.d.ts
  types/jsrsasign/modules/KJUR/asn1/cades/CAdESUtil.d.ts
  types/jsrsasign/modules/KJUR/asn1/cms/CMSUtil.d.ts
  types/jsrsasign/modules/KJUR/asn1/csr/CSRUtil.d.ts
  types/jsrsasign/modules/KJUR/asn1/csr/CertificationRequestInfo.d.ts
  types/jsrsasign/modules/KJUR/asn1/tsp/PKIStatusInfo.d.ts
  types/jsrsasign/modules/KJUR/asn1/tsp/TSPUtil.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/AdobeTimeStamp.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/AlgorithmIdentifier.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/CRL.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/CRLNumber.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/CRLReason.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/Certificate.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/CertificatePolicies.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/OCSPNoCheck.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/OCSPNonce.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/SubjectDirectoryAttributes.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/SubjectKeyIdentifier.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/X500Name.d.ts
  types/jsrsasign/modules/KJUR/asn1/x509/index.d.ts
  types/jsrsasign/modules/KJUR/jws/JWS.d.ts
  types/jsrsasign/modules/X509.d.ts
  types/jsrsasign/modules/X509CRL.d.ts
Labels: Self Merge, Owner Approved

#60141 [video.js] - Added clickHandler option to ClickableComponent
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60136 [video.js] Added noUITitleAttributes param to player options
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#59849 formdiable: parse callback optional
  types/formidable/Formidable.d.ts
  types/formidable/formidable-tests.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#59971 [luxon] DateTime constructor is private
  types/luxon/src/datetime.d.ts
  types/luxon/src/duration.d.ts
  types/luxon/src/interval.d.ts
  types/luxon/src/zone.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Popular package, Self Merge, Owner Approved

#60145 [amqp-connection-manager] 🌇 Contains built-in declarations
  notNeededPackages.json
  types/amqp-connection-manager/amqp-connection-manager-tests.ts
  types/amqp-connection-manager/index.d.ts
  types/amqp-connection-manager/tsconfig.json
  types/amqp-connection-manager/tslint.json
Labels: Owner Approved, Edits Infrastructure

#60134 [infra] Delete .travis.yml
  .travis.yml
Labels: Edits Infrastructure

#59812 fixed-data-table-2: Add children to ColumnGroupProps props
  types/fixed-data-table-2/fixed-data-table-2-tests.tsx
  types/fixed-data-table-2/index.d.ts
Labels: Unreviewed

#60132 Add types for typedarray-to-buffer
  types/typedarray-to-buffer/index.d.ts
  types/typedarray-to-buffer/tsconfig.json
  types/typedarray-to-buffer/tslint.json
  types/typedarray-to-buffer/typedarray-to-buffer-tests.ts
Labels: New Definition

#59961 Update strophejs types
  types/strophe.js/index.d.ts
  types/strophe.js/muc.d.ts
  types/strophejs-plugin-roster/index.d.ts
Labels: Other Approved, Edits multiple packages, Untested Change, Unreviewed, Edits Owners

#60002 [react-tracking] useTracking generic type can be a function
  types/react-tracking/index.d.ts
  types/react-tracking/test/react-tracking-with-types-tests.tsx
Labels: Other Approved, Self Merge

#60118 [google-apps-script] Renamed Bigquery to BigQuery
  types/google-apps-script/apis/bigquery_v2.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#60149 Added types for npm package `leo-profanity`
  types/leo-profanity/index.d.ts
  types/leo-profanity/leo-profanity-tests.ts
  types/leo-profanity/tsconfig.json
  types/leo-profanity/tslint.json
Labels: New Definition

#60148 [infra] Upgrade actions/checkout and actions/setup-node
  .github/dependabot.yml
Labels: Edits Infrastructure

#59780 [@types/vimeo__player] Add missing player methods
  types/vimeo__player/index.d.ts
  types/vimeo__player/vimeo__player-tests.ts
Labels: Popular package, Edits Owners

#59787 [ramda] chore: normalize types
  types/ramda/index.d.ts
  types/ramda/test/constructN-tests.ts
  types/ramda/tools.d.ts
Labels: Popular package, Unreviewed

#60137 [jest] MockContext lastCall
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#60119 [gestalt] 53.1.1 April ( 28,2022)
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#60104 node-schedule: Add Promise<any> to JobCallback return
  types/node-schedule/index.d.ts
  types/node-schedule/node-schedule-tests.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#60009 (spotify-api) Replaced PlayHistoryObject.track with TrackObjectFull
  types/spotify-api/index.d.ts
  types/spotify-api/spotify-api-tests.ts
Labels: Self Merge, Owner Approved

#60057 [sharedb] Loosen creation types
  types/sharedb/lib/sharedb.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60131 [http-proxy] add generics for all callbacks
  types/http-proxy/http-proxy-tests.ts
  types/http-proxy/index.d.ts
Labels: Self Merge, Owner Approved, Critical package

#60143 [three] r140
  types/aframe/tsconfig.json
  types/three/OTHER_FILES.txt
  types/three/examples/jsm/controls/OrbitControls.d.ts
  types/three/examples/jsm/controls/TransformControls.d.ts
  types/three/examples/jsm/exporters/GLTFExporter.d.ts
  types/three/examples/jsm/loaders/GLTFLoader.d.ts
  types/three/examples/jsm/objects/Reflector.d.ts
  types/three/examples/jsm/objects/Refractor.d.ts
  types/three/examples/jsm/postprocessing/SavePass.d.ts
  types/three/examples/jsm/utils/BufferGeometryUtils.d.ts
  types/three/examples/jsm/utils/SkeletonUtils.d.ts
  types/three/index.d.ts
  types/three/src/Three.d.ts
  types/three/src/constants.d.ts
  types/three/src/extras/Earcut.d.ts
  types/three/src/materials/Material.d.ts
  types/three/src/materials/MeshBasicMaterial.d.ts
  types/three/src/materials/MeshLambertMaterial.d.ts
  types/three/src/materials/MeshMatcapMaterial.d.ts
  types/three/src/materials/MeshPhongMaterial.d.ts
  types/three/src/materials/MeshStandardMaterial.d.ts
  types/three/src/materials/MeshToonMaterial.d.ts
  types/three/src/materials/PointsMaterial.d.ts
  types/three/src/materials/ShadowMaterial.d.ts
  types/three/src/materials/SpriteMaterial.d.ts
  types/three/src/math/Color.d.ts
  types/three/src/math/Euler.d.ts
  types/three/src/math/Quaternion.d.ts
  types/three/test/postprocessing/postprocessing-savepass.ts
  types/three/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Check Config

#60168 mapbox-gl: add 'to-rgba' expression
  types/mapbox-gl/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#60169 [video.js] - Added nextSeekedFromUser method
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59793 Add tests for @ckeditor/ckeditor5-engine XmlDataProcessor
  types/ckeditor__ckeditor5-engine/OTHER_FILES.txt
  types/ckeditor__ckeditor5-engine/ckeditor__ckeditor5-engine-tests.ts
  types/ckeditor__ckeditor5-engine/src/dataprocessor/xmldataprocessor.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#60072 [@types/chrome] make `declarativeNetRequest.Rule.priority` optional
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#60166 write types for throttle-debounce v5.0
  types/throttle-debounce/index.d.ts
  types/throttle-debounce/throttle-debounce-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#60012 [protractor-http-mock] Support data, headers in mocks.
  types/protractor-http-mock/index.d.ts
  types/protractor-http-mock/protractor-http-mock-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59818 @types/dockerode: Added missing stats fields.
  types/dockerode/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60120 Typings for node-telegram-bot-api v6.0
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Other Approved, Self Merge, Edits Owners

#60173 Add missing comments to @ckeditor/ckeditor5-autoformat
  types/ckeditor__ckeditor5-autoformat/src/autoformat.d.ts
  types/ckeditor__ckeditor5-autoformat/src/blockautoformatediting.d.ts
  types/ckeditor__ckeditor5-autoformat/src/inlineautoformatediting.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#60031 [chess.js] Update board return type
  types/chess.js/chess.js-tests.ts
  types/chess.js/index.d.ts
Labels: Unreviewed

#60190 Types for bitcoin computer bitcore (New Package)
  types/bitcoin-computer-bitcore/bitcoin-computer-bitcore-tests.ts
  types/bitcoin-computer-bitcore/index.d.ts
  types/bitcoin-computer-bitcore/tsconfig.json
  types/bitcoin-computer-bitcore/tslint.json
Labels: New Definition

#60121 update(stopword): v2 updates
  types/stopword/index.d.ts
  types/stopword/stopword-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#60133 [video.js] - Added currentBreakpoint and currentBreakpointClass methods
  types/video.js/index.d.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#60208 [content-disposition] Update type of `parameters`
  types/content-disposition/content-disposition-tests.ts
  types/content-disposition/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60174 [bootstrap] fix: Return jQuery instance from jQuery functions
  types/bootstrap/js/dist/alert.d.ts
  types/bootstrap/js/dist/button.d.ts
  types/bootstrap/js/dist/carousel.d.ts
  types/bootstrap/js/dist/collapse.d.ts
  types/bootstrap/js/dist/dropdown.d.ts
  types/bootstrap/js/dist/modal.d.ts
  types/bootstrap/js/dist/offcanvas.d.ts
  types/bootstrap/js/dist/popover.d.ts
  types/bootstrap/js/dist/scrollspy.d.ts
  types/bootstrap/js/dist/tab.d.ts
  types/bootstrap/js/dist/toast.d.ts
  types/bootstrap/js/dist/tooltip.d.ts
  types/bootstrap/test/alert-tests.ts
  types/bootstrap/test/button-tests.ts
  types/bootstrap/test/carousel-tests.ts
  types/bootstrap/test/collapse-tests.ts
  types/bootstrap/test/dropdown-tests.ts
  types/bootstrap/test/modal-tests.ts
  types/bootstrap/test/offcanvas-tests.ts
  types/bootstrap/test/popover-tests.ts
  types/bootstrap/test/scrollspy-tests.ts
  types/bootstrap/test/tab-tests.ts
  types/bootstrap/test/toast-tests.ts
  types/bootstrap/test/tooltip-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#60209 Added missing definition for layers in [@types/serverless].service.provider
  types/serverless/classes/Service.d.ts
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60210 VS Code 1.67.0 Extension API
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#60188 feat(@types/react-pdf): add common property of TextLayerItemInternal
  types/react-pdf/dist/Page.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#60218 Implement freezeColumns property
  types/jspreadsheet-ce/index.d.ts
  types/jspreadsheet-ce/jspreadsheet-ce-tests.ts
Labels: Self Merge, Owner Approved

#60214 fast-als typing
  types/fast-als/fast-als-tests.ts
  types/fast-als/index.d.ts
  types/fast-als/tsconfig.json
  types/fast-als/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#59851 @ckeditor/ckeditor5-special-characters: Missing comments and better events typing
  types/ckeditor__ckeditor5-special-characters/ckeditor__ckeditor5-special-characters-tests.ts
  types/ckeditor__ckeditor5-special-characters/src/specialcharacters.d.ts
  types/ckeditor__ckeditor5-special-characters/src/specialcharactersarrows.d.ts
  types/ckeditor__ckeditor5-special-characters/src/specialcharacterscurrency.d.ts
  types/ckeditor__ckeditor5-special-characters/src/specialcharactersessentials.d.ts
  types/ckeditor__ckeditor5-special-characters/src/specialcharacterslatin.d.ts
  types/ckeditor__ckeditor5-special-characters/src/specialcharactersmathematical.d.ts
  types/ckeditor__ckeditor5-special-characters/src/specialcharacterstext.d.ts
  types/ckeditor__ckeditor5-special-characters/src/ui/charactergridview.d.ts
  types/ckeditor__ckeditor5-special-characters/src/ui/characterinfoview.d.ts
  types/ckeditor__ckeditor5-special-characters/src/ui/specialcharactersnavigationview.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/OTHER_FILES.txt
  types/ckeditor__ckeditor5-special-characters/v27/ckeditor__ckeditor5-special-characters-tests.ts
  types/ckeditor__ckeditor5-special-characters/v27/index.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/specialcharacters.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/specialcharactersarrows.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/specialcharacterscurrency.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/specialcharactersessentials.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/specialcharacterslatin.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/specialcharactersmathematical.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/specialcharacterstext.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/ui/charactergridview.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/ui/characterinfoview.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/src/ui/specialcharactersnavigationview.d.ts
  types/ckeditor__ckeditor5-special-characters/v27/tsconfig.json
  types/ckeditor__ckeditor5-special-characters/v27/tslint.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60195 adding typings for html2json
  types/html2json/html2json-tests.ts
  types/html2json/index.d.ts
  types/html2json/tsconfig.json
  types/html2json/tslint.json
Labels: New Definition

#60220 add types for webpack-files-archive-plugin
  types/webpack-files-archive-plugin/index.d.ts
  types/webpack-files-archive-plugin/package.json
  types/webpack-files-archive-plugin/tsconfig.json
  types/webpack-files-archive-plugin/tslint.json
  types/webpack-files-archive-plugin/webpack-files-archive-plugin-tests.ts
Labels: New Definition

#60232 [memoizee] add profileName to options
  types/memoizee/index.d.ts
  types/memoizee/memoizee-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60230 [react] Allow onCancel and onClose on <dialog /> elements
  types/react/index.d.ts
  types/react/test/elementAttributes.tsx
  types/react/v16/index.d.ts
  types/react/v16/test/elementAttributes.tsx
  types/react/v17/index.d.ts
  types/react/v17/test/elementAttributes.tsx
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#59935 [@ronomon/crypto-async] Update types to v5
  types/ronomon__crypto-async/index.d.ts
  types/ronomon__crypto-async/ronomon__crypto-async-tests.ts
  types/ronomon__crypto-async/tsconfig.json
  types/ronomon__crypto-async/tslint.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60176 [selenium-webdriver]:added types for chromium driver
  types/selenium-webdriver/chrome.d.ts
  types/selenium-webdriver/edge.d.ts
  types/selenium-webdriver/index.d.ts
  types/selenium-webdriver/networkinterceptor.d.ts
  types/selenium-webdriver/test/chrome.ts
  types/selenium-webdriver/test/index.ts
Labels: Self Merge, Owner Approved, Critical package

#60061 [snowflake-sdk] Define createPool function
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#60247 [sortablejs] Update to v1.13
  types/sortablejs/index.d.ts
  types/sortablejs/sortablejs-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60240 feat(aws-lambda): add cloudfront event record type
  types/aws-lambda/test/cloudfront-tests.ts
  types/aws-lambda/trigger/cloudfront-request.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#60245 [sequelize] Add null to some types to be able to use it with "strictNullChecks": true
  types/sequelize/index.d.ts
  types/sequelize/sequelize-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#59803 [@rifat/miio] Added discovery types
  types/rifat__miio/device.d.ts
  types/rifat__miio/discovery.d.ts
  types/rifat__miio/index.d.ts
  types/rifat__miio/rifat__miio-tests.ts
Labels: Unmerged, Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60250 [yaireo__tagify] version 4.12, additional dropdown templates
  types/yaireo__tagify/index.d.ts
  types/yaireo__tagify/yaireo__tagify-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60198 Adding the checked assertion
  types/chai-dom/chai-dom-tests.ts
  types/chai-dom/index.d.ts
Labels: Other Approved, Self Merge, Owner Approved

#60037 fix(amplitude-js): Rename onExit to onExitPage. Closes #59987
  types/amplitude-js/amplitude-js-tests.ts
  types/amplitude-js/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#60213 [jsrsasign 10.5.20] Adding missing key arg for JWS.sign
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/KJUR/jws/JWS.d.ts
Labels: Self Merge, Owner Approved

#60144 [aws-lambda] Handler typo
  types/aws-lambda/handler.d.ts
Labels: Self Merge, Owner Approved, Critical package, Untested Change

#60212 feat(find-package-json): Update package manifest type from schemastore
  types/find-package-json/find-package-json-tests.ts
  types/find-package-json/index.d.ts
  types/find-package-json/package-json.d.ts
Labels: Self Merge, Owner Approved

#60252 feat: :label: add clientProperties property to ConnectionAttributes
  types/rascal/index.d.ts
  types/rascal/rascal-tests.ts
Labels: Other Approved, Self Merge

#60248 feat(indy-sdk): add proverGetCredentials
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#60251 [react-canvas-draw] update types to v1.2.1
  types/react-canvas-draw/index.d.ts
  types/react-canvas-draw/react-canvas-draw-tests.tsx
Labels: Other Approved, Self Merge

#60233 [@cloudfour/simple-svg-placeholder] Add new types package
  types/cloudfour__simple-svg-placeholder/cloudfour__simple-svg-placeholder-tests.ts
  types/cloudfour__simple-svg-placeholder/index.d.ts
  types/cloudfour__simple-svg-placeholder/tsconfig.json
  types/cloudfour__simple-svg-placeholder/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60266 [svelte-leafletjs] support binding getters via props
  types/svelte-leafletjs/index.d.ts
  types/svelte-leafletjs/svelte-leafletjs-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#60069 humanparser - optional parameter added to parseName type definition
  types/humanparser/humanparser-tests.ts
  types/humanparser/index.d.ts
Labels: Other Approved, Self Merge

#60267 vexflow: add missing definitions for stave.setNumLines etc
  types/vexflow/index.d.ts
  types/vexflow/vexflow-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59806 feat: add `@npmcli/package-json` package
  types/npmcli__package-json/index.d.ts
  types/npmcli__package-json/npmcli__package-json-tests.ts
  types/npmcli__package-json/tsconfig.json
  types/npmcli__package-json/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60191 cli-progress 3.11
  types/cli-progress/cli-progress-tests.ts
  types/cli-progress/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#59914 feat(node): allow `undefined` as argument for functions that clear timers
  types/node/test/timers.ts
  types/node/timers.d.ts
  types/node/v12/globals.d.ts
  types/node/v12/timers.d.ts
  types/node/v14/globals.d.ts
  types/node/v14/timers.d.ts
  types/node/v16/timers.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60222 [Swagger-UI-React] Sync props with lib
  types/swagger-ui-react/index.d.ts
  types/swagger-ui-react/swagger-ui-react-tests.tsx
Labels: Other Approved, Self Merge

#59969 [react-breadcrumbs] Don't assume implicit children
  types/react-breadcrumbs/index.d.ts
  types/react-breadcrumbs/react-breadcrumbs-tests.tsx
Labels: Self Merge, Maintainer Approved

#59995 [stylus] Add `render` overloads
  types/stylus/index.d.ts
  types/stylus/stylus-tests.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#60059 [wordpress__blocks] Add typings for block variations registration api
  types/wordpress__blocks/api/registration.d.ts
  types/wordpress__blocks/index.d.ts
  types/wordpress__blocks/wordpress__blocks-tests.tsx
Labels: Self Merge, Owner Approved, Edits Owners

#59980 Leaflet.markercluster: Add typed events
  types/leaflet.markercluster/index.d.ts
  types/leaflet.markercluster/leaflet.markercluster-tests.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#60261 Add types for `ttest`
  types/ttest/index.d.ts
  types/ttest/tsconfig.json
  types/ttest/tslint.json
  types/ttest/ttest-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#60001 [google-map-react] Add `children` to the list of props
  types/google-map-react/google-map-react-tests.tsx
  types/google-map-react/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved, Edits Owners

#60260 Add evaluatex
  types/evaluatex/dist/evaluatex.d.ts
  types/evaluatex/evaluatex-tests.ts
  types/evaluatex/index.d.ts
  types/evaluatex/tsconfig.json
  types/evaluatex/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#60280 [ziggy-js]: Fix allow single RouteParam as Route Parameters
  types/ziggy-js/index.d.ts
  types/ziggy-js/ziggy-js-tests.ts
Labels: Self Merge, Owner Approved

#60217 [cron] Update to v2.0: replace moment with luxon
  types/cron/cron-tests.ts
  types/cron/index.d.ts
  types/cron/package.json
Labels: Popular package, Self Merge, Owner Approved

#60290 [@types/react-table] Include column on FooterProps
  types/react-table/index.d.ts
  types/react-table/react-table-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#60278 [jest] Make jest.mock type-safe
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#60275 graphql-resolve-batch: add info param & remove dependency on graphql@14
  types/graphql-resolve-batch/graphql-resolve-batch-tests.ts
  types/graphql-resolve-batch/index.d.ts
  types/graphql-resolve-batch/package.json
  types/graphql-resolve-batch/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Check Config

#60287 Add popup variable to the leafletEvent interface
  types/leaflet/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#60293 update kendo-ui typescript definitions to 2022.2.510
  types/kendo-ui/index.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Untested Change

#60283 Set plugins as optional in DirectEditorProps
  types/prosemirror-view/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#60292 oidc-provider - Add revokeGrantPolicy Configuration interface
  types/oidc-provider/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60272 Bugfix/60271 - Fix UIkitSwiterOptions name
  types/uikit/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60265 pg-cursor, the read method now returns the generic type passed to the constructor
  types/pg-cursor/index.d.ts
  types/pg-cursor/pg-cursor-tests.ts
Labels: Self Merge, Owner Approved

#60231 [selenium-webdriver] add ShadowRoot definition
  types/selenium-webdriver/index.d.ts
  types/selenium-webdriver/lib/by.d.ts
  types/selenium-webdriver/lib/capabilities.d.ts
  types/selenium-webdriver/lib/command.d.ts
  types/selenium-webdriver/lib/input.d.ts
  types/selenium-webdriver/lib/logging.d.ts
  types/selenium-webdriver/lib/promise.d.ts
  types/selenium-webdriver/lib/symbols.d.ts
  types/selenium-webdriver/lib/until.d.ts
  types/selenium-webdriver/lib/webdriver.d.ts
  types/selenium-webdriver/test/chrome.ts
  types/selenium-webdriver/test/edge.ts
  types/selenium-webdriver/test/firefox.ts
  types/selenium-webdriver/test/index.ts
  types/selenium-webdriver/test/logging.ts
  types/selenium-webdriver/test/remote.ts
  types/selenium-webdriver/v2/chrome.d.ts
  types/selenium-webdriver/v2/edge.d.ts
  types/selenium-webdriver/v2/executors.d.ts
  types/selenium-webdriver/v2/firefox.d.ts
  types/selenium-webdriver/v2/http.d.ts
  types/selenium-webdriver/v2/index.d.ts
  types/selenium-webdriver/v2/opera.d.ts
  types/selenium-webdriver/v2/remote.d.ts
  types/selenium-webdriver/v2/safari.d.ts
  types/selenium-webdriver/v2/testing.d.ts
  types/selenium-webdriver/v3/chrome.d.ts
  types/selenium-webdriver/v3/edge.d.ts
  types/selenium-webdriver/v3/firefox.d.ts
  types/selenium-webdriver/v3/ie.d.ts
  types/selenium-webdriver/v3/index.d.ts
  types/selenium-webdriver/v3/opera.d.ts
  types/selenium-webdriver/v3/remote.d.ts
  types/selenium-webdriver/v3/safari.d.ts
  types/selenium-webdriver/v3/testing.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Huge Change

#59926 Update @types/analytics-node flush
  types/analytics-node/analytics-node-tests.ts
  types/analytics-node/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#59690 prettier: Add generics for call, each, and map property keys
  types/babel-plugin-tester/index.d.ts
  types/prettier/index.d.ts
  types/prettier/prettier-tests.ts
  types/pretty-quick/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#60289 [react-modal-view] Add types for react-modal-view
  types/react-modal-view/index.d.ts
  types/react-modal-view/react-modal-view-tests.tsx
  types/react-modal-view/tsconfig.json
  types/react-modal-view/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60296 [@types/react-native] Add Android Bluetooth Permissions
  types/react-native/index.d.ts
  types/react-native/test/index.tsx
Labels: Self Merge, Owner Approved, Critical package

#60202 [react-dom] createPortal container can be a DocumentFragment
  types/react-dom/index.d.ts
  types/react-dom/test/react-dom-tests.tsx
  types/react-dom/v16/index.d.ts
  types/react-dom/v16/test/react-dom-tests.tsx
  types/react-dom/v17/index.d.ts
  types/react-dom/v17/test/react-dom-tests.tsx
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#60297 [lru-cache] rm typings as they are now included with the library
  notNeededPackages.json
  types/async-cache/package.json
  types/async-cache/tsconfig.json
  types/ejs/test/ejs.cjs.test.ts
  types/ejs/tsconfig.json
  types/lru-cache/index.d.ts
  types/lru-cache/lru-cache-tests.ts
  types/lru-cache/tsconfig.json
  types/lru-cache/tslint.json
  types/lru-cache/v4/index.d.ts
  types/lru-cache/v4/lru-cache-tests.ts
  types/lru-cache/v4/tsconfig.json
  types/lru-cache/v4/tslint.json
  types/mem-fs-editor/tsconfig.json
  types/mustache-express/package.json
  types/mustache-express/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package

#60305 [lost] Add types for lost
  types/lost/index.d.ts
  types/lost/lib/lg-gutter.d.ts
  types/lost/lib/lost-align.d.ts
  types/lost/lib/lost-at-rule.d.ts
  types/lost/lib/lost-center.d.ts
  types/lost/lib/lost-column.d.ts
  types/lost/lib/lost-flex-container.d.ts
  types/lost/lib/lost-masonry-column.d.ts
  types/lost/lib/lost-masonry-wrap.d.ts
  types/lost/lib/lost-move.d.ts
  types/lost/lib/lost-offset.d.ts
  types/lost/lib/lost-row.d.ts
  types/lost/lib/lost-utility.d.ts
  types/lost/lib/lost-vars-gutter-local.d.ts
  types/lost/lib/lost-vars-gutter.d.ts
  types/lost/lib/lost-vars.d.ts
  types/lost/lib/lost-waffle.d.ts
  types/lost/lib/new-block.d.ts
  types/lost/lost-tests.ts
  types/lost/package.json
  types/lost/tsconfig.json
  types/lost/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#59625 [node] Add missing timeout property on node's net.Socket
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v12/net.d.ts
  types/node/v12/test/net.ts
  types/node/v14/net.d.ts
  types/node/v14/test/net.ts
  types/node/v16/net.d.ts
  types/node/v16/test/net.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60187 [plotly.js] Config.setBackground function needs parentheses (fix #60184)
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#60277 add types for exaroton package 📦
  types/exaroton/exaroton-tests.ts
  types/exaroton/index.d.ts
  types/exaroton/package.json
  types/exaroton/tsconfig.json
  types/exaroton/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60249 @ckeditor/ckeditor5-horizontal-line Typing for events, plus missing comments
  types/ckeditor__ckeditor5-horizontal-line/ckeditor__ckeditor5-horizontal-line-tests.ts
  types/ckeditor__ckeditor5-horizontal-line/src/horizontalline.d.ts
  types/ckeditor__ckeditor5-horizontal-line/src/horizontallinecommand.d.ts
  types/ckeditor__ckeditor5-horizontal-line/src/horizontallineediting.d.ts
  types/ckeditor__ckeditor5-horizontal-line/src/horizontallineui.d.ts
  types/ckeditor__ckeditor5-horizontal-line/v27/ckeditor__ckeditor5-horizontal-line-tests.ts
  types/ckeditor__ckeditor5-horizontal-line/v27/index.d.ts
  types/ckeditor__ckeditor5-horizontal-line/v27/src/horizontalline.d.ts
  types/ckeditor__ckeditor5-horizontal-line/v27/src/horizontallinecommand.d.ts
  types/ckeditor__ckeditor5-horizontal-line/v27/src/horizontallineediting.d.ts
  types/ckeditor__ckeditor5-horizontal-line/v27/src/horizontallineui.d.ts
  types/ckeditor__ckeditor5-horizontal-line/v27/tsconfig.json
  types/ckeditor__ckeditor5-horizontal-line/v27/tslint.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#60253 fix webpack-files-archive-plugin fixed webpack dependency version
  types/webpack-files-archive-plugin/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#60301 Add types for traceparent npm package.
  types/traceparent/index.d.ts
  types/traceparent/traceparent-tests.ts
  types/traceparent/tsconfig.json
  types/traceparent/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60317 [chrome] Add missing `'orange'` option to tab color enum
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#60177 Add RtpEndopoint and improve SdpEndpoint
  types/kurento-client/index.d.ts
  types/kurento-client/kurento-client-tests.ts
Labels: Self Merge, Owner Approved

#60326 [postcss-mixins] Add types for postcss-mixins
  types/postcss-mixins/index.d.ts
  types/postcss-mixins/package.json
  types/postcss-mixins/postcss-mixins-tests.ts
  types/postcss-mixins/tsconfig.json
  types/postcss-mixins/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#60322 [google-spreadsheet] Add missing optional argument
  types/google-spreadsheet/google-spreadsheet-tests.ts
  types/google-spreadsheet/index.d.ts
Labels: Other Approved, Self Merge

#60331 Updates and additions to WebXR types, with Layers and Multiview Extension
  types/webxr/index.d.ts
  types/webxr/webxr-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#60286 feat(@types/react-reconciler): update `createContainer`
  types/react-reconciler/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#60332 [discord-rpc] Fix signature for subscribe
  types/discord-rpc/discord-rpc-tests.ts
  types/discord-rpc/index.d.ts
Labels: Self Merge, Owner Approved

#60329 google-map-react - Update interface for Maps
  types/google-map-react/google-map-react-tests.tsx
  types/google-map-react/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#60325 [@types/chrome] Deprecate and add replacements for domains and excludedDomains
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#60291 [triangle-wasm] Add new types for triangle-wasm
  types/triangle-wasm/index.d.ts
  types/triangle-wasm/triangle-wasm-tests.ts
  types/triangle-wasm/tsconfig.json
  types/triangle-wasm/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60146 [deep-assign] 🌇 Deprecated npm package
  types/deep-assign/deep-assign-tests.ts
  types/deep-assign/index.d.ts
  types/deep-assign/tsconfig.json
  types/deep-assign/tslint.json
Labels: Self Merge, Maintainer Approved

#60343 Allow MDX JSX functions to return null
  types/mdx/mdx-tests.tsx
  types/mdx/types.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#60350 [iobroker] fix several type definitions
  types/iobroker/index.d.ts
  types/iobroker/iobroker-tests.ts
  types/iobroker/objects.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#60348 [@mailchimp/mailchimp_marketing] Update return definitions for mailing lists
  types/mailchimp__mailchimp_marketing/index.d.ts
  types/mailchimp__mailchimp_marketing/mailchimp__mailchimp_marketing-tests.ts
Labels: Self Merge, Owner Approved

#60347 Add type definitions for log
  types/log/index.d.ts
  types/log/log-tests.ts
  types/log/tsconfig.json
  types/log/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#60344 add banchatmember typings
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60338 Add style-inject typings
  types/style-inject/index.d.ts
  types/style-inject/style-inject-tests.ts
  types/style-inject/tsconfig.json
  types/style-inject/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60294 New mojang-minecraft modules: -net, -minecraft-ui, -server-admin
  types/mojang-minecraft-server-admin/index.d.ts
  types/mojang-minecraft-server-admin/mojang-minecraft-server-admin-tests.ts
  types/mojang-minecraft-server-admin/tsconfig.json
  types/mojang-minecraft-server-admin/tslint.json
  types/mojang-minecraft-ui/index.d.ts
  types/mojang-minecraft-ui/mojang-minecraft-ui-tests.ts
  types/mojang-minecraft-ui/tsconfig.json
  types/mojang-minecraft-ui/tslint.json
  types/mojang-net/index.d.ts
  types/mojang-net/mojang-net-tests.ts
  types/mojang-net/tsconfig.json
  types/mojang-net/tslint.json
Labels: Other Approved, New Definition, Self Merge, Edits multiple packages, Maintainer Approved, Check Config

#60361 [yup] Remove self from definition authors
  types/yup/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#60330 mithril - Change order in Hyperscript interface
  types/mithril/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#60315 [asn1js] rm typings as they are now provided by upstream library
  notNeededPackages.json
  types/asn1js/asn1js-tests.ts
  types/asn1js/index.d.ts
  types/asn1js/tsconfig.json
  types/asn1js/tslint.json
  types/pkijs/package.json
Labels: Popular package, Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#60366 feat: update @nginstack/engine definitions
  types/nginstack__engine/index.d.ts
  types/nginstack__engine/nginstack__engine-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60367 feat: update @nginstack/iquery definitions
  types/nginstack__iquery/index.d.ts
  types/nginstack__iquery/nginstack__iquery-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60368 feat: update @nginstack/orm definitions
  types/nginstack__orm/index.d.ts
  types/nginstack__orm/nginstack__orm-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60369 feat: update @nginstack/jsunit definitions
  types/nginstack__jsunit/index.d.ts
  types/nginstack__jsunit/nginstack__jsunit-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60370 feat: update @nginstack/datasource definitions
  types/nginstack__datasource/index.d.ts
  types/nginstack__datasource/nginstack__datasource-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60371 feat: update @nginstack/web-framework definitions
  types/nginstack__web-framework/index.d.ts
  types/nginstack__web-framework/lib/simple-layout/SimpleLayout.d.ts
  types/nginstack__web-framework/nginstack__web-framework-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60372 feat: update @nginstack/dev-tools definitions
  types/nginstack__dev-tools/index.d.ts
  types/nginstack__dev-tools/nginstack__dev-tools-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#60373 feat: update @nginstack/devops definitions
  types/nginstack__devops/index.d.ts
  types/nginstack__devops/nginstack__devops-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#59587 [node] Add typings for stream.isReadable and stream.isErrored
  types/node/stream.d.ts
  types/node/test/stream.ts
  types/node/v16/stream.d.ts
  types/node/v16/test/stream.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60093 wellknown: remove null from GeoJSONGeometry to prevent null inside collections
  types/wellknown/index.d.ts
  types/wellknown/wellknown-tests.ts
Labels: Self Merge, Maintainer Approved

#60098 Update chess.js to v0.13: Move constants to top level
  types/chess.js/chess.js-tests.ts
  types/chess.js/index.d.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#60328 Add types for @11ty/eleventy img
  types/11ty__eleventy-img/11ty__eleventy-img-tests.ts
  types/11ty__eleventy-img/generate-html.d.ts
  types/11ty__eleventy-img/index.d.ts
  types/11ty__eleventy-img/tsconfig.json
  types/11ty__eleventy-img/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60058 add-BasicAuthInterceptor-typeDef-camunda-client-js
  types/camunda-external-task-client-js/camunda-external-task-client-js-tests.ts
  types/camunda-external-task-client-js/index.d.ts
Labels: Self Merge, Maintainer Approved

#60039 [react-calendar]: allow null values in dates range
  types/react-calendar/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#60197 [mssql] add ConnectionPool.parseConnectionString() static method definition
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#60147 [node-mailjet] Add options to SMS.Client functions
  types/node-mailjet/index.d.ts
Labels: Other Approved, Self Merge, Owner Approved, Untested Change

#60379 update tabulator-tables add TooltipModule
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#60359 Adding missing types in video.js
  types/video.js/index.d.ts
  types/video.js/test/videojs-alt-distributions-tests.ts
  types/video.js/video.js-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#60346 Add types for ember-useragent
  types/ember-useragent/helpers/user-agent.d.ts
  types/ember-useragent/index.d.ts
  types/ember-useragent/services/user-agent.d.ts
  types/ember-useragent/test/ember-useragent-tests.ts
  types/ember-useragent/tsconfig.json
  types/ember-useragent/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60340 Add types for selfsigned
  types/selfsigned/index.d.ts
  types/selfsigned/selfsigned-tests.ts
  types/selfsigned/tsconfig.json
  types/selfsigned/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60352 Add pym.js type definitions
  types/pym.js/index.d.ts
  types/pym.js/pym.js-tests.ts
  types/pym.js/tsconfig.json
  types/pym.js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#60384 [aws-lambda] fix 4.8 errors
  types/aws-lambda/test/cognito-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#60378 Fix "picture" typo in @11ty/eleventy-img
  types/11ty__eleventy-img/11ty__eleventy-img-tests.ts
  types/11ty__eleventy-img/generate-html.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners
