Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2022-12, with the labels that each got.

#63408 [@types/vector2djs] add new vector2djs package types.
  types/vector2js/index.d.ts
  types/vector2js/tsconfig.json
  types/vector2js/tslint.json
  types/vector2js/vector2js-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#63328 fix(rdf-dataset-ext): deleteMatch should allow null arguments
  types/rdf-dataset-ext/deleteMatch.d.ts
  types/rdf-dataset-ext/rdf-dataset-ext-tests.ts
Labels: Self Merge, Owner Approved

#63450 feat: @types/mparticle-web-sdk - add getEnvironment, update typings to 2.18
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-instance-tests.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#63443 add types for easy-speech package
  types/easy-speech/easy-speech-tests.ts
  types/easy-speech/index.d.ts
  types/easy-speech/tsconfig.json
  types/easy-speech/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63460 [swell-js] Added missing method for ShippingRates
  types/swell-js/index.d.ts
  types/swell-js/swell-js-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63447 @types/google.accounts - add error_callback to CodeClientConfig & TokenClientConfig
  types/google.accounts/google.accounts-tests.ts
  types/google.accounts/index.d.ts
Labels: Self Merge, Owner Approved

#63416 "Center" html tag support for React Typescript
  types/react/index.d.ts
  types/react/test/elementAttributes.tsx
Labels: Owner Approved, Critical package

#63444 [mapbox-gl]: Added the getter and setter for the projection
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63445 Add types for 'sort-by' package
  types/sort-by/index.d.ts
  types/sort-by/sort-by-tests.ts
  types/sort-by/tsconfig.json
  types/sort-by/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#63395 [glidejs__glide] Refactor typings, add components, etc
  types/glidejs__glide/components/anchors.d.ts
  types/glidejs__glide/components/autoplay.d.ts
  types/glidejs__glide/components/breakpoints.d.ts
  types/glidejs__glide/components/build.d.ts
  types/glidejs__glide/components/clones.d.ts
  types/glidejs__glide/components/controls.d.ts
  types/glidejs__glide/components/direction.d.ts
  types/glidejs__glide/components/gaps.d.ts
  types/glidejs__glide/components/html.d.ts
  types/glidejs__glide/components/images.d.ts
  types/glidejs__glide/components/index.d.ts
  types/glidejs__glide/components/keyboard.d.ts
  types/glidejs__glide/components/move.d.ts
  types/glidejs__glide/components/peek.d.ts
  types/glidejs__glide/components/resize.d.ts
  types/glidejs__glide/components/run.d.ts
  types/glidejs__glide/components/sizes.d.ts
  types/glidejs__glide/components/swipe.d.ts
  types/glidejs__glide/components/transition.d.ts
  types/glidejs__glide/components/translate.d.ts
  types/glidejs__glide/core/event/events-bus.d.ts
  types/glidejs__glide/dist/glide.modular.esm.d.ts
  types/glidejs__glide/glidejs__glide-modular-tests.ts
  types/glidejs__glide/glidejs__glide-tests.ts
  types/glidejs__glide/index.d.ts
  types/glidejs__glide/mutator/transformers/index.d.ts
  types/glidejs__glide/tsconfig.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#62226 Fix nightwatch types for programmatic API
  types/nightwatch/index.d.ts
  types/nightwatch/test/testProgrammaticApi.ts
Labels: Self Merge, Owner Approved

#63407 [chrome-remote-interface] add support for `Network.enable()` and its ilk
  types/chrome-remote-interface/chrome-remote-interface-tests.ts
  types/chrome-remote-interface/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63391 [next-pwa]: add type declaration
  types/next-pwa/index.d.ts
  types/next-pwa/next-pwa-tests.ts
  types/next-pwa/package.json
  types/next-pwa/tsconfig.json
  types/next-pwa/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#63344 axios-token-interceptor: Fix return type for operator()
  types/axios-token-interceptor/axios-token-interceptor-tests.ts
  types/axios-token-interceptor/index.d.ts
Labels: Self Merge, Owner Approved

#63244 [mapbox-gl]: extend options for addImage
  types/mapbox-gl/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#63466 Making two Trees API's have optional args
  types/antlr4/test/tree.ts
  types/antlr4/tree/Trees.d.ts
Labels: Self Merge, Owner Approved

#63411 [buffer-crc32] type fixes (partials, strings)
  types/buffer-crc32/buffer-crc32-tests.ts
  types/buffer-crc32/index.d.ts
Labels: Self Merge, Owner Approved

#63477 [buffer-crc32] Improve tests and docs
  types/buffer-crc32/buffer-crc32-tests.ts
  types/buffer-crc32/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#63426 Migrate types for osrm to project-osrm__osrm and update for package 5.27
  types/project-osrm__osrm/index.d.ts
  types/project-osrm__osrm/project-osrm__osrm-tests.ts
  types/project-osrm__osrm/tsconfig.json
  types/project-osrm__osrm/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#63151 chore(jest): loosen expect.any() type restrictions
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#63293 [@types/cors] Add reference to `node`
  types/cors/cors-tests.ts
  types/cors/index.d.ts
Labels: Self Merge, Owner Approved, Critical package

#63486 update fabric-impl.d.ts
  types/fabric/fabric-impl.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#63406 fix: object-hash - NotUndefined should allow arrays
  types/object-hash/index.d.ts
  types/object-hash/object-hash-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63482 [base62-random] Add types
  types/base62-random/base62-random-tests.ts
  types/base62-random/index.d.ts
  types/base62-random/tsconfig.json
  types/base62-random/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63481 [base58-random] Add types
  types/base58-random/base58-random-tests.ts
  types/base58-random/index.d.ts
  types/base58-random/tsconfig.json
  types/base58-random/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63422 [@types/nova-editor] [@types/nova-editor-node] Update min ECMAScript version for Nova
  types/nova-editor-node/index.d.ts
  types/nova-editor-node/tsconfig.json
  types/nova-editor/tsconfig.json
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Untested Change, Check Config

#63250 [@types/requestretry] Add `skipHeaderSanitize` to RequestRetryOptions
  types/requestretry/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#63446 [Jasmine] Fix resolveTo and rejectWith to work for spies that return a promise in a union type
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/jasmine/v3/index.d.ts
  types/jasmine/v3/jasmine-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#63418 @ember/application: remove nonsense deprecation functions
  types/ember/index.d.ts
  types/ember/test/ember-module-tests.ts
  types/ember/test/utils.ts
  types/ember__application/deprecations.d.ts
  types/ember__application/test/deprecations.ts
  types/ember__application/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits multiple packages, Maintainer Approved

#63116 fix(node): support for `symbol` type in `diagnostic_channel`
  types/node/diagnostics_channel.d.ts
  types/node/test/diagnostics_channel.ts
  types/node/ts4.8/diagnostics_channel.d.ts
  types/node/ts4.8/test/diagnostics_channel.ts
  types/node/v16/diagnostics_channel.d.ts
  types/node/v16/test/diagnostics_channel.ts
  types/node/v16/ts4.8/diagnostics_channel.d.ts
  types/node/v16/ts4.8/test/diagnostics_channel.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#63453 prompts: Add missing onRender method to PromptObject
  types/prompts/index.d.ts
  types/prompts/package.json
Labels: Popular package, Self Merge, Owner Approved, Untested Change, Edits Owners

#63349 [draft-js] Fix `DraftEntityType` and `DraftBlockType`
  types/draft-js/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63490 [foldify] Add types
  types/foldify/foldify-tests.ts
  types/foldify/index.d.ts
  types/foldify/tsconfig.json
  types/foldify/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63267 [retry-as-promised] - add Function as valid match type
  types/retry-as-promised/index.d.ts
  types/retry-as-promised/retry-as-promised-tests.ts
Labels: Self Merge, Maintainer Approved

#63385 [oojs] Add better type inference for event functions
  types/oojs/EmitterList.d.ts
  types/oojs/EventEmitter.d.ts
  types/oojs/Registry.d.ts
  types/oojs/oojs-tests.ts
  types/oojs/utils.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#63400 [@types/yargs] add FallbackCompletionFunction types
  types/yargs/index.d.ts
  types/yargs/yargs-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#63360 add stopFollowing method
  types/leaflet.locatecontrol/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#63126 feat(ali-oss): add listV2() function.
  types/ali-oss/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#63150 Update fundamental-react SideNav 0.14.5-rc.3
  types/fundamental-react/fundamental-react-tests.tsx
  types/fundamental-react/lib/SideNavigation/SideNav.d.ts
Labels: Unmerged, Self Merge, Owner Approved

#63249 [@types/svg-sprite] fix type error, add missing parameter and method
  types/svg-sprite/index.d.ts
  types/svg-sprite/svg-sprite-tests.ts
Labels: Self Merge, Owner Approved

#63265 fix: fixed optional fields when updating a subscription
  types/braintree/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#63502 Type Definition Fixes
  types/react-native-razorpay/index.d.ts
  types/react-native-razorpay/react-native-razorpay-tests.tsx
Labels: Self Merge, Owner Approved

#63336 fix: deep-diff: add default export
  types/deep-diff/deep-diff-tests.ts
  types/deep-diff/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#63501 [jest-image-snapshot] add `onlyDiff` option added in version 6.1.0
  types/jest-image-snapshot/index.d.ts
  types/jest-image-snapshot/jest-image-snapshot-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#63509 [unicode-dragon] Add types
  types/unicode-dragon/index.d.ts
  types/unicode-dragon/tsconfig.json
  types/unicode-dragon/tslint.json
  types/unicode-dragon/unicode-dragon-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#63511 [@ember/error] Error is just a re-export of native
  types/ember-data/test/error.ts
  types/ember__error/ember__error-tests.ts
  types/ember__error/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits multiple packages, Maintainer Approved

#63462 Updating ckeditor5-editor-decoupled to include sourceElement
  types/ckeditor__ckeditor5-editor-decoupled/ckeditor__ckeditor5-editor-decoupled-tests.ts
  types/ckeditor__ckeditor5-editor-decoupled/src/decouplededitor.d.ts
Labels: Self Merge, Owner Approved

#63519 [swell-js] Updated Product with missing definition
  types/swell-js/index.d.ts
  types/swell-js/swell-js-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63525 [swell-js] Updated wrong names and added definitions
  types/swell-js/index.d.ts
  types/swell-js/swell-js-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63463 bugfix(feather-icons): partial attrs for replace() and toSvg()
  types/feather-icons/index.d.ts
  types/feather-icons/test/feather-icons-tests.ts
Labels: Self Merge, Owner Approved

#63528 feat(carbon__icons-react): upgrade to 11.12
  types/carbon__icons-react/OTHER_FILES.txt
  types/carbon__icons-react/es/DiamondFillGlyph.d.ts
  types/carbon__icons-react/es/UndefinedGlyph.d.ts
  types/carbon__icons-react/es/index.d.ts
  types/carbon__icons-react/index.d.ts
  types/carbon__icons-react/lib/DiamondFillGlyph.d.ts
  types/carbon__icons-react/lib/UndefinedGlyph.d.ts
  types/carbon__icons-react/lib/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, Check Config, No Other Owners

#63515 [stream-counter] Add type definition
  types/stream-counter/index.d.ts
  types/stream-counter/stream-counter-tests.ts
  types/stream-counter/tsconfig.json
  types/stream-counter/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63485 [react-beautiful-dnd] fix some types
  types/react-beautiful-dnd/index.d.ts
  types/react-beautiful-dnd/react-beautiful-dnd-tests.tsx
  types/react-beautiful-dnd/v12/index.d.ts
  types/react-beautiful-dnd/v12/react-beautiful-dnd-tests.tsx
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Edits Owners

#63389 [react-pdf] Update for version 6
  types/react-pdf/dist/Page.d.ts
  types/react-pdf/dist/esm/entry.vite.d.ts
  types/react-pdf/dist/umd/entry.vite.d.ts
  types/react-pdf/index.d.ts
  types/react-pdf/package.json
  types/react-pdf/react-pdf-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#63540 Update types for VS Code 1.74
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#63545 [@types/node] Add missed scheduler at timers/promises
  types/node/test/timers_promises.ts
  types/node/timers/promises.d.ts
  types/node/ts4.8/test/timers_promises.ts
  types/node/ts4.8/timers/promises.d.ts
  types/node/v16/test/timers_promises.ts
  types/node/v16/timers/promises.d.ts
  types/node/v16/ts4.8/test/timers_promises.ts
  types/node/v16/ts4.8/timers/promises.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#62557 [daterangepicker] Fixed minYear/maxYear properties for DateRangePicker
  types/daterangepicker/daterangepicker-tests.ts
  types/daterangepicker/index.d.ts
Labels: Owner Approved, Maintainer Approved, Where is GH Actions?

#63531 Add cvss types
  types/cvss/cvss-tests.ts
  types/cvss/index.d.ts
  types/cvss/tsconfig.json
  types/cvss/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#63108 Add jscodeshift Runner function type
  types/jscodeshift/src/Runner.d.ts
  types/jscodeshift/test/jscodeshift-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63548 [marked.js] Alone tokenizer and renderer extension
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63552 Fix missing push permissions on codeowners workflow
  .github/workflows/UpdateCodeowners.yml
Labels: Edits Infrastructure

#63542 [plotly.js] Add definition for "contours" field in PlotData type
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#63551 [karma-browserstack-launcher] Fix: credentials are mistakenly required
  types/karma-browserstack-launcher/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#63499 ioredis-mock: mock Redis take different options than `ioredis.Redis`
  types/ioredis-mock/index.d.ts
  types/ioredis-mock/ioredis-mock-tests.ts
  types/ioredis-mock/tslint.json
Labels: Self Merge, Maintainer Approved, Check Config

#63107 fix: stringify-object ESM support
  types/stringify-object/package.json
  types/stringify-object/stringify-object-tests.ts
Labels: Self Merge, Maintainer Approved, Check Config

#63554 [needle] Fix typo in follow_set_cookies
  types/needle/index.d.ts
  types/needle/needle-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63493 update(node): expand changes from #63417
  types/node/crypto.d.ts
  types/node/test/crypto.ts
  types/node/ts4.8/crypto.d.ts
  types/node/ts4.8/test/crypto.ts
  types/node/v16/ts4.8/crypto.d.ts
  types/node/v16/ts4.8/test/crypto.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#63514 [@type/mailgun-js] add Mailgun STO option
  types/mailgun-js/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63559 [chrome] Add injectImmediately property to Script Injection
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#63547 nodemailer-html-to-text - remove deprecated options in test code
  types/nodemailer-html-to-text/nodemailer-html-to-text-tests.ts
Labels: Self Merge, Owner Approved

#63564 [googletag] discard support for lower versions
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
  types/googletag/package.json
  types/googletag/ts4.2/googletag-tests.ts
  types/googletag/ts4.2/index.d.ts
  types/googletag/ts4.2/tsconfig.json
  types/googletag/ts4.2/tslint.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#63570 [chrome-remote-interface] add support for shorthand callback version of events
  types/chrome-remote-interface/chrome-remote-interface-tests.ts
  types/chrome-remote-interface/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63546 [retry-as-promised] add retry-as-promised to not needed packages as of v7.0.3
  notNeededPackages.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#63544 [properties-parser] Add types for properties-parser
  types/properties-parser/index.d.ts
  types/properties-parser/properties-parser-tests.ts
  types/properties-parser/tsconfig.json
  types/properties-parser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63403 [gettext-parser] Fix typing of Po parser export and add typing for `createParseStream`
  types/gettext-parser/gettext-parser-tests.ts
  types/gettext-parser/index.d.ts
Labels: Self Merge, Owner Approved

#63586 Add missing History module typ quill.js typings
  types/quill/index.d.ts
  types/quill/quill-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63578 [log-rotate] add type definition
  types/log-rotate/index.d.ts
  types/log-rotate/log-rotate-tests.ts
  types/log-rotate/tsconfig.json
  types/log-rotate/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63201 [node] http: Update `ClientRequestArgs` and `ServerOptions`
  types/node/http.d.ts
  types/node/index.d.ts
  types/node/test/http.ts
  types/node/ts4.8/http.d.ts
  types/node/ts4.8/test/http.ts
Labels: Self Merge, Maintainer Approved, Critical package, Edits Owners

#63580 [chrome-remote-interface] put `@types\chrome-remote-interface` overloads before `devtools-protocol` overloads
  types/chrome-remote-interface/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#63597 [swell-js] Added missing array from expanded categories
  types/swell-js/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#63584 Types updated for react-native-auth0:2.16.0
  types/react-native-auth0/index.d.ts
  types/react-native-auth0/react-native-auth0-tests.tsx
  types/react-native-auth0/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Owners

#63492 fix(node): add missing `jwk` key option in crypto
  types/node/crypto.d.ts
  types/node/test/crypto.ts
  types/node/ts4.8/crypto.d.ts
  types/node/ts4.8/test/crypto.ts
  types/node/v16/crypto.d.ts
  types/node/v16/test/crypto.ts
  types/node/v16/ts4.8/crypto.d.ts
  types/node/v16/ts4.8/test/crypto.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#63321 fix(get-image-colors): support for missing options object
  types/get-image-colors/get-image-colors-tests.ts
  types/get-image-colors/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#63532 Update "@types/express" dependency "@types/express-serve-static-core": "^4.17.18"
  types/express/package.json
Labels: Self Merge, Maintainer Approved, Critical package

#63583 Add types for ansi-align
  types/ansi-align/ansi-align-tests.ts
  types/ansi-align/index.d.ts
  types/ansi-align/tsconfig.json
  types/ansi-align/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63595 [plotly.js] Missing definitions of "autocontour" and "ncontours"
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#63468 [nightwatchjs] Fix typo: cliRunner -> CliRunner.
  types/nightwatch/index.d.ts
  types/nightwatch/test/testProgrammaticApi.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63598 [@types/xrm] Added Choices types
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Owner Approved

#63616 [chrome-remote-interface] support the Promise version of events
  types/chrome-remote-interface/chrome-remote-interface-tests.ts
  types/chrome-remote-interface/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63621 add missing TextEncoder/ TextDecoder bindings
  types/akamai-edgeworkers/index.d.ts
  types/akamai-edgeworkers/test/encoding.ts
  types/akamai-edgeworkers/tsconfig.json
Labels: Self Merge, Owner Approved

#63614 [@testing-library/jasmine-dom] Added missing types of 1.3.x version
  types/testing-library__jasmine-dom/index.d.ts
  types/testing-library__jasmine-dom/test/testing-library__jasmine-dom-global-tests.ts
Labels: Self Merge, Owner Approved

#63549 [passport-jwt] Issuer accepts array
  types/passport-jwt/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#63632 [@types/indy-sdk] fix indy proof request
  types/indy-sdk/index.d.ts
  types/indy-sdk/indy-sdk-tests.ts
Labels: Self Merge, Owner Approved

#63567 [got] Remove types
  types/download/download-tests.ts
  types/download/package.json
  types/download/tsconfig.json
  types/got-resume/got-resume-tests.ts
  types/got-resume/index.d.ts
  types/got-resume/tsconfig.json
  types/got/got-tests.ts
  types/got/index.d.ts
  types/got/tsconfig.json
  types/got/tslint.json
  types/got/v8/got-tests.ts
  types/got/v8/index.d.ts
  types/got/v8/tsconfig.json
  types/got/v8/tslint.json
  types/kap-plugin/package.json
  types/onionoo/package.json
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved

#63622 [chromecast-caf-receiver]: Include new TS_HE_AAC format in HlsSegmentFormat
  types/chromecast-caf-receiver/cast.framework.messages.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63378 [onflow-flow-js-testing] Fix Jest helpers
  types/onflow__flow-js-testing/onflow__flow-js-testing-tests.ts
  types/onflow__flow-js-testing/src/interaction.d.ts
  types/onflow__flow-js-testing/src/jest-asserts.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#63618 add a deletions field to FiberNote
  types/react-devtools-inline/commons.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63596 [@types/wordpress__components] Add `disabled` prop type to ToggleControl
  types/wordpress__components/toggle-control/index.d.ts
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Self Merge, Owner Approved

#63606 [hawk] Update package to latest version, update tests
  types/hawk/hawk-tests.ts
  types/hawk/index.d.ts
  types/hawk/lib/server.d.ts
  types/hawk/lib/utils.d.ts
Labels: Self Merge, Owner Approved

#63624 feat(chai-subset-in-order): add missing types
  types/chai-subset-in-order/chai-subset-in-order-tests.ts
  types/chai-subset-in-order/index.d.ts
  types/chai-subset-in-order/tsconfig.json
  types/chai-subset-in-order/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63650 Updated wordpress__blocks to 12.0
  types/wordpress__blocks/api/children.d.ts
  types/wordpress__blocks/api/node.d.ts
  types/wordpress__blocks/block-content-provider.d.ts
  types/wordpress__blocks/index.d.ts
  types/wordpress__blocks/package.json
  types/wordpress__blocks/wordpress__blocks-tests.tsx
Labels: Self Merge, Owner Approved

#63053 [node] Add https.RequestOptions checkServerIdentity
  types/node/https.d.ts
  types/node/test/https.ts
  types/node/ts4.8/https.d.ts
  types/node/ts4.8/test/https.ts
  types/node/v14/https.d.ts
  types/node/v14/test/https.ts
  types/node/v14/ts4.8/https.d.ts
  types/node/v14/ts4.8/test/https.ts
  types/node/v16/https.d.ts
  types/node/v16/test/https.ts
  types/node/v16/ts4.8/https.d.ts
  types/node/v16/ts4.8/test/https.ts
Labels: Self Merge, Maintainer Approved, Critical package

#63633 Bump sanitize-html types for v2.8
  types/sanitize-html/index.d.ts
  types/sanitize-html/package.json
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63651 [color-thief-node] Fixed return type of getColor method
  types/color-thief-node/color-thief-node-tests.ts
  types/color-thief-node/index.d.ts
Labels: Self Merge, Owner Approved

#63398 [Nodemailer] Add attachDataUrls to mail options
  types/nodemailer/lib/mailer/index.d.ts
  types/nodemailer/nodemailer-tests.ts
  types/nodemailer/v3/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#63655 [node:test] Update types
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#63656 [node:util] Update types
  types/node/test/util.ts
  types/node/ts4.8/test/util.ts
  types/node/ts4.8/util.d.ts
  types/node/util.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#63386 [jwplayer] - add resize as string option
  types/jwplayer/index.d.ts
  types/jwplayer/jwplayer-tests.ts
  types/jwplayer/tsconfig.json
Labels: Self Merge, Maintainer Approved, Edits Owners

#63518 Add @types/html-entities-decoder
  types/html-entities-decoder/html-entities-decoder-tests.ts
  types/html-entities-decoder/index.d.ts
  types/html-entities-decoder/tsconfig.json
  types/html-entities-decoder/tslint.json
Labels: Unmerged, New Definition, Self Merge, Maintainer Approved

#63648 [swell-js] more definitions added and fixed with 3.18
  types/swell-js/currency.d.ts
  types/swell-js/index.d.ts
  types/swell-js/locale.d.ts
  types/swell-js/settings.d.ts
  types/swell-js/swell-js-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#63663 [glidejs] Fix contructor type
  types/glidejs__glide/components/html.d.ts
  types/glidejs__glide/glidejs__glide-tests.ts
  types/glidejs__glide/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#63603 [js-md5] Add latest version
  types/js-md5/index.d.ts
  types/js-md5/js-md5-tests.ts
Labels: Self Merge, Maintainer Approved

#63427 Update type definitions for @materializecss/materialize 1.2
  types/materializecss__materialize/autocomplete.d.ts
  types/materializecss__materialize/carousel.d.ts
  types/materializecss__materialize/character-counter.d.ts
  types/materializecss__materialize/chips.d.ts
  types/materializecss__materialize/collapsible.d.ts
  types/materializecss__materialize/common.d.ts
  types/materializecss__materialize/datepicker.d.ts
  types/materializecss__materialize/dropdown.d.ts
  types/materializecss__materialize/fab.d.ts
  types/materializecss__materialize/formselect.d.ts
  types/materializecss__materialize/index.d.ts
  types/materializecss__materialize/inputfields.d.ts
  types/materializecss__materialize/materialbox.d.ts
  types/materializecss__materialize/modal.d.ts
  types/materializecss__materialize/parallax.d.ts
  types/materializecss__materialize/pushpin.d.ts
  types/materializecss__materialize/range.d.ts
  types/materializecss__materialize/scrollspy.d.ts
  types/materializecss__materialize/sidenav.d.ts
  types/materializecss__materialize/slider.d.ts
  types/materializecss__materialize/tabs.d.ts
  types/materializecss__materialize/taptarget.d.ts
  types/materializecss__materialize/test/autocomplete.test.ts
  types/materializecss__materialize/test/formselect.test.ts
  types/materializecss__materialize/timepicker.d.ts
  types/materializecss__materialize/toast.d.ts
  types/materializecss__materialize/tooltip.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#63620 [object-hash] Allow objects implementing interfaces
  types/object-hash/index.d.ts
  types/object-hash/object-hash-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63506 [@types/amqplib] Expose connection on channels
  types/amqplib/amqplib-tests.ts
  types/amqplib/callback_api.d.ts
  types/amqplib/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#63649 [url-file-size] add types
  types/url-file-size/index.d.ts
  types/url-file-size/tsconfig.json
  types/url-file-size/tslint.json
  types/url-file-size/url-file-size-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#63587 [@types/oojs] Use intersection instead of conditional types for EventEmitter overloads
  types/oojs/EmitterList.d.ts
  types/oojs/Factory.d.ts
  types/oojs/Registry.d.ts
  types/oojs/oojs-tests.ts
  types/oojs/utils.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#63599 [snowflake-sdk] Fix error data / response fields typing
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63413 Update VerovioOptions.d.ts to add new options for Verovio 3.13
  types/verovio/VerovioOptions.d.ts
  types/verovio/index.d.ts
  types/verovio/verovio-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#63637 Fix rerender function export in @ember/test-helpers package
  types/ember__test-helpers/index.d.ts
  types/ember__test-helpers/rerender.d.ts
  types/ember__test-helpers/setup-rendering-context.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63669 Remove 3 Ember packages which publish their own types
  notNeededPackages.json
  types/ember-qunit/ember-qunit-tests.ts
  types/ember-qunit/index.d.ts
  types/ember-qunit/tsconfig.json
  types/ember-qunit/tslint.json
  types/ember-qunit/v2/ember-qunit-tests.ts
  types/ember-qunit/v2/index.d.ts
  types/ember-qunit/v2/tsconfig.json
  types/ember-qunit/v2/tslint.json
  types/ember-qunit/v4/ember-qunit-tests.ts
  types/ember-qunit/v4/index.d.ts
  types/ember-qunit/v4/tsconfig.json
  types/ember-qunit/v4/tslint.json
  types/ember-resolver/ember-resolver-tests.ts
  types/ember-resolver/index.d.ts
  types/ember-resolver/tsconfig.json
  types/ember-resolver/tslint.json
  types/ember-resolver/v4/ember-resolver-tests.ts
  types/ember-resolver/v4/index.d.ts
  types/ember-resolver/v4/tsconfig.json
  types/ember-resolver/v4/tslint.json
  types/ember__test-helpers/application.d.ts
  types/ember__test-helpers/dom/blur.d.ts
  types/ember__test-helpers/dom/click.d.ts
  types/ember__test-helpers/dom/double-click.d.ts
  types/ember__test-helpers/dom/fill-in.d.ts
  types/ember__test-helpers/dom/find-all.d.ts
  types/ember__test-helpers/dom/find.d.ts
  types/ember__test-helpers/dom/focus.d.ts
  types/ember__test-helpers/dom/get-root-element.d.ts
  types/ember__test-helpers/dom/scroll-to.d.ts
  types/ember__test-helpers/dom/select.d.ts
  types/ember__test-helpers/dom/tap.d.ts
  types/ember__test-helpers/dom/trigger-event.d.ts
  types/ember__test-helpers/dom/trigger-key-event.d.ts
  types/ember__test-helpers/dom/triggerTab.d.ts
  types/ember__test-helpers/dom/type-in.d.ts
  types/ember__test-helpers/dom/wait-for.d.ts
  types/ember__test-helpers/ember__test-helpers-tests.ts
  types/ember__test-helpers/index.d.ts
  types/ember__test-helpers/rerender.d.ts
  types/ember__test-helpers/resolver.d.ts
  types/ember__test-helpers/settled.d.ts
  types/ember__test-helpers/setup-application-context.d.ts
  types/ember__test-helpers/setup-context.d.ts
  types/ember__test-helpers/setup-onerror.d.ts
  types/ember__test-helpers/setup-rendering-context.d.ts
  types/ember__test-helpers/teardown-application-context.d.ts
  types/ember__test-helpers/teardown-context.d.ts
  types/ember__test-helpers/teardown-rendering-context.d.ts
  types/ember__test-helpers/tsconfig.json
  types/ember__test-helpers/tslint.json
  types/ember__test-helpers/v1/ember__test-helpers-tests.ts
  types/ember__test-helpers/v1/index.d.ts
  types/ember__test-helpers/v1/tsconfig.json
  types/ember__test-helpers/v1/tslint.json
  types/ember__test-helpers/validate-error-handler.d.ts
  types/ember__test-helpers/wait-until.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#63659 [protractor-console-plugin] add type definition
  types/protractor-console-plugin/index.d.ts
  types/protractor-console-plugin/package.json
  types/protractor-console-plugin/protractor-console-plugin-tests.ts
  types/protractor-console-plugin/tsconfig.json
  types/protractor-console-plugin/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63589 Ember: backport Owner improvements from Ember's own types
  types/ember__owner/ember__owner-tests.ts
  types/ember__owner/index.d.ts
  types/ember__service/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved

#63665 [@types/k6] Add type annotations for v0.42.0
  types/k6/experimental/redis.d.ts
  types/k6/experimental/websockets.d.ts
  types/k6/index.d.ts
  types/k6/test/websockets.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits Owners

#63456 [prettier] Add 'string' options for plugins
  types/prettier/index.d.ts
  types/prettier/prettier-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#63672 [chrome] Add Definition for Promise Version of Top-Sites Get
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#63680 [@types/chrome] Make extensionId in sendMessage optional
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#63361 fix(angular-aria): 'typeof import' is not assignable to type 'string'
  types/angular-aria/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63557 [react-big-calendar] Luxon localizer options
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#63473 [seedrandom] Add support for constructors
  types/seedrandom/index.d.ts
  types/seedrandom/seedrandom-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#63707 I meant publish, not download
  azure-pipelines.yml
Labels: Edits Infrastructure

#63639 Updated wordpress__media-utils to 4.14
  types/wordpress__media-utils/index.d.ts
  types/wordpress__media-utils/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#63708 Remove self from owners of react-dual-listbox types
  types/react-dual-listbox/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners, Edits Owners

#63690 pg: remove not supposed option from ClientConfig
  types/pg/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#63465 [leaflet-gpx] Add missing properties for marker_options
  types/leaflet-gpx/index.d.ts
  types/leaflet-gpx/leaflet-gpx-tests.ts
Labels: Self Merge, Maintainer Approved

#63560 @types/query-selector-shadow-dom Add overloads for simple selectors
  types/query-selector-shadow-dom/index.d.ts
  types/query-selector-shadow-dom/query-selector-shadow-dom-tests.ts
Labels: Self Merge, Owner Approved

#63421 [knex-cleaner] Update Knex dependency to v2.3.0
  types/knex-cleaner/package.json
Labels: Self Merge, Owner Approved

#63577 [redux-first-router-link] Add children for React 18 compatibility
  types/redux-first-router-link/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#63561 [react-dom] Don't trigger dangling Promise lint rules on void `act` callbacks
  types/react-dom/test-utils/index.d.ts
  types/react-dom/test/react-dom-tests.tsx
Labels: Owner Approved, Critical package

#63710 [jsonwebtoken] Update for version 9.0.0
  types/jsonwebtoken/index.d.ts
  types/jsonwebtoken/jsonwebtoken-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#63699 Export ParseError as a part of katex default export
  types/katex/index.d.ts
  types/katex/katex-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63615 [@types/xrm] updated MS Docs links
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Owner Approved

#63660 [stream-json] Add `checkErrors` field introduced in v1.7.2 of library
  types/stream-json/jsonl/Parser.d.ts
  types/stream-json/stream-json-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#63686 Add types for twitter_cldr package
  types/twitter_cldr/index.d.ts
  types/twitter_cldr/tsconfig.json
  types/twitter_cldr/tslint.json
  types/twitter_cldr/twitter_cldr-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#63731 docs(@types/node): misleading jsdoc value for windowsHide
  types/node/child_process.d.ts
  types/node/ts4.8/child_process.d.ts
  types/node/v14/child_process.d.ts
  types/node/v14/ts4.8/child_process.d.ts
  types/node/v16/child_process.d.ts
  types/node/v16/ts4.8/child_process.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#63521 [happo-cypress] Make types generically compatible with Cypress after v6.4
  types/happo-cypress/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved

#63619 [virtual-scroll] Fix type exports and improve tests
  types/virtual-scroll/index.d.ts
  types/virtual-scroll/virtual-scroll-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#63538 [lambda-tester] make verifier parameter optional
  types/lambda-tester/index.d.ts
  types/lambda-tester/lambda-tester-tests.ts
Labels: Self Merge, Maintainer Approved

#63687 Add types for string-algorithms package
  types/string-algorithms/index.d.ts
  types/string-algorithms/string-algorithms-tests.ts
  types/string-algorithms/tsconfig.json
  types/string-algorithms/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63734 fix(reveal.js): make static Reveal inherit the api
  types/reveal.js/index.d.ts
  types/reveal.js/reveal.js-tests.ts
Labels: Self Merge, Owner Approved
