Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2023-09, with the labels that each got.

#66519 feat: add `random-word` typings
  types/random-word/index.d.ts
  types/random-word/random-word-tests.ts
  types/random-word/tsconfig.json
  types/random-word/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66444 [ari-client] Use string type instead of JS Date type for ISO 8601 formatted date/time responses
  types/ari-client/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66489 Remove "VincentLanglet" occurences
  types/dotenv-flow/index.d.ts
  types/dotenv-flow/v2/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change, Edits Owners

#66561 feat: Add types for any-base
  types/any-base/any-base-tests.ts
  types/any-base/index.d.ts
  types/any-base/tsconfig.json
  types/any-base/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66579 Add missing lint exemptions
  types/auth0-js/v7/index.d.ts
  types/bluebird/v1/index.d.ts
  types/ember__application/v3/.eslintrc.json
  types/ember__array/v3/.eslintrc.json
  types/ember__component/v3/.eslintrc.json
  types/ember__engine/v3/.eslintrc.json
  types/ember__object/v3/.eslintrc.json
  types/ember__routing/v3/.eslintrc.json
  types/ember__runloop/v3/.eslintrc.json
  types/feathersjs__authentication-jwt/index.d.ts
  types/feathersjs__authentication-oauth1/index.d.ts
  types/feathersjs__authentication/index.d.ts
  types/feathersjs__express/index.d.ts
  types/google-cloud__datastore/.eslintrc.json
  types/hapi/v12/index.d.ts
  types/hapi__catbox-redis/index.d.ts
  types/humblebee__styled-components-breakpoint/index.d.ts
  types/isomorphic-git__lightning-fs/index.d.ts
  types/jquery/v2/index.d.ts
  types/keystonejs__email/index.d.ts
  types/keystonejs__session/index.d.ts
  types/mapbox__shelf-pack/index.d.ts
  types/needle/v1/index.d.ts
  types/node-notifier/v5/index.d.ts
  types/openlayers/v3/index.d.ts
  types/parse/v1/index.d.ts
  types/rbush/v2/index.d.ts
  types/riderize__passport-strava-oauth2/index.d.ts
  types/stampit/v2/index.d.ts
  types/wordpress__blocks/index.d.ts
  types/wordpress__editor/index.d.ts
  types/wordpress__notices/index.d.ts
Labels: Edits multiple packages, Critical package, Untested Change, Check Config, Too Many Owners

#66554 Update react custom scroll v5.0.0
  types/react-custom-scroll/index.d.ts
  types/react-custom-scroll/react-custom-scroll-tests.tsx
Labels: Self Merge, Owner Approved

#66584 [tampermonkey] Add the `title` option to `GM_registerMenuCommand`
  types/tampermonkey/index.d.ts
  types/tampermonkey/tampermonkey-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66469 Add short_code definition for mapbox__mapbox-sdk GeocodeFeature
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Self Merge, Owner Approved

#66501 Add @types/svgdom
  types/svgdom/index.d.ts
  types/svgdom/package.json
  types/svgdom/svgdom-tests.ts
  types/svgdom/tsconfig.json
  types/svgdom/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66510 Add empty args method overload for node async_hooks
  types/node/async_hooks.d.ts
  types/node/ts4.8/async_hooks.d.ts
  types/node/v14/async_hooks.d.ts
  types/node/v14/ts4.8/async_hooks.d.ts
  types/node/v16/async_hooks.d.ts
  types/node/v16/ts4.8/async_hooks.d.ts
  types/node/v18/async_hooks.d.ts
  types/node/v18/ts4.8/async_hooks.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#66506 Add types for object.groupby
  types/object.groupby/index.d.ts
  types/object.groupby/object.groupby-tests.ts
  types/object.groupby/tsconfig.json
  types/object.groupby/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#65855 [@types/react-test-renderer] fix type of react children may be any primitive
  types/react-test-renderer/index.d.ts
  types/react-test-renderer/react-test-renderer-tests.ts
  types/react-test-renderer/v15/index.d.ts
  types/react-test-renderer/v15/react-test-renderer-tests.ts
  types/react-test-renderer/v16/index.d.ts
  types/react-test-renderer/v16/react-test-renderer-tests.ts
  types/react-test-renderer/v17/index.d.ts
  types/react-test-renderer/v17/react-test-renderer-tests.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package

#66580 Add types for Twitch's embebbed player API
  types/twitch-browser/index.d.ts
  types/twitch-browser/readme.md
  types/twitch-browser/tsconfig.json
  types/twitch-browser/tslint.json
  types/twitch-browser/twitch-browser-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66588 Update venmo.create method options
  types/braintree-web/test/web.ts
  types/braintree-web/venmo.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66464 [@types/humanparser] Add options argument in parseName
  types/humanparser/humanparser-tests.ts
  types/humanparser/index.d.ts
Labels: Self Merge, Owner Approved

#66591 [pubnub] update appContext types
  types/pubnub/index.d.ts
  types/pubnub/pubnub-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66582 Update Forge-apis to v0.9.6
  types/forge-apis/forge-apis-tests.ts
  types/forge-apis/index.d.ts
Labels: Self Merge, Owner Approved

#66596 [@wordpress/block-editor] MediaPlaceholder: include string as 'multiple' type
  types/wordpress__block-editor/components/media-placeholder.d.ts
  types/wordpress__block-editor/wordpress__block-editor-tests.tsx
Labels: Self Merge, Owner Approved

#66583 [dcp-client] Add support for more import methods
  types/dcp-client/compute.d.ts
  types/dcp-client/dcp.d.ts
  types/dcp-client/index.d.ts
  types/dcp-client/test/dcp-client-global.tests.ts
  types/dcp-client/test/dcp-client-module.tests.ts
  types/dcp-client/tsconfig.json
  types/dcp-client/wallet.d.ts
  types/dcp-client/worker.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66459 [lodash] fix: provide non-undefined signatures for sample
  types/lodash/common/collection.d.ts
  types/lodash/fp.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66598 [google-apps-script] CommonEventObject.formInputs: Allow V8 Syntax
  types/google-apps-script/addons/google-apps-script.addon-event-objects.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#66486 [Tedious] Add multiSubnetFailover connection option
  types/tedious/index.d.ts
  types/tedious/tedious-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66478 Updated JW Player version up to version 8.28
  types/jwplayer/index.d.ts
  types/jwplayer/jwplayer-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#66602 node-red__editor-client: Add onadd and change invoke
  types/node-red__editor-client/index.d.ts
  types/node-red__editor-client/node-red__editor-client-tests.ts
Labels: Self Merge, Owner Approved

#66479 Upate react-lazy-load-image-component types for 1.6
  types/react-lazy-load-image-component/index.d.ts
  types/react-lazy-load-image-component/react-lazy-load-image-component-tests.tsx
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66333 Update types for dynamodb-lock-client
  types/dynamodb-lock-client/dynamodb-lock-client-tests.ts
  types/dynamodb-lock-client/index.d.ts
Labels: Self Merge, Maintainer Approved

#66551 cli-progress: add missing property to `Params`
  types/cli-progress/cli-progress-tests.ts
  types/cli-progress/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#66610 [markdownlint-rule-helpers] fix: LineMetadata line should be string
  types/markdownlint-rule-helpers/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#66570 Add types for easycaptchajs package
  types/easycaptchajs/easycaptchajs-tests.ts
  types/easycaptchajs/index.d.ts
  types/easycaptchajs/tsconfig.json
  types/easycaptchajs/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66632 VS Code 1.82 update
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#66636 oidc-provider: bump to 8.4.0
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#66400 [node-forge] more details about encryption in PKCS#7 EnvelopedData
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66626 Mark node:util#inspect options as optional
  types/node/v14/ts4.8/util.d.ts
  types/node/v14/util.d.ts
  types/node/v16/ts4.8/util.d.ts
  types/node/v16/util.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#66634 [node] Update types to v20.6.0
  types/node/async_hooks.d.ts
  types/node/fs.d.ts
  types/node/http.d.ts
  types/node/index.d.ts
  types/node/inspector.d.ts
  types/node/module.d.ts
  types/node/process.d.ts
  types/node/test/inspector.ts
  types/node/test/module.ts
  types/node/ts4.8/async_hooks.d.ts
  types/node/ts4.8/fs.d.ts
  types/node/ts4.8/http.d.ts
  types/node/ts4.8/inspector.d.ts
  types/node/ts4.8/module.d.ts
  types/node/ts4.8/process.d.ts
  types/node/ts4.8/test/inspector.ts
  types/node/ts4.8/test/module.ts
  types/node/ts4.8/worker_threads.d.ts
  types/node/v16/process.d.ts
  types/node/v16/ts4.8/process.d.ts
  types/node/v18/process.d.ts
  types/node/v18/ts4.8/process.d.ts
  types/node/worker_threads.d.ts
  types/rollup-plugin-add-git-msg/index.d.ts
  types/rollup-plugin-add-git-msg/rollup-plugin-add-git-msg-tests.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#66491 Add @types/broccoli-merge-trees
  types/broccoli-merge-trees/broccoli-merge-trees-tests.ts
  types/broccoli-merge-trees/index.d.ts
  types/broccoli-merge-trees/package.json
  types/broccoli-merge-trees/tsconfig.json
  types/broccoli-merge-trees/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66482 [ffprobe] Fix duration/duration_ts types
  types/ffprobe/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#66639 [mapbox-gl-draw] Fix isOfMetaType type in CommonSelectors
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66631 [mersenne-twister] init_by_array
  types/mersenne-twister/index.d.ts
  types/mersenne-twister/mersenne-twister-tests.ts
Labels: Other Approved, Self Merge, Owner Approved, Edits Owners

#66398 Update index.d.ts
  types/react-window-scroller/index.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Untested Change

#66473 Export Error messages from adm-zip/util
  types/adm-zip/adm-zip-tests.ts
  types/adm-zip/index.d.ts
  types/adm-zip/util.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66649 added context to JSONPatch
  types/jiff/index.d.ts
  types/jiff/jiff-tests.ts
Labels: Self Merge, Owner Approved

#66653 [multer] fix Upload.fields return value and $ExpectType omitted from …
  types/multer/multer-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66397 [nodemailer] add raw to SESTransport.SentMessageInfo
  types/nodemailer/lib/ses-transport/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66445 @types/styled-components add missing clearTag method to ServerStyleSheet class
  types/styled-components/index.d.ts
  types/styled-components/test/index.tsx
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Edits Owners

#66638 cesc/maxmsp maxobj missing stuff
  types/maxmsp/index.d.ts
  types/maxmsp/maxmsp-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66641 Updated ComboBoxPopupStyles to add font
  types/gorilla-engine/components/ComboBox.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66645 Disable improved eslint rules
  types/beyonk__gdpr-cookie-consent-banner/index.d.ts
  types/bluebird/v2/index.d.ts
  types/ember/v2/index.d.ts
  types/ember__application/-private/event-dispatcher.d.ts
  types/ember__application/index.d.ts
  types/ember__array/-private/enumerable.d.ts
  types/ember__array/-private/mutable-enumerable.d.ts
  types/ember__array/-private/native-array.d.ts
  types/ember__array/index.d.ts
  types/ember__array/mutable.d.ts
  types/ember__array/proxy.d.ts
  types/ember__array/types/prototype-extensions.d.ts
  types/ember__component/index.d.ts
  types/ember__engine/index.d.ts
  types/ember__engine/instance.d.ts
  types/ember__object/-private/action-handler.d.ts
  types/ember__object/-private/types.d.ts
  types/ember__object/computed.d.ts
  types/ember__object/core.d.ts
  types/ember__object/evented.d.ts
  types/ember__object/events.d.ts
  types/ember__object/index.d.ts
  types/ember__object/internals.d.ts
  types/ember__object/mixin.d.ts
  types/ember__object/observable.d.ts
  types/ember__object/observers.d.ts
  types/ember__object/promise-proxy-mixin.d.ts
  types/ember__object/proxy.d.ts
  types/ember__routing/route.d.ts
  types/ember__routing/router-service.d.ts
  types/ember__routing/router.d.ts
  types/ember__runloop/index.d.ts
  types/ember__string/v2/index.d.ts
  types/express-useragent/v0/index.d.ts
  types/feathersjs__authentication-client/index.d.ts
  types/feathersjs__authentication-local/index.d.ts
  types/feathersjs__authentication-oauth2/index.d.ts
  types/jquery/v1/index.d.ts
  types/keystonejs__logger/index.d.ts
  types/leaflet/v0/index.d.ts
  types/mapbox__geojson-area/index.d.ts
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__s3urls/index.d.ts
  types/needle/v0/index.d.ts
  types/novnc__novnc/index.d.ts
  types/ronomon__hash-table/index.d.ts
  types/wordpress__components/popover/index.d.ts
  types/wordpress__rich-text/index.d.ts
  types/wordpress__rich-text/store/actions.d.ts
  types/wordpress__rich-text/store/selectors.d.ts
  types/yaireo__tagify/dist/react.tagify.d.ts
Labels: Edits multiple packages, Critical package, Untested Change, Too Many Owners

#66607 Add https://www.npmjs.com/package/animals types
  types/animals/animals-tests.ts
  types/animals/index.d.ts
  types/animals/tsconfig.json
  types/animals/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66483 [diff-match-patch] Fix types to use `export =`
  types/diff-match-patch/diff-match-patch-tests.ts
  types/diff-match-patch/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, No Other Owners, Edits Owners

#66357 [ej.web.all] ran dprint fmt
  types/ej.web.all/ej.web.all-tests.ts
  types/ej.web.all/index.d.ts
Labels: Self Merge, Maintainer Approved, Huge Change

#66648 Add `has-property-descriptors` types
  types/has-property-descriptors/has-property-descriptors-tests.ts
  types/has-property-descriptors/index.d.ts
  types/has-property-descriptors/tsconfig.json
  types/has-property-descriptors/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66644 Add `for-each` types
  types/for-each/for-each-tests.ts
  types/for-each/index.d.ts
  types/for-each/tsconfig.json
  types/for-each/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66664 [serverless] Add functionResponseType toStream
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66647 Add `es-value-fixtures` types
  types/es-value-fixtures/es-value-fixtures-tests.ts
  types/es-value-fixtures/index.d.ts
  types/es-value-fixtures/tsconfig.json
  types/es-value-fixtures/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66410 Fix aws-lambda sns trigger urls
  types/aws-lambda/test/sns-tests.ts
  types/aws-lambda/trigger/sns.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66406 [mssql] parseConnectionString always returns `pool` and `options` props
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#66575 [@types/survicate__react-native-survicate] Updated API
  types/survicate__react-native-survicate/index.d.ts
  types/survicate__react-native-survicate/survicate__react-native-survicate-tests.ts
Labels: Other Approved, Self Merge, Owner Approved, Edits Owners

#66622 :trash: remove(sequelize-cursor-pagination): migrated to TS
  notNeededPackages.json
  types/sequelize-cursor-pagination/index.d.ts
  types/sequelize-cursor-pagination/sequelize-cursor-pagination-tests.ts
  types/sequelize-cursor-pagination/tsconfig.json
  types/sequelize-cursor-pagination/tslint.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#66629 Add getHeaders to all callbacks in akamai-edgeworkers.
  types/akamai-edgeworkers/index.d.ts
  types/akamai-edgeworkers/test/akamai-edgeworkers-global.test.ts
Labels: Self Merge, Owner Approved

#66646 [git-log-parser] Added typings
  types/git-log-parser/git-log-parser-tests.ts
  types/git-log-parser/index.d.ts
  types/git-log-parser/tsconfig.json
  types/git-log-parser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66560 Updating yog-bigpipe for Readable changes
  types/yog-bigpipe/index.d.ts
Labels: Untested Change, Unreviewed

#66569 Updating mongodb and bson dependencies for Mongoose-promise
  types/mongoose-promise/package.json
Labels: Unreviewed

#66680 Remove self as maintainer
  types/twig/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#66682 Refactor raphael to improve compile performance
  types/raphael/index.d.ts
Labels: Owner Approved, Untested Change

#66658 [@types/aws-lambda] Update FirehoseTransformationResultRecord data property to optional
  types/aws-lambda/test/kinesis-tests.ts
  types/aws-lambda/trigger/kinesis-firehose-transformation.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66463 Added toCSV type
  types/react-csv/components/CommonPropTypes.d.ts
  types/react-csv/lib/core.d.ts
  types/react-csv/react-csv-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#66654 add react-recompose types
  types/react-recompose/.eslintrc.json
  types/react-recompose/index.d.ts
  types/react-recompose/react-recompose-tests.tsx
  types/react-recompose/tsconfig.json
  types/react-recompose/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66650 add png-chunk* libs
  types/png-chunk-text/index.d.ts
  types/png-chunk-text/png-chunk-text-tests.ts
  types/png-chunk-text/tsconfig.json
  types/png-chunk-text/tslint.json
  types/png-chunks-encode/index.d.ts
  types/png-chunks-encode/png-chunks-encode-tests.ts
  types/png-chunks-encode/tsconfig.json
  types/png-chunks-encode/tslint.json
  types/png-chunks-extract/index.d.ts
  types/png-chunks-extract/png-chunks-extract-tests.ts
  types/png-chunks-extract/tsconfig.json
  types/png-chunks-extract/tslint.json
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved

#66661 update rdf-transform-triple-to-quad to v2 (ESM)
  types/rdf-transform-triple-to-quad/index.d.ts
  types/rdf-transform-triple-to-quad/package.json
  types/rdf-transform-triple-to-quad/rdf-transform-triple-to-quad-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Check Config, No Other Owners

#66408 [@types/chrome] Add cloudIdentifier to chrome.fileSystemProvider
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Maintainer Approved

#66660 update @rdfjs/express-handler to v2 (ESM)
  types/rdfjs__express-handler/index.d.ts
  types/rdfjs__express-handler/package.json
  types/rdfjs__express-handler/rdfjs__express-handler-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Check Config, No Other Owners

#66481 [opossum] Add rotateBucketController option to CircuitBreaker.Options
  types/opossum/index.d.ts
  types/opossum/opossum-tests.ts
Labels: Unmerged, Popular package, Self Merge, Owner Approved

#66520 fix(types): :label: Adding missing types from autocannon options.
  types/autocannon/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#66380 [@types/intersects] Update to intersects@2.7.2
  types/intersects/OTHER_FILES.txt
  types/intersects/box-box.d.ts
  types/intersects/box-circle.d.ts
  types/intersects/box-circleOutline.d.ts
  types/intersects/box-ellipse.d.ts
  types/intersects/box-line.d.ts
  types/intersects/box-point.d.ts
  types/intersects/box-polygon.d.ts
  types/intersects/box.d.ts
  types/intersects/circle-box.d.ts
  types/intersects/circle-circle.d.ts
  types/intersects/circle-ellipse.d.ts
  types/intersects/circle-line.d.ts
  types/intersects/circle-point.d.ts
  types/intersects/circle-polygon.d.ts
  types/intersects/circle.d.ts
  types/intersects/circleOutline-box.d.ts
  types/intersects/circleOutline-circle.d.ts
  types/intersects/circleOutline-line.d.ts
  types/intersects/circleOutline-point.d.ts
  types/intersects/circleOutline.d.ts
  types/intersects/ellipse-box.d.ts
  types/intersects/ellipse-circle.d.ts
  types/intersects/ellipse-ellipse.d.ts
  types/intersects/ellipse-line.d.ts
  types/intersects/ellipse-point.d.ts
  types/intersects/ellipse-polygon.d.ts
  types/intersects/ellipse.d.ts
  types/intersects/index.d.ts
  types/intersects/intersects-tests.ts
  types/intersects/line-box.d.ts
  types/intersects/line-circle.d.ts
  types/intersects/line-circleOutline.d.ts
  types/intersects/line-ellipse.d.ts
  types/intersects/line-line.d.ts
  types/intersects/line-point.d.ts
  types/intersects/line-polygon.d.ts
  types/intersects/line.d.ts
  types/intersects/lineToLine.d.ts
  types/intersects/lineToPolygon.d.ts
  types/intersects/point-box.d.ts
  types/intersects/point-circle.d.ts
  types/intersects/point-circleOutline.d.ts
  types/intersects/point-ellipse.d.ts
  types/intersects/point-line.d.ts
  types/intersects/point-polygon.d.ts
  types/intersects/point.d.ts
  types/intersects/polygon-box.d.ts
  types/intersects/polygon-circle.d.ts
  types/intersects/polygon-ellipse.d.ts
  types/intersects/polygon-line.d.ts
  types/intersects/polygon-point.d.ts
  types/intersects/polygon-polygon.d.ts
  types/intersects/polygon.d.ts
Labels: Self Merge, Maintainer Approved, Check Config

#66676 Create new `circomlibjs` package
  types/circomlibjs/circomlibjs-tests.ts
  types/circomlibjs/index.d.cts
  types/circomlibjs/index.d.ts
  types/circomlibjs/package.json
  types/circomlibjs/tsconfig.json
  types/circomlibjs/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66625 feat: Add types for route-cache
  types/route-cache/index.d.ts
  types/route-cache/ioRedisStore.d.ts
  types/route-cache/lruStore.d.ts
  types/route-cache/package.json
  types/route-cache/route-cache-tests.ts
  types/route-cache/tsconfig.json
  types/route-cache/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66565 chore: update `node-fetch` to use `form-data` v4.x
  types/node-fetch/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66695 fix(semver): add missing RELEASE_TYPES constant
  types/semver/index.d.ts
  types/semver/semver-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66689 Update vanillajs-datepicker to v1.3
  types/vanillajs-datepicker/DateRangePicker.d.ts
  types/vanillajs-datepicker/Datepicker.d.ts
  types/vanillajs-datepicker/index.d.ts
  types/vanillajs-datepicker/vanillajs-datepicker-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#66699 [navermaps] fix: fix typo 'onJsContentLoaded' => 'onJSContentLoaded'
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Owner Approved

#66657 fix map.getBounds() return params miss | error
  types/mapbox-gl/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#66700 fix : add containsKey method for check-types library
  types/check-types/check-types-tests.ts
  types/check-types/index.d.ts
Labels: Self Merge, Owner Approved

#66606 uuid: Update outdated URLs in comments
  types/uuid/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#66679 in types/bindings add the missing parameter module_root to the bindings call options definition
  types/bindings/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#66461 fix: FieldRoleType enum
  types/loopback/index.d.ts
  types/tableau/index.d.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Untested Change

#66692 [node] Add `highWaterMark` option to `createWriteStream`
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/ts4.8/fs.d.ts
  types/node/ts4.8/fs/promises.d.ts
  types/node/v14/fs.d.ts
  types/node/v14/ts4.8/fs.d.ts
  types/node/v16/fs.d.ts
  types/node/v16/fs/promises.d.ts
  types/node/v16/ts4.8/fs.d.ts
  types/node/v16/ts4.8/fs/promises.d.ts
  types/node/v18/fs.d.ts
  types/node/v18/fs/promises.d.ts
  types/node/v18/ts4.8/fs.d.ts
  types/node/v18/ts4.8/fs/promises.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Untested Change

#66666 pdfkit: Adds types needed for accessibility features
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66707 Update jquery tests for TS 5.3
  types/jquery/jquery-tests.ts
Labels: Owner Approved, Critical package

#66504 fix: represent module correctly
  types/twig/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66718 [webpack-node-externals] added "module" value into "importType" option
  types/webpack-node-externals/index.d.ts
  types/webpack-node-externals/webpack-node-externals-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#66721 Use correct import in cassanknex
  types/cassanknex/index.d.ts
Labels: Untested Change

#66698 (react-scramble) Added "reset" and "restart" declarations to AnimationControls interface
  types/react-scramble/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#66691 cytoscape-cxtmenu set element target type to cytoscape.Singular
  types/cytoscape-cxtmenu/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#66687 fix(diff): fix return type of `applyPatch`
  types/diff/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#66701 Update `circomlibjs` BabyJub interface
  types/circomlibjs/circomlibjs-tests.ts
  types/circomlibjs/index.d.cts
Labels: Self Merge, Owner Approved, Maintainer Approved, Check Config

#66703 Create new `snarkjs` package
  types/snarkjs/index.d.cts
  types/snarkjs/index.d.ts
  types/snarkjs/package.json
  types/snarkjs/snarkjs-tests.ts
  types/snarkjs/tsconfig.json
  types/snarkjs/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved, Check Config

#66711 node-oracledb@6.0.0 Types
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66706 Update directory_v1.d.ts - tie User interface to UserOrganization namespace.
  types/google-apps-script/apis/directory_v1.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#66705 Update calendar_v3.d.ts
  types/google-apps-script/apis/calendar_v3.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#66673 [mapbox-gl-draw] Fixes to createSupplementaryPoints and related functions types
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66722 Add types for the ads-client package
  types/ads-client/ads-client-tests.ts
  types/ads-client/index.d.ts
  types/ads-client/tsconfig.json
  types/ads-client/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66642 [dcp-client] Add exported wallet module symbols
  types/dcp-client/test/dcp-client-global.tests.ts
  types/dcp-client/test/dcp-client-module.tests.ts
  types/dcp-client/wallet.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66723 [react] Add support for BigInt in `key`
  types/prop-types/index.d.ts
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
Labels: Owner Approved, Edits multiple packages, Critical package, Untested Change

#66729 Replace proof `string` types with numeric strings
  types/snarkjs/index.d.cts
Labels: Self Merge, Author is Owner, Owner Approved, Check Config

#66738 Remove @types/date-and-time (now bundles its own types)
  notNeededPackages.json
  types/date-and-time/date-and-time-tests.ts
  types/date-and-time/index.d.ts
  types/date-and-time/tsconfig.json
  types/date-and-time/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66730 Add @types/broccoli-funnel
  types/broccoli-funnel/broccoli-funnel-tests.ts
  types/broccoli-funnel/index.d.ts
  types/broccoli-funnel/package.json
  types/broccoli-funnel/tsconfig.json
  types/broccoli-funnel/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66739 [presto-client] Update Column definition
  types/presto-client/index.d.ts
  types/presto-client/presto-client-tests.ts
  types/presto-client/tsconfig.json
Labels: Self Merge, Owner Approved

#66741 Fixes for point clouds in draco3d
  types/draco3d/draco3d-tests.ts
  types/draco3d/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66568 Add ExpertEncoder API to @types/draco3d and @types/draco3dgltf
  types/draco3d/draco3d-tests.ts
  types/draco3d/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Maintainer Approved

#66728 uniq: add missing function parameters
  types/uniq/index.d.ts
  types/uniq/uniq-tests.ts
Labels: Other Approved, Self Merge

#66507 fix: new-relic-browser fix newrelic.setCustomAttribute arg (#66219)
  types/new-relic-browser/index.d.ts
  types/new-relic-browser/new-relic-browser-tests.ts
Labels: Self Merge, Maintainer Approved

#66623 [workerpool ] add 'maxQueueSize' to WorkerPoolOptions
  types/workerpool/index.d.ts
  types/workerpool/workerpool-tests.ts
Labels: Self Merge, Owner Approved

#66715 :sparkles: @types/alpinejs__mask
  types/alpinejs__mask/alpinejs__mask-tests.ts
  types/alpinejs__mask/index.d.ts
  types/alpinejs__mask/tsconfig.json
  types/alpinejs__mask/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66716 :sparkles: Types @alpinejs/intersect
  types/alpinejs__intersect/alpinejs__intersect-tests.ts
  types/alpinejs__intersect/index.d.ts
  types/alpinejs__intersect/tsconfig.json
  types/alpinejs__intersect/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66394 chai-arrays - add sorted overloads with comareFn
  types/chai-arrays/chai-arrays-tests.ts
  types/chai-arrays/index.d.ts
Labels: Self Merge, Maintainer Approved

#66704 [pem] Update typings to 1.14.8
  types/pem/index.d.ts
  types/pem/pem-tests.ts
Labels: Other Approved, Self Merge, Owner Approved

#66727 [MithrilJS] Added censor and JSX children
  types/mithril-global/index.d.ts
  types/mithril-global/mithril-global-tests.ts
  types/mithril/index.d.ts
  types/mithril/test/test-misc.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved

#66731 Add @types/map-stream
  types/map-stream/index.d.ts
  types/map-stream/map-stream-tests.ts
  types/map-stream/tsconfig.json
  types/map-stream/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66755 add missing function to wordpress__blocks
  types/wordpress__blocks/api/factory.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#66714 ✨ 🏷️ Types @alpinejs/persist
  types/alpinejs/alpinejs-tests.ts
  types/alpinejs/index.d.ts
  types/alpinejs__persist/alpinejs__persist-tests.ts
  types/alpinejs__persist/index.d.ts
  types/alpinejs__persist/tsconfig.json
  types/alpinejs__persist/tslint.json
Labels: New Definition, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved

#66748 Add types for myanmar-phonenumber
  types/myanmar-phonenumber/index.d.ts
  types/myanmar-phonenumber/myanmar-phonenumber-tests.ts
  types/myanmar-phonenumber/tsconfig.json
  types/myanmar-phonenumber/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66393 fix(auth0): made AuthenticationClient members (e.g. oauth) always defined
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
  types/auth0/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved

#66740 fix: add number type to Content in Pdfmake
  types/pdfmake/interfaces.d.ts
  types/pdfmake/test/pdfmake-interfaces-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66765 Numeric strings for public signals
  types/snarkjs/index.d.cts
Labels: Self Merge, Author is Owner, Owner Approved, Check Config

#66766 Azure Data Studio 1.46.0 Extension API
  types/azdata/azdata-tests.ts
  types/azdata/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66761 feat: add type for express-cache-response-directive
  types/express-cache-response-directive/express-cache-response-directive-tests.ts
  types/express-cache-response-directive/index.d.ts
  types/express-cache-response-directive/tsconfig.json
  types/express-cache-response-directive/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66651 dxf - fix for old typo for capital letters in entity type and polyline exports type corrected
  types/dxf/Helper.d.ts
  types/dxf/dxf-tests.ts
  types/dxf/handlers/entity/common.d.ts
  types/dxf/toPolylines.d.ts
Labels: Self Merge, Owner Approved

#66712 Create tar-stream type definitions for v3.1
  types/tar-stream/index.d.ts
  types/tar-stream/tar-stream-tests.ts
  types/tar-stream/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved, Check Config, Edits Owners

#66771 chore(nodegit): remove all free function #66770
  types/nodegit/annotated-commit.d.ts
  types/nodegit/blame.d.ts
  types/nodegit/blob.d.ts
  types/nodegit/buf.d.ts
  types/nodegit/commit.d.ts
  types/nodegit/cred.d.ts
  types/nodegit/hash-sig.d.ts
  types/nodegit/indexer.d.ts
  types/nodegit/nodegit-tests.ts
  types/nodegit/note.d.ts
  types/nodegit/object.d.ts
  types/nodegit/odb-object.d.ts
  types/nodegit/odb.d.ts
  types/nodegit/oid-array.d.ts
  types/nodegit/pack-builder.d.ts
  types/nodegit/path-spec.d.ts
  types/nodegit/ref-db.d.ts
  types/nodegit/ref-log.d.ts
  types/nodegit/remote.d.ts
  types/nodegit/repository.d.ts
  types/nodegit/signature.d.ts
  types/nodegit/status-list.d.ts
  types/nodegit/str-array.d.ts
  types/nodegit/submodule.d.ts
  types/nodegit/tag.d.ts
  types/nodegit/tree-builder.d.ts
  types/nodegit/tree-entry.d.ts
  types/nodegit/tree.d.ts
Labels: Self Merge, Owner Approved

#66774 Add mastercard-oauth1-signer types
  types/mastercard-oauth1-signer/index.d.ts
  types/mastercard-oauth1-signer/mastercard-oauth1-signer-tests.ts
  types/mastercard-oauth1-signer/tsconfig.json
  types/mastercard-oauth1-signer/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66779 add new fields to IdConfiguration data type types/gsi
  types/gsi/gsi-tests.ts
  types/gsi/index.d.ts
Labels: Self Merge, Owner Approved

#66796 Add types for rasa-webchat
  types/rasa-webchat/index.d.ts
  types/rasa-webchat/rasa-webchat-tests.tsx
  types/rasa-webchat/tsconfig.json
  types/rasa-webchat/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66790 [wicg-file-system-access] remove WritableStream augmentation
  types/wicg-file-system-access/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#66795 Additional attributes to classes/interfaces
  types/circomlibjs/circomlibjs-tests.ts
  types/circomlibjs/index.d.cts
Labels: Self Merge, Author is Owner, Owner Approved, Check Config

#66793 add DataSourceSheet type to google-apps-script
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#66785 feat: Add types for compact-timezone-list package
  types/compact-timezone-list/compact-timezone-list-tests.ts
  types/compact-timezone-list/index.d.ts
  types/compact-timezone-list/tsconfig.json
  types/compact-timezone-list/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66555 [d3-dsv] Remove `undefined` from DSVRowString
  types/d3-dsv/d3-dsv-tests.ts
  types/d3-dsv/index.d.ts
  types/d3-dsv/v1/d3-dsv-tests.ts
  types/d3-dsv/v1/index.d.ts
  types/d3-dsv/v2/d3-dsv-tests.ts
  types/d3-dsv/v2/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Maintainer Approved, Critical package

#66800 Add missing array predicate in @types/check-types
  types/check-types/check-types-tests.ts
  types/check-types/index.d.ts
Labels: Self Merge, Owner Approved

#66803 add optional alt-property to LatLngLiteral and LatLngTuple
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66768 feat(node): export `Mock` type from node:test
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66688 Update mixpanel-browser InTrackingOptions regarding docs v2.47.1
  types/mixpanel-browser/index.d.ts
  types/mixpanel-browser/mixpanel-browser-tests.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#66750 [node] Update types to v18.18
  types/node/events.d.ts
  types/node/module.d.ts
  types/node/net.d.ts
  types/node/v18/child_process.d.ts
  types/node/v18/dgram.d.ts
  types/node/v18/events.d.ts
  types/node/v18/fs/promises.d.ts
  types/node/v18/globals.d.ts
  types/node/v18/index.d.ts
  types/node/v18/module.d.ts
  types/node/v18/net.d.ts
  types/node/v18/stream.d.ts
  types/node/v18/test.d.ts
  types/node/v18/test/child_process.ts
  types/node/v18/test/dgram.ts
  types/node/v18/test/events.ts
  types/node/v18/test/http.ts
  types/node/v18/test/net.ts
  types/node/v18/test/stream.ts
  types/node/v18/test/test.ts
  types/node/v18/test/timers.ts
  types/node/v18/test/tls.ts
  types/node/v18/timers.d.ts
  types/node/v18/ts4.8/child_process.d.ts
  types/node/v18/ts4.8/dgram.d.ts
  types/node/v18/ts4.8/events.d.ts
  types/node/v18/ts4.8/fs/promises.d.ts
  types/node/v18/ts4.8/globals.d.ts
  types/node/v18/ts4.8/module.d.ts
  types/node/v18/ts4.8/net.d.ts
  types/node/v18/ts4.8/node-tests.ts
  types/node/v18/ts4.8/stream.d.ts
  types/node/v18/ts4.8/test.d.ts
  types/node/v18/ts4.8/test/child_process.ts
  types/node/v18/ts4.8/test/dgram.ts
  types/node/v18/ts4.8/test/events.ts
  types/node/v18/ts4.8/test/http.ts
  types/node/v18/ts4.8/test/net.ts
  types/node/v18/ts4.8/test/stream.ts
  types/node/v18/ts4.8/test/test.ts
  types/node/v18/ts4.8/test/timers.ts
  types/node/v18/ts4.8/test/tls.ts
  types/node/v18/ts4.8/timers.d.ts
  types/node/v18/ts4.8/url.d.ts
  types/node/v18/url.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#66745 [node] Update types to v20.7.0
  types/node/console.d.ts
  types/node/index.d.ts
  types/node/module.d.ts
  types/node/process.d.ts
  types/node/string_decoder.d.ts
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/console.d.ts
  types/node/ts4.8/module.d.ts
  types/node/ts4.8/process.d.ts
  types/node/ts4.8/string_decoder.d.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#66733 update(swagger-ui): Add idea syntax highlight theme
  types/swagger-ui/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#66822 [navermaps] Fix parameter types for functions (KVO, DOMEventListener)
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66807 [OvenPlayer] updating types, export types so developers can finnaly use them, Mark deleted method as unrequired, new types.
  types/ovenplayer/index.d.ts
  types/ovenplayer/ovenplayer-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#66827 Update types for migrate-mongo 11
  types/migrate-mongo/package.json
Labels: Self Merge, Owner Approved

#66352 [react] ran dprint fmt
  types/react/canary.d.ts
  types/react/experimental.d.ts
  types/react/global.d.ts
  types/react/index.d.ts
  types/react/jsx-dev-runtime.d.ts
  types/react/jsx-runtime.d.ts
  types/react/test/canary.tsx
  types/react/test/cssProperties.tsx
  types/react/test/elementAttributes.tsx
  types/react/test/experimental.tsx
  types/react/test/hooks.tsx
  types/react/test/index.ts
  types/react/test/managedAttributes.tsx
  types/react/test/tsx.tsx
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/global.d.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/jsx-dev-runtime.d.ts
  types/react/ts5.0/jsx-runtime.d.ts
  types/react/ts5.0/test/canary.tsx
  types/react/ts5.0/test/cssProperties.tsx
  types/react/ts5.0/test/elementAttributes.tsx
  types/react/ts5.0/test/experimental.tsx
  types/react/ts5.0/test/hooks.tsx
  types/react/ts5.0/test/index.ts
  types/react/ts5.0/test/managedAttributes.tsx
  types/react/ts5.0/test/tsx.tsx
  types/react/v15/index.d.ts
  types/react/v15/jsx-dev-runtime.d.ts
  types/react/v15/jsx-runtime.d.ts
  types/react/v15/test/cssProperties.tsx
  types/react/v15/test/index.ts
  types/react/v15/test/tsx.tsx
  types/react/v16/global.d.ts
  types/react/v16/index.d.ts
  types/react/v16/jsx-dev-runtime.d.ts
  types/react/v16/jsx-runtime.d.ts
  types/react/v16/test/cssProperties.tsx
  types/react/v16/test/elementAttributes.tsx
  types/react/v16/test/hooks.tsx
  types/react/v16/test/index.ts
  types/react/v16/test/managedAttributes.tsx
  types/react/v16/test/tsx.tsx
  types/react/v17/global.d.ts
  types/react/v17/index.d.ts
  types/react/v17/jsx-dev-runtime.d.ts
  types/react/v17/jsx-runtime.d.ts
  types/react/v17/test/cssProperties.tsx
  types/react/v17/test/elementAttributes.tsx
  types/react/v17/test/hooks.tsx
  types/react/v17/test/index.ts
  types/react/v17/test/managedAttributes.tsx
  types/react/v17/test/tsx.tsx
Labels: Maintainer Approved, Critical package, The CI failed, Huge Change

#66834 Formatted mp4frag with dprint and removed node/buffer import
  .dprint.jsonc
  types/mp4frag/index.d.ts
  types/mp4frag/mp4frag-tests.ts
Labels: Edits Infrastructure

#66836 d3-fetch/request: remove unused non-null assertions
  types/d3-fetch/d3-fetch-tests.ts
  types/d3-fetch/v1/d3-fetch-tests.ts
  types/d3-fetch/v2/d3-fetch-tests.ts
  types/d3-request/d3-request-tests.ts
Labels: Popular package, Edits multiple packages
