Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2023-05, with the labels that each got.

#65332 dadata-api definitions
  types/dadata-api/dadata-api-tests.ts
  types/dadata-api/index.d.ts
  types/dadata-api/tsconfig.json
  types/dadata-api/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#65342 [atlassian-connect-js] Add type definitions for several new methods
  types/atlassian-connect-js/atlassian-connect-js-tests.ts
  types/atlassian-connect-js/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65357 [marked] Add support for hooks option
  types/marked/index.d.ts
  types/marked/marked-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65254 [react-scroll] Add new prop type for Link Component
  types/react-scroll/modules/components/Link.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#65365 Add choropleth to TDF
  types/zingchart/es6/index.d.ts
  types/zingchart/zingchart-tests.ts
Labels: Other Approved, Self Merge

#65247 [newman] Add missing timings property to NewmanRun
  types/newman/index.d.ts
  types/newman/newman-tests.ts
Labels: Other Approved, Self Merge

#65153 [gremlin] Added Merge Enum, updated direction enum, update Translator
  types/gremlin/gremlin-tests.ts
  types/gremlin/index.d.ts
Labels: Self Merge, Owner Approved

#65310 Chrome: Fix typo in chrome.input_ime.InputContext
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#65361 [mailchimp__mailchimp-marketing] lists.batchListMembers method typings add
  types/mailchimp__mailchimp_marketing/index.d.ts
  types/mailchimp__mailchimp_marketing/mailchimp__mailchimp_marketing-tests.ts
Labels: Self Merge, Owner Approved

#65378 [matter-js] Correct Constraint.bodyA .bodyB nullability
  types/matter-js/index.d.ts
  types/matter-js/matter-js-tests.ts
Labels: Self Merge, Owner Approved

#65377 Add missing shaka-player config types for the chromecast-caf-receiver package
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Self Merge, Owner Approved

#65380 frida-gum: Add `address` to HexdumpOptions
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65325 add typings for js-sha1 0.6
  types/js-sha1/index.d.ts
  types/js-sha1/js-sha1-tests.ts
  types/js-sha1/tsconfig.json
  types/js-sha1/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#65381 [mongoose-aggregate-paginate-v2] Do not extend Document as this is not supported anymore in Mongoose v7
  types/mongoose-aggregate-paginate-v2/index.d.ts
  types/mongoose-aggregate-paginate-v2/mongoose-aggregate-paginate-v2-tests.ts
Labels: Self Merge, Owner Approved

#65228 [jsts] Add jsts.operation.linemerge.LineMerger to typings
  types/jsts/index.d.ts
  types/jsts/jsts-tests.ts
Labels: Other Approved, Self Merge

#65379 Updates types of "photoshop" to version 24.5
  types/photoshop/dom/Actions.d.ts
  types/photoshop/dom/Channel.d.ts
  types/photoshop/dom/Constants.d.ts
  types/photoshop/dom/CoreModules.d.ts
  types/photoshop/dom/CountItem.d.ts
  types/photoshop/dom/Document.d.ts
  types/photoshop/dom/Guide.d.ts
  types/photoshop/dom/HistoryState.d.ts
  types/photoshop/dom/ImagingModule.d.ts
  types/photoshop/dom/Layer.d.ts
  types/photoshop/dom/LayerComp.d.ts
  types/photoshop/dom/PathItem.d.ts
  types/photoshop/dom/Photoshop.d.ts
  types/photoshop/dom/TextItem.d.ts
  types/photoshop/dom/collections/ColorSamplers.d.ts
  types/photoshop/dom/collections/CountItems.d.ts
  types/photoshop/dom/collections/Guides.d.ts
  types/photoshop/dom/collections/HistoryStates.d.ts
  types/photoshop/dom/collections/LayerComps.d.ts
  types/photoshop/dom/collections/PathItems.d.ts
  types/photoshop/dom/collections/PathPoints.d.ts
  types/photoshop/dom/collections/SubPathItems.d.ts
  types/photoshop/dom/objects/Colors.d.ts
  types/photoshop/dom/objects/SolidColor.d.ts
  types/photoshop/dom/preferences/PreferencesGeneral.d.ts
  types/photoshop/dom/text/CharacterStyle.d.ts
  types/photoshop/dom/text/ParagraphStyle.d.ts
  types/photoshop/dom/text/WarpStyle.d.ts
  types/photoshop/dom/types/ApplyImageTypes.d.ts
  types/photoshop/dom/types/CalculationsTypes.d.ts
  types/photoshop/dom/types/LayerCompTypes.d.ts
  types/photoshop/dom/types/LayerTypes.d.ts
  types/photoshop/dom/types/TextTypes.d.ts
  types/photoshop/index.d.ts
  types/photoshop/test/photoshop-tests.cjs.ts
  types/photoshop/util/unit.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65338 [react-dom] Add types for `experimental_useFormStatus`
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
Labels: Other Approved, Author is Owner, Critical package

#65362 [react-dom] Add types for `PreinitOptions#nonce`
  types/react-dom/next.d.ts
  types/react-dom/test/next-tests.tsx
Labels: Other Approved, Author is Owner, Critical package

#65396 [react] Backport recent changes to 5.0 fork
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/global.d.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/test/elementAttributes.tsx
  types/react/ts5.0/test/experimental.tsx
  types/react/ts5.0/test/hooks.tsx
Labels: Author is Owner, Critical package

#65398 Update for VS Code 1.78
  types/vscode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#65267 [@json2csv] Add types for `@json2csv` packages
  types/json2csv__formatters/index.d.ts
  types/json2csv__formatters/json2csv__formatters-tests.ts
  types/json2csv__formatters/src/default.d.ts
  types/json2csv__formatters/src/index.d.ts
  types/json2csv__formatters/src/number.d.ts
  types/json2csv__formatters/src/object.d.ts
  types/json2csv__formatters/src/string.d.ts
  types/json2csv__formatters/src/stringExcel.d.ts
  types/json2csv__formatters/src/stringQuoteOnlyIfNecessary.d.ts
  types/json2csv__formatters/src/symbol.d.ts
  types/json2csv__formatters/tsconfig.json
  types/json2csv__formatters/tslint.json
  types/json2csv__node/index.d.ts
  types/json2csv__node/json2csv__node-tests.ts
  types/json2csv__node/src/AsyncParser.d.ts
  types/json2csv__node/src/Transform.d.ts
  types/json2csv__node/src/index.d.ts
  types/json2csv__node/tsconfig.json
  types/json2csv__node/tslint.json
  types/json2csv__plainjs/index.d.ts
  types/json2csv__plainjs/json2csv__plainjs-tests.ts
  types/json2csv__plainjs/package.json
  types/json2csv__plainjs/src/BaseParser.d.ts
  types/json2csv__plainjs/src/Parser.d.ts
  types/json2csv__plainjs/src/StreamParser.d.ts
  types/json2csv__plainjs/src/index.d.ts
  types/json2csv__plainjs/src/utils.d.ts
  types/json2csv__plainjs/tsconfig.json
  types/json2csv__plainjs/tslint.json
  types/json2csv__transforms/index.d.ts
  types/json2csv__transforms/json2csv__transforms-tests.ts
  types/json2csv__transforms/src/flatten.d.ts
  types/json2csv__transforms/src/index.d.ts
  types/json2csv__transforms/src/unwind.d.ts
  types/json2csv__transforms/src/utils.d.ts
  types/json2csv__transforms/tsconfig.json
  types/json2csv__transforms/tslint.json
  types/json2csv__whatwg/index.d.ts
  types/json2csv__whatwg/json2csv__whatwg-tests.ts
  types/json2csv__whatwg/src/AsyncParser.d.ts
  types/json2csv__whatwg/src/TransformStream.d.ts
  types/json2csv__whatwg/src/index.d.ts
  types/json2csv__whatwg/tsconfig.json
  types/json2csv__whatwg/tslint.json
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved, Check Config

#65336 New stubs: react-key-value
  types/react-key-value/index.d.ts
  types/react-key-value/react-key-value-tests.tsx
  types/react-key-value/tsconfig.json
  types/react-key-value/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65355 [smallest-enclosing-circle] Add definitions
  types/smallest-enclosing-circle/index.d.ts
  types/smallest-enclosing-circle/smallest-enclosing-circle-tests.ts
  types/smallest-enclosing-circle/tsconfig.json
  types/smallest-enclosing-circle/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65255 [dockerode] Add ContainerStopOptions, ContainerAttachOptions interfaces and fix t…
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#65358 Add definition for shallow-clone
  types/shallow-clone/index.d.ts
  types/shallow-clone/shallow-clone-tests.ts
  types/shallow-clone/tsconfig.json
  types/shallow-clone/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65295 [intercom-web] Add showSpace to IntercomCommandSignature
  types/intercom-web/index.d.ts
  types/intercom-web/intercom-web-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65216 Added argument to 'change values' in 'semantic-ui-dropdown'
  types/semantic-ui-dropdown/global.d.ts
  types/semantic-ui-dropdown/semantic-ui-dropdown-tests.ts
Labels: Other Approved, Self Merge

#65386 Add url.urlToHttpOptions to Node 14
  types/node/v14/test/url.ts
  types/node/v14/ts4.8/test/url.ts
  types/node/v14/ts4.8/url.d.ts
  types/node/v14/url.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65315 chore: ran eslint-plugin-jsdoc/check-tag-names autofixer on fibjs
  types/fibjs/declare/BufferedStream.d.ts
  types/fibjs/declare/Cipher.d.ts
  types/fibjs/declare/DbConnection.d.ts
  types/fibjs/declare/Digest.d.ts
  types/fibjs/declare/EventEmitter.d.ts
  types/fibjs/declare/EventInfo.d.ts
  types/fibjs/declare/Fiber.d.ts
  types/fibjs/declare/File.d.ts
  types/fibjs/declare/HeapGraphEdge.d.ts
  types/fibjs/declare/HeapGraphNode.d.ts
  types/fibjs/declare/HttpClient.d.ts
  types/fibjs/declare/HttpCookie.d.ts
  types/fibjs/declare/HttpHandler.d.ts
  types/fibjs/declare/HttpMessage.d.ts
  types/fibjs/declare/HttpRequest.d.ts
  types/fibjs/declare/HttpResponse.d.ts
  types/fibjs/declare/HttpServer.d.ts
  types/fibjs/declare/HttpUploadData.d.ts
  types/fibjs/declare/HttpsServer.d.ts
  types/fibjs/declare/Image.d.ts
  types/fibjs/declare/Int64.d.ts
  types/fibjs/declare/LruCache.d.ts
  types/fibjs/declare/Message.d.ts
  types/fibjs/declare/MySQL.d.ts
  types/fibjs/declare/PKey.d.ts
  types/fibjs/declare/SQLite.d.ts
  types/fibjs/declare/SandBox.d.ts
  types/fibjs/declare/Service.d.ts
  types/fibjs/declare/Smtp.d.ts
  types/fibjs/declare/Socket.d.ts
  types/fibjs/declare/SslHandler.d.ts
  types/fibjs/declare/SslServer.d.ts
  types/fibjs/declare/SslSocket.d.ts
  types/fibjs/declare/Stat.d.ts
  types/fibjs/declare/StringDecoder.d.ts
  types/fibjs/declare/SubProcess.d.ts
  types/fibjs/declare/UrlObject.d.ts
  types/fibjs/declare/WebSocket.d.ts
  types/fibjs/declare/WebSocketMessage.d.ts
  types/fibjs/declare/X509Cert.d.ts
  types/fibjs/declare/X509Req.d.ts
  types/fibjs/declare/XmlAttr.d.ts
  types/fibjs/declare/XmlCharacterData.d.ts
  types/fibjs/declare/XmlDocument.d.ts
  types/fibjs/declare/XmlDocumentType.d.ts
  types/fibjs/declare/XmlElement.d.ts
  types/fibjs/declare/XmlNamedNodeMap.d.ts
  types/fibjs/declare/XmlNode.d.ts
  types/fibjs/declare/XmlNodeList.d.ts
  types/fibjs/declare/XmlProcessingInstruction.d.ts
  types/fibjs/declare/ZmqSocket.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change, Huge Change

#65407 [react-dom] Add `this: void` to PipeableStream functions
  types/react-dom/server.d.ts
  types/react-dom/test/react-dom-tests.tsx
Labels: Critical package

#65308 [@types/vinyl-fs] Remove `rimraf` Dependency from `vinyl-fs/v0` Properly
  types/vinyl-fs/v0/package.json
  types/vinyl-fs/v0/vinyl-fs-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#65339 @types/dat.gui: Update generic type constraint to work with TypeScript ^4.9.0
  types/dat.gui/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#64977 [react-html-email] add missing `platforms` field
  types/react-html-email/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65412 Add new tabulator-tables editor selectContents param for number, input and TextArea Editor
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#65408 [node] `http.Agent` extends from `EventEmitter`
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/v14/http.d.ts
  types/node/v14/test/http.ts
  types/node/v16/http.d.ts
  types/node/v16/test/http.ts
  types/node/v18/http.d.ts
  types/node/v18/test/http.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65103 Allow file uploads to be Buffers for @types/node-zendesk
  types/node-zendesk/index.d.ts
  types/node-zendesk/node-zendesk-tests.ts
Labels: Other Approved, Self Merge

#64464 [react] Add JSX namespace to React namespace
  types/react-blessed/index.d.ts
  types/react-blessed/react-blessed-tests.tsx
  types/react/index.d.ts
  types/react/jsx-dev-runtime.d.ts
  types/react/jsx-runtime.d.ts
  types/react/test/tsx.tsx
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/jsx-dev-runtime.d.ts
  types/react/ts5.0/jsx-runtime.d.ts
  types/react/ts5.0/test/tsx.tsx
  types/react/v15/index.d.ts
  types/react/v15/test/tsx.tsx
  types/react/v16/index.d.ts
  types/react/v16/test/tsx.tsx
  types/react/v17/index.d.ts
  types/react/v17/test/tsx.tsx
Labels: Other Approved, Edits multiple packages, Critical package

#65388 Fixed typo in @types/html-to-pdfmake
  types/html-to-pdfmake/html-to-pdfmake-tests.ts
  types/html-to-pdfmake/index.d.ts
Labels: Self Merge, Owner Approved

#65406 [types/validator] Add new supported UUID versions 1 and 2
  types/validator/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#65416 Add adblock-rs
  types/adblock-rs/adblock-rs-tests.ts
  types/adblock-rs/index.d.ts
  types/adblock-rs/tsconfig.json
  types/adblock-rs/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65427 [@types/google-apps-script] add cellImage and cellImageBuilder
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#65418 feat: Add typings for @mertasan/tailwindcss-variables
  types/mertasan__tailwindcss-variables/api.d.ts
  types/mertasan__tailwindcss-variables/colorVariable.d.ts
  types/mertasan__tailwindcss-variables/index.d.ts
  types/mertasan__tailwindcss-variables/mertasan__tailwindcss-variables-tests.ts
  types/mertasan__tailwindcss-variables/package.json
  types/mertasan__tailwindcss-variables/tsconfig.json
  types/mertasan__tailwindcss-variables/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#65369 gorilla-engine 1.1 - minor updates and fixes
  types/gorilla-engine/components/AmpEnv.d.ts
  types/gorilla-engine/components/BarStepEditor.d.ts
  types/gorilla-engine/components/ComboBox.d.ts
  types/gorilla-engine/components/DragContainer.d.ts
  types/gorilla-engine/components/DragTarget.d.ts
  types/gorilla-engine/components/DropZone.d.ts
  types/gorilla-engine/components/Knob.d.ts
  types/gorilla-engine/components/Label.d.ts
  types/gorilla-engine/components/LevelMeter.d.ts
  types/gorilla-engine/components/ListBox.d.ts
  types/gorilla-engine/components/LottieAnimation.d.ts
  types/gorilla-engine/components/MidiKeyboard.d.ts
  types/gorilla-engine/components/Pad.d.ts
  types/gorilla-engine/components/ScrollView.d.ts
  types/gorilla-engine/components/SliceEditor.d.ts
  types/gorilla-engine/components/Slider.d.ts
  types/gorilla-engine/components/StepEditor.d.ts
  types/gorilla-engine/components/TextBox.d.ts
  types/gorilla-engine/components/Toggle.d.ts
  types/gorilla-engine/components/Trigger.d.ts
  types/gorilla-engine/components/Waveform.d.ts
  types/gorilla-engine/index.d.ts
  types/gorilla-engine/interfaces/Background.d.ts
  types/gorilla-engine/interfaces/Bounds.d.ts
  types/gorilla-engine/interfaces/Clickable.d.ts
  types/gorilla-engine/interfaces/Common.d.ts
  types/gorilla-engine/interfaces/Component.d.ts
  types/gorilla-engine/interfaces/Font.d.ts
  types/gorilla-engine/interfaces/KeyboardFocus.d.ts
  types/gorilla-engine/interfaces/Scrollable.d.ts
  types/gorilla-engine/interfaces/Skinnable.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#65420 Update to latest FHIR specification
  types/fhir/index.d.ts
  types/fhir/r2.d.ts
  types/fhir/r3.d.ts
  types/fhir/r4.d.ts
  types/fhir/r4b.d.ts
  types/fhir/r5.d.ts
  types/fhir/test/r2-tests.ts
  types/fhir/test/r3-tests.ts
  types/fhir/test/r4-tests.ts
  types/fhir/test/r4b-tests.ts
  types/fhir/test/r5-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Huge Change

#65359 [@types/vuelidate] Remove orblazer from contributor
  types/vuelidate/index.d.ts
Labels: Popular package, Author is Owner, Untested Change, Edits Owners

#65391 fix(unzipper): updated unzipper types
  types/unzipper/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65157 p5 - add static methods back to Vector class
  types/p5/src/math/p5.Vector.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#65180 update(semver): `identifierBase` option support
  types/semver/functions/inc.d.ts
  types/semver/index.d.ts
  types/semver/semver-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#65382 Adds a Security Policy to the repository
  SECURITY.md
Labels: Edits Infrastructure

#65399 fix(Wavesurfer): allow `CanvasGradient` type
  types/wavesurfer.js/types/params.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65426 [node] fix `ExecFileException` having `code?: undefined`
  types/node/child_process.d.ts
  types/node/test/child_process.ts
  types/node/ts4.8/child_process.d.ts
  types/node/v14/child_process.d.ts
  types/node/v14/test/child_process.ts
  types/node/v14/ts4.8/child_process.d.ts
  types/node/v16/child_process.d.ts
  types/node/v16/test/child_process.ts
  types/node/v16/ts4.8/child_process.d.ts
  types/node/v18/child_process.d.ts
  types/node/v18/test/child_process.ts
  types/node/v18/ts4.8/child_process.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65411 Added types for esbuild-copy-static-files
  types/esbuild-copy-static-files/esbuild-copy-static-files-tests.ts
  types/esbuild-copy-static-files/index.d.ts
  types/esbuild-copy-static-files/tsconfig.json
  types/esbuild-copy-static-files/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65392 Add react-native-channel-plugin
  types/react-native-channel-plugin/index.d.ts
  types/react-native-channel-plugin/react-native-channel-plugin-tests.ts
  types/react-native-channel-plugin/tsconfig.json
  types/react-native-channel-plugin/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65451 Fix stream type in mailparser-mit
  types/mailparser-mit/index.d.ts
  types/mailparser-mit/mailparser-mit-tests.ts
Labels: Self Merge, Owner Approved

#65370 Add find-pkg-dir
  types/find-pkg-dir/find-pkg-dir-tests.ts
  types/find-pkg-dir/index.d.ts
  types/find-pkg-dir/tsconfig.json
  types/find-pkg-dir/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65448 [webxr] Add enabledFeatures attribute
  types/webxr/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#65443 add validate_length to validator isURL IsURLOptions
  types/validator/lib/isURL.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#65429 [tar] fix onwarn arguments
  types/tar/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#65446 add types for `test-exclude`
  types/test-exclude/index.d.ts
  types/test-exclude/test-exclude-tests.ts
  types/test-exclude/tsconfig.json
  types/test-exclude/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65327 Added Mercado Pago's Frontend JS
  types/mercadopago-sdk-js/core.d.ts
  types/mercadopago-sdk-js/index.d.ts
  types/mercadopago-sdk-js/mercadopago-sdk-js-tests.ts
  types/mercadopago-sdk-js/modules/bricks.d.ts
  types/mercadopago-sdk-js/modules/cardform.d.ts
  types/mercadopago-sdk-js/modules/fields.d.ts
  types/mercadopago-sdk-js/shared.d.ts
  types/mercadopago-sdk-js/tsconfig.json
  types/mercadopago-sdk-js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65442 google-spreadsheet: add includeCells parameter in GoogleSpreadsheet.loadInfo function
  types/google-spreadsheet/google-spreadsheet-tests.ts
  types/google-spreadsheet/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#65423 [types/snapsvg] Fix Paper.g
  types/snapsvg/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65405 Add possible events that are emitted by steam-user and globaloffensive packages
  types/globaloffensive/globaloffensive-tests.ts
  types/globaloffensive/index.d.ts
  types/steam-user/index.d.ts
  types/steam-user/steam-user-tests.ts
Labels: Edits multiple packages

#65469 [@types/glob-stream] Update Declarations According to `glob-stream` v8
  types/glob-stream/glob-stream-tests.ts
  types/glob-stream/index.d.ts
  types/glob-stream/package.json
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#64354 Draft: [@mapbox/mapbox-gl-draw] Added new types for new exposed methods and constants
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#65453 Add typings for @tonic-ui/react 1.10
  types/tonic-ui__react/index.d.ts
  types/tonic-ui__react/tonic-ui__react-tests.tsx
  types/tonic-ui__react/tsconfig.json
  types/tonic-ui__react/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65462 [node] Improve documentation, add missed types
  types/node/assert.d.ts
  types/node/async_hooks.d.ts
  types/node/crypto.d.ts
  types/node/dns.d.ts
  types/node/dns/promises.d.ts
  types/node/events.d.ts
  types/node/fs.d.ts
  types/node/readline.d.ts
  types/node/readline/promises.d.ts
  types/node/repl.d.ts
  types/node/scripts/generate-docs/ast-processing.ts
  types/node/scripts/generate-docs/node-doc-processing.ts
  types/node/timers.d.ts
  types/node/ts4.8/assert.d.ts
  types/node/ts4.8/async_hooks.d.ts
  types/node/ts4.8/crypto.d.ts
  types/node/ts4.8/dns.d.ts
  types/node/ts4.8/dns/promises.d.ts
  types/node/ts4.8/events.d.ts
  types/node/ts4.8/fs.d.ts
  types/node/ts4.8/readline.d.ts
  types/node/ts4.8/readline/promises.d.ts
  types/node/ts4.8/repl.d.ts
  types/node/ts4.8/timers.d.ts
  types/node/v16/dns.d.ts
  types/node/v16/dns/promises.d.ts
  types/node/v18/dns.d.ts
  types/node/v18/ts4.8/dns.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#65440 add greenlock-express types
  types/greenlock-express/greenlock-express-tests.ts
  types/greenlock-express/index.d.ts
  types/greenlock-express/tsconfig.json
  types/greenlock-express/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65476 React google recaptcha enterprise
  types/react-google-recaptcha-enterprise/index.d.ts
  types/react-google-recaptcha-enterprise/react-google-recaptcha-enterprise-tests.tsx
  types/react-google-recaptcha-enterprise/tsconfig.json
  types/react-google-recaptcha-enterprise/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65473 [@types/google-apps-script] add `Slide.isSkipped`
  types/google-apps-script/google-apps-script.slides.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65474 Create a release version 2.31.0 of the package microsoft-graph
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65475 [openseadragon] Add flipped option for addTiledImage
  types/openseadragon/index.d.ts
  types/openseadragon/openseadragon-tests.ts
Labels: Self Merge, Maintainer Approved

#64964 Adding the text-metrics library
  types/text-metrics/index.d.ts
  types/text-metrics/text-metrics-tests.ts
  types/text-metrics/tsconfig.json
  types/text-metrics/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65436 fix: fix the return type of delete function in @types/ali-oss
  types/ali-oss/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#65238 [@types/express-serve-static-core] Add link and unlink method for Express Router
  types/express-serve-static-core/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#65140 ioredis-mock: Add cluster typing to ioredis-mock
  types/ioredis-mock/index.d.ts
  types/ioredis-mock/ioredis-mock-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#65484 feat(node): add jsdoc for stdio options
  types/node/child_process.d.ts
  types/node/ts4.8/child_process.d.ts
  types/node/v14/child_process.d.ts
  types/node/v14/ts4.8/child_process.d.ts
  types/node/v16/child_process.d.ts
  types/node/v16/ts4.8/child_process.d.ts
  types/node/v18/child_process.d.ts
  types/node/v18/ts4.8/child_process.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#64947 [sinon] extend replacement type in replace function
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Unmerged, Self Merge, Owner Approved, Maintainer Approved, Critical package

#65316 chrome: add {MessageSendOptions, ConnectInfo}.documentId implemented in Chromium 106
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#65472 [@types/mvdan-sh] Fix Mismatching Type Declaration of `mvdan-sh`
  types/mvdan-sh/index.d.ts
  types/mvdan-sh/mvdan-sh-tests.ts
Labels: Self Merge, Owner Approved

#65497 [braintree] Fix typo in `additionalProcessorResponse`
  types/braintree/braintree-tests.ts
  types/braintree/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#65492 Add simpleheat typing
  types/simpleheat/index.d.ts
  types/simpleheat/simpleheat-tests.ts
  types/simpleheat/tsconfig.json
  types/simpleheat/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65273 [react-simple-oauth2-login] Change `children` type to `ReactNode`
  types/react-simple-oauth2-login/index.d.ts
  types/react-simple-oauth2-login/react-simple-oauth2-login-tests.tsx
Labels: Self Merge, Maintainer Approved

#65496 Added definitions for "git-init" (supersedes #65055).
  types/git-init/git-init-tests.ts
  types/git-init/index.d.ts
  types/git-init/tsconfig.json
  types/git-init/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65390 Adds Cookiebot to the Window interface (cookiebot-sdk)
  types/cookiebot-sdk/cookiebot-sdk-tests.ts
  types/cookiebot-sdk/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Edits Owners

#65437 Add options parameter for clearSession in react-native-auth0
  types/react-native-auth0/index.d.ts
  types/react-native-auth0/react-native-auth0-tests.tsx
Labels: Self Merge, Author is Owner, Owner Approved

#65504 Update types of getAnimation/setAnimation are properties of the Marker
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Owner Approved

#65464 chore: update types to reflect state of package
  types/blueimp-load-image/blueimp-load-image-tests.ts
  types/blueimp-load-image/index.d.ts
Labels: Self Merge, Owner Approved

#65410 [mongoose-aggregate-paginate-v2] Add 'useFacet' to PaginateOptions
  types/mongoose-aggregate-paginate-v2/index.d.ts
  types/mongoose-aggregate-paginate-v2/mongoose-aggregate-paginate-v2-tests.ts
Labels: Self Merge, Owner Approved

#65511 fix(node): align behavior of it and test
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/v18/test.d.ts
  types/node/v18/test/test.ts
  types/node/v18/ts4.8/test.d.ts
  types/node/v18/ts4.8/test/test.ts
Labels: Self Merge, Maintainer Approved, Critical package

#65506 [node] Create `@legacy` tag instead of `@deprecated` for legacy API
  types/node/buffer.d.ts
  types/node/scripts/generate-docs/ast-processing.ts
  types/node/ts4.8/buffer.d.ts
  types/node/ts4.8/url.d.ts
  types/node/ts4.8/util.d.ts
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/v16/buffer.d.ts
  types/node/v16/ts4.8/buffer.d.ts
  types/node/v16/ts4.8/url.d.ts
  types/node/v16/ts4.8/util.d.ts
  types/node/v16/url.d.ts
  types/node/v16/util.d.ts
  types/node/v18/buffer.d.ts
  types/node/v18/ts4.8/buffer.d.ts
  types/node/v18/ts4.8/url.d.ts
  types/node/v18/ts4.8/util.d.ts
  types/node/v18/url.d.ts
  types/node/v18/util.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#65344 [@wordpress/editor] fix type function uploadMedia()
  types/wordpress__editor/utils/index.d.ts
  types/wordpress__editor/wordpress__editor-tests.tsx
Labels: Other Approved, Self Merge

#65520 Release version 2.32.0 of microsoft-graph
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65312 [@types/imap] add highestmodseq on Box
  types/imap/imap-tests.ts
  types/imap/index.d.ts
Labels: Self Merge, Maintainer Approved

#65525 Add union ordering fix for luxon in 5.2
  types/luxon/test/luxon-tests.module.ts
Labels: Critical package, The CI failed

#65335 update(find-unused-sass-variables): 4.1 update
  types/find-unused-sass-variables/find-unused-sass-variables-tests.ts
  types/find-unused-sass-variables/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#65470 Setting the initialZoom to null | number
  types/react-d3-graph/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65518 node: Add tests and types for new Node test runner todo shorthands (skip and todo)
  types/node/index.d.ts
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65526 Added types/jqueryui TooltipUIParams.tooltip
  types/jqueryui/index.d.ts
  types/jqueryui/jqueryui-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65521 feat(node): extend test API shorthands
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
  types/node/v18/test.d.ts
  types/node/v18/test/test.ts
  types/node/v18/ts4.8/test.d.ts
  types/node/v18/ts4.8/test/test.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65487 Add newrelic obfuscateSql, setErrorGroupCallback & update noticeError
  types/newrelic/index.d.ts
  types/newrelic/newrelic-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65516 Add types for epub-gen
  types/epub-gen/epub-gen-tests.ts
  types/epub-gen/index.d.ts
  types/epub-gen/tsconfig.json
  types/epub-gen/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65540 Add validate prop to react-tagsinput
  types/react-tagsinput/index.d.ts
  types/react-tagsinput/react-tagsinput-tests.tsx
Labels: Self Merge, Owner Approved, Edits Owners

#65554 Update tape definitions to 5.6
  types/tape/index.d.ts
  types/tape/tape-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65528 [scriptable-ios] fix props of Reminder, definition of RecurrenceRule and add private constructors where needed
  types/scriptable-ios/index.d.ts
  types/scriptable-ios/scriptable-ios-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#65549 update(update-notifier): TS minimum version bump
  types/update-notifier/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#65548 @types/node - NodeJS.BufferEncoding
  types/node/buffer.d.ts
  types/node/test/buffer.ts
  types/node/ts4.8/buffer.d.ts
  types/node/v16/buffer.d.ts
  types/node/v16/ts4.8/buffer.d.ts
  types/node/v18/buffer.d.ts
  types/node/v18/ts4.8/buffer.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65545 `update-notifier`:add `UpdateNotifier` as export
  types/update-notifier/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#64587 feat(node): add Duplex.toWeb and Duplex.fromWeb
  types/node/stream.d.ts
  types/node/test/stream.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65531 Add gulp-concat-css package definition
  types/gulp-concat-css/gulp-concat-css-tests.ts
  types/gulp-concat-css/index.d.ts
  types/gulp-concat-css/tsconfig.json
  types/gulp-concat-css/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65550 Exported `TradeOffer` class in `steam-tradeoffer-manager`
  types/steam-tradeoffer-manager/index.d.ts
  types/steam-tradeoffer-manager/lib/classes/TradeOffer.d.ts
  types/steam-tradeoffer-manager/steam-tradeoffer-manager-tests.ts
Labels: Self Merge, Owner Approved

#65482 Add types for Web App Launch Handling
  types/wicg-web-app-launch/index.d.ts
  types/wicg-web-app-launch/tsconfig.json
  types/wicg-web-app-launch/tslint.json
  types/wicg-web-app-launch/wicg-web-app-launch-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#65415 [pg] Update pg package types to v8.10
  types/pg/index.d.ts
  types/pg/lib/type-overrides.d.ts
  types/pg/package.json
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#65479 [minio]: add myself to maintainer
  types/minio/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change, Edits Owners

#65565 Require TS 5.1 for next-pwa
  types/next-pwa/index.d.ts
Labels: Owner Approved, Untested Change

#65413 [debug] add type for inspectOpts
  types/debug/debug-tests.ts
  types/debug/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#65552 Dedupe dtslint
  package.json
Labels: Edits Infrastructure

#65485 [react-native] Add experimental types
  types/react-native/test/experimental.tsx
  types/react-native/tsconfig.json
  types/react-native/types/experimental.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#65527 Add stream factory method type in `pg`
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#65522 feat(eslint): add new context properties, deprecate some methods
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#65374 [@yarnpkg/lockfile] Narrower parse return type
  types/yarnpkg__lockfile/index.d.ts
  types/yarnpkg__lockfile/tsconfig.json
  types/yarnpkg__lockfile/yarnpkg__lockfile-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Check Config

#65345 types for rdf-store-fs
  types/rdf-store-fs/FlatMultiFileStore.d.ts
  types/rdf-store-fs/MultiFileStore.d.ts
  types/rdf-store-fs/index.d.ts
  types/rdf-store-fs/lib/FlatFilenameResolver.d.ts
  types/rdf-store-fs/lib/MultiFileDatasetStore.d.ts
  types/rdf-store-fs/package.json
  types/rdf-store-fs/rdf-store-fs-tests.ts
  types/rdf-store-fs/tsconfig.json
  types/rdf-store-fs/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65270 [dockerode] Add missing types for docker.run
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved

#65544 Fix @testing-library/jest-dom types
  types/testing-library__jest-dom/matchers.d.ts
  types/testing-library__jest-dom/test/testing-library__jest-dom-extend-matchers-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#65573 Release microsoft-graph-types version 2.33
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65498 [react-relay] Fix type mismatch in `PreloadedEntryPoint['entryPoints']`
  types/react-relay/relay-hooks/EntryPointTypes.d.ts
  types/react-relay/test/relay-hooks-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#65583 [chrome-remote-interface] support opt `sessionId` param of commands
  types/chrome-remote-interface/chrome-remote-interface-tests.ts
  types/chrome-remote-interface/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#65566 [react] Add support for legacy context in JSXElementConstructor
  types/react/index.d.ts
  types/react/test/index.ts
  types/react/test/tsx.tsx
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/test/index.ts
  types/react/ts5.0/test/tsx.tsx
Labels: Author is Owner, Critical package

#65562 Added types for crypto-ld
  types/crypto-ld/crypto-ld-tests.ts
  types/crypto-ld/index.d.ts
  types/crypto-ld/tsconfig.json
  types/crypto-ld/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#65586 Azure Data Studio 1.44.0 Extension API
  types/azdata/azdata-tests.ts
  types/azdata/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65568 Fix some typos in README.it.md
  README.it.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#65547 Update superagent ResponseError with optional timeout property
  types/superagent/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#65555 [draft-js] added DraftDecoratorComponentProps to support typed React components
  types/draft-js/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65419 [oauth2orize] add more functions with different arities
  types/oauth2orize/index.d.ts
  types/oauth2orize/oauth2orize-tests.ts
Labels: Self Merge, Maintainer Approved

#65561 [@type/react-syntax-highlighter] add missing stackoverflow-dark and stackoverflow-light styles in styles/hljs
  types/react-syntax-highlighter/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#65309 Fix JSONSchema7 contains to allow boolean JSON Schema
  types/conventional-changelog-config-spec/conventional-changelog-config-spec-tests.ts
  types/json-schema/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#65603 [ramda] Bump types-ramda package to latest
  types/ramda/package.json
  types/ramda/test/all-tests.ts
  types/ramda/test/filter-tests.ts
  types/ramda/test/gt-tests.ts
  types/ramda/test/gte-tests.ts
  types/ramda/test/has-tests.ts
  types/ramda/test/lt-tests.ts
  types/ramda/test/lte-tests.ts
  types/ramda/test/map-tests.ts
  types/ramda/test/pathEq-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#65599 [presto-client] Improved PrestoError type
  types/presto-client/index.d.ts
  types/presto-client/presto-client-tests.ts
Labels: Self Merge, Owner Approved

#65505 fix: add missing null on file watch event filename
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/ts4.8/fs.d.ts
  types/node/ts4.8/fs/promises.d.ts
  types/node/v16/fs.d.ts
  types/node/v16/fs/promises.d.ts
  types/node/v16/ts4.8/fs.d.ts
  types/node/v16/ts4.8/fs/promises.d.ts
  types/node/v18/fs.d.ts
  types/node/v18/fs/promises.d.ts
  types/node/v18/ts4.8/fs.d.ts
  types/node/v18/ts4.8/fs/promises.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#65616 Fix identifier typo in nova-editor-node
  types/nova-editor-node/index.d.ts
  types/nova-editor-node/nova-editor-node-tests.ts
Labels: Self Merge, Owner Approved

#65510 [detect-port] Port is optional and will be random by default
  types/detect-port/detect-port-tests.ts
  types/detect-port/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#65601 add @types/zwlog-browser
  types/zwlog-browser/index.d.ts
  types/zwlog-browser/tsconfig.json
  types/zwlog-browser/tslint.json
  types/zwlog-browser/zwlog-browser-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#65595 Add types for react-native-listener
  types/react-native-listener/index.d.ts
  types/react-native-listener/react-native-listener-tests.tsx
  types/react-native-listener/tsconfig.json
  types/react-native-listener/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65557 feat(rollup-plugin-natives): add type definitions
  types/rollup-plugin-natives/index.d.ts
  types/rollup-plugin-natives/package.json
  types/rollup-plugin-natives/rollup-plugin-natives-tests.ts
  types/rollup-plugin-natives/tsconfig.json
  types/rollup-plugin-natives/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65507 [convict] Rename InternalSchema `properties` to `_cvtProperties` (broken since v6.0.0)
  types/convict/convict-tests.ts
  types/convict/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#65556 Add types for img-clipboard
  types/img-clipboard/img-clipboard-tests.ts
  types/img-clipboard/index.d.ts
  types/img-clipboard/tsconfig.json
  types/img-clipboard/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65608 @types/word-extractor: fix class function name
  types/word-extractor/index.d.ts
  types/word-extractor/word-extractor-tests.ts
Labels: Self Merge, Owner Approved

#65630 Update two types for nova-editor-node
  types/nova-editor-node/index.d.ts
  types/nova-editor-node/nova-editor-node-tests.ts
Labels: Self Merge, Owner Approved

#65481 [@types/k6] Add experimental browser module type annotations for v0.44.0
  types/k6/experimental/browser/element_handle.d.ts
  types/k6/experimental/browser/frame.d.ts
  types/k6/experimental/browser/index.d.ts
  types/k6/experimental/browser/js_handle.d.ts
  types/k6/experimental/browser/keyboard.d.ts
  types/k6/experimental/browser/locator.d.ts
  types/k6/experimental/browser/mouse.d.ts
  types/k6/experimental/browser/page.d.ts
  types/k6/experimental/browser/request.d.ts
  types/k6/experimental/browser/response.d.ts
  types/k6/experimental/browser/touchscreen.d.ts
  types/k6/experimental/browser/worker.d.ts
  types/k6/test/browser.ts
Labels: Popular package, Self Merge, Owner Approved

#65536 Update type to support json-diff 1.x
  types/json-diff/index.d.ts
  types/json-diff/json-diff-tests.ts
Labels: Popular package, Self Merge, Owner Approved
