Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2023-10, with the labels that each got.

#66802 Update quill-delta version to 5.1.0
  types/quill/index.d.ts
  types/quill/package.json
  types/quill/quill-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66735 [react] `element.key` is a string
  types/prop-types/index.d.ts
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
  types/react/v16/index.d.ts
  types/react/v17/index.d.ts
Labels: Author is Owner, Edits multiple packages, Critical package, Untested Change, Unreviewed

#66860 Add support for supportedCardBrands to HostedFieldsField in braintree-web hosted-fields.d.ts
  types/braintree-web/hosted-fields.d.ts
  types/braintree-web/paypal-checkout.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Self Merge, Owner Approved

#66778 Add new fields for IdConfiguration types/google.accounts
  types/google.accounts/google.accounts-tests.ts
  types/google.accounts/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66879 Remove nick-thompson__elementary, no owners and deprecated upstream
  types/nick-thompson__elementary/.eslintrc.json
  types/nick-thompson__elementary/index.d.ts
  types/nick-thompson__elementary/nick-thompson__elementary-tests.ts
  types/nick-thompson__elementary/src/api.d.ts
  types/nick-thompson__elementary/src/basics.d.ts
  types/nick-thompson__elementary/src/core/api.d.ts
  types/nick-thompson__elementary/src/core/children.d.ts
  types/nick-thompson__elementary/src/core/core.d.ts
  types/nick-thompson__elementary/src/core/index.d.ts
  types/nick-thompson__elementary/src/core/midi.d.ts
  types/nick-thompson__elementary/src/core/node.d.ts
  types/nick-thompson__elementary/src/core/props.d.ts
  types/nick-thompson__elementary/src/core/types.d.ts
  types/nick-thompson__elementary/src/delays.d.ts
  types/nick-thompson__elementary/src/elementary.d.ts
  types/nick-thompson__elementary/src/factories.d.ts
  types/nick-thompson__elementary/src/filters.d.ts
  types/nick-thompson__elementary/src/in.d.ts
  types/nick-thompson__elementary/src/index.d.ts
  types/nick-thompson__elementary/src/math.d.ts
  types/nick-thompson__elementary/src/native.d.ts
  types/nick-thompson__elementary/src/noise.d.ts
  types/nick-thompson__elementary/src/oscillators.d.ts
  types/nick-thompson__elementary/src/samples.d.ts
  types/nick-thompson__elementary/src/signals.d.ts
  types/nick-thompson__elementary/tests/index.ts
  types/nick-thompson__elementary/tests/load.ts
  types/nick-thompson__elementary/tests/suites/basics.ts
  types/nick-thompson__elementary/tests/suites/core.ts
  types/nick-thompson__elementary/tests/suites/delays.ts
  types/nick-thompson__elementary/tests/suites/factories.ts
  types/nick-thompson__elementary/tests/suites/filters.ts
  types/nick-thompson__elementary/tests/suites/math.ts
  types/nick-thompson__elementary/tests/suites/native.ts
  types/nick-thompson__elementary/tests/suites/noise.ts
  types/nick-thompson__elementary/tests/suites/oscillators.ts
  types/nick-thompson__elementary/tests/suites/samples.ts
  types/nick-thompson__elementary/tests/suites/signals.ts
  types/nick-thompson__elementary/tests/tester.ts
  types/nick-thompson__elementary/tsconfig.json
  types/nick-thompson__elementary/tslint.json
Labels: Self Merge, Maintainer Approved, Check Config

#66878 Remove matrix-js-sdk, which has had types for ages
  notNeededPackages.json
  types/matrix-js-sdk/index.d.ts
  types/matrix-js-sdk/matrix-js-sdk-tests.ts
  types/matrix-js-sdk/tsconfig.json
  types/matrix-js-sdk/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66881 Fix node-geocoder depending on the wrong version of node-fetch
  types/node-geocoder/package.json
Labels: Self Merge, Maintainer Approved

#66900 [Xrm] Add getWebResourceUrl to GlobalContext
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Owner Approved

#66825 [geodesy] indicate that geodesyv2 is an esmodule
  types/geodesy/package.json
Labels: Self Merge, Maintainer Approved, Check Config

#66814 feat(node): add async event emitter
  types/node/events.d.ts
  types/node/test/events.ts
  types/node/v16/events.d.ts
  types/node/v16/test/events.ts
  types/node/v18/events.d.ts
  types/node/v18/test/events.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#66888 feat(sinon): add define method to sandboxes
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#66843 [node] - Fix stream/consumers iterable types
  types/node/stream/consumers.d.ts
  types/node/test/stream.ts
  types/node/ts4.8/stream/consumers.d.ts
  types/node/v16/stream/consumers.d.ts
  types/node/v16/ts4.8/stream/consumers.d.ts
  types/node/v18/stream/consumers.d.ts
  types/node/v18/ts4.8/stream/consumers.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66895 Less strict types on files and proofs
  types/snarkjs/index.d.cts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Check Config

#66883 [supertest] add options to `supertest()` and `supertest.agent()`
  types/supertest/index.d.ts
  types/supertest/supertest-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66797 wavesurfer.js: remove myself as owner
  types/wavesurfer.js/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change, Edits Owners

#66906 [OvenPlayer] add undocumented evnet, fix create type
  types/ovenplayer/index.d.ts
  types/ovenplayer/ovenplayer-tests.ts
Labels: Self Merge, Owner Approved

#66908 [invity_api] Add destinationPaymentExtraIdDescription to SellFiatTrade
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
  types/invity-api/tslint.json
Labels: Self Merge, Owner Approved

#66859 Update wicg-file-system-access types based on latest spec (2023/10)
  types/wicg-file-system-access/index.d.ts
  types/wicg-file-system-access/wicg-file-system-access-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66905 fix failing test in wordpress__components
  types/wordpress__components/wordpress__components-tests.tsx
Labels: Self Merge, Owner Approved, Maintainer Approved

#66914 Remove @google-cloud/tasks
  notNeededPackages.json
  types/google-cloud__tasks/.eslintrc.json
  types/google-cloud__tasks/google-cloud__tasks-tests.ts
  types/google-cloud__tasks/index.d.ts
  types/google-cloud__tasks/package.json
  types/google-cloud__tasks/tsconfig.json
  types/google-cloud__tasks/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Check Config

#66831 feat: add type for express-legacy-expires
  types/express-legacy-expires/express-legacy-expires-tests.ts
  types/express-legacy-expires/index.d.ts
  types/express-legacy-expires/tsconfig.json
  types/express-legacy-expires/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66845 [postcss-functions] Add types for postcss-functions
  types/postcss-functions/index.d.ts
  types/postcss-functions/package.json
  types/postcss-functions/postcss-functions-tests.ts
  types/postcss-functions/tsconfig.json
  types/postcss-functions/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66762 remove marked
  notNeededPackages.json
  types/marked-terminal/marked-terminal-tests.ts
  types/marked-terminal/package.json
  types/marked-terminal/tsconfig.json
  types/marked/OTHER_FILES.txt
  types/marked/index.d.mts
  types/marked/index.d.ts
  types/marked/marked-tests.ts
  types/marked/package.json
  types/marked/tsconfig.json
  types/marked/tslint.json
  types/marked/v3/.eslintrc.json
  types/marked/v3/index.d.ts
  types/marked/v3/marked-tests.ts
  types/marked/v3/tsconfig.json
  types/marked/v3/tslint.json
  types/marked/v4/OTHER_FILES.txt
  types/marked/v4/index.d.mts
  types/marked/v4/index.d.ts
  types/marked/v4/marked-tests.ts
  types/marked/v4/tsconfig.json
  types/marked/v4/tslint.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Check Config

#66842 V1.26.0
  types/consumer-data-standards/admin/index.d.ts
  types/consumer-data-standards/banking/index.d.ts
  types/consumer-data-standards/energy/index.d.ts
  types/consumer-data-standards/index.d.ts
  types/consumer-data-standards/telco/index.d.ts
  types/consumer-data-standards/tslint.json
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Check Config, No Other Owners, Huge Change

#66817 docs(zh): fix typo
  README.zh-Hans.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66818 aws-lambda | add IoT Custom Authorizer
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/iot-authorizer-tests.ts
  types/aws-lambda/trigger/iot-authorizer.d.ts
  types/aws-lambda/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66656 fix(conventional-recommended-bump): update typings for v9 of the library
  types/conventional-recommended-bump/conventional-recommended-bump-tests.ts
  types/conventional-recommended-bump/index.d.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#66811 :label: Types @alpinejs/collapse
  types/alpinejs__collapse/alpinejs__collapse-tests.ts
  types/alpinejs__collapse/index.d.ts
  types/alpinejs__collapse/tsconfig.json
  types/alpinejs__collapse/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66885 remove exif-reader as types are bundled since 2.0.0
  notNeededPackages.json
  types/exif-reader/exif-reader-tests.ts
  types/exif-reader/index.d.ts
  types/exif-reader/tsconfig.json
  types/exif-reader/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66726 [react-dom] Add types for experimental_useFormState
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
Labels: Author is Owner, Critical package, Unreviewed

#66913 [pexrtc] Disable npm-naming rule
  types/pexrtc/tslint.json
Labels: Self Merge, Maintainer Approved, Check Config

#66828 [pdfmake] Add decoration array support
  types/pdfmake/interfaces.d.ts
  types/pdfmake/test/pdfmake-interfaces-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66896 [react-dom] Update types for latest state of Float
  types/react-dom/canary.d.ts
  types/react-dom/test/canary-tests.tsx
Labels: Other Approved, Author is Owner, Critical package

#66907 [ramda] Bump types-ramda package to latest
  types/ramda/package.json
  types/ramda/test/filter-tests.ts
  types/ramda/test/fromPairs-tests.ts
  types/ramda/test/indexBy-tests.ts
  types/ramda/test/keys-tests.ts
  types/ramda/test/on-tests.ts
  types/ramda/test/pick-tests.ts
  types/ramda/test/prop-tests.ts
  types/ramda/test/propEq-tests.ts
  types/ramda/test/remove-tests.ts
  types/ramda/test/slice-tests.ts
  types/ramda/test/toPairs-tests.ts
  types/ramda/test/toPairsIn-tests.ts
  types/ramda/test/tryCatch-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#66897 [react] Taint APIs
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#66901 [@types/intersects] Add optional thickness parameters
  types/intersects/OTHER_FILES.txt
  types/intersects/intersects-tests.ts
  types/intersects/line-line.d.ts
Labels: Self Merge, Maintainer Approved, Check Config

#66863 fix: add missing content in the Japanese README
  README.ja.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66902 [colab] migrating typing from colabtools
  types/colab/colab-tests.ts
  types/colab/index.d.ts
  types/colab/tsconfig.json
  types/colab/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved, Check Config

#66801 jquery: Specialize .val() for elements with known value types
  types/jquery/JQuery.d.ts
  types/jquery/test/val.ts
  types/jquery/tsconfig.json
Labels: Self Merge, Maintainer Approved, Critical package

#66847 add `make-arrow-function`
  types/make-arrow-function/index.d.ts
  types/make-arrow-function/make-arrow-function-tests.ts
  types/make-arrow-function/tsconfig.json
  types/make-arrow-function/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66886 add `make-generator-function`
  types/make-generator-function/index.d.ts
  types/make-generator-function/make-generator-function-tests.ts
  types/make-generator-function/tsconfig.json
  types/make-generator-function/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66887 add `make-async-generator-function`
  types/make-async-generator-function/index.d.ts
  types/make-async-generator-function/make-async-generator-function-tests.ts
  types/make-async-generator-function/tsconfig.json
  types/make-async-generator-function/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66927 Update types for VS Code 1.83
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#66929 [passport-apple] Update typings
  types/passport-apple/index.d.ts
  types/passport-apple/passport-apple-tests.ts
Labels: Other Approved, Self Merge

#66877 Feature/update types
  types/gorilla-engine/components/Knob.d.ts
  types/gorilla-engine/components/SliceEditor.d.ts
  types/gorilla-engine/components/Slider.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66921 fix: tizen-tv-webapis: make onsubtitlechange callback attributes an array
  types/tizen-tv-webapis/index.d.ts
  types/tizen-tv-webapis/test/tizen-tv-webapis-tests.cjs.ts
  types/tizen-tv-webapis/test/tizen-tv-webapis-tests.global.ts
Labels: Self Merge, Owner Approved

#66940 Ensure support window regularly updates, tweak workflow and script
  .github/workflows/support-window.yml
  scripts/support-window.js
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66923 [vanillajs-datepicker] Make DateRangePickerOptions extend from DatepickerOptions
  types/vanillajs-datepicker/DateRangePicker.d.ts
  types/vanillajs-datepicker/vanillajs-datepicker-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#66933 [check-types] added, updated and grouped all search keys and values methods
  types/check-types/check-types-tests.ts
  types/check-types/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66948 [mercadopago-sdk-js] Fix bricks complement in address types
  types/mercadopago-sdk-js/core.d.ts
  types/mercadopago-sdk-js/index.d.ts
  types/mercadopago-sdk-js/mercadopago-sdk-js-tests.ts
  types/mercadopago-sdk-js/modules/bricks.d.ts
  types/mercadopago-sdk-js/modules/cardform.d.ts
  types/mercadopago-sdk-js/modules/fields.d.ts
  types/mercadopago-sdk-js/shared.d.ts
Labels: Other Approved, Self Merge

#66819 [mailchimp__mailchimp_marketing] Add customer journeys API
  types/mailchimp__mailchimp_marketing/index.d.ts
  types/mailchimp__mailchimp_marketing/mailchimp__mailchimp_marketing-tests.ts
Labels: Self Merge, Owner Approved

#66941 [dns2] Add support for IPv6 UDP DNS servers
  types/dns2/dns2-tests.ts
  types/dns2/index.d.ts
Labels: Self Merge, Owner Approved

#66939 [gtag.js] Replace function overload with generics
  types/gtag.js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#66235 Added dprint config and commit-on-master task
  .dprint.jsonc
  .git-blame-ignore-revs
  .github/workflows/format-and-commit.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  .vscode/extensions.json
  .vscode/settings.template.json
  README.fr.md
  README.it.md
  README.ja.md
  README.md
  README.zh-Hans.md
  dangerfile.ts
  package.json
  scripts/tslint-rule-begone.js
  scripts/tslint-rule-to-eslint.js
  types/lodash-es/scripts/generate-modules.ts
  types/node/scripts/generate-docs/docs.ts
  types/node/scripts/generate-docs/package.json
  types/node/ts4.8/scripts/generate-docs/docs.ts
  types/node/ts4.8/scripts/generate-docs/package.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package

#66954 Fix misplaced no-unnecessary-generics in yargs after reformat
  types/yargs/index.d.ts
Labels: Critical package, Untested Change

#66962 Remove react-clipboardjs-copy, typed since 2.0.0
  .dprint.jsonc
  notNeededPackages.json
  types/react-clipboardjs-copy/index.d.ts
  types/react-clipboardjs-copy/react-clipboardjs-copy-tests.tsx
  types/react-clipboardjs-copy/tsconfig.json
  types/react-clipboardjs-copy/tslint.json
Labels: Edits Infrastructure

#66938 [wordpress__*] Resolve breaking changes with `@wordpress/element@5.2.0`
  types/wordpress__block-editor/package.json
  types/wordpress__blocks/package.json
  types/wordpress__edit-post/package.json
  types/wordpress__notices/package.json
  types/wordpress__rich-text/package.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#66871 [server] engine option should accept an object
  types/server/server-tests.ts
  types/server/typings/options.d.ts
Labels: Other Approved, Self Merge, Owner Approved

#66968 [jsx-pdf] fix failing nightly test
  types/jsx-pdf/jsx-pdf-tests.tsx
Labels: Self Merge, Owner Approved

#66958 Remove formatting exception for righto
  .dprint.jsonc
  types/righto/index.d.ts
  types/righto/righto-tests.ts
Labels: Owner Approved, Edits Infrastructure

#66959 Fix and format react-native-awesome-card-io
  .dprint.jsonc
  types/react-native-awesome-card-io/index.d.ts
  types/react-native-awesome-card-io/react-native-awesome-card-io-tests.tsx
Labels: Edits Infrastructure

#66966 add correct return type for drawflow addNode
  types/drawflow/drawflow-tests.ts
  types/drawflow/index.d.ts
Labels: Other Approved, Self Merge

#66972 [koa-favicon] Fix DefinitelyTyped header
  types/koa-favicon/.eslintrc.json
  types/koa-favicon/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change, Check Config

#66960 Remove formatting exception for react-syntax-highlighter
  .dprint.jsonc
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Edits Infrastructure, Critical package

#66976 Enable formatting for a few working i18n* packages
  .dprint.jsonc
  types/i18n-abide/i18n-abide-tests.ts
  types/i18n-abide/index.d.ts
  types/i18n-js/i18n-js-tests.ts
  types/i18n-js/index.d.ts
  types/i18n/i18n-tests.ts
  types/i18n/index.d.ts
  types/i18next-fs-backend/i18next-fs-backend-tests.ts
  types/i18next-fs-backend/index.d.ts
Labels: Popular package, Edits Infrastructure, Edits multiple packages

#66980 [react-map-gl] enable formatting
  .dprint.jsonc
  types/react-map-gl/index.d.ts
  types/react-map-gl/react-map-gl-tests.tsx
Labels: Edits Infrastructure

#66975 [google-apps-script] Add SpreadsheetApp ValueType
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#66944 Update types for koa-favicon@2.1.0
  types/koa-favicon/index.d.ts
  types/koa-favicon/koa-favicon-tests.ts
Labels: Other Approved, Self Merge

#66989 [vue-select]: Make child components optional
  types/vue-select/index.d.ts
  types/vue-select/vue-select-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66984 Remove Tino's handle
  types/node-forge/index.d.ts
Labels: Popular package, Author is Owner, Untested Change, Edits Owners

#66919 [pixrem] Add types for pixrem
  types/pixrem/index.d.ts
  types/pixrem/package.json
  types/pixrem/pixrem-tests.ts
  types/pixrem/tsconfig.json
  types/pixrem/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66917 [colorguard] Add types for colorguard
  types/colorguard/colorguard-tests.ts
  types/colorguard/index.d.ts
  types/colorguard/package.json
  types/colorguard/tsconfig.json
  types/colorguard/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66928 [react] Upgrade Server Actions to canary
  types/react-dom/canary.d.ts
  types/react-dom/experimental.d.ts
  types/react-dom/test/canary-tests.tsx
  types/react-dom/test/experimental-tests.tsx
  types/react/canary.d.ts
  types/react/experimental.d.ts
  types/react/test/canary.tsx
  types/react/test/experimental.tsx
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/canary.tsx
  types/react/ts5.0/test/experimental.tsx
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, Critical package

#66684 fix(pg): add missing default configuration option
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66824 [node] Add fetch types
  types/formidable/formidable-tests.ts
  types/hidefile/test/hidefile-tests.cjs.ts
  types/levelup/levelup-tests.ts
  types/node/globals.d.ts
  types/node/package.json
  types/node/test/globals.ts
  types/node/ts4.8/globals.d.ts
  types/node/ts4.8/test/globals.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Critical package

#66970 [http-signature] Add types for http-signature
  types/http-signature/http-signature-tests.ts
  types/http-signature/index.d.ts
  types/http-signature/lib/parser.d.ts
  types/http-signature/lib/signer.d.ts
  types/http-signature/lib/utils.d.ts
  types/http-signature/lib/verify.d.ts
  types/http-signature/tsconfig.json
  types/http-signature/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66918 [postcss-use] Add types for postcss-use
  types/postcss-use/index.d.ts
  types/postcss-use/package.json
  types/postcss-use/postcss-use-tests.ts
  types/postcss-use/tsconfig.json
  types/postcss-use/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66891 feat: :sparkles: add types for @bugsnag/cuid
  types/bugsnag__cuid/bugsnag__cuid-tests.ts
  types/bugsnag__cuid/index.d.ts
  types/bugsnag__cuid/tsconfig.json
  types/bugsnag__cuid/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66931 [postcss-color-gray] Add types for postcss-color-gray
  types/postcss-color-gray/index.d.ts
  types/postcss-color-gray/package.json
  types/postcss-color-gray/postcss-color-gray-tests.ts
  types/postcss-color-gray/tsconfig.json
  types/postcss-color-gray/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66965 [postcss-sorting] Add types for postcss-sorting
  types/postcss-sorting/index.d.ts
  types/postcss-sorting/package.json
  types/postcss-sorting/postcss-sorting-tests.ts
  types/postcss-sorting/tsconfig.json
  types/postcss-sorting/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#66993 Fix git add when used on types dirs that look like ignored files
  .gitignore
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66781 [Bluebird] Fix reduce initialValue type
  types/bluebird/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#66889 chore(dom-clipboard-api): remove redundant types
  types/dom-clipboard-api/dom-clipboard-api-tests.ts
  types/dom-clipboard-api/index.d.ts
  types/dom-clipboard-api/tsconfig.json
  types/dom-clipboard-api/tslint.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#66945 react-places-autocomplete: Add locationRestriction prop to searchOptions
  types/react-places-autocomplete/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66956 Added missing enums
  types/consumer-data-standards/energy/index.d.ts
  types/consumer-data-standards/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#66949 Remove `ziggy-js`
  notNeededPackages.json
  types/ziggy-js/index.d.ts
  types/ziggy-js/package.json
  types/ziggy-js/tsconfig.json
  types/ziggy-js/tslint.json
  types/ziggy-js/ziggy-js-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66936 feat: add type for makeerror
  types/makeerror/index.d.ts
  types/makeerror/makeerror-tests.ts
  types/makeerror/tsconfig.json
  types/makeerror/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66869 [three] r157
  types/three/examples/jsm/capabilities/WebGL.d.ts
  types/three/examples/jsm/controls/DragControls.d.ts
  types/three/examples/jsm/controls/OrbitControls.d.ts
  types/three/examples/jsm/controls/TrackballControls.d.ts
  types/three/examples/jsm/controls/TransformControls.d.ts
  types/three/examples/jsm/exporters/EXRExporter.d.ts
  types/three/examples/jsm/loaders/DRACOLoader.d.ts
  types/three/examples/jsm/loaders/FontLoader.d.ts
  types/three/examples/jsm/nodes/accessors/ReflectVectorNode.d.ts
  types/three/examples/jsm/nodes/core/Node.d.ts
  types/three/examples/jsm/nodes/display/BlendModeNode.d.ts
  types/three/index.d.ts
  types/three/src/Three.d.ts
  types/three/src/animation/AnimationUtils.d.ts
  types/three/src/cameras/CubeCamera.d.ts
  types/three/src/constants.d.ts
  types/three/src/core/Raycaster.d.ts
  types/three/src/core/RenderTarget.d.ts
  types/three/src/extras/core/CurvePath.d.ts
  types/three/src/extras/core/Path.d.ts
  types/three/src/lights/AmbientLightProbe.d.ts
  types/three/src/lights/HemisphereLightProbe.d.ts
  types/three/src/loaders/FileLoader.d.ts
  types/three/src/loaders/ImageBitmapLoader.d.ts
  types/three/src/loaders/Loader.d.ts
  types/three/src/loaders/ObjectLoader.d.ts
  types/three/src/materials/Material.d.ts
  types/three/src/math/Color.d.ts
  types/three/src/math/ColorManagement.d.ts
  types/three/src/objects/Sprite.d.ts
  types/three/src/renderers/WebGLRenderer.d.ts
  types/three/src/renderers/webgl/WebGLLights.d.ts
  types/three/src/renderers/webgl/WebGLProgram.d.ts
  types/three/test/unit/examples/jsm/nodes/display/ColorAdjustmentNode.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#66763 Add missing `pannable` attribute to `ElementDefinition` in cytoscape.
  types/cytoscape/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#66909 [k6] Add context.cookies and improve cookie TS definitions
  types/k6/experimental/browser.d.ts
  types/k6/experimental/grpc.d.ts
  types/k6/index.d.ts
  types/k6/net/grpc.d.ts
  types/k6/test/browser.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66549 Add `page.on('console')` method definition for k6/experimental/browser
  types/k6/experimental/browser.d.ts
  types/k6/test/browser.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66992 Feat: add types for streamsearch module.
  types/streamsearch/index.d.ts
  types/streamsearch/streamsearch-tests.ts
  types/streamsearch/tsconfig.json
  types/streamsearch/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#67002 Remove self from owners of testing-library__cypress
  types/testing-library__cypress/index.d.ts
Labels: Popular package, Author is Owner, Untested Change, Edits Owners

#66999 remove: @xstyled/* packages
  notNeededPackages.json
  types/xstyled__styled-components/index.d.ts
  types/xstyled__styled-components/tsconfig.json
  types/xstyled__styled-components/tslint.json
  types/xstyled__styled-components/xstyled__styled-components-tests.tsx
  types/xstyled__system/index.d.ts
  types/xstyled__system/package.json
  types/xstyled__system/tsconfig.json
  types/xstyled__system/tslint.json
  types/xstyled__system/xstyled__system-tests.tsx
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#66994 Update dprint settings to format JSON
  .dprint.jsonc
  .vscode/settings.template.json
  scripts/tslint-rule-to-eslint.js
Labels: Edits Infrastructure

#67006 Don't format and commit on forks
  .github/workflows/format-and-commit.yml
Labels: Edits Infrastructure

#67007 Exempt recurly__recurly-js from formatting enforcement
  .dprint.jsonc
Labels: Edits Infrastructure

#66760 pg: Pool callback gets err ^ client
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66995 update(balanced-match): v3 updates
  types/balanced-match/balanced-match-tests.ts
  types/balanced-match/index.d.ts
  types/balanced-match/package.json
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Check Config, No Other Owners

#67008 feat: :sparkles: add types for node-random-name
  types/node-random-name/index.d.ts
  types/node-random-name/node-random-name-tests.ts
  types/node-random-name/tsconfig.json
  types/node-random-name/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66791 [google-libphonenumber] Add new method getLengthOfNationalDestination…
  types/google-libphonenumber/google-libphonenumber-tests.ts
  types/google-libphonenumber/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#67015 [sharedb] Add `doc.del()` overloads
  types/sharedb/lib/sharedb.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#67010 [postcss-page-break] Add types for postcss-page-break
  types/postcss-page-break/index.d.ts
  types/postcss-page-break/package.json
  types/postcss-page-break/postcss-page-break-tests.ts
  types/postcss-page-break/tsconfig.json
  types/postcss-page-break/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#67012 add `mock-property`
  types/mock-property/index.d.ts
  types/mock-property/mock-property-tests.ts
  types/mock-property/tsconfig.json
  types/mock-property/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#67020 feat: ✨ add types for chartjs-color-string
  types/chartjs-color-string/chartjs-color-string-tests.ts
  types/chartjs-color-string/index.d.ts
  types/chartjs-color-string/tsconfig.json
  types/chartjs-color-string/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#67026 Add missing newline to dangerbot formatting message
  dangerfile.ts
Labels: Edits Infrastructure

#67017 Add `esbuild-vue` package types
  types/esbuild-vue/esbuild-vue-tests.ts
  types/esbuild-vue/index.d.ts
  types/esbuild-vue/tsconfig.json
  types/esbuild-vue/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#67027 Format yaml with dprint
  .dprint.jsonc
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/CI.yml
  .github/workflows/UpdateCodeowners.yml
  .github/workflows/daily.yml
  .github/workflows/format-and-commit.yml
  .github/workflows/ghostbuster.yml
  .github/workflows/support-window.yml
  azure-pipelines.yml
Labels: Edits Infrastructure

#67014 mapbox_mapbox-gl-draw: fix return type on constrainFeatureMovement function
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#67025 [http-signature] Fix typo in `writeDateHeader`
  types/http-signature/http-signature-tests.ts
  types/http-signature/lib/signer.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#67028 feat: ✨ add types for random-uuid-v4
  types/random-uuid-v4/index.d.ts
  types/random-uuid-v4/random-uuid-v4-tests.ts
  types/random-uuid-v4/tsconfig.json
  types/random-uuid-v4/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66784 update @types/jenkins definition version 1.0.2
  types/jenkins/index.d.ts
  types/jenkins/jenkins-tests.ts
  types/jenkins/package.json
Labels: Self Merge, Maintainer Approved, No Other Owners

#66759 facebook-js-sdk: Support Facebook Login for Business
  types/facebook-js-sdk/facebook-js-sdk-tests.ts
  types/facebook-js-sdk/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#67001 update: type definition for leaflet.fullscreen to v3.0
  types/leaflet.fullscreen/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#66991 [react-big-calendar] Add allDayMaxRows property to CalendarProps
  types/react-big-calendar/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66747 [chai] add missing _super parameter to overwriteProperty getter parameter
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#66986 Fix/react datepicker icon type
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#66981 Adding ts support for africastalking
  types/africastalking/africastalking-tests.ts
  types/africastalking/index.d.ts
  types/africastalking/tsconfig.json
  types/africastalking/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#67046 Correct `applyPatch` return type in `@types/diff`
  types/diff/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#67034 [node] fix Blob to correctly merge with DOM
  types/node/buffer.d.ts
  types/node/test/buffer.ts
  types/node/ts4.8/buffer.d.ts
  types/node/ts4.8/test/buffer.ts
  types/node/v16/test/buffer.ts
  types/node/v16/ts4.8/test/buffer.ts
  types/node/v18/buffer.d.ts
  types/node/v18/test/buffer.ts
  types/node/v18/ts4.8/buffer.d.ts
  types/node/v18/ts4.8/test/buffer.ts
Labels: Self Merge, Maintainer Approved, Critical package

#67041 [node-zookeeper-client] fix node-zookeeper-client Stat type
  types/node-zookeeper-client/index.d.ts
  types/node-zookeeper-client/node-zookeeper-client-tests.ts
Labels: Self Merge, Owner Approved

#67048 make height and width properties accommodate string values in graphset
  types/zingchart/es6/index.d.ts
  types/zingchart/zingchart-tests.ts
Labels: Other Approved, Self Merge

#67019 [sharedb] stronger `doc.create()` typing
  types/sharedb/lib/sharedb.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#66810 [google-apps-script] Add driveFile, driveFolder to DriveItem/DriveItemReference
  types/google-apps-script/apis/driveactivity_v2.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#67038 [types/node] `import.meta.resolve(…)` updates: version, arg name, comment
  types/node/module.d.ts
  types/node/ts4.8/module.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#67051 `ads-client`: Add `PLCEnum` type
  types/ads-client/ads-client-tests.ts
  types/ads-client/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#67018 [PDFKit] Update to 1.3
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#67056 Add `vue-template-es2015-compiler` package types
  types/vue-template-es2015-compiler/index.d.ts
  types/vue-template-es2015-compiler/tsconfig.json
  types/vue-template-es2015-compiler/tslint.json
  types/vue-template-es2015-compiler/vue-template-es2015-compiler-tests.ts
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#66873 Create bidi/logInspector.d.ts in selenium-webdriver types
  types/selenium-webdriver/bidi/filterBy.d.ts
  types/selenium-webdriver/bidi/logEntries.d.ts
  types/selenium-webdriver/bidi/logInspector.d.ts
  types/selenium-webdriver/index.d.ts
  types/selenium-webdriver/test/bidi/filterBy.ts
  types/selenium-webdriver/test/bidi/logEntries.ts
  types/selenium-webdriver/test/bidi/logInspector.ts
  types/selenium-webdriver/tsconfig.json
Labels: Self Merge, Maintainer Approved, Critical package

#67055 add types for `hex-to-binary` by @geunheejung
  types/hex-to-binary/hex-to-binary-tests.ts
  types/hex-to-binary/index.d.ts
  types/hex-to-binary/tsconfig.json
  types/hex-to-binary/tslint.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#67062 [@type/react-native-sqlite-storage] change property typo
  types/react-native-sqlite-storage/index.d.ts
  types/react-native-sqlite-storage/react-native-sqlite-storage-tests.ts
Labels: Self Merge, Owner Approved

#66672 [mapbox-gl] `rotateTo` method accepts CameraOptions & AnimationOptions
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved

#67070 [node-fetch-cache] Update cache.set args
  types/node-fetch-cache/index.d.ts
  types/node-fetch-cache/node-fetch-cache-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#67066 Fixed type for StandardApiResponse.status
  types/backblaze-b2/backblaze-b2-tests.ts
  types/backblaze-b2/index.d.ts
Labels: Self Merge, Owner Approved

#67054 Remove nodejs-captcha, not on npm, repo gone
  types/nodejs-captcha/index.d.ts
  types/nodejs-captcha/nodejs-captcha-tests.ts
  types/nodejs-captcha/tsconfig.json
  types/nodejs-captcha/tslint.json
Labels: Self Merge, Maintainer Approved

#66743 [@types/chrome] Added missing type "chrome.dom"
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#67078 Feature/update types
  types/gorilla-engine/components/ScrollView.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66635 Updates types for Recurly.js v4.25.9
  types/recurly__recurly-js/lib/google-pay/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Untested Change

#66861 Updates types for Recurly.js v4.25.10
  types/recurly__recurly-js/index.d.ts
  types/recurly__recurly-js/lib/3d-secure.d.ts
  types/recurly__recurly-js/lib/address.d.ts
  types/recurly__recurly-js/lib/adyen.d.ts
  types/recurly__recurly-js/lib/alternative-payment-methods.d.ts
  types/recurly__recurly-js/lib/apple-pay/index.d.ts
  types/recurly__recurly-js/lib/apple-pay/native.d.ts
  types/recurly__recurly-js/lib/bank-account.d.ts
  types/recurly__recurly-js/lib/bank-redirect.d.ts
  types/recurly__recurly-js/lib/configure.d.ts
  types/recurly__recurly-js/lib/elements.d.ts
  types/recurly__recurly-js/lib/emitter.d.ts
  types/recurly__recurly-js/lib/error.d.ts
  types/recurly__recurly-js/lib/gift-card.d.ts
  types/recurly__recurly-js/lib/google-pay/index.d.ts
  types/recurly__recurly-js/lib/google-pay/native.d.ts
  types/recurly__recurly-js/lib/paypal.d.ts
  types/recurly__recurly-js/lib/pricing/checkout.d.ts
  types/recurly__recurly-js/lib/pricing/index.d.ts
  types/recurly__recurly-js/lib/pricing/promise.d.ts
  types/recurly__recurly-js/lib/pricing/subscription.d.ts
  types/recurly__recurly-js/lib/recurly.d.ts
  types/recurly__recurly-js/lib/token.d.ts
  types/recurly__recurly-js/lib/validate.d.ts
  types/recurly__recurly-js/test/3d-secure.ts
  types/recurly__recurly-js/test/adyen.ts
  types/recurly__recurly-js/test/apple-pay.ts
  types/recurly__recurly-js/test/bank-account.ts
  types/recurly__recurly-js/test/configure.ts
  types/recurly__recurly-js/test/elements.ts
  types/recurly__recurly-js/test/gift-card.ts
  types/recurly__recurly-js/test/google-pay.ts
  types/recurly__recurly-js/test/paypal.ts
  types/recurly__recurly-js/test/pricing/checkout.ts
  types/recurly__recurly-js/test/pricing/subscription.ts
  types/recurly__recurly-js/test/recurly-error.ts
  types/recurly__recurly-js/test/token/elements.ts
  types/recurly__recurly-js/test/token/hosted-field.ts
  types/recurly__recurly-js/test/validate.ts
Labels: Self Merge, Owner Approved, Huge Change

#67016 [sharedb] Fix `lib/client` class exports
  types/sharedb/lib/client.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66898 [@types/node]: Fix typing of UserInfo.shell to be correct to behaviour and documentation
  types/node/os.d.ts
  types/node/ts4.8/os.d.ts
  types/node/v16/os.d.ts
  types/node/v16/ts4.8/os.d.ts
  types/node/v18/os.d.ts
  types/node/v18/ts4.8/os.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package, Untested Change, No Other Owners

#66979 [react-blessed] enable formatting
  .dprint.jsonc
  types/react-blessed/.eslintrc.json
  types/react-blessed/index.d.ts
  types/react-blessed/react-blessed-tests.tsx
Labels: Edits Infrastructure, Check Config

#66978 Format rest of i18next packages
  .dprint.jsonc
  types/i18next-ko/i18next-ko-tests.ts
  types/i18next-ko/index.d.ts
  types/i18next-node-fs-backend/i18next-node-fs-backend-tests.ts
  types/i18next-node-fs-backend/index.d.ts
  types/i18next-sprintf-postprocessor/i18next-sprintf-postprocessor-tests.ts
  types/i18next-sprintf-postprocessor/index.d.ts
Labels: Edits Infrastructure, Edits multiple packages

#66942 Remove prose from READMEs which hardcode the minimum supported TS
  README.es.md
  README.fr.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66926 feat: added support for "poll" event for @yagop/node-telegram-bot-api
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Other Approved, Self Merge, No Other Owners

#67103 [poool-access] add new config option - v.5.14
  types/poool-access/index.d.ts
  types/poool-access/package.json
  types/poool-access/poool-access-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#67092 [package-json-validator] add types
  types/package-json-validator/index.d.ts
  types/package-json-validator/package-json-validator-tests.ts
  types/package-json-validator/package.json
  types/package-json-validator/tsconfig.json
  types/package-json-validator/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#67081 Fix for #66946 - forge-apis - add hookExpiry to HooksOptions
  types/forge-apis/index.d.ts
  types/forge-apis/package.json
Labels: Self Merge, Maintainer Approved, Untested Change, Edits Owners

#67094 Fix ghostbuster post-pnpm
  scripts/ghostbuster.js
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#67091 Add types for the eslint-ast-utils package
  types/eslint-ast-utils/eslint-ast-utils-tests.ts
  types/eslint-ast-utils/index.d.ts
  types/eslint-ast-utils/package.json
  types/eslint-ast-utils/tsconfig.json
  types/eslint-ast-utils/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved
