Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2023-03, with the labels that each got.

#64535 minio: region of `makeBucket`is optional and add missing `makeOpt`
  types/minio/index.d.ts
  types/minio/minio-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#64539 fix: clownface pointer returned from list
  types/clownface/clownface-tests.ts
  types/clownface/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#64531 [dns2] Add options to DNS client constructor
  types/dns2/dns2-tests.ts
  types/dns2/index.d.ts
Labels: Self Merge, Owner Approved

#64502 [cytoscape-fcose] Update definitions for v2.2.0
  types/cytoscape-fcose/cytoscape-fcose-tests.ts
  types/cytoscape-fcose/index.d.ts
Labels: Self Merge, Owner Approved

#64530 React-Big-Calendar: Remove self as reviewer
  types/react-big-calendar/index.d.ts
Labels: Popular package, Author is Owner, Untested Change, Edits Owners

#64545 Update @types/vscode to 1.76
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#64365 [node] Add pending var on node/net.d.ts
  types/node/net.d.ts
  types/node/ts4.8/net.d.ts
  types/node/v14/net.d.ts
  types/node/v14/ts4.8/net.d.ts
  types/node/v16/net.d.ts
  types/node/v16/ts4.8/net.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#64542 [node-telegram-bot-api] sync typings with docs
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Owner Approved

#63984 [node] Add a JSDoc description to setTimeout
  types/node/timers.d.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#64521 [sanitize-html] Added missing `mediaChildren` property to IFrame
  types/sanitize-html/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#64538 [react-native-auth0] make authorize params optional
  types/react-native-auth0/index.d.ts
  types/react-native-auth0/react-native-auth0-tests.tsx
Labels: Other Approved, Self Merge

#64549 [react-native-calendar-picker] Add initialView prop to CalendarPickerProps (v7.1.4)
  types/react-native-calendar-picker/index.d.ts
  types/react-native-calendar-picker/react-native-calendar-picker-tests.tsx
Labels: Self Merge, Owner Approved

#64544 update Danger
  docs/support-window.svg
  package.json
Labels: Edits Infrastructure, Maintainer Approved, Where is GH Actions?

#64400 [validator] Add second argument `options` for isCreditCard
  types/validator/index.d.ts
  types/validator/validator-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package, Edits Owners

#64562 (type/preview-email modified): adding a new value, with considering the tests
  types/preview-email/index.d.ts
  types/preview-email/preview-email-tests.ts
Labels: Self Merge, Maintainer Approved

#64512 fix(@types/auth0): add okta as a value for Strategy
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#63539 [@types/chrome] Update RuleCondition from type to interface
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved

#64564 [navermaps] change paths type KVOArrayOfCoords to KVOArray<KVOArrayOfCoords>
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Owner Approved

#64260 [bugfix/64259] fix IteratableIterator type in MIMEParams/entries()
  types/node/ts4.8/util.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package, Untested Change

#64454 chore (sass): remove redundant types
  notNeededPackages.json
  types/get-sass-vars/get-sass-vars-tests.ts
  types/get-sass-vars/index.d.ts
  types/get-sass-vars/package.json
  types/gulp-dart-sass/index.d.ts
  types/gulp-dart-sass/package.json
  types/gulp-postcss/gulp-postcss-tests.ts
  types/sass-loader/index.d.ts
  types/sass-loader/interfaces.d.ts
  types/sass-loader/package.json
  types/sass-true/index.d.ts
  types/sass-true/package.json
  types/sass/index.d.ts
  types/sass/sass-tests.ts
  types/sass/tsconfig.json
  types/sass/tslint.json
Labels: Popular package, Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#64416 Add `PingApi.get()`, add `ListsApi.getAllLists()`, add namespaces to `@types/mailchimp__mailchimp_marketing`
  types/mailchimp__mailchimp_marketing/index.d.ts
  types/mailchimp__mailchimp_marketing/mailchimp__mailchimp_marketing-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#64571 nodegit Deprecated Cred and changed Clone
  types/nodegit/clone.d.ts
  types/nodegit/cred.d.ts
  types/nodegit/credential.d.ts
  types/nodegit/index.d.ts
  types/nodegit/nodegit-tests.ts
Labels: Self Merge, Owner Approved

#63824 [node] Add `os.availableParallelism()` available in 18.4.0
  types/node/os.d.ts
  types/node/test/os.ts
  types/node/ts4.8/os.d.ts
  types/node/ts4.8/test/os.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64537 [firefox-webext-browser] Update to Firefox 111.0b8
  types/firefox-webext-browser/firefox-webext-browser-tests.ts
  types/firefox-webext-browser/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#62306 Opentok 2.23 - Added ScreenshareArchiveLayoutOptions
  types/opentok/index.d.ts
  types/opentok/opentok-tests.ts
Labels: Unmerged, Self Merge, Maintainer Approved

#62571 Adding optional missed construction parameters to @types/lambda-log v3
  types/lambda-log/index.d.ts
  types/lambda-log/lambda-log-tests.ts
Labels: Self Merge, Owner Approved

#64578 [koa-better-body] Update for version 3.3.9
  types/koa-better-body/index.d.ts
  types/koa-better-body/koa-better-body-tests.ts
Labels: Self Merge, Owner Approved

#64532 Types for `readdir-glob` package
  types/readdir-glob/index.d.ts
  types/readdir-glob/readdir-glob-tests.ts
  types/readdir-glob/tsconfig.json
  types/readdir-glob/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64507 [@segment/isodate] Add types
  types/segment__isodate/index.d.ts
  types/segment__isodate/segment__isodate-tests.ts
  types/segment__isodate/tsconfig.json
  types/segment__isodate/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64506 [new-date] Add types
  types/new-date/index.d.ts
  types/new-date/new-date-tests.ts
  types/new-date/tsconfig.json
  types/new-date/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64504 [dog-statsy] Add types
  types/dog-statsy/dog-statsy-tests.ts
  types/dog-statsy/index.d.ts
  types/dog-statsy/tsconfig.json
  types/dog-statsy/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#63961 Fix return type of setInterval in experimental/timers package
  types/k6/experimental/timers.d.ts
  types/k6/test/timers.ts
Labels: Popular package, Self Merge, Owner Approved

#64591 ✨ [sharedb@3.3.0] Add channels to query context
  types/sharedb/index.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Owner Approved

#64595 ⬆ Bump correlating version in index.d.ts
  types/sharedb/index.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Owner Approved

#64309 [tabulator-tables] add missing event callbacks + fix some function return types
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Unmerged, Self Merge, Owner Approved

#64546 Update lesgo's firebase-admin dependency 9->11
  types/lesgo/package.json
  types/lesgo/tsconfig.json
  types/lesgo/v0.6/package.json
  types/lesgo/v0.6/tsconfig.json
Labels: Check Config

#64602 Bump k6 types
  types/k6/crypto.d.ts
  types/k6/http.d.ts
  types/k6/index.d.ts
Labels: Popular package, Untested Change

#64480 Updated selenium-webdriver to include new methods for IE options
  types/selenium-webdriver/ie.d.ts
  types/selenium-webdriver/index.d.ts
  types/selenium-webdriver/test/ie.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Edits Owners

#64496 [win-ca] Add types
  types/win-ca/api.d.ts
  types/win-ca/fallback.d.ts
  types/win-ca/index.d.ts
  types/win-ca/tsconfig.json
  types/win-ca/tslint.json
  types/win-ca/win-ca-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#64604 [chrome] Fix methods in chrome.browserAction namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#64394 Fix typo in App.Notification
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Owner Approved

#64617 chore: add types for CircuitBreaker.toJSON() for opossum
  types/opossum/index.d.ts
  types/opossum/opossum-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#64339 feat(workerpool): update to version 6.4
  types/workerpool/index.d.ts
  types/workerpool/tsconfig.json
  types/workerpool/workerpool-tests.ts
Labels: Self Merge, Owner Approved

#62254 Update gulp-newer to allow using options.map wiithout options.dest.
  types/gulp-newer/gulp-newer-tests.ts
  types/gulp-newer/index.d.ts
Labels: Self Merge, Maintainer Approved

#64428 Update types for 'netmask' package
  types/netmask/index.d.ts
  types/netmask/netmask-tests.ts
  types/netmask/tslint.json
Labels: Self Merge, Owner Approved, Edits Owners

#64326 [dcp-client]: Update `localExec` and event listener methods
  types/dcp-client/dcp-client-tests.ts
  types/dcp-client/index.d.ts
  types/dcp-client/tsconfig.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners, Edits Owners

#64633 Fix inquirer tests for TS 5.1
  types/inquirer/inquirer-tests.ts
  types/inquirer/v8/inquirer-tests.ts
Labels: Critical package

#64608 auth0: Add options for getConnections()
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#64566 feat(types): add types for sd-notify
  types/sd-notify/index.d.ts
  types/sd-notify/sd-notify-tests.ts
  types/sd-notify/tsconfig.json
  types/sd-notify/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64533 [persistent-cache] new module types
  types/persistent-cache/index.d.ts
  types/persistent-cache/persistent-cache-tests.ts
  types/persistent-cache/tsconfig.json
  types/persistent-cache/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64635 Update lodash intersectionWith test for new TS improvements
  types/lodash/lodash-tests.ts
Labels: Owner Approved, Critical package

#64636 Update zen-observable subscribe test for new TS improvements
  types/zen-observable/test/esm-tests.ts
Labels: Critical package

#64637 Exempt resolve-bin from redundant-jsdoc lint rule
  types/resolve-bin/tslint.json
Labels: Check Config

#64638 Exempt react-relay from jsdoc rule
  types/react-relay/tslint.json
  types/react-relay/v7/tslint.json
Labels: Popular package, Owner Approved, Check Config

#64639 Exempt @architect/sandbox from jsdoc lint rule
  types/architect__sandbox/tslint.json
Labels: Check Config

#64643 fix(stremio-addon-sdk): add id to Subtitle type
  types/stremio-addon-sdk/index.d.ts
  types/stremio-addon-sdk/stremio-addon-sdk-tests.ts
Labels: Self Merge, Owner Approved

#64640 Delete polymer-ts
  types/polymer-ts/.eslintrc.json
  types/polymer-ts/index.d.ts
  types/polymer-ts/polymer-ts-tests.ts
  types/polymer-ts/tsconfig.json
  types/polymer-ts/tslint.json
Labels: Check Config

#64646 Adds Buffer.isAscii method to Node
  types/node/buffer.d.ts
  types/node/index.d.ts
  types/node/test/buffer.ts
  types/node/ts4.8/buffer.d.ts
  types/node/ts4.8/test/buffer.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64625 Update chrome.fileSystemProvider in chrome/index.d.ts
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#64116 [README]: Improve Chinese translation
  README.es.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
  README.zh.md
Labels: Other Approved, Edits Infrastructure

#64666 Update ramda test for TS bugfix
  types/ramda/test/binary-tests.ts
  types/ramda/test/nAry-tests.ts
Labels: Popular package

#64657 Update TokenClientConfig in google.accounts
  types/google.accounts/google.accounts-tests.ts
  types/google.accounts/index.d.ts
Labels: Other Approved, Self Merge

#64642 Nightwatch: delete unused jsdoc types
  types/nightwatch/index.d.ts
Labels: Untested Change

#64671 Update dom-screen-wake-lock for TS 5.1
  types/dom-screen-wake-lock/index.d.ts
Labels: Untested Change

#64672 Update dom-webcodecs for TS 5.1
  types/dom-mediacapture-transform/index.d.ts
  types/dom-webcodecs/index.d.ts
  types/dom-webcodecs/test/dom-webcodecs-tests.ts
  types/dom-webcodecs/webcodecs.generated.d.ts
Labels: Popular package, Edits multiple packages

#64674 Update web-animations-js for TS 5.1
  types/web-animations-js/index.d.ts
Labels: Untested Change

#64673 Update w3c-css-typed-object-model-level-1 for TS 5.1
  types/w3c-css-typed-object-model-level-1/index.d.ts
  types/w3c-css-typed-object-model-level-1/w3c-css-typed-object-model-level-1-tests.ts
Labels: Author is Owner, No Other Owners

#64676 Update webappsec-credential-management for TS 5.1
  types/webappsec-credential-management/index.d.ts
Labels: Popular package, Untested Change

#64687 prompts: make `PromptObject.message` required
  types/prompts/index.d.ts
  types/prompts/prompts-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#64611 Archiver: Use readdir-glob instead of glob
  types/archiver/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#64677 Add types for esbuild-plugin-import-map-tests
  types/esbuild-plugin-import-map/esbuild-plugin-import-map-tests.ts
  types/esbuild-plugin-import-map/index.d.ts
  types/esbuild-plugin-import-map/tsconfig.json
  types/esbuild-plugin-import-map/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64700 [chrome] Add chrome.downloads.setUiOptions
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#64420 chore(simple-oauth2): remove enums
  types/simple-oauth2/index.d.ts
  types/simple-oauth2/simple-oauth2-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#64536 feat: update `get-intrinsic` to v1.2
  types/get-intrinsic/get-intrinsic-tests.ts
  types/get-intrinsic/index.d.ts
  types/get-intrinsic/internal/intrinsics.d.ts
  types/get-intrinsic/scripts/collect-intrinsics.ts
  types/get-intrinsic/scripts/intrinsics-data.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#64704 Add type defintions for jp-conversion
  types/jp-conversion/index.d.ts
  types/jp-conversion/jp-conversion-tests.ts
  types/jp-conversion/tsconfig.json
  types/jp-conversion/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64679 Add kakao-pixel type definition
  types/kakao-pixel/index.d.ts
  types/kakao-pixel/kakao-pixel-tests.ts
  types/kakao-pixel/tsconfig.json
  types/kakao-pixel/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64660 Added types for vue3Carousel3d
  types/vue3-carousel-3d/index.d.ts
  types/vue3-carousel-3d/package.json
  types/vue3-carousel-3d/tsconfig.json
  types/vue3-carousel-3d/tslint.json
  types/vue3-carousel-3d/vue3-carousel-3d-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#64707 [leaflet] Add `maxMargin` optional argument to `LatLngBounds.equals`
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#64510 node v18.15 newly added statfs function + related objects
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/test/fs.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64658 [proxy] Add module types
  types/proxy/index.d.ts
  types/proxy/proxy-tests.ts
  types/proxy/tsconfig.json
  types/proxy/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64596 [dockerode] Add headers to Docker options
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#64597 [dockerode] Add nocache to ImageBuildOptions
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#63742 [pouchdb-core] alldocs with keys can have error
  types/pouchdb-core/index.d.ts
  types/pouchdb-core/pouchdb-core-tests.ts
Labels: Unmerged, Self Merge, Maintainer Approved

#64706 [leaflet.vectorgrid] Extend VectorGridOptions from L.GridLayerOptions
  types/leaflet.vectorgrid/index.d.ts
  types/leaflet.vectorgrid/leaflet.vectorgrid-tests.ts
Labels: Self Merge, Owner Approved

#64723 Exempt relay-runtime jsdoc in one place
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
Labels: Popular package, Untested Change

#64467 fix(node): add type `VerifyJsonWebKeyInput` to work with `crypto.verify`
  types/node/crypto.d.ts
  types/node/test/crypto.ts
  types/node/ts4.8/crypto.d.ts
  types/node/ts4.8/test/crypto.ts
  types/node/v16/crypto.d.ts
  types/node/v16/test/crypto.ts
  types/node/v16/ts4.8/crypto.d.ts
  types/node/v16/ts4.8/test/crypto.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64585 chore: removes me from braintree-web-drop-in owners
  types/braintree-web-drop-in/index.d.ts
Labels: Author is Owner, Owner Approved, Untested Change, Edits Owners

#64588 Remove myself from Screeps contributors list
  types/screeps/index.d.ts
Labels: Author is Owner, Owner Approved, Untested Change, Edits Owners

#64603 [jest]: remove unnecessary `ExtractEachCallbackArgs` type helper
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#64503 graphql-upload: Update types to v16
  types/graphql-upload/GraphQLUpload.d.mts
  types/graphql-upload/OTHER_FILES.txt
  types/graphql-upload/Upload.d.mts
  types/graphql-upload/graphql-upload-tests.ts
  types/graphql-upload/graphqlUploadExpress.d.mts
  types/graphql-upload/graphqlUploadKoa.d.mts
  types/graphql-upload/index.d.ts
  types/graphql-upload/package.json
  types/graphql-upload/processRequest.d.mts
Labels: Popular package, Self Merge, Maintainer Approved, Check Config

#64463 Target ES2022 in Akamai EdgeWorkers types
  types/akamai-edgeworkers/index.d.ts
  types/akamai-edgeworkers/test/http-request-tests.ts
  types/akamai-edgeworkers/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Check Config

#64663 Fix `gm` `delay` parameter name from `milliseconds` to `centiseconds`
  types/gm/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#64644 typo agregatorName should be aggregatorName
  types/react-pivottable/Utilities.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#64493 feat(carbon__icons-react): upgrade to 11.16
  types/carbon__icons-react/OTHER_FILES.txt
  types/carbon__icons-react/carbon__icons-react-tests.tsx
  types/carbon__icons-react/es/DocumentMultiple_01.d.ts
  types/carbon__icons-react/es/DocumentMultiple_02.d.ts
  types/carbon__icons-react/es/IbmProcessMining.d.ts
  types/carbon__icons-react/es/ReferenceArchitecture.d.ts
  types/carbon__icons-react/es/UserSponsor.d.ts
  types/carbon__icons-react/es/WhitePaper.d.ts
  types/carbon__icons-react/es/index.d.ts
  types/carbon__icons-react/index.d.ts
  types/carbon__icons-react/lib/DocumentMultiple_01.d.ts
  types/carbon__icons-react/lib/DocumentMultiple_02.d.ts
  types/carbon__icons-react/lib/IbmProcessMining.d.ts
  types/carbon__icons-react/lib/ReferenceArchitecture.d.ts
  types/carbon__icons-react/lib/UserSponsor.d.ts
  types/carbon__icons-react/lib/WhitePaper.d.ts
  types/carbon__icons-react/lib/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Check Config, No Other Owners

#64494 feat(carbon__pictograms-react): upgrade to 11.39
  types/carbon__pictograms-react/OTHER_FILES.txt
  types/carbon__pictograms-react/carbon__pictograms-react-tests.tsx
  types/carbon__pictograms-react/es/app--modernization/index.d.ts
  types/carbon__pictograms-react/es/index.d.ts
  types/carbon__pictograms-react/index.d.ts
  types/carbon__pictograms-react/lib/app--modernization/index.d.ts
  types/carbon__pictograms-react/lib/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Check Config, No Other Owners

#64552 feat: update @nginstack/web-framework other files
  types/nginstack__web-framework/OTHER_FILES.txt
  types/nginstack__web-framework/nginstack__web-framework-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Check Config

#64630 [eslint] include `:exit` nodes in `NodeListener`
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64396 update(dompurify): v3 update
  types/dompurify/index.d.ts
  types/dompurify/test/dompurify-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#64605 [ssh2] Revert status codes to SFTPv3
  types/ssh2/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#64703 Added types for react-simple-oauth2-login
  types/react-simple-oauth2-login/index.d.ts
  types/react-simple-oauth2-login/react-simple-oauth2-login-tests.tsx
  types/react-simple-oauth2-login/tsconfig.json
  types/react-simple-oauth2-login/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64558 [pendo-io-browser] Add initialize.cookieDomain
  types/pendo-io-browser/index.d.ts
  types/pendo-io-browser/pendo-io-browser-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#64261 Enforce strict identity in analytics-node types
  types/analytics-node/analytics-node-tests.ts
  types/analytics-node/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#64718 Add type definitions for fuzzysearch
  types/fuzzysearch/fuzzysearch-tests.ts
  types/fuzzysearch/index.d.ts
  types/fuzzysearch/tsconfig.json
  types/fuzzysearch/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64710 [@koa/cors] bump the major version after breaking changes
  types/koa__cors/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#64721 Add type definitions for postcss-resolve-nested-selector
  types/postcss-resolve-nested-selector/index.d.ts
  types/postcss-resolve-nested-selector/package.json
  types/postcss-resolve-nested-selector/postcss-resolve-nested-selector-tests.ts
  types/postcss-resolve-nested-selector/tsconfig.json
  types/postcss-resolve-nested-selector/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#64720 Add type definitions for postcss-media-query-parser
  types/postcss-media-query-parser/index.d.ts
  types/postcss-media-query-parser/postcss-media-query-parser-tests.ts
  types/postcss-media-query-parser/tsconfig.json
  types/postcss-media-query-parser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64699 [chrome] Add missing manifest permission types
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#64692 New definition package thunderbird-webext-browser: the Thunderbird WebExtensions API
  types/thunderbird-webext-browser/index.d.ts
  types/thunderbird-webext-browser/thunderbird-webext-browser-tests.ts
  types/thunderbird-webext-browser/tsconfig.json
  types/thunderbird-webext-browser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config, Huge Change

#64398 [react-speech-recognition] fix getRecognition return type
  types/react-speech-recognition/index.d.ts
  types/react-speech-recognition/tsconfig.json
Labels: Self Merge, Maintainer Approved, Untested Change

#64573 fix(node): align with AbortConroller.abort(reason?: any)
  types/node/globals.d.ts
  types/node/ts4.8/globals.d.ts
  types/node/v14/globals.d.ts
  types/node/v14/test/globals.ts
  types/node/v14/ts4.8/globals.d.ts
  types/node/v14/ts4.8/test/globals.ts
  types/node/v16/globals.d.ts
  types/node/v16/ts4.8/globals.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#64500 [@types/bmapgl] fix: typo in type AutocompleteResultPoi
  types/bmapgl/bmapgl.service.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#64190 fix: update @types/fundamental-react
  types/fundamental-react/fundamental-react-tests.tsx
  types/fundamental-react/lib/Dialog/Dialog.d.ts
  types/fundamental-react/lib/Popover/Popover.d.ts
  types/fundamental-react/lib/Token/Token.d.ts
Labels: Self Merge, Maintainer Approved

#64629 lz-string: Remove
  notNeededPackages.json
  types/lz-string/index.d.ts
  types/lz-string/lz-string-tests.ts
  types/lz-string/tsconfig.json
  types/lz-string/tslint.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#64711 Update api-gateway-authorizer.d.ts
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/trigger/api-gateway-authorizer.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64716 [react-calendar-rimeline] Fix selected prop type
  types/react-calendar-timeline/index.d.ts
  types/react-calendar-timeline/react-calendar-timeline-tests.tsx
Labels: Self Merge, Owner Approved

#64149 [bwip-js] add missing methods and FontLib
  types/bwip-js/bwip-js-tests.ts
  types/bwip-js/index.d.ts
Labels: Self Merge, Maintainer Approved

#64499 [unix-time] Add types
  types/unix-time/index.d.ts
  types/unix-time/tsconfig.json
  types/unix-time/tslint.json
  types/unix-time/unix-time-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#64719 Add type definitions for fuzzysearch-highlight
  types/fuzzysearch-highlight/fuzzysearch-highlight-tests.ts
  types/fuzzysearch-highlight/index.d.ts
  types/fuzzysearch-highlight/tsconfig.json
  types/fuzzysearch-highlight/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64741 Update vk-openapi tests
  types/vk-openapi/vk-openapi-tests.ts
Labels: Self Merge, Maintainer Approved

#64305 [gestalt]: update to version 95.0
  types/gestalt/gestalt-tests.tsx
  types/gestalt/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#64705 [leaflet] Add `options` property to `L.Layer`, extend `GridLayerOptions` from `LayerOptions`
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#64527 [emailjs-mime-codec] Add initial type definitions
  types/emailjs-mime-codec/emailjs-mime-codec-tests.ts
  types/emailjs-mime-codec/index.d.ts
  types/emailjs-mime-codec/tsconfig.json
  types/emailjs-mime-codec/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64726 fix(sanitize-html): bump to 2.9
  types/sanitize-html/index.d.ts
  types/sanitize-html/sanitize-html-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#64513 chore (react-router-native): remove redundant types
  notNeededPackages.json
  types/react-router-native/index.d.ts
  types/react-router-native/package.json
  types/react-router-native/react-router-native-tests.tsx
  types/react-router-native/tsconfig.json
  types/react-router-native/tslint.json
  types/react-router-navigation/react-router-navigation-tests.tsx
Labels: Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#63883 [gamedig] Add new ipFamily option
  types/gamedig/gamedig-tests.ts
  types/gamedig/index.d.ts
Labels: Self Merge, Owner Approved

#64732 Fixes some typos and small nits in @types/chrome
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#64297 [plaid-link] Update event objects by adding properties and add'l values for union types.
  types/plaid-link/index.d.ts
  types/plaid-link/plaid-link-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#64733 [stripe-v3] add definition for verifyIdentity method
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#64501 fix(sortablejs): Add avoidImplicitDeselect to MultiDragOptions
  types/sortablejs/plugins.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#63882 [jest] type done callback on each
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64432 update koa session 6.4.0
  types/koa-session/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#64599 aws-lambda | add CodeCommit trigger event
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/codecommit-tests.ts
  types/aws-lambda/trigger/codecommit.d.ts
  types/aws-lambda/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64752 feat: update @nginstack/engine definitions
  types/nginstack__engine/index.d.ts
  types/nginstack__engine/lib/database/Database.d.ts
  types/nginstack__engine/lib/database/LobStorage.d.ts
  types/nginstack__engine/lib/dataset/DataSet.d.ts
  types/nginstack__engine/lib/io/File.d.ts
  types/nginstack__engine/lib/net/XMLHttpRequest.d.ts
  types/nginstack__engine/nginstack__engine-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#64754 feat: update @nginstack/orm definitions
  types/nginstack__orm/index.d.ts
  types/nginstack__orm/nginstack__orm-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#64753 feat: update @nginstack/iquery definitions
  types/nginstack__iquery/index.d.ts
  types/nginstack__iquery/nginstack__iquery-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#64755 feat: update @nginstack/jsunit definitions
  types/nginstack__jsunit/index.d.ts
  types/nginstack__jsunit/nginstack__jsunit-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#64756 feat: update @nginstack/datasource definitions
  types/nginstack__datasource/index.d.ts
  types/nginstack__datasource/nginstack__datasource-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#64757 feat: update @nginstack/web-framework definitions
  types/nginstack__web-framework/index.d.ts
  types/nginstack__web-framework/keys/Classes.d.ts
  types/nginstack__web-framework/lib/anchor/AnchorCollection.d.ts
  types/nginstack__web-framework/nginstack__web-framework-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#64739 [jest]: Restore `ExtractEachCallbackArgs` and add tests
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#64766 mParticle: Add types for sideloaded kits
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-instance-tests.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#64760 feat: remove module.d.ts from @nginstack/engine
  types/nginstack__engine/OTHER_FILES.txt
  types/nginstack__engine/lib/module/Module.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change, Check Config

#64770 Disable npm-naming for yandex-maps
  types/yandex-maps/tslint.json
Labels: Check Config

#64751 Add type definitions for passport-twitter-token
  types/passport-twitter-token/index.d.ts
  types/passport-twitter-token/passport-twitter-token-tests.ts
  types/passport-twitter-token/tsconfig.json
  types/passport-twitter-token/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64743 [jest] add `jest.replaceProperty` method types
  types/jest/index.d.ts
  types/jest/jest-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#64479 Updated forge-api-nodejs-client to 0.9.x
  types/forge-apis/README.md
  types/forge-apis/forge-apis-tests.ts
  types/forge-apis/index.d.ts
Labels: Self Merge, Maintainer Approved

#64768 gpt: slot.getResponseInformation() might be null
  types/doubleclick-gpt/doubleclick-gpt-tests.ts
  types/doubleclick-gpt/index.d.ts
Labels: Self Merge, Owner Approved

#64767 Add type definitions for fast-password-entropy
  types/fast-password-entropy/fast-password-entropy-tests.ts
  types/fast-password-entropy/index.d.ts
  types/fast-password-entropy/tsconfig.json
  types/fast-password-entropy/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#64415 Add `setAttribute()` and `removeAttribute()` to `HostedFields` for `@types/braintree-web`
  types/braintree-web/modules/hosted-fields.d.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Self Merge, Maintainer Approved

#64764 [metro] Fix types on 0.76
  types/metro-config/configTypes.d.ts
  types/metro-config/loadConfig.d.ts
  types/metro-resolver/types.d.ts
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, Untested Change

#64775 fix(metro-config): return type of GetTransformOptions should be partial
  types/metro-config/configTypes.d.ts
  types/metro-config/test/configTypes-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved
