Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2023-06, with the labels that each got.

#65135 [react] Allow returning ReactNode from function components
  types/react/index.d.ts
  types/react/jsx-dev-runtime.d.ts
  types/react/jsx-runtime.d.ts
  types/react/test/experimental.tsx
  types/react/test/index.ts
  types/react/test/tsx.tsx
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#65569 add simply-blackjack to DefinitelyTyped
  types/simply-blackjack/cards.d.ts
  types/simply-blackjack/index.d.ts
  types/simply-blackjack/simply-blackjack-tests.ts
  types/simply-blackjack/tsconfig.json
  types/simply-blackjack/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65664 Remove ts4.3 typesVersions
  types/babel__traverse/package.json
  types/babel__traverse/ts4.3/babel__traverse-tests.ts
  types/babel__traverse/ts4.3/index.d.ts
  types/babel__traverse/ts4.3/tsconfig.json
  types/babel__traverse/ts4.3/tslint.json
  types/har-format/package.json
  types/har-format/ts4.3/index.d.ts
  types/har-format/ts4.3/test/har-format-tests.ts
  types/har-format/ts4.3/tsconfig.json
  types/har-format/ts4.3/tslint.json
Labels: Edits multiple packages, Critical package

#65657 Added observ types
  types/observ/computed.d.ts
  types/observ/index.d.ts
  types/observ/observ-tests.ts
  types/observ/source.d.ts
  types/observ/tsconfig.json
  types/observ/tslint.json
  types/observ/watch.d.ts
Labels: New Definition, Self Merge, Maintainer Approved

#65647 Remove metalsmith types
  notNeededPackages.json
  types/metalsmith/index.d.ts
  types/metalsmith/metalsmith-tests.ts
  types/metalsmith/tsconfig.json
  types/metalsmith/tslint.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#65633 [cookieclicker] Update types to 2.052
  types/cookieclicker/cookieclicker-tests.ts
  types/cookieclicker/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#65693 [serverless] Add self managed kafka to the aws provider
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65644 [xmlhttprequest] Add types for xmlhttprequest
  types/xmlhttprequest/index.d.ts
  types/xmlhttprequest/tsconfig.json
  types/xmlhttprequest/tslint.json
  types/xmlhttprequest/xmlhttprequest-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#65691 [aspect-fit] Added definitions
  types/aspect-fit/aspect-fit-tests.ts
  types/aspect-fit/index.d.ts
  types/aspect-fit/tsconfig.json
  types/aspect-fit/tslint.json
Labels: New Definition

#65690 Add types for `@hapi/pez`
  types/hapi__pez/hapi__pez-tests.ts
  types/hapi__pez/index.d.ts
  types/hapi__pez/package.json
  types/hapi__pez/tsconfig.json
  types/hapi__pez/tslint.json
Labels: New Definition, Check Config

#65669 Add types for quantize
  types/quantize/index.d.ts
  types/quantize/quantize-tests.ts
  types/quantize/tsconfig.json
  types/quantize/tslint.json
Labels: New Definition

#65667 @types/strip-bom-string added types
  types/strip-bom-string/index.d.ts
  types/strip-bom-string/strip-bom-string-tests.ts
  types/strip-bom-string/tsconfig.json
  types/strip-bom-string/tslint.json
Labels: New Definition

#65663 Deprecate `@types/filter-invalid-dom-props`
  notNeededPackages.json
  types/filter-invalid-dom-props/filter-invalid-dom-props-tests.ts
  types/filter-invalid-dom-props/index.d.ts
  types/filter-invalid-dom-props/tsconfig.json
  types/filter-invalid-dom-props/tslint.json
Labels: Edits Infrastructure

#65662 Deprecate @types/flatbush - flatbush ships its own types in 4.2.0
  notNeededPackages.json
  types/flatbush/flatbush-tests.ts
  types/flatbush/index.d.ts
  types/flatbush/tsconfig.json
  types/flatbush/tslint.json
  types/geoflatbush/geoflatbush-tests.ts
  types/geoflatbush/index.d.ts
  types/geoflatbush/package.json
  types/geoflatbush/tsconfig.json
Labels: Edits Infrastructure, Edits multiple packages, Check Config, No Other Owners

#65643 Add @types/pqclean
  types/pqclean/index.d.ts
  types/pqclean/pqclean-tests.ts
  types/pqclean/tsconfig.json
  types/pqclean/tslint.json
Labels: New Definition

#65576 Add types for namespace-js
  types/namespace-js/index.d.ts
  types/namespace-js/namespace-js-tests.ts
  types/namespace-js/tsconfig.json
  types/namespace-js/tslint.json
Labels: New Definition

#65588 Remove @types/react-pdf
  notNeededPackages.json
  types/react-pdf/dist/Document.d.ts
  types/react-pdf/dist/Outline.d.ts
  types/react-pdf/dist/Page.d.ts
  types/react-pdf/dist/esm/entry.parcel.d.ts
  types/react-pdf/dist/esm/entry.parcel2.d.ts
  types/react-pdf/dist/esm/entry.vite.d.ts
  types/react-pdf/dist/esm/entry.webpack.d.ts
  types/react-pdf/dist/esm/entry.webpack5.d.ts
  types/react-pdf/dist/pdfjs-dist.d.ts
  types/react-pdf/dist/umd/entry.parcel.d.ts
  types/react-pdf/dist/umd/entry.parcel2.d.ts
  types/react-pdf/dist/umd/entry.vite.d.ts
  types/react-pdf/dist/umd/entry.webpack.d.ts
  types/react-pdf/dist/umd/entry.webpack5.d.ts
  types/react-pdf/index.d.ts
  types/react-pdf/package.json
  types/react-pdf/react-pdf-tests.tsx
  types/react-pdf/tsconfig.json
  types/react-pdf/tslint.json
Labels: Popular package, Owner Approved, Edits Infrastructure

#65587 [minio]: remove package
  notNeededPackages.json
  types/minio/index.d.ts
  types/minio/minio-tests.ts
  types/minio/tsconfig.json
  types/minio/tslint.json
Labels: Popular package, Owner Approved, Edits Infrastructure, Unreviewed

#65067 update(intl-tel-input): update to v18.1
  types/intl-tel-input/index.d.ts
  types/intl-tel-input/test/intl-tel-input-global.ts
Labels: Author is Owner, Unreviewed

#65352 Adding 'distance' return field to the 'polylabel' package
  types/polylabel/index.d.ts
  types/polylabel/polylabel-tests.ts
Labels: Other Approved, Popular package, Unreviewed

#65384 Updates types to "esc-pos-encoder" 1.3
  types/esc-pos-encoder/esc-pos-encoder-tests.ts
  types/esc-pos-encoder/index.d.ts
Labels: Unreviewed, Edits Owners

#64811 [codemirror] add missing rangeFinder option
  types/codemirror/addon/fold/foldgutter.d.ts
  types/codemirror/test/addon/fold/foldgutter.ts
Labels: Popular package, Unreviewed

#65551 Adds types for geojson-validation by @LiamAttClarke
  types/geojson-validation/geojson-validation-tests.ts
  types/geojson-validation/index.d.ts
  types/geojson-validation/tsconfig.json
  types/geojson-validation/tslint.json
Labels: New Definition

#65696 [@types/aws-lambda] Added optional marker for Subject to solve #54379
  types/aws-lambda/test/sns-tests.ts
  types/aws-lambda/trigger/sns.d.ts
Labels: Owner Approved, Critical package

#65685 make headers optional for Request of request-ip package
  types/request-ip/index.d.ts
Labels: Popular package, Untested Change

#65348 [pg] Add missing parameter to BindConfig
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#65590 update(auth0-js): `cookieDomain` configuration option
  types/auth0-js/auth0-js-tests.ts
  types/auth0-js/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#65698 Add types for @eslint/js
  types/eslint__js/eslint__js-tests.ts
  types/eslint__js/index.d.ts
  types/eslint__js/tsconfig.json
  types/eslint__js/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65171 [ldapjs] Adapt to v3
  types/ldapjs/index.d.ts
  types/ldapjs/ldapjs-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65486 fix(auth0): `enabled_connections` added
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#65716 [@wordpress/editor] Updated @wordpress/data package version to 9
  types/wordpress__editor/package.json
Labels: Self Merge, Owner Approved

#65404 Ckeditor4 update tools.d to reflect more upto date functions (4.20.0)
  types/ckeditor4/ckeditor4-tests.ts
  types/ckeditor4/core/dom/dom.d.ts
  types/ckeditor4/core/tools.d.ts
Labels: Author is Owner, Unreviewed

#65501 [ws]: Add generics to the `ServerOptions`
  types/ws/index.d.ts
  types/ws/ws-tests.ts
Labels: Other Approved, Critical package, Unreviewed

#65513 update(preview-email): new options properties
  types/preview-email/index.d.ts
  types/preview-email/preview-email-tests.ts
Labels: Author is Owner, No Other Owners, Unreviewed

#65493 [jsonnet] fix Jsonnet().evalFile()
  types/jsonnet/index.d.ts
  types/jsonnet/jsonnet-tests.ts
Labels: Unreviewed, Edits Owners

#65708 fix(pdfkit): add `Subject` as allowed metadata key
  types/pdfkit/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#65564 Narrow function type of ESLint.IPlugin.rules
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Owner Approved, Critical package

#65705 update kendo-ui typescript definitions to 2023.2.606
  types/kendo-ui/index.d.ts
Labels: Other Approved, Untested Change

#65668 @types/eslint: Flat config support in Linter
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Other Approved, Owner Approved, Critical package

#65634 [uuid] add jsdoc
  types/uuid/index.d.ts
Labels: Other Approved, Owner Approved, Critical package, Untested Change

#65627 [draft-js] exported DraftDecoratorComponentProps
  types/draft-js/index.d.ts
Labels: Popular package, Untested Change

#65718 update for 1.79
  types/vscode/index.d.ts
Labels: Other Approved, Popular package, Untested Change

#65618 Update type definitions of apicache
  types/apicache/index.d.ts
Labels: Untested Change, Unreviewed

#65615 dockerode: Add ConfigReference interface and ContainerSpec configs array
  types/dockerode/index.d.ts
Labels: Popular package, Untested Change, Unreviewed

#65606 Removed attribute clientMetadata for unprovided triggers
  types/aws-lambda/index.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/create-auth-challenge.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/define-auth-challenge.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/post-authentication.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/pre-authentication.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/pre-token-generation.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/verify-auth-challenge-response.d.ts
Labels: Owner Approved, Critical package, Untested Change, Unreviewed, Edits Owners

#65593 Added Version v5.3.0 type changes for oracledb (https://node-oracledb.readthedocs.io/en/latest/release_notes.html)
  types/oracledb/index.d.ts
Labels: Author is Owner, Owner Approved, Untested Change, Unreviewed

#65530 Update eslint.FlatConfig to remove string alternatives from files and ignores
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Owner Approved, Critical package, Unreviewed

#65719 Add VexTab library types
  types/vextab/index.d.ts
  types/vextab/tsconfig.json
  types/vextab/tslint.json
  types/vextab/vextab-tests.ts
Labels: New Definition

#65713 [@types/zipcodes] : Wrong type of lookupByCoords function
  types/zipcodes/index.d.ts
  types/zipcodes/zipcodes-tests.ts
Labels: Self Merge, Maintainer Approved

#65728 [facebook-pixel] Add eventID option
  types/facebook-pixel/facebook-pixel-tests.ts
  types/facebook-pixel/index.d.ts
Labels: Self Merge, Owner Approved

#65724 [@breejs/later] add types
  types/breejs__later/breejs__later-tests.ts
  types/breejs__later/index.d.ts
  types/breejs__later/tsconfig.json
  types/breejs__later/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65729 [node] add missing serialization property in ClusterSettings
  types/node/cluster.d.ts
  types/node/test/cluster.ts
  types/node/ts4.8/cluster.d.ts
  types/node/ts4.8/test/cluster.ts
  types/node/v14/cluster.d.ts
  types/node/v14/ts4.8/cluster.d.ts
  types/node/v16/cluster.d.ts
  types/node/v16/test/cluster.ts
  types/node/v16/ts4.8/cluster.d.ts
  types/node/v16/ts4.8/test/cluster.ts
  types/node/v18/cluster.d.ts
  types/node/v18/test/cluster.ts
  types/node/v18/ts4.8/cluster.d.ts
  types/node/v18/ts4.8/test/cluster.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65726 `react`: add `fetchPriority` to `LinkHTMLAttributes`
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
  types/react/v15/index.d.ts
  types/react/v16/index.d.ts
  types/react/v17/index.d.ts
Labels: Critical package, Untested Change

#65737 [react] Deprecate `React.ReactFragment` (not to be confused with `React.Fragment`)
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Untested Change

#65743 Correct Node@14 `Signer` type to be `Sign`
  types/node/v14/crypto.d.ts
  types/node/v14/test/crypto.ts
Labels: Self Merge, Maintainer Approved, Critical package

#65741 [node] Update types to v20.3.0
  types/node/buffer.d.ts
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/index.d.ts
  types/node/net.d.ts
  types/node/process.d.ts
  types/node/ts4.8/buffer.d.ts
  types/node/ts4.8/crypto.d.ts
  types/node/ts4.8/fs.d.ts
  types/node/ts4.8/net.d.ts
  types/node/ts4.8/process.d.ts
  types/node/ts4.8/tty.d.ts
  types/node/ts4.8/wasi.d.ts
  types/node/tty.d.ts
  types/node/wasi.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Untested Change

#65723 [@types/oojs & @types/oojs-ui] Add @ChlodAlejandro as owner
  types/oojs-ui/index.d.ts
  types/oojs/index.d.ts
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, Untested Change, No Other Owners, Edits Owners

#65739 Add types for fast-astar:1.0
  types/fast-astar/fast-astar-tests.ts
  types/fast-astar/index.d.ts
  types/fast-astar/tsconfig.json
  types/fast-astar/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65582 [react-scroll-to-bottom] fix: useScrollTo hooks lack option error
  types/react-scroll-to-bottom/index.d.ts
  types/react-scroll-to-bottom/react-scroll-to-bottom-tests.tsx
Labels: Self Merge, Owner Approved

#65704 react-native-snackbar-component positioning props
  types/react-native-snackbar-component/index.d.ts
  types/react-native-snackbar-component/react-native-snackbar-component-tests.tsx
Labels: Self Merge, Owner Approved, Edits Owners

#65758 es-abstract, get-intrinsic:: Update types for 5.2 WeakMap type changes
  types/es-abstract/test/GetIntrinsic.test.ts
  types/get-intrinsic/get-intrinsic-tests.ts
Labels: Popular package, Edits multiple packages

#65421 fix(react-dom): use arrow functions instead of `this: void`
  types/react-dom/server.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package, Untested Change

#65733 [@breejs/later]: add missing `isValid` method to `Schedule` interface
  types/breejs__later/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#65660 chore: added jsdoc/check-tag-names to ESLint config
  .eslintrc.cjs
  .eslintrc.json
  package.json
  tsconfig.json
  types/ember/test/debug.ts
  types/ember/v3/test/debug.ts
  types/ember__debug/ember__debug-tests.ts
  types/ember__debug/v3/ember__debug-tests.ts
  types/gulp-help-doc/gulp-help-doc-tests.ts
  types/openfin/.eslintrc.json
  types/openui5/sap.f.d.ts
  types/openui5/sap.ui.mdc.d.ts
  types/react-native/v0.71/Libraries/ActionSheetIOS/ActionSheetIOS.d.ts
  types/react-native/v0.71/Libraries/ReactNative/RootTag.d.ts
  types/react-native/v0.71/Libraries/TurboModule/RCTExport.d.ts
  types/react-reconciler/test/ReactFiberHostConfigWithNoTestSelectors.ts
  types/subset-font/subset-font-tests.ts
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package, Check Config, Too Many Owners

#65395 Update react-swipeable-views prop types with action prop
  types/react-swipeable-views/index.d.ts
  types/react-swipeable-views/react-swipeable-views-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#65759 [@breejs/later]: add second owner
  types/breejs__later/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change, Edits Owners

#65629 Types for leaflet-side-by-side
  types/leaflet-side-by-side/index.d.ts
  types/leaflet-side-by-side/leaflet-side-by-side-tests.ts
  types/leaflet-side-by-side/tsconfig.json
  types/leaflet-side-by-side/tslint.json
Labels: New Definition

#65433 Extending interface CircleMarkerOptions from MarkerOptions to allow access 'repeatMode' option
  types/leaflet-draw/index.d.ts
  types/leaflet-draw/leaflet-draw-tests.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#65574 Docs(README.ja.md): add link to README.it.md
  README.ja.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#65749 [node] add missing cwd, windowsHide property in ClusterSettings
  types/node/cluster.d.ts
  types/node/test/cluster.ts
  types/node/ts4.8/cluster.d.ts
  types/node/ts4.8/test/cluster.ts
  types/node/v14/cluster.d.ts
  types/node/v14/ts4.8/cluster.d.ts
  types/node/v16/cluster.d.ts
  types/node/v16/test/cluster.ts
  types/node/v16/ts4.8/cluster.d.ts
  types/node/v16/ts4.8/test/cluster.ts
  types/node/v18/cluster.d.ts
  types/node/v18/test/cluster.ts
  types/node/v18/ts4.8/cluster.d.ts
  types/node/v18/ts4.8/test/cluster.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#65760 Expand ESLint.Plugin for new-style configs
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Self Merge, Owner Approved, Critical package

#65639 [react]: update react v17 types to use Omit
  types/react/v17/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#65769 @ember/modifier: cover missing Ember 3.x/4.x APIs
  types/ember__modifier/ember__modifier-tests.ts
  types/ember__modifier/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65625 Sendsay api
  types/sendsay-api/index.d.ts
  types/sendsay-api/sendsay-api-tests.ts
  types/sendsay-api/tsconfig.json
  types/sendsay-api/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65746 [is-firefox] Add types
  types/is-firefox/index.d.ts
  types/is-firefox/is-firefox-tests.ts
  types/is-firefox/tsconfig.json
  types/is-firefox/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65592 [imap-simple] expose imap field type
  types/imap-simple/imap-simple-tests.ts
  types/imap-simple/index.d.ts
Labels: Self Merge, Maintainer Approved

#65768 Add clientMeta to aws-lambda triggers
  types/aws-lambda/test/cognito-tests.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/create-auth-challenge.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/define-auth-challenge.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/post-authentication.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/pre-token-generation.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/verify-auth-challenge-response.d.ts
Labels: Self Merge, Owner Approved, Critical package

#65715 cls-hooked: Add strong typing for namespace key/values
  types/cls-hooked/cls-hooked-tests.ts
  types/cls-hooked/index.d.ts
  types/cls-hooked/tslint.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#65761 Types for Leaflet.sync
  types/leaflet.sync/index.d.ts
  types/leaflet.sync/leaflet.sync-tests.ts
  types/leaflet.sync/tsconfig.json
  types/leaflet.sync/tslint.json
Labels: New Definition

#65781 Fix nightly breaks because of jsdoc tag name rule
  .eslintrc.cjs
  types/ckeditor4/core/tools.d.ts
  types/vscode/index.d.ts
Labels: Popular package, Edits Infrastructure, Edits multiple packages, Untested Change

#65607 [@types/aws-lambda] Fixing SNSMessage field names to match the AWS developer guide
  types/aws-lambda/aws-lambda-tests.ts
  types/aws-lambda/common/api-gateway.d.ts
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/alb-tests.ts
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/test/autoscaling-tests.ts
  types/aws-lambda/test/cdk-custom-resource-tests.ts
  types/aws-lambda/test/cloudformation-tests.ts
  types/aws-lambda/test/cloudwatch-tests.ts
  types/aws-lambda/test/codebuild-tests.ts
  types/aws-lambda/test/codecommit-tests.ts
  types/aws-lambda/test/codepipeline-tests.ts
  types/aws-lambda/test/cognito-tests.ts
  types/aws-lambda/test/connect-contact-flow-tests.ts
  types/aws-lambda/test/dynamodb-tests.ts
  types/aws-lambda/test/eventbridge-tests.ts
  types/aws-lambda/test/iot-tests.ts
  types/aws-lambda/test/kinesis-tests.ts
  types/aws-lambda/test/lex-tests.ts
  types/aws-lambda/test/lex-v2-tests.ts
  types/aws-lambda/test/s3-tests.ts
  types/aws-lambda/test/secretsmanager-tests.ts
  types/aws-lambda/test/ses-tests.ts
  types/aws-lambda/test/sns-tests.ts
  types/aws-lambda/test/sqs-tests.ts
  types/aws-lambda/trigger/alb.d.ts
  types/aws-lambda/trigger/api-gateway-proxy.d.ts
  types/aws-lambda/trigger/autoscaling.d.ts
  types/aws-lambda/trigger/cloudformation-custom-resource.d.ts
  types/aws-lambda/trigger/cloudfront-request.d.ts
  types/aws-lambda/trigger/cloudfront-response.d.ts
  types/aws-lambda/trigger/cloudwatch-logs.d.ts
  types/aws-lambda/trigger/codebuild-cloudwatch-state.d.ts
  types/aws-lambda/trigger/codecommit.d.ts
  types/aws-lambda/trigger/codepipeline-cloudwatch-action.d.ts
  types/aws-lambda/trigger/codepipeline-cloudwatch-pipeline.d.ts
  types/aws-lambda/trigger/codepipeline-cloudwatch-stage.d.ts
  types/aws-lambda/trigger/codepipeline-cloudwatch.d.ts
  types/aws-lambda/trigger/codepipeline.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/_common.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/custom-email-sender.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/custom-message.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/custom-sms-sender.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/index.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/post-authentication.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/post-confirmation.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/pre-signup.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/pre-token-generation.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/user-migration.d.ts
  types/aws-lambda/trigger/connect-contact-flow.d.ts
  types/aws-lambda/trigger/dynamodb-stream.d.ts
  types/aws-lambda/trigger/iot.d.ts
  types/aws-lambda/trigger/kinesis-firehose-transformation.d.ts
  types/aws-lambda/trigger/kinesis-stream.d.ts
  types/aws-lambda/trigger/lex-v2.d.ts
  types/aws-lambda/trigger/lex.d.ts
  types/aws-lambda/trigger/s3-batch.d.ts
  types/aws-lambda/trigger/s3.d.ts
  types/aws-lambda/trigger/ses.d.ts
  types/aws-lambda/trigger/sns.d.ts
Labels: Self Merge, Owner Approved, Critical package

#65623 [memory-cache] Fix del sig, return boolean instead of void
  types/memory-cache/index.d.ts
  types/memory-cache/memory-cache-tests.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Maintainer Approved

#65785 default-gateway: upgrade to v7.2
  types/default-gateway/default-gateway-tests.ts
  types/default-gateway/index.d.ts
Labels: Other Approved, Self Merge, Edits Owners

#65683 Update cytoscape core style API and make collections iterable
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
  types/cytoscape/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved

#65765 Run prettier on the k6 types as suggested in the common mistakes
  types/k6/crypto.d.ts
  types/k6/data.d.ts
  types/k6/encoding.d.ts
  types/k6/experimental/browser/element_handle.d.ts
  types/k6/experimental/browser/frame.d.ts
  types/k6/experimental/browser/index.d.ts
  types/k6/experimental/browser/js_handle.d.ts
  types/k6/experimental/browser/keyboard.d.ts
  types/k6/experimental/browser/locator.d.ts
  types/k6/experimental/browser/mouse.d.ts
  types/k6/experimental/browser/page.d.ts
  types/k6/experimental/browser/request.d.ts
  types/k6/experimental/browser/response.d.ts
  types/k6/experimental/browser/touchscreen.d.ts
  types/k6/experimental/browser/worker.d.ts
  types/k6/experimental/tracing.d.ts
  types/k6/experimental/webcrypto.d.ts
  types/k6/experimental/websockets.d.ts
  types/k6/http.d.ts
  types/k6/k6-tests.ts
  types/k6/options.d.ts
  types/k6/test/browser.ts
  types/k6/test/data.ts
  types/k6/test/http.ts
  types/k6/test/index.ts
  types/k6/test/options.ts
  types/k6/test/redis.ts
  types/k6/test/tracing.ts
  types/k6/test/webcrypto.ts
  types/k6/test/websockets.ts
  types/k6/test/ws.ts
  types/k6/ws.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Huge Change

#65777 [Mixpanel] Update types of register methods
  types/mixpanel-browser/index.d.ts
  types/mixpanel-browser/mixpanel-browser-tests.ts
  types/mixpanel/index.d.ts
  types/mixpanel/mixpanel-tests.ts
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved

#65790 Jasmine - Make createSpyObj work when toString is overridden
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/jasmine/v3/index.d.ts
  types/jasmine/v3/jasmine-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#65796 [jsonld] Use different name for local type and variable
  types/jsonld/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#65795 [relay-runtime] Remove unneeded interface
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65786 [npm-whoami] Add types
  types/npm-whoami/index.d.ts
  types/npm-whoami/npm-whoami-tests.ts
  types/npm-whoami/tsconfig.json
  types/npm-whoami/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65614 Fix convert() function signatures on Carbone (carbone.io) types
  types/carbone/carbone-tests.ts
  types/carbone/index.d.ts
Labels: Self Merge, Maintainer Approved

#65788 Add types definitions for xk6-sql
  types/xk6-sql-browser/index.d.ts
  types/xk6-sql-browser/tsconfig.json
  types/xk6-sql-browser/tslint.json
  types/xk6-sql-browser/xk6-sql-browser-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#65764 k6 v0.45.0 updates
  types/k6/execution.d.ts
  types/k6/experimental/grpc.d.ts
  types/k6/index.d.ts
  types/k6/options.d.ts
  types/k6/test/execution.ts
  types/k6/test/experimental/grpc.ts
  types/k6/test/options.ts
  types/k6/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#65734 [react] react@next is now react@canary
  types/react-dom/canary.d.ts
  types/react-dom/experimental.d.ts
  types/react-dom/package.json
  types/react-dom/test/canary-tests.tsx
  types/react-dom/tsconfig.json
  types/react-is/canary.d.ts
  types/react-is/test/canary-tests.tsx
  types/react-is/tsconfig.json
  types/react/OTHER_FILES.txt
  types/react/canary.d.ts
  types/react/experimental.d.ts
  types/react/package.json
  types/react/test/canary.tsx
  types/react/ts5.0/OTHER_FILES.txt
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/canary.tsx
  types/react/ts5.0/tsconfig.json
  types/react/tsconfig.json
Labels: Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, Critical package, Check Config

#65824 [netmask]: Fix regressions in 2.0.0 typings
  types/netmask/index.d.ts
  types/netmask/netmask-tests.ts
Labels: Self Merge, Owner Approved

#65807 Jasmine: Remove Enzam from maintainers list.
  types/jasmine/index.d.ts
  types/jasmine/v3/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package, Untested Change, Edits Owners

#65798 Fix prettier command to not expand in shell
  README.it.md
  README.ja.md
  README.md
  README.pt.md
  README.zh-Hans.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#65815 Deprecate @types/node-emoji as of node-emoji@2.1.0
  notNeededPackages.json
  types/node-emoji/index.d.ts
  types/node-emoji/node-emoji-tests.ts
  types/node-emoji/tsconfig.json
  types/node-emoji/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#65680 Added @types/hot-formula-parser
  types/hot-formula-parser/hot-formula-parser-tests.ts
  types/hot-formula-parser/index.d.mts
  types/hot-formula-parser/index.d.ts
  types/hot-formula-parser/package.json
  types/hot-formula-parser/tsconfig.json
  types/hot-formula-parser/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#65820 feat: Add types for kebabcase-keys
  types/kebabcase-keys/index.d.ts
  types/kebabcase-keys/kebabcase-keys-tests.ts
  types/kebabcase-keys/tsconfig.json
  types/kebabcase-keys/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65833 Added PSE types
  types/mercadopago-sdk-js/core.d.ts
  types/mercadopago-sdk-js/index.d.ts
  types/mercadopago-sdk-js/mercadopago-sdk-js-tests.ts
  types/mercadopago-sdk-js/modules/bricks.d.ts
  types/mercadopago-sdk-js/modules/cardform.d.ts
  types/mercadopago-sdk-js/modules/fields.d.ts
  types/mercadopago-sdk-js/shared.d.ts
Labels: Other Approved, Self Merge

#65805 [@types/aws-param-store] Add type definitions for put methods
  types/aws-param-store/aws-param-store-tests.ts
  types/aws-param-store/index.d.ts
Labels: Other Approved, Self Merge

#65730 [minimasonry] Initial types for minimasonry
  types/minimasonry/index.d.ts
  types/minimasonry/minimasonry-tests.ts
  types/minimasonry/tsconfig.json
  types/minimasonry/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65811 Added definitions to 1.24.0
  types/consumer-data-standards/admin/index.d.ts
  types/consumer-data-standards/banking/index.d.ts
  types/consumer-data-standards/dcr/index.d.ts
  types/consumer-data-standards/energy/index.d.ts
  types/consumer-data-standards/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#65834 stripe-v3: Add disableLink
  types/stripe-v3/index.d.ts
  types/stripe-v3/stripe-v3-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#65843 `@types/shippo` - add missing `is_complete` property to `Address`
  types/shippo/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#65670 AlpineJS: Fix types for custom directives
  types/alpinejs/alpinejs-tests.ts
  types/alpinejs/index.d.ts
Labels: Self Merge, Maintainer Approved

#65842 docs(readme): improving spanish translations
  README.es.md
Labels: Other Approved, Self Merge, Edits Infrastructure, Maintainer Approved

#65804 @types/snowflake-sdk: add promisified Connection.isValidAsync()
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65570 [nightwatchjs] Final type fixes for v2.x
  types/nightwatch/expect.d.ts
  types/nightwatch/globals.d.ts
  types/nightwatch/index.d.ts
  types/nightwatch/test/nightwatch-tests.ts
  types/nightwatch/test/testActions.ts
  types/nightwatch/test/testClientCommands.ts
  types/nightwatch/test/testElementCommands.ts
  types/nightwatch/test/testExpect.ts
  types/nightwatch/test/testGlobalElementApi.ts
  types/nightwatch/test/testProgrammaticApi.ts
  types/nightwatch/test/testWebdriverProtocolCommands.ts
  types/nightwatch/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved

#65672 [@types/mixpanel-browser] Add track_pageview types
  types/mixpanel-browser/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#65799 [serve-static] Missing `err` parameter added to `next` handler
  types/serve-static/index.d.ts
  types/serve-static/serve-static-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#65841 [mercadopago-sdk-js] Improve params and returns from constructors and submits
  types/mercadopago-sdk-js/mercadopago-sdk-js-tests.ts
  types/mercadopago-sdk-js/modules/bricks.d.ts
Labels: Other Approved, Self Merge

#65837 [mercadopago-sdk-js] Added new value props for Wallet Brick (credits and smart)
  types/mercadopago-sdk-js/mercadopago-sdk-js-tests.ts
  types/mercadopago-sdk-js/modules/bricks.d.ts
Labels: Other Approved, Self Merge

#65620 style: fix react ExoticComponent interface style
  types/react/ts5.0/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Critical package, Untested Change

#65848 docs(readme.es): translating non-translated content
  README.es.md
Labels: Other Approved, Self Merge, Edits Infrastructure, Maintainer Approved

#65689 [@types/chrome] Add SidePanel API Support
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Maintainer Approved

#65853 express-mysql-session: Update to 3.0
  types/express-mysql-session/express-mysql-session-tests.ts
  types/express-mysql-session/index.d.ts
  types/express-mysql-session/package.json
Labels: Self Merge, Owner Approved

#65845 [serverless] Add serviceDir and configurationFilename properties
  types/serverless/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65866 Update node-cron index.d.ts file
  types/node-cron/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#65868 [mvdan-sh] Add typings and tests for Parser's interactive methods
  types/mvdan-sh/index.d.ts
  types/mvdan-sh/mvdan-sh-tests.ts
Labels: Self Merge, Owner Approved

#65846 feat: support for the exclude option for kebabcase-keys
  types/kebabcase-keys/index.d.ts
  types/kebabcase-keys/kebabcase-keys-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#65864 [convert-units] Add missing unit 'yd', fix typo 'min/km' => 'min/mi'
  types/convert-units/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#65751 Create a new release - version 2.34, for microsoft-graph-types
  types/microsoft-graph/index.d.ts
  types/microsoft-graph/microsoft-graph-tests.ts
Labels: Unmerged, Self Merge, Author is Owner, Owner Approved

#65878 web-app-manifest: inline type of orientation
  types/web-app-manifest/index.d.ts
Labels: Owner Approved, Untested Change

#65879 Update dom-webcodecs for TS 5.2
  types/dom-mediacapture-transform/index.d.ts
  types/dom-webcodecs/index.d.ts
  types/dom-webcodecs/webcodecs.generated.d.ts
Labels: Popular package, Edits multiple packages, Untested Change

#65877 Add URLSearchParams.size
  types/node/v14/ts4.8/url.d.ts
  types/node/v14/url.d.ts
  types/node/v16/ts4.8/url.d.ts
  types/node/v16/url.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#65860 node: add `node:test/reporters` module
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#65884 `humps` - fix distributed conditional type
  types/humps/index.d.ts
  types/humps/test/humps-tests.cjs.ts
Labels: Popular package, Self Merge, Owner Approved

#65687 Gulp - Fix - add `events` property `options` paramter of `gulp.watch` method
  types/gulp/index.d.ts
  types/gulp/test/index.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#65797 @types/chrome: add promisified chrome.runtime.requestUpdateCheck()
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#65889 [remark-oembed] Add types
  types/remark-oembed/index.d.ts
  types/remark-oembed/package.json
  types/remark-oembed/remark-oembed-tests.ts
  types/remark-oembed/tsconfig.json
  types/remark-oembed/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65867 update @rdfjs/formats-common to v3 (ESM)
  types/rdfjs__express-handler/index.d.ts
  types/rdfjs__fetch-lite/index.d.ts
  types/rdfjs__fetch-lite/rdfjs__fetch-lite-tests.ts
  types/rdfjs__formats-common/index.d.ts
  types/rdfjs__formats-common/package.json
  types/rdfjs__formats-common/rdfjs__formats-common-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Edits multiple packages, Maintainer Approved, Check Config

#65801 react-native-snackbar-component styles properties
  types/react-native-snackbar-component/index.d.ts
  types/react-native-snackbar-component/react-native-snackbar-component-tests.tsx
Labels: Self Merge, Author is Owner, Owner Approved

#65900 netmask: constructor accepts string+number
  types/netmask/index.d.ts
  types/netmask/netmask-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#65909 Fix broken JS Doc tag in gulp
  types/gulp/index.d.ts
Labels: Popular package, Untested Change

#65908 Fix broken JSDoc tag in microsoft-graph
  types/microsoft-graph/index.d.ts
Labels: Untested Change

#65896 Add typings for jiff
  types/jiff/index.d.ts
  types/jiff/jiff-tests.ts
  types/jiff/tsconfig.json
  types/jiff/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65897 Add typings for lodash-match-pattern
  types/lodash-match-pattern/index.d.ts
  types/lodash-match-pattern/lodash-match-pattern-tests.ts
  types/lodash-match-pattern/tsconfig.json
  types/lodash-match-pattern/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65882 Restore @checkReturnValue annotations in Jasmine
  .eslintrc.cjs
  types/jasmine/index.d.ts
  types/jasmine/v3/index.d.ts
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved, Critical package, Untested Change

#65907 fix(rdfjs/term-set): relative import without extension
  types/rdfjs__term-set/Factory.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Untested Change

#65901 fix(edfjs/environment): missing factories
  types/rdfjs__environment/DataFactory.d.ts
  types/rdfjs__environment/DatasetFactory.d.ts
  types/rdfjs__environment/FormatsFactory.d.ts
  types/rdfjs__environment/NamespaceFactory.d.ts
  types/rdfjs__environment/TermMapSetFactory.d.ts
  types/rdfjs__environment/rdfjs__environment-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65903 fix(rdfjs/dataset): module resolution problem with node16/nodenext
  types/rdfjs__dataset/Factory.d.ts
  types/rdfjs__dataset/index.d.ts
  types/rdfjs__dataset/rdfjs__dataset-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65904 fix(rdfjs/data-model): module resolution problem with node16/nodenext
  types/rdfjs__data-model/Factory.d.ts
  types/rdfjs__data-model/index.d.ts
  types/rdfjs__data-model/rdfjs__data-model-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#65905 fix(rdfjs/score): module resolution problem with node16/nodenext
  types/rdfjs__score/Factory.d.ts
  types/rdfjs__score/combine.d.ts
  types/rdfjs__score/concat.d.ts
  types/rdfjs__score/count.d.ts
  types/rdfjs__score/distinct.d.ts
  types/rdfjs__score/exists.d.ts
  types/rdfjs__score/fallback.d.ts
  types/rdfjs__score/fixed.d.ts
  types/rdfjs__score/index.d.ts
  types/rdfjs__score/language.d.ts
  types/rdfjs__score/pageRank.d.ts
  types/rdfjs__score/pathDepth.d.ts
  types/rdfjs__score/prioritized.d.ts
  types/rdfjs__score/product.d.ts
  types/rdfjs__score/scale.d.ts
  types/rdfjs__score/sort.d.ts
  types/rdfjs__score/sortObjects.d.ts
  types/rdfjs__score/sum.d.ts
  types/rdfjs__score/type.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Untested Change

#65906 fix(rdfjs/term-map): relative import without extension
  types/rdfjs__term-map/Factory.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Untested Change

#65818 added shutterColor, frameQuality & onFrameChange props type-defs
  types/react-native-video/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#65816 Make optional cytoscape-fcose layout constraints optional
  types/cytoscape-fcose/cytoscape-fcose-tests.ts
  types/cytoscape-fcose/index.d.ts
Labels: Self Merge, Owner Approved

#65883 nunjucks: fix ILoader.getSource
  types/nunjucks/index.d.ts
  types/nunjucks/nunjucks-tests.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#65914 [ramda] Bump types-ramda package to latest
  types/ramda/package.json
  types/ramda/test/all-tests.ts
  types/ramda/test/concat-tests.ts
  types/ramda/test/converge-tests.ts
  types/ramda/test/divide-tests.ts
  types/ramda/test/map-tests.ts
  types/ramda/test/mathMod-tests.ts
  types/ramda/test/modulo-tests.ts
  types/ramda/test/of-tests.ts
  types/ramda/test/on-tests.ts
  types/ramda/test/over-tests.ts
  types/ramda/test/pipe-tests.ts
  types/ramda/test/set-tests.ts
  types/ramda/test/subtract-tests.ts
  types/ramda/test/transduce-tests.ts
  types/ramda/test/unless-tests.ts
  types/ramda/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved
