Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2023-08, with the labels that each got.

#66242 Fix function name typo on tabulator-tables - refreshFilters to refreshFilter
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#66201 [sinon] static mock can get a string as name
  types/sinon/index.d.ts
  types/sinon/sinon-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66169 [crypto-ld] fixed return types of LDKeypair.signer() and LDKeypair.verifier() methods
  types/crypto-ld/crypto-ld-tests.ts
  types/crypto-ld/index.d.ts
Labels: Other Approved, Self Merge

#66230 fix(pubnub)/missing dedupeOnSubscribe configuration
  types/pubnub/index.d.ts
  types/pubnub/pubnub-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66220 [opossum] Add enableSnapshots option to CircuitBreaker.Options
  types/opossum/index.d.ts
  types/opossum/opossum-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#66211 [protobuf-fieldmask] Add new type definitions
  types/protobuf-fieldmask/index.d.ts
  types/protobuf-fieldmask/protobuf-fieldmask-tests.ts
  types/protobuf-fieldmask/tsconfig.json
  types/protobuf-fieldmask/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66237 Add types for cypress-cdp
  types/cypress-cdp/cypress-cdp-tests.ts
  types/cypress-cdp/index.d.ts
  types/cypress-cdp/package.json
  types/cypress-cdp/tsconfig.json
  types/cypress-cdp/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66251 [docker-modem] Fix stream types
  types/docker-modem/docker-modem-tests.ts
  types/docker-modem/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66221 Add @types/simple-get
  types/simple-get/index.d.ts
  types/simple-get/simple-get-tests.ts
  types/simple-get/tsconfig.json
  types/simple-get/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66184 Add type definitions for split-file
  types/split-file/index.d.ts
  types/split-file/split-file-tests.ts
  types/split-file/tsconfig.json
  types/split-file/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66164 feat: remove cron - not needed as of 2.4.0
  notNeededPackages.json
  types/cron/.eslintrc.json
  types/cron/cron-tests.ts
  types/cron/index.d.ts
  types/cron/tsconfig.json
  types/cron/tslint.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved, Check Config

#66249 Fix/revert lint tabulator - revert linter
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#66259 [github-label-sync] Add delete property to LabelInfo
  types/github-label-sync/github-label-sync-tests.ts
  types/github-label-sync/index.d.ts
Labels: Self Merge, Owner Approved

#66256 chore(node): remove simon schick as an author
  types/node/index.d.ts
Labels: Author is Owner, Critical package, Untested Change, Edits Owners

#65949 @types/chrome: Add world property for content_scripts
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Maintainer Approved

#66262 Sync Chinese Translation
  README.zh-Hans.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66111 Refactor/k6 browser one file
  types/k6/experimental/browser.d.ts
  types/k6/experimental/browser/element_handle.d.ts
  types/k6/experimental/browser/frame.d.ts
  types/k6/experimental/browser/index.d.ts
  types/k6/experimental/browser/js_handle.d.ts
  types/k6/experimental/browser/keyboard.d.ts
  types/k6/experimental/browser/locator.d.ts
  types/k6/experimental/browser/mouse.d.ts
  types/k6/experimental/browser/page.d.ts
  types/k6/experimental/browser/request.d.ts
  types/k6/experimental/browser/response.d.ts
  types/k6/experimental/browser/touchscreen.d.ts
  types/k6/experimental/browser/worker.d.ts
  types/k6/test/browser.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Huge Change

#66266 mithril: Added SKIP property to the Route interface
  types/mithril/index.d.ts
  types/mithril/test/test-route.ts
Labels: Self Merge, Owner Approved

#66275 Update `@types/vscode` for VS Code 1.81.0 Release
  types/vscode/index.d.ts
Labels: Popular package, Untested Change

#66274 Enable ban-ts-comment eslint rule so we can conditionally allow ts-ignore
  .eslintrc.cjs
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66257 [node] Adds test:enqueue, test:dequeue and test:watch:drained to test reporter events
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
  types/node/v18/test.d.ts
  types/node/v18/test/test.ts
  types/node/v18/ts4.8/test.d.ts
  types/node/v18/ts4.8/test/test.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66272 feat: add more types of input and output and fix userId for sm-crypto.
  types/sm-crypto/index.d.ts
  types/sm-crypto/sm-crypto-tests.ts
Labels: Self Merge, Owner Approved

#66277 [atlassian-connect-js] Fix some types and other improvements
  types/atlassian-connect-js/atlassian-connect-js-tests.ts
  types/atlassian-connect-js/index.d.ts
Labels: Self Merge, Owner Approved

#65826 [eslint] Adding metadata to Plugin/Processor/ParserModule
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66287 Add `@types/treeverse`
  types/treeverse/index.d.ts
  types/treeverse/treeverse-tests.ts
  types/treeverse/tsconfig.json
  types/treeverse/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66285 [numjs] Fix subtract function return type
  types/numjs/index.d.ts
  types/numjs/numjs-tests.ts
Labels: Other Approved, Self Merge

#66048 update types for fancade-editor beta
  types/fancade-editor/fancade-editor-tests.ts
  types/fancade-editor/index.d.ts
Labels: Self Merge, Maintainer Approved, Edits Owners

#66281 feat: add `flags` type to `ember-feature-flags` Features service
  types/ember-feature-flags/ember-feature-flags-tests.ts
  types/ember-feature-flags/index.d.ts
Labels: Other Approved, Self Merge

#66246 feat(bip38): encrypt decrypt async supports for v3.1
  types/bip38/bip38-tests.ts
  types/bip38/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#66286 Added priceAmount to the Product
  types/facebook-instant-games/facebook-instant-games-tests.ts
  types/facebook-instant-games/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner

#66064 [node:test] add setup and watch for RunOptions
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
  types/node/v18/test.d.ts
  types/node/v18/test/test.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package

#66295 [node-telegram-bot-api] Fixed declaration for unpinChatMessage method
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Owner Approved

#66289 add `@types/lynx`
  types/lynx/index.d.ts
  types/lynx/lynx-tests.ts
  types/lynx/tsconfig.json
  types/lynx/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66139 Remove 7jpsan (self) from owners
  types/gremlin/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners, Edits Owners

#66254 feat(cloudflare/index.d.ts): add DnsRecords.browse options and response types
  types/cloudflare/cloudflare-tests.ts
  types/cloudflare/index.d.ts
Labels: Self Merge, Owner Approved

#66300 Moo! Add RegExp[] to Rules' value options.
  types/moo/index.d.ts
  types/moo/moo-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66172 update(jest-image-snapshot): 6.2 update
  types/jest-image-snapshot/index.d.ts
  types/jest-image-snapshot/jest-image-snapshot-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66298 fix(treeverse): correct `leave` definition
  types/treeverse/index.d.ts
  types/treeverse/treeverse-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#66306 Add types for `react-curved-text`
  types/react-curved-text/index.d.ts
  types/react-curved-text/react-curved-text-tests.tsx
  types/react-curved-text/tsconfig.json
  types/react-curved-text/tslint.json
Labels: New Definition

#66302 Type declarations for bicubic-interpolate
  types/bicubic-interpolate/bicubic-interpolate-tests.ts
  types/bicubic-interpolate/index.d.ts
  types/bicubic-interpolate/tsconfig.json
  types/bicubic-interpolate/tslint.json
Labels: New Definition

#66261 [react-native-charts-wrapper] Add missing Icon property to LineValue
  types/react-native-charts-wrapper/index.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Untested Change

#66296 update(validator.js): version 3.11 updates
  types/validator/es/lib/isISO6346.d.ts
  types/validator/es/lib/isMailtoURI.d.ts
  types/validator/index.d.ts
  types/validator/lib/isISO6346.d.ts
  types/validator/lib/isMailtoURI.d.ts
  types/validator/validator-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#66303 Update markdown-it version to 13.1
  types/markdown-it/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#66307 [mercadopago-sdk-js] Add update method for Card Payment Brick and Payment Brick
  types/mercadopago-sdk-js/mercadopago-sdk-js-tests.ts
  types/mercadopago-sdk-js/modules/bricks.d.ts
Labels: Other Approved, Self Merge

#66301 [@mapbox/geo-viewport]: Update to v0.5.0
  types/mapbox__geo-viewport/index.d.ts
  types/mapbox__geo-viewport/mapbox__geo-viewport-tests.ts
Labels: Other Approved, Self Merge

#66106 [mongoose-delete] Update supported mongoose version to add v7
  types/mongoose-delete/index.d.ts
  types/mongoose-delete/mongoose-delete-tests.ts
  types/mongoose-delete/package.json
Labels: Self Merge, Maintainer Approved

#66096 Add collectDeviceData and deprecate frame props in 3DS options
  types/braintree-web/index.d.ts
  types/braintree-web/modules/client.d.ts
  types/braintree-web/modules/data-collector.d.ts
  types/braintree-web/modules/google-payment.d.ts
  types/braintree-web/modules/hosted-fields.d.ts
  types/braintree-web/modules/paypal-checkout.d.ts
  types/braintree-web/modules/three-d-secure.d.ts
  types/braintree-web/modules/vault-manager.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Unreviewed

#66087 update(intl-tel-input): `CountryData` amended
  types/intl-tel-input/index.d.ts
  types/intl-tel-input/test/intl-tel-input-global.ts
Labels: Author is Owner, Unreviewed

#65972 Correct fetchPriority naming
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
  types/react/v15/index.d.ts
  types/react/v16/index.d.ts
  types/react/v17/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package, Untested Change

#66170 [ldapjs] fix SearchEntryObject and some others
  types/ldapjs/index.d.ts
  types/ldapjs/ldapjs-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66142 Mapbox-GL: update Marker with missing occludedOpacity option
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#65982 MapboxGeocoder - add missing options/methods
  types/mapbox__mapbox-gl-geocoder/index.d.ts
  types/mapbox__mapbox-gl-geocoder/mapbox__mapbox-gl-geocoder-tests.ts
Labels: Self Merge, Maintainer Approved

#66308 Add DNS type for Node perfhooks
  types/node/perf_hooks.d.ts
  types/node/v16/perf_hooks.d.ts
  types/node/v18/perf_hooks.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#66313 Add minexponent to plotly chart types
  types/plotly.js/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66193 docs: add doc french
  README.fr.md
  README.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#66327 Update gtag.js for missing some consent states
  types/gtag.js/gtag.js-tests.ts
  types/gtag.js/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66325 fix(object-hash): add missing hash option algorithm allowed values
  types/object-hash/index.d.ts
  types/object-hash/object-hash-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66310 Added langdetect types definitions
  types/langdetect/index.d.ts
  types/langdetect/langdetect-tests.ts
  types/langdetect/tsconfig.json
  types/langdetect/tslint.json
Labels: New Definition

#66328 Add types for json-mask
  types/json-mask/index.d.ts
  types/json-mask/json-mask-tests.ts
  types/json-mask/tsconfig.json
  types/json-mask/tslint.json
Labels: New Definition

#66316 Add type definitions for identity-obj-proxy
  types/identity-obj-proxy/identity-obj-proxy-tests.ts
  types/identity-obj-proxy/index.d.ts
  types/identity-obj-proxy/tsconfig.json
  types/identity-obj-proxy/tslint.json
Labels: New Definition

#66304 React: remove crossOrigin from Input, factor out definition
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
  types/react/v15/index.d.ts
  types/react/v16/index.d.ts
  types/react/v17/index.d.ts
Labels: Owner Approved, Critical package, Untested Change

#66309 feat(cacache): update to v17
  types/cacache/index.d.ts
Labels: Owner Approved, Untested Change

#66305 Added type definition for randomSeed
  types/k6/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#66297 chore(lodash): fix typo
  types/lodash/common/string.d.ts
Labels: Critical package, Untested Change

#66195 Add wasTerminated for request objects
  types/akamai-edgeworkers/index.d.ts
  types/akamai-edgeworkers/test/akamai-edgeworkers-global.test.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66315 Update Braintree types
  types/braintree-web-drop-in/index.d.ts
  types/braintree-web-drop-in/test/braintree-web-drop-in-global.test.ts
  types/braintree-web/american-express.d.ts
  types/braintree-web/apple-pay.d.ts
  types/braintree-web/client.d.ts
  types/braintree-web/core.d.ts
  types/braintree-web/data-collector.d.ts
  types/braintree-web/google-payment.d.ts
  types/braintree-web/hosted-fields.d.ts
  types/braintree-web/index.d.ts
  types/braintree-web/local-payment.d.ts
  types/braintree-web/paypal-checkout.d.ts
  types/braintree-web/paypal.d.ts
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
  types/braintree-web/three-d-secure.d.ts
  types/braintree-web/unionpay.d.ts
  types/braintree-web/us-bank-account.d.ts
  types/braintree-web/vault-manager.d.ts
  types/braintree-web/venmo.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Edits Owners

#66335 [snuownd] Add types for snuownd
  types/snuownd/index.d.ts
  types/snuownd/snuownd-tests.ts
  types/snuownd/tsconfig.json
  types/snuownd/tslint.json
Labels: New Definition

#66263 [google.accounts] update params for TokenClientConfig and CodeClientConfig in oauth2
  types/google.accounts/google.accounts-tests.ts
  types/google.accounts/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66332 [formidable] Add createDirsFromUploads option, fix type for Fields interface and Files interface
  types/formidable/formidable-tests.ts
  types/formidable/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#66344 Fix braintree-web --> adjust type in verifyCard params
  types/braintree-web/test/node.ts
  types/braintree-web/test/web.ts
  types/braintree-web/three-d-secure.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66340 @types/k6 Fix runtime error when grcp Stream experimental
  types/k6/experimental/grpc.d.ts
  types/k6/test/experimental/grpc.ts
Labels: Popular package, Self Merge, Owner Approved

#66329 [tampermonkey] add `options_or_accessKey` to `GM_registerMenuCommand`
  types/tampermonkey/index.d.ts
  types/tampermonkey/tampermonkey-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66282 [node] adds "type" to test runner event details
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
  types/node/v18/test.d.ts
  types/node/v18/test/test.ts
  types/node/v18/ts4.8/test.d.ts
  types/node/v18/ts4.8/test/test.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#66360 [aws-sdk2-types] ran dprint fmt
  types/aws-sdk2-types/aws-sdk2-types-tests.ts
  types/aws-sdk2-types/clients/dynamodb.d.ts
  types/aws-sdk2-types/clients/rdsdataservice.d.ts
  types/aws-sdk2-types/clients/s3.d.ts
  types/aws-sdk2-types/clients/ses.d.ts
  types/aws-sdk2-types/clients/sqs.d.ts
  types/aws-sdk2-types/clients/ssm.d.ts
  types/aws-sdk2-types/index.d.ts
  types/aws-sdk2-types/lib/config-base.d.ts
  types/aws-sdk2-types/lib/config.d.ts
  types/aws-sdk2-types/lib/config_service_placeholders.d.ts
  types/aws-sdk2-types/lib/config_use_dualstack.d.ts
  types/aws-sdk2-types/lib/core.d.ts
  types/aws-sdk2-types/lib/credentials.d.ts
  types/aws-sdk2-types/lib/credentials/credential_provider_chain.d.ts
  types/aws-sdk2-types/lib/credentials/ec2_metadata_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/ecs_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/environment_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/file_system_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/process_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/remote_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/saml_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/shared_ini_file_credentials.d.ts
  types/aws-sdk2-types/lib/credentials/token_file_web_identity_credentials.d.ts
  types/aws-sdk2-types/lib/dynamodb/converter.d.ts
  types/aws-sdk2-types/lib/dynamodb/document_client.d.ts
  types/aws-sdk2-types/lib/endpoint.d.ts
  types/aws-sdk2-types/lib/error.d.ts
  types/aws-sdk2-types/lib/event-stream/event-stream.d.ts
  types/aws-sdk2-types/lib/event_listeners.d.ts
  types/aws-sdk2-types/lib/http_request.d.ts
  types/aws-sdk2-types/lib/http_response.d.ts
  types/aws-sdk2-types/lib/metadata_service.d.ts
  types/aws-sdk2-types/lib/request.d.ts
  types/aws-sdk2-types/lib/response.d.ts
  types/aws-sdk2-types/lib/s3/managed_upload.d.ts
  types/aws-sdk2-types/lib/s3/presigned_post.d.ts
  types/aws-sdk2-types/lib/service.d.ts
  types/aws-sdk2-types/lib/services/dynamodb.d.ts
  types/aws-sdk2-types/lib/services/s3.d.ts
  types/aws-sdk2-types/lib/shared-ini/ini-loader.d.ts
  types/aws-sdk2-types/lib/token.d.ts
  types/aws-sdk2-types/lib/token/sso_token_provider.d.ts
  types/aws-sdk2-types/lib/token/static_token_provider.d.ts
  types/aws-sdk2-types/lib/token/token_provider_chain.d.ts
Labels: Self Merge, Maintainer Approved, Huge Change

#66365 [module-alias] Add type declaration for `module-alias/register` import
  types/module-alias/module-alias-tests.ts
  types/module-alias/register.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66236 [flickity] Improve event typings
  types/flickity/flickity-tests.ts
  types/flickity/index.d.ts
  types/flickity/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Owners

#66176 [node] Update types to v20.5.0
  types/node/child_process.d.ts
  types/node/dgram.d.ts
  types/node/events.d.ts
  types/node/fs/promises.d.ts
  types/node/globals.d.ts
  types/node/index.d.ts
  types/node/net.d.ts
  types/node/stream.d.ts
  types/node/test.d.ts
  types/node/test/child_process.ts
  types/node/test/dgram.ts
  types/node/test/events.ts
  types/node/test/http.ts
  types/node/test/net.ts
  types/node/test/stream.ts
  types/node/test/test.ts
  types/node/test/timers.ts
  types/node/timers.d.ts
  types/node/ts4.8/child_process.d.ts
  types/node/ts4.8/dgram.d.ts
  types/node/ts4.8/events.d.ts
  types/node/ts4.8/fs/promises.d.ts
  types/node/ts4.8/globals.d.ts
  types/node/ts4.8/net.d.ts
  types/node/ts4.8/stream.d.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
  types/node/ts4.8/timers.d.ts
  types/readable-stream/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#66177 [serverless] Add consumerGroupId to self managed kafka in the aws pro…
  types/serverless/plugins/aws/provider/awsProvider.d.ts
  types/serverless/serverless-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66271 [@types/k6] Add type annotations for version v0.46.0
  types/k6/experimental/grpc.d.ts
  types/k6/index.d.ts
  types/k6/net/grpc.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#66378 pubnub/add-missing-fields
  types/pubnub/index.d.ts
  types/pubnub/pubnub-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66370 [react-native-vector-icons] Types for FontAwesome6 and FontAwesome6Pro
  types/react-native-vector-icons/FontAwesome6.d.ts
  types/react-native-vector-icons/FontAwesome6Pro.d.ts
  types/react-native-vector-icons/react-native-vector-icons-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#66381 [@types/ember__owner] Add types for getOwner and setOwner
  types/ember__owner/ember__owner-tests.ts
  types/ember__owner/index.d.ts
Labels: Self Merge, Owner Approved

#66373 Node red node test helper - added setFlows
  types/node-red-node-test-helper/index.d.ts
  types/node-red-node-test-helper/node-red-node-test-helper-tests.ts
Labels: Self Merge, Owner Approved

#66376 fix: add missing functions for matter-js
  types/matter-js/index.d.ts
  types/matter-js/matter-js-tests.ts
Labels: Self Merge, Owner Approved

#66342 Update types for @npmcli/package-json to v4
  types/npmcli__package-json/index.d.ts
  types/npmcli__package-json/npmcli__package-json-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#66046 [@types/leaflet-freedraw] Add eventType to MarkerEvent
  types/leaflet-freedraw/index.d.ts
  types/leaflet-freedraw/leaflet-freedraw-tests.ts
Labels: Self Merge, Owner Approved

#66204 google-libphonenumber Type the return of getRegionCodeForCountryCode to handle not found result ZZ
  types/google-libphonenumber/google-libphonenumber-tests.ts
  types/google-libphonenumber/index.d.ts
Labels: Popular package, Unreviewed

#66385 [@types/ydn-db] Add KeyRange class
  types/ydn-db/index.d.ts
Labels: Owner Approved, Untested Change

#66321 [webxr] Add support for mesh-detection APIs
  types/webxr/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#66372 remove(@hapi/nes): remove just sources of the package for #66292
  types/hapi__nes/.eslintrc.json
  types/hapi__nes/index.d.ts
  types/hapi__nes/lib/client.d.ts
  types/hapi__nes/package.json
  types/hapi__nes/test/broadcast-client.ts
  types/hapi__nes/test/broadcast-server.ts
  types/hapi__nes/test/client-require.ts
  types/hapi__nes/test/hapi__nes-tests.ts
  types/hapi__nes/test/route-authentication-client.ts
  types/hapi__nes/test/route-authentication-server.ts
  types/hapi__nes/test/route-invocation-client.ts
  types/hapi__nes/test/route-invocation-server.ts
  types/hapi__nes/test/socket.ts
  types/hapi__nes/test/subscription-filter-client.ts
  types/hapi__nes/test/subscription-filter-server.ts
  types/hapi__nes/test/subscriptions-client.ts
  types/hapi__nes/test/subscriptions-server.ts
  types/hapi__nes/tsconfig.json
  types/hapi__nes/tslint.json
Labels: Check Config

#66322 slug - Add opts.mode to slug types
  types/slug/index.d.ts
Labels: Popular package, Untested Change

#66312 [auth0-lock] added missing 'signUpFieldsStrictValidation' option
  types/auth0-lock/index.d.ts
Labels: Untested Change

#66245 Braintree web add setMessage to hosted-fields
  types/braintree-web/hosted-fields.d.ts
  types/braintree-web/test/web.ts
Labels: Popular package, Self Merge, Owner Approved

#66392 [node] Expose `TextDecoder` and `TextEncoder` globals in v16
  types/node/v16/test/util.ts
  types/node/v16/ts4.8/test/util.ts
  types/node/v16/ts4.8/util.d.ts
  types/node/v16/util.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66386 [node] Expose `performance` global in v16
  types/node/v16/perf_hooks.d.ts
  types/node/v16/test/perf_hooks.ts
  types/node/v16/ts4.8/perf_hooks.d.ts
  types/node/v16/ts4.8/test/perf_hooks.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66399 Add support for include_totals to getClients method
  types/auth0/auth0-tests.ts
  types/auth0/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#66347 Fix k6 browser type definitions
  types/k6/experimental/browser.d.ts
  types/k6/test/browser.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Owner Approved

#66405 fix(node): 'Dirent.path' property added v18.17.0
  types/node/v18/fs.d.ts
  types/node/v18/test/fs.ts
  types/node/v18/ts4.8/fs.d.ts
  types/node/v18/ts4.8/test/fs.ts
Labels: Author is Owner, Owner Approved, Critical package

#66409 Add Inanc and Daniel as k6 browser maintainers
  types/k6/index.d.ts
Labels: Other Approved, Popular package, Author is Owner, Owner Approved, Untested Change, Edits Owners

#66391 [jasmine] Add support for passing DiffBuilder as the third argument to v3
  types/jasmine/v3/index.d.ts
  types/jasmine/v3/jasmine-tests.ts
Labels: Owner Approved, Critical package

#66371 update(node): `fs.openAsBlob`
  types/node/fs.d.ts
  types/node/test/fs.ts
  types/node/ts4.8/fs.d.ts
  types/node/ts4.8/test/fs.ts
Labels: Author is Owner, Owner Approved, Critical package

#66222 [howler] fix: add missing exports, remove incorrect export and remove private `Sound`
  types/howler/howler-tests.ts
  types/howler/index.d.ts
  types/howler/test/globals.ts
Labels: Popular package, Author is Owner, Unreviewed

#66416 Remove types for find-cache-dir
  notNeededPackages.json
  types/find-cache-dir/find-cache-dir-tests.ts
  types/find-cache-dir/index.d.ts
  types/find-cache-dir/tsconfig.json
  types/find-cache-dir/tslint.json
  types/find-cache-dir/v2/find-cache-dir-tests.ts
  types/find-cache-dir/v2/index.d.ts
  types/find-cache-dir/v2/tsconfig.json
  types/find-cache-dir/v2/tslint.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Critical package

#66419 [yt-search] update for v2.10
  types/yt-search/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#66424 [spotify-web-playback-sdk] Add missing property for PlayerInit Interface
  types/spotify-web-playback-sdk/index.d.ts
  types/spotify-web-playback-sdk/spotify-web-playback-sdk-tests.ts
Labels: Self Merge, Owner Approved

#66420 [har-format] add some Chromium-specific properties
  types/har-format/index.d.ts
  types/har-format/test/har-format-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66429 [dns-packet] Add missing DNS Answer types from docs
  types/dns-packet/dns-packet-tests.ts
  types/dns-packet/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#66432 [invity-api]: Adding optional paymentMethodName property to trade
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#66435 [invity-api]: Fix optional paymentMethodName property for SavingsTradeItem
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#66434 [tampermonkey] Add missing properties and new methods, update jsdoc comments
  types/tampermonkey/index.d.ts
  types/tampermonkey/tampermonkey-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66438 [atlassian-connect-js] Add undocumented function AP.history.popState
  types/atlassian-connect-js/atlassian-connect-js-tests.ts
  types/atlassian-connect-js/index.d.ts
Labels: Self Merge, Owner Approved

#66414 Add types for range-map package
  types/range-map/index.d.ts
  types/range-map/range-map-tests.ts
  types/range-map/tsconfig.json
  types/range-map/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#65490 [node] Add module loader hooks types
  types/node/module.d.ts
  types/node/test/module.ts
  types/node/ts4.8/module.d.ts
  types/node/ts4.8/test/module.ts
  types/node/v16/module.d.ts
  types/node/v16/test/module.ts
  types/node/v16/ts4.8/module.d.ts
  types/node/v16/ts4.8/test/module.ts
  types/node/v18/module.d.ts
  types/node/v18/test/module.ts
  types/node/v18/ts4.8/module.d.ts
  types/node/v18/ts4.8/test/module.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#66446 gorilla-engine typings added for window updated for toggle
  types/gorilla-engine/components/Toggle.d.ts
  types/gorilla-engine/components/Window.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Owner Approved, Edits Owners

#66440 Fix recent test failures
  types/hammerjs/hammerjs-tests.ts
  types/postcss-js/postcss-js-tests.ts
  types/react-blessed/react-blessed-tests.tsx
Labels: Popular package, Edits multiple packages, Maintainer Approved, The CI failed

#66187 fix(maxmsp): mgraphics size missing
  types/maxmsp/index.d.ts
  types/maxmsp/maxmsp-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#66425 feat(carbon__icons-react): upgrade to 11.25
  types/carbon__icons-react/OTHER_FILES.txt
  types/carbon__icons-react/carbon__icons-react-tests.tsx
  types/carbon__icons-react/es/Delete.d.ts
  types/carbon__icons-react/es/Return.d.ts
  types/carbon__icons-react/es/index.d.ts
  types/carbon__icons-react/index.d.ts
  types/carbon__icons-react/lib/Delete.d.ts
  types/carbon__icons-react/lib/Return.d.ts
  types/carbon__icons-react/lib/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Check Config, No Other Owners

#66449 fix(rethinkdb): use optional chaining in tests
  types/rethinkdb/rethinkdb-tests.ts
Labels: Self Merge, Maintainer Approved

#66368 fix: wrong postcss-prefix-selector return type
  types/postcss-prefix-selector/index.d.ts
  types/postcss-prefix-selector/package.json
  types/postcss-prefix-selector/postcss-prefix-selector-tests.ts
  types/postcss-prefix-selector/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Check Config

#66311 feat(lambda-tester): update to v4
  types/lambda-tester/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66054 [node] Update `fs.createReadStream` and `fs.createWriteStream` options
  types/node/fs.d.ts
  types/node/test/fs.ts
  types/node/ts4.8/fs.d.ts
  types/node/v14/fs.d.ts
  types/node/v14/test/fs.ts
  types/node/v14/ts4.8/fs.d.ts
  types/node/v16/fs.d.ts
  types/node/v16/test/fs.ts
  types/node/v16/ts4.8/fs.d.ts
  types/node/v18/fs.d.ts
  types/node/v18/test/fs.ts
  types/node/v18/ts4.8/fs.d.ts
  types/write/write-tests.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#66422 [webxr] Add isSystemKeyboardSupported property
  types/webxr/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66442 Fix clusterRefreshInterval type for eureka-js-client
  types/eureka-js-client/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#66426 Add render method to Smooch
  types/smooch/index.d.ts
  types/smooch/smooch-tests.ts
  types/smooch/tsconfig.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#66411 Add types for WICG JS Self Profiling API
  types/wicg-js-self-profiling/index.d.ts
  types/wicg-js-self-profiling/tsconfig.json
  types/wicg-js-self-profiling/tslint.json
  types/wicg-js-self-profiling/wicg-js-self-profiling-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#66369 [tedious]: add missing `Variant` data type.
  types/tedious/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#66208 [node:stream] add iterator, all the Array-like Readable methods
  types/jsforce/query.d.ts
  types/node/stream.d.ts
  types/node/test/stream.ts
  types/node/v16/stream.d.ts
  types/node/v18/stream.d.ts
  types/readable-stream/index.d.ts
  types/readable-stream/readable-stream-tests.ts
  types/stream-to-array/index.d.ts
  types/stream-to-array/stream-to-array-tests.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Critical package, Too Many Owners

#66468 [node] Fix `nextResolve`/`nextLoad` return type, improve `ImportAssertions` type
  types/node/module.d.ts
  types/node/test/module.ts
  types/node/ts4.8/module.d.ts
  types/node/ts4.8/test/module.ts
  types/node/ts4.8/vm.d.ts
  types/node/v16/module.d.ts
  types/node/v16/test/module.ts
  types/node/v16/ts4.8/module.d.ts
  types/node/v16/ts4.8/test/module.ts
  types/node/v18/module.d.ts
  types/node/v18/test/module.ts
  types/node/v18/ts4.8/module.d.ts
  types/node/v18/ts4.8/test/module.ts
  types/node/v18/ts4.8/vm.d.ts
  types/node/v18/vm.d.ts
  types/node/vm.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#66465 [websocket] fix resourceURL type
  types/websocket/index.d.ts
  types/websocket/websocket-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66294 update p5 to 1.7
  types/p5/OTHER_FILES.txt
  types/p5/global.d.ts
  types/p5/index.d.ts
  types/p5/literals.d.ts
  types/p5/src/color/creating_reading.d.ts
  types/p5/src/color/p5.Color.d.ts
  types/p5/src/color/setting.d.ts
  types/p5/src/core/constants.d.ts
  types/p5/src/core/environment.d.ts
  types/p5/src/core/p5.Element.d.ts
  types/p5/src/core/p5.Graphics.d.ts
  types/p5/src/core/p5.Renderer.d.ts
  types/p5/src/core/rendering.d.ts
  types/p5/src/core/shape/2d_primitives.d.ts
  types/p5/src/core/shape/attributes.d.ts
  types/p5/src/core/transform.d.ts
  types/p5/src/dom/dom.d.ts
  types/p5/src/image/loading_displaying.d.ts
  types/p5/src/image/pixels.d.ts
  types/p5/src/io/files.d.ts
  types/p5/src/math/p5.Vector.d.ts
  types/p5/src/webgl/interaction.d.ts
  types/p5/src/webgl/material.d.ts
  types/p5/src/webgl/p5.Camera.d.ts
  types/p5/src/webgl/p5.Framebuffer.d.ts
  types/p5/src/webgl/p5.RendererGL.Immediate.d.ts
  types/p5/src/webgl/p5.RendererGL.d.ts
  types/p5/tsconfig.json
Labels: Self Merge, Maintainer Approved, Untested Change, Check Config, Huge Change

#66290 sitemap-generator: Fixed event callback type
  types/sitemap-generator/index.d.ts
  types/sitemap-generator/sitemap-generator-tests.ts
Labels: Self Merge, Maintainer Approved

#66462 Add speedometer module definition
  types/speedometer/index.d.ts
  types/speedometer/speedometer-tests.ts
  types/speedometer/tsconfig.json
  types/speedometer/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved

#66471 [dotenv-flow] define types for v3.3.x
  types/dotenv-flow/dotenv-flow-tests.ts
  types/dotenv-flow/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#66413 [markdownlint-rule-helpers] Add types
  types/markdown-it/lib/index.d.ts
  types/markdownlint-rule-helpers/index.d.ts
  types/markdownlint-rule-helpers/markdownlint-rule-helpers-tests.ts
  types/markdownlint-rule-helpers/package.json
  types/markdownlint-rule-helpers/tsconfig.json
  types/markdownlint-rule-helpers/tslint.json
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#66349 [titanium] ran dprint fmt
  types/titanium/console.d.ts
  types/titanium/globals.d.ts
  types/titanium/index.d.ts
  types/titanium/titanium-tests.ts
Labels: Self Merge, Owner Approved, Huge Change

#66490 feat: Update web-push to 3.6
  types/web-push/index.d.ts
  types/web-push/web-push-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#66454 [node]: Fix test runner HookFn method signature
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/ts4.8/test.d.ts
  types/node/ts4.8/test/test.ts
  types/node/v18/test.d.ts
  types/node/v18/test/test.ts
  types/node/v18/ts4.8/test.d.ts
  types/node/v18/ts4.8/test/test.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66334 [node-windows] Add string array type to nodeOptions
  types/node-windows/index.d.ts
  types/node-windows/node-windows-tests.ts
Labels: Self Merge, Owner Approved

#66484 Fix buffer time optional parameter
  types/speedometer/index.d.ts
  types/speedometer/speedometer-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66488 [sortablejs] Add forceAutoScrollFallback option, and test other plugin options
  types/sortablejs/plugins.d.ts
  types/sortablejs/sortablejs-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66014 [d3-array]: Implement unlimited number of accessor key functions for group, groups, etc. functions
  types/d3-array/d3-array-tests.ts
  types/d3-array/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#66500 [@primer/octicons] Update to 19.6
  types/primer__octicons/index.d.ts
  types/primer__octicons/primer__octicons-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#66502 fix: missing basePath in interface
  types/barnard59-core/barnard59-core-tests.ts
  types/barnard59-core/lib/StreamObject.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66509 [formidable]: Update - Add type parameters to form.parse function and Fields & Files object types
  types/formidable/Formidable.d.ts
  types/formidable/formidable-tests.ts
  types/formidable/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#66515 [phoenix] Fix Channel.[onClose,onError] return types
  types/phoenix/index.d.ts
  types/phoenix/phoenix-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#66517 Update lodash tests for eslint rule change
  types/lodash/lodash-tests.ts
Labels: Critical package, The CI failed

#66477 fix(maxmsp): MaxobjListener missing
  types/maxmsp/index.d.ts
  types/maxmsp/maxmsp-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66474 fix(maxmsp): wrong and missing function signture
  types/maxmsp/index.d.ts
  types/maxmsp/maxmsp-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#66512 Mailchimp Marketing - add getListInterestCategories, listInterestCategoryInterests
  types/mailchimp__mailchimp_marketing/index.d.ts
  types/mailchimp__mailchimp_marketing/mailchimp__mailchimp_marketing-tests.ts
Labels: Self Merge, Owner Approved

#66518 Update tslint->eslint port script
  scripts/tslint-rule-to-eslint.js
Labels: Other Approved, Edits Infrastructure
