Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2024-05, with the labels that each got.

#69485 Fix errors related to new RegExp syntax checking
  types/regexp.prototype.flags/tsconfig.json
  types/webpack-manifest-plugin/webpack-manifest-plugin-tests.ts
Labels: Owner Approved, Edits multiple packages, Maintainer Approved, Check Config

#69486 [kap-plugin] Use correct version of electron-store
  types/kap-plugin/index.d.ts
  types/kap-plugin/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69379 [@types/oracledb] Change description for `password`
  types/oracledb/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69489 [@types/fs-readdir-recursive] Complete typings
  types/fs-readdir-recursive/fs-readdir-recursive-tests.ts
  types/fs-readdir-recursive/index.d.ts
Labels: Self Merge, Owner Approved

#69394 [@types/hubot] Update the declaration for users() to bring it up to date for Hubot v11
  types/hubot-slack/hubot-extension.d.ts
  types/hubot-slack/hubot-slack-tests.ts
  types/hubot-slack/index.d.ts
  types/hubot-slack/package.json
  types/hubot/hubot-tests.ts
  types/hubot/index.d.ts
  types/hubot/package.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#69414 [types/binary-parser] Fix 4 typos in 3 files
  types/binary-parser/binary-parser-tests.ts
  types/binary-parser/index.d.ts
  types/bytebuffer/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved

#69386 [@types/emscripten] Added analyzePath, updated Module.instantiateWasm
  types/emscripten/emscripten-tests.ts
  types/emscripten/index.d.ts
  types/emscripten/package.json
Labels: Self Merge, Maintainer Approved, Critical package

#69400 [@types/plotly.js] Add xref and yref to layout.legend
  types/plotly.js/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68985 [busboy] Add `stream.truncated` property
  types/busboy/busboy-tests.ts
  types/busboy/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69364 Put `asserts` on various `assert` functions.
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69493 fix(wktohtml): fix callback and return types
  types/wkhtmltopdf/index.d.ts
  types/wkhtmltopdf/wkhtmltopdf-tests.ts
Labels: Self Merge, Owner Approved

#69476 [@types/passport-google-oauth20] Use VerifyCallback from base @types/passport-oauth2
  types/passport-google-oauth20/index.d.ts
  types/passport-google-oauth20/passport-google-oauth20-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69437 Typo s/componentWillUmount/componentWillUnmount/
  types/react-form/v2/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69458 fix typo in types/nodemailer/lib/mailer/index.d.ts
  types/nodemailer/lib/mailer/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#69470 feat: loadable__server, use PropsWithChildren type alias for ChunkExtractorManager props
  types/loadable__server/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69467 fix(pngjs): add re-export for browser usage
  types/pngjs/browser.d.ts
  types/pngjs/pngjs-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69446 [luxon-business-days] New type definitions
  types/luxon-business-days/.npmignore
  types/luxon-business-days/index.d.ts
  types/luxon-business-days/luxon-business-days-tests.ts
  types/luxon-business-days/package.json
  types/luxon-business-days/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69164 [readable-stream] remove deprecated tag from Duplex.from
  types/readable-stream/index.d.ts
  types/readable-stream/readable-stream-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69501 Update VS code types to 1.89
  types/vscode/index.d.ts
  types/vscode/package.json
Labels: Popular package, Untested Change

#69419 [forge-viewer] update for version 7.89
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
  types/forge-viewer/package.json
  types/forge-viewer/tsconfig.json
Labels: Self Merge, Maintainer Approved, Check Config, Edits Owners

#69448 [react-syntax-highlighter] add missing definition in for prism style
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Self Merge, Maintainer Approved, Critical package

#69462 [jsrsasign] add missing null type in X509CRL.getRevCertArray()
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/X509CRL.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69440 [@types/superagent] - fix disableTLSCerts typo
  types/superagent/lib/agent-base.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#69471 [@types/react-syntax-highlighter] add type for the method alias of prism-light
  types/react-syntax-highlighter/index.d.ts
  types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
Labels: Self Merge, Maintainer Approved, Critical package

#69494 [ramda] everything to 0.30.0
  types/ramda/es/flow.d.ts
  types/ramda/es/isNotEmpty.d.ts
  types/ramda/package.json
  types/ramda/src/flow.d.ts
  types/ramda/src/isNotEmpty.d.ts
  types/ramda/test/converge-tests.ts
  types/ramda/test/zipObj-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#69510 add types for `filename-reserved-regex`
  types/filename-reserved-regex/.npmignore
  types/filename-reserved-regex/filename-reserved-regex-tests.ts
  types/filename-reserved-regex/index.d.ts
  types/filename-reserved-regex/package.json
  types/filename-reserved-regex/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69420 [@types/stylis] Add SCOPE
  types/stylis/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change, No Other Owners

#69356 update(snowflake-sdk): Add additional connection options for use with proxy
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69291 [lodash] add type guard signature for has
  types/lodash/common/object.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69271 [pg] add connection-parameters
  types/pg/lib/connection-parameters.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#69338 [passport-google-oauth20] Update `email_verified` type and override `passport.Profile` `provider` type
  types/passport-google-oauth20/index.d.ts
  types/passport-google-oauth20/passport-google-oauth20-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69517 [types/alpinejs] Adds Test for Class constructors
  types/alpinejs/alpinejs-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69247 [chai] added missing notIncludeDeepMembers assertion
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69312 [yaireo__tagify] update library changes up to version 4.23.0
  types/yaireo__tagify/index.d.ts
  types/yaireo__tagify/package.json
  types/yaireo__tagify/src/react.tagify.d.ts
  types/yaireo__tagify/test/yaireo__tagify-react-tests.tsx
  types/yaireo__tagify/yaireo__tagify-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#69515 Fix missing async fetch-meta-tags
  types/fetch-meta-tags/fetch-meta-tags-tests.ts
  types/fetch-meta-tags/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#69216 `once` helper does not receive arbitrary objects that just have `addEventListener` method
  types/node/events.d.ts
  types/node/test/events.ts
Labels: Self Merge, Owner Approved, Critical package

#69497 [node] Export TestContext and SuiteContext on v16-v18-v2x
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/v16/test.d.ts
  types/node/v16/test/test.ts
  types/node/v18/test.d.ts
  types/node/v18/test/test.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#69537 [diff] Add ESM entrypoint
  attw.json
  types/diff/diff-tests.mts
  types/diff/index.d.mts
  types/diff/package.json
  types/diff/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved

#69524 [sluggo] Add types for sluggo
  types/sluggo/.npmignore
  types/sluggo/index.d.ts
  types/sluggo/package.json
  types/sluggo/sluggo-tests.ts
  types/sluggo/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69260 [webpack-env] Make `import.meta.webpackContext` non-nullable
  types/webpack-env/index.d.ts
  types/webpack-env/webpack-env-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69455 [README.es]: Update spanish doc and fix typos
  README.es.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#69542 [@types/jquery] Fix link to shorthands and adjust description
  types/jquery/JQuery.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#69256 Extend `ControlOptions` for `leaflet.locatecontrol`
  types/leaflet.locatecontrol/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69451 [@types/passport-oauth2] Allow login rejects and unknown errors
  types/passport-oauth2/index.d.ts
  types/passport-oauth2/passport-oauth2-tests.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#69490 [@types/node] Dirent.path is renamed to Dirent.parentPath
  types/node/fs.d.ts
  types/node/test/fs.ts
  types/node/v18/fs.d.ts
  types/node/v18/test/fs.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#69546 [approximate-number] Add types for `approximate-number`
  types/approximate-number/.npmignore
  types/approximate-number/approximate-number-tests.ts
  types/approximate-number/index.d.ts
  types/approximate-number/package.json
  types/approximate-number/tsconfig.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#69541 create @types/isomorphic-git__openpgp-plugin
  types/isomorphic-git__openpgp-plugin/.npmignore
  types/isomorphic-git__openpgp-plugin/index.d.ts
  types/isomorphic-git__openpgp-plugin/isomorphic-git__openpgp-plugin-tests.ts
  types/isomorphic-git__openpgp-plugin/package.json
  types/isomorphic-git__openpgp-plugin/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69569 [PCF] Support events in public interface
  types/powerapps-component-framework/componentframework.d.ts
  types/powerapps-component-framework/powerapps-component-framework-tests.ts
Labels: Other Approved, Self Merge

#69570 [plotly.js] Add Plotly.animate
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69512 [@types/simpl-schema] Update types to allow passing schema to constructor
  types/simpl-schema/index.d.ts
  types/simpl-schema/simpl-schema-tests.ts
Labels: Other Approved, Self Merge

#69548 [@types/chrome] Add cloudFileInfo to chrome.fileSystemProvider.notify
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69562 [express-requests-logger] Add shouldSkipAuditFunc option
  types/express-requests-logger/express-requests-logger-tests.ts
  types/express-requests-logger/index.d.ts
  types/express-requests-logger/package.json
Labels: Self Merge, Maintainer Approved

#69545 Add isLicensePlate and isLuhnNumber interface definitions to @ types/validator
  types/validator/index.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package, Untested Change

#69567 Remove Thenable related types from React canary
  types/react/canary.d.ts
  types/react/ts5.0/canary.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#69577 feat(carbon__pictograms-react): bump to 12.36
  types/carbon__pictograms-react/carbon__pictograms-react-tests.tsx
  types/carbon__pictograms-react/es/bucharest--national-theatre/index.d.ts
  types/carbon__pictograms-react/es/bucharest--romanian-athenaeum/index.d.ts
  types/carbon__pictograms-react/es/cloud/index.d.ts
  types/carbon__pictograms-react/es/ibm--uk-labs-hursley/index.d.ts
  types/carbon__pictograms-react/es/index.d.ts
  types/carbon__pictograms-react/es/kochi-houseboat/index.d.ts
  types/carbon__pictograms-react/es/osaka--tsutenkaku-tower/index.d.ts
  types/carbon__pictograms-react/es/romania--the-gate-of-the-kiss/index.d.ts
  types/carbon__pictograms-react/es/shanghai--skyline/index.d.ts
  types/carbon__pictograms-react/es/walldorf-ibm-innovation-studios/index.d.ts
  types/carbon__pictograms-react/es/zurich/index.d.ts
  types/carbon__pictograms-react/index.d.ts
  types/carbon__pictograms-react/lib/bucharest--national-theatre/index.d.ts
  types/carbon__pictograms-react/lib/bucharest--romanian-athenaeum/index.d.ts
  types/carbon__pictograms-react/lib/cloud/index.d.ts
  types/carbon__pictograms-react/lib/ibm--uk-labs-hursley/index.d.ts
  types/carbon__pictograms-react/lib/index.d.ts
  types/carbon__pictograms-react/lib/kochi-houseboat/index.d.ts
  types/carbon__pictograms-react/lib/osaka--tsutenkaku-tower/index.d.ts
  types/carbon__pictograms-react/lib/romania--the-gate-of-the-kiss/index.d.ts
  types/carbon__pictograms-react/lib/shanghai--skyline/index.d.ts
  types/carbon__pictograms-react/lib/walldorf-ibm-innovation-studios/index.d.ts
  types/carbon__pictograms-react/lib/zurich/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#69556 [video-react] Added missing parameters and functions
  types/video-react/index.d.ts
  types/video-react/video-react-tests.tsx
Labels: Other Approved, Self Merge

#69461 [@types/chromecast-caf-sender] update RemotePlayerEventType
  types/chromecast-caf-sender/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69581 Bump @types/bun to 1.1.8
  types/bun/package.json
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Owner Approved

#69472 [@types/k6] Type annotations for version v0.51.0
  types/k6/experimental/browser.d.ts
  types/k6/experimental/grpc.d.ts
  types/k6/experimental/webcrypto.d.ts
  types/k6/experimental/websockets.d.ts
  types/k6/index.d.ts
  types/k6/net/grpc.d.ts
  types/k6/package.json
  types/k6/test/browser.ts
  types/k6/test/experimental/grpc.ts
  types/k6/test/grpc.ts
  types/k6/test/webcrypto.ts
  types/k6/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69555 [@types/masonry-layout] Add prototype for option() function to masonry-layout
  types/masonry-layout/index.d.ts
  types/masonry-layout/masonry-layout-tests.ts
Labels: Other Approved, Self Merge

#69218 Add class types to emscripten, fix readable-stream
  types/emscripten/index.d.ts
  types/readable-stream/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package, Untested Change

#69498 [@types/node] Update types for `node:stream`
  types/node/stream.d.ts
  types/node/test/stream.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#69579 [esquery] fix type of `selector` parameter in `traverse`
  types/esquery/esquery-tests.ts
  types/esquery/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69584 Remove emoji from @types/mdast
  types/mdast/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package, Untested Change

#69505 draco3d: Add definitions for the metadata API
  types/draco3d/draco3d-tests.ts
  types/draco3d/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69533 [@types/multicoin-address-validator] Improve types for networkType
  types/multicoin-address-validator/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69599 feat(@rdfjs/parser-jsonld): document loader
  types/rdfjs__parser-jsonld/FsDocumentLoader.d.ts
  types/rdfjs__parser-jsonld/index.d.ts
  types/rdfjs__parser-jsonld/rdfjs__parser-jsonld-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69426 [trianglify]: fix trianglify types
  types/trianglify/index.d.ts
  types/trianglify/package.json
  types/trianglify/trianglify-tests.ts
  types/trianglify/tsconfig.json
Labels: Self Merge, Maintainer Approved, Check Config, Edits Owners

#69580 fix(conventional-recommended-bump): remove @types/conventional-recommended-bump for v10 onwards
  notNeededPackages.json
  types/conventional-recommended-bump/.npmignore
  types/conventional-recommended-bump/conventional-recommended-bump-tests.ts
  types/conventional-recommended-bump/index.d.ts
  types/conventional-recommended-bump/package.json
  types/conventional-recommended-bump/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#69445 Cytoscape: add pie background style properties
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69620 fix(trianglify): update chroma-js dependency version
  types/trianglify/package.json
Labels: Self Merge, Owner Approved, Edits Owners

#69608 [eslint-plugin-security] add types for eslint-plugin-security
  types/eslint-plugin-security/.npmignore
  types/eslint-plugin-security/eslint-plugin-security-tests.ts
  types/eslint-plugin-security/index.d.ts
  types/eslint-plugin-security/package.json
  types/eslint-plugin-security/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69595 new: @rdfjs/sink-to-duplex
  types/rdfjs__sink-to-duplex/.npmignore
  types/rdfjs__sink-to-duplex/index.d.ts
  types/rdfjs__sink-to-duplex/package.json
  types/rdfjs__sink-to-duplex/rdfjs__sink-to-duplex-tests.ts
  types/rdfjs__sink-to-duplex/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69596 new: rdf-parser-csvw
  types/rdf-parser-csvw/.npmignore
  types/rdf-parser-csvw/index.d.ts
  types/rdf-parser-csvw/package.json
  types/rdf-parser-csvw/rdf-parser-csvw-tests.ts
  types/rdf-parser-csvw/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69597 new: rdf-parser-csvw-xlsx
  types/rdf-parser-csvw-xlsx/.npmignore
  types/rdf-parser-csvw-xlsx/index.d.ts
  types/rdf-parser-csvw-xlsx/package.json
  types/rdf-parser-csvw-xlsx/rdf-parser-csvw-xlsx-tests.ts
  types/rdf-parser-csvw-xlsx/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69583 Remove @types/mdx-js__react
  notNeededPackages.json
  types/mdx-js__react/.npmignore
  types/mdx-js__react/index.d.ts
  types/mdx-js__react/mdx-js__react-tests.tsx
  types/mdx-js__react/package.json
  types/mdx-js__react/tsconfig.json
Labels: Other Approved, Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#69590 Add Types for react-smartbanner
  types/react-smartbanner/.npmignore
  types/react-smartbanner/index.d.ts
  types/react-smartbanner/package.json
  types/react-smartbanner/react-smartbanner-tests.tsx
  types/react-smartbanner/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69561 [lodash] Fix _.partial() with 3 arity func and full args
  types/lodash/common/function.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69600 build(rdf-utils-dataset): is actually ESM
  attw.json
  types/rdf-utils-dataset/index.d.ts
  types/rdf-utils-dataset/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69504 [@types/lodash] Infer lodash.throttle return type from 'leading' option
  types/lodash/common/function.d.ts
  types/lodash/fp.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69617 phoenix_live_view: Add longPollFallbackMs to SocketOptions
  types/phoenix_live_view/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69566 [aws-lambda] Add `requestHeaders` to `AppSyncAuthorizerEvent`
  types/aws-lambda/test/appsync-resolver-tests.ts
  types/aws-lambda/trigger/appsync-resolver.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69622 [relay-runtime] return undefined from readInlineFragment
  types/relay-runtime/lib/store/readInlineData.d.ts
Labels: Popular package, Untested Change

#69624 [gamedig] Fix attw errors for 5.0 stable
  types/gamedig/gamedig-tests.ts
  types/gamedig/index.d.cts
  types/gamedig/index.d.ts
  types/gamedig/package.json
Labels: Self Merge, Maintainer Approved

#69534 [lodash] fix _.has not to be inferred to never on or operator
  types/lodash/common/common.d.ts
  types/lodash/common/object.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69628 [video-react] Make all props of PlayerProps optional
  types/video-react/index.d.ts
  types/video-react/video-react-tests.tsx
Labels: Self Merge, Owner Approved

#69625 conventional-changelog-core: Inline deleted options types
  types/conventional-changelog-core/index.d.ts
Labels: Untested Change

#69407 Added type definitions for @commerce7/admin-ui
  types/commerce7__admin-ui/.npmignore
  types/commerce7__admin-ui/commerce7__admin-ui-tests.tsx
  types/commerce7__admin-ui/index.d.ts
  types/commerce7__admin-ui/package.json
  types/commerce7__admin-ui/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#69633 [mongoose-delete] Update SoftDeteleModel with missing arguments from the mongoose.Model to work with model methods
  types/mongoose-delete/index.d.ts
  types/mongoose-delete/mongoose-delete-tests.ts
Labels: Self Merge, Owner Approved

#69629 [purify] Add package purify
  types/purify/.npmignore
  types/purify/index.d.ts
  types/purify/package.json
  types/purify/purify-tests.ts
  types/purify/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69538 update(snowflake-sdk): Add noProxy connection option
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69638 [tampermonkey] Sync types with documentation
  types/tampermonkey/index.d.ts
  types/tampermonkey/tampermonkey-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69637 [whatwg-url] update specification link for percentDecodeString()
  types/whatwg-url/index.d.ts
Labels: Critical package, Untested Change

#69578 [@types/umami] Fix umami type definitions
  types/umami/index.d.ts
  types/umami/package.json
  types/umami/umami-tests.ts
Labels: Other Approved, Self Merge

#69544 [@types/yandex-maps] add `coordSystem` namespace, add `GeoQueryResult…
  types/yandex-maps/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69654 Add types for elizabot
  types/elizabot/.npmignore
  types/elizabot/elizabot-tests.ts
  types/elizabot/index.d.ts
  types/elizabot/package.json
  types/elizabot/tsconfig.json
Labels: New Definition

#69647 Add types for Brittle
  types/brittle/.npmignore
  types/brittle/brittle-tests.ts
  types/brittle/index.d.ts
  types/brittle/package.json
  types/brittle/tsconfig.json
Labels: New Definition

#69641 [yauzl-promise] adjust types following v4 rewrite
  types/yauzl-promise/index.d.ts
  types/yauzl-promise/yauzl-promise-tests.ts
Labels: Popular package, No Other Owners

#69605 Mark read-only properties in express requests
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69648 [three] fix spelling of TextGeometryParameters.height jsdoc deprecated
  types/three/examples/jsm/geometries/TextGeometry.d.ts
Labels: Popular package, Untested Change

#69540 [@types/oracledb] v6.5 - add support for bigint bind variables
  types/oracledb/index.d.ts
  types/oracledb/package.json
Labels: Untested Change, Unreviewed

#69522 [@babel/traverse] Improve performance of mapped Visitor type
  types/babel__traverse/index.d.ts
Labels: Critical package, Untested Change, Unreviewed

#69656 fix(trianglify): seed should not accept numbers, only strings
  types/trianglify/index.d.ts
  types/trianglify/trianglify-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69658 Upgrade bun-types from 1.1.8 -> 1.1.9
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69659 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#69553 [karma-chai-sinon] remove duplicate global variables
  types/karma-chai-sinon/index.d.ts
  types/karma-chai-sinon/karma-chai-sinon-tests.ts
Labels: Other Approved, Unmerged, Self Merge

#69670 [react] Types for Popover API
  types/react/canary.d.ts
  types/react/global.d.ts
  types/react/test/canary.tsx
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/global.d.ts
  types/react/ts5.0/test/canary.tsx
Labels: Author is Owner, Critical package

#69676 [detect-rpi] add types
  types/detect-rpi/.npmignore
  types/detect-rpi/detect-rpi-tests.ts
  types/detect-rpi/index.d.ts
  types/detect-rpi/package.json
  types/detect-rpi/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69402 fix: 68883 - BindDefinition to support DbType fix
  types/oracledb/index.d.ts
Labels: Other Approved, Unmerged, Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#69552 [regenerator-runtime] remove duplicate global variables
  types/regenerator-runtime/index.d.ts
  types/regenerator-runtime/regenerator-runtime-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69571 [pendo-io-browser] Add missing functions, update return type
  types/pendo-io-browser/index.d.ts
  types/pendo-io-browser/package.json
  types/pendo-io-browser/pendo-io-browser-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69611 Emscripten: Added more types
  types/emscripten/emscripten-tests.ts
  types/emscripten/index.d.ts
Labels: Self Merge, Owner Approved, Critical package

#69667 chore: update woosmap.map
  types/woosmap.map/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#69477 [@types/passport-oauth2] Allow Unknown Error
  types/passport-oauth2/index.d.ts
  types/passport-oauth2/passport-oauth2-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69508 [@types/node] Types for Node v20.13.1
  types/node/assert.d.ts
  types/node/async_hooks.d.ts
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/cluster.d.ts
  types/node/console.d.ts
  types/node/crypto.d.ts
  types/node/dgram.d.ts
  types/node/diagnostics_channel.d.ts
  types/node/dns.d.ts
  types/node/dns/promises.d.ts
  types/node/domain.d.ts
  types/node/events.d.ts
  types/node/fs.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/https.d.ts
  types/node/inspector.d.ts
  types/node/net.d.ts
  types/node/os.d.ts
  types/node/path.d.ts
  types/node/perf_hooks.d.ts
  types/node/process.d.ts
  types/node/punycode.d.ts
  types/node/querystring.d.ts
  types/node/readline.d.ts
  types/node/repl.d.ts
  types/node/stream.d.ts
  types/node/string_decoder.d.ts
  types/node/test.d.ts
  types/node/test/child_process.ts
  types/node/test/process.ts
  types/node/test/url.ts
  types/node/test/util.ts
  types/node/test/v8.ts
  types/node/timers.d.ts
  types/node/tls.d.ts
  types/node/trace_events.d.ts
  types/node/tty.d.ts
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/v8.d.ts
  types/node/vm.d.ts
  types/node/wasi.d.ts
  types/node/worker_threads.d.ts
  types/node/zlib.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69523 react-highlight-words: Add type information for new unhighlightTag property
  types/react-highlight-words/index.d.ts
  types/react-highlight-words/package.json
  types/react-highlight-words/react-highlight-words-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#69675 Add types for mongoose-lean-id
  types/mongoose-lean-id/.npmignore
  types/mongoose-lean-id/index.d.ts
  types/mongoose-lean-id/mongoose-lean-id-tests.ts
  types/mongoose-lean-id/package.json
  types/mongoose-lean-id/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69695 [@types/lfsr] add package
  types/lfsr/.npmignore
  types/lfsr/index.d.ts
  types/lfsr/lfsr-tests.ts
  types/lfsr/package.json
  types/lfsr/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69539 feat(express-serve-static-core): Add Layer typings to express Router & Route stack prop
  types/express-serve-static-core/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#69547 Cytoscape layout options sort function
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69694 Remove social-logos
  notNeededPackages.json
  types/social-logos/.npmignore
  types/social-logos/index.d.ts
  types/social-logos/package.json
  types/social-logos/social-logos-tests.tsx
  types/social-logos/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#69560 [offline-js] Support function variant of `url` property in `OfflineCheck`, add `timeout` and `type` properties
  types/offline-js/index.d.ts
  types/offline-js/offline-js-tests.ts
Labels: Self Merge, Maintainer Approved

#69616 bootstrap-datepicker: Allow variable arguments as described in the docs
  attw.json
  types/bootstrap-datepicker/bootstrap-datepicker-tests.ts
  types/bootstrap-datepicker/index.d.ts
  types/bootstrap-datepicker/package.json
Labels: Other Approved, Self Merge

#69690 Add new methods to tg-ads-mediation__ads-cdn.
  types/tg-ads-mediation__ads-cdn/index.d.ts
  types/tg-ads-mediation__ads-cdn/package.json
  types/tg-ads-mediation__ads-cdn/tg-ads-mediation__ads-cdn-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#69655 update vorpal types to include missing argument for command.help signature
  types/vorpal/index.d.ts
  types/vorpal/vorpal-tests.ts
Labels: Other Approved, Self Merge, Owner Approved

#69601 build(@rdfjs/serializer-rdfjs): is actually ESM
  attw.json
  types/rdfjs__serializer-rdfjs/package.json
Labels: Other Approved, Self Merge

#69520 [@types/jsdom] Make `contentType` less restrictive
  types/jsdom/base.d.ts
  types/jsdom/test/core.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69679 Add types for connect-route
  types/connect-route/.npmignore
  types/connect-route/connect-route-tests.ts
  types/connect-route/index.d.ts
  types/connect-route/package.json
  types/connect-route/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69576 [@types/which] Update the options of `which` for version 3.0.0.
  types/which/index.d.ts
  types/which/tsconfig.json
  types/which/which-tests.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#69703 @types/express-serve-static-core: remove @samijaber as contributor
  types/express-serve-static-core/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Edits Owners

#69685 Add @types/slip
  types/slip/.npmignore
  types/slip/index.d.ts
  types/slip/package.json
  types/slip/slip-tests.ts
  types/slip/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69688 Added @tonic-ui/react__icons and updated @tonic-ui/react types for v2
  types/tonic-ui__react-icons/.npmignore
  types/tonic-ui__react-icons/index.d.ts
  types/tonic-ui__react-icons/package.json
  types/tonic-ui__react-icons/scripts/generate-definitions/README.md
  types/tonic-ui__react-icons/scripts/generate-definitions/base.d.ts.template
  types/tonic-ui__react-icons/scripts/generate-definitions/icon.d.ts.template
  types/tonic-ui__react-icons/scripts/generate-definitions/index.ts
  types/tonic-ui__react-icons/scripts/generate-definitions/package.json
  types/tonic-ui__react-icons/scripts/generate-definitions/tsconfig.json
  types/tonic-ui__react-icons/tonic-ui__react-icons-tests.tsx
  types/tonic-ui__react-icons/tsconfig.json
  types/tonic-ui__react/.eslintrc.json
  types/tonic-ui__react/index.d.ts
  types/tonic-ui__react/package.json
Labels: New Definition, Self Merge, Edits multiple packages, Maintainer Approved, Check Config

#69536 [color-hash] Types for version 2.0
  types/color-hash/color-hash-tests.ts
  types/color-hash/index.d.ts
  types/color-hash/package.json
Labels: Popular package, Self Merge, Maintainer Approved

#69711 [invity-api] WatchSellTradeResponse cryptoStringAmount
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#69487 [@types/selenium-webdriver]: split Chromium into a new file
  types/selenium-webdriver/chrome.d.ts
  types/selenium-webdriver/chromium.d.ts
  types/selenium-webdriver/edge.d.ts
  types/selenium-webdriver/firefox.d.ts
  types/selenium-webdriver/ie.d.ts
  types/selenium-webdriver/index.d.ts
  types/selenium-webdriver/lib/command.d.ts
  types/selenium-webdriver/lib/input.d.ts
  types/selenium-webdriver/lib/webdriver.d.ts
  types/selenium-webdriver/package.json
  types/selenium-webdriver/safari.d.ts
  types/selenium-webdriver/test/chrome.ts
  types/selenium-webdriver/test/chromium.ts
  types/selenium-webdriver/test/edge.ts
  types/selenium-webdriver/test/firefox.ts
  types/selenium-webdriver/test/index.ts
  types/selenium-webdriver/tsconfig.json
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package

#69481 Add Beacon transport type
  types/gtag.js/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved, Untested Change

#69671 Fix types for fromRDF and toRDF to use RdfOrString instead of RdfDataSet
  types/jsonld/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69716 [node] Revert 20.13 changes that were missing version bump
  types/node/assert.d.ts
  types/node/async_hooks.d.ts
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/cluster.d.ts
  types/node/console.d.ts
  types/node/crypto.d.ts
  types/node/dgram.d.ts
  types/node/diagnostics_channel.d.ts
  types/node/dns.d.ts
  types/node/dns/promises.d.ts
  types/node/domain.d.ts
  types/node/events.d.ts
  types/node/fs.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/https.d.ts
  types/node/inspector.d.ts
  types/node/net.d.ts
  types/node/os.d.ts
  types/node/path.d.ts
  types/node/perf_hooks.d.ts
  types/node/process.d.ts
  types/node/punycode.d.ts
  types/node/querystring.d.ts
  types/node/readline.d.ts
  types/node/repl.d.ts
  types/node/stream.d.ts
  types/node/string_decoder.d.ts
  types/node/test.d.ts
  types/node/test/child_process.ts
  types/node/test/process.ts
  types/node/test/url.ts
  types/node/test/util.ts
  types/node/test/v8.ts
  types/node/timers.d.ts
  types/node/tls.d.ts
  types/node/trace_events.d.ts
  types/node/tty.d.ts
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/v8.d.ts
  types/node/vm.d.ts
  types/node/wasi.d.ts
  types/node/worker_threads.d.ts
  types/node/zlib.d.ts
Labels: Critical package

#69718 Revert "[node] Revert 20.13 changes that were missing version bump (#…
  types/node/assert.d.ts
  types/node/async_hooks.d.ts
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/cluster.d.ts
  types/node/console.d.ts
  types/node/crypto.d.ts
  types/node/dgram.d.ts
  types/node/diagnostics_channel.d.ts
  types/node/dns.d.ts
  types/node/dns/promises.d.ts
  types/node/domain.d.ts
  types/node/events.d.ts
  types/node/fs.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/https.d.ts
  types/node/inspector.d.ts
  types/node/net.d.ts
  types/node/os.d.ts
  types/node/package.json
  types/node/path.d.ts
  types/node/perf_hooks.d.ts
  types/node/process.d.ts
  types/node/punycode.d.ts
  types/node/querystring.d.ts
  types/node/readline.d.ts
  types/node/repl.d.ts
  types/node/stream.d.ts
  types/node/string_decoder.d.ts
  types/node/test.d.ts
  types/node/test/child_process.ts
  types/node/test/process.ts
  types/node/test/url.ts
  types/node/test/util.ts
  types/node/test/v8.ts
  types/node/timers.d.ts
  types/node/tls.d.ts
  types/node/trace_events.d.ts
  types/node/tty.d.ts
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/v8.d.ts
  types/node/vm.d.ts
  types/node/wasi.d.ts
  types/node/worker_threads.d.ts
  types/node/zlib.d.ts
Labels: Other Approved, Critical package
