Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2024-04, with the labels that each got.

#69185 [eslint]: support `name` field in `FlatConfig`
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69232 [@types/tabulator-tables] Add module definitions, types for 6.0, 6.1 and 6.2
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/package.json
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#69233 [telegram-web-app] Update Telegram Web App to API 7.2
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/package.json
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Owner Approved

#69235 fix(telegram-web-app): Fix BiometricManager typings (events)
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Owner Approved

#69222 [node] 'inspector' reexport without `require`
  types/node/inspector.d.ts
  types/node/scripts/generate-inspector/inspector.d.ts.template
  types/node/v16/inspector.d.ts
  types/node/v18/inspector.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change, Check Config

#69258 [serve-static] restore old http import
  types/serve-static/index.d.ts
Labels: Critical package, Untested Change

#69109 [@types/dat.gui] Update index.d.ts - Correcting hideable default
  types/dat.gui/index.d.ts
Labels: Other Approved, Self Merge, Owner Approved, Untested Change

#69221 Leaflet circle radius should not accept undefined radius
  types/iitc/core/iitctypes.d.ts
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages

#68997 [react-timeago] Remove usage of deprecated global React JSX namespace
  types/react-timeago/react-timeago-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#69217 Add typing for `resolve-id-refs`
  types/resolve-id-refs/.npmignore
  types/resolve-id-refs/index.d.ts
  types/resolve-id-refs/package.json
  types/resolve-id-refs/resolve-id-refs-tests.ts
  types/resolve-id-refs/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69241 [@types/react-dom] fix: react-dom flushSync types
  types/react-dom/index.d.ts
  types/react-dom/test/react-dom-tests.tsx
Labels: Critical package

#69223 [node] `node:sea`
  types/node/index.d.ts
  types/node/scripts/generate-docs/docs.ts
  types/node/scripts/generate-docs/node-doc-processing.ts
  types/node/sea.d.ts
  types/node/test/sea.ts
Labels: Self Merge, Maintainer Approved, Critical package

#68981 [tar] add brotli and preservePaths options with minor cleanup
  types/tar/index.d.ts
  types/tar/tar-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69014 [@types/dockerode] Add `sshOptions` to `DockerOptions` interface
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
  types/dockerode/package.json
Labels: Popular package, Self Merge, Maintainer Approved

#69264 fix(react-refresh): fix incorrect type definitions of `react-refresh`
  types/react-refresh/react-refresh-tests.ts
  types/react-refresh/runtime.d.ts
Labels: Self Merge, Owner Approved

#69246 Bring back exported interfaces
  types/sparql-http-client/ParsingClient.d.ts
  types/sparql-http-client/SimpleClient.d.ts
  types/sparql-http-client/StreamClient.d.ts
  types/sparql-http-client/sparql-http-client-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#69267 [PXR Oneline] Add custom parameters to the interface,
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/oneline-tests.ts
  types/pxr-oneline/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68920 fix: randomstring also accepts an array of charsets
  types/randomstring/index.d.ts
  types/randomstring/package.json
  types/randomstring/randomstring-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69274 chore: update types for vscode 1.88.0
  types/vscode/index.d.ts
  types/vscode/package.json
Labels: Popular package, Untested Change

#68941 [@types/node-schedule] make all spec parms have correct types + tests
  types/node-schedule/index.d.ts
  types/node-schedule/node-schedule-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69219 [webxr] Add transient-pointer
  types/webxr/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69145 [@types/espree] Add type definitions
  types/espree/.npmignore
  types/espree/espree-tests.ts
  types/espree/index.d.cts
  types/espree/index.d.ts
  types/espree/package.json
  types/espree/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68366 [express-serve-static-core] Added CookieOption.partitioned
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express-serve-static-core/package.json
Labels: Self Merge, Maintainer Approved, Critical package

#69165 types/zafclient
  types/zafclient/.npmignore
  types/zafclient/index.d.ts
  types/zafclient/package.json
  types/zafclient/tsconfig.json
  types/zafclient/zafclient-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#69019 [chrome] Add Promise overloads for getAutoLockDelay and queryState for chrome.idle
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69270 [aws-lambda] add Transfer Family Authorizer types
  types/aws-lambda/test/transfer-family-authorizer-tests.ts
  types/aws-lambda/trigger/transfer-family-authorizer.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69273 Add clevertap methods for product experiences
  types/clevertap-web-sdk/clevertap-web-sdk-tests.ts
  types/clevertap-web-sdk/clevertap.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69272 Add LinkPreview to google app script card service
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#69191 Remove datatables.net* types
  notNeededPackages.json
  types/datatables.net-autofill/.npmignore
  types/datatables.net-autofill/datatables.net-autofill-tests.ts
  types/datatables.net-autofill/index.d.ts
  types/datatables.net-autofill/package.json
  types/datatables.net-autofill/tsconfig.json
  types/datatables.net-buttons/.npmignore
  types/datatables.net-buttons/datatables.net-buttons-tests.ts
  types/datatables.net-buttons/index.d.ts
  types/datatables.net-buttons/package.json
  types/datatables.net-buttons/tsconfig.json
  types/datatables.net-colreorder/.npmignore
  types/datatables.net-colreorder/datatables.net-colreorder-tests.ts
  types/datatables.net-colreorder/index.d.ts
  types/datatables.net-colreorder/package.json
  types/datatables.net-colreorder/tsconfig.json
  types/datatables.net-fixedcolumns/.npmignore
  types/datatables.net-fixedcolumns/datatables.net-fixedcolumns-tests.ts
  types/datatables.net-fixedcolumns/index.d.ts
  types/datatables.net-fixedcolumns/package.json
  types/datatables.net-fixedcolumns/tsconfig.json
  types/datatables.net-fixedheader/.npmignore
  types/datatables.net-fixedheader/datatables.net-fixedheader-tests.ts
  types/datatables.net-fixedheader/index.d.ts
  types/datatables.net-fixedheader/package.json
  types/datatables.net-fixedheader/tsconfig.json
  types/datatables.net-keytable/.npmignore
  types/datatables.net-keytable/datatables.net-keytable-tests.ts
  types/datatables.net-keytable/index.d.ts
  types/datatables.net-keytable/package.json
  types/datatables.net-keytable/tsconfig.json
  types/datatables.net-rowgroup/.npmignore
  types/datatables.net-rowgroup/datatables.net-rowgroup-tests.ts
  types/datatables.net-rowgroup/index.d.ts
  types/datatables.net-rowgroup/package.json
  types/datatables.net-rowgroup/tsconfig.json
  types/datatables.net-rowreorder/.npmignore
  types/datatables.net-rowreorder/datatables.net-rowreorder-tests.ts
  types/datatables.net-rowreorder/index.d.ts
  types/datatables.net-rowreorder/package.json
  types/datatables.net-rowreorder/tsconfig.json
  types/datatables.net-scroller/.npmignore
  types/datatables.net-scroller/datatables.net-scroller-tests.ts
  types/datatables.net-scroller/index.d.ts
  types/datatables.net-scroller/package.json
  types/datatables.net-scroller/tsconfig.json
  types/datatables.net-select/.npmignore
  types/datatables.net-select/datatables.net-select-tests.ts
  types/datatables.net-select/index.d.ts
  types/datatables.net-select/package.json
  types/datatables.net-select/tsconfig.json
  types/datatables.net/.npmignore
  types/datatables.net/datatables.net-tests.ts
  types/datatables.net/index.d.ts
  types/datatables.net/package.json
  types/datatables.net/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Huge Change

#69279 Update Decode Return Type to include failed validation
  types/jws/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#68638 [gamedig] v5 beta updates
  types/gamedig/gamedig-tests.ts
  types/gamedig/index.d.ts
Labels: Self Merge, Maintainer Approved

#69269 add CORS headers to node package
  types/node/http2.d.ts
  types/node/test/http2.ts
  types/node/v16/http2.d.ts
  types/node/v16/test/http2.ts
  types/node/v18/http2.d.ts
  types/node/v18/test/http2.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69276 smartystreets-javascript-sdk: Update usStreet types
  types/smartystreets-javascript-sdk/index.d.ts
  types/smartystreets-javascript-sdk/package.json
  types/smartystreets-javascript-sdk/smartystreets-javascript-sdk-tests.ts
Labels: Self Merge, Owner Approved

#69094 Definitions for ahocorasick
  types/ahocorasick/.npmignore
  types/ahocorasick/ahocorasick-tests.ts
  types/ahocorasick/index.d.ts
  types/ahocorasick/package.json
  types/ahocorasick/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69226 added type definitions for libsodium-wrappers crypto_aead_aegis functions and constants
  types/libsodium-wrappers/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#69281 [@types/mailchimp__mailchimp_transactional] Update axios depencency
  types/mailchimp__mailchimp_transactional/package.json
Labels: Other Approved, Self Merge

#69184 [chrome] Add chrome.platformKeys.challengeKey, update (...).challengeUserKey and (...).challengeMachineKey
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#69290 Update Vorpal types to support vorpal.mode command
  types/vorpal/index.d.ts
  types/vorpal/vorpal-tests.ts
Labels: Other Approved, Self Merge

#69028 [@types/splunk-logging] Remove extraneous dependency of request
  types/splunk-bunyan-logger/splunk-bunyan-logger-tests.ts
  types/splunk-logging/index.d.ts
  types/splunk-logging/package.json
  types/splunk-logging/splunk-logging-tests.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#69293 Definitions for cie-rgb-color-converter
  types/cie-rgb-color-converter/.npmignore
  types/cie-rgb-color-converter/cie-rgb-color-converter-tests.ts
  types/cie-rgb-color-converter/index.d.ts
  types/cie-rgb-color-converter/package.json
  types/cie-rgb-color-converter/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69305 [react/ts5.0] Allow async actions for `React.startTransition()`
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/test/canary.tsx
  types/react/ts5.0/test/hooks.tsx
Labels: Author is Owner, Critical package, The CI failed

#69295 [consolidated-events] Add types for consolidated-events
  types/consolidated-events/.npmignore
  types/consolidated-events/consolidated-events-tests.ts
  types/consolidated-events/index.d.ts
  types/consolidated-events/package.json
  types/consolidated-events/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69297 [rrdiagram-js] Add types for rrdiagram-js
  types/rrdiagram-js/.npmignore
  types/rrdiagram-js/index.d.ts
  types/rrdiagram-js/package.json
  types/rrdiagram-js/rrdiagram-js-tests.ts
  types/rrdiagram-js/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69309 [openui5] Update the definition files really for OpenUI5 1.121.0
  types/openui5/openui5-tests.ts
  types/openui5/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#69113 Add new package - tg-ads-mediation/ads-cdn.
  types/tg-ads-mediation__ads-cdn/.npmignore
  types/tg-ads-mediation__ads-cdn/index.d.ts
  types/tg-ads-mediation__ads-cdn/package.json
  types/tg-ads-mediation__ads-cdn/tg-ads-mediation__ads-cdn-tests.ts
  types/tg-ads-mediation__ads-cdn/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69308 [wordpress__edit-post] Use latest `@wordpress/components` types
  types/wordpress__edit-post/components/block-settings-menu/plugin-block-settings-menu-item.d.ts
  types/wordpress__edit-post/components/header/plugin-more-menu-item.d.ts
  types/wordpress__edit-post/components/header/plugin-sidebar-more-menu-item.d.ts
  types/wordpress__edit-post/components/sidebar/plugin-document-setting-panel.d.ts
  types/wordpress__edit-post/components/sidebar/plugin-post-publish-panel.d.ts
  types/wordpress__edit-post/components/sidebar/plugin-post-status-info.d.ts
  types/wordpress__edit-post/components/sidebar/plugin-pre-publish-panel.d.ts
  types/wordpress__edit-post/components/sidebar/plugin-sidebar.d.ts
  types/wordpress__edit-post/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#69311 Feature/curve component
  types/gorilla-engine/components/Curve.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69300 [mailchimp__mailchimp_marketing] Add namespace searchMembers and function search definitions
  types/mailchimp__mailchimp_marketing/index.d.ts
  types/mailchimp__mailchimp_marketing/mailchimp__mailchimp_marketing-tests.ts
Labels: Other Approved, Self Merge

#69315 gulp-tar: Create definitions
  types/gulp-tar/.npmignore
  types/gulp-tar/gulp-tar-tests.ts
  types/gulp-tar/index.d.ts
  types/gulp-tar/package.json
  types/gulp-tar/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69316 rdf-validate-shacl: add value to ValidationResult
  types/rdf-validate-shacl/src/validation-report.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69036 [@types/oracledb] Fix FetchTypeResponse
  types/oracledb/index.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Untested Change

#69285 Export types from assert.strict namespace
  types/node/assert.d.ts
  types/node/test/assert.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69121 [material-ui] Replace usage of deprecated types related to propTypes with their counterpart from the prop-types package
  types/material-ui/material-ui-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#69228 Add the makeBuffer interface to lz4js
  types/lz4js/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#69314 steam-user getSteamGuardDetails callback param fix
  types/steam-user/index.d.ts
  types/steam-user/package.json
  types/steam-user/steam-user-tests.ts
Labels: Self Merge, Owner Approved

#69126 [recompose] Replace usage of deprecated types related to propTypes with their counterpart from the prop-types package
  types/recompose/index.d.ts
  types/recompose/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69125 [react-virtualized] Replace usage of deprecated types related to propTypes with their counterpart from the prop-types package
  types/react-virtualized/dist/es/ArrowKeyStepper.d.ts
  types/react-virtualized/dist/es/AutoSizer.d.ts
  types/react-virtualized/dist/es/Collection.d.ts
  types/react-virtualized/dist/es/ColumnSizer.d.ts
  types/react-virtualized/dist/es/Grid.d.ts
  types/react-virtualized/dist/es/InfiniteLoader.d.ts
  types/react-virtualized/dist/es/Masonry.d.ts
  types/react-virtualized/dist/es/MultiGrid.d.ts
  types/react-virtualized/dist/es/ScrollSync.d.ts
  types/react-virtualized/dist/es/Table.d.ts
  types/react-virtualized/dist/es/WindowScroller.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69123 [react-props-decorators] Replace usage of deprecated types related to propTypes with their counterpart from the prop-types package
  types/react-props-decorators/index.d.ts
  types/react-props-decorators/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#69127 [shakacode__recompose] Replace usage of deprecated types related to propTypes with their counterpart from the prop-types package
  types/shakacode__recompose/index.d.ts
  types/shakacode__recompose/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#69322 steam-tradeoffer-manager Release v2.11.0
  types/steam-tradeoffer-manager/index.d.ts
  types/steam-tradeoffer-manager/package.json
  types/steam-tradeoffer-manager/steam-tradeoffer-manager-tests.ts
Labels: Self Merge, Owner Approved

#69324 [geodesy] Fix mistake with geodesy transform definitions
  types/geodesy/geodesy-tests.ts
  types/geodesy/latlon-ellipsoidal-referenceframe.d.ts
Labels: Other Approved, Self Merge

#69321 [@types/oracledb] Fix converter type
  types/oracledb/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69320 [winjs] Fix 5.5 nightly errors
  types/winjs/index.d.ts
Labels: Owner Approved, Untested Change

#69186 [eslint]: support rules generic for `FlatConfig`
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
  types/eslint__eslintrc/eslint__eslintrc-tests.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Critical package

#69142 [mdx] Stop relying on deprecated, global JSX namespace in React tests
  types/mdx/package.json
Labels: Critical package, Unreviewed

#69306 [react] Add new Transition events to Canary release channel
  types/react/canary.d.ts
  types/react/test/canary.tsx
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/test/canary.tsx
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#69313 libnpmpublish: Add publish options
  types/libnpmpublish/index.d.ts
  types/libnpmpublish/libnpmpublish-tests.ts
  types/libnpmpublish/package.json
Labels: Other Approved, Self Merge

#69188 [jwplayer] Update `registerPlugin` types
  types/jwplayer/index.d.ts
  types/jwplayer/jwplayer-tests.ts
  types/jwplayer/package.json
Labels: Self Merge, Owner Approved

#69210 [eslint]: remove function form of files/ignores in flat config files
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Critical package

#69334 @types/pg: extend unit tests for queries values with different types
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69302 [@types/doubleclick-gpt] slotRenderEnded event has isBackfill property
  types/doubleclick-gpt/doubleclick-gpt-tests.ts
  types/doubleclick-gpt/index.d.ts
Labels: Other Approved, Self Merge

#69330 fix(markdown-it): convert missing namespace
  types/markdown-it/lib/parser_block.d.mts
  types/markdown-it/test/parser_block.mts
Labels: Self Merge, Maintainer Approved, Critical package

#69331 [react] Add types for bigint render support in Canary
  types/react/canary.d.ts
  types/react/test/canary.tsx
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/test/canary.tsx
  types/react/ts5.0/tsconfig.json
  types/react/tsconfig.json
Labels: Author is Owner, Critical package, Check Config

#69242 [@types/micromatch] fix: match method parameter type
  types/micromatch/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Owner Approved, Untested Change

#69237 [leaflet] Forward given feature property type
  types/leaflet/.eslintrc.json
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Check Config

#69344 [Leaflet] setStyle now accepts optional radius
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69263 fix: Add missing types on Shipment object
  types/shippo/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Untested Change

#69342 [color-name] Remove myself from owners
  types/color-name/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, No Other Owners

#69144 [snowflake-sdk]: Add keepAlive and column variant parsers to configureOptions and fix docs link
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69354 [slice-ansi] remove empty dir
  types/slice-ansi/.npmignore
Labels: New Definition, Popular package

#69280 chore: remove repetitive words in comment
  types/jsts/index.d.ts
  types/video.js/index.d.ts
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved, Untested Change

#69296 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Other Approved, Self Merge

#69362 [intercom-web] Add showConversation to IntercomCommandSignature
  types/intercom-web/index.d.ts
  types/intercom-web/intercom-web-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69253 Add additional message types to castv2
  types/castv2/castv2-tests.ts
  types/castv2/index.d.ts
  types/castv2/package.json
Labels: Other Approved, Unmerged, Self Merge, Author is Owner, No Other Owners

#69333 Remove react-phone-number-input
  notNeededPackages.json
  types/react-phone-number-input/.npmignore
  types/react-phone-number-input/index.d.ts
  types/react-phone-number-input/input.d.ts
  types/react-phone-number-input/package.json
  types/react-phone-number-input/test/bare-import.tsx
  types/react-phone-number-input/test/react-phone-number-input.tsx
  types/react-phone-number-input/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#69335 For Package @types/xrm : Changes for Postsave context
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Other Approved, Self Merge

#69348 [react] Add tests for `createContext`
  types/react/test/tsx.tsx
  types/react/ts5.0/test/tsx.tsx
Labels: Author is Owner, Critical package

#69347 [react] Revert "Allow React context in ReactNode"
  types/react/canary.d.ts
  types/react/test/canary.tsx
  types/react/test/index.ts
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/test/canary.tsx
  types/react/ts5.0/test/index.ts
Labels: Author is Owner, Critical package

#69319 [vinyl][vinyl-file] Fix 5.5 nightly errors
  types/vinyl-file/index.d.ts
  types/vinyl/index.d.ts
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved, Untested Change

#69277 Add allowEmptyArray option to qs.stringify
  types/qs/index.d.ts
  types/qs/qs-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#69366 [react-lazy-load-image-component] fix onLoad props
  types/react-lazy-load-image-component/index.d.ts
  types/react-lazy-load-image-component/react-lazy-load-image-component-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#69254 [@types/bun] Update `@types/bun` to point to `bun-types@1.1.0`
  types/bun/package.json
Labels: Popular package, Self Merge, Maintainer Approved

#69327 6.4.0 Changes
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
  types/oracledb/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69372 Fix types of csrf impl
  types/lusca/index.d.ts
  types/lusca/lusca-tests.ts
Labels: Self Merge, Maintainer Approved

#69155 [@types/cookie-session] Add `partitioned` property to `CookieSessionOptions`
  types/cookie-session/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69154 fix: Parameter of `EdgeHandlesInstance.start()`
  types/cytoscape-edgehandles/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69157 [@types/mixpanel] Allow string types for the `Mixpanel.Config.track_pageview` parameter
  types/mixpanel/index.d.ts
  types/mixpanel/mixpanel-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69370 [@types/ysdk] Add types for player paying status api and more tests
  types/ysdk/index.d.ts
  types/ysdk/ysdk-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#69373 [@npmcli/arborist] Add inventory query types
  types/npmcli__arborist/index.d.ts
  types/npmcli__arborist/npmcli__arborist-tests.ts
  types/npmcli__arborist/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#69390 [@types/applepayjs]Add ApplePayLaterAvailability type and attribute to ApplePayPaymentRe…
  types/applepayjs/applepayjs-tests.ts
  types/applepayjs/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69174 [jsprintmanager]: Updates license_url and WSStatus types for 3.0+
  types/jsprintmanager/index.d.ts
  types/jsprintmanager/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#69368 [@types/eslint] Make `Linter.configType` accept `eslintrc`
  types/eslint/eslint-tests.ts
  types/eslint/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69367 [@types/splunk-logging] Revert "Remove extraneous dependency of request"
  types/splunk-bunyan-logger/splunk-bunyan-logger-tests.ts
  types/splunk-logging/index.d.ts
  types/splunk-logging/package.json
  types/splunk-logging/splunk-logging-tests.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#69392 [@types/hotwired__turbo] add types for StreamActions and events
  types/hotwired__turbo/hotwired__turbo-tests.ts
  types/hotwired__turbo/index.d.ts
Labels: Other Approved, Self Merge

#69299 Update cloudflare-turnstile types and CODEOWNERS
  types/cloudflare-turnstile/cloudflare-turnstile-tests.ts
  types/cloudflare-turnstile/index.d.ts
  types/cloudflare-turnstile/package.json
Labels: Unmerged, Self Merge, Owner Approved, Edits Owners

#69376 [@types/is-potential-custom-element-name] add new library types
  types/is-potential-custom-element-name/.npmignore
  types/is-potential-custom-element-name/index.d.ts
  types/is-potential-custom-element-name/is-potential-custom-element-name-tests.ts
  types/is-potential-custom-element-name/package.json
  types/is-potential-custom-element-name/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69371 [@types/facebook-jd-sdk] Add extras to LoginOptions
  types/facebook-js-sdk/facebook-js-sdk-tests.ts
  types/facebook-js-sdk/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69382 [@types/dragula] Implemented slideFactorX and slideFactorY parameters for enhanced dragging control
  types/dragula/dragula-tests.ts
  types/dragula/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69384 Add missing field to chromecast-caf-receiver PlaybackConfig
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Other Approved, Self Merge

#69397 [react] Add tests showing inaccurate types for refs with cleanup functions
  types/react/test/canary.tsx
  types/react/ts5.0/test/canary.tsx
Labels: Author is Owner, Critical package

#69387 Update remark related packages
  package.json
Labels: Edits Infrastructure

#69183 update(diff): `reversePatch` function
  types/diff/diff-tests.ts
  types/diff/index.d.ts
  types/diff/package.json
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#69388 Update VSCode extension recommendations
  .vscode/extensions.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#69383 Fix : __n does not have all overloads in the class i18n
  types/i18n/i18n-tests.ts
  types/i18n/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69359 [better-sqlite3] allow generic result type on Statement methods
  types/better-sqlite3/better-sqlite3-tests.ts
  types/better-sqlite3/index.d.ts
  types/better-sqlite3/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#69238 [leaflet] Turn on strictNullChecks and fix errors that arise
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
  types/leaflet/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69413 [meaningful-string] Add types for meaningful-string
  types/meaningful-string/.npmignore
  types/meaningful-string/index.d.ts
  types/meaningful-string/meaningful-string-tests.ts
  types/meaningful-string/package.json
  types/meaningful-string/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69323 Add missing k6 browser apis
  types/k6/experimental/browser.d.ts
  types/k6/test/browser.ts
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Owner Approved

#69292 [snowflake-sdk] Add requestId to connection.execute options
  types/snowflake-sdk/index.d.ts
  types/snowflake-sdk/snowflake-sdk-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69337 [i18n] add string option to objectNotation
  types/i18n/i18n-tests.ts
  types/i18n/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69398 [react] Types for 18.3
  types/react-dom/index.d.ts
  types/react-dom/package.json
  types/react-dom/server.d.ts
  types/react-dom/test-utils/index.d.ts
  types/react-is/index.d.ts
  types/react-is/package.json
  types/react-test-renderer/index.d.ts
  types/react-test-renderer/package.json
  types/react-test-renderer/shallow/index.d.ts
  types/react/index.d.ts
  types/react/package.json
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/test/tsx.tsx
Labels: Author is Owner, Edits multiple packages, Critical package

#69443 Fix more mentions of header in README
  README.md
Labels: Other Approved, Edits Infrastructure, Maintainer Approved

#69442 [stream-chain] add missing types for /utils and /defs
  types/stream-chain/defs/index.d.ts
  types/stream-chain/index.d.ts
  types/stream-chain/package.json
  types/stream-chain/stream-chain-tests.ts
  types/stream-chain/utils/FromIterable.d.ts
  types/stream-chain/utils/Reduce.d.ts
  types/stream-chain/utils/asFun.d.ts
  types/stream-chain/utils/asGen.d.ts
  types/stream-chain/utils/comp.d.ts
  types/stream-chain/utils/fold.d.ts
  types/stream-chain/utils/gen.d.ts
  types/stream-chain/utils/scan.d.ts
  types/stream-chain/utils/skip.d.ts
  types/stream-chain/utils/skipWhile.d.ts
  types/stream-chain/utils/take.d.ts
  types/stream-chain/utils/takeWhile.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69450 feat(@rdfjs/data-model): add term classes
  types/rdfjs__data-model/lib/BlankNode.d.ts
  types/rdfjs__data-model/lib/DefaultGraph.d.ts
  types/rdfjs__data-model/lib/Literal.d.ts
  types/rdfjs__data-model/lib/NamedNode.d.ts
  types/rdfjs__data-model/lib/Quad.d.ts
  types/rdfjs__data-model/lib/Variable.d.ts
  types/rdfjs__data-model/rdfjs__data-model-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69453 [react] Types for 18.3.1
  types/react/index.d.ts
  types/react/test/index.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/test/index.ts
Labels: Critical package

#69391 Add Clerk.io types
  types/clerk.io/.npmignore
  types/clerk.io/clerk.io-tests.ts
  types/clerk.io/index.d.ts
  types/clerk.io/package.json
  types/clerk.io/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69447 [shpjs] Fix casing in getShapefile function name
  types/shpjs/index.d.ts
  types/shpjs/shpjs-tests.ts
Labels: Other Approved, Self Merge

#69454 [intercom-web] Add startChecklist to IntercomCommandSignature
  types/intercom-web/index.d.ts
  types/intercom-web/intercom-web-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69240 [@types/chrome] Add cloudFileInfo to chrome.fileSystemProvider
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#69421 [types/smpte-timecode] Updated type of frameRate parameter
  types/smpte-timecode/index.d.ts
  types/smpte-timecode/smpte-timecode-tests.ts
Labels: Other Approved, Self Merge

#69468 [@types/bun] Update @types/bun to point to 1.1.6
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69385 [@types/dockerode] Improve AuthConfig and pull() types
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Owner Approved
