Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2024-11, with the labels that each got.

#71062 fix(trayballoon): bump version, change to esm, modify type & test
  attw.json
  types/trayballoon/.eslintrc.json
  types/trayballoon/index.d.ts
  types/trayballoon/package.json
  types/trayballoon/trayballoon-tests.ts
Labels: Self Merge, Maintainer Approved, Check Config

#71061 fix(friendly-errors-webpack-plugin): bump version, modify types, test
  attw.json
  types/friendly-errors-webpack-plugin/friendly-errors-webpack-plugin-tests.ts
  types/friendly-errors-webpack-plugin/index.d.ts
  types/friendly-errors-webpack-plugin/package.json
Labels: Self Merge, Maintainer Approved

#71048 add types for @digitalbazaar/bitstring
  types/digitalbazaar__bitstring/.npmignore
  types/digitalbazaar__bitstring/digitalbazaar__bitstring-tests.ts
  types/digitalbazaar__bitstring/index.d.ts
  types/digitalbazaar__bitstring/package.json
  types/digitalbazaar__bitstring/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#70788 [serverless] adds missing options
  types/serverless/classes/Plugin.d.ts
  types/serverless/serverless-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#70876 @event-calendar/core: Conform to a Svelte component
  types/event-calendar__core/event-calendar__core-tests.ts
  types/event-calendar__core/index.d.ts
  types/event-calendar__core/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#70877 Added missing type definitions and fixed the result types.
  types/amazon-product-api/amazon-product-api-tests.ts
  types/amazon-product-api/index.d.ts
Labels: Self Merge, Maintainer Approved

#71032 `@types/chrome` make details parameter optional
  types/chrome/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved, Untested Change

#70881 [jquery-toast-plugin] Allow `string` and `string[]` as input
  types/jquery-toast-plugin/index.d.ts
  types/jquery-toast-plugin/jquery-toast-plugin-tests.ts
Labels: Self Merge, Maintainer Approved

#70991 [ws] Add ws finishRequest callback type
  types/ws/index.d.mts
  types/ws/index.d.ts
  types/ws/ws-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#70971 fix(mapbox-gl): Add missing className to mapboxgl.MarkerOptions
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#70778 Update simpl-schema types
  types/simpl-schema/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Untested Change

#71071 [@types/bun] Update bun-types to 1.1.34
  types/bun/package.json
Labels: Popular package, Self Merge, Owner Approved

#71068 fix(redux-mock-store): Fix export equal & remove invalid typedef in v0
  attw.json
  types/redux-mock-store/v0/.eslintrc.json
  types/redux-mock-store/v0/index.d.ts
  types/redux-mock-store/v0/redux-mock-store-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved, Check Config

#70990 fix(run-sequence): Bump version, refine types, add back jsdoc
  attw.json
  types/run-sequence/.eslintrc.json
  types/run-sequence/index.d.ts
  types/run-sequence/package.json
  types/run-sequence/run-sequence-tests.ts
Labels: Self Merge, Maintainer Approved, Check Config

#71063 fix(wait-please): add "type: module" to fix attw error
  attw.json
  types/wait-please/package.json
Labels: Self Merge, Maintainer Approved

#71069 feat(preview-email): bump version, add missing opt, remove @types/node
  types/preview-email/index.d.ts
  types/preview-email/package.json
  types/preview-email/preview-email-tests.ts
Labels: Self Merge, Maintainer Approved

#70957 fix(node): Add signal & fix completer in ReadLineOptions, add jsdoc
  types/node/readline.d.ts
  types/node/readline/promises.d.ts
  types/node/test/readline.ts
  types/node/v16/readline.d.ts
  types/node/v16/test/readline.ts
  types/node/v18/readline.d.ts
  types/node/v18/readline/promises.d.ts
  types/node/v18/test/readline.ts
  types/node/v20/readline.d.ts
  types/node/v20/readline/promises.d.ts
  types/node/v20/test/readline.ts
Labels: Self Merge, Maintainer Approved, Critical package

#71072 fix(moment-business): Bump version to fix attw, add jsdoc
  attw.json
  types/moment-business/index.d.ts
  types/moment-business/moment-business-tests.ts
  types/moment-business/package.json
Labels: Self Merge, Maintainer Approved

#70929 [mjml-core] use Record instead of object
  types/mjml-core/index.d.ts
  types/mjml-core/mjml-core-tests.ts
Labels: Unmerged, Popular package, Self Merge, Owner Approved

#70955 [node] Update typings to v22.9.0
  types/node/package.json
  types/node/test.d.ts
  types/node/test/timers_promises.ts
  types/node/test/util.ts
  types/node/timers/promises.d.ts
  types/node/tls.d.ts
  types/node/util.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#71085 [@types/applepayjs] Add applePayCapabilities method type
  types/applepayjs/applepayjs-tests.ts
  types/applepayjs/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#71100 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#70910 [any-db] fix: make config in createPool() and add null case in callback errors
  types/any-db/any-db-tests.ts
  types/any-db/index.d.ts
Labels: Self Merge, Maintainer Approved

#70909 [node-memwatch] fix missing GcStats field and incorrect on() return type
  types/airbnb__node-memwatch/airbnb__node-memwatch-tests.ts
  types/airbnb__node-memwatch/index.d.ts
  types/airbnb__node-memwatch/package.json
Labels: Self Merge, Maintainer Approved

#71087 qs: Add `strictDepth` to parseOption
  types/qs/index.d.ts
  types/qs/qs-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#71079 feat(mongoose-autopopulate): remove types
  attw.json
  notNeededPackages.json
  types/mongoose-autopopulate/.npmignore
  types/mongoose-autopopulate/index.d.ts
  types/mongoose-autopopulate/mongoose-autopopulate-tests.ts
  types/mongoose-autopopulate/package.json
  types/mongoose-autopopulate/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#71064 [pouchdb-adapter-indexeddb] Add types
  types/pouchdb-adapter-indexeddb/.npmignore
  types/pouchdb-adapter-indexeddb/index.d.ts
  types/pouchdb-adapter-indexeddb/package.json
  types/pouchdb-adapter-indexeddb/pouchdb-adapter-indexeddb-tests.ts
  types/pouchdb-adapter-indexeddb/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71102 [elementary-circuits-directed-graph] allow missing nested list on adjacencyList
  types/elementary-circuits-directed-graph/elementary-circuits-directed-graph-tests.ts
  types/elementary-circuits-directed-graph/index.d.ts
  types/elementary-circuits-directed-graph/package.json
Labels: Self Merge, Owner Approved

#71067 Added types for react-add-new package
  types/react-add-new/.npmignore
  types/react-add-new/index.d.ts
  types/react-add-new/package.json
  types/react-add-new/react-add-new-tests.ts
  types/react-add-new/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71094 @event-calendar/core: Added allDay property to Calendar.SelectInfo interface.
  types/event-calendar__core/event-calendar__core-tests.ts
  types/event-calendar__core/index.d.ts
Labels: Self Merge, Owner Approved

#71088 Json-logic-js adding null type to allowed variables
  types/json-logic-js/index.d.ts
  types/json-logic-js/json-logic-js-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#71030 @types/vuelidate: required, minLength - minor fixes.
  types/vuelidate/package.json
  types/vuelidate/vuelidate-tests.ts
  types/vuelidate/vuelidate.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#70947 Adding typescript support for WebOTP API
  types/webappsec-credential-management/index.d.ts
  types/webappsec-credential-management/webappsec-credential-management-tests.ts
Labels: Self Merge, Maintainer Approved

#70976 [react-input-mask] Fix suggestion for issue: [@types/react-input-mask] InputMask children type does not match required value from lib #70974
  types/react-input-mask/index.d.ts
  types/react-input-mask/react-input-mask-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#71097 chore[google-apps-script]: change owners to Google Workspace DevRel team
  types/google-apps-script/package.json
Labels: Self Merge, Owner Approved, Edits Owners

#71107 [webostvjs] Update DeviceInfo to match current version of library
  types/webostvjs/index.d.ts
  types/webostvjs/package.json
  types/webostvjs/test/webOS.ts
Labels: Self Merge, Owner Approved

#71122 [google.picker]: automated update to Google Picker cl/694495820
  types/google.picker/google.picker-tests.ts
  types/google.picker/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#70489 chore(tough-cookie): @types package is not needed as of tough-cookie v5
  types/tough-cookie/.npmignore
  types/tough-cookie/index.d.ts
  types/tough-cookie/package.json
  types/tough-cookie/tough-cookie-tests.ts
  types/tough-cookie/tsconfig.json
  types/tough-cookie/v2/.npmignore
  types/tough-cookie/v2/index.d.ts
  types/tough-cookie/v2/package.json
  types/tough-cookie/v2/tough-cookie-tests.ts
  types/tough-cookie/v2/tsconfig.json
Labels: Other Approved, Unmerged, Self Merge, Maintainer Approved, Critical package

#70724 fix: update babel__standalone, add correct packages export types
  types/babel__standalone/babel__standalone-tests.ts
  types/babel__standalone/index.d.ts
  types/babel__standalone/package.json
Labels: Unmerged, Self Merge, Maintainer Approved, No Other Owners

#71140 Feature/mapping editor
  types/gorilla-engine/components/MappingEditor.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#70017 [didyoumean]: add `object[]` to list parameter
  types/didyoumean/didyoumean-tests.ts
  types/didyoumean/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Maintainer Approved

#71084 fix(natural-drag-animation-rbdnd): Fix export =, add jsdoc, modify test
  attw.json
  types/natural-drag-animation-rbdnd/index.d.ts
  types/natural-drag-animation-rbdnd/natural-drag-animation-rbdnd-tests.tsx
Labels: Self Merge, Maintainer Approved

#71098 fix(readline-transform-fix): Fix export =, add test
  attw.json
  types/readline-transform/index.d.ts
  types/readline-transform/readline-transform-tests.ts
  types/readline-transform/v0/index.d.ts
  types/readline-transform/v0/readline-transform-tests.ts
Labels: Self Merge, Maintainer Approved

#71101 feat(react-s-alert): upgrade, fix export =, add missing props & jsdoc
  attw.json
  types/react-s-alert/index.d.ts
  types/react-s-alert/package.json
  types/react-s-alert/react-s-alert-tests.tsx
Labels: Self Merge, Maintainer Approved

#71125 fix(react-window-size): Fix export =, modify test
  attw.json
  types/react-window-size/index.d.ts
  types/react-window-size/react-window-size-tests.tsx
Labels: Self Merge, Maintainer Approved

#71138 fix: node-fetch add arrayBuffer in Blob type
  types/node-fetch/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#71145 [@types/hotwired__turbo] Add missing fields to FetchRequest, FetchResponse and FormSubmission
  types/hotwired__turbo/hotwired__turbo-tests.ts
  types/hotwired__turbo/index.d.ts
Labels: Self Merge, Owner Approved

#71099 fix(newrelic): correct recordCustomEvent return type
  types/newrelic/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#71089 [whatwg-url] Update types to v13.0.0
  types/whatwg-url/index.d.ts
  types/whatwg-url/package.json
  types/whatwg-url/test/whatwg-url.index.test.ts
Labels: Self Merge, Maintainer Approved, Critical package

#71148 Fix 70724
  types/babel__standalone/package.json
Labels: Other Approved, Self Merge, No Other Owners

#71139 Add new topic PXR Oneline
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/oneline-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#71150 chore: remove me from owners
  types/tinycon/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#71152 [itowns] Add new contributor
  types/itowns/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#71155 feat(css-tree): add support for `cssWideKeywords` in `fork()`
  types/css-tree/css-tree-tests.ts
  types/css-tree/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#71129 Dlv fix undefined type
  types/dlv/dlv-tests.ts
  types/dlv/index.d.ts
  types/dlv/package.json
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#71170 fix(vinyl-paths): bump version, rewrite into esm to resolve attw
  attw.json
  types/vinyl-paths/index.d.ts
  types/vinyl-paths/package.json
  types/vinyl-paths/vinyl-paths-tests.ts
Labels: Self Merge, Maintainer Approved

#71118 update LegendTitle to include "top center" and "top right"
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#71167 [@types/dxf] Update toPolylines return type
  types/dxf/Helper.d.ts
  types/dxf/dxf-tests.ts
Labels: Other Approved, Self Merge

#70967 [Chrome] Add chrome.storage.getKeys() API
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#71113 [discourse-sso] Fix types for external_id in UserParams
  types/discourse-sso/discourse-sso-tests.ts
  types/discourse-sso/index.d.ts
Labels: Other Approved, Self Merge

#71141 [@types/k6] Update k6 type definitions for v0.55.0
  types/k6/browser/index.d.ts
  types/k6/experimental/tracing/index.d.ts
  types/k6/experimental/webcrypto/index.d.ts
  types/k6/test/browser.ts
  types/k6/test/tracing.ts
  types/k6/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#71156 Add type definitions for @11ty/eleventy-plugin-rss
  types/11ty__eleventy-plugin-rss/.npmignore
  types/11ty__eleventy-plugin-rss/11ty__eleventy-plugin-rss-tests.ts
  types/11ty__eleventy-plugin-rss/index.d.ts
  types/11ty__eleventy-plugin-rss/package.json
  types/11ty__eleventy-plugin-rss/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71123 [chrome] New owner suggestion
  types/chrome/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#70972 [chrome] Add hasCrossSiteAncestor to CookiePartitionKey
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#71076 Add the EscapeLatexOptions parameter of the lescape function of type { preserveFormatting?: boolean; escapeMapFn?: (defaultEscapes: any, formattingEscapes: any) => any; }
  types/escape-latex/escape-latex-tests.ts
  types/escape-latex/index.d.ts
Labels: Self Merge, Owner Approved

#70960 [react-mentions]: Add type for style of MentionsInput and Mentions
  types/react-mentions/index.d.ts
  types/react-mentions/react-mentions-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved

#70969 [compress-commons] Correct issues with initial PR
  types/compress-commons/archivers/archive-output-stream.d.ts
  types/compress-commons/archivers/zip/zip-archive-output-stream.d.ts
  types/compress-commons/compress-commons-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#70987 [delete-empty] modify return type of filter
  types/delete-empty/delete-empty-tests.ts
  types/delete-empty/index.d.ts
Labels: Self Merge, Maintainer Approved

#71092 Added Subpath to mount VolumeOptions (sorry for repost)
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#70975 [clamscan] Add ping() method
  types/clamscan/clamscan-tests.ts
  types/clamscan/index.d.ts
  types/clamscan/package.json
Labels: Self Merge, Maintainer Approved

#71193 Change preseveFormatting to preserveFormatting
  types/escape-latex/escape-latex-tests.ts
  types/escape-latex/index.d.ts
Labels: Self Merge, Owner Approved

#70965 [Redux Mock Store] - Copy over deprecation notice
  types/redux-mock-store/index.d.ts
  types/redux-mock-store/package.json
  types/redux-mock-store/redux-mock-store-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#71189 feat(subset-font): add `noLayoutClosure` flag introduced in v2.3.0
  types/subset-font/index.d.ts
  types/subset-font/package.json
  types/subset-font/subset-font-tests.ts
Labels: Self Merge, Owner Approved

#71011 fix type in zarinpal-checkout PaymentVerificationOutput RefId => refid as in the actual object
  types/zarinpal-checkout/index.d.ts
  types/zarinpal-checkout/zarinpal-checkout-tests.ts
Labels: Self Merge, Maintainer Approved

#70998 fix(sparqljs): more accurate path types
  types/sparqljs/index.d.ts
  types/sparqljs/sparqljs-tests.ts
Labels: Self Merge, Maintainer Approved

#71001 Fix/ibm db/missing types
  types/ibm_db/ibm_db-tests.ts
  types/ibm_db/index.d.ts
  types/ibm_db/package.json
Labels: Self Merge, Maintainer Approved

#71202 @types/js-sha1 modified the JsSha1 interface property type and added …
  types/js-sha1/index.d.ts
  types/js-sha1/js-sha1-tests.ts
Labels: Self Merge, Owner Approved

#71169 fix(nodemailer): Add back missing type for MimeNode
  types/nodemailer/lib/mime-node/index.d.ts
  types/nodemailer/nodemailer-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#71179 [node] fix types for glob exclude with file types
  types/node/fs.d.ts
  types/node/test/fs.ts
Labels: Self Merge, Maintainer Approved, Critical package

#71146 remove me from definition owners
  types/dropzone/package.json
  types/i18next-ko/package.json
  types/less/package.json
  types/tinycon/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits multiple packages, Maintainer Approved, Edits Owners

#71206 [react-virtualized] `registerChild` render prop is not optional
  types/react-virtualized/dist/es/CellMeasurer.d.ts
  types/react-virtualized/package.json
  types/react-virtualized/react-virtualized-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#71109 Update `@types/stream-json` to more accurately reflect `StreamBase` declaration
  types/stream-json/streamers/StreamBase.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#71153 [dompurify] Remove type declarations because they are now included in v3.2.0
  notNeededPackages.json
  types/dompurify/.npmignore
  types/dompurify/index.d.ts
  types/dompurify/package.json
  types/dompurify/test/dompurify-namespace-tests.ts
  types/dompurify/test/dompurify-tests.ts
  types/dompurify/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Critical package

#71177 [@types/dxf] Fix Box2 typo
  types/dxf/Utils.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#71210 [@uswds/uswds] Bump version to 3.10.x
  types/uswds__uswds/package.json
Labels: Other Approved, Self Merge, Author is Owner

#71190 fix(phoenix-live-view): improve phoenix liveView hooks types
  types/phoenix_live_view/README.md
  types/phoenix_live_view/index.d.ts
  types/phoenix_live_view/package.json
  types/phoenix_live_view/phoenix_live_view-tests.ts
Labels: Self Merge, Owner Approved

#71157 feat(nulogy__components): remove types
  notNeededPackages.json
  types/nulogy__components/.npmignore
  types/nulogy__components/index.d.ts
  types/nulogy__components/nulogy__components-tests.tsx
  types/nulogy__components/package.json
  types/nulogy__components/src/Alert.d.ts
  types/nulogy__components/src/Box.d.ts
  types/nulogy__components/src/BrandedNavBar.d.ts
  types/nulogy__components/src/Branding.d.ts
  types/nulogy__components/src/Breadcrumbs.d.ts
  types/nulogy__components/src/Button.d.ts
  types/nulogy__components/src/ButtonGroup.d.ts
  types/nulogy__components/src/Card.d.ts
  types/nulogy__components/src/Checkbox.d.ts
  types/nulogy__components/src/DatePicker.d.ts
  types/nulogy__components/src/DateRange.d.ts
  types/nulogy__components/src/DropdownMenu.d.ts
  types/nulogy__components/src/FieldLabel.d.ts
  types/nulogy__components/src/Flex.d.ts
  types/nulogy__components/src/Form.d.ts
  types/nulogy__components/src/Icon.d.ts
  types/nulogy__components/src/Input.d.ts
  types/nulogy__components/src/Link.d.ts
  types/nulogy__components/src/List.d.ts
  types/nulogy__components/src/LoadingAnimation.d.ts
  types/nulogy__components/src/Modal.d.ts
  types/nulogy__components/src/MonthPicker.d.ts
  types/nulogy__components/src/MonthRange.d.ts
  types/nulogy__components/src/NDSProvider.d.ts
  types/nulogy__components/src/NavBar.d.ts
  types/nulogy__components/src/NavBarSearch.d.ts
  types/nulogy__components/src/Overlay.d.ts
  types/nulogy__components/src/PMPagination.d.ts
  types/nulogy__components/src/PMTable.d.ts
  types/nulogy__components/src/Pagination.d.ts
  types/nulogy__components/src/Radio.d.ts
  types/nulogy__components/src/RangeContainer.d.ts
  types/nulogy__components/src/Select.d.ts
  types/nulogy__components/src/StatusIndicator.d.ts
  types/nulogy__components/src/Table.d.ts
  types/nulogy__components/src/Tabs.d.ts
  types/nulogy__components/src/Textarea.d.ts
  types/nulogy__components/src/TimePicker.d.ts
  types/nulogy__components/src/TimeRange.d.ts
  types/nulogy__components/src/Toast.d.ts
  types/nulogy__components/src/Toggle.d.ts
  types/nulogy__components/src/Tooltip.d.ts
  types/nulogy__components/src/TruncatedText.d.ts
  types/nulogy__components/src/Type.d.ts
  types/nulogy__components/src/Validation.d.ts
  types/nulogy__components/src/locales.const.d.ts
  types/nulogy__components/src/theme.d.ts
  types/nulogy__components/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#71174 added the eslint-plugin-react-refresh package
  types/eslint-plugin-react-refresh/.npmignore
  types/eslint-plugin-react-refresh/eslint-plugin-react-refresh-tests.ts
  types/eslint-plugin-react-refresh/index.d.ts
  types/eslint-plugin-react-refresh/package.json
  types/eslint-plugin-react-refresh/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71164 chore: update woosmap.map
  types/woosmap.map/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#71218 Adding oAuth2 types to liferay package
  types/liferay/index.d.ts
  types/liferay/liferay-tests.global.ts
Labels: Self Merge, Author is Owner, Owner Approved

#71166 Added types for salling-group__auth
  types/salling-group__auth/.npmignore
  types/salling-group__auth/index.d.ts
  types/salling-group__auth/package.json
  types/salling-group__auth/salling-group__auth.tests.ts
  types/salling-group__auth/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71223 event-calendar: Support nested resources
  types/event-calendar__core/event-calendar__core-tests.ts
  types/event-calendar__core/index.d.ts
  types/event-calendar__core/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#71224 [react-big-calendar] Update type for new prop resourceGroupingLayout and fix onDropFromOutside type
  types/react-big-calendar/index.d.ts
  types/react-big-calendar/lib/addons/dragAndDrop.d.ts
  types/react-big-calendar/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#71230 [pico-sdk-js] Adding new types for Pico-SDK-JS typescript packages
  types/pico-sdk-js/.npmignore
  types/pico-sdk-js/index.d.ts
  types/pico-sdk-js/package.json
  types/pico-sdk-js/pico-sdk-js-tests.ts
  types/pico-sdk-js/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#71216 [node] Fix module.findSourceMap can return undefined
  types/node/module.d.ts
  types/node/test/module.ts
  types/node/v18/module.d.ts
  types/node/v20/module.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#71175 Add Cast owners (castv2, chromecast-caf-receiver, and chromecast-caf-sender)
  types/castv2/package.json
  types/chromecast-caf-receiver/package.json
  types/chromecast-caf-sender/package.json
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Edits Owners

#71236 [@types/eslint-plugin-jsx-a11y] Update flat configs type
  types/eslint-plugin-jsx-a11y/eslint-plugin-jsx-a11y-tests.ts
  types/eslint-plugin-jsx-a11y/index.d.ts
  types/eslint-plugin-jsx-a11y/package.json
Labels: Popular package, Self Merge, Owner Approved

#71015 [cordova-plugin-qrscanner] Update types to v2.6.0
  types/cordova-plugin-qrscanner/cordova-plugin-qrscanner-tests.ts
  types/cordova-plugin-qrscanner/index.d.ts
  types/cordova-plugin-qrscanner/package.json
Labels: Self Merge, Maintainer Approved

#71124 feat(react-sticky-el): remove types
  attw.json
  notNeededPackages.json
  types/react-sticky-el/.npmignore
  types/react-sticky-el/index.d.ts
  types/react-sticky-el/package.json
  types/react-sticky-el/react-sticky-el-tests.tsx
  types/react-sticky-el/tsconfig.json
Labels: Other Approved, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#71133 feat(better-scroll): remove types
  attw.json
  notNeededPackages.json
  types/better-scroll/.npmignore
  types/better-scroll/better-scroll-tests.ts
  types/better-scroll/index.d.ts
  types/better-scroll/package.json
  types/better-scroll/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#71126 feat(crc): remove types
  attw.json
  notNeededPackages.json
  types/crc/.npmignore
  types/crc/crc-tests.ts
  types/crc/crc1.d.ts
  types/crc/crc16.d.ts
  types/crc/crc16ccitt.d.ts
  types/crc/crc16kermit.d.ts
  types/crc/crc16modbus.d.ts
  types/crc/crc16xmodem.d.ts
  types/crc/crc17ccitt.d.ts
  types/crc/crc17kermit.d.ts
  types/crc/crc17modbus.d.ts
  types/crc/crc17xmodem.d.ts
  types/crc/crc24.d.ts
  types/crc/crc32.d.ts
  types/crc/crc8.d.ts
  types/crc/crc81wire.d.ts
  types/crc/crc91wire.d.ts
  types/crc/crcjam.d.ts
  types/crc/index.d.ts
  types/crc/lib/crc1.d.ts
  types/crc/lib/crc16.d.ts
  types/crc/lib/crc16_ccitt.d.ts
  types/crc/lib/crc16_kermit.d.ts
  types/crc/lib/crc16_modbus.d.ts
  types/crc/lib/crc16_xmodem.d.ts
  types/crc/lib/crc24.d.ts
  types/crc/lib/crc32.d.ts
  types/crc/lib/crc8.d.ts
  types/crc/lib/crc8_1wire.d.ts
  types/crc/lib/crcjam.d.ts
  types/crc/lib/index.d.ts
  types/crc/package.json
  types/crc/test/lib.test.ts
  types/crc/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#71137 feat(nightwatch): remove types
  notNeededPackages.json
  types/nightwatch/.eslintrc.json
  types/nightwatch/.npmignore
  types/nightwatch/expect.d.ts
  types/nightwatch/globals.d.ts
  types/nightwatch/index.d.ts
  types/nightwatch/lib/core/client.d.ts
  types/nightwatch/lib/runner/cli/cli.d.ts
  types/nightwatch/package.json
  types/nightwatch/test/nightwatch-tests.ts
  types/nightwatch/test/react.tsx
  types/nightwatch/test/testActions.ts
  types/nightwatch/test/testAppiumCommands.ts
  types/nightwatch/test/testChromiumClientCommands.ts
  types/nightwatch/test/testClientCommands.ts
  types/nightwatch/test/testComponent.ts
  types/nightwatch/test/testDescribe.ts
  types/nightwatch/test/testElementCommands.ts
  types/nightwatch/test/testExpect.ts
  types/nightwatch/test/testGlobalElementApi.ts
  types/nightwatch/test/testProgrammaticApi.ts
  types/nightwatch/test/testWebdriverProtocolCommands.ts
  types/nightwatch/test/utils.ts
  types/nightwatch/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Check Config, Huge Change

#71019 chrome: Split deprecated namespaces to avoid ambiguity
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change, Huge Change

#71024 Remove deprecated methods that have been removed in Express 5
  types/express-serve-static-core/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#71239 chore(pdfkit): Remove @she11sh0cked from the owners list
  types/pdfkit/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits Owners

#71014 Add fatal and ignoreBOM parameters to the TextDecoderOptions and Text…
  types/text-encoding/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#71242 [phoenix] add ping method
  types/phoenix/index.d.ts
  types/phoenix/phoenix-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#71039 [d3-time] added types and tests for unixDay and unixDays
  types/d3-time/d3-time-tests.ts
  types/d3-time/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#70839 [dom-chromium-ai] introduce `languageAvailable()` methods
  types/dom-chromium-ai/dom-chromium-ai-tests.ts
  types/dom-chromium-ai/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved

#71238 [dom-chromium-ai] allow assistant-role prompts and multiple prompts
  types/dom-chromium-ai/dom-chromium-ai-tests.ts
  types/dom-chromium-ai/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#71211 Remove ambient module declaration of `@wordpress/blocks`
  types/wordpress__blocks/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#71247 feat(chromecast-caf-receiver): add ErrorSeverity enum and severity property to ErrorEvent
  types/chromecast-caf-receiver/cast.framework.events.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Self Merge, Owner Approved

#71240 [chrome] Fix JSDoc annotations of `chrome`
  types/chrome/chrome-cast/index.d.ts
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#71248 [cookie-parser] Move @types/express to peerDependencies
  types/cookie-parser/package.json
Labels: Self Merge, Maintainer Approved, Critical package, Check Config

#71204 Add type definitions for open-in-editor
  types/open-in-editor/.npmignore
  types/open-in-editor/index.d.ts
  types/open-in-editor/open-in-editor-tests.ts
  types/open-in-editor/package.json
  types/open-in-editor/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71192 rename existing package kineticjs -> kinetic because new npm package
  types/kinetic/.eslintrc.json
  types/kinetic/.npmignore
  types/kinetic/index.d.ts
  types/kinetic/kinetic-tests.ts
  types/kinetic/package.json
  types/kinetic/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#71096 [aws-lambda] Add aws guard duty scan result event notification
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/guard-duty-event-notification-tests.ts
  types/aws-lambda/trigger/guard-duty-event-notification.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#71251 Remove TS 4.9 only dirs
  types/conventional-changelog-preset-loader/package.json
  types/conventional-changelog-preset-loader/ts4.9/conventional-changelog-preset-loader-tests.ts
  types/conventional-changelog-preset-loader/ts4.9/index.d.ts
  types/conventional-changelog-preset-loader/ts4.9/tsconfig.json
  types/conventional-commits-parser/package.json
  types/conventional-commits-parser/ts4.9/conventional-commits-parser-tests.ts
  types/conventional-commits-parser/ts4.9/index.d.ts
  types/conventional-commits-parser/ts4.9/tsconfig.json
Labels: Edits multiple packages, Critical package

#71198 Adding TypeScript definitions for react-native-simple-animations
  types/react-native-simple-animations/.npmignore
  types/react-native-simple-animations/index.d.ts
  types/react-native-simple-animations/package.json
  types/react-native-simple-animations/react-native-simple-animations-tests.tsx
  types/react-native-simple-animations/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71176 [chrome] remove pokutuna from owners
  types/chrome/package.json
Labels: Unmerged, Popular package, Self Merge, Author is Owner, Owner Approved, Edits Owners

#70856 :tada: Adds AlpineJS resize & sort
  attw.json
  types/alpinejs/index.d.ts
  types/alpinejs__resize/.npmignore
  types/alpinejs__resize/alpinejs__resize-tests.ts
  types/alpinejs__resize/index.d.ts
  types/alpinejs__resize/package.json
  types/alpinejs__resize/tsconfig.json
  types/alpinejs__sort/.npmignore
  types/alpinejs__sort/alpinejs__sort-tests.ts
  types/alpinejs__sort/index.d.ts
  types/alpinejs__sort/package.json
  types/alpinejs__sort/tsconfig.json
Labels: New Definition, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved

#71042 [chrome] Update chrome.system.display
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#71257 express-session: fix the `secret` option to allow buffers
  types/express-session/express-session-tests.ts
  types/express-session/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#71158 Add types for @11ty/eleventy-plugin-component-directory
  types/11ty__eleventy-plugin-directory-output/.npmignore
  types/11ty__eleventy-plugin-directory-output/11ty__eleventy-plugin-directory-output-tests.ts
  types/11ty__eleventy-plugin-directory-output/index.d.ts
  types/11ty__eleventy-plugin-directory-output/package.json
  types/11ty__eleventy-plugin-directory-output/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71159 Add type definitions for eleventy-plugin-toc
  types/eleventy-plugin-toc/.npmignore
  types/eleventy-plugin-toc/eleventy-plugin-toc-tests.ts
  types/eleventy-plugin-toc/index.d.ts
  types/eleventy-plugin-toc/package.json
  types/eleventy-plugin-toc/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71256 tape: `skip` property can be a string
  attw.json
  types/tape/index.d.ts
  types/tape/lib/default_stream.d.ts
  types/tape/lib/results.d.ts
  types/tape/lib/test.d.ts
  types/tape/package.json
  types/tape/tape-tests.ts
  types/tape/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved

#71233 [matter-js] Make callback optional in Events.off
  types/matter-js/index.d.ts
  types/matter-js/matter-js-tests.ts
Labels: Other Approved, Self Merge

#71274 Update wordpress__edit-post
  types/wordpress__edit-post/package.json
  types/wordpress__edit-post/wordpress__edit-post-tests.tsx
Labels: Self Merge, Maintainer Approved

#71185 add luminous-lightbox
  types/luminous-lightbox/.npmignore
  types/luminous-lightbox/index.d.ts
  types/luminous-lightbox/package.json
  types/luminous-lightbox/test/luminous-lightbox-tests.ts
  types/luminous-lightbox/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71271 Add types for ga-gtag
  types/ga-gtag/.npmignore
  types/ga-gtag/ga-gtag-tests.ts
  types/ga-gtag/index.d.ts
  types/ga-gtag/package.json
  types/ga-gtag/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#71270 Add types for winchan
  types/winchan/.npmignore
  types/winchan/index.d.ts
  types/winchan/package.json
  types/winchan/tsconfig.json
  types/winchan/winchan-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#71243 fix(node): v8 deserialize accepts Buffer, TypedArray and DataView as input
  types/node/test/v8.ts
  types/node/v16/test/v8.ts
  types/node/v16/v8.d.ts
  types/node/v18/test/v8.ts
  types/node/v18/v8.d.ts
  types/node/v20/test/v8.ts
  types/node/v20/v8.d.ts
  types/node/v8.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#71045 Update SignedData.d.ts constructor method to comply with jsrsasign lib.
  types/jsrsasign/jsrsasign-tests.ts
  types/jsrsasign/modules/KJUR/asn1/cms/SignedData.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#71209 [jasmine] Fix Spec.id and add SuiteResult.filename
  attw.json
  types/jasmine-enzyme/index.d.ts
  types/jasmine-reporters/jasmine-reporters-tests.ts
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
  types/protractor-beautiful-reporter/protractor-beautiful-reporter-tests.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#71283 Chromium AI: Use `self` instead of `window` as entry point
  types/dom-chromium-ai/dom-chromium-ai-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#71268 Remove mattsains from adm-zip owners
  types/adm-zip/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits Owners

#71263 feat(intercom-client): remove types
  notNeededPackages.json
  types/intercom-client/.eslintrc.json
  types/intercom-client/.npmignore
  types/intercom-client/Company.d.ts
  types/intercom-client/Event.d.ts
  types/intercom-client/IntercomError.d.ts
  types/intercom-client/Lead.d.ts
  types/intercom-client/Message.d.ts
  types/intercom-client/Scroll.d.ts
  types/intercom-client/Tag.d.ts
  types/intercom-client/User.d.ts
  types/intercom-client/Visitor.d.ts
  types/intercom-client/index.d.ts
  types/intercom-client/intercom-client-tests.ts
  types/intercom-client/package.json
  types/intercom-client/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Check Config

#71284 Fix link to Pull Request Status Board in readme
  README.es.md
  README.fr.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#71287 feat(react-image-crop): remove types
  notNeededPackages.json
  types/react-image-crop/.npmignore
  types/react-image-crop/index.d.ts
  types/react-image-crop/package.json
  types/react-image-crop/test/react-image-crop-global-tests.ts
  types/react-image-crop/test/react-image-crop-module-tests.tsx
  types/react-image-crop/tsconfig.json
  types/react-image-crop/v7/.npmignore
  types/react-image-crop/v7/index.d.ts
  types/react-image-crop/v7/package.json
  types/react-image-crop/v7/test/react-image-crop-global-tests.ts
  types/react-image-crop/v7/test/react-image-crop-module-tests.tsx
  types/react-image-crop/v7/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#71162 types/locomotive-scroll: Update OnScrollEvent Interface
  types/locomotive-scroll/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#71291 [invity-api] KYC swap flow
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#71186 [@types/google-apps-script] Add Drive API V3
  types/google-apps-script/apis/drive_v2.d.ts
  types/google-apps-script/apis/drive_v3.d.ts
  types/google-apps-script/index.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#71260 fix(react-user-tour): bump version, add missing props, modify test
  attw.json
  types/react-user-tour/.eslintrc.json
  types/react-user-tour/index.d.ts
  types/react-user-tour/package.json
  types/react-user-tour/react-user-tour-tests.tsx
Labels: Self Merge, Maintainer Approved, Check Config

#71008 Updates types for Recurly.js v4.32.1
  types/recurly__recurly-js/lib/alternative-payment-methods.d.ts
  types/recurly__recurly-js/package.json
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved, Untested Change
