Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2024-03, with the labels that each got.

#68753 [@types/node-telegram-bot-api] Added entities field to SendMessageOptions interface
  types/node-telegram-bot-api/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#44037 Remove superfluous /// <reference types="node" />
  types/aws-param-store/index.d.ts
  types/aws-param-store/package.json
  types/boom/v3/index.d.ts
  types/boom/v3/package.json
  types/chai-fs/index.d.ts
  types/chai-fs/package.json
  types/chai-json-schema/index.d.ts
  types/chai-json-schema/package.json
  types/chai-uuid/index.d.ts
  types/chai-uuid/package.json
  types/http-aws-es/index.d.ts
  types/http-aws-es/package.json
  types/mandrill-api/index.d.ts
  types/mandrill-api/package.json
  types/mobile-messaging-cordova/index.d.ts
  types/mobile-messaging-cordova/package.json
  types/rollup-plugin-buble/index.d.ts
  types/rollup-plugin-buble/package.json
  types/rollup-plugin-json/index.d.ts
  types/rollup-plugin-json/package.json
  types/rollup-plugin-peer-deps-external/index.d.ts
  types/rollup-plugin-peer-deps-external/package.json
  types/rollup-plugin-progress/index.d.ts
  types/rollup-plugin-progress/package.json
  types/rollup-plugin-size-snapshot/index.d.ts
  types/rollup-plugin-size-snapshot/package.json
  types/rollup-plugin-url/index.d.ts
  types/rollup-plugin-url/package.json
  types/rollup-plugin-visualizer/index.d.ts
  types/rollup-plugin-visualizer/package.json
  types/rollup__plugin-virtual/index.d.ts
  types/rollup__plugin-virtual/package.json
  types/styled-components/v3/index.d.ts
  types/styled-components/v3/package.json
  types/svgr__rollup/index.d.ts
  types/svgr__rollup/package.json
  types/uglify-js/package.json
  types/uglify-js/uglify-js-tests.ts
  types/zui/package.json
  types/zui/zui-tests.ts
Labels: Edits multiple packages, Critical package, Unreviewed

#68818 [react-flex] Ensure forwards compatible pattern for typing `ref` is used
  types/react-flex/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68813 [react-bootstrap-typeahead] Ensure forwards compatible pattern for typing `ref` is used
  types/react-bootstrap-typeahead/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68827 [react-redux] Ensure forwards compatible pattern for typing `ref` is used
  types/react-redux/react-redux-tests.tsx
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#68828 [react-scrollbar] Ensure forwards compatible pattern for typing `ref` is used
  types/react-scrollbar/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68826 [react-portal] Ensure forwards compatible pattern for typing `ref` is used
  types/react-portal/v3/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68823 [react-list] Ensure forwards compatible pattern for typing `ref` is used
  types/react-list/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68821 [react-infinite] Ensure forwards compatible pattern for typing `ref` is used
  types/react-infinite/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68829 [react-tagcloud] Ensure forwards compatible pattern for typing `ref` is used
  types/react-tagcloud/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68822 [react-lines-ellipsis] Ensure forwards compatible pattern for typing `ref` is used
  types/react-lines-ellipsis/lib/responsiveHOC.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68682 [@types/react-datepicker] Add typings for `renderQuarterContent`
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#45119 Fix bpmn-moddle typo
  types/bpmn-moddle/index.d.ts
Labels: Self Merge, Perf: Same, Maintainer Approved, Untested Change

#45085 components.width accept string and number
  types/video.js/index.d.ts
Labels: Self Merge, Perf: Same, Maintainer Approved, Untested Change

#68839 node-wit - Add apiVersion to config type
  types/node-wit/index.d.ts
  types/node-wit/node-wit-tests.ts
Labels: Other Approved, Self Merge

#68705 :label: Type react-elm-components
  types/react-elm-components/.npmignore
  types/react-elm-components/index.d.ts
  types/react-elm-components/package.json
  types/react-elm-components/react-elm-components-tests.tsx
  types/react-elm-components/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68845 [@types/oracledb] Fix fetchAsBuffer and fetchAsString types
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
Labels: Other Approved, Self Merge

#68855 [PXR online] Update index interface and test
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/oneline-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68850 [baidumap-web-sdk] Add the missing PolylineOptions.icons field
  types/baidumap-web-sdk/baidumap-web-sdk-tests.ts
  types/baidumap-web-sdk/baidumap.overlay.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68856 [PXR Oneline] Bump version
  types/pxr-oneline/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68863 [@uswds/uswds]: Fix inaccurate typings for optional elements, add new components
  types/uswds__uswds/js/_usa-password/index.d.ts
  types/uswds__uswds/js/index.d.ts
  types/uswds__uswds/js/usa-accordion/index.d.ts
  types/uswds__uswds/js/usa-banner/index.d.ts
  types/uswds__uswds/js/usa-button/index.d.ts
  types/uswds__uswds/js/usa-character-count/index.d.ts
  types/uswds__uswds/js/usa-combo-box/index.d.ts
  types/uswds__uswds/js/usa-date-picker/index.d.ts
  types/uswds__uswds/js/usa-date-range-picker/index.d.ts
  types/uswds__uswds/js/usa-file-input/index.d.ts
  types/uswds__uswds/js/usa-footer/index.d.ts
  types/uswds__uswds/js/usa-header/index.d.ts
  types/uswds__uswds/js/usa-in-page-navigation/index.d.ts
  types/uswds__uswds/js/usa-input-mask/index.d.ts
  types/uswds__uswds/js/usa-input-prefix-suffix/index.d.ts
  types/uswds__uswds/js/usa-language-selector/index.d.ts
  types/uswds__uswds/js/usa-modal/index.d.ts
  types/uswds__uswds/js/usa-range/index.d.ts
  types/uswds__uswds/js/usa-search/index.d.ts
  types/uswds__uswds/js/usa-skipnav/index.d.ts
  types/uswds__uswds/js/usa-table/index.d.ts
  types/uswds__uswds/js/usa-time-picker/index.d.ts
  types/uswds__uswds/js/usa-tooltip/index.d.ts
  types/uswds__uswds/js/usa-validation/index.d.ts
  types/uswds__uswds/package.json
  types/uswds__uswds/uswds__uswds-tests.ts
Labels: Self Merge, Owner Approved

#68864 [wallabyjs] add new configuration options
  types/wallabyjs/index.d.ts
  types/wallabyjs/wallabyjs-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68695 [ramda] Bump types-ramda package to latest
  types/ramda/package.json
  types/ramda/test/assoc-tests.ts
  types/ramda/test/complement-tests.ts
  types/ramda/test/filter-tests.ts
  types/ramda/test/pick-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#68848 Add Missing Prop for React Native Signature Capture
  types/react-native-signature-capture/index.d.ts
  types/react-native-signature-capture/react-native-signature-capture-tests.tsx
Labels: Other Approved, Self Merge

#68808 frida-gum: Add putChainingReturn stalker function
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
  types/frida-gum/package.json
Labels: Other Approved, Self Merge

#68866 docs: change dts-gen link to current location
  README.es.md
  README.fr.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
  docs/admin.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68709 [@types/react-datepicker] fix: remove named export
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#68859 [PXR Online] Add new version + Add new interface
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/package.json
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#68880 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#68870 Node-wit: Updated type definitions for entities
  types/node-wit/index.d.ts
  types/node-wit/node-wit-tests.ts
  types/node-wit/package.json
Labels: Other Approved, Self Merge

#68882 Update for tabulator-tables 5.6
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/package.json
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68884 [invity-api]: Add brandName to BuyProviderInfo
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#68885 [react] Remove unused dependencies
  types/react/package.json
Labels: Author is Owner, Critical package

#68872 [passport-discord] Fix existing and add missing profile types
  types/passport-discord/index.d.ts
  types/passport-discord/package.json
  types/passport-discord/passport-discord-tests.ts
Labels: Other Approved, Self Merge, Edits Owners

#68857 infinitescroll: fix type of checkLastPage
  types/infinite-scroll/index.d.ts
  types/infinite-scroll/infinite-scroll-tests.ts
Labels: Self Merge, Owner Approved

#68876 Added `NestingSelector` type in `csstree`
  types/css-tree/css-tree-tests.ts
  types/css-tree/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68892 [react-dom] Add support for `createRoot(document)` in Canary and Experimental release channels
  types/react-dom/canary.d.ts
  types/react-dom/client.d.ts
  types/react-dom/test/canary-tests.tsx
  types/react-dom/test/react-dom-tests.tsx
Labels: Other Approved, Author is Owner, Critical package

#68803 Add Vtex.js Types
  types/vtex.js/.npmignore
  types/vtex.js/index.d.ts
  types/vtex.js/package.json
  types/vtex.js/tsconfig.json
  types/vtex.js/vtex.js-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#68893 [aws-lambda] add types for CloudWatch alarm events
  types/aws-lambda/index.d.ts
  types/aws-lambda/test/cloudwatch-tests.ts
  types/aws-lambda/trigger/cloudwatch-alarm.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#68770 [@types/steamcommunity] fix login callback cookies type
  types/steamcommunity/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68771 [@types/firefox-webext-browser] Allow `null` as a type in more methods
  types/firefox-webext-browser/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#68738 Add parse_intermixed_args and parse_known_intermixed_args to argparse
  types/argparse/argparse-tests.ts
  types/argparse/index.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#68849 [aws-lambda] CloudFrontS3Origin.region not on authType none.
  types/aws-lambda/common/cloudfront.d.ts
  types/aws-lambda/test/cloudfront-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#68896 [@types/telegram-web-app] feat: add detailed comments for requestContact callback types.
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/package.json
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Owner Approved

#68794 [@types/plotly.js] Add legend types to shapes
  types/plotly.js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#68767 Fix/k6 browser 1.3.0 type definitions
  types/k6/experimental/browser.d.ts
  types/k6/test/browser.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#68917 [node] Remove myself from the owners
  types/node/package.json
  types/node/v16/package.json
  types/node/v18/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#68888 [react] Replace DOM tests with `createElement`
  types/react-dom-factories/react-dom-factories-tests.ts
  types/react/package.json
  types/react/test/index.ts
  types/react/ts5.0/test/index.ts
Labels: Edits multiple packages, Critical package

#68911 twine-sugarcube: Fix ariaDisabled return type
  types/twine-sugarcube/extensions.d.ts
  types/twine-sugarcube/test/extensions.ts
Labels: Other Approved, Self Merge, Owner Approved

#68922 [react-dom] add PreloadOptions.type
  types/react-dom/canary.d.ts
  types/react-dom/test/canary-tests.tsx
Labels: Critical package

#68929 [Poool-access]: add externalLinkClick event and Audit/Access to globalThis
  types/poool-access/index.d.ts
  types/poool-access/package.json
  types/poool-access/poool-access-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68902 [itowns] Add missing WMTSSource options
  types/itowns/src/Source/WMTSSource.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#68928 [verror] raise minimum TS version to 4.8
  types/jsprim/package.json
  types/restify-errors/package.json
  types/verror/package.json
Labels: Popular package, Edits multiple packages

#68913 [@types/selenium-webdriver] Remove deprecated headless methods
  types/selenium-webdriver/chrome.d.ts
  types/selenium-webdriver/edge.d.ts
  types/selenium-webdriver/firefox.d.ts
  types/selenium-webdriver/test/chrome.ts
  types/selenium-webdriver/test/edge.ts
  types/selenium-webdriver/test/firefox.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#68732 Removed frameQuality & onFrameChange props type-defs
  types/react-native-video/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved, Untested Change

#68327 [dockerode] Adding missing properties
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved

#68933 [@types/svg-sprite] Fix missing namespaceIDPrefix attribute on Svg interface
  types/svg-sprite/index.d.ts
  types/svg-sprite/svg-sprite-tests.ts
Labels: Other Approved, Self Merge

#68836 chrome/chrome-cast: Mark as optional, fields documented as nullable in Media and MediaInfo
  types/chrome/chrome-cast/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68935 [dockerode] missing properties (regression from #68327)
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#68932 Remove redundant explicit TS minimums
  types/agnostic-http-error-handler/package.json
  types/alpinejs/package.json
  types/alpinejs__anchor/package.json
  types/alpinejs__collapse/package.json
  types/alpinejs__focus/package.json
  types/alpinejs__intersect/package.json
  types/alpinejs__mask/package.json
  types/alpinejs__morph/package.json
  types/alpinejs__persist/package.json
  types/cadviewer/package.json
  types/can-autoplay/package.json
  types/dcp-client/package.json
  types/express-healthcheck/package.json
  types/gulp-run/package.json
  types/jsrsasign/package.json
  types/keycloak-connect-roles/package.json
  types/node-red-node-test-helper/package.json
  types/node-red/package.json
  types/node-red__editor-api/package.json
  types/node-red__editor-client/package.json
  types/node-red__registry/package.json
  types/node-red__runtime/package.json
  types/node-red__util/package.json
  types/react-scroll-to-bottom/package.json
  types/rollup-plugin-generate-package-json/package.json
  types/screeps/package.json
  types/scriptable-ios/package.json
  types/statuses/package.json
  types/terraformer__wkt/package.json
  types/treeverse/package.json
  types/wicg-file-system-access/package.json
  types/wicg-web-app-launch/package.json
  types/zingchart/package.json
Labels: Popular package, Owner Approved, Edits multiple packages

#68905 [ssh2] add typings for generateKeyPair(sync)?
  types/ssh2/index.d.ts
  types/ssh2/package.json
  types/ssh2/ssh2-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68937 [eslint-plugin-mocha] Add typings for `eslint-plugin-mocha` package
  types/eslint-plugin-mocha/.npmignore
  types/eslint-plugin-mocha/eslint-plugin-mocha-tests.ts
  types/eslint-plugin-mocha/index.d.ts
  types/eslint-plugin-mocha/package.json
  types/eslint-plugin-mocha/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68788 @types/rsocket-core - Add RSocketError Type
  types/rsocket-core/RSocketError.d.ts
  types/rsocket-core/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#68468 [@types/firefox-webext-browser] #68241 fix type for `browser.runtime.Port.postMessage` argument
  types/firefox-webext-browser/index.d.ts
Labels: Other Approved, Unmerged, Popular package, Self Merge, Maintainer Approved, Untested Change

#68416 [@types/stripe-v3] Remove typings in favour of `@stripe/stripe-js` types
  types/react-stripe-elements/.npmignore
  types/react-stripe-elements/index.d.ts
  types/react-stripe-elements/package.json
  types/react-stripe-elements/react-stripe-elements-tests.tsx
  types/react-stripe-elements/tsconfig.json
  types/stripe-checkout/.npmignore
  types/stripe-checkout/index.d.ts
  types/stripe-checkout/package.json
  types/stripe-checkout/stripe-checkout-tests.ts
  types/stripe-checkout/tsconfig.json
  types/stripe-v3/.eslintrc.json
  types/stripe-v3/.npmignore
  types/stripe-v3/index.d.ts
  types/stripe-v3/package.json
  types/stripe-v3/stripe-v3-tests.ts
  types/stripe-v3/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Check Config

#68956 Definitions for lzma
  types/lzma/.npmignore
  types/lzma/index.d.ts
  types/lzma/lzma-tests.ts
  types/lzma/package.json
  types/lzma/tsconfig.json
Labels: New Definition

#68946 [@types/tiny-segmenter] Add type definitions
  types/tiny-segmenter/.npmignore
  types/tiny-segmenter/index.d.ts
  types/tiny-segmenter/package.json
  types/tiny-segmenter/tiny-segmenter-tests.ts
  types/tiny-segmenter/tsconfig.json
Labels: New Definition

#68958 [defect] export AllReservedOperationsInterface to avoid TS4023 in projects
  types/json-logic-js/index.d.ts
Labels: Owner Approved, Untested Change

#68801 Update react-datepicker definitions with selectsMultiple
  types/react-datepicker/index.d.ts
  types/react-datepicker/package.json
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Critical package, Unreviewed

#68834 [@types/mysql] make the `values` parameter for `format` optional.
  types/mysql/index.d.ts
  types/mysql/mysql-tests.ts
Labels: Critical package, Unreviewed

#68918 [react] Enable Awaited<ReactNode> in experimental release channels
  types/react-dom/test/canary-tests.tsx
  types/react/experimental.d.ts
  types/react/index.d.ts
  types/react/test/experimental.tsx
  types/react/test/index.ts
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/test/experimental.tsx
  types/react/ts5.0/test/index.ts
Labels: Author is Owner, Edits multiple packages, Critical package

#68939 fix: correct type on transaction type
  types/shippo/index.d.ts
  types/shippo/shippo-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#67571 Bump lodash types to 4.17
  types/lodash/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#68703 [@types/pleasanter-web-script] fix AttachmentsHash data type
  types/pleasanter-web-script/index.d.ts
  types/pleasanter-web-script/pleasanter-web-script-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#68969 [node] remove ableist language from crypto module
  types/node/crypto.d.ts
  types/node/v16/crypto.d.ts
  types/node/v18/crypto.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#68976 [@types/httptoolkit__esm] added types for @httptoolkit/esm
  types/httptoolkit__esm/.npmignore
  types/httptoolkit__esm/httptoolkit__esm-tests.ts
  types/httptoolkit__esm/index.d.ts
  types/httptoolkit__esm/package.json
  types/httptoolkit__esm/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68910 AlpineJS: Add optional arg types to Binding functions
  types/alpinejs/alpinejs-tests.ts
  types/alpinejs/index.d.ts
Labels: Self Merge, Owner Approved

#68950 :memo: alpinejs improves JSDoc
  types/alpinejs/alpinejs-tests.ts
  types/alpinejs/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68979 improve object.groupby
  types/object.groupby/auto.d.ts
  types/object.groupby/implementation.d.ts
  types/object.groupby/index.d.mts
  types/object.groupby/object.groupby-tests.ts
  types/object.groupby/package.json
  types/object.groupby/polyfill.d.ts
  types/object.groupby/shim.d.ts
  types/object.groupby/tsconfig.json
Labels: Other Approved, Self Merge, Author is Owner

#68978 [@types/vue-writer] Add type definitions
  types/vue-writer/.npmignore
  types/vue-writer/index.d.ts
  types/vue-writer/package.json
  types/vue-writer/tsconfig.json
  types/vue-writer/vue-writer-tests.ts
Labels: New Definition

#68994 [@types/react] Export JSX namespace from react v17 jsx-runtime.d.ts and jsx-dev-runtime.d.ts
  types/react/v17/jsx-dev-runtime.d.ts
  types/react/v17/jsx-runtime.d.ts
Labels: Critical package, Untested Change

#68861 [node] adds missing ReadableStream.from constructor
  types/node/stream/web.d.ts
  types/node/test/stream.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#68993 [xrm] fix Xrm.Navigation.openFile
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Other Approved, Self Merge

#68999 [react-elemental] Explicitly rely on `ReactElement<any>` in tests
  types/react-elemental/react-elemental-tests.tsx
Labels: Self Merge, Owner Approved

#68742 Dsb/oracle 6.3.0 update
  types/oracledb/index.d.ts
  types/oracledb/package.json
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#68952 [@types/node-telegram-bot-api] Added caption_entities fields to interfaces. ChatId supports BigInt.
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Self Merge, Owner Approved

#69012 @wordpress/block-editor: add missing `templateLock` option
  types/wordpress__block-editor/components/inner-blocks.d.ts
  types/wordpress__block-editor/index.d.ts
  types/wordpress__block-editor/wordpress__block-editor-tests.tsx
Labels: Other Approved, Self Merge

#68904 [pendo-io-browser] Fix pendo guides disabled
  types/pendo-io-browser/index.d.ts
  types/pendo-io-browser/package.json
  types/pendo-io-browser/pendo-io-browser-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68988 feat(tonic-ui/react): Enabled optional name prop on RadioGroupProps
  types/tonic-ui__react/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#68781 fix(readable-stream): missing Readable.from
  types/readable-stream/index.d.ts
  types/readable-stream/readable-stream-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#69000 [react-table] Remove deprecated `ReactFragment`
  types/react-table/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68996 [react-google-login-component] Remove usage of deprecated global React JSX namespace
  types/react-google-login-component/react-google-login-component-tests.tsx
Labels: Other Approved, Self Merge

#69001 [use-double-click] Use modern typings for refs
  types/use-double-click/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69003 [@types/array-to-sentence] Add type definitions
  types/array-to-sentence/.npmignore
  types/array-to-sentence/array-to-sentence-tests.ts
  types/array-to-sentence/index.d.ts
  types/array-to-sentence/package.json
  types/array-to-sentence/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69013 [@types/git-clone] Add missing option type
  types/git-clone/git-clone-tests.ts
  types/git-clone/index.d.ts
Labels: Other Approved, Self Merge, No Other Owners

#69027 [aws-synthetics-puppeteer] Replaced deprecated @types/puppeteer
  types/aws-synthetics-puppeteer/aws-synthetics-puppeteer-tests.ts
  types/aws-synthetics-puppeteer/package.json
  types/aws-synthetics-puppeteer/src/Synthetics.d.ts
Labels: Self Merge, Owner Approved

#68987 [@types/tgwf__co2] Update types to match behaviour
  types/tgwf__co2/co2.d.ts
  types/tgwf__co2/tgwf__co2-tests.ts
Labels: Other Approved, Self Merge

#69018 [@types/k6] fix typo in Redis method name `lpush`
  types/k6/experimental/redis.d.ts
  types/k6/test/redis.ts
Labels: Popular package, Self Merge, Owner Approved

#69024 [OvenPlayer] Fix volumeChanged eventData fields
  types/ovenplayer/index.d.ts
  types/ovenplayer/ovenplayer-tests.ts
Labels: Other Approved, Self Merge

#60822 [react] Add types for `inert` to Experimental release channel
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Author is Owner, Critical package, Unreviewed

#69033 Newly added open capability ZWJSBridge.voicedictation voice Convert text API
  types/zwjsbridge/index.d.ts
  types/zwjsbridge/zwjsbridge-tests.ts
Labels: Other Approved, Self Merge

#69005 Revert "[@types/react] fix: remove onPointerEnterCapture & onPointerLeaveCapture (#68984)
  types/react/v16/index.d.ts
  types/react/v17/index.d.ts
Labels: Owner Approved, Critical package, Untested Change

#69032 feat(sparql-http-client): update to v3
  types/sparql-http-client/BaseClient.d.ts
  types/sparql-http-client/Endpoint.d.ts
  types/sparql-http-client/ParsingClient.d.ts
  types/sparql-http-client/ParsingQuery.d.ts
  types/sparql-http-client/RawQuery.d.ts
  types/sparql-http-client/ResultParser.d.ts
  types/sparql-http-client/SimpleClient.d.ts
  types/sparql-http-client/StreamClient.d.ts
  types/sparql-http-client/StreamQuery.d.ts
  types/sparql-http-client/StreamStore.d.ts
  types/sparql-http-client/index.d.ts
  types/sparql-http-client/package.json
  types/sparql-http-client/sparql-http-client-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#69010 [@types/11ty__eleventy-img] update types to `@11ty/eleventy-img@4.0`
  types/11ty__eleventy-img/11ty__eleventy-img-tests.ts
  types/11ty__eleventy-img/index.d.ts
  types/11ty__eleventy-img/package.json
Labels: Other Approved, Self Merge

#68990 [@types/d3-hierarchy] add x and y to hierarchy node
  types/d3-hierarchy/d3-hierarchy-tests.ts
  types/d3-hierarchy/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#68945 is-map, is-set: remove no-longer-needed types
  types/is-map/.npmignore
  types/is-map/index.d.ts
  types/is-map/is-map-tests.ts
  types/is-map/package.json
  types/is-map/tsconfig.json
  types/is-set/.npmignore
  types/is-set/index.d.ts
  types/is-set/is-set-tests.ts
  types/is-set/package.json
  types/is-set/tsconfig.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#68936 [@types/qs] Compatibility for version 6.12.0.
  types/qs/index.d.ts
  types/qs/qs-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#68998 [react-instantsearch-core] Explicitly rely on `ReactElement<any>` in tests
  types/react-instantsearch-core/react-instantsearch-core-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#68906 dygraphs: Add access to the built in Tickers so they can be used in custom tickers
  types/dygraphs/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69016 Adding `logger` option for `express-fileupload`
  types/express-fileupload/express-fileupload-tests.ts
  types/express-fileupload/index.d.ts
  types/express-fileupload/package.json
Labels: Popular package, Self Merge, Maintainer Approved

#68995 [snappyjs] Add types for snappyjs
  types/snappyjs/.npmignore
  types/snappyjs/index.d.ts
  types/snappyjs/package.json
  types/snappyjs/snappyjs-tests.ts
  types/snappyjs/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68373 Update Braintree NonceDetails
  types/braintree/index.d.ts
  types/braintree/package.json
Labels: Other Approved, Unmerged, Self Merge, Maintainer Approved, Untested Change, Edits Owners

#69031 Update index.d.ts
  types/zwjsbridge/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#68963 Definitions for cbor-js
  types/cbor-js/.npmignore
  types/cbor-js/cbor-js-tests.ts
  types/cbor-js/index.d.ts
  types/cbor-js/package.json
  types/cbor-js/tsconfig.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#69047 Patch 1
  types/zwjsbridge/index.d.ts
  types/zwjsbridge/package.json
  types/zwjsbridge/zwjsbridge-tests.ts
Labels: Self Merge, Owner Approved, Edits Owners

#68871 #68869 Fix @types/pg types enforce users to define query config values as array of any
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69049 [@types/zwjsbridge] fix: lint
  types/zwjsbridge/index.d.ts
  types/zwjsbridge/package.json
  types/zwjsbridge/zwjsbridge-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69048 [@types/fast-fifo] add length to FastFIFO class
  types/fast-fifo/fast-fifo-tests.ts
  types/fast-fifo/index.d.ts
  types/fast-fifo/package.json
Labels: Other Approved, Self Merge

#68780 Put `asserts` on various `assert*` functions in chai.
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69042 k6: remove inactive maintainer
  types/k6/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#68953 [@types/eslint] Add rule definitions and update
  types/eslint/rules/best-practices.d.ts
  types/eslint/rules/ecmascript-6.d.ts
  types/eslint/rules/possible-errors.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#69026 [@types/node-telegram-bot-api] InputMediaBase caption_entities
  types/node-telegram-bot-api/index.d.ts
  types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
Labels: Other Approved, Self Merge, Owner Approved

#69021 [@types/node] Update docs for `wasi`
  types/node/v16/wasi.d.ts
  types/node/v18/wasi.d.ts
  types/node/wasi.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package, Untested Change

#69046 feat: add action param to @types/grecaptcha
  types/grecaptcha/grecaptcha-tests.ts
  types/grecaptcha/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69052 [@types/node-telegram-bot-api] Update owners - remove myself
  types/node-telegram-bot-api/package.json
Labels: Other Approved, Self Merge, Author is Owner, Owner Approved

#69037 feat(@rdfjs/to-ntriples): updated to ESM
  types/rdfjs__to-ntriples/index.d.ts
  types/rdfjs__to-ntriples/lib/blankNode.d.ts
  types/rdfjs__to-ntriples/lib/dataset.d.ts
  types/rdfjs__to-ntriples/lib/defaultGraph.d.ts
  types/rdfjs__to-ntriples/lib/literal.d.ts
  types/rdfjs__to-ntriples/lib/namedNode.d.ts
  types/rdfjs__to-ntriples/lib/quad.d.ts
  types/rdfjs__to-ntriples/lib/term.d.ts
  types/rdfjs__to-ntriples/lib/variable.d.ts
  types/rdfjs__to-ntriples/package.json
  types/rdfjs__to-ntriples/rdfjs__to-ntriples-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68881 [@types/bun] Update `@types/bun` to point to `bun-types@1.0.30`
  types/bun/package.json
Labels: Popular package, Self Merge, Owner Approved

#69008 [@types/bun] Update `@types/bun` to point to `bun-types@1.0.31`
  types/bun/package.json
Labels: Popular package, Self Merge, Owner Approved

#69039 [@types/bun] Update `@types/bun` to point to `bun-types@1.0.32`
  types/bun/package.json
Labels: Popular package, Self Merge, Owner Approved

#69040 [@types/bun] Update `@types/bun` to point to `bun-types@1.0.33`
  types/bun/package.json
Labels: Popular package, Self Merge, Owner Approved

#68982 Adds fixes to @WP/block-editor
  types/wordpress__block-editor/components/block-controls.d.ts
  types/wordpress__block-editor/components/inner-blocks.d.ts
  types/wordpress__block-editor/components/rich-text.d.ts
  types/wordpress__block-editor/wordpress__block-editor-tests.tsx
Labels: Other Approved, Self Merge

#68942 [jqueryui] add `ResizableOptions.classes`, improve `ResizableOptions.aspectRatio`.
  types/jqueryui/index.d.ts
  types/jqueryui/jqueryui-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69058 [@types/get-size] Add missing `isBorderBox` property
  types/get-size/get-size-tests.ts
  types/get-size/index.d.ts
Labels: Self Merge, Owner Approved

#69055 Clean up GHA workflows a bit
  .github/workflows/daily.yml
  .github/workflows/ghostbuster.yml
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#69063 Use deploy key instead of PAT to run dprint
  .github/workflows/format-and-commit.yml
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#69060 Revert "Put `asserts` on various `assert*` functions in chai."
  types/chai/chai-tests.ts
  types/chai/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69064 Add fromfile_prefix_chars to ArgumentParserOptions in argparse
  types/argparse/argparse-tests.ts
  types/argparse/index.d.ts
Labels: Self Merge, Owner Approved, Critical package

#69072 [react-dom-factories] Stop implicit return in ref callback
  types/react-dom-factories/react-dom-factories-tests.ts
Labels: Self Merge, Owner Approved

#69069 [create-react-class] Stop implicit return in ref callback
  types/create-react-class/create-react-class-tests.ts
Labels: Self Merge, Owner Approved

#68865 [@types/relationship.js] Update the types declarations exported from …
  types/relationship.js/dist/relationship-mode.min.d.ts
  types/relationship.js/package.json
  types/relationship.js/relationship.js-tests.ts
Labels: Unmerged, Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#69080 [react-native-modalbox] Stop implicit return in ref callback
  types/react-native-modalbox/react-native-modalbox-tests.tsx
Labels: Self Merge, Owner Approved

#69068 `superagent`: `Response#get` may return `undefined`
  types/superagent/lib/node/response.d.ts
  types/superagent/superagent-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#69056 [@types/rrdir] Update types to 13.0.0
  types/rrdir/index.d.ts
  types/rrdir/package.json
  types/rrdir/rrdir-tests.ts
  types/rrdir/test/rrdir-tests.cjs.ts
  types/rrdir/tsconfig.json
Labels: Other Approved, Self Merge

#69079 [react-native-material-menu] Stop implicit return in ref callback
  types/react-native-material-menu/react-native-material-menu-tests.tsx
Labels: Other Approved, Self Merge, Owner Approved

#69070 [react-alert] Stop implicit return in ref callback
  types/react-alert/v2/react-alert-tests.tsx
Labels: Other Approved, Self Merge, Owner Approved

#69077 [react-native-ad-manager] Stop implicit return in ref callback
  types/react-native-ad-manager/test/NativeAdView.tsx
Labels: Other Approved, Self Merge

#69088 [reactabular-sticky] Stop implicit return in ref callback
  types/reactabular-sticky/reactabular-sticky-tests.tsx
Labels: Other Approved, Self Merge

#69071 [react-codemirror] Stop implicit return in ref callback
  types/react-codemirror/react-codemirror-tests.tsx
Labels: Other Approved, Self Merge

#69084 [react-smooth-scrollbar] Stop implicit return in ref callback
  types/react-smooth-scrollbar/react-smooth-scrollbar-tests.tsx
Labels: Other Approved, Self Merge

#69061 [@uswds/uswds]: Synchronize exports across entrypoints, bump to 3.8.0
  types/uswds__uswds/index.d.ts
  types/uswds__uswds/package.json
  types/uswds__uswds/src/js/components/index.d.ts
  types/uswds__uswds/uswds__uswds-tests.ts
Labels: Other Approved, Self Merge, Author is Owner
