Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2024-02, with the labels that each got.

#68412 [@types/react] Added comments to React.ComponentProps
  types/react/index.d.ts
Labels: Critical package, Untested Change

#68409 [@types/react] Wrote JSDoc comments for React.FC and related types
  types/react/index.d.ts
Labels: Critical package, Untested Change

#68410 [@types/react] Added JSDoc comments to forwardRef
  types/react/index.d.ts
Labels: Critical package, Untested Change

#68417 [googletag] Update the definition of SlotsSettingsConfig
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68415 [@types/react] Made various small improvements to React JSDoc comments
  types/react/index.d.ts
Labels: Critical package, Untested Change

#68213 net: Support lookup of one address in `net.LookupFunction` (`autoSelectFamily: false`)
  types/node/net.d.ts
  types/node/test/http.ts
  types/node/test/https.ts
  types/node/test/net.ts
  types/node/ts4.8/net.d.ts
  types/node/ts4.8/test/http.ts
  types/node/ts4.8/test/https.ts
  types/node/ts4.8/test/net.ts
  types/node/v18/net.d.ts
  types/node/v18/test/net.ts
  types/node/v18/ts4.8/net.d.ts
  types/node/v18/ts4.8/test/net.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#68419 [@types/react] More miscellaneous changes to React's JSDoc typings
  types/react/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#68210 [chrome] Add `optional_host_permissions`
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#68422 [@types/jest] Fix some typos in comments
  types/jest/index.d.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#68429 Fix artifact name in new sharded GHA workflow
  .github/workflows/CI.yml
Labels: Edits Infrastructure

#68428 Pass --diffBase to test-all
  .github/workflows/CI.yml
Labels: Edits Infrastructure

#68431 Fix GHA nightly run matrixes
  .github/workflows/CI.yml
  scripts/get-ci-matrix.js
Labels: Edits Infrastructure

#68433 [vscode] disable @typescript-eslint/array-type
  types/vscode/.eslintrc.json
Labels: Popular package, Check Config

#68430 Remove --depth from git clone instructions in README
  README.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68331 TypeScript definitions for npm:iyzipay module
  types/iyzipay/.npmignore
  types/iyzipay/index.d.ts
  types/iyzipay/iyzipay-tests.ts
  types/iyzipay/package.json
  types/iyzipay/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68426 [three] Fix PerspectiveCamera.getViewSize()
  types/three/src/cameras/PerspectiveCamera.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#68393 [@types/payu-emea-sdk] Update types for changes in sdk
  types/payu-emea-sdk/index.d.ts
  types/payu-emea-sdk/package.json
  types/payu-emea-sdk/payu-emea-sdk-tests.ts
  types/payu-emea-sdk/tsconfig.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#68413 [mssql] Update Request properties
  types/mssql/index.d.ts
  types/mssql/mssql-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68445 feat: relax TermSet#has
  types/rdfjs__term-set/index.d.ts
  types/rdfjs__term-set/rdfjs__term-set-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68219 fix: import of jsonld
  types/rdfjs__serializer-jsonld-ext/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#68446 feat: relax TermMap#has and TermMap#get
  types/rdfjs__term-map/index.d.ts
  types/rdfjs__term-map/rdfjs__term-map-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68390 Add basic types for sub-encoder
  types/sub-encoder/.npmignore
  types/sub-encoder/index.d.ts
  types/sub-encoder/package.json
  types/sub-encoder/sub-encoder-tests.ts
  types/sub-encoder/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68452 Update Plotly.js Sankey Diagram for v2.29.0
  types/plotly.js/lib/traces/sankey.d.ts
  types/plotly.js/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#68443 [@types/react] Continued adding JSDoc comments to React types
  types/react/index.d.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#68267 [@types/dxf] Add missing `width` and `height` definition to Box2
  types/dxf/Utils.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#68449 [@types/basic-auth] Add `undefined` type to `authorization` property
  types/basic-auth/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68333 [webxr] Fixed XRMesh interface and added detectedMeshes to XRFrame
  types/webxr/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68381 [@types/express-serve-static-core] Fix `Request.accepts()` example
  types/express-serve-static-core/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#68435 [npm:@types/iyzipay] Small Namespace Variable Names' Update
  types/iyzipay/index.d.ts
  types/iyzipay/iyzipay-tests.ts
  types/iyzipay/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#68438 Add types for big-sparse-array
  types/big-sparse-array/.npmignore
  types/big-sparse-array/big-sparse-array-tests.ts
  types/big-sparse-array/index.d.ts
  types/big-sparse-array/package.json
  types/big-sparse-array/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68465 [telegram-web-app] Update Telegram Web App to API 7.0
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/package.json
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68447 [@types/node-schedule] Update typings
  types/node-schedule/index.d.ts
  types/node-schedule/node-schedule-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68387 Update types for yauzl-promise to add AsyncIterable support
  types/yauzl-promise/index.d.ts
  types/yauzl-promise/yauzl-promise-tests.ts
Labels: Self Merge, Maintainer Approved, No Other Owners

#68408 [scriptable-ios] add Data.fromBytes and fix typos
  types/scriptable-ios/index.d.ts
  types/scriptable-ios/scriptable-ios-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#68477 add missing read.missing_required_field log event to relay-runtime
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#68464 [react] Backport recent changes to fork for TypeScript <= 5.0
  types/react/ts5.0/index.d.ts
Labels: Other Approved, Author is Owner, Critical package, Untested Change

#68479 feat(sanitize-html): update types to 2.11 with nonBooleanAttributes
  types/sanitize-html/index.d.ts
  types/sanitize-html/package.json
  types/sanitize-html/sanitize-html-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#68462 [meteor] Showcase modern usage of react-dom
  types/meteor/test/server-render.tsx
Labels: Self Merge, Owner Approved

#68459 [@types/react] Added many changes to @types/react JSDocs
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#68473 [@types/validator] Update isMACAddress typings
  types/validator/index.d.ts
  types/validator/validator-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#68474 Change last name for kryops
  types/assets-webpack-plugin/package.json
  types/browser-bunyan/package.json
  types/hpp/package.json
  types/pdfmake/package.json
  types/smoothscroll-polyfill/package.json
  types/webpack-bundle-analyzer/package.json
  types/webpack-bundle-analyzer/v3/package.json
  types/webpack-dotenv-plugin/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits multiple packages, Maintainer Approved

#68471 [pdfmake] Add QR code padding and document language
  types/pdfmake/interfaces.d.ts
  types/pdfmake/test/pdfmake-examples-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#68496 splitting.js | update Splitting() return type (Result -> Result[])
  types/splitting/index.d.ts
  types/splitting/splitting-tests.ts
Labels: Self Merge, Owner Approved

#68282 Fix #68281 [@types/react-datepicker] Add a new prop toggleCalendarOnIconClick
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#68487 [tabulator-tables] add missing download callback options, update comment
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#68499 [@types/react] Added more JSDoc comments to memo, lazy, ReactElement
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#68491 [@types/bun] Update `@types/bun` to point to `bun-types@1.0.26`
  types/bun/package.json
Labels: Self Merge, Owner Approved

#68500 Simplify react-shadow-dom-retarget-events tests
  types/react-shadow-dom-retarget-events/package.json
  types/react-shadow-dom-retarget-events/react-shadow-dom-retarget-events-tests.ts
  types/react-shadow-dom-retarget-events/react-shadow-dom-retarget-events-tests.tsx
  types/react-shadow-dom-retarget-events/tsconfig.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68432 Update react-simple-tooltip to accept all valid React props
  attw.json
  types/react-simple-tooltip/index.d.ts
  types/react-simple-tooltip/package.json
  types/react-simple-tooltip/react-simple-tooltip-tests.tsx
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Edits Owners

#68513 [postcss-sass] Add types for postcss-sass
  types/postcss-sass/.npmignore
  types/postcss-sass/index.d.ts
  types/postcss-sass/package.json
  types/postcss-sass/parse.d.ts
  types/postcss-sass/postcss-sass-tests.ts
  types/postcss-sass/stringify.d.ts
  types/postcss-sass/tsconfig.json
  types/postcss-sass/tslint.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#68497 [npm:@types/iyzipay] Updated some of the interface names & Exported all Interfaces in the namespace
  types/iyzipay/index.d.ts
  types/iyzipay/iyzipay-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#68515 [@types/langs]: add missing literals to union type, closes #68508
  types/langs/index.d.ts
  types/langs/langs-tests.ts
Labels: Self Merge, Owner Approved

#68519 Update dependabot config to match TS
  .github/dependabot.yml
Labels: Edits Infrastructure

#68517 Update packages to new username (@leonsilicon)
  types/ansi-align/package.json
  types/console-clear/package.json
  types/get-size/package.json
  types/is-async-function/package.json
  types/is-file-esm/package.json
  types/markdown-it-footnote/package.json
  types/style-inject/package.json
  types/typedarray-to-buffer/package.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved

#68524 [atlassian-connect-js] Add overloads for AP.resize and AP.history.getState
  types/atlassian-connect-js/atlassian-connect-js-tests.ts
  types/atlassian-connect-js/index.d.ts
Labels: Self Merge, Owner Approved

#68526 Dsb/oracle 6.1.0
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
  types/oracledb/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#68312 [@types/react] Render functions should accept ReactNode instead of ReactElement
  types/react-dom/server.d.ts
  types/react-dom/test/react-dom-tests.tsx
Labels: Self Merge, Owner Approved, Critical package

#68344 [d3-path] Add pathRound function definition
  types/d3-path/d3-path-tests.ts
  types/d3-path/index.d.ts
  types/d3-path/package.json
Labels: Self Merge, Owner Approved, Critical package

#68531 Skip trying pnpm partial install pack when react stuff is modified
  scripts/pnpm-install.sh
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68509 [webpack-bundle-analyzer] Add isInitialByEntrypoint to JSON report data
  types/webpack-bundle-analyzer/index.d.ts
  types/webpack-bundle-analyzer/package.json
  types/webpack-bundle-analyzer/webpack-bundle-analyzer-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#68546 Increase sharding to 12 shards, at least 100 packages per shard
  scripts/get-ci-matrix.js
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68541 [react-flags-select] Remove usage of deprecated string refs in tests
  types/react-flags-select/react-flags-select-tests.tsx
Labels: Other Approved, Self Merge

#68314 [@ember/runloop] Add `Timer` to `@ember/runloop` exports
  types/ember__runloop/ember__runloop-tests.ts
  types/ember__runloop/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68222 [@types/chroma-js] Add `chroma.brewer.Viridis` type definition
  types/chroma-js/chroma-js-tests.ts
  types/chroma-js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#68537 [react-bootstrap] Remove usage of deprecated string refs in tests
  types/react-bootstrap/test/react-bootstrap-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#68130 feat(fabric): add `Gamma` & `Vibrance` filters #62371
  types/fabric/fabric-impl.d.ts
  types/fabric/package.json
  types/fabric/test/index.ts
Labels: Popular package, Self Merge, Maintainer Approved

#68552 Document how to install @scoped typings
  README.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68504 [@types/gtag.js] Update types for consent mode `v2`
  types/gtag.js/gtag.js-tests.ts
  types/gtag.js/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#68532 Oracledb - added types for 6.2.0
  types/oracledb/index.d.ts
  types/oracledb/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change, Edits Owners

#68216 [@types/culori] Update type definitions for `clampChroma()`
  types/culori/fn/index.d.ts
  types/culori/index.d.ts
  types/culori/package.json
  types/culori/src/clamp.d.ts
  types/culori/src/common.d.ts
  types/culori/test/clamp.test.ts
  types/culori/tsconfig.json
Labels: Self Merge, Maintainer Approved

#68355 [@types/mpv-script] Update types for `mp.command_native`
  types/mpv-script/index.d.ts
  types/mpv-script/mpv-script-tests.ts
Labels: Self Merge, Owner Approved

#68554 Add CampaignsFolder and new functions in Campaigns for mailchimp__marketing
  types/mailchimp__mailchimp_marketing/index.d.ts
  types/mailchimp__mailchimp_marketing/mailchimp__mailchimp_marketing-tests.ts
Labels: Other Approved, Self Merge

#68539 [react-data-grid] Remove usage of deprecated string refs in tests
  types/react-data-grid/react-data-grid-tests.tsx
  types/react-data-grid/v1/react-data-grid-tests.tsx
  types/react-data-grid/v2/react-data-grid-tests.tsx
Labels: Self Merge, Owner Approved

#68549 [WebXR] Add detectedPlanes, improve detectedMeshes, add tests
  types/webxr/index.d.ts
  types/webxr/webxr-tests.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#68264 [@types/node] Update `v8` type definitions
  types/node/test/v8.ts
  types/node/ts4.8/test/v8.ts
  types/node/ts4.8/v8.d.ts
  types/node/v16/test/v8.ts
  types/node/v16/ts4.8/test/v8.ts
  types/node/v16/ts4.8/v8.d.ts
  types/node/v16/v8.d.ts
  types/node/v18/test/v8.ts
  types/node/v18/ts4.8/test/v8.ts
  types/node/v18/ts4.8/v8.d.ts
  types/node/v18/v8.d.ts
  types/node/v8.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#68561 Add hoist-workspace-packages=false in prep for pnpm v9
  .npmrc
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68562 Attempt to get people to not use the issue tracker for package problems
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/infrastructure_issue.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68563 Update pnpm/action-setup to v3
  .github/workflows/CI.yml
  .github/workflows/UpdateCodeowners.yml
  .github/workflows/format-and-commit.yml
  .github/workflows/ghostbuster.yml
  .github/workflows/lint-md.yml
  .github/workflows/pnpm-cache.yml
  .github/workflows/support-window.yml
Labels: Edits Infrastructure

#68567 [pdfkit] add string type for image links
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68548 Update to interface Action of the @types/google-apps-script package
  types/google-apps-script/google-apps-script.card-service.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68560 [@types/mercadopago-sdk-js] feat: Add new prop additionalInformation of shipping
  types/mercadopago-sdk-js/mercadopago-sdk-js-tests.ts
  types/mercadopago-sdk-js/modules/bricks.d.ts
Labels: Other Approved, Self Merge

#68460 fix(backbone): do not import `underscore` as namespace
  types/backbone/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#68571 [mixpanel-browser] Update typings for v2.49.0
  types/mixpanel-browser/index.d.ts
  types/mixpanel-browser/mixpanel-browser-tests.ts
  types/mixpanel-browser/package.json
Labels: Popular package, Self Merge, Owner Approved

#68574 Add types for react native dialog input
  types/react-native-dialog-input/.npmignore
  types/react-native-dialog-input/index.d.ts
  types/react-native-dialog-input/package.json
  types/react-native-dialog-input/react-native-dialog-input-tests.tsx
  types/react-native-dialog-input/tsconfig.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#68478 bitcoin-computer__lib types update
  types/bitcoin-computer__lib/index.d.ts
  types/bitcoin-computer__lib/package.json
  types/bitcoin-computer__lib/tslint.json
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Check Config, No Other Owners, Edits Owners

#68584 Update author for type declaration
  types/react-native-dialog-input/package.json
Labels: Other Approved, Self Merge

#68573 [npm:@types/iyzipay] Updated naming of a one function - Small Error
  types/iyzipay/index.d.ts
  types/iyzipay/iyzipay-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68218 oidc-provider: add args to default resource indicator
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Self Merge, Owner Approved

#68569 fix(semver): add `toString` override to make eslint happy
  types/semver/classes/semver.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package, Untested Change

#68588 Format markdown with dprint
  .dprint.jsonc
  .github/ISSUE_TEMPLATE/infrastructure_issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .vscode/settings.template.json
  README.es.md
  README.fr.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
  docs/admin.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#68455 Update PackageJson type in @npmcli/package-json
  types/npmcli__package-json/index.d.ts
  types/npmcli__package-json/npmcli__package-json-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#68551 [@types/css-tree] Add formattedMessage to SyntaxParseError
  types/css-tree/css-tree-tests.ts
  types/css-tree/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68536 [react-bootstrap-table] Remove usage of deprecated string refs in tests
  types/react-bootstrap-table/react-bootstrap-table-tests.tsx
Labels: Other Approved, Self Merge

#68535 [react-blessed] Remove usage of deprecated string refs in tests
  types/react-blessed/react-blessed-tests.tsx
Labels: Other Approved, Self Merge

#68540 [react-datagrid] Remove usage of deprecated string refs in tests
  types/react-datagrid/react-datagrid-tests.tsx
Labels: Other Approved, Self Merge

#68593 [plotly.js] allow `offset` to be `number[]`
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68273 feat: support `punycode` js file imports
  types/punycode/punycode-tests.ts
  types/punycode/punycode.d.ts
  types/punycode/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved

#68564 Update dprint and restore ember formatting
  .dprint.jsonc
  types/ember/test/create.ts
  types/ember/v3/test/create.ts
Labels: Popular package, Owner Approved, Edits Infrastructure

#68566 [ember] Make Transition.to nullable
  types/ember__routing/test/router-service.ts
  types/ember__routing/test/router.ts
  types/ember__routing/transition.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68609 Remove old tslint.json files
  types/bitcoin-computer__lib/tslint.json
  types/pleasanter-web-script/tslint.json
  types/postcss-sass/tslint.json
  types/twitter-text/tslint.json
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Check Config

#68597 [@types/lolcatjs] Add type for `lolcatjs`
  types/lolcatjs/.npmignore
  types/lolcatjs/index.d.ts
  types/lolcatjs/lolcatjs-tests.ts
  types/lolcatjs/package.json
  types/lolcatjs/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68599 [mapbox-gl] Add `reload` method to `VectorSourceImpl` and `RasterSource`.
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68364 Update @tgwf/co2js 0.14.2
  types/tgwf__co2/hosting.d.ts
  types/tgwf__co2/package.json
  types/tgwf__co2/tgwf__co2-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68427 fix: teardown overload order in hosted-fields.d.ts
  types/braintree-web/hosted-fields.d.ts
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#68538 [react-cropper] Remove usage of deprecated string refs in tests
  types/react-cropper/react-cropper-tests.tsx
Labels: Other Approved, Self Merge, Owner Approved

#68613 [tabulator-tables] Fix parameter order error issue.
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#68437 [@types/react-datepicker] Update types for v6.0
  types/react-datepicker/index.d.ts
  types/react-datepicker/package.json
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#68618 Sync frida-gum typings with Frida 16.1.12
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
  types/frida-gum/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#68559 Update to interface TextButton of the @types/google-apps-script package
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#68612 [@types/oojs-ui] Sync with upstream OOUI 0.49.0
  types/oojs-ui/ButtonInputWidget.d.ts
  types/oojs-ui/OO.ui.d.ts
  types/oojs-ui/README.MD
  types/oojs-ui/SelectFileInputWidget.d.ts
  types/oojs-ui/SelectFileWidget.d.ts
  types/oojs-ui/index.d.ts
  types/oojs-ui/mixin/LabelElement.d.ts
  types/oojs-ui/oojs-ui-tests.ts
  types/oojs-ui/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Check Config

#68484 [@types/pubnub] Update type definitions
  types/pubnub/index.d.ts
  types/pubnub/pubnub-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#68522 [jsdom-screenshot] add missing options to GenerateImageOptions
  types/jsdom-screenshot/index.d.ts
  types/jsdom-screenshot/jsdom-screenshot-tests.ts
  types/jsdom-screenshot/package.json
Labels: Self Merge, Owner Approved

#68385 [@types/applepayjs] Adding coupon code related types
  types/applepayjs/applepayjs-tests.ts
  types/applepayjs/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68632 [chromium-installation-events] Improve types
  types/dom-chromium-installation-events/dom-chromium-installation-events-tests.ts
  types/dom-chromium-installation-events/index.d.ts
Labels: Self Merge, Owner Approved

#68450 add react-datepicker prop renderYearContent
  types/react-datepicker/index.d.ts
  types/react-datepicker/react-datepicker-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#68141 update(node): add 'BlockList.rules'
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/ts4.8/net.d.ts
  types/node/ts4.8/test/net.ts
  types/node/v16/net.d.ts
  types/node/v16/test/net.ts
  types/node/v16/ts4.8/net.d.ts
  types/node/v16/ts4.8/test/net.ts
  types/node/v18/net.d.ts
  types/node/v18/test/net.ts
  types/node/v18/ts4.8/net.d.ts
  types/node/v18/ts4.8/test/net.ts
Labels: Self Merge, Owner Approved, Critical package

#68595 Add types for `dockerode-compose`
  types/dockerode-compose/.npmignore
  types/dockerode-compose/dockerode-compose-tests.ts
  types/dockerode-compose/index.d.ts
  types/dockerode-compose/package.json
  types/dockerode-compose/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68660 [@types/applepayjs] Updating paymentRequest and all complete methods
  types/applepayjs/applepayjs-tests.ts
  types/applepayjs/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68637 add `object.assign`
  types/object.assign/.npmignore
  types/object.assign/auto.d.ts
  types/object.assign/implementation.d.ts
  types/object.assign/index.d.ts
  types/object.assign/object.assign-tests.ts
  types/object.assign/package.json
  types/object.assign/polyfill.d.ts
  types/object.assign/shim.d.ts
  types/object.assign/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68665 Added missing ready function on Turnstile interface for @types/cloudflare-turnstile
  types/cloudflare-turnstile/cloudflare-turnstile-tests.ts
  types/cloudflare-turnstile/index.d.ts
Labels: Self Merge, Owner Approved

#68662 Add `LaunchHandler` to `WebAppManifest`
  types/web-app-manifest/index.d.ts
  types/web-app-manifest/web-app-manifest-tests.ts
Labels: Self Merge, Owner Approved

#68418 [@types/sortablejs](fix) Fix the MultiDragOptions' error
  types/sortablejs/plugins.d.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved, Untested Change

#68658 [googletag] Add support for publisher provided signals
  types/googletag/googletag-tests.ts
  types/googletag/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#68669 Update attw.json with failures
  attw.json
Labels: Edits Infrastructure

#68656 React Element Type Definition - Add Type Definition for element `set`
  types/react/global.d.ts
  types/react/index.d.ts
  types/react/ts5.0/global.d.ts
  types/react/ts5.0/index.d.ts
Labels: Owner Approved, Critical package, Untested Change

#68670 [@types/bun] Update `@types/bun` to point to `bun-types@1.0.27`
  types/bun/package.json
Labels: Self Merge, Maintainer Approved

#68667 fix(aws-lambda): mark as non-npm and remove from `attr.json`
  attw.json
  types/aws-lambda/package.json
Labels: Self Merge, Maintainer Approved, Critical package

#68523 @types/dotenv-safe: add missing path option
  types/dotenv-safe/dotenv-safe-tests.ts
  types/dotenv-safe/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68631 chore: update yauzl-promise type definitions for v4.0
  types/yauzl-promise/index.d.ts
  types/yauzl-promise/package.json
  types/yauzl-promise/yauzl-promise-tests.ts
Labels: Self Merge, Maintainer Approved, No Other Owners

#68659 [@types/mpv-script] Update types for `mp.add_key_binding`
  types/mpv-script/index.d.ts
  types/mpv-script/mpv-script-tests.ts
Labels: Self Merge, Owner Approved

#68233 fix(tryghost__content-api): add makeRequest parameter
  types/tryghost__content-api/index.d.ts
  types/tryghost__content-api/tryghost__content-api-tests.ts
Labels: Unmerged, Self Merge, Maintainer Approved

#68525 [npm: @types/json2xls] Add Type Definitions for json2xls
  types/json2xls/.npmignore
  types/json2xls/index.d.ts
  types/json2xls/json2xls-tests.ts
  types/json2xls/package.json
  types/json2xls/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68691 New types: uri-template-route
  types/uri-template-route/.npmignore
  types/uri-template-route/index.d.ts
  types/uri-template-route/package.json
  types/uri-template-route/tsconfig.json
  types/uri-template-route/uri-template-route-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#68652 [@torchlight-api/torchlight-cli] Add type definitions
  types/torchlight-api__torchlight-cli/.npmignore
  types/torchlight-api__torchlight-cli/index.d.ts
  types/torchlight-api__torchlight-cli/package.json
  types/torchlight-api__torchlight-cli/torchlight-api__torchlight-cli-tests.ts
  types/torchlight-api__torchlight-cli/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68594 feat: Add typing to `InputHTMLAttributes` autoComplete to `react` package from the official TS library
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
Labels: Owner Approved, Critical package, Untested Change

#68601 Add type definitions for Yandex.Games SDK
  types/ysdk/.npmignore
  types/ysdk/index.d.ts
  types/ysdk/package.json
  types/ysdk/tsconfig.json
  types/ysdk/ysdk-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#68689 [react-lazyload-youtube] Add types for react-lazyload-youtube
  types/react-lazyload-youtube/.npmignore
  types/react-lazyload-youtube/index.d.ts
  types/react-lazyload-youtube/index.modern.d.ts
  types/react-lazyload-youtube/package.json
  types/react-lazyload-youtube/react-lazyload-youtube-tests.tsx
  types/react-lazyload-youtube/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68698 fix(rdfjs/fetch): preserve return dataset type
  types/rdfjs__fetch-lite/Factory.d.ts
  types/rdfjs__fetch-lite/rdfjs__fetch-lite-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68700 Added on and off instrument functions, added more documentation
  types/gorilla-engine/components/AmpEnv.d.ts
  types/gorilla-engine/components/BarStepEditor.d.ts
  types/gorilla-engine/components/ComboBox.d.ts
  types/gorilla-engine/components/DragContainer.d.ts
  types/gorilla-engine/components/DragTarget.d.ts
  types/gorilla-engine/components/DropZone.d.ts
  types/gorilla-engine/components/Knob.d.ts
  types/gorilla-engine/components/Label.d.ts
  types/gorilla-engine/components/LevelMeter.d.ts
  types/gorilla-engine/components/ListBox.d.ts
  types/gorilla-engine/components/LottieAnimation.d.ts
  types/gorilla-engine/components/MidiKeyboard.d.ts
  types/gorilla-engine/components/Pad.d.ts
  types/gorilla-engine/components/Rubberband.d.ts
  types/gorilla-engine/components/ScrollView.d.ts
  types/gorilla-engine/components/SliceEditor.d.ts
  types/gorilla-engine/components/Slider.d.ts
  types/gorilla-engine/components/StepEditor.d.ts
  types/gorilla-engine/components/TagBrowser.d.ts
  types/gorilla-engine/components/TagEditor.d.ts
  types/gorilla-engine/components/Toggle.d.ts
  types/gorilla-engine/components/Trigger.d.ts
  types/gorilla-engine/components/Waveform.d.ts
  types/gorilla-engine/components/Window.d.ts
  types/gorilla-engine/components/XYPad.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68672 @ember/template: add SafeString type export to align with types shipped by ember-source itself
  types/ember__template/ember__template-tests.ts
  types/ember__template/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#68701 [tabulator-tables] Fix RowLookup, selectRow and deselectRow signatures.
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#68654 Fix depency version in `dockerode-compose`
  types/dockerode-compose/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#68614 [Oneline] - Add type definition
  types/pxr-oneline/.npmignore
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/oneline-tests.ts
  types/pxr-oneline/package.json
  types/pxr-oneline/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68688 [google-apps-script] add missing range and pivottable methods
  types/google-apps-script/google-apps-script.spreadsheet.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#68708 Fix arethetypeswrong issues after version upgrade
  attw.json
  notNeededPackages.json
  types/complex.js/.npmignore
  types/complex.js/complex.js-tests.ts
  types/complex.js/index.d.ts
  types/complex.js/package.json
  types/complex.js/tsconfig.json
  types/nightwatch/index.d.ts
  types/nightwatch/lib/core/client.d.ts
  types/nightwatch/lib/runner/cli/cli.d.ts
  types/nightwatch/package.json
  types/nightwatch/test/testProgrammaticApi.ts
  types/tgwf__co2/data/average-intensities.min.d.ts
  types/tgwf__co2/data/marginal-intensities-2021.min.d.ts
  types/tgwf__co2/index.d.mts
  types/tgwf__co2/index.d.ts
  types/tgwf__co2/package.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Check Config

#68550 Add types for @mapbox/whoots-js
  types/mapbox__whoots-js/.npmignore
  types/mapbox__whoots-js/index.d.ts
  types/mapbox__whoots-js/mapbox__whoots-js-tests.ts
  types/mapbox__whoots-js/package.json
  types/mapbox__whoots-js/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#68725 GENG-928 documentation of parameter controlType
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#68470 [@types/node] Update type definitions for `node:buffer`
  types/node/buffer.d.ts
  types/node/test/buffer.ts
  types/node/ts4.8/buffer.d.ts
  types/node/ts4.8/test/buffer.ts
  types/node/v16/buffer.d.ts
  types/node/v16/test/buffer.ts
  types/node/v16/ts4.8/buffer.d.ts
  types/node/v16/ts4.8/test/buffer.ts
  types/node/v18/buffer.d.ts
  types/node/v18/test/buffer.ts
  types/node/v18/ts4.8/buffer.d.ts
  types/node/v18/ts4.8/test/buffer.ts
Labels: Self Merge, Maintainer Approved, Critical package

#68619 eslint: tweak documentation for rule meta properties
  types/eslint/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#68620 eslint: add owner
  types/eslint/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package
