Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2024-07, with the labels that each got.

#69686 Update index.d.ts
  types/drawflow/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Untested Change

#69968 Change mergebot links in README
  README.es.md
  README.fr.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
Labels: Edits Infrastructure

#69866 Allow react resizable axis prop to have type none
  types/react-resizable/index.d.ts
  types/react-resizable/react-resizable-tests.tsx
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#69833 [better-sqlite3] Add VirtualTableOptions rows params
  types/better-sqlite3/better-sqlite3-tests.ts
  types/better-sqlite3/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69921 [Poool-engage] - Add types for poool Engage
  types/poool-engage/.npmignore
  types/poool-engage/index.d.ts
  types/poool-engage/package.json
  types/poool-engage/poool-engage-tests.ts
  types/poool-engage/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69969 [sharedb] Add emitter types to `MilestoneDB`
  types/sharedb/index.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69973 Clerk.io Fix wrong base response key
  types/clerk.io/clerk.io-tests.ts
  types/clerk.io/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69873 [cloudflare-turnstile] updated render parameters types as per cloudfl…
  types/cloudflare-turnstile/cloudflare-turnstile-tests.ts
  types/cloudflare-turnstile/index.d.ts
  types/cloudflare-turnstile/package.json
Labels: Self Merge, Owner Approved

#69979 [oidc-provider] named Provider export, type exports
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#69985 VS Code 1.91 types update
  types/vscode/index.d.ts
  types/vscode/package.json
Labels: Other Approved, Popular package, Untested Change

#69982 Update encoding-japanese for v2.2.0
  types/encoding-japanese/index.d.ts
  types/encoding-japanese/package.json
  types/encoding-japanese/test/encoding-japanese-tests.cjs.ts
Labels: Popular package, Self Merge, Owner Approved

#69909 Fixed matchings_index and waypoint_index in types/project-osrm__osrm
  types/project-osrm__osrm/index.d.ts
  types/project-osrm__osrm/project-osrm__osrm-tests.ts
Labels: Self Merge, Maintainer Approved

#69895 feat(node): Add mock module
  types/node/test.d.ts
  types/node/test/test.ts
Labels: Self Merge, Owner Approved, Critical package

#69947 fix: drop incorrect types for webtorrent org packages: webtorrent, create-torrent, parse-torrent, bittorrent-protocol
  notNeededPackages.json
  types/bittorrent-protocol/.eslintrc.json
  types/bittorrent-protocol/.npmignore
  types/bittorrent-protocol/bittorrent-protocol-tests.ts
  types/bittorrent-protocol/index.d.ts
  types/bittorrent-protocol/package.json
  types/bittorrent-protocol/tsconfig.json
  types/create-torrent/.npmignore
  types/create-torrent/create-torrent-tests.ts
  types/create-torrent/index.d.ts
  types/create-torrent/package.json
  types/create-torrent/tsconfig.json
  types/parse-torrent/.npmignore
  types/parse-torrent/index.d.ts
  types/parse-torrent/package.json
  types/parse-torrent/parse-torrent-tests.ts
  types/parse-torrent/tsconfig.json
  types/webtorrent/.npmignore
  types/webtorrent/index.d.ts
  types/webtorrent/package.json
  types/webtorrent/tsconfig.json
  types/webtorrent/webtorrent-tests.ts
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Check Config

#69922 thunderbird-webext-browser: update of definitions to API version Thunderbird 127.0
  types/thunderbird-webext-browser/index.d.ts
  types/thunderbird-webext-browser/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners, Huge Change

#69960 [ramda] bump types-ramda to 0.30.1
  types/ramda/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Critical package

#69965 add types for [flubber]
  types/flubber/.npmignore
  types/flubber/flubber-tests.ts
  types/flubber/index.d.ts
  types/flubber/package.json
  types/flubber/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69981 [cli-progress] Add isActive field to bars
  types/cli-progress/cli-progress-tests.ts
  types/cli-progress/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69995 [telegram-web-app] Update Telegram Web App to API 7.7
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/package.json
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69996 style: rewrap doc strings for telegram-web-app
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69945 [carbon-components-react] Remove myself from the contributors
  types/carbon-components-react/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Edits Owners

#69955 [haxball-headless-browser] Fixes setPlayerAvatar
  types/haxball-headless-browser/haxball-headless-browser-tests.ts
  types/haxball-headless-browser/index.d.ts
Labels: Self Merge, Owner Approved

#69913 [@types/jmuxer] Add missing properties to `JMuxer.Options`
  types/jmuxer/index.d.ts
  types/jmuxer/jmuxer-tests.ts
Labels: Self Merge, Owner Approved

#69951 fix: [facebook-nodejs-business-sdk] constructor type params to optional
  types/facebook-nodejs-business-sdk/facebook-nodejs-business-sdk-tests.ts
  types/facebook-nodejs-business-sdk/src/abstract-crud-object.d.ts
  types/facebook-nodejs-business-sdk/src/objects/serverside/app-data.d.ts
  types/facebook-nodejs-business-sdk/src/objects/serverside/content.d.ts
  types/facebook-nodejs-business-sdk/src/objects/serverside/custom-data.d.ts
  types/facebook-nodejs-business-sdk/src/objects/serverside/extended-device-info.d.ts
  types/facebook-nodejs-business-sdk/src/objects/serverside/server-event.d.ts
  types/facebook-nodejs-business-sdk/src/objects/serverside/user-data.d.ts
Labels: Self Merge, Owner Approved

#69966 [shimmer] Remove global `Function` modification
  types/shimmer/index.d.ts
  types/shimmer/package.json
  types/shimmer/shimmer-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69999 [invity-api]: Add default amounts for fiat currencies
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#69998 bugfix: [facebook-nodejs-business-sdk] add delete function types to classes
  types/facebook-nodejs-business-sdk/facebook-nodejs-business-sdk-tests.ts
  types/facebook-nodejs-business-sdk/src/objects/ad-async-request-set.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ad-async-request.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ad-creative.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ad-label.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ad-rule.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ad-set.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ad-study.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ad.d.ts
  types/facebook-nodejs-business-sdk/src/objects/app-request.d.ts
  types/facebook-nodejs-business-sdk/src/objects/business-role-request.d.ts
  types/facebook-nodejs-business-sdk/src/objects/business-user.d.ts
  types/facebook-nodejs-business-sdk/src/objects/campaign.d.ts
  types/facebook-nodejs-business-sdk/src/objects/comment.d.ts
  types/facebook-nodejs-business-sdk/src/objects/custom-audience.d.ts
  types/facebook-nodejs-business-sdk/src/objects/custom-conversion.d.ts
  types/facebook-nodejs-business-sdk/src/objects/extended-credit-allocation-config.d.ts
  types/facebook-nodejs-business-sdk/src/objects/extended-credit-invoice-group.d.ts
  types/facebook-nodejs-business-sdk/src/objects/high-demand-period.d.ts
  types/facebook-nodejs-business-sdk/src/objects/home-listing.d.ts
  types/facebook-nodejs-business-sdk/src/objects/hotel.d.ts
  types/facebook-nodejs-business-sdk/src/objects/ig-comment.d.ts
  types/facebook-nodejs-business-sdk/src/objects/instagram-comment.d.ts
  types/facebook-nodejs-business-sdk/src/objects/lead.d.ts
  types/facebook-nodejs-business-sdk/src/objects/live-video.d.ts
  types/facebook-nodejs-business-sdk/src/objects/media-title.d.ts
  types/facebook-nodejs-business-sdk/src/objects/open-bridge-configuration.d.ts
  types/facebook-nodejs-business-sdk/src/objects/page-call-to-action.d.ts
  types/facebook-nodejs-business-sdk/src/objects/page-post-experiment.d.ts
  types/facebook-nodejs-business-sdk/src/objects/page-post.d.ts
  types/facebook-nodejs-business-sdk/src/objects/page-user-message-thread-label.d.ts
  types/facebook-nodejs-business-sdk/src/objects/persona.d.ts
  types/facebook-nodejs-business-sdk/src/objects/photo.d.ts
  types/facebook-nodejs-business-sdk/src/objects/post.d.ts
  types/facebook-nodejs-business-sdk/src/objects/product-catalog.d.ts
  types/facebook-nodejs-business-sdk/src/objects/product-feed-rule.d.ts
  types/facebook-nodejs-business-sdk/src/objects/product-feed.d.ts
  types/facebook-nodejs-business-sdk/src/objects/product-group.d.ts
  types/facebook-nodejs-business-sdk/src/objects/product-item.d.ts
  types/facebook-nodejs-business-sdk/src/objects/product-set.d.ts
  types/facebook-nodejs-business-sdk/src/objects/publisher-block-list.d.ts
  types/facebook-nodejs-business-sdk/src/objects/store-catalog-settings.d.ts
  types/facebook-nodejs-business-sdk/src/objects/user.d.ts
  types/facebook-nodejs-business-sdk/src/objects/whats-app-business-pre-verified-phone-number.d.ts
Labels: Self Merge, Owner Approved

#70003 [Poool-engage] - rename namespace and add display condition
  types/poool-engage/index.d.ts
  types/poool-engage/poool-engage-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69975 fix(karma-webpack): make webpackMiddleware optional
  types/karma-webpack/index.d.ts
  types/karma-webpack/karma-webpack-tests.ts
  types/karma-webpack/package.json
Labels: Self Merge, Owner Approved

#69904 [@types/picomatch] Add new `windows` options field
  types/picomatch/lib/picomatch.d.ts
  types/picomatch/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69852 A JsonLdArray is an array of JsonLdObj's not an array with a single JsonLdObj
  types/jsonld/jsonld-spec.d.ts
  types/jsonld/jsonld-tests.ts
Labels: Self Merge, Maintainer Approved

#70013 fix(sparqljs): inaccurate types of INSERT/DELETE operations
  types/sparqljs/index.d.ts
  types/sparqljs/sparqljs-tests.ts
Labels: Self Merge, Owner Approved

#69944 [@types/set-cookie-parser] Revert updated `sameSite` typings
  types/set-cookie-parser/index.d.ts
  types/set-cookie-parser/set-cookie-parser-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69988 feat(aws-lambda): Add generics for stronger typing of CFN/CDK Custom Resource properties
  types/aws-lambda/package.json
  types/aws-lambda/test/cdk-custom-resource-tests.ts
  types/aws-lambda/test/cloudformation-tests.ts
  types/aws-lambda/trigger/cdk-custom-resource.d.ts
  types/aws-lambda/trigger/cloudformation-custom-resource.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Edits Owners

#69938 Improved definitions for awesome-notifications
  types/awesome-notifications/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#70014 [plotly.js] Updated types for LayoutAxis and Axis to match current API
  types/plotly.js/index.d.ts
  types/plotly.js/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#70015 [easy-soap-request] update axios dependency to v1.6.7
  types/easy-soap-request/package.json
Labels: Self Merge, Owner Approved

#70016 [imapflow] Update types for v1.0.164 (`fetchAll` method)
  types/imapflow/imapflow-tests.ts
  types/imapflow/index.d.ts
  types/imapflow/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#70020 feat(relay-test-utils): update types to match latest version and add option for stricter typing for resolvers
  types/relay-test-utils/lib/RelayMockPayloadGenerator.d.ts
  types/relay-test-utils/lib/RelayModernMockEnvironment.d.ts
  types/relay-test-utils/lib/index.d.ts
  types/relay-test-utils/package.json
  types/relay-test-utils/test/classical.tsx
  types/relay-test-utils/test/index.tsx
Labels: Popular package

#69971 [mixpanel-browser] Support api_payload_format for Config object
  types/mixpanel-browser/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#70009 [`mapbox__mapbox-sdk`] - Add types for missing `@mapbox/mapbox-sdk` and `isochrone` service
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
  types/mapbox__mapbox-sdk/package.json
Labels: Self Merge, Owner Approved

#70034 [delaunator] Use type parameter correctly on class Delaunator
  types/delaunator/delaunator-tests.ts
  types/delaunator/index.d.ts
Labels: Self Merge, Maintainer Approved

#70033 matter.js -> (small typo) Update index.d.ts
  types/matter-js/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#70025 Update index.d.ts for `keythereum`: Add types of `recover` function
  types/keythereum/index.d.ts
  types/keythereum/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change, Edits Owners

#70024 feat(ws): Enable `addEventListener`/`removeEventListener` to Work with Unions of Event Types
  types/ws/index.d.ts
  types/ws/ws-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#70026 [@types/modesl] - Event getHeader() method returns string | null
  types/modesl/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69978 chore: update woosmap.map
  types/woosmap.map/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#69970 [react] Add failing tests for returning `ReactNode` from an async Component
  types/react/test/tsx.tsx
  types/react/ts5.0/test/tsx.tsx
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#69885 [@types/espree] Update to 10.1.0
  types/espree/espree-tests.ts
  types/espree/index.d.cts
  types/espree/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#69787 [carbon-components-react] Ensure forwards compatiblity with React 19
  types/carbon-components-react/lib/components/Toggle/Toggle.d.ts
  types/carbon-components-react/lib/components/ToggleSmall/ToggleSmall.d.ts
  types/carbon-components-react/lib/components/TreeView/TreeNode.d.ts
  types/carbon-components-react/lib/components/UIShell/SideNav.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69788 [react-bootstrap] Ensure forwards compatiblity with React 19
  types/react-bootstrap/lib/NavItem.d.ts
  types/react-bootstrap/lib/Navbar.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69894 Cytoscape closeness centrality normalized result
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#70057 [carbon-components-react] Removing myself from owners.
  types/carbon-components-react/package.json
Labels: Author is Owner, Edits Owners

#69780 [dockerode] add version option for `buildImage`
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#70042 [@types/critters-webpack-plugin] Update critters-webpack-plugin to 3.0.2
  types/critters-webpack-plugin/critters-webpack-plugin-tests.ts
  types/critters-webpack-plugin/index.d.ts
  types/critters-webpack-plugin/package.json
Labels: Self Merge, Owner Approved

#70039 [lodash] fix _.get return type cannot refer to correct type and default type in nested object with optional fields
  types/lodash/common/object.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#70059 Revert "fix: drop incorrect types for webtorrent org packages: webtorrent, create-torrent, parse-torrent, bittorrent-protocol"
  notNeededPackages.json
  types/bittorrent-protocol/.eslintrc.json
  types/bittorrent-protocol/.npmignore
  types/bittorrent-protocol/bittorrent-protocol-tests.ts
  types/bittorrent-protocol/index.d.ts
  types/bittorrent-protocol/package.json
  types/bittorrent-protocol/tsconfig.json
  types/create-torrent/.npmignore
  types/create-torrent/create-torrent-tests.ts
  types/create-torrent/index.d.ts
  types/create-torrent/package.json
  types/create-torrent/tsconfig.json
  types/parse-torrent/.npmignore
  types/parse-torrent/index.d.ts
  types/parse-torrent/package.json
  types/parse-torrent/parse-torrent-tests.ts
  types/parse-torrent/tsconfig.json
  types/webtorrent/.npmignore
  types/webtorrent/index.d.ts
  types/webtorrent/package.json
  types/webtorrent/tsconfig.json
  types/webtorrent/webtorrent-tests.ts
Labels: New Definition, Edits Infrastructure, Edits multiple packages, Check Config

#70012 react-datepicker v7 was migrated to TypeScript, typings no longer needed
  notNeededPackages.json
  types/react-datepicker/.npmignore
  types/react-datepicker/index.d.ts
  types/react-datepicker/package.json
  types/react-datepicker/react-datepicker-tests.tsx
  types/react-datepicker/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved, Critical package

#70062 zipkin-context-cls: make namespace an optional argument, since it is
  types/zipkin-context-cls/index.d.ts
  types/zipkin-context-cls/zipkin-context-cls-tests.ts
Labels: Self Merge, Owner Approved

#70035 remove: @fcostarodrigo/walk
  notNeededPackages.json
  types/fcostarodrigo__walk/.npmignore
  types/fcostarodrigo__walk/fcostarodrigo__walk-tests.ts
  types/fcostarodrigo__walk/index.d.ts
  types/fcostarodrigo__walk/package.json
  types/fcostarodrigo__walk/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#70063 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#70068 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#70069 Fix notNeededPackages for fcostarodrigo__walk
  notNeededPackages.json
Labels: Edits Infrastructure

#70071 [tabulator-tables] Update for new export maps upstream
  types/tabulator-tables/index.d.mts
  types/tabulator-tables/package.json
Labels: Untested Change

#69941 motion-sensors-polyfill: Correct GyroscopeSensorOptions Inheritance
  types/motion-sensors-polyfill/index.d.ts
  types/motion-sensors-polyfill/motion-sensors-polyfill-tests.ts
  types/motion-sensors-polyfill/package.json
Labels: Self Merge, Maintainer Approved

#69820 node crypto sign should accept a private key in jwk format
  types/node/crypto.d.ts
  types/node/test/crypto.ts
  types/node/v16/crypto.d.ts
  types/node/v16/test/crypto.ts
  types/node/v18/crypto.d.ts
  types/node/v18/test/crypto.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69934 [ads-client] Allow `null` as `Settings` properties
  types/ads-client/ads-client-tests.ts
  types/ads-client/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#69920 [react-simple-maps] Add missing hook types
  types/react-simple-maps/index.d.ts
  types/react-simple-maps/package.json
  types/react-simple-maps/react-simple-maps-tests.tsx
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#70075 Updates types for Recurly.js v4.29.1
  types/recurly__recurly-js/lib/amazon-pay.d.ts
  types/recurly__recurly-js/lib/apple-pay/index.d.ts
  types/recurly__recurly-js/lib/google-pay/index.d.ts
  types/recurly__recurly-js/lib/recurly.d.ts
  types/recurly__recurly-js/package.json
  types/recurly__recurly-js/test/google-pay.ts
Labels: Self Merge, Owner Approved, Edits Owners

#70067 Update ari client. Add missing field protocol_id to Channel
  types/ari-client/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#70065 [Poool-access][Poool-engage]: add ispoool boolean on every elements, event names and fix some stuff
  types/poool-access/index.d.ts
  types/poool-access/package.json
  types/poool-access/poool-access-tests.ts
  types/poool-engage/index.d.ts
  types/poool-engage/poool-engage-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved, Edits multiple packages, Maintainer Approved

#70078 Fix Clerk.io Search response
  types/clerk.io/clerk.io-tests.ts
  types/clerk.io/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#70080 [@types/node-cmd] Adding type definitions
  types/node-cmd/.npmignore
  types/node-cmd/index.d.ts
  types/node-cmd/node-cmd-tests.ts
  types/node-cmd/package.json
  types/node-cmd/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69950 [color-rgba] Fix return type
  types/color-rgba/color-rgba-tests.ts
  types/color-rgba/index.d.ts
Labels: Self Merge, Maintainer Approved

#70092 Update dprint cli
  package.json
Labels: Edits Infrastructure

#65463 Add printerSupport to mjml-core
  types/mjml-core/index.d.ts
  types/mjml-core/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#70054 Make ImportMeta.resolve conditional
  types/node/v16/module.d.ts
  types/node/v16/node-tests-dom.ts
  types/node/v16/node-tests-non-dom.ts
  types/node/v16/test/module-dom.ts
  types/node/v16/test/module-non-dom.ts
  types/node/v16/test/module.ts
  types/node/v16/tsconfig.dom.json
  types/node/v16/tsconfig.non-dom.json
  types/node/v18/module.d.ts
  types/node/v18/node-tests-dom.ts
  types/node/v18/node-tests-non-dom.ts
  types/node/v18/test/module-dom.ts
  types/node/v18/test/module-non-dom.ts
  types/node/v18/test/module.ts
Labels: Self Merge, Maintainer Approved, Critical package

#70095 Don't use github search in publisher watchdog
  scripts/watchdog-publisher.js
Labels: Edits Infrastructure

#70087 [d3-3d] add types for d3-3d
  types/d3-3d/.npmignore
  types/d3-3d/d3-3d-tests.ts
  types/d3-3d/index.d.ts
  types/d3-3d/package.json
  types/d3-3d/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69862 [plotly.js] Make width/height nullable in Plotly.toImage / Plotly.downloadImage
  types/plotly.js/index.d.ts
  types/plotly.js/test/core-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#70053 qrcode-svg: add svg-viewbox option
  types/qrcode-svg/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#70103 Update dprint to pick up comment bugfix
  .dprint.jsonc
Labels: Edits Infrastructure

#70102 [@types/oojs-ui] Refine annotation of OO.ui.Element.ScrollIntoViewConfig
  types/oojs-ui/Element.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#70097 Update types for fabric: Add enablePointerEvents as a boolean feature to fabric canvas initialization.
  types/fabric/fabric-impl.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#70100 [@types/streamtest] Embed types since 3.0.0
  notNeededPackages.json
  types/streamtest/.npmignore
  types/streamtest/index.d.ts
  types/streamtest/package.json
  types/streamtest/streamtest-tests.ts
  types/streamtest/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#70108 [@types/ttf2woff2] Embed types since 6.0.0
  notNeededPackages.json
  types/ttf2woff2/.npmignore
  types/ttf2woff2/index.d.ts
  types/ttf2woff2/package.json
  types/ttf2woff2/tsconfig.json
  types/ttf2woff2/ttf2woff2-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#70116 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#69946 Lazy.js: fix many incorrect types and improve others
  types/lazy.js/index.d.ts
  types/lazy.js/lazy.js-tests.ts
  types/lazy.js/tsconfig.json
Labels: Self Merge, Maintainer Approved

#70124 Export inline fragment and condition
  types/relay-runtime/index.d.ts
Labels: Popular package, Untested Change

#70126 Fix always-truthy errors
  types/ember/test/component.ts
  types/ember/v2/test/component.ts
  types/ember/v3/test/component.ts
  types/ember__component/test/component.ts
  types/ember__component/v3/test/component.ts
  types/hapi__joi/hapi__joi-tests.ts
  types/karma-browserstack-launcher/karma-browserstack-launcher-tests.ts
  types/react-native-joi/react-native-joi-tests.ts
  types/rsvp/rsvp-tests.ts
Labels: Popular package, Edits multiple packages

#69632 Support forthcoming changes to `Iterator` type in TS 5.6
  types/bresenham/bresenham-tests.ts
  types/call-bind/test/callBound.test.ts
  types/es-abstract/test/GetIntrinsic.test.ts
  types/es-abstract/test/es2015.test.ts
  types/es-abstract/test/helpers/callBound.test.ts
  types/es-get-iterator/es-get-iterator-tests.ts
  types/es-get-iterator/index.d.ts
  types/get-intrinsic/get-intrinsic-tests.ts
  types/lodash/lodash-tests.ts
  types/node/buffer.d.ts
  types/node/test/test.ts
  types/node/test/util_types.ts
  types/node/v16/buffer.d.ts
  types/node/v16/test/util_types.ts
  types/node/v18/buffer.d.ts
  types/node/v18/test/test.ts
  types/node/v18/test/util_types.ts
  types/pouchdb-core/index.d.ts
  types/regenerator-runtime/regenerator-runtime-tests.ts
  types/string.prototype.matchall/string.prototype.matchall-tests.ts
  types/win-ca/win-ca-tests.ts
Labels: Edits multiple packages, Critical package, Too Many Owners, Unreviewed

#70111 Add new turndown options field preformattedCode
  types/turndown/index.d.ts
  types/turndown/turndown-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69994 [@types/chrome] Fix Window type in ExtensionSidebarPaneShownEvent
  types/chrome/index.d.ts
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved, Untested Change

#69993 Adds webhook payload definitions
  types/onfleet__node-onfleet/Resources/Webhooks.d.ts
  types/onfleet__node-onfleet/onfleet__node-onfleet-tests.ts
Labels: Self Merge, Maintainer Approved

#69992 Adds Task custom fields definitions
  types/onfleet__node-onfleet/Resources/Tasks.d.ts
  types/onfleet__node-onfleet/onfleet__node-onfleet-tests.ts
Labels: Self Merge, Maintainer Approved

#69899 Add missing type definitions for package `probe-image-size` deep imports.
  types/probe-image-size/lib/parse_sync/bmp.d.ts
  types/probe-image-size/lib/parse_sync/ico.d.ts
  types/probe-image-size/lib/parse_sync/png.d.ts
  types/probe-image-size/probe-image-size-tests.ts
  types/probe-image-size/stream.d.ts
  types/probe-image-size/tsconfig.json
Labels: Self Merge, Maintainer Approved

#70107 Nise add missing `abort` property
  types/nise/index.d.ts
  types/nise/nise-tests.ts
Labels: Other Approved, Self Merge

#70066 Remove `stuartthomson` from dockerode owners
  types/dockerode/package.json
Labels: Popular package, Author is Owner, Edits Owners

#70117 Remove 'jump' property from markdown-it type definitions
  types/markdown-it/dist/index.cjs.d.ts
  types/markdown-it/lib/rules_inline/state_inline.d.mts
  types/markdown-it/markdown-it-tests.mts
  types/markdown-it/markdown-it-tests.ts
  types/markdown-it/test/rules_inline/state_inline.mts
  types/markdown-it/v13/lib/rules_inline/state_inline.d.ts
  types/markdown-it/v13/test/rules_inline/state_inline.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#70130 [@types/govuk-frontend] Add new definition for govuk-frontend
  types/govuk-frontend/.npmignore
  types/govuk-frontend/dist/govuk/all.bundle.d.mts
  types/govuk-frontend/dist/govuk/all.bundle.d.ts
  types/govuk-frontend/dist/govuk/all.d.mts
  types/govuk-frontend/dist/govuk/common/closest-attribute-value.d.mts
  types/govuk-frontend/dist/govuk/common/closest-attribute-value.d.ts
  types/govuk-frontend/dist/govuk/common/govuk-frontend-version.d.mts
  types/govuk-frontend/dist/govuk/common/govuk-frontend-version.d.ts
  types/govuk-frontend/dist/govuk/common/index.d.mts
  types/govuk-frontend/dist/govuk/common/index.d.ts
  types/govuk-frontend/dist/govuk/common/normalise-dataset.d.mts
  types/govuk-frontend/dist/govuk/common/normalise-dataset.d.ts
  types/govuk-frontend/dist/govuk/common/normalise-string.d.mts
  types/govuk-frontend/dist/govuk/common/normalise-string.d.ts
  types/govuk-frontend/dist/govuk/components/accordion/accordion.d.mts
  types/govuk-frontend/dist/govuk/components/accordion/accordion.d.ts
  types/govuk-frontend/dist/govuk/components/button/button.d.mts
  types/govuk-frontend/dist/govuk/components/button/button.d.ts
  types/govuk-frontend/dist/govuk/components/character-count/character-count.d.mts
  types/govuk-frontend/dist/govuk/components/character-count/character-count.d.ts
  types/govuk-frontend/dist/govuk/components/checkboxes/checkboxes.d.mts
  types/govuk-frontend/dist/govuk/components/checkboxes/checkboxes.d.ts
  types/govuk-frontend/dist/govuk/components/error-summary/error-summary.d.mts
  types/govuk-frontend/dist/govuk/components/error-summary/error-summary.d.ts
  types/govuk-frontend/dist/govuk/components/exit-this-page/exit-this-page.d.mts
  types/govuk-frontend/dist/govuk/components/exit-this-page/exit-this-page.d.ts
  types/govuk-frontend/dist/govuk/components/header/header.d.mts
  types/govuk-frontend/dist/govuk/components/header/header.d.ts
  types/govuk-frontend/dist/govuk/components/notification-banner/notification-banner.d.mts
  types/govuk-frontend/dist/govuk/components/notification-banner/notification-banner.d.ts
  types/govuk-frontend/dist/govuk/components/password-input/password-input.d.mts
  types/govuk-frontend/dist/govuk/components/password-input/password-input.d.ts
  types/govuk-frontend/dist/govuk/components/radios/radios.d.mts
  types/govuk-frontend/dist/govuk/components/radios/radios.d.ts
  types/govuk-frontend/dist/govuk/components/skip-link/skip-link.d.mts
  types/govuk-frontend/dist/govuk/components/skip-link/skip-link.d.ts
  types/govuk-frontend/dist/govuk/components/tabs/tabs.d.mts
  types/govuk-frontend/dist/govuk/components/tabs/tabs.d.ts
  types/govuk-frontend/dist/govuk/errors/index.d.mts
  types/govuk-frontend/dist/govuk/errors/index.d.ts
  types/govuk-frontend/dist/govuk/govuk-frontend-component.d.mts
  types/govuk-frontend/dist/govuk/govuk-frontend-component.d.ts
  types/govuk-frontend/dist/govuk/i18n.d.mts
  types/govuk-frontend/dist/govuk/i18n.d.ts
  types/govuk-frontend/dist/govuk/init.d.mts
  types/govuk-frontend/dist/govuk/init.d.ts
  types/govuk-frontend/govuk-frontend-tests.mts
  types/govuk-frontend/govuk-frontend-tests.ts
  types/govuk-frontend/index.d.mts
  types/govuk-frontend/index.d.ts
  types/govuk-frontend/package.json
  types/govuk-frontend/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#70142 [three] r167 patches
  types/three/src/Three.WebGPU.d.ts
  types/three/src/Three.d.ts
  types/three/src/math/Matrix3.d.ts
  types/three/src/math/Matrix4.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#70050 [@types/superagent] add form data append options on field function
  types/superagent/lib/node/index.d.ts
  types/superagent/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#70145 [@types/camelize] fixes types for camelize package
  types/camelize/camelize-tests.ts
  types/camelize/index.d.ts
Labels: Self Merge, Owner Approved

#70148 [@mapbox-sdk]: Restrict `SimpleMarker` coordinates type
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Self Merge, Owner Approved

#70082 Update `relay-runtime` environment types to reflect the renaming of `requiredFieldLogger` to `relayFieldLogger`
  types/relay-runtime/index.d.ts
  types/relay-runtime/lib/multi-actor-environment/MultiActorEnvironment.d.ts
  types/relay-runtime/lib/store/RelayModernEnvironment.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#70132 fix: WS server address can be null
  types/ws/index.d.ts
  types/ws/ws-tests.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#69871 [plotly.js] Update types for x and y axis names to match documentation
  types/plotly.js/index.d.ts
  types/plotly.js/package.json
  types/plotly.js/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#70022 [novnc__novnc]: Update RFB module path to match NoVnc v1.5
  types/novnc__novnc/index.d.ts
  types/novnc__novnc/novnc__novnc-tests.ts
  types/novnc__novnc/package.json
Labels: Unreviewed

#70019 Add event listeners typings for `fluent-ffmpeg`
  types/fluent-ffmpeg/fluent-ffmpeg-tests.ts
  types/fluent-ffmpeg/index.d.ts
Labels: Popular package, Unreviewed

#70008 [`mapbox-gl`] - Add missing `MapOptions` types
  types/mapbox-gl/index.d.ts
  types/mapbox-gl/mapbox-gl-tests.ts
  types/mapbox-gl/package.json
Labels: Popular package, Unreviewed

#70128 Updated to v1.31.0
  types/consumer-data-standards/README.md
  types/consumer-data-standards/admin/index.d.ts
  types/consumer-data-standards/banking/index.d.ts
  types/consumer-data-standards/energy/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#70144 [mapbox__mapbox-gl-draw] compatibility with MapBox GL js 3.5+ native types
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
  types/mapbox__mapbox-gl-draw/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#70079 [sharedb] Add `defaultType` and `transformPresence()`
  types/sharedb/lib/sharedb.d.ts
  types/sharedb/sharedb-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#70149 Update project website URL for voca
  types/voca/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#70155 [node] Remove post-22.0 features from v22.0.x package
  types/node/dns.d.ts
  types/node/dns/promises.d.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/test.d.ts
  types/node/test/fs.ts
  types/node/test/test.ts
  types/node/test/url.ts
  types/node/url.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#70166 [node] Add global WebSocket
  types/node/globals.d.ts
  types/node/test/globals-dom.ts
  types/node/test/globals-non-dom.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#70182 [telegram-web-app] add support for Bot API 7.8
  types/telegram-web-app/index.d.ts
  types/telegram-web-app/package.json
  types/telegram-web-app/telegram-web-app-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved
