Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2024-06, with the labels that each got.

#69585 WebMIDI -- WebMIDI types refactor according to spec update and fixes
  types/webmidi/index.d.ts
  types/webmidi/package.json
  types/webmidi/webmidi-tests.ts
Labels: Self Merge, Maintainer Approved

#69719 [@types/node] Types for v20.14.0
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/crypto.d.ts
  types/node/dgram.d.ts
  types/node/http.d.ts
  types/node/https.d.ts
  types/node/net.d.ts
  types/node/os.d.ts
  types/node/package.json
  types/node/perf_hooks.d.ts
  types/node/process.d.ts
  types/node/repl.d.ts
  types/node/test.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#69661 Update imagemin's Plugin to Uint8Array instead of Buffer.
  types/imagemin/index.d.ts
  types/imagemin/package.json
Labels: Popular package, Self Merge, Owner Approved, Untested Change

#69714 node: Add missing spaces
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/net.d.ts
  types/node/v16/assert.d.ts
  types/node/v16/buffer.d.ts
  types/node/v16/child_process.d.ts
  types/node/v16/crypto.d.ts
  types/node/v16/dgram.d.ts
  types/node/v16/domain.d.ts
  types/node/v16/events.d.ts
  types/node/v16/fs.d.ts
  types/node/v16/fs/promises.d.ts
  types/node/v16/http.d.ts
  types/node/v16/http2.d.ts
  types/node/v16/https.d.ts
  types/node/v16/net.d.ts
  types/node/v16/os.d.ts
  types/node/v16/perf_hooks.d.ts
  types/node/v16/process.d.ts
  types/node/v16/repl.d.ts
  types/node/v16/stream.d.ts
  types/node/v16/tls.d.ts
  types/node/v16/trace_events.d.ts
  types/node/v16/tty.d.ts
  types/node/v16/util.d.ts
  types/node/v18/assert.d.ts
  types/node/v18/buffer.d.ts
  types/node/v18/child_process.d.ts
  types/node/v18/crypto.d.ts
  types/node/v18/dgram.d.ts
  types/node/v18/domain.d.ts
  types/node/v18/events.d.ts
  types/node/v18/fs.d.ts
  types/node/v18/fs/promises.d.ts
  types/node/v18/http.d.ts
  types/node/v18/http2.d.ts
  types/node/v18/https.d.ts
  types/node/v18/net.d.ts
  types/node/v18/os.d.ts
  types/node/v18/perf_hooks.d.ts
  types/node/v18/process.d.ts
  types/node/v18/repl.d.ts
  types/node/v18/stream.d.ts
  types/node/v18/test.d.ts
  types/node/v18/tls.d.ts
  types/node/v18/trace_events.d.ts
  types/node/v18/tty.d.ts
  types/node/v18/util.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#69741 [@types/redux-form] Remove unused imports
  types/redux-form/index.d.ts
  types/redux-form/lib/Field.d.ts
  types/redux-form/lib/Form.d.ts
  types/redux-form/lib/formValues.d.ts
  types/redux-form/redux-form-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#69621 [plotly.js] Fix TS2430 error with `exactOptionalPropertyTypes`
  types/plotly.js/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69738 [@types/envinfo]: update type for HelperNames
  types/envinfo/envinfo-tests.ts
  types/envinfo/index.d.ts
Labels: Self Merge, Owner Approved

#69535 [@types/node] Make it possible to use `static EventEmitter.on` with `EventTarget`
  types/node/events.d.ts
  types/node/test/events.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#69752 Update VS Code types to 1.90
  types/vscode/index.d.ts
  types/vscode/package.json
  types/vscode/tsconfig.json
Labels: Popular package, Untested Change, Check Config

#69681 [@types/lodash]: mapValues returns object if applied to array input
  types/lodash/common/object.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Critical package

#69748 [@types/webvtt-parser]: add new package
  types/webvtt-parser/.npmignore
  types/webvtt-parser/index.d.ts
  types/webvtt-parser/package.json
  types/webvtt-parser/tsconfig.json
  types/webvtt-parser/webvtt-parser-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#69763 [@types/atlassian-connect-js] add `AP.jira.openIssueDialog()`
  types/atlassian-connect-js/atlassian-connect-js-tests.ts
  types/atlassian-connect-js/index.d.ts
Labels: Self Merge, Owner Approved

#69657 [ini] add decoding options
  types/ini/index.d.ts
  types/ini/ini-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69652 Update ovenplayer playback event listener callback
  types/ovenplayer/index.d.ts
  types/ovenplayer/ovenplayer-tests.ts
Labels: Other Approved, Unmerged, Self Merge

#69768 feat(@carbon/icon-helpers): not needed as of version 10.45.0
  notNeededPackages.json
  types/carbon__icon-helpers/.npmignore
  types/carbon__icon-helpers/carbon__icon-helpers-tests.ts
  types/carbon__icon-helpers/index.d.ts
  types/carbon__icon-helpers/package.json
  types/carbon__icon-helpers/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#69591 [cytoscape] Fixes typing of arguments to concentric, levelWidth callbacks
  types/cytoscape/cytoscape-tests.ts
  types/cytoscape/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved

#69772 Add `GenerateOptions.mode` in css-tree
  types/css-tree/css-tree-tests.ts
  types/css-tree/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#69774 [@types/traverse] Update for 0.6.9
  types/traverse/index.d.ts
  types/traverse/traverse-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69734 [@types/set-cookie-parser] Update typings of `sameSite` property
  types/set-cookie-parser/index.d.ts
  types/set-cookie-parser/set-cookie-parser-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69361 knuddels-userapp-backend-api - deprecated KnuddelAccount and KnuddelPot
  types/knuddels-userapp-backend-api/index.d.ts
  types/knuddels-userapp-backend-api/package.json
Labels: Self Merge, Maintainer Approved, Untested Change

#69794 Update `@types/bun` to `1.1.13`
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#69761 [react-autocomplete]: add default for `autoHighlight` prop
  types/react-autocomplete/index.d.ts
  types/react-autocomplete/react-autocomplete-tests.tsx
Labels: Self Merge, Owner Approved

#69814 [relay-runtime] Sync types for v17
  types/relay-runtime/lib/network/RelayNetworkTypes.d.ts
  types/relay-runtime/lib/util/RelayFeatureFlags.d.ts
  types/relay-runtime/package.json
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#69813 graphql-list-fields: Unpin GraphQL version
  types/graphql-list-fields/package.json
Labels: Other Approved, Self Merge

#69793 [validator] `isUUID` also accepts version 7
  types/validator/index.d.ts
  types/validator/package.json
  types/validator/validator-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69762 Add types for Pannellum
  types/pannellum/.npmignore
  types/pannellum/index.d.ts
  types/pannellum/package.json
  types/pannellum/pannellum-tests.ts
  types/pannellum/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69811 [PXR-oneline] Add method
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/oneline-tests.ts
  types/pxr-oneline/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#69800 Added 'alpha' Type for operationsSorter in SwaggerConfigs (@types/swagger-ui-dist)
  types/swagger-ui-dist/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69618 [@types/node] Add AbortSignal.any()
  types/node/globals.d.ts
  types/node/test/globals-non-dom.ts
  types/node/v18/globals.d.ts
  types/node/v18/test/globals-non-dom.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69801 Add type definitions for stream-line-wrapper
  types/stream-line-wrapper/.npmignore
  types/stream-line-wrapper/index.d.ts
  types/stream-line-wrapper/package.json
  types/stream-line-wrapper/stream-line-wrapper-tests.ts
  types/stream-line-wrapper/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69825 Fix documentation of default `strength` value of d3-force's `ForceCollide<T>` interface
  types/d3-force/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#69715 API Gateway Policy Effect can only be `Allow` or `Deny` in @types/aws-lambda
  types/aws-lambda/test/api-gateway-tests.ts
  types/aws-lambda/test/iot-authorizer-tests.ts
  types/aws-lambda/trigger/api-gateway-authorizer.d.ts
Labels: Other Approved, Self Merge, Owner Approved, Maintainer Approved, Critical package

#69803 add typings for wicket
  types/wicket/.npmignore
  types/wicket/index.d.ts
  types/wicket/package.json
  types/wicket/tsconfig.json
  types/wicket/wicket-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#69790 Add `signedStorageUrl` property to `VaporStoreOptions` interface in laravel-vapor
  types/laravel-vapor/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69697 [forge-viewer] added new error codes
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Self Merge, Maintainer Approved

#69817 [@types/vite-plugin-react-control-statements]: Add new package
  types/vite-plugin-react-control-statements/.npmignore
  types/vite-plugin-react-control-statements/index.d.ts
  types/vite-plugin-react-control-statements/package.json
  types/vite-plugin-react-control-statements/tsconfig.json
  types/vite-plugin-react-control-statements/vite-plugin-react-control-statements-tests.tsx
Labels: New Definition, Self Merge, Maintainer Approved

#69701 Cytoscape - Removing myself from the owners list
  types/cytoscape/package.json
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Edits Owners

#69723 [node] Add missing typings for MessagePort in worker_threads
  types/node/test/worker_threads.ts
  types/node/v16/test/worker_threads.ts
  types/node/v16/worker_threads.d.ts
  types/node/v18/test/worker_threads.ts
  types/node/v18/worker_threads.d.ts
  types/node/worker_threads.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69736 [aws-lambda] Export AWS transfer family types
  types/aws-lambda/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#69796 Update toValue interface to match current configuration.
  types/vanillajs-datepicker/Datepicker.d.ts
  types/vanillajs-datepicker/vanillajs-datepicker-tests.ts
Labels: Self Merge, Owner Approved

#69831 Add missing parameters to `phoenix`'s `SocketConnectOption` type
  types/phoenix/index.d.ts
  types/phoenix/phoenix-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69743 Add testEnvironment option to ConstructorOptions in node-telegram-bot-api
  types/node-telegram-bot-api/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69730 [@types/jwplayer]: The `Source` interface requires only the `file` type
  types/jwplayer/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69789 Add type definitions for passport-line
  types/passport-line/.npmignore
  types/passport-line/index.d.ts
  types/passport-line/package.json
  types/passport-line/passport-line-tests.ts
  types/passport-line/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69684 [@types/node]: Add missing options to `events.on`
  types/node/events.d.ts
  types/node/test/events.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69798 Added typing for OL3Parser.inject, LengthIndexedLine and OffsetCurveB…
  types/jsts/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#69828 fix: remove types for hyphenate-style-name
  notNeededPackages.json
  types/hyphenate-style-name/.npmignore
  types/hyphenate-style-name/hyphenate-style-name-tests.ts
  types/hyphenate-style-name/index.d.ts
  types/hyphenate-style-name/package.json
  types/hyphenate-style-name/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#69797 Move watchdogs to GHA
  .github/actions/setup-for-scripts/action.yml
  .github/workflows/CI.yml
  .github/workflows/UpdateCodeowners.yml
  .github/workflows/format-and-commit.yml
  .github/workflows/ghostbuster.yml
  .github/workflows/lint-md.yml
  .github/workflows/support-window.yml
  .github/workflows/watchdog-publisher.yml
  .github/workflows/watchdog-typescript-bot.yml
  README.md
  scripts/ghostbuster.js
  scripts/package.json
  scripts/watchdog-publisher.js
  scripts/watchdog-typescript-bot.js
Labels: Edits Infrastructure

#69840 Fix ExpectType with extra whitespace
  types/crimsonq/crimsonq-tests.ts
  types/drivelist/drivelist-tests.ts
  types/marvelapp__react-ab-test/marvelapp__react-ab-test-tests.ts
  types/papaparse/papaparse-tests.ts
  types/poool-access/poool-access-tests.ts
  types/progressbar.js/progressbar.js-tests.ts
  types/react-swipeable-views-core/react-swipeable-views-core-tests.ts
  types/wechat-miniprogram-xmly/wechat-miniprogram-xmly-tests.ts
Labels: Edits multiple packages, Critical package

#69843 Update 6.0 and 6.2 definitions
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#69673 [@types/node] Fix dns error code types
  types/node/dns.d.ts
  types/node/dns/promises.d.ts
  types/node/test/dns.ts
  types/node/v16/dns.d.ts
  types/node/v16/dns/promises.d.ts
  types/node/v18/dns.d.ts
  types/node/v18/dns/promises.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69660 [@types/express-serve-static-core] 🏷️ Add `Promise<void>` to `RequestHandler`'s return type
  types/architect__functions/test/http-tests.ts
  types/create-test-server/create-test-server-tests.ts
  types/express-brute-memcached/express-brute-memcached-tests.ts
  types/express-brute-mongo/express-brute-mongo-tests.ts
  types/express-brute/express-brute-tests.ts
  types/express-oauth-server/express-oauth-server-tests.ts
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express-ua-middleware/express-ua-middleware-tests.ts
  types/feathersjs__express/feathersjs__express-tests.ts
  types/forest-express-mongoose/forest-express-mongoose-tests.ts
  types/forest-express-sequelize/forest-express-sequelize-tests.ts
  types/fusebit__oauth-connector/fusebit__oauth-connector-tests.ts
  types/logfmt/logfmt-tests.ts
  types/mock-req-res/mock-req-res-tests.ts
  types/mongoose-aggregate-paginate-v2/mongoose-aggregate-paginate-v2-tests.ts
  types/swaggerize-express/swaggerize-express-tests.ts
Labels: Other Approved, Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#69845 Revert "[@types/express-serve-static-core] 🏷️ Add `Promise<void>` to `RequestHandler`'s return type"
  types/architect__functions/test/http-tests.ts
  types/create-test-server/create-test-server-tests.ts
  types/express-brute-memcached/express-brute-memcached-tests.ts
  types/express-brute-mongo/express-brute-mongo-tests.ts
  types/express-brute/express-brute-tests.ts
  types/express-oauth-server/express-oauth-server-tests.ts
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express-ua-middleware/express-ua-middleware-tests.ts
  types/feathersjs__express/feathersjs__express-tests.ts
  types/forest-express-mongoose/forest-express-mongoose-tests.ts
  types/forest-express-sequelize/forest-express-sequelize-tests.ts
  types/fusebit__oauth-connector/fusebit__oauth-connector-tests.ts
  types/logfmt/logfmt-tests.ts
  types/mock-req-res/mock-req-res-tests.ts
  types/mongoose-aggregate-paginate-v2/mongoose-aggregate-paginate-v2-tests.ts
  types/swaggerize-express/swaggerize-express-tests.ts
Labels: Edits multiple packages, Critical package

#69832 [webpack-react-component-name] added type definitions
  types/webpack-react-component-name/.npmignore
  types/webpack-react-component-name/index.d.ts
  types/webpack-react-component-name/package.json
  types/webpack-react-component-name/tsconfig.json
  types/webpack-react-component-name/webpack-react-component-name-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#69709 [@types/wordpress__block-editor] Allow first param of innerBlocksProps to be output of useBlockProps
  types/wordpress__block-editor/components/use-block-props.d.ts
  types/wordpress__block-editor/wordpress__block-editor-tests.tsx
Labels: Self Merge, Maintainer Approved

#69848 Offset watchdog crons
  .github/workflows/watchdog-publisher.yml
  .github/workflows/watchdog-typescript-bot.yml
Labels: Edits Infrastructure

#69850 Update @types/bun to 1.1.14
  types/bun/package.json
Labels: Popular package, Self Merge, Owner Approved

#69839 Add types for random-access-storage
  types/random-access-storage/.npmignore
  types/random-access-storage/index.d.ts
  types/random-access-storage/package.json
  types/random-access-storage/random-access-storage-tests.ts
  types/random-access-storage/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69826 [@types/chromecast-caf-receiver] Extensible customData types
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/cast.framework.messages.d.ts
  types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
Labels: Other Approved, Self Merge

#69836 add back my user as an owner
  types/arc4/package.json
  types/exaroton/package.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved, No Other Owners, Edits Owners

#69819 fix(node): child_process:for takes URL
  types/node/child_process.d.ts
  types/node/test/child_process.ts
  types/node/v16/child_process.d.ts
  types/node/v16/test/child_process.ts
  types/node/v18/child_process.d.ts
  types/node/v18/test/child_process.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#69773 [@types/uuid]: Update for uuid v10
  types/uuid/index.d.mts
  types/uuid/index.d.ts
  types/uuid/package.json
  types/uuid/uuid-tests.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#69853 [@npmcli/arborist] Fix edgesOut and edgesIn types
  types/npmcli__arborist/index.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#69786 add type for ezuikit-js package
  types/ezuikit-js/.npmignore
  types/ezuikit-js/ezuikit-js-tests.ts
  types/ezuikit-js/index.d.ts
  types/ezuikit-js/package.json
  types/ezuikit-js/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69849 [@npmcli/arborist] Fix Node.edgesOut and Define Node.isWorkspace
  types/npmcli__arborist/index.d.ts
  types/npmcli__arborist/npmcli__arborist-tests.ts
Labels: Self Merge, Owner Approved

#69872 [@npmcli/arborist] Add Myself as Owner
  types/npmcli__arborist/package.json
Labels: Self Merge, Owner Approved, Edits Owners

#69860 Add types for random-access-file
  types/random-access-file/.npmignore
  types/random-access-file/index.d.ts
  types/random-access-file/package.json
  types/random-access-file/random-access-file-tests.ts
  types/random-access-file/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#69869 Add missing type definition for `http-link-header` package `toString()` method.
  types/http-link-header/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69856 feat(node): pass generic function implementation to `mockImplementation` and `mockImplementationOnce` for node:test
  types/node/test.d.ts
  types/node/test/test.ts
  types/node/v18/test.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69857 feat(mocha): add missing failZero option
  types/mocha/index.d.ts
  types/mocha/mocha-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69876 [@types/tabulator-tables] fixed setData for invoking without any parameter as per official docs
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#69668 Add riskCorrelationId to @types/braintree-web DataCollector
  types/braintree-web/data-collector.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#69868 [@types/chromecast-caf-receiver] Add start and end to LiveSeekableRange
  types/chromecast-caf-receiver/cast.framework.messages.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#69881 Preemptively fix broken ExpectTypes
  types/alpinejs/alpinejs-tests.ts
  types/antlr4/test/atn.ts
  types/css-mediaquery/css-mediaquery-tests.ts
  types/d3-array/d3-array-tests.ts
  types/d3-array/v2/d3-array-tests.ts
  types/ember-data__adapter/test/error.ts
  types/ember-data__adapter/v3/test/error.ts
  types/ember-data__store/ember-data__store-tests.ts
  types/ember-data__store/v3/ember-data__store-tests.ts
  types/es-aggregate-error/es-aggregate-error-tests.ts
  types/fernet/fernet-tests.ts
  types/firstline/firstline-tests.ts
  types/floreal/floreal-tests.ts
  types/moonjs/moonjs-tests.ts
  types/oojs-ui/oojs-ui-tests.ts
  types/shelljs.exec/shelljs.exec-tests.ts
  types/systemjs/systemjs-tests.ts
  types/vk-openapi/vk-openapi-tests.ts
  types/yargs/v15/yargs-tests.ts
  types/yargs/v16/yargs-tests.ts
  types/yargs/yargs-tests.ts
Labels: Edits multiple packages, Critical package

#69900 Add missing type definition for package `http-link-header` method `setUnique()`.
  types/http-link-header/http-link-header-tests.ts
  types/http-link-header/index.d.ts
Labels: Self Merge, Owner Approved

#69767 [gamedig] fix import when using `moduleResolution: node16`
  types/gamedig/gamedig-tests.ts
  types/gamedig/index.d.cts
  types/gamedig/package.json
  types/gamedig/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Owners

#69781 [k6] Fix `ResponseBody` type to use `ArrayBuffer` instead of `bytes`
  types/k6/http.d.ts
  types/k6/k6-tests.ts
  types/k6/test/http.ts
Labels: Popular package, Self Merge, Owner Approved

#69901 [@types/react-instantsearch-dom] Add onFocus to SearchBoxProps
  types/react-instantsearch-dom/index.d.ts
  types/react-instantsearch-dom/react-instantsearch-dom-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#69903 [@types/jqueryui] Button method return types
  attw.json
  types/jqueryui/index.d.ts
  types/jqueryui/jqueryui-tests.ts
  types/jqueryui/package.json
Labels: Popular package, Self Merge, Owner Approved

#69735 Node auth users settings update
  types/node-red__runtime/index.d.ts
  types/node-red__runtime/node-red__runtime-tests.ts
Labels: Self Merge, Owner Approved

#69879 [node] events: improve static methods, fix broken reversion
  types/node/events.d.ts
  types/node/test/events.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#69887 fix 'frictionStuffness' -> 'frictionStiffness' type on p2 types
  types/p2/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69892 [webxr] Add missing s for XRInputSourcesChangeEvent
  types/webxr/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69893 [@types/micromatch] Add new negatedExtglob state to result of scan
  types/micromatch/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69908 Fix some definitions for qz-tray
  types/qz-tray/index.d.ts
  types/qz-tray/qz-tray-tests.ts
Labels: Self Merge, Owner Approved

#69917 [styled-theming] use new conditional ts-expect-ignore
  types/styled-theming/styled-theming-tests.tsx
Labels: Self Merge, Maintainer Approved

#69918 update Version of bun-types in @types/bun to 1.1.17
  types/bun/package.json
Labels: Popular package, Self Merge, Owner Approved

#69687 Add template import type for uniqueId helper
  types/ember__helper/ember__helper-tests.ts
  types/ember__helper/index.d.ts
Labels: Self Merge, Owner Approved

#69750 fix: typescript compilation error in lib/webdriver.d.ts
  types/selenium-webdriver/lib/webdriver.d.ts
  types/selenium-webdriver/test/index.ts
Labels: Self Merge, Maintainer Approved, Critical package

#69936 fix(clownface): improve support iterables in overloads
  types/clownface/clownface-tests.ts
  types/clownface/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#69725 relay-runtime - Improve type-safety of RecordProxy#getOrCreateLinkedRecord
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
Labels: Unmerged, Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#69927 rails__actioncable update createConsumer type to accept function which returns string
  types/rails__actioncable/index.d.ts
  types/rails__actioncable/rails__actioncable-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69935 [postcss-functions] fix plugin options type
  types/postcss-functions/index.d.ts
  types/postcss-functions/postcss-functions-tests.ts
Labels: Self Merge, Owner Approved

#69613 [WebXR] Add hapticActuators to gamepad on XRInputSource
  types/webxr/index.d.ts
  types/webxr/webxr-tests.ts
Labels: Unmerged, Popular package, Self Merge, Author is Owner, Owner Approved

#69729 (@types/exaroton) update exaroton types to 1.11
  types/exaroton/exaroton-tests.ts
  types/exaroton/index.d.ts
  types/exaroton/package.json
  types/exaroton/tsconfig.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#69948 [micromatch] Remove myself from owners
  types/micromatch/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits Owners

#69949 [oidc-provider] v8.5.0 bump
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
  types/oidc-provider/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#69905 [@types/picomatch] Add new negatedExtglob state to result of scan
  types/picomatch/lib/scan.d.ts
  types/picomatch/picomatch-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#69771 culori: Add XYB colorspace, missing fns, and culori/css + culori/all entry points
  types/culori/all/index.d.ts
  types/culori/css/index.d.ts
  types/culori/fn/index.d.ts
  types/culori/index.d.ts
  types/culori/package.json
  types/culori/src/clamp.d.ts
  types/culori/src/common.d.ts
  types/culori/src/displayable.d.ts
  types/culori/src/xyb/constants.d.ts
  types/culori/src/xyb/convertRgbToXyb.d.ts
  types/culori/src/xyb/convertXybToRgb.d.ts
  types/culori/src/xyb/definition.d.ts
  types/culori/src/xyb/types.d.ts
  types/culori/test/clamp.test.ts
  types/culori/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Owners

#69956 Only check watchdog every two hours
  .github/workflows/watchdog-publisher.yml
  .github/workflows/watchdog-typescript-bot.yml
Labels: Edits Infrastructure
