Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2025-10, with the labels that each got.

#73766 [react-dom] Add types for `headersLengthHint`, `importMap` and `onHeaders` to /server and /static rendering APIs
  types/react-dom/server.d.ts
  types/react-dom/static.d.ts
  types/react-dom/test/react-dom-tests.tsx
Labels: Author is Owner, Critical package

#73794 [chrome] update sidePanel namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73659 upgrade: update types for exaroton 1.12.0
  types/exaroton/exaroton-tests.ts
  types/exaroton/index.d.ts
  types/exaroton/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#73798 [chrome] update system.memory namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73797 [chrome] update system.cpu namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73806 [tapable] fix test, bump to 2.3.0
  types/tapable/package.json
  types/tapable/tapable-tests.ts
Labels: Critical package

#73802 [chrome] update tabCapture namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73805 [recordrtc] accept array of MediaStream in RecordRTC constructor
  types/recordrtc/index.d.ts
  types/recordrtc/recordrtc-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73824 [es6-collections] Pull in es6 types
  types/es6-collections/index.d.ts
Labels: Untested Change

#73817 [aws-lambda] fix casing of fields in SNSMessage type
  types/aws-lambda/test/sns-tests.ts
  types/aws-lambda/trigger/sns.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#73820 [wicg-file-system-access] update types to match DOM declaration
  types/wicg-file-system-access/index.d.ts
Labels: Popular package, Untested Change

#73742 google-apps-script: Added missing methods for Action
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#73793 node: v24.7
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/http.d.ts
  types/node/http2.d.ts
  types/node/index.d.ts
  types/node/inspector.d.ts
  types/node/inspector.generated.d.ts
  types/node/package.json
  types/node/sqlite.d.ts
  types/node/stream/web.d.ts
  types/node/test.d.ts
  types/node/test/crypto.ts
  types/node/test/globals-non-dom.ts
  types/node/test/http.ts
  types/node/test/http2.ts
  types/node/test/sqlite.ts
  types/node/test/test.ts
  types/node/ts5.6/index.d.ts
  types/node/ts5.7/index.d.ts
  types/node/web-globals/crypto.d.ts
  types/node/web-globals/streams.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#73631 Add `apollo-upload-client` definitions for `19.0.0` version (update createUploadLink -> UploadHttpLink)
  types/apollo-upload-client/UploadHttpLink.d.mts
  types/apollo-upload-client/apollo-upload-client-tests.ts
  types/apollo-upload-client/createUploadLink.d.mts
  types/apollo-upload-client/package.json
  types/apollo-upload-client/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved

#73681 fix express-serve-static-core application event emitter types
  types/express-serve-static-core/express-serve-static-core-tests.ts
  types/express-serve-static-core/index.d.ts
  types/express-serve-static-core/package.json
  types/express-serve-static-core/v4/index.d.ts
Labels: Owner Approved, Critical package, Unreviewed

#73651 feat(react): add "closedby" to DialogHTMLAttributes
  types/babel-plugin-react-html-attrs/babel-plugin-react-html-attrs-tests.tsx
  types/babel-plugin-react-html-attrs/index.d.ts
  types/rax/index.d.ts
  types/react/index.d.ts
  types/react/test/elementAttributes.tsx
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/test/elementAttributes.tsx
  types/react/v16/index.d.ts
  types/react/v16/test/elementAttributes.tsx
  types/react/v17/index.d.ts
  types/react/v17/test/elementAttributes.tsx
  types/react/v18/index.d.ts
  types/react/v18/test/elementAttributes.tsx
  types/react/v18/ts5.0/index.d.ts
  types/react/v18/ts5.0/test/elementAttributes.tsx
Labels: Edits multiple packages, Critical package, Unreviewed

#73849 reveal.js: include config fields from notes plugin
  types/reveal.js/plugin/notes/notes.esm.d.ts
  types/reveal.js/plugin/notes/notes/index.d.ts
  types/reveal.js/reveal.esm.js-tests.ts
  types/reveal.js/reveal.js-tests.ts
Labels: Self Merge, Owner Approved
