Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2025-06, with the labels that each got.

#72660 fix(pg): use same version of pg-types that's use in pg itself
  types/pg/index.d.ts
  types/pg/package.json
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#72731 Update fetch-meta-tags second optional param requestInit
  types/fetch-meta-tags/fetch-meta-tags-tests.ts
  types/fetch-meta-tags/index.d.ts
  types/fetch-meta-tags/package.json
  types/fetch-meta-tags/tsconfig.json
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#72857 [mjml-core] Fix registerComponent function typing
  types/mjml-core/index.d.ts
  types/mjml-core/mjml-core-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#72848 chore: update Twig type definitions for consistency and clarity
  types/twig/index.d.ts
  types/twig/twig-tests.ts
Labels: Other Approved, Unmerged, Self Merge

#72929 n3: Add N3Util.isQuad type predicate
  types/n3/index.d.ts
  types/n3/n3-tests.ts
  types/n3/package.json
Labels: Other Approved, Self Merge

#72792 update 0.8.3
  types/js-md5/index.d.ts
  types/js-md5/js-md5-tests.ts
  types/js-md5/package.json
Labels: Self Merge, Maintainer Approved

#72931 feat(pizzip): remove types
  notNeededPackages.json
  types/pizzip/.npmignore
  types/pizzip/index.d.ts
  types/pizzip/package.json
  types/pizzip/pizzip-tests.ts
  types/pizzip/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72933 feat(chenfengyuan__vue-qrcode): remove types
  notNeededPackages.json
  types/chenfengyuan__vue-qrcode/.npmignore
  types/chenfengyuan__vue-qrcode/chenfengyuan__vue-qrcode-tests.ts
  types/chenfengyuan__vue-qrcode/index.d.ts
  types/chenfengyuan__vue-qrcode/package.json
  types/chenfengyuan__vue-qrcode/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72934 feat(flatbuffers): remove types
  notNeededPackages.json
  types/flatbuffers/.npmignore
  types/flatbuffers/flatbuffers-tests.ts
  types/flatbuffers/index.d.ts
  types/flatbuffers/package.json
  types/flatbuffers/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#72936 feat(hapi__jwt): remove types
  notNeededPackages.json
  types/hapi__jwt/.npmignore
  types/hapi__jwt/hapi__jwt-tests.ts
  types/hapi__jwt/index.d.ts
  types/hapi__jwt/package.json
  types/hapi__jwt/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72926 fix(react-dom): add environment-specific entrypoints
  types/react-dom/package.json
  types/react-dom/server.browser.d.ts
  types/react-dom/server.bun.d.ts
  types/react-dom/server.edge.d.ts
  types/react-dom/server.node.d.ts
  types/react-dom/static.browser.d.ts
  types/react-dom/static.edge.d.ts
  types/react-dom/static.node.d.ts
Labels: Critical package, Untested Change

#72898 Update for IMA v3.697.0
  types/google_interactive_media_ads_types/index.d.ts
  types/google_interactive_media_ads_types/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#72692 Add the missing callbacks param for the resumeTransaction method.
  types/paystack__inline-js/index.d.ts
  types/paystack__inline-js/paystack__inline-js-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#72887 fix(node/http2): refine SessionOptions typings, add jsdoc
  types/node/http2.d.ts
  types/node/test/http2.ts
  types/node/v18/http2.d.ts
  types/node/v18/test/http2.ts
  types/node/v20/http2.d.ts
  types/node/v20/test/http2.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72922 node: `util.parseEnv()` returns string dictionary
  types/node/test/util.ts
  types/node/util.d.ts
  types/node/v20/test/util.ts
  types/node/v20/util.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#72958 [@event-calendar/core] Update type definitions for version 4.4 release.
  types/event-calendar__core/event-calendar__core-tests.ts
  types/event-calendar__core/index.d.ts
  types/event-calendar__core/package.json
Labels: Self Merge, Owner Approved

#72847 fix(bn.js): `bigint` is actually supported as a side effect of `.toString()`
  types/bn.js/bn.js-tests.ts
  types/bn.js/index.d.ts
  types/bn.js/package.json
Labels: Self Merge, Maintainer Approved, Critical package, Edits Owners

#72892 [estree] add support for `using` and `await using` declarations
  types/estree/estree-tests.ts
  types/estree/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72935 feat(node_redis): remove types
  types/node_redis/.eslintrc.json
  types/node_redis/.npmignore
  types/node_redis/index.d.ts
  types/node_redis/package.json
  types/node_redis/tsconfig.json
Labels: Self Merge, Maintainer Approved, Untested Change

#72517 add bjohansebas as an owner of several express packages
  types/body-parser/package.json
  types/compressible/package.json
  types/compression/package.json
  types/content-disposition/package.json
  types/content-type/package.json
  types/cookie-parser/package.json
  types/cookies/package.json
  types/cors/package.json
  types/encodeurl/package.json
  types/etag/package.json
  types/express-session/package.json
  types/express/package.json
  types/express/v4/package.json
  types/finalhandler/package.json
  types/forwarded/package.json
  types/fresh/package.json
  types/hbs/package.json
  types/http-errors/package.json
  types/mime-db/package.json
  types/mime-types/package.json
  types/morgan/package.json
  types/multer/package.json
  types/negotiator/package.json
  types/on-finished/package.json
  types/on-headers/package.json
  types/response-time/package.json
  types/send/package.json
  types/serve-static/package.json
  types/statuses/package.json
  types/statuses/v1/package.json
  types/vhost/package.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package, Edits Owners

#72851 Add StartInterval to HealthConfig for Dockerode project
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#72946 leaflet.vectorgrid: fix copy/paste error in TileParameters
  types/leaflet.vectorgrid/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#72980 [navermaps] Fix types - ReverseGeocodeResponse(Area, Land)
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#72951 reveal.js: add controls:"speaker-only" type
  types/reveal.js/index.d.ts
  types/reveal.js/package.json
  types/reveal.js/reveal.js-tests.ts
Labels: Other Approved, Self Merge

#72979 [OvenPlayer] Add types for doubleTapToSeek and parseStream initialization options and metaData event
  types/ovenplayer/index.d.ts
  types/ovenplayer/ovenplayer-tests.ts
  types/ovenplayer/package.json
  types/ovenplayer/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved

#72984 Update google-apps-script typings to include EventType support in CalendarApp
  types/google-apps-script/google-apps-script.calendar.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#72989 Add html attributes to react-spinner
  types/react-spinner/index.d.ts
  types/react-spinner/react-spinner-tests.tsx
Labels: Self Merge, Owner Approved

#72949 [react] Update SuspenseList types
  types/react-is/test/canary-tests.tsx
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Revision needed, Author is Owner, Edits multiple packages, Critical package

#73003 [bun] update to 1.2.16
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits Owners

#73008 [invity-api]: add trade signatures
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#72964 Create @types/country-iso
  types/country-iso/.npmignore
  types/country-iso/country-iso-tests.ts
  types/country-iso/index.d.ts
  types/country-iso/package.json
  types/country-iso/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72967 [oracledb] Fix fetchInfo type
  types/oracledb/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#73004 feat: types/validator add support for 'loose' for UUID version
  types/validator/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#72970 @types/steam-user - Fix spelling mistakes
  types/steam-user/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#73033 jsonwebtoken - Tighten audience and issuer properties of VerifyOptions to disallow empty arrays
  types/jsonwebtoken/index.d.ts
  types/jsonwebtoken/jsonwebtoken-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72918 google.accounts add support for use_fedcm_for_button
  types/google.accounts/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#73017 feat: add types for the Trello PowerUp Client Library
  types/trellopowerup/.npmignore
  types/trellopowerup/index.d.ts
  types/trellopowerup/lib/base.d.ts
  types/trellopowerup/lib/callback.d.ts
  types/trellopowerup/lib/context.d.ts
  types/trellopowerup/lib/hosthandlers.d.ts
  types/trellopowerup/lib/localizer.d.ts
  types/trellopowerup/lib/powerup.d.ts
  types/trellopowerup/lib/restapi.d.ts
  types/trellopowerup/lib/theming.d.ts
  types/trellopowerup/lib/util.d.ts
  types/trellopowerup/package.json
  types/trellopowerup/tests/base-tests.ts
  types/trellopowerup/tests/callback-tests.ts
  types/trellopowerup/tests/context-tests.ts
  types/trellopowerup/tests/hosthandlers-tests.ts
  types/trellopowerup/tests/index-tests.ts
  types/trellopowerup/tests/localizer-tests.ts
  types/trellopowerup/tests/powerup-tests.ts
  types/trellopowerup/tests/restapi-tests.ts
  types/trellopowerup/tests/theming-tests.ts
  types/trellopowerup/tests/util-tests.ts
  types/trellopowerup/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72540 fix(node/assert): refine the signature of CallTracker.calls()
  types/node/assert.d.ts
  types/node/test/assert.ts
  types/node/v18/assert.d.ts
  types/node/v18/test/assert.ts
  types/node/v20/assert.d.ts
  types/node/v20/test/assert.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72991 feat(ffmpeg-static): remove types
  notNeededPackages.json
  types/ffmpeg-static/.npmignore
  types/ffmpeg-static/ffmpeg-static-tests.ts
  types/ffmpeg-static/index.d.ts
  types/ffmpeg-static/package.json
  types/ffmpeg-static/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#72994 feat(sql-bricks): remove types
  notNeededPackages.json
  types/sql-bricks/.npmignore
  types/sql-bricks/index.d.ts
  types/sql-bricks/package.json
  types/sql-bricks/sql-bricks-tests.ts
  types/sql-bricks/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72995 feat(hapi__catbox): remove types
  notNeededPackages.json
  types/hapi__catbox-memcached/package.json
  types/hapi__catbox/.npmignore
  types/hapi__catbox/hapi__catbox-tests.ts
  types/hapi__catbox/index.d.ts
  types/hapi__catbox/package.json
  types/hapi__catbox/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#73022 [three-dat.gui] Remove instantiation of THREE.Material
  types/three-dat.gui/three-dat.gui-tests.ts
Labels: Self Merge, Owner Approved

#72536 [@types/lodash] Make sure readonly arrays can't be modified
  types/lodash/common/array.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73021 [russian-nouns-js] Updated to v2.3.0
  types/russian-nouns-js/index.d.ts
  types/russian-nouns-js/package.json
  types/russian-nouns-js/russian-nouns-js-tests.ts
  types/russian-nouns-js/src/Engine.d.ts
  types/russian-nouns-js/src/Lemma.d.ts
  types/russian-nouns-js/src/LocativeForm.d.ts
  types/russian-nouns-js/src/StressDictionary.d.ts
  types/russian-nouns-js/tsconfig.json
Labels: Self Merge, Owner Approved

#73069 fix[oidc-provider]: issueRegistrationAccessToken type
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73071 [mokapi] Update typings to v0.20.0
  types/mokapi/encoding.d.ts
  types/mokapi/faker.d.ts
  types/mokapi/global.d.ts
  types/mokapi/http.d.ts
  types/mokapi/index.d.ts
  types/mokapi/kafka.d.ts
  types/mokapi/mail.d.ts
  types/mokapi/mustache.d.ts
  types/mokapi/package.json
  types/mokapi/test/encoding-test.ts
  types/mokapi/test/faker-test.ts
  types/mokapi/test/mokapi-tests.ts
  types/mokapi/tsconfig.json
  types/mokapi/yaml.d.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#73068 [russian-nouns-js] restore deleted test file and add author
  types/russian-nouns-js/package.json
  types/russian-nouns-js/russian-nouns-js-tests.ts
  types/russian-nouns-js/tsconfig.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners, Edits Owners

#73076 [bun] update to 1.2.17
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72524 feat(zwlog-browser): add types in sendPV
  types/zwlog-browser/index.d.ts
  types/zwlog-browser/zwlog-browser-tests.ts
Labels: Self Merge, Maintainer Approved

#73042 feat(plotly.js): update ColorBar interface
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
  types/plotly.js/v2/index.d.ts
  types/plotly.js/v2/test/index-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73090 @types/npmcli__arborist: add Edge.workspace
  types/npmcli__arborist/index.d.ts
  types/npmcli__arborist/npmcli__arborist-tests.ts
Labels: Self Merge, Owner Approved

#73047 [xmpp__xml] do not use internal modules of ltx
  types/xmpp__xml/index.d.ts
  types/xmpp__xml/xmpp__xml-tests.ts
Labels: Other Approved, Self Merge

#73110 [dom-chromium-ai] Add tool support
  types/dom-chromium-ai/dom-chromium-ai-tests.ts
  types/dom-chromium-ai/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#73105 [russian-nouns-js] Removed assertions
  types/russian-nouns-js/russian-nouns-js-tests.ts
  types/russian-nouns-js/src/Lemma.d.ts
  types/russian-nouns-js/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Owners

#73119 Allow readonly array-param for pick* methods
  types/chance/chance-tests.ts
  types/chance/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#73113 [invity-api] dex approval flow tag
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#73102 Update module.d.ts
  types/node/module.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#73038 feat(hapi__basic): remove types
  notNeededPackages.json
  types/hapi__basic/.npmignore
  types/hapi__basic/hapi__basic-tests.ts
  types/hapi__basic/index.d.ts
  types/hapi__basic/package.json
  types/hapi__basic/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72982 [uikit]: uikit/3.23.9
  attw.json
  types/uikit/dist/js/uikit.d.ts
  types/uikit/index.d.ts
  types/uikit/package.json
  types/uikit/uikit-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved

#73084 feat(chrome): add chrome.management.ExtensionInfo.versionName
  types/chrome/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#73112 feat: adding types for uuid-encoder (https://www.npmjs.com/package/uuid-encoder)
  types/uuid-encoder/.npmignore
  types/uuid-encoder/index.d.ts
  types/uuid-encoder/package.json
  types/uuid-encoder/tsconfig.json
  types/uuid-encoder/uuid-encoder-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved

#72977 [chrome] update PlatformKeys namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#73093 [eslint-plugin-mobx] Add types for eslint-plugin-mobx
  types/eslint-plugin-mobx/.npmignore
  types/eslint-plugin-mobx/eslint-plugin-mobx-tests.ts
  types/eslint-plugin-mobx/index.d.ts
  types/eslint-plugin-mobx/package.json
  types/eslint-plugin-mobx/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73061 proj4 not needed any more
  notNeededPackages.json
  types/proj4/.npmignore
  types/proj4/index.d.ts
  types/proj4/package.json
  types/proj4/proj4-tests.ts
  types/proj4/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#73127 [invity-api]: update signature trade
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#73107 [dockerode] Fix ConfigFrom type in NetworkCreateOptions
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#72961 fix(node): export TestContextAssert interface
  types/node/test.d.ts
  types/node/test/test.ts
Labels: Unmerged, Self Merge, Owner Approved, Critical package
