Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2025-04, with the labels that each got.

#72284 Transfer ownership of h-joo frigus and mprobst to brad4d and blickly.
  .github/CODEOWNERS
  types/closure-compiler/package.json
  types/dom-background-sync/package.json
  types/dom-navigation-preload/package.json
  types/dom-speech-recognition/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Edits Owners

#72268 ci: prevent pnpm-cache from running on forked repo
  .github/workflows/pnpm-cache.yml
Labels: Edits Infrastructure

#72297 feat(yog-ral): remove types
  notNeededPackages.json
  types/yog-ral/.npmignore
  types/yog-ral/index.d.ts
  types/yog-ral/package.json
  types/yog-ral/tsconfig.json
  types/yog-ral/yog-ral-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72299 feat(correlation-id): remove types
  notNeededPackages.json
  types/correlation-id/.npmignore
  types/correlation-id/correlation-id-tests.ts
  types/correlation-id/index.d.ts
  types/correlation-id/package.json
  types/correlation-id/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#72298 feat(base64-js): remove types
  notNeededPackages.json
  types/base64-js/.npmignore
  types/base64-js/index.d.ts
  types/base64-js/package.json
  types/base64-js/test/base64-js-tests.cjs.ts
  types/base64-js/test/base64-js-tests.global.ts
  types/base64-js/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72317 feat(romans): remove types
  notNeededPackages.json
  types/romans/.npmignore
  types/romans/index.d.ts
  types/romans/package.json
  types/romans/romans-tests.ts
  types/romans/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72318 feat(7zip-min): remove types
  notNeededPackages.json
  types/7zip-min/.npmignore
  types/7zip-min/7zip-min-tests.ts
  types/7zip-min/index.d.ts
  types/7zip-min/package.json
  types/7zip-min/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72321 [ws] Update type of finishRequest to match documentation.
  types/ws/index.d.mts
  types/ws/index.d.ts
  types/ws/ws-tests.mts
  types/ws/ws-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72031 [node] `node:timers` cleanup, restore `NodeJS` namespace to ambient-only
  types/node/test/globals.ts
  types/node/test/timers.ts
  types/node/test/timers_promises.ts
  types/node/timers.d.ts
  types/node/timers/promises.d.ts
  types/node/v18/test/globals.ts
  types/node/v18/test/timers.ts
  types/node/v18/test/timers_promises.ts
  types/node/v18/timers.d.ts
  types/node/v18/timers/promises.d.ts
  types/node/v20/test/globals.ts
  types/node/v20/test/timers.ts
  types/node/v20/test/timers_promises.ts
  types/node/v20/timers.d.ts
  types/node/v20/timers/promises.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72106 delete: rdf-validate-shacl
  notNeededPackages.json
  types/rdf-validate-shacl/.eslintrc.json
  types/rdf-validate-shacl/.npmignore
  types/rdf-validate-shacl/index.d.ts
  types/rdf-validate-shacl/package.json
  types/rdf-validate-shacl/rdf-validate-shacl-tests.ts
  types/rdf-validate-shacl/src/validation-report.d.ts
  types/rdf-validate-shacl/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72054 fix(@types/node): https.RequestOptions.checkServerIdentity is always called with DetailedPeerCertificate
  types/node/https.d.ts
  types/node/test/https.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72342 [README] Remove `base64-js` mention from README
  README.es.md
  README.fr.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72343 Remove ts5.0 dirs other than react
  types/dom-mediacapture-record/package.json
  types/dom-mediacapture-record/ts5.0/dom-mediacapture-record-tests.ts
  types/dom-mediacapture-record/ts5.0/index.d.ts
  types/dom-mediacapture-record/ts5.0/tsconfig.json
  types/webrtc/package.json
  types/webrtc/ts5.0/.eslintrc.json
  types/webrtc/ts5.0/MediaStream.d.ts
  types/webrtc/ts5.0/RTCPeerConnection.d.ts
  types/webrtc/ts5.0/index.d.ts
  types/webrtc/ts5.0/test/MediaStream.ts
  types/webrtc/ts5.0/test/RTCPeerConnection.ts
  types/webrtc/ts5.0/tsconfig.json
  types/wicg-file-system-access/package.json
  types/wicg-file-system-access/ts5.0/index.d.ts
  types/wicg-file-system-access/ts5.0/tsconfig.json
  types/wicg-file-system-access/ts5.0/wicg-file-system-access-tests.ts
Labels: Popular package, Edits multiple packages

#72316 feat(react-virtualized-auto-sizer): remove types
  notNeededPackages.json
  types/react-virtualized-auto-sizer/.npmignore
  types/react-virtualized-auto-sizer/index.d.ts
  types/react-virtualized-auto-sizer/package.json
  types/react-virtualized-auto-sizer/react-virtualized-auto-sizer-tests.tsx
  types/react-virtualized-auto-sizer/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72347 feat(react-native-webrtc): remove types
  notNeededPackages.json
  types/react-native-webrtc/.npmignore
  types/react-native-webrtc/index.d.ts
  types/react-native-webrtc/package.json
  types/react-native-webrtc/react-native-webrtc-tests.tsx
  types/react-native-webrtc/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72351 fix(picomatch): bump version, add missing declaration, fix Matcher type
  types/picomatch/lib/picomatch.d.ts
  types/picomatch/package.json
  types/picomatch/picomatch-tests.ts
  types/picomatch/posix.d.ts
  types/picomatch/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved

#72331 [zendesk-web-widget] add resetWidget signature
  types/zendesk-web-widget/index.d.ts
  types/zendesk-web-widget/zendesk-web-widget-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#72244 fix(pdf-parse): move @types/node to dep, modify pagerender return type
  types/pdf-parse/index.d.ts
  types/pdf-parse/package.json
  types/pdf-parse/pdf-parse-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72355 feat(cloudflare): remove types
  notNeededPackages.json
  types/cloudflare/.eslintrc.json
  types/cloudflare/.npmignore
  types/cloudflare/cloudflare-tests.ts
  types/cloudflare/index.d.ts
  types/cloudflare/package.json
  types/cloudflare/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#72353 feat(vexflow): remove types
  notNeededPackages.json
  types/vexflow/.eslintrc.json
  types/vexflow/.npmignore
  types/vexflow/index.d.ts
  types/vexflow/package.json
  types/vexflow/tsconfig.json
  types/vexflow/vexflow-tests.ts
  types/vextab/package.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#72356 feat(math-expression-evaluator): remove types
  notNeededPackages.json
  types/math-expression-evaluator/.npmignore
  types/math-expression-evaluator/index.d.ts
  types/math-expression-evaluator/math-expression-evaluator-tests.ts
  types/math-expression-evaluator/package.json
  types/math-expression-evaluator/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72350 feat(subtitle): remove types
  notNeededPackages.json
  types/subtitle/.npmignore
  types/subtitle/index.d.ts
  types/subtitle/package.json
  types/subtitle/subtitle-tests.ts
  types/subtitle/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72339 [react] Updates to View Transition
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Other Approved, Author is Owner, Edits multiple packages, Critical package, The CI failed

#72340 [react] Updates to Gesture Transitions
  types/react-dom/test/experimental-tests.tsx
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Author is Owner, Edits multiple packages, Critical package, Where is GH Actions?

#72348 [react] Add Fragment Refs
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
  types/react/experimental.d.ts
  types/react/index.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Other Approved, Author is Owner, Edits multiple packages, Critical package, Where is GH Actions?

#72341 Feature/mapping editor
  types/gorilla-engine/components/MappingEditor.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#72335 Fix type of React `bootstrapScripts` and `bootstrapModules`
  types/react-dom/server.d.ts
  types/react-dom/v18/server.d.ts
Labels: Critical package, The CI failed, Untested Change

#72267 feat(chivox_types): add MediaStream property and update TypeScript lib options
  types/chivox_h5sdk/src/html5/html5recorder.d.ts
  types/chivox_h5sdk/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change, Check Config

#72289 MapBox SDK: extend geocode response to align with documentation
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Self Merge, Owner Approved

#72354 feat(node-hid): remove types
  notNeededPackages.json
  types/node-hid/.npmignore
  types/node-hid/index.d.ts
  types/node-hid/node-hid-tests.ts
  types/node-hid/package.json
  types/node-hid/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#71922 [node] Update typings to v22.14.0
  types/node/fs.d.ts
  types/node/module.d.ts
  types/node/package.json
  types/node/process.d.ts
  types/node/sqlite.d.ts
  types/node/test.d.ts
  types/node/test/fs.ts
  types/node/test/module.ts
  types/node/test/process.ts
  types/node/test/sqlite.ts
  types/node/test/test.ts
  types/node/test/util.ts
  types/node/util.d.ts
  types/node/worker_threads.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72366 feat(forest-express-mongoose): remove types
  notNeededPackages.json
  types/forest-express-mongoose/.eslintrc.json
  types/forest-express-mongoose/.npmignore
  types/forest-express-mongoose/forest-express-mongoose-tests.ts
  types/forest-express-mongoose/index.d.ts
  types/forest-express-mongoose/package.json
  types/forest-express-mongoose/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72367 feat(ceddl__ceddl-polyfill): remove types
  notNeededPackages.json
  types/ceddl__ceddl-polyfill/.npmignore
  types/ceddl__ceddl-polyfill/ceddl__ceddl-polyfill-tests.ts
  types/ceddl__ceddl-polyfill/index.d.ts
  types/ceddl__ceddl-polyfill/package.json
  types/ceddl__ceddl-polyfill/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72369 feat(shevyjs): remove types
  notNeededPackages.json
  types/shevyjs/.npmignore
  types/shevyjs/constants/index.d.ts
  types/shevyjs/index.d.ts
  types/shevyjs/package.json
  types/shevyjs/shevyjs-tests.ts
  types/shevyjs/tsconfig.json
  types/shevyjs/types.d.ts
  types/shevyjs/utils/index.d.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72370 feat(easycaptchajs): remove types
  notNeededPackages.json
  types/easycaptchajs/.npmignore
  types/easycaptchajs/easycaptchajs-tests.ts
  types/easycaptchajs/index.d.ts
  types/easycaptchajs/package.json
  types/easycaptchajs/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72365 feat(react-dnd-multi-backend): remove types
  notNeededPackages.json
  types/react-dnd-multi-backend/.npmignore
  types/react-dnd-multi-backend/dist/HTML5toTouch.d.ts
  types/react-dnd-multi-backend/dist/cjs/HTML5toTouch.d.ts
  types/react-dnd-multi-backend/dist/esm/HTML5toTouch.d.ts
  types/react-dnd-multi-backend/index.d.ts
  types/react-dnd-multi-backend/package.json
  types/react-dnd-multi-backend/react-dnd-multi-backend-tests.tsx
  types/react-dnd-multi-backend/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72364 fix(delowar__react-circle-progressbar): fix FalseExportDefault, jsdoc
  attw.json
  types/delowar__react-circle-progressbar/delowar__react-circle-progressbar-tests.tsx
  types/delowar__react-circle-progressbar/index.d.ts
Labels: Self Merge, Maintainer Approved

#72371 feat(markdown-it-fence): add types
  types/markdown-it-fence/.npmignore
  types/markdown-it-fence/index.d.ts
  types/markdown-it-fence/markdown-it-fence-tests.ts
  types/markdown-it-fence/package.json
  types/markdown-it-fence/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72363 feat(git-url-parse,git-up): update types to match latest versions
  types/git-up/git-up-tests.ts
  types/git-up/index.d.ts
  types/git-up/package.json
  types/git-url-parse/git-url-parse-tests.ts
  types/git-url-parse/index.d.ts
  types/git-url-parse/package.json
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved

#72376 feat(babel__generator): Add named export which introduced in @babel/generator@7.27.0
  types/babel__generator/babel__generator-tests.ts
  types/babel__generator/index.d.ts
  types/babel__generator/package.json
Labels: Self Merge, Maintainer Approved, Critical package

#72374 [Luxon] Fix output types of DateTime min/max
  types/luxon/src/datetime.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72124 [@types/govuk-frontend] Update for GOV.UK Frontend v5.9.0
  types/govuk-frontend/dist/govuk/all.bundle.d.mts
  types/govuk-frontend/dist/govuk/all.bundle.d.ts
  types/govuk-frontend/dist/govuk/common/closest-attribute-value.d.ts
  types/govuk-frontend/dist/govuk/common/configuration.d.ts
  types/govuk-frontend/dist/govuk/common/index.d.ts
  types/govuk-frontend/dist/govuk/component.d.mts
  types/govuk-frontend/dist/govuk/component.d.ts
  types/govuk-frontend/dist/govuk/components/accordion/accordion.d.ts
  types/govuk-frontend/dist/govuk/components/button/button.d.ts
  types/govuk-frontend/dist/govuk/components/character-count/character-count.d.ts
  types/govuk-frontend/dist/govuk/components/checkboxes/checkboxes.d.ts
  types/govuk-frontend/dist/govuk/components/error-summary/error-summary.d.ts
  types/govuk-frontend/dist/govuk/components/exit-this-page/exit-this-page.d.ts
  types/govuk-frontend/dist/govuk/components/file-upload/file-upload.d.mts
  types/govuk-frontend/dist/govuk/components/file-upload/file-upload.d.ts
  types/govuk-frontend/dist/govuk/components/header/header.d.ts
  types/govuk-frontend/dist/govuk/components/notification-banner/notification-banner.d.ts
  types/govuk-frontend/dist/govuk/components/password-input/password-input.d.ts
  types/govuk-frontend/dist/govuk/components/radios/radios.d.ts
  types/govuk-frontend/dist/govuk/components/service-navigation/service-navigation.d.ts
  types/govuk-frontend/dist/govuk/components/skip-link/skip-link.d.ts
  types/govuk-frontend/dist/govuk/components/tabs/tabs.d.ts
  types/govuk-frontend/dist/govuk/errors/index.d.ts
  types/govuk-frontend/dist/govuk/govuk-frontend-component.d.mts
  types/govuk-frontend/dist/govuk/i18n.d.ts
  types/govuk-frontend/dist/govuk/init.d.ts
  types/govuk-frontend/govuk-frontend-tests.mts
  types/govuk-frontend/govuk-frontend-tests.ts
  types/govuk-frontend/package.json
  types/govuk-frontend/tsconfig.json
Labels: Self Merge, Author is Owner, Maintainer Approved

#72380 feat(nodemon): remove types
  notNeededPackages.json
  types/nodemon/.npmignore
  types/nodemon/index.d.ts
  types/nodemon/nodemon-tests.ts
  types/nodemon/package.json
  types/nodemon/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72381 feat(markdown-it-color-inline): add types
  types/markdown-it-color-inline/.npmignore
  types/markdown-it-color-inline/index.d.ts
  types/markdown-it-color-inline/lib/inlinecolor.d.ts
  types/markdown-it-color-inline/markdown-it-color-inline-tests.ts
  types/markdown-it-color-inline/package.json
  types/markdown-it-color-inline/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72382 feat(ads-client): remove types
  notNeededPackages.json
  types/ads-client/.npmignore
  types/ads-client/ads-client-tests.ts
  types/ads-client/index.d.ts
  types/ads-client/package.json
  types/ads-client/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72383 feat(hapi__catbox-redis): remove types
  notNeededPackages.json
  types/hapi__catbox-redis/.npmignore
  types/hapi__catbox-redis/hapi__catbox-redis-tests.ts
  types/hapi__catbox-redis/index.d.ts
  types/hapi__catbox-redis/package.json
  types/hapi__catbox-redis/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72384 feat(couchbase): remove types
  notNeededPackages.json
  types/couchbase/.eslintrc.json
  types/couchbase/.npmignore
  types/couchbase/couchbase-tests.ts
  types/couchbase/index.d.ts
  types/couchbase/package.json
  types/couchbase/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72385 feat(detect-port): remove types
  notNeededPackages.json
  types/detect-port/.npmignore
  types/detect-port/detect-port-tests.ts
  types/detect-port/index.d.ts
  types/detect-port/package.json
  types/detect-port/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Critical package

#72386 feat(pubnub): remove types
  notNeededPackages.json
  types/pubnub/.eslintrc.json
  types/pubnub/.npmignore
  types/pubnub/index.d.ts
  types/pubnub/package.json
  types/pubnub/pubnub-tests.ts
  types/pubnub/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72378 tabulator-tables - selectableCheck is deprecated by selectableRowsCheck
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#72399 Fix VS Code settings precedence by splitting
  .vscode/settings.template.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72396 fix(better-sqlite3): use any instead of unknown for function()
  types/better-sqlite3/better-sqlite3-tests.ts
  types/better-sqlite3/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72379 fix(timed-cache): add type: module, add callback option, jsdoc
  attw.json
  types/timed-cache/index.d.ts
  types/timed-cache/package.json
  types/timed-cache/timed-cache-tests.ts
Labels: Self Merge, Maintainer Approved

#72401 feat(sunrise-sunset-js): remove types
  notNeededPackages.json
  types/sunrise-sunset-js/.npmignore
  types/sunrise-sunset-js/index.d.ts
  types/sunrise-sunset-js/package.json
  types/sunrise-sunset-js/sunrise-sunset-js-tests.ts
  types/sunrise-sunset-js/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72389 feat(flexmonster): remove types
  notNeededPackages.json
  types/flexmonster/.npmignore
  types/flexmonster/flexmonster-tests.ts
  types/flexmonster/index.d.ts
  types/flexmonster/package.json
  types/flexmonster/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72402 feat(react-flags-select): remove types
  attw.json
  notNeededPackages.json
  types/react-flags-select/.npmignore
  types/react-flags-select/index.d.ts
  types/react-flags-select/package.json
  types/react-flags-select/react-flags-select-tests.tsx
  types/react-flags-select/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72405 feat(vite-plugin-react-control-statements): remove types
  notNeededPackages.json
  types/vite-plugin-react-control-statements/.npmignore
  types/vite-plugin-react-control-statements/index.d.ts
  types/vite-plugin-react-control-statements/package.json
  types/vite-plugin-react-control-statements/tsconfig.json
  types/vite-plugin-react-control-statements/vite-plugin-react-control-statements-tests.tsx
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72390 feat(lowdb): remove types
  notNeededPackages.json
  types/json-server/package.json
  types/json-server/tsconfig.json
  types/lowdb/.eslintrc.json
  types/lowdb/.npmignore
  types/lowdb/adapters/Base.d.ts
  types/lowdb/adapters/FileAsync.d.ts
  types/lowdb/adapters/FileSync.d.ts
  types/lowdb/adapters/LocalStorage.d.ts
  types/lowdb/adapters/Memory.d.ts
  types/lowdb/index.d.ts
  types/lowdb/lib/fp.d.ts
  types/lowdb/lib/main.d.ts
  types/lowdb/lowdb-tests.ts
  types/lowdb/package.json
  types/lowdb/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#72406 feat(markdown-it-highlightjs): remove types
  notNeededPackages.json
  types/markdown-it-highlightjs/.npmignore
  types/markdown-it-highlightjs/index.d.ts
  types/markdown-it-highlightjs/markdown-it-highlightjs-tests.ts
  types/markdown-it-highlightjs/package.json
  types/markdown-it-highlightjs/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72412 feat(kesha-antonov__react-native-background-downloader): remove types
  notNeededPackages.json
  types/kesha-antonov__react-native-background-downloader/.npmignore
  types/kesha-antonov__react-native-background-downloader/index.d.ts
  types/kesha-antonov__react-native-background-downloader/kesha-antonov__react-native-background-downloader-tests.ts
  types/kesha-antonov__react-native-background-downloader/package.json
  types/kesha-antonov__react-native-background-downloader/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72411 feat(recharts): remove types
  notNeededPackages.json
  types/recharts/.npmignore
  types/recharts/README.md
  types/recharts/index.d.ts
  types/recharts/package.json
  types/recharts/recharts-tests.tsx
  types/recharts/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72395 feat(react-highcharts): add missing props & methods, resolve attw
  attw.json
  types/react-highcharts/index.d.ts
  types/react-highcharts/react-highcharts-tests.tsx
Labels: Self Merge, Maintainer Approved

#72398 Add types for @architect/utils
  types/architect__utils/.npmignore
  types/architect__utils/architect__utils-tests.ts
  types/architect__utils/index.d.ts
  types/architect__utils/package.json
  types/architect__utils/tsconfig.json
  types/architect__utils/updater.d.ts
Labels: New Definition, Self Merge, Maintainer Approved

#72410 feat(bs58): remove types
  notNeededPackages.json
  types/bs58/.npmignore
  types/bs58/bs58-tests.ts
  types/bs58/index.d.ts
  types/bs58/package.json
  types/bs58/tsconfig.json
  types/bs58/v3/.npmignore
  types/bs58/v3/bs58-tests.ts
  types/bs58/v3/index.d.ts
  types/bs58/v3/package.json
  types/bs58/v3/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72409 feat(title): remove types
  notNeededPackages.json
  types/title/.npmignore
  types/title/index.d.ts
  types/title/package.json
  types/title/title-tests.ts
  types/title/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72422 feat(survicate__react-native-survicate): remove types
  notNeededPackages.json
  types/survicate__react-native-survicate/.npmignore
  types/survicate__react-native-survicate/index.d.ts
  types/survicate__react-native-survicate/package.json
  types/survicate__react-native-survicate/survicate__react-native-survicate-tests.ts
  types/survicate__react-native-survicate/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72427 Fix for not returning null for array get commands
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#72421 feat(react-native-calendars): remove types
  notNeededPackages.json
  types/react-native-calendars/.npmignore
  types/react-native-calendars/index.d.ts
  types/react-native-calendars/package.json
  types/react-native-calendars/react-native-calendars-tests.tsx
  types/react-native-calendars/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72423 feat(koa-helmet): remove types
  notNeededPackages.json
  types/koa-helmet/.npmignore
  types/koa-helmet/index.d.ts
  types/koa-helmet/koa-helmet-tests.ts
  types/koa-helmet/package.json
  types/koa-helmet/tsconfig.json
  types/koa-helmet/v5/.npmignore
  types/koa-helmet/v5/index.d.ts
  types/koa-helmet/v5/koa-helmet-tests.ts
  types/koa-helmet/v5/package.json
  types/koa-helmet/v5/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72425 feat(zinggrid): remove types
  notNeededPackages.json
  types/zinggrid/.npmignore
  types/zinggrid/index.d.ts
  types/zinggrid/package.json
  types/zinggrid/tsconfig.json
  types/zinggrid/zinggrid-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72426 feat(apicalypse): remove types
  notNeededPackages.json
  types/apicalypse/.npmignore
  types/apicalypse/apicalypse-tests.ts
  types/apicalypse/index.d.ts
  types/apicalypse/package.json
  types/apicalypse/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72229 Add @devicefarmer/stf-syrup types
  types/devicefarmer__stf-syrup/.npmignore
  types/devicefarmer__stf-syrup/devicefarmer__stf-syrup-tests.ts
  types/devicefarmer__stf-syrup/index.d.ts
  types/devicefarmer__stf-syrup/package.json
  types/devicefarmer__stf-syrup/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72432 [xrm] Add getAttributeType method to specific attribute interfaces, changes getControlType method to use template literal instead of string
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#72431 Fix type of React `bootstrapScripts` and `bootstrapModules` (static)
  types/react-dom/static.d.ts
Labels: Critical package, Untested Change

#72437 [bun] update to 1.2.9
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72442 Update headerMenu type definition
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#72404 feat(certstream): add types
  types/certstream/.npmignore
  types/certstream/certstream-tests.ts
  types/certstream/index.d.ts
  types/certstream/package.json
  types/certstream/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72449 feat(seneca): remove types
  notNeededPackages.json
  types/seneca/.eslintrc.json
  types/seneca/.npmignore
  types/seneca/index.d.ts
  types/seneca/package.json
  types/seneca/seneca-tests.ts
  types/seneca/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72448 feat(lestate): remove types
  types/lestate/.eslintrc.json
  types/lestate/.npmignore
  types/lestate/index.d.ts
  types/lestate/lestate-tests.ts
  types/lestate/package.json
  types/lestate/tsconfig.json
Labels: Self Merge, Maintainer Approved, No Other Owners

#72450 feat(quaternion): remove types
  notNeededPackages.json
  types/quaternion/.npmignore
  types/quaternion/index.d.ts
  types/quaternion/package.json
  types/quaternion/quaternion-tests.ts
  types/quaternion/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72358 Add missing top-level methods to Plotly namespace
  types/plotly.js/index.d.ts
  types/plotly.js/test/core-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#72445 Add event binding methods for isotope-layout
  types/isotope-layout/index.d.ts
  types/isotope-layout/isotope-layout-tests.ts
Labels: Self Merge, Owner Approved

#72454 [react] Add `unstable_Activity`
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Author is Owner, Critical package

#72430 fix(nodegit): replace deprecated type names
  types/nodegit/nodegit-tests.ts
  types/nodegit/reference.d.ts
Labels: Other Approved, Self Merge, Owner Approved

#72451 feat(jsoneditoronline): remove types
  types/jsoneditoronline/.eslintrc.json
  types/jsoneditoronline/.npmignore
  types/jsoneditoronline/index.d.ts
  types/jsoneditoronline/jsoneditoronline-tests.ts
  types/jsoneditoronline/package.json
  types/jsoneditoronline/tsconfig.json
Labels: Other Approved, Self Merge

#72424 feat(workgrid-core): remove types
  types/workgrid-core/.npmignore
  types/workgrid-core/index.d.ts
  types/workgrid-core/package.json
  types/workgrid-core/tsconfig.json
  types/workgrid-core/workgrid-core-tests.ts
Labels: Other Approved, Self Merge

#72200 fix(node): export parseArgs options config types
  types/node/test/util.ts
  types/node/util.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Critical package

#72253 [Chrome] update contextMenus namespaces
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#72243 [Chrome] update tts namespaces
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#72455 [pg] Remove non-existent min option
  types/pg-pool/pg-pool-tests.ts
  types/pg/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#72462 feat(tinymce): remove types
  notNeededPackages.json
  types/react-mce/package.json
  types/tinymce/.eslintrc.json
  types/tinymce/.npmignore
  types/tinymce/index.d.ts
  types/tinymce/package.json
  types/tinymce/tinymce-tests.ts
  types/tinymce/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#72461 feat(simple-datatables): remove types
  notNeededPackages.json
  types/simple-datatables/.npmignore
  types/simple-datatables/index.d.ts
  types/simple-datatables/package.json
  types/simple-datatables/simple-datatables-tests.ts
  types/simple-datatables/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72460 feat(package-name-regex): remove types
  notNeededPackages.json
  types/package-name-regex/.npmignore
  types/package-name-regex/index.d.ts
  types/package-name-regex/package-name-regex-tests.ts
  types/package-name-regex/package.json
  types/package-name-regex/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72459 feat(cli-welcome): remove types
  notNeededPackages.json
  types/cli-welcome/.npmignore
  types/cli-welcome/cli-welcome-tests.ts
  types/cli-welcome/index.d.ts
  types/cli-welcome/package.json
  types/cli-welcome/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72458 feat(httpsnippet): remove types
  notNeededPackages.json
  types/httpsnippet/.npmignore
  types/httpsnippet/httpsnippet-tests.ts
  types/httpsnippet/index.d.ts
  types/httpsnippet/package.json
  types/httpsnippet/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72238 oracledb: add registration ID in CQN subscription message
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
  types/oracledb/package.json
Labels: Popular package, Self Merge, Maintainer Approved

#72064 [rascal] Fix @typescript-eslint/no-misused-promises errors on subscription events
  types/rascal/index.d.ts
Labels: Unmerged, Self Merge, Maintainer Approved, Untested Change

#72362 chore(node-apple-receipt-verify): Add missing `originalTransactionId` param
  types/node-apple-receipt-verify/index.d.ts
  types/node-apple-receipt-verify/node-apple-receipt-verify-tests.ts
Labels: Other Approved, Self Merge

#72245 dockerode: Update ImageInspectInfo to include new Descriptor model
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72467 feat(mini-html-webpack-plugin): remove types
  notNeededPackages.json
  types/mini-html-webpack-plugin/.npmignore
  types/mini-html-webpack-plugin/index.d.ts
  types/mini-html-webpack-plugin/mini-html-webpack-plugin-tests.ts
  types/mini-html-webpack-plugin/package.json
  types/mini-html-webpack-plugin/tsconfig.json
  types/vxna__mini-html-webpack-template/package.json
Labels: Edits Infrastructure, Edits multiple packages

#72468 feat(react-type-animation): remove types
  attw.json
  notNeededPackages.json
  types/react-type-animation/.npmignore
  types/react-type-animation/index.d.ts
  types/react-type-animation/package.json
  types/react-type-animation/react-type-animation-tests.tsx
  types/react-type-animation/tsconfig.json
Labels: Edits Infrastructure

#72470 feat(pvutils): remove types
  notNeededPackages.json
  types/pvutils/.eslintrc.json
  types/pvutils/.npmignore
  types/pvutils/index.d.ts
  types/pvutils/package.json
  types/pvutils/pvutils-tests.ts
  types/pvutils/tsconfig.json
Labels: Edits Infrastructure

#72478 feat(node-unifi): add types
  types/node-unifi/.npmignore
  types/node-unifi/index.d.ts
  types/node-unifi/node-unifi-tests.ts
  types/node-unifi/package.json
  types/node-unifi/tsconfig.json
Labels: New Definition

#72488 feat(git-url-parse): remove types
  notNeededPackages.json
  types/git-url-parse/.npmignore
  types/git-url-parse/git-url-parse-tests.ts
  types/git-url-parse/index.d.ts
  types/git-url-parse/package.json
  types/git-url-parse/tsconfig.json
Labels: Popular package, Edits Infrastructure

#72457 Updates types for Recurly.js v4.33.2
  types/recurly__recurly-js/lib/paypal.d.ts
  types/recurly__recurly-js/package.json
Labels: Popular package, Untested Change

#72475 [@types/validator] update types for release 13.15.0
  types/validator/es/lib/isISO15924.d.ts
  types/validator/es/lib/isISO31661Numeric.d.ts
  types/validator/es/lib/isULID.d.ts
  types/validator/index.d.ts
  types/validator/lib/isISO15924.d.ts
  types/validator/lib/isISO31661Numeric.d.ts
  types/validator/lib/isISO4217.d.ts
  types/validator/lib/isULID.d.ts
  types/validator/lib/isURL.d.ts
  types/validator/package.json
  types/validator/validator-tests.ts
Labels: Author is Owner, Critical package

#72486 Remove myself as owner for `pg`
  types/pg/package.json
Labels: Author is Owner, Critical package, Edits Owners

#72084 Add rangy types
  types/rangy/index.d.ts
  types/rangy/lib/rangy-classapplier.d.ts
  types/rangy/lib/rangy-core.d.ts
  types/rangy/lib/rangy-highlighter.d.ts
  types/rangy/lib/rangy-selectionsaverestore.d.ts
  types/rangy/lib/rangy-serializer.d.ts
  types/rangy/lib/rangy-textrange.d.ts
  types/rangy/package.json
  types/rangy/rangy-classapplier.d.ts
  types/rangy/rangy-tests.ts
  types/rangy/tsconfig.json
Labels: Self Merge, Maintainer Approved, No Other Owners

#72503 fix: add missing param
  types/zwjsbridge/index.d.ts
  types/zwjsbridge/zwjsbridge-tests.ts
Labels: Self Merge, Owner Approved

#72502 fix(webxr): wrong type for XRProjectionLayer.ignoreDepthValues
  types/webxr/index.d.ts
Labels: Popular package, Owner Approved, Untested Change

#72512 feat(is-equal-shallow): add type support for is-equal-shallow package
  types/is-equal-shallow/.npmignore
  types/is-equal-shallow/index.d.ts
  types/is-equal-shallow/is-equal-shallow-tests.ts
  types/is-equal-shallow/package.json
  types/is-equal-shallow/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72527 [bun] update to 1.2.10
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72528 fix: "node-unifi" site stats type
  types/node-unifi/index.d.ts
  types/node-unifi/node-unifi-tests.ts
Labels: Self Merge, Owner Approved

#72522 [@types/docusign-esign] fix: Include updateEnvelopeDocGenFormFields in EnvelopeApi types
  types/docusign-esign/docusign-esign-tests.ts
  types/docusign-esign/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#72444 Replace prettier script with format using dprint
  package.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72542 refactor(pxroneline): update SocialVendorConsents to SocialConsents a…
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/oneline-tests.ts
  types/pxr-oneline/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72493 Add isInValuePreview type to custom-functions-runtime package's invocation object
  types/custom-functions-runtime/custom-functions-runtime-tests.ts
  types/custom-functions-runtime/index.d.ts
Labels: Self Merge, Owner Approved

#72501 fix definition for qz-tray
  types/qz-tray/index.d.ts
  types/qz-tray/qz-tray-tests.ts
Labels: Other Approved, Self Merge

#72447 feat(flowdoc): remove types
  types/flowdoc/.eslintrc.json
  types/flowdoc/.npmignore
  types/flowdoc/flowdoc-tests.ts
  types/flowdoc/index.d.ts
  types/flowdoc/package.json
  types/flowdoc/tsconfig.json
Labels: Other Approved, Self Merge

#72537 [@rails/activestorage] Update types for @rails/activestorage v8.0
  types/rails__activestorage/index.d.ts
  types/rails__activestorage/package.json
  types/rails__activestorage/rails__activestorage-tests.ts
Labels: Self Merge, Owner Approved

#72257 [Chrome] update permisions and optional_permissions lists
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Unmerged, Popular package, Self Merge, Author is Owner, Maintainer Approved

#72471 feat(itemsjs): add missing `ids` parameter to SearchOptions
  types/itemsjs/index.d.ts
  types/itemsjs/itemsjs-tests.ts
Labels: Self Merge, Owner Approved

#72441 forge-viewer: add FeatureFlags class
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
  types/forge-viewer/package.json
Labels: Self Merge, Owner Approved

#72433 feat(openseadragon): upgrade, make several option.button accept Element
  types/openseadragon/index.d.ts
  types/openseadragon/openseadragon-tests.ts
  types/openseadragon/package.json
Labels: Other Approved, Self Merge

#72584 pg: amend pg-protocol path resolution
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72452 fix(koa-generic-session): context extension #72440
  types/koa-generic-session/index.d.ts
  types/koa-generic-session/koa-generic-session-tests.ts
Labels: Other Approved, Self Merge, Author is Owner

#72491 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#72476 [novnc__novnc]: Add missing RFB event "clippingviewport" and update version to match NoVnc v1.6.0
  types/novnc__novnc/index.d.ts
  types/novnc__novnc/novnc__novnc-tests.ts
  types/novnc__novnc/package.json
Labels: Self Merge, Owner Approved

#72585 [three] r176
  types/three/examples/jsm/helpers/RapierHelper.d.ts
  types/three/examples/jsm/loaders/LottieLoader.d.ts
  types/three/examples/jsm/misc/MD2CharacterComplex.d.ts
  types/three/examples/jsm/physics/RapierPhysics.d.ts
  types/three/examples/jsm/postprocessing/BokehPass.d.ts
  types/three/examples/jsm/tsl/shadows/TileShadowNode.d.ts
  types/three/examples/jsm/tsl/shadows/TileShadowNodeHelper.d.ts
  types/three/package.json
  types/three/src/Three.Core.d.ts
  types/three/src/Three.TSL.d.ts
  types/three/src/audio/AudioListener.d.ts
  types/three/src/cameras/ArrayCamera.d.ts
  types/three/src/constants.d.ts
  types/three/src/core/RenderTarget.d.ts
  types/three/src/geometries/CapsuleGeometry.d.ts
  types/three/src/lights/LightShadow.d.ts
  types/three/src/materials/Material.d.ts
  types/three/src/materials/ShaderMaterial.d.ts
  types/three/src/materials/nodes/NodeMaterial.d.ts
  types/three/src/materials/nodes/manager/NodeMaterialObserver.d.ts
  types/three/src/math/FrustumArray.d.ts
  types/three/src/nodes/TSL.d.ts
  types/three/src/nodes/accessors/InstanceNode.d.ts
  types/three/src/nodes/accessors/VertexColorNode.d.ts
  types/three/src/nodes/core/Node.d.ts
  types/three/src/nodes/core/NodeVarying.d.ts
  types/three/src/nodes/core/StackNode.d.ts
  types/three/src/nodes/core/VaryingNode.d.ts
  types/three/src/nodes/gpgpu/AtomicFunctionNode.d.ts
  types/three/src/nodes/lighting/ShadowFilterNode.d.ts
  types/three/src/nodes/lighting/ShadowNode.d.ts
  types/three/src/nodes/math/OperatorNode.d.ts
  types/three/src/nodes/tsl/TSLCore.d.ts
  types/three/src/nodes/utils/DebugNode.d.ts
  types/three/src/nodes/utils/ReflectorNode.d.ts
  types/three/src/renderers/common/Animation.d.ts
  types/three/src/renderers/common/Renderer.d.ts
  types/three/src/renderers/common/Textures.d.ts
  types/three/src/renderers/common/TimestampQueryPool.d.ts
  types/three/src/renderers/common/XRManager.d.ts
  types/three/src/renderers/webgpu/WebGPUBackend.d.ts
  types/three/src/textures/DepthArrayTexture.d.ts
  types/three/src/textures/Texture.d.ts
  types/three/src/textures/VideoFrameTexture.d.ts
  types/three/test/integration/geometry-buffer.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72572 [invity-api]: sell provider lockAmount parameter
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#72588 [react-native-web] Declare and export unstable_createElement
  types/react-native-web/index.d.ts
  types/react-native-web/react-native-web-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#72580 [node] Update typings to v22.15.0
  types/node/assert.d.ts
  types/node/async_hooks.d.ts
  types/node/crypto.d.ts
  types/node/fs/promises.d.ts
  types/node/http2.d.ts
  types/node/inspector.d.ts
  types/node/module.d.ts
  types/node/package.json
  types/node/process.d.ts
  types/node/readline.d.ts
  types/node/sqlite.d.ts
  types/node/test.d.ts
  types/node/test/http2.ts
  types/node/test/module.ts
  types/node/test/process.ts
  types/node/test/sqlite.ts
  types/node/test/test.ts
  types/node/test/tls.ts
  types/node/test/util.ts
  types/node/test/v8.ts
  types/node/test/zlib.ts
  types/node/tls.d.ts
  types/node/util.d.ts
  types/node/v8.d.ts
  types/node/zlib.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72592 node: +o
  types/node/package.json
Labels: Self Merge, Maintainer Approved, Critical package, Edits Owners

#72499 feat(parse-numeric-range): remove types
  notNeededPackages.json
  types/parse-numeric-range/.npmignore
  types/parse-numeric-range/index.d.ts
  types/parse-numeric-range/package.json
  types/parse-numeric-range/parse-numeric-range-tests.ts
  types/parse-numeric-range/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72097 [node] buffer: allow `ArrayBuffer | string` to be passed to `Buffer.from`
  types/node/buffer.buffer.d.ts
  types/node/test/buffer.ts
  types/node/ts5.6/buffer.buffer.d.ts
  types/node/v18/buffer.buffer.d.ts
  types/node/v18/test/buffer.ts
  types/node/v18/ts5.6/buffer.buffer.d.ts
  types/node/v20/buffer.buffer.d.ts
  types/node/v20/test/buffer.ts
  types/node/v20/ts5.6/buffer.buffer.d.ts
Labels: Other Approved, Self Merge, Maintainer Approved, Critical package

#72600 [aws-synthetics-puppeteer] Bump to 10.0 and upgrade puppeteer-core
  types/aws-synthetics-puppeteer/package.json
Labels: Self Merge, Owner Approved

#72587 feat: stream-concat
  types/stream-concat/.npmignore
  types/stream-concat/index.d.ts
  types/stream-concat/package.json
  types/stream-concat/stream-concat-tests.ts
  types/stream-concat/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72605 feat(url-template): remove types
  notNeededPackages.json
  types/url-template/.npmignore
  types/url-template/index.d.ts
  types/url-template/package.json
  types/url-template/tsconfig.json
  types/url-template/url-template-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72604 feat(minizlib): remove types
  notNeededPackages.json
  types/minizlib/.npmignore
  types/minizlib/index.d.ts
  types/minizlib/minizlib-tests.ts
  types/minizlib/package.json
  types/minizlib/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72496 feat(react-otp-input): remove types
  notNeededPackages.json
  types/react-otp-input/.npmignore
  types/react-otp-input/index.d.ts
  types/react-otp-input/package.json
  types/react-otp-input/react-otp-input-tests.tsx
  types/react-otp-input/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72373 feat(node-red__registry): Allow extra properties on messages
  types/node-red__registry/index.d.ts
  types/node-red__registry/node-red__registry-tests.ts
  types/node-red__util/node-red__util-tests.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved

#72508 feat(node/tls): add TLSSocket.setKeyCert()
  types/node/test/tls.ts
  types/node/tls.d.ts
  types/node/v20/test/tls.ts
  types/node/v20/tls.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72506 Add types for @dailymotion/vast-client
  types/dailymotion__vast-client/.npmignore
  types/dailymotion__vast-client/dailymotion__vast-client-tests.ts
  types/dailymotion__vast-client/index.d.ts
  types/dailymotion__vast-client/package.json
  types/dailymotion__vast-client/tsconfig.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#72583 [custom-functions-runtime] (Invocation) Fix requirement set tag
  types/custom-functions-runtime/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change

#72634 feat: update @nginstack/iquery definitions
  types/nginstack__iquery/lib/IClauseFrom.d.ts
  types/nginstack__iquery/lib/IClauseJoin.d.ts
  types/nginstack__iquery/lib/IClauseSelect.d.ts
  types/nginstack__iquery/lib/IClauseWhere.d.ts
  types/nginstack__iquery/lib/IClauseWhereFactory.d.ts
  types/nginstack__iquery/lib/IClauseWhereManager.d.ts
  types/nginstack__iquery/lib/IColumn.d.ts
  types/nginstack__iquery/lib/IJoinManager.d.ts
  types/nginstack__iquery/lib/IQuery.d.ts
  types/nginstack__iquery/lib/PermissionClauseGenerator.d.ts
  types/nginstack__iquery/nginstack__iquery-tests.ts
  types/nginstack__iquery/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72635 feat: update @nginstack/orm definitions
  types/nginstack__orm/lib/Entity.d.ts
  types/nginstack__orm/lib/EntityOptions.d.ts
  types/nginstack__orm/lib/EntitySet.d.ts
  types/nginstack__orm/lib/EntitySetOptions.d.ts
  types/nginstack__orm/lib/EntityState.d.ts
  types/nginstack__orm/lib/persistDataSets.d.ts
  types/nginstack__orm/nginstack__orm-tests.ts
  types/nginstack__orm/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72636 feat: update @nginstack/jsunit definitions
  types/nginstack__jsunit/index.d.ts
  types/nginstack__jsunit/lib/AggregatedTestResult.d.ts
  types/nginstack__jsunit/lib/LegacyAssertMethods.d.ts
  types/nginstack__jsunit/lib/SuiteTestRunner.d.ts
  types/nginstack__jsunit/lib/TestCase.d.ts
  types/nginstack__jsunit/lib/TestCaseEvent.d.ts
  types/nginstack__jsunit/lib/TestError.d.ts
  types/nginstack__jsunit/lib/TestResult.d.ts
  types/nginstack__jsunit/lib/TestRunner.d.ts
  types/nginstack__jsunit/lib/TestSourceScanner.d.ts
  types/nginstack__jsunit/lib/TestSuite.d.ts
  types/nginstack__jsunit/lib/TestSuiteRunner.d.ts
  types/nginstack__jsunit/nginstack__jsunit-tests.ts
  types/nginstack__jsunit/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72638 feat: update @nginstack/datasource definitions
  types/nginstack__datasource/lib/ClassDerivation.d.ts
  types/nginstack__datasource/lib/DBKeyDerivation.d.ts
  types/nginstack__datasource/lib/DataSource.d.ts
  types/nginstack__datasource/lib/DataSourceColumn.d.ts
  types/nginstack__datasource/lib/DataSourceColumns.d.ts
  types/nginstack__datasource/lib/DataSourceDataType.d.ts
  types/nginstack__datasource/lib/DataSourceDef.d.ts
  types/nginstack__datasource/lib/DataSourceExecutor.d.ts
  types/nginstack__datasource/lib/DataSourceField.d.ts
  types/nginstack__datasource/lib/DataSourceFieldDef.d.ts
  types/nginstack__datasource/lib/DataSourceFilter.d.ts
  types/nginstack__datasource/lib/DataSourceFilters.d.ts
  types/nginstack__datasource/lib/DataSourceQuery.d.ts
  types/nginstack__datasource/lib/DataSourceQueryDef.d.ts
  types/nginstack__datasource/lib/DataSourceResult.d.ts
  types/nginstack__datasource/lib/FilterOperator.d.ts
  types/nginstack__datasource/lib/SecurityMode.d.ts
  types/nginstack__datasource/nginstack__datasource-tests.ts
  types/nginstack__datasource/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72640 feat: update @nginstack/dev-tools definitions
  types/nginstack__dev-tools/lib/database/QueryAnalyzer.d.ts
  types/nginstack__dev-tools/nginstack__dev-tools-tests.ts
  types/nginstack__dev-tools/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72641 feat: update @nginstack/devops definitions
  types/nginstack__devops/index.d.ts
  types/nginstack__devops/keys/Scripts.d.ts
  types/nginstack__devops/keys/UpdateTypes.d.ts
  types/nginstack__devops/lib/database/normalizeQueryFunction.d.ts
  types/nginstack__devops/lib/database/normalizeRunScriptFunction.d.ts
  types/nginstack__devops/lib/product/ProductDataSetFilter.d.ts
  types/nginstack__devops/lib/security/allowAnonymousConnection.d.ts
  types/nginstack__devops/lib/update/SystemUpdateOptions.d.ts
  types/nginstack__devops/lib/update/UpdateOptions.d.ts
  types/nginstack__devops/lib/update/UpdateScript.d.ts
  types/nginstack__devops/lib/update/VfsUpdateOptions.d.ts
  types/nginstack__devops/nginstack__devops-tests.ts
  types/nginstack__devops/package.json
  types/nginstack__devops/tsconfig.json
Labels: Self Merge, Author is Owner, Owner Approved
