Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2025-07, with the labels that each got.

#73165 Fix dependencies on proj4
  types/itowns/package.json
  types/proj4leaflet/index.d.ts
  types/proj4leaflet/package.json
  types/transform-coordinates/index.d.ts
  types/transform-coordinates/package.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Untested Change

#73158 fix(@types/glob): add to notNeededPackage.json
  notNeededPackages.json
Labels: Edits Infrastructure

#73157 fix(@types/minimatch): add to notNeededPackages.json
  notNeededPackages.json
Labels: Edits Infrastructure

#73149 @types/alicloud__log: Add types for @alicloud/log
  types/alicloud__log/.npmignore
  types/alicloud__log/alicloud__log-tests.ts
  types/alicloud__log/index.d.ts
  types/alicloud__log/package.json
  types/alicloud__log/tsconfig.json
Labels: New Definition

#73132 feat(yawn-yaml): remove types
  notNeededPackages.json
  types/yawn-yaml/.npmignore
  types/yawn-yaml/cjs/index.d.ts
  types/yawn-yaml/index.d.ts
  types/yawn-yaml/package.json
  types/yawn-yaml/tsconfig.json
  types/yawn-yaml/yawn-yaml-tests.ts
Labels: Owner Approved, Edits Infrastructure

#73130 feat(react-native-auth0): remove types
  notNeededPackages.json
  types/react-native-auth0/.npmignore
  types/react-native-auth0/index.d.ts
  types/react-native-auth0/package.json
  types/react-native-auth0/react-native-auth0-tests.tsx
  types/react-native-auth0/tsconfig.json
Labels: Edits Infrastructure

#72987 BakongKHQR: Add Static Modifier to generateDeepLink in Type Definitions
  types/bakong-khqr/index.d.ts
Labels: Untested Change, Unreviewed

#72975 [chrome] update Runtime namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Author is Owner, Unreviewed

#72955 [react-dates]: add constants
  types/react-dates/constants.d.ts
  types/react-dates/index.d.ts
  types/react-dates/package.json
  types/react-dates/react-dates-tests.tsx
Labels: Popular package, Author is Owner, Check Config, Unreviewed

#72932 feat(dropboxjs): remove types
  types/dropboxjs/.npmignore
  types/dropboxjs/dropboxjs-tests.ts
  types/dropboxjs/index.d.ts
  types/dropboxjs/package.json
  types/dropboxjs/tsconfig.json
Labels: Unreviewed

#72921 [chrome] update windows namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Author is Owner, Critical package, Unreviewed

#72917 [chrome] update downloads namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
  types/naver-whale/index.d.ts
Labels: Edits multiple packages, Critical package, Unreviewed

#73059 [@types/lodash] Fix readonly gate on impure functions
  types/lodash/common/array.d.ts
  types/lodash/common/common.d.ts
  types/lodash/lodash-tests.ts
Labels: Owner Approved, Critical package, Unreviewed

#73143 node/buffer: Enhance Buffer.fill Type Definitions with Overload Variants for Encoding Parameter Flexibility
  types/node/buffer.d.ts
  types/node/test/buffer.ts
  types/node/v18/buffer.d.ts
  types/node/v18/test/buffer.ts
  types/node/v20/buffer.d.ts
  types/node/v20/test/buffer.ts
  types/node/v22/buffer.d.ts
  types/node/v22/test/buffer.ts
Labels: Owner Approved, Critical package

#73167 Lock @types/minimatch deps to pre-deprecatation version
  types/gulp-filter/package.json
  types/gulp-if/package.json
  types/gulp-match/package.json
Labels: Edits multiple packages

#73137 feat: add types for @mathieuc/tradingview
  types/mathieuc__tradingview/.npmignore
  types/mathieuc__tradingview/index.d.ts
  types/mathieuc__tradingview/mathieuc__tradingview-tests.ts
  types/mathieuc__tradingview/package.json
  types/mathieuc__tradingview/tsconfig.json
Labels: New Definition

#73075 [@types/k6] Update k6 for the latest version 1.1.0
  types/k6/browser/index.d.ts
  types/k6/experimental/webcrypto/index.d.ts
  types/k6/package.json
  types/k6/test/webcrypto.ts
  types/k6/tsconfig.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#73175 @types/tabulator-tables paginationSize, setPageSize can accept "true" (i.e. "All)
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#73188 [bun] update to 1.2.18
  types/bun/package.json
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Owner Approved

#73183 feat(react-medium-image-zoom): remove types
  notNeededPackages.json
  types/react-medium-image-zoom/.npmignore
  types/react-medium-image-zoom/index.d.ts
  types/react-medium-image-zoom/package.json
  types/react-medium-image-zoom/react-medium-image-zoom-tests.tsx
  types/react-medium-image-zoom/tsconfig.json
Labels: Owner Approved, Edits Infrastructure

#73182 feat(react-component-benchmark): remove types
  notNeededPackages.json
  types/react-component-benchmark/.npmignore
  types/react-component-benchmark/index.d.ts
  types/react-component-benchmark/package.json
  types/react-component-benchmark/react-component-benchmark-tests.tsx
  types/react-component-benchmark/tsconfig.json
Labels: Edits Infrastructure

#73181 feat(open-graph-scraper): remove types
  notNeededPackages.json
  types/open-graph-scraper/.npmignore
  types/open-graph-scraper/index.d.ts
  types/open-graph-scraper/open-graph-scraper-tests.ts
  types/open-graph-scraper/package.json
  types/open-graph-scraper/tsconfig.json
Labels: Owner Approved, Edits Infrastructure

#73179 feat(hapipal__toys): remove types
  notNeededPackages.json
  types/hapipal__toys/.npmignore
  types/hapipal__toys/hapipal__toys-tests.ts
  types/hapipal__toys/index.d.ts
  types/hapipal__toys/package.json
  types/hapipal__toys/tsconfig.json
Labels: Edits Infrastructure

#73178 feat(simpl-schema): remove types
  attw.json
  notNeededPackages.json
  types/meteor-mdg-validated-method/package.json
  types/simpl-schema/.eslintrc.json
  types/simpl-schema/.npmignore
  types/simpl-schema/index.d.ts
  types/simpl-schema/package.json
  types/simpl-schema/simpl-schema-tests.ts
  types/simpl-schema/tsconfig.json
Labels: Edits Infrastructure, Edits multiple packages

#72888 Add autoRenewAbortController to options
  types/opossum/index.d.ts
  types/opossum/opossum-tests.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved

#73173 [@types/k6] feat: add jsdoc for exec.test.fail
  types/k6/execution/index.d.ts
  types/k6/test/execution.ts
Labels: Popular package, Self Merge, Owner Approved

#73212 Fix types for 5.9, npm conflict
  types/happen/happen-tests.ts
  types/htmlbars-inline-precompile/package.json
  types/rails__ujs/rails__ujs-tests.ts
Labels: Popular package, Edits multiple packages

#73144 fix(eslint-scope): fix for exported class types
  types/eslint-scope/eslint-scope-tests.ts
  types/eslint-scope/index.d.cts
Labels: Self Merge, Maintainer Approved, Critical package

#72974 [chrome] update Tabs namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#73147 node/buffer: allow encoding as second argument in Buffer.includes/indexOf/lastIndexOf type definitions
  types/node/buffer.d.ts
  types/node/test/buffer.ts
  types/node/v18/buffer.d.ts
  types/node/v18/test/buffer.ts
  types/node/v20/buffer.d.ts
  types/node/v20/test/buffer.ts
  types/node/v22/buffer.d.ts
  types/node/v22/test/buffer.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73207 [three] Add back MeshPhysicalMaterial.reflectivity
  types/three/src/materials/MeshPhysicalMaterial.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#73077 feat(daum-postcode): Add `minWidth` to `PostcodeOptions`
  types/daum-postcode/daum-postcode-tests.ts
  types/daum-postcode/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#73194 [node] http: deconflict overridable Agent methods
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/v18/http.d.ts
  types/node/v18/test/http.ts
  types/node/v20/http.d.ts
  types/node/v20/test/http.ts
  types/node/v22/http.d.ts
  types/node/v22/test/http.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73199 feat(craco__craco): remove types
  notNeededPackages.json
  types/craco__craco/.npmignore
  types/craco__craco/craco__craco-tests.ts
  types/craco__craco/index.d.ts
  types/craco__craco/package.json
  types/craco__craco/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73232 VS Code `1.102`
  types/vscode/index.d.ts
  types/vscode/package.json
Labels: Popular package, Untested Change

#73202 feat(rgrove__parse-xml): remove types
  notNeededPackages.json
  types/rgrove__parse-xml/.npmignore
  types/rgrove__parse-xml/index.d.ts
  types/rgrove__parse-xml/package.json
  types/rgrove__parse-xml/rgrove__parse-xml-tests.ts
  types/rgrove__parse-xml/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73204 feat(mem-fs): remove types
  notNeededPackages.json
  types/mem-fs/.npmignore
  types/mem-fs/index.d.ts
  types/mem-fs/mem-fs-tests.ts
  types/mem-fs/package.json
  types/mem-fs/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#73192 [chrome] drop obsolete APIs
  types/chrome/index.d.ts
  types/chrome/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change

#73190 fix(bundle-id): add type: module to fix attw error
  attw.json
  types/bundle-id/package.json
Labels: Self Merge, Maintainer Approved

#73230 [iso-3166-2] Fix "alpha 3 codes" typo
  types/iso-3166-2/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#73219 bluebird: remove EOL branches
  types/bluebird/.npmignore
  types/bluebird/v1/.eslintrc.json
  types/bluebird/v1/.npmignore
  types/bluebird/v1/bluebird-tests.ts
  types/bluebird/v1/index.d.ts
  types/bluebird/v1/package.json
  types/bluebird/v1/tsconfig.json
  types/bluebird/v2/.eslintrc.json
  types/bluebird/v2/.npmignore
  types/bluebird/v2/bluebird-tests.ts
  types/bluebird/v2/index.d.ts
  types/bluebird/v2/package.json
  types/bluebird/v2/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73216 update node-forge to support custom csr and certificate signers
  types/node-forge/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#73233 string-template: com[p]ile typo
  types/string-template/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#73214 Type created to support sabpaisa-react-lite plugin
  types/sabpaisa-react-lite/.npmignore
  types/sabpaisa-react-lite/index.d.ts
  types/sabpaisa-react-lite/package.json
  types/sabpaisa-react-lite/sabpaisa-reactlite-tests.tsx
  types/sabpaisa-react-lite/tsconfig.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#73262 [openui5] Update website links and general text
  types/openui5/README.md
Labels: Self Merge, Author is Owner, Owner Approved

#73046 [node] prune codeowners
  types/node/package.json
  types/node/v18/package.json
  types/node/v20/package.json
  types/node/v22/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Edits Owners

#73264 [openui5] Update readme text
  types/openui5/README.md
Labels: Self Merge, Author is Owner, Owner Approved

#73070 @types/ssh2-sftp-client – Update `end()` return type
  types/ssh2-sftp-client/index.d.ts
Labels: Unmerged, Popular package, Self Merge, Owner Approved, Untested Change

#73273 optional @alpinejs/morph options
  types/alpinejs__morph/alpinejs__morph-tests.ts
  types/alpinejs__morph/index.d.ts
Labels: Self Merge, Owner Approved

#73272 Fix chrome alarms.get() return type
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Owner Approved

#73267 [elm] correct types
  types/elm/elm-tests.ts
  types/elm/index.d.ts
  types/elm/package.json
Labels: Self Merge, Owner Approved, Edits Owners

#73277 Update Rokt Attributes Type Definitions
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Self Merge, Owner Approved

#73238 feat(mixpanel): remove self-typed "mixpanel" and" mixpanel-browser"
  notNeededPackages.json
  types/mixpanel-browser/.npmignore
  types/mixpanel-browser/dist/mixpanel-core.cjs.d.ts
  types/mixpanel-browser/dist/mixpanel-with-async-recorder.cjs.d.ts
  types/mixpanel-browser/index.d.ts
  types/mixpanel-browser/mixpanel-browser-tests.ts
  types/mixpanel-browser/package.json
  types/mixpanel-browser/src/loaders/loader-module-core.d.ts
  types/mixpanel-browser/src/loaders/loader-module-with-async-recorder.d.ts
  types/mixpanel-browser/tsconfig.json
  types/mixpanel/.npmignore
  types/mixpanel/index.d.ts
  types/mixpanel/mixpanel-tests.ts
  types/mixpanel/package.json
  types/mixpanel/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#73213 feat: add types for express-xss-sanitizer
  types/express-xss-sanitizer/.npmignore
  types/express-xss-sanitizer/express-xss-sanitizer-tests.ts
  types/express-xss-sanitizer/index.d.ts
  types/express-xss-sanitizer/package.json
  types/express-xss-sanitizer/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73229 feat(bcrypt): update for v6.0.0
  types/bcrypt/package.json
Labels: Self Merge, Maintainer Approved, Critical package

#73259 Add cognito v3 pre token generation trigger event and handler
  types/aws-lambda/test/cognito-tests.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/index.d.ts
  types/aws-lambda/trigger/cognito-user-pool-trigger/pre-token-generation-v3.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#73275 add callback to ServerResponse.writeProcessing
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/v18/http.d.ts
  types/node/v18/test/http.ts
  types/node/v20/http.d.ts
  types/node/v20/test/http.ts
  types/node/v22/http.d.ts
  types/node/v22/test/http.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#73249 feat(cypress-cdp): remove types
  notNeededPackages.json
  types/cypress-cdp/.npmignore
  types/cypress-cdp/cypress-cdp-tests.ts
  types/cypress-cdp/index.d.ts
  types/cypress-cdp/package.json
  types/cypress-cdp/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73248 feat(react-native-shared-group-preferences): remove types
  notNeededPackages.json
  types/react-native-shared-group-preferences/.npmignore
  types/react-native-shared-group-preferences/index.d.ts
  types/react-native-shared-group-preferences/package.json
  types/react-native-shared-group-preferences/react-native-shared-group-preferences-tests.ts
  types/react-native-shared-group-preferences/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#73246 feat(easy-speech): remove types
  attw.json
  notNeededPackages.json
  types/easy-speech/.npmignore
  types/easy-speech/easy-speech-tests.ts
  types/easy-speech/index.d.ts
  types/easy-speech/package.json
  types/easy-speech/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73145 fix(esrecurse): remove non-existing dynamic methods
  types/esrecurse/esrecurse-tests.ts
  types/esrecurse/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#73268 Remove typings for `read` package
  notNeededPackages.json
  types/read/.npmignore
  types/read/index.d.ts
  types/read/package.json
  types/read/read-tests.ts
  types/read/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73265 feat: add tenantId to `@types/aws-lambda` Context
  types/aws-lambda/handler.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#73294 [bun] update to 1.2.19
  types/bun/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package, Edits Owners

#73101 [m3u8-parser] fix typo
  types/m3u8-parser/index.d.ts
  types/m3u8-parser/m3u8-parser-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#73099 [oracledb] Addition of new features from version 6.7
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73260 Fix dependencies of @types/hoist-non-react-statics to avoid bundling pinned @types/react in node_modules
  types/hoist-non-react-statics/package.json
Labels: Self Merge, Maintainer Approved, Critical package, Check Config

#73295 [@wordpress/blocks] Added the enum field to block attributes
  types/wordpress__blocks/index.d.ts
  types/wordpress__blocks/wordpress__blocks-tests.tsx
Labels: Self Merge, Owner Approved

#73240 Add Web Install API
  types/web-install-api/.npmignore
  types/web-install-api/index.d.ts
  types/web-install-api/package.json
  types/web-install-api/tsconfig.json
  types/web-install-api/web-install-api-tests.ts
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#73311 [@types/pdfkit] add `boundsOfString`
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73316 Update RoktPartnerAttributes type to support nested objects
  types/mparticle__web-sdk/index.d.ts
  types/mparticle__web-sdk/test/mparticle__web-sdk-tests.ts
Labels: Self Merge, Owner Approved

#73323 Sync frida-gum typings with Frida 17.2.14
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#73321 [electron-progressbar] update types, electron-progressbar-test.ts and version
  types/electron-progressbar/electron-progressbar-tests.ts
  types/electron-progressbar/index.d.ts
  types/electron-progressbar/package.json
Labels: Other Approved, Self Merge, No Other Owners

#73331 Copy paste promises
  types/copy-paste/copy-paste-tests.ts
  types/copy-paste/package.json
  types/copy-paste/promises.d.ts
Labels: Self Merge, Owner Approved

#73292 feat(luxon): upgrade to v3.7, add export map to fix attw
  attw.json
  types/luxon/index.d.mts
  types/luxon/index.d.ts
  types/luxon/package.json
  types/luxon/src/datetime.d.ts
  types/luxon/src/duration.d.ts
  types/luxon/src/interval.d.ts
  types/luxon/test/luxon-tests.module.ts
  types/luxon/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73215 [express-http-proxy] Update request options decorator param
  types/express-http-proxy/express-http-proxy-tests.ts
  types/express-http-proxy/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73291 feat(node/module): update import.meta.resolve signature for v18.19.x
  types/node/v18/module.d.ts
  types/node/v18/node-tests-dom.ts
  types/node/v18/node-tests-non-dom.ts
  types/node/v18/test/module-dom.ts
  types/node/v18/test/module-non-dom.ts
  types/node/v18/test/module.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73287 feat(xsd-schema-validator): remove types
  notNeededPackages.json
  types/xsd-schema-validator/.npmignore
  types/xsd-schema-validator/index.d.ts
  types/xsd-schema-validator/package.json
  types/xsd-schema-validator/tsconfig.json
  types/xsd-schema-validator/xsd-schema-validator-tests.ts
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73290 feat(react-native-video-player): remove types
  notNeededPackages.json
  types/react-native-video-player/.npmignore
  types/react-native-video-player/index.d.ts
  types/react-native-video-player/package.json
  types/react-native-video-player/react-native-video-player-tests.tsx
  types/react-native-video-player/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73116 feat(plotly.js): update Config type, add jsdoc from source code schema
  types/plotly.js/index.d.ts
  types/plotly.js/test/index-tests.ts
  types/plotly.js/v2/index.d.ts
  types/plotly.js/v2/test/index-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73243 [react] Add types for `cacheSignal`
  types/react-dom/canary.d.ts
  types/react-dom/test/canary-tests.tsx
  types/react/canary.d.ts
  types/react/test/canary.tsx
  types/react/ts5.0/canary.d.ts
  types/react/ts5.0/test/canary.tsx
Labels: Unmerged, Self Merge, Author is Owner, Edits multiple packages, Maintainer Approved, Critical package

#73341 Feature/mapping editor
  types/gorilla-engine/components/MappingEditor.d.ts
  types/gorilla-engine/gorilla-engine-tests.ts
  types/gorilla-engine/index.d.ts
Labels: Self Merge, Author is Owner, Owner Approved

#73177 feat(carbon__pictograms-react): bump to 12.55.0
  types/carbon__pictograms-react/carbon__pictograms-react-tests.tsx
  types/carbon__pictograms-react/es/design/index.d.ts
  types/carbon__pictograms-react/es/human-in-the-loop/index.d.ts
  types/carbon__pictograms-react/es/index.d.ts
  types/carbon__pictograms-react/es/masters-leader-board/index.d.ts
  types/carbon__pictograms-react/es/pencil/index.d.ts
  types/carbon__pictograms-react/es/product/index.d.ts
  types/carbon__pictograms-react/es/recruitment--01/index.d.ts
  types/carbon__pictograms-react/es/software--02/index.d.ts
  types/carbon__pictograms-react/es/tickets/index.d.ts
  types/carbon__pictograms-react/es/user--research-tools/index.d.ts
  types/carbon__pictograms-react/es/zurich--swiss-national-museum/index.d.ts
  types/carbon__pictograms-react/index.d.ts
  types/carbon__pictograms-react/lib/design/index.d.ts
  types/carbon__pictograms-react/lib/human-in-the-loop/index.d.ts
  types/carbon__pictograms-react/lib/index.d.ts
  types/carbon__pictograms-react/lib/masters-leader-board/index.d.ts
  types/carbon__pictograms-react/lib/pencil/index.d.ts
  types/carbon__pictograms-react/lib/product/index.d.ts
  types/carbon__pictograms-react/lib/recruitment--01/index.d.ts
  types/carbon__pictograms-react/lib/software--02/index.d.ts
  types/carbon__pictograms-react/lib/tickets/index.d.ts
  types/carbon__pictograms-react/lib/user--research-tools/index.d.ts
  types/carbon__pictograms-react/lib/zurich--swiss-national-museum/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#73356 Fix webpack-hot-middleware after webpack null change
  types/webpack-hot-middleware/webpack-hot-middleware-tests.ts
Labels: Popular package

#73326 `types/project-osrm__osrm`: Fixed typo, added RouteStep.driving_side; `types/osrm`: Mirrored type fixes
  types/osrm/index.d.ts
  types/osrm/osrm-tests.ts
  types/project-osrm__osrm/index.d.ts
  types/project-osrm__osrm/project-osrm__osrm-tests.ts
Labels: Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved

#73336 Add type definitions for cheerio-tableparser
  types/cheerio-tableparser/.npmignore
  types/cheerio-tableparser/cheerio-tableparser-tests.ts
  types/cheerio-tableparser/index.d.ts
  types/cheerio-tableparser/package.json
  types/cheerio-tableparser/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73347 [luxon] fix: DateTime.fromSeconds can return DateTime<Invalid>
  types/luxon/src/datetime.d.ts
  types/luxon/test/luxon-tests.module.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73354 chore(node-fetch): bump form-data to ^4.0.4 to address security vulnerability
  types/node-fetch/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73352 feat(carbon__pictograms-react): bump to 12.56.0
  types/carbon__pictograms-react/es/ibm--power11/index.d.ts
  types/carbon__pictograms-react/es/index.d.ts
  types/carbon__pictograms-react/index.d.ts
  types/carbon__pictograms-react/lib/ibm--power11/index.d.ts
  types/carbon__pictograms-react/lib/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, No Other Owners

#73351 [`usercentrics-browser-ui`] Add `name` to `CategoryData`
  types/usercentrics-browser-ui/api-interfaces.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#73344 feat: remove @types/svg-spritemap-webpack-plugin package
  notNeededPackages.json
  types/svg-spritemap-webpack-plugin/.npmignore
  types/svg-spritemap-webpack-plugin/index.d.ts
  types/svg-spritemap-webpack-plugin/package.json
  types/svg-spritemap-webpack-plugin/svg-spritemap-webpack-plugin-tests.ts
  types/svg-spritemap-webpack-plugin/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73162 [@types/oracledb] Update types till oracledb@6.9.0
  types/oracledb/index.d.ts
  types/oracledb/oracledb-tests.ts
  types/oracledb/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Edits Owners

#73274 Updates types for Recurly.js v4.38.0
  types/recurly__recurly-js/lib/apple-pay/native.d.ts
  types/recurly__recurly-js/package.json
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved, Untested Change

#73374 fix(oidc-provider): Provider ctx getter is not static
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73359 feat(eth-sig-util): remove types
  notNeededPackages.json
  types/eth-sig-util/.npmignore
  types/eth-sig-util/eth-sig-util-tests.ts
  types/eth-sig-util/index.d.ts
  types/eth-sig-util/package.json
  types/eth-sig-util/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73378 [@babel/traverse] Sync types of asserts and validators
  types/babel__traverse/index.d.ts
  types/babel__traverse/package.json
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Untested Change
