Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2025-05, with the labels that each got.

#72553 (Feat)@types/imapflow Added docs, missing functions and changed some parameters to optional
  types/imapflow/imapflow-tests.ts
  types/imapflow/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#72665 [chrome] update TabGroups namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72668 Add @types/deno 2.3
  types/deno/deno-tests.ts
  types/deno/index.d.ts
  types/deno/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72574 [dxf] Fixes capitalization and types
  types/dxf/dxf-tests.ts
  types/dxf/handlers/entity/common.d.ts
Labels: Other Approved, Self Merge

#72675 [bun] update to 1.2.12
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72564 [chrome] add printing.getJobStatus() since Chrome 135
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72659 feat(mapbox__mapbox-sdk): refine TileQueryService.listFeatures() return
  types/mapbox__mapbox-sdk/index.d.ts
  types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts
Labels: Self Merge, Owner Approved

#72579 [itemsjs] Rename generics and fix `extends`
  types/itemsjs/index.d.ts
  types/itemsjs/itemsjs-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#72667 feat(@node-red/flow-parser): add types
  types/node-red__flow-parser/.npmignore
  types/node-red__flow-parser/index.d.ts
  types/node-red__flow-parser/node-red__flow-parser-tests.ts
  types/node-red__flow-parser/package.json
  types/node-red__flow-parser/tsconfig.json
Labels: Other Approved, New Definition, Self Merge, Maintainer Approved

#72446 [xrm] Add specificAttributes type and attributeValues type, change formContext.getAttribute() method to return specific attribute types
  types/xrm/index.d.ts
  types/xrm/xrm-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved

#72439 Update tests in react-plotly.js to be forward-compatible with Plotly v3
  types/react-plotly.js/react-plotly.js-tests.tsx
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#72602 chore: Improve Japanese README for Better Clarity and Consistency
  README.ja.md
Labels: Edits Infrastructure

#72601 fix: update build status links in multiple language README files
  README.fr.md
  README.it.md
  README.ja.md
  README.ko.md
  README.md
  README.pt.md
  README.ru.md
  README.zh-Hans.md
Labels: Edits Infrastructure

#72507 fix(node/tls): fix context param in Server.addContext()
  types/node/test/tls.ts
  types/node/tls.d.ts
  types/node/v18/test/tls.ts
  types/node/v18/tls.d.ts
  types/node/v20/test/tls.ts
  types/node/v20/tls.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72498 feat(yoga-layout): remove types
  notNeededPackages.json
  types/yoga-layout/.npmignore
  types/yoga-layout/index.d.ts
  types/yoga-layout/package.json
  types/yoga-layout/tsconfig.json
  types/yoga-layout/yoga-layout-tests.ts
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72497 feat(iamport-react-native): remove types
  notNeededPackages.json
  types/iamport-react-native/.npmignore
  types/iamport-react-native/iamport-react-native-tests.tsx
  types/iamport-react-native/index.d.ts
  types/iamport-react-native/package.json
  types/iamport-react-native/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72495 feat(cheerio): remove types
  notNeededPackages.json
  types/chai-enzyme/package.json
  types/cheerio/.eslintrc.json
  types/cheerio/.npmignore
  types/cheerio/cheerio-tests.ts
  types/cheerio/index.d.ts
  types/cheerio/package.json
  types/cheerio/tsconfig.json
  types/crawler/package.json
  types/enzyme/package.json
  types/gulp-cheerio/package.json
  types/hoxy/package.json
  types/inline-css/package.json
  types/json_ml/package.json
  types/open-graph/package.json
Labels: Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved, Critical package

#72630 feat(express-slow-down): remove types
  notNeededPackages.json
  types/express-slow-down/.npmignore
  types/express-slow-down/express-slow-down-tests.ts
  types/express-slow-down/index.d.ts
  types/express-slow-down/package.json
  types/express-slow-down/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72629 feat(node-zendesk): remove types
  notNeededPackages.json
  types/node-zendesk/.npmignore
  types/node-zendesk/index.d.ts
  types/node-zendesk/node-zendesk-tests.ts
  types/node-zendesk/package.json
  types/node-zendesk/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72489 feat(parse-path): remove types
  notNeededPackages.json
  types/parse-path/.npmignore
  types/parse-path/index.d.ts
  types/parse-path/package.json
  types/parse-path/parse-path-tests.ts
  types/parse-path/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#72628 feat(safe-flat): remove types
  notNeededPackages.json
  types/safe-flat/.npmignore
  types/safe-flat/index.d.ts
  types/safe-flat/package.json
  types/safe-flat/safe-flat-tests.ts
  types/safe-flat/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72607 feat(node/querystring): add BigInt to ParsedUrlQueryInput
  types/node/querystring.d.ts
  types/node/test/querystring.ts
  types/node/v18/querystring.d.ts
  types/node/v18/test/querystring.ts
  types/node/v20/querystring.d.ts
  types/node/v20/test/querystring.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72606 feat(node/async_hooks): add asyncWrapProviders
  types/node/async_hooks.d.ts
  types/node/test/async_hooks.ts
  types/node/v18/async_hooks.d.ts
  types/node/v18/test/async_hooks.ts
  types/node/v20/async_hooks.d.ts
  types/node/v20/test/async_hooks.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72550 feat(node/http): add missing ServerOptions
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/v18/http.d.ts
  types/node/v18/test/http.ts
  types/node/v20/http.d.ts
  types/node/v20/test/http.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72611 feat(pg): add connection property to Client
  types/pg/index.d.ts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72648 [chessboardjs] fix Square enum "g-file"
  types/chessboardjs/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#72551 Define Node.js util.styleText options
  types/node/test/util.ts
  types/node/util.d.ts
  types/node/v20/test/util.ts
  types/node/v20/util.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72295 [oidc-provider] v9.1.0 bump
  types/oidc-provider/index.d.ts
  types/oidc-provider/oidc-provider-tests.ts
  types/oidc-provider/package.json
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Maintainer Approved, No Other Owners

#72576 feat(pg): add additional Client parameters
  types/pg/index.d.ts
  types/pg/package.json
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#72652 fix(jasmine): Add Clock.autoTick from jasmine 5.7
  types/jasmine/index.d.ts
  types/jasmine/jasmine-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72591 [chrome] no unsafe function type
  types/chrome/.eslintrc.json
  types/chrome/chrome-cast/index.d.ts
  types/chrome/index.d.ts
  types/sinon-chrome/index.d.ts
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved, Untested Change

#72543 feat(sanitize-html): add onOpenTag and onCloseTag options
  types/sanitize-html/index.d.ts
  types/sanitize-html/package.json
  types/sanitize-html/sanitize-html-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72556 node/stream: Update undefined->void in line with TS 5.8 changes
  types/node/stream/web.d.ts
  types/node/test/stream.ts
  types/node/v18/stream/web.d.ts
  types/node/v18/test/stream.ts
  types/node/v20/stream/web.d.ts
  types/node/v20/test/stream.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72359 [connect-timeout] Update package.json version to match library version. v1.9.x
  types/connect-timeout/package.json
Labels: Popular package, Self Merge, Maintainer Approved

#72311 [mixpanel-browser] Add `autocapture` configuration
  types/mixpanel-browser/index.d.ts
  types/mixpanel-browser/mixpanel-browser-tests.ts
  types/mixpanel-browser/package.json
Labels: Other Approved, Popular package, Self Merge, Maintainer Approved

#72596 [node] globals.d.ts housekeeping
  types/node/globals.d.ts
  types/node/node-tests.ts
  types/node/test/globals.ts
  types/node/v18/globals.d.ts
  types/node/v18/node-tests.ts
  types/node/v18/test/globals.ts
  types/node/v20/globals.d.ts
  types/node/v20/node-tests.ts
  types/node/v20/test/globals.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#72689 relay-runtime: Update Environment config to mark it as optional to match updated types in version 19
  types/relay-runtime/lib/store/RelayModernEnvironment.d.ts
  types/relay-runtime/package.json
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#72676 feat: Add @types/base58
  types/base58/.npmignore
  types/base58/base58-tests.ts
  types/base58/index.d.ts
  types/base58/package.json
  types/base58/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72547 fix(react): move onResize and onResizeCapture to VideoHTMLAttributes
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/v18/index.d.ts
  types/react/ts5.0/v18/ts5.0/index.d.ts
  types/react/v18/index.d.ts
  types/react/v18/ts5.0/index.d.ts
Labels: Self Merge, Maintainer Approved, Critical package, Untested Change

#72546 fix(node/cluster): correct the return type of Worker.disconnect()
  types/node/cluster.d.ts
  types/node/test/cluster.ts
  types/node/v18/cluster.d.ts
  types/node/v18/test/cluster.ts
  types/node/v20/cluster.d.ts
  types/node/v20/test/cluster.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72531 feat(node/diagnostics_channel): add TracingChannel.hasSubscribers
  types/node/diagnostics_channel.d.ts
  types/node/test/diagnostics_channel.ts
  types/node/v20/diagnostics_channel.d.ts
  types/node/v20/test/diagnostics_channel.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72509 leaflet-draw: add showArea prop to multiple shapes, not only polygon
  types/leaflet-draw/index.d.ts
  types/leaflet-draw/leaflet-draw-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72671 [npm-registry-fetch] fix `retry` object option property names
  types/npm-registry-fetch/index.d.ts
  types/npm-registry-fetch/npm-registry-fetch-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved, No Other Owners

#72617 @types/node: Add strings array type to http.request
  types/node/http.d.ts
  types/node/test/http.ts
  types/node/v18/http.d.ts
  types/node/v18/test/http.ts
  types/node/v20/http.d.ts
  types/node/v20/test/http.ts
Labels: Self Merge, Owner Approved, Critical package

#72673 doc[node]: add "accept-encoding" to `interface IncomingHttpHeaders`
  types/node/http.d.ts
  types/node/v18/http.d.ts
  types/node/v20/http.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#72642 fix(serverless-step-functions): add itemspath
  types/serverless-step-functions/package.json
  types/serverless-step-functions/types/map.d.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Untested Change, Edits Owners

#72420 Add onAutoplayBlocked to Player events on @types/youtube
  types/youtube/index.d.ts
  types/youtube/youtube-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72479 Update accept-language-parser to accept readonly language options
  types/accept-language-parser/accept-language-parser-tests.ts
  types/accept-language-parser/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72682 fix(imap-simple): rename seqno to seqNo in Message
  types/imap-simple/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#72521 mailparser: Add checksumAlgo field to MailParserOptions
  types/mailparser/index.d.ts
  types/mailparser/mailparser-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72666 feat(gettext.js): bump version, fix incorrect types, add tests
  types/gettext.js/gettext.js-tests.ts
  types/gettext.js/index.d.ts
  types/gettext.js/package.json
Labels: Other Approved, Self Merge

#72593 [chrome] re-enable prefer-namespace eslint rule
  types/chrome/.eslintrc.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72645 fix(node/net): add missing "error" to connectionAttemptFailed event
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v20/net.d.ts
  types/node/v20/test/net.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72690 Add self as owner of Relay packages
  types/react-relay/package.json
  types/relay-compiler/package.json
  types/relay-runtime/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits multiple packages, Maintainer Approved, Edits Owners

#72700 [stremio-addon-sdk] Fix incorrect `Manifest.config[].options` type
  types/stremio-addon-sdk/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#72549 [@types/toastify] Add defaults property
  types/toastify-js/index.d.ts
  types/toastify-js/toastify-js-tests.ts
Labels: Other Approved, Self Merge

#72698 fix(react-native-multi-slider): modify jsdoc with @default, fix attw
  attw.json
  types/react-native-multi-slider/index.d.ts
  types/react-native-multi-slider/react-native-multi-slider-tests.tsx
Labels: Self Merge, Maintainer Approved

#72672 [elm] allow specifying `Elm.*` namespace
  types/elm/.eslintrc.json
  types/elm/elm-tests.ts
  types/elm/index.d.ts
  types/elm/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Check Config

#72663 update(papaparse): add `skipFirstNLines` config option for v5.5.0 implementation
  types/papaparse/index.d.ts
  types/papaparse/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change, Edits Owners

#72255 [@sabaki/sgf] Add definitions for "@sabaki/sgf"
  types/sabaki__sgf/.npmignore
  types/sabaki__sgf/index.d.ts
  types/sabaki__sgf/package.json
  types/sabaki__sgf/sabaki__sgf-tests.ts
  types/sabaki__sgf/src/helper.d.ts
  types/sabaki__sgf/src/main.d.ts
  types/sabaki__sgf/src/parse.d.ts
  types/sabaki__sgf/src/stringify.d.ts
  types/sabaki__sgf/src/tokenize.d.ts
  types/sabaki__sgf/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#72691 fix(node/vm): correct SourceTextModuleOptions["importModuleDynamically"]
  types/node/test/vm.ts
  types/node/v18/test/vm.ts
  types/node/v18/vm.d.ts
  types/node/v20/test/vm.ts
  types/node/v20/vm.d.ts
  types/node/vm.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72695 feat(react-native-material-menu): remove types
  notNeededPackages.json
  types/react-native-material-menu/.npmignore
  types/react-native-material-menu/index.d.ts
  types/react-native-material-menu/package.json
  types/react-native-material-menu/react-native-material-menu-tests.tsx
  types/react-native-material-menu/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72696 feat(mongoose-aggregate-paginate-v2): remove types
  notNeededPackages.json
  types/mongoose-aggregate-paginate-v2/.npmignore
  types/mongoose-aggregate-paginate-v2/index.d.ts
  types/mongoose-aggregate-paginate-v2/mongoose-aggregate-paginate-v2-tests.ts
  types/mongoose-aggregate-paginate-v2/package.json
  types/mongoose-aggregate-paginate-v2/tsconfig.json
Labels: Other Approved, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72704 feat(webmidi): remove types
  notNeededPackages.json
  types/webmidi/.npmignore
  types/webmidi/index.d.ts
  types/webmidi/package.json
  types/webmidi/tsconfig.json
  types/webmidi/webmidi-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72709 feat(secure-json-parse): remove types
  notNeededPackages.json
  types/secure-json-parse/.npmignore
  types/secure-json-parse/index.d.ts
  types/secure-json-parse/package.json
  types/secure-json-parse/secure-json-parse-tests.ts
  types/secure-json-parse/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72701 feat(yallist): remove types
  notNeededPackages.json
  types/yallist/.eslintrc.json
  types/yallist/.npmignore
  types/yallist/index.d.ts
  types/yallist/package.json
  types/yallist/tsconfig.json
  types/yallist/yallist-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72539 feat(google.accounts): add Intermediate Iframe and Intermediate Iframe Support API
  types/google.accounts/google.accounts-tests.ts
  types/google.accounts/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72534 node/fs: support Buffer as Dirent.name and refine types for readdir/readdirSync with encoding: "buffer"
  types/fs-extra/test/fs-extra-tests.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/test/fs.ts
  types/node/v18/fs.d.ts
  types/node/v18/fs/promises.d.ts
  types/node/v20/fs.d.ts
  types/node/v20/fs/promises.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#72544 Fix:(autocanon) Added missing function types for the requests array
  types/autocannon/autocannon-tests.ts
  types/autocannon/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72693 feat(xmldoc): remove types
  notNeededPackages.json
  types/xmldoc/.npmignore
  types/xmldoc/index.d.ts
  types/xmldoc/package.json
  types/xmldoc/tsconfig.json
  types/xmldoc/xmldoc-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72710 fix(pg): named exports
  types/pg/index.d.mts
  types/pg/index.d.ts
  types/pg/pg-tests.mts
  types/pg/pg-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#72614 [@types/bro-fs] Fix issues and update type definitions
  types/bro-fs/bro-fs-tests.ts
  types/bro-fs/index.d.ts
Labels: Self Merge, Owner Approved

#72735 shelljs: Add missing types for 'cmd' function
  types/shelljs/index.d.ts
  types/shelljs/make.d.ts
  types/shelljs/shelljs-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#72719 feat(openapi-factory): remove types
  notNeededPackages.json
  types/openapi-factory/.npmignore
  types/openapi-factory/index.d.ts
  types/openapi-factory/openapi-factory-tests.ts
  types/openapi-factory/package.json
  types/openapi-factory/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72721 feat(chart.js): remove types
  notNeededPackages.json
  types/chart.js/.eslintrc.json
  types/chart.js/.npmignore
  types/chart.js/chart.js-tests.ts
  types/chart.js/index.d.ts
  types/chart.js/package.json
  types/chart.js/tsconfig.json
  types/chartjs-plugin-colorschemes/package.json
  types/chartjs-plugin-crosshair/package.json
  types/vue-chartkick/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#72722 feat(private-ip): remove types
  notNeededPackages.json
  types/private-ip/.npmignore
  types/private-ip/index.d.ts
  types/private-ip/package.json
  types/private-ip/private-ip-tests.ts
  types/private-ip/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#72724 feat(workgrid-toolbar): remove types
  types/workgrid-toolbar/.npmignore
  types/workgrid-toolbar/index.d.ts
  types/workgrid-toolbar/package.json
  types/workgrid-toolbar/tsconfig.json
  types/workgrid-toolbar/workgrid-toolbar-tests.ts
Labels: Other Approved, Self Merge

#72723 feat(react-embed-gist): remove types
  attw.json
  notNeededPackages.json
  types/react-embed-gist/.npmignore
  types/react-embed-gist/index.d.ts
  types/react-embed-gist/package.json
  types/react-embed-gist/react-embed-gist-tests.tsx
  types/react-embed-gist/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, No Other Owners

#72725 feat(testing-library__cypress): remove types
  notNeededPackages.json
  types/testing-library__cypress/.npmignore
  types/testing-library__cypress/add-commands.d.ts
  types/testing-library__cypress/index.d.ts
  types/testing-library__cypress/package.json
  types/testing-library__cypress/testing-library__cypress-tests.ts
  types/testing-library__cypress/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72727 feat(pxroneline): add subscribeSocialConsents method and update versi…
  types/pxr-oneline/index.d.ts
  types/pxr-oneline/oneline-tests.ts
  types/pxr-oneline/package.json
Labels: Other Approved, Self Merge, Author is Owner

#72625 Remove ImageTrack etc. from dom-webcodecs
  types/dom-webcodecs/webcodecs.generated.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#72590 [chrome] no wrapper object types
  types/chrome/.eslintrc.json
  types/chrome/chrome-cast/index.d.ts
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72734 fix(react-html5-camera-photo): fix props, resolve attw
  attw.json
  types/react-html5-camera-photo/index.d.ts
  types/react-html5-camera-photo/react-html5-camera-photo-tests.tsx
  types/react-html5-camera-photo/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved

#72557 gulp-flatmap: add type for package
  types/gulp-flatmap/.npmignore
  types/gulp-flatmap/gulp-flatmap-tests.ts
  types/gulp-flatmap/index.d.ts
  types/gulp-flatmap/package.json
  types/gulp-flatmap/tsconfig.json
Labels: Unmerged, New Definition, Self Merge, Maintainer Approved

#72753 [bun] update to 1.2.13
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72758 [navermaps] Add options related to GL submodule
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#72726 [react-dom] Types for `onDefaultTransitionIndicator`
  types/react-dom/.eslintrc.json
  types/react-dom/experimental.d.ts
  types/react-dom/test/experimental-tests.tsx
Labels: Other Approved, Author is Owner, Critical package, Check Config

#72759 [@types/react] Remove duplicate useReducer type definition
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
Labels: Owner Approved, Critical package, Untested Change

#72767 [react-dom] (experimental) Fix typo
  types/react-dom/experimental.d.ts
Labels: Critical package, Untested Change

#72781 [relay-test-utils] upgrade to v19
  types/relay-test-utils/package.json
Labels: Other Approved, Popular package, Self Merge, Owner Approved

#72783 chore: remove Stephen2 as owner [relay-test-utils]
  types/relay-test-utils/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved, Edits Owners

#72670 [node] Allow the `err` parameter to the `net.Socket#write` callback (in case of success) to be `null` as well as `undefined`
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v20/net.d.ts
  types/node/v20/test/net.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72785 Add a new options for Version 3.
  types/event-calendar__core/event-calendar__core-tests.ts
  types/event-calendar__core/index.d.ts
  types/event-calendar__core/package.json
Labels: Self Merge, Owner Approved

#72529 fix: move ioredis from dependencies to peerDependencies in @types/ior…
  types/ioredis-mock/index.d.ts
  types/ioredis-mock/package.json
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change, Check Config

#72603 Reintroduce [pg] min option
  types/pg-pool/pg-pool-tests.ts
  types/pg/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package

#72526 feat(swagger-ui): type support for internal presets and subpath mods
  types/swagger-ui/dist/oauth2-redirect.html.d.ts
  types/swagger-ui/dist/swagger-ui-standalone-preset.d.ts
  types/swagger-ui/dist/swagger-ui.css.d.ts
  types/swagger-ui/index.d.ts
  types/swagger-ui/package.json
  types/swagger-ui/swagger-ui-tests.ts
Labels: Unmerged, Popular package, Self Merge, Maintainer Approved

#72598 [chrome] update Notifications namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#72626 Remove myself from owners of swagger-ui
  types/swagger-ui/package.json
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Edits Owners

#72742 feat(overlayscrollbars): remove types
  notNeededPackages.json
  types/overlayscrollbars/.npmignore
  types/overlayscrollbars/index.d.ts
  types/overlayscrollbars/overlayscrollbars-tests.ts
  types/overlayscrollbars/package.json
  types/overlayscrollbars/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72743 feat(chordsheetjs): remove types
  notNeededPackages.json
  types/chordsheetjs/.npmignore
  types/chordsheetjs/chordsheetjs-tests.ts
  types/chordsheetjs/index.d.ts
  types/chordsheetjs/package.json
  types/chordsheetjs/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#72745 feat(dhis2__ui-*): remove types
  notNeededPackages.json
  types/dhis2__ui-constants/.npmignore
  types/dhis2__ui-constants/dhis2__ui-constants-tests.ts
  types/dhis2__ui-constants/index.d.ts
  types/dhis2__ui-constants/package.json
  types/dhis2__ui-constants/tsconfig.json
  types/dhis2__ui-icons/.npmignore
  types/dhis2__ui-icons/dhis2__ui-icons-tests.tsx
  types/dhis2__ui-icons/index.d.ts
  types/dhis2__ui-icons/package.json
  types/dhis2__ui-icons/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#72746 feat(node-powershell): remove types
  notNeededPackages.json
  types/node-powershell/.npmignore
  types/node-powershell/index.d.ts
  types/node-powershell/node-powershell-tests.ts
  types/node-powershell/package.json
  types/node-powershell/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#72511 [qs] Add the new throwOnLimitExceeded option to the parsers options definition
  types/qs/index.d.ts
  types/qs/package.json
  types/qs/qs-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72819 Sync frida-gum typings with Frida 17
  types/frida-gum/frida-gum-tests.ts
  types/frida-gum/index.d.ts
  types/frida-gum/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#72777 Remove jsdiff (aka diff) typings (we now bundle our own)
  notNeededPackages.json
  types/diff/.eslintrc.json
  types/diff/.npmignore
  types/diff/diff-tests.mts
  types/diff/diff-tests.ts
  types/diff/index.d.mts
  types/diff/index.d.ts
  types/diff/package.json
  types/diff/tsconfig.json
  types/diff/v3/.eslintrc.json
  types/diff/v3/.npmignore
  types/diff/v3/diff-tests.ts
  types/diff/v3/index.d.ts
  types/diff/v3/package.json
  types/diff/v3/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Critical package

#72804 feat: Add types for leaflet-pixi-overlay
  types/leaflet-pixi-overlay/.npmignore
  types/leaflet-pixi-overlay/index.d.ts
  types/leaflet-pixi-overlay/leaflet-pixi-overlay-tests.ts
  types/leaflet-pixi-overlay/package.json
  types/leaflet-pixi-overlay/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved, Check Config

#72814 fix(parcel-env): update project url in package.json
  types/parcel-env/package.json
Labels: Other Approved, Self Merge

#72780 fix(forge-viewer): add optional RegExp parameters to getPropertyHashes
  types/forge-viewer/forge-viewer-tests.ts
  types/forge-viewer/index.d.ts
Labels: Other Approved, Self Merge

#72747 feat(stamplay-js-sdk): remove types
  types/stamplay-js-sdk/.eslintrc.json
  types/stamplay-js-sdk/.npmignore
  types/stamplay-js-sdk/index.d.ts
  types/stamplay-js-sdk/package.json
  types/stamplay-js-sdk/stamplay-js-sdk-tests.ts
  types/stamplay-js-sdk/tsconfig.json
Labels: Other Approved, Self Merge

#72803 Updated leaflet whenReady type
  types/leaflet/index.d.ts
  types/leaflet/leaflet-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#72729 [@vimeo/vimeo] Add Promise API
  types/vimeo__vimeo/index.d.ts
  types/vimeo__vimeo/vimeo__vimeo-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#72798 [custom-functions-runtime] Release CustomFunctionsRuntime 1.5 to GA
  types/custom-functions-runtime/index.d.ts
Labels: Author is Owner, Owner Approved, Untested Change

#72830 [@event-calendar/core] Update type definitions for version 4 release.
  types/event-calendar__core/event-calendar__core-tests.ts
  types/event-calendar__core/index.d.ts
  types/event-calendar__core/package.json
Labels: Self Merge, Owner Approved

#72555 Update dockerode types to include manifest information.
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72741 @Imapflow - Fixed download and downloadMany functions return type
  types/imapflow/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#72708 fix(node/net): correct Server.getConnections() return type
  types/node/net.d.ts
  types/node/test/net.ts
  types/node/v18/net.d.ts
  types/node/v18/test/net.ts
  types/node/v20/net.d.ts
  types/node/v20/test/net.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72749 fix(react-youtube-embed): fix types, add jsdoc, fix export = for attw
  attw.json
  types/react-youtube-embed/index.d.ts
  types/react-youtube-embed/react-youtube-embed-tests.tsx
Labels: Self Merge, Owner Approved, Maintainer Approved

#72823 readable-stream: remove safe-buffer dependency
  types/readable-stream/index.d.ts
  types/readable-stream/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#72809 Lodash intersectioWith, fixing types in comparator's parameters
  types/lodash/common/array.d.ts
  types/lodash/fp.d.ts
  types/lodash/lodash-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72784 Fix typo in `IsIntOptions` in `@types/validatorjs`
  types/validator/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#72754 doc[node]: add `sec-fetch-` to `IncomingHttpHeaders`
  types/node/http.d.ts
  types/node/v18/http.d.ts
  types/node/v20/http.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Untested Change

#72713 Update `@types/aws-cloudfront-function` to include kvs and origin helper methods
  types/aws-cloudfront-function/.eslintrc.json
  types/aws-cloudfront-function/aws-cloudfront-function-tests.ts
  types/aws-cloudfront-function/index.d.ts
  types/aws-cloudfront-function/package.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Check Config

#72831 [react-router-bootstrap] Fix tests
  types/react-router-bootstrap/package.json
Labels: Other Approved, Self Merge

#72802 [react] support 'InputEvent' type for 'onBeforeInput' event
  types/react/global.d.ts
  types/react/index.d.ts
  types/react/ts5.0/global.d.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/v18/global.d.ts
  types/react/ts5.0/v18/index.d.ts
  types/react/ts5.0/v18/ts5.0/global.d.ts
  types/react/ts5.0/v18/ts5.0/index.d.ts
  types/react/v16/global.d.ts
  types/react/v16/index.d.ts
  types/react/v17/global.d.ts
  types/react/v17/index.d.ts
  types/react/v18/global.d.ts
  types/react/v18/index.d.ts
  types/react/v18/ts5.0/global.d.ts
  types/react/v18/ts5.0/index.d.ts
Labels: Owner Approved, Critical package, Untested Change

#72755 feat(compression): add brotli options and enforceEncoding support
  types/compression/compression-tests.ts
  types/compression/index.d.ts
  types/compression/package.json
Labels: Self Merge, Maintainer Approved, Critical package

#72838 [yazl] Bring up to date with 3.3.x
  types/yazl/index.d.ts
  types/yazl/package.json
  types/yazl/yazl-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#72846 [bun] update to 1.2.14
  types/bun/package.json
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#72778 Update @types/dom-chromium-ai
  types/dom-chromium-ai/dom-chromium-ai-tests.ts
  types/dom-chromium-ai/index.d.ts
  types/dom-chromium-ai/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72841 feat(@tonic-ui/react): updated typings and improvements/fixes
  types/tonic-ui__react/index.d.ts
  types/tonic-ui__react/package.json
  types/tonic-ui__react/tonic-ui__react-tests.tsx
Labels: Self Merge, Author is Owner, Owner Approved, Edits Owners

#72797 fix: [react-native-htmlview] support for React 18.3
  types/react-native-htmlview/index.d.ts
  types/react-native-htmlview/react-native-htmlview-tests.tsx
Labels: Other Approved, Self Merge

#72711 fix: update dragFromOutsideItem type to allow correct function return type
  types/react-big-calendar/lib/addons/dragAndDrop.d.ts
  types/react-big-calendar/package.json
  types/react-big-calendar/react-big-calendar-tests.tsx
Labels: Other Approved, Popular package, Self Merge, Owner Approved, Edits Owners

#72874 node, readable-stream: add `Writable.prototype.writableAborted`
  types/node/stream.d.ts
  types/node/v18/stream.d.ts
  types/node/v20/stream.d.ts
  types/readable-stream/index.d.ts
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Critical package, Untested Change

#72651 [node] v22.15 hotfix: enforce synchronous callbacks to `module.registerHooks()`
  types/node/module.d.ts
  types/node/test/module.ts
Labels: Other Approved, Self Merge, Author is Owner, Maintainer Approved, Critical package

#72844 node: do not reference generic TypedArrays in test suite
  types/node/test/buffer.ts
  types/node/v18/test/buffer.ts
  types/node/v20/test/buffer.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#72858 n3: Fix addQuad, removeQuad, getQuads and readQuads accepting array of objects
  types/n3/index.d.ts
  types/n3/n3-tests.ts
Labels: Self Merge, Owner Approved

#72891 [navermaps] Update the ReverseGeocodeResponse type
  types/navermaps/index.d.ts
  types/navermaps/navermaps-tests.ts
  types/navermaps/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#72808 [codemirror] Add 'origin' parameter to replaceSelection(s)
  types/codemirror/index.d.ts
  types/codemirror/package.json
  types/codemirror/test/index.ts
Labels: Self Merge, Maintainer Approved, Critical package, Edits Owners

#72836 [@types/node]: Allow passing undefined to delete key in `setEnvironmentData`
  types/node/test/worker_threads.ts
  types/node/v18/worker_threads.d.ts
  types/node/v20/worker_threads.d.ts
  types/node/worker_threads.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#72849 [chrome] clean action namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#72843 mime-types: bump from 2.1 to 3.0 and add more test cases
  types/mime-types/index.d.ts
  types/mime-types/mime-types-tests.ts
  types/mime-types/package.json
  types/mime-types/tsconfig.json
Labels: Self Merge, Maintainer Approved, Critical package

#72899 Updates types for Recurly.js v4.36.0
  types/recurly__recurly-js/lib/paypal.d.ts
  types/recurly__recurly-js/package.json
  types/recurly__recurly-js/test/paypal.ts
Labels: Popular package

#72896 [convert-units] Add missing Volume units, 'cl' and 'dl'
  types/convert-units/convert-units-tests.ts
  types/convert-units/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#72886 node: correct transferables, canonicalise Transferable
  types/node/globals.d.ts
  types/node/test/globals.ts
  types/node/test/util.ts
  types/node/test/worker_threads.ts
  types/node/v18/globals.d.ts
  types/node/v18/test/globals.ts
  types/node/v18/test/util.ts
  types/node/v18/test/worker_threads.ts
  types/node/v18/worker_threads.d.ts
  types/node/v20/globals.d.ts
  types/node/v20/test/globals.ts
  types/node/v20/test/util.ts
  types/node/v20/test/worker_threads.ts
  types/node/v20/worker_threads.d.ts
  types/node/worker_threads.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#72894 [relay-runtime] Add waitForFragmentData, observeFragment & observeQuery
  types/relay-runtime/experimental.d.ts
  types/relay-runtime/lib/store/FragmentTypes.d.ts
  types/relay-runtime/lib/store/RelayStoreTypes.d.ts
  types/relay-runtime/lib/store/ResolverFragments.d.ts
  types/relay-runtime/lib/store/observeFragmentExperimental.d.ts
  types/relay-runtime/lib/store/observeQueryExperimental.d.ts
  types/relay-runtime/lib/store/readInlineData.d.ts
  types/relay-runtime/lib/store/waitForFragmentExperimental.d.ts
  types/relay-runtime/relay-runtime-tests.tsx
Labels: Popular package, Self Merge, Owner Approved

#72822 [chrome] not force to use enum in declarativeNetRequest namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#72752 [chrome] add webAuthenticationProxy namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#72718 [chrome] add certificateProvider namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#72852 Fix mapbox-gl-draw 'getFeature' interface
  types/mapbox__mapbox-gl-draw/index.d.ts
  types/mapbox__mapbox-gl-draw/mapbox__mapbox-gl-draw-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#72577 Add getVideoData() to youtube Api
  types/youtube/index.d.ts
  types/youtube/package.json
  types/youtube/youtube-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#72816 feat(tinajs__tina): remove types
  notNeededPackages.json
  types/tinajs__tina/.npmignore
  types/tinajs__tina/index.d.ts
  types/tinajs__tina/package.json
  types/tinajs__tina/tinajs__tina-tests.ts
  types/tinajs__tina/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved
