Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2025-09, with the labels that each got.

#73596 fix(culori): Allow passing mode as null when calling mapper
  types/culori/src/map.d.ts
  types/culori/test/mapper.test.ts
Labels: Popular package, Self Merge, Owner Approved

#73600 feat: + @types/ssi-modal
  types/ssi-modal/.npmignore
  types/ssi-modal/SsiModal.d.ts
  types/ssi-modal/index.d.ts
  types/ssi-modal/package.json
  types/ssi-modal/ssi-modal-tests.ts
  types/ssi-modal/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73457 [google.accounts] IdConfiguration: Add `color_scheme` config option
  types/google.accounts/google.accounts-tests.ts
  types/google.accounts/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73575 [mssql] Add `getTypeByValue`
  types/mssql/index.d.ts
Labels: Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#73556 [@types/facebook-nodejs-business-sdk]: added LooseAutocomplete for ServerEvents
  types/facebook-nodejs-business-sdk/src/objects/serverside/server-event.d.ts
  types/facebook-nodejs-business-sdk/src/objects/serverside/standard-events.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#73505 feat(Emscripten): Add BigInt support to type definitions
  types/emscripten/emscripten-tests.ts
  types/emscripten/index.d.ts
  types/emscripten/package.json
  types/emscripten/tsconfig.json
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package, Check Config, Edits Owners

#73576 [validator] add padding option to base64 options
  types/validator/index.d.ts
  types/validator/validator-tests.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73539 pin leaflet typings to current major.minor version to unblock the release of new leaflet typings
  types/dynmap/package.json
  types/esri-leaflet-geocoder/package.json
  types/esri-leaflet/package.json
  types/esri-leaflet/v2/package.json
  types/iitc/package.json
  types/leaflet-areaselect/package.json
  types/leaflet-boundary-canvas/package.json
  types/leaflet-contextmenu/package.json
  types/leaflet-curve/package.json
  types/leaflet-deepzoom/package.json
  types/leaflet-draw/package.json
  types/leaflet-editable/package.json
  types/leaflet-freedraw/package.json
  types/leaflet-freehandshapes/package.json
  types/leaflet-fullscreen/package.json
  types/leaflet-gpx/package.json
  types/leaflet-groupedlayercontrol/package.json
  types/leaflet-imageoverlay-rotated/package.json
  types/leaflet-loading/package.json
  types/leaflet-mouse-position/package.json
  types/leaflet-pixi-overlay/package.json
  types/leaflet-polylinedecorator/package.json
  types/leaflet-providers/package.json
  types/leaflet-rastercoords/package.json
  types/leaflet-responsive-popup/package.json
  types/leaflet-rotate/package.json
  types/leaflet-rotatedmarker/package.json
  types/leaflet-routing-machine/package.json
  types/leaflet-side-by-side/package.json
  types/leaflet-textpath/package.json
  types/leaflet.awesome-markers/package.json
  types/leaflet.chinatmsproviders/package.json
  types/leaflet.featuregroup.subgroup/package.json
  types/leaflet.fullscreen/package.json
  types/leaflet.gridlayer.googlemutant/package.json
  types/leaflet.heat/package.json
  types/leaflet.icon.glyph/package.json
  types/leaflet.locatecontrol/package.json
  types/leaflet.markercluster.layersupport/package.json
  types/leaflet.markercluster/package.json
  types/leaflet.pancontrol/package.json
  types/leaflet.pattern/package.json
  types/leaflet.pm/package.json
  types/leaflet.polylinemeasure/package.json
  types/leaflet.sync/package.json
  types/leaflet.utm/package.json
  types/leaflet.vectorgrid/package.json
  types/leaflet.wms/package.json
  types/mapbox-gl-leaflet/package.json
  types/proj4leaflet/package.json
  types/svelte-leafletjs/package.json
Labels: Popular package, Self Merge, Edits multiple packages, Maintainer Approved, Too Many Owners

#73563 node:fs/promises filehandle.createReadStream([options]) options.signal
  types/node/v20/fs/promises.d.ts
  types/node/v20/test/fs.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73499 [umami-browser] update identify() function
  types/umami-browser/index.d.ts
  types/umami-browser/package.json
  types/umami-browser/umami-browser-tests.ts
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners

#73532 init types and test for Net-snmp
  types/net-snmp/.npmignore
  types/net-snmp/index.d.ts
  types/net-snmp/net-snmp-tests.ts
  types/net-snmp/package.json
  types/net-snmp/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73586 feat(windows-1251): remove types
  notNeededPackages.json
  types/windows-1251/.npmignore
  types/windows-1251/index.d.ts
  types/windows-1251/package.json
  types/windows-1251/tsconfig.json
  types/windows-1251/windows-1251-tests.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73590 feat(rc-switch): remove types
  attw.json
  notNeededPackages.json
  types/rc-switch/.npmignore
  types/rc-switch/index.d.ts
  types/rc-switch/package.json
  types/rc-switch/rc-switch-tests.ts
  types/rc-switch/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73608 fix (vtex.js): BREAKING CHANGE - Update OrderFormMarketingData properties to be required and change types
  types/vtex.js/index.d.ts
  types/vtex.js/vtex.js-tests.ts
Labels: Self Merge, Owner Approved

#73565 [chrome] update idle namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73555 Add type definitions for emailjs-utf7
  types/emailjs-utf7/.npmignore
  types/emailjs-utf7/emailjs-utf7-tests.ts
  types/emailjs-utf7/index.d.ts
  types/emailjs-utf7/package.json
  types/emailjs-utf7/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73406 [@types/pdfkit] Further define table related properties
  types/pdfkit/index.d.ts
  types/pdfkit/pdfkit-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73424 feat(express-correlation-id): update express-correlation-id types to v3
  types/express-correlation-id/express-correlation-id-tests.ts
  types/express-correlation-id/index.d.ts
  types/express-correlation-id/package.json
Labels: Self Merge, Maintainer Approved, No Other Owners, Edits Owners

#73568 w3c-web-usb: fix nullable types
  types/w3c-web-usb/index.d.ts
  types/w3c-web-usb/w3c-web-usb-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73636 Add definition for "setSort" in SortModule
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#73644 tryghost__admin-api: remove empty type parameter list
  types/tryghost__admin-api/index.d.ts
Labels: Self Merge, Maintainer Approved, Untested Change

#73645 [google-publisher-tag] mark as conflicting npm
  types/google-publisher-tag/package.json
Labels: Popular package

#73646 [ramda] Fix for TS 6.0
  types/ramda/test/index-tests.ts
  types/ramda/test/maxBy-tests.ts
  types/ramda/test/minBy-tests.ts
  types/ramda/tools.d.ts
Labels: Self Merge, Maintainer Approved, Critical package

#73453 Add types for treescape
  types/treescape/.npmignore
  types/treescape/index.d.ts
  types/treescape/package.json
  types/treescape/treescape-tests.ts
  types/treescape/tsconfig.json
Labels: Unmerged, New Definition, Self Merge, Maintainer Approved

#73549 Fix heic-decode types
  types/heic-decode/index.d.ts
Labels: Unmerged, Self Merge, Owner Approved, Maintainer Approved, Untested Change

#73663 Added owner
  types/facebook-nodejs-business-sdk/package.json
Labels: Popular package, Self Merge, Owner Approved, Edits Owners

#73444 node: v24.4
  types/node/buffer.d.ts
  types/node/child_process.d.ts
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/http.d.ts
  types/node/module.d.ts
  types/node/package.json
  types/node/sqlite.d.ts
  types/node/test/crypto.ts
  types/node/test/fs.ts
  types/node/test/sqlite.ts
  types/node/test/vm.ts
  types/node/test/wasi.ts
  types/node/vm.d.ts
  types/node/wasi.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73673 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#73674 fix(gimloader): Allow returning nothing from certain callbacks
  types/gimloader/gimloader-tests.ts
  types/gimloader/index.d.ts
  types/gimloader/package.json
Labels: Other Approved, Self Merge, Author is Owner, No Other Owners, Edits Owners

#73676 google-apps-scripts: Added CardService.MaterialIcon type
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#73672 feat(uuid): remove types
  notNeededPackages.json
  types/uuid/.npmignore
  types/uuid/index.d.mts
  types/uuid/index.d.ts
  types/uuid/package.json
  types/uuid/tsconfig.json
  types/uuid/uuid-tests.ts
  types/uuid/v2/.npmignore
  types/uuid/v2/index.d.ts
  types/uuid/v2/package.json
  types/uuid/v2/tsconfig.json
  types/uuid/v2/uuid-tests.ts
  types/uuid/v3/.npmignore
  types/uuid/v3/index.d.ts
  types/uuid/v3/interfaces.d.ts
  types/uuid/v3/package.json
  types/uuid/v3/tsconfig.json
  types/uuid/v3/uuid-tests.ts
  types/uuid/v3/v1.d.ts
  types/uuid/v3/v4.d.ts
  types/uuid/v3/v5.d.ts
  types/uuid/v7/.npmignore
  types/uuid/v7/index.d.ts
  types/uuid/v7/interfaces.d.ts
  types/uuid/v7/package.json
  types/uuid/v7/tsconfig.json
  types/uuid/v7/uuid-tests.ts
  types/uuid/v7/v1.d.ts
  types/uuid/v7/v3.d.ts
  types/uuid/v7/v4.d.ts
  types/uuid/v7/v5.d.ts
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Critical package

#73658 feat(react-window): remove types
  notNeededPackages.json
  types/react-window/.npmignore
  types/react-window/index.d.ts
  types/react-window/package.json
  types/react-window/react-window-tests.tsx
  types/react-window/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved, Critical package

#73520 fix(dockerode): improve types for `AuthConfig`, `Image.push`
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#73527 [node] https: deconflict overridable Agent methods
  types/node/http.d.ts
  types/node/https.d.ts
  types/node/test/https.ts
  types/node/v18/http.d.ts
  types/node/v18/https.d.ts
  types/node/v18/test/https.ts
  types/node/v20/http.d.ts
  types/node/v20/https.d.ts
  types/node/v20/test/https.ts
  types/node/v22/http.d.ts
  types/node/v22/https.d.ts
  types/node/v22/test/https.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73535 [chrome] update history namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#73546 fb-watchman: Allow for optional callback argument for all commands, including unofficial ones
  types/fb-watchman/fb-watchman-tests.ts
  types/fb-watchman/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73691 [dom-chromium-ai] change test to current implementation state
  types/dom-chromium-ai/dom-chromium-ai-tests.ts
Labels: Self Merge, Author is Owner, Owner Approved

#73525 V1.35.0
  types/consumer-data-standards/.eslintrc.json
  types/consumer-data-standards/admin/index.d.ts
  types/consumer-data-standards/banking/index.d.ts
  types/consumer-data-standards/common/index.d.ts
  types/consumer-data-standards/dcr/index.d.ts
  types/consumer-data-standards/energy/index.d.ts
  types/consumer-data-standards/energy_sdh/index.d.ts
  types/consumer-data-standards/index.d.ts
  types/consumer-data-standards/package.json
  types/consumer-data-standards/register/index.d.ts
  types/consumer-data-standards/telco/index.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Untested Change, Check Config, No Other Owners, Huge Change

#71163 fix(styled-system): fix conditionals to make it work with `exactOptionalPropertyTypes: true`
  types/styled-system/index.d.ts
  types/styled-system/tsconfig.json
Labels: Unmerged, Popular package, Self Merge, Owner Approved, Maintainer Approved, Untested Change, Check Config

#73695 Update clerk.io TypeScript definitions to v2 with comprehensive API coverage
  types/clerk.io/clerk.io-tests.ts
  types/clerk.io/index.d.ts
  types/clerk.io/package.json
  types/clerk.io/tsconfig.json
  types/clerk.io/types/config.ts
  types/clerk.io/types/helpers.ts
  types/clerk.io/types/optional.ts
  types/clerk.io/types/response.ts
Labels: Self Merge, Owner Approved

#73620 [@types/matter.js] Update type definitions for Matter.Runner to reflect matter.js docs
  types/matter-js/index.d.ts
  types/matter-js/matter-js-tests.ts
Labels: Self Merge, Owner Approved

#73735 google-apps-script: Added Validation for TextInput
  types/google-apps-script/google-apps-script.card-service.d.ts
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#73743 Delete minapp-env, miniprogram-wxs
  types/minapp-env/.npmignore
  types/minapp-env/index.d.ts
  types/minapp-env/minapp-env-tests.ts
  types/minapp-env/package.json
  types/minapp-env/tsconfig.json
  types/miniprogram-wxs/.npmignore
  types/miniprogram-wxs/es5.d.ts
  types/miniprogram-wxs/index.d.ts
  types/miniprogram-wxs/miniprogram-wxs-tests.ts
  types/miniprogram-wxs/package.json
  types/miniprogram-wxs/tsconfig.json
Labels: Self Merge, Edits multiple packages, Maintainer Approved, Huge Change

#73744 [nova-editor-node] remove no-default-lib directive
  types/nova-editor-node/index.d.ts
Labels: Untested Change

#73748 [invity-api] receiveAddress in quotes request
  types/invity-api/index.d.ts
  types/invity-api/invity-api-tests.ts
Labels: Self Merge, Owner Approved

#73756 [Gimloader] Add types for gamemode header/apis
  types/gimloader/gimloader-tests.ts
  types/gimloader/index.d.ts
  types/gimloader/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#73675 feat(html-minifier-next): update to v2.1 with many changes
  types/html-minifier-next/html-minifier-next-tests.ts
  types/html-minifier-next/index.d.cts
  types/html-minifier-next/index.d.ts
  types/html-minifier-next/package.json
Labels: Self Merge, Owner Approved

#73767 [bun] update to 1.2.23
  types/bun/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#73760 [leaflet-rotate]: Add missing type definitions in MapOptions and MarkerOptions interfaces
  types/leaflet-rotate/index.d.ts
  types/leaflet-rotate/leaflet-rotate-tests.ts
  types/leaflet-rotate/package.json
Labels: Self Merge, Owner Approved

#73671 [node] worker_threads: remove postMessageToThread from Worker prototype
  types/node/test/worker_threads.ts
  types/node/v20/test/worker_threads.ts
  types/node/v20/worker_threads.d.ts
  types/node/v22/test/worker_threads.ts
  types/node/v22/worker_threads.d.ts
  types/node/worker_threads.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73733 node: v24.6
  types/node/assert.d.ts
  types/node/assert/strict.d.ts
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/http.d.ts
  types/node/package.json
  types/node/test.d.ts
  types/node/test/assert.ts
  types/node/test/crypto.ts
  types/node/test/fs.ts
  types/node/test/http.ts
  types/node/test/https.ts
  types/node/test/test.ts
  types/node/test/util.ts
  types/node/test/worker_threads.ts
  types/node/util.d.ts
  types/node/v18/assert.d.ts
  types/node/v20/assert.d.ts
  types/node/v20/test.d.ts
  types/node/v22/assert.d.ts
  types/node/v22/test.d.ts
  types/node/worker_threads.d.ts
  types/node/zlib.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73752 [WebXR] Enhance XRAnchor and XRSession with persistent anchor support
  types/webxr/index.d.ts
  types/webxr/webxr-tests.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73708 feat(babel-plugin-tester): remove types
  notNeededPackages.json
  types/babel-plugin-tester/.npmignore
  types/babel-plugin-tester/babel-plugin-tester-tests.ts
  types/babel-plugin-tester/index.d.ts
  types/babel-plugin-tester/package.json
  types/babel-plugin-tester/pure.d.ts
  types/babel-plugin-tester/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73714 [chrome] update since Chrome 139-140
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73583 fix(selenium-webdriver): add back url for NavigationInfo & jsdoc & test
  types/selenium-webdriver/bidi/browsingContextTypes.d.ts
  types/selenium-webdriver/bidi/index.d.ts
  types/selenium-webdriver/test/bidi/browsingContextTypes.ts
  types/selenium-webdriver/tsconfig.json
Labels: Popular package, Self Merge, Maintainer Approved

#73638 fix(nodemailer): add back default callbacks for sendMail()
  types/nodemailer/lib/mailer/index.d.ts
  types/nodemailer/lib/ses-transport/index.d.ts
  types/nodemailer/nodemailer-tests.ts
  types/nodemailer/tsconfig.json
  types/nodemailer/v6/lib/mailer/index.d.ts
  types/nodemailer/v6/lib/ses-transport/index.d.ts
  types/nodemailer/v6/nodemailer-tests.ts
  types/nodemailer/v6/tsconfig.json
Labels: Self Merge, Maintainer Approved, Critical package

#73761 [chrome] update proxy namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73699 [chrome] update declarativeNetRequest namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73711 feat(imapflow): remove types
  notNeededPackages.json
  types/imapflow/.eslintrc.json
  types/imapflow/.npmignore
  types/imapflow/imapflow-tests.ts
  types/imapflow/index.d.ts
  types/imapflow/package.json
  types/imapflow/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73763 [chrome] update search namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73696 [tizen-tv-webapis] Add missing getUuid method for AppCommonManager
  types/tizen-tv-webapis/index.d.ts
  types/tizen-tv-webapis/test/tizen-tv-webapis-tests.cjs.ts
Labels: Other Approved, Self Merge

#73634 feat(firefox-webext-browser): add type checking for browser.scripting.executeScript between func and args property
  types/firefox-webext-browser/firefox-webext-browser-tests.ts
  types/firefox-webext-browser/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73712 feat(libxmljs): remove types
  notNeededPackages.json
  types/libxmljs/.npmignore
  types/libxmljs/index.d.ts
  types/libxmljs/libxmljs-tests.ts
  types/libxmljs/package.json
  types/libxmljs/tsconfig.json
  types/libxslt/package.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#73725 [@types/aws-lambda] Update ConnectContactFlowChannel type to accommodate email
  types/aws-lambda/test/connect-contact-flow-tests.ts
  types/aws-lambda/trigger/connect-contact-flow.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Critical package

#73773 [react-gauge-chart] add new types to react-gauge-chart
  types/react-gauge-chart/index.d.ts
  types/react-gauge-chart/package.json
  types/react-gauge-chart/react-gauge-chart-tests.tsx
Labels: Self Merge, Maintainer Approved

#73787 webpack-hot-middleware: fix CI
  types/webpack-hot-middleware/webpack-hot-middleware-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73785 [chrome] update pageCapture namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package

#73717 updated types for webextension-polyfill
  types/webextension-polyfill/index.d.ts
  types/webextension-polyfill/namespaces/action.d.ts
  types/webextension-polyfill/namespaces/alarms.d.ts
  types/webextension-polyfill/namespaces/browserSettings.d.ts
  types/webextension-polyfill/namespaces/contentScripts.d.ts
  types/webextension-polyfill/namespaces/cookies.d.ts
  types/webextension-polyfill/namespaces/declarativeNetRequest.d.ts
  types/webextension-polyfill/namespaces/i18n.d.ts
  types/webextension-polyfill/namespaces/manifest.d.ts
  types/webextension-polyfill/namespaces/menus.d.ts
  types/webextension-polyfill/namespaces/permissions.d.ts
  types/webextension-polyfill/namespaces/runtime.d.ts
  types/webextension-polyfill/namespaces/scripting.d.ts
  types/webextension-polyfill/namespaces/storage.d.ts
  types/webextension-polyfill/namespaces/tabGroups.d.ts
  types/webextension-polyfill/namespaces/tabs.d.ts
  types/webextension-polyfill/namespaces/webRequest.d.ts
  types/webextension-polyfill/package.json
Labels: Other Approved, Popular package, Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change, Edits Owners
