Repository DefinitelyTyped/DefinitelyTyped, pull requests merged in 2025-08, with the labels that each got.

#73379 ysdk Update formatting and onError
  types/ysdk/index.d.ts
  types/ysdk/package.json
  types/ysdk/ysdk-tests.ts
Labels: Self Merge, Owner Approved

#73371 Exposes Identity API Methods
  types/mparticle__web-sdk/index.d.ts
Labels: Self Merge, Owner Approved, Maintainer Approved, Untested Change

#73382 Sync latest changes to @types/google-publisher-tag
  types/google-publisher-tag/google-publisher-tag-tests.ts
  types/google-publisher-tag/index.d.ts
Labels: Popular package, Self Merge, Owner Approved

#73383 Remove watchdogs, unused script deps
  .github/workflows/watchdog-publisher.yml
  .github/workflows/watchdog-typescript-bot.yml
  README.md
  scripts/package.json
  scripts/watchdog-publisher.js
  scripts/watchdog-typescript-bot.js
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73210 feat(async): remove depreciated exports, add missing async func exports
  types/async/index.d.ts
  types/async/test/index.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73361 feat(photoswipe): remove types
  notNeededPackages.json
  types/photoswipe/.eslintrc.json
  types/photoswipe/.npmignore
  types/photoswipe/dist/photoswipe-ui-default/index.d.ts
  types/photoswipe/index.d.ts
  types/photoswipe/package.json
  types/photoswipe/photoswipe-tests.ts
  types/photoswipe/tsconfig.json
  types/react-photoswipe/package.json
Labels: Popular package, Self Merge, Edits Infrastructure, Edits multiple packages, Maintainer Approved

#73358 feat(colorbrewer): remove types
  notNeededPackages.json
  types/colorbrewer/.eslintrc.json
  types/colorbrewer/.npmignore
  types/colorbrewer/colorbrewer-tests.ts
  types/colorbrewer/index.d.ts
  types/colorbrewer/package.json
  types/colorbrewer/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73124 [node] v24.2
  types/node/crypto.d.ts
  types/node/fs.d.ts
  types/node/fs/promises.d.ts
  types/node/http2.d.ts
  types/node/inspector.d.ts
  types/node/module.d.ts
  types/node/package.json
  types/node/perf_hooks.d.ts
  types/node/repl.d.ts
  types/node/scripts/generate-inspector/devtools-protocol-schema.ts
  types/node/scripts/generate-inspector/generate-substitute-args.ts
  types/node/scripts/generate-inspector/inspector.d.ts.template
  types/node/sqlite.d.ts
  types/node/stream.d.ts
  types/node/test.d.ts
  types/node/test/fs.ts
  types/node/test/http2.ts
  types/node/test/module.ts
  types/node/test/repl.ts
  types/node/test/test.ts
  types/node/timers.d.ts
  types/node/url.d.ts
  types/node/util.d.ts
  types/node/worker_threads.d.ts
  types/node/zlib.d.ts
Labels: Self Merge, Author is Owner, Maintainer Approved, Critical package, Check Config

#73398 [three] r179
  types/three/examples/jsm/Addons.d.ts
  types/three/examples/jsm/exporters/USDZExporter.d.ts
  types/three/examples/jsm/loaders/EXRLoader.d.ts
  types/three/examples/jsm/loaders/USDLoader.d.ts
  types/three/examples/jsm/loaders/USDZLoader.d.ts
  types/three/examples/jsm/tsl/display/TRAANode.d.ts
  types/three/examples/jsm/tsl/display/TRAAPassNode.d.ts
  types/three/package.json
  types/three/src/Three.Core.d.ts
  types/three/src/Three.TSL.d.ts
  types/three/src/animation/KeyframeTrack.d.ts
  types/three/src/animation/tracks/BooleanKeyframeTrack.d.ts
  types/three/src/animation/tracks/StringKeyframeTrack.d.ts
  types/three/src/cameras/Camera.d.ts
  types/three/src/constants.d.ts
  types/three/src/core/Timer.d.ts
  types/three/src/helpers/SkeletonHelper.d.ts
  types/three/src/loaders/FileLoader.d.ts
  types/three/src/loaders/ImageBitmapLoader.d.ts
  types/three/src/loaders/Loader.d.ts
  types/three/src/loaders/LoadingManager.d.ts
  types/three/src/materials/nodes/Line2NodeMaterial.d.ts
  types/three/src/materials/nodes/PointsNodeMaterial.d.ts
  types/three/src/materials/nodes/manager/NodeMaterialObserver.d.ts
  types/three/src/math/Frustum.d.ts
  types/three/src/math/Line3.d.ts
  types/three/src/math/Matrix4.d.ts
  types/three/src/nodes/Nodes.d.ts
  types/three/src/nodes/TSL.d.ts
  types/three/src/nodes/accessors/TextureNode.d.ts
  types/three/src/nodes/core/ContextNode.d.ts
  types/three/src/nodes/core/Node.d.ts
  types/three/src/nodes/core/UniformNode.d.ts
  types/three/src/nodes/core/VarNode.d.ts
  types/three/src/nodes/display/PassNode.d.ts
  types/three/src/nodes/gpgpu/ComputeNode.d.ts
  types/three/src/nodes/materialx/MaterialXNodes.d.ts
  types/three/src/nodes/materialx/lib/mx_noise.d.ts
  types/three/src/nodes/math/MathNode.d.ts
  types/three/src/nodes/tsl/TSLCore.d.ts
  types/three/src/nodes/utils/EventNode.d.ts
  types/three/src/nodes/utils/RTTNode.d.ts
  types/three/src/renderers/common/Color4.d.ts
  types/three/src/renderers/common/Renderer.d.ts
  types/three/src/renderers/common/SampledTexture.d.ts
  types/three/src/renderers/common/Sampler.d.ts
  types/three/src/renderers/common/Storage3DTexture.d.ts
  types/three/src/renderers/common/StorageArrayTexture.d.ts
  types/three/src/renderers/common/StorageTexture.d.ts
  types/three/src/renderers/common/XRManager.d.ts
  types/three/src/renderers/webgl/WebGLCapabilities.d.ts
  types/three/src/renderers/webgpu/nodes/WGSLNodeBuilder.d.ts
  types/three/src/renderers/webxr/WebXRDepthSensing.d.ts
  types/three/src/renderers/webxr/WebXRManager.d.ts
  types/three/src/textures/ExternalTexture.d.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved, Untested Change

#73389 feat(contract-proxy-kit): remove types
  notNeededPackages.json
  types/contract-proxy-kit/.npmignore
  types/contract-proxy-kit/contract-proxy-kit-tests.ts
  types/contract-proxy-kit/index.d.ts
  types/contract-proxy-kit/package.json
  types/contract-proxy-kit/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved

#73387 feat(binary-parser): remove types
  notNeededPackages.json
  types/binary-parser/.npmignore
  types/binary-parser/binary-parser-tests.ts
  types/binary-parser/index.d.ts
  types/binary-parser/package.json
  types/binary-parser/tsconfig.json
Labels: Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73320 [elm] refactor into an ESM `.d.ts`
  types/elm/elm-tests.ts
  types/elm/index.d.ts
  types/elm/package.json
Labels: Self Merge, Author is Owner, Owner Approved

#73228 chore: improve type definitions for istanbul-lib-instrument
  types/istanbul-lib-instrument/index.d.ts
  types/istanbul-lib-instrument/package.json
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#73407 feat: remove lint-staged
  attw.json
  notNeededPackages.json
  types/lint-staged/.eslintrc.json
  types/lint-staged/.npmignore
  types/lint-staged/index.d.ts
  types/lint-staged/lint-staged-tests.ts
  types/lint-staged/package.json
  types/lint-staged/tsconfig.json
Labels: Popular package, Self Merge, Owner Approved, Edits Infrastructure, Maintainer Approved

#73362 feat(bs58check): remove types
  notNeededPackages.json
  types/bs58check/.npmignore
  types/bs58check/bs58check-tests.ts
  types/bs58check/index.d.ts
  types/bs58check/package.json
  types/bs58check/tsconfig.json
Labels: Popular package, Self Merge, Edits Infrastructure, Maintainer Approved

#73411 feat : add type definitions for html2pdf.js
  types/html2pdf.js/.npmignore
  types/html2pdf.js/html2pdf.js-tests.ts
  types/html2pdf.js/index.d.ts
  types/html2pdf.js/package.json
  types/html2pdf.js/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73419 feat(hash-code): add types
  types/hash-code/.npmignore
  types/hash-code/hash-code-tests.ts
  types/hash-code/index.d.ts
  types/hash-code/package.json
  types/hash-code/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73434 chore: update woosmap.map
  types/woosmap.map/index.d.ts
  types/woosmap.map/woosmap.map-tests.ts
Labels: Self Merge, Owner Approved

#73433 Add `round-tofixed` package types
  types/round-tofixed/.npmignore
  types/round-tofixed/index.d.ts
  types/round-tofixed/package.json
  types/round-tofixed/round-tofixed-tests.ts
  types/round-tofixed/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73429 feat(qunit): add types for module.if
  types/qunit/index.d.ts
  types/qunit/test/global-test.ts
  types/qunit/test/module-test.ts
Labels: Popular package, Self Merge, Owner Approved

#73299 [chrome] update commands namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#73298 [chrome] update browsingData namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Maintainer Approved

#73421 Move Chromecast SDK enums to const enum
  types/chromecast-caf-receiver/.eslintrc.json
  types/chromecast-caf-receiver/cast.framework.d.ts
  types/chromecast-caf-receiver/cast.framework.events.d.ts
  types/chromecast-caf-receiver/cast.framework.messages.d.ts
  types/chromecast-caf-receiver/cast.framework.system.d.ts
  types/chromecast-caf-receiver/cast.framework.ui.d.ts
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Untested Change, Check Config

#73315 `dom-webcodecs`: Add `rotation` field to `VideoFrame` object
  types/dom-webcodecs/webcodecs.generated.d.ts
Labels: Popular package, Self Merge, Maintainer Approved, Untested Change

#73415 node: remove TS 5.1 support
  types/node/package.json
  types/node/ts5.1/compatibility/disposable.d.ts
  types/node/ts5.1/index.d.ts
  types/node/ts5.1/tsconfig.dom.json
  types/node/ts5.1/tsconfig.json
  types/node/ts5.1/tsconfig.non-dom.json
  types/node/ts5.1/tsconfig.webworker.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package, Untested Change

#73128 [webvis] Add type definitions for the non-npm package webvis 3.11.x
  types/webvis/.npmignore
  types/webvis/index.d.ts
  types/webvis/package.json
  types/webvis/test/AnimationAPI.ts
  types/webvis/test/AnnotationAPI.ts
  types/webvis/test/AttachmentAPI.ts
  types/webvis/test/ClipPlaneAPI.ts
  types/webvis/test/CollectionAPI.ts
  types/webvis/test/ContextAPI.ts
  types/webvis/test/ContextRegistryAPI.ts
  types/webvis/test/ContextStateAPI.ts
  types/webvis/test/CoordinateSystemAPI.ts
  types/webvis/test/DrawingAPI.ts
  types/webvis/test/DrawingPlaneAPI.ts
  types/webvis/test/EventAPI.ts
  types/webvis/test/ExplosionAPI.ts
  types/webvis/test/FrameAPI.ts
  types/webvis/test/HubAPI.ts
  types/webvis/test/InstanceGraphAPI.ts
  types/webvis/test/InteractionAPI.ts
  types/webvis/test/LayerFilterAPI.ts
  types/webvis/test/LogAPI.ts
  types/webvis/test/MaterialAPI.ts
  types/webvis/test/MeasurementAPI.ts
  types/webvis/test/NodePathAPI.ts
  types/webvis/test/QueryAPI.ts
  types/webvis/test/RealityAPI.ts
  types/webvis/test/SelectionAPI.ts
  types/webvis/test/SessionStorageAPI.ts
  types/webvis/test/SettingsAPI.ts
  types/webvis/test/TopologyAPI.ts
  types/webvis/test/UtilityAPI.ts
  types/webvis/test/VariantsAPI.ts
  types/webvis/test/ViewerAPI.ts
  types/webvis/test/ViewerDrawingAPI.ts
  types/webvis/test/ViewerGizmoAPI.ts
  types/webvis/test/ViewerHeatmapAPI.ts
  types/webvis/test/ViewerHighlightAPI.ts
  types/webvis/test/ViewerInteractionAPI.ts
  types/webvis/test/ViewerMagnifierAPI.ts
  types/webvis/test/ViewerNavigationAPI.ts
  types/webvis/test/ViewerPointCloudAPI.ts
  types/webvis/test/ViewerPolylineAPI.ts
  types/webvis/test/ViewerStateAPI.ts
  types/webvis/test/ViewerUserGeometryAPI.ts
  types/webvis/test/ViewerXREdgeCompareAPI.ts
  types/webvis/tsconfig.json
  types/webvis/webvis-tests.ts
Labels: New Definition, Self Merge, Maintainer Approved, Check Config, Huge Change

#73353 fix(node-pushnotifications): fix `fcm` settings definition
  types/node-pushnotifications/index.d.ts
  types/node-pushnotifications/node-pushnotifications-tests.ts
  types/node-pushnotifications/package.json
Labels: Self Merge, Owner Approved

#73338 [webpack-hot-middleware] statsOptions typing
  types/webpack-hot-middleware/index.d.ts
  types/webpack-hot-middleware/webpack-hot-middleware-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73450 [googlepay] add buttonBorderType property to the ButtonOptions object
  types/googlepay/googlepay-tests.ts
  types/googlepay/index.d.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#73454 [react] Add `name` prop to `Activity`
  types/react/experimental.d.ts
  types/react/test/experimental.tsx
  types/react/ts5.0/experimental.d.ts
  types/react/ts5.0/test/experimental.tsx
Labels: Author is Owner, Critical package

#73455 Additional definitions for Filters
  types/tabulator-tables/index.d.ts
  types/tabulator-tables/tabulator-tables-tests.ts
Labels: Self Merge, Owner Approved

#73447 [@types/gradient-parser] support HSL, HSLA, CSS variable, calc() expression
  types/gradient-parser/gradient-parser-tests.ts
  types/gradient-parser/index.d.ts
  types/gradient-parser/package.json
Labels: Popular package, Self Merge, Owner Approved

#73458 Type updates for v1.2.0 k6 release
  types/k6/browser/index.d.ts
  types/k6/net/grpc/index.d.ts
  types/k6/package.json
  types/k6/test/browser.ts
  types/k6/test/grpc.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#73439 [chrome] add enterprise.login namespace
  types/chrome/index.d.ts
  types/chrome/test/index.ts
Labels: Popular package, Self Merge, Author is Owner, Owner Approved

#73198 Add types for Catchpoint Playwright
  types/catchpoint-playwright/.npmignore
  types/catchpoint-playwright/catchpoint-playwright-test.ts
  types/catchpoint-playwright/index.d.ts
  types/catchpoint-playwright/package.json
  types/catchpoint-playwright/tsconfig.json
Labels: New Definition, Unreviewed

#73308 fix(wtfnode): add fullStacks option to wtf.dump()
  types/wtfnode/index.d.ts
  types/wtfnode/package.json
  types/wtfnode/wtfnode-tests.ts
Labels: Unreviewed

#73314 [gaze] add missing overload and extend EventEmitter
  types/gaze/gaze-tests.ts
  types/gaze/index.d.ts
  types/gaze/package.json
Labels: No Other Owners, Unreviewed, Edits Owners

#73459 Add @types/vpk package
  types/vpk/.npmignore
  types/vpk/index.d.ts
  types/vpk/package.json
  types/vpk/tsconfig.json
  types/vpk/vpk-tests.ts
Labels: New Definition

#73463 Add types for react-native-immersive
  types/react-native-immersive/.npmignore
  types/react-native-immersive/index.d.ts
  types/react-native-immersive/package.json
  types/react-native-immersive/react-native-immersive-tests.ts
  types/react-native-immersive/tsconfig.json
Labels: New Definition, Check Config

#73403 [pako] Explicitly reference ArrayBuffer
  types/pako/index.d.ts
  types/pako/pako-tests.ts
Labels: Owner Approved, Critical package

#73503 fix(intercept-stdout): hook param
  types/intercept-stdout/index.d.ts
  types/intercept-stdout/intercept-stdout-tests.ts
  types/intercept-stdout/package.json
Labels: Self Merge, Owner Approved

#73497 Conform to JSend Specifications
  types/jsend/index.d.ts
Labels: Self Merge, Owner Approved, Untested Change

#73474 google-apps-script: Adding missing ScriptApp API requireAllScopes/requireScopes
  types/google-apps-script/test/google-apps-script-tests.ts
Labels: Self Merge, Owner Approved

#73271 fix(node-forge): update PrivateKey and PublicKey usage to better reflect library support
  types/node-forge/index.d.ts
  types/node-forge/node-forge-tests.ts
Labels: Self Merge, Maintainer Approved, Critical package

#73357 feat(dockerode): add Healthcheck to ImageInspectInfo.Config
  types/dockerode/dockerode-tests.ts
  types/dockerode/index.d.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73348 doc(smtp-server): sync `SMTPServerOptions` with official document
  types/smtp-server/index.d.ts
  types/smtp-server/smtp-server-tests.ts
Labels: Popular package, Self Merge, Maintainer Approved

#73481 Add the `number-abbreviate` npm package
  types/number-abbreviate/.npmignore
  types/number-abbreviate/index.d.ts
  types/number-abbreviate/number-abbreviate-tests.ts
  types/number-abbreviate/package.json
  types/number-abbreviate/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73488 feat(midtrans-client): Add initial type definitions
  types/midtrans-client/.npmignore
  types/midtrans-client/index.d.ts
  types/midtrans-client/midtrans-client-tests.ts
  types/midtrans-client/package.json
  types/midtrans-client/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73397 feat(loader-utils): Update to v3
  types/loader-utils/index.d.ts
  types/loader-utils/loader-utils-tests.ts
  types/loader-utils/package.json
Labels: Popular package, Self Merge, Maintainer Approved

#73510 [react] Use string union for `textAnchor` and `dominatBaseline`
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
  types/react/ts5.0/v18/index.d.ts
  types/react/ts5.0/v18/ts5.0/index.d.ts
  types/react/v15/index.d.ts
  types/react/v16/index.d.ts
  types/react/v17/index.d.ts
  types/react/v18/index.d.ts
  types/react/v18/test/elementAttributes.tsx
  types/react/v18/ts5.0/index.d.ts
Labels: Critical package, The CI failed

#73404 [react] Added `fetchPriority` prop in script tag
  types/react/index.d.ts
  types/react/ts5.0/index.d.ts
Labels: Owner Approved, Critical package, The CI failed, Untested Change

#73384 Added Type Definition for @tryghost/admin-api version 1.14.0
  types/tryghost__admin-api/.npmignore
  types/tryghost__admin-api/index.d.ts
  types/tryghost__admin-api/package.json
  types/tryghost__admin-api/tryghost__admin-api-tests.ts
  types/tryghost__admin-api/tsconfig.json
Labels: New Definition, Self Merge, Maintainer Approved

#73521 [rn-material-ui-textfield] Update types to be compatible with latest React Native types
  types/rn-material-ui-textfield/index.d.ts
Labels: Owner Approved, Untested Change

#73466 fix(google-apps-script): allow nullable return types for APIs that return null
  types/google-apps-script/google-apps-script.xml-service.d.ts
  types/google-apps-script/package.json
  types/google-apps-script/test/google-apps-script-tests.ts
  types/google-apps-script/tsconfig.json
Labels: Self Merge, Owner Approved, Check Config

#73544 [bun] update to 1.2.21
  types/bun/package.json
Labels: Self Merge, Author is Owner, Owner Approved, Maintainer Approved, Critical package

#73545 fix(react-dom): add `formState` option to SSR APIs
  types/react-dom/server.d.ts
  types/react-dom/test/react-dom-tests.tsx
Labels: Critical package

#73482 fix(react-native-snap-carousel): move react-native to peerDependencie…
  types/react-native-snap-carousel/package.json
Labels: Popular package, Self Merge, Owner Approved, Check Config

#73548 Add `identify` method to umami namespace
  types/umami/index.d.ts
  types/umami/umami-tests.ts
Labels: Self Merge, Owner Approved

#73487 Update WebXR Depth to the 21 May 2025 draft
  types/webxr/index.d.ts
  types/webxr/webxr-tests.ts
Labels: Popular package, Self Merge, Owner Approved

#73567 parse: remove definitions
  notNeededPackages.json
  types/parse/.eslintrc.json
  types/parse/.npmignore
  types/parse/index.d.ts
  types/parse/node.d.ts
  types/parse/package.json
  types/parse/parse-tests.ts
  types/parse/react-native.d.ts
  types/parse/tsconfig.json
  types/parse/v1/.eslintrc.json
  types/parse/v1/.npmignore
  types/parse/v1/index.d.ts
  types/parse/v1/package.json
  types/parse/v1/parse-tests.ts
  types/parse/v1/tsconfig.json
Labels: Self Merge, Edits Infrastructure, Maintainer Approved, Huge Change
